### ISSUE TITLE
Furnitures(entity: item_frame) can be duplicated with item_frame

### ISSUE THREAD

**Issue by Xiao-MoMi** [PluginBugs/Issues-ItemsAdder#1000]
①and② are two bugs

**Describe the bug**
①Furnitures(entity: item_frame) can be duplicated with item_frame
②furniture would disappear when there is an item_frame in the place where you want to place the furniture

①just try a lot and you can reproduce it
My Config here:
  huawei_mate_40_pro:
    display_name: "华为Mate40Pro"
    resource:
      model_id: 5210
      material: PAPER
      generate: false
      model_path: item/furniture/phone/huawei_mate_40_pro
    behaviours:
      furniture:
        entity: item_frame
        solid: false
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          walls: false
          ceiling: false
          floor: true
②just place the furniture on the edge of the block

**Expected behavior**
①furnitures can be duplicated with an item_frame and an item_frame will be consumed
②furniture would disappear when there is an item_frame in the place where you want to place the furniture

**Screenshots**
**I recorded a video and made it into gif
You can check it here:**
①https://imgtu.com/i/R2npm6
②https://imgtu.com/i/R2nnnP

**Info (please complete the following information):**
 - Server version: Spigot 1.17
 - Client version: Minecraft vanilla 1.17

**Special Info**
 - ItemsAdder version:2.4.2
 - LightAPI Fork version: 3.5.0
 - LoneLibs version: 1.0.13
 - ProtocolLib version: 4.7.0-SNAPSHOT-b526

**Comment by Xiao-MoMi** [comment]
Another issue is that you can ride rideable furniture which is in the item_frame

**Comment by LoneDev6** [comment]
make sure to run the very LATEST Spigot 1.17.
It works fine on my server
