### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by SentixDev** [PluginBugs/Issues-ItemsAdder#1002]
**Describe the bug**
Running ItemsAdder with LoneLibs, LibsDisguises and ProtocolLib ends in some jvmdumps spamming our server folder.

**To Reproduce**
Setup itemsadder on a purpur 1.16.5 server

**Expected behavior**
plugin startup as usual and load the items and textures.

**PASTEBIN STACKTRACE**
https://pastebin.com/NResvJQZ

**TIMINGS REPORT**
https://timings.pl3x.net/?id=12270f50ed1e447f82d41056358f51d5#timings

**Info (please complete the following information):**
 - Server version: Purpur 1.16.5
 - Client version: Badlion Client 1.16.5 (not joined)

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.0
 - LightAPI Fork version: 3.5.0
 - LoneLibs version: 1.0.13
 - ProtocolLib version: 4.7.0-SNAPSHOT

**Additional context**
https://pastebin.com/NResvJQZ

**Comment by LoneDev6** [comment]
Update ItemsAdder.

Also fix your Java flags, I see strange stuff configured, why aren't you using Aikar's flags?
These are your flags which are likely to be the cause of these JVM dumps. ItemsAdder doesn't generate nor trigger dumps, you're the first customer ever that reports this issue.
`
flags: -Xoptionsfile=/opt/java/openjdk/lib/options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse29 -Dcom.ibm.oti.vm.bootstrap.library.path=/opt/java/openjdk/lib/default:/opt/java/openjdk/lib -Dsun.boot.library.path=/opt/java/openjdk/lib/default:/opt/java/openjdk/lib -Djava.library.path=/opt/java/openjdk/lib/default:/opt/java/openjdk/lib:/usr/lib64:/usr/lib -Djava.home=/opt/java/openjdk -Duser.dir=/home/container -XX:+IgnoreUnrecognizedVMOptions -XX:+IdleTuningGcOnIdle -Xshareclasses:name=openj9_system_scc,cacheDir=/opt/java/.scc,readonly,nonFatal -Xms128M -Xmx6144M -Djava.class.path=server.jar -Dsun.java.command=server.jar -Dsun.java.launcher=SUN_STANDARD
`


These are Aikar's flags:
https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/

**Comment by SentixDev** [comment]
Yeah, I already tried Aikars tuning flags but without any effect. It seems like these strange flags are preset from our Hoster and the casual xms and xmx flags are just attached. They both should be fine, I will just contact the Hoster and ask about those custom flags. Other thing is that it worked until I updated from 2.3.8 to 2.4.0, that was the main factor (beside my correct xms and xmx args) that made me curious about if it’s caused by the actual plugin. I mean we were using it for quite a long time without any major changes until it stopped working on 2.4.0. anyway thanks for clarifying it, I’ll contact the Hoster and will let you know soon.

**Comment by LoneDev6** [comment]
I suspect it's a Purpur feature.
> [17:30:42 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Purpur-1171 (MC: 1.16.5) ---
> The server has not responded for 12 seconds! Creating thread dump

You can try opening paper.yml and set this:
`early-warning-delay: 120000`

**Comment by SentixDev** [comment]
Well, the dumps were caused by a wrong docker image from our hoster. They gave us another version of java 16 which fixed the whole thing. Anyways now its working and wasnt caused by any jvm flags as your supporter dude told me on discord. Thank you for the help and also thanks for the great plugin!

**Comment by LoneDev6** [comment]
No problem, happy you managed to fix the issue, sadly this type of problems is very hard to identify as every hosting has its own configuration and I don't have knowledge for every serverside JVM implementation.

I hope you will consider leaving a 5 stars review, it will help me a lot to make the plugin grow
