### ISSUE TITLE
[BUG] Update the ItemsAdder+WE addon

### ISSUE THREAD

**Issue by Dkavila** [PluginBugs/Issues-ItemsAdder#1005]
**Is your feature request related to a problem? Please describe.**
Need to update to the lastest WE version.
--------------------------
![image](https://user-images.githubusercontent.com/43159733/124501842-ab154f00-dd98-11eb-8942-d840fd7c27a6.png)
--------------------------
![image](https://user-images.githubusercontent.com/43159733/124501780-92a53480-dd98-11eb-9a61-5132740fbd63.png)

**Describe the solution you'd like**
I think WE modified one of its class arguments.
So the solution is to update the addon using the latest version of the WE API to send the correct arguments.

**Describe alternatives you've considered**
Create your own free addon thats set the custom blocks in a given area.

**Additional context**
I am a Brazilian developer who works professionally with java development. If you have a vacancy on your development team I'm interested in helping.

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/917#issuecomment-855744207
