### ISSUE TITLE
[BUG] Block are not returning ores, exception BlockBreakEvent

### ISSUE THREAD

**Issue by darkdragon0226** [PluginBugs/Issues-ItemsAdder#1006]
Hi, I have this exception when a player breaks a custom ore (one of the included by default in the plugin, like ruby ore, coal dirt ore....). It returns a note block instead of the ore. This only happen in a certain area and when I use /iareload I get the exception

https://pastebin.com/e8Lhiudm

**Comment by LoneDev6** [comment]
Do not erase the issue template, you didn't include the requested information

**Comment by darkdragon0226** [comment]
sorry, right now I'm uploading the information
