### ISSUE TITLE
[BUG] [AnimatedTitles]

### ISSUE THREAD

**Issue by sketrick** [PluginBugs/Issues-ItemsAdder#1008]
**Items Adder addon in question**
[AnimatedTitles]
https://www.spigotmc.org/resources/animatedtitles-some-example-animations-itemsadder-addon.84865/

**Describe the bug**
Other players hear the loud noise from animated titles activating.

**To Reproduce**
Be near a player who will get an animated title notification.

**Expected behavior**
Silent notification only for the player that sees it.

**Info (please complete the following information):**
 - Server version: paper 1.17
 - Client version:  Vanilla 1.17

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.2
 - LightAPI Fork version: 3.5.1
 - LoneLibs version: 1.0.13
 - ProtocolLib version: 4.7.0-snapshot-b526

**Comment by LoneDev6** [comment]
Will be fixed, thanks
