### ISSUE TITLE
[BUG] Block are not returning ores, exception BlockBreakEvent

### ISSUE THREAD

**Issue by darkdragon0226** [PluginBugs/Issues-ItemsAdder#1009]
**Describe the bug**

Hi, I have this exception when a player breaks a custom ore (one of the included by default in the plugin, like ruby ore, coal dirt ore....). It returns a note block instead of the ore. This only happen in a certain area and when I use /iareload I get the exception

forget to mention that I use a datapack,  add sub biomes but do not rename the original biomes or add new biomes with different names
datapack: William Wythers' Overhauled Overworld

https://pastebin.com/e8Lhiudm

**To Reproduce**

**Expected behavior**

**Screenshots**
![2021-07-06_12 02 47](https://user-images.githubusercontent.com/84732793/124640596-3d7a2900-de53-11eb-9a02-6798ea45f5fb.png)
![unknown](https://user-images.githubusercontent.com/84732793/124662097-f9485200-de6d-11eb-8071-0adce7bb6867.png)

**Info (please complete the following information):**
 - Server version: (paper-1.17-68.jar)

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: (itemsadder: 2.4.2)
 - LightAPI Fork version: (LightAPI-fork-3.5.0.jar)
 - LoneLibs version: (1.0.13)
 - ProtocolLib version: (4.7.0)

**Comment by LoneDev6** [comment]
I'm sure if you read the full log you can see that a block/loot or something failed to load.
This made the plugin unstable since the loots manager seems to have not been loaded due to this.
