### ISSUE TITLE
[BUG] hide_items in ia_gui.yml not working

### ISSUE THREAD

**Issue by zhenghanlee** [PluginBugs/Issues-ItemsAdder#1010]
**Describe the bug**
**hide_item** key in `ia_gui.yml` doesn't seem to actually hide the listed items in selected categories from admins/OPs.

**To Reproduce**
1. Go to `/ia` menu in-game
2. Click on **All** category
3. See that the category still contains mcicons and rings, which are listed under the **All**'s `hide_item` key by default

**Expected behavior**
Anything under `hide_item` should not be visible under the specified category, even for admins and OPs.

**Screenshots**
![Screenshot 2021-07-07 at 1 41 46 AM](https://user-images.githubusercontent.com/75558451/124644175-8ae2ae80-dec4-11eb-9f13-0a047fb28e99.png)

**Info:**
 - Server version: spigot 1.16.5
 - Client version: lunar client 1.16.5

**Special Info**
 - ItemsAdder version: 2.3.12
 - LoneLibs version: 1.0.9
 - ProtocolLib version: v4.6.1-SNAPSHOT-b505

**Additional context**
For CustomShop plugin to hide its models from `/ia`.

**Comment by LoneDev6** [comment]
Thanks!
This will be fixed
