### ISSUE TITLE
Items have custom durability even when it's not included [BUG] 

### ISSUE THREAD

**Issue by Agaloth** [PluginBugs/Issues-ItemsAdder#1011]
**Describe the bug**
Basically, I'm making custom armor/tool sets on my server, I didn't put the custom durability attribute and it's still there and causes it to regenerate to full durability randomly.

**To Reproduce**
1. Just add a new item and don't add the custom durability property then test.

**Expected behavior**
Items will have custom durability even without the property

**Screenshots**
![image](https://user-images.githubusercontent.com/33335971/124668847-bc9e4a00-deb1-11eb-814d-32e40d1c5f5a.png)

**Info (please complete the following information):**
 - Server version: Airplane-purpur 1.16.5
 - Client version: Lunar and Vanilla Minecraft 1.16.5

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.2
 - LoneLibs version: 1.0.13
 - ProtocolLib version: ProtocolLib 501

Here is my config for the tools: https://pastebin.com/hPLJ7dcd

**Comment by LoneDev6** [comment]
Set `hide-custom-durability-lore: true` in config.yml
This will hide the durability lore from custom items

**Comment by Agaloth** [comment]
The bug doesn't seem to be over, I'm gonna upload a video, seems to only happen for axes.

**Comment by LoneDev6** [comment]
This is strange, did you restart the server and craft a new item?
Works fine for me, no custom durability lore
![image](https://user-images.githubusercontent.com/27242001/125325369-22bb1f00-e341-11eb-86b4-2a5095b7ed66.png)

**Comment by Agaloth** [comment]
https://www.youtube.com/watch?v=PjtaucZLn6U

Look at the durability closely, the durability goes up on custom axe when breaking leaves for some reason but doesn't happen on normal axes.

**Comment by LoneDev6** [comment]
Seems something to do with the instant trees break plugin.
Try to break normal blocks and see what happens

**Comment by Agaloth** [comment]
It works without the timber plugin, but that doesn't happen on a normal netherite axe with the same enchants as the custom axe in the video.

**Comment by LoneDev6** [comment]
> It works without the timber plugin

what does it means?
you mean that without the timber plugin everything is okay or you still experience the problem?

**Comment by Agaloth** [comment]
Basically, without the timber plugin, the custom axe has its normal durability loss and doesn't gain durability by breaking leaves. But with the timber plugin enabled it gains durability by breaking leaves however this doesn't happen on vanilla axes.
