### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by ocyt** [PluginBugs/Issues-ItemsAdder#1012]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Ability to change category titles without interfering with the category name on the main page (hide title per category gui)

**Describe alternatives you've considered**
N/A

**Additional context**
LoneDev, this should ring a bell with the conversation we had via ticket.

**Comment by LoneDev6** [comment]
Will be added in the next update as `title` attribute in the categories section.
You will then be able to set
```yml
name: "My Items"
title: ""
```
