### ISSUE TITLE
[BUG] Warn when clicked MMOcore party menu's "Leave Button"

### ISSUE THREAD

**Issue by ChrisRak** [PluginBugs/Issues-ItemsAdder#1013]
**Describe the bug**
Warn when clicked MMOcore party menu's "Leave Button"

**To Reproduce**
Add ItemsAdder Font image into MMOCore party menu's Title
Use MMOCore command /party
Click the Create party button
Click the Leave button
Warn appear

**Screenshots**
![image](https://user-images.githubusercontent.com/35684012/124713662-6b369f00-df33-11eb-9ec9-cdb166f1bede.png)

**Info (please complete the following information):**
 - Server version: 
![image](https://user-images.githubusercontent.com/35684012/124713726-7be71500-df33-11eb-92a5-fc717726ae50.png)
 - Client version: (example: fabric 1.16.5)
![image](https://user-images.githubusercontent.com/35684012/124713772-87d2d700-df33-11eb-9089-e687f3878c79.png)

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version:
![image](https://user-images.githubusercontent.com/35684012/124713820-96b98980-df33-11eb-9327-77612963288c.png)
 - LightAPI Fork version: not using
 - LoneLibs version:
![image](https://user-images.githubusercontent.com/35684012/124713857-a46f0f00-df33-11eb-8c18-28c81ba06e49.png)
 - ProtocolLib version:
![image](https://user-images.githubusercontent.com/35684012/124713888-afc23a80-df33-11eb-9719-cf77f96f431e.png)

**Comment by LoneDev6** [comment]
Please send this as text log not image.
