### ISSUE TITLE
[BUG] Chairs do not have any solid when solid is set to true

### ISSUE THREAD

**Issue by ChrisRak** [PluginBugs/Issues-ItemsAdder#1014]
**Describe the bug**
Chairs do not have any solid when solid is set to true

**To Reproduce**
![image](https://user-images.githubusercontent.com/35684012/124714029-d84a3480-df33-11eb-9e29-a985459b117d.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/35684012/124714029-d84a3480-df33-11eb-9e29-a985459b117d.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/35684012/124714029-d84a3480-df33-11eb-9e29-a985459b117d.png)

**Info (please complete the following information):**
 - Server version:
![image](https://user-images.githubusercontent.com/35684012/124714108-edbf5e80-df33-11eb-9077-f3945d5f0090.png)
 - Client version: 
![image](https://user-images.githubusercontent.com/35684012/124714133-f6179980-df33-11eb-8490-9e17fea2a693.png)

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - LightAPI Fork version: not installed
 - ItemsAdder version: 
 - LoneLibs version:
 - ProtocolLib version:
![image](https://user-images.githubusercontent.com/35684012/124714159-02035b80-df34-11eb-8e4d-12a92cc9bd0a.png)

**Comment by LoneDev6** [comment]
Tested and works fine.
Something else is wrong, it's hard to tell what is interfering

`This server is running Paper version git-Paper-775 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)`
![image](https://user-images.githubusercontent.com/27242001/125329725-1dac9e80-e346-11eb-8ae2-120487f099fb.png)


```yml
    behaviours:
      furniture:
        small: true
        solid: true
```

![image](https://user-images.githubusercontent.com/27242001/125329799-34eb8c00-e346-11eb-916f-c491eed40314.png)

![image](https://user-images.githubusercontent.com/27242001/125329884-50ef2d80-e346-11eb-9d83-7036c989c451.png)
