### ISSUE TITLE
[Suggestion] Add "HongKong" language support 

### ISSUE THREAD

**Issue by ChrisRak** [PluginBugs/Issues-ItemsAdder#1015]
**Is your feature request related to a problem? Please describe.**
Add "HongKong" language support , and yes i want HongKong language can be added into ia , it will help me to do not need update the resourcepack by myself

**Describe the solution you'd like**
just add that thx a lot

**Comment by LoneDev6** [comment]
I don't have any translator which can help me translating to HongKong Chinese, I'm sorry
