### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by radqnico** [PluginBugs/Issues-ItemsAdder#1016]
**Describe the bug**
events-cooldown doesn't work every time. Statistically, it works 1/2 of the times that events are fired. I am trying to create rings that applies potion effects on right click. I set a cooldown but it lets me spam the right click anyway most of the times.

**To Reproduce**
Insert a custom ring with config: https://hastebin.com/ripipesana.yaml
1. Zip, Reload and Texture all.
2. Get the ring.
3. Spam the right click.

**Expected behavior**
It shouldn't let me spam the right click potion effect and particles effect but statistically 1/2 of the times it just let me spam as i've not set the events-cooldown property.

**Screenshots**

**Info (please complete the following information):**
 - Server version: Airplane 1.16.5
 - Client version: Fabric 1.16.5

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: (example: 2.4.2)
 - LightAPI Fork version: (example: 3.5.0)
 - LoneLibs version: (example: 1.0.12)
 - ProtocolLib version: (example: 4.7.0-SNAPSHOT-b521)

**Additional context**
It's not a simple problem to replicate, due to its probabilistic nature, I hope the information i gave it's enough to investigate.

**Comment by LoneDev6** [comment]
Prova a riavviare il server una volta creato l'item, mi sembra funzionare correttamente dopo un riavvio completo

**Comment by LoneDev6** [comment]
E ricorda che saturation 1 0 applica solo per 1 tick, ti consiglio di aumentare il valore
