### ISSUE TITLE
No field with type int exists in class PacketPlayOutEntityDestroy.  After upgrade to 1.17.1

### ISSUE THREAD

**Issue by taka1945** [PluginBugs/Issues-ItemsAdder#1017]
**Describe the bug**
after upgrade to 1.17.1 got this message.
https://pastebin.com/nughBX1y

**Info (please complete the following information):**
 - Server version: paper 1.17.1
 - Client version: 1.17.1

**Special Info**
 - ItemsAdder version: 2.4.2
 - LightAPI Fork version: LightAPI-fork-3.5.0
 - LoneLibs version: LoneLibs-1.0.13
 - ProtocolLib version: ProtocolLib #526

**Comment by LoneDev6** [comment]
Will be fixed, thanks
