### ISSUE TITLE
[BUG] PacketFilterManager : Unsupport server packet

### ISSUE THREAD

**Issue by LoneDevilX** [PluginBugs/Issues-ItemsAdder#1018]
**Describe the bug**
Unsupport server packet from Protocolib with 'Call stack'
# not so sure what happen...

**To Reproduce**
1. Start server
2. Have error

**Expected behavior**
Without error?

**Screenshots**
x

**Info (please complete the following information):**
 - Server version: paper-1.17-71 (dev build)
 - Client version: -

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.2
 - LightAPI Fork version: 3.5.1
 - LoneLibs version: 1.0.13
 - ProtocolLib version: 4.6.0 Dev Build #526

**Additional context**
https://pastebin.ubuntu.com/p/HwqNNzq7NS/

**Comment by SirCraftypants** [comment]
Not an Error, it's a Warn but still needs attention of course, i have a similar Warn

[01:16:58 WARN]: [ProtocolLib] [PacketFilterManager] [ItemsAdder] Unsupported server packet in current Minecraft version: TITLE[PLAY, SERVER, 249, classNames: [net.minecraft.network.protocol.game.PacketPlayOutTitle, net.minecraft.network.protocol.game.ClientboundTitlePacket] (unregistered)]

**Comment by LoneDev6** [comment]
You can ignore it
