### ISSUE TITLE
[BUG]  Could not pass event ChunkLoadEvent to ItemsAdder v2.3.12

### ISSUE THREAD

**Issue by hankwu0501** [PluginBugs/Issues-ItemsAdder#1021]
**Describe the bug**
https://hastebin.com/ruzikuyole.properties
https://hastebin.com/somepetake.properties

**Screenshots**
![image](https://user-images.githubusercontent.com/70510836/124942717-732f3580-e03e-11eb-990e-805e847c86f6.png)
**Info (please complete the following information):**
 - Server version: purpur 1.16.5
 - Client version: optifine1.16.5

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.3.12
 - LightAPI Fork version: 3.4.6
 - LoneLibs version:  1.0.13
 - ProtocolLib version: 4.6.1

if you would like to see on my server feel free to contact me
派小星#2926

**Comment by LoneDev6** [comment]
Update
