### ISSUE TITLE
Using sharpness enchant doesn't update the attack damage description 

### ISSUE THREAD

**Issue by Sixsoul** [PluginBugs/Issues-ItemsAdder#1022]
Same as this issue. It hasn't worked correctly for many versions now, sharpness does not change the damage lore.

https://github.com/PluginBugs/Issues-ItemsAdder/issues/183

**Comment by LoneDev6** [comment]
It works fine when you enchant it using the enchanting table or anvil.
Custom enchant commands won't work simply because I don't know each plugin available which allows to enchant items directly, so I cannot syncronize it.
You will have to enchant using the enchanting table

**Comment by LoneDev6** [comment]
Also please next time don't erase the issue template.
All the info asked is mandatory for me to identify the issue.
Thanks
