### ISSUE TITLE
[BUG] NullPointerException thrown when using CustomFurnitureAPI

### ISSUE THREAD

**Issue by SignorPollito** [PluginBugs/Issues-ItemsAdder#1023]
**Describe the bug**
An NPE (NullPointerException) is thrown when spawning a custom furniture using the API.

**To Reproduce**
1) Use the CustomFurniture#spawn(id, block) or CustomFurniture#spawnPreciseNonSolid(id, location) API
2) Then the exception will be thrown

**Expected behavior**
The furniture should be placed without exceptions in console.

**Screenshots**
https://pastebin.com/XpAp58wF

**Info (please complete the following information):**
 - Server version: Purpur 1.16.5
 - Client version: Optifine 1.16.4
 - Java version: 16

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.2
 - LightAPI Fork version: /
 - LoneLibs version: 1.0.13
 - ProtocolLib version: 4.6.0

**Additional context**
The exception is thrown only when spawning the furniture using the CustomFurniture API.

**Comment by LoneDev6** [comment]
Thanks, this will be fixed in the next update
