### ISSUE TITLE
[BUG] Swords keep extra damage when unenchanted

### ISSUE THREAD

**Issue by ElMoha943** [PluginBugs/Issues-ItemsAdder#1024]
**Describe the bug**
When you unenchant a sword that has sharpness it keeps the extra damage

**To Reproduce**
1. Enchant a custom sword with sharpness
2. Use a grindstone to unenchant the sword

**Expected behavior**
Damage stat should revert to default

**Screenshots**
![image](https://user-images.githubusercontent.com/25410859/125149330-f4ee9400-e10e-11eb-95a1-4ccaefc03ba8.png)
![image](https://user-images.githubusercontent.com/25410859/125149351-fcae3880-e10e-11eb-91bc-d925cc1c19b5.png)
![image](https://user-images.githubusercontent.com/25410859/125149357-05067380-e10f-11eb-840d-8de56405fefe.png)
![image](https://user-images.githubusercontent.com/25410859/125149365-0fc10880-e10f-11eb-9f6d-9f8a3f900864.png)

**Info (please complete the following information):**
 - Server version: tuinity 1.16.5
 - Client version: fabric 1.16.5 (but happens to multiple user with multiple clients)

**Special Info**
 - ItemsAdder version: 2.4.2
 - LightAPI Fork version: 3.5.1
 - LoneLibs version: 1.0.13
 - ProtocolLib version: 4.6.0

**Comment by LoneDev6** [comment]
I'll fix this bug, but don't worry, it's only a visual bug, the damage is internally updated.
