### ISSUE TITLE
[BUG] the vehicles cannot be used

### ISSUE THREAD

**Issue by 100petr** [PluginBugs/Issues-ItemsAdder#1025]
**Describe the bug**
the plane cannot be used

**To Reproduce**
1. Put coal on the plane
2. Click on the plane
3. See error

**Expected behavior**
It will be possible to sit the plane and there will be no error in the console

**Info (please complete the following information):**
 - Server version: Purpur 1.17.1
 - Client version: optifine 1.17.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.2
 - LightAPI Fork version: 3.5.1
 - LoneLibs version: 1.0.13
 - ProtocolLib version: 4.7.0 #528

**Additional context**
Error: https://pastebin.com/LbdF48Vh
No vehicle works, only the cart.

**Comment by LoneDev6** [comment]
This will be fixed
