### ISSUE TITLE
[BUG]  Invisible dropped items

### ISSUE THREAD

**Issue by darkdragon0226** [PluginBugs/Issues-ItemsAdder#1027]
**Describe the bug**
When I drop a item (it happens more often with swords) it become invisible, but the item still exists and I can take it. This happens with the version 2.4.2. 
When I tested in an older version (2.4.0) this not happend

**Screenshots**
in this version works fine
![ia](https://user-images.githubusercontent.com/84732793/125181430-44de6100-e1ca-11eb-9e0a-8c9de28f4329.PNG)
This is a gif of the bug in 2.4.2 version
![drop](https://user-images.githubusercontent.com/84732793/125181585-b9fe6600-e1cb-11eb-9e05-76f9ac9a029b.gif)

Info (please complete the following information):

Server version: (paper-1.17-79.jar)
Special Info

ItemsAdder version: (2.4.2)
LightAPI Fork version: (fork 3.5.0)
LoneLibs version: (example: 1.0.13)
ProtocolLib version: (4.7.0 SNAPSHOT b528)

**Comment by sketrick** [comment]
There is a new version of LightsAPI 3.5.1 and new version of Paper and ProtocolLib released a stable build.

I can't reproduce this on my 1.17.1 server with updated plugins.

**Comment by darkdragon0226** [comment]
I already update and stay the same, the swords become invisible

**Comment by darkdragon0226** [comment]
I noticed that this happens with swords and tome of knowledge sharing from slime fun and only in certain zones, the sword stills invisible until I restart the server, but if I go out and return to this zone the sword becomes invisible again

**Comment by LoneDev6** [comment]
I suspect it's not an ItemsAdder issue, seems something vanilla.
https://www.reddit.com/r/Minecraft/comments/cle9j5/invisible_dropped_items/
https://www.minecraftforum.net/forums/support/java-edition-support/1868555-ssp-14w04b-dropped-items-invisible

I can't manage to find a post but it contained also a video about that, recorded in vanilla Minecraft.
I'll work hard on finding the cause if you manage to prove that this doesn't happen if you disable itemsadder

**Comment by darkdragon0226** [comment]
this only happens with the custom swords of the Items adder
![Minecraft_ 1 17 1 - Multijugador (servidor de terceros) 2021-07-12 12-12-00](https://user-images.githubusercontent.com/84732793/125329316-f71d4200-e30a-11eb-9313-f28859aeaebf.gif)

**Comment by LoneDev6** [comment]
okay but if you disable itemsadder temporarily, then drop an item, does it still vanishes or not?

**Comment by darkdragon0226** [comment]
1- I tested with items adder disabled, vanilla sword are not disappearing, but i had one sword tha was from items adder and when I dropped it disappeared, the sword of items adder was the last
2 - yes
3 - no, they don`t
![ia](https://user-images.githubusercontent.com/84732793/125331445-9ba08380-e30d-11eb-97ad-4a7bb029ebb9.gif)

**Comment by LoneDev6** [comment]
so seems to be another plugin interfering or an actual vanilla bug, since if itemsadder is disabled there is nothing in itemsadder code that is making the item invisible or interfering with the drop itself.

I really have no clue since it doesn't happen on my test server, that's very hard to identify
