### ISSUE TITLE
[BUG] A huge furniture bug (item_frame) multiplies six times after breaking.

### ISSUE THREAD

**Issue by TeiBri** [PluginBugs/Issues-ItemsAdder#1029]
** Describe the bug **
The error is with item_frames furnitures, etc. KIf I break the furniture (item_frame), 6 more will fall out of it.

** To Reproduce **
1. Go to 'server'
2. Click on 'my furniture or addon furniture2 (item_frame)'
3. Place it on the ground
3. Break it
4. See error (Console does not report any error)

** Screenshots and videos **

https://user-images.githubusercontent.com/62265168/125195218-0a6dd600-e255-11eb-86b8-b072672144fb.mp4

** Info (please complete the following information): **
  - Server version: spigot 1.16.5
  - Client version: vanilla 1.16.5

** Special Info **
Please do not write "latest"! Tell us the specific plugin version you are using.
  - ItemsAdder version: 2.4.2
  - LightAPI Fork version: 3.5.1
  - LoneLibs version: 1.0.13
  - ProtocolLib version: 4.7.1 SNAPSHOT

** yml **
  template_plant_in_pot:
    template: true
    display_name: ""
    lore:
    - 'lore-decorative-item'
    resource:
      material: PAPER
      generate: false
      model_path: item/bamboo_plant_in_pot
    behaviours:
      furniture:
        entity: item_frame
        solid: false
        hitbox:
          length: 1
          width: 1
          height: 1.5
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  bamboo_plant_in_pot:
    variant_of: template_plant_in_pot
    display_name: Bamboo Plant in Pot
    permission: bamboo_plant_in_pot
    resource:
      material: PAPER
      generate: false
      model_path: item/bamboo_plant_in_pot

**Comment by LoneDev6** [comment]
This will be fixed
Anyway next time please publish your config as file and not as text, spaces got lost..
