### ISSUE TITLE
[BUG] server crash

### ISSUE THREAD

**Issue by 100petr** [PluginBugs/Issues-ItemsAdder#1030]
**Describe the bug**
The server crashes while generating trees (probably) even though you fixed it

**To Reproduce**
I don't know the exact procedure, so I write what I think it is
1. Go to the end
2. Fly (probably at the end) and have IA trees generated

**Expected behavior**
The server will not crash

**Screenshots**

**Info (please complete the following information):**
 - Server version: Purpur 1.17

**Special Info**
 - ItemsAdder version: 2.4.2
 - LightAPI Fork version: 3.5.0
 - LoneLibs version: 1.0.13
 - ProtocolLib version: 4.7.0-SNAPSHOT-b526

**Additional context**
Crash: https://pastebin.com/fFPECDR2

**Comment by LoneDev6** [comment]
Update to 1.17.1 after I release ItemsAdder 2.4.3.
I think it's a 1.17 bug about chunks loading.

You may also try to use Paper

**Comment by 100petr** [comment]
I have been using 1.17.1 since Saturday, but the problem has only occurred once since your fix. before and several times a day (or the players stopped flying so much in the end, before that I restarted them)

**Comment by LoneDev6** [comment]
I'd report this to Spigot directly.
Seems that somehow the server is calling the populator callback even if the chunk is not loaded in memory.
My plugin uses the normal Bukkit populator, no hacky stuff.

I implement this function:
```java
@Override
public void populate(@NotNull World world, @NotNull Random random, @NotNull Chunk source)
```

**Comment by 100petr** [comment]
It was probably a 1.17 bug, the server has been at 1.17.1 for 2 weeks and it hasn't crashed yet.

**Comment by 100petr** [comment]
https://github.com/pl3xgaming/Purpur/commit/6ba5e90c5bea746c5a03f0ccd8f9463d934009be Maybe it's related

**Comment by LoneDev6** [comment]
This may be reported also to Spigot itself in order to let them know about the issue.
Feel free to open an issue report on their website https://hub.spigotmc.org/jira/projects/SPIGOT/issues
