### ISSUE TITLE
[BUG] ItemsAdder block fail to generate light when using RWG to generate

### ISSUE THREAD

**Issue by Caishangqi** [PluginBugs/Issues-ItemsAdder#1032]
**Describe the bug**
HI, I found that when I use RWG to generate itemsadder block by Schematics system, the block can not emit light.

**To Reproduce**
1. Write a block in IA, with lightlevel
2. use RWG Schematics to generate the structure with that block
3. the Block generate by RWG do not have any lightlevel

**Expected behavior**
It should have light level.

**Screenshots**
The mushroom generate by RWG
![image](https://user-images.githubusercontent.com/39553613/125389022-6586f200-e355-11eb-9f91-b9b20118f3bd.png)

The mushroom placed by Player
![image](https://user-images.githubusercontent.com/39553613/125389836-afbca300-e356-11eb-8755-f0e068c107bb.png)

**Info (please complete the following information):**
 - Server version: paper 1.16.5
 - Client version: vanilla 1.16.5

**Special Info**
 - ItemsAdder version: 2.4.2
 - LightAPI Fork version: 3.5.1
 - LoneLibs version: 1.0.13
 - ProtocolLib version: 4.7.0-b526
 - RealisticWorldGenerator version: 4.28.5
 - Light Cleaner 1.16.5-v1

**Additional context**
The configuration of RWG file
https://paste.ubuntu.com/p/SYzGr53tfJ/
The configuration of IA block file
https://paste.ubuntu.com/p/S7W3VM7qvC/

I would send another issue to RWG :)

**Comment by LoneDev6** [comment]
This will be fixed in the next update, thanks

**Comment by Caishangqi** [comment]
I had update IA to 2.4.3 with Protocolib v4.7.0 and LoneLibs 1.0.14, but seems like the block still does not emit light.
![image](https://user-images.githubusercontent.com/39553613/125478609-1d3c87a5-8c91-486e-8929-61b527d79fda.png)
Do I need to rewrite the custom block schematic or regenerate the whole world? :)

**Comment by LoneDev6** [comment]
Did you try to check new chunks?
Custom blocks in already generated chunks won't receive the light fix

**Comment by Caishangqi** [comment]
> Did you try to check new chunks?
> Custom blocks in already generated chunks won't receive the light fix

I had tried to generate entire word, but it seem the light level not working

**Comment by LoneDev6** [comment]
I'll publish an update in the next days, I may have found the actual issue

**Comment by Caishangqi** [comment]
> I'll publish an update in the next days, I may have found the actual issue

Thanks a lot!

**Comment by Caishangqi** [comment]
It works fine :) thanks for fixing.

![image](https://user-images.githubusercontent.com/39553613/125778587-b9aa2b4b-b39b-4137-b2b9-1f41e6342283.png)
