### ISSUE TITLE
[BUG] An error occurred while joining without activating the resource pack server in the console.

### ISSUE THREAD

**Issue by Rushia140** [PluginBugs/Issues-ItemsAdder#1034]
**Describe the bug**
I didn't find a bug, but I see an error popping up in my console.

**To Reproduce**
1. Open Minecraft
2. Edit server: Server Resource Packs: Disabled
3. Join server
4. See error on console
5. if the Server Resource Pack is enabled, error not showing in console

**Expected behavior**
No error appears on console.

**Screenshots**
![Screenshot (410)](https://user-images.githubusercontent.com/45330419/125464798-92cf04b4-0fed-48c8-b9e9-c43346acf0c1.png)

**Info (please complete the following information):**
 - Server version: Airplane 1.17.1#45
 - Client version: Optifine 1.17.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.3
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Additional context**
logs https://pastebin.com/FMw50CbS

**Comment by LoneDev6** [comment]
Test on normal Spigot, let me know if it happens also on Spigot.
I think it's an Airplane bug

**Comment by Rushia140** [comment]
I have tried, still the same.
https://pastebin.com/bHiFhTc7

**Comment by LoneDev6** [comment]
Thanks, this should be fixed in the new update, let me know
