### ISSUE TITLE
[BUG] sometimes can connect without pack

### ISSUE THREAD

**Issue by 100petr** [PluginBugs/Issues-ItemsAdder#1035]
**Describe the bug**
sometimes it can be connected without a resourcepack

**To Reproduce**
1. Connect to the server 
2. Some players don't throw it away if they don't have a resourcepack

**Expected behavior**
Everyone will need to have a resourcepack

**Screenshots**
![image](https://user-images.githubusercontent.com/29830635/125470309-ad727e95-60a3-4132-af11-f7d9e87dba0d.png)
![IMG_20210708_150411053](https://user-images.githubusercontent.com/29830635/125470562-388b1059-b965-4a60-bf70-2688bc3f0cc0.jpg)

**Info (please complete the following information):**
 - Server version: purpur 1.17.1 it also did on 1.16.5
 - Client version: vanilla 1.17.1, tlauncher 1.17.1 it also did on 1.16.5
 
**Special Info**
 - ItemsAdder version: 2.4.2
 - LightAPI Fork version: 3.5.1
 - LoneLibs version: 1.0.13
 - ProtocolLib version: 4.7.0 b528
 
**Additional context**
My config: https://pastebin.com/gsqp0p6m
Reportedly, players have a server resource pack: prompt
In the console, I see that it kick players to activate the resource pack, but sometimes it leaves them. There is someone without pack that every day.

**Comment by LoneDev6** [comment]
can you try 2.4.3?

**Comment by 100petr** [comment]
there is no error in the console, I uploaded the update to the server (I have to upload the hotfix again) and there is an automatic restart tomorrow 4:32
What I asked one player who was on the server without a resourcepack a while ago so wrote that he has a clean original launcher

**Comment by 100petr** [comment]
I sent you a log on the discord.
