### ISSUE TITLE
[BUG] bukkit version 1.17.1 (my bukkit Fork Airplane)

### ISSUE THREAD

**Issue by ninesik** [PluginBugs/Issues-ItemsAdder#1036]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - Server version: (example: paper 1.16.5)
 - Client version: (example: fabric 1.16.5)

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: (example: 2.4.2)
 - LightAPI Fork version: (example: 3.5.0)
 - LoneLibs version: (example: 1.0.13)
 - ProtocolLib version: (example: 4.6.0)

**Additional context**

Server version: (Airplane-Purpur 1.17.1)
ItemsAdder version: (2.4.3)

![image](https://user-images.githubusercontent.com/41807903/125492586-b66a1f3a-fd25-465f-99bc-7504b82755c3.png)

**Comment by ninesik** [comment]
https://ci.tivy.ca/

**Comment by ninesik** [comment]
![image](https://user-images.githubusercontent.com/41807903/125492671-36920d2a-0836-4a88-9a56-a01ec4babf90.png)

**Comment by ninesik** [comment]
my build version #17

**Comment by LoneDev6** [comment]
Send the complete log

**Comment by ninesik** [comment]
[2021-07-14-16.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/6819480/2021-07-14-16.log)

**Comment by LoneDev6** [comment]
will be fixed, thanks
