### ISSUE TITLE
[BUG] double arrow

### ISSUE THREAD

**Issue by 100petr** [PluginBugs/Issues-ItemsAdder#1041]
**Describe the bug**
There are two from one arrow

**To Reproduce**
1. Get bow / crossbow
2. Shoot
3. There are two from one arrow

**Expected behavior**
There will be only one arrow after shoot

**Screenshots**
https://user-images.githubusercontent.com/29830635/125642203-93e9faa6-1987-407e-a999-24c1abab6480.mp4

**Info (please complete the following information):**
 - Server version: purpur 1.17.1
 - Client version: optifine 1.17.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.3
 - LightAPI Fork version: 3.5.0
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Comment by LoneDev6** [comment]
Will be fixed, thanks
