### ISSUE TITLE
[BUG] problem with vehicles plugin

### ISSUE THREAD

**Issue by 100petr** [PluginBugs/Issues-ItemsAdder#1046]
**Describe the bug**
Submarines from vehicles plugin https://www.spigotmc.org/resources/✈%EF%B8%8Fvehicles-no-resourcepacks-needed.12446/ do not work after updating to IA 2.4.3

**To Reproduce**
1. Update IA to 2.4.3 (or 2.4.4)
2. Place submarine from vehicles plugin
3. Sit in the submarine, you can't move

**Expected behavior**
You can move with submarines from the Vehicles plugin

**Screenshots**

https://user-images.githubusercontent.com/29830635/126034639-de5b092f-ed98-4afc-b1a1-d4a0cafe0b07.mp4

https://user-images.githubusercontent.com/29830635/126034643-63464666-226e-491e-be29-bcc63b19c6d1.mp4

**Info (please complete the following information):**
 - Server version: purpur 1.17.1
 - Client version: optifine 1.17.1

**Special Info**
 - ItemsAdder version: 2.4.4 (problem started in version 2.4.3)
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.1 b530

**Comment by LoneDev6** [comment]
Are you sure it worked on 2.4.3? I didn't change anything about vehicles in 2.4.4, I checked my logs
