### ISSUE TITLE
Crafting Table Recipe Book

### ISSUE THREAD

**Issue by Fantom250YT** [PluginBugs/Issues-ItemsAdder#1047]
**Crafting Table Recipe Book for Items**
A way to put the custom items into the crafting table recipe book, you can then see the recipes from selecting the item of choice in the book.

**Screenshot of Menu**
<img width="512" alt="Screenshot 2021-07-18 at 12 59 49" src="https://user-images.githubusercontent.com/73852683/126066210-52b264d7-8bea-405e-a3e9-24dc3067b51c.png">

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/6
https://github.com/PluginBugs/Issues-ItemsAdder/issues/665
https://github.com/PluginBugs/Issues-ItemsAdder/issues/330

Use the search button, thanks!
Have a nice day
