### ISSUE TITLE
[BUG] Resource Pack Error

### ISSUE THREAD

**Issue by Kasumaca** [PluginBugs/Issues-ItemsAdder#1048]
![image](https://user-images.githubusercontent.com/58649780/126066318-38c296a1-068a-45d9-865c-146143ea679d.png)

**Comment by 100petr** [comment]
https://itemsadder.devs.beer/first-install#step-2-resourcepack-first-installation

**Comment by LoneDev6** [comment]
1. Please avoid erasing the entire issue template, all the info asked is required.
2. as 100petr said: read the installation tutorial

have a nice day
