### ISSUE TITLE
chairs directions problem

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#1050]
**Describe the bug**
after i Update the itemadder there was problem with the directions this problem wasn't on the old version 
![unknown](https://user-images.githubusercontent.com/68678154/126069052-eea273d9-6ba4-4efb-a2b9-d7a46b6ae848.png)
![image](https://user-images.githubusercontent.com/68678154/126069063-f0bc5aa7-f0ef-4a92-bdde-2faa23fac7d6.png)
but this is a big problem because if i rotate it by my self without use the Block bench the problem will still the same
https://i.imgur.com/tYqyrXJ.mp4
also when i put the chair on west it's working fine but when i changed to NORTH the Problem happens again
![unknown (1)](https://user-images.githubusercontent.com/68678154/126069593-31a92391-b12b-4200-af15-29bacc82f39d.png)

also, I don't know do I saw this on a console when I sit on a chair 
![image](https://user-images.githubusercontent.com/68678154/126069825-34f90f62-fb8a-4157-9343-6d6eec350220.png)

**Info (please complete the following information):**
 - Server version: (paper 1.16.5)
 - Client version: (vanilla 1.16.5)

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: (2.4.4)
 - LightAPI Fork version: (3.5.2)
 - LoneLibs version: (1.0.14)
 - ProtocolLib version: (4.7.0)

**Additional context**
add a new attribute that set the direction automatically like the old version ^^

**Comment by LoneDev6** [comment]
Send here your chair configuration yml.
I can't manage to reproduce the issue @SNokerYT
