### ISSUE TITLE
Can't place a Furniture glitchy disappear when I place after /iazip or iareload ⚠

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#1051]
**Describe the bug**
i Can't place Furniture Above any other Furniture this Problem hasn't happened on the old Version of item adder 
also there a Weird thing that happened when you place it it's glitchy disappear when I place it anywhere 
there a problem but i don't know where the problem comes from
![chairssssdwa](https://user-images.githubusercontent.com/68678154/126093143-4758cb21-6bb3-4927-a588-e15aa2d743da.gif)
Here is the small Example about what I mean by glitchy disappear when I place it
![image](https://user-images.githubusercontent.com/68678154/126092578-7d0d5a7e-fa04-4f65-9fcc-f6b7546316a7.png)

**Info (please complete the following information):**
Server version: (paper 1.16.5)
Client version: (vanilla 1.16.5)

**Special Info**
ItemsAdder version: (2.4.4)
LightAPI Fork version: (3.5.2)
LoneLibs version: (1.0.14)
ProtocolLib version: (4.7.0)

**Comment by LoneDev6** [comment]
>  this Problem hasn't happened on the old Version of item adder

which one? please be more specific


also, are you running the very latest 1.16.5 paper? https://papermc.io/downloads#Paper-1.16
does this happens on normal spigot? https://serverjars.com/

**Comment by LoneDev6** [comment]
https://user-images.githubusercontent.com/27242001/126143218-3a62d369-2945-4379-8025-d97d5e9f93cc.mp4

**Comment by SNokerYT** [comment]
i Discover that item disappearing like this when you do /iazip
but if you do /restart and join the server once again will be fixed

**Comment by LoneDev6** [comment]
strange..

can you make a video or a list of actions to trigger this bug?

**Comment by SNokerYT** [comment]
https://i.imgur.com/px0BYcl.mp4

**Comment by LoneDev6** [comment]
Is your item material PAPER or a block?
I tested with PAPER and works fine, I exactly did what you did in the video

**Comment by SNokerYT** [comment]
![image](https://user-images.githubusercontent.com/68678154/127305363-ec53e0f2-ebfa-4cff-b733-c07e3a47ea08.png)
![image](https://user-images.githubusercontent.com/68678154/127305439-fe2834ba-8476-483a-9767-82e3c86b58ba.png)

**Comment by LoneDev6** [comment]
are you running the latest itemsadder? i see 2.4.4 in the issue report

**Comment by SNokerYT** [comment]
yes it's the latest version

**Comment by SNokerYT** [comment]
https://paste.lucko.me/Qg8MIHPRCw

**Comment by LoneDev6** [comment]
Can i see your furniture .yml settings? I only need the item part, no need to share the whole file with all the items

**Comment by SNokerYT** [comment]
beach_chair:
    display_name: beach chair
    permission: beach_chair
    lore:
    - ':paintable:'
    resource:
      material: LEATHER_HORSE_ARMOR
      generate: false
      model_path: item/beach_chair
    behaviours:
      furniture:
        small_hitbox: true
        solid: true
        fixed_rotation: false
      furniture_sit:
        sit_height: 0.5

**Comment by LoneDev6** [comment]
I tried multiple times and still I can't manage to reproduce the issue.. I'm sorry for the inconvenience but it works fine on my server.

```yml
This server is running CraftBukkit version 3208-Spigot-18c71bf-97f629b (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)
[15:01:24] [Server thread/INFO]: Checking version, please wait...
[15:01:25] [Thread-78/INFO]: You are running the latest version
>version itemsadder
[15:01:26] [Server thread/INFO]: ItemsAdder version 2.4.6

**Comment by SNokerYT** [comment]
Did you try version 1.16.5

**Comment by LoneDev6** [comment]
Using your config.
```yml
  beach_chair:
    display_name: beach chair
    permission: beach_chair
    lore:
    - ':paintable:'
    resource:
      material: LEATHER_HORSE_ARMOR
      generate: false
      model_path: item/beach_chair
    behaviours:
      furniture:
        small_hitbox: true
        solid: true
        fixed_rotation: false
        furniture_sit:
        sit_height: 0.5
```
https://user-images.githubusercontent.com/27242001/127874554-191fe027-2fe7-4b5a-8b6c-bff5e88f0dc7.mp4



Can you try removing all plugins temporarily? Enable whitelist so that no one will enter, then keep only ItemsAdder and its dependencies.

**Comment by SNokerYT** [comment]
I did remove the plugins only kept the ItemsAdder and the dependencies and I am still having the same problem and I updated everything to the latest version.
also, there was someone have the same problem on discord
![image](https://user-images.githubusercontent.com/68678154/132089303-487510d6-26ae-4a00-89c6-f7eccf200d52.png)
this is a big issue you have to look into, I'm serious I tried everything to find where the problem comes from but it's come from itemsadder.
=====
watch this video | https://i.imgur.com/msgPTh2.mp4

**Comment by LoneDev6** [comment]
So basically you can't place furnitures/vehicles anymore after you run /iazip command?
Also on /iareload?

Let me know

**Comment by SNokerYT** [comment]
In my situation I just testing the furniture, i never test it on vehicles but when I tried the vehicles before I do /iareload can't even put it on the ground I did not do /a reload or /ia zip that's Weird :/

**Video =** https://i.imgur.com/nscWXI2.mp4

**Comment by LoneDev6** [comment]
Thanks, I managed to trigger the issue.
This will be fixed in the next update.
