### ISSUE TITLE
[BUG][ItemsAdder] Corrupted region data! Copying it into '_corrupted' folder. Loading NBT data

### ISSUE THREAD

**Issue by hankwu0501** [PluginBugs/Issues-ItemsAdder#1052]
**Describe the bug**
https://pastebin.com/7E9Aff7U

**To Reproduce**
/iazip
**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - Server version: (paper 1.16.5)
 - Client version: (optifin  1.16.5)

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: ( 2.4.4 )
 - LightAPI Fork version: (example: 3.4.6)
 - LoneLibs version: (example: 1.0.14)
 - ProtocolLib version: (example: 4.7.0)

**Additional context**

**Comment by LoneDev6** [comment]
Read the previous log lines, I'm sure something failed to load, probably a block.
This caused itemsadder to fail loading region files.
