### ISSUE TITLE
[BUG] Server slowing down if fixed_glitched_blocks.nbt is very big

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#1058]
Add a check if the file is > 1MB, this should speedup loading and avoid this problem.
Or find a way to make the file smaller.

**Comment by shmezi** [comment]
What was the method used to reduce startup times?

Smaller size/clearing/other

**Comment by LoneDev6** [comment]
https://itemsadder.devs.beer/faq/plugin-loading-very-slow#after-some-weeks-months-itemsadder-loading-is-very-slow
