### ISSUE TITLE
Player can fly[BUG] 

### ISSUE THREAD

**Issue by DarrienNN** [PluginBugs/Issues-ItemsAdder#1060]
**Describe the bug**
Player are able to fly without permission (Problem from **_LoneLibs_**, sometime i go overworld then i can fly without any perms/cmd, and sometime i go spawn can fly. It random [100% fly will work in this 2 world]

**To Reproduce**

**Expected behavior**

**Screenshots**
Dont have screenshot

**Info (please complete the following information):**
 - Server version: (This server is running Tuinity version git-Tuinity-23 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: ce43ccd on HEAD))
 - Client version: (Mojang + Optifine pre30 1.17.1)

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: (2.4.5)
 - LightAPI Fork version: (3.5.2)
 - LoneLibs version: (1.0.14)
 - ProtocolLib version: (4.7.0)

**Additional context**

**Comment by LoneDev6** [comment]
post your complete log of when this issue happened

**Comment by DarrienNN** [comment]
In console no any update 🤔 but player will get fly

**Comment by LoneDev6** [comment]
try to install normal Spigot or Paper instead of Tuinity.
I tested on a server with Spigot 1.17.1 latest build and works fine, no fly problem.

In the next update I'll add an option to disable fly completely on join when applying resourcepack.

**Comment by DarrienNN** [comment]
I tried install paper / spigot but same, and this fly sometime in flat world sometime in overworld

**Comment by DarrienNN** [comment]
After restart maybe when you go flat world and we can fly, sometime after restart will get fly at overworld

**Comment by LoneDev6** [comment]
I'll try to fix this in the next update.
Please update after I publish the update and let me know.


have a nice day
