### ISSUE TITLE
Compatibility with AE 

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-ItemsAdder#1061]
Please can you provide support for Advanced Enchantments 

https://www.spigotmc.org/resources/1-8-1-17-1-%E2%AD%95-advancedenchantments-%E2%AD%90-450-custom-enchants-%E2%AD%90create-custom-enchantments-%E2%9C%85-30-sale.43058/

**Comment by LoneDev6** [comment]
It should already be supported, try to use the enchant name itself without adding `advanced_enchantment:` in front of it.

keep in mind that lore may not be updated correctly

**Comment by maxwellvalasek** [comment]
I am also experiencing trouble with the compatability of Advanced Enchants, would love to see this implemented!

**Comment by SirCraftypants** [comment]
Just to make sure, so you've tried the below yes?

vampire:1
ae_enchantment:vampire:1
advanced_enchantment:vampire:1

I'd try myself but away from my computer.

**Comment by maxwellvalasek** [comment]
Yes I have! My solution was to add this to the items config, however, now i cant get the lore to show up. 
![unknown](https://user-images.githubusercontent.com/78054390/140179258-4a917dd1-7ed0-427b-9c6b-3b7bce9696d8.png)

**Comment by SirCraftypants** [comment]
Hopefully Lonedev can get it to work as soon as he has the time spare.

**Comment by LoneDev6** [comment]
It should already be compatible.
The reason why lore doesn't show up is a bug I think, let me know if this still happens in 2.4.21

**Comment by LeveledChemist** [comment]
I am still having issues myself with this, I can't seem to get any AEs to apply w/o using the nbt method mentioned above.

**Comment by LeveledChemist** [comment]
info:
  namespace: newitems
recipes:
  crafting_table:
    lava_dipped:
      permission: newitems.lava_dipped
      enabled: true
      pattern:
      - EEE
      - XSX
      - XSX
      ingredients:
        E: LAVA_BUCKET
        S: STICK
      result:
        item: newitems:lava_dipped
        amount: 1
items:
  lava_dipped:
    display_name: '&cLava Dipped Pickaxe'
    permission: newitems.lava_dippeduse
    resource:
      material: NETHERITE_PICKAXE
      generate: true
      textures:
      - item/lava_dipped.png
    durability:
      max_custom_durability: 3000
    nbt: '{Enchantments: [{id: "minecraft:ae_glow", lvl: 1s}], "ae_enchantment;smelting": 3}'
    enchants:
    - "ae_enchantment:replenish:1"
    lore:
      - '&4Picked up from the depths of a deep cave.'
      - ''
      - '&7Increased durability and efficiency.'
      - ''
      - ''
    drop:
      show_name: true
    events:
      drop:
          play_sound:
            name: item.bucket.empty_lava
            volume: 1
            pitch: 1
      held:
        play_sound:
          name: item.bucket.fill_lava
          volume: 1
          pitch: 1

**Comment by LoneDev6** [comment]
> 
> 
> I am still having issues myself with this, I can't seem to get any AEs to apply w/o using the nbt method mentioned above.

Do you get this error in console? `Unknown vanilla/custom enchant`

**Comment by LoneDev6** [comment]
I suspect it's not a real enchant, it may be handled by the plugin internally. That's why it's not recognized as a registered Bukkit enchant.

**Comment by LeveledChemist** [comment]
Most likely, I don't get any errors at all in console when i try to use
your suggestion.

**Comment by LoneDev6** [comment]
can you try to run /iatag while holding the custom item generated? send here the result (it's also shown in console)

**Comment by Baterka** [comment]
Plugin in fact giving `[11:12:27 INFO]: [ItemsAdder] Unknown vanilla/custom enchant 'ae_enchantment' for item...` when trying to use AE enchants:

```
enchants:
      - "ae_enchantment:planter:1"
```

**Comment by LoneDev6** [comment]
https://itemsadder.devs.beer/compatibility-with-other-plugins/compatible/advancedenchantments
