### ISSUE TITLE
[BUG] Empty NBT tag (itemsadder: {}) when player clicking on REAL_NOTE blocks

### ISSUE THREAD

**Issue by Feniksovich** [PluginBugs/Issues-ItemsAdder#1063]
**Describe the bug**
When you click RMB with a tool (for example, a pickaxe) on a block, the NBT tag of the tool changes (adding empty array itemsadder{}), after which it is impossible to mine any blocks from IA with this tool.

**To Reproduce**
1. Place custom REAL_NOTE block
2. Click RMB or RMB+Shift on the block with pickaxe
3. Take pickaxe in your hand and run the command `/data get entity @s SelectedItem`
4. See empty array (itemsadder:{}) in NBT tag of pickaxe
5. Try to mine IA block with this pickaxe in survival mode

**Expected behavior**
NBT tool tag should not change / tool with changed NBT tags should be able to break IA blocks.

**Demo**
https://www.youtube.com/watch?v=1YMA8elivsE

**Info (please complete the following information):**
 - Server version: git-Purpur-1149 (MC: 1.16.5)
 - Client version: 1.16.5

**Special Info**
 - ItemsAdder version: 2.4.5
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.13
 - ProtocolLib version: 4.6.0

**Additional context**
Custom block configuartion:
https://paste.lucko.me/6HeX7D4NfY

**Comment by LoneDev6** [comment]
Please try on a server without any other plugin

**Comment by LoneDev6** [comment]
I managed to trigger the issue, thanks.
I'll publish an update to fix this problem.
