### ISSUE TITLE
[BUG] i can not change size image itemadder is game crash

### ISSUE THREAD

**Issue by sinxao** [PluginBugs/Issues-ItemsAdder#1064]
i want change size image brodcast
i change scale_ratio > 9 is game crash
![2564-07-24_00 12 31](https://user-images.githubusercontent.com/87874245/126822405-86858f32-6121-4d3e-9ab0-28ac3739f2f1.png)

**Screenshots**
[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/6870450/latest.log)

 - Server version: paper 1.16.5
 - Client version: TLauncher

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.5
 - LightAPI Fork version:  3.5.2
 - LoneLibs version:1.0.14
 - ProtocolLib version: : 4.7.0

**Additional context**

**Comment by LoneDev6** [comment]
For example if you want to make the time 64x64 you have to resize the image file to 64x64 and don't set any scale_ratio, remove the property.
