### ISSUE TITLE
[BUG] The picture played by iaplaytotemanimation is black

### ISSUE THREAD

**Issue by RuiiiR** [PluginBugs/Issues-ItemsAdder#1066]
**Describe the bug**
The picture played by iaplaytotemanimation is black

**To Reproduce**

**Expected behavior**
Fix display error, I think it is the problem of json generating face

**Screenshots**
[https://i.loli.net/2021/07/25/HzvbKlBgwd8joY6.png](url)

**Info (please complete the following information):**
 - Server version:  purpur1.17.1
 - Client version: fabric 1.17.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.5
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.1-SNAPSHOT-b530

**Additional context**
none

**Comment by LoneDev6** [comment]
black?
what do you mean?

I see it perfectly here in your screenshot
![image](https://user-images.githubusercontent.com/27242001/126957473-bf4b783c-a0c6-4de6-8a51-44a8d508810b.png)
