### ISSUE TITLE
[BUG] ItemsAdder Swapped textures

### ISSUE THREAD

**Issue by Kqmu** [PluginBugs/Issues-ItemsAdder#1067]
**Describe the bug**
When freshly installed on the server all textures look all switched around and wacky especially the blocks, for example. Basically I've never seen this happen before on any servers that Used ItemsAdder but this 1 specfici server it just goes all wacky. any advice would be Much Appreciated!
![image](https://user-images.githubusercontent.com/70139586/126924817-fd126ba3-344e-4f23-9e1b-98648e2e1a59.png)

**Expected behavior**
What is suppose to happen is everything is matching textures etc. (this is after I did the ./iazip and followed the steps) 

**Screenshots**
Example Images
![image](https://user-images.githubusercontent.com/70139586/126924513-bb51d82c-18d9-4d26-a796-e6676c1f2cea.png)
![image](https://user-images.githubusercontent.com/70139586/126924544-50ae7535-a00a-4744-afb0-c0b6f6f6486c.png)

**Info (please complete the following information):**
(MultiCraft type server so I would say Bungeecord but idrk)
(1.17.1)
![image](https://user-images.githubusercontent.com/70139586/126924985-f9b64055-ad3e-41c0-b4dc-dd53e28b774c.png)

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: (example: 2.4.2)
 
![image](https://user-images.githubusercontent.com/70139586/126925082-696ed268-d8dd-4c0b-892c-f28713ab1dee.png)

 - LightAPI Fork version: (example: 3.5.0)
 
![image](https://user-images.githubusercontent.com/70139586/126925132-633b5752-8919-4bbc-acd8-2298f66a82c0.png)

 - LoneLibs version: (example: 1.0.13)
 
![image](https://user-images.githubusercontent.com/70139586/126925200-cd7935ac-6358-47e0-bae5-7a75f7f3c8ea.png)

 - ProtocolLib version: (example: 4.6.0)
![image](https://user-images.githubusercontent.com/70139586/126925254-e3d9cdb9-bb1f-4f5f-9f92-7103aaa5e495.png)

**Additional context**
Plugin LIst
![image](https://user-images.githubusercontent.com/70139586/126925280-46ab2a0f-18ae-4108-9fd6-2a7b0032ca8e.png)

**Comment by LoneDev6** [comment]
Hello,
you have to follow the installation tutorial and host the pack on Dropbox or use the ItemsAdder self-host feature.
This will update your resourcepack and make it perfectly compatible with your server.
https://itemsadder.devs.beer/first-install

Have a nice day
