### ISSUE TITLE
Itemsadder vehicles disappear when you sit on them [BUG] 

### ISSUE THREAD

**Issue by EsissDev** [PluginBugs/Issues-ItemsAdder#1068]
**Describe the bug**
So when a player places a vehicle and they to use them(sit on them) they dissapear, both the player and the vehicle. 

**To Reproduce**
1. Place the vehicle
2. Try to use it (sit on it)

**Expected behavior**
It would let them sit in the vehicle and work.

**Info (please complete the following information):**
 - Server version: (Paper 1.16.5)
 - Client version: (all versions basically)

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: (2.4.2)
 - LightAPI Fork version: (3.5.0)
 - LoneLibs version: (1.0.13)
 - ProtocolLib version: (4.6.0)

**Additional context**
Only happens to users, people with op works normal

**Comment by LoneDev6** [comment]
Update ItemsAdder to the latest version and let me know.
Also update ProtocolLib and LoneLibs.
Thanks!
