### ISSUE TITLE
[BUG] Durability problems of Pear jam jar and Apple jam jar

### ISSUE THREAD

**Issue by Rushia140** [PluginBugs/Issues-ItemsAdder#1069]
**Describe the bug**
Durability shouldn't be lost right away

**To Reproduce**
1. You can see it in the video https://youtu.be/r-UQyRycAcs

**Expected behavior**
The jar does not just disappear, and has durability.

**Screenshots**
 You can see it in the video https://youtu.be/r-UQyRycAcs

**Info (please complete the following information):**
 - Server version: 1.17.1 Airplane/Paper
 - Client version: 1.17.1 Optifine/vanilla

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.6
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Additional context**
The two jars I mentioned above just disappeared when making jam bread,
not with strawberries, it works in such a way.
_Sorry if I said wrong, I used a translator_

**Comment by LoneDev6** [comment]
Thanks!
I made a mistake.
This is the fixed file:
[food.yml.txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/6884293/food.yml.txt)

Rename it to `food.yml` and put it inside `plugins\ItemsAdder\data\items_packs\itemsadder`, then restart

**Comment by LoneDev6** [comment]
@Rushia140  Thanks for contacting me!
I hope you will consider leaving a 5 stars review on my plugin page. It will help me a lot to publish new updates and add new features!
https://www.spigotmc.org/resources/73355/rate?rating=5
Have a nice day :D
