### ISSUE TITLE
Bug with secure resourcepack

### ISSUE THREAD

**Issue by ReformedHooper** [PluginBugs/Issues-ItemsAdder#1070]
Hi, I wanted to secure my resourcepack against anyone stealing it from me, and when I upload files to the dropbox, for example, my assets / minecraft / textures / font folder doesn't work and there's a logo here, but instead of a logo I have a Chinese character here and normally it does it work? Where can be the mistake please? Thanks
![Bez_nazvu](https://user-images.githubusercontent.com/62069758/127227513-aa497ff2-6c15-4f3a-9ed2-9656d76da54f.png)

This is what it looks like when the file is not secure

![Bez_nazvu (1)](https://user-images.githubusercontent.com/62069758/127227553-63086dc2-ff44-4027-94a3-3b025d2944b7.png)

**Comment by LoneDev6** [comment]
Continue on Discord, no need to open another report here.
Thanks
