### ISSUE TITLE
[BUG] on the console sometimes an error appears that I don't know about, when the player join.

### ISSUE THREAD

**Issue by Rushia140** [PluginBugs/Issues-ItemsAdder#1072]
**Describe the bug**
I didn't find a bug, but I see an error popping up in my console.
logs: https://pastebin.com/v4vHLVep

**To Reproduce**
1. sometimes when a player enters an error appears
   error: https://pastebin.com/v4vHLVep
**Expected behavior**
this error should not appear,
moments before I updated to the current version, this error did not appear.

**Screenshots**
![Screenshot (518)](https://user-images.githubusercontent.com/45330419/127309101-8cead0ed-c410-4dd1-99d0-2ec95a04e442.png)

**Info (please complete the following information):**
 - Server version: 1.17.1 Paper/Airplane Fork
 - Client version: Optifine 1.17.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.6
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Additional context**
moments before I updated to the current version, this error did not appear.
this never happened before.
_Sorry if I said wrong, I used a translator_

**Comment by LoneDev6** [comment]
does this happens when you run /iazip or when server is loading and a player joins?

**Comment by Rushia140** [comment]
I don't use that

**Comment by Rushia140** [comment]
maybe when the player loads

**Comment by Rushia140** [comment]
and also i was recently waiting for this reply, i got a new error list https://pastebin.com/hrtfmpNF
I don't know why, but it shows up on my console.

**Comment by SolarPepper** [comment]
I have a similar problem. IA 2.4.5 on two cores paper and purpur

**Comment by LoneDev6** [comment]
Disable this in config.yml
`font_images.scoreboard-teams.enabled`

I'll fix this issue in the next update.



> 
> 
> and also i was recently waiting for this reply, i got a new error list https://pastebin.com/hrtfmpNF
> I don't know why, but it shows up on my console.

Somehow you managed to:
- place a custom block
- edit the config to remove the block attributes, so now the block is a normal item
- then you digged the block

the error basically reports that you're trying to dig an item not a block.
