### ISSUE TITLE
Cannot display textures properly

### ISSUE THREAD

**Issue by xiaosange233** [PluginBugs/Issues-ItemsAdder#1076]
![CXLS31HEF 2NJ5T0B3KM(@U](https://user-images.githubusercontent.com/78241727/127498420-109e6688-7f08-43ca-b237-7cd2e62bceba.png)
![D79HC7~PT_9UUI~}~}%FPL4](https://user-images.githubusercontent.com/78241727/127498433-12c2348e-118b-400b-be69-e1fe4964bc26.png)
![MWC$91{%TS@V7PNFBT1Z6%V](https://user-images.githubusercontent.com/78241727/127498442-ad413260-999b-4e92-a9b9-d8cef3c10648.png)
I seem to have done what needs to be set, but the texture cannot be displayed, and the plug-in has been reloaded

**Comment by LoneDev6** [comment]
Please provide all the asked information, open a new issue report and don't erase the text.
