### ISSUE TITLE
[BUG] Cannot display textures normally

### ISSUE THREAD

**Issue by xiaosange233** [PluginBugs/Issues-ItemsAdder#1077]
I seem to have done what needs to be set, 
but the texture cannot be displayed, and the plug-in has been reloaded

![CXLS31HEF 2NJ5T0B3KM(@U](https://user-images.githubusercontent.com/78241727/127498991-19ddb4b4-f8f3-489d-aea1-7e8c5a6b6d6d.png)
![D79HC7~PT_9UUI~}~}%FPL4](https://user-images.githubusercontent.com/78241727/127499000-7d23f3ad-2252-4dac-a3b3-7c7c3ab5a19e.png)
![MWC$91{%TS@V7PNFBT1Z6%V](https://user-images.githubusercontent.com/78241727/127499009-60355898-aa8a-4cf1-9c47-3da0b047d134.png)

**Comment by 100petr** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1076

**Comment by 100petr** [comment]
but deliberately, is it visible with optifine?

**Comment by LoneDev6** [comment]
@xiaosange233 
You erased the issue template completely.
Please provide all the asked information, open a new issue report and don't erase the text.

This is the second issue report that lacks all the info I asked.
I need everything that is stated in the issue template.

Please don't ignore my questions, I can't help you without cooperation.
