### ISSUE TITLE
[Suggestion] Lightsaber sounds

### ISSUE THREAD

**Issue by ZeonBT** [PluginBugs/Issues-ItemsAdder#1078]
I was playing with the Lightsabers with in my own pack and the itemsadder config and, i've made some really cool models, but i was wondering with the sound is the same sounds for both on/off state. is it possible to spilt them to have to different sounds when you activate the lightsaber and when you turn it off ?

**Comment by LoneDev6** [comment]
sadly no, and i don't think there is a clean way to implement this in the current system

**Comment by SirCraftypants** [comment]
It is possible if you create your lightsabers the way i did it in the video below

[Lightsaber](https://www.youtube.com/watch?v=F6vNXUnxG10)

[Config](https://paste.helpch.at/uyocozugud.cpp)
