### ISSUE TITLE
[BUG] Addon Itemsadder-WorldEdit doesn't support Schematics

### ISSUE THREAD

**Issue by Xiao-MoMi** [PluginBugs/Issues-ItemsAdder#1079]
**Describe the bug**
CustomBlocks( REAL, REAL_NOTE ...) will be broken after //schematic load  //paste
For example REAL_NOTE block will be simple note_block

**Info (please complete the following information):**
 - Server version: purpur-1.17.1-1299
 - Client version: Minecraft 1.17.1 with Optifine G9 pre27

**Special Info**
 - ItemsAdder version: (example: 2.4.4)
 - LightAPI Fork version: (example: 3.5.1)
 - LoneLibs version: (example: 1.0.14)
 - ProtocolLib version: (example: 4.7.1 SNAPSHOT)
 - ItemsAdder-WorldEdit 1.0.3

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/917#issuecomment-855744207
