### ISSUE TITLE
[BUG] Trees spawn on Vines

### ISSUE THREAD

**Issue by Xiao-MoMi** [PluginBugs/Issues-ItemsAdder#1080]
**To Reproduce**
  dragonfruit_tree:
    worlds:
    - world
    chance: 2.0
    max_height: 200
    min_height: 50
    amount: 3
    iterations: 2
    log: forestry:dragonfruit_tree_log
    leaves: forestry:dragonfruit_tree_leaves
    biomes:
    - JUNGLE
    - JUNGLE_EDGE
    - JUNGLE_HILLS
    - MODIFIED_JUNGLE
    - MODIFIED_JUNGLE_EDGE
    - SAVANNA

Screenshot↓↓↓
https://imgtu.com/i/WX2958

Info (please complete the following information):
Server version: purpur-1.17.1-1299
Client version: Minecraft 1.17.1 with Optifine G9 pre27

Special Info
ItemsAdder version: (example: 2.4.4)
LightAPI Fork version: (example: 3.5.1)
LoneLibs version: (example: 1.0.14)
ProtocolLib version: (example: 4.7.1 SNAPSHOT)

**Comment by Xiao-MoMi** [comment]
In addition, trees can also spawn on seagrass and grass

**Comment by LoneDev6** [comment]
Thanks, this will be fixed
