### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by JBramcer** [PluginBugs/Issues-ItemsAdder#1082]
**Describe the bug**
Console flags "Task # 14 for ItemsAdder v2.4.6 generated an exception"
and makes a loop (sorry for my terrible english)

**To Reproduce**
1. install the latest version of  the APIs(LightAPI Fork 3.5.2, LoneLibs 1.0.14, ProtocolLib 4.7.0) on a clean plugin server
2.  install the latest version of the plugin (itemsadder 2.4.6)
3. start the server
4. Scroll down on the console
5. See errors

**Expected behavior**
I open the server console to check if everything is loaded, the world is ready and players can even enter, but itemsadder never lets the files load, and a loop is made, which does not end until I turn off the server

**Screenshots**
![Captura](https://user-images.githubusercontent.com/88307758/127818565-7953c66c-deb9-4af1-a2da-311c6c5846a3.PNG)

**Info (please complete the following information):**
 - Server version: spigot 1.16.2

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.6
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Additional context**

**Comment by LoneDev6** [comment]
Please update your server from 1.16.2 to 1.16.5.

1.16.2  is very old and bugged, no one uses it anymore because 1.16.5 is the latest stable and fixed version of Minecraft 1.16.
