### ISSUE TITLE
[BUG] When you open the door with furniture in your hand, the furniture will disappear

### ISSUE THREAD

**Issue by 28451553** [PluginBugs/Issues-ItemsAdder#1083]
When you open the door with furniture in your hand, the furniture will disappear

**Comment by LoneDev6** [comment]
Please next time don't erase the issue template. In order to identify the issue I need all the info requested.
Thanks for the patience.

I can't reproduce the issue.


https://user-images.githubusercontent.com/27242001/127866686-6ff3c876-879f-4571-88b0-d5dbcd103ea7.mp4
