### ISSUE TITLE
[BUG] lightsaber bug

### ISSUE THREAD

**Issue by ZeonBT** [PluginBugs/Issues-ItemsAdder#1086]
Howdy LoneDev i tired to make my own version of what craftypants done with his lightsabers and found this bug, https://pastebin.com/7z6GXc2z, 

This is my side of the config with the new lightsabers in there, https://pastebin.com/dDvKiMd4

**Comment by LoneDev6** [comment]
@ZeonBT Was this closed because you fixed or because you closed by mistake?

**Comment by ZeonBT** [comment]
yeah i did fix this, I messaged the who made the lightsaber config, we noticed the namespace he had was called "customitems" and for me it should be "itemsadder" as soon as i fixed that, the error stopped and the lightsabers starting to work with the events of the models and the sounds. soz to bother you lone, that's why i closed it  lol

**Comment by LoneDev6** [comment]
Perfect!
