### ISSUE TITLE
[BUG] Can't remove furnitures and vehicles

### ISSUE THREAD

**Issue by Togglerine** [PluginBugs/Issues-ItemsAdder#1087]
**Describe the bug**
I can't remove furnitures and vehicles despite using newest versions of LoneLibs, ProtocolLib and ItemsAdder. 
I don't use "Armor Stand Tools" on my server

**Info**
 - Server version: This server is running Purpur version git-Purpur-1310 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d5017e9 on ver/1.17.1)

**Special Info**

 - ItemsAdder version: 2.4.7
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0 (DevBuild 531 (2021-07-27 06:52:08))

Any ErrorLogs in console
I don't know does problem occures since last version or earlier, but i tried to use other versions of IttemsAdder and problem still existed. 

Thank you for any suggestions

**Comment by LoneDev6** [comment]
When did you install itemsadder did that work fine or not?
I think something installed recently or a change on the server introduced this problem.

It can be another plugin interfering or an entities attack/block break permissions plugin.

Let me know

**Comment by Togglerine** [comment]
I have ItemsAdder from 2 months and everthing was good earlier, but i did lot of updates last week, so...
I will check it and write back.
TY!

**Comment by Togglerine** [comment]
Solved. Problematic plugin was "LootChest"
After remove it everything is ok
Thank you for help once again :D
