### ISSUE TITLE
[BUG] servrer crash java.lang.IllegalArgumentException: y out of range (expected 0-256, got 257)

### ISSUE THREAD

**Issue by taka1945** [PluginBugs/Issues-ItemsAdder#1090]
**Describe the bug**
server crash just got this message
java.lang.IllegalArgumentException: y out of range (expected 0-256, got 257)

**Info (please complete the following information):**
 - Server version: paper 1.17.1 - 157
 - Client version:  java  1.17.1

**Special Info**

 - ItemsAdder version: 2.4.7
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.10.4
 - ProtocolLib version: 5.3.1

**Additional context**
log
https://pastebin.com/05C9FyB0

crash report
https://pastebin.com/60Su2yzF

**Comment by wkurumi** [comment]
1.17 BUG!!!

**Comment by taka1945** [comment]
> 1.17 BUG!!!

Itemsadder downgrade to 2.4.6 now , it seem works normal now.

will report it after more time later.

**Comment by wkurumi** [comment]
> > 1.17 错误！！！
> 
> Itemsadder 现在降级到 2.4.6 ，现在看起来工作正常。
> 
> 稍后将报告它。

OK,thanks

**Comment by taka1945** [comment]
I think it's 2.4.7 bug now, it run normal 18 hours passed  after run server with version 2.4.6 .

**Comment by LoneDev6** [comment]
Would be nice to know which are you configuration for the world_populator.
I think it has a too high max_height set, that's why for sure

**Comment by taka1945** [comment]
> I need to know which are you configuration for the world_populator.
> I think it has a too high max_height set, that's why for sure.
> 
> Anyway, in the next update I will explicitly check the min and max height of worlds since it can be customized in most recent Minecraft versions.

hi, here is my blocks.yml
https://pastebin.com/NySEpZLd

**Comment by LoneDev6** [comment]
This will be fixed in the next update, comment here if it's not fixed after the new update.
I will release the update in some days.

**Comment by a-verk** [comment]
faced the same error, the server crashes constantly on 1.17 version 2.4.7

**Comment by LoneDev6** [comment]
Thanks this will be fixed in the upcoming update, it will be released in some hours, thanks for the patience
