### ISSUE TITLE
[BUG] Crossbow is vertical instead of horizontal

### ISSUE THREAD

**Issue by Agaloth** [PluginBugs/Issues-ItemsAdder#1091]
**Describe the bug**
Title says it.

**To Reproduce**
Use “CROSSBOW” material.

**Expected behavior**
It should be horizontal like vanilla’s.

**Screenshots**
Self-explanatory + seen on discord.

**Info (please complete the following information):**
 - Server version: airplane-purpur 1.16.5
 - Client version: lunar/vanilla 1.16.5

**Comment by LoneDev6** [comment]
Is it possible to get an example configuration for your crossbow?

**Comment by LoneDev6** [comment]
This will be fixed
