### ISSUE TITLE
[BUG] When the trident hits the furniture, the trident will disappear

### ISSUE THREAD

**Issue by 28451553** [PluginBugs/Issues-ItemsAdder#1093]
When the trident hits the furniture, the trident will disappear

**Comment by LoneDev6** [comment]
Please next time provide all the requested information.
Do not delete the whole issue template.
Thanks.

This will be fixed in the next update :D
Have a nice day

**Comment by Caishangqi** [comment]
> Please next time provide all the requested information.
> Do not delete the whole issue template.
> Thanks.
> 
> This will be fixed in the next update :D
> Have a nice day

Okay, I will try that
