### ISSUE TITLE
[BUG] CustomCrafting causes errors on Itemsadder

### ISSUE THREAD

**Issue by Agaloth** [PluginBugs/Issues-ItemsAdder#1094]
**Describe the bug**
Console error spam by itemsadder caused apparently by customcrafting.

**To Reproduce**
Install CustomCrafting
Install Itemsadder 2.4.7
Install LoneLibs 1.0.14

**Expected behavior**
Console error when crafting custom items or whenever (customcrafting crafts)

**Screenshots**
https://pastebin.com/RhMBn33i

**Info (please complete the following information):**
 - Server version: (example: paper 1.16.5)
 - Client version: (example: fabric 1.16.5)

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.7
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.6.1-SNAPSHOT-b501

**Additional context**
I'm currently using customcrafting version 1.6.5.1.4

**Comment by LoneDev6** [comment]
Update customcrafting to 1.7.1.1 and let me know

**Comment by Agaloth** [comment]
I can't update to 1.7.1.1 due to it requiring java 16

**Comment by LoneDev6** [comment]
Did you try it?
Try to update it should work fine even if it's Java 16.
ItemsAdder is compiled using Java 16 but works fine also on Java 8

**Comment by Agaloth** [comment]
I've tested it, it doesn't work under java 16

**Comment by Agaloth** [comment]
talking of customcrafting's update ofc

**Comment by fnrcum** [comment]
I can deny this claim, I am running customcrafting and IA together under Java 16 and it works fine

**Comment by Agaloth** [comment]
> I can deny this claim, I am running customcrafting and IA together under Java 16 and it works fine

Newest version of customcrafting and wolfyutilities doesn’t work under java 16 he even said it in the update post he made.

**Comment by LoneDev6** [comment]
Wait, before you said:
> I can't update to 1.7.1.1 due to it requiring java 16

now
> Newest version of customcrafting and wolfyutilities doesn’t work under java 16 

I'm a bit confused

**Comment by fnrcum** [comment]
I'm a tad confused as well, we are talking about this right?
https://www.spigotmc.org/resources/customcrafting-advanced-custom-recipe-plugin-1-15-1-17-free.55883/

In the latest update dev notes it literally says you NEED java 16
https://www.spigotmc.org/resources/customcrafting-advanced-custom-recipe-plugin-1-15-1-17-free.55883/updates

I currently use this on my server which is paper 1.17.1 under java 16 and i have IA there as well and it works fine so i'm confused what you are talking about.
Maybe i'm talking about the wrong plugin but this is the one that requires Wolfyutils

**Comment by Agaloth** [comment]
> I'm a tad confused as well, we are talking about this right?
> https://www.spigotmc.org/resources/customcrafting-advanced-custom-recipe-plugin-1-15-1-17-free.55883/
> 
> In the latest update dev notes it literally says you NEED java 16
> https://www.spigotmc.org/resources/customcrafting-advanced-custom-recipe-plugin-1-15-1-17-free.55883/updates
> 
> I currently use this on my server which is paper 1.17.1 on java 16 and i have IA there as well and it works fine so i'm confused what you are talking about.
> Maybe i'm talking about the wrong plugin but this is the one that requires Wolfyutils

Yeah that’s the one but the problem is that I’m running on 1.16.5 and not all of my plugins aren’t compatible with java 16 yet

**Comment by fnrcum** [comment]
Aaaaah, you need backwards compatibility to older mc server versions that don't force the need for java 16.
For reference do you have a list of incompatible plugins?
Or have you tried running them with the `--illegal-access=permit` flag? It might allow them to run.

**Comment by Agaloth** [comment]
--illegal-access=permit doesn't work for customcrafting

**Comment by Agaloth** [comment]
lmk if there are any updates on this

**Comment by Agaloth** [comment]
This issue creates craft dupes with itemsadder as mentionned on the issue above

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1104#issuecomment-899374166
