### ISSUE TITLE
[BUG] Can't Place Real Block on 1.17.1

### ISSUE THREAD

**Issue by dabai233** [PluginBugs/Issues-ItemsAdder#1097]
**Describe the bug**
Cant't place any real block

**Info (please complete the following information):**
 - Server version: Tuinity 1.17.1
 - Client version: Fabric 1.17.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: (2.4.8)
 - LightAPI Fork version: (3.5.2)
 - LoneLibs version: (1.0.14)
 - ProtocolLib version: (4.7.0)

**Additional context**
Version 2.4.7 works normally(Tuinity 1.17.1,too,and no error log)
oh,I remember one thing. It can be placed next to the real block already placed in the old version

**Comment by LoneDev6** [comment]
Can you make a video?
Thanks

**Comment by LoneDev6** [comment]
I also need your complete server log

**Comment by dabai233** [comment]
Hi friend,  I send you video/log in discord ticket. Please have a look when you are free

**Comment by LoneDev6** [comment]
Continue on Discord
