### ISSUE TITLE
[Suggestion] real_wire generation

### ISSUE THREAD

**Issue by 100petr** [PluginBugs/Issues-ItemsAdder#1098]
**Describe alternatives you've considered**
For REAL_WIRE, the generation information would be displayed in the gui

**Additional context**
It would be something like ore.
![image](https://user-images.githubusercontent.com/29830635/129169259-d6188e3d-b725-4a07-ad48-571026d0f50a.png)
(chest)
![image](https://user-images.githubusercontent.com/29830635/129169277-18a8d8be-76c0-445a-9ef6-771404d8416a.png)

**Comment by LoneDev6** [comment]
Will be added, thanks
