### ISSUE TITLE
[BUG] REAL_WIRE x REAL_NOTE (BUG)

### ISSUE THREAD

**Issue by TeiBri** [PluginBugs/Issues-ItemsAdder#1099]
** Describe the bug **
When I place a block of type REAL_WIRE on a block of type REAL_NOTE, it becomes a tripwire with all false.

** To Reproduce **
1. Go to server
2. Pick up block type REAL_WIRE
3. Place a block of type REAL_WIRE on a block of type REAL_NOTE

** Screenshots **
Here is the problem:

https://user-images.githubusercontent.com/62265168/129246593-c78428a1-286a-47f0-885a-7e73954baaf6.mp4

Here you can see what happens when I go through it or when I right-click on a block of type REAL_NOTE:

https://user-images.githubusercontent.com/62265168/129246683-556f8d40-1185-4533-8eb7-2b6041cef7fe.mp4

** Info (please complete the following information): **
  - Server version: 1.17.1
  - Client version: 1.17.1 Vanilla

** Special Info **
Please do not write "latest"! Tell us the specific plugin version you are using.
  - ItemsAdder version: 2.4.8
  - LightAPI Fork version: 3.5.2
  - LoneLibs version: 1.0.14
  - ProtocolLib version: 4.7.0

**Comment by LoneDev6** [comment]
Will be fixed, thanks
