### ISSUE TITLE
[BUG] Can't replace REAL_NOTE blocks

### ISSUE THREAD

**Issue by SirGlozz** [PluginBugs/Issues-ItemsAdder#1100]
**Describe the bug**
When i try to replace REAL_NOTE block type using 'replace_near_blocks' action, it doesn't work.
It's weird because it works with REAL mushroom type, but I'd prefer to use REAL_NOTE because it has less bugs when breaking blocks.

**To Reproduce**
1. Place some REAL_NOTE block type
2. Hold some tool with 'replace_near_blocks' action with event 'interact.right' 
3. Block replacement not working when right clicking to the block

**Expected behavior**
I think REAL_NOTE block is canceling something when you interact with it as it does not allow the action of replacing blocks.

**Screenshots**
I have this example, i made working paint brushes that paints wooden planks, i added every plank color to 'from_multiple' list (replace_near_blocks action), but only works with REAL mushroom block type and normal minecraft blocks. In the screenshots color planks are every REAL_NOTE.
![image](https://user-images.githubusercontent.com/77519944/129271007-60bf887f-9e1c-461b-9643-a9e93ec0b102.png)

**Info:**
 - Server version: Paper 1.16.5
 - Client version: Optifine 1.16.5

**Special Info**
 - ItemsAdder version: 2.4.8
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Comment by LoneDev6** [comment]
Did you try using `replace_block`?

**Comment by SirGlozz** [comment]
> Did you try using `replace_block`?
> Use the online editor to get autocompletition of properties:
> https://ide.devs.beer/itemsadder/

Already tried using 'replace_block', and it doesn't work on REAL_NOTE blocks, and besides that you can't use the 'from_multiple' function.
Maybe it's something with 'interact.right', because I tried 'interact.left' and it worked (On 'replace_near_blocks' event).

**Comment by LoneDev6** [comment]
Can you send here what you tried and worked?
I don't really understand your tests

**Comment by LoneDev6** [comment]
I found out the problem, thanks.
This will be fixed in the next update, you will be able to do this correctly:
```yml
    events:
      interact:
        right:
          replace_block:
            from: itemsadder:ruby_block
            to: itemsadder:amethyst_block
            decrement_durability: 0

**Comment by SirGlozz** [comment]
Thanks LoneDev! :)
I tested the new update and replacing REAL_NOTE blocks is working.
Now we can repaint the already painted wooden planks.

![image](https://user-images.githubusercontent.com/77519944/129727739-39e96480-ed15-4950-a97b-17621e9dca9a.png)

**Comment by LoneDev6** [comment]
This is amazing!
I love the idea :D

If you want you can share your addon with the community once you've finished it, people will love it so much

https://addons.devs.beer/itemsadder/

**Comment by SirGlozz** [comment]
> This is amazing!
> I love the idea :D
> 
> If you want you can share your addon with the community once you've finished it, people will love it so much
> 
> https://addons.devs.beer/itemsadder/

Thanks! I will try to make an addon, but first i need to add more blocks like bricks, stone bricks, stone, cobblestone, etc.

**Comment by LoneDev6** [comment]
Amazing :D
