### ISSUE TITLE
[BUG] ERROR

### ISSUE THREAD

**Issue by DarrienNN** [PluginBugs/Issues-ItemsAdder#1101]
**Describe the bug**
After PaperMC update i got this update (Yesterday other plugin also have this error but they fixed it) [LockLogin]

**To Reproduce**
https://pastebin.com/7ZBspyCx

 - Server version: 1.17.1
 - Client version: Mojang Launcher 1.17.1

 - ItemsAdder version: 2.4.8
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Comment by DarrienNN** [comment]
https://pastebin.com/2jquSbwe

**Comment by DarrienNN** [comment]
https://pastebin.com/SA8xh2Qd

**Comment by DarrienNN** [comment]
```
[ERROR] Could not pass event NotePlayEvent to ItemsAdder v2.4.8
[ERROR] Could not pass event PlayerInteractEvent to ItemsAdder v2.4.8
[ERROR] Could not pass event NotePlayEvent to ItemsAdder v2.4.8
[ERROR] Could not pass event BlockPhysicsEvent to ItemsAdder v2.4.7
```

**Comment by DarrienNN** [comment]
https://pastebin.com/MttGmdqM

**Comment by LoneDev6** [comment]
I'll add compatibility to the new Paper version in the next update.
Thanks

**Comment by DarrienNN** [comment]
Alright thanks

**Comment by DarrienNN** [comment]
Hello im not sure if im still allowed to continue this.. 
Theres another error btw
https://pastebin.com/g15wJwmr

**Comment by DarrienNN** [comment]
After i add locklogin i got this problem (Resourcespack also not work)
https://pastebin.com/7Mt8FdMy

**Comment by LoneDev6** [comment]
> 
> 
> Hello im not sure if im still allowed to continue this..
> Theres another error btw
> https://pastebin.com/g15wJwmr

This error is related to the fact that a loot or item failed to load, you surely can get more information in the top part of your log about ItemsAdder loading.



> 
> 
> After i add locklogin i got this problem (Resourcespack also not work)
> https://pastebin.com/7Mt8FdMy

This will be fixed in the next update, thanks. It's a rare issue with some files on Dropbox. I'd use self-host btw: https://itemsadder.devs.beer/plugin-usage/resourcepack-hosting/resourcepack-self-hosting

**Comment by DarrienNN** [comment]
Okay thanks
