### ISSUE TITLE
[BUG] A dark gui

### ISSUE THREAD

**Issue by YKDZ** [PluginBugs/Issues-ItemsAdder#1102]
**Describe the bug**
When I use font images in the GUI created by trmenu, the picture looks like a layer of black.

**To Reproduce**
1. add %img_offset_-16%%img_blank_menu% or something else in trmenu gui's title
2. open that gui

**Expected behavior**

**Screenshots**
![Snipaste_2021-08-14_11-25-53](https://user-images.githubusercontent.com/69898831/129433021-9e8d8a41-7a87-4d40-af83-f33930e868ef.png)

**Info (please complete the following information):**
 - Server version: purpur 1.16.5
 - Client version: fabric 1.16.5 + optfine

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.4
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.1-SNAPSHOT-b531

**Additional context**

**Comment by Xiao-MoMi** [comment]
It's not a bug. Add '&f' in the title...

**Comment by LoneDev6** [comment]
`&f%img_offset_-16%%img_blank_menu%`

`&f` will fix the color problem
