### ISSUE TITLE
[Suggestion] Hide Item Display Name

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-ItemsAdder#1105]
Ability to hide an items Display Name.

I've tried the following

Leaving the display name empty or removing display Name entirely from the items configuration which leaves the item ID instead.

![2021-08-15](https://user-images.githubusercontent.com/66942713/129479518-1650c3d5-1c30-406c-b6c3-bba7586a660f.png)

And trying '' and '&c' as the items display name resulting in this

![2021-08-15 (1)](https://user-images.githubusercontent.com/66942713/129479608-dfe233ea-5c5a-4fb7-8887-bda211584abd.png)

Would be good if there was a way to disable display name completely including the gray holo.

**Comment by LoneDev6** [comment]
It's impossible to completely hide the display name from the item shown in an itemframe, it will still be shown as a small semi-transparent tag

**Comment by SirCraftypants** [comment]
> 
> 
> It's impossible to completely hide the display name from the item shown in an itemframe, it will still be shown as a small semi-transparent tag

Any way to make it transparent?

**Comment by LoneDev6** [comment]
Nope, it's a clientside feature

**Comment by SirGlozz** [comment]
> > It's impossible to completely hide the display name from the item shown in an itemframe, it will still be shown as a small semi-transparent tag
> 
> Any way to make it transparent?

If you change the item name:
`    display_name: '&f:offset_-10:'`
the gray thing will dissapear when you place the item in the item frame.

**Comment by LoneDev6** [comment]
Black magic.
I'm glad you're enjoying my offsets feature
