### ISSUE TITLE
[Suggestion] Ability to place Texture with an Invisible Item Frame

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-ItemsAdder#1106]
Ability to place a Texture with an invisible Item Frame.

Disable Rotate Item ability

Trigger Command on Item Rotate

![2021-08-15 (2)](https://user-images.githubusercontent.com/66942713/129480104-ff2c4822-5feb-4454-856e-1c5d4aad7ad8.png)

**Comment by LoneDev6** [comment]
You can already place it

Create an item, spawn an invisible itemframe, interact with the spot where you have the itemframe to place the item.
For example you can use IA already included icons items.

To get the invisible itemframe item:
`/minecraft:give @p item_frame{EntityTag:{Invisible:1b}}`

**Comment by SirCraftypants** [comment]
> 
> 
> You can already place it
> 
> Create an item, spawn an invisible itemframe, interact with the spot where you have the itemframe to place the item.
> For example you can use IA already included icons items.
> 
> To get the invisible itemframe item:
> `/minecraft:give @p item_frame{EntityTag:{Invisible:1b}}`

I don't want to be giving my players the ability to just spawn invisible item frames at will.

What i'm trying to do is, place 2d textures as invisible item frames.

**Comment by SirCraftypants** [comment]
or maybe a way to use glow_lichen and change its texture

**Comment by LoneDev6** [comment]
You can create a furniture that uses `entity: item_frame` and set it to be placed only on walls.
```yml
placeable_on:
  walls: true
  ```

Check this addon: https://www.spigotmc.org/resources/furniture-itemsadder-more-furniture.93193/

Check the lamps

**Comment by SirCraftypants** [comment]
Yeah I considered that.

Do you think it's possible to use glow_lichen or vines as the material host with a custom texture.

Trying to avoid player using too many armor stands/item frames if possible.

**Comment by LoneDev6** [comment]
Currently I'd avoid using vines as they're resource intensive to be rendered on the client, I had a lot of issues in the past when I had chunks with a lot of vines.
