### ISSUE TITLE
[BUG] ItemsAdder breaks messages of the plugins WorldEdit and WorldGuard.

### ISSUE THREAD

**Issue by Xsasal** [PluginBugs/Issues-ItemsAdder#1109]
ItemsAdder breaks messages of the plugins WorldEdit and WorldGuard. For example: I select the first point, I get a message that the point is selected, then I select the second point and the message of the first point is duplicated for me. But the plugins themselves continue to work, the problem is only in the messages. I started a clean server with WorldGuard, WorldEdit and ItemsAdder, no other plugins.

 - Server version: spigot 1.17.1
 - Client version: vanilla 1.17.1
 - ItemsAdder version: 2.4.8
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Comment by LoneDev6** [comment]
Thanks, this will be fixed in the next update
