### ISSUE TITLE
Addon BetterHud[BUG] 

### ISSUE THREAD

**Issue by Caishangqi** [PluginBugs/Issues-ItemsAdder#1111]
**Describe the bug**
The latest version of Itemsadder lets betterhud be disabled.

**To Reproduce**
1. install BetterHUd
2. install Itemsadder
3. The BetterHUd disabled when loading the plugins

**Expected behavior**
It should work properly with Itemsadder

**Screenshots**
![X99B7WY$MX5YIQ_T2P4XH98](https://user-images.githubusercontent.com/39553613/129845786-093da007-18a9-43f7-b690-3a0450cc3ffe.png)

**Info (please complete the following information):**
 - Server version: paper 1.17.1-195
 - Client version: Optfine 1.17.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.9
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0
 - BetterHUD version: 2.2-b04

**Additional context**
server log: [LOG](https://paste.ubuntu.com/p/qVbd4bkmps/)
The problems occurred when I updated the Itemsadder from v 2.4.8 to v 2.4.9.

**Comment by LoneDev6** [comment]
You have to ask BetterHuds developer to fix this, sadly I can't do anything since BetterHuds is an "hack" for ItemsAdder because it doesn't use the ItemsAdder API but it overrides the HUDs system breaking the builtin one.

Thanks for the patience
