### ISSUE TITLE
Can not place real_block when update to v 2.4.9[BUG] 

### ISSUE THREAD

**Issue by Caishangqi** [PluginBugs/Issues-ItemsAdder#1112]
**Describe the bug**

**To Reproduce**
1. update Itemsadder from 2.4.7 to 2.4.9
2. Place a REAL block, and it would suddenly disappear.
3. Place REAL_TRANSPARENT block  and it works properly
4. There is no error log when the block disappears.

**Expected behavior**
The REAL block should place on the ground.

**Screenshots**
**When Using v 2.4.9**
[Video](https://user-images.githubusercontent.com/39553613/130022345-53f754d6-0745-463b-a266-a68aad2fc7c0.mp4)

**When Using v 2.4.7**
[Video](https://user-images.githubusercontent.com/39553613/130023690-d4af13d2-8e89-452b-b5a0-9629498622cb.mp4)

**Info (please complete the following information):**
 - Server version: paper 1.17.1
 - Client version: Optfine 1.17.1

**Special Info**
 - ItemsAdder version: 2.4.7\2.4.9
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Additional context**
The server with v 2.4.7 [latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/7012433/latest.log)

The server with v 2.4.9 [latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/7012439/latest.log)

**Comment by iBuseWinner** [comment]
Same problem.
Using NewTrees addon https://www.spigotmc.org/resources/trees-newtrees-itemsadder-addon.84604/
Can't place log

**Comment by LoneDev6** [comment]
Thanks this is already fixed in the upcoming update
