### ISSUE TITLE
[Suggestion] LevelledMobs Compatibility

### ISSUE THREAD

**Issue by lokka30** [PluginBugs/Issues-ItemsAdder#1116]
# Problem
[LevelledMobs](https://www.spigotmc.org/resources/levelledmobs.74304/)'s nametags are not being displayed on ItemsAdder mobs

# Intended behaviour
LevelledMobs nametags to appear on ItemsAdder mobs

# Additional context
* I am the developer of LevelledMobs
* We are sending entity metadata packets to display name tags on mobs
* ItemsAdder mobs are being levelled properly, the only issue is that they are not being nametagged by LM
* This issue was brought to my attention by `Xafnir#1337`. I am unable to test it myself since I do not own a license to ItemsAdder

I am unsure if this is a LevelledMobs issue, ItemsAdder issue, both or neither. Regardless, I wish that we can resolve this issue so our two plugins can seamlessly integrate with each other.

Thank you very much. :smiley:

**Comment by fnrcum** [comment]
Yeah I can confirm here that this is the case. The mobs themselves get leveled but the nametags are not displayed

**Comment by LoneDev6** [comment]
Hello!
I'm investigating and I think this would require a complex update, so I will work on it in the next days.
Basically the ItemsAdder entities are invisible (only the skin is shown) so that's why the nametag is hidden. I have to somehow show the nametag even if the entity is invisible and hide it when the player is too far.

**Comment by lokka30** [comment]
> Hello!
> I'm investigating and I think this would require a complex update, so I will work on it in the next days.
> Basically the ItemsAdder entities are invisible (only the skin is shown) so that's why the nametag is hidden. I have to somehow show the nametag even if the entity is invisible and hide it when the player is too far.

Hey, thanks for the reply. :)

I wish to note that LevelledMobs uses packets to send name tags, so ItemsAdder won't be able to tell what nametag LevelledMobs is using. This is probably going to be quite painful to work with, so I'm unsure how any integration will be added yet. I am planning on re-programming LevelledMobs in December to clear the spaghetti and make it far easier for other plugins to integrate - even then, it might be difficult to work with packet nametags.

Secondly, this could be achieved with floating armor stand entities (packet-based of course). I know armor stands are a nuisance for everyone, so I am also unsure how you will fix the issue.

Cheers

**Comment by LoneDev6** [comment]
Thanks for the details!
The issue about using armorstands is that we have to make sure the player is actually near the entity or players can use the nametag this to find mobs underground.

It's a bit of a pain, yea

**Comment by LoneDev6** [comment]
This would require serverside calculation.
Basically we'd have to make a task which checks all the entities for every player and hides the nametag for every single player if the entity is not visible.

This is not a very good thing do to since it can easily increate CPU usage.
There might be a better clientside workaround for that but I'm not aware of any.

**Comment by LoneDev6** [comment]
I have to cite what the LevelledMobs dev said:
> I wish to note that LevelledMobs uses packets to send name tags, so ItemsAdder won't be able to tell what nametag LevelledMobs is using. This is probably going to be quite painful to work with, so I'm unsure how any integration will be added yet

We have to wait them in order to find a solution

**Comment by lokka30** [comment]
In LevelledMobs 4, I'll be adding a basic API which should (fingers crossed) expand in the future. Just taking baby steps to ensure everything is stable 😄. This should be possible in the future to simply fetch the final (fully formatted) nametag that LM wants to set to a mob. There should be an event for it too so plugins can listen to whenever LM wants to change it.
