### ISSUE TITLE
[BUG] 2.4.10 version , unknow error

### ISSUE THREAD

**Issue by ChrisRak** [PluginBugs/Issues-ItemsAdder#1118]
**Describe the bug**
2.4.10 version , unknow error

**To Reproduce**
install the plugin then the error appear

**Expected behavior**
NA

**Screenshots**
https://paste.helpch.at/vasebenugi.cs

**Info (please complete the following information):**
 - Server version: paper 186 1.17.1
 - Client version: fabric 1.17.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.10
 - LightAPI Fork version: NA
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Comment by LoneDev6** [comment]
Does this happen very often? Or only one time?
