### ISSUE TITLE
[BUG] Block place removed nbt

### ISSUE THREAD

**Issue by iBuseWinner** [PluginBugs/Issues-ItemsAdder#1120]
**Describe the bug**
When we breaking REAL block and then trying to place it, block now has standart minecraft texture and name.

**To Reproduce**
1. Download NewTrees addon from spigot
2. Place tree with /iaspawntree orange_tree
3. Break orange log(s)
4. Place orange log(s)
5. Now it's spruce log and you can craft spruce planks

**Expected behavior**
Log(s) must be orange tree's log(s) and not spruce...

**Screenshots**
https://youtu.be/NnOIJUGi_ZQ

**Info (please complete the following information):**
 - Server version: Purpur 1.17.1
 - Client version: Optifine 1.17.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.10
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.10

**Additional context**

**Comment by LoneDev6** [comment]
Thanks, this will be fixed in the next update
