### ISSUE TITLE
[BUG] Unrecognized Character n

### ISSUE THREAD

**Issue by SentixDev** [PluginBugs/Issues-ItemsAdder#1123]
**Describe the bug**
After updating to the latest version loading the texture pack (on join or on /iatexture) leads to this error:
https://pastebin.com/FMkvkKBJ

**To Reproduce**
1. update to v2.4.10
2. restart the server
3. try to load the texture pack

**Expected behavior**
pack should load and apply all updates without breaking something

**Screenshots**
https://please.end-your.life/I4ZmjSqV
https://please.end-your.life/cfUfgTIi

**Info (please complete the following information):**
 - Server version: (example: purpur 1.17.1 build 1335)
 - Client version: (example: fabric 1.17.1)

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: (example: 2.4.10)
 - LightAPI Fork version: (example: 3.5.2)
 - LoneLibs version: (example: 1.0.14)
 - ProtocolLib version: (example: 4.7.1 build 531)

**Additional context**
when joining the server after first restart after update the texture pack url was missing in the config and whole plugin behaved like it just got first installed and going back to previous version doesnt fix the error.

**Comment by LoneDev6** [comment]
Hello, this is a known issue and an update will be released, thanks
