### ISSUE TITLE
[BUG] ChunkLoadEvent lag 1.17.1 - loading custom furnitures

### ISSUE THREAD

**Issue by a-verk** [PluginBugs/Issues-ItemsAdder#1125]
https://timings.pl3x.net/?id=bcceebafc0e6465fb70cbacf6a6365a7
The plugin worked perfectly, the last days I noticed lags and a drawdown of the tps

**Comment by a-verk** [comment]
ver plugin 2.4.11
Updated from 2.4.6 a few days ago

**Comment by LoneDev6** [comment]
It's probably because of this Spigot issue which will hopefully be addressed by Spigot developers in the next updates:
https://hub.spigotmc.org/jira/browse/SPIGOT-6547

**Comment by LoneDev6** [comment]
Anyway I don't see any TPS drop in this log, it's 20 TPS.
Is the game lagging or not?

**Comment by a-verk** [comment]
Previously, the tps was stable at 20, now it jumps constantly from 5 to 20, even 1 extra player leads to a drop in tps

**Comment by a-verk** [comment]
ryzen 3800x
32dd4
and at 15 online, TPP may drop, which was not the case before

**Comment by a-verk** [comment]
tps*

**Comment by LoneDev6** [comment]
Do you have Discord?

**Comment by a-verk** [comment]
yes

**Comment by a-verk** [comment]
VERKME#4364
