### ISSUE TITLE
[BUG] iazip error

### ISSUE THREAD

**Issue by nnKuroneko** [PluginBugs/Issues-ItemsAdder#1126]
![eRROR2](https://user-images.githubusercontent.com/89374465/130417535-42f1e50f-95c4-4b6c-9db9-5f6e7d7d7d04.jpg)

 ProtocolLib last version 
LoneLibs last version
Itemadder last version

**Comment by LoneDev6** [comment]
Please don't post screenshots, send me the error as text.
Anyway one of your json files failed to load because it's corrupted.

I need the full server log to help you.
Have a nice day

**Comment by nnKuroneko** [comment]
That work . thank you for the advice This is my first report, sorry.

**Comment by LoneDev6** [comment]
Don't worry! Feel free to ask for help on my Discord.
