### ISSUE TITLE
[BUG] Reloading PlaceholderAPI breaks %img_<name>% placeholders

### ISSUE THREAD

**Issue by VsevolodEpinetov** [PluginBugs/Issues-ItemsAdder#1133]
**Describe the bug**
If you reload placeholder api it breaks all the placeholders until server restart.

**To Reproduce**
1. Have active placeholders
2. Execute 'papi reload'
3. Placeholders are broken

**Expected behavior**
Obviously, for placeholders to stay intact

**Info (please complete the following information):**
 - Server version: (example: tuinity last build 1.17.1)

**Special Info**
 - ItemsAdder version: (example: 2.4.10)
 - LightAPI Fork version: (example: 3.5.2)
 - LoneLibs version: (example: 1.0.14)
 - ProtocolLib version: (example: 4.7.0)

**Comment by LoneDev6** [comment]
Thanks for the report, I'll fix this in the next days
