### ISSUE TITLE
Stipping Logs [BUG] 

### ISSUE THREAD

**Issue by spiker5032** [PluginBugs/Issues-ItemsAdder#1134]
Describe the bug
Logs with something above them can not be stripped. eg Naturally spawning

To Reproduce
Try stripping log when naturally grown

Expected behavior
Log would strip when right clicked even if it has something above it.

Screenshots
Bug In GIF
https://i.gyazo.com/005824741ee3c895fa2814207bef10b8.mp4

Server version: 1.17.2
Client version: 1.17.2 Fabric

ItemsAdder version: 2.4.12
LoneLibs version: 1.0.14
ProtocolLib version: 4.7.0

**Comment by LoneDev6** [comment]
Thanks, this will be fixed in the next update
