### ISSUE TITLE
Can not use wheat as custom model data[BUG] 

### ISSUE THREAD

**Issue by Caishangqi** [PluginBugs/Issues-ItemsAdder#1135]
**Describe the bug**
I can not give custom model data to WHEAT, the custom item with WHEAT material can not show the texture.

**To Reproduce**
1. Set items that using WHEAT as material
2. give the item texture
3. /iareload
4. /iazip

**Expected behavior**
The items with material: wheat should show the texture

**Screenshots**
This is the items that use PAPER as material
![1DEY)0D `0N$8OR`K1 F7NX](https://user-images.githubusercontent.com/39553613/130705143-2d83ca77-0728-47c8-82d4-c8a69cfc2693.png)

This is the items that use WHEAT as material
![{DIA7XGQ93Y6EJVIX1{ITT](https://user-images.githubusercontent.com/39553613/130705270-96c642a8-bfcb-4fea-9b4d-79ebc6d7c81d.png)

**Info (please complete the following information):**
 - Server version: paper 1.17.1
 - Client version: Optfine 1.17.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.12
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Additional context**
[crops.yml](https://paste.ubuntu.com/p/FQZSQ77b2m/)

**Comment by LoneDev6** [comment]
Thanks, this will be fixed
