### ISSUE TITLE
[BUG] Server restart and no recipes

### ISSUE THREAD

**Issue by iBuseWinner** [PluginBugs/Issues-ItemsAdder#1136]
**Describe the bug**
When we restarting server (/stop and launch again) there is no recipes shows in `/ia` and any item.

**To Reproduce**
1. Stop server
2. Start server
3. Use /iarecipe <any item with recipe>
4. See no recipe
5. Use /iareload
6. See recipe

**Expected behavior**
We need to see recipes after server restart

**Info (please complete the following information):**
 - Server version: Purpur 1.17.1
 - Client version: Optifine 1.17.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.11
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Comment by SirCraftypants** [comment]
To see Recipes a player requires Permissions. Example:

`ia.user.craft.PERMISSION`

So if the Recipes permission is say `permission:customrecipe.emerald_sword` the permission required would be

`ia.user.craft.customrecipe.emerald_sword`

If the player does not have the permission then they can not see the recipe.

**Comment by iBuseWinner** [comment]
> To see Recipes a player requires Permissions. Example:
> 
> `ia.user.craft.PERMISSION`
> 
> So if the Recipes permission is say `permission:customrecipe.emerald_sword` the permission required would be
> 
> `ia.user.craft.customrecipe.emerald_sword`
> 
> If the player does not have the permission then they can not see the recipe.
> 
> https://itemsadder.devs.beer/plugin-usage/permissions

I know it.
Read my message.
I said that after /iareload I see recipes.
Also I have op, so I don't need to give myself that permission.

**Comment by SirCraftypants** [comment]
> 
> 
> > To see Recipes a player requires Permissions. Example:
> > `ia.user.craft.PERMISSION`
> > So if the Recipes permission is say `permission:customrecipe.emerald_sword` the permission required would be
> > `ia.user.craft.customrecipe.emerald_sword`
> > If the player does not have the permission then they can not see the recipe.
> > https://itemsadder.devs.beer/plugin-usage/permissions
> 
> I know it.
> Read my message.
> I said that after /iareload I see recipes.
> Also I have op, so I don't need to give myself that permission.

I did read your message, i know you can see the recipes, i'm talking about have you given your players the right permissions.

For example `category permissions` for a start.

Example `ia.menu.CATEGORYNAME`

Then the specific Recipe permission as stated in my previous message.

**Comment by iBuseWinner** [comment]
> > > To see Recipes a player requires Permissions. Example:
> > > `ia.user.craft.PERMISSION`
> > > So if the Recipes permission is say `permission:customrecipe.emerald_sword` the permission required would be
> > > `ia.user.craft.customrecipe.emerald_sword`
> > > If the player does not have the permission then they can not see the recipe.
> > > https://itemsadder.devs.beer/plugin-usage/permissions
> > 
> > 
> > I know it.
> > Read my message.
> > I said that after /iareload I see recipes.
> > Also I have op, so I don't need to give myself that permission.
> 
> I did read your message, i know you can see the recipes, i'm talking about have you given your players the right permissions.
> 
> For example category permissions for a start.
> 
> Example `ia.menu.CATEGORYNAME`
> 
> Then the specific Recipe permission as stated in my previous message.

Then your answer doesn't make sense. The problem is not because of the permissions.

**Comment by SirCraftypants** [comment]
> 
> 
> > > > To see Recipes a player requires Permissions. Example:
> > > > `ia.user.craft.PERMISSION`
> > > > So if the Recipes permission is say `permission:customrecipe.emerald_sword` the permission required would be
> > > > `ia.user.craft.customrecipe.emerald_sword`
> > > > If the player does not have the permission then they can not see the recipe.
> > > > https://itemsadder.devs.beer/plugin-usage/permissions
> > > 
> > > 
> > > I know it.
> > > Read my message.
> > > I said that after /iareload I see recipes.
> > > Also I have op, so I don't need to give myself that permission.
> > 
> > 
> > I did read your message, i know you can see the recipes, i'm talking about have you given your players the right permissions.
> > For example category permissions for a start.
> > Example `ia.menu.CATEGORYNAME`
> > Then the specific Recipe permission as stated in my previous message.
> 
> Then your answer doesn't make sense. The problem is not because of the permissions.

Lets start from the beginning. 

/iarecipe does not work unless you hold a custom item in your hand while typing /iarecipe or by typing /iarecipe <itemname>

The Recipe Book is /ia, this opens the IA menu with all the categories and recipes.

So if you have not got the permission of the recipe, you can not see the recipe no matter how many times you type /iarecipe or /ia.

I've checked /iarecipe and it's working fine on Paper 1.17.1

If you have given them the recipe permission and they have held the item in their hand and ran /iarecipe then say so and it will be investigated, if this is the case then it could be down to the permission plugin you are using or Purpur.

**Comment by SirCraftypants** [comment]
what permission plugin are you using

**Comment by LoneDev6** [comment]
Hello @iBuseWinner , seems not an issue about permission, I don't know why SirCraftypants thought about it.
Anyway, did you try updating Purpur and ItemsAdder to the latest version?

Do you have any recipes plugin installed which may interfere?

**Comment by iBuseWinner** [comment]
@LoneDev6 
> do you have any recipes plugin installed which may interfere?
Only CMI.

I'll try to update Purpur and IA.

**Comment by LoneDev6** [comment]
Please let me know

**Comment by SirCraftypants** [comment]
> 
> 
> Hello @iBuseWinner , seems not an issue about permission, I don't know why SirCraftypants thought about it.
> Anyway,
> 
>     1. did you try updating Purpur and ItemsAdder to the latest version?
> 
>     2. do you have any recipes plugin installed which may interfere?

Because some permission plugins like permissionsx seem to have issues with enforcing permissions, i've know to date a few users having issues with other permissions plugins and i've directed them all to luckperms because luckperms never has issues.

**Comment by LoneDev6** [comment]
Any news @iBuseWinner  :D
Let me know if I can do anything!

**Comment by LoneDev6** [comment]
Also let me know if 2.4.15 fixed this issue, thanks!
I had recoded part of the recipes loading, so it may be fixed.
