### ISSUE TITLE
[BUG] the resource pack still does not load

### ISSUE THREAD

**Issue by istarengwa** [PluginBugs/Issues-ItemsAdder#1137]
**Describe the bug**
Another new version, and the resource pack still does not load, I even reset the config file thinking that it could come from the

**To Reproduce**
1. restart server
2. activate enabled resource pack
3. connect to server
4. no error no message
5. I use /iatexture
6. result in screen

https://zupimages.net/up/21/34/030p.png

**Screenshots**

config host : https://zupimages.net/up/21/34/djv8.png

**Info (please complete the following information):**
- client version : optifine 1.17.1 or official 1.17.1
- serveur version : purpur-1336 1.17.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.12
 - LightAPI Fork version: none
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Additional context**
Only version 2.4.5 works correctly for loading the player pack, after that none works anymore

**Comment by SirCraftypants** [comment]
when uploading your resource pack, you need to run /iazip first, then /iareload followed by /iatexture or for all players /iatexture all

**Comment by istarengwa** [comment]
I may have expressed myself badly in my bug report, I have been using the plugin since its first version I know this kind of command well, and I apply them to each new content or update of the plugin, this is the first once it doesn't work, just this message to players and nothing else and only on the latest versions, updating the pack doesn't change anything, doing iatexture all just resets the message and doesn't apply the pack

**Comment by SirCraftypants** [comment]
Usually that message appears after someones uploaded an updated resource pack and not run /iareload. I notice you are self hosting but it looks like you have  not setup a port for it, is that correct?

**Comment by LoneDev6** [comment]
server-ip is wrong.
It's not set to your server IP, it's the default setting.

**Comment by istarengwa** [comment]
> server-ip is wrong.
> It's not set to your server IP, it's the default setting.
> 
> Check the video: https://itemsadder.devs.beer/plugin-usage/resourcepack-hosting/resourcepack-self-hosting

Hello, I have always used your plugin, version 2.4.5 allows you to have exactly this ip in the configuration and it works, I am on a dedicated machine

**Comment by LoneDev6** [comment]
It's impossible as 127.0.0.1 means "local machine".
So if you don't have your server inside your house you won't be able to get the resourcepack.

Set `ip:` property to your Spigot server IP address (the one where you have ItemsAdder installed)

**Comment by istarengwa** [comment]
Hello, my toothache makes me stupid, I noticed just after your post that the plugin update completely changed the config.yml and deleted my ip already put in the previous version, sorry for the unnecessary inconvenience = /

**Comment by LoneDev6** [comment]
No need to apologize, what's important is making the plugin working again.
Have a nice day!
