### ISSUE TITLE
[BUG] the blocks takes two times

### ISSUE THREAD

**Issue by 100petr** [PluginBugs/Issues-ItemsAdder#1139]
**Describe the bug**
If I place one IA block, it takes two

**To Reproduce**
1. Go to survival
2. Have 2+ IA blocks
3. Place block
4. It take two instead of one

**Expected behavior**
it will take only one (placed) block

**Screenshots**

https://user-images.githubusercontent.com/29830635/130819953-d03ea42e-74ee-435e-9ef0-75c0506413c4.mp4

**Info (please complete the following information):**
 - Server version: purpur 1.17.1
 - Client version: optifine 1.17.1

**Special Info**
 - ItemsAdder version: 2.4.12
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.1 b530

**Comment by LoneDev6** [comment]
Testing on my latest in-development version and doesn't happen, so I might have fixed it by fixing https://github.com/PluginBugs/Issues-ItemsAdder/issues/1134

**Comment by LoneDev6** [comment]
This happens because you're wearing a backpack, I'll find a solution for this

**Comment by LoneDev6** [comment]
nvm found the real cause
