### ISSUE TITLE
[BUG] `damage_entity_in_sight` action does not affect players

### ISSUE THREAD

**Issue by Maroon28** [PluginBugs/Issues-ItemsAdder#1140]
**Describe the bug**
When putting the damage_entity_in_sight action to any item, it affects regular mobs just fine, but when tested on a player it doesn't work. 

**To Reproduce**
1. Create an item
2. Add the damage_entity_in_sight action to it
3. Put the damage to something very high like 100000
4. Hit a wither, it will die instantly. Test it on a player, and they take regular damage.

**Expected behavior**
The damage should apply to both players and mobs, instead of mobs only.

**Info (please complete the following information):**
 - Server version: Purpur 1.17.1
 - Client version: Fabric 1.17.1 + Sodium 

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.7
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Comment by LoneDev6** [comment]
Thanks!
This will be fixed in the next update
