### ISSUE TITLE
[BUG] Not placing custom block

### ISSUE THREAD

**Issue by SignorPollito** [PluginBugs/Issues-ItemsAdder#1144]
**Describe the bug**
The plugin is not placing a custom block when you have only 1 (amount) item in your hand.
The bug has been tested only with REAL_NOTE and REAL_TRANSPARENT, so it may be affect also the other types.

**To Reproduce**
1. Create a custom block
2. Go in survival mode
3. Place the block when you have only 1 item in the hand

**Expected behavior**
The custom block should be placed even if you have only 1 of it in the hand.

**Screenshots**
https://imgur.com/a/uRIoO1b

**Info (please complete the following information):**
 - Server version: Purpur 1.16.5
 - Java version: 16
 - Client version: Optifine 1.16.4

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: (example: 2.4.12)
 - LightAPI Fork version: (example: 3.5.2)
 - LoneLibs version: (example: 1.0.14)
 - ProtocolLib version: (example: 4.7.0)

**Comment by 100petr** [comment]
maybe it's related to #1139

**Comment by LoneDev6** [comment]
Testing on my latest in-development version and doesn't happen, so I might have fixed it by fixing https://github.com/PluginBugs/Issues-ItemsAdder/issues/1134
