### ISSUE TITLE
[BUG] Solid furnitures not sitable after restart

### ISSUE THREAD

**Issue by Dude42069Nice** [PluginBugs/Issues-ItemsAdder#1148]
**Describe the bug**
hi, i have a problem with solid furnitures, every time server is restarted, every solid furniture is no longer sitable. 
it's true for default "[Furniture] ItemsAdder more furniture 1.0" and any other custom solid sitable furniture

**To Reproduce**
1. Add [Furniture] ItemsAdder more furniture 1.0
2. Place any bench
3. Restart server

**Expected behavior**
After server restar i can still sit on solid furnitures

**Screenshots**
Not applicable

**Info (please complete the following information):**
 - Server version: Purpur 1.17.1
 - Client version: Fabric 1.17.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.12
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Additional context**
Nope

**Comment by LoneDev6** [comment]
This probably will be fixed in the next ItemsAdder update, it was due to a Spigot bug they fixed.
You have to also update Spigot/Purpur.
