### ISSUE TITLE
[BUG] Enchant bug

### ISSUE THREAD

**Issue by jurajplayercze** [PluginBugs/Issues-ItemsAdder#1149]
**Describe the bug**
https://www.youtube.com/watch?v=K4DDLU-bHNQ

That item has options for blocking enchants, but players can bug it like that

**Screenshots**

**Info (please complete the following information):**
 - Server version: 1.17.1
 - Client version: 1.17.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version:  2.4.12
 - LightAPI Fork version: 
 - LoneLibs version: 
 - ProtocolLib version:

**Additional context**
I think everything is well described in video

**Comment by LoneDev6** [comment]
I also need your item yml configuration to reproduce the issue correctly.
Thanks

**Comment by LoneDev6** [comment]
Anyway this will be fixed in the next update
