### ISSUE TITLE
[BUG] Liquid physics not updated when breaking using hammers

### ISSUE THREAD

**Issue by Steamox** [PluginBugs/Issues-ItemsAdder#1150]
**Describe the bug**
When a player mines with a hammer, if a block holding lava is destroyed by the hammer like this :

XXXYX
XPPPX
XPPPX
XPPPX
XXXXX

Or :

Y = Lava source
X = Block
P = block destroyed by the hammer

The lava will not flow and will remain in the air

**To Reproduce**
1. Take a hammer
2. Mine under the lava
3. See the error

**Expected behavior**
The lava flow

**Screenshots**
![2021-08-30_15 48 36](https://user-images.githubusercontent.com/60044348/131398902-afb00d9c-e578-4a77-ab3e-eab617118ee2.png)

**Info (please complete the following information):**
 - Server version: Purpur 1.17.1
 - Client version: 1.17.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.8
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 1.7.1 snapshot b531

**Comment by 100petr** [comment]
#289

**Comment by LoneDev6** [comment]
Hello!

As I said in the other issue report:
> I don't think I will fix this because this "bug" is intentional.
I don't update physics of blocks to avoid lag

Do you think it's worth risking to make the plugin laggy to fix this "bug"?
I need an opinion on this, I'd prefer to keep the plugin not laggy

**Comment by Steamox** [comment]
Hello ! 

Maybe give the choice in the config? 

I admit that this is a concern on my side but maybe there is another solution than updating the physics of the blocks?

**Comment by LoneDev6** [comment]
> 
> 
> Hello !
> 
> Maybe give the choice in the config?
> 
> I admit that this is a concern on my side but maybe there is another solution than updating the physics of the blocks?

Sadly no. Updating physics may also introduce bugs for the custom blocks, because updating physics blocks is okay but if a custom block is near it will bug out.
For now I'll leave this as "Complex to implement", in the future I may find a way to address this without lag and without introducing bugs, but I doubt.

Thanks for the patience
