### ISSUE TITLE
[BUG] Itemframe Multiblock Furniture Not Rotating with model.

### ISSUE THREAD

**Issue by Celticism** [PluginBugs/Issues-ItemsAdder#1151]
**Describe the bug**
itemframe based barriers dont rotate with the furniture model. I noticed this when I tried making a 2x1 furniture.

**To Reproduce**
1. Make a 2 length or width furniture using itemframe entity and try rotating it. Only half of the barrier will be inside the model while the other half will be always to the side and wont rotate with the model.

**Expected behavior**
The furniture models blocks were supposed to be able to rotate with the model. Only the model rotated when I tried making 2x1 solid block furniture. (2 Sidebyside barriers) The barriers didnt rotate with the model. I was using the itemframe entity because I wanted to make the pixels to scale with ingame blocks and the armorstand doesnt seem to scale the same its always off a bit even if I make changes in blockbench etc.
**Screenshots**
![image](https://user-images.githubusercontent.com/84742331/131594983-50022cfa-c5c7-4183-a969-ccc33a44f822.png)

**Info (please complete the following information):**
 - Server version: Spigot 1.17.1
 - Client version: 1.17.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.12
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Additional context**

**Comment by LoneDev6** [comment]
Send me screenshots of the furniture while having `/iahitbox` enabled

Thanks

**Comment by Celticism** [comment]
![2021-09-02_15 07 56](https://user-images.githubusercontent.com/84742331/131902291-7655576b-12df-4bb4-86e8-0c2b8a95f821.png)

**Comment by Celticism** [comment]
![2021-09-02_15 10 03](https://user-images.githubusercontent.com/84742331/131902503-85d3e220-e309-4594-af57-8bb81e07eedf.png)
north

**Comment by Celticism** [comment]
![2021-09-02_15 10 41](https://user-images.githubusercontent.com/84742331/131902576-efbee596-d96b-445d-bfdd-fa6f2082ceaa.png)
west

**Comment by Celticism** [comment]
![image](https://user-images.githubusercontent.com/84742331/131903318-585d46b9-a74e-4765-adbe-3383751bcad4.png)
yml wouldnt upload this is what my yml looks like i can copy paste it to you over discord dms if you want richmister101#9767

**Comment by LoneDev6** [comment]
Contacted on Discord
