### ISSUE TITLE
[BUG] Vehicles placing on Slabs but not Blocks

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-ItemsAdder#1153]
OK everything has been fine and i've not added any new plugins since 1.16.5 other than 1 plugin named CreativeItemControl.

Up until today i was on Itemsadder 2.4.7. Logged on this morning and tried to place a new Vehicle i created on Blocks but as soon as i placed it, it unplaced itself and returned to its floating item state. I then placed the same Vehicle on slabs and it placed ok.

So i checked Worldguard regions and everything's setup fine, i did all the above in the exact same location. I am opped.

So i removed the last 2 plugins i installed on the server, Armorstand Tools and CreativeItemControl and restarted the Server, no change.

All my Vehicles sit height are set to 0 but this also happens with Itemsadders default Vehicles.

I've checked my furniture and they are fine, this is only affecting Vehicles being placed on Blocks, not Slabs.

Very strange.

 - Server version: Paper 1.17.1
 - Client version: MC 1.17.1

 - ItemsAdder version: 2.4.12
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0 #531

I've updated to 2.4.12 but no change.

No Errors in Console.

**Comment by LoneDev6** [comment]
Provide one of the vehicles yml configuration so that I can test, I can't manage to reproduce the issue with IA default go carts.
They can be placed correctly without any issue.
`This server is running Purpur version git-Purpur-1370 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cdbf59d on ver/1.17.1)`


https://user-images.githubusercontent.com/27242001/131885606-f2a3e3bd-51e4-4039-865b-3f56acc56a23.mp4

**Comment by SirCraftypants** [comment]
The issue there is the Car actually place on slabs, just not on blocks. 

https://paste.helpch.at/anomiyeros.sql

Mine are also Paper, only difference is mines set at sit 0

**Comment by SirCraftypants** [comment]
sorry wrong vehicle config https://paste.helpch.at/izidaxayik.makefile

**Comment by LoneDev6** [comment]
I have no idea what could be the cause, it works fine on `This server is running Purpur version git-Purpur-1370 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cdbf59d on ver/1.17.1)`

`Plugins (30): EpicBackpacks, EpicRename, Essentials, ItemsAdder, LibsDisguises, LightAPI, LoneDevCheck*, LoneLibs, LuckPerms, Mimic, Multiverse-Core, Multiverse-Portals, MythicMobs, PlaceholderAPI, PlugMan*, PocketMobs, ProtocolLib, RPGBank, RPGMoney, Scoreboard-revision*, ScratchIt, ScreenEffects, ServerBooster, Vault, ViaBackwards, ViaRewind, ViaVersion, WolfyUtilities, WorldEdit, WorldGuard`

https://user-images.githubusercontent.com/27242001/131887417-162db0f0-f0fa-4a33-bbd1-950b6831e4e3.mp4

**Comment by SirCraftypants** [comment]
Ah there's one plugin i forgot i added recently, it's Mypets 1.17.1, let me remove it and see what happens.

**Comment by SirCraftypants** [comment]
No, no change, still the same, this is messed up.

**Comment by SirCraftypants** [comment]
Even more messed up, i just spammed the vehicle around on different blocks and some refuse but others place.

Only big change that's occurred is the new essentialsX

**Comment by SirCraftypants** [comment]
Removed all plugins accept for 

Itemsadder and it's dependencies, essentialsx and multiverse.

Still happening. 

Reverting from 2.4.12 back to 2.4.7 and it's still happening

Another user has reported the same issue here https://github.com/PluginBugs/Issues-ItemsAdder/issues/1051

And this morning another user reported the same issue here https://discord.com/channels/533407895010803753/533413171403292712/883944497581555732
