### ISSUE TITLE
[BUG] Server crashing

### ISSUE THREAD

**Issue by user0347** [PluginBugs/Issues-ItemsAdder#1156]
**Describe the bug**
Server crashes after 'x' amount of time

**To Reproduce**
1. Start server
2. Let it run
3. Crash

**Expected behavior**
For no crash to occur

**Info (please complete the following information):**
 - Server version: git-Purpur-1320 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: b0f2151 on ver/1.17.1)

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.7
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Additional context**
crash-report: https://pastebin.com/e76mWE3y
latest log: https://pastebin.com/xMMnzy56

**Comment by 100petr** [comment]
Update IA, fixed in 2.4.9
