### ISSUE TITLE
[BUG] Crafting IA items can sometimes dupe items

### ISSUE THREAD

**Issue by FokaStudio** [PluginBugs/Issues-ItemsAdder#1159]
**Describe the bug**
 Crafting IA items while can sometimes dupe items by like 900 times (can lead to full inventories being quickly filled up)

**To Reproduce**
1. Go and prepare any IA recipe that results in multiple items being crafted (like e.g. rubies from ruby block)
2. Prepare the recipe **twice** (like you would want to quickly make 2 of smth)
3. Press click the result slot

**Expected behavior**
Recipe working was expected, but we got mutlitplied item and the input staying in the grid

**Screenshots**
https://file.coffee/u/Q0ePN-qK3O3nVu.mp4

**Info (please complete the following information):**
```
This server is running Purpur version git-Purpur-1375 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: e444ad7 on ver/1.17.1)
You are 1 version(s) behind
Previous version: git-Purpur-1370 (MC: 1.17.1)
```
 - Client version: Vanilla 1.17.1
**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.12
 - LightAPI Fork version: *absent*
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Additional context**
X

**Comment by FokaStudio** [comment]
Forgot to mention - on the video, first 2 crafting sessions are whem SHIFT is pressed to transport straight to inv, last one has nothing other than left mouse button being pressed repeatedly

**Comment by LoneDev6** [comment]
@FokaStudio 
Please read here and let me know if it's the case.
https://itemsadder.devs.beer/compatibility-with-other-plugins/not-compatible

![immagine](https://user-images.githubusercontent.com/27242001/132250773-3ff78860-75d3-465e-9808-de3bcd3848ba.png)

**Comment by FokaStudio** [comment]
```
Plugins (45): AureliumSkills, Citizens, ColorBundles, ColoredEnderChests, Denizen, DiSky, ExoticGarden, ExtraGear, FarmControl, GoatHorn, GriefPrevention, HeadDatabase, HolographicDisplays, ItemsAdder, LibsDisguises, LightAPI, LoneLibs, LuckPerms, MorkazSk, OpenAudioMc, PlaceholderAPI, PlayerParticles, ProtocolLib, Reqn*, Shopkeepers, SkBee, Skellett, SkImage*, SkJade, SkQuery, skRayFall, Skript, skript-gui*, Skript-Packet*, skript-placeholders*, skript-reflect, skript-yaml, SkriptJSON*, Slimefun, SoulJars, TAB, Tweakin, Votifier, WorldEdit, WorldGuard
``` No CraftEnchance, but those are my plugins, maybe this will help

**Comment by LoneDev6** [comment]
Disable 5 plugins at time (copy the jars in another temporary folder), restart the server and check until the bug disappears.
That's the only way, that's what I'd do on my server to find out the cause.

Let me know which plugin was so that I can try to add compatibility or ask the developer for more information.

Thanks

**Comment by FokaStudio** [comment]
Idk how, but it fixed itself 😳
