### ISSUE TITLE
[Suggestion] make Cooking GUI more peautiful

### ISSUE THREAD

**Issue by minecraft-dripdrop** [PluginBugs/Issues-ItemsAdder#1160]
**Is your feature request related to a problem? Please describe.**
Can you move the Furnace icon here to let GUI more peautiful?

and maybe the menu size be 5*9?
![QQ图片20210905114529](https://user-images.githubusercontent.com/62246956/132114450-a2d8e761-92c5-4f60-bad6-9937fd50c3e0.png)

**Describe the solution you'd like**
The best way is make ia_gui.yml have more configuration files,so we can decide the slot place,the menu size and so on

**Comment by LoneDev6** [comment]
Will be solved with that:
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1669
