### ISSUE TITLE
[BUG] Duplication of Slimefun items - REAL_NOTE blocks interaction

### ISSUE THREAD

**Issue by istarengwa** [PluginBugs/Issues-ItemsAdder#1162]
Description (Required)
Hello hello, I am explaining the current bug, which is really annoying at the time, and I do not know if the error came from you or from slimefun.

In fact, if a player puts a slimefun object in his left hand and nothing in his right hand, that he types with the right hand empty an itemsadders block, this duplicates the slimefun object held in his left hand ad infinitum, with all his content if it is a backpack.

I created a ticket on the lonedev discord which told me:

"LoneDev — 31/05/2021
did you try contacting slimefun devs about that? i don't drop items on blocks interact
they probably are not checking if the block break event is cancelled or their blockbreak event priority is not set to MONITOR"

Video: https://cdn.discordapp.com/attachments/849633185003733023/849633251550691369/2021-05-31_01-40-41_Scene_Trim.mp4

Environment 
Minecraft Version: purpurclip-1149
Slimefun Version: Dev 928 (git cccf6)
ItemsAdder: 2.4.12

Hello I am redoing this ticket here because apparently they cannot or cannot help me there, I just copied and pasted my ticket there but the problem remains the same except that now a simple right click while holding in right hand is enough to do the duplication and that on any item adders block with any slimefun object, if anyone other than me has this problem or we managed to solve it I beg you to me please help !!!!

**Comment by 100petr** [comment]
You didn't answer us there. https://github.com/Slimefun/Slimefun4/issues/3100#issuecomment-908484058 
"have you only tried it with IA (and the necessary plugins) and sf?"

**Comment by istarengwa** [comment]
> You didn't answer us there. [Slimefun/Slimefun4#3100 (comment)](https://github.com/Slimefun/Slimefun4/issues/3100#issuecomment-908484058)
> "have you only tried it with IA (and the necessary plugins) and sf?"

hello, I must have missed the question, excuse me, yes I only tested it with "slimefun / lonelibs / itemsadder / protocolib"

**Comment by 100petr** [comment]
and can you write me the type of block which block it does? I also use purpur and I don't have this problem.

**Comment by istarengwa** [comment]
I just tried with the fork paper and the problem is still there.

**Comment by istarengwa** [comment]
> and can you write me the type of block which block it does? I also use purpur and I don't have this problem.

with REAL_NOTE blocks

**Comment by LoneDev6** [comment]
> 
> 
> > You didn't answer us there. [Slimefun/Slimefun4#3100 (comment)](https://github.com/Slimefun/Slimefun4/issues/3100#issuecomment-908484058)
> > "have you only tried it with IA (and the necessary plugins) and sf?"
> 
> hello, I must have missed the question, excuse me, yes I only tested it with "slimefun / lonelibs / itemsadder / protocolib"
> 
> I use purpur for fork (purpurclip-1378) https://ci.pl3x.net/job/Purpur/1378/
> 
> another example video with left click on block :
> 
> https://cdn.discordapp.com/attachments/638870738002247681/885870276791894026/2021-09-10_14-47-42_Scene.mp4

I have no idea of why this could happen.
It seems to be something to do with Slimefun itself.
Can you ask the Slimefun developers to join this conversation?


Thanks

**Comment by istarengwa** [comment]
> > > You didn't answer us there. [Slimefun/Slimefun4#3100 (comment)](https://github.com/Slimefun/Slimefun4/issues/3100#issuecomment-908484058)
> > > "have you only tried it with IA (and the necessary plugins) and sf?"
> > 
> > 
> > hello, I must have missed the question, excuse me, yes I only tested it with "slimefun / lonelibs / itemsadder / protocolib"
> > I use purpur for fork (purpurclip-1378) https://ci.pl3x.net/job/Purpur/1378/
> > another example video with left click on block :
> > https://cdn.discordapp.com/attachments/638870738002247681/885870276791894026/2021-09-10_14-47-42_Scene.mp4
> 
> I have no idea of why this could happen.
> It seems to be something to do with Slimefun itself.
> Can you ask the Slimefun developers to join this conversation?
> 
> Thanks

Hello LoneDev, I have already opened the same ticket on the slimefun github, I expect more response from them, here is the link:

https://github.com/Slimefun/Slimefun4/issues/3100

**Comment by LoneDev6** [comment]
https://github.com/Slimefun/Slimefun4/issues/3100#issuecomment-925683358
> 
> 
> > @LoneDev6 looks like you might've been right about your NMS code
> 
> Very good, I hope it's the issue so it's "easier" for me to fix since I've already identified the possible cause.
> I'll fix this in the next days
