### ISSUE TITLE
[Suggestion] Restrict item in certain worlds

### ISSUE THREAD

**Issue by Akiranya** [PluginBugs/Issues-ItemsAdder#1165]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

I'd like to restrict a item that it only can be used in certain worlds. Pretty much like the world option for HUDs:

```
info:
  namespace: "realcraft"
huds:
  thirst_bar:
    enabled: true
    world:
      - world
```
Also, I'd like to customize the message sent to players when they try to use the item in prohibited worlds.

**Describe alternatives you've considered**

1. For now I'm trying to use world-specific permission because IA does support setting permission for items.
2. Also, I've considered a plugin called BanItems which can restrict the item in certain worlds.

Both should work but not quite elegant .. 

For solution 1, the message promping to player is not quite friendly as what a player sees is a permission message. What if we restrict the item in certain worlds because it's part of the gameplay like MMORPG? the message should make sense instead of just a permission message.

For 2, it works and it supports custom message but it's a bit of heavy solution as BanItems can do much more than just restricting worlds. I'm reluctant to add something that I don't actually need to my servers and I believe other people think so more or less.

**Additional context**

**Comment by LoneDev6** [comment]
You can use BanItem, it has complete ItemsAdder support.
https://itemsadder.devs.beer/compatibility-with-other-plugins/compatible/banitem

Just hold an item in your hand and run /banitem add (for the various events)
