### ISSUE TITLE
[BUG] [........ ERROR]: [org.bukkit.craftbukkit.v1_17_R1.util.CraftMagicNumbers] null

### ISSUE THREAD

**Issue by vdl19** [PluginBugs/Issues-ItemsAdder#1170]
**Describe the bug**
Hello, when the server starts from version 2.4.13 and also 2.4.14 I have in the console these errors:

[ERROR]: [org.bukkit.craftbukkit.v1_17_R1.util.CraftMagicNumbers] null

[ERRORS raftMagicNumbers.txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/7137449/ERRORS.raftMagicNumbers.txt)

**Screenshots**

![image](https://user-images.githubusercontent.com/80985545/132706481-28bd8ccf-d22c-4c05-9c65-06980ae9594c.png)

**Info (please complete the following information):**
 Minecraft PaperSpigot 1.17.1 #255

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
ItemsAdder version: 2.4.14
LightAPI Fork version: 3.5.2
LoneLibs version: 1.0.14
ProtocolLib version: ProtocolLib #531 (27 juil. 2021 06:52:08) 
LibsDisguises 10.0.26-SNAPSHOT #992"

**Comment by LoneDev6** [comment]
Does this happen on every reload?
Or only after the first start after the update?

**Comment by LoneDev6** [comment]
Are you running the latest LibsDisguises?

**Comment by vdl19** [comment]
Hello,
- It's doing this after every server reboot since 2.4.13 and then 2.4.14 before I never had it. 
- It doesn't seem to do it after /iareload or /iazip or /iatexture all
- Yes, as mentioned, I have the latest version: LibsDisguises 10.0.26-SNAPSHOT #992"

I just restarted here are the captures :

![image](https://user-images.githubusercontent.com/80985545/132853256-bd864842-c70e-4e31-bf29-4bb0bb4b99ac.png)

![image](https://user-images.githubusercontent.com/80985545/132853339-b707c813-53e1-45d1-9677-b04e5aaac9d8.png)

**Comment by LoneDev6** [comment]
Thanks for the report.
I'll fix this in the next update but keep in mind that old spawned mobs will still throw this error.
You have to kill them using /iakill command

**Comment by vdl19** [comment]
Hello, ok thanks
I tested /iakill all but it only does it on loaded chunks, so considering the size of the worlds I don't see myself doing it everywhere. Is there any other way to disable them all, like disabling ItemsAdder at a server startup and then restarting it at the next one. I'm not sure if it makes any difference!

**Comment by LoneDev6** [comment]
you can **stop the server** and delete the mob storage `plugins\ItemsAdder\storage\mobs` (important: stop the server before).
then start it again

**Comment by vdl19** [comment]
Ok thanks great it will be easier.
