### ISSUE TITLE
[BUG] "Restoration Table" that lets you see inside the floor

### ISSUE THREAD

**Issue by vdl19** [PluginBugs/Issues-ItemsAdder#1171]
**Describe the bug**
An invisible "Restoration Table" that lets you see inside the floor. I have not yet put the table of restoration for my players, I began to look at it this morning, I had put one in this place there. I just saw that it became invisible and moreover it allows to see through the floor, on the other hand if I put others they are normal. I tried to disconnect and reconnect, to restart the server also 2 times to see if the ones I put next to it were doing the same, but they were all normal except this one. 
If you right click on it it works correctly!
I can't give any manipulation for the moment which would allow to reproduce the bug, I can just show it.

**Screenshots**

![image](https://user-images.githubusercontent.com/80985545/132713291-ca6284e3-1128-4511-aaa8-131e3f382d9d.png)

![image](https://user-images.githubusercontent.com/80985545/132713324-feca9963-d30b-4e49-a8a3-4c0c85566fcf.png)

![image](https://user-images.githubusercontent.com/80985545/132713799-9622332e-7292-423e-8ec0-2dc3904103f1.png)

Info (please complete the following information):
Minecraft PaperSpigot 1.17.1 #255

Special Info
Please do not write "latest"! Tell us the specific plugin version you are using.
ItemsAdder version: 2.4.14
LightAPI Fork version: 3.5.2
LoneLibs version: 1.0.14
ProtocolLib version: ProtocolLib #531 (27 juil. 2021 06:52:08)
LibsDisguises 10.0.26-SNAPSHOT #992"

**Comment by vdl19** [comment]
Next, I was in front of the invisible block (hole) I put myself in survival and there! The block disappeared and a block of earth remained on the ground!

![image](https://user-images.githubusercontent.com/80985545/132714080-d7b9491f-fd7e-46fd-a375-4ead9a85c76a.png)

**Comment by LoneDev6** [comment]
This might be because of some reasons:
1. you're in gamemode creative 
2. the blocks were placed with version 2.4.13 which had a bug about blocks saving and it might have triggered this issue

I'm sure it won't happen on placed blocks in survival gamemode


if it happens... it's something to do with your configuration, I need more information to detect the issue.

https://user-images.githubusercontent.com/27242001/132852099-e90ed826-427f-486d-af01-d2d0a812560b.mp4
