### ISSUE TITLE
[BUG] Attribute modifiers error 

### ISSUE THREAD

**Issue by yebanme** [PluginBugs/Issues-ItemsAdder#1172]
**Describe the bug**
attribute_modifiers:
  head:
    maxHealth: 2

The effect of maxHealth in the game is opposite to the configuration. The actual effect of using maxHealth: 2 is health minus 2. The actual effect of using maxHealth: -2 is health plus 2. 
But the attributes on the item are displayed and configured correctly 

**To Reproduce**
1. Add maxHealth attribute to armor
2. Wear 
3. See error

**Expected behavior**
The actual effect of the armor is the same as the configuration 

**Screenshots**

**Info (please complete the following information):**
 - Server version: paper 1.17.1
 - Client version: fabric 1.17.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.14
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Additional context**
```java  obsidian_legs:
    display_name: '&fobsidian legs'
    permission: Commongoods
    resource:
      generate: true
    durability:
      max_custom_durability: 855
    specific_properties:
      armor:
        slot: legs
        color: '010002'
    attribute_modifiers:
      legs:
        maxHealth: -2`

**Comment by LoneDev6** [comment]
I don't really understand the issue.
ItemsAdder is correctly setting the Vanilla AttributeModifier max_health to `-2` as specified in the config.
Maybe there is a plugin interfering?


## -2
As you can read using `/iatag` command
```
AttributeModifiers:[{Name:"itemsadder",Amount:-2.0d,Operation:0,UUID:[I;1743622743,337005294,-1376904637,-199145526],Slot:"legs",AttributeName:"minecraft:generic.max_health"}]
```
![immagine](https://user-images.githubusercontent.com/27242001/132849892-9bb46df7-d9d8-4b4f-9f7f-85e778775615.png)
![immagine](https://user-images.githubusercontent.com/27242001/132849903-161459c3-e214-4715-80b4-24c469d2a0d9.png)



## 2
As you can read using `/iatag` command
```
AttributeModifiers:[{Name:"itemsadder",Amount:2.0d,Operation:0,UUID:[I;1743622743,337005294,-1376904637,-199145526],Slot:"legs",AttributeName:"minecraft:generic.max_health"}]
```
![immagine](https://user-images.githubusercontent.com/27242001/132850262-98b9a865-6629-4243-9b78-94fca4e7a672.png)
![immagine](https://user-images.githubusercontent.com/27242001/132850278-ba44ede3-c3da-4bdd-95f7-bbd62bd1a708.png)


More info on attributes: https://minecraft.fandom.com/wiki/Attribute#Attributes_available_on_all_living_entities
