### ISSUE TITLE
[BUG] reattach vehicle bug

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-ItemsAdder#1173]
[09:22:37 WARN]: Couldn't reattach entity to player

Whilst still being in your vehicle, if you log out and then back in again, your vehicle is destroyed.

1. sit in Vehicle
2. log out
3. log in 
4. see vehicle gone.

Expect to see Vehicle to be reattached/survive.

 - Server version: (example: paper 1.17.1)
 - Client version: (example: fabric 1.17.1)

 - ItemsAdder version: 2.4.13
 - LightAPI Fork version:  3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0 #531

**Comment by LoneDev6** [comment]
I cannot reproduce it, it may be another plugin removing the vehicle on logout
