### ISSUE TITLE
Font's default.json resets with /iazip [BUG] 

### ISSUE THREAD

**Issue by Agaloth** [PluginBugs/Issues-ItemsAdder#1174]
**Describe the bug**
The default.json file breaks itself when doing /iazip

**To Reproduce**
1. Add images but don't use itemsadder to add them (add them manually with font/default.json
2. /iazip
3. The default.json will get broken because of it

**Expected behavior**
Normal default.json that I'm trying to run: https://pastebin.com/n0XtgkvQ
What happens when I do /iazip: https://pastebin.com/dbhDn8Tw

**Info (please complete the following information):**
 - Server version: Airplane-Purpur: 1.16.5 (https://ci.tivy.ca/view/Purpur/job/Airplane-Purpur-1.16/)
 - Client version: Optifine 1.16.5 (lunar client)

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.14
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.6.1-SNAPSHOT-b501

**Comment by LoneDev6** [comment]
You're not supposed to manually add textures into the default.json file, if I allow it I would get countless amount of support tickets about that since the pack would become unstable.

If you explain what you're trying to do I might help you in the Discord server.
