### ISSUE TITLE
[BUG] Error when I break a real_string

### ISSUE THREAD

**Issue by darkdragon0226** [PluginBugs/Issues-ItemsAdder#1175]
**Describe the bug**
when I break a real_string already generated in the world I get this error in console

**PasteBin**
https://pastebin.com/1E8VGHE8

**Info (please complete the following information):**
 - Server version: (example: purpur1.17.1)

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: (example: 2.4.14)
 - LightAPI Fork version: I don't use it as purpur is not supported
 - LoneLibs version: (example: 1.0.14)
 - ProtocolLib version: (example: 4.7.0)

**Comment by LoneDev6** [comment]
Do you have any custom datapack installed?
Anyway "purpur1.17.1" is not enought, I need the full server, get it using /version and make sure it's the latest.

**Comment by LoneDev6** [comment]
I think this is a Spigot bug, somehow the biome fails to be obtained when I call `block.getBiome()`.
Maybe it's a custom biome?

**Comment by darkdragon0226** [comment]
version: Purpur version git-Purpur-1377 (MC: 1.17.1) 
I use a datapack (william wythers overhauled overworld)

**Comment by LoneDev6** [comment]
Does it contains custom biomes?

**Comment by darkdragon0226** [comment]
just modify vanilla biomes

**Comment by darkdragon0226** [comment]
hi, I missed a thing. when I use the 2.4.12 version, the error doesn't appear and everything seems work fine

**Comment by LoneDev6** [comment]
You have to report this to Purpur, it seems to be a Purpur bug about biomes.

```
09.09 18:19:53 [Server] INFO java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.MinecraftKey.getNamespace()" because "minecraft" is null
09.09 18:19:53 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.util.CraftNamespacedKey.fromMinecraft(CraftNamespacedKey.java:24) ~[patched_1.17.1.jar:git-Purpur-1377]
09.09 18:19:53 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.biomeBaseToBiome(CraftBlock.java:517) ~[patched_1.17.1.jar:git-Purpur-1377]
09.09 18:19:53 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftRegionAccessor.getBiome(CraftRegionAccessor.java:202) ~[patched_1.17.1.jar:git-Purpur-1377]
09.09 18:19:53 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.getBiome(CraftBlock.java:504) ~[patched_1.17.1.jar:git-Purpur-1377]
```

**Comment by darkdragon0226** [comment]
in version 2.4.12 works fine, version 2.4.13 onwards sends me those errors and in version 2.4.16 it sends me this error with minerals, when breaking it does not drop anything and spam this in the console

https://pastebin.com/CGvsEQzj

**Comment by LoneDev6** [comment]
Send your complete log, this is only the last part of the error.
Thanks

**Comment by darkdragon0226** [comment]
It is the only error that he sends me, here I send the complete log
[2021-09-17-7.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/7190404/2021-09-17-7.log)

**Comment by LoneDev6** [comment]
For some reason the errors in the log are cut.
There is something wrong in the server configuration, or maybe startup parameters I need the full error in order to fix an issue.

**Comment by LoneDev6** [comment]
About the errors: I suspect there is something misconfigured in the loots of ItemsAdder.
Did you edit them?
