### ISSUE TITLE
Solid Furniture Broke in Update. [BUG] 

### ISSUE THREAD

**Issue by Celticism** [PluginBugs/Issues-ItemsAdder#1176]
**Describe the bug**
I had made itemframe based solid furniture like chairs etc in 2.4.12 but when I updated to 2.4.13 and 2.4.14 the solid blocks were shifted even tho it had worked in the previous update with no issue. I also had an issue where angled chairs would sit the player to the side instead of directly out like the fixed position ones do.

**To Reproduce**
Place down a solid itemframe based chair in all six directions and check the barrierblock location. then try sitting in each one. I had mine working fine in 2.4.12 as far as the solid block location /hitbox goes. when you update to either 2.4.13 or 2.4.14 with chair furniture that was working in 2.4.12 the hitbox should be off and the solid blocks. I found that the east chair regardless of height of seat etc wasnt letting me sit in it for some reason. Also I noticed that when I tried sitting in the corner chairs it was facing to the sides instead of straight out.

**Expected behavior**
I expected to have my models have the solid blocks unaltered from the previous version. I found the fixed sides to be working fine except for east which wouldnt let me sit for some reason. I expected the corner chairs to face out like in picture 4 as it does in the fixed chair.

**Screenshots**
![2021-09-09_22 53 44](https://user-images.githubusercontent.com/84742331/132793936-1e4de651-20f7-4290-b8a1-e34414f7294c.png)
![2021-09-09_22 58 14](https://user-images.githubusercontent.com/84742331/132793945-57a91d64-f917-4dd8-844d-771db89d966e.png)
![2021-09-09_22 59 14](https://user-images.githubusercontent.com/84742331/132793955-6c3563d3-0cc4-4753-93e3-0400b0ff5344.png)
![2021-09-09_23 00 01](https://user-images.githubusercontent.com/84742331/132793970-52d78dcf-3f11-4ed4-abd5-b332e355f790.png)

**Info (please complete the following information):**
 - Server version: Spigot 1.17.1
 - Client version: Minecraft 1.17.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version:  2.4.14
 - LightAPI Fork version: 3.5.2
- LoneLibs version: 1.0.14
- ProtocolLib version: 4.7.0

**Additional context**

**Comment by Xiao-MoMi** [comment]
I met the same problem. Barriers are in the wrong place.
In addition. "Fixed_rotation" breaks too.

**Comment by LoneDev6** [comment]
When you report bugs you should always provide an easy way for me to reproduce the issue.
I need the json model of your char and the yml configuration of the item.

**Comment by LoneDev6** [comment]
https://user-images.githubusercontent.com/27242001/132852869-42754c3f-850f-48cd-9d9e-95ccab3fe986.mp4

**Comment by LoneDev6** [comment]
I can confirm that item_frame type is causing issues with the hitbox, I'll publish an update

**Comment by Xiao-MoMi** [comment]
This is my config

 quartz_table1:
    display_name: "石英桌子"
    resource:
      model_id: 5066
      material: PAPER
      generate: false
      model_path: item/furniture/table/quartz_table1
    behaviours:
      furniture:
        entity: item_frame
        solid: true
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          walls: false
          ceiling: false
          floor: true

{
    "credit": "Made with Blockbench",
    "textures": {
        "0": "block/quartz_pillar_top",
        "1": "block/quartz_block_top",
        "particle": "block/quartz_block_top"
    },
    "elements": [
        {
            "name": "Leg2",
            "from": [
                5,
                0,
                5
            ],
            "to": [
                11,
                3,
                11
            ],
            "rotation": {
                "angle": 0,
                "axis": "y",
                "origin": [
                    7.5,
                    6.5,
                    7.5
                ]
            },
            "faces": {
                "north": {
                    "uv": [
                        5,
                        13,
                        11,
                        16
                    ],
                    "texture": "#1"
                },
                "east": {
                    "uv": [
                        5,
                        13,
                        11,
                        16
                    ],
                    "texture": "#1"
                },
                "south": {
                    "uv": [
                        5,
                        13,
                        11,
                        16
                    ],
                    "texture": "#1"
                },
                "west": {
                    "uv": [
                        5,
                        13,
                        11,
                        16
                    ],
                    "texture": "#1"
                },
                "up": {
                    "uv": [
                        5,
                        5,
                        11,
                        11
                    ],
                    "rotation": 270,
                    "texture": "#0"
                },
                "down": {
                    "uv": [
                        12,
                        1,
                        18,
                        7
                    ],
                    "rotation": 180,
                    "texture": "#0"
                }
            }
        },
        {
            "name": "Leg2",
            "from": [
                6,
                3,
                6
            ],
            "to": [
                10,
                12,
                10
            ],
            "rotation": {
                "angle": 0,
                "axis": "y",
                "origin": [
                    8,
                    7.5,
                    8
                ]
            },
            "faces": {
                "north": {
                    "uv": [
                        6,
                        4,
                        10,
                        13
                    ],
                    "texture": "#1"
                },
                "east": {
                    "uv": [
                        6,
                        4,
                        10,
                        13
                    ],
                    "texture": "#1"
                },
                "south": {
                    "uv": [
                        6,
                        4,
                        10,
                        13
                    ],
                    "texture": "#1"
                },
                "west": {
                    "uv": [
                        6,
                        4,
                        10,
                        13
                    ],
                    "texture": "#1"
                }
            }
        },
        {
            "name": "Leg2",
            "from": [
                2,
                12,
                2
            ],
            "to": [
                14,
                13,
                14
            ],
            "rotation": {
                "angle": 0,
                "axis": "y",
                "origin": [
                    7.5,
                    6.5,
                    7.5
                ]
            },
            "faces": {
                "north": {
                    "uv": [
                        2,
                        13,
                        14,
                        14
                    ],
                    "texture": "#1"
                },
                "east": {
                    "uv": [
                        2,
                        13,
                        14,
                        14
                    ],
                    "texture": "#1"
                },
                "south": {
                    "uv": [
                        1,
                        13,
                        13,
                        14
                    ],
                    "texture": "#1"
                },
                "west": {
                    "uv": [
                        2,
                        13,
                        14,
                        14
                    ],
                    "texture": "#1"
                },
                "down": {
                    "uv": [
                        2,
                        2,
                        14,
                        14
                    ],
                    "rotation": 180,
                    "texture": "#0"
                }
            }
        },
        {
            "name": "Leg3",
            "from": [
                2,
                0,
                2
            ],
            "to": [
                14,
                1,
                14
            ],
            "rotation": {
                "angle": 0,
                "axis": "y",
                "origin": [
                    7.5,
                    -5.5,
                    7.5
                ]
            },
            "faces": {
                "north": {
                    "uv": [
                        2,
                        13,
                        14,
                        14
                    ],
                    "texture": "#1"
                },
                "east": {
                    "uv": [
                        2,
                        13,
                        14,
                        14
                    ],
                    "texture": "#1"
                },
                "south": {
                    "uv": [
                        1,
                        13,
                        13,
                        14
                    ],
                    "texture": "#1"
                },
                "west": {
                    "uv": [
                        2,
                        13,
                        14,
                        14
                    ],
                    "texture": "#1"
                },
                "up": {
                    "uv": [
                        2,
                        2,
                        14,
                        14
                    ],
                    "texture": "#0"
                },
                "down": {
                    "uv": [
                        2,
                        2,
                        14,
                        14
                    ],
                    "rotation": 180,
                    "texture": "#0"
                }
            }
        },
        {
            "name": "Leg4",
            "from": [
                3,
                1,
                3
            ],
            "to": [
                13,
                2,
                13
            ],
            "rotation": {
                "angle": 0,
                "axis": "y",
                "origin": [
                    7.5,
                    -4.5,
                    7.5
                ]
            },
            "faces": {
                "north": {
                    "uv": [
                        2,
                        13,
                        12,
                        14
                    ],
                    "texture": "#1"
                },
                "east": {
                    "uv": [
                        2,
                        13,
                        12,
                        14
                    ],
                    "texture": "#1"
                },
                "south": {
                    "uv": [
                        1,
                        13,
                        11,
                        14
                    ],
                    "texture": "#1"
                },
                "west": {
                    "uv": [
                        2,
                        13,
                        12,
                        14
                    ],
                    "texture": "#1"
                },
                "up": {
                    "uv": [
                        3,
                        3,
                        13,
                        13
                    ],
                    "texture": "#0"
                }
            }
        },
        {
            "name": "Surface",
            "from": [
                0,
                13,
                0
            ],
            "to": [
                16,
                16,
                16
            ],
            "rotation": {
                "angle": 0,
                "axis": "y",
                "origin": [
                    8,
                    21,
                    8
                ]
            },
            "faces": {
                "north": {
                    "uv": [
                        0,
                        0,
                        16,
                        4
                    ],
                    "texture": "#0"
                },
                "east": {
                    "uv": [
                        0,
                        0,
                        16,
                        4
                    ],
                    "texture": "#0"
                },
                "south": {
                    "uv": [
                        0,
                        0,
                        16,
                        4
                    ],
                    "texture": "#0"
                },
                "west": {
                    "uv": [
                        0,
                        0,
                        16,
                        4
                    ],
                    "texture": "#0"
                },
                "up": {
                    "uv": [
                        0,
                        0,
                        16,
                        16
                    ],
                    "texture": "#0"
                },
                "down": {
                    "uv": [
                        0,
                        0,
                        16,
                        16
                    ],
                    "texture": "#0"
                }
            }
        }
    ],
    "display": {
        "thirdperson_righthand": {
            "rotation": [
                45,
                0,
                0
            ],
            "translation": [
                0,
                1,
                0
            ],
            "scale": [
                0.35,
                0.35,
                0.35
            ]
        },
        "thirdperson_lefthand": {
            "rotation": [
                45,
                0,
                0
            ],
            "translation": [
                0,
                1,
                0
            ],
            "scale": [
                0.35,
                0.35,
                0.35
            ]
        },
        "firstperson_righthand": {
            "rotation": [
                -10,
                15,
                0
            ],
            "translation": [
                1,
                0,
                0
            ],
            "scale": [
                0.4,
                0.4,
                0.4
            ]
        },
        "firstperson_lefthand": {
            "rotation": [
                -10,
                15,
                0
            ],
            "translation": [
                1,
                0,
                0
            ],
            "scale": [
                0.4,
                0.4,
                0.4
            ]
        },
        "ground": {
            "translation": [
                0,
                1,
                0
            ],
            "scale": [
                0.3,
                0.3,
                0.3
            ]
        },
        "gui": {
            "rotation": [
                35,
                -135,
                0
            ],
            "translation": [
                0,
                -1,
                0
            ],
            "scale": [
                0.5,
                0.5,
                0.5
            ]
        },
        "head": {
            "translation": [
                0,
                -32.9,
                0
            ],
            "scale": [
                2.289,
                2.289,
                2.289
            ]
        },
        "fixed": {
            "rotation": [
                -90,
                0,
                0
            ],
            "translation": [
                0,
                0,
                -16
            ],
            "scale": [
                2,
                2,
                2
            ]
        }
    }
}

**Comment by Xiao-MoMi** [comment]
![image](https://user-images.githubusercontent.com/70987828/132861174-8f465606-00e1-4438-b724-d04f574493b8.png)

In addition. "Fixed_rotation" breaks too.
In addition. "Fixed_rotation" breaks too.
Plz fix it

**Comment by Xiao-MoMi** [comment]
"Fixed_rotation" breaks too.
![image](https://user-images.githubusercontent.com/70987828/132861806-3cd55977-a392-4ba7-82bc-2f80baed7219.png)

**Comment by LoneDev6** [comment]
As I said, I need the json and yml of all the models....

You didn't provide the model and config of the lamp.

**Comment by LoneDev6** [comment]
Anyway, the next update should fix the issues, I tried my best but it took me more time to fix the problem because I didn't get the model files on the first message.
I hope you understand.
Have a nice day
