### ISSUE TITLE
[BUG] mushroom blocks

### ISSUE THREAD

**Issue by ghtg** [PluginBugs/Issues-ItemsAdder#1177]
**Describe the bug**
when world generates a mushroom biome this happening on every mushroom

**To Reproduce**
find the mushroom biome

**Expected behavior**
normal mushrooms

**Screenshots**
but i see this
![image](https://user-images.githubusercontent.com/21358664/132879994-c57286b4-0dd9-4ec3-a707-fa6791a0bda4.png)

**Info (please complete the following information):**
 - Server version: papermc 1.17.1
 - Client version: optifine 1.17.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
ItemsAdder version: 2.4.14
LightAPI Fork version: 3.5.2
LoneLibs version: 1.0.14
ProtocolLib version: 4.7.0

**Comment by LoneDev6** [comment]
https://itemsadder.devs.beer/faq/blocks-minerals-issues/custom-blocks-glitch-texture
