### ISSUE TITLE
behaviours hat Not working on the last update  | 2.4.15

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#1179]
behaviours:   
      hat: true 
Not working on | 2.4.15

**Comment by LoneDev6** [comment]
Strange.. I'll check this in the next days, thanks for the report.

**Comment by SNokerYT** [comment]
it's working only when you Click on the Ground, take your time 
Thanks for the quick reply 🌹

**Comment by LoneDev6** [comment]
No problem!
I fixed it, it was because of a fix I implemented for BanItem plugin, but introduced this new problem.

Refer to: https://github.com/PluginBugs/Issues-ItemsAdder/issues/1194
