### ISSUE TITLE
[Suggestion] /iaimport to import a resource pack

### ISSUE THREAD

**Issue by FokaStudio** [PluginBugs/Issues-ItemsAdder#1181]
**Is your feature request related to a problem? Please describe.**
It is from my previous ticket (`-transcript 2271`) where I wrote about an issue with not being able to run /iazip and having to manually merge RPs

**Describe the solution you'd like**
A command like **/iaimport**, which would be reversed /iazip - it would delete current RP packs, **UNZIP the pack.zip** and replace the old files with new ones

**Describe alternatives you've considered**
Could wrote my own script for that (using Skript with Skent addon, too dumb for Java `:/`)

**Additional context**
--x--

**Comment by LoneDev6** [comment]
This is not required and is very complex.
You can check the new logic which allows easy packs merging: https://itemsadder.devs.beer/3-3-vs-3-2
