### ISSUE TITLE
Upside down New Behaviour with out edit it on Blockbench 💖

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#1183]
it's will be great if you add a new feature that upside down the furniture like the 
opposite_direction: false #makes the model rotate 180 when placed
but this time, **Upsidedown: false**  # makes upside-down furniture 

![image](https://user-images.githubusercontent.com/68678154/132962216-1b76be4a-74f8-4f00-a3cb-442d3050c35f.png)
Upsidedown: true
![image](https://user-images.githubusercontent.com/68678154/132962251-c74d5bfc-aa86-42f7-b740-81a10a4a5605.png)

**Comment by LoneDev6** [comment]
Why is this needed?
I don't find a practical usage for this, you just can rotate it in blockbench.
