### ISSUE TITLE
No more craft previews and stonecutter not working with Itemsadder [BUG] 

### ISSUE THREAD

**Issue by Agaloth** [PluginBugs/Issues-ItemsAdder#1184]
**Describe the bug**
Stonecutters don't work anymore and the crafting table doesn't show the possible crafts to the player.

**To Reproduce**
1. Install Itemsadder 2.4.15
2. Use a stonecutter or crafting table
3. See error

**Expected behavior**
Well, the stonecutter should work and the crafting table should show already unlocked crafts.

**Screenshots**
Without itemsadder: 
![image](https://user-images.githubusercontent.com/33335971/132962639-2b6506b2-9ff9-4bfe-91e7-2a4cab864eb6.png)

With itemsadder:
![image](https://user-images.githubusercontent.com/33335971/132962725-b588366e-6c1f-4509-a019-1ea50238c4a7.png)
![image](https://user-images.githubusercontent.com/33335971/132962729-1d0c3712-eaaf-47d6-85f3-9b5976ab2cc4.png)

**Info (please complete the following information):**
 - Server version: Airplane-Purpur 1.16.5 and also on Purpur 1.17.1 have same results.
 - Client version: Minecraft w/ optifine 1.16.5 and 1.17.1 have same results.

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.15
 - LoneLibs version: 1.0.14
 - ProtocolLib version: Same result with build # 501 (1.16.5) and build # 531 (1.17.1)

**Comment by LoneDev6** [comment]
is this related to itemsadder?

**Comment by Agaloth** [comment]
> is this related to itemsadder?

yes

**Comment by LoneDev6** [comment]
I cannot reproduce the issue with ItemsAdder installed

![immagine](https://user-images.githubusercontent.com/27242001/133641725-1012eecb-f586-497a-9e1f-cf2cde79565d.png)
![immagine](https://user-images.githubusercontent.com/27242001/133641765-14217afb-d628-4b62-b0b7-72c3931fef9d.png)
