### ISSUE TITLE
Problem when you put furniture above furniture | itemframe 

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#1185]
Problem when you put furniture above furniture | itemframe 

**Video |** https://i.imgur.com/DBIg6az.mp4

itemsadder | 2.4.15

**Comment by LoneDev6** [comment]
Why are you creating a furniture using the item_frame?
Use the armor_stand item.

item_frame entity is useful only for furnitures that needs to be placed on walls and ceiling.

There is no other advantage into using item_frame furnitures instead of armor_stand.
