### ISSUE TITLE
Problem when you put furniture on walls it will keep rotating for each Direction | itemframe 

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#1186]
The problem is when you put furniture on walls it will keep rotating for each Direction 

**Video |** https://i.imgur.com/pH2seBa.mp4
 
the problem happened when I used 
        placeable_on:                                                         
          walls: true  
          
also I tried to use 
fixed_rotation: true | but when you try to break it won't 
itemsadder | 2.4.15

**Comment by LoneDev6** [comment]
set fixed_rotation

**Comment by SNokerYT** [comment]
look at the end of the video I can't remove the furniture when I used fixed_rotation: true

**Comment by SNokerYT** [comment]
![image](https://user-images.githubusercontent.com/68678154/132991336-c97ad3fa-1b81-42c4-a932-401be6ba8f5a.png)

**Comment by SNokerYT** [comment]
the problem happened on this direction
**look at this video =** https://i.imgur.com/kSb3Wsa.mp4

**Comment by SNokerYT** [comment]
also, i think this problem related to this https://github.com/PluginBugs/Issues-ItemsAdder/issues/1185

**Comment by LoneDev6** [comment]
You have to fix your hitbox offsets.

Enable /iahitbox command and place the furniture, you can see the hitbox is shifted.
Read more here: https://github.com/PluginBugs/Issues-ItemsAdder/issues/1195#issuecomment-920988619

**Comment by SNokerYT** [comment]
when you facing south the furniture will not break
I tried the width_offset and height_offset still all the same problem
Video | https://i.imgur.com/UYUfl4j.mp4

**Comment by LoneDev6** [comment]
Please can you send me on discord your namespace files?
I want to directly test with your furnitures

Thanks
