### ISSUE TITLE
[BUG] infinite jukebox area

### ISSUE THREAD

**Issue by ghtg** [PluginBugs/Issues-ItemsAdder#1187]
**Describe the bug**
when i placed a disk in jukebox then i fly away i still hear it playing.

**To Reproduce**

https://youtu.be/O1WQHxO7XZw

**Expected behavior**
the sound is getting quiet and completely disappears in radius of ~10 blocks, but if i come closer i will hear it on right timing (synchronized)

Info (please complete the following information):
server: papermc 1.17.1
client: optifine 1.17.1

Special Info
ItemsAdder version: 2.4.15
LightAPI Fork version: 3.5.2
LoneLibs version: 1.0.14
ProtocolLib version: 4.7.0

**Comment by LoneDev6** [comment]
Be sure to read my wiki.
It's a Minecraft "bug" and it's explained how to fix it (make your audio MONO not STEREO)

https://itemsadder.devs.beer/plugin-usage/adding-content/advanced/sounds/convert-sound-to-.ogg
https://bugs.mojang.com/browse/MC-146721
