### ISSUE TITLE
Transparent texture will penetrate image[BUG] 

### ISSUE THREAD

**Issue by Caishangqi** [PluginBugs/Issues-ItemsAdder#1188]
**Describe the bug**
when you use a transparent texture in GUI and set a GUI with an image, the transparent texture will penetrate the GUI image.

**To Reproduce**
1. Create a bottom with a transparent texture
2. Set GUI title to an image
3. the transparent button will penetrate the GUI image

**Expected behavior**
The GUI image should not be penetrated.

**Screenshots**
![QAU} }ZO(CMLF6W(Z61~9YM](https://user-images.githubusercontent.com/39553613/133108948-527a0118-5b4e-4157-9572-5a34922baaa6.png)
You can see the bottom with transparent texture penetrate GUI image.

**Info (please complete the following information):**
 - Server version: Paper 1.17.1
 - Client version: Optfine 1.17.1

**Special Info**
 - ItemsAdder version: 2.4.15
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.13
 - ProtocolLib version: 4.7.0

**Additional context**
[json file](https://paste.ubuntu.com/p/pbv5kXtjWd/)
texture
![travel_locked](https://user-images.githubusercontent.com/39553613/133109761-5528cf8f-eb64-446f-986a-257c1dbcd89a.png)

**Comment by LoneDev6** [comment]
This is strange, this doesn't happen in the /ia GUI items

**Comment by Caishangqi** [comment]
> This is strange, this doesn't happen in the /ia GUI items

it penetrated the IA GUI.
![)%UQ0 UP7CCDMB}0LD_UL0](https://user-images.githubusercontent.com/39553613/133248866-7bbf95f9-ddbf-4bb7-805e-1bf1b466eb4a.png)

**Comment by LoneDev6** [comment]
Why do the example GUI items don't have this bug?
![immagine](https://user-images.githubusercontent.com/27242001/133615119-05cb3481-e6f3-495e-bd8c-a951eb54fb77.png)

This is strange..
Can you try making your icon by looking at how I created mine?

**Comment by Caishangqi** [comment]
> Why do the example GUI items don't have this bug?
> ![immagine](https://user-images.githubusercontent.com/27242001/133615119-05cb3481-e6f3-495e-bd8c-a951eb54fb77.png)
> 
> This is strange..
> Can you try making your icon by looking at how I created mine?

This might be because your example icons are not transparent, all pixel fill with 100% color

**Comment by LoneDev6** [comment]
![immagine](https://user-images.githubusercontent.com/27242001/133635974-fdbf0d30-8e5f-4a3a-9f7c-7d76f81a177f.png)
alpha is 0

**Comment by LoneDev6** [comment]
I also did a test.
I set alpha to 160 in my custom icon.

![immagine](https://user-images.githubusercontent.com/27242001/133636670-6c614967-003c-4381-b0b0-ca9365895913.png)
![immagine](https://user-images.githubusercontent.com/27242001/133636628-19f44c0d-741c-4adb-9059-45b932f58278.png)


It works fine but the color is shown like if it had alpha 0.
I suspect it's a Minecraft "bug".
Alpha is ignored until a specific value, then it's shown as 255 even if it's lower.

**Comment by Caishangqi** [comment]
> I also did a test.
> I set alpha to 160 in my custom icon.
> 
> ![immagine](https://user-images.githubusercontent.com/27242001/133636670-6c614967-003c-4381-b0b0-ca9365895913.png)
> ![immagine](https://user-images.githubusercontent.com/27242001/133636628-19f44c0d-741c-4adb-9059-45b932f58278.png)
> 
> It works fine but the color is shown like if it had alpha 0.
> I suspect it's a Minecraft "bug".
> Alpha is ignored until a specific value, then it's shown as 255 even if it's lower.

okay I got it
