### ISSUE TITLE
[BUG] Drop double item when 2 player break quickly

### ISSUE THREAD

**Issue by amwatchara** [PluginBugs/Issues-ItemsAdder#1189]
**Describe the bug**
Drop double item when 2 player break quickly

**To Reproduce**
dont have any error

**Expected behavior**
Drop double item when 2 player break quickly

**Screenshots**
https://drive.google.com/file/d/1qgc71aPS22oedYmtygy6b27rcXEcx9E-/view?usp=sharing

**Info (please complete the following information):**
 - Server version: 1.17.1
 - Client version: 1.17.1

**Special Info**
 - ItemsAdder version: 2.4.15
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Comment by LoneDev6** [comment]
This will be fixed in the next update.
Let me know if you will still experience the same problem even after updating.
Thanks
