### ISSUE TITLE
[Suggestion] Authme Support

### ISSUE THREAD

**Issue by ArtifactyNight** [PluginBugs/Issues-ItemsAdder#1191]
This feature will send a resourcepack to player after they login or register successfully

Authme plugin: https://www.spigotmc.org/resources/authmereloaded.6269/

example:
```yml
authme:
  send-resourcepack-after-login-successfully: true
```

**Comment by LoneDev6** [comment]
Hello!
It's already compatible
https://itemsadder.devs.beer/compatibility-with-other-plugins/compatible/authme#how-to-apply-resourcepack-after-login
