### ISSUE TITLE
URL[BUG] 

### ISSUE THREAD

**Issue by MidianIdu** [PluginBugs/Issues-ItemsAdder#1192]
Resourcepack URL is not valid, not a zip file (external-host). Type: text/html, LastEdit: 2021-01-12_22-39 Url: http://b3vht.cn/UEYIb

**Comment by LoneDev6** [comment]
It's not a bug the content type provided by the URL is clearly not valid: `text/html`
It must provide a zip file directly without strange redirects with wrong content type.

Also note that this is not an ItemsAdder limitation, it's how Minecraft works. If the link doesn't provide a direct zip file it won't work.
