### ISSUE TITLE
Allow edit minecraft/font/default.json

### ISSUE THREAD

**Issue by ZDaPlaY** [PluginBugs/Issues-ItemsAdder#1193]
I use the version 2.4.15 of itemsadder
I need to edit the default.json of minecraft /font but every time I edit it and iazip the file it changes and the default.json is changed and the json becomes invalid.
I have the config like this:

    overwrite-vanilla-models__DISABLE_AT_YOUR_OWN_RISK: false
    overwrite-vanilla-lang-json__DISABLE_AT_YOUR_OWN_RISK: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    
It would be nice if you add that the default.json **_(overwrite-font-default-json__DISABLE_AT_YOUR_OWN_RISK: false)_** can be edited by deactivating it in the config or something like that

**Comment by Agaloth** [comment]
I agree with this since it makes working with freelancers much easier (they give us the default.json)

**Comment by LoneDev6** [comment]
I'll add this but please avoid opening support requests in the future if anything messes up

**Comment by ZDaPlaY** [comment]
> I'll add this but please avoid opening support requests in the future if anything messes up

Ok thanks

**Comment by LoneDev6** [comment]
> 
> 
> > I'll add this but please avoid opening support requests in the future if anything messes up
> 
> Ok thanks

No problem! I will release an update the next week probably, I have a lot of requests to handle.
Thanks for understanding

**Comment by LoneDev6** [comment]
In the next update you will be able to edit the `default.json` as much as you like.
I will simply ignore support requests about strange tricks used in this file.


## How to edit the file?

The first time you use `/iazip` you will see the `default.json` file edited to:
```json
{
  "providers": [
  ]
}
```

Here you can add your custom stuff, for example:
```json
{
  "providers": [
      {
      "file": "twitteremojis:font/emoji/smile.png",
      "chars": [
        "A"
      ],
      "height": 9,
      "ascent": 8,
      "type": "bitmap"
    }
  ]
}
```
This will happen:
![immagine](https://user-images.githubusercontent.com/27242001/133660275-dfb8704a-c371-4ffd-a401-0c4bdf0fd4fc.png)

ItemsAdder won't let you see its custom file anymore, it will be automatically put inside the jar itself.
The plugin will use a temporary folder instead which will contain the merged files (your default.json and the generated one): `ItemsAdder\storage\cache\tmp\font\.default.json`

**Comment by ZDaPlaY** [comment]
when I do /iazip the default.json from /plugins/ItemsAdder/data/resource_pack/assets/minecraft/font is modified and only the following text is output in the file:
{
  "providers": []
}

**Comment by LoneDev6** [comment]
Yes, it removes the ItemsAdder generated font entries the first time you run /iazip after the update.
Now you can put your font entries in this file.

**Comment by ZDaPlaY** [comment]
> In the next update you will be able to edit the `default.json` as much as you like.
> I will simply ignore support requests about strange tricks used in this file.
> 
> ## How to edit the file?
> The first time you use `/iazip` you will see the `default.json` file edited to:
> 
> ```json
> {
>   "providers": [
>   ]
> }
> ```
> 
> Here you can add your custom stuff, for example:
> 
> ```json
> {
>   "providers": [
>       {
>       "file": "twitteremojis:font/emoji/smile.png",
>       "chars": [
>         "A"
>       ],
>       "height": 9,
>       "ascent": 8,
>       "type": "bitmap"
>     }
>   ]
> }
> ```
> 
> This will happen:
> ![immagine](https://user-images.githubusercontent.com/27242001/133660275-dfb8704a-c371-4ffd-a401-0c4bdf0fd4fc.png)
> 
> ItemsAdder won't let you see its custom file anymore, it will be automatically put inside the jar itself.
> The plugin will use a temporary folder instead which will contain the merged files (your default.json and the generated one): `ItemsAdder/storage/cache/tmp/resource_pack/assets/minecraft/font/.default.json`
> 
> # Be careful while editing this file. ItemsAdder won't guide you to find out errors. You will have to do that on your own.

So every time i have to change the .jar to update the plugin will you have to add the dafault.json again?
Inside ItemsAdder.jar\storage I can only find 4 yml files, data, font_images_unicode_cache, items_ids_cache, real_blocks_ids_cache and they are all empty

**Comment by LoneDev6** [comment]
> So every time i have to change the .jar to update the plugin will you have to add the dafault.json again?
Inside ItemsAdder.jar\storage I can only find 4 yml files, data, font_images_unicode_cache, items_ids_cache, real_blocks_ids_cache and they are all empty


What?

**Comment by ZDaPlaY** [comment]
the default.json that I added to the server is this: https://mclo.gs/jvNypVL
but the one in /plugins /ItemsAdder/storage/cache/tmp/resource_pack/assets/minecraft/font was changed and transformed to this:
https://mclo.gs/SyZPDTC
it deletes those that do not have file: twitteremojis or mcemojis:font and leave only those that are from the itemsadder

**Comment by LoneDev6** [comment]
Why are you adding a default.json file which contains itemsadder stuff?

Only add the entries which are not generated by itemsadder.
