### ISSUE TITLE
[BUG] Sit mechanic and solid hitbox doesn't work properly

### ISSUE THREAD

**Issue by Uinajo** [PluginBugs/Issues-ItemsAdder#1195]
**Describe the bug**
- Furnitures like bench that is made with `_item_frame_`  and also have option `sit_all_solid_blocks: true`  only allow player to sit on one barrier/solid block. There's only one block that player can sit which is the block that contain item_frame itself while the other one isn't working.

- Furniture hitbox placement is not accurate for some direction depends on item display setting

**Expected behavior**

- I should be able to sit on both hitbox for the bench
- The furniture hitbox should be accurate based on player facing direction

**Video**
Here's the [video](https://youtu.be/44qbGze5boE)

 - Server version: Purpur 1.17.1 [BUILD 1385]
 - ItemsAdder version: 2.4.15
 - LoneLibs version: 1.0.14
 - ProtocolLib version: v4.7.0

**Comment by LoneDev6** [comment]
Please provide your files to reproduce this issue.

Anyway I suggest you to use `entity: armor_stand` instead of `entity: item_frame`.

`item_frame` is supposed to be used only when you want the furniture to be placed also on **walls** or **ceiling**, because ItemFrames can be rotated and placed on surfaces different from the ground.

**Comment by Uinajo** [comment]
Hi,

Thanks for replying, If that's a real purpose of item_frame then it have no difference with armor_stand in term of memory.
Also, here's a [file of the furniture](https://drive.google.com/file/d/1bKuzvZ5DfjEhTdBOAN5BV7yj3bF6M0Sa/view?usp=sharing)

Thanks.

**Comment by LoneDev6** [comment]
Yes, I'm sure nothing changes.
The only real advantage of item_frame is that you can place it on walls and ceiling and see it rotated.


Anyway to fix the hitbox use:
`          width_offset: 0.5`
