### ISSUE TITLE
[BUG] Can not place Armorstands

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-ItemsAdder#1196]
Can not place Armorstands

After updating to 2.4.15, i just tried to place an normal armorstand a few times and it refuses too place and throws this error.

https://paste.helpch.at/ulufucevab.pl

Server version: Paper 1.17.1
Client version: Minecraft 1.17.1

ItemsAdder version: 2.4.15
LightAPI Fork version: 3.5.2
LoneLibs version: 1.0.14
ProtocolLib version: 4.7.0

**Comment by SirCraftypants** [comment]
Strange, i just tried again and the error is not occurring anymore but, i still can't place in that specific world, going to investigate more. May not be itemsadder.

**Comment by LoneDev6** [comment]
Probably the item you're trying to place was renamed or removed from IA configurations

**Comment by SirCraftypants** [comment]
I did some investigating and it's actually an issue with a Plugin named ARMORSTAND TOOLS version 4.2.0, I reverted back to 4.1.2 and it's working again.

To trigger the above Error with Itemsadder, i had 4.2.0 of the above plugin installed and attempted to shift-click an armorstand to access the editing gui.

I will report this to the Developer of Armorstand Tools.

**Comment by SirCraftypants** [comment]
Just happened again

> 
> 
> Probably the item you're trying to place was renamed or removed from IA configurations

Just happened again https://paste.helpch.at/ohusuxojez.pl

? Nothing was removing from IA configurations, I'm talking about a plain old vanilla Armorstand, not being able to place in one of my worlds and i have no idea why but, what i do know is i'm getting this Itemsadder Error. Nothing has changed on my server, other than updating plugins. I've eleminated Armorstand Tools and Worldguard from the possible cause.

**Comment by SirCraftypants** [comment]
I recently updated Protocolib, could that be the cause?

**Comment by SirCraftypants** [comment]
I found the culprit, was a plugin dependency named MOB DISABLER that was preventing me from placing armorstands, this Error must just be a random one.

**Comment by LoneDev6** [comment]
Please be sure to investigate deeply before reporting on Github/opening tickets.
Currently I receive a notification for each message.

Thanks
