### ISSUE TITLE
[BUG] chars in default.json are squares

### ISSUE THREAD

**Issue by istarengwa** [PluginBugs/Issues-ItemsAdder#1197]
**Describe the bug**
Hello, in the default.json file only squares are displayed instead of "\ uF825" so it is impossible for me to use them in my Mythicmobs files for example. Before that correctly displayed this information and allowed me to call images by custom Mobs.

**Screenshots**
the problem of squares :
https://zupimages.net/up/21/37/cj2b.png

before the problem :
https://zupimages.net/up/21/37/zfpj.png

an example of use :
https://zupimages.net/up/21/37/iehh.png

**Info (please complete the following information):**
 - Server version: purpur 1.17.1
 - Client version: official 1.17.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.15
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Comment by LoneDev6** [comment]
Does mythicmobs allow you to use placeholder api placeholders?
You can use %img_kinghead% for example.

**Comment by LoneDev6** [comment]
Or just copy and paste the square.

**Comment by istarengwa** [comment]
> Does mythicmobs allow you to use placeholder api placeholders?
> You can use %img_kinghead% for example.

It's work !!!! Very thank's for you'r help

https://zupimages.net/up/21/37/taqk.png
