### ISSUE TITLE
[BUG] Kick player when interacting custom blocks without tools in hand

### ISSUE THREAD

**Issue by matyasvane** [PluginBugs/Issues-ItemsAdder#1200]
**Describe the bug**
If a player tries to destroy a block with his hand, the server will throw him out.

**To Reproduce**
1. Spawn block
2. Disable Creative
3. hit with hand to block

**Screenshots**
https://cdn.discordapp.com/attachments/888482671540453446/888483744162414592/2021-09-17_19-47-07.mp4

**Info (please complete the following information):**
 - Server version: 1.17.1
 - Client version: 1.17.1

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder version: 2.4.16
 - LightAPI Fork version: 3.5.2
 - LoneLibs version: 1.0.14
 - ProtocolLib version: 4.7.0

**Comment by LoneDev6** [comment]
Is your server under a Bungeecord network?
If yes, please use Waterfall. Bungee has a problem I can't manage find the source of.

**Comment by LoneDev6** [comment]
Anyway, this is similar to an issue I already fixed, maybe you're running an old Bungeecord version?
https://github.com/PluginBugs/Issues-ItemsAdder/issues/875#issuecomment-834569613
