### ISSUE TITLE
[BUG] I place a vehicle (of Vehicles No Resourcepack) my chestplate just disappears and turns into a chest.

### ISSUE THREAD

**Issue by ShockCharge** [PluginBugs/Issues-ItemsAdder#1206]
Did not have this issue when I updated ItemsAdder to 2.4.16b whenever I place a vehicle my chestplate just disappears and turns       
into a chest.

So. the name of the plugin ItemsAdder having a conflict is https://www.spigotmc.org/resources/%E2%9C%88%EF%B8%8Fvehicles-no-resourcepacks-needed.12446/updates
![image](https://user-images.githubusercontent.com/48907444/133922204-cbba953f-0753-40d5-80f5-d2a4163fc0f0.png)

(Plugin Versions):
![image](https://user-images.githubusercontent.com/48907444/133922055-67584716-e204-4a81-bd27-79a3887e1d50.png)
![image](https://user-images.githubusercontent.com/48907444/133922068-dc867581-7645-4e26-b079-b4854260b4a4.png)
![image](https://user-images.githubusercontent.com/48907444/133922075-c2368cdd-ee82-4851-b600-75584b8d7f3a.png)
![image](https://user-images.githubusercontent.com/48907444/133922083-a04a429f-6656-4b50-96a5-0beb155b3dfe.png)

(Video Proof):
https://www.dropbox.com/s/oe1tu0pyuv3uhwu/2021-09-19%2017-11-27.mp4?dl=0

**Comment by LoneDev6** [comment]
>when I updated ItemsAdder to 2.4.16b

Which was your previous version?

**Comment by ShockCharge** [comment]
2.4.15

**Comment by LoneDev6** [comment]
Please open a ticket on my discord and send me a copy of the plugin so i can test.
I find it quite strange tho, I didn't change anything about armors.

I suspect it's a plugin that is automatically moving an item in your hand for some reason and this caused the issue

**Comment by ShockCharge** [comment]
This is a paid plugin though is it alright to send you a premium plugin that you do not own? I might have to ask the author. also it would be best if I could just send it to you via DMs

**Comment by LoneDev6** [comment]
I asked to speedup things, I'm not a leaker and I don't care about using or sharing the jar.
If you want you can ask the author to provide me a copy of the plugin, my Spigot username is `LoneDev`.

**Comment by ShockCharge** [comment]
Fixed in 2.4.17 Thank you.

Also I did not mean that I am just trying to be safe because I don't wanna get my account banned in Spigot.

**Comment by LoneDev6** [comment]
> Fixed in 2.4.17 Thank you.
No problem!
I'll delete this issue messages for privacy
