### ISSUE TITLE
furniture direction problem | itemframe

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#1207]
**Describe the bug**
when I put furniture on a floor in a different direction the problem will happen I remember that you fixed it before on walls
![image](https://user-images.githubusercontent.com/68678154/133938790-76241bab-8c94-440a-a733-a140ad2b9f38.png)

  iron_coffe_table:                                                           
    display_name: "&6Iron Coffe Table"
    lore:         
    - ':paintable:'                                                           
    resource:     
      material: LEATHER_HORSE_ARMOR                                                         
      generate: false                                                         
      model_path: item/iron_coffe_table                                 
    behaviours:   
      furniture:  
        entity: item_frame                                                    
        solid: true                                                           
        hitbox:   
          length: 1                                                           
          width: 2
          height: 1                                                           
        placeable_on:                                                         
          walls: false                                                        
          ceiling: false                                                      
          floor: true                                                         
        sound:
          place:
            name: block.wood.place
          break:
            name: block.wood.break ``

**Screenshots**

**VIDEO** | https://i.imgur.com/NgXH4MV.mp4
 - itemsadder version: (2.4.16b)

**Comment by LoneDev6** [comment]
Why closed?
Please always leave a message why you closed an issue.
Thanks

**Comment by SNokerYT** [comment]
I closed it because I found a solution sorry ^^

**Comment by LoneDev6** [comment]
What is the solution?

**Comment by SNokerYT** [comment]
i used | width_offset: -0.5 to fix that 
https://paste.md-5.net/kuvilumene.cs
