### ISSUE TITLE
CraftArmorStand cannot be cast to class org.bukkit.entity.ItemFrame

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#1209]
the Logfile | https://paste.md-5.net/evusonuzuy.md
the Error | https://paste.md-5.net/uzifirapay.pl

**Comment by SNokerYT** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1199#issuecomment-922185274

**Comment by LoneDev6** [comment]
Thanks.
I think you changed a custom furniture type from armorstand to itemframe in your config, so itemsadder tries to load already placed entities and fails.

I'll fix this in the next update.



Anyway (if you're doing everything in the production server) please make your changes and creation of items in a test server, then once done you transfer them to the production server.
Don't do the editing directly on the production server, it's a bad practice.

**Comment by SNokerYT** [comment]
I removed all the hidden corrupted armorstand and the problem was fixed there no Errors anymore but.
i think the solution for this problem is if someone changed the furniture from armor stand to itemframe you have by coding to remove the whole furniture  that changed, from the world to avoid someone to report it on future
that's my opinion of curse i don't know about your's you have experience more than me.

**Comment by LoneDev6** [comment]
For sure I have to fix this to avoid confusion.
Anyway it's always good to do configurations on a test server then move everything in the production one
