### ISSUE TITLE
[Bug] kill event never triggered

### ISSUE THREAD

**Issue by tinkeringmatt** [PluginBugs/Issues-ItemsAdder#1211]
**Describe the bug**    The kill event never triggers
**To Reproduce**     compare kill event with any other event trigger.
**Expected behavior**   example code below and video would show playing gaining 1 mana every time you kill a mob if it was working.

Note the mana on the server adds 1 per minute, but in the video many mobs are killed both with the event trigger being KILL and with the event trigger being attack, and there is a clear action taken only while the event is attack.

Video showing the event with the attack event trigger, and not triggering from the kill event.
https://www.youtube.com/watch?v=syjGYT7BqfA

Info (please complete the following information):
    Server version: papermc 1.17.1
    Client version: fabric 1.17.1

Special Info
Please do not write "latest"! Tell us the specific plugin version you are using.
    ItemsAdder version: 2.4.16
    LightAPI Fork version: 3.5.2
    LoneLibs version: 1.0.14
    ProtocolLib version: 4.7.0

**Comment by tinkeringmatt** [comment]
Here is the paste bin of the BROKEN kill event
https://pastebin.com/gixjCJWv

**Comment by LoneDev6** [comment]
Thanks, I fixed it in the next update
