### ISSUE TITLE
[Suggestion] Trigger Sound on Vehicle Move.

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-ItemsAdder#1215]
The ability to trigger a sound when a Vehicle initially moves and is constantly moving, I think this would improve Vehicles so much if at all possible.

**Comment by SirCraftypants** [comment]
apologies, i didn't realize i already asked for this feature last year.

**Comment by LoneDev6** [comment]
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/566
