### ISSUE TITLE
Pet Protection flag on damageing effects

### ISSUE THREAD

**Issue by tinkeringmatt** [PluginBugs/Issues-ItemsAdder#1217]
An issue with some of the offensive and especially the AOE damage effects.

They can hurt pets.

In particular these:

damage_entity_in_sight
damage_entity
target_potion_effect
target_remove_potion_effect

**Describe the solution you'd like**
A flag that can be added, "hit_player_pet" or something similar/more fitting.
Where it would allow you to indicate true or false, where the default if not included is that it hurt anything even pets.
Then if its set to true it would not be applied if the mobs owner uuid was the player using the effect

**Describe alternatives you've considered**
Maybe allowing a way to target either set mobs or a list of set mobs?

**Additional context**
every dead doggie that lead to a player quitting out of shear sadness

**Comment by tinkeringmatt** [comment]
For more context
https://youtu.be/BqY8HBBnOVA

**Comment by LoneDev6** [comment]
Sorry the issue is not really clear looking at the video.
Are you the owner of the claim? I can't identify the claim region in the video.


It should actually respect the player damage permission because I call this method to damage entities:
`((LivingEntity) entity).damage(damage, e.getEntity())`
Internally Spigot triggers the event `EntityDamageEvent` and checks if it's cancelled, then won't damage the entity if it's cancelled.


Very strange..

**Comment by tinkeringmatt** [comment]
claim region?

no claim regions were mentioned at all?
The pet was mine and I dont understand why the video was so confusing.
I can make another showing what I mean if you have any specific video request

**Comment by tinkeringmatt** [comment]
If I tame a dog, it is my dog, having something in itemsadder damage effeects that allows the effect to not apply to your own tamed pets that you tame and are your pets would be a feature I would see many players caring about as Ive had this request sent to me by 3 different players on my tiny server

**Comment by tinkeringmatt** [comment]
Also the last time I replied to a ticket you closed out of it and I ended up making a video and only then you fixed it.
I can make as many video as are needed just please dont close the ticket on me

**Comment by tinkeringmatt** [comment]
I did not mention anything about a claim.

I tamed the dog, and using a right click event showed that it did damage to both a random wolf and the one that I tamed.

Please let me know what I can do to clear this up

**Comment by tinkeringmatt** [comment]
In the video at 0:25 you see me tame the dog

**Comment by LoneDev6** [comment]
I understand what you mean now, I thought you needed a protection flag for WorldGuard or similar.
Do you think a global setting in config.yml would be good? I doubt anyone wants their radius weapons to damage the player pets, so I think would be useless to make it a per-item option, right?

Let me know
