### ISSUE TITLE
[BUG] Server crash when loading a REAL_WIRE block 

### ISSUE THREAD

**Issue by enterausername3** [PluginBugs/Issues-ItemsAdder#1219]
**Describe the bug**
When you make custom REAL_WIRE block, and make ItemsAdder populate chunks with that specific block there is a chance that your server will crash when loading that block. I made quite a few custom flowers for my server but when I load in new chunks the server seems to give up and crash

**To Reproduce**
1. Go to ItemsAdder/data
2. Create a custom block populator (like this: https://www.spigotmc.org/resources/deco-worlddeco-add-autogenerating-decorations-on-your-world-surface.95207/ (just copy an example and make 1-2 custom REAL_WIRE blocks then make a populator that populates chunks with them))
3. do /iareload then /iazip (to see the texture)
4. Go into the world where the block is supposed to spawn
5. Go in creative and load in new chunks (Fly as far as 1000 blocks)
6. As you load in a new chunk where the block is supposed to spawn, the server will spam error messages ,crashes and you will be presented with a "Server Closed" message.

**Expected behavior**
When you load in the chunk the block populator should populate that chunk with the specified REAL_WIRE block. 

**Screenshots**
View Attachment. [latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/7217574/latest.log)

**Info (please complete the following information):**
 - Server version: Airplane-Purpur 1.16.5 (tried with Purpur-1.16.5, got the same result)
 - Client version: Vanilla 1.16.5

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder v2.4.17
 - LightAPI Fork 3.5.2
 - LoneLibs 1.0.14
 - ProtocolLib 4.6.0
 - CrashAPI 1.0.14
 - LibsDisguises v10.0.26 (Free version)
 - (I don't use any other plugins that interacts with chunk population or world generation)

**Additional context**
I think because I made over 30 custom blocks I guess when you load in a new chunk the first block will generate to a location and then the second block generates to te exact same position. This may not be the case but this is my Guess. Also when this happens all loaded ItemsAdder blocks will be converted back to noteblock/strings.

**Comment by LoneDev6** [comment]
```
	at me.imdanix.caves.generator.defaults.BuildingsGroup.decideBlock(BuildingsGroup.java:179) ~[?:?]
	at me.imdanix.caves.generator.defaults.BuildingsGroup.generateStructure(BuildingsGroup.java:101) ~[?:?]
	at me.imdanix.caves.generator.defaults.BuildingsGroup.generate(BuildingsGroup.java:84) ~[?:?]
	at me.imdanix.caves.generator.CaveGenerator.populate(CaveGenerator.java:105) ~[?:?]
```

Probably it's a problem the CaveGenerator plugin.
Send the author this error log

**Comment by enterausername3** [comment]
Thank you!
