### ISSUE TITLE
[Bug]: Error when place/rotate item in ITEM_FRAME

### ISSUE THREAD

**Issue by ArtifactyNight** [PluginBugs/Issues-ItemsAdder#1220]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

NightKunGz#0790

### What happened?

Error in console when i place or rotate item frame

### Steps to reproduce the issue

1.) Place Item frame
2.) Add Item / Rotate Item in item frame
3.) See errors in console

### Server version

This server is running Purpur version git-Purpur-1393 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 3ff85ed on ver/1.17.1)
You are running the latest version
Previous version: git-Purpur-1391 (MC: 1.17.1)

### ItemsAdder Version

2.4.17

### ProtocolLib Version

4.7.0

### LoneLibs Version

1.0.14

### LightAPI Version (optional)

3.5.2

### FULL server log

https://mclo.gs/a3txyzD

### Error (optional)

```shell
https://mclo.gs/m4TAVlc
```

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1218
