### ISSUE TITLE
[Bug]: Could not pass event PlayerInteractAtEntityEvent to itemsAdder v2.4.17

### ISSUE THREAD

**Issue by TruongHogent** [PluginBugs/Issues-ItemsAdder#1223]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Wassabi#0317

### What happened?

If I right click an armorstand it get the [error](https://pastebin.com/9xgxQPQ3)

### Steps to reproduce the issue

It's litteraly just right clicking an armor stand. 

### Server version

1.17.1
https://pastebin.com/AE80V9Nm

### ItemsAdder Version

2.4.17

### ProtocolLib Version

Build #531

### LoneLibs Version

1.0.14

### FULL server log

https://pastebin.com/uVQUdNAa

### Screenshots/Videos

(you can drag and drop files or paste links)

**Comment by Akiranya** [comment]
I'm using the same ItemsAdder as the author and have this issue too

**Comment by EchocallingEarth** [comment]
Can confirm this BUG and note it will spam console and if enough interactions happen can lead to freezing or crashes of a server.

Tested with 20 players and caused severe tps to drop from the '20s to 8 when all players rapidly clicked on items causing this error. Items are from item frames to various blocks added to the game via ItemsAdder or other plugins. However yes all errors relate back to the same as above.

Please inform of an eta for a fix LoneDev thank you.

**Comment by yuna123324** [comment]
I'm have same issue too

**Comment by Go4SKILL** [comment]
Can confirm, related to itemframes and interaction with them.

**Comment by LoneDev6** [comment]
@TruongHogent the provided log doesn't contain anything about the `PlayerInteractAtEntityEvent` error.
I see there is a clear error about the mushrooms cache file, delete it as stated in the error `Error loading 'fixed chunks glitched blocks' cache, please stop the server and delete the file: /home/container/plugins/ItemsAdder/storage/cache/fixed_glitched_blocks.nbt`.


Anyway I can assume this Github issue page is related to one of these reports (different problem in each one btw https://github.com/PluginBugs/Issues-ItemsAdder/issues/1223 https://github.com/PluginBugs/Issues-ItemsAdder/issues/1224 ).
I close this in the meantime, follow both the other two issues.
