### ISSUE TITLE
[Bug]: Furniture loses sitting ability after server restart

### ISSUE THREAD

**Issue by Andre601** [PluginBugs/Issues-ItemsAdder#1229]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Andre_601#0601

### What happened?

When you place down a furniture (In my case a Park bench) and then restart the server will that furniture lose the ability to be sit on.
If the furniture also is larger than 1 block will only the block you click on get broken and any other barrier block will remain. The furniture itself (the model) is removed.

### Steps to reproduce the issue

1. Place down any 2-tile furniture you can interact with (i.e. Park bench)
2. Stop the server
3. Start it again
4. Try to interact with the Bench.

### Server version

[00:29:26 INFO]: This server is running Paper version git-Paper-273 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: caa4780)

### ItemsAdder Version

[00:29:55 INFO]: ItemsAdder version 2.4.17
[00:29:55 INFO]: Customize Minecraft without client mods!
[00:29:55 INFO]: Website: devs.beer
[00:29:55 INFO]: Authors: LoneDev and LoneDev

### ProtocolLib Version

[00:30:18 INFO]: ProtocolLib version 4.7.0
[00:30:18 INFO]: Provides read/write access to the Minecraft protocol.
[00:30:18 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[00:30:33 INFO]: LoneLibs version 1.0.14
[00:30:33 INFO]: Collection of libs used by my plugins
[00:30:33 INFO]: Authors: LoneDev and others

### LightAPI Version (optional)

Not used because of light issues with Starlight engine

### LibsDisguises Version (optional)

Not used because no custom mobs are used.

### FULL server log

https://paste.helpch.at/walekegiyo.md

### Error (optional)

```shell
https://paste.helpch.at/jazoruzuxe.cs
```

### Configurations

Exported from `/iaexort example` (Not sure if that is the namespace containing the furniture)
[example.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/7230448/example.zip)

**Comment by patatoplugin** [comment]
yes,this bug happend to me,too.After you broke a chair,and put it again,all the chair can sit

**Comment by LoneDev6** [comment]
I suspect it's related to the error you sent.
The next update should address this.

Thanks for the report
