### ISSUE TITLE
[Suggestion]: Ability to sync the world with itemsadder. 

### ISSUE THREAD

**Issue by xalixilax** [PluginBugs/Issues-ItemsAdder#1230]
### Is your feature request related to a problem?

This plugin allow us to do a lot of customisation with REAL_NOTE REAL__WIRE but one of the big downside is that you can't really use that to generate those blocks in the world. Yes you can do ores and it work well but other than that, it is far from perfect.

### Describe alternatives you've considered

I've been thinking of a way of doing it that I think could resolve a lot of issue without having to create compatibility for most if not all world gen plugin, datapack or even worldpainter. 

There could be setting or even a plugin that when activated start to search the world for placed blocks that could be Itemsadder block. For example, i could set RWG or Iris world gen to place string:west=true,east=false... The plugin would then look from string, note blocks, mushroom (Probably better to disable that one) chorus and if it match something, it is added as a custom block. The plugin could then check new generated chunk for new blocks. I'm not a programmer so this might be an issue. 

Second option could be a one time thing. You generate your world chunks, run the plugin and that's it. This limit the capability and would require some time, but I would prefer to have a 2k x 2k map with custom blocks than no generated custom blocks at all. Could be an issue for existing world that have infinite chunk but if I'm not mistaken, it is always better to limit the size. 

### Additional context

Some issue i could foresee is mushroom blocks, string in jungle temple and chorus fruit in the end. Mushroom should just be avoided in that case. String would be basically 2 states out of 128? And chorus could be disabled by default in the end.

**Comment by LoneDev6** [comment]
Basically you want something that scans the chunk and converts manually placed (with other plugins) custom blocks to itemsadder blocks based on their blockstate value?

**Comment by xalixilax** [comment]
Yes exactly. As long as those blocks are not updated (Pre generated world should still have them with their given data) they could be converted. Even after creation. 

Maybe this could also be used further for world edit?
