### ISSUE TITLE
[Bug]: /iazip can't work with mmobars

### ISSUE THREAD

**Issue by patatoplugin** [PluginBugs/Issues-ItemsAdder#1231]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

I want merge itemsadder's resourcepack with mmobar's.I copy all the mmobars file to itemsadder,then use/iazip,it works well in itemsadder-version-2.4.15,but it can't work in 2.4.17
all the mmobar'sfont can't show
（Itemsadder's emoji works，and I set force unicode-font:off）

So now I have to use the old itemsadder version to build my resourcepack.I don't know where is changed between 2.4.15 to 2.4.17

### Steps to reproduce the issue

I upload the mmobars'pack,you can see why can't merge two packs

### Server version

1.17.1-purpur-1394

### ItemsAdder Version

2.4.17 cant work
2.4.15 work well

### ProtocolLib Version

ProtocolLib version 4.7.0

### LoneLibs Version

LoneLibs version 1.0.14

### LightAPI Version (optional)

LightAPI version 3.5.2

### Screenshots/Videos

[MMOBars-Pack-2.0.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/7231218/MMOBars-Pack-2.0.zip)
![2021-09-26_18 42 30](https://user-images.githubusercontent.com/62246956/134804715-93cc149b-896f-4b64-babf-aa7558437ebf.png)

**Comment by avatario** [comment]
I also am having this issue, it only started a few updates ago, I had it fully operational until a few updates ago. Hope that helps.

**Comment by LoneDev6** [comment]
![immagine](https://user-images.githubusercontent.com/27242001/135678428-d862a0ec-6c05-4661-9167-be93b94bfe54.png)
`/tellraw LoneDev {"text":"\uF06C\uF06D\uF06E\uF06F\uF070\uF071\uF072\uF073\uF074\uF075\uF076\uF077\uF078\uF079\uF07A\uF07B\uF07C\uF07D", "font":"mmobars:ab_0"}`

It works fine for me.
Keep in mind that I don't own the plugin so I cannot test directly, but currently I can see the custom images correctly ingame using the example command.

**Comment by LoneDev6** [comment]
Feel free to ask the developer of MMOBars to contact me via Discord and provide me a copy of the plugin so I can test.
Have a nice day!

**Comment by LoneDev6** [comment]
I tested with the upcoming 2.4.19 version and it works fine, so please wait for the 2.4.19 update as it should fix the problem you're having.
I think it's related to this: https://github.com/PluginBugs/Issues-ItemsAdder/issues/1242
