### ISSUE TITLE
[Bug]: 'Start' value for HUDs/Playerstats not working properly

### ISSUE THREAD

**Issue by Maroon28** [PluginBugs/Issues-ItemsAdder#1235]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Maroon#1461

### What happened?

The 'start' value for status HUDs doesn't seem to work when you set it to 0. It's meant to start with nothing, but instead it starts with the max value. 

### Steps to reproduce the issue

1. Create a HUD with any stat
2. Set the 'start' option to 0
3. Set the max value to anything. 10 for example.
4. Reload itemsadder, or restart.
5. Join the server.
6. You'll have the max amount for that player stat, not the starting value (0)

### Server version

>version
[15:41:29 INFO]: Checking version, please wait...
[15:41:30 INFO]: This server is running Purpur version git-Purpur-1350 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 348846b on ver/1.17.1)
[15:41:30 INFO]: You are 44 version(s) behind
[15:41:30 INFO]: Previous version: git-Purpur-1280 (MC: 1.17.1)

### ItemsAdder Version

[15:41:51 INFO]: ItemsAdder version 2.4.17

### ProtocolLib Version

ProtocolLib version 4.7.0

### LoneLibs Version

LoneLibs version 1.0.14

### FULL server log

https://bin.bloom.host/okolukipot.yaml

### Configurations

Config.yml: https://bin.bloom.host/rimasaninu
Hud configuration: https://bin.bloom.host/omizotufow

### Screenshots/Videos

(you can drag and drop files or paste links)

**Comment by LoneDev6** [comment]
Thanks this will be fixed in the next update.
If you want to delete the player hud data you can delete it from: `plugins\ItemsAdder\storage\players\stats\<UUID>.nbt`
