### ISSUE TITLE
Itemsadder can't inherit MMOitems random stats

### ISSUE THREAD

**Issue by minecraft-dripdrop** [PluginBugs/Issues-ItemsAdder#1239]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

I set a sword inherit mmoitems‘ sword,and I set it random damage.
But I always get the same damge by itemsadder's command. Only you use /iareload,you can get diffferent damge sword.

### Steps to reproduce the issue

1. create a sword in itemsadder
2. create a sword in mmoitems with attack-damage spread
3. let the sword inhert mmoitems stat
4. use /iaget,You will find always same damage
5. use/iareload,and then /iaget,get a different damage sword.

### Server version

This server is running Purpur version git-Purpur-1394 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: acb8a26 on ver/1.17.1)

### ItemsAdder Version

ItemsAdder version 2.4.17

### ProtocolLib Version

ProtocolLib version 4.7.0

### LoneLibs Version

 LoneLibs version 1.0.14

### Screenshots/Videos

(you can drag and drop files or paste links)

**Comment by LoneDev6** [comment]
I don't think this is easily possible to integrate sincerely.
I'll try to find a workaround, thanks.

**Comment by LoneDev6** [comment]
I'm thinking about a solution for that, but might cause issues. I'll keep you updated.

**Comment by AncowiePk** [comment]
> Estoy pensando en una solución para eso, pero podría causar problemas. Te mantendré informado.

Could it be solved by removing the randomization of stats for those items? From mmoitems, of course.

**Comment by jere62smi** [comment]
I count on you, if you need to carry out tests or other, I want to help you. Because currently in my case, mmoitems items with itemsadder are not usable for gameplay.

**Comment by LoneDev6** [comment]
The new upcoming update implements the logic to apply mmoitems random stats on itemsadder items when:
- give item action is performed
- drop item action is performed
- craft result item is obtained (not when it's previewed, to avoid users form clicking until a good stat is found)

Any other event won't trigger this to avoid random stats from happening on unwanted occasions.

Warning: this causes any lore added on itemsadder yml to be replaced by the mmoitems item lore.

**Comment by jere62smi** [comment]
Many thanks for this feature! I'm so excited to be able to set it up on my server :)
