### ISSUE TITLE
Drop Bug Mysterious ore bug

### ISSUE THREAD

**Issue by sfemnksbk3** [PluginBugs/Issues-ItemsAdder#1240]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

When you break the block, dec mysterious ore comes out every now and then.

### Steps to reproduce the issue

1. Break Block
2. Drop mysterious ore

### Server version

This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 2.4.17

### ProtocolLib Version

ProtocolLib version 4.7.10

### LoneLibs Version

LoneLibs version 1.0.14

### Configurations

No Log

### Screenshots/Videos

Video: https://www.youtube.com/watch?v=dgPQmOukwz4

**Comment by LoneDev6** [comment]
I cannot reproduce this issue.
It's very hard to identify what happened here... You have to make sure to remember if you changed anything in the plugin configurations in order to trigger this problem.
Normally this doesn't happen (you're free to check in my test server. Address: `mc.devs.beer`).
