### ISSUE TITLE
I set keep_on_death: true for my item. But when I die, the item still drops.

### ISSUE THREAD

**Issue by sharpaddroot** [PluginBugs/Issues-ItemsAdder#1246]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Paimon wonder. 🌺#2230

### What happened?

I set keep_on_death: true for my item. But when I die, the item still drops.

I have a plugin that is about death. DeathPenalties

### Steps to reproduce the issue

-

### Server version

1.17.1

### ItemsAdder Version

2.4.7

### ProtocolLib Version

4.7.0

### LoneLibs Version

1.0.14

### LightAPI Version (optional)

3.5.2

### LibsDisguises Version (optional)

10.0.26

### Screenshots/Videos

(you can drag and drop files or paste links)

**Comment by LoneDev6** [comment]
Does removing DeathPenalties cause the bug to stop from happening?

**Comment by sharpaddroot** [comment]
It works, but I want exp and tang to be deducted upon death, so I have to use it. deathpenalties or do you have another plugin to recommend me?

**Comment by LoneDev6** [comment]
I think it's a bug of deathpenalties itself, can you send the plugin author this Github issue link? We may find a solution

**Comment by sharpaddroot** [comment]
Okay, let's go talk to him.
