### ISSUE TITLE
Ability to create custom textured armors without Optifine (MC 1.17+)

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#1249]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Implement a way to automate the shaders trick to add custom armors textures.
This will avoid manual editing of the pixels of the png images which slow down the workflow of creating armors.

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

None

**Comment by LoneDev6** [comment]
Scheduled to be added on November

**Comment by patatoplugin** [comment]
It is possilbe?Amazing

**Comment by LoneDev6** [comment]
https://www.youtube.com/watch?v=Ape1acitJCc
