### ISSUE TITLE
Text Effects

### ISSUE THREAD

**Issue by GHsorryiwon12345** [PluginBugs/Issues-ItemsAdder#1254]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

eNji#7430

### Describe the solution you'd like

- Support for TAB plugin
- Support for /rename commands
- Support for color codes for some effects
- PlaceholderAPI support* [maybe something like %iatexteffect_<TAG> TEXT </TAG>%]

### Is your feature request related to a problem?

🧢

### Describe alternatives you've considered

🧢

**Comment by LoneDev6** [comment]
New command will be introduced in ItemsAdder 2.4.23: `/iarename`

Usage example:
`/iarename test <r qqqqq> :smile: very nice`
![immagine](https://user-images.githubusercontent.com/27242001/143230790-515c74db-b7f6-4c1d-8a03-7bba80ac83cd.png)


Supports font_images and text effects

**Comment by GHsorryiwon12345** [comment]
> ## rename
> New command will be introduced in ItemsAdder 2.4.23: `/iarename`
> 
> Usage example: `/iarename test <r qqqqq> :smile: very nice` ![immagine](https://user-images.githubusercontent.com/27242001/143230790-515c74db-b7f6-4c1d-8a03-7bba80ac83cd.png) Supports font_images and text effects.
> 
> ## TAB
> Added also text effects support on the TAB menu (`asdasd` text in this example) ![immagine](https://user-images.githubusercontent.com/27242001/143235338-52409e16-4ba1-4f9f-ab1c-5b8dc21b83b0.png) TAB plugin config example:
> 
> ```yaml
> web:
>   change-interval: 200
>   texts:
>   - '&ewww.domain.com <r asdas>'
> ```
> 
> ItemsAdder config:
> 
> ```yaml
> effects:
>   hide-scoreboard-numbers: false
>   text-effects:
>     enabled: true
>     replace-in-customitems-name-and-lore: true
> ## .....
>     tab-header-footer:
>       enabled: true
> ```

amazing job!
