### ISSUE TITLE
Waila and RPGMoney integrations suggestions

### ISSUE THREAD

**Issue by GHsorryiwon12345** [PluginBugs/Issues-ItemsAdder#1255]
### Discord tag (optional)

eNji#7430

### Describe the solution you'd like

Waila: 
- Change color of a bossbar
- Multilanguage material support
- PlaceholderAPI support
- *textures?
- Entity support
- World deco support
- RGB colors support (HEX)

RPGMoney:
- Support for IA font images in currency-format: ''
- MythicMobs mobs support
- When you drop money from your inventory it will have a hologram with an amount (same as when dropping from mob or ore)
- Item glow effect
- RGB colors support (HEX)

**Comment by LoneDev6** [comment]
# RPGMoney 
https://github.com/PluginBugs/Issues-RPGMoney/issues/31
https://github.com/PluginBugs/Issues-RPGMoney/issues/32
https://github.com/PluginBugs/Issues-RPGMoney/issues/33
https://github.com/PluginBugs/Issues-RPGMoney/issues/34

# Waila
Waila is a side project, I don't think I'll find the time to implement these suggestions sadly
