### ISSUE TITLE
Noteblock bell sound not working!

### ISSUE THREAD

**Issue by TruongHogent** [PluginBugs/Issues-ItemsAdder#1257]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Wassabi#0317

### What happened?

Note block bell sound does not work when placing a note block on top of a gold block, it turns in to a harp sound instead

### Steps to reproduce the issue

When placing a note block on top of a gold block, it turns in to a harp noteblock sound instead

### Server version

1.17.1

### ItemsAdder Version

2.4.19

### ProtocolLib Version

4.7.0

### LoneLibs Version

1.0.15

### LightAPI Version (optional)

/

### LibsDisguises Version (optional)

/

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/7312609/latest.log)

### Error (optional)

```shell
/
```

### Configurations

[config.txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/7312619/config.txt)

### Screenshots/Videos

(you can drag and drop files or paste link

https://user-images.githubusercontent.com/80478455/136586967-cf32fc5a-c909-460c-9741-e3a802c891bb.mp4

s)

**Comment by LoneDev6** [comment]
https://user-images.githubusercontent.com/27242001/137956340-a06ec289-a08f-40cb-8fc7-44d275c6b956.mp4



Tested on:
`This server is running CraftBukkit version 3094-Spigot-9fb885e-fae895a (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)`
`This server is running CraftBukkit version 3254-Spigot-8e90744-1df303e (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)`

`ItemsAdder version 2.4.19`


Check if you have any plugin which is overriding the noteblock behaviour and playing the sound manually.
