### ISSUE TITLE
Add compatibility with RealisticSeasons 5.1 temperatures

### ISSUE THREAD

**Issue by vdl19** [PluginBugs/Issues-ItemsAdder#1262]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Hello, the "RealisticSeasons 5.1" plugin has just set up a temperature system, part of which uses armor to increase the temperature depending on the model, this changes of course. The problem is that the armor which increases the heat the most it is the armor of cooking + 20 ° to 25 ° the other armors they are very low in increase 3 + ° to 5 °. And on ItemsAdder all armor is based on leather armor so it all becomes hot armor and none can be adjusted to hot or cold. So if its plugin could manage your armor, it would allow you to configure each armor according to a custom level of heat.

https://www.spigotmc.org/resources/realisticseasons-1-16-3-1-17-1-seasons-in-your-minecraft-world-temperature-update.93275/

### Is your feature request related to a problem?

Yes as explaining just before the fact that all AI armor is based on leather armor does not make the use of temperatures usable properly, players will not have the logic of hot bake armor and others will not hot, so all AI armor will be very hot.

### Describe alternatives you've considered

Do not use the realistic season temperature system!

**Comment by LoneDev6** [comment]
Hello!
I already contacted the developer providing a free copy of ItemsAdder to them, but I think they are not really interested to add ItemsAdder support as I didn't get any news from them since some months ago.
![immagine](https://user-images.githubusercontent.com/27242001/144035036-58a46158-d0b7-48df-911d-4274ed508f42.png)

I'll try to contact them again.

**Comment by LoneDev6** [comment]
Contacted them again, I wait for an answer

**Comment by LoneDev6** [comment]
Contacted them again, I wait for some news.

![image](https://user-images.githubusercontent.com/27242001/213147534-5ab9f2b5-84d1-4247-8da9-39a5f7567c6c.png)

**Comment by LoneDev6** [comment]
Closing since clearly the RealisticSeasons plugin developer is not interested into adding compatibility, we waited 2 years and a half.
