### ISSUE TITLE
suggestion for custom esc menu

### ISSUE THREAD

**Issue by Miyamoto61** [PluginBugs/Issues-ItemsAdder#1264]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Miyamoto#0429

### Describe the solution you'd like

to allow multiple servers in a single esc menu .yml

this would allow you to add custom esc menus to diffrent servers in your bungeecord while using one itemsadder resorce pack utilising bungeepackfix 

### Is your feature request related to a problem?

yes i would like diffrent custom esc menus on each of my bungeecord server while only using one resorce pack

### Describe alternatives you've considered

server: "server_name1"
info:
  namespace: ia_various_configs
minecraft_lang_overwrite:
  esc_menu_texts:
    entries:
      "menu.game": ":offset_-20::top_logo::offset_-243::bottom_news:"
      "menu.returnToGame": "Return to &bItsNotAnarchy"
      "menu.disconnect": ":quit_button:"
      "deathScreen.title": ":you_died:"
    languages:
      - ALL
server: "server_name2"
info:
  namespace: ia_various_configs
minecraft_lang_overwrite:
  esc_menu_texts:
    entries:
      "menu.game": ":offset_-20::top_logo::offset_-243::bottom_news:"
      "menu.returnToGame": "Return to &bItsNotAnarchy"
      "menu.disconnect": ":quit_button:"
      "deathScreen.title": ":you_died:"
    languages:
      - ALL
server: "server_name3"

(hope this is what you mean)

**Comment by jacquelynra** [comment]
For what I know, you cannot set "conditions" to what server are you on in resource packs. That's a client-side thing.

**Comment by LoneDev6** [comment]
I wish it was possible. This simply cannot be done, you have to modify the resourcepack manually for each server.
It's a Minecraft limitation.
