### ISSUE TITLE
Use two font-image in ia_gui.yml

### ISSUE THREAD

**Issue by minecraft-dripdrop** [PluginBugs/Issues-ItemsAdder#1284]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Can I use two pictures at the same time in ia_gui.yml? 
`  crafting_preview:
    craft_font_image:
      name: dripdrop:crafting_1;dripdrop:crafting_2
      x_position_pixels: -8`
I'm going to use 512px pictures, but the maximum size is 256px, so I'm cut them into two pictures.
(If you just zoom the 512px to 256px in photoshop,the picture will be vague)
![2021-10-29_13 37 10](https://user-images.githubusercontent.com/62246956/139381508-2cf9c80c-b9d3-4ffb-bd66-de8f2e46555d.png)
![2021-10-29_13 37 57](https://user-images.githubusercontent.com/62246956/139381571-743f3e78-d7bb-4d2a-a581-3ce735652f2b.png)

And I think it's more beautiful for all item icons to move down one grid

### Is your feature request related to a problem?

The max size of font is 256px

### Describe alternatives you've considered

let ia_gui.yml can be more customized,for example,the place of icons(next_page...)

**Comment by LoneDev6** [comment]
I don't think this fits the Minecraft style because bigger images will mean HQ textures, which don't fit the game style itself.
