### ISSUE TITLE
model_id isn't saving

### ISSUE THREAD

**Issue by LuluxClient** [PluginBugs/Issues-ItemsAdder#1288]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Lulux#4614

### What happened?

So I'm trying to add custom items to my menus via deluxemenu, the issue is that sometimes the items are overriding default textures and also the model_id isn't saving. I enabled the debug and I found out that it gave random id to items and it wasn't saving the ids I was adding.

config: https://gyazo.com/d5af92031e97d26ed516164e76a84a45
Console output with debug: https://gyazo.com/d407d23bca7ba4eb7443db360d86e5ff

### Steps to reproduce the issue

Create a blank item
add this to your item namespace: 
items:     
  icon_retour:
    display_name: display-name-icon_retour  
    resource:
      material: PAPER
      model_id: 10001
      generate: true
      textures:
      - item/icon_retour.png
      
enable the debug on everything and you will see the model_id they chose is different.

### Server version

https://gyazo.com/2f973d30e88c974977b4979f93992eb4 

### ItemsAdder Version

[20:43:43 INFO]: ItemsAdder version 2.4.19b
[20:43:43 INFO]: Customize Minecraft without client mods!
[20:43:43 INFO]: Website: devs.beer
[20:43:43 INFO]: Authors: LoneDev and LoneDev

### ProtocolLib Version

[20:43:56 INFO]: ProtocolLib version 4.7.0
[20:43:56 INFO]: Provides read/write access to the Minecraft protocol.
[20:43:56 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

> version lonelibs
[20:44:05 INFO]: LoneLibs version 1.0.15
[20:44:05 INFO]: Collection of libs used by my plugins
[20:44:05 INFO]: Authors: LoneDev and others

### LightAPI Version (optional)

none

### LibsDisguises Version (optional)

nop

### FULL server log

https://pastebin.com/VgbdtB8Z

### Error (optional)

```shell
none
```

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: HIDDEN LOL
      pack-port: HIDDEN LOL
    external-host:
      enabled: false
      url: ''
  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: true
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: fr-carragrive
  dictionaries-lang: fr-carragrive
  extract-default-items: false
  extract-default-resources: false
  minify-json: true
blocks:
  light-api: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: false
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
effects:
  hide-scoreboard-numbers: true
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
recipes:
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
  hide-vanilla-unrecognized-recipe-errors: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
debug:
  items:
    log-files-loading: true
    log-items-loading: true
    log-items-loading-disabled: true
    log-font-images-loading: true
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
  resource-pack:
    log-extract-default-resources: true
    log-not-extract-default-resources-already-exist: true
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: epicworld_icons
font_images:
  icon_profil:
    permission: "epicworld_grades.icon_profil"
    show_in_gui: true
    suggest_in_command: false
    path: "font/png/icon_profil.png"
    scale_ratio: 9
    y_position: 8
  icon_votre_ile:
    permission: "epicworld_grades.icon_votre_ile"
    show_in_gui: true
    suggest_in_command: false
    path: "font/png/icon_votre_ile.png"
    scale_ratio: 9
    y_position: 8
  icon_visite:
    permission: "epicworld_grades.icon_visite"
    show_in_gui: true
    suggest_in_command: false
    path: "font/png/icon_visite.png"
    scale_ratio: 9
    y_position: 8
  amethyst_shard:
    permission: "epicworld_grades.amethyst_shard"
    show_in_gui: true
    suggest_in_command: false
    path: "font/png/amethyst_shard.png"
    scale_ratio: 9
    y_position: 8
items:     
  icon_retour:
    display_name: display-name-icon_retour  
    resource:
      material: PAPER
      model_id: 10001
      generate: true
      textures:
      - item/icon_retour.png
```

### Other files, you can drag and drop them here to upload. (optional)

none

### Screenshots/Videos (you can drag and drop files or paste links)

none

**Comment by LoneDev6** [comment]
I think you created the item, used /iazip, then set the model_id, used /iazip.
Now ItemsAdder loads the model_id from the cache instead of using the specified one.

Please do this test:
- open the cache file 
- delete the line containing your custom item name `plugin\ItemsAdder\storage\items_ids_cache.yml`
- run /iazip
- check if the model id is correct
if not, it's a bug and i have to investigate more

**Comment by LuluxClient** [comment]
> I think you created the item, used /iazip, then set the model_id, used /iazip. Now ItemsAdder loads the model_id from the cache instead of using the specified one.
> 
> Please do this test:
> 
> * open the cache file
> * delete the line containing your custom item name `plugin\ItemsAdder\storage\items_ids_cache.yml`
> * run /iazip
> * check if the model id is correct
>   if not, it's a bug and i have to investigate more

After doing that it fixed the issue thanks, I'll check this file more often !

**Comment by LoneDev6** [comment]
No problem! :D

**Comment by LoneDev6** [comment]
Feel free to leave a good review :D
It helps me a lot: https://www.spigotmc.org/resources/73355/
