### ISSUE TITLE
Vehicle can be removed/destoyed while worldguard flags are set to deny

### ISSUE THREAD

**Issue by Andre601** [PluginBugs/Issues-ItemsAdder#1289]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Andre_601#0601

### What happened?

Vehicles can be destroyed by other players despite lacking the required permissions and while the WorldGuard region has the ItemsAdder flags set to deny.

### Steps to reproduce the issue

1. Place a vehicle
2. Make sure region flags AND possible permissions (if any) are denied.
3. Let normal player destroy vehicle.

### Server version

[01:48:16 INFO]: Checking version, please wait...
[01:48:16 INFO]: This server is running Paper version git-Paper-353 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: f2cb9cb)
You are running the latest version
Previous version: git-Paper-273 (MC: 1.17.1)

### ItemsAdder Version

[01:48:41 INFO]: ItemsAdder version 2.4.20
[01:48:41 INFO]: Customize Minecraft without client mods!
[01:48:41 INFO]: Website: devs.beer
[01:48:41 INFO]: Authors: LoneDev and LoneDev

### ProtocolLib Version

[01:48:57 INFO]: ProtocolLib version 4.7.0
[01:48:57 INFO]: Provides read/write access to the Minecraft protocol.
[01:48:57 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[01:49:12 INFO]: LoneLibs version 1.0.15
[01:49:12 INFO]: Collection of libs used by my plugins
[01:49:12 INFO]: Authors: LoneDev and others

### LightAPI Version (optional)

Not Used

### LibsDisguises Version (optional)

Not used

### FULL server log

https://paste.helpch.at/ohenubajoc.md

### Error (optional)

```shell
N/A
```

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: false
      server-ip: 127.0.0.1
      pack-port: 8163
    external-host:
      enabled: true
      url: https://download.mc-packs.net/pack/9825a738714ae51518861a398fe4cd1f8fea00ec.zip
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-items: true
  extract-default-resources: true
  minify-json: true
blocks:
  light-api: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
recipes:
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
  hide-vanilla-unrecognized-recipe-errors: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
```

### Screenshots/Videos (you can drag and drop files or paste links)

![gif](https://thumbs.gfycat.com/SlowWhoppingBarasingha-size_restricted.gif)

**Comment by LoneDev6** [comment]
Which are your worldguard region permissions?
Can I see a screenshot?
Also, is your region __global__ ? It's known to cause problems

**Comment by Andre601** [comment]
> 1. Which are your worldguard region flags?
> 2. Can I see a screenshot?
> 3. Is your region **global** ? It's known to cause problems
> 4. Did you use these worldguad flags? https://itemsadder.devs.beer/compatibility-with-other-plugins/compatible/worldguard-flags#flags-list
> 
> Btw the broomstick holder is a very cool idea!

1. Those are all **actively set flags** (All others are the WG defaults)
   - passthrough: deny
   - pvp: deny
   - item-frame-rotation: deny
   - item-drop: deny
   - mob-damage: deny
   - creeper-explosion: deny
   - ghast-fireball: deny
   - other-explosion: deny
   - enderman-grief: deny
   - entity-painting-destroy: deny
   - entity-item-frame-destroy: deny
   - mob-spawning: deny
   - fire-spread: deny
   - lava-fire: deny
   - lighting: deny
   - invincible: allow
   - fall-damage: deny
   - feed-delay: 0
   - feed-amount: 20
   - feed-min-hunger: 20
   - deny-message: -e (empty)
   - ast (custom): deny
   - ia-furniture-sit: allow
   - ia-placed-armorstand-interact: deny
   - ia-placed-block-interact: deny
   - ia-placed-itemframe-interact: deny
   - ia-vehicle-personal-remove: deny
   - ia-vehicle-personal-sit: deny
   - ia-vehicle-place: deny
   - ia-vehicle-remove: deny
   - ia-vehicle-sit: deny
2. Screenshot of what? The flags? In that case did I gave all I modified above.
3. Yes. Region is `__global__` but from the link you gave in point 4 should this not be related, since it's not a sitting issue?

**Comment by Andre601** [comment]
Seems to be a `__global__` region issue
