### ISSUE TITLE
Dupe glitch crafting recipes

### ISSUE THREAD

**Issue by poityTMK** [PluginBugs/Issues-ItemsAdder#1290]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

!ｐｏｉｔｙ_ＴＭＫ#6586

### What happened?

Craftings that include a consumable item can duplicate the items included in the crafting

### Steps to reproduce the issue

is shown in the attached video
(if you close the inventory quickly while clicking to take the crafting result, the items are duplicated)

### Server version

This server is running Airplane version git-Airplane-99 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: e68f5c2 on HEAD)
You are on the latest version!
Previous version: git-Airplane-98 (MC: 1.17.1)

### ItemsAdder Version

2.4.20

### ProtocolLib Version

4.7.0

### LoneLibs Version

1.0.15

### Screenshots/Videos (you can drag and drop files or paste links)

https://www.dropbox.com/s/ojz52rvi47zemdl/Minecraft_1_17_1_Multiplayer_3rd_party_Server_2021_10_31_09_37_00.mp4?dl=0

**Comment by LoneDev6** [comment]
@poityTMK does this only happens on the 2x2 crafting?

**Comment by LoneDev6** [comment]
Send me your yml file which contains the recipe, the hammer and the ingredients for the recipe, thanks

**Comment by LoneDev6** [comment]
I'm trying but I cannot reproduce the issue.
Maybe you have a crafting plugin which is interfering with ItemsAdder recipes?
https://itemsadder.devs.beer/compatibility-with-other-plugins/not-compatible

## 2x2 crafting with low ping client:

https://user-images.githubusercontent.com/27242001/139870870-97fa463f-a4d0-42ea-9b54-911102e965fe.mp4

## crafting table with high ping client:

https://user-images.githubusercontent.com/27242001/139872035-177e3fae-76b4-423e-a013-75ea16ada0dd.mp4

**Comment by poityTMK** [comment]
@LoneDev6 Attached you can find all the files plus the photo of the plugin list, all those with 'Areson' in the name do not interfere with the crafting, plus we do not use any plugin that goes to use the crafting table

unfortunately I can't show you the files related to the second video because later I had the possibility to get the nuggets from the crafting

In addition I can assure you that it is not related to the user's ping because more than a dozen people have used these bugs and the items they get are real; I don't know how else to explain
![2021-11-02_16 15 52](https://user-images.githubusercontent.com/44748641/139876716-8cfc5d3a-816c-4a4a-ae57-0b7cae2f4687.png
[files.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/7461915/files.zip)
)

**Comment by poityTMK** [comment]
@LoneDev6 Ok, I understand well how to reproduce the problem, it does not center the ping you have (I have tested now with multiple people with different pings)

What you need to do is:
- put items in 2x2 crafting
- take with the cursor the item that comes out of crafting and practically at the same time you have to press esc to close the inventory and reopen it after

I just tested with plugin default objects on a nearly plugin-free server

**Comment by LoneDev6** [comment]
Non trovo "Lingotto di Zinco" tra gli oggetti dei file che mi hai mandato

**Comment by poityTMK** [comment]
@LoneDev6 come ho scritto nel messaggio precedente il bug è riproducibile anche con gli oggetti di deafult come il coltello e la patata, allego il file mancante
[ingots.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/7462474/ingots.zip)

**Comment by poityTMK** [comment]
@LoneDev6 c'è un modo per la quale possa dimostartelo "di persona"?

**Comment by Scot-Survivor** [comment]
Can confirm this is still happening to this day, 
ItemsAdder version 3.2.2-beta5
Let me know if you need more information you need

**Comment by LoneDev6** [comment]
Provide a log of when " the zip was already loading in process" message appears.
I need to get info on what failed to load to help you.
