### ISSUE TITLE
[BUG] Overrides lefthand placing

### ISSUE THREAD

**Issue by LogGits** [PluginBugs/Issues-ItemsAdder#1292]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?
2 bugs in 1 report:
1) Typically when holding two placeable items, the item in the main hand is used when placed. With a custom itemsadder block in my main hand and another placeable item in my offhand, if i press right click (even shift right click) it places my left hand then the itemsadder block will override the thing placed.

2) I was also able to place the block on wall attached things (e.g. torches attached to wall)

### Steps to reproduce the issue

- Hold torch in offhand
- Hold custom itemsadder block in main hand
- Try to place the itemsadder block
(it will place the torch then the itemsadder block will replace the torch)

### Server version

This server is running Paper version git-Paper-353 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: f2cb9cb)

### ItemsAdder Version

ItemsAdder version 2.4.20

### ProtocolLib Version

ProtocolLib 4.7.0

### LoneLibs Version

LoneLib 1.0.15

### Screenshots/Videos (you can drag and drop files or paste links)

As seen in [this video](https://gyazo.com/8c5f8b2155f6c4883cc6f8cfee8b0b22) and somewhat relates to this [issue](https://gyazo.com/c6fa64dbe23976b23197418c861f2923).

**Comment by LoneDev6** [comment]
The first issue is just a clientside desync.
Basically the game predicts the placement of the offhand item and thinks the torch was placed.
If you press F you can clearly see the torch reappear in the inventory, it wasn't placed.


The second issue:
Seems ItemsAdder for some reasons thinks the torch is a "replaceable" block (like plants), so it replaces it with the itemsadder block. I'll fix it in the next update.

**Comment by LoneDev6** [comment]
## Fix for first problem:
Note: I cannot disable the placing animation for the left hand item even if it's not actually placed.

https://user-images.githubusercontent.com/27242001/139867239-0b00199c-e436-4577-a68d-986cf0bd9d3c.mp4



## Fix for the second problem:

https://user-images.githubusercontent.com/27242001/139867841-d8472174-72fa-4d93-bbad-7689710acbcb.mp4
