### ISSUE TITLE
About Resourcepack External-host ! Important !

### ISSUE THREAD

**Issue by IPECTER** [PluginBugs/Issues-ItemsAdder#1297]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

이팩터@5621

### Describe the solution you'd like

Important....
Can use it on server.properties.
There's a direct download link that can't be used in IA's config.
I hope it will be resolved in the next update.
If you want, I can give you a few direct download links.
Link is using "the cloud in Korea" and "onedrive".
They're both links that I changed to "direct download link".

### Is your feature request related to a problem?

I must use fast resourcepack hosting.. but I can't use fast cloud in IA

### Describe alternatives you've considered

make Logic like bukkit

**Comment by LoneDev6** [comment]
config.yml of itemsadder:
```yml
    external-host:
      enabled: true
      url: 'YOUR URL HERE'
```

**Comment by IPECTER** [comment]
> config.yml of itemsadder:
> 
> ```yaml
>     external-host:
>       enabled: true
>       url: 'YOUR URL HERE'
> ```

.... I mean THIS IS NOT WORK!
I mean that Some link is work well in server.properties 
but 
not working in  external-host

**Comment by LoneDev6** [comment]
I need to know your url...
This works for other 1000 servers

**Comment by LoneDev6** [comment]
Anyway, since you're in Korea, why not using self-host?
It's easier to use and faster. And works fine in Korea.

**Comment by IPECTER** [comment]
> Anyway, since you're in Korea, why not using self-host? It's easier to use and faster. And works fine in Korea.

There are no security issues with self-host, right?
Example, It's a problem where the ip of the server is revealed.

**Comment by IPECTER** [comment]
> I need to know your URL... This works for other 1000 servers, there is a problem with your URL. I can't help you without this information.

This is a method that's not used very well.

It's a direct-download link to "OneDrive".

https\://onedrive.live.com/download?cid\=BA7D3A1C922D4025&resid\=BA7D3A1C922D4025%211262&authkey\=AFNyP5Fk502c4pg

When I approach the link, sometime it takes a long time to load.
But it's very fast to download in any country.

**Comment by LoneDev6** [comment]
I'm working on it:
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1308

**Comment by IPECTER** [comment]
Thx!!!!!
