### ISSUE TITLE
GearPlus textures

### ISSUE THREAD

**Issue by 100petr** [PluginBugs/Issues-ItemsAdder#1300]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

pitilon#6950

### What happened?

After upgrading to version 2.4.21c, the elytra texture from GearPlus (https://www.spigotmc.org/resources/gearplus-elytras-itemsadder-add-on.94293/) is not displayed. There is no problem with version 2.4.20. I'm not sure if this is an IA or addon bug.

### Steps to reproduce the issue

Install GearPlus (https://www.spigotmc.org/resources/gearplus-elytras-itemsadder-add-on.94293/)
/iaget green
No texture

### Server version

 This server is running Purpur version git-Purpur-1423 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6cbba00 on ver/1.17.1)

### ItemsAdder Version

2.4.21c

### ProtocolLib Version

4.7.1-SNAPSHOT-b530

### LoneLibs Version

1.0.15

**Comment by 100petr** [comment]
yes i have optifine. and I write that in the last version there was no problem

**Comment by 100petr** [comment]
![image](https://user-images.githubusercontent.com/29830635/141611998-82bfdc9b-f6b3-4b83-ab3f-b847d54167da.png)
![image](https://user-images.githubusercontent.com/29830635/141612161-5b1ab0ca-818c-46ed-9b5f-977fa8226ce8.png)

**Comment by 100petr** [comment]
hi, I don't want to bother you, but is there anything new? it prevents me from updating the plugin

**Comment by LoneDev6** [comment]
![immagine](https://user-images.githubusercontent.com/27242001/143031935-0b9fbbe4-d57c-40e0-a859-0102db363df9.png)

![immagine](https://user-images.githubusercontent.com/27242001/143031949-60f4b00c-f790-4246-bdcb-b01795ee6da6.png)


Works fine on 2.4.23 and 1.17.1

**Comment by 100petr** [comment]
so it was probably a problem that is already fixed, thanks
