### ISSUE TITLE
Placing furniture on block with a flower placed on it 

### ISSUE THREAD

**Issue by GHsorryiwon12345** [PluginBugs/Issues-ItemsAdder#1304]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

eNji#7430

### What happened?

Placing furniture on block with a flower placed on it results a furniture place without a border

### Steps to reproduce the issue

1. place a grass with a flower on it
2. place a furniture on the same exact grass block

### Server version

This server is running Airplane version git-Airplane-81 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 2386904 on HEAD)
Unknown version

### ItemsAdder Version

2.4.21c

### ProtocolLib Version

4.7.0

### LoneLibs Version

1.0.15

### LightAPI Version (optional)

-

### LibsDisguises Version (optional)

-

### FULL server log

not needed

### Error (optional)

```shell
not needed
```

### ItemsAdder config.yml

```shell
not needed
```

### Problematic items yml configuration file (optional)

```shell
not needed
```

### Other files, you can drag and drop them here to upload. (optional)

not needed

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/43861907/140773706-1b7c3c76-e68a-45ee-aad7-49a45af8c908.png)

**Comment by LoneDev6** [comment]
Thanks, will be fixed
