### ISSUE TITLE
Pickaxes and axes mining configuration (mining efficiency)

### ISSUE THREAD

**Issue by vdl19** [PluginBugs/Issues-ItemsAdder#1313]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Hello, from the start I have been using the swords, shields and armor of the plugin because I have access to their configuration to balance them as I need with the settings below for the swords for example:

    durability:
      max_custom_durability: 3000
    attribute_modifiers:
      mainhand:
        attackDamage: 10.0
        attackSpeed: 1.8
        
- I never put the picks, axes or shovels because I did not have its settings to change.
So can I add the missing settings like with Swords?

- I think so, but above all are the sword settings the only ones useful?
Because damage and speed and durability are good but is the efficiency in mining or cutting trees for axes related to attackDamage where then you need another line in addition for efficiency to mine or cut down trees?
What makes me doubt that this is enough is that the crystal tools are based on the wooden pickaxe and ax and all the others are on diamond.
So I think to myself that the concern could be that all pickaxes and axes have the same efficiency as the diamond one apart from the durability, damage and speed that I could put in?

> So is there another line added for "miningSpeed" and can I add the lines like swords already?

Example that I could add as lines? :

  spinel_pickaxe:
    display_name: display-name-spinel_pickaxe
    permission: spinel_pickaxe
    resource:
      material: DIAMOND_PICKAXE
      generate: true
      textures:
      - item/spinel_pickaxe.png
    _durability:
      max_custom_durability: 1800
    attribute_modifiers:
      mainhand:
        attackDamage: 7.0
        attackSpeed: 1.9_
		**? minage ?: ?**

### Is your feature request related to a problem?

As to explain for me it is a problem which prevents me from making the pickaxes, axes and shovels available for the players because I cannot configure them sufficiently to make them logical in their evolution at the mining level (I believe that cutting a tree is it considered mining?)

### Describe alternatives you've considered

Until now it is not to give the pickaxes, axes and shovels available to players despite their request.

**Comment by LoneDev6** [comment]
You can achieve this by enchanting the pickaxe with [DIG_SPEED](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/enchantments/Enchantment.html#DIG_SPEED) and hiding it using 
```yml
    item_flags:
      - HIDE_ENCHANTS
```

This is the only way in Minecraft to achieve this.

**Comment by vdl19** [comment]
Hi, ok i had seen this possibility on other requests, it wasn't really my preference, but i had another thought on commissioning pickaxes, i will just use durability and what it is on bases itself as a diamond or netherite pickaxe and it had to be fine with me.
Good day

**Comment by purejosh** [comment]
**dig_speed** is not **efficiency**. Where are you getting these words? They should be synonymous with vanilla minecraft definitions. Efficiency, unbreaking, smite, sharpness, etc.

**Comment by LoneDev6** [comment]
I think I misunderstood the request.

Anyway `attribute_modifiers` contains the vanilla Minecraft attribute modifiers, you can get them from the [official wiki](https://minecraft.fandom.com/wiki/Attribute#Modifiers).

If you want to increase the mining speed you can apply the HASTE potion effect to the player when they hold the pickaxe and remove it when they stop holding it.
Here is an example of a working item: https://github.com/PluginBugs/Issues-ItemsAdder/issues/1033#issuecomment-879082140
