### ISSUE TITLE
FURNITURE BUGS in 2.4.21c and 2.4.22BETA

### ISSUE THREAD

**Issue by TeiBri** [PluginBugs/Issues-ItemsAdder#1318]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

Good day. I have 4 furniture errors here. (There is a video for everyone)
(Sorry, there are textures from OriginRealms, I know they can't be used and I won't use them for a public server. I appreciate their work.) :-)

1, SAVE
When I build furniture, for example (a table and a chair next to it) and turn off the server, after returning to the server it is no longer furniture, but only BARRIER and PAPER or LEATHER_HORSE_ARMOR. (Console does not report any errors)

2, Possibility to sit on all barriers
Option: sit_all_solid_blocks: true is invalid in this version.
(You can see it in video 2)

3, Wrong layout barrier for furniture with more than 1 barrier.
I created sample furniture (Sofa Chair).
In video 3 you can see that I am laying a Sofa Chair with Fixed_rotation from every angle. From some angles the barrier blocks are well built and from some they are shifted.
YML file Sofa Chair is in Problematic items yml configuration file (optional)

4/ (EDIT) I don't know if this is an error now, but why can't I paint the furniture LEATHER_HORSE_ARMOR now?

### Steps to reproduce the issue

In this problem is more problems. I cant do it.

### Server version

This server is running CraftBukkit version 3277-Spigot-3892929-2071671 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)

### ItemsAdder Version

2.4.21c

### ProtocolLib Version

4.7.0

### LoneLibs Version

1.0.15

### LightAPI Version (optional)

LightAPI Fork 3.5.2

### LibsDisguises Version (optional)

This plugin isnt on my server.

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/7556317/latest.log)

### Error (optional)

```shell
The plugin does not report any issues.
```

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: false
      server-ip: 127.0.0.1
      pack-port: 8163
    external-host:
      enabled: true
      url: (((My pack :D)))
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-items: false
  extract-default-resources: false
  minify-json: true
blocks:
  light-api: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: false
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
```

### Problematic items yml configuration file (optional)

```shell
sofa_chair:
    display_name: Sofa Chair
    resource:
      material: LEATHER_HORSE_ARMOR
      generate: false
      model_path: custom/furniture/sofa_chair
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        light_level: 0
        entity: item_frame
        hitbox:
          length: 1
          width: 2
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true 
      furniture_sit:
        sit_height: 0.9
        sit_all_solid_blocks: true
```

### Screenshots/Videos (you can drag and drop files or paste links)

Video for the FIRST ERROR:
https://user-images.githubusercontent.com/62265168/142264007-023fcc20-f54b-4fb7-8f02-eb3f7050e808.mp4

Video for the SECOND ERROR:
https://user-images.githubusercontent.com/62265168/142264105-2c93ebee-e016-42a1-ab84-a5690b6113c3.mp4

Video for the THIRD ERROR:
https://user-images.githubusercontent.com/62265168/142264239-a829f124-7bd8-4e66-b29e-2a9d08f5edbd.mp4

**Comment by TeiBri** [comment]
I tested it in the new version 2.4.22BETA and it's wrong too.

**Comment by LoneDev6** [comment]
> 1, SAVE
When I build furniture, for example (a table and a chair next to it) and turn off the server, after returning to the server it is no longer furniture, but only BARRIER and PAPER or LEATHER_HORSE_ARMOR. (Console does not report any errors)

I don't understand, basically your furnitures disappear on restart? And only the barrier is kept? This seems to be a problem related to another plugin cleaning up entities for some reason


> 2, Possibility to sit on all barriers
Option: sit_all_solid_blocks: true is invalid in this version.
(You can see it in video 2)


The hitbox is wrong.
![immagine](https://user-images.githubusercontent.com/27242001/143050888-2efd90f5-a462-459b-b71b-0e63beaa7620.png)
Always use /iahitbox command when you are testing your furniture, it shows the hitbox.
This is the correct hitbox: 
![immagine](https://user-images.githubusercontent.com/27242001/143051038-92bafa25-90f7-4677-9466-c6cc2a591e7e.png)
```yml
        hitbox:
          length: 1
          width: 2
          height: 1
          width_offset: 0.5
```

Anyway I have one advice: Do not use item_frame as base for your furniture.
item_frame is used to create furniture which can be attached to walls and ceiling and needs to be rotated freely by the player based on the surface where they get attached to. [Also read here](https://itemsadder.devs.beer/plugin-usage/adding-content/advanced/furniture/furniture-collisions#hitboxes-limitations).
armor_stand is used to create normal furniture which will be placed on the ground.

Now I added this info clearly on the wiki to avoid confusion: https://itemsadder.devs.beer/plugin-usage/adding-content/advanced/furniture/furniture-entity





> 3, Wrong layout barrier for furniture with more than 1 barrier.
I created sample furniture (Sofa Chair).
In video 3 you can see that I am laying a Sofa Chair with Fixed_rotation from every angle. From some angles the barrier blocks are well built and from some they are shifted.
YML file Sofa Chair is in Problematic items yml configuration file (optional)

same as before, fix the hitbox configuration 



> 4/ (EDIT) I don't know if this is an error now, but why can't I paint the furniture LEATHER_HORSE_ARMOR now?

I recently introduced a fix which prevents custom player armors items to be recolored to avoid people from recoloring custom armors to change their appearance and scam people by selling fake armors.
I will now add a fix to allow LEATHER_HORSE_ARMOR to be colored 👍🏻 this wasn't intended
