### ISSUE TITLE
Bug with RPGhuds with Nummber thousands

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#1322]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

SLoKer#5953

### What happened?

When you have 1000 on any kind of placeholder the logo will start to move like this vid
![bug222222dd](https://user-images.githubusercontent.com/68678154/142603049-9a04b3d4-4ae6-4719-93a4-b105c78b62cb.gif)
eo

### Steps to reproduce the issue

/eco set SLoKerYT 1000
/eco take SLoKerYT 1000

### Server version

This server is running Paper version git-Paper-378 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc2ecbc)
You are 8 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-372 (MC: 1.17.1)

### ItemsAdder Version

2.4.22

### ProtocolLib Version

4.7.0

### LoneLibs Version

1.0.15

**Comment by LoneDev6** [comment]
It has to do with your economy plugin, I need your RPGhuds configuration btw.

It works fine with Vault and EssentialsX

**Comment by SNokerYT** [comment]
[rpghuds.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/7584192/rpghuds.zip)

**Comment by LoneDev6** [comment]
> It has to do with your economy plugin, I need your RPGhuds configuration btw.
It works fine with Vault and EssentialsX

**Comment by LoneDev6** [comment]
@SNokerYT I see you didn't join the beta 2.4.23, did you check it? It has a fix for the shifting issue
