### ISSUE TITLE
"Durabilty" is no longer displayed 2.4.22

### ISSUE THREAD

**Issue by vdl19** [PluginBugs/Issues-ItemsAdder#1328]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

Hello, with version 2.4.22 there is a problem with displaying the "durability" for armor, shield and equipment also from minecraft (unless they wear out there it is displayed).
- Swords from itemsAdder do not have this problem.
- I just have the durability visible on the mysterious boots in the AI ​​menu!
- If I update version 2.4.21c I no longer have a problem with displaying the "Durability"

### Steps to reproduce the issue

Install 2.4.22 and check durability in the shield and armor AI menu and also in the Minecraft creative menu by having done F3 + H before.

### Server version

This server is running Paper version git-Paper-388 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 22aaf91)

### ItemsAdder Version

ItemsAdder version 2.4.22

### ProtocolLib Version

ProtocolLib version 4.7.1-SNAPSHOT-b536

### LoneLibs Version

LoneLibs version 1.0.15

### LightAPI Version (optional)

LightAPI version bukkit-5.0.0 (build SNAPSHOT)

### LibsDisguises Version (optional)

ibsDisguises version 10.0.26-SNAPSHOT

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/7587135/latest.log)

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: 146.59.138.51
      pack-port: 30070
    external-host:
      enabled: false
      url: ''
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: false
    hide-hud: true
    cancel-movement: true
    lock-player: true
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
    protect-file-from-unzip:
      enabled: true
      extreme: true
    overwrite-vanilla-models: true
    overwrite-vanilla-lang-json: true
    compress-png-files: true
    compress-json-files: true
    generate-custom-armors-textures:
      _: 'Available values: VANILLA_1_17 or OPTIFINE'
      enabled: true
      mode: VANILLA_1_17
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
  command:
    usage-cooldown-seconds: 60
config_files:
  lang: fr
  dictionaries-lang: fr
  extract-default-items: true
  extract-default-resources: true
blocks:
  light-api: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    seach-also-in-these-biomes: {}
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
      - DARK_FOREST
      - JUNGLE
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
recipes:
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
  hide-vanilla-unrecognized-recipe-errors: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
```

### Other files, you can drag and drop them here to upload. (optional)

**armors.yml **

info:
  namespace: itemsadder
recipes:
  crafting_table:
    ruby_head:
      permission: itemsadder.ruby_head
      enabled: true
      pattern:
      - rrr
      - rXr
      - XXX
      ingredients:
        r: itemsadder:ruby
      result:
        item: itemsadder:ruby_head
        amount: 1
    ruby_chest:
      permission: itemsadder.ruby_chest
      enabled: true
      pattern:
      - rXr
      - rrr
      - rrr
      ingredients:
        r: itemsadder:ruby
      result:
        item: itemsadder:ruby_chest
        amount: 1
    ruby_legs:
      permission: itemsadder.ruby_legs
      enabled: true
      pattern:
      - rrr
      - rXr
      - rXr
      ingredients:
        r: itemsadder:ruby
      result:
        item: itemsadder:ruby_legs
        amount: 1
    ruby_boots:
      permission: itemsadder.ruby_boots
      enabled: true
      pattern:
      - XXX
      - rXr
      - rXr
      ingredients:
        r: itemsadder:ruby
      result:
        item: itemsadder:ruby_boots
        amount: 1
    spinel_head:
      permission: itemsadder.spinel_head
      enabled: true
      pattern:
      - rrr
      - rXr
      - XXX
      ingredients:
        r: itemsadder:spinel
      result:
        item: itemsadder:spinel_head
        amount: 1
    spinel_chest:
      permission: itemsadder.spinel_chest
      enabled: true
      pattern:
      - rXr
      - rrr
      - rrr
      ingredients:
        r: itemsadder:spinel
      result:
        item: itemsadder:spinel_chest
        amount: 1
    spinel_legs:
      permission: itemsadder.spinel_legs
      enabled: true
      pattern:
      - rrr
      - rXr
      - rXr
      ingredients:
        r: itemsadder:spinel
      result:
        item: itemsadder:spinel_legs
        amount: 1
    spinel_boots:
      permission: itemsadder.spinel_boots
      enabled: true
      pattern:
      - XXX
      - rXr
      - rXr
      ingredients:
        r: itemsadder:spinel
      result:
        item: itemsadder:spinel_boots
        amount: 1
    turquoise_head:
      permission: itemsadder.turquoise_head
      enabled: true
      pattern:
      - rrr
      - rXr
      - XXX
      ingredients:
        r: itemsadder:turquoise
      result:
        item: itemsadder:turquoise_head
        amount: 1
    turquoise_chest:
      permission: itemsadder.turquoise_chest
      enabled: true
      pattern:
      - rXr
      - rrr
      - rrr
      ingredients:
        r: itemsadder:turquoise
      result:
        item: itemsadder:turquoise_chest
        amount: 1
    turquoise_legs:
      permission: itemsadder.turquoise_legs
      enabled: true
      pattern:
      - rrr
      - rXr
      - rXr
      ingredients:
        r: itemsadder:turquoise
      result:
        item: itemsadder:turquoise_legs
        amount: 1
    turquoise_boots:
      permission: itemsadder.turquoise_boots
      enabled: true
      pattern:
      - XXX
      - rXr
      - rXr
      ingredients:
        r: itemsadder:turquoise
      result:
        item: itemsadder:turquoise_boots
        amount: 1
    aqua_head:
      permission: itemsadder.aqua_head
      enabled: true
      pattern:
      - rrr
      - rXr
      - XXX
      ingredients:
        r: itemsadder:aqua_aura
      result:
        item: itemsadder:aqua_head
        amount: 1
    aqua_chest:
      permission: itemsadder.aqua_chest
      enabled: true
      pattern:
      - rXr
      - rrr
      - rrr
      ingredients:
        r: itemsadder:aqua_aura
      result:
        item: itemsadder:aqua_chest
        amount: 1
    aqua_legs:
      permission: itemsadder.aqua_legs
      enabled: true
      pattern:
      - rrr
      - rXr
      - rXr
      ingredients:
        r: itemsadder:aqua_aura
      result:
        item: itemsadder:aqua_legs
        amount: 1
    aqua_boots:
      permission: itemsadder.aqua_boots
      enabled: true
      pattern:
      - XXX
      - rXr
      - rXr
      ingredients:
        r: itemsadder:aqua_aura
      result:
        item: itemsadder:aqua_boots
        amount: 1
    amethyst_head:
      permission: itemsadder.amethyst_head
      enabled: true
      pattern:
      - rrr
      - rXr
      - XXX
      ingredients:
        r: itemsadder:amethyst
      result:
        item: itemsadder:amethyst_head
        amount: 1
    amethyst_chest:
      permission: itemsadder.amethyst_chest
      enabled: true
      pattern:
      - rXr
      - rrr
      - rrr
      ingredients:
        r: itemsadder:amethyst
      result:
        item: itemsadder:amethyst_chest
        amount: 1
    amethyst_legs:
      permission: itemsadder.amethyst_legs
      enabled: true
      pattern:
      - rrr
      - rXr
      - rXr
      ingredients:
        r: itemsadder:amethyst
      result:
        item: itemsadder:amethyst_legs
        amount: 1
    amethyst_boots:
      permission: itemsadder.amethyst_boots
      enabled: true
      pattern:
      - XXX
      - rXr
      - rXr
      ingredients:
        r: itemsadder:amethyst
      result:
        item: itemsadder:amethyst_boots
        amount: 1
    emerald_head:
      permission: itemsadder.emerald_head
      enabled: true
      pattern:
      - rrr
      - rsr
      - XXX
      ingredients:
        r: EMERALD_BLOCK
        s: mysterious_material
      result:
        item: itemsadder:emerald_head
        amount: 1
    emerald_chest:
      permission: itemsadder.emerald_chest
      enabled: true
      pattern:
      - rsr
      - rrr
      - rrr
      ingredients:
        r: EMERALD_BLOCK
        s: mysterious_material
      result:
        item: itemsadder:emerald_chest
        amount: 1
    emerald_legs:
      permission: itemsadder.emerald_legs
      enabled: true
      pattern:
      - rrr
      - rsr
      - rXr
      ingredients:
        r: EMERALD_BLOCK
        s: mysterious_material
      result:
        item: itemsadder:emerald_legs
        amount: 1
    emerald_boots:
      permission: itemsadder.emerald_boots
      enabled: true
      pattern:
      - XXX
      - rXr
      - rsr
      ingredients:
        r: EMERALD_BLOCK
        s: mysterious_material
      result:
        item: itemsadder:emerald_boots
        amount: 1
    obsidian_head:
      permission: itemsadder.obsidian_head
      enabled: true
      pattern:
      - rrr
      - rXr
      - XXX
      ingredients:
        r: OBSIDIAN
      result:
        item: itemsadder:obsidian_head
        amount: 1
    obsidian_chest:
      permission: itemsadder.obsidian_chest
      enabled: true
      pattern:
      - rXr
      - rrr
      - rrr
      ingredients:
        r: OBSIDIAN
      result:
        item: itemsadder:obsidian_chest
        amount: 1
    obsidian_legs:
      permission: itemsadder.obsidian_legs
      enabled: true
      pattern:
      - rrr
      - rXr
      - rXr
      ingredients:
        r: OBSIDIAN
      result:
        item: itemsadder:obsidian_legs
        amount: 1
    obsidian_boots:
      permission: itemsadder.obsidian_boots
      enabled: true
      pattern:
      - XXX
      - rXr
      - rXr
      ingredients:
        r: OBSIDIAN
      result:
        item: itemsadder:obsidian_boots
        amount: 1
    bronze_head:
      permission: itemsadder.bronze_head
      enabled: true
      pattern:
      - rrr
      - rXr
      - XXX
      ingredients:
        r: itemsadder:bronze_ingot
      result:
        item: itemsadder:bronze_head
        amount: 1
    bronze_chest:
      permission: itemsadder.bronze_chest
      enabled: true
      pattern:
      - rXr
      - rrr
      - rrr
      ingredients:
        r: itemsadder:bronze_ingot
      result:
        item: itemsadder:bronze_chest
        amount: 1
    bronze_legs:
      permission: itemsadder.bronze_legs
      enabled: true
      pattern:
      - rrr
      - rXr
      - rXr
      ingredients:
        r: itemsadder:bronze_ingot
      result:
        item: itemsadder:bronze_legs
        amount: 1
    bronze_boots:
      permission: itemsadder.bronze_boots
      enabled: true
      pattern:
      - XXX
      - rXr
      - rXr
      ingredients:
        r: itemsadder:bronze_ingot
      result:
        item: itemsadder:bronze_boots
        amount: 1
  anvil_repair:
    ruby_head:
      permission: itemsadder.ruby_head
      ingredient: ruby
      item: itemsadder:ruby_head
    ruby_chest:
      permission: itemsadder.ruby_chest
      ingredient: ruby
      item: itemsadder:ruby_chest
    ruby_legs:
      permission: itemsadder.ruby_legs
      ingredient: ruby
      item: itemsadder:ruby_legs
    ruby_boots:
      permission: itemsadder.ruby_boots
      ingredient: ruby
      item: itemsadder:ruby_boots
    spinel_head:
      permission: itemsadder.spinel_head
      ingredient: spinel
      item: itemsadder:spinel_head
    spinel_chest:
      permission: itemsadder.spinel_chest
      ingredient: spinel
      item: itemsadder:spinel_chest
    spinel_legs:
      permission: itemsadder.spinel_legs
      ingredient: spinel
      item: itemsadder:spinel_legs
    spinel_boots:
      permission: itemsadder.spinel_boots
      ingredient: spinel
      item: itemsadder:spinel_boots
    turquoise_head:
      permission: itemsadder.turquoise_head
      ingredient: turquoise
      item: itemsadder:turquoise_head
    turquoise_chest:
      permission: itemsadder.turquoise_chest
      ingredient: turquoise
      item: itemsadder:turquoise_chest
    turquoise_legs:
      permission: itemsadder.turquoise_legs
      ingredient: turquoise
      item: itemsadder:turquoise_legs
    turquoise_boots:
      permission: itemsadder.turquoise_boots
      ingredient: turquoise
      item: itemsadder:turquoise_boots
    aqua_head:
      permission: itemsadder.aqua_head
      ingredient: aqua_aura
      item: itemsadder:aqua_head
    aqua_chest:
      permission: itemsadder.aqua_chest
      ingredient: aqua_aura
      item: itemsadder:aqua_chest
    aqua_legs:
      permission: itemsadder.aqua_legs
      ingredient: aqua_aura
      item: itemsadder:aqua_legs
    aqua_boots:
      permission: itemsadder.aqua_boots
      ingredient: aqua_aura
      item: itemsadder:aqua_boots
    amethyst_head:
      permission: itemsadder.amethyst_head
      ingredient: amethyst
      item: itemsadder:amethyst_head
    amethyst_chest:
      permission: itemsadder.amethyst_chest
      ingredient: amethyst
      item: itemsadder:amethyst_chest
    amethyst_legs:
      permission: itemsadder.amethyst_legs
      ingredient: amethyst
      item: itemsadder:amethyst_legs
    amethyst_boots:
      permission: itemsadder.amethyst_boots
      ingredient: amethyst
      item: itemsadder:amethyst_boots
    emerald_head:
      permission: itemsadder.emerald_head
      ingredient: mysterious_material
      item: itemsadder:emerald_head
    emerald_chest:
      permission: itemsadder.emerald_chest
      ingredient: mysterious_material
      item: itemsadder:emerald_chest
    emerald_legs:
      permission: itemsadder.emerald_legs
      ingredient: mysterious_material
      item: itemsadder:emerald_legs
    emerald_boots:
      permission: itemsadder.emerald_boots
      ingredient: mysterious_material
      item: itemsadder:emerald_boots
    obsidian_head:
      permission: itemsadder.obsidian_head
      ingredient: OBSIDIAN
      item: itemsadder:obsidian_head
    obsidian_chest:
      permission: itemsadder.obsidian_chest
      ingredient: OBSIDIAN
      item: itemsadder:obsidian_chest
    obsidian_legs:
      permission: itemsadder.obsidian_legs
      ingredient: OBSIDIAN
      item: itemsadder:obsidian_legs
    obsidian_boots:
      permission: itemsadder.obsidian_boots
      ingredient: OBSIDIAN
      item: itemsadder:obsidian_boots
    bronze_head:
      permission: itemsadder.bronze_head
      ingredient: bronze_ingot
      item: itemsadder:bronze_head
    bronze_chest:
      permission: itemsadder.bronze_chest
      ingredient: bronze_ingot
      item: itemsadder:bronze_chest
    bronze_legs:
      permission: itemsadder.bronze_legs
      ingredient: bronze_ingot
      item: itemsadder:bronze_legs
    bronze_boots:
      permission: itemsadder.bronze_boots
      ingredient: bronze_ingot
      item: itemsadder:bronze_boots  
items:
  ruby_head:
    display_name: display-name-ruby_head
    permission: rubyarmor
    resource:
      generate: true
    durability:
      max_custom_durability: 550
    specific_properties:
      armor:
        slot: head
        color: ff0000
    attribute_modifiers:
      head:
        armor: 3
        armorToughness: 3
  ruby_chest:
    display_name: display-name-ruby_chest
    permission: rubyarmor
    resource:
      generate: true
    durability:
      max_custom_durability: 700
    specific_properties:
      armor:
        slot: chest
        color: ff0000
    attribute_modifiers:
      chest:
        armor: 8
        armorToughness: 3
  ruby_legs:
    display_name: display-name-ruby_legs
    permission: rubyarmor
    resource:
      generate: true
    durability:
      max_custom_durability: 650
    specific_properties:
      armor:
        slot: legs
        color: ff0000
    attribute_modifiers:
      legs:
        armor: 6
        armorToughness: 3
  ruby_boots:
    display_name: display-name-ruby_boots
    permission: rubyarmor
    resource:
      generate: true
    durability:
      max_custom_durability: 500
    specific_properties:
      armor:
        slot: FEET
        color: ff0000
    attribute_modifiers:
      feet:
        armor: 3
        armorToughness: 3
  spinel_head:
    display_name: display-name-spinel_head
    permission: spinelarmor
    resource:
      generate: true
    durability:
      max_custom_durability: 650
    specific_properties:
      armor:
        slot: head
        color: ff7e7e
    attribute_modifiers:
      head:
        armor: 4
        armorToughness: 3
  spinel_chest:
    display_name: display-name-spinel_chest
    permission: spinelarmor
    resource:
      generate: true
    durability:
      max_custom_durability: 800
    specific_properties:
      armor:
        slot: chest
        color: ff7e7e
    attribute_modifiers:
      chest:
        armor: 8
        armorToughness: 3
  spinel_legs:
    display_name: display-name-spinel_legs
    permission: spinelarmor
    resource:
      generate: true
    durability:
      max_custom_durability: 750
    specific_properties:
      armor:
        slot: legs
        color: ff7e7e
    attribute_modifiers:
      legs:
        armor: 6
        armorToughness: 3
  spinel_boots:
    display_name: display-name-spinel_boots
    permission: spinelarmor
    resource:
      generate: true
    durability:
      max_custom_durability: 700
    specific_properties:
      armor:
        slot: FEET
        color: ff7e7e
    attribute_modifiers:
      feet:
        armor: 4
        armorToughness: 3
  turquoise_head:
    display_name: display-name-turquoise_head
    permission: turquoisearmor
    resource:
      generate: true
    durability:
      max_custom_durability: 850
    specific_properties:
      armor:
        slot: head
        color: 75bebe
    attribute_modifiers:
      head:
        armor: 5
        armorToughness: 4
  turquoise_chest:
    display_name: display-name-turquoise_chest
    permission: turquoisearmor
    resource:
      generate: true
    durability:
      max_custom_durability: 1000
    specific_properties:
      armor:
        slot: chest
        color: 75bebe
    attribute_modifiers:
      chest:
        armor: 9
        armorToughness: 4
  turquoise_legs:
    display_name: display-name-turquoise_legs
    permission: turquoisearmor
    resource:
      generate: true
    durability:
      max_custom_durability: 850
    specific_properties:
      armor:
        slot: legs
        color: 75bebe
    attribute_modifiers:
      legs:
        armor: 7
        armorToughness: 4
  turquoise_boots:
    display_name: display-name-turquoise_boots
    permission: turquoisearmor
    resource:
      generate: true
    durability:
      max_custom_durability: 900
    specific_properties:
      armor:
        slot: FEET
        color: 75bebe
    attribute_modifiers:
      feet:
        armor: 5
        armorToughness: 4
  aqua_head:
    display_name: display-name-aqua_head
    permission: aquaarmor
    resource:
      generate: true
    durability:
      max_custom_durability: 450
    specific_properties:
      armor:
        slot: head
        color: 16d4ff
    attribute_modifiers:
      head:
        armor: 3
        armorToughness: 2
  aqua_chest:
    display_name: display-name-aqua_chest
    permission: aquaarmor
    resource:
      generate: true
    durability:
      max_custom_durability: 600
    specific_properties:
      armor:
        slot: chest
        color: 16d4ff
    attribute_modifiers:
      chest:
        armor: 8
        armorToughness: 3
  aqua_legs:
    display_name: display-name-aqua_legs
    permission: aquaarmor
    resource:
      generate: true
    durability:
      max_custom_durability: 550
    specific_properties:
      armor:
        slot: legs
        color: 16d4ff
    attribute_modifiers:
      legs:
        armor: 6
        armorToughness: 3
  aqua_boots:
    display_name: display-name-aqua_boots
    permission: aquaarmor
    resource:
      generate: true
    durability:
      max_custom_durability: 500
    specific_properties:
      armor:
        slot: FEET
        color: 16d4ff
    attribute_modifiers:
      feet:
        armor: 3
        armorToughness: 2
  amethyst_head:
    display_name: display-name-amethyst_head
    permission: amethystarmor
    resource:
      generate: true
    durability:
      max_custom_durability: 950
    specific_properties:
      armor:
        slot: head
        color: '530766'
    attribute_modifiers:
      head:
        armor: 5
        armorToughness: 5
  amethyst_chest:
    display_name: display-name-amethyst_chest
    permission: amethystarmor
    resource:
      generate: true
    durability:
      max_custom_durability: 1100
    specific_properties:
      armor:
        slot: chest
        color: '530766'
    attribute_modifiers:
      chest:
        armor: 10
        armorToughness: 5
  amethyst_legs:
    display_name: display-name-amethyst_legs
    permission: amethystarmor
    resource:
      generate: true
    durability:
      max_custom_durability: 950
    specific_properties:
      armor:
        slot: legs
        color: '530766'
    attribute_modifiers:
      legs:
        armor: 8
        armorToughness: 5
  amethyst_boots:
    display_name: display-name-amethyst_boots
    permission: amethystarmor
    resource:
      generate: true
    durability:
      max_custom_durability: 1000
    specific_properties:
      armor:
        slot: FEET
        color: '530766'
    attribute_modifiers:
      feet:
        armor: 5
        armorToughness: 5
  emerald_head:
    display_name: display-name-emerald_head
    permission: emeraldhead
    resource:
      generate: true
    durability:
      max_custom_durability: 1200
    specific_properties:
      armor:
        slot: head
        color: 00ff72
    attribute_modifiers:
      head:
        armor: 6
        armorToughness: 5
  emerald_chest:
    display_name: display-name-emerald_chest
    permission: emeraldarmor
    resource:
      generate: true
    durability:
      max_custom_durability: 1300
    specific_properties:
      armor:
        slot: chest
        color: 00ff72
    attribute_modifiers:
      chest:
        armor: 11
        armorToughness: 5
  emerald_legs:
    display_name: display-name-emerald_legs
    permission: emeraldarmor
    resource:
      generate: true
    durability:
      max_custom_durability: 1200
    specific_properties:
      armor:
        slot: legs
        color: 00ff72
    attribute_modifiers:
      legs:
        armor: 9
        armorToughness: 5
  emerald_boots:
    display_name: display-name-emerald_boots
    permission: emeraldarmor
    resource:
      generate: true
    durability:
      max_custom_durability: 1200
    specific_properties:
      armor:
        slot: FEET
        color: 00ff72
    attribute_modifiers:
      feet:
        armor: 6
        armorToughness: 5
  obsidian_head:
    display_name: display-name-obsidian_head
    permission: obsidianhead
    resource:
      generate: true
    durability:
      max_custom_durability: 350
    specific_properties:
      armor:
        slot: head
        color: '010002'
    attribute_modifiers:
      head:
        armor: 3
        armorToughness: 1
  obsidian_chest:
    display_name: display-name-obsidian_chest
    permission: obsidianarmor
    resource:
      generate: true
    durability:
      max_custom_durability: 500
    specific_properties:
      armor:
        slot: chest
        color: '010002'
    attribute_modifiers:
      chest:
        armor: 7
        armorToughness: 1
  obsidian_legs:
    display_name: display-name-obsidian_legs
    permission: obsidianarmor
    resource:
      generate: true
    durability:
      max_custom_durability: 450
    specific_properties:
      armor:
        slot: legs
        color: '010002'
    attribute_modifiers:
      legs:
        armor: 6
        armorToughness: 1
  obsidian_boots:
    display_name: display-name-obsidian_boots
    permission: obsidianarmor
    resource:
      generate: true
    durability:
      max_custom_durability: 400
    specific_properties:
      armor:
        slot: FEET
        color: '010002'
    attribute_modifiers:
      feet:
        armor: 3
        armorToughness: 1
  mysterious_chest:
    display_name: display-name-mysterious_chest
    permission: mysterious_armor
    resource:
      generate: true
    durability:
      max_custom_durability: 928
    specific_properties:
      armor:
        slot: chest
        color: '570e11'
    attribute_modifiers:
      chest:
        armor: 6
        armorToughness: 1
    events:
      wear:
        play_sound:
          name: itemsadder:ambient.creepy
          volume: 1
          pitch: 1
      unwear:
        play_sound:
          name: itemsadder:ambient.creepy
          volume: 1
          pitch: 1
  mysterious_legs:
    display_name: display-name-mysterious_legs
    permission: mysterious_armor
    resource:
      generate: true
    durability:
      max_custom_durability: 895
    specific_properties:
      armor:
        slot: legs
        color: '570e11'
    attribute_modifiers:
      legs:
        armor: 5
        armorToughness: 1
    events:
      wear:
        play_sound:
          name: itemsadder:ambient.creepy
          volume: 1
          pitch: 1
      unwear:
        play_sound:
          name: itemsadder:ambient.creepy
          volume: 1
          pitch: 1
  mysterious_boots:
    display_name: display-name-mysterious_boots
    permission: mysterious_armor
    lore:
    - 'lore-1-mysterious_boots'
    - 'lore-2-mysterious_boots'
    resource:
      generate: true
    durability:
      max_custom_durability: 829
    specific_properties:
      armor:
        slot: FEET
        color: '570e11'
    attribute_modifiers:
      feet:
        armor: 2
        armorToughness: 1
    events:
      wear:
        play_sound:
          name: itemsadder:ambient.creepy
          volume: 1
          pitch: 1
        potion_effect:
          type: SPEED
          duration: 1000000
          amplifier: 1
        play_particle:
          name: ENCHANTMENT_TABLE
        decrement_durability:
          amount: 5
      unwear:
        play_sound:
          name: itemsadder:ambient.creepy
          volume: 1
          pitch: 1
        remove_potion_effect:
          type: SPEED
        play_particle:
          name: ENCHANTMENT_TABLE
  bronze_head:
    display_name: display-name-bronze_head
    permission: bronzearmor
    resource:
      generate: true
    durability:
      max_custom_durability: 750
    specific_properties:
      armor:
        slot: head
        color: d36823
    attribute_modifiers:
      head:
        armor: 4
        armorToughness: 3
  bronze_chest:
    display_name: display-name-bronze_chest
    permission: bronzearmor
    resource:
      generate: true
    durability:
      max_custom_durability: 900
    specific_properties:
      armor:
        slot: chest
        color: d36823
    attribute_modifiers:
      chest:
        armor: 9
        armorToughness: 3
  bronze_legs:
    display_name: display-name-bronze_legs
    permission: bronzearmor
    resource:
      generate: true
    durability:
      max_custom_durability: 850
    specific_properties:
      armor:
        slot: legs
        color: d36823
    attribute_modifiers:
      legs:
        armor: 7
        armorToughness: 3
  bronze_boots:
    display_name: display-name-bronze_boots
    permission: bronzearmor
    resource:
      generate: true
    durability:
      max_custom_durability: 800
    specific_properties:
      armor:
        slot: FEET
        color: d36823
    attribute_modifiers:
      feet:
        armor: 4
        armorToughness: 3

### Screenshots/Videos (you can drag and drop files or paste links)

![Sans titre 12](https://user-images.githubusercontent.com/80985545/143007245-9d2de3f4-db84-42a4-95f2-3f44edebf298.png)

**Comment by LoneDev6** [comment]
Thanks, this will be fixed in the next update.
![immagine](https://user-images.githubusercontent.com/27242001/143035202-2724135f-3b6a-4879-ae59-99d09d1e1289.png)


Note: Durability for armors will be shown on the top instead of the bottom, it's a bug I cannot fix, it's how the game works.
