### ISSUE TITLE
Scoreboard hide numbers feature problems

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#1338]
### What happened?

The feature which hides Scoreboard numbers has some downsides.
It affects also other places where red color is rendered on the right part of the screen.

### Solution

Find a way to check if the rendered color is on the scoreboard or in the world (maybe z coord checking?)

### Server version

Any

### ItemsAdder Version

Any

### Screenshots/Videos (you can drag and drop files or paste links)

![](https://media.discordapp.net/attachments/533413171403292712/915258276889894992/unknown.png?width=1075&height=589)

**Comment by TenReeez** [comment]
Im also getting the small red arrows in scoreboard, where numbers greater than 9 would go.

**Comment by LoneDev6** [comment]
> Im also getting the small red arrows in scoreboard, where numbers greater than 9 would go.

This can happen based on your GUI scale.
I'm still looking for a solution, not really easy to achieve.

**Comment by TenReeez** [comment]
Lone, i fixed it by just changing the numbers in scoreboard to single digits. I use animatedscoreboard. Not sure if it would work with other scoreboards. thanks for the reply
