### ISSUE TITLE
Hex color gets removed from IA items when using anvil to rename/enchant. Unable to rename.

### ISSUE THREAD

**Issue by Baterka** [PluginBugs/Issues-ItemsAdder#1339]
### Discord tag (optional)

baterka.xyz#9408

### What happened?

Color gets removed from IA items when using anvil to rename/enchant. See steps and screenshots...

### Steps to reproduce the issue

1. Create custom item with customModelData, custom (colored) name, and custom (colored) lore
2. Try to use anvil to rename item
3. This is where problem appears. Color gets removed from item's name and there is only original name with italic (screenshots).
4. On top of that, you cannot rename this item with colors. Color is not parsed (screenshots).

Also using enchanted book in anvil cause item name to change (blue italic) and it is not changeable (screenshots).

### Server version

This server is running Airplane version git-Airplane-63 (MC: 1.17.1)

### ItemsAdder Version

2.4.23

### ProtocolLib Version

4.7.1

### LoneLibs Version

1.0.15

### Screenshots/Videos (you can drag and drop files or paste links)

Original name:
![image](https://user-images.githubusercontent.com/3463591/144443532-a76536c8-f185-4382-a4a4-0377bd0152f1.png)

Output name:
![image](https://user-images.githubusercontent.com/3463591/144443598-adefecf1-a981-4121-b0c7-187d1c7ef3bb.png)

Unable to use colors:
![image](https://user-images.githubusercontent.com/3463591/144443712-891f87d8-213e-4918-b270-f70f8ae0e653.png)

**Comment by Baterka** [comment]
Still not fixed in 3.1.1
![image](https://user-images.githubusercontent.com/3463591/163650557-92999d85-b8d2-44b9-8ece-be33d3c8ee1b.png)
![image](https://user-images.githubusercontent.com/3463591/163650579-27162ca5-275e-4f8f-b0b7-f37816bbe637.png)

`display_name: "%#ff99ff%&lH%#eea0ff%&le%#dca7ff%&ll%#cbaeff%&li%#b4baff%&lo%#9ec5ff%&ls %#87d1ff%&lb%#6ce0ff%&lo%#52f0ff%&lt%#37ffff%&ly"`

**Comment by LoneDev6** [comment]
I can't reproduce the issue

https://user-images.githubusercontent.com/27242001/164238088-298d335b-dd99-4a19-93f1-80b1a478801c.mp4

https://user-images.githubusercontent.com/27242001/164238129-2b154db1-8a14-4c74-a60e-bfcd744ac17b.mp4

You might have a plugin interfering with anvil events.
