### ISSUE TITLE
Confirm compatibility with Terralith worldgen datapack

### ISSUE THREAD

**Issue by purejosh** [PluginBugs/Issues-ItemsAdder#1340]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

purejosh#2047

### Describe the solution you'd like

I would like to know if Itemsadder and Terralith (a worldgen datapack) will have conflicts with each other. I could not find any information about their interoperability in discord or in wiki/github. 

Terralith is becoming VERY popular since their newest release, so I'm sure this will be asked more in the future. 

### Is your feature request related to a problem?

Not a problem, at this time. 

### Describe alternatives you've considered

No alternatives considered.

**Comment by LoneDev6** [comment]
I don't know if they would have conflicts, you should test them, but I don't see how it could cause conflicts, so for now I'd say it's compatible.
I sadly cannot test each mod/datapack available online.
Anyway ItemsAdder for 1.18 is not released due to the fact that 1.18 is still unstable.

Have a nice day.
