### ISSUE TITLE
Cannot break item with 0 durability

### ISSUE THREAD

**Issue by NewJeb** [PluginBugs/Issues-ItemsAdder#1341]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

newjebv#2777

### What happened?

An item with a tethered effect does not break even at 0 durability. I think it is unlikely that the plug-in for effects is somehow involved in this, because this can happen near the minecraft lighthouse

### Steps to reproduce the issue

1) Craft an IA object to which the effect is attached through our other plugin
2) Destroy it to 0 durability and it won't break

### Server version

[13:00:30 INFO]: This server is running Airplane version git-Airplane-103 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 86fee6b on HEAD)
Previous version: git-Paper-377 (MC: 1.17.1)

### ItemsAdder Version

ItemsAdder version 2.4.23

### ProtocolLib Version

ProtocolLib version 4.7.0

### LoneLibs Version

LoneLibs version 1.0.15

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/YfLsV2CUZnE

**Comment by LoneDev6** [comment]
> which the effect is attached through our other plugin

Which other plugin?
Sorry I don't understand, I can't know which other plugin you're using.


Can you also provide your item configuration file? (yml file).
Please post the file, don't paste text and don't upload a screenshot, thanks.

**Comment by NewJeb** [comment]
> > which the effect is attached through our other plugin
> 
> Which other plugin? Sorry I don't understand, I can't know which other plugin you're using.
> 
> Can you also provide your item configuration file? (yml file). Please post the file, don't paste text and don't upload a screenshot, thanks.
[gt_tools(config).zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/7661476/gt_tools.config.zip)

[archive-2021-12-06T174538+0300.tar.gz](https://github.com/PluginBugs/Issues-ItemsAdder/files/7661479/archive-2021-12-06T174538%2B0300.tar.gz)

**Comment by LoneDev6** [comment]
1. this plugin code must be changed. You are using NMS code to get CustomModelData. Spigot has an API method to get [CustomModelData](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/meta/ItemMeta.html#getCustomModelData()).
2. you literally set `disappear_when_broken: false` in your items...
