### ISSUE TITLE
Enable Jukebox's custom discs "has_record":"true" 

### ISSUE THREAD

**Issue by ConaII** [PluginBugs/Issues-ItemsAdder#1344]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

ConaII#1154

### Describe the solution you'd like

For example, a normal disc with my texturepack does this:
**"has_record":"false"**
![image](https://user-images.githubusercontent.com/72966048/144754567-e5b8c608-986e-4d90-8940-a54d63d596bc.png)
**"has_record":"true"** (you put a vanilla disc)
![image](https://user-images.githubusercontent.com/72966048/144754586-00cc583b-04dd-4fff-978c-3b9dd33d15ea.png)

I would like the same for custom discs. It would just update the jukebox state to true, thats all.

**"has_record":"false"** (you put a custom disc)
![image](https://user-images.githubusercontent.com/72966048/144754728-1f604e37-4f7d-46be-a275-9a56bf8a3756.png)

### Is your feature request related to a problem?

No.

### Describe alternatives you've considered

When playing a customdisc update the jukebox properties.
Example, if you start playing a custom disc and you do a /setblock x y z minecraft:jukebox[has_record=true] it just works but i want the plugin to do it automatically without commands.

**Comment by LoneDev6** [comment]
Sorry I don't understand how ItemsAdder is related to this, you can do it without ItemsAdder, you just have to create a blockstate json file and configure your 2 models (like it's done the your resourcepack you're showing)

**Comment by ConaII** [comment]
@LoneDev6 ItemsAdder is the problem.
How i'm i supposed to change the texture if using custom discs FROM itemsadder doesn't change the blockstate.

**Comment by ConaII** [comment]
If you use F3 on the jukebox and play a custom disc you will see that the blockstate isn't changing

**Comment by ConaII** [comment]
I know how to do this on vanilla, with normal discs
But i want this to work with custom dics that play custom music with itemsadder.
And itemsadder just removes the disc from your inv, sends a actionbar "playing ..." and starts spawning note particles on top of the jukebox.

This also removes the disc even if you're in creative mode, and it's not actually stored in the jukebox.
But i'm not asking for that, i'm just asking that ItemsAdder changes the jukebox has_record state so i can do that

**Comment by LoneDev6** [comment]
Okay now I understand your question.
Basically you want ItemsAdder to change the blockstate to has_record if the player uses a custom disc.
I will try to do that, thanks for the report.
