### ISSUE TITLE
ItemsAdder seems to corrupt the players local plotsquared world

### ISSUE THREAD

**Issue by SentixDev** [PluginBugs/Issues-ItemsAdder#1345]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Sentix#1337

### What happened?

Hey,
When i leave the server (or the server restarts), while im in a plotsquared world and try to join again afterwards, i am stuck in a kinda like corrupted world. i cant get teleported, i cant die, blocks doesnt load and all chat input just returns "chat disabled in client options". players from other worlds still can join the plot world and have no problems, until they leave too.
i found out that itemsadder causes the problem and as soon as i delete itemsadder i can enter the server normally again and i am in the right world & chat works again.
https://cdn.upload.systems/uploads/OWMdJCD9.jpg

### Steps to reproduce the issue

1. install a worldmanager, plotsquared & needed dependencies and install itemsadder & needed dependencies
2. setup itemsadder
3. setup a plotsquared plot-world
4. log out while being in the plot-world
5. join the server again

### Server version

This server is running Purpur version git-Purpur-1428 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9beb23b on ver/1.17.1)

Running on java version: 17.0.1

### ItemsAdder Version

ItemsAdder version: 2.4.23

### ProtocolLib Version

ProtocolLib version: 4.7.1-SNAPSHOT-b531

### LoneLibs Version

LoneLibs version: 1.0.15

### LibsDisguises Version (optional)

LibsDisguises version: 10.0.26

### FULL server log

no stacktrace or errors shown in console beside:
[22:05:37 INFO]: SentixDev logged in with entity id 949 at ([plots]-85.83089252441694, 63.0, -7.9536361828575215)
[22:05:37 INFO]: Attempt to teleport removed player SentixDev restricted

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
    protect-file-from-unzip:
      enabled: true
      extreme: true
    overwrite-vanilla-models: true
    overwrite-vanilla-lang-json: true
    compress-png-files: true
    compress-json-files: true
    generate-custom-armors-textures:
      _: 'Available values: VANILLA_1_17 or OPTIFINE'
      enabled: true
      mode: VANILLA_1_17
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: false
      server-ip: 127.0.0.1
      pack-port: 8163
    external-host:
      enabled: true
      url: https://www.dropbox.com/s/1b9kjmc1i54xk4v/pack.zip?dl=1
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  command:
    usage-cooldown-seconds: 60
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-items: true
  extract-default-resources: true
blocks:
  light-api: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    seach-also-in-these-biomes: {}
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    replace-only-packets: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: true
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-generation: false
    log-loading-no-world: true
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-generation: false
    log-loading-no-world: true
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-generation: false
    log-loading-no-world: true
recipes:
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
  hide-vanilla-unrecognized-recipe-errors: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: true
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://cdn.upload.systems/uploads/OWMdJCD9.jpg

**Comment by LoneDev6** [comment]
This is very strange, seems somehow another plugin is deleting the player entity for some reason.
ItemsAdder is not deleting the player entity.

I'll try to follow your steps in order to reproduce the issue but I suspect it can be fixed editing some settings in plotsquared

**Comment by SentixDev** [comment]
sircraftypants#4875 was able to reproduce it. I’ll check the plotsquared settings again.

**Comment by SirCraftypants** [comment]
I'm not saying Itemsadder is the cause but I have the latest PlotsquaredV6 and the latest Itemsadder 2.4.23

Already had a plotworld set and logged in to my Server, entered the plotworld from my lobby, logged out and then logged back in directly to the plotworld instead of the lobby. The spawn area of the plotworld between 10 and 20 blocks radius appeared but the rest of the world was void.

I can confirm Itemsadder plays no part in my plotworld in any way so find this truly baffling.

I have not tried without Itemsadder and it's dependencies though.

**Comment by LoneDev6** [comment]
Did you try using Spigot or Paper instead of Purpur? It might be the cause of the issue.
Generally deleting Player entities is not a vanilla behaviour, that's strange.

**Comment by SentixDev** [comment]
Sure! I can test it with paper, but since sircraftypants was able to reproduce it on Paper 1.17.1, I don't know if I will get a different result.

**Comment by SentixDev** [comment]
Yeah.. still the same issue on latest 1.17.1 Paper build.

**Comment by SirCraftypants** [comment]
The `"chat disabled in client options".` issue may be being caused by the `lock player` locking more than just the players movement, someone discovered the same issue and i've instructed them to report it all on github.

The way i fixed the world issue was by shutting down the server, removing the corrupt world and replacing the corrupted world with a backup but not before making sure i wasn't respawning in the same world upon logging in. This doesn't fix the world corruption issue but it does fix the world corruption if you have a world backup.

**Comment by SentixDev** [comment]
Yes I fixed it the same way, was also able to teleport the player back in to the plot world by scheduling it for like 30 ticks. Very weird issue. I think this can be closed now.

**Comment by LoneDev6** [comment]
This is a very strange issue indeed.
I suspect it's a client bug.

**Comment by LoneDev6** [comment]
After some testing seems `lock-player: false` solves the issue, no need to delete the world.
I'm trying to find the main cause of this problem and I'll provide a fix.
Thanks all for the patience
