### ISSUE TITLE
HOOK request ItemsAdder + MMOBars

### ISSUE THREAD

**Issue by Tylwen** [PluginBugs/Issues-ItemsAdder#1346]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Tylwen#4130

### Describe the solution you'd like

Add hook between ItemsAdder et MMOBars
https://mythiccraft.io/index.php?resources/mmobars.394/

### Is your feature request related to a problem?

problem unicode in action bar or others

### Describe alternatives you've considered

Make sure that the unicode file can split the data of ItemsAdder and MMObars in order to avoid conflicts and that it takes into account the 2 data and not just one or the other

**Comment by LoneDev6** [comment]
This is going to be a bit hard/impossible to do from my side.
MMOBars dev should hook my API and use it to show their custom huds if ItemsAdder is installed.
They can look here for an example: https://github.com/LoneDev6/RPGhuds/

The problem is that two huds systems cannot coexist, it's a limitation we cannot bypass in any way.

You should share this page with MMOBars developer

**Comment by Tylwen** [comment]
Solution (in config.yml of MMOBars)

# The resource pack namespace where the assets are stored.
  namespace: 'mmobars'

  # The font where negative spaces are stored.
  negative-space-font: 'minecraft:default'
  
  # before its  negative-space-font: 'space:default'

**Comment by LoneDev6** [comment]
You also need to completely disable ItemsAdder HUDs surely (config.yml of ItemsAdder and disable huds).
