### ISSUE TITLE
Music disc glitch

### ISSUE THREAD

**Issue by Faris90** [PluginBugs/Issues-ItemsAdder#1348]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

When I pull out one disc the music completely stops

### Steps to reproduce the issue

1. Get a music disc
2. Place two jukeboxes
3. Take one disc out
4. Now the music completely stopped

### Server version

1.17.1

### ItemsAdder Version

2.4.23

### ProtocolLib Version

4.7.1

### LoneLibs Version

1.0.15

**Comment by Faris90** [comment]
If I left anything out tell me @LoneDev6

**Comment by LoneDev6** [comment]
Hello, currently there is no way to fix this.
The plugin will stop both sounds if the audio in both jukebox is the same, it's a limitation of the game custom sounds.
