### ISSUE TITLE
Please update to version 1.18

### ISSUE THREAD

**Issue by StealthDeci** [PluginBugs/Issues-ItemsAdder#1350]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

> > > Please update to version 1.18 < < <
-----------------------------------------------------------

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

> > > Please update to version 1.18 < < <
-----------------------------------------------------------

### Additional context

> > > Please update to version 1.18 < < <
-----------------------------------------------------------

**Comment by LoneDev6** [comment]
Asking for an update doesn't speedup my work.
I'm already working on an update for ItemsAdder to support Minecraft 1.18, it will be released after the beta testing phase will get good results.

Updating is not a snap of finders sadly.
