### ISSUE TITLE
Copy/Move Pack.zip to another directory to help with external-host.

### ISSUE THREAD

**Issue by HolographicWings** [PluginBugs/Issues-ItemsAdder#1356]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

HolographicWings#2104

### Describe the solution you'd like

Hello, i wish use the external-host to host the pack.zip on my web server and take adventage of my SSL
Can you add a way to change the directory of the pack.zip ? Or a way to copy the zip to this directory ?

Thanks you, cordially. ^^

### Is your feature request related to a problem?

Yes and not, it's not a big issue, just a practical concern.

### Describe alternatives you've considered

Manual copy paste, but it gets boring after the 50th time. ^^"

**Comment by HolographicWings** [comment]
Not only, this would allow me to use the same web server for the dynmap, package, server website, etc.

**Comment by HolographicWings** [comment]
Not only, this would allow me to use the same web server for the dynmap, pack.zip, website, etc.
Anyway it's not an let's encrypt SSL but an cloudflare one.
I tested it and it work.

**Comment by LoneDev6** [comment]
I'll add this feature in the next update, thanks.
Would the zip destination be in the same server as where you run Spigot?
Or a remote server?
