### ISSUE TITLE
iazip error, language file compression failed

### ISSUE THREAD

**Issue by yun334022** [PluginBugs/Issues-ItemsAdder#1357]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

YUN#6107

### What happened?

These errors occur when using iazip to package the data package, and the language cannot be loaded normally.
> 
> iazip
[INFO]: [ItemsAdder] [Init] Loading YML files...
[INFO]: [ItemsAdder] [Init] Loading items_packs...
[INFO]: [ItemsAdder] Loaded 484 items
[INFO]: [ItemsAdder] Used 0/188 REAL block IDs.
[INFO]: [ItemsAdder] Used 28/750 REAL_NOTE block IDs.
[INFO]: [ItemsAdder] Used 0/63 REAL_TRANSPARENT block IDs.
[INFO]: [ItemsAdder] Used 0/127 REAL_WIRE block IDs.
[INFO]: [ItemsAdder] Used 0/14 FIRE block IDs.
[INFO]: [ItemsAdder] Used 888/6608 available max font_images.
[INFO]: [PlaceholderAPI] Successfully registered expansion: img
[INFO]: [PlaceholderAPI] Successfully registered expansion: iaplayerstat
[INFO]: [ItemsAdder] [Init] Loaded 40 categories
[INFO]: [ItemsAdder] [Init] Loaded 484 items and stuff in 430ms
[ERROR]: [ItemsAdder] Error saving generated font file (default.json)
[WARN]: java.nio.charset.MalformedInputException: Input length = 1
[WARN]:        at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
[WARN]:        at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:315)
[WARN]:        at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:290)
[WARN]:        at java.base/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:131)
[WARN]:        at java.base/java.io.OutputStreamWriter.write(OutputStreamWriter.java:205)
[WARN]:        at java.base/java.io.BufferedWriter.flushBuffer(BufferedWriter.java:120)
[WARN]:        at java.base/java.io.BufferedWriter.write(BufferedWriter.java:233)
[WARN]:        at java.base/java.io.Writer.write(Writer.java:249)
[WARN]:        at java.base/java.io.Writer.append(Writer.java:322)
[WARN]:        at java.base/java.nio.file.Files.write(Files.java:3559)
[WARN]:        at ItemsAdder.jar//dev.lone.itemsadder.main.gE.bh(SourceFile:157)
[WARN]:        at ItemsAdder.jar//dev.lone.itemsadder.main.gE.bg(SourceFile:83)
[WARN]:        at ItemsAdder.jar//dev.lone.itemsadder.main.gI.c(SourceFile:378)
[WARN]:        at ItemsAdder.jar//dev.lone.itemsadder.main.aV.a(SourceFile:2141)
[WARN]:        at ItemsAdder.jar//dev.lone.itemsadder.main.aP.a(SourceFile:91)
[WARN]:        at ItemsAdder.jar//dev.lone.itemsadder.main.aV.a(SourceFile:1991)
[WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[WARN]:        Suppressed: java.nio.charset.MalformedInputException: Input length = 1
[WARN]:                at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
[WARN]:                at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:315)
[WARN]:                at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:290)
[WARN]:                at java.base/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:131)
[WARN]:                at java.base/java.io.OutputStreamWriter.write(OutputStreamWriter.java:205)
[WARN]:                at java.base/java.io.BufferedWriter.flushBuffer(BufferedWriter.java:120)
[WARN]:                at java.base/java.io.BufferedWriter.close(BufferedWriter.java:268)
[WARN]:                at java.base/java.nio.file.Files.write(Files.java:3556)
[WARN]:                ... 12 more
[INFO]: [ItemsAdder] [Pack] Extracting utility resource_pack assets from .jar
[INFO]: [ItemsAdder] [Pack] DONE extracting utility resource_pack assets from .jar
[INFO]: [ItemsAdder] Compressed 440 PNGs in 15944ms. 46.7 MB->43.5 MB
[INFO]: [ItemsAdder] [OK] Your zip file will be protected from unzip (as set in config.yml)
[INFO]: [ItemsAdder] [Pack] Compressing resource_pack ...
[INFO]: [ItemsAdder] [Pack] Resourcepack successfully compressed: \plugins\ItemsAdder\data\resource_pack\pack.zip
[INFO]: Welcome! Thanks for buying ItemsAdder! <3
[INFO]: To make the textures show you have to follow this simple tutorial: https://bit.ly/ia-precompr
[INFO]: If you have any problem configuring the resourcepack please contact me: https://a.devs.beer/ia-supp-first-install
[INFO]: Have fun! :D
>
This language profile is located in assets\minecraft\
[font.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/7734112/font.zip)

### Steps to reproduce the issue

The language configuration file I used was put into ItemsAdder\data\resource_pack\assets\minecraft and repackaged with /iazip to reproduce this error

### Server version

This server is running Paper version git-Paper-388 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 22aaf91)

### ItemsAdder Version

ItemsAdder v2.5.0-beta

### ProtocolLib Version

ProtocolLib v4.7.1

### LoneLibs Version

LoneLibs v1.0.16b

### LightAPI Version (optional)

LightAPI v5.0.0

**Comment by LoneDev6** [comment]
Hello, this is the characters file not the language file.
Please make a backup of `ItemsAdder\data\resource_pack\assets\minecraft\font\default.json` file and delete it, then run /iazip again.

**Comment by LoneDev6** [comment]
@yun334022 please open a ticket on my Discord and send me your complete ItemsAdder folder, thanks.

**Comment by LoneDev6** [comment]
Solved:
> To fix it you have to delete this folder: `ItemsAdder\data\resource_pack\assets\minecraft\font\` and run `/iazip` again
