### ISSUE TITLE
[Suggestion] Prevent storing certain items

### ISSUE THREAD

**Issue by Alejitus** [PluginBugs/Issues-ItemsAdder#136]
I don't know if it is possible but I would like there to be an option that prevents an item from being stored in chests or any other container.

**Comment by LoneDev6** [comment]
This could be achieved using skript api, I may make an example in the future.
Do you have experience with skript?
https://itemsadder.plugin.ga/developers/skript-api

**Comment by Alejitus** [comment]
No, I have no experience with skript but will investigate. 

Thanks.
