### ISSUE TITLE
Items don't show in category

### ISSUE THREAD

**Issue by IncludivicS** [PluginBugs/Issues-ItemsAdder#1360]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Keizenbergz#7164

### What happened?

Items don't show in category. I added it to category. 
Item is available for craft and show in all category but did not show in specify category

### Steps to reproduce the issue

No

### Server version

git-Paper-77 (MC: 1.18.1)

### ItemsAdder Version

ItemsAdder version 2.5.0-beta

### ProtocolLib Version

ProtocolLib version 4.8.0-SNAPSHOT-b538

### LoneLibs Version

LoneLibs version 1.0.16b

### LightAPI Version (optional)

LightAPI version bukkit-5.1.0 (build SNAPSHOT)

### LibsDisguises Version (optional)

LibsDisguises version 10.0.26-SNAPSHOT

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: vanzy.sytes.net
      pack-port: 8163
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: true
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      _: 'Available values: VANILLA_1_17 or OPTIFINE'
      enabled: true
      mode: VANILLA_1_17
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-items: false
  extract-default-resources: false
blocks:
  light-api: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: false
  vault-prefix-suffix:
    enabled: false
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: false
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
effects:
  hide-scoreboard-numbers: true
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
```

### Other files, you can drag and drop them here to upload. (optional)

info:
  namespace: itemsadder
recipes:
  crafting_table:
    oak_wood_chair:
      enabled: true
      pattern:
      - OXX
      - AAA
      - AXA
      ingredients:
        A: OAK_PLANKS
        O: OAK_LOG
      result:
        item: itemsadder:oak_wood_chair
        amount: 1
    spruce_chair:
      enabled: true
      pattern:
      - OXX
      - AAA
      - AXA
      ingredients:
        A: spruce_PLANKS
        O: spruce_LOG
      result:
        item: itemsadder:spruce_chair
        amount: 1
    jungle_chair:
      enabled: true
      pattern:
      - OXX
      - AAA
      - AXA
      ingredients:
        A: JUNGLE_PLANKS
        O: JUNGLE_LOG
      result:
        item: itemsadder:jungle_chair
        amount: 1
    dark_oak_chair:
      enabled: true
      pattern:
      - OXX
      - AAA
      - AXA
      ingredients:
        A: DARK_OAK_PLANKS
        O: DARK_OAK_LOG
      result:
        item: itemsadder:dark_oak_chair
        amount: 1
    birch_chair:
      enabled: true
      pattern:
      - OXX
      - AAA
      - AXA
      ingredients:
        A: birch_PLANKS
        O: birch_LOG
      result:
        item: itemsadder:birch_chair
        amount: 1
    acacia_chair:
      enabled: true
      pattern:
      - OXX
      - AAA
      - AXA
      ingredients:
        A: acacia_PLANKS
        O: acacia_LOG
      result:
        item: itemsadder:acacia_chair
        amount: 1
items:
  jungle_chair:
    display_name: display-name-jungle_chair
    lore:
    - 'lore-5-philosopher_stone'
    - 'lore-chair'
    resource:
      material: PAPER
      generate: false
      model_path: item/jungle_chair
    behaviours:
      furniture:
        small: true
      furniture_sit:
        sit_height: 0.5
  dark_oak_chair:
    display_name: display-name-dark_oak_chair
    lore:
    - 'lore-5-philosopher_stone'
    - 'lore-chair'
    resource:
      material: PAPER
      generate: false
      model_path: item/dark_oak_chair
    behaviours:
      furniture:
        small: true
      furniture_sit:
        sit_height: 0.5
  birch_chair:
    display_name: display-name-birch_chair
    lore:
    - 'lore-5-philosopher_stone'
    - 'lore-chair'
    resource:
      material: PAPER
      generate: false
      model_path: item/birch_chair
    behaviours:
      furniture:
        small: true
      furniture_sit:
        sit_height: 0.5
  acacia_chair:
    display_name: display-name-acacia_chair
    lore:
    - 'lore-5-philosopher_stone'
    - 'lore-chair'
    resource:
      material: PAPER
      generate: false
      model_path: item/acacia_chair
    behaviours:
      furniture:
        small: true
      furniture_sit:
        sit_height: 0.5
  oak_wood_chair:
    display_name: display-name-oak_wood_chair
    lore:
    - 'lore-5-philosopher_stone'
    - 'lore-chair'
    resource:
      material: PAPER
      generate: false
      model_path: item/oak_wood_chair
    behaviours:
      furniture:
        small: true
      furniture_sit:
        sit_height: 0.5
  spruce_chair:
    display_name: display-name-spruce_chair
    lore:
    - 'lore-5-philosopher_stone'
    - 'lore-chair'
    resource:
      material: PAPER
      generate: false
      model_path: item/spruce_chair
    behaviours:
      furniture:
        small: true
      furniture_sit:
        sit_height: 0.5

info:
  namespace: ia_various_configs
categories:  
    chairs:
      enabled: true
      skip_if_already: false
      icon: itemsadder.oak_wood_chair
      name: display-category-chairs
      permission: ia.menu.chairs
      font_image:
        name: "mcguis:blank_menu"
        x_position_pixels: -16
      title_position_pixels: 0
      items:
        - itemsadder:jungle_chair
        - itemsadder:dark_oak_chair
        - itemsadder:birch_chair
        - itemsadder:acacia_chair
        - itemsadder.oak_wood_chair
        - itemsadder.spruce_chair

**Comment by LoneDev6** [comment]
I think you miss the permission to show the items in the whole /ia GUI.
https://itemsadder.devs.beer/plugin-usage/permissions/example-permissions

ia.user.ia.*
