### ISSUE TITLE
"Place_block and Place_furniture" action (Temporary replacement for 2D block textures)

### ISSUE THREAD

**Issue by RichElephant** [PluginBugs/Issues-ItemsAdder#1361]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Good day.
One thing that bothers me terribly is in this plugin, and that is that it doesn't exist, for example, with a flower (2D texture in inventory and a model on the ground). But I got an idea how to solve it easily. I looked through all the suggestions and came across a suggestion from TeiBri. He included exactly what I mean, but here I have a simple solution.

New actions: place_block, place_furniture.
Example:

**PLACE_BLOCK**
info:
  namespace: worlddeco
items:
  rose:
    enabled: true
    display_name: display-name-rose
    resource:
      generate: false
      material: PAPER
      model_path: rose
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        sound:
          place:
            name: block.grass.place
          break:
            name: block.grass.break

  rose_item:
    display_name: Rose
    resource:
      material: PAPER
      generate: true
      textures:
      - item/rose_item.png
     **events:
      interact:
        right:
          place_block:
            block: worlddeco:rose
            remove: true (When you right-click on the ground with this item and place WORLDDECO: ROSE, this item disappears. However, if you give FALSE, the item places the model but remains in the inventory)**

**PLACE_FURNITURE**

info:
  namespace: itemsadder
items:
  plant_in_pot:
    display_name: "Plant in Pot"
    lore:
    - 'lore-decorative-item'
    resource:
      material: PAPER
      generate: false
      model_path: item/bamboo_plant_in_pot
    behaviours:
      furniture:
        entity: item_frame
        solid: false
        hitbox:
          length: 1
          width: 1
          height: 1.5
        placeable_on:
          walls: false
          ceiling: false
          floor: true

  plant_in_pot_item:
    display_name: Plant in pot
    resource:
      material: PAPER
      generate: true
      textures:
      - item/plant_in_pot_item.png
     **events:
      interact:
        right:
          place_furniture:
            furniture: itemsadder:plant_in_pot
            remove: true (When you right-click on the ground with this item and place WORLDDECO: ROSE, this item disappears. However, if you give FALSE, the item places the model but remains in the inventory)**

**EDIT: It would also be great to make it so that there can be furniture in the loots. e.g:

loots:
  furniture:
    plant_in_pot:
      type: itemsadder:plant_in_pot(furniture)
      items:
        plant_in_pot_item:
          item: itemsadder:plant_in_pot_item
          min_amount: 1
          max_amount: 1
          chance: 100
                                             Thanks ...**
### Is your feature request related to a problem?

I don't think it's necessary ...

### Describe alternatives you've considered

I don't think it's necessary ...

### Additional context

I don't think it's necessary ...

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1704#issuecomment-1135146991
