### ISSUE TITLE
"compress-png-files: false" doesn't work

### ISSUE THREAD

**Issue by Xiao-MoMi** [PluginBugs/Issues-ItemsAdder#1362]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

I've set "compress-png-files: false"
But it still compress my images and only making it bigger
![1](https://user-images.githubusercontent.com/70987828/146851782-c3bd23c7-504e-4e0a-80e2-139f27d593cf.png)
![2](https://user-images.githubusercontent.com/70987828/146851790-91f637a0-2833-4298-86e1-2dbb07d65b75.png)

After iareload
![3](https://user-images.githubusercontent.com/70987828/146851809-88dbe226-1c2b-4f12-be2e-e5c4a62774da.png)

### Steps to reproduce the issue

see above

### ItemsAdder Version

[08:44:33 INFO]: ItemsAdder version 2.5.0-beta
[08:44:33 INFO]: Customized Minecraft without client mods!
[08:44:33 INFO]: Website: devs.beer
[08:44:33 INFO]: Author: LoneDev

### ProtocolLib Version

> about ProtocolLib
[08:44:41 INFO]: ProtocolLib version 4.7.1-SNAPSHOT-b536
[08:44:41 INFO]: Provides read/write access to the Minecraft protocol.
[08:44:41 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

> about LoneLibs
[08:44:48 INFO]: LoneLibs version 1.0.16b
[08:44:48 INFO]: Collection of libs used by my plugins
[08:44:48 INFO]: Authors: LoneDev and others

**Comment by LoneDev6** [comment]
The plugin is editing the images to make them work with Minecraft.
I have no way to fix this currently.
`compress-png-files: true` is important to make images compressed after itemsadder edited them.
