### ISSUE TITLE
add a way to remove custom items from a players inventory

### ISSUE THREAD

**Issue by Apiz05** [PluginBugs/Issues-ItemsAdder#1366]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Aech_#1655

### Describe the solution you'd like

I want to remove specific item from player 

### Is your feature request related to a problem?

no

### Describe alternatives you've considered

like this i guess ```public void blaze(PlayerInteractEvent e)
if(e.getPlayer().getInventory().getItemInHand().getType() == Material.BLAZE_POWDER){
e.getItem().setType(Material.AIR);
}```

### Additional context

I hope this will be added cause this will a game change for us

**Comment by LoneDev6** [comment]
It's easy, you have to iterate the player inventory and check if it's the custom item you want.

This should work fine, but depends on what you need to achieve.
```java
public void removeCustomItem(Player player, String namespacedId)
    {
        PlayerInventory inv = player.getInventory();
        int i = 0;
        for (ItemStack item : inv)
        {
            if (!ItemsAdder.isCustomItem(item))
                continue;
            if (ItemsAdder.getCustomItemName(item).equals(namespacedId))
            {
                item.setAmount(item.getAmount() - 1);
            }
        }
    }
```

**Comment by Apiz05** [comment]
> 

How to use this cause i never build a plugin?

**Comment by LoneDev6** [comment]
You posted a Java code so I thought you were coding a plugin...

There is a remove command, please check the wiki before opening support requests.
`/iaremove`
https://itemsadder.devs.beer/plugin-usage/commands

Have a nice day.
