### ISSUE TITLE
Support other plugins with action bar or custom resource pack.

### ISSUE THREAD

**Issue by Lucky-fish** [PluginBugs/Issues-ItemsAdder#1368]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

It seems that this plugin conflicts with other plugins like [Transport-Pipe](https://github.com/BlackBeltPanda/Transport-Pipes) and plugins that sends action bar. So you might need to catch the action bar packet and resource pack packet in order to make it compatible with the plugins uses action bar and custom resource packs.

### Is your feature request related to a problem?

Yes. When we use this plugin together with the [Transport-Pipe](https://github.com/BlackBeltPanda/Transport-Pipes). The pipe can not show up correctly when placed and configured to use custom models.

### Describe alternatives you've considered

Maybe you could combine two or more resource packs together by `java.util.zip.ZipFile` class or something else. And you maybe nedd to automatically align the things on action bar when you caught the action bar packet of other plugins.

**Comment by LoneDev6** [comment]
A video / screenshot would be nice.
