### ISSUE TITLE
IA shouldn't merge/combine categories of different namespaces

### ISSUE THREAD

**Issue by Andre601** [PluginBugs/Issues-ItemsAdder#1374]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

`Andre_601#0601`

### Describe the solution you'd like

Right now does ItemsAdder merge categories from different namespaces, if those are using the same name for their categories in the category files.

If I for example have an item pack with namespace `myitems` and one with namespace `otheritems` and both have a yaml file containing `all` as a category, will ItemsAdder merge them together, even tho they have separate namespaces.

It makes sense to merge item categories if they share the same namespace, but having two separate namespaces merged is imo a wrong solution and not something most people want.

ItemsAdder should include the actual namespace used in the category file to create the category name.
As an example would `all` become `myitems_all` for the `myitems` namespace and `otheritems_all` in the `otheritems` namespace.

This should serve as a more than unique enough category id to not have some mix up unintentionally.
If people still want their pack to combine with another one could they just use the same namespace for the category itself...

### Is your feature request related to a problem?

Yes. ItemsAdder merging categories together is unintentionally destroying the `/ia` GUI by having some categories not show up because they already got included in other categories, making the items pack appear broken or incomplete.

Pack creators may not be aware of this random quirk of IA and create common categories such as `all` or `misc` without realising that IA will merge their items into another category, if that items pack is handled first...

### Describe alternatives you've considered

Alternative would be to now rewrite the category names, which may work if using the `namespace_category` format, but would also not guarantee that another items pack wouldn't also use this same name format...

### Additional context

Here is a gif displaying the actual issue this "feature" causes.
![gif](https://thumbs.gfycat.com/OddballWellmadeKakarikis-size_restricted.gif)

**Comment by Akiranya** [comment]
I'm actually taking the advantage of this merging feature ... for me I added many furnitures pack from other authors and I added all of the furnitures into the "furnitures" category (created by IA). I duno what other people think about it.

**Comment by Andre601** [comment]
That is *your* argument here.
It's not clear if people didn't want a change, so saying that *they* wouldn't like nor want it, without any proof is imo a bad practice to do.
