### ISSUE TITLE
tree populators - tree type incorrect

### ISSUE THREAD

**Issue by lexingtonnn** [PluginBugs/Issues-ItemsAdder#1377]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

lexington#3236

### What happened?

here's some Example code for Reference.

info:
  namespace: lexington
trees_populators:
  candycane_tree:
    worlds:
      - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 1
    max_height: 250
    min_height: 25
    amount: 1
    iterations: 1
    tree_type: DARK_OAK
# DARK_OAK acts as ACACIA currently.
    leaves: lexington:candycane_tree_leaves
    log: lexington:candycane_tree_log#1376 

______________________________________________________

Under "tree type:" certain trees are spawning incorrectly.  for instance, the "ACACIA" try is spawning as a swamp tree.  the DARK_OAK tree spawns as an acacia tree, and the REDWOOD spawns as a tall Jungle tree.  I went through all the  catagories, and only the BROWN_MUSHROOM and RED_MUSHROOM seemed to match correctly.  Sorry I cant be my thorough in my explanation.

would put it as a very minor bug.

### Steps to reproduce the issue

create a tree populator YML
then mess around with tree types.

### Server version

This server is running CraftBukkit version 3360-Spigot-f65de01-c2e0bbd (MC 1.18.1) (implementing API version 1.18.1-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 2.5.1-beta4

### ProtocolLib Version

ProtocolLib version 4.8.0-SHAPSHOT-b539

### LoneLibs Version

LoneLibs version 1.0.16b

### LightAPI Version (optional)

LightAPI version bukkit-5.1.0 (build SNAPSHOT)

### LibsDisguises Version (optional)

LibsDisguises version 10.0.27

**Comment by LoneDev6** [comment]
Strange, I'm using the Bukkit API code to spawn trees.
```java
            case TREE:
            default:
                gen = TreeFeatures.OAK;
                break;
            case BIG_TREE:
                gen = TreeFeatures.FANCY_OAK;
                break;
            case REDWOOD:
                gen = TreeFeatures.SPRUCE;
                break;
            case TALL_REDWOOD:
                gen = TreeFeatures.PINE;
                break;
            case BIRCH:
                gen = TreeFeatures.BIRCH;
                break;
            case JUNGLE:
                gen = TreeFeatures.MEGA_JUNGLE_TREE;
                break;
            case SMALL_JUNGLE:
                gen = TreeFeatures.JUNGLE_TREE_NO_VINE;
                break;
            case COCOA_TREE:
                gen = TreeFeatures.JUNGLE_TREE;
                break;
            case JUNGLE_BUSH:
                gen = TreeFeatures.JUNGLE_BUSH;
                break;
            case RED_MUSHROOM:
                gen = TreeFeatures.HUGE_RED_MUSHROOM;
                break;
            case BROWN_MUSHROOM:
                gen = TreeFeatures.HUGE_BROWN_MUSHROOM;
                break;
            case SWAMP:
                gen = TreeFeatures.SWAMP_OAK;
                break;
            case ACACIA:
                gen = TreeFeatures.ACACIA;
                break;
            case DARK_OAK:
                gen = TreeFeatures.DARK_OAK;
                break;
            case MEGA_REDWOOD:
                gen = TreeFeatures.MEGA_PINE;
                break;
            case TALL_BIRCH:
                gen = TreeFeatures.SUPER_BIRCH_BEES_0002;
                break;
            case CRIMSON_FUNGUS:
                gen = TreeFeatures.CRIMSON_FUNGUS_PLANTED;
                break;
            case WARPED_FUNGUS:
                gen = TreeFeatures.WARPED_FUNGUS_PLANTED;
                break;
            case AZALEA:
                gen = TreeFeatures.AZALEA_TREE;
```

**Comment by LoneDev6** [comment]
I'll try a thing in the next update which should fix your issue, but I'm not sure
