### ISSUE TITLE
players can remove the color code from armor using the couldron

### ISSUE THREAD

**Issue by darktubeNL** [PluginBugs/Issues-ItemsAdder#1390]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Ashwin | DarktubeNL#6896

### What happened?

if you right click a couldron holding a custom armor piece the color code get removed and armor reset to normal leather

### Steps to reproduce the issue

place a couldron
fill it with water
grap a custom armor piece
right click the cauldron

### Server version

This server is running Paper version git-Paper-120 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 3a43821)

### ItemsAdder Version

ItemsAdder version 2.5.1-beta4

### ProtocolLib Version

ProtocolLib version 4.7.0

### LoneLibs Version

LoneLibs version 1.0.16b

**Comment by LoneDev6** [comment]
Will be fixed, thanks
