### ISSUE TITLE
Add won't burn/netherite item property

### ISSUE THREAD

**Issue by EMERALD0874** [PluginBugs/Issues-ItemsAdder#1391]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

`EMERALD#0874`

### Describe the solution you'd like

Add a property to items that prevents destruction by burning like netherite items.

### Is your feature request related to a problem?

When creating a custom armor that should function like netherite, you cannot add a custom armor texture _and_ netherite armor as a material. While the item texture shows correctly, the armor appears as netherite.

### Describe alternatives you've considered

Adding the unbreakable property. This doesn't prevent the item from burning.

**Comment by LoneDev6** [comment]
I'm not sure if this is currently possible:
https://www.spigotmc.org/threads/stop-item-from-burning-in-lava.397664/#post-3699133
