### ISSUE TITLE
Missing "increment_durability" action for events

### ISSUE THREAD

**Issue by vasiliy-23** [PluginBugs/Issues-ItemsAdder#1394]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

why is this code not working? I want my item to be repaired when the mouse button is clicked

### Steps to reproduce the issue

Launch code

### ItemsAdder Version

 ItemsAdder 2.5.1-beta4

### ProtocolLib Version

ProtocolLib 4.7.0

### LoneLibs Version

LoneLibs 1.0.16b

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: ic2
items:

 drill1:
    display_name: Шахтёрский бур
    permission: drill1
    durability:
      max_custom_durability: 27  
      custom_durability: 27  
      disappear_when_broken: false 
      unbreakable: false 
      usages: 1
    item_flags:
    - HIDE_ENCHANTS
    resource:
      material: DIAMOND_PICKAXE
      generate: true
      textures:
      - items/tool/electric/drill.png
    lore:                  
    attribute_modifiers:   
      mainhand:
        attackDamage: 5
        attackSpeed: 1
      offhand:
        attackDamage: 5
        attackSpeed: 1     
    events_cooldown: 20  
    events:          
     interact:
        right:
          increment_durability:
            amount: 1
```

**Comment by LoneDev6** [comment]
Thanks for the report, this will be fixed in the next update.
