### ISSUE TITLE
Fake blocks generated when mining

### ISSUE THREAD

**Issue by ninesik** [PluginBugs/Issues-ItemsAdder#1401]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

나인#1927

### What happened?

I have a big problem, so I contacted you.
When using the block mining event 3x3 system,
When user 1 is mining with the pickaxe, there is a bug where the block does not disappear if user 2 is not looking at user 1.
Even if the block is mined, it does not appear to be mined to user #2.
Is there any solution to this problem?

### Steps to reproduce the issue

1. User No. 1 mines with a 3x3 pickaxe.
2. User 2 doesn't see it. What user 1 mines
3. The blocks mined by user 1 remain as virtual images.
4. When user 2 climbs on the block, an error occurs and disappears when right-clicking.

### Server version

all ver

### ItemsAdder Version

latest release

### ProtocolLib Version

latest release

### LoneLibs Version

latest release

### LightAPI Version (optional)

latest release

### LibsDisguises Version (optional)

latest release

### Error (optional)

```shell
not
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/1_deeczBiiA

**Comment by LoneDev6** [comment]
I'll look into this report and see if I can reproduce the issue, thanks

**Comment by ninesik** [comment]
> I'll look into this report and see if I can reproduce the issue, thanks

I hope the problem is resolved quickly.

**Comment by LoneDev6** [comment]
This happens because of optimization of my plugin.
You won't get updates if you are far more than > 16 blocks from the broken blocks area.
I will increase this to 128.

**Comment by ninesik** [comment]
@LoneDev6 
Hello?
With the addition of the 1.19 version
The height of mining has increased to -64.
So if you go underground, you'll see a fake block.
The currently set optimization value is 128
Can you increase it further?

**Comment by LoneDev6** [comment]
Is the issue the same issue as the one you reported in this ticket back in 2022?
Can you please open a new issue report providing again all the requested information and a video on how to reproduce the issue?

Thanks.
