### ISSUE TITLE
Option to disable automatic coloring of emoji in white in the chat.

### ISSUE THREAD

**Issue by Ultim4t** [PluginBugs/Issues-ItemsAdder#1407]
### Describe the solution you'd like

add an option to disable automatic coloring of emoticons in white in the chat.

### Is your feature request related to a problem?

emoticons are colored in the custom color of the chat message, which is bad

### Describe alternatives you've considered

Make either a command output using codes example /emoji :smiling: with tab codes or fix the emoticons so that they don't get colored

**Comment by Ultim4t** [comment]
Not a man, you haven't fixed anything, absolutely nothing has changed, the emoticons also continue to be painted in a custom color. 

You probably didn't understand me when I use the /emojis command, if I have the same Essentials in my chat settings, for example, &a{message}, then when sending a smiley to the chat, it turns green

**Comment by Ultim4t** [comment]
![image](https://user-images.githubusercontent.com/71952785/148974900-4cedd90a-ff4f-499a-9243-69b08aaaac11.png)
![image](https://user-images.githubusercontent.com/71952785/148975133-fdbfe494-c601-42bf-80ad-b8ba3976b435.png)
![image](https://user-images.githubusercontent.com/71952785/148975573-c074b18d-1fab-4177-9ef2-5b1b9bf19624.png)

**Comment by Ultim4t** [comment]
And it doesn't matter if I turn on the parameter or don't turn on the parameter true or false

reset-color-to-white: true 

Anyway, the smiley face is not of normal color painted in §x§f§7§c§3§c§7{message} as I threw above in the Essentials configuration example

**Comment by Ultim4t** [comment]
Make it easier to output codes by command /emojis :smiling: with the ability to tab tabs

**Comment by Ultim4t** [comment]
Even I'm in my nedo plugin that doesn't work because I don't have enough knowledge, I partially implemented it 
![image](https://user-images.githubusercontent.com/71952785/148976531-067f2106-30f0-4a15-a2d8-b0b92e0a151f.png)
But I started studying recently

**Comment by Ultim4t** [comment]
If my message in the Essentials config is colored in a custom color, then this parameter with the value true simply does not work when sending a message from Essentials or another plugin, it still repaints even if this function is enabled 

reset-color-to-white: true

**Comment by Ultim4t** [comment]
The problem is not with me, I used all the plugins that exist at all, and in all cases, with the custom color of the message in the configuration, the smiley still colors

**Comment by LoneDev6** [comment]
`reset-color-to-white: false` disable it

**Comment by LoneDev6** [comment]
> Not a man, you haven't fixed anything, absolutely nothing has changed, the emoticons also continue to be painted in a custom color.
> 
> You probably didn't understand me when I use the /emojis command, if I have the same Essentials in my chat settings, for example, &a{message}, then when sending a smiley to the chat, it turns green

:facepalm:
I think we misunderstood.
I thought you wanted a way to color emojis... not the opposite.
The opposite is already coded. Basically what you're saying is that if you use /emoji , then press tab to complete and emoji, the emoji will get colored as your EssentialsX chat configuration.
I'll fix this in the next update.

**Comment by Ultim4t** [comment]
That's right, that's what I need, I'm a Russian user and I have to use a translator to somehow solve problems, I apologize for the inconveniences I brought

**Comment by Ultim4t** [comment]
I need emoticons to have a normal appearance and not be colored to match the color of EssentialsEx messages because this is the problem of all chats emoticons are colored to match the color of messages

**Comment by LoneDev6** [comment]
This will be fixed, thanks
