### ISSUE TITLE
The new option "reset-color-to-white" not work

### ISSUE THREAD

**Issue by PJGamerr** [PluginBugs/Issues-ItemsAdder#1414]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

Hi, I just updated the plugin reading the news .. and the new option that should allow you to write colored without affecting the emojis does not work ..

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/85345525/149004926-a99b0834-29e1-48e8-9529-dba664a04ca8.png)
![2022-01-11_20 02 40](https://user-images.githubusercontent.com/85345525/149005067-42329e22-d381-4bd8-96e3-f8bf1ba0f8a1.png)

### ItemsAdder Version

2.5.3

### ProtocolLib Version

4.7.0

### LoneLibs Version

1.0.16b

**Comment by LoneDev6** [comment]
Seems everyone mislead the purpose of this option.

Anyway I'll fix the bug you reported.
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1407#issuecomment-1010185571
