### ISSUE TITLE
Disable texture.

### ISSUE THREAD

**Issue by PJGamerr** [PluginBugs/Issues-ItemsAdder#1417]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

is it possible to disable the texture automatically once the player returns to the server hub? that is, that it comes out of the modality in which the itemsadder texture is present?

it often happens that a player enters the mode where itemsadder is present and applies the texture .. but once the player returns to the hub and changes mode the texture remains ..

### Is your feature request related to a problem?

no

### Describe alternatives you've considered

I do not know

**Comment by LoneDev6** [comment]
https://itemsadder.devs.beer/faq/remove-pack-on-server-change
