### ISSUE TITLE
Custom Esc addon for itemsadder plugin.

### ISSUE THREAD

**Issue by PJGamerr** [PluginBugs/Issues-ItemsAdder#1418]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

Hi, a few days ago I installed the "custom esc" addon and it works great .. but once I try to modify the images of the custom esc I can never create one that can be seen clearly in the game .. as I understand I have to create images of maximum x256 pixels, how can I recreate images like those of the default addon that are sharp but so small? I have tried everything but every time in game I always see blurry images ..

### Steps to reproduce the issue

.

### ItemsAdder Version

2.5.3

### ProtocolLib Version

4.7.0

### LoneLibs Version

1.0.16b

**Comment by LoneDev6** [comment]
There is an example which provides an image bigger than 255x255
https://www.spigotmc.org/resources/addon-custom-esc-menu-and-death-screen-for-itemsadder.88809/

> Open the ZIP file and decide which addon you want to use: Small version or HQ version.
Open one of the two folders and extract the content inside plugins/ItemsAdder folder, to overwrite the data folder.
