### ISSUE TITLE
Issues with getting max_custom_durability working

### ISSUE THREAD

**Issue by purejosh** [PluginBugs/Issues-ItemsAdder#1422]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

purejosh#2047

### What happened?

When creating a tool using the same syntax listed in the default itemsadder swords.yml under "aqualight sword", I cannot create a tool or weapon that has more than the default durability for the material used. 

### Steps to reproduce the issue

1. Make a custom tool using "IRON_PICKAXE" as the material, and set the durability to 2000. Try using the Ruby Pickaxe. 
2. Make a custom tool using "DIAMOND_PICKAXE" as the material, and set the durability to 4000. Try using the Ruby Pickaxe. 
3. Note that the tools, when given to you, are 250 and 1561 on the durability, and they are ignoring the requested durability increase that was defined in the config for the tool/weapon. 

### Server version

Paper version git-Paper-76 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 95d881f)

### ItemsAdder Version

ItemsAdder version 2.5.4-beta2

### ProtocolLib Version

ProtocolLib version 4.8.0-SNAPSHOT-b538

### LoneLibs Version

LoneLibs version 1.0.16b

### Problematic items yml configuration file (optional)

```shell
ruby_pickaxe:
    display_name: display-name-ruby_pickaxe
    permission: ruby_pickaxe
    resource:
      material: DIAMOND_PICKAXE
      generate: true
      textures:
      - item/ruby_pickaxe.png
    durability:
      max_custom_durability: 4000
      custom_durability: 4000
      disappear_when_broken: true
```

**Comment by LoneDev6** [comment]
Is this bug introduced by a recent update?
What makes you think that the durability is not correct?
Did you enable the durability lore in config.yml to make sure it's working? `hide-custom-durability-lore: false`

**Comment by purejosh** [comment]
Alright, setting that tag did allow the custom durability to show, which also is showing alongside the normal durability. I believe that is because I'm using tooltips on, and we're also using durability mods. Does IA do durability changes by applying a multiplier to the base durability? For example, base durability is 100 and IA is 20, so every use on the IA tool causes it to go down to 95 and 19 for base and IA?

**Comment by LoneDev6** [comment]
What I need to know is if the item custom durability is correct if you enable the lore setting.
Send me a screenshot, thanks!

There is sadly no way to modify the internal Minecraft item durability, so if you use mods to show the vanilla durability you will get the vanilla durability not the ItemsAdder custom durability which is handled by the plugin internally, not by the game.
Also if you enable F3+H advanced tooltips you will see the vanilla durability no the custom one.

That's why I implemented the lore option.
Anyway your users will see the custom durability in the `/ia` guide menu regardless of the lore setting.
