### ISSUE TITLE
Invisibility Armor Stand....

### ISSUE THREAD

**Issue by PJGamerr** [PluginBugs/Issues-ItemsAdder#1423]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

Hi, I often find invisible armor stands scattered around my server in places where I have never even placed blocks .. as in the screen below .. and removing them with the command "/ execute as PJGamer_ run kill @e [type: ArmorStand, distance ..2] "I am told" Itemsadderprotection killed "so they are caused by the itemsadder plugin .. the invisible armor stands scattered generate lag .. I think it is a very serious bug ..

Use itemsadder v. 2.5.3, I have not updated to 2.5.4 because I read that it is a beta version and in any case it does not solve this problem .. or am I wrong?

### Steps to reproduce the issue

![2022-01-13_20 54 11](https://user-images.githubusercontent.com/85345525/149510553-f1cd6a3c-60cf-4300-bd46-5a0ffd81a87d.png)
![Uploading 2022-01-13_20.53.44.png…]()

### ItemsAdder Version

2.5.3

### ProtocolLib Version

4.7.0

### LoneLibs Version

1.0.16b

**Comment by LoneDev6** [comment]
For some reason protection armorstands are not removed correctly.
Did you kill your server or did it crash in the past?
This is the only reason why the armorstands are not removed.

**Comment by PJGamerr** [comment]
if I understand correctly these invisible armor stands are generated only when a player is loading the texture and crashes .. isn't there a way to totally avoid that during the loading of the texture the armor stand is not generated at all?

**Comment by LoneDev6** [comment]
Yes, disable this option in config.yml `lock-player: false`
