### ISSUE TITLE
Enchant Glint Property

### ISSUE THREAD

**Issue by Litning11** [PluginBugs/Issues-ItemsAdder#1425]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

@Litning11#0090

### Describe the solution you'd like

I'd like to add a property to custom items that allow them to glow like they're enchanted without actually having any enchants. Similar to Golden Apples.

### Is your feature request related to a problem?

Yes, there's no way to make items just *look* enchanted.

### Describe alternatives you've considered

I've tried making the base material a golden apple, but any potion effects you give the items don't work as they're overwritten by the golden apple effects.
Enchanting an item and hiding the enchants don't work as that also removes the glow.

### Additional context

This would be useful to make different types of golden apple foods with different potion effects.

**Comment by SirCraftypants** [comment]
He's referring to enchantment glint, not glow to save confusion. He ideally wants to be apple to use APPLE and give it an Enchantment Glint. If possible is would be quite useful.

**Comment by Litning11** [comment]
@LoneDev6 Sorry for ping, but mind taking a look at this at some point?

**Comment by LoneDev6** [comment]
You can already do that, just add a random enchant to the item and apply the HIDE_ENCHANTS flag.

```yml
    enchants:
      - ARROW_DAMAGE
    item_flags:
      - HIDE_ENCHANTS
```

**Comment by LoneDev6** [comment]
Yep I suggest ARROW_DAMAGE since it has no usage.
In the future I might register a custom enchant with no usage, but it's the same thing.

**Comment by Litning11** [comment]
Thank you for closing this issue without actually fixing it, like I mentioned already that method doesn't work for me.
![image](https://user-images.githubusercontent.com/82062096/156620755-98c358fb-1896-4f73-a009-51464addd19b.png)
My config is set up exactly like that and still the item doesn't glow
![image](https://user-images.githubusercontent.com/82062096/156620831-11940672-0c73-4e02-9994-627575bcd4be.png)

**Comment by Litning11** [comment]
@LoneDev6 I'd like this re-opened until it is actually fixed, even if the error is on my end but nothing that has been suggested so far has worked.

**Comment by SirCraftypants** [comment]
OK enchants don't glow, they glint, glow is completely different

If you want an item to glow you do it like this https://itemsadder.devs.beer/plugin-usage/advanced/item-properties/basic#glow

**Comment by SirCraftypants** [comment]
just because this has been closed, it doesn't mean we don't get notified of new comments.

**Comment by Litning11** [comment]
Okay, my point still stands. They don't GLINT with the methods provided

**Comment by SirCraftypants** [comment]
> Okay, my point still stands. They don't GLINT with the methods provided

Have you tried an alternative enchant id, maybe ARROW_DAMAGE doesn't have a glint.

Try LUCK or LURE

**Comment by LoneDev6** [comment]
https://user-images.githubusercontent.com/27242001/156781993-3b828c45-011d-42d1-850c-cc934f22c2e4.mp4
