### ISSUE TITLE
Title command don't work 

### ISSUE THREAD

**Issue by PJGamerr** [PluginBugs/Issues-ItemsAdder#1433]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

When the itemsadder plugin is active the titles are not shown to the players.

Command Example:
/ title @a title "test"

the title does not appear to anyone .. disabling itemsadder returns to work .. this thing is quite annoying .. is it possible to fix it? Thank you

I haven't updated the plugin to 2.5.4 yet because I've read it's a beta .. and I don't think it fixes this bug right?

### Steps to reproduce the issue

.

### ItemsAdder Version

2.5.3

### ProtocolLib Version

4.7.0

### LoneLibs Version

1.0.16b

**Comment by LoneDev6** [comment]
You seem to have forgotten to set title times before sending it.
`/title @p times 40 120 60`

I tested and works fine for me.
`/title @p times 40 120 60`
`/title @p title {"text":"The End is Near", "bold":true, "italic":true, "color":"red"}`
