### ISSUE TITLE
Important question..

### ISSUE THREAD

**Issue by PJGamerr** [PluginBugs/Issues-ItemsAdder#1437]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

In the itemsadder wiki I read that it is possible to create blocks (not entities) in the generation of the world .. such as leaves on the ground .. stones etc .. I was wondering .. if it is possible to create these "new blocks" that are not entity .. is it possible to do it "out of the generation of the world?" in order to create, for example, home decorations that are blocks and not entities ..
Thank you.

### Is your feature request related to a problem?

.

### Describe alternatives you've considered

.

**Comment by LoneDev6** [comment]
I don't understand your question.
ItemsAdder doesn't use entities to create blocks, they are _blocks_.

Check out this example pack: https://www.spigotmc.org/resources/deco-worlddeco-add-autogenerating-decorations-on-your-world-surface.95207/
