### ISSUE TITLE
Water cannot be filled

### ISSUE THREAD

**Issue by StealthDeci** [PluginBugs/Issues-ItemsAdder#1438]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

Blocks with custom textures are placed in water, and the water will not fill up when broken

### Steps to reproduce the issue

none

### Server version

1.18.1 purpur

### ItemsAdder Version

2.5.4bate2

### ProtocolLib Version

4.8.0-SNAPSHOT-b539

### LoneLibs Version

1.0.16b

### FULL server log

none

### Error (optional)

```shell
none
```

### Screenshots/Videos (you can drag and drop files or paste links)

![GIF 2022-1-20 12-33-13](https://user-images.githubusercontent.com/83644017/150274004-5e34322a-dff9-4546-83c6-f3e1c74ebf7f.gif)

**Comment by LoneDev6** [comment]
I'll work on this, thanks

**Comment by StealthDeci** [comment]
Although problems emerge one after another, you always try to solve it at the first time. thank you very much! happy new year

**Comment by StealthDeci** [comment]
> 我会努力解决这个问题，谢谢

Although problems emerge one after another, you always try to solve it at the first time. thank you very much! happy new year

**Comment by LoneDev6** [comment]
No problem! Happy new year ^^
