### ISSUE TITLE
BUG when placing furniture

### ISSUE THREAD

**Issue by paulreob** [PluginBugs/Issues-ItemsAdder#1440]
### Discord tag (optional)

! Pau#9216

### What happened?

When trying to place a stuffed animal without a hitbox on a piece of furniture with a hitbox, it is placed laterally and not on the floor.
This also happens with furniture with hitboxes placed one on top of the other.

I attach video and configuration of the corresponding furniture.

### Steps to reproduce the issue

1. First place the cabinet with hitbox
2. Try to place the stuffed animal without the hitbox on the furniture. 
You can't just right click, you have to shift + right click.
3. You will see that the stuffed animal is positioned laterally.

### Server version

This server is running Purpur version git-Purpur-1509 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: b88a81e on HEAD

### ItemsAdder Version

ItemsAdder version 2.5.5

### ProtocolLib Version

ProtocolLib version 4.8.0-SNAPSHOT-b539

### LoneLibs Version

LoneLibs version 1.0.16b

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: 127.0.0.1
      pack-port: 8163
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: true
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      _: 'Available values: VANILLA_1_17 or OPTIFINE'
      enabled: true
      mode: VANILLA_1_17
    fix_transparent_noteblocks__disable-for-more-performance: true
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
    disable-overwrite-leather-armor-layers-textures: false
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-items: false
  extract-default-resources: false
blocks:
  light-api: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: false
  disable-FIRE: false
  fix-liquids-flow: true
  fix-floating-blocks: true
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
  fix-packet-too-large-kick: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
```

### Problematic items yml configuration file (optional)

```shell
perry_peluche:
    resource:
      material: PAPER
      generate: false
      model_path: custom/decorations/perry_peluche
    behaviours:
      furniture:
        entity: item_frame
        solid: false
        placeable_on:
          walls: false
          ceiling: false
          floor: true

  reposapies_birch:
    specific_properties:
      leather_horse_armor:
        color: WHITE
    resource:
      material: LEATHER_HORSE_ARMOR
      generate: false
      model_path: custom/blocks/furniture/birch_footstool
    behaviours:
      furniture:
        entity: item_frame
        light_level: 13
        solid: true
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          height: 1
        sound:
          place:
            name: block.metal.fall
          break:
            name: block.metal.break
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://gyazo.com/213a7973b5a6e2e87e2343c068488cb9

https://gyazo.com/c98d372c74ff3d4de3914cc47217f0a8

**Comment by SirCraftypants** [comment]
This is not a bug, don't use leather horse armor for furniture, use PAPER, only use ITEM_FRAME if you actually intend on allowing the item to be placed on a wall or ceiling which it shows you're not. Use ARMORSTAND with the small attribute. Also you are using `        solid: true` which places and invisible barrier block so that you can place an item or block on top of the models. This was implemented for placing items on furniture like tables, if you make the seating lower than 6 pixel blocks then anything you place in top of it will look like it's floating. placing an item on a seat is not the same as a player sitting on a seat.

**Comment by SirCraftypants** [comment]
if you want the animal sitting on the footstool then just make the stool and animal 1 model.

**Comment by paulreob** [comment]
Why not use horse armor?! How the fuck do you want me to dye the furniture ._.

**Comment by paulreob** [comment]
Makes another model with the stool and the animal, not what I'm looking for, it's not practical to do that.

**Comment by SirCraftypants** [comment]
> Why not use horse armor?! How the fuck do you want me to dye the furniture ._.

first of all mind your language, second, all you had to say was your were using horse armor for that purpose. If you don't want to make them 1 then your only other option is to raise your footstool is 16 block height and use the solid attribute.

**Comment by SirCraftypants** [comment]
`perry_peluche:
    resource:
      material: PAPER
      generate: false
      model_path: custom/decorations/perry_peluche
    behaviours:
      furniture:
        entity: armor_stand
        small: true
        fixed_rotation: false

  reposapies_birch:
    specific_properties:
      leather_horse_armor:
        color: WHITE
    resource:
      material: LEATHER_HORSE_ARMOR
      generate: false
      model_path: custom/blocks/furniture/birch_footstool
    behaviours:
      furniture:
        entity: armor_stand
        small: true
        light_level: 13
        solid: true
        fixed_rotation: true
        sound:
          place:
            name: block.metal.fall
          break:
            name: block.metal.break`

**Comment by SirCraftypants** [comment]
Im guessing the placing of an itemframe on top of another itemframe could be the cause of the model being placed vertically on top of the stool.

**Comment by paulreob** [comment]
https://gyazo.com/6a6185b4aa009035ddd966170c43be55

It also happens if I try to place it on REAL_WIRE blocks.

**Comment by SirCraftypants** [comment]
> https://gyazo.com/6a6185b4aa009035ddd966170c43be55
> 
> It also happens if I try to place it on REAL_WIRE blocks

Are you still using item_frame for those models?

**Comment by LoneDev6** [comment]
Basically what I need to fix the height of where furniture get placed on REAL_NOTE blocks?
Is this what this issue report is about?

**Comment by LoneDev6** [comment]
Anyway here is an explanation on when to use armor_stand and when to use item_frame.
https://itemsadder.devs.beer/plugin-usage/adding-content/advanced/furniture/furniture-entity
