### ISSUE TITLE
BUG when placing furniture with Hitboxes

### ISSUE THREAD

**Issue by paulreob** [PluginBugs/Issues-ItemsAdder#1441]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

! Pau#9216

### What happened?

When placing a piece of furniture one block high and 2 blocks long, facing west and north, the hitbox is placed 1 block towards me, so that half of the piece of furniture is outside the hitbox.

Facing east and south is placed correctly...

### Steps to reproduce the issue

see attached video

### Server version

1.18.1

### ItemsAdder Version

ItemsAdder version 2.5.5

### ProtocolLib Version

 ProtocolLib version 4.8.0-SNAPSHOT-b539

### LoneLibs Version

LoneLibs version 1.0.16b

### Problematic items yml configuration file (optional)

```shell
birch_couch:
    specific_properties:
      leather_horse_armor:
        color: WHITE
    resource:
      material: LEATHER_HORSE_ARMOR
      generate: false
      model_path: custom/blocks/furniture/birch_couch
    behaviours:
      furniture:
        entity: item_frame
        fixed_rotation: true
        light_level: 13
        solid: true
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          height: 1
          length: 2
      furniture_sit:
        sit_height: 1
        sound:
          place:
            name: block.metal.fall
          break:
            name: block.metal.break
```

### Screenshots/Videos (you can drag and drop files or paste links)

Video looking west and north
https://gyazo.com/dd64b6d084db1a0c2dce72ecc79c7488
Video looking east and south
https://gyazo.com/608232ba6cb2f21fb6f77e1846d99a88

**Comment by LoneDev6** [comment]
You didn't specify any offset, check my examples: https://www.spigotmc.org/resources/furniture-itemsadder-more-furniture.93193/

```yml
        hitbox:
          length: 1
          width: 2
          height: 1
          width_offset: 0.5
```

To preview the offset you have to run `/iahitbox`, then place the furniture and see it.
