### ISSUE TITLE
Non riesco a creare un blocco.

### ISSUE THREAD

**Issue by PJGamerr** [PluginBugs/Issues-ItemsAdder#1442]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

(Se non sbaglio se scrivo in italiano mi capisci giusto? ahah)

Ho seguito la wiki passo passo.. il blocco viene aggiunto al gioco ma la texture non funziona.. 

### Steps to reproduce the issue

![2022-01-21_10 16 59](https://user-images.githubusercontent.com/85345525/150500276-58d479f9-ae90-4a8c-8cdd-42ecbc573a56.png)
![2022-01-21_10 17 04](https://user-images.githubusercontent.com/85345525/150500292-56c812a2-a49c-4388-99b7-9d3aa72134cc.png)
![2022-01-21_10 17 08](https://user-images.githubusercontent.com/85345525/150500296-1de0f6a5-b73b-4bb5-ad2f-a6c04a97ca58.png)
![hhhh](https://user-images.githubusercontent.com/85345525/150501630-de38c595-4496-4b48-8c19-935a22e7bf25.png)
![www](https://user-images.githubusercontent.com/85345525/150500628-eb580cf3-6cad-4f26-bc49-5226f74affe4.png)
eab-1623-4d93-a3ca-33d5bf2858da.png)
![hhhhh](https://user-images.githubusercontent.com/85345525/150500837-6d4d215a-d364-41f4-8620-ce54e88cf2cd.png)

Questa è la texture:
500x500

![medievalcity_block](https://user-images.githubusercontent.com/85345525/150500928-2aa47bb1-11f8-488c-b0d3-2c6898154d74.png)

### Server version

1.18.1

### ItemsAdder Version

2.5.3

### ProtocolLib Version

4.7.0

### LoneLibs Version

1.0.16b

**Comment by LoneDev6** [comment]
Il percorso è sbagliato e non devi mettere .png alla fine.

![immagine](https://user-images.githubusercontent.com/27242001/150501583-c9251e57-a327-4343-b9dc-c64126c06f01.png)

Dovresti scrivere così, in base a dove hai messo il file:

```yml
textures:
  - medievalcity_block
```

E non

```yml
textures:
  - block/medievalcity_block.png
```

Per quanto riguarda i problemi di questo tipo utilizza questo metodo, ti mostra esattamente perché un modello non è stato caricato correttamente dal gioco (non dal server): https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown#enable-output-log
Questo metodo mostra i log del GIOCO non del SERVER, ti aiuta a capire come mai delle cose del pack non sono state caricate correttamente.

Comunque in realtà già nel log del SERVER dovresti aver letto un errore riguardo il fatto che la texture del blocco non è stata trovata... mi sembra un po' strano non ci fosse nulla a riguardo e non posso controllare dato che non c'è nessun log incluso.

Comunque quando reporti un problema non postare screenshot ma carica il testo, altrimenti ci metto più tempo ad aiutare, vorrei aiutare nel minor tempo possibile

Buona giornata e spero di averti chiarito le idee, buona fortuna col tuo progetto

**Comment by PJGamerr** [comment]
wiki: 

Using the same texture for each face
info:
  namespace: myitems
items:
  red_block:
    display_name: Red Block
    permission: red_block
    resource:
      generate: true
      material: PAPER
      textures:
        - block/red_block.png

c'è sia png che block/ davanti.. 

ho risolto, grazie mille, supporto veramente perfetto! ma dovresti correggere questa cosa nella wiki no?

**Comment by LoneDev6** [comment]
Ti spiego:
`png` puoi toglierlo che non serve, ma dovrebbe funzionare comunque.

`block/` lo devi mettere solo se il tuo file immagine è nella cartella `block`, nella wiki sembra ci sia un errore, ora lo correggo, grazie!

**Comment by LoneDev6** [comment]
Ho corretto l'immagine:
![immagine](https://user-images.githubusercontent.com/27242001/150507856-7d5a733d-3369-4b86-8c15-778b1b61c80c.png)
