### ISSUE TITLE
Minecraft model animator [Fixed]

### ISSUE THREAD

**Issue by PJGamerr** [PluginBugs/Issues-ItemsAdder#1445]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

I'm following the wiki step by step to create a custom mob with its animation .. but getting to the point of uploading the animation frames to the site:

https://lonedev6.github.io/animated-models/

it keeps giving me error .. I have created (as mentioned in the wiki) a temporary folder on the desktop, and I have inserted the .json files (the various frames) inside, but once uploaded to the Minecraft model animator site it continues to give me this error:

Couldn't find texture "medievalcity: yellowkey.png".

Can I have clarifications on where exactly the json files and the texture must be before uploading them to the site to avoid errors? in the wiki this thing is not explained ..

Thank you.

### Steps to reproduce the issue

.

### ItemsAdder Version

2.5.3

### ProtocolLib Version

4.7.0

### LoneLibs Version

1.0.16b

**Comment by LoneDev6** [comment]
Send me a screenshot of these errors, I don't know where you read them.
Thanks!
