### ISSUE TITLE
Custom model data items not working right 

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#1446]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

SLoKer#5953

### What happened?

when i tryed to get item with command /minecraft:give SLoKerYT minecraft:wooden_axe{custommodedata:10000} 1
the item doesn't have any ( custom model ) it's default 
( i think there a problem , with custom mode
![custom-leafsss3](https://user-images.githubusercontent.com/68678154/150643750-6afb0f49-d3c0-407a-affd-900d47b34436.gif)
l data numbers )

### Steps to reproduce the issue

just get any custom model data item and it's gonna be default without texture

### Server version

This server is running Paper version git-Paper-167 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: feb72b8)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-152 (MC: 1.18.1)

### ItemsAdder Version

![image](https://user-images.githubusercontent.com/68678154/150643870-6587e4e2-1ef3-4029-bf77-c7f5d570f362.png)

### ProtocolLib Version

![image](https://user-images.githubusercontent.com/68678154/150643881-5aa1e366-cd95-4b36-a82f-3b38ec208d3a.png)

### LoneLibs Version

![image](https://user-images.githubusercontent.com/68678154/150643905-56399f71-16ec-4ffb-bac1-24f505d3f4da.png)

**Comment by HakanUnsalP** [comment]
![image](https://user-images.githubusercontent.com/58227275/152531485-c6c895d1-3e19-4692-baaf-91eccff56cc9.png)

**Comment by SNokerYT** [comment]
oops! Thanks, HakanUnsalP 😂
this is the most stupid report I have been made xD
