### ISSUE TITLE
Online editor warning issue

### ISSUE THREAD

**Issue by QuentiumYT** [PluginBugs/Issues-ItemsAdder#1455]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

QuentiumYT#0207

### What happened?

This warning issue shows up on every possible yml config file

![image](https://user-images.githubusercontent.com/35229942/151414357-9178e850-17be-4f92-a16e-ba015f689bef.png)

Also, is it possible to open source it?

### Steps to reproduce the issue

Go on https://ide.devs.beer/itemsadder/

### ItemsAdder Version

/

### ProtocolLib Version

/

### LoneLibs Version

/

### ItemsAdder config.yml

```shell
/
```

**Comment by LoneDev6** [comment]
Fixed, thanks!
