### ISSUE TITLE
Furnace Permission Glitch

### ISSUE THREAD

**Issue by ColorsASD** [PluginBugs/Issues-ItemsAdder#1460]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Eriik#0580

### What happened?

Permission system can be played!

### Steps to reproduce the issue

https://imgur.com/a/D48URzd

### Server version

git-Purpur-1428 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9beb23b on ver/1.17.1)

### ItemsAdder Version

ItemsAdder version 2.5.5

### ProtocolLib Version

ProtocolLib version 4.7.0

### LoneLibs Version

LoneLibs version 1.0.16b

### LightAPI Version (optional)

LightAPI version bukkit-5.1.0 (build SNAPSHOT)

### LibsDisguises Version (optional)

LibsDisguises version 10.0.27

### FULL server log

Nothing happens in the console.

### ItemsAdder config.yml

```shell
Nothing happens in the config.
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://imgur.com/a/D48URzd

**Comment by LoneDev6** [comment]
I fixed it in v3.0.0, will be released in the next days.


https://user-images.githubusercontent.com/27242001/153844029-4929a526-c2c0-46f4-980d-0129beef026c.mp4
