### ISSUE TITLE
[Suggestion] The possibility of lying on the furniture

### ISSUE THREAD

**Issue by chimal1994** [PluginBugs/Issues-ItemsAdder#1463]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

For example:

behaviours:
      furniture:
        small: true
      furniture_lay:
        lay_height: 0.5

### Is your feature request related to a problem?

It would be easier to make custom beds.
Currently we use third-party plugins and the option to execute commands

### Describe alternatives you've considered

Do not consider any as it seems to me that a workaround is not necessary

**Comment by LoneDev6** [comment]
It's impossible to trigger the lay animation for the current player, only other players will see it.
It would look awful and feel bugged. I cannot implement that feature.
