### ISSUE TITLE
CreativeManager with Slimefun problem

### ISSUE THREAD

**Issue by 100petr** [PluginBugs/Issues-ItemsAdder#1469]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

pitilon#6950

### What happened?

I switched to the CreativeManager plugin (https://www.spigotmc.org/resources/⚡-creativemanager-⚡-customizable-complete-control.75097/), the author block the placing of slimefun stuff in creative. It works on a clean server, but once I had the CM + IA + sf + sf addons (+-25), or other plugins (+-50), it didn't work anymore. After removing the itemsadder, it could no longer be placed (which is correct), although I had all the other plugins on the server.

### Steps to reproduce the issue

Add this to the server https://discord.com/channels/@me/937712191329669150/937717480925831218
For example, try placing a small capacitor in the creative

### Server version

 This server is running Paper version git-Paper-177 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 2e99e5e)

### ItemsAdder Version

ItemsAdder version 2.5.5

### ProtocolLib Version

ProtocolLib version 4.8.0-SNAPSHOT-b538

### LoneLibs Version

LoneLibs version 1.0.16b

### LibsDisguises Version (optional)

LibsDisguises version 10.0.27-SNAPSHOT

**Comment by LoneDev6** [comment]
I have a check to prevent Slimefun items to be interfered by my place event.
It used to work just fine.

```java
if (Main.hasSlimefun)
{
    NBTItem tmp = new NBTItem(itemStack);
    if (tmp.hasNBTData() && tmp.hasKey("PublicBukkitValues")
            && tmp.getCompound("PublicBukkitValues").hasKey("slimefun:slimefun_item"))
    {
        return;
    }
}
```

This CreativeManager code seems to be the problem:
https://github.com/K0bus/CreativeManager/blob/master/src/main/java/fr/k0bus/creativemanager/event/plugin/SlimeFun.java#L102


I think they must call these two functions and mark them as [DENY](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/Event.Result.html#DENY)

https://slimefun.github.io/javadocs/Slimefun4/docs/io/github/thebusybiscuit/slimefun4/api/events/PlayerRightClickEvent.html#setUseBlock(org.bukkit.event.Event.Result)
https://slimefun.github.io/javadocs/Slimefun4/docs/io/github/thebusybiscuit/slimefun4/api/events/PlayerRightClickEvent.html#setUseItem(org.bukkit.event.Event.Result)

**Comment by K0bus** [comment]
Hi, @LoneDev6 
I'm the CreativeManager dev.
I try tu Deny the two result on your Event but actually don't Work.
What lib do you use for NBTItem ?

**Comment by LoneDev6** [comment]
https://www.spigotmc.org/resources/nbt-api.7939/

**Comment by LoneDev6** [comment]
I was referring to [this line](https://github.com/K0bus/CreativeManager/blob/9820a2470a0320c4b45f6f2f5f8012c118ebe553/src/main/java/fr/k0bus/creativemanager/event/plugin/SlimeFun.java#L102). I updated my original comment.
