### ISSUE TITLE
[Suggestion] Make thirst value can restore by drink water.

### ISSUE THREAD

**Issue by R-Josef** [PluginBugs/Issues-ItemsAdder#147]
**Is your feature request related to a problem? Please describe.**
I own a server, my player always complains of the thirst value is annoying.

**Describe the solution you'd like**
I think it will be better if drink a bottle of water can restore thirst value.

**Describe alternatives you've considered**
Make a option in config file to disable thirst.

**Comment by LoneDev6** [comment]
you can disable thirst

open plugins\ItemsAdder\data\items_packs\realcraft\huds.yml
and disable thirst

```
  thirst_bar:
    enabled: false
```

**Comment by R-Josef** [comment]
oh, thank you. but will you let drink a bottle of water can restore thirst?

**Comment by LoneDev6** [comment]
Yes it's a good idea

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/413
