### ISSUE TITLE
Visual bug with custom model

### ISSUE THREAD

**Issue by PJGamerr** [PluginBugs/Issues-ItemsAdder#1471]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

hi, I found a pretty annoying bug, I practically created some custom models with blockbench and I inserted them in the plugin following the wiki .. the custom blocks / models work perfectly but generate this annoying visual bug (I made some texts by removing my models custom and the bug disappears)

![2022-02-01_11 37 56](https://user-images.githubusercontent.com/85345525/151960555-797c03f0-da8c-47a3-9ec5-ef28994fe2aa.png)

![2022-02-01_11 38 17](https://user-images.githubusercontent.com/85345525/151960540-6029dca8-b16c-4793-8a99-455f224e1119.png)

same screen, same position, with zoom:

![2](https://user-images.githubusercontent.com/85345525/151961299-8eb773e5-e8c8-4c2c-baf8-476088d97098.PNG)

![1](https://user-images.githubusercontent.com/85345525/151961284-e9a1fead-baa4-4327-87c3-c586a36238b4.PNG)

the only difference I found between my templates and the default plugin ones is that my templates refer to the texture folder directly instead the default plugin ones have a subfolder, example:

Mine: / root / SurvivalFantasy / plugins / ItemsAdder / data / resource_pack / assets / medievalcity / textures /

Plugin:
/ root / SurvivalFantasy / plugins / ItemsAdder / data / resource_pack / assets / itemsadder / textures / block /

could this be the cause?

### Steps to reproduce the issue

.

### ItemsAdder Version

2.5.5

### ProtocolLib Version

4.7.0

### LoneLibs Version

1.0.16b

**Comment by LoneDev6** [comment]
https://itemsadder.devs.beer/faq/i-see-crisp-textures-far-away

**Comment by LoneDev6** [comment]
16x16, 32x32, 64x64, 128x128, 256x256, 512x512 and 1024x1024 etc.
This is generally how computer graphics work, you must use power of two sizes to avoid this kind of issues.
Have a nice day!
