### ISSUE TITLE
API broken after reload of ItemAdder.

### ISSUE THREAD

**Issue by SwartZCoding** [PluginBugs/Issues-ItemsAdder#1474]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Anto'#1234

### What happened?

When i /iareload the plugin, my custom craft with custom plugin didn't work if i don't restart the server.

I think the API is broken after a reload of ItemAdder.

### Steps to reproduce the issue

1. I put craft on my custom plugin for an item managed by ItemAdder.
2. i try to craft this item. ATM the craft works.
3. i make /iareload
4. i retry this same craft and now it didn't work again.
5. Restart the server and now it re-work.

### Server version

This server is running Paper version git-Paper-790 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 4 version(s) behind
Previous version: git-Purpur-1171 (MC: 1.16.5)

### ItemsAdder Version

2.5.3

### ProtocolLib Version

4.7.0

### LoneLibs Version

1.0.16b

### Screenshots/Videos (you can drag and drop files or paste links)

Before /iareload : https://gyazo.com/ca7ac98f9d6e53d221373a9ebc11ebe0
After /iareload : https://gyazo.com/13f1ec2c138da3d40ffec1e559d3a10e

**Comment by LoneDev6** [comment]
You have to listen to the itemsadder reload event and register again your recipes.
