### ISSUE TITLE
Make a silent give command

### ISSUE THREAD

**Issue by Apiz05** [PluginBugs/Issues-ItemsAdder#1477]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Aech_#1655

### Describe the solution you'd like

I want it to be added cause it will helpful when it come to custom gui

### Is your feature request related to a problem?

nope

### Describe alternatives you've considered

nope

### Additional context

nope

**Comment by LoneDev6** [comment]
`/iagive <player> <itemname> [amount] [silent]`
please read the wiki
