### ISSUE TITLE
Shapeless recipes

### ISSUE THREAD

**Issue by paulreob** [PluginBugs/Issues-ItemsAdder#1481]
### Discord tag (optional)

! Pau#9216

### Describe the solution you'd like

RECIPES WITHOUT PATTERN
I am sure that this can be achieved easily, as it says in the title that you can create recipes without a specific pattern, so you could craft in any slot of the crafting table.

Take the example of the vanilla oak log, you place it in any slot on the crafting table and it gives you 4 oak planks.

I think it's not feasible to create multiple patterns just to accomplish this ... 

### Describe alternatives you've considered

This is an alternative to using recipe patterns so you don't have to create several patterns that would not be feasible ...

**Comment by ProfessionalBoatDrifter** [comment]
Yes, a hundred times, yes! I've been thinking about this for a while too, especially given how often people have been reporting in broken recipes.
Yeah, we can add alternative recipes but I feel like that's just madness...

Why not add this as a setting: `shapeless: true`?

Example using the default crops.yml file:
```
info:
  namespace: itemsadder
recipes:
  crafting_table:
    tomato_seeds:
      permission: itemsadder.crops
      enabled: true
      shapeless: true # This would simply ignore the "pattern:" and just check for the required items and/or amounts in the crafting area.
      pattern:
      - XXX
      - XOX
      - XXX
      ingredients:
        O: itemsadder:tomato
      result:
        item: itemsadder:tomato_seeds
        amount: 1
```

**Comment by LoneDev6** [comment]
This had been asked hundred times and I always answer the same: this is complicated, I will try my best to add this feature but it's not really easy to add this feature without introducing lag and dupe bugs.

**Comment by DrkMatr1984** [comment]
<3 <3 <3

**Comment by DayzDuck** [comment]
what about the possiblitly to add it with only one ingredient. for example:

```
info:
  namespace: aiena
recipes:
  crafting_table:
    color01:
      permission: color
      enabled: true
      shapeless: true
      ingredients:
        s: OAK_LEAVES
      result:
        item: GREEN_DYE
        amount: 1
```
