### ISSUE TITLE
Items-Adder TexturePack Problem

### ISSUE THREAD

**Issue by MrHyperMC** [PluginBugs/Issues-ItemsAdder#1484]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

UrageX#0975

### What happened?

Hello
I need a little help. After packing the ItemsAdder plugin texture pack with the command /iazip, (...completed...), I take out the texture and everything in it crashes, and dont working... ()

Thank you for help.

### Steps to reproduce the issue

1. I put my "addon" resources into items adder data/resource_packs/
2. I use command /iazip
3. Completed the zipping...
4. It wont work, I cant remove files from the zip.

### Server version

This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### ItemsAdder Version

Latest, 2.5.5

### ProtocolLib Version

Latest, 4.7.0

### LoneLibs Version

LoneLibs, 1.0.16b

### LightAPI Version (optional)

LightAPI 5.1.0

### FULL server log

There are no logs needed.

### Error (optional)

```shell
-
```

### ItemsAdder config.yml

```shell
default
```

### Problematic items yml configuration file (optional)

```shell
default
```

### Other files, you can drag and drop them here to upload. (optional)

[pack.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/8054709/pack.zip)

### Screenshots/Videos (you can drag and drop files or paste links)

![unknown](https://user-images.githubusercontent.com/78217004/153732388-c50f6e2c-93fd-4ae4-8e37-d90447132b94.png)
![unknown](https://user-images.githubusercontent.com/78217004/153732389-a13cf605-0ae1-4fbc-ae98-823cbea4ff94.png)
![unknown](https://user-images.githubusercontent.com/78217004/153732391-aaea71e3-25a0-4937-b93d-b02a614911f5.png)

**Comment by LoneDev6** [comment]
>  I take out the texture and everything in it crashes

I don't understand, I also need a complete log of your server of when the issue happened.

**Comment by LoneDev6** [comment]
Anyway the size is 0 because it's protected.. you're not supposed to open the zip file manually.
If you don't want the zip file to be protected disable protection in the config.yml of ItemsAdder
