### ISSUE TITLE
Add command to dye hand items

### ISSUE THREAD

**Issue by paulreob** [PluginBugs/Issues-ItemsAdder#1491]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

This command will tint the item you have in hand, this would be very useful when tinting furniture without the need to create another configuration to vary the color.....

the furniture for example would be made of leather_horse_armor material to be able to dye it as it says in the wiki

the ser command 
`/ie dye #HEX`
o
`/ie dye 225 255 255`

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

this is an alternative to not using other item editing plugins, or creating many ItemsAdder configs just to change the item.

**Comment by LoneDev6** [comment]
I'll implement a free separate plugin for that since it's out of scope.

**Comment by LoneDev6** [comment]
Apologizes for the extremely long wait. I had to prioritize other issue reports during the years.
`/iacolor <color> [player]`. Example: `/iacolor #32a852 LoneDev`

I hope this is still needed, thanks again for the very welcome patience.
