### ISSUE TITLE
/iadrop doesn't support negative coordinate values

### ISSUE THREAD

**Issue by ProfessionalBoatDrifter** [PluginBugs/Issues-ItemsAdder#1492]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Akrill#0001

### What happened?

Using the command `/iadrop` to drop an item at any negative coordinate either returns a "[ItemsAdder] This player is offline" or a "[ItemsAdder] Wrong command usage" message.

### Steps to reproduce the issue

Can skip steps 1 -> 6

1. Go to x0 y z0 in the world `world`
2. Run command `/iadrop itemsadder:ruby 0 ~ 0 world 1` (~ is placeholder for the y coordinate in this report)
3. Item drops as expected
4. Go to `x10 Y z0` in the world `world`
5. Run command `/iadrop itemsadder:ruby 10 ~ 10 world 1`
6. Item drops as expected

7. Go to x-10 y z-10 in the world `world`
8. Run command `/iadrop itemsadder:ruby -10 ~ -10 world 1`
9. Receive error message: "[ItemsAdder] This player is offline"
10. Go to x10 y z-10 in the world `world`
11. Run command `/iadrop itemsadder:ruby 10 ~ -10 world 1`
12. Receive error message: "[ItemsAdder] Wrong command usage"

### Server version

This server is running Paper version git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)

### ItemsAdder Version

ItemsAdder version 2.5.5

### ProtocolLib Version

ProtocolLib version 4.8.0-SNAPSHOT-b538

### LoneLibs Version

LoneLibs version 1.0.16b

### LightAPI Version (optional)

LightAPI version bukkit-5.1.0 (build SNAPSHOT)

### LibsDisguises Version (optional)

LibsDisguises version 10.0.27-SNAPSHOT

**Comment by LoneDev6** [comment]
Will be fixed in 3.0, thanks
