### ISSUE TITLE
Security issue & not being able to upload resource pack 

### ISSUE THREAD

**Issue by SuperIsSuper** [PluginBugs/Issues-ItemsAdder#1493]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Super#0001

### What happened?

What has happen was that itemsadder was working fine and all was well, but Minehut has released an update, which changed the way uploading the resourcepack is done. What they did now it when you get the link from dropbox you would need to go to their panel and paste the link there, which checks if the resource pack is safe to use and then the user can user the link from them which is not .zip.  They have told me it should work like it used to with itemsadder. 

The user that said it was FiXed#2721 and told me to give him the resource link on spigot. I have done as told and after doing the steps he told me to do it did not work with itemsadder. Reason probably for this was that is probably that Itemsadder did not recognise .zip file which is why it did not work. Additionally, now /iatexture SuperJava « does not work as it is probably disabled by Minehut or requires a safe link from Minehut panel. 

When I told FiXed#2721 that it does not work he said it is the developer's fault. I told him its not because Minehut are the one that added this unless update, which I do not seem to understand how it would damage someone's computer. He said a new regulation came out which requires them to do this and said they might not add this, which would work with Itemsadder feature.

Furthermore, I did not like his attitude because at first he thought I owned the plugin and told me the plugin is rubbish and was not made well. I have followed with reporting him to higher ups because he did not deal with the situation well and he treated the situation as it was a joke. I have spent like $5000 on Minehut and him acting like this made me feel unsafe in keeping my data with Minehut and also using their services. I hope Minehut deals with such behaviour because they do not seem professional in any shape or form. 

LoneDev, I am therefore asking you to add a fix for this in order to make it work with their link protection panel, which provides a different type link. I would want this and so would other players in order to make it work. I understand Minehut are not fair and I would switch rather to an external server, however, I have spent a lot in upgrades on Minehut and also time in settings everything up, which took my months. 

### Steps to reproduce the issue

I have pasted the link from dropbox and it does not work anymore, it requires me to paste the link to Minehut panel which checks for abnormal content. I the use the link to itemsadder config and it does not work as it does not recognise it. 

### Server version

1.17.1 paper

### ItemsAdder Version

2.5.5

### ProtocolLib Version

4.7.0

### LoneLibs Version

1.0.16b

**Comment by LoneDev6** [comment]
Hello,
I have no idea who is `FiXed#2721` nor am I affiliated with `Minehut` and what I feel like is that they are just trying to wash their hands and tell you that it's my fault.
ItemsAdder is working fine on 1300+ servers, so it's likely to be a Minehut issue. 

I didn't get much details in this Github report so, based on what I can read, I suspect they are blocking network calls to external urls.
ItemsAdder is checking if the resourcepack URL is reachable or not, to avoid players from being stuck at login (Minecraft bug).
What you can do is set `skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: true` in config.yml of ItemsAdder and try again.

Feel free to provide me a full server log and add more details if my advice doesn't work.


Have a nice day

**Comment by SuperIsSuper** [comment]
Hi, I have done as you said and it works now, however, when I do /iatexture Superjava « it does nothing. before it worked well but now it does not work in loading the texture and I am not getting any errors from console

**Comment by LoneDev6** [comment]
I need a full log and your resourcepack dropbox link.
