### ISSUE TITLE
Urgently add block hardness for a specific tool so I can specify it in the configs!

### ISSUE THREAD

**Issue by MrJorman** [PluginBugs/Issues-ItemsAdder#1498]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

CrackedLix#3875

### Describe the solution you'd like

I want to be able to specify for each tool and custom item my block strength and the speed of its extraction, since a wooden pick breaks a block with hardness 5.0 at the same speed as a non-granite one. please add your own block mining speed for each tool, this is very necessary!

### Is your feature request related to a problem?

I want to be able to specify for each tool and custom item my block strength and the speed of its extraction, since a wooden pick breaks a block with hardness 5.0 at the same speed as a non-granite one. please add your own block mining speed for each tool, this is very necessary!

### Describe alternatives you've considered

https://pastebin.com/cXy472pS see example config.

**Comment by LoneDev6** [comment]
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/1268
