### ISSUE TITLE
Finally add "sound_hit, sound_step" for blocks! I want to break blocks, not note blocks!

### ISSUE THREAD

**Issue by MrJorman** [PluginBugs/Issues-ItemsAdder#1499]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

CrackedLix#3875

### Describe the solution you'd like

Finally add "sound_hit, sound_step" for blocks! I want to break blocks, not note blocks!

### Is your feature request related to a problem?

I think there is no need to explain anything and so everything is clear, please do it - it is very important, really.

### Describe alternatives you've considered

I think there is no need to explain anything and so everything is clear, please do it - it is very important, really.

**Comment by Hrobitaillie** [comment]
Hi, i don't understand why there is not this functionnality.
It's a major problem, itt looks like they ignore this feature

**Comment by LoneDev6** [comment]
Duplicate https://github.com/PluginBugs/Issues-ItemsAdder/issues/1260
