### ISSUE TITLE
Tomato Bush stops growing

### ISSUE THREAD

**Issue by ProfessionalBoatDrifter** [PluginBugs/Issues-ItemsAdder#1507]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Akrill#0001

### What happened?

>Tomato Bushes seem to randomly stop growing at certain stages.

Breaking and replacing the Tomato Bush fixes this.
Using Bone Meal on the Tomato Bush fixes this.

### Steps to reproduce the issue

1. Create a large field of tilled soil (suggested: 14x10 to 20x20, to minimize waiting time)
2. Plant Tomato Seeds
3. Wait a few minutes (2-5) and take note of which Tomato Bushes are grown and which aren't
4. Wait 15-30 minutes (to be sure) and note which Tomato Bushes are still not grown

### Server version

This server is running Paper version git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)

### ItemsAdder Version

ItemsAdder version 2.5.5

### ProtocolLib Version

ProtocolLib version 4.8.0-SNAPSHOT-b538

### LoneLibs Version

LoneLibs version 1.0.16b

### FULL server log

No errors.

**Comment by LoneDev6** [comment]
I can't reproduce the issue, it works fine for me, maybe there is a plugin interfering with crops? ItemsAdder uses the same vanilla code for crops.
https://streamable.com/nnlw1n
