### ISSUE TITLE
[CRITICAL] Massive lag causing Itemsadder

### ISSUE THREAD

**Issue by ArtifactyNight** [PluginBugs/Issues-ItemsAdder#1508]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

NightKunGz#0790

### What happened?

I found the problem when player is up to 40-60
the TPS will down to 6-10 and mspt will 100+

i'm checking with spark so it's happen because of itemsadder

for now, i'm tried to remove ItemsAdder
and my server is fine now (70 players but TPS still 19+ and 30-50 mspt)

My Server Spec is
Ryzen 9 5950X
RAM 32 3200 MHz
1TB SSD M.2 (No HDD)

https://spark.lucko.me/uq3XfGWAwm

![image](https://user-images.githubusercontent.com/53427253/155162984-8279c434-a2ff-4908-b7ea-040cbd0ac66c.png)

![image](https://user-images.githubusercontent.com/53427253/155163932-5f6c94f4-f16b-4900-85a6-e245a964058b.png)

### Steps to reproduce the issue

None

### Server version

`git-Pufferfish-45 (1.18.1)`

### ItemsAdder Version

2.5.5

### ProtocolLib Version

4.8.0-SNAPSHOT

### LoneLibs Version

1.0.16b

### LightAPI Version (optional)

5.1.0

### FULL server log

None, I removed ItemsAdder since 16/02/2022

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: 127.0.0.1
      pack-port: 50008
    external-host:
      enabled: false
      url: https://download.mc-packs.net/pack/fa7e15706a09fd9041a34bf2403c67b48bf1de8b.zip
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 0
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
    compress-png-files: true
    compress-json-files: true
    generate-custom-armors-textures:
      _: 'Available values: VANILLA_1_17 or OPTIFINE'
      enabled: true
      mode: VANILLA_1_17
    disable-overwrite-leather-armor-layers-textures: false
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-items: false
  extract-default-resources: false
blocks:
  light-api: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: true
  disable-REAL_TRANSPARENT: true
  disable-REAL_NOTE: true
  disable-REAL_WIRE: true
  disable-FIRE: true
  fix-liquids-flow: true
  fix-floating-blocks: true
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: true
liquids:
  enabled: false
huds:
  enabled: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: false
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
effects:
  hide-scoreboard-numbers: true
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
  fix-packet-too-large-kick: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
```

**Comment by SirCraftypants** [comment]
I requested your server timings on discord but you have ignored that request

Please provide you timings so that we can figure out the true cause of the lag. 

Also can you confirm how much RAM your server has, above it says `RAM 32 3200 Mhz`? RAM is in GB's

**Comment by ArtifactyNight** [comment]
> Also can you confirm how much RAM your server has, above it says `RAM 32 3200 Mhz`? RAM is in GB's
32 GB / Bus 3200 MHz (not ECC ram)
I'm using self host server

anyway, i'll send more information in discord

**Comment by SirCraftypants** [comment]
OK seeing as you've reinstalled Itemsadder now and the lag no longer exists, i highly suspect that when you have a large number of players on something is happening to cause the issue.

Are you a survival server and if yes, have you optimized how many mods spawn per player
Do you allow players to create mod farms
Do you allow your players full access to entities, i.e furniture which are armorstands/item frames.
Do you use Worldguard and if so have you set limits to how many entities your players can place in rented area's or per chunk.

The list is long but these questions will do for now.

**Comment by SirCraftypants** [comment]
OK so after sharing your latest timings on Discord, it shows you have no problems, so the issue is now the server crash.

Itemsadder should not cause problems when freshly installing.

Make sure you have all of Itemsadders Dependencies installed and updated.

It may also be another plugin causing a conflict, share you plugins list here.

**Comment by LoneDev6** [comment]
@ArtifactyNight Hello, please disable this setting in config.yml
`tab-header-footer`
You can find it two times, one for `effects`, one for `font_images`

Let me know

**Comment by ArtifactyNight** [comment]
> @ArtifactyNight Hello, please disable this setting in config.yml `tab-header-footer` You can find it two times, one for `effects`, one for `font_images`
> 
> Let me know

I'll try this

**Comment by ArtifactyNight** [comment]
still happen

for now
no tps drop when player is up to 50+
but it's instant server shutdown

**Comment by ArtifactyNight** [comment]
here's the timings after start a server when crashed
https://timings.aikar.co/?id=228d3c2f8f434d69b3eb513884dd16ac

the problem about lag is gone
but for now, server is instantly shutdown instead ;-;

**Comment by ArtifactyNight** [comment]
hm.. looks like i have issues with memory leak when i'm install itemsadder
for now it's can handle 70+ players with tps 20

but it's suddenly tps drop to 5-6 and my linux terminal is freeze

**Comment by LoneDev6** [comment]
I need timings reports and spark reports of when these issues occurred, i can't identify the issue without this info
