### ISSUE TITLE
Philosophers stone can't be recharged

### ISSUE THREAD

**Issue by BookWyrm114** [PluginBugs/Issues-ItemsAdder#1511]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

![image](https://user-images.githubusercontent.com/79489385/156058892-24e9e339-2ce0-4ec3-9172-557a5b83864f.png)

### Steps to reproduce the issue

try to recharge to philosopher's stone

### Server version

Current: git-Purpur-1565 (MC: 1.18.1)*

### ItemsAdder Version

2.5.5

### ProtocolLib Version

4.8.0-SNAPSHOT-b540

### LoneLibs Version

10.0.16b

### Problematic items yml configuration file (optional)

```shell
no changes were made to item configuration
```

**Comment by LoneDev6** [comment]
You have to click the dirt
