### ISSUE TITLE
Internal Exception: net.minecraft.server.v1_16_R3.PacketEncoder$PacketTooLargeException: PacketTooLarge - PacketPlayOutRecipeUpdate is 2145433. Max is 2097152

### ISSUE THREAD

**Issue by VOIDDERtm** [PluginBugs/Issues-ItemsAdder#1512]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

VOIDDER_#6923

### What happened?

doesn't let people in after reboot, well I don't believe that IA adds 2 million recipes...

### Steps to reproduce the issue

adding resipes:

> info:
  namespace: christmas
recipes:
  crafting_table:
    christmas_tree:
      permission: christmas.christmas_tree
      enabled: true
      pattern:
      - DBD
      - BBB
      - CAC
      ingredients:
        A: OAK_LOG
        B: OAK_LEAVES
        C: RED_WOOL
        D: YELLOW_WOOL
      result:
        item: christmas:christmas_tree
        amount: 1
    christmas_candle:
      permission: christmas.christmas_candle
      enabled: true
      pattern:
      - AEA
      - CDC
      - BBB
      ingredients:
        A: STICK
        B: OAK_LEAVES
        C: SAND
        D: CLAY
        E: REDSTONE
      result:
        item: christmas:christmas_candle
        amount: 1
    decorative_candy_cane:
      permission: christmas.decorative_candy_cane
      enabled: true
      pattern:
      - XAC
      - ACB
      - CBX
      ingredients:
        A: CLAY
        B: RED_WOOL
        C: WHITE_WOOL
      result:
        item: christmas:decorative_candy_cane
        amount: 1
    christmas_wreath:
      permission: christmas.christmas_wreath
      enabled: true
      pattern:
      - BBB
      - BXB
      - ACA
      ingredients:
        A: SWEET_BERRIES
        B: OAK_LEAVES
        C: RED_WOOL
      result:
        item: christmas:christmas_wreath
        amount: 1
items:
  christmas_tree:
    display_name: "Новогоднее дерево"
    permission: christmas
    resource:
      material: STONE
      generate: false
      model_path: christmas_tree
    behaviours:
      furniture:
        gravity: false
        fixed_rotation: false

        light_level: 15
  christmas_candle:
    display_name: "Рождественская свеча"
    permission: christmas
    resource:
      material: STONE
      generate: false
      model_path: christmas_candle
    behaviours:
      furniture:
        gravity: false
        fixed_rotation: false
        small: true
        light_level: 8
  decorative_candy_cane:
    display_name: "Декоративная конфетная трость"
    permission: christmas
    resource:
      material: STONE
      generate: false
      model_path: decorative_candy_cane
    behaviours:
      furniture:
        gravity: false
        fixed_rotation: false

  christmas_wreath:
    display_name: "Рождественский венок"
    permission: christmas
    resource:
      material: STONE
      generate: false
      model_path: christmas_wreath
    behaviours:
      furniture:
        gravity: false
        fixed_rotation: true
        small: true

### Server version

1.16.5

### ItemsAdder Version

2.5.5

### ProtocolLib Version

4.7.0

### LoneLibs Version

1.0.16b

### LibsDisguises Version (optional)

10.0.27

### Error (optional)

```shell
[13:16:25] [Server thread/INFO]: Ranko lost connection: Internal Exception: net.minecraft.server.v1_16_R3.PacketEncoder$PacketTooLargeException: PacketTooLarge - PacketPlayOutRecipeUpdate is 2145433. Max is 2097152
```

### ItemsAdder config.yml

```shell
metrics: false
update-checker: false
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: false
      server-ip: 127.0.0.1
      pack-port: 8163
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: false
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: false
  protect-player:
    black-screen: false
    hide-hud: false
    cancel-movement: false
    lock-player: false
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 15.0
    oversample: 2.0
  thin-font:
    enabled: true
  zip:
    protect-file-from-unzip:
      enabled: false
      extreme: false
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      _: 'Available values: VANILLA_1_17 or OPTIFINE'
      enabled: true
      mode: OPTIFIN
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
      CROSSBOW: 1
config_files:
  lang: ru
  dictionaries-lang: ru
  extract-default-items: false
  extract-default-resources: false
blocks:
  light-api: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
  fix-liquids-flow: true
  fix-floating-blocks: true
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: false
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/79021022/156163755-f14f5e12-e53f-43d7-8a81-0015d5882fa2.png)

**Comment by VOIDDERtm** [comment]
[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/8161350/latest.log)

**Comment by LoneDev6** [comment]
The size of the packet is not necessarily related to the amount of recipes, but it's related to the size of each item in the recipe: name, lore, enchants.
ItemsAdder has a builtin system to avoid this situation, it cleans lore of items in recipebook to avoid this.
Open config.yml of ItemsAdder and then check logs: `log-fix-packet-too-large: true` to see this feature logs in the console.

You might also have other plugins which are adding recipes with ingredients which have a very long lore.

**Comment by VOIDDERtm** [comment]
> The size of the packet is not necessarily related to the amount of recipes, but it's related to the size of each item in the recipe: name, lore, enchants. ItemsAdder has a builtin system to avoid this situation, it cleans lore of items in recipebook to avoid this. Open config.yml of ItemsAdder and then check logs: `log-fix-packet-too-large: true` to see this feature logs in the console.
> 
> You might also have other plugins which are adding recipes with ingredients which have a very long lore.
> 
> Another note: this is a Minecraft limitation I had bypassed with the method I cited before. I can't really do anything else since this game packets system is bad designed: https://bugs.mojang.com/browse/MC-185901

Thank! its's helped!
