### ISSUE TITLE
Custom Status Effects

### ISSUE THREAD

**Issue by BookWyrm114** [PluginBugs/Issues-ItemsAdder#1513]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

A way to make custom status effects by defining the name, an icon for the effect, and how the player is modified during the effect, as well as how the effects of the effect scale depending on level. The effect icons could be displayed using the actionbar

### Is your feature request related to a problem?

Nope

### Describe alternatives you've considered

There don’t seem to be any other plugins th that allow for custom effects besides magic, and that would probably conflict with IA

**Comment by BookWyrm114** [comment]
Ok, as an alternative could the scoreboard be used so it would always display on the far right of the screen? The textures would have to block out the numbers on the right side of the scoreboard, or perhaps it could be possible to get rid of those with a resource pack?

**Comment by LoneDev6** [comment]
This is a very customized request and can be achieved with an addon, ItemsAdder has an API which can allow your devs to add extremely customized HUDs into the game.
For example this: https://github.com/LoneDev6/RPGhuds/

But you can do the same thing in the scoreboard, just get the texture character and add it into the scoreboard.
https://github.com/LoneDev6/API-ItemsAdder/blob/master/src/main/java/dev/lone/itemsadder/api/FontImages/FontImageWrapper.java#L94
