### ISSUE TITLE
[Custom Entities] Option to play particles on repeat

### ISSUE THREAD

**Issue by Andre601** [PluginBugs/Issues-ItemsAdder#1515]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Andre_601#0601

### Describe the solution you'd like

It would be nice to have a way to define a particle once (One keyframe) and let it play on loop.
This is useful for custom mobs which should display particles all the time, such as f.e. a custom blaze mob emitting smoke particles.

### Is your feature request related to a problem?

Right now do you have to define multiple keyframes in blockbench to play the particle multiple times.

### Describe alternatives you've considered

See previous part

### Additional context

I made a robot model with a "engine" on its back that in all animations is moving.
![image](https://user-images.githubusercontent.com/11576465/156585919-f98d2cb3-a881-4768-bef4-4f88a76131ec.png)

I would like to have constant smoke particles coming from that location for extra effect.

**Comment by LoneDev6** [comment]
> Right now do you have to define multiple keyframes in blockbench to play the particle multiple times.

That's the easiest way to do that and I think it's the cleanest because you might want looping particles to stop on some animations and restart at some point.
I don't think it's worth implementing.
