### ISSUE TITLE
Broadcastevent Null?

### ISSUE THREAD

**Issue by MainTaylor** [PluginBugs/Issues-ItemsAdder#1521]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

Server thread/ERROR Could not pass event BroadcastMessageEvent to ItemsAdder v3.0.2
04.03 18:33:45 [Server] INFO org.bukkit.event.EventException: null
04.03 18:33:45 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
04.03 18:33:45 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
04.03 18:33:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
04.03 18:33:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
04.03 18:33:45 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.CraftServer.broadcast(CraftServer.java:1592) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
04.03 18:33:45 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.CraftServer.broadcastMessage(CraftServer.java:595) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
04.03 18:33:45 [Server] INFO at org.bukkit.Bukkit.broadcastMessage(Bukkit.java:362) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
04.03 18:33:45 [Server] INFO at com.olziedev.playerwarps.utils.l.b(PluginUtils.java:151) ~[?:?]
04.03 18:33:45 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
04.03 18:33:45 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
04.03 18:33:45 [Server] INFO at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1255) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
04.03 18:33:45 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:428) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
04.03 18:33:45 [Server] INFO at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1206) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
04.03 18:33:45 [Server] INFO at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1034) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
04.03 18:33:45 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
04.03 18:33:45 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?]
04.03 18:33:45 [Server] INFO Caused by: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component org.bukkit.event.server.BroadcastMessageEvent.message()'
04.03 18:33:45 [Server] INFO at dev.lone.itemsadder.main.gy.a(SourceFile:762) ~[?:?]
04.03 18:33:45 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
04.03 18:33:45 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
04.03 18:33:45 [Server] INFO at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
04.03 18:33:45 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
04.03 18:33:45 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
04.03 18:33:45 [Server] INFO ... 15 more

### Steps to reproduce the issue

Anytime a player is teleported by any plugin or method of teleporation.

### Server version

1.18.1 Spigot Latest 1.18.1 Jar

### ItemsAdder Version

3.0.2

### ProtocolLib Version

4.8.0

### LoneLibs Version

1.0.18

### FULL server log

Server thread/ERROR Could not pass event BroadcastMessageEvent to ItemsAdder v3.0.2
04.03 18:33:45 [Server] INFO org.bukkit.event.EventException: null
04.03 18:33:45 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
04.03 18:33:45 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
04.03 18:33:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
04.03 18:33:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
04.03 18:33:45 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.CraftServer.broadcast(CraftServer.java:1592) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
04.03 18:33:45 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.CraftServer.broadcastMessage(CraftServer.java:595) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
04.03 18:33:45 [Server] INFO at org.bukkit.Bukkit.broadcastMessage(Bukkit.java:362) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
04.03 18:33:45 [Server] INFO at com.olziedev.playerwarps.utils.l.b(PluginUtils.java:151) ~[?:?]
04.03 18:33:45 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
04.03 18:33:45 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
04.03 18:33:45 [Server] INFO at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1255) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
04.03 18:33:45 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:428) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
04.03 18:33:45 [Server] INFO at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1206) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
04.03 18:33:45 [Server] INFO at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1034) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
04.03 18:33:45 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
04.03 18:33:45 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?]
04.03 18:33:45 [Server] INFO Caused by: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component org.bukkit.event.server.BroadcastMessageEvent.message()'
04.03 18:33:45 [Server] INFO at dev.lone.itemsadder.main.gy.a(SourceFile:762) ~[?:?]
04.03 18:33:45 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
04.03 18:33:45 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
04.03 18:33:45 [Server] INFO at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
04.03 18:33:45 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
04.03 18:33:45 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
04.03 18:33:45 [Server] INFO ... 15 more

### Error (optional)

```shell
Server thread/ERROR Could not pass event BroadcastMessageEvent to ItemsAdder v3.0.2
04.03 18:33:45 [Server] INFO org.bukkit.event.EventException: null
04.03 18:33:45 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
04.03 18:33:45 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
04.03 18:33:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
04.03 18:33:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
04.03 18:33:45 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.CraftServer.broadcast(CraftServer.java:1592) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
04.03 18:33:45 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.CraftServer.broadcastMessage(CraftServer.java:595) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
04.03 18:33:45 [Server] INFO at org.bukkit.Bukkit.broadcastMessage(Bukkit.java:362) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
04.03 18:33:45 [Server] INFO at com.olziedev.playerwarps.utils.l.b(PluginUtils.java:151) ~[?:?]
04.03 18:33:45 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
04.03 18:33:45 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
04.03 18:33:45 [Server] INFO at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1255) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
04.03 18:33:45 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:428) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
04.03 18:33:45 [Server] INFO at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1206) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
04.03 18:33:45 [Server] INFO at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1034) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
04.03 18:33:45 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
04.03 18:33:45 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?]
04.03 18:33:45 [Server] INFO Caused by: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component org.bukkit.event.server.BroadcastMessageEvent.message()'
04.03 18:33:45 [Server] INFO at dev.lone.itemsadder.main.gy.a(SourceFile:762) ~[?:?]
04.03 18:33:45 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
04.03 18:33:45 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
04.03 18:33:45 [Server] INFO at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
04.03 18:33:45 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
04.03 18:33:45 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
04.03 18:33:45 [Server] INFO ... 15 more
```

**Comment by LoneDev6** [comment]
A plugin is interfering with ItemsAdder.
I will add a better checking in the next update to avoid this situation.

Thanks
