### ISSUE TITLE
IAEntity Plugin breaks BlockBench MAC

### ISSUE THREAD

**Issue by tigerboy3050** [PluginBugs/Issues-ItemsAdder#1523]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

tigerboy3050#7702

### What happened?

So. I tried to install the IAEntity (Blockbench) plugin, and as soon as I did, all the menus (except for the main menu and the close menu) stopped working (example in the attached video). I was able to uninstall the plugin (not through the menu because that didn't work) by deleting iaentity.js from my computer, which reverted Blockbench back to a usable state (all menus were functional and everything was just like before). So this time I opened up the Blockbench console (which I couldn't do before because the plugin broke all the keybinds and menus), then installed the plugin again, and when I clicked any menu buttons (for example, add cube) it gave this weird stack error or something (check attached video). Anyway, I'm on the latest version of Blockbench, the latest version of IAEntity, tried uninstalling and reinstalling everything, and nothing seems to work. It is important to note, however, that I am on an Intel Mac, running MacOS Monterey, so that could be the problem. Maybe?? Anyway, some help (or a fix) would be greatly appreciated. 

And here's the video:

https://user-images.githubusercontent.com/63379262/156903006-3bc85920-457a-4d6d-a5be-39fc6005c071.mp4

### Steps to reproduce the issue

Install IAEntity plugin to the latest version of Blockbench on a Mac running MacOS Monterey I guess...

### Server version

NA

Running latest version of Blockbench

### ItemsAdder Version

NA

IAEntity version 1.0.1 (Latest)

### ProtocolLib Version

NA

### LoneLibs Version

NA

### LightAPI Version (optional)

NA

### LibsDisguises Version (optional)

NA

### FULL server log

NA

Blockbench console in video

### Error (optional)

```shell
NA

Blockbench Console in Video
```

### ItemsAdder config.yml

```shell
NA
```

### Problematic items yml configuration file (optional)

```shell
NA
```

### Other files, you can drag and drop them here to upload. (optional)

https://user-images.githubusercontent.com/63379262/156903006-3bc85920-457a-4d6d-a5be-39fc6005c071.mp4

**Comment by LoneDev6** [comment]
https://apple.stackexchange.com/questions/28928/what-is-the-macos-equivalent-to-windows-appdata-folder
I don't have a mac so i can't help you directly, but you have to access the blockbench settings folder and delete the plugin from plugins folder.
Then install the new js i sent you here and check if it works.

[iaentitymodel.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/8195713/iaentitymodel.zip)

**Comment by tigerboy3050** [comment]
I was able to uninstall the plugin, but upon installing the the new version of the plugin (and opening the console before installation) I was greeted with some errors. (and the same problems as before, except theres more stuff in the console now.) 

So here's the console log I suppose:

Electron 16.0.4, Node 16.9.1
boot_loader.js:44 Three.js r129
boot_loader.js:45 Blockbench 4.1.5 Desktop (macOS)
plugin_loader.js:502 Loaded 5 plugins Array(5)0: "Store: animated_java"1: "Store: optimize"2: "Store: shape_generator"3: "Store: player_statue_generator"4: "Store: texture_stitcher"length: 5[[Prototype]]: Array(0)
VM301:216 hello from Animated Java!
VM301:217 lifecycle event redirects

> When I installed the ItemsAdder Entity Model Plugin

VM301:217 failed to load global data
(anonymous) @ VM301:217
VM301:217 e is not iterable
(anonymous) @ VM301:217
DevTools failed to load source map: Could not parse content for file:///peerjs.min.js.map: Unexpected end of JSON input
VM310:989 lifecycle event redirects
VM310:1708 failed to load global data
Settings$1 @ VM310:1708
(anonymous) @ VM310:1909
(anonymous) @ VM310:14905
b @ jquery.js:2
globalEval @ jquery.js:2
text script @ jquery.js:2
(anonymous) @ jquery.js:2
l @ jquery.js:2
(anonymous) @ jquery.js:2
load (async)
send @ jquery.js:2
ajax @ jquery.js:2
S.<computed> @ jquery.js:2
getScript @ jquery.js:2
(anonymous) @ plugin_loader.js:170
loadFromFile @ plugin_loader.js:167
(anonymous) @ io.js:31
(anonymous) @ io.js:30
(anonymous) @ file_system.js:398
(anonymous) @ file_system.js:180
read @ file_system.js:183
(anonymous) @ file_system.js:397
forDragHandlers @ file_system.js:457
document.body.ondrop @ file_system.js:381
VM310:1709 global_data is not iterable
Settings$1 @ VM310:1709
(anonymous) @ VM310:1909
(anonymous) @ VM310:14905
b @ jquery.js:2
globalEval @ jquery.js:2
text script @ jquery.js:2
(anonymous) @ jquery.js:2
l @ jquery.js:2
(anonymous) @ jquery.js:2
load (async)
send @ jquery.js:2
ajax @ jquery.js:2
S.<computed> @ jquery.js:2
getScript @ jquery.js:2
(anonymous) @ plugin_loader.js:170
loadFromFile @ plugin_loader.js:167
(anonymous) @ io.js:31
(anonymous) @ io.js:30
(anonymous) @ file_system.js:398
(anonymous) @ file_system.js:180
read @ file_system.js:183
(anonymous) @ file_system.js:397
forDragHandlers @ file_system.js:457
document.body.ondrop @ file_system.js:381
VM310:10163 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtoolsYou might need to use a local HTTP server (instead of file://): https://reactjs.org/link/react-devtools-faq
VM310:1372 Successfully Collected Item List: (1101) ['minecraft:acacia_boat', 'minecraft:acacia_button', 'minecraft:acacia_door', 'minecraft:acacia_fence', 'minecraft:acacia_fence_gate', 'minecraft:acacia_leaves', 'minecraft:acacia_log', 'minecraft:acacia_planks', 'minecraft:acacia_pressure_plate', 'minecraft:acacia_sapling', 'minecraft:acacia_sign', 'minecraft:acacia_slab', 'minecraft:acacia_stairs', 'minecraft:acacia_trapdoor', 'minecraft:acacia_wood', 'minecraft:activator_rail', 'minecraft:air', 'minecraft:allium', 'minecraft:amethyst_block', 'minecraft:amethyst_cluster', 'minecraft:amethyst_shard', 'minecraft:ancient_debris', 'minecraft:andesite', 'minecraft:andesite_slab', 'minecraft:andesite_stairs', 'minecraft:andesite_wall', 'minecraft:anvil', 'minecraft:apple', 'minecraft:armor_stand', 'minecraft:arrow', 'minecraft:axolotl_bucket', 'minecraft:axolotl_spawn_egg', 'minecraft:azalea', 'minecraft:azalea_leaves', 'minecraft:azure_bluet', 'minecraft:baked_potato', 'minecraft:bamboo', 'minecraft:barrel', 'minecraft:barrier', 'minecraft:basalt', 'minecraft:bat_spawn_egg', 'minecraft:beacon', 'minecraft:bedrock', 'minecraft:bee_nest', 'minecraft:bee_spawn_egg', 'minecraft:beef', 'minecraft:beehive', 'minecraft:beetroot', 'minecraft:beetroot_seeds', 'minecraft:beetroot_soup', 'minecraft:bell', 'minecraft:big_dripleaf', 'minecraft:birch_boat', 'minecraft:birch_button', 'minecraft:birch_door', 'minecraft:birch_fence', 'minecraft:birch_fence_gate', 'minecraft:birch_leaves', 'minecraft:birch_log', 'minecraft:birch_planks', 'minecraft:birch_pressure_plate', 'minecraft:birch_sapling', 'minecraft:birch_sign', 'minecraft:birch_slab', 'minecraft:birch_stairs', 'minecraft:birch_trapdoor', 'minecraft:birch_wood', 'minecraft:black_banner', 'minecraft:black_bed', 'minecraft:black_candle', 'minecraft:black_carpet', 'minecraft:black_concrete', 'minecraft:black_concrete_powder', 'minecraft:black_dye', 'minecraft:black_glazed_terracotta', 'minecraft:black_shulker_box', 'minecraft:black_stained_glass', 'minecraft:black_stained_glass_pane', 'minecraft:black_terracotta', 'minecraft:black_wool', 'minecraft:blackstone', 'minecraft:blackstone_slab', 'minecraft:blackstone_stairs', 'minecraft:blackstone_wall', 'minecraft:blast_furnace', 'minecraft:blaze_powder', 'minecraft:blaze_rod', 'minecraft:blaze_spawn_egg', 'minecraft:blue_banner', 'minecraft:blue_bed', 'minecraft:blue_candle', 'minecraft:blue_carpet', 'minecraft:blue_concrete', 'minecraft:blue_concrete_powder', 'minecraft:blue_dye', 'minecraft:blue_glazed_terracotta', 'minecraft:blue_ice', 'minecraft:blue_orchid', 'minecraft:blue_shulker_box', 'minecraft:blue_stained_glass', …]
VM310:9935 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'forEach')
    at startWorkOnPendingInteractions (<anonymous>:9935:55)
    at renderRootSync (<anonymous>:9693:100)
    at performSyncWorkOnRoot (<anonymous>:9623:122)
    at <anonymous>:7947:188
    at unstable_runWithPriority (<anonymous>:5330:18)
    at runWithPriority$1 (<anonymous>:7941:1059)
    at flushSyncCallbackQueueImpl (<anonymous>:7947:78)
    at flushSyncCallbackQueue (<anonymous>:7946:339)
    at scheduleUpdateOnFiber (<anonymous>:9509:20)
    at updateContainer (<anonymous>:10103:313)
startWorkOnPendingInteractions @ VM310:9935
renderRootSync @ VM310:9693
performSyncWorkOnRoot @ VM310:9623
(anonymous) @ VM310:7947
unstable_runWithPriority @ VM310:5330
runWithPriority$1 @ VM310:7941
flushSyncCallbackQueueImpl @ VM310:7947
flushSyncCallbackQueue @ VM310:7946
scheduleUpdateOnFiber @ VM310:9509
updateContainer @ VM310:10103
legacyRenderSubtreeIntoContainer @ VM310:10147
render @ VM310:10148
(anonymous) @ VM310:11045
Promise.then (async)
(anonymous) @ VM310:11043
(anonymous) @ VM310:14905
b @ jquery.js:2
globalEval @ jquery.js:2
text script @ jquery.js:2
(anonymous) @ jquery.js:2
l @ jquery.js:2
(anonymous) @ jquery.js:2
load (async)
send @ jquery.js:2
ajax @ jquery.js:2
S.<computed> @ jquery.js:2
getScript @ jquery.js:2
(anonymous) @ plugin_loader.js:170
loadFromFile @ plugin_loader.js:167
(anonymous) @ io.js:31
(anonymous) @ io.js:30
(anonymous) @ file_system.js:398
(anonymous) @ file_system.js:180
read @ file_system.js:183
(anonymous) @ file_system.js:397
forDragHandlers @ file_system.js:457
document.body.ondrop @ file_system.js:381
VM310:14783 Successfully Collected Entity List: (113) ['minecraft:area_effect_cloud', 'minecraft:armor_stand', 'minecraft:arrow', 'minecraft:axolotl', 'minecraft:bat', 'minecraft:bee', 'minecraft:blaze', 'minecraft:boat', 'minecraft:cat', 'minecraft:cave_spider', 'minecraft:chest_minecart', 'minecraft:chicken', 'minecraft:cod', 'minecraft:command_block_minecart', 'minecraft:cow', 'minecraft:creeper', 'minecraft:dolphin', 'minecraft:donkey', 'minecraft:dragon_fireball', 'minecraft:drowned', 'minecraft:egg', 'minecraft:elder_guardian', 'minecraft:end_crystal', 'minecraft:ender_dragon', 'minecraft:ender_pearl', 'minecraft:enderman', 'minecraft:endermite', 'minecraft:evoker', 'minecraft:evoker_fangs', 'minecraft:experience_bottle', 'minecraft:experience_orb', 'minecraft:eye_of_ender', 'minecraft:falling_block', 'minecraft:fireball', 'minecraft:firework_rocket', 'minecraft:fishing_bobber', 'minecraft:fox', 'minecraft:furnace_minecart', 'minecraft:ghast', 'minecraft:giant', 'minecraft:glow_item_frame', 'minecraft:glow_squid', 'minecraft:goat', 'minecraft:guardian', 'minecraft:hoglin', 'minecraft:hopper_minecart', 'minecraft:horse', 'minecraft:husk', 'minecraft:illusioner', 'minecraft:iron_golem', 'minecraft:item', 'minecraft:item_frame', 'minecraft:leash_knot', 'minecraft:lightning_bolt', 'minecraft:llama', 'minecraft:llama_spit', 'minecraft:magma_cube', 'minecraft:marker', 'minecraft:minecart', 'minecraft:mooshroom', 'minecraft:mule', 'minecraft:ocelot', 'minecraft:painting', 'minecraft:panda', 'minecraft:parrot', 'minecraft:phantom', 'minecraft:pig', 'minecraft:piglin', 'minecraft:piglin_brute', 'minecraft:pillager', 'minecraft:player', 'minecraft:polar_bear', 'minecraft:potion', 'minecraft:pufferfish', 'minecraft:rabbit', 'minecraft:ravager', 'minecraft:salmon', 'minecraft:sheep', 'minecraft:shulker', 'minecraft:shulker_bullet', 'minecraft:silverfish', 'minecraft:skeleton', 'minecraft:skeleton_horse', 'minecraft:slime', 'minecraft:small_fireball', 'minecraft:snow_golem', 'minecraft:snowball', 'minecraft:spawner_minecart', 'minecraft:spectral_arrow', 'minecraft:spider', 'minecraft:squid', 'minecraft:stray', 'minecraft:strider', 'minecraft:tnt', 'minecraft:tnt_minecart', 'minecraft:trader_llama', 'minecraft:trident', 'minecraft:tropical_fish', 'minecraft:turtle', 'minecraft:vex', …]


Anyway, thanks for helping, hopefully we can find a solution for this, and if not, thanks for trying.
Tigerboy3050

**Comment by LoneDev6** [comment]
This seems to be an old console log, I think.
Which plugins do you have installed?

**Comment by LoneDev6** [comment]
Continue on Discord
