### ISSUE TITLE
Whenever itemsadder is reloaded, mythicmobs is also reloaded

### ISSUE THREAD

**Issue by BookWyrm114** [PluginBugs/Issues-ItemsAdder#1527]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

When /iareload is executed the mythicmobs plugin also reloads

### Steps to reproduce the issue

Use both IA and MM together and execute /iareload

### Server version

git-purpur-1565

### ItemsAdder Version

3.0.2

### ProtocolLib Version

4.8.0-SNAPSHOT-b540

### LoneLibs Version

1.0.18

**Comment by LoneDev6** [comment]
It's normal, or Mythicmobs mobs won't be registered correctly.
