### ISSUE TITLE
The damage entity actions will just instantly kill stuff sometimes

### ISSUE THREAD

**Issue by BookWyrm114** [PluginBugs/Issues-ItemsAdder#1529]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

When using the damage entity action, or the one that damages entities in a radius, it will work fine sometimes, but for some reason it will occasionally just instantly kill entities. to test this out I spawned a mob with 2k health and it instantly killed the mob though the damage value was set to 3. this also happened with the wither and ender dragon. though for some reason it will occasionally do the correct amount of damage.

### Steps to reproduce the issue

just play around with that action

### Server version

git-purpur-1565

### ItemsAdder Version

3.0.2

### ProtocolLib Version

4.8.0-SNAPSHOT-b540

### LoneLibs Version

1.0.18

**Comment by BookWyrm114** [comment]
here it is:


 powered_void_staff:
    display_name: Powered Void Staff
    lore:
    - '&5A Void Staff infused with stabilized void matter'
    permission: powered_void_staff
    resource:
      material: ENCHANTED_BOOK
      generate: false
      model_path: "item/powered_void_staff.json"
    events:
      interact:
        right:
          damage_near_entities:
            entity_groups:
             - HOSTILE
             - PLAYERS
             - PASSIVE
            damage: 3
            range: 5
          play_particle:
            name: "SOUL_FIRE_FLAME"

**Comment by LoneDev6** [comment]
I can't manage to reproduce the issue, maybe there is another plugin interfering
https://streamable.com/e7mwyx
