### ISSUE TITLE
An item frame option for furniture, or a way to make some furnitures only face cardinal directions

### ISSUE THREAD

**Issue by BookWyrm114** [PluginBugs/Issues-ItemsAdder#1530]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

An option to use item frames to display furniture, or a way to make some furnitures only face cardinal directions.

### Is your feature request related to a problem?

Yep, I made a custom model for some machines and so I used the furniture mechanic to display them, but they are always rotated however I place them, it would be nice to have them only face cardinal directions.

### Describe alternatives you've considered

I haven't found any alternatives in the wiki

**Comment by LoneDev6** [comment]
Why do you need to use item_frame entity?
Anyway, you can use armor_stand which already has this feature, but it should also work with item_frame furniture.

```yml
    behaviours:
      furniture:
        fixed_rotation: true
```

**Comment by BookWyrm114** [comment]
Oh thanks! Sorry I didn’t see that in the wiki
