### ISSUE TITLE
For some reason vanilla blocks cannot be placed on custom IA blocks or furniture

### ISSUE THREAD

**Issue by BookWyrm114** [PluginBugs/Issues-ItemsAdder#1531]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

For some reason vanilla blocks cannot be placed on custom IA blocks or furniture, if I right-click an IA block/furniture block with a vanilla block it will not place, however it works with other IA blocks

### Steps to reproduce the issue

try placing vanilla block on an IA block

### Server version

git-purpur-1565

### ItemsAdder Version

3.0.2

### ProtocolLib Version

4.8.0-SNAPSHOT-b540

### LoneLibs Version

1.0.18

### Other files, you can drag and drop them here to upload. (optional)

Sorry for the bug report/feature request spam. I decided to make and add a ton of items and stuff to my server and ended up finding alot of bugs and some useful features that could be implemented.

**Comment by LoneDev6** [comment]
I cannot reproduce the issue

https://user-images.githubusercontent.com/27242001/158150814-e398b7fa-c94e-4563-a13b-6fe0b13993e5.mp4
