### ISSUE TITLE
Event and Action [Feature Req]

### ISSUE THREAD

**Issue by Apiz05** [PluginBugs/Issues-ItemsAdder#1533]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Aech_#1655

### Describe the solution you'd like

I want a improvement for the event and the action 
- add more placeholder like 
   - {world} etc
- add a requirement like
  - permission 
  - region
  `                                                                                                                    `
  change_me_xxx:
    enabled: true
    display_name: test
    resource:
      generate: true
      material: PAPER
      textures:
        - item/test.png
    events:
      interact:
        right:
          execute_commands:
            change_me_1:
              command: 'tp {player} {world}'
              as_console: true
              delay: 0
              requirment: 'test.requirment','region:spawn'
  `                                                                                                                    `

### Is your feature request related to a problem?

Yes i currently can't use the {world} cause it so usefull

### Describe alternatives you've considered

more placeholder

> {world} = World
{position1} = x,y,z
{position2} = x y z
 
A requirement 
> 'region:spawn' only can execute in spawn 
'!region:spawn' only can execute outside spawn 
'perms:test.requirment' only can execute if have permission  
'!perms:test.requirment' only can execute if doesn't permission 

### Additional context

It can really help us to make our server better 
PLS HERE ME

**Comment by Apiz05** [comment]
Bump

**Comment by Apiz05** [comment]
bump

**Comment by Apiz05** [comment]
bump

**Comment by oOHiyoriOo** [comment]
bump

**Comment by LoneDev6** [comment]
This is an extremely detailed feature request, won't this be easier to be coded in skript or by using the ItemsAdder Java api?

**Comment by Apiz05** [comment]
ouh ok 
but you can add it right?
