### ISSUE TITLE
Dupe Bug

### ISSUE THREAD

**Issue by BowieatRivals** [PluginBugs/Issues-ItemsAdder#1535]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Bowe#2540

### What happened?

If you use crafting guide and an itemsadder item you can dupe.

### Steps to reproduce the issue

1. you have bone block in your inventory
2.  in the crafting table guide click on the bone shield
3. in the crafting table you put for example a rare key to one of the bone block placings
4. Item duped

But it works with other itemss as well.

### Server version

This server is running Purpur version git-Purpur-1428 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9beb23b on ver/1.17.1)
You are running the latest version
Previous version: git-Purpur-"08dd6c7" (MC: 1.17.1)

### ItemsAdder Version

2.4.23

### ProtocolLib Version

4.7.0

### LoneLibs Version

1.0.15

### LightAPI Version (optional)

5.0.0

**Comment by BowieatRivals** [comment]
I just updated ItemsAdder and this bug still persists.

**Comment by BowieatRivals** [comment]
Here's a video: https://medal.tv/games/minecraft/clips/dMNxctIXyvcxQ/d1337yNiAfRn?invite=cr-MSxEbVMsNDg1MzEwNDAs

**Comment by LoneDev6** [comment]
Will be fixed in the next update, thanks
