### ISSUE TITLE
Custom tree saplings planted underground spawn on the surface

### ISSUE THREAD

**Issue by ProfessionalBoatDrifter** [PluginBugs/Issues-ItemsAdder#1537]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Akrill#0001

### What happened?

Planting a custom sapling in an underground space spawns it on the surface.

### Steps to reproduce the issue

0. (Optional) Install EssentialsX for `/top`
1. Obtain a custom tree sapling.
2. Dig down and clear a decent area underground.
3. Plant the sapling on suitable blocks.
4. See that there is no tree. Break blocks straight up (or use `/top`) and see the custom tree on the surface.

### Server version

git-Paper-409 (MC: 1.17.1)

### ItemsAdder Version

ItemsAdder version 3.0.2

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.18

**Comment by LoneDev6** [comment]
Will be fixed in the next update, thanks
