### ISSUE TITLE
[Compatibility] I can't use the itemsadder texturepack along with another (mmoitnventory) texturepack on the server

### ISSUE THREAD

**Issue by maximsGitHub** [PluginBugs/Issues-ItemsAdder#154]
I can't use both resourcepacks on my server which are necessary for both of the plugins to currently work, of course itemsadder being one of them, the other is mmoinventory.
itemsadder asks to provide a dropbox link for the config.yml file to setup which makes itemsadder work as it should by itself but when in the config file of mmoinventory it also asks for a dropbox link of the mmoinventory resourcepack. If i set up both configs with the resourcepack seperately however the links wont work, I also tried merging the resourcepacks which will also get me the message "error occurred when enabling the resourcepack. " by the itemsadder plugin and again stops both resourcepacks from working. I really don't want to choose between 2 plugins that are necessary for the server.

**Expected behavior**
expected 2 plugins/resourcepacks not to interfere with each other

 - Server version: spigot 1.15.2)
 - Plugin version: 2.0.9

**Comment by Andrew99CZ** [comment]
I have problems with it too, I must remove mmoinventory.

**Comment by Andrew99CZ** [comment]
Good it works for me you have to move the folders from the moorpg plugin resoucepack-) 
v5-vanilla.zip to pack.zip from items adder and in config.yml in the rpginventory folder disable resourcepack.

**Comment by maximsGitHub** [comment]
I'm glad someone else has almost the same problem as I do however rpginventory is discontinued or outddated for mmoitems to work according to the devs. They have a plugin specifically for mmoitems called mmoinventory which comes with its own files and texturepack so its not the same one as rpginventory

**Comment by maximsGitHub** [comment]
> 
> 
> Good it works for me you have to move the folders from the rpginventory plugin resoucepack-)
> v5-vanilla.zip to pack.zip (move only assets) from items adder and in config.yml in the rpginventory folder disable resourcepack.
> In the FTP you must go to /plugins/ItemsAdder/data/resource_pack , and unzip assets from
> v5-vanilla.zip .
> ![Výstřižek2](https://user-images.githubusercontent.com/63855329/79643231-4c1ee680-81a2-11ea-8807-a0a46090d55b.PNG)

I'm glad someone else has almost the same problem as I do however rpginventory is discontinued or outddated for mmoitems to work according to the devs. They have a plugin specifically for mmoitems called mmoinventory which comes with its own files and texturepack so its not the same one as rpginventory

**Comment by Andrew99CZ** [comment]
If you download latest version RPGInventory-2.3.2-20200412-2-all.jar from here:https://cloud.endlesscode.ru/s/oPXy4XCbzQQjZMk
It is have mmoitems support.

![Výstřižek5](https://user-images.githubusercontent.com/63855329/79677325-51a31d80-81f0-11ea-84f2-dd0aa71f2fee.PNG)

Picture where I use ItemsAdder new texture, mmoitems and RPGInventory and that dmg working :) .

**Comment by LoneDev6** [comment]
Related to: https://github.com/LoneDev6/ItemsAdder/issues/150

I have to work on an addon or idk to be able to merge other plugins packs, but that would be a messy job.
For now please refer to this that I've already stated before: https://itemsadder.plugin.ga/compatibility-with-other-plugins/not-compatible
But the problem is that you won't be able to use selfhost, only dropbox host and you'll have to merge it everytime you generate a new pack.zip with ItemsAdder.

**Comment by LoneDev6** [comment]
Will be implemented with this new feature: https://github.com/PluginBugs/Issues-ItemsAdder/issues/1866
