### ISSUE TITLE
Suggestion to improve the experience with itemsadder

### ISSUE THREAD

**Issue by EiderFC** [PluginBugs/Issues-ItemsAdder#1541]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

ZDaPlaY#6666

### Describe the solution you'd like

Add what file have the error when you do /iazip, you only have "Unterminated array at line 486 column 6 path $.overrides"

When you do /iazip and there is an error, after you found the error and correct it, you can't do /iazip, there is an message "Already reloading... Please wait before using /iazip" and you need to restart the server, fix that please

![image](https://user-images.githubusercontent.com/88196950/157932212-130a33ec-5179-41e5-b021-df6ee47e6799.png)

### Is your feature request related to a problem?

Yes

### Describe alternatives you've considered

Add what file have the error when you do /iazip, you only have "Unterminated array at line 486 column 6 path $.overrides"

When you do /iazip and there is an error, after you found the error and correct it, you can't do /iazip, there is an message "Already reloading... Please wait before using /iazip" and you need to restart the server, fix that please

![image](https://user-images.githubusercontent.com/88196950/157932212-130a33ec-5179-41e5-b021-df6ee47e6799.png)

**Comment by LoneDev6** [comment]
Please send the full log of when the issue happened.
Thanks
