### ISSUE TITLE
Itemsadder not loading properly

### ISSUE THREAD

**Issue by BookWyrm114** [PluginBugs/Issues-ItemsAdder#1544]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

Itemsadder failed to load in 1.18.2 despite being on the latest version

### Steps to reproduce the issue

Try loading IA on the latest version

### Server version

git-Purpur-1585 (MC: 1.18.2)*

### ItemsAdder Version

3.0.2

### ProtocolLib Version

4.8.0-SNAPSHOT-b540

### LoneLibs Version

1.0.18

### LightAPI Version (optional)

Bukkit-5.1.0 (build SNAPSHOT)

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/8238067/latest.log)

**Comment by LoneDev6** [comment]
There are a lot of errors of also other plugins which report Mythicmobs problems.
Update Mythicmobs.
