### ISSUE TITLE
MythicMobs are currently unable to drop ItemsAdder Items

### ISSUE THREAD

**Issue by ItzASecret** [PluginBugs/Issues-ItemsAdder#1546]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

ItzASecretBoi0#1300

### Describe the solution you'd like

Further compatibility with MythicMobs that allows Itemsadder items to drop from MythicMobs

### Is your feature request related to a problem?

No.

### Describe alternatives you've considered

I considered getting MMOitems and then making a Itemsadder compatible MMOitem that has a custom texture. Then afterwards making the MMOItem drop with MythicMobs. I thought of this because both Itemsadder and MythicMobs have MMOItems compatibillity. However I havent tried this and I'm not familliar with MMOItems yet.

### Additional context

None

**Comment by LoneDev6** [comment]
Sorry I don't understand when you need ItemsAdder to be able to drop Mythicmobs/MMOitems items.

**Comment by ItzASecret** [comment]
I need the exact opposite, I want a mythic mob to drop a itemsadder item. Example: kill a mythic mob they drop a ruby pickaxe, or any other itemsadder item like a special hat.

**Comment by LoneDev6** [comment]
I think this can only be implemented by Mythicmobs using my API, can you send this github issue link to the Mythicmobs developers?
Maybe we can achieve something together

**Comment by ItzASecret** [comment]
Sure, I'll do it when I get home lol.

**Comment by ItzASecret** [comment]
![Screenshot_20220315-091537_Discord.jpg](https://user-images.githubusercontent.com/82130468/158397510-c6623909-1226-49f0-b6a3-3e99cd169500.jpg) 

They suggested that you use this instead if you were interested in adding compatibility.

**Comment by LoneDev6** [comment]
Amazing, thanks for the info

**Comment by LoneDev6** [comment]
This will be available in the next update
https://itemsadder.devs.beer/compatibility-with-other-plugins/compatible/mythicmobs

**Comment by Dant35tra5t** [comment]
Was this broken? I can't seem to get myitems: itemsadder drop type working.
`    - myitem:aqualight_sword 1 100%`

ia 3.4.0c
mm 5.3.0
git-purpur-1933

I appreciate any help with this <3

**Comment by LoneDev6** [comment]
This Github issue is from 1 year ago, do not comment on ancient issues.
@Dant35tra5t 

Next time provide a proper Github issue with the required information.
Probably Mythicmobs changed something in their code and the api cannot be hooked correctly.
