### ISSUE TITLE
Recipes aren't working with custom NBT items 

### ISSUE THREAD

**Issue by purejosh** [PluginBugs/Issues-ItemsAdder#1548]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

purejosh#2047

### What happened?

If you have a custom item (frost essense) that's based on another item (glistening_melon_slice), the recipe for the item will not show up in your crafting table recipe book unless you have the BASE item in your inventory. I've attached a video displaying the issue. 

### Steps to reproduce the issue

1. Make a recipe using a custom NBT item based on something else (stick, iron ingot, etc)
2. Observe the recipe missing from your crafting table when you have only the items needed to make the crafted item.
3. Add the root item from one of your custom items in the recipe, and observe that the recipe shows up in the crafting grid now. 

### Server version

This server is running Paper version git-Paper-175 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 9490475)
You are 41 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-76 (MC: 1.18.1)

### ItemsAdder Version

2.5.5

### ProtocolLib Version

4.8.0-SNAPSHOT-b538

### LoneLibs Version

1.0.16b

### FULL server log

Not relevant. 

### Screenshots/Videos (you can drag and drop files or paste links)

https://user-images.githubusercontent.com/70633949/158101303-e33b6282-d0ff-4b60-a5d6-1f9c6d6adac7.mp4

**Comment by LoneDev6** [comment]
Sadly this is a Minecraft limitation I cannot fix, only Mojang can.
https://itemsadder.devs.beer/faq/recipes-book-problems?q=recipe
