### ISSUE TITLE
Possible API improvement ideas

### ISSUE THREAD

**Issue by Andre601** [PluginBugs/Issues-ItemsAdder#1549]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Andre_601#0601

### Describe the solution you'd like

The current IA API is a bit weird in certain ways and I have some suggestions on changing that where possible.

### Change classes to interfaces

From what I can see are most if not all classes in the API repo only for basic methods, to return or do something.
The only purpose they have to be a class is so that a `throw new NotActuallyItemsAdderException()` can be set for when this is used without ItemsAdder.

This is IMO a bit useless.

Personally would I say should the classes, wherever possible, be changed to interfaces, for a cleaner look.

### Generic interfaces for common stuff

Several of the classes in the API use the exact same methods.
I believe it could be beneficial to add a more generic interface that contains those methods, so that it can be slightly easier for developers to get an object and later on cast it to an entity or similar (Or have a way for them to implement their own classes for IA, such as custom entities with more advanced/extra stuff).

For example could the `getNamespacedID`, `getNamespace` and `getID` methods be moved to a interface called `CustomNamespacedObject` like so:

```java
public interface CustomNamespacedObject
{
    default String getNamespacedID()
    {
        return getNamespace() + ":" + getID();
    }
    
    String getNamespace();
    
    String getID();
}
```

You would then have the classes implement this interface to have the `getNamespace` and `getID` methods applied.
ItemsAdder would then have an internal class (i.e. `ICustomEntity`) that extends (or implements if previous suggestion is applied) the class and has setters for the namespace and id to use. ItemsAdder could then create the ICustomEntity instance and return it to the plugin as `CustomEntity` thanks to its inheritance.

I hope you get my understanding here...

### Is your feature request related to a problem?

Not really. The API just seems a bit... weird in design.

### Describe alternatives you've considered

Just use the API as it is now.

**Comment by LoneDev6** [comment]
Not a bad idea, this is another design technique, it has its advantages.
I'll think about that.

Having instances generators in the same class would also surely make finding ItemsAdder features easier.

**Comment by LoneDev6** [comment]
Not possible to implement based on how the API is structured and how the internals wrapping system needs to work.
