### ISSUE TITLE
[BUG FURNITURE] Clicking on vanilla interactive blocks

### ISSUE THREAD

**Issue by paulreob** [PluginBugs/Issues-ItemsAdder#1553]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

! Pau#9216

### What happened?

The bug is that when clicking on a chest, crafting table, enderchest, etc., the furniture of the hand is placed and prevents to open the chest.

There would be a way to cancel the event of placing the furniture if you right click on a chest, crafting table, etc.
Ahh but if I can fix this, it should still work on the customblocks, since I have customblocks that run an X command when right clicked.

### Steps to reproduce the issue

1. A furniture in hand
2. try to interact with a chest
3. see how the furniture is placed, but the chest does not open. 

PS: Watch the video https://imgur.com/a/6r3Ut9U

### Server version

git-Purpur-1562 (MC: 1.18.1)*

### ItemsAdder Version

ItemsAdder version 3.0.2

### ProtocolLib Version

ProtocolLib version 4.8.0-SNAPSHOT-b539

### LoneLibs Version

LoneLibs version 1.0.18

### Screenshots/Videos (you can drag and drop files or paste links)

https://imgur.com/a/6r3Ut9U

**Comment by LoneDev6** [comment]
Will be fixed in the next update
