### ISSUE TITLE
Items in GUIs don't show up, the item is still there and it registers being clicked, but they are completely invisible

### ISSUE THREAD

**Issue by BookWyrm114** [PluginBugs/Issues-ItemsAdder#1554]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

Items in GUIs no longer show up, including machine GUIs, GUIs from the Nova plugin, and even the slimefun GUI.

This issue only occured after updating IA to 3.0.3-beta4

### Steps to reproduce the issue

use the latest release of IA and run /ia or open a custom GUI

### Server version

git-purpur-1585

### ItemsAdder Version

3.0.3-beta4

### ProtocolLib Version

5.0.0-SNAPSHOT-b551

### LoneLibs Version

1.0.18

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/79489385/158406112-3da3ba2d-4c59-4181-81fe-c048e4f956f5.png)
![image](https://user-images.githubusercontent.com/79489385/158406178-15a3d438-7181-45de-af25-5f36b0995418.png)
![image](https://user-images.githubusercontent.com/79489385/158406231-190e6927-846c-4699-8bc1-7ba789d93f47.png)

**Comment by LoneDev6** [comment]
It's hard to help you without knowing what exactly you did edit.
A normal configuration won't cause this.

**Comment by LoneDev6** [comment]
Your pack works fine on my game, you may have another resourcepack, a mod or something else interfering.
![immagine](https://user-images.githubusercontent.com/27242001/158546975-0ee040ef-808c-42da-b8b9-cacb7cb88bf3.png)
![immagine](https://user-images.githubusercontent.com/27242001/158546997-ad69aff5-75ee-47a1-bd5a-43f045bbdc62.png)

`itemsadder:auto_generated/ruby_block`
![immagine](https://user-images.githubusercontent.com/27242001/158547056-2ead0135-06b8-416c-ad09-a4adc1246bfe.png)

`vanillamcuis:item/loom/loom_pattern_brickwall`
![immagine](https://user-images.githubusercontent.com/27242001/158547233-0459a3b1-85be-4ae4-bc3c-5111d4ffa636.png)

**Comment by BookWyrm114** [comment]
Normal vanilla guis work fine, the problem is with custom guis. Not the items themselves. And the issue is not client-sided, as it occurs on vanilla Minecraft and all players who have joined the server are experiencing the same issue.

**Comment by LoneDev6** [comment]
Open a private ticket on my Discord (even if it's not a payment related issue), send me your server IP, OP my account: `LoneDev`

Thanks

**Comment by BookWyrm114** [comment]
Ok, though small update, I actually fixed most of the problem by replacing the jar again, so the guis flicker but the items are visible, but villager trades don't show up at all still.

**Comment by BookWyrm114** [comment]
I've DM'd you the server IP on discord but It didn't go through so I sent a friend request
and the the screenshot won't upload to github so I uploaded it on imgur: https://imgur.com/uEm2JFt

**Comment by BookWyrm114** [comment]
![image](https://user-images.githubusercontent.com/79489385/158831446-a94ebe4c-a527-4b89-ada4-0c72bc5f4587.png)
