### ISSUE TITLE
Critical MMOItems error integration: Losing the skins of each item on revision update

### ISSUE THREAD

**Issue by TonyMontero** [PluginBugs/Issues-ItemsAdder#1558]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Sistemas#8487

### What happened?

If MMOItems has the "Revision ID system" activated (makes an item update their stats / name upon picking it again or just joining again the server) ItemsAdder will delete automatically his Skin as it will try to load the default texture.

### Steps to reproduce the issue

This video explains it pretty well: https://www.youtube.com/watch?v=ascJBP30M3k

1. Create a new MMOItems item, in this case:

`AWESOME_SWORD:
  base:
    material: STONE_SWORD
    revision-id: 1
    name: 'My awesome sword'
    lore:
    - '&7Look at me, I'm a lore!'
    attack-damage:
      base: 9.7
    required-level:
      base: 3
    max-durability: 230
    tier: UNCOMMON`

2. Create the item in ItemsAdder to add a custom skin to the MMOItems and link both of them.
3. Update the revision id of any item using commands or config
4. Enjoy the lose of the texture dropping from the ground, moving from your inventory, fast shift clicking or any action that moves the item.

### Server version

Current: git-Purpur-1564 (MC: 1.18.1)*

### ItemsAdder Version

ItemsAdder version 3.0.3-beta4

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.18

### Screenshots/Videos (you can drag and drop files or paste links)

https://www.youtube.com/watch?v=ascJBP30M3k

**Comment by LoneDev6** [comment]
Can you add MMOItems developer to this ticket?
I am not resetting the CustomModelData of items on pickup, so I guess this is something to do with MMOItems itself removing the CustomModelData set by ItemsAdder to the pickedup ItemStack.

Let me know

**Comment by Indyuce** [comment]
The item loses its custom model data because it doesn't have one in the MMOItems config file. It's "losing" it because MMOItems considers that it should NOT have any.

What the item revision ID system does is that it basically regenerates the item with the newest config version. However the item config happens NOT to have any info about the custom model data bound to it.

The solution is to set the right custom model data when creating the item in MMOItems. ItemsAdder should be providing that custom model data

**Comment by TonyMontero** [comment]
It does with the /iatag, but still think something's a little off with the integration, but still I give it as a closed issue I guess.
Thanks both of you for your time!
