### ISSUE TITLE
/iazip not working 

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#1559]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

SLoKer#5953

### What happened?

just type , /iazip | Error | https://paste.md-5.net/jibidoraki.cs

### Steps to reproduce the issue

/iazip

### Server version

[06:37:19 INFO]: This server is running Paper version git-Paper-257 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: b8c90d2)
You are running the latest version
Previous version: git-Paper-252 (MC: 1.18.2)

### ItemsAdder Version

ItemsAdder version 3.0.3-beta4

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.18

### LightAPI Version (optional)

.

### LibsDisguises Version (optional)

.

### FULL server log

.

### Error (optional)

```shell
https://paste.md-5.net/jibidoraki.cs
```

### ItemsAdder config.yml

```shell
.
```

### Problematic items yml configuration file (optional)

```shell
.
```

### Other files, you can drag and drop them here to upload. (optional)

.

**Comment by LoneDev6** [comment]
Will be fixed
