### ISSUE TITLE
Double chests interfere with REAL_TRANSPARENT blocks (Forestry add-on)

### ISSUE THREAD

**Issue by ProfessionalBoatDrifter** [PluginBugs/Issues-ItemsAdder#1562]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Akrill#0001

### What happened?

Pre-report disclosure:
We're running `ItemsAdder version 3.0.2` as `3.0.3-beta4` doesn't pass the bootup, stating it's out of date.

Placing down a double chest next to custom leaves (real block is `chorus_plant`) causes one Leaves block to disappear when creating the double chest and causing another Leaves block to disappear when breaking either side of the double chest.

### Steps to reproduce the issue

1. Install `ItemsAdder version 3.0.2`
2. Install Forestry add-on (https://www.spigotmc.org/resources/trees-fruits-forestry-itemsadder-addon.86963/).
3. Give yourself any custom Leaves (tested with Guava, Cherry and Avocado).
4. Give yourself at least 2 Chests.
5. Place down 2 of any Leaves in a horizontal line.
6. Place down 2 Chests along the Leaves.
7. A custom Leaves block disappears.
8. Break one of the two Chests.
9. The remaining custom Leaves block disappears.

### Server version

`git-Paper-409 (MC: 1.17.1)`

### ItemsAdder Version

`ItemsAdder version 3.0.2`

### ProtocolLib Version

`ProtocolLib version 4.8.0`

### LoneLibs Version

`LoneLibs version 1.0.18`

**Comment by LoneDev6** [comment]
This is a bit hard to fix without introducing overhead in the plugin code
