### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by LuluxClient** [PluginBugs/Issues-ItemsAdder#1567]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Lulux#4614

### What happened?

Itemsadder is the #1 plugin consuming the most on my server.
I'm on 1.18.1, latest version

### Steps to reproduce the issue

1. Have 800 players
2. 300 players on each realm
3. start a spark or a flare

### Server version

[18:48:56 INFO]: This server is running Pufferfish version git-Pufferfish-47 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: a786526 on HEAD)
You are running 9 versions beyond. Please update your server when possible to maintain stability, security, and receive the latest optimizations.
Previous version: git-Purpur-1544 (MC: 1.18.1)

### ItemsAdder Version

ItemsAdder version 3.0.3-beta4

### ProtocolLib Version

ProtocolLib version 4.8.0-SNAPSHOT-b545

### LoneLibs Version

LoneLibs version 1.0.18

### LightAPI Version (optional)

none

### LibsDisguises Version (optional)

none

### FULL server log

To big

### Error (optional)

```shell
none
```

### ItemsAdder config.yml

```shell
metrics: false
update-checker: false
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: false
      server-ip: lol
      pack-port: xd
    external-host:
      enabled: true
      url: hidden
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: false
  delay-ticks: 40
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: false
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-items: false
  extract-default-resources: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: true
liquids:
  enabled: true
huds:
  enabled: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    interval-rendering-packets-ticks: 1
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
```

### Other files, you can drag and drop them here to upload. (optional)

Profiler: https://flare.airplane.gg/4b670929

**Comment by LuluxClient** [comment]
Hey plugin is installed but why does itemsadder lag because of that ? It's only automatic cobblestone generators with some pistons, ItemsAdder has 0 link to it, no custom blocks nothing none nada so I don't understand

**Comment by LuluxClient** [comment]
![2022-03-21_11 34 46](https://user-images.githubusercontent.com/62576432/159244504-d32c8235-b57e-416d-9454-50371137df4b.png)

**Comment by LoneDev6** [comment]
1. What do you mean by "lag"?
2. Do you get actual TPS drops?
3. is that farm detected by the `/blockphysicseventdetector` command? You should let the server online for some time then use that command to log all lagging chunks.

Anyway the airplane report you sent contains info about block physics updates.
ItemsAdder has to cancel CHORUS and MUSHROOM blocks updates in order to avoid custom blocks from losing their custom texture.
If you are not using REAL and REAL_TRANSPARENT blocks types of ItemsAdder you can disable them in config.yml in order to avoid useless CPU usage.
```yml
  disable-REAL: true
  disable-REAL_TRANSPARENT: true
```

the block physics event is sadly a very intensive event on Spigot, we can't do much about that, ItemsAdder is already heavily optimized.


Let me know if I can help you with anything else.

**Comment by LoneDev6** [comment]
You can follow my advice and safely disable the options:

> Anyway the airplane report you sent contains info about block physics updates. ItemsAdder has to cancel CHORUS and MUSHROOM blocks updates in order to avoid custom blocks from losing their custom texture. If you are not using REAL and REAL_TRANSPARENT blocks types of ItemsAdder you can disable them in config.yml in order to avoid useless CPU usage.
> 
> ```yaml
>   disable-REAL: true
>   disable-REAL_TRANSPARENT: true
> ```
> 
> the block physics event is sadly a very intensive event on Spigot, we can't do much about that, ItemsAdder is already heavily optimized.

**Comment by LuluxClient** [comment]
> You can follow my advice and safely disable the options:
> 
> 
> 
> > Anyway the airplane report you sent contains info about block physics updates. ItemsAdder has to cancel CHORUS and MUSHROOM blocks updates in order to avoid custom blocks from losing their custom texture. If you are not using REAL and REAL_TRANSPARENT blocks types of ItemsAdder you can disable them in config.yml in order to avoid useless CPU usage.
> 
> > 
> 
> > ```yaml
> 
> >   disable-REAL: true
> 
> >   disable-REAL_TRANSPARENT: true
> 
> > ```
> 
> > 
> 
> > the block physics event is sadly a very intensive event on Spigot, we can't do much about that, ItemsAdder is already heavily optimized.
> 
> 
> 
> You could also disable REAL_NOTE
> 
> 

Hey after disabling it it went from 4-5% to 1-2% ! 

Also should I create another git issue for another bug I have ? The latest update is breaking half of my textures.

**Comment by LoneDev6** [comment]
For sure, open a new issue report.

Anyway this is very strange, I always test the update before release
