### ISSUE TITLE
IA version 3.0.4b custom symbol does not work

### ISSUE THREAD

**Issue by nhanledev** [PluginBugs/Issues-ItemsAdder#1576]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

The update 3.0.4 stated that there is a problem that cause custom symbol of font stop working. The problem is still persist in both 3.0.4 and 3.0.4b to me even I followed the step:
- Delete font_images_unicode_cache.yml
- Do an /iazip to recompile the pack

Even a server restart does not help. As soon as I upload 3.0.3beta4 and do a /iazip, the custom symbol font works again.

### Steps to reproduce the issue

1. Update 3.0.3 to 3.0.4
2. Remove `font_images_unicode_cache.yml`
3. Do `/iazip`
4. Reboot the server
5. The custom symbol is still a square thing

### Server version

Paper 1.17.1 build 409

### ItemsAdder Version

3.0.4 and 3.0.4b

### ProtocolLib Version

ProtocolLib 4.0.8

### LoneLibs Version

Lonelib 1.0.18

### LightAPI Version (optional)

LightAPI 5.0.2

**Comment by LoneDev6** [comment]
Changelog:
> - fix font images manual symbol loading not working correctly. If you had this problem: stop your server, delete ItemsAdder/storage/font_images_unicode_cache.yml file, start, regen your resourcepack.

The fix mentioned was for manually set symbols, the problem you're having is surely not related.
Feel free to open a public thread on the Discord server to get help from the community.
Also make sure to read here, you might find the cause: https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown#enable-output-log

**Comment by LoneDev6** [comment]
Wait.
I don't quite understand what you're saying here:
> Even a server restart does not help. As soon as I upload 3.0.3beta4 and do a /iazip, the custom symbol font works again.


What do you mean?

**Comment by nhanledev** [comment]
> Wait. I don't quite understand what you're saying here:
> 
> > Even a server restart does not help. As soon as I upload 3.0.3beta4 and do a /iazip, the custom symbol font works again.
> 
> What do you mean?

I am sorry for have been writing so ambiguous. What I mean is that I have a config like this:
```
  gui_logo_small_1:
    path: "gui/logo_01.png"
    scale_ratio: 39
    y_position: 23
    symbol: "覟"
``` 

The symbol show as a square character which mean it is broken in both version 3.0.4 and 3.0.4b.
I followed the instruction to delete `ItemsAdder/storage/font_images_unicode_cache.yml` and regen the resource pack, but it did not help.
If I reupload 3.0.3beta4 and delete the `font_images_unicode_cache.yml` and regen the resource pack, the character works normally.
That why I need you to recheck if custom symbol is fixed or not.
Thank you so much <3

**Comment by LoneDev6** [comment]
Okay, basically you delete `font_images_unicode_cache.yml` one time then run /iazip, as explained in the update note.
This allows the plugin to bind the character correctly.

Wasn't that enough to fix the issue?

**Comment by nhanledev** [comment]
Yes it does not work on my end.

**Comment by LoneDev6** [comment]
what happens if you write `覟` in chat?

**Comment by nhanledev** [comment]
It show a square character, not the character itself

**Comment by nhanledev** [comment]
I can send you my whole ItemAdder folder privately to let you inspect what is happening

**Comment by LoneDev6** [comment]
Open a private ticket on my Discord server and send me your whole itemsadder folder, thanks a lot

**Comment by LoneDev6** [comment]
https://discord.com/channels/533407895010803753/638735698693718037/944572047093297183

**Comment by nhanledev** [comment]
> Open a private ticket on my Discord server and send me your whole itemsadder folder, thanks a lot

I have created a ticket and send you my whole ItemAdder folder. Thank you.
