### ISSUE TITLE
Add options about 'auto-external-host' can select between resourcepack.host  or mc-packs.net

### ISSUE THREAD

**Issue by ArtifactyNight** [PluginBugs/Issues-ItemsAdder#1579]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

NightKunGz#0790

### Describe the solution you'd like

add option to allow admin can select between mc-packs.net or resourcepack.host
like:

```yml
auto-external-host:
      enabled: true
      # choose between: mc-packs.net or resourcepack.host
      host: mc-packs.net
```

### Is your feature request related to a problem?

mc-packs is much faster than resourcepack.host for my region (thailand)

so resourcepack.host is make resourcepack loading screen is weird display like this 😂 
(it's happen everytime and so slow when i update a resourcepack)
![image](https://user-images.githubusercontent.com/53427253/160120595-f570629b-db3b-47c3-85c8-77dadc89ba2e.png)

### Describe alternatives you've considered

-

**Comment by LoneDev6** [comment]
I'll do some testing but I'm not sure if https://mc-packs.net/ supports automatic uploading.

**Comment by LoneDev6** [comment]
mc-packs.net doesn't support automatic uploading, I have to work on something since resourcepack.host was shut down.
