### ISSUE TITLE
Console error and spam trying to summon new entity

### ISSUE THREAD

**Issue by GuardianFlame** [PluginBugs/Issues-ItemsAdder#1581]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

GuardianFlame#8252

### What happened?

After adding spikedcreations Purple Dragon to my server with the newest itemsadder and lonelibs update (3.0.4b), attempting to spawn the dragon returns a repeating spam error, that does not stop until i restart the server. Id love to get this feature working so any help would be appreciated!

Here is the error from the start as far as i could copy it, if you need a full server log contact me on discord at guardianflame#8252
https://pastebin.com/SqWC9PGg

Im running paper 1.17.1, I updated itemsadder from 2.5.5 at the same time updating lonelibs, and adding this dragon. To add the dragon i unzipped the file from the download, and dragged the data folder to my itemsadder plugin folder. All files and namespaces seemed to be where they should be. Then i did /iazip, uploaded the resourcepack to dropbox, and ran /iareload and /iatexture. here is attempt #3 to summon the dragon
https://pastebin.com/bfsMRCPu

### Steps to reproduce the issue

1. download itemsadder update (3.0.4b) and latest lone libs version
2. download spikedcreations purple dragon https://www.spigotmc.org/resources/spiked-creations-rideable-dragon.100777/
3. delete old items adder and lone lobs jar, replace with newly downloaded jars
4. restat the server
5. run /iazip
6. upload resource pack to dropbox
7. run /iareload
8. run /iatexture
9. run /iaentity summon spikedcreations:purpledragon or /iaentity summon purpledragon

Errors:
https://pastebin.com/GF8LabFQ
https://pastebin.com/SqWC9PGg
https://pastebin.com/bfsMRCPu

### Server version

This server is running Paper version git-Paper-378 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc2ecbc)
You are 31 version(s) behind
Download the new version at: https://papermc.io/downloads

### ItemsAdder Version

itemsadder version 3.0.4b

### ProtocolLib Version

ProtocolLib 4.7.0

### LoneLibs Version

LoneLibs 1.0.18

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: false
      server-ip: 127.0.0.1
      pack-port: 8163
    external-host:
      enabled: true
      url: https://www.dropbox.com/s/74rc1ko3emoljaw/pack1.3.zip?dl=0
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: false
    hide-hud: false
    cancel-movement: false
    lock-player: false
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: false
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-items: false
  extract-default-resources: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: true
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - OCEAN
      - PLAINS
      - DESERT
      - MOUNTAINS
      - FOREST
      - TAIGA
      - SWAMP
      - RIVER
      - FROZEN_OCEAN
      - FROZEN_RIVER
      - SNOWY_TUNDRA
      - SNOWY_MOUNTAINS
      - MUSHROOM_FIELDS
      - MUSHROOM_FIELD_SHORE
      - BEACH
      - DESERT_HILLS
      - WOODED_HILLS
      - TAIGA_HILLS
      - MOUNTAIN_EDGE
      - JUNGLE
      - JUNGLE_HILLS
      - JUNGLE_EDGE
      - DEEP_OCEAN
      - STONE_SHORE
      - SNOWY_BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - DARK_FOREST
      - SNOWY_TAIGA
      - SNOWY_TAIGA_HILLS
      - GIANT_TREE_TAIGA
      - GIANT_TREE_TAIGA_HILLS
      - WOODED_MOUNTAINS
      - SAVANNA
      - SAVANNA_PLATEAU
      - BADLANDS
      - WOODED_BADLANDS_PLATEAU
      - BADLANDS_PLATEAU
      - SMALL_END_ISLANDS
      - END_MIDLANDS
      - END_HIGHLANDS
      - END_BARRENS
      - WARM_OCEAN
      - LUKEWARM_OCEAN
      - COLD_OCEAN
      - DEEP_WARM_OCEAN
      - DEEP_LUKEWARM_OCEAN
      - DEEP_COLD_OCEAN
      - DEEP_FROZEN_OCEAN
      - THE_VOID
      - SUNFLOWER_PLAINS
      - DESERT_LAKES
      - GRAVELLY_MOUNTAINS
      - FLOWER_FOREST
      - TAIGA_MOUNTAINS
      - SWAMP_HILLS
      - ICE_SPIKES
      - MODIFIED_JUNGLE
      - MODIFIED_JUNGLE_EDGE
      - TALL_BIRCH_FOREST
      - TALL_BIRCH_HILLS
      - DARK_FOREST_HILLS
      - SNOWY_TAIGA_MOUNTAINS
      - GIANT_SPRUCE_TAIGA
      - GIANT_SPRUCE_TAIGA_HILLS
      - MODIFIED_GRAVELLY_MOUNTAINS
      - SHATTERED_SAVANNA
      - SHATTERED_SAVANNA_PLATEAU
      - ERODED_BADLANDS
      - MODIFIED_WOODED_BADLANDS_PLATEAU
      - MODIFIED_BADLANDS_PLATEAU
      - BAMBOO_JUNGLE
      - BAMBOO_JUNGLE_HILLS
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: false
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 50
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    interval-rendering-packets-ticks: 1
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
```

**Comment by SirCraftypants** [comment]
Update Paper, if that does not fix it, try reverting to IA version 3.0.4

**Comment by GuardianFlame** [comment]
> Update Paper, if that does not fix it, try reverting to IA version 3.0.4

Update paper to what? 1.18? I dont plan to update to that, is it required? I run through shockbyte and these are my options
![image](https://user-images.githubusercontent.com/102440382/160268438-af195c25-e648-4b58-8f5f-38e01141ab1e.png)

**Comment by SirCraftypants** [comment]
I see, ok try reverting to IA 3.0.4 and see if the error stops.

**Comment by GuardianFlame** [comment]
> I see, ok try reverting to IA 3.0.4 and see if the error stops.

Same issue here is the console error
https://pastebin.com/Q8MNEjBE

**Comment by SirCraftypants** [comment]
> > I see, ok try reverting to IA 3.0.4 and see if the error stops.
> 
> Same issue here is the console error https://pastebin.com/Q8MNEjBE

OK, lonedev will be with you asap, he doesn't work on weekends and should be back on Monday (tomorrow) so please bare with us.

**Comment by GuardianFlame** [comment]
Thats alright! Thank you!

**Comment by LoneDev6** [comment]
Send the full log.
Somehow the plugin cannot spawn the entity because it can't find the needed code in the Minecraft server version installed.
This cannot happen in normal conditions

**Comment by GuardianFlame** [comment]
> Send the full log. Somehow the plugin cannot spawn the entity because it can't find the needed code in the Minecraft server version installed. This cannot happen in normal conditions

https://paste.shockbyte.com/nifehifucevoweqiqewe

and just in case i left it to spam for a bit and here is that log
https://paste.shockbyte.com/afocupahojogapupatel

**Comment by GuardianFlame** [comment]
Here is after restarting the server, maybe theres an error in there that helps https://paste.shockbyte.com/nipeletolidolovijopa

**Comment by LoneDev6** [comment]
Update to 3.0.4b

**Comment by GuardianFlame** [comment]
> Update to 3.0.4b.
> 
> 3.0.4 version was a corrupted JAR.

I was in 3.0.4b, SirCraftypants above asked me to try downgrading, ill try upgrading again.

**Comment by SirCraftypants** [comment]
could explain why i'm having issues seeing as i'm on 3.0.4 also.

**Comment by GuardianFlame** [comment]
Here is me trying to summon the dragon in 3.0.4b
https://paste.shockbyte.com/inobihupiquletisicag

Same error

**Comment by LoneDev6** [comment]
I found the cause of the issue, thanks for the detailed log
