### ISSUE TITLE
ItemBridge Support

### ISSUE THREAD

**Issue by ElMoha943** [PluginBugs/Issues-ItemsAdder#1585]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Valen#7358

### Describe the solution you'd like

There is this plugin called [ItemBridge](https://www.spigotmc.org/resources/itembridge-save-items-and-use-them-wherever-you-want-including-other-plugins-best-w-customitems.77080/), wich help adding compatibility between plugins. I already suggested this in discord and people seem to like it.

### Is your feature request related to a problem?

Not directly but there are plugins having trouble to implement things, for example using other custom items inside IAs recipes/vendors.

### Describe alternatives you've considered

There are similar plugins like Mimic for example that would also do the job, ideally ia should support both.

**Comment by ElMoha943** [comment]
![imagen](https://user-images.githubusercontent.com/25410859/160723104-a11204c4-79bb-4f9f-a068-d250b7312231.png)

**Comment by ArubikU** [comment]
public class ItemsAdderBridge implements ItemBridgeListener{

    private static ItemBridge bridge;
    public static void setup(Plugin plugin){
        bridge = new ItemBridge(plugin, "itemsadder", "ia");
        bridge.registerListener(new ItemsAdderBridge());
    }

    @Override
    public ItemStack fetchItemStack(String item){
        return ItemsAdder.getCustomItem(item);
    }
}

@LoneDev6

**Comment by LoneDev6** [comment]
Will be added in 3.1.0

**Comment by ElMoha943** [comment]
@LoneDev6 is this working on vendor behaviour?
![imagen](https://user-images.githubusercontent.com/25410859/162534397-281165a5-8df8-4bb8-86a5-ebee0ef08294.png)
![imagen](https://user-images.githubusercontent.com/25410859/162534442-4693d2d4-5aee-4292-8ee4-417f90827a0c.png)

**Comment by LoneDev6** [comment]
I literally just implemented the code sent by @ArubikU , this code makes OTHER plugins use ItemsAdder items, not the opposite.

https://itemsadder.devs.beer/compatibility-with-other-plugins/compatible/itembridge

**Comment by ElMoha943** [comment]
Would it be possible to implement it inside items adder too? it kinda was the whole point of the suggestion 😅

**Comment by ElMoha943** [comment]
@LoneDev6 would it be possible to add that?

**Comment by LoneDev6** [comment]
There is no need to bump issues, as you can see there are 174 currently opened suggestions/help requests.
Anyway, this request is not really straightforward to be implemented, I'll try to find a proper solution to do that but it's not easy to add without introducing issues.
The Minecraft trading GUI is known to be unstable because most recipes won't match if the items have complex NBT data inside.
That's one of the reasons why I'd avoid adding compatibility.

**Comment by ElMoha943** [comment]
Sorry for the bump, i didnt want to open a new issue of the same topic and didnt know if  you saw the message bc it was already closed. 

About compatibility, you could add itemsbridge/mimic compat inside vendors and worst case essenario some items wouldnt work, but at least most would.

Thanx you again for taking time to answer this issue <3

**Comment by LoneDev6** [comment]
No problem, I wish I could answer faster but you can clearly see the amount of messages I get scattered around all the websites.
I'll try to find the best solution to support every plugin.

Basically you to be able to use mimic/itemsbridge items in:
- ItemsAdder recipes
- ItemsAdder trading machines
- ItemsAdder drops/loots

Nothing else?

**Comment by ElMoha943** [comment]
Nothing else i can think off, does recipes include all crating table, cooking, anvil repair, etc?

**Comment by Garfieldwxg55** [comment]
Would this also be compatible with the /ia menu? Thanks
