### ISSUE TITLE
Ability to send different resource packs to players.

### ISSUE THREAD

**Issue by RedishKitter** [PluginBugs/Issues-ItemsAdder#1588]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Kitters#5239

### Describe the solution you'd like

A way for itemadder to send different resourcepacks to players.

This could be useful for many things, such as having custom resourcepacks for different gamemodes within the same server; or giving players the option to choose from a resourcepack that retextures vanilla minecraft, and one that doesn't retexture vanilla minecraft (in order for the player to use their own resourcepack alongside the server one)

### Is your feature request related to a problem?

Just want to be able to give my players the best catered visual experience.

### Describe alternatives you've considered

Ive considered using other plugins to do this, however it would be nice if it was built into itemadder.

**Comment by LoneDev6** [comment]
This idea is good but would make resourcepack management very tedious/hard for the admin and is also complex to implement

**Comment by RedishKitter** [comment]
> This idea is good but would make resourcepack management very tedious/hard for the admin and is also complex to implement

Valid reasons. Would be a useful feature if you ever got to implementing it though. 
Here's one plugin that's able to do it if you ever wanted to look more into it: https://www.spigotmc.org/resources/bungee-resourcepacks.6137/
