### ISSUE TITLE
AdvancedSlimePaper compatibility

### ISSUE THREAD

**Issue by bckd00r** [PluginBugs/Issues-ItemsAdder#1589]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

if#7858

### What happened?

I'm using the Advanced Slime World Manager plugin and creating a custom world for each player. When I add itemsadder blocks to the created worlds, it creates hundreds of empty folders in my server folder where only the itemsadder blocks are registered for each world.

### Steps to reproduce the issue

1. slime world manager plugin creates low-dimensional worlds for players.
![image](https://user-images.githubusercontent.com/48347237/161303370-9fb5978b-270f-443d-bb68-07a4899ab499.png)

2.The player saves their current world's progress on the slime world system, but when they use a block for the itemsadder it creates a folder in my server list for each player.
![image](https://user-images.githubusercontent.com/48347237/161303749-e9116ee8-48e3-4475-b449-fda1ad5f7a76.png)

### Server version

![image](https://user-images.githubusercontent.com/48347237/161303992-cb58fb2e-5709-43cd-831b-9e11778b9fdf.png)

### ItemsAdder Version

3.0.4b

### ProtocolLib Version

4.8.0

### LoneLibs Version

1.0.18

### LightAPI Version (optional)

5.2.0

### FULL server log

not error

### Error (optional)

```shell
not error
```

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: 146.19.57.53
      pack-port: 3162
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: false
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: false # default true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    - bbmodel
    - iaentitymodel
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-items: true
  extract-default-resources: true
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: false
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: false
liquids:
  enabled: false
huds:
  enabled: false
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: false
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: false
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    interval-rendering-packets-ticks: 1
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

I think the error is pretty self explanatory. The only solution is to create a single folder and keep the player block data in it.

**Comment by LoneDev6** [comment]
> it creates hundreds of empty folders in my server folder where only the itemsadder blocks are registered for each world.

> The only solution is to create a single folder and keep the player block data in it.


I don't really understand your solution.
ItemsAdder creates custom region files in order to save custom blocks data. These files are saved inside the Minecraft world folder. One file per-region.
What else should I do?

**Comment by ComputerNerd100** [comment]
Hey @LoneDev6 I was nudged to have a look at this one - I'm one of the devs working on ASWM.
Is the custom block data, etc. that's saved into the minecraft world folder just standard NBT data?
If so, we expose a feature in the ASWM API that allows plugins to add NBT data which can be compressed and saved alongside the world in the slime format. I'm happy to lend a hand looking at integrating this if it's something you'd like to explore :)

**Comment by LoneDev6** [comment]
Yes it's just normal NBT.
There is already an API to write this info: https://github.com/LoneDev6/API-ItemsAdder/blob/master/src/main/java/dev/lone/itemsadder/api/CustomBlock.java#L316

**Comment by ComputerNerd100** [comment]
The API on your side looks great, it definitely seems like an integration would be possible.
Would an ASWM integration be something you'd be willing to look at bundling into IA internally, or would this be something you'd want to be an external hook that bridges between IA and ASWM?

**Comment by LoneDev6** [comment]
I don't really have any idea of how ASWM works so I guess i'd have to restructure the whole plugin?

**Comment by ComputerNerd100** [comment]
@LoneDev6 It shouldn't need a major restructure, although I guess it would depend how the NBT saving process works internally.
Realistically it should be possible to include a hook class that links into the ASWM API which could be utilised during saving to tell if its a regular bukkit world and apply standard saving, or if its an ASWM world and then save the NBT data into the NBT tag of the world.
I'll have a flick through my end and see if I can figure out some slightly clearer explanation of what I've got in my head

**Comment by bckd00r** [comment]
@LoneDev6 ASWM uses a special algorithm to save external world data, so you can learn that the current world is ASWM and save data on it, with only minor changes, if the api or config allows it, I can code it as an addon!

**Comment by AltrixMC** [comment]
So ? @LoneDev6 Can you do that ?

**Comment by matyasvane** [comment]
@LoneDev6 We are calling to add support. :dancing_men:

**Comment by LoneDev6** [comment]
I didn't test but the new update should add compatibility out of the box: https://github.com/PluginBugs/Issues-ItemsAdder/milestone/78

I'll do some tests later.

**Comment by matyasvane** [comment]
@LoneDev6 Of course I know, now I can create a plugin that uses the Iris generator to create a world with custom blocks. these worlds have a maximum size of 300x300 and are bordered by a worldbordel. At the same time, I have a server with 5950X and 128gb of ram built for good operation. At the same time, I added safety features. My server at full load will load a maximum of 500 worlds, which I calculated should be fine

**Comment by LoneDev6** [comment]
Basically the new update just fixes a bug where the plugin creates custom region folder in the `world/X` folder even though some servers have worlds folders in custom paths, in this case Slime format saves worlds in non standard folders if I understood.

**Comment by matyasvane** [comment]
> 
Yes exactly, the slimeworldmanager saves the files in the slimeworld_worlds folder (if I'm not mistaken). Here it creates <world_name>.slime style files.

**Comment by LoneDev6** [comment]
To be honest based on the first message I see that `Advanced Slime World Manager` plugin is creating a single folder per world, so itemsadder might still have issues in this particular case because it will create a single region folder for all worlds, this will surely break stuff.
So nvm, I doubt it will work fine even in the new update. I will probably have so make some proper compatibility for slime regions.

**Comment by matyasvane** [comment]
> Nová aktualizace v podstatě jen opravuje chybu, kdy plugin vytváří složku vlastní oblasti ve složce, `world/X`i když některé servery mají složky světů ve vlastních cestách, v tomto případě formát Slime ukládá světy do nestandardních složek, pokud jsem to pochopil.

Yes exactly, the slimeworldmanager saves the files in the slimeworld_worlds folder (if I'm not mistaken). Here it creates <world_name>.slime style files.

**Comment by matyasvane** [comment]
@LoneDev6 The workaround doesn't seem to work. Blocks are changed to noteblocks without ia function. I'm not sure where you store this data. But it would be best if we could possibly change the /root/itemsadder/<world>/<data> folder

**Comment by LoneDev6** [comment]
yea as i said in my previous message it surely won't work because files are saved into `<worldfolder>/itemsadder/regions/xxx`.
I will have to customize that for slime worlds specifically, I'll do some tests as soon as I have time.

**Comment by matyasvane** [comment]
When do you think you could try to focus on this problem? I know you are busy with this plugin, but a lot of us are waiting for this update to be able to use Slime worlds :D

**Comment by matyasvane** [comment]
> ano, jak jsem řekl ve své předchozí zprávě, určitě to nebude fungovat, protože soubory jsou uloženy do `<worldfolder>/itemsadder/regions/xxx`. Budu to muset upravit speciálně pro slizové světy, hned jak budu mít čas, udělám nějaké testy.

When do you think you could try to focus on this problem? I know you are busy with this plugin, but a lot of us are waiting for this update to be able to use Slime worlds

**Comment by matyasvane** [comment]
> yea as i said in my previous message it surely won't work because files are saved into `<worldfolder>/itemsadder/regions/xxx`. I will have to customize that for slime worlds specifically, I'll do some tests as soon as I have time.

When do you think you could try to focus on this problem? I know you are busy with this plugin, but a lot of us are waiting for this update to be able to use Slime worlds :D

**Comment by LoneDev6** [comment]
Will be checked.
I'll work on this as soon as I find the time.
