### ISSUE TITLE
Add support for Velocity to BungeePackFix

### ISSUE THREAD

**Issue by ImFound** [PluginBugs/Issues-ItemsAdder#1593]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

ImFound#0001

### Describe the solution you'd like

Hi, I want to get velocity support to bungeepackfix

### Is your feature request related to a problem?

yes, it's annoying that if a player goes to hub and the texture  needs to be reloaded

### Describe alternatives you've considered

nope

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1504
https://github.com/PluginBugs/Issues-ItemsAdder/issues/701
