### ISSUE TITLE
Double emotes?

### ISSUE THREAD

**Issue by Wupin** [PluginBugs/Issues-ItemsAdder#1599]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Wupin#8643

### What happened?

The bug is self-explanatory just look at this video https://www.youtube.com/watch?v=ETV9FXZYCdk

### Steps to reproduce the issue

1. Play any emote
2. Switch to gamemode spectator
3. Switch back to survival
4. Tada you clone yourself

### Server version

This server is running Paper version git-Paper-270 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fa68bb1)
You are 13 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-168 (MC: 1.18.1)

### ItemsAdder Version

3.1.0c

### ProtocolLib Version

4.8.0

### LoneLibs Version

1.0.18

### LibsDisguises Version (optional)

10.0.28-SNAPSHOT

### Screenshots/Videos (you can drag and drop files or paste links)

https://www.youtube.com/watch?v=ETV9FXZYCdk

**Comment by LoneDev6** [comment]
yea i think i might just stop emotes on gamemode change
