### ISSUE TITLE
[Compatibility] Mana Bar and Skill API

### ISSUE THREAD

**Issue by Andrew99CZ** [PluginBugs/Issues-ItemsAdder#160]
It would be great if the mana bar worked for a plugin like skill api.
(I don't know what the mana bar now works with)

**Comment by maximsGitHub** [comment]
Yeah I'd like to know what the mana bar is for too

**Comment by Andrew99CZ** [comment]
Ok, Skill API dont work well on new version but Heroes or MMOCore work well on 1.15.
