### ISSUE TITLE
[DUPE REAL_WIRE] 

### ISSUE THREAD

**Issue by paulreob** [PluginBugs/Issues-ItemsAdder#1601]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

Duplication consists of placing and breaking at the same time ON A CUSTOM BLOCK

Ps: duplication doesn't work on vanilla blocks and sometimes when you break a REAL_WIRE the custom block below it disappears

https://imgur.com/a/3pfDinw

### Steps to reproduce the issue

Place and break a REAL_WIRE type block at the same time on a customblock, and you will see how it is duplicated

### Server version

git-Purpur-1562 (MC: 1.18.1)*

### ItemsAdder Version

ItemsAdder version 3.1.0d

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.18

### Screenshots/Videos (you can drag and drop files or paste links)

https://imgur.com/a/3pfDinw

**Comment by LoneDev6** [comment]
Thanks for the high amount of details, I will fix this in the next release
