### ISSUE TITLE
REAL_TRANSPARENT DUPE

### ISSUE THREAD

**Issue by ElMoha943** [PluginBugs/Issues-ItemsAdder#1603]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

After updating to lastest version, REAL_TRANSPARENT custom blocks started appearing randomly when placing/breaking/updating other blocks

### Steps to reproduce the issue

Place blocks. More info in video below

### Server version

git-Purpur-1609 (MC: 1.18.2)

### ItemsAdder Version

3.1.0c

### ProtocolLib Version

4.8.0

### LoneLibs Version

1.0.18

### LibsDisguises Version (optional)

10.0.28-SNAPSHOT

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/8455616/latest.log)

### Screenshots/Videos (you can drag and drop files or paste links)

https://user-images.githubusercontent.com/25410859/162541653-ae58c727-6e4c-46e8-8d66-e52f6869b03a.mp4

**Comment by LoneDev6** [comment]
This is just impossible, are you sure you don't have any plugin which uses ItemsAdder API and is placing these blocks?

**Comment by ElMoha943** [comment]
Here is a list with all my plugins
![imagen](https://user-images.githubusercontent.com/25410859/162723682-684b87a1-09b1-4c0f-aea7-37bec2c2874a.png)

This bug only happens in the last version of ItemsAdder, downgradding to previous version solves it.

**Comment by LoneDev6** [comment]
I cannot reproduce the issue in any way
https://streamable.com/qs0d5z

**Comment by ElMoha943** [comment]
may be problem with purpur? i have a setting to prevent chorus fruit update.

**Comment by LoneDev6** [comment]
I don't know, you have to test.
I sadly can't know each server setup out there, so the only way to know the cause is to test

**Comment by ElMoha943** [comment]
> I think this area had some custom blocks before, someone replaced them via worldedit with AIR. Then if you place a block it will refresh blocks around making old blocks popup back again.
> 
> I'm 99% sure this is the issue

Could reproduce this. That was causing the problem, thanx.

**Comment by matyasvane** [comment]
I have same problem, with purpur

**Comment by matyasvane** [comment]
https://streamable.com/vyidfq VIDEO about problem.

**Comment by LoneDev6** [comment]
> https://streamable.com/vyidfq VIDEO about problem.

Open a new bug report, this is clearly a different and you're even in creative, so it's not a duplication bug.

**Comment by mitchngwen** [comment]
I am having a similar issue, custom blocks that were removed via world edit now reappear when manually placing a block in that area, when breaking the custom blocks that reappear  another one appears next to where that block was broken. Does anyone know the fix?
