### ISSUE TITLE
BeautyQuests hologram text on npc head are missing

### ISSUE THREAD

**Issue by h266579110** [PluginBugs/Issues-ItemsAdder#1604]
### What happened?

ItemsAdder cause beautyquests quest npc hologram missing, conflict?

https://github.com/SkytAsul/BeautyQuests/issues/214

### Steps to reproduce the issue

0. Server install BeautyQuests and ItemsAdder
1. Create a quests attach to a Citizens NPC
2. Full restart server.
3. Quest holograms missing.

### Server version

PaperMC 1.18.2-281

### ItemsAdder Version

ItemsAdder 3.1.0c

### ProtocolLib Version

ProtocolLib 4.8.0

### LoneLibs Version

LoneLibs 1.0.18

**Comment by SkytAsul** [comment]
After investigating, I found out that the issue in BeautyQuests was caused by ItemsAdder reloading Citizens. I made a fix to make BeautyQuests handle reloads gracefully, but it would be better for ItemsAdder to work without having to reload Citizens.
