### ISSUE TITLE
Mcmmo treefeller durability issue with custom axes

### ISSUE THREAD

**Issue by Ecilpse** [PluginBugs/Issues-ItemsAdder#1605]
### Discord tag (optional)

EclipseMC#7777

### What happened?

I asked the developer of MCmmo, but I also i wrote here because I thought it might be an IA problem.

when player break wood block with tree feller, (mcmmo skill)
custom model axe's durability was decrased 3x faster than normal axe.
The screenshot is shows the durability left after each treefeller skill was used once.
(same enchantments : durabiliy 3, dig_speed 5, fortune 3, silk_touch 3)
![3](https://user-images.githubusercontent.com/25452835/162568741-f1e42e75-57da-456d-a0da-987f8d555f23.PNG)
![3](https://user-images.githubusercontent.com/25452835/162568760-dbf00cec-bd8f-4e2d-9424-594b36f6dfa7.PNG)

Config: [download](https://github.com/PluginBugs/Issues-ItemsAdder/files/8463821/Desktop.zip)

Video: https://www.youtube.com/watch?v=_1eTEmXfETs

### Steps to reproduce the issue

1. make the same tool as the option in the screenshot I attached.
2. apply same enchant each axe. (custom model axe, normal axe / durabiliy 3, dig_speed 5, fortune 3, silk_touch 3)
3. use mcmmo axe skill (  mcMMO: Version: 2.1.210 )

### Server version

Purpur 1.18.1-RO.1-SNAPSHOT

### ItemsAdder Version

3.0.3-beta4

### ProtocolLib Version

Version: 4.8.0-SNAPSHOT-b545

### LoneLibs Version

1.0.18

**Comment by LoneDev6** [comment]
Send the configuration as text not screenshot

**Comment by NCSV** [comment]
> Send the configuration as text not screenshot
[Desktop.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/8463821/Desktop.zip)

**Comment by LoneDev6** [comment]
I think it's because of the amount of broken block at the same time.
The tool gets durability decreased based on the amount of broken blocks.

**Comment by LoneDev6** [comment]
Is this actually a problem?

**Comment by NCSV** [comment]
> Is this actually a problem?

critical issue for players.
when player once execute woodcutting skills, axe's durability was almost broken. (3 times faster than normal axe)
So some users's item was destoried because they don't know this problems was happend.
I'm selling custom model items for players. (per 5 dollars) so they are very upset..

**Comment by LoneDev6** [comment]
I see, I will send you a beta JAR to test with a fix!

**Comment by NCSV** [comment]
> I see, I will send you a beta JAR to test with a fix!

thank you i will check.

**Comment by LoneDev6** [comment]
@NCSV 
I cannot reproduce the issue.
This is a McMMO behaviour, it works the same way as with vanilla axes.
Durability of the tool is changed based on the amount of broken blocks.
This has nothing to do with ItemsAdder.

https://user-images.githubusercontent.com/27242001/162763949-37bd7cb5-bbce-4900-be3e-57e2b49db7bf.mp4



Here is the McMMO code which handles that:
https://github.com/mcMMO-Dev/mcMMO/blob/5ab55c16539f4f3db0bd7c84882f5fa719b9a440/src/main/java/com/gmail/nossr50/skills/woodcutting/WoodcuttingManager.java#L223

**Comment by Ecilpse** [comment]
> @NCSV I cannot reproduce the issue. This is a McMMO behaviour, it works the same way as with vanilla axes. Durability of the tool is changed based on the amount of broken blocks. This has nothing to do with ItemsAdder.
> 
>  OUTPUT.mp4 
> Here is the McMMO code which handles that: https://github.com/mcMMO-Dev/mcMMO/blob/5ab55c16539f4f3db0bd7c84882f5fa719b9a440/src/main/java/com/gmail/nossr50/skills/woodcutting/WoodcuttingManager.java#L223
I'm giving you a mention in case you don't see the message.
i reproduced in video.
@LoneDev6
video :  https://www.youtube.com/watch?v=_1eTEmXfETs
server info & plugins : https://paste.md-5.net/eqexujipeq

**Comment by LoneDev6** [comment]
I think it's impossible to fix because of how mcMMO works.
See:
https://github.com/mcMMO-Dev/mcMMO/blob/101c43a4bcf7d50c5ce086e0f649ee647d9eaadb/src/main/java/com/gmail/nossr50/skills/woodcutting/WoodcuttingManager.java#L226

https://github.com/mcMMO-Dev/mcMMO/blob/101c43a4bcf7d50c5ce086e0f649ee647d9eaadb/src/main/java/com/gmail/nossr50/util/skills/SkillUtils.java#L253

**Comment by LoneDev6** [comment]
Please contact mcMMO dev and link them this issue page.
