### ISSUE TITLE
Placed player heads glitched when emotes feature is enabled

### ISSUE THREAD

**Issue by DarrienNN** [PluginBugs/Issues-ItemsAdder#1606]
### Discord tag (optional)

Darrien#0022

### What happened?

After updating ItemsAdder to **_3.1.0c_** the plugin made some mods bugged again
https://www.curseforge.com/minecraft/texture-packs/night-vision

### Steps to reproduce the issue

After updating ItemsAdder to **_3.1.0c_** the plugin made some mods bugged again.
https://www.curseforge.com/minecraft/texture-packs/night-vision

Things that bugged after update IA
- Head
- Mod

It happens when LoneDev release the hide scoreboard number/etc

(I reported before using Support ticket)

### Server version

git-Purpur-1609 (MC: 1.18.2)*

### ItemsAdder Version

ItemsAdder version 3.1.0c

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b553

### LoneLibs Version

LoneLibs version 1.0.18

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/8456819/latest.log)

### ItemsAdder config.yml
<details><summary>Click to unfold</summary>

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: 15.235.151.144
      pack-port: 8189
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 3
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    - bbmodel
    - iaentitymodel
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-items: false
  extract-default-resources: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: true
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
effects:
  hide-scoreboard-numbers: true
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    interval-rendering-packets-ticks: 1
    emotes: true
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
```

</details>

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/58543201/162572402-365653f4-389e-42b8-adcb-b212ae7ed03e.png)

<details><summary>Click to unfold</summary>

![image](https://user-images.githubusercontent.com/58543201/162572404-67ce00fa-a26f-4306-a5b5-58faeae0afb9.png)
![image](https://user-images.githubusercontent.com/58543201/162572409-5151129e-4ef0-441d-a016-86e81f87579b.png)
![image](https://user-images.githubusercontent.com/58543201/162572413-6eefd996-1f4f-418e-a8f4-7689088ea0ee.png)

https://user-images.githubusercontent.com/58543201/162600855-7756f9b4-dc7c-43c6-8128-6adb862dc89d.mp4

</details>

**Comment by vdl19** [comment]
Hi, I tried disabling emote in config.yml as a solution but it didn't change anything.

entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    **emotes: false**
    interval-rendering-packets-ticks: 1

**Comment by vdl19** [comment]
> This bug is also reproducible in OriginRealms server and will be reproducible with any other custom emotes system that will be released by other developers. I can't fix this bug in any way because it's how the emotes system works.
> 
> This bug happens if you have more than 1 player head of the same player in front of you. This doesn't happen if you have different player heads in front of you or if you have only 1 head in front of you.
> 
> I'll do my best to find a solution but I doubt this game allows me to identify placed heads in order to fix that.
> 
> The only way to fix this is to disable emotes system in `config.yml` of ItemsAdder.
> 
> Thanks for your patience.

Hi, I tried disabling emote in config.yml as a solution but it didn't change anything.

entities:
max-furniture-vehicles-per-chunk: 30
allow-removing-old-furnitures_2_3_11: false
custom-entitites:
enabled: true
emotes: false
interval-rendering-packets-ticks: 1

**Comment by vdl19** [comment]
Hi, great version 3.1.4 corrects the functioning of emotes well I was able to put "emotes: false" and I no longer have a bug with the Heads. Thank you

**Comment by xPhantoMTVx** [comment]
![image](https://user-images.githubusercontent.com/44167558/170069963-bc434cff-df7e-47b7-9ff2-fc655494bd71.png)
Maybe this is a problem?
Heads are storing some ID's which plugin addon might be understanding as separate heads?

There's always 4 patterns
![image](https://user-images.githubusercontent.com/44167558/170070817-1e191df5-c9e5-409e-a608-baa85b3aa54d.png)

That's just my suggestion - idk if am i correct.

**Comment by LoneDev6** [comment]
Thanks for trying but it's more complex than that.
These values have nothing to do with the bug.

Have a nice week
