### ISSUE TITLE
Border

### ISSUE THREAD

**Issue by 100petr** [PluginBugs/Issues-ItemsAdder#1608]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

pitilon#6950

### What happened?

On the server I have a bentobox with bskyblock and border and a worldborder api (https://www.spigotmc.org/resources/player-worldborder-api.67734/). If the player uses a vehicle (specifically, I tried wooden planes), he can get beyond the border on a skyblock. Yesterday I contacted the author of the worldborder api, who wrote that this is a matter for the plugin itself. Which I don't want the player to get beyond that border on the skyblock.

### Steps to reproduce the issue

Install bentobox, bskyblock, border, worldborder api (+ia and lonelibs)
Try to fly across the border with a wooden plane

### Server version

Current: git-Purpur-1609 (MC: 1.18.2)*
Previous: git-Purpur-1607 (MC: 1.18.2)
* You are running the latest version

### ItemsAdder Version

3.1.0c

### ProtocolLib Version

4.8.0-SNAPSHOT-b538

### LoneLibs Version

1.0.18

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/29830635/162602163-90a68294-e1d6-42db-a6b5-d4164dab0c63.png)

**Comment by LoneDev6** [comment]
So basically any hacked client can bypass this?
I think ysl3000 must add a serverside check for that, not me

**Comment by 100petr** [comment]
no, any normal client. in a few hours I will send him your answer with a link to the issue, so that any communication is faster

**Comment by LoneDev6** [comment]
You didn't understand.
This dev is saying that I must add my own check to prevent people to bypass the clientside world border.
I can't add this check because I don't have any idea of where the border finishes.

> So basically any hacked client can bypass this?
I think ysl3000 must add a serverside check for that, not me

This sentence means that any custom hacked client can bypass the border, so this dev must add a serverside check too.
It's not just an ItemsAdder issue, any hacked client or any normal client + another vehicles plugin can bypass the border.

**Comment by 100petr** [comment]
I attached a link to the issue, but I still got the answer in a conversation on a spigot:
![image](https://user-images.githubusercontent.com/29830635/162797934-48ffeec1-e372-4e46-9a53-61b266773bf2.png)

**Comment by LoneDev6** [comment]
I still don't get how am I supposed to fix that
