### ISSUE TITLE
Custom blocks of leaves (Trees expansion)

### ISSUE THREAD

**Issue by TeiBri** [PluginBugs/Issues-ItemsAdder#1610]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Block of leaves with custom texture can be realized using distance. I think there are seven types of leaves in the game + 1 - 7 distances (I think :D)
That would involve changing the generation of leaves in the world. Each type of leaf should have only 1 distance allowed.

### Is your feature request related to a problem?

No, its only good feature. :D

### Describe alternatives you've considered

...

### Additional context

You can see this on play.originrealms.com server :-)

There is minecraft:oak_leaves, **distance=7** (Default texture)
![2022-04-10_15 40 53](https://user-images.githubusercontent.com/62265168/162621111-cfa05f37-9e21-4ff1-b053-f42e4e29ca96.png)

And there is minecraft:azaela_leaves, **DISTANCE=4!** (Custom texture)
![2022-04-10_15 40 37](https://user-images.githubusercontent.com/62265168/162621144-a9afac12-1d7b-4b5f-b110-95c75fdc0e96.png)

*There can be saplings with custom texture too...
minecraft:jungle_sapling, **STAGE=1!** But this is for another feature I think :-)
![2022-04-10_15 47 33](https://user-images.githubusercontent.com/62265168/162621308-f1b32942-f715-45b5-abf7-b5299c50e02e.png)

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1522
