### ISSUE TITLE
Leather Armor overlay messed up

### ISSUE THREAD

**Issue by Truongvv10** [PluginBugs/Issues-ItemsAdder#1615]
### Discord tag (optional)

Wassabi#0317

### What happened?

I was trying to use to custom armor feature. But after implemented them I realised that leather armor looked totally different from how vanilla leather armor looks like. Basically what I was expecting was that using custom armor feature, leather armor would still look like how it always has in vanilla. 

### **Leather armor with optifine and resource pack looks much darker in color**
![unknown2](https://user-images.githubusercontent.com/67742370/162730006-dd1bf2b0-08e4-488d-93cc-56883183b790.png)

### **Leather armor using vanilla and resource pack has a weird overlay and not the normal leather one**
![unknown3](https://user-images.githubusercontent.com/67742370/162730108-8800cf61-8363-4b03-bda1-2c052427083e.png)

**And how it really should look like while using custom armor feature in vanilla or optifine:**
![unknown](https://user-images.githubusercontent.com/67742370/162730150-8afcb27c-e2d5-45fb-896a-b9939161e47e.png)

**NOTE**: Custom armor works, just leather overlay is messed up with colors or weird overlay.

### Steps to reproduce the issue

1. Go to config
2. Enable **vanilla_1_17** and **optifine** 
3. Enable **disable-overwrite-leather-armor-layers-textures**

### Server version

![image](https://user-images.githubusercontent.com/67742370/162730605-44d325d9-1a38-4ec9-878e-289aa080f598.png)

### ItemsAdder Version

![image](https://user-images.githubusercontent.com/67742370/162730639-84a748be-2f0a-4ce5-9440-052d9e3d39e7.png)

### ProtocolLib Version

![image](https://user-images.githubusercontent.com/67742370/162730662-2b7fb3db-38cd-46d5-831c-cc14974600dc.png)

### LoneLibs Version

![image](https://user-images.githubusercontent.com/67742370/162730689-6ce3e81d-4da4-415a-aea8-e50b12875e13.png)

### LibsDisguises Version (optional)

![image](https://user-images.githubusercontent.com/67742370/162730804-11a8778e-85f4-4b9f-af99-3fbbe3d8be6e.png)

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/8463589/latest.log)

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: x.x.x.x
      pack-port: x
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: false
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: true
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    fix_transparent_noteblocks__disable-for-more-performance: true
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
    disable-overwrite-leather-armor-layers-textures: true
  items:
    CustomModelData-starting-value:
      ALL: 1
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-items: false
  extract-default-resources: false
blocks:
  light-api: false
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: false
    allow-any-item: false
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
  fix-liquids-flow: true
  fix-floating-blocks: true
items:
  fix-show-attack-and-damage-as-lore: false
  give_death_location_maps: false
  hide-custom-durability-lore: true
liquids:
  enabled: false
huds:
  enabled: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: true
    add-hover-suggestion: true
  command:
    enabled: false
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: false
  book:
    enabled: false
  anvil:
    enabled: false
  inventory-title:
    enabled: false
  tab-header-footer:
    enabled: false
  vault-prefix-suffix:
    enabled: false
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: false
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: false
    anvil:
      enabled: true
    tab-header-footer:
      enabled: false
entities:
  max-furniture-vehicles-per-chunk: 32
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    interval-rendering-packets-ticks: 1
    emotes: true
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: false
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
  fix-packet-too-large-kick: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

![yes1](https://user-images.githubusercontent.com/67742370/162731230-438d8827-ed87-4f66-8fec-cc29fc1c5ac4.png)
![yes2](https://user-images.githubusercontent.com/67742370/162731232-0cfb5bdb-a108-4c62-b41f-db1b6bfcab1e.png)
![yes3](https://user-images.githubusercontent.com/67742370/162731234-12832b86-6335-439c-a7b7-4df9af3d3755.png)

**Comment by LoneDev6** [comment]
Notes:
probably the issue is here

Current
![image](https://user-images.githubusercontent.com/27242001/173795264-420b88e2-3d1d-4bb8-8c85-4c1fe2b7afa3.png)

Probable fix
![image](https://user-images.githubusercontent.com/27242001/173795289-d723c259-ed17-4a31-bc2d-5dfb4193e73f.png)

**Comment by LoneDev6** [comment]
In the next update you will be able to set [this option](https://itemsadder.devs.beer/faq/armors-bugs/leather-armor-texture-overwritten) in config.yml of ItemsAdder, then run `/iazip` again.
`disable-overwrite-leather-armor-layers-textures: true`

Note: if you enable the option and create a custom armor using ItemsAdder and you don't manually make a texture for the armor it will be shown as the leather vanilla armor.
This won't happen if you use Optifine tho. It will happen only on vanilla Minecraft.
