### ISSUE TITLE
Use custom entity as furniture for server owner decorate their spawn / building

### ISSUE THREAD

**Issue by ChrisRak** [PluginBugs/Issues-ItemsAdder#1621]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

! LmaoLoop !#6840

### Describe the solution you'd like

add advance entity as a furniture type . and we can make some cool decoration for spawn building .

### Is your feature request related to a problem?

i think if it is server owner / admin use only will be ok .

### Describe alternatives you've considered

i think no , model engine have no furniture feature

**Comment by LoneDev6** [comment]
You can already do that with the entities system, just set movement speed to 0 and silent of the base mob and spawn it.
In the future I might add also a disable AI setting.

Anyway you could also use Citizens to make a no-ai mob with ItemsAdder skin on it.
