### ISSUE TITLE
Allow item_frame furniture to be rotated through events/actions

### ISSUE THREAD

**Issue by SenPr** [PluginBugs/Issues-ItemsAdder#1623]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

The furnitures placed on walls are pretty annoying to rotate. Sometimes it only rotate properly in one direction

Allowing players to rotate with right click or some sort of actions would improve this

### Is your feature request related to a problem?

Some models are intended to be used on walls, specifically with item frames, but the rotations with item_frame furniture are hard to work with, especially when its on walls. 

### Describe alternatives you've considered

I tried fixed_rotation, opposite_direction but those would kind of mess up things.

### Additional context

![image](https://user-images.githubusercontent.com/18487475/162958172-2a765d04-3703-4270-b568-0e165dd813e4.png)
Here is an image of a "furniture" that is intended to be placed facing up, but only one side is facing the correct way.

**Comment by patatoplugin** [comment]
cool，just like the true item-frame

**Comment by SenPr** [comment]
> cool，just like the true item-frame

right, but without the frames/item name appearing
Invisible item frames would be confusing for players and build with

Rotating furniture is similar to some other building games. Something along the lines of "Shift + Click" to rotate

**Comment by LoneDev6** [comment]
Can you please make a video of the issue you're facing?
Also, can you send me your configuration and model for that furniture?
Thanks

**Comment by SenPr** [comment]
Will be sending it on Discord.

**Comment by SenPr** [comment]
https://gyazo.com/40dcb5d7026d139e76af972dc71a7dc2
^
Short clip of what I'm trying to describe.

Sorry it couldnt be longer, my screen capture is acting up I'll upload a proper video when I can

**Comment by LoneDev6** [comment]
I'm thinking about a proper way to handle that.
The shift+click option seems a bit strange to me, or isn't?

**Comment by SenPr** [comment]
Its a suggestion. Plus it provides quick solution to what I described.

Not the cleanest tho I agree. But making a clean solution sounds like a pain considering the factors

**Comment by LoneDev6** [comment]
Yea I think it's the only solution considering the fact that we lack of any other specific player input.
Feel free to send me the files on Discord (I don't know your Discord tag).

**Comment by SenPr** [comment]
> 

I sent you some files on Discord through a ticket we opened from an earlier issue.

My tag is SayWut#9598

**Comment by SenPr** [comment]
So I looked through some stuff today, after a bit of a busy week.

You can get around my specific case, where the Axolotl is supposed to always facing up by directly changing it in the model, and setting fixed_rotation: true

So if anyone is getting this problem, I recommend popping in the .json and edit some values or blockbench to see the changes real time before changing.

**Comment by LoneDev6** [comment]
In the next update you will be able to shift-rightclick to rotate itemframes furniture
