### ISSUE TITLE
Prevent people who load material resource pack in the air from being judged to fly.

### ISSUE THREAD

**Issue by buchaosi** [PluginBugs/Issues-ItemsAdder#1624]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [ ] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Prevent people who load material resource pack in the air from being judged to fly.

### Is your feature request related to a problem?

After entering the password, my player will be sent to the place where he left the game last time, but the place where he left the game last time is just in the air, resulting in the player being judged as flying by anti cheating

### Describe alternatives you've considered

nothing

**Comment by buchaosi** [comment]
The previous version will not be judged, but I will be judged when I update to the latest version
The last old version I used was 2.5.5

**Comment by LoneDev6** [comment]
Did you check here? https://itemsadder.devs.beer/faq/kick-flight-on-join

**Comment by buchaosi** [comment]
> 你检查过这里吗？https://itemsadder.devs.beer/faq/kick-flight-on-join

I didn't test here
The language I use does not have this page
My language is Chinese
And it seems that many things are not written in the Chinese page

**Comment by LoneDev6** [comment]
The chinese wiki is outdated, I'm not chinese so I sadly can't update it.
You can try using google translate
