### ISSUE TITLE
is it possible to make gif-like emojis?

### ISSUE THREAD

**Issue by patatoplugin** [PluginBugs/Issues-ItemsAdder#1625]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

I know how to make a anim-sword just like your firesword .
So I want to make a emoji  like gif.
But seems can't work and I can't find anything about this in the Wiki.

If the plugin can do this,pls add how to do it in WIKI
If not,Can you make this true?

### Is your feature request related to a problem?

no

### Describe alternatives you've considered

no

### Additional context

no

**Comment by LoneDev6** [comment]
Sadly it's not possible for now but it's planned for the next updates.
It's not an easy task.


You should ask in on Discord, Github it's not a place to ask questions, I hope you understand, thanks!
Have a nice week
