### ISSUE TITLE
Model_ID Issue

### ISSUE THREAD

**Issue by RhinoCD** [PluginBugs/Issues-ItemsAdder#1635]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

Issue:

The Model ID i'm trying to set for Clown hat (Feather) is 1

The Model ID i'm trying to set for Clown helmet (Armor - Leather Helmet) is 1

There shouldn't be any issues with this, as its 2 different materials.

Due to this, its also not generating the model data 1 clown hat for feather, and is instead auto generating it as -1, which causes all feathers in the game to now look like the clown hat.

### Steps to reproduce the issue

  clown_hat:
    display_name: '&eClown Hat'
    permission: custom.clown_set
    resource:
      material: FEATHER
      generate: false
      model_id: 1
      model_path: item/models/cosmetic/hat/clown_hat
    behaviours:
      hat: true
      

  clown_helmet:
    display_name: '&eClown Helmet'
    permission: custom.clown_set
    resource:
      generate: false
      model_id: 1
      model_path: item/models/armor/clown_helmet
    specific_properties:
      armor:
        slot: head
        custom_armor: clown_set_armor

### Server version

14.04 20:14:21 [Server] INFO This server is running Paper version git-Paper-194 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 9567753)

### ItemsAdder Version

ItemsAdder version 3.1.1

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

Lonelibs version 1.0.18

### LightAPI Version (optional)

x

### LibsDisguises Version (optional)

x

### FULL server log

14.04 20:15:48 [Server] INFO lilPandaz issued server command: /iazip self
14.04 20:15:49 [Server] INFO [ItemsAdder] [Host] Started self-host webserver on port: 1548
14.04 20:15:49 [Server] ERROR [ItemsAdder] Cannot set model_id for item minecraft:clown_hat Another item is already using model_id 1 [minecraft:clown_helmet]
14.04 20:15:49 [Server] INFO [ItemsAdder] Loaded 15 items
14.04 20:15:49 [Server] INFO [ItemsAdder] Used 0/188 REAL block IDs
14.04 20:15:49 [Server] INFO [ItemsAdder] Used 0/750 REAL_NOTE block IDs
14.04 20:15:49 [Server] INFO [ItemsAdder] Used 0/63 REAL_TRANSPARENT block IDs
14.04 20:15:49 [Server] INFO [ItemsAdder] Used 0/127 REAL_WIRE block IDs
14.04 20:15:49 [Server] INFO [ItemsAdder] Used 0/14 FIRE block IDs
14.04 20:15:49 [Server] INFO [ItemsAdder] Used 568/6608 available max font_images
14.04 20:15:49 [Server] INFO [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.categories_view.font_image.name
14.04 20:15:49 [Server] INFO [ItemsAdder] [Init] Loaded 3 categories
14.04 20:15:49 [Server] INFO [ItemsAdder] [Init] Loaded 15 items and stuff in 72ms
14.04 20:15:49 [Server] INFO [ItemsAdder] Please don't use 'minecraft' as namespace...
14.04 20:15:49 [Server] INFO [ItemsAdder] Please don't use 'minecraft' as namespace...
14.04 20:15:49 [Server] INFO [ItemsAdder] Please don't use 'minecraft' as namespace...
14.04 20:15:49 [Server] INFO [ItemsAdder] Please don't use 'minecraft' as namespace...
14.04 20:15:49 [Server] INFO [ItemsAdder] Please don't use 'minecraft' as namespace...
14.04 20:15:49 [Server] INFO [ItemsAdder] Please don't use 'minecraft' as namespace...
14.04 20:15:49 [Server] INFO [ItemsAdder] Please don't use 'minecraft' as namespace...
14.04 20:15:49 [Server] INFO [ItemsAdder] Please don't use 'minecraft' as namespace...
14.04 20:15:49 [Server] INFO [ItemsAdder] Please don't use 'minecraft' as namespace...
14.04 20:15:49 [Server] INFO [ItemsAdder] Please don't use 'minecraft' as namespace...
14.04 20:15:49 [Server] INFO [ItemsAdder] Please don't use 'minecraft' as namespace...
14.04 20:15:49 [Server] INFO [ItemsAdder] Please don't use 'minecraft' as namespace...
14.04 20:15:49 [Server] INFO [ItemsAdder] Please don't use 'minecraft' as namespace...
14.04 20:15:49 [Server] INFO [ItemsAdder] Please don't use 'minecraft' as namespace...
14.04 20:15:49 [Server] INFO [ItemsAdder] Please don't use 'minecraft' as namespace...
14.04 20:15:49 [Server] INFO [ItemsAdder] [Pack] Extracting utility resource_pack assets from .jar
14.04 20:15:49 [Server] INFO [PlaceholderAPI] Successfully registered expansion: img [1.0.1]
14.04 20:15:49 [Server] INFO [PlaceholderAPI] Successfully registered expansion: iaplayerstat [1.0.1]
14.04 20:15:49 [Server] INFO [ItemsAdder] Reloading Citizens
14.04 20:15:49 [Server] INFO [ItemsAdder] [Pack] DONE extracting utility resource_pack assets from .jar
14.04 20:15:49 [Server] INFO [ItemsAdder] [OK] Your zip file will be protected from unzip (as set in config.yml)
14.04 20:15:49 [Server] INFO [ItemsAdder] [Pack] Compressing resource_pack ... 
14.04 20:15:49 [Server] INFO [ItemsAdder] [Pack] Resourcepack successfully compressed: /plugins/ItemsAdder/data/resource_pack/pack.zip
14.04 20:15:49 [Server] INFO [ItemsAdder] Applying pack to lilPandaz... 
14.04 20:15:49 [Server] INFO [ItemsAdder] Applied pack to lilPandaz

### Error (optional)

```shell
Error: [ItemsAdder] Cannot set model_id for item minecraft:clown_hat Another item is already using model_id 1 [minecraft:clown_helmet]
```

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: 51.81.59.254
      pack-port: 1548
    external-host:
      enabled: false
      url: https://www.dropbox.com/sh/qnerd0zhc9ym4yv/AAB-YmLrQj_5Ni0f1iQc6FNYa?dl=1
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    - bbmodel
    - iaentitymodel
  items:
    CustomModelData-starting-value:
      ALL: 1
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-items: false
  extract-default-resources: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: false
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: false
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    emotes: true
    interval-rendering-packets-ticks: 1
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
```

**Comment by LoneDev6** [comment]
As clearly reported in the log: `Please don't use 'minecraft' as namespace`.
This causes a lot of issues because of how the game works.
Use another namespace, make sure to read the tutorial: https://itemsadder.devs.beer/plugin-usage/adding-content/basic-concepts/namespace
