### ISSUE TITLE
API | Furniture events

### ISSUE THREAD

**Issue by dercraftnetwork** [PluginBugs/Issues-ItemsAdder#1646]
### Describe the solution you'd like

I would like to have FurniturePlaceEvent, FurnitureInteractEvent and FurnitureBreakEvent.

### Is your feature request related to a problem?

I am working on a plugin that interacts with ItemsAdder furniture, and I need a few features added in the ItemsAdder's API.

### Describe alternatives you've considered

Only alternative way I could think of is to listen for PlayerInteractEvent, and check if the interacted entity is furniture.. but this doesn't seem very reliable. Same for placing and breaking the furniture.

I also have a question. Does ItemsAdder ever respawn armor stands used for furniture? Because I would like to store some metadata to these armor stands.

**Comment by LoneDev6** [comment]
> I also have a question. Does ItemsAdder ever respawn armor stands used for furniture? Because I would like to store some metadata to these armor stands.

No, they are real entities and are spawned in the world, completely handled by Spigot

**Comment by LoneDev6** [comment]
These methods will be implemented into the API:
`FurnitureBreakEvent`
`FurnitureInteractEvent`
`FurniturePlaceEvent`

**Comment by LoneDev6** [comment]
Example code (register that listener in your plugin, obviously).
Write `testFurnitureApi` in chat in order to enable/disable the cancellation of these events, for testing purposes.
```Java
import dev.lone.itemsadder.api.Events.FurnitureBreakEvent;
import dev.lone.itemsadder.api.Events.FurnitureInteractEvent;
import dev.lone.itemsadder.api.Events.FurniturePlaceEvent;
import org.bukkit.ChatColor;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.AsyncPlayerChatEvent;

public class TestFurnitureEvents implements Listener
{
    private boolean cancelTest;

    @EventHandler
    private void onFurnitureInteractEvent(FurnitureInteractEvent e)
    {
        System.out.println(e.getClass().getName() + e.getPlayer() + " " + e.getFurniture().getArmorstand().getType() + " " + e.getNamespacedID());
        if(cancelTest)
        {
            e.setCancelled(true);
            System.out.println("Cancelled " + e.getClass().getName());
        }
    }

    @EventHandler
    private void onFurnitureBreakEvent(FurnitureBreakEvent e)
    {
        System.out.println(e.getClass().getName() + e.getPlayer() + " " + e.getFurniture().getArmorstand().getType() + " " + e.getNamespacedID());
        if(cancelTest)
        {
            e.setCancelled(true);
            System.out.println("Cancelled " + e.getClass().getName());
        }
    }

    @EventHandler
    private void onFurnitureBreakEvent(FurniturePlaceEvent e)
    {
        System.out.println(e.getClass().getName() + e.getPlayer() + " " + " " + e.getNamespacedID());
        if(cancelTest)
        {
            e.setCancelled(true);
            System.out.println("Cancelled " + e.getClass().getName());
        }
    }

    @EventHandler
    private void onChat(AsyncPlayerChatEvent e)
    {
        String message = e.getMessage();
        message = ChatColor.stripColor(message);

        if(message.equals("testFurnitureApi"))
        {
            cancelTest = !cancelTest;
        }
    }
}
```
