### ISSUE TITLE
Custom Biomes/Generation and DataPack support!

### ISSUE THREAD

**Issue by Zemenus** [PluginBugs/Issues-ItemsAdder#1648]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Zemen#0209

### Describe the solution you'd like

I'm probably not the first one (and not the last one) to ask this, but listen to me, I have couple solutions for the problem with world generation and IA together:

Just add the datapack compatibility with world populators and other stuff! We create our biome in datapack, and then when setting this biome inside world populator settings (like said in the wiki), the world populator will spawn in this biome (for now it's not working with biomes from datapacks). Or maybe even create new setting inside items adder like: Structures, and structure will have settings almost like world decorators, but the main one is in WHAT BIOME it should spawn, again, with datapack biome support.

### Is your feature request related to a problem?

Ok, so... IA supports only ONE plugin with custom generation, and it's not even on 1.18! (RWG) Even ORAXEN has 3 custom world generators and supports them! There is a problem with that! So, if IA could have custom world generation or something like that already IN IT - this gonna be awesome!

### Describe alternatives you've considered

2 Solution that you could use) Make a custom world generator inside IA. It's hard, even too hard. There must be settings like Structures, Biome name and other stuff, and I'm not even speaking about noise settings!

3 Solution that you could use) Add custom world generator trough the datapack! Ok, so, you need to implement all the features that datapacks have for generating a custom biomes and world generation, sooo... it's gonna work kinda like that:
  1. User creates new biome setting inside items_pack inside IA 
  2. User configuring this biome.yml (idk what name of the file user will make). Setting things like: mobs inside biome, structures, terrain settings and other things.
  3. Saves this
  4. And then after command or a server restart IA will generate datapack and inject it into world of the server

### Additional context

Imagine custom trees inside terralith biomes, or volcanic mushrooms ONLY inside volcanic biome of Terralith... *just for example*

**Comment by LoneDev6** [comment]
This is a very confusing feature request.
Basically you're asking me to implement datapacks support or implement more world generator plugins support.

# datapack support

Datapacks are limited and do not integrate well with Spigot, it's almost impossible to integrate ItemsAdder with datapacks.
What you can do is trying to use [ItemsAdderBlocksInjector](https://www.spigotmc.org/resources/itemsadderblocksinjector.102078/) and directly use the custom ItemsAdder blocks names in your datapack, but I'm not sure if it will work fine, not tested.
For example `iasurvival:ruby_block`

# world generator plugins

ItemsAdder has an open API and I help developer to integrate compatibility whenever I can.
