### ISSUE TITLE
Mimic integration broken by obfuscation

### ISSUE THREAD

**Issue by osipxd** [PluginBugs/Issues-ItemsAdder#1649]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

osipxd#1577

### What happened?

When I try to get items from ItemsAdder I get the following exception:
```
[Mimic] Error in ItemsRegistry 'ia' implemented via ItemsAdder v3.1.1. Please, report it to LoneDev.
java.lang.AbstractMethodError: Receiver class dev.lone.itemsadder.main.fB does not define or inherit an implementation of the resolved method 'java.lang.String getItemId(java.lang.Object)' of interface ru.endlesscode.mimic.items.BukkitItemsRegistry.
	at ru.endlesscode.mimic.items.WrappedItemsRegistry.getItemId(WrappedItemsRegistry.kt:26) ~[Mimic.jar:?]
	...
```
In `dev.lone.itemsadder.main.fB` I see that all its methods are obfuscated.

### Steps to reproduce the issue

0. Install Mimic 0.8.0
1. Take any item in hand
2. Execute command `/mimic items id`
3. See the error

### Environment

This server is running Paper version git-Paper-287 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: a9f252e)

- ItemsAdder Version: 3.1.1
- ProtocolLib Version: 4.8.0
- LoneLibs Version: 1.0.18
- Mimic Version: 0.8.0

**Comment by LoneDev6** [comment]
Thanks! 
Probably I refactored some of the packages and my obfuscation whitelist stopped matching.
I will fix it ASAP
