### ISSUE TITLE
[Suggestion] Add compatibility with Logblock or CoreProtect

### ISSUE THREAD

**Issue by alejandro0256** [PluginBugs/Issues-ItemsAdder#165]
Add compatibility with Logblock or CoreProtect, It would be very useful for moderating to have logs of all the items and blocks of the plugin

**Comment by nhanledev** [comment]
+1 for this

**Comment by evilsaloon** [comment]
+1! CoreProtect is probably the most useful admin plugin on my server

**Comment by LoneDev6** [comment]
Will be implemented.
It will also log blocks placed by API (although I have to benchmark if it could cause lag due to CoreProtect saving if API gets called by world generators and similar with a lot of blocks).

**Comment by LoneDev6** [comment]
Coreprotect support cannot be implemented as it doesn't offer any way to save custom data into the log.
It allows only vanilla blocks data: https://docs.coreprotect.net/api/version/v9/#logplacementstring-user-location-location-material-type-blockdata-blockdata
