### ISSUE TITLE
Mimic: New API implementation registering mechanism

### ISSUE THREAD

**Issue by osipxd** [PluginBugs/Issues-ItemsAdder#1650]
Hm. It looks like you've not migrated to the new mechanism of API imlementations registering. I see the following message on ItemsAdapter enable:

```
[Mimic] Service ru.endlesscode.mimic.items.BukkitItemsRegistry with id 'ia' registered in deprecated way.
Please ask the ItemsAdder authors (LoneDev) to migrate
to the new service registration API introduced in Mimic v0.7:
   https://github.com/EndlessCodeGroup/Mimic/releases/tag/v0.7
```

_Originally posted by @osipxd in https://github.com/PluginBugs/Issues-ItemsAdder/issues/1503#issuecomment-1101743625_

**Comment by osipxd** [comment]
Also, if you interested, in [Mimic 0.8.0](https://github.com/EndlessCodeGroup/Mimic/releases/tag/v0.8.0) I've added API to access player's inventory contents. So you can use it to get equipped items for RPGInventory instead of direct RPGInventory API usage.

**Comment by LoneDev6** [comment]
I already am registering it using the new method.
```Java
if (MimicApiLevel.checkApiLevel(1) || MimicApiLevel.checkApiLevel(2))
        {
            Bukkit.getServicesManager().register(BukkitItemsRegistry.class, new ItemsAdderItemsRegistryCreator(), plugin, ServicePriority.Normal);
        }
        else
        {
            Mimic mimic = Mimic.getInstance();
            mimic.registerItemsRegistry(new ItemsAdderItemsRegistryCreator(), MimicApiLevel.CURRENT, plugin);
        }
```

**Comment by osipxd** [comment]
Hm it think it should work:
```java
// Checks user have installed 0.7 or higher
if (MimicApiLevel.checkApiLevel(MimicApiLevel.VERSION_0_7))
{
    Mimic mimic = Mimic.getInstance();
    mimic.registerItemsRegistry(new ItemsAdderItemsRegistryCreator(), MimicApiLevel.CURRENT, plugin);
}
else
{
    Bukkit.getServicesManager().register(BukkitItemsRegistry.class, new ItemsAdderItemsRegistryCreator(), plugin, ServicePriority.Normal);
}
```

**Comment by osipxd** [comment]
Maybe I should rename this method? To something like `checkApiLevelAtLeast`?

**Comment by osipxd** [comment]
By the way, it should be safe to use constant `MimicApiLevel.VERSION_0_7` instead of numbers because it is constant and it will be inlined during compilation.

**Comment by LoneDev6** [comment]
I'm using integers because `VERSION_0_7` won't be available in each jar and would cause compile errors, if I recall I already tested and it wasn't inlined

**Comment by LoneDev6** [comment]
> Hm I think it should be corrected:
> 
> ```java
> // Checks user have installed 0.7 or higher
> if (MimicApiLevel.checkApiLevel(MimicApiLevel.VERSION_0_7))
> {
>     Mimic mimic = Mimic.getInstance();
>     mimic.registerItemsRegistry(new ItemsAdderItemsRegistryCreator(), MimicApiLevel.CURRENT, plugin);
> }
> else
> {
>     Bukkit.getServicesManager().register(BukkitItemsRegistry.class, new ItemsAdderItemsRegistryCreator(), plugin, ServicePriority.Normal);
> }
> ```
> 
> So `MimicApiLevel.checkApiLevel(1)` will always return `true`.

Yes I tested and it gets inlined, very good, I'll use the new code you shared.
Thanks
