### ISSUE TITLE
Anvil shows incorrect repair needed levels

### ISSUE THREAD

**Issue by Katalijst** [PluginBugs/Issues-ItemsAdder#1651]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Katalijst#0001

### What happened?

1. When you want to repair an item in anvil, it always ask you for 1lvl only, no matter how many times it has already been repaired
2. When you repair the item, if the slot of the item you used to repair contains more than the amount required to fix to 100%, it still consume all the items in the slot

### Steps to reproduce the issue

Create a custom item with durability
Set an anvil recipe to repair it
Damage the custom item
Use a stack of the ingredient in anvil to fix it
The whole stack is consumed
Damage the item again
Repair it, it still ask only 1 level

### Server version

This server is running Paper version git-Paper-250 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: a5be178)

### ItemsAdder Version

3.1.1

### ProtocolLib Version

4.8.0

### LoneLibs Version

1.0.18

### ItemsAdder config.yml

https://pastebin.com/vtKD1ZKK

### Problematic items yml configuration file (optional)

https://pastebin.com/WZQxhCUw

### Screenshots/Videos (you can drag and drop files or paste links)
https://youtu.be/aOhYTl1OaJI

**Comment by LoneDev6** [comment]
Please make a video

**Comment by Katalijst** [comment]
@LoneDev6 https://youtu.be/aOhYTl1OaJI

**Comment by LoneDev6** [comment]
A plugin is interfering with the anvil events.
Sadly I can't do really anything against this, this is a limitation of Spigot itself. If two plugins use the anvil events you surely will have this kind of issues.
You have to disable plugins and find out which one is the cause.
Someone reported me that CMI can cause similar problems.


Please let me know which plugin is causing this problem, thanks!

https://user-images.githubusercontent.com/27242001/164432525-f0479ad3-fe40-485a-990b-a38d3f1598f5.mp4

**Comment by Katalijst** [comment]
I think you may have misunderstood here are the problem better explained (slot 0 is the damaged item, slot 1 the material and slot 2 the result):
1. It consume the whole slot 1 instead of just the amount to repair the item to 100%, for example if my item is damaged at 20%, it should only consume one item in slot 1, event if I put a whole stack in slot 1
2. The xp cost doesnt increase each time you repair the item (with vanilla item, every time armor or tools are repaired, the minimum experience cost doubles), for that you could just save the number of time the item has been repaired in an nbt tag.

I've made another video which compare the behaviour of the anvil with vanilla item and custom item https://youtu.be/ydrOKxcvE2Y
You can contact me on discord if you want (Katalijst#0001), I've done custom item plugin before and I've had the same problems with anvil that I fixed

**Comment by Katalijst** [comment]
@LoneDev6 Please look my message above, this issue needs to be reopened

**Comment by LoneDev6** [comment]
Please read my message again and watch my video.
There is a plugin which is interfering with the ItemsAdder anvil event and it's completely disabling my logic.
In my video you can clearly see that the behaviour works fine (ignore the missing textures, I didn't load the resourcepack, these are custom items).

**Comment by Katalijst** [comment]
@LoneDev6 Look your video again, it doesnt show the cost to repair it a second time, which should be doubled from the first repair, btw I tried without any other plugin installed it still has the problem I said

**Comment by LoneDev6** [comment]
Thanks for the detailed info, I will fix this in the next update
