### ISSUE TITLE
Armor appears during an emote when switching hotbar slot

### ISSUE THREAD

**Issue by BookWyrm114** [PluginBugs/Issues-ItemsAdder#1658]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

![image](https://user-images.githubusercontent.com/79489385/164782320-d8daed95-592e-44a1-b3f9-2b5118f29990.png)

### Steps to reproduce the issue

start an emote and switch hotbar slots whilst it's playing

### Server version

Current: git-Purpur-1612 (MC: 1.18.2)*
* You are running the latest version

### ItemsAdder Version

3.1.2

### ProtocolLib Version

5.0.0-SNAPSHOT-b553

### LoneLibs Version

1.0.18

**Comment by LoneDev6** [comment]
Will be fixed, thanks
