### ISSUE TITLE
sometimes models will display facing backwards

### ISSUE THREAD

**Issue by BookWyrm114** [PluginBugs/Issues-ItemsAdder#1659]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

when walking sometimes the model of a custom enitity was facing the opposite direction

### Steps to reproduce the issue

play around with custom entities for a while

### Server version

Current: git-Purpur-1612 (MC: 1.18.2)*
* You are running the latest version

### ItemsAdder Version

3.1.2

### ProtocolLib Version

5.0.0-SNAPSHOT-b553

### LoneLibs Version

1.0.18

### Other files, you can drag and drop them here to upload. (optional)

Mythicmobs config:

NPC_1:
  Type: ZOMBIE
  Display: 'NPC'
  Health: 20
  Damage: 0
  Skills:
  - customentity{model=dragoncraft:buisiness_npc} @self ~onSpawn
  - customentity{play=attack} @self ~onAttack
  - customentity{play=hurt} @self ~onDamaged
  - customentity{play=death} @self ~onDeath
  Options:
    MovementSpeed: 0.12

.metadata file:
https://www.dropbox.com/s/5i925i89hpn5xbw/.metadata?dl=0

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1663
