### ISSUE TITLE
Custom Heads texture glitch

### ISSUE THREAD

**Issue by poityTMK** [PluginBugs/Issues-ItemsAdder#1662]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

!ｐｏｉｔｙ_ＴＭＫ#6586

### What happened?

Most of the custom heads are displayed as pictured, I have no idea what this is due to

### Steps to reproduce the issue

.

### Server version

Current: git-Purpur-1566 (MC: 1.18.1)*
Previous: git-Purpur-1565 (MC: 1.18.1)
* You are running the latest version

### ItemsAdder Version

Itemadder version 3.1.2

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

Lonelibs version 1.0.18

### Screenshots/Videos (you can drag and drop files or paste links)

![2022-04-24_20 47 33](https://user-images.githubusercontent.com/44748641/164992042-c302622d-a3f2-46ae-85a8-bb86428555f1.png)

**Comment by Tifffy** [comment]
I am also experiencing this issue and require help fixing it as its affecting heads for all players. Is there any progress?

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1606#issuecomment-1096293136
