### ISSUE TITLE
java.nio.file.AccessDeniedException

### ISSUE THREAD

**Issue by LucidAPs** [PluginBugs/Issues-ItemsAdder#1676]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Dinos#3904

### What happened?

Same as issue #1383
I am using Ubuntu 20.04 Java 17 and this is the error I am getting.
https://nekobin.com/rijikupoga

### Steps to reproduce the issue

I don't think this can be reproduced by everyone, it doesn't seem to effect everyone.

### Server version

Current: git-Purpur-1614 (MC: 1.18.2)*

### ItemsAdder Version

ItemsAdder version 3.1.2

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b553

### LoneLibs Version

LoneLibs version 1.0.18

### LightAPI Version (optional)

LightAPI version bukkit-5.2.0 (build SNAPSHOT)

### LibsDisguises Version (optional)

LibsDisguises version 10.0.28-SNAPSHOT

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/8598447/latest.log)

### ItemsAdder config.yml

```shell
metrics: false
update-checker: false
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: false
      server-ip: 127.0.0.1
      pack-port: 8163
    external-host:
      enabled: true
      url: https://drive.google.com/uc?export=view&id=1NdXPoT_SeLoWxcEtsnPoM-p6a82NKgJM
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: true
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    - bbmodel
    - iaentitymodel
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-items: true
  extract-default-resources: true
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: false
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: false
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    emotes: true
    interval-rendering-packets-ticks: 1
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
```

**Comment by LucidAPs** [comment]
This is what I am trying to add/create by the way
[data.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/8598543/data.zip)
.

**Comment by LucidAPs** [comment]
I think a basic requirement for reproducing this, is using Linus, using docker and using a panel with server containers (like most hosting companies). It was tested with ptero, running the commands in game or from console made no difference.

**Comment by LoneDev6** [comment]
The Spigot process probably doesn't have correct permissions to write into the ItemsAdder folder.
Check your FTP permissions

**Comment by LucidAPs** [comment]
Yes I can see that it doesn't have permission do that, ItemsAdder is the only plugin I faced this issue with. I know what is wrong, I don't know how to fix it if it is somehow on my end. I have a standard setup that many will have aswell. Like I said, going through DIscord I am not the only only facing this issue, with no actually step by step solution.

**Comment by LucidAPs** [comment]
![image](https://user-images.githubusercontent.com/42933023/166251797-a989eded-397a-4014-b18f-d8df731d5133.png)
![image](https://user-images.githubusercontent.com/42933023/166251834-08f8d629-6a63-491d-a01c-ed7aac311298.png)
![image](https://user-images.githubusercontent.com/42933023/166251875-49bc2d4e-f1ea-418f-950c-3db3ba93c1c6.png)
![image](https://user-images.githubusercontent.com/42933023/166251925-1d32170f-133f-4c29-9e04-e4f8fb498a58.png)
![image](https://user-images.githubusercontent.com/42933023/166251993-d8888b3e-e36e-407e-9263-0a23b76c15ae.png)

**Comment by LucidAPs** [comment]
@LoneDev6 Also anyone that gets this error and then restarts the server will no longer see this error, tricking people into thinking it got fixed but in reality the files will still not work properly, it just wont be reported in the console.

**Comment by LucidAPs** [comment]
Ohhh thanks for the info, yes that makes sense! I have added some users with the permission to delete files as false. I guess the java process gets confused and doesn't recognize which user is doing which action, that is strange. But it makes sense, although it's still strange that itemsadder is the only plugin with that issue, although no plugin i am using is doing similar operations that itemsadder is doing. Alright thank you LoneDev for helping me understand, I will be doing the configuring for itemsadded in my local server that doesn't have permission issues, and then upload the files to my production server.

**Comment by LoneDev6** [comment]
Don't worry about that, I'm here to help :D  

Let me know how it goes

**Comment by LoneDev6** [comment]
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/1652
