### ISSUE TITLE
Custom font images/emoji/guis can be sent via chat bridges like DiscordSrv

### ISSUE THREAD

**Issue by chrismwiggs** [PluginBugs/Issues-ItemsAdder#1678]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

chrismwiggs#4011

### What happened?

Let's say you have a custom ESC screen, using font images (as many of us do!). If you use a chat -> discord bridge plugin, like Discordsrv and send one of the unicode characters used (for example, , not sure if Github will render that or if it is just broken), it will send + render the font image in chat. 

It would be great to have a config option to disallow any of these characters from being sent via DiscordSRV. I know you can't prevent all unicode, but I imagine the unicode IA picks for font images is predictable (and obscure) so it should be something that can be filtered out and safely blocked. 

### Steps to reproduce the issue

- Install ItemsAdder
- Use addon like the Custom Escape Gui  (or other font images)
- Install DiscordSrv or similar
- Send unicode characters through Discord

### Server version

git-Purpur-1612 (MC: 1.18.2)*, although this would be version independent as far as I can tell. 

### ItemsAdder Version

 ItemsAdder version 3.1.2

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.18

### LightAPI Version (optional)

NA

### LibsDisguises Version (optional)

NA

### FULL server log

NA, this is not an error, but either a design flaw or limitation of how font images are handled.

### Error (optional)

```shell
NA
```

**Comment by LoneDev6** [comment]
Are these characters successfully sent in the server chat?
ItemsAdder checks for emojis permissions and avoids people from sending them if they don't have permission.

**Comment by chrismwiggs** [comment]
They do send successfully in the server chat. In theory, they're not being sent as the player, but as DiscordSRV itself. I suppose part of the mix here is also my chat plugin (VentureChat, where a filter could be added, I can ask them as well), but without a player attached to the message I assume the permission checks are totally bypassed here.

**Comment by LoneDev6** [comment]
So basically users send messages (containing special characters) on Discord and they get sent on the network, right?
You might ask DiscordSRV author if you can setup a rule to avoid special unicode characters from being sent via DiscordSRV.

**Comment by chrismwiggs** [comment]
That's right. They suggested to use their regex filter, which I will likely do. Probably easier than trying to have IA guess when to disallow them.

Thanks!
