### ISSUE TITLE
Secret passage

### ISSUE THREAD

**Issue by vdl19** [PluginBugs/Issues-ItemsAdder#1680]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Hello, I have an idea that comes from my son (ldl19) maybe more to make an addon.
He made me a map by installing a resource pack that he had just modified.

So if possible create a special "secret passage" addon:
- Propose wooden and iron doors, wooden and iron hatches, scaffolding that have textures of:
rock, earth, sand...

It is already possible to make secret passages by changing the minecraft resource pack but in this case the modified doors, hatches, etc. are for everyone, so the idea and proposed doors, hatches, scaffolding, more than IA would suggest.

Example with doors, hatches and scaffolding from Minecraft with just the textures changed :
![image](https://user-images.githubusercontent.com/80985545/166452109-7cb99624-fc92-465e-8bb9-26aa34d75a6e.png)

### Is your feature request related to a problem?

no, especially the desire to offer secret passages for Spawn secrets that players will have to look for, and perhaps make them available to players who want to hide the entrance to their secret base without having to block them with blocks

### Describe alternatives you've considered

As explained just before, change the texture of 1, 2 or 3 Minecraft items but this will change them for everyone

**Comment by LoneDev6** [comment]
Cool idea, you can make an addon easily
