### ISSUE TITLE
GUI: Misplaced Icons 3.1.3

### ISSUE THREAD

**Issue by vdl19** [PluginBugs/Issues-ItemsAdder#1683]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

The 3.1.3 update brings a problem in the GUI "/ia" see the screenshots below. I put back 3.1.2 no Bug, I put back 3.1.3 and the bug is there.

![image](https://user-images.githubusercontent.com/80985545/167174306-6691855a-61fc-454e-bf96-d7e916c4fe1a.png)

### Steps to reproduce the issue

1. I had 3.1.2
2. I installed 3.1.3 with server restart
3. redo /iazip
4. The bug happens in the GUI
(I put back 3.1.2 /iazip no bug, then put back 3.1.3 and /iazip and GUI bug)

### Server version

git-Paper-323 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 2515bc4)

### ItemsAdder Version

ItemsAdder version 3.1.3

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.18

### LightAPI Version (optional)

LightAPI version bukkit-5.2.0 (build SNAPSHOT)

### LibsDisguises Version (optional)

LibsDisguises version 10.0.28-SNAPSHOT

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/8642218/latest.log)

**Comment by BookWyrm114** [comment]
I am also experiencing this issue

**Comment by LoneDev6** [comment]
Yes I forgot to provide the new GUI texture.
[iafix_center_icon.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/8643270/iafix_center_icon.zip)

Extract this into the ItemsAdder folder (make a backup before)

**Comment by LoneDev6** [comment]
![no_recipe](https://user-images.githubusercontent.com/27242001/167207543-03a3f64f-214e-470e-98ed-151fd6d7ff7a.png)

**Comment by vdl19** [comment]
Hi, thanks I tried the fix but it didn't work. I went to see the modifications I saw that he added the "no_recipe.png" file but that in "ia_gui.yml" it was not configured with but with the old one, other settings have been fine changed but I think that only this setting is missing because I tried to put "no_recipe" instead of "crafting", the interface changes but a lot of things are missing and it is misplaced :

crafting_preview:
 no_recipe_font_image:
      name: "mcguis:crafting"


![image](https://user-images.githubusercontent.com/80985545/167245906-4ba7e369-6268-4f35-9b35-78876b448c7d.png)

**Comment by vdl19** [comment]
If I just change the name of the image to "no_recipe" using the "ia_gui.yml" file from the fix I get this, so it actually fixes for items with Craft but those without craft it I think there is a placement problem:

![image](https://user-images.githubusercontent.com/80985545/167246233-15adb9f8-dfd8-48e4-aea6-c6db33b011f2.png)
![image](https://user-images.githubusercontent.com/80985545/167246248-7cd67403-833b-4a20-9c89-5794573e0f30.png)


  crafting_preview:
    no_recipe_font_image:
      name: mcguis:no_recipe
      x_position_pixels: -8

**Comment by vdl19** [comment]
When I modified with "no_recipe" the items with craft on the other hand works as below, so there remains I think the items without craft as explained above:

![image](https://user-images.githubusercontent.com/80985545/167246373-808b8bf2-aa19-4b84-b849-7c9c60aecdf0.png)

**Comment by LoneDev6** [comment]
set `x_position_pixels: -16`

**Comment by vdl19** [comment]
Hi, super thank you I modified and it is perfect now.
