### ISSUE TITLE
Repairing Custom Armor on an anvil consumes the entire stack

### ISSUE THREAD

**Issue by jmalloy125** [PluginBugs/Issues-ItemsAdder#1684]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Kaur#2728

### What happened?

Repair custom textured armor/items on an anvil consumes the entire stack of repair material.

Ex: Emerald chain helmet at 95% durability.  Place entire stack of emerald in anvil with chain helmet.  Repair the item.  All 64 emeralds are consumed.

### Steps to reproduce the issue

1. Create an armor with a custom texture, add a repair recipe to it.  My code is below
2. `info:
  namespace: server
armors_rendering:
  emerald_chain:
    color: "#d60002"
    layer_1: armor/emerald_chain/layer1
    layer_2: armor/emerald_chain/layer2
    use_color: false
    
recipes:
  anvil_repair:
      emerald_chain_helm:
          permission: repair
          ingredient: EMERALD
          item: server:emerald_chain_helm
      emerald_chest:
          permission: repair
          ingredient: EMERALD
          item: server:emerald_chest
      emerald_legs:
          permission: repair
          ingredient: EMERALD
          item: server:emerald_legs
      emerald_boots:
          permission: repair
          ingredient: EMERALD
          item: server:emerald_boots
          
items:
  emerald_chain_helm:
    display_name: "Emerald Chain Helm"
    permission: server.emerald_chain
    resource:
      generate: true
      textures:
      - item/emerald_chain/helm
    durability:
      max_custom_durability: 165
    specific_properties:
      armor:
        slot: head
        custom_armor: emerald_chain
    attribute_modifiers:
      head:
        armor: 2
        armorToughness: 1
  emerald_chest:
    display_name: "Emerald Chain Shirt"
    permission: server.emerald_chain
    resource:
      generate: true
      textures:
      - item/emerald_chain/chest
    durability:
      max_custom_durability: 240
    specific_properties:
      armor:
        slot: chest
        custom_armor: emerald_chain
    attribute_modifiers:
      chest:
        armor: 6
        armorToughness: 1
  emerald_legs:
    display_name: "Emerald Chain Legs"
    permission: server.emerald_chain
    resource:
      generate: true
      textures:
      - item/emerald_chain/legs
    durability:
      max_custom_durability: 225
    specific_properties:
      armor:
        slot: legs
        custom_armor: emerald_chain
    attribute_modifiers:
      legs:
        armor: 5
        armorToughness: 1
  emerald_boots:
    display_name: "Emerald Chain Boots"
    permission: server.emerald_chain
    resource:
      generate: true
      textures:
      - item/emerald_chain/boots
    durability:
      max_custom_durability: 195
    specific_properties:
      armor:
        slot: feet
        custom_armor: emerald_chain
    attribute_modifiers:
      feet:
        armor: 2
        armorToughness: 1`

3. Obtain item in-game
4. Repair items on an anvil after they are damaged, but use more than one emerald/repair material.  It consumes the entire stack of items.

### Server version

This server is running Paper version git-Paper-323 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 2515bc4)
You are 3 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Purpur-1612 (MC: 1.18.2)

### ItemsAdder Version

ItemsAdder version 3.1.3

### ProtocolLib Version

ProtocolLib Version 5.0.0-SNAPSHOT-b553

### LoneLibs Version

Lonelibs version 1.0.18

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/8645626/latest.log)

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: 155.94.186.139
      pack-port: 25570
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: true
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    - bbmodel
    - iaentitymodel
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-items: false
  extract-default-resources: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: false
liquids:
  enabled: false
huds:
  enabled: false
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: false
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: false
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    emotes: true
    interval-rendering-packets-ticks: 1
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: true
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
```

### Other files, you can drag and drop them here to upload. (optional)

My items and resource pack folder

[server143780 - 7 May 2022 10_9_38.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/8645628/server143780.-.7.May.2022.10_9_38.zip)

**Comment by LoneDev6** [comment]
Will be fixed, thanks!
