### ISSUE TITLE
error display in the editor

### ISSUE THREAD

**Issue by strifeslider** [PluginBugs/Issues-ItemsAdder#1685]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

greenelte

### Describe the solution you'd like

прошу добавить отображение ошибки в онлайн редакторе. armors_rendering: более 1 сета брони используют одинаковый цвет

### Is your feature request related to a problem?

.

### Describe alternatives you've considered

.

**Comment by LoneDev6** [comment]
Sorry I don't speak russian, please write in english and provide screenshots.
Thanks!
