### ISSUE TITLE
Heads BUG with Resource Pack IA

### ISSUE THREAD

**Issue by vdl19** [PluginBugs/Issues-ItemsAdder#1687]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

Hi, for some time I have Heads on my servers which display bugs.
When I put them on they can be completely broken texture level or normal but often buggy (see image 1 and 2), if I remove them and put them back either it's the same or sometimes they are normal, if I move around sometimes the texture comes back but others are corrupt too and it varies. If I replace one sometimes the others around change become good or bad.

This morning when I tested other resource packs and I had deactivated the IA one, no more bugs, I completely set 0 IA, 1st start without resource pack configure = heads OK (image 3), resource pack configuration and restart and there BUG of the heads.

I thought it was the heads plugin's fault some time ago so a few days ago I changed to Skull instead of Customhead but it didn't change anything. it does the same and even these plugins remove the bug from the serve

![image](https://user-images.githubusercontent.com/80985545/167377913-b50b7d30-d8db-4751-a82d-a6e98818ca39.png)

### Steps to reproduce the issue

1. Install and activate the AI ​​resource pack
2. Install a Heads plugin (I tested with "Custom Heads" and "Skull" it does the same and even these plugins remove the bug from the server)
3. put several Heads and the bugs start quickly (I tested especially with apples and bees but it works with other letters too, well a little all I think)

### Server version

Paper version git-Paper-330 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 268476b)

### ItemsAdder Version

 ItemsAdder version 3.1.3

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.18

### LightAPI Version (optional)

LightAPI version bukkit-5.2.0 (build SNAPSHOT)

### LibsDisguises Version (optional)

LibsDisguises version 10.0.28-SNAPSHOT

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/8650277/latest.log)

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1606#issuecomment-1096293136
