### ISSUE TITLE
display of attributes from itemadder in the lore of the mmoitems item

### ISSUE THREAD

**Issue by Diezel0468** [PluginBugs/Issues-ItemsAdder#1688]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Diezel0468#5581

### What happened?

After some update of the plugin or version of the game (I can’t find out for sure), new description lines in the lore of items from the mmoitems plugin began to be displayed. I found out that these lines belong to the itemadder plugin. They didn't exist before. I ask you to help solve this problem. they take up a lot of space in the lore, but I don't need them.
I must say right away that this setting does not help items:

  fix-show-attack-and-damage-as-lore: false

Lines to be removed:
they are in lang.yml

attribute-armor: '&9+{value} Armor'
attribute-toughness: '&9+{value} Armor Toughness'
attribute-attack-damage: ' &2{value} Attack Damage'
attribute-attack-speed: ' &2{value} Attack Speed'
attribute-when-in-main-hand: '&7When in Main Hand:'
attribute-when-in-off-hand: '&7When in Off Hand:'
attribute-when-on-body: '&7When on Body:'
attribute-when-on-feet: '&7When on Feet:'
attribute-when-on-head: '&7When on Head:'
attribute-when-on-legs: '&7When on Legs:'

### Steps to reproduce the issue

no steps

### Server version

Server: Purpur 1.18.2-R0.1-SNAPSHOT

### ItemsAdder Version

ItemsAdder_3.1.3

### ProtocolLib Version

Protocol 4.8.0

### LoneLibs Version

LoneLibs 1.0.18

### Screenshots/Videos (you can drag and drop files or paste links)

![Безымянный](https://user-images.githubusercontent.com/67608438/167454148-58ce32b5-9460-4642-9e56-c87d7bb6ef20.png)
I have them in Russian

**Comment by LoneDev6** [comment]
This setting must indeed work fine on latest versions of ItemsAdder:
`fix-show-attack-and-damage-as-lore: false`
