### ISSUE TITLE
Getting Kicked When Breaking Items Adder Ore

### ISSUE THREAD

**Issue by AliEmirPro** [PluginBugs/Issues-ItemsAdder#1701]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

By Cio#5293

### What happened?

When someone breaks items adder ore like bronze_ore they got kicked 
when i break them with gamemode 1 it doesnt kick

- BungeeCoord Server
- Spigot 1.16.5
- Items Adder 3.1.2
- Protocollib 4.8.0
- lone libs 1.0.18

This is the error i got on bungee consoloe
12:57:52 [WARNING] [AliEmirPro] <-> DownstreamBridge <-> [towny] - could not dec
ode packet! java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exce
eds writerIndex(1): UnpooledSlicedByteBuf(ridx: 1, widx: 1, cap: 1/1, unwrapped:
 PooledUnsafeDirectByteBuf(ridx: 2, widx: 2, cap: 128))
12:57:52 [INFO] [AliEmirPro] <-> DownstreamBridge <-> [towny] has disconnected
any help ?

### Steps to reproduce the issue

Play Game  break a ore (itemsadder ore) on gamemode 0
Get kicked

### Server version

Craftbukkit Version 3096a-Spigot-9fb885e-af1a232 MC 1.16.5  API 1.16.5-R0.1 SNAPSHOT

### ItemsAdder Version

- Items Adder 3.1.2

### ProtocolLib Version

- Protocollib 4.8.0

### LoneLibs Version

- lone libs 1.0.18

### FULL server log

k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 382, -523. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 382, -522. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 382, -521. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 382, -520. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 382, -519. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 382, -518. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 382, -517. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 382, -516. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 382, -515. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 383, -539. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 383, -538. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 383, -537. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 383, -536. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 383, -535. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 383, -534. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 383, -533. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 383, -532. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 383, -531. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 383, -530. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 383, -529. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 383, -528. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 383, -527. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 383, -526. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 383, -525. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 383, -524. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 383, -523. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 383, -522. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 383, -521. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 383, -520. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 383, -519. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 383, -518. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 383, -517. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 383, -516. Chun
k was already loaded: true
12:52:07 [WARNING] [ViaVersion] No light data found for chunk at 383, -515. Chun
k was already loaded: true
12:54:04 [WARNING] [ViaVersion] No light data found for chunk at 358, -528. Chun
k was already loaded: false
12:54:04 [WARNING] [ViaVersion] No light data found for chunk at 358, -530. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 358, -531. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 358, -516. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 358, -515. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 358, -533. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 358, -532. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 371, -527. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 370, -526. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 370, -527. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 371, -526. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 371, -528. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 372, -527. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 370, -528. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 372, -526. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 372, -528. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 369, -527. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 369, -526. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 371, -525. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 369, -525. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 370, -525. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 369, -528. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 372, -525. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 373, -529. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 372, -529. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 371, -529. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 373, -528. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 373, -527. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 373, -526. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 370, -529. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 369, -529. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 373, -525. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 369, -524. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 370, -524. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 371, -524. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 374, -528. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 374, -529. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 374, -530. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 373, -530. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 372, -530. Chun
k was already loaded: false
12:54:05 [WARNING] [ViaVersion] No light data found for chunk at 374, -527. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 374, -526. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 374, -525. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 368, -528. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 368, -527. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 368, -529. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 371, -530. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 370, -530. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 368, -526. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 372, -524. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 368, -525. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 373, -524. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 368, -524. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 370, -523. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 371, -523. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 372, -523. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 367, -525. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 369, -523. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 367, -524. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 368, -523. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 367, -523. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 369, -530. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 368, -530. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 374, -524. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 373, -523. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 368, -531. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 369, -531. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 370, -531. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 375, -524. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 375, -525. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 375, -526. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 371, -531. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 372, -531. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 373, -531. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 374, -531. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 367, -529. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 374, -523. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 375, -523. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 367, -528. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 375, -527. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 375, -529. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 375, -528. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 367, -527. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 375, -530. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 367, -526. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 375, -531. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 367, -530. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 370, -522. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 371, -522. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 372, -522. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 369, -522. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 368, -522. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 367, -522. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 367, -531. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 373, -532. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 372, -532. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 374, -532. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 370, -532. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 369, -532. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 368, -532. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 367, -532. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 366, -532. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 366, -531. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 366, -530. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 373, -522. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 375, -522. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 374, -522. Chun
k was already loaded: false
12:54:06 [WARNING] [ViaVersion] No light data found for chunk at 371, -532. Chun
k was already loaded: false
12:57:52 [WARNING] [AliEmirPro] <-> DownstreamBridge <-> [towny] - could not dec
ode packet! java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exce
eds writerIndex(1): UnpooledSlicedByteBuf(ridx: 1, widx: 1, cap: 1/1, unwrapped:
 PooledUnsafeDirectByteBuf(ridx: 2, widx: 2, cap: 128))
12:57:52 [INFO] [AliEmirPro] <-> DownstreamBridge <-> [towny] has disconnected
12:57:52 [INFO] [AliEmirPro] <-> ServerConnector [cakmalobi] has connected
12:57:58 [INFO] [AliEmirPro] <-> ServerConnector [lobby] has connected
12:57:58 [INFO] [AliEmirPro] <-> DownstreamBridge <-> [cakmalobi] has disconnect
ed
12:58:12 [INFO] [AliEmirPro] <-> ServerConnector [towny] has connected
12:58:12 [INFO] [AliEmirPro] <-> DownstreamBridge <-> [lobby] has disconnected
12:58:28 [INFO] [/154.21.212.235:34810] <-> InitialHandler has pinged
13:04:41 [INFO] [/51.15.244.103:58798] <-> InitialHandler has pinged
13:09:24 [INFO] [/207.244.236.144:57956] <-> InitialHandler has pinged
>

### Error (optional)

```shell
12:57:52 [WARNING] [AliEmirPro] <-> DownstreamBridge <-> [towny] - could not dec
ode packet! java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exce
eds writerIndex(1): UnpooledSlicedByteBuf(ridx: 1, widx: 1, cap: 1/1, unwrapped:
 PooledUnsafeDirectByteBuf(ridx: 2, widx: 2, cap: 128))
12:57:52 [INFO] [AliEmirPro] <-> DownstreamBridge <-> [towny] has disconnected
```

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: false
      server-ip: 127.0.0.1
      pack-port: 8163
    external-host:
      enabled: false
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: true
      url: ''
  apply-on-join: false
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: false
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      vanilla_1_17: false
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    - bbmodel
    - iaentitymodel
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-items: false
  extract-default-resources: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: false
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: false
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    emotes: true
    interval-rendering-packets-ticks: 1
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: false
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
```

**Comment by LoneDev6** [comment]
Make sure your are running the latest viaversion https://ci.viaversion.com/ and viabackwards if needed.
