### ISSUE TITLE
Making IA load before the plugin Iris Worldgen

### ISSUE THREAD

**Issue by RareMaker50** [PluginBugs/Issues-ItemsAdder#1706]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Bulletro#8515

### Describe the solution you'd like

Making it so that IA loads before the plugin Iris Worldgen,

I am currently trying to implement support for the 2 plugins since Iris is open source, and I made the default vanilla world to be generated and loaded by iris with a modified overworld config (replaced stone with ruby block)
when starting the server, iris creates/loads the world before IA loads its items and so the ruby block doesn't exist. So I want IA to load before the plugin so that the compatibillity will work.

### Is your feature request related to a problem?

The problem is there being no support for Iris Worldgen

### Describe alternatives you've considered

Trying RWG, which is outdated and not that great.

**Comment by LoneDev6** [comment]
https://itemsadder.devs.beer/compatibility-with-other-plugins/compatible/iris
