### ISSUE TITLE
Armor texture bug if "Custom cosmetic" + "armor pack with 112 or more armors"

### ISSUE THREAD

**Issue by vdl19** [PluginBugs/Issues-ItemsAdder#1714]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

I made an armor pack with more than 108 armors (now 140) and from there I had big problems with the armors of my pack but also with the default AI armors and the armors of the addons "More ItemsAdder minerals + custom armors" and "cosmetic_armors"".
All armor became black and those of the other 2 addons had a fixed color.
The bugs were sometimes worse, I had to restore my server at some point because even the reduction in the number of armor did not change anything, sometimes I also had the minecraft leather armor which also became black but not all the time after reducing armor count and attempting to repair.

- When I saw the problem the first thing I thought was that it came from my last armors added, I removed them (when I was at 108) and there no more bug, but problem as soon as I added a new one again the texture bug. I deleted the layers of various armor in my pack 1 only at a time to drop below the number that was causing the bug and it worked again each time!
- I then redid my pack from 0 by changing the names of folders, files etc. armor, but once you reach 108 > bug!

- I reset to 0 AI, then I put my armor pack by adding armor (140), no worries.
I then started to put back the addons that I use and there the bug came back when I put "cosmetic_armors", I deleted it no more bug, put back and bug again.
- so I submitted my complete IA file with the bug then I removed "cosmetic_armors" and there was no more bug!

So I don't understand the logic of the bug but it is there, I give the number of 108/112 armor before the bug arrives but this can vary depending on the addons we already have because it counts in the arrival of the bug (when I was at 108 with the bug I deleted the 2 files "emissive_1" "emissive_2" from "cosmetic_armors" and I no longer had the bug but as soon as an armor with its 4 pieces was added the bug is back so the link is really an armor count reached when "cosmetic_armors" is installed for the bug to start

![image](https://user-images.githubusercontent.com/80985545/168886781-ecb036ab-2937-431f-8df1-4f67a2d8b831.png)

I removed 2 layers of armor, I did not change the menu so there are indeed 108 armor displayed but there are actually 104 pieces of armor configured:
![image](https://user-images.githubusercontent.com/80985545/168886826-0c4eb90b-e96a-4f4f-85dd-ef119c8a4835.png)

I am attaching my armor pack with the 140 in it can be used for the test because if there is not enough armor there is no bug

### Steps to reproduce the issue

1. Installed AI
2. Installed an armor pack with 112 (armor pieces) see more in it, 112 may not have the right number it depends on the number already present me it was 108 (my pack with 140 will show the bug)
3. Installed the "cosmetic_armors" addon
4. /iazip
5. the armors of the pack will be displayed on the player in black, the Galaxy and Dark ruby ​​armors will no longer have their beautiful texture but a fixed color.

### Server version

Paper version git-Paper-336 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 73bd35d)

### ItemsAdder Version

ItemsAdder version 3.1.4b

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.18

### LightAPI Version (optional)

LightAPI version bukkit-5.2.0 (build SNAPSHOT)

### LibsDisguises Version (optional)

LibsDisguises version 10.0.28-SNAPSHOT

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/8710786/latest.log)

### Error (optional)

```shell
>.... [18:55:35 INFO]: [MythicMobs] Mythic has finished reloading!
>.... [18:55:35 WARN]: [ItemsAdder] §e##########################
>.... [18:55:35 WARN]: [ItemsAdder] §e
>.... [18:55:35 WARN]: [ItemsAdder] §e Warning
>.... [18:55:35 WARN]: [ItemsAdder] §e
>.... [18:55:35 WARN]: [ItemsAdder] §e##########################
>.... [18:55:35 WARN]: [ItemsAdder] §cWarning: the generated armors texture is too big 18944x512!
>.... [18:55:35 WARN]: [ItemsAdder] §cPlease use smaller armor textures.
>.... [18:55:35 WARN]: [ItemsAdder] §cMost graphics cards can't support very high sized textures.
>.... [18:55:35 WARN]: [ItemsAdder]
>.... [18:55:35 WARN]: [ItemsAdder]
>.... [18:55:35 WARN]: [ItemsAdder]
>.... [18:55:36 WARN]: [ItemsAdder] §e##########################
>.... [18:55:36 WARN]: [ItemsAdder] §e
>.... [18:55:36 WARN]: [ItemsAdder] §e Warning
>.... [18:55:36 WARN]: [ItemsAdder] §e
>.... [18:55:36 WARN]: [ItemsAdder] §e##########################
>.... [18:55:36 WARN]: [ItemsAdder] §cWarning: the generated armors texture is too big 18944x512!
>.... [18:55:36 WARN]: [ItemsAdder] §cPlease use smaller armor textures.
>.... [18:55:36 WARN]: [ItemsAdder] §cMost graphics cards can't support very high sized textures.
>.... [18:55:36 WARN]: [ItemsAdder]
>.... [18:55:36 WARN]: [ItemsAdder]
>.... [18:55:36 WARN]: [ItemsAdder]
>.... [18:55:37 INFO]: [ItemsAdder] [Pack] Extracting utility resource_pack assets from .jar
>.... [18:55:37 INFO]: [ItemsAdder] [Pack] DONE extracting utility resource_pack assets from .jar
```

### Other files, you can drag and drop them here to upload. (optional)

[armor_superpack.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/8710800/armor_superpack.zip)

### Screenshots/Videos (you can drag and drop files or paste links)

![Sans titre 1](https://user-images.githubusercontent.com/80985545/168889194-1d9a17ad-0116-48ed-9ab5-0ca598f466fa.png)

![Sans titre 4](https://user-images.githubusercontent.com/80985545/168889219-09ce429c-13db-425e-a713-a45f5528b40c.png)

![Sans titre 5](https://user-images.githubusercontent.com/80985545/168889239-b4b4e5bf-4220-4e5a-838b-7560fb4d4578.png)

**Comment by vdl19** [comment]
Accuracy, the warn:

>.... [18:55:36 WARN]: [ItemsAdder] §cWarning: the generated armors texture is too big 18944x512!

It is in the server console by doing /iazip when "cosmetic_armors" is installed afterwards and a fairly large armor pack is also in place.
But I didn't have it at the beginning of the problem, finally I had it at the beginning where I thought it was the fault of an armor that I had just put on but this message only happens if there is "cosmetic_armors" install in addition to armor pack

**Comment by vdl19** [comment]
Hi, so I had to delete "Custom cosmetic", there I just tried to integrate the galaxy armor into the dark_ruby pack.
I first copied and pasted the configuration of the dark_ruby then I modified the names dark_ruby by galaxy and set up the png, layer and emissive. Once done /iazip I have the warn as if I had set up the addon:

What I see since the last time I had not so many armors the definition has gone from 18944x512 to 24064x768, this may help to find the source of the problem.


>.... [10:57:52 INFO]: [MythicMobs] Mythic has finished reloading!
>.... [10:57:53 WARN]: [ItemsAdder] §e##########################
>.... [10:57:53 WARN]: [ItemsAdder] §e
>.... [10:57:53 WARN]: [ItemsAdder] §e Warning
>.... [10:57:53 WARN]: [ItemsAdder] §e
>.... [10:57:53 WARN]: [ItemsAdder] §e##########################
>.... [10:57:53 WARN]: [ItemsAdder] §cWarning: the generated armors texture is too big 24064x768!
>.... [10:57:53 WARN]: [ItemsAdder] §cPlease use smaller armor textures.
>.... [10:57:53 WARN]: [ItemsAdder] §cMost graphics cards can't support very high sized textures.
>.... [10:57:53 WARN]: [ItemsAdder]
>.... [10:57:53 WARN]: [ItemsAdder]
>.... [10:57:53 WARN]: [ItemsAdder]
>.... [10:57:54 WARN]: [ItemsAdder] §e##########################
>.... [10:57:54 WARN]: [ItemsAdder] §e
>.... [10:57:54 WARN]: [ItemsAdder] §e Warning
>.... [10:57:54 WARN]: [ItemsAdder] §e
>.... [10:57:54 WARN]: [ItemsAdder] §e##########################
>.... [10:57:54 WARN]: [ItemsAdder] §cWarning: the generated armors texture is too big 24064x768!
>.... [10:57:54 WARN]: [ItemsAdder] §cPlease use smaller armor textures.
>.... [10:57:54 WARN]: [ItemsAdder] §cMost graphics cards can't support very high sized textures.
>.... [10:57:54 WARN]: [ItemsAdder]
>.... [10:57:54 WARN]: [ItemsAdder]
>.... [10:57:54 WARN]: [ItemsAdder]
>.... [10:57:56 INFO]: [ItemsAdder] [Pack] Extracting utility resource_pack assets from .jar

![image](https://user-images.githubusercontent.com/80985545/169644196-ffb53944-924c-44f7-beee-2c0301e69a15.png)

**Comment by vdl19** [comment]
So I have another info related to the definition surely, if I remember correctly at one time during my attempts to create an armor pack I had a problem with an armor that I had taken from a pack which I seem to use optifine but it was not the real problem I think, the problem was that the .png was not 1 or 2 kb like the others but much more can be in the 60 kb but nothing sure but in anyway that's what made me tick so I removed the armor and put one with .png files of a size of 1 to 2 ko and no more worries.

![image](https://user-images.githubusercontent.com/80985545/169644918-df922666-4fd2-4ded-a475-74e9bd0de3f5.png)

**Comment by vdl19** [comment]
I continue the track in relation to the size of the .png so not just the problem with the "Galaxy" armor when there is too much armor.
So I replaced all the layers and emmisives of the galaxy armor with those of the Dark_ruby armor and redid /iazip and there were no more bugs. Of course the galaxy armor took on the appearance of the Dark_Ruby armor but everything works even the changing color effect.

![image](https://user-images.githubusercontent.com/80985545/169645111-1070ea16-0516-4158-92b3-9b7aea2e6627.png)

**Comment by vdl19** [comment]
So the problem comes from the definition of .png which generates a huge overall image, but that's up to you ;)
Otherwise I reduced the 4 .png of the Galaxy armor by 128 I put them in 16 and 32, for emissive_1 and 2 I was able to do it directly with my image editor, for layer_1 and 2 my editor refused to open them, I opened them with my image reader, made screenshots in 100% size, cropped etc. to then be able to reduce them to 16 and 32.
I therefore tested with the 16x and 32x models of armor and no more bugs on the armor.
I could see that the dark_ruby armor was 32x which explains why it works without problems with the others. The Galaxy armor I recall worked until I had 108/112 armor or more so the bug is not immediately visible if you do not add enough armor on AI.

I put you the zip file containing the reduced .PNGs that I tested that work with all the other armors.
[GALAXY 16 32 128 .zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/8747401/GALAXY.16.32.128.zip)

**Comment by vdl19** [comment]
To simplify the tests I made you the pack in 16x and 32x version directly:

[cosmetic_armors (16x).zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/8747418/cosmetic_armors.16x.zip)

[cosmetic_armors (32x).zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/8747419/cosmetic_armors.32x.zip)

**Comment by vdl19** [comment]
I just upgraded my armor pack to 236 pieces and I have them again the armors that were no longer showing on players.
So I went to see the size of layer_1 and 2 in armor.
The 7th had a layer_1 of 9.28 ko for a definition of 256x128, it seems to me to be in 256x but in black and white I suppose that's what makes its weight reduced. I join it.


![layer_1](https://user-images.githubusercontent.com/80985545/169662412-89572f24-60d0-4dc2-97c7-9140bd54007f.png)

![layer_2](https://user-images.githubusercontent.com/80985545/169662416-666bd4a1-d4af-4df3-968c-5baba4fc72af.png)

**Comment by vdl19** [comment]
on the other hand I did not have a warn in the console

**Comment by vdl19** [comment]
So as I had imagined a little higher it may well be the total size of the armor compared to their definition and/or their weight that the problem arises. By releasing the galaxy armor I therefore had something to do with new ones and when it just bugged again, I removed an armor that had worked without problems since 05/18, which therefore lightened up, but if I Had removed a number of normal armors it would have worked again like when I removed just 1 single armor when I had the bug at 108/112 it wasn't big at all and 16x the ones I removed.
So the problem seems to come from a limit in size Ko.. or in total definition as the Warn spoke about it

**Comment by vdl19** [comment]
One last message and I'll bother you more ;) so I put back the layer_1 and 2 and emisive-1 and 2 of "cosmetic armor" and so there we can see that the definition announced has still been inflated so it certainly adds up all the images of the armors seen that at the beginning towards 108 armors (pieces of armors) and cosmetic armor it gave 18944x512 then towards more than 140 I had 24064x768 and now with 240 I have 31744x768

>.... [20:55:22 WARN]: [ItemsAdder] §cWarning: the generated armors texture is too big 31744x768!

**Comment by vdl19** [comment]
Finally I bother you a little more there was one test left that I had thought of doing, it is with Optifine in addition that I do not use.

So there I stayed in the case where the armor bug with the Galaxy armor put back in place at its normal size:

1. Minecraft 1.18.2 + Optifine = I have the warning in the console on the definition + the AI ​​armor + armor of my pack no longer have a bug / on the other hand the Galaxy armor and Dark Ruby are not displayed not but good I have an error with Optifine I did not note.
![image](https://user-images.githubusercontent.com/80985545/169666215-7547d08b-6444-42e0-9c39-f67ebf2b1836.png)

2. I changed the PNG of the Galaxy armor and /iazip and I keep Optifine = I no longer have Warn in the console, the armors work except Galaxy and Darkruby but this must be related to the problem with Optifine
![image](https://user-images.githubusercontent.com/80985545/169666467-7aa18d81-99e9-43e3-aa31-350abd287680.png)

3. I restart Minecraft in 1.18.2 without Optifine and with the galaxy armor reduced and therefore without error in the console = everything works




4. I put the Galaxy PNGs back to default, I have the Warns in the console and the armors no longer work = Bug for all armors
![image](https://user-images.githubusercontent.com/80985545/169666579-e2db14b2-6e13-4e0f-a686-75b6c23b78ca.png)

Here I finally leave you

**Comment by LoneDev6** [comment]
I didn't read the whole issue report because it's huge, but the black texture is 99.9% caused by the texture size.
GPUs can't handle this kind of size, 100 hi-res armors will generate an huge armor texture, you can verify that by opening the resourcepack zip and extracting this file: `assets\minecraft\textures\models\armor\leather_layer_1.png`.

Each GPU has its own texture size limit and it's not detectable by the plugins, so I can do nothing against that sadly.

**Comment by vdl19** [comment]
> 
Hello, okay thank you. I was just thinking about a limitation without knowing where it could come from, on the discord I had also asked first if a limitation was known on the number of armors, but I was told that it didn't. There was no known limitation so I continued my research.
So that confirms my first thought, thank you

**Comment by LoneDev6** [comment]
It should be noted in the log, you should see a big warning about GPU limitations.
> Warning: the generated armors texture is too big 18944x512!
> Most graphics cards can't support very high sized textures.
