### ISSUE TITLE
Allow some bars such as thirst to be removed/added for CERTAIN players via command

### ISSUE THREAD

**Issue by ItzASecret** [PluginBugs/Issues-ItemsAdder#1715]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

ItzASecretBoi#1300

### Describe the solution you'd like

I'd like a command that can remove/add the bar from players. It may not seem useful, however in my server I have all players with the thirst bar and I'm making classes/roles right now and one of them are going to be a robot type and obviously robots dont drink water. I was thinking something like /iahud remove itemsadder:thirst remove {player} and /iahud add itemsadder:thirst. That way some players can have bars that other may not have/need and the commands can be assigned to other actions and plugins. As of right now if I wanna remove it I'd have to remove it from all players, which I dont wanna do.

### Is your feature request related to a problem?

No.

### Describe alternatives you've considered

None.

### Additional context

Thanks for reading!

**Comment by LoneDev6** [comment]
There is already a command: `/iahud realcraft:thirst_bar`

Have a nice day

**Comment by ItzASecret** [comment]
Well the problem is even if i can make the player not see the bar anymore, it still affects them if they are thirsty.

**Comment by ItzASecret** [comment]
I tested it and when the bar was low, and I disabled the bar via command the bar still damaged and gave slowness to the player

**Comment by ItzASecret** [comment]
Hello, firstly I am sorry for taking so long to answer you.

I want to be able to completely remove a particular hud or all huds for certain players preferably via command so that I can trigger it in other configs. I'd like this ability because I have roles/classes in my Minecraft server and certain classes/roles such as the robot one I'm making will not require water if I can remove them via command which as of now I cannot. If it seems pointless to you I'd understand.

**Comment by ItzASecret** [comment]
@LoneDev6
