### ISSUE TITLE
Allow us to create dyeable/paintable items (using tint w/ potions/leather horse armor/tipped arrows).

### ISSUE THREAD

**Issue by Zangerine** [PluginBugs/Issues-ItemsAdder#1717]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Zangerine#0001

### Describe the solution you'd like

Other plugins have the feature where if a model supports tint you are able to recolour the model. This is done by the model being either Leather Horse Armor, Potions or Tipped arrows. As these items are dyeable/tintable we are able to recolour models that have been designed for this. 

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

No alternatives

### Additional context

Another similar plugin to IA that has this feature is Oraxen. It's also something that big servers such as Origin Realms supports.

**Comment by Zangerine** [comment]
https://docs.oraxen.com/configuration/items-advanced/dyeable-items

I mean something like this. Nothing to do with leather armour. It's possible to have paintable/dyeable cosmetics. It's also present in the plugin Magic Cosmetics. I figured it would be nice to have this in ItemsAdder.

**Comment by LoneDev6** [comment]
You already can: https://ide.devs.beer/itemsadder/
```yml
    specific_properties:
      leather_horse_armor:
        color: GRAY
```

![immagine](https://user-images.githubusercontent.com/27242001/169895388-59ef7d31-8a3e-480c-9e35-b542158724d1.png)
