### ISSUE TITLE
Better block breaking

### ISSUE THREAD

**Issue by FivesBlue** [PluginBugs/Issues-ItemsAdder#1721]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Garfieldwxg55#3279

### Describe the solution you'd like

I'm making this feature request based on a suggestion I made on the LoneDev discord server which gained a few votes. It read:

"Right now as far as I can tell, specific tools are either blacklisted or whitelisted (you can mine the block with that specific tool or get a can't mine message), and you can't set a general preferred tool for a block (like setting a stone block to a pickaxe). What if it was possible to set preferred tools to a block, that will mine a block faster (like how any pickaxe will mine an ore faster), define specific tools that will trigger an event after mining the block (like mining an ore and getting an item), and still allowing the block to be mined by hand/another tool, but just not drop anything (like how you can mine an ore with your hand/shovel, but it won't drop anything), I feel like this would be a fantastic addition and would probably be possible"

Since it gained quite a few votes on the discord server, I thought I would post it here as a feature request. Any feedback or suggestions are greatly appreciated!

### Is your feature request related to a problem?

No, this is more of an improvement

### Describe alternatives you've considered

The only other way to achieve a similar result would probably have to be to use an addon of some sort, but I don't know of any addons like that that exist currently.

**Comment by LoneDev6** [comment]
I agree the system can be improved but I don't really understand this suggestion.
Right now you can already disable the actionbar message and let the ore disappear if a wrong tool is used:
check config.yml: `cancel-break-wrong-tool`

**Comment by Garfieldwxg55** [comment]
Ah sorry for not explaining well, what I meant is basically have the block breaking work exactly like vanilla, so like how you can break a diamond ore with any tool/your hand, but breaking with a Stone Pickaxe will be faster then by hand, even though neither drop anything. And of course if you mine with a Iron+ Pickaxe, then you get the loot. Sorry if I wasn't clear earlier, hope this explains it better :)

**Comment by LoneDev6** [comment]
Basically something like that:

```yml
per_tool_hardness:
  "*_axe": 4
  "*_pickaxe": 2
  "ultra_pickaxe": 1
```
`*` is a wildcard, so every item which has its name ending with `_axe` or `_pickaxe` would match the rule.

do you have any better idea for the config?
Thanks!

**Comment by BookWyrm114** [comment]
There's already plugin implementing something just like this: [Breaker 2](https://www.spigotmc.org/resources/breaker-2-configurable-breaking-speeds-1-16-1-18.99022/)
However it's not compatible with ItemsAdder custom blocks

**Comment by Garfieldwxg55** [comment]
Yeah, I think ideally Breaker 2 compatibility would be fantastic, but if that's not possible, the config option would probably work too. Do you know if it would be aligned with the vanilla breaking values? Thanks again

**Comment by LoneDev6** [comment]
Should be the same as this: https://github.com/PluginBugs/Issues-ItemsAdder/issues/1268#issuecomment-1387363694
