### ISSUE TITLE
Add a reverse(upside down) property for furniture 

### ISSUE THREAD

**Issue by patatoplugin** [PluginBugs/Issues-ItemsAdder#1727]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

neverlag#6619

### Describe the solution you'd like

If you make a 2 or 3 height furniture and using entity:item-frame.
You will can't see the furniture when you so close to it because you can't see the true item-frame

But if you make a revese(upside down) furniture, and put the item-frame under the highest barrier,you can see it.

Pic 1 is the normal mailbox made by item-fram
Pic 2 is when you close to the mailbox,and you will can't see it
Pic 3 is I revese it 
Pic 4 is I put the item-frame under the higheset barrier
![2022-05-26_15 27 47](https://user-images.githubusercontent.com/62246956/170442130-2d7e2b7d-fb63-44bf-9c42-cfdfdd0dac69.png)
![2022-05-26_15 27 51](https://user-images.githubusercontent.com/62246956/170442139-0dec0e73-2230-42a9-8e53-827269a44501.png)
![2022-05-26_15 42 14](https://user-images.githubusercontent.com/62246956/170442147-2c8fd5a7-8b2f-4986-818e-8b56c32f9cbf.png)
![2022-05-26_15 42 34](https://user-images.githubusercontent.com/62246956/170442152-f8dae886-801c-460c-a374-b98667239e82.png)

### Is your feature request related to a problem?

no, vannila mojang limit

### Describe alternatives you've considered

Add a furniture properties: 
revese: true

and the barrier should be revese

### Additional context

My English is not good ,if you can't understanding what I am say,pls tell me,I will try my best to explain my idea.

**Comment by patatoplugin** [comment]
Item-frame seem cant truely solve this problem,when you sight are too high,you can't see this furniture,either.
Maybe just use armorstand is better
![2022-05-26_15 57 40](https://user-images.githubusercontent.com/62246956/170444657-bf303faa-6377-4a1b-907d-cdf001806c97.png)

**Comment by LoneDev6** [comment]
Can you try to remove the solid attribute?

**Comment by patatoplugin** [comment]
> Can you try to remove the solid attribute? It's a clientside bug surely

set solid: false is same.
I think it is because you can't see the item frame,so you can't see the model
The big armorstand is 2 height,so it is better
