### ISSUE TITLE
Emotes bug

### ISSUE THREAD

**Issue by PystoyPlayer** [PluginBugs/Issues-ItemsAdder#1729]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Пустой#7677

### What happened?

If I turn on emotes in config and do /iazip, players and NPCs become without heads

### Steps to reproduce the issue

Update ItemsAdder from 2.5.5 to the latest
extract defaults
generate resourcepack 
done

### Server version

This server is running Purpur version git-Purpur-"08dd6c7" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 08dd6c7 on ver/1.17.1)
You are running the latest version

### ItemsAdder Version

ItemsAdder version 3.1.6
Customized Minecraft without client mods!
Website: devs.beer
Author: LoneDev

### ProtocolLib Version

ProtocolLib version 4.8.0
Provides read/write access to the Minecraft protocol.
Authors: dmulloy2 and comphenix

### LoneLibs Version

LoneLibs version 1.0.18
Collection of libs used by my plugins
Authors: LoneDev and others

### LightAPI Version (optional)

LightAPI version bukkit-5.1.0 (build SNAPSHOT)
Bukkit library for edit light levels
Website: https://github.com/BeYkeRYkt/LightAPI
Authors: BeYkeRYkt and other contributors in GitHub

### FULL server log

> [18:55:07] [main/INFO]: Environment: authHost='authserver.mojang.com', accountsHost='api.mojang.com', sessionHost='sessionserver.mojang.com', servicesHost='api.minecraftservices.com', name='PROD'
> [18:55:07] [main/INFO]: Reloading ResourceManager: Default, bukkit
> [18:55:08] [Worker-Main-1/INFO]: Loaded 7 recipes
> [18:55:10] [Server thread/INFO]: Starting minecraft server version 1.17.1
> [18:55:10] [Server thread/INFO]: Loading properties
> [18:55:10] [Server thread/INFO]: This server is running Purpur version git-Purpur-"08dd6c7" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 08dd6c7 on ver/1.17.1)
> [18:55:10] [Server thread/INFO]: Server Ping Player Sample Count: 12
> [18:55:10] [Server thread/INFO]: Using 4 threads for Netty based IO
> [18:55:10] [Server thread/INFO]: Default game type: SURVIVAL
> [18:55:10] [Server thread/INFO]: Generating keypair
> [18:55:11] [Server thread/INFO]: Starting Minecraft server on 0.0.0.0:hidden
> [18:55:11] [Server thread/INFO]: Using epoll channel type
> [18:55:11] [Server thread/INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
> [18:55:11] [Server thread/INFO]: Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
> [18:55:11] [Server thread/INFO]: [LuckPerms] Loading LuckPerms v5.3.86
> [18:55:11] [Server thread/INFO]: [LoneLibs] Loading LoneLibs v1.0.18
> [18:55:11] [Server thread/INFO]: [PlaceholderAPI] Loading PlaceholderAPI v2.11.0
> [18:55:11] [Server thread/INFO]: [LightAPI] Loading LightAPI vbukkit-5.1.0 (build SNAPSHOT)
> [18:55:12] [Server thread/INFO]: <LightAPI>: [INFO] Preparing LightAPI...
> [18:55:12] [Server thread/INFO]: <LightAPI>: [INFO] Preparing done!
> [18:55:12] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.8.0
> [18:55:13] [Server thread/INFO]: [ItemsAdder] Loading ItemsAdder v3.1.6
> [18:55:13] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
> [18:55:13] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v5.3.86
> [18:55:13] [Server thread/INFO]:         __    
> [18:55:13] [Server thread/INFO]:   |    |__)   LuckPerms v5.3.86
> [18:55:13] [Server thread/INFO]:   |___ |      Running on Bukkit - Purpur
> [18:55:13] [Server thread/INFO]: 
> [18:55:13] [Server thread/INFO]: [LuckPerms] Loading configuration...
> [18:55:13] [Server thread/INFO]: [LuckPerms] Loading storage provider... [H2]
> [18:55:14] [Server thread/INFO]: [LuckPerms] Loading internal permission managers...
> [18:55:14] [Server thread/INFO]: [LuckPerms] Performing initial data load...
> [18:55:14] [Server thread/INFO]: [LuckPerms] Successfully enabled. (took 1563ms)
> [18:55:14] [Server thread/INFO]: [LoneLibs] Enabling LoneLibs v1.0.18
> [18:55:14] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.8.0
> [18:55:14] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
> [18:55:14] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
> [18:55:14] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
> [18:55:14] [Server thread/WARN]: Whilst this makes it possible to use BungeeCord or Velocity, unless access to your server is properly restricted, it also opens up the ability for hackers to connect with any username they choose.
> [18:55:14] [Server thread/WARN]: Please see spigotmc.org for further information.
> [18:55:14] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
> [18:55:14] [Server thread/INFO]: Preparing level "cleanroom"
> [18:55:15] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
> [18:55:15] [Server thread/INFO]: Preparing spawn area: 0%
> [18:55:15] [Server thread/INFO]: Preparing spawn area: 0%
> [18:55:15] [Server thread/INFO]: Time elapsed: 694 ms
> [18:55:15] [Server thread/INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.11.0
> [18:55:16] [Server thread/INFO]: [PlaceholderAPI] Fetching available expansion information...
> [18:55:16] [Server thread/INFO]: [LightAPI] Enabling LightAPI vbukkit-5.1.0 (build SNAPSHOT)
> [18:55:16] [Server thread/INFO]: <LightAPI>: [INFO] Initializing LightAPI...
> [18:55:16] [Server thread/INFO]: <LightAPI>: [INFO] Handler initialization is done
> [18:55:16] [Server thread/INFO]: <LightAPI>: [INFO] Metrics is enabled!
> [18:55:16] [Server thread/INFO]: <LightAPI>: [INFO] LightAPI initialized!
> [18:55:16] [Server thread/INFO]: [ItemsAdder] Enabling ItemsAdder v3.1.6
> [18:55:16] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_17_R1! Trying to find NMS support
> [18:55:16] [Server thread/INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_17_R1' loaded!
> [18:55:16] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
> [18:55:16] [Server thread/INFO]: [ItemsAdder] 
>   ___  ___        __        __   __   ___  __      ItemsAdder 3.1.6
> |  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.18
> |  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Purpur git-Purpur-"08dd6c7" (MC: 1.17.1)
>                                                
> [18:55:17] [Server thread/INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
> [18:55:17] [Server thread/INFO]: Starting GS4 status listener
> [18:55:17] [Server thread/INFO]: Thread Query Listener started
> [18:55:17] [Server thread/INFO]: Running delayed init tasks
> [18:55:17] [Query Listener 1/INFO]: Query running on 0.0.0.0:hidden
> [18:55:17] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [ItemsAdder] [License] Product licensed to: Demilune (1450406)
> [18:55:19] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: server [2.6.1]
> [18:55:19] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: bungee [1.0.1]
> [18:55:19] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: player [2.0.2]
> [18:55:19] [Server thread/INFO]: 3 placeholder hook(s) registered! 1 placeholder hook(s) have an update available.
> [18:55:19] [Server thread/INFO]: Done (9.317s)! For help, type "help"
> [18:55:19] [Server thread/INFO]: Timings Reset
> [18:55:20] [Craft Scheduler Thread - 1 - ItemsAdder/INFO]: [ItemsAdder] Loaded 484 items
> [18:55:20] [Craft Scheduler Thread - 1 - ItemsAdder/INFO]: [ItemsAdder] Used 0/188 REAL block IDs
> [18:55:20] [Craft Scheduler Thread - 1 - ItemsAdder/INFO]: [ItemsAdder] Used 28/750 REAL_NOTE block IDs
> [18:55:20] [Craft Scheduler Thread - 1 - ItemsAdder/INFO]: [ItemsAdder] Used 0/63 REAL_TRANSPARENT block IDs
> [18:55:20] [Craft Scheduler Thread - 1 - ItemsAdder/INFO]: [ItemsAdder] Used 0/127 REAL_WIRE block IDs
> [18:55:20] [Craft Scheduler Thread - 1 - ItemsAdder/INFO]: [ItemsAdder] Used 0/14 FIRE block IDs
> [18:55:20] [Craft Scheduler Thread - 1 - ItemsAdder/INFO]: [ItemsAdder] Used 569/6608 available max font_images
> [18:55:20] [Craft Scheduler Thread - 1 - ItemsAdder/INFO]: [ItemsAdder] [Init] Loaded 40 categories
> [18:55:20] [Craft Scheduler Thread - 1 - ItemsAdder/INFO]: [ItemsAdder] [Init] Loaded 484 items and stuff in 3216ms
> [18:55:20] [Craft Scheduler Thread - 1 - ItemsAdder/INFO]: [ItemsAdder] [Pack] Checking resourcepack url... 
> [18:55:20] [Craft Scheduler Thread - 6 - ItemsAdder/INFO]: [ItemsAdder] [Pack] Resourcepack URL (self-host): hidden/pack.zip
> [18:55:20] [Server thread/ERROR]: (org.bukkit.craftbukkit.v1_17_R1.legacy.CraftLegacy:259) Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
> [18:55:29] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: img [1.0.1]
> [18:55:29] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: iaplayerstat [1.0.1]

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: hidden
      pack-port: hidden
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    - bbmodel
    - iaentitymodel
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-items: false
  extract-default-resources: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: false
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: false
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    emotes: true
    interval-rendering-packets-ticks: 1
    optimized-packets: false
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

NPC:
![Screenshot_2022-05-24_at_6_PM_22x](https://user-images.githubusercontent.com/88878911/170563253-748fdbb3-251c-480d-bd95-5625362095fc.png)

F5:
![Screenshot_2022-05-24_at_6_PM2x](https://user-images.githubusercontent.com/88878911/170563262-71a5c7f6-45bd-4717-8c3c-28f73bf3c0be.png)

Without SkinsRestorer plugin etc. I also reset all ItemsAdder files there:
![Screenshot_2022-05-27_at_6_PM2x](https://user-images.githubusercontent.com/88878911/170743732-50779b0a-fd9a-4d63-be12-9db377f6a9c5.png)

`online-mode: false`
I think that's the reason of the bug

**Comment by PystoyPlayer** [comment]
online-mode: false

I think that's the reason of the bug

**Comment by LoneDev6** [comment]
Can you ask another player to test?
Can you also try without client mods?

Thanks

**Comment by PystoyPlayer** [comment]
> Can you ask another player to test? Can you also try without client mods?
> 
> Thanks

I asked my subscribers to test it, and now I'm sure that it's just a cracked client problem. If you have a Minecraft licence, everything is fine (even with mods), but if you join without the licence, heads disappear.

**Comment by LoneDev6** [comment]
Which cracked client are they using?
Can they try another cracked client?

**Comment by PystoyPlayer** [comment]
> Which cracked client are they using?
> Can they try another cracked client?

They're using licenced minecraft launcher - everything is fine

**Comment by PystoyPlayer** [comment]
but if I join from TLaucher Legacy etc. (cracked minecraft) - no heads

**Comment by PystoyPlayer** [comment]
I see that you've already closed my issue, but I would like to add some information:
1) I tried many times
2) I deleted ALL plugins
3) I deleted ALL mods (even without OptiFine sometimes)
4) I tried other minecraft clients
5) To fix the issue everyone should buy Minecraft license
