### ISSUE TITLE
new methods for the api of custom entities.

### ISSUE THREAD

**Issue by FrancoBM12** [PluginBugs/Issues-ItemsAdder#1731]
### Discord tag (optional)

FrancoBM#2980

### Describe the solution you'd like

I described it to LoneDev before and he told me to suggest it here.

First of all I ask this for the benefit of both other developers using the api and myself as I will be using it in 2 of my plugins one already released and one soon to be released.

- Add the api to be able to spawn entities that can be rendered anywhere no matter what is behind the player.
- Add a method to be able to colorize a whole model and parts of the model.
- Add a method to spawn an entity for a single player so that only one player can interact with that entity.
- Add a method to teleport custom entities or at least to set their gaze.

### Is your feature request related to a problem?

- The custom entity does not render well when it is behind the player. https://cdn.discordapp.com/attachments/978365533189705818/979189931014508614/2022-05-25_19-13-54.mp4
- The custom entity does not allow spawning to a single player.
[It should look like this.](https://cdn.discordapp.com/attachments/978365533189705818/979199985704915015/2022-05-25_20-31-42.mp4) 
[But it looks like this(because it is not included in the api)](https://cdn.discordapp.com/attachments/978365533189705818/979200081234395158/2022-05-25_20-32-41.mp4)

### Describe alternatives you've considered

Include new methods in the api to help us further customize custom entities.
something like this.
```java
CustomEntity.spawnFakeEntity(String namespaceId, Player player, Location location); //May apply to the first and the last problem.
customEntity.colorModel(Color color);
customEntity.colorBone(String boneId, Color color); //These 2 can apply very well for the api about coloring a whole model and its parts.
customEntity.setLocation(Location location); //or 
customEntity.setLook(float yaw, float pitch); //To establish the look of a customized entity.
```

### Additional context

Sorry for asking so much but my users love ItemsAdder and I can't deny them compatibility with it = )

**Comment by FrancoBM12** [comment]
I propose a method where you can know if the namespace of the custom entity exists without trying to spawn it.
```java
CustomEntity.exist(String namespacedId); //returns a boolean.
```
In my plugin I need to know if the model exists before placing it, it would be very useful. Thank you very much.

**Comment by LoneDev6** [comment]
Amazing ideas, I'll work on that task this week

**Comment by LoneDev6** [comment]
No problem.
Is this really needed?
You can check if the animation played. It will return false if the animation doesn't exists:
https://github.com/LoneDev6/API-ItemsAdder/blob/b043eee2008ef6274331a1336e0cfa483539e5d8/src/main/java/dev/lone/itemsadder/api/CustomEntity.java#L191

**Comment by FrancoBM12** [comment]
Look, the problem is that I save some animations and if you write any animation in the chat when trying to play it, it will not do it, so I would prefer before you are allowed to put any animation first check if the animation exists in the model and if it does not exist send you the list of animations available in that model.
I hope I have explained myself well.

**Comment by LoneDev6** [comment]
Will be available in the next update:
```java
    /**
     * Check if a custom entity model has an animation registered by its name
     * @param entityNamespacedId the custom entity identifier in the format {@code namespace:id}
     * @param animationName the animation name
     * @return true if the animation exists, otherwise false
     */
    public static boolean hasAnimation(String entityNamespacedId, String animationName)
    {
        throw new NotActuallyItemsAdderException();
    }

    /**
     * Check if this custom entity model has an animation registered
     * @param name the animation name
     * @return true if the animation exists, otherwise false
     */
    public boolean hasAnimation(String name)
    {
        throw new NotActuallyItemsAdderException();
    }

    /**
     * Get all custom entity model animations registered by its name
     * @param entityNamespacedId the custom entity identifier in the format {@code namespace:id}
     * @return a list of the animations registered for a custom entity
     */
    public static List<String> getAnimationsNames(String entityNamespacedId)
    {
        throw new NotActuallyItemsAdderException();
    }

    /**
     * Get all custom entity model animations for this custom entity
     * @return a list of the animations registered for a custom entity
     */
    public List<String> getAnimationsNames()
    {
        throw new NotActuallyItemsAdderException();
    }
```

### Test
```java
            System.out.println("anim idle exists:");
            System.out.println(cust.hasAnimation("idle"));
            System.out.println("static:");
            System.out.println(CustomEntity.hasAnimation("custom:barman_robot", "idle"));

            System.out.println("anim list:");
            System.out.println("obj:");
            for (String animName : cust.getAnimationsNames())
            {
                System.out.println("   " + animName);
            }
            System.out.println("static:");
            for (String animName : CustomEntity.getAnimationsNames("custom:barman_robot"))
            {
                System.out.println("   " + animName);
            }
```

### Output
```
[16:24:03 INFO]: [Test] [STDOUT] anim idle exists:
[16:24:03 INFO]: true
[16:24:03 INFO]: [Test] [STDOUT] static:
[16:24:03 INFO]: true
[16:24:03 INFO]: [Test] [STDOUT] anim list:
[16:24:03 INFO]: [Test] [STDOUT] obj:
[16:24:03 INFO]: [Test] [STDOUT]    idle
[16:24:03 INFO]: [Test] [STDOUT]    talking
[16:24:03 INFO]: [Test] [STDOUT]    looking right
[16:24:03 INFO]: [Test] [STDOUT]    looking left
[16:24:03 INFO]: [Test] [STDOUT]    drinking
[16:24:03 INFO]: [Test] [STDOUT]    blink
[16:24:03 INFO]: [Test] [STDOUT]    tpose
[16:24:03 INFO]: [Test] [STDOUT]    test
[16:24:03 INFO]: [Test] [STDOUT] static:
[16:24:03 INFO]: [Test] [STDOUT]    idle
[16:24:03 INFO]: [Test] [STDOUT]    talking
[16:24:03 INFO]: [Test] [STDOUT]    looking right
[16:24:03 INFO]: [Test] [STDOUT]    looking left
[16:24:03 INFO]: [Test] [STDOUT]    drinking
[16:24:03 INFO]: [Test] [STDOUT]    blink
[16:24:03 INFO]: [Test] [STDOUT]    tpose
[16:24:03 INFO]: [Test] [STDOUT]    test
```
