### ISSUE TITLE
[CustomBlock] Custom Digging Sound

### ISSUE THREAD

**Issue by ArtifactyNight** [PluginBugs/Issues-ItemsAdder#1732]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

NightKunGz  🌒#0790

### Describe the solution you'd like

Option to add custom digging sound when digging custom blocks similar Origin Realms server
Example Videos: 

https://user-images.githubusercontent.com/53427253/170674697-be6ba4ae-0135-44b7-8dc0-ac919599ba12.mp4

 

### Is your feature request related to a problem?

I want to make custom block is more realistic like vanilla block in minecraft

### Describe alternatives you've considered

I think Origin Realms server is remove noteblock's original digging sound in resourcepack
and add simulate sound to original noteblock and other block that use same digging sound as noteblock?

and add potion effect slow digging for 255 and bypass arm swing animation with NMS 
then play block cracking effect and play custom digging sound to make it look like mining progress (I know that because my ping latency is 200+ in Origin Realms, if I digging custom block and stop it while block is not break yet, it's will have some delay)

if block is cracking i think they use some method like [#breakNaturally(boolean)](https://jd.papermc.io/paper/1.18/org/bukkit/block/Block.html#breakNaturally(boolean)) in Paper API

I'm not sure my opinion is correctly 
if it's can do, i think it's will improve custom block feature about custom digging sound

**Comment by LoneDev6** [comment]
If I recall I already did some tests in the past because I had the same idea, the issue is that I'd have to replace the wood sound  with a blank sound which would require me to simulate the wood sound each time the server tries to play it, to avoid playing an empty sound.

I don't know if this is a really good solution sincerely.
