### ISSUE TITLE
Missing/glitched mob/player heads

### ISSUE THREAD

**Issue by srnyx** [PluginBugs/Issues-ItemsAdder#1734]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

srnyx#0001

### What happened?

For some players/mobs (depends on who's looking), the head will be either completely gone or glitched (depends on the angle the player is looking at them).
You can easily see it happening with player heads. If you get the skull of a player and put a bunch of the same skull next to each other on the ground, then move around and look at them at different angles, they change. Only a few will actually show the player's head, while the rest show the other body parts (like the image below) of the player.

### Steps to reproduce the issue

All I know is that when **I** look at a zombified piglin it glitches its head. But, it's different for everyone. Some people experience the bug with other players and even themselves. Except with players it just completely removes the head and does nothing else.

### Server version

git-Purpur-1592 (MC: 1.18.2)

### ItemsAdder Version

3.1.6

### ProtocolLib Version

4.8.0

### LoneLibs Version

1.0.18

### LightAPI Version (optional)

bukkit-5.2.0 (build SNAPSHOT)

### LibsDisguises Version (optional)

10.0.28

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: REDACTED
      pack-port: REDACTED
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: false
    hide-hud: false
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    - bbmodel
    - iaentitymodel
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-items: false
  extract-default-resources: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: false
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: false
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    interval-rendering-packets-ticks: 1
    emotes: true
    optimized-packets: true
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

The left one is subtle, but the brown part on the top isn't supposed to be there.
![image](https://user-images.githubusercontent.com/25808801/170729099-3ce97e0d-faf0-40d2-84e1-b5b77ea3b02f.png)

**Comment by LoneDev6** [comment]
Can you check if it's related to this? https://github.com/PluginBugs/Issues-ItemsAdder/issues/1729#issuecomment-1141425834

**Comment by srnyx** [comment]
> Can you check if it's related to this? [#1729 (comment)](https://github.com/PluginBugs/Issues-ItemsAdder/issues/1729#issuecomment-1141425834)

We're all using premium (bought) Minecraft (the server is in online mode). I'm using a modpack, but another player didn't see other people's heads was on vanilla iirc.

**Comment by PystoyPlayer** [comment]
> > Can you check if it's related to this? [#1729 (comment)](https://github.com/PluginBugs/Issues-ItemsAdder/issues/1729#issuecomment-1141425834)
> 
> We're all using premium (bought) Minecraft (the server is in online mode). I'm using a modpack, but another player didn't see other people's heads was on vanilla iirc.

Yeah. And in my case there's no matter what angle you look at
<img width="1440" alt="Screenshot (2022-05-30 at 10 PM)@2x" src="https://user-images.githubusercontent.com/88878911/171050762-dbda7fa6-5e32-46c0-bf3d-061e2dc2eb54.png">
+ In my case it's only for cracked players. Premium players see can everything right

**Comment by srnyx** [comment]
> And in my case there's no matter what angle you look at

If it's a player's head, it doesn't matter about the angle. But, if it's a mob head or a placed player skull, it changes.

**Comment by PystoyPlayer** [comment]
> > And in my case there's no matter what angle you look at
> 
> If it's a player's head, it doesn't matter about the angle. But, if it's a mob head or a placed player skull, it changes. _Also, where you are located (position) is another factor._

check this https://github.com/PluginBugs/Issues-ItemsAdder/issues/1729

**Comment by PystoyPlayer** [comment]
(I realized, that forgot to tell you all that if you join the server from 1.16, everything is fine (maybe because emotes are 1.17+ etc) )

**Comment by LoneDev6** [comment]
This seem to be related to the GPUs hardware or the drivers.
Can you send your server IP so that I can join and see?

I don't have this issue on my PC and it's only the second time I get this report since I released the emotes feature

**Comment by PystoyPlayer** [comment]
> This seem to be related to the GPUs hardware or the drivers. Can you send your server IP so that I can join and see?
> 
> I don't have this issue on my PC and it's only the second time I get this report since I released the emotes feature

well, try it from cracked client  play.lonto.xyz
