### ISSUE TITLE
Sound problems of blocks

### ISSUE THREAD

**Issue by HakanUnsalP** [PluginBugs/Issues-ItemsAdder#1735]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Hakan#4089

### What happened?

1. If the number of blocks is 1, it does not sound properly when placed on the ground.
2. When a vanilla block is put on a custom block with shift, the sound plays 2 times

### Steps to reproduce the issue

1. If the number of blocks is 1, it does not sound properly when placed on the ground.
2. When a vanilla block is put on a custom block with shift, the sound plays 2 times

### Server version

Current: git-Purpur-1625 (MC: 1.18.2)*

### ItemsAdder Version

![image](https://user-images.githubusercontent.com/58227275/170814402-d86c3d60-6156-486c-b498-1331edcdd423.png)

### ProtocolLib Version

![image](https://user-images.githubusercontent.com/58227275/170814390-17380985-368b-45f1-80f0-631737dcbae4.png)

### LoneLibs Version

![image](https://user-images.githubusercontent.com/58227275/170814410-b877e04d-49e3-4ce1-9734-0d262ec44dfc.png)

### Screenshots/Videos (you can drag and drop files or paste links)

https://user-images.githubusercontent.com/58227275/170814490-7e7f9e64-4f3b-4f38-8427-8e2034173a7f.mp4

**Comment by LoneDev6** [comment]
Tested on 3.2.0b, I might already have fixed it some updates ago, I don't remember.

https://user-images.githubusercontent.com/27242001/173848669-ba7ef451-48ca-44d1-a5d1-7301d798dde6.mp4
