### ISSUE TITLE
Possibility of Hiding Minecraft default Durability of an Item + ArmorRendering

### ISSUE THREAD

**Issue by NaTorOG** [PluginBugs/Issues-ItemsAdder#1739]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

https://cdn.discordapp.com/attachments/533413171403292712/979479161917825104/unknown.png

The problem is that is aesthetically bad to see different Durability as displayed above.
Players will be confused also, not understanding which one is the right durability.
I tried with items_flags to hide but won't hide.

Another cool feature would be to give the ability of creating custom armors without using leather as base.
I mean that I have created a custom armor using material NETHERITE_HELMET(For the head, this  is an example) with a custom texture.
The problem is that my custom layer1&2 texture won't work unless I don't use any material.
This would be a huge improvement, because I have created the most powerful armor of the server but still displays the normal durability of Leather, so returning at the first suggestion I stated above.

### Is your feature request related to a problem?

Nope

### Describe alternatives you've considered

I have not considered any alternative

**Comment by NaTorOG** [comment]
Possibile soluzione per il primo problema.
Usare item unbreakable
In ItemsFlags nascondere l'unbreakable.
In durability settare solo Usages
Ascoltare l'evento PlayerColpito? (Che attualmente non esiste)

**Comment by NaTorOG** [comment]
Ho notato una cosa ambigua, usando /iadurability con l'item in gioco, la durabilità mostrata è solo una

**Comment by LoneDev6** [comment]
Your players are not supposed to use the debug F3+H which enables "Advanced tooltips".
The second durability indicator you see is the vanilla internal one and the only way to remove it is to use F3+H key again.
