### ISSUE TITLE
Blocks with dark 3d model.

### ISSUE THREAD

**Issue by dani626** [PluginBugs/Issues-ItemsAdder#1740]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

XDaniXSin#3332

### What happened?

I have a problem with the blocks generated by AI, when I create a block with 3d model the block looks dark inside.

### Steps to reproduce the issue

Place AI generated block.

### Server version

This server is running Paper version git-Paper-349 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: b6a6544)

### ItemsAdder Version

3.1.6

### ProtocolLib Version

4.8.0

### LoneLibs Version

1.0.18

### FULL server log

visual bug

### Screenshots/Videos (you can drag and drop files or paste links)

On the left block generated by AI, on the right block of a Datapack.
Both are mushroom blocks.
¨[https://media.discordapp.net/attachments/980258102123298877/980258352875569203/2022-05-28_19.48.44.png?width=873&height=499](url)

**Comment by LoneDev6** [comment]
Use REAL_TRANSPARENT block type instead, or use a furniture (better).
This is a vanilla client bug, I'm 99% sure.

REAL_TRANSPARENT should support custom shaped blocks better.
