### ISSUE TITLE
Space plugin compatibility

### ISSUE THREAD

**Issue by ZDaPlaY** [PluginBugs/Issues-ItemsAdder#1741]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

ZDaPlaY#6666

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/88196950/170882638-d855310d-5080-4b9c-9b94-e676830dfce3.png)
Compatibility with the space plugin

### Is your feature request related to a problem?

![image](https://user-images.githubusercontent.com/88196950/170882638-d855310d-5080-4b9c-9b94-e676830dfce3.png)
Compatibility with the space plugin

### Describe alternatives you've considered

![image](https://user-images.githubusercontent.com/88196950/170882638-d855310d-5080-4b9c-9b94-e676830dfce3.png)
Compatibility with the space plugin

**Comment by BookWyrm114** [comment]
Yes please, Space compatibility would be amazing

**Comment by Garfieldwxg55** [comment]
Would love to see this, do you know anything more about the error? Like is it maybe a resource pack thing or something else? Might help to figuring out the solution, thanks for your help :)

**Comment by LoneDev6** [comment]
It's about armors if I recall, I hope to find the time to fix that, but it's not an easy/fast task

**Comment by srnyx** [comment]
Not to be that person, but I really need this fixed because with the Space rewrite **and** ItemsAdder default items rewrite, it seems like the perfect time to reset my server, but this is preventing that.

If possible, I'd be more than happy to donate $5-$10 to get this bug fast-tracked/prioritized! 😄
