### ISSUE TITLE
Players should have destroy flag of Residence plugin, but not container flag, to break a furniture

### ISSUE THREAD

**Issue by JinOuYongGu** [PluginBugs/Issues-ItemsAdder#1755]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

A player with destroy flag can break furnitures in Residence area.
A player with container flag can not break furnitures in Residence area.

### Is your feature request related to a problem?

I'm not sure it is the behavior of ItemsAdders or Residence...
In my opinion, the flag containers do not mean that a player can destroy the furniture.
The only way to do that is to get destroy flag.
Current setting of residence flag maybe confusing.

### Describe alternatives you've considered

Change the flag judgement of Residence from Container to Destroy

**Comment by LoneDev6** [comment]
ItemsAdder checks if any other plugin has cancelled the block break event, then it cancels the furniture event if the block break event is cancelled.

Maybe residence plugin has a wrong event priority set?
Can you ask the Residence plugin developer about that?
Maybe link them this Github issue.

Have a nice day

**Comment by LoneDev6** [comment]
The logic checks if the player can damage entities by triggering the `EntityDamageByEntityEvent` event and checking if any proteciton plugin cancelled it before processing the furniture removal.
So Residence should listen to `EntityDamageByEntityEvent` and cancel it if the player has no permission to interact with armorstands and itemframes.
