### ISSUE TITLE
Armor set bonus idea!

### ISSUE THREAD

**Issue by purejosh** [PluginBugs/Issues-ItemsAdder#1756]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

purejosh#2047

### Describe the solution you'd like

Allow for an armor set bonus, should the player be wearing the correct armor in all 4 slots. Would be a really cool idea for something like fireproof armor, or regen armor. Not sure how you'd do the checks, but in the config, if we could denote a "armor set bonus" field, we could add beacon effects to it. 

### Is your feature request related to a problem?

No. 

### Describe alternatives you've considered

Really aren't any alternatives.

**Comment by Annijang** [comment]
Your opinion, I have a plugin to recommend to you, its name is "MMOitem", it can give you the set bonus function you want, link: https://www.spigotmc.org/resources/mmoitems- premium.39267/

**Comment by LoneDev6** [comment]
Duplicate https://github.com/PluginBugs/Issues-ItemsAdder/issues/1333
