### ISSUE TITLE
Refresh Rate HUD

### ISSUE THREAD

**Issue by NhProGamer** [PluginBugs/Issues-ItemsAdder#1758]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

NнPяo🗕 🗗 🗙#2800

### Describe the solution you'd like

it's that possible to change refresh rate of an HUD ?

### Is your feature request related to a problem?

no

### Describe alternatives you've considered

nothing

**Comment by LoneDev6** [comment]
It's not possible
