### ISSUE TITLE
Magic wands / scepters without the use of magiccraft

### ISSUE THREAD

**Issue by vdl19** [PluginBugs/Issues-ItemsAdder#1769]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

https://discord.com/channels/533407895010803753/571988026704527371/979711952219672646

### Describe the solution you'd like

In fact I would like to configure wands and not necessarily with the use of magic
I would like to configure the wands like the one the "Yes We Craft" server had I put a video with 2 wands shown, so I would like to be able to reproduce them, maybe it's possible but I don't see how to do it setup? Without the use of magic and I wanted to avoid magic

So I would like to modify: speed, ranged attack damage, block distance, shot particle and not ranged damage so with the other mouse click

Sticks visible in action from 1:25
https://www.youtube.com/watch?v=__DfchjQJZA

I will use the wands from the "3dfantasyweaponscit" addon:

..................................
info:
  namespace: 3dfantasyweaponscit
items:
  night_staff:
    display_name: display-name-night_staff
    permission: 3dfantasyweaponscit.shotgun.night_staff
    resource:
      material: CROSSBOW
      generate: false
      model_path: item/staff/night_staff
    specific_properties:
      crossbow:
        multishot: true
  ..................................
  
  I know there is an example on the wiki but with the use of magic, but what I did doesn't work for me at all, I think the qomme wands setup on the YWC server would work better for me without the use of magic.
  
  
![image](https://user-images.githubusercontent.com/80985545/173231157-bb489e1f-ced8-48d1-b8dc-23d3d885b0c5.png)

I asked my question on the discord and also on the spigot discussion page of the one who made the "3dfantasyweaponscit" addon and the 2 or 3 people who answered me told me they don't know if we can do that with ItemsAdder, uses mmoitems

I asked my question on the discord and also on the spigot discussion page of the one who made the "3dfantasyweaponscit" addon and the 2 or 3 people who answered me told me they don't know if we can do that with ItemsAdder, uses mmoitems.
But I would like to be able to do this with itemsAdder and not have to use another plugin, I use it to add all my items, food, sword, armor.. and since we can add chopsticks and scepter I would find it unfortunate not being able to use them directly with IA.

The goal is to make wands / sceptres without the need for magic with above all just times and distances of shots which will be more or less long depending on the power

### Is your feature request related to a problem?

Not really

### Describe alternatives you've considered

Well mmoitems seems to be my only solution but I don't really want to add yet another plugin when IA could do it I think

**Comment by LoneDev6** [comment]
Hello, this is not a place to ask for configurations, please ask on Discord, maybe someone can help.
Anyway this is a very complex task, I doubt it can be implemented just with ItemsAdder configurations.
You might achieve that with the ItemsAdder API + Skript or a Java plugin.
