### ISSUE TITLE
Updating and load new textures in /iatexture

### ISSUE THREAD

**Issue by Desmordss** [PluginBugs/Issues-ItemsAdder#1773]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

When I add new textures, upload them to google drive, write /iareload and /iatexture on the server, no new textures appear. Only removing the old resource pack from the /server-resource-pack/ helps. How to force the server to delete the old resource pack and install a new one?

### Is your feature request related to a problem?

yep

### Describe alternatives you've considered

I didn't find a solution on the wiki

### Additional context

I don't see any errors in the console.

**Comment by LoneDev6** [comment]
You must change the GoogleDrive URL each time you upload a new version of the pack, probably you're using the same URL as before.
Let me know
