### ISSUE TITLE
Add the ability to specify specific string replacement to font images

### ISSUE THREAD

**Issue by Mike5357** [PluginBugs/Issues-ItemsAdder#1776]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Mike🎤#5357

### Describe the solution you'd like

I'd like a feature that would allow specific strings to be replaced with images in chat. For example, instead of `:owner:` being replaced with an image, you could define specifically `[Owner]` to be replaced. 

This feature could be used for more purposes than just prefixes, for example as a chat censoring tool. Instead of using external plugins to remove or replace messages with "bad words", you could render a black CENSORED image bar in the words place instead.

### Is your feature request related to a problem?

Yes. I'm using a proxy network and have cross-server chat using VentureChat, but want to use image prefixes. The problem is that we do not want our lobby server to have a resource pack thats required to be downloaded, so while chat on one server appears like this: 
![unknown](https://user-images.githubusercontent.com/12630858/174125078-b6e48c11-7afc-4b34-863a-4488acf2c72a.png)
on the lobby that doesnt use ItemsAdder/a resource pack it appears like this (which is pretty ugly):
![unknown](https://user-images.githubusercontent.com/12630858/174125167-c6e4d494-2327-4286-834b-fda90e9b6bb5.png)

### Describe alternatives you've considered

I have tried using additional chat replacement plugins/tools, but none of them seem to work for replacing strings in usernames/prefixes to resolve my problem. Previously we used Multichat instead of Venturechat which allowed you to format received chat messages on a per-server basis so we would have had a solution to this problem, however we have switched to using Velocity instead of Bungeecord and VC does not support it.

**Comment by LoneDev6** [comment]
This is not possible to be added without introducing severe CPU usage to the plugin.
Currently the plugin can detect placeholders which are between `:` characters, similarly to how PlaceholderAPI works which uses `%`.
