### ISSUE TITLE
Emojis & Placeholders no longer working in chat/prefixes on 1.19

### ISSUE THREAD

**Issue by IshKaigen** [PluginBugs/Issues-ItemsAdder#1777]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

~Red#1969

### What happened?

Im using VenturaChat, although i tested this with several other chat plugins including Chatty, LuckPermsChat, and SIR. Whenever attempting to set a prefix through LuckPerms, instead of showing the image of let's say the Admin Rank, it shows up instead as :staffadmin: in chat. Using the /e command also doesn't work for emotes, they show up in suggestions but do not show on chat when typed and entered. They all work fine on Signs though. 

Using latest defaultpack 2.0.2, moreranks and emojispack resources.
MoreRanks: https://www.spigotmc.org/resources/moreranks-itemsadder-addon.97852/
EmojisPack: https://www.spigotmc.org/resources/emoji-pack-itemsadder-addon.101954/

All dependencies installed including PlaceholderAPI and it's expansions. Followed all steps on LoneDev wiki, LuckPerms Wiki and VenturaChat Wiki. Resources are correctly installed and work, as i said earlier emotes and other textures show up just fine and work.

### Steps to reproduce the issue

1.Install all required plugins, resources and dependencies.

2.Attempt to use Custom Prefixes via Luckperms or Emotes in Chat.

### Server version

Current: git-Purpur-1668 (MC: 1.19)*
* You are running the latest version

### ItemsAdder Version

ItemsAdder version 3.2.0b-beta4

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b569

### LoneLibs Version

LoneLibs version 1.0.19

### LibsDisguises Version (optional)

LibsDisguises version 10.0.28-SNAPSHOT

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: false
      server-ip: 127.0.0.1
      pack-port: 8163
    external-host:
      enabled: true
      url: https://www.dropbox.com/s/enjgxax0wh25d1q/ad_ia.zip?dl=1
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: true
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    - bbmodel
    - iaentitymodel
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-configs: true
  legacy_pack: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: false
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: false
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    emotes: true
    interval-rendering-packets-ticks: 1
    optimized-packets: true
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-recipes-unknown-item: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

![chatsuggestions](https://user-images.githubusercontent.com/65985361/174252753-cd6624a6-60fe-4f25-a278-a6a5bafaffcd.png)
![chatemotepng](https://user-images.githubusercontent.com/65985361/174252778-4647ec8b-4764-4f2a-a92a-6b508b73e5de.png)
![moreranks](https://user-images.githubusercontent.com/65985361/174252811-7a626322-a8e8-4bf9-8f99-55d849599725.png)
![venturachatconfig](https://user-images.githubusercontent.com/65985361/174252854-261d5f35-d31f-4543-aa0d-080af9a6c22c.png)
![signrank](https://user-images.githubusercontent.com/65985361/174252865-8ef35c8c-0dca-419e-9c12-79b278e40101.png)
![signemote](https://user-images.githubusercontent.com/65985361/174252887-805e8300-5040-4e46-b366-15a709064bde.png)
![lpconfig](https://user-images.githubusercontent.com/65985361/174253447-9b9b9496-43d8-4a23-9deb-f47a15943754.png)

**Comment by thefourcraft** [comment]
# Mojang Bug 😠 
We know about the problem but Mojang did something wrong in the new update for Minecraft 1.19 (not surprised)\
The best way to help fix the quickly is to vote and comment on the bug report that Boy#8008 made.
# What Can I do?
first, don't update to 1.19 most of the plugins are in beta versions and won't support 1.19 100%\
In the upcoming weeks, most of the problems will be solved... \
you can try things on a **test server** and report bugs to improve plugins and help the developers :)\
## Q&N 💯 
## How I Can Help ✋🏻 
Go to https://bugs.mojang.com/browse/MC-253169 (make an account) vote & comment on the bug...\
we need to bring this to the Mojang team **argutely**
## When Will This Be Fixed 🐺 
We don't know and don't have any due date its up to Mojang to fix it up in the next update
### Dose This means that I won't be able to update to 1.19
well, if you love font images (who doesn't) then you need to wait for Mojang to wake up 🚑 
## Is this an IA problem 🍨 
As far as I know (@thefourcraft), it's a problem within Minecraft so Mojang is responsible for the fix.
## What If I found A fix 🌵 
Amazing, commit to the issue and help us all 😸

**Comment by thefourcraft** [comment]
# Update 6\19\2022
We have a temporary fix by @Fox2Code
https://github.com/Fox2Code/ItemsAdderEmojiFixer

## About the Mojang report ⛏️ 
Whiles the temporary fix makes emojis work... the bug is still present in Minecraft 1.19
"Negative space Unicode fails to load when the font has errors"
### bug information ✍🏻 
Unlike on <1.19 resource packs, negative space/zero-width unicodes fail to load when the font file has any issues. Be that a texture missing etc. This only seems to affect zero-width Unicode as others load just fine.
As in the image, where player.png is missing, the zero-width is the rectangle, whilst the logo Unicode load just fine. Caused a lot of confusion seemingly as this never was the case before 1.19.
### The result 🧾 
![image](https://user-images.githubusercontent.com/90725541/174470541-107040cb-9c99-4d0a-a8d2-21ad235262c9.png)

![image](https://user-images.githubusercontent.com/90725541/174470548-d5406ed7-fb04-4168-8f71-158d1234d1d4.png)

### Links
[Bug Report](https://bugs.mojang.com/browse/MC-253169)
[Mojang Discord For Bugs](https://discord.com/invite/rpCyfKV)
[Discord Chat about the bug In IA Discord](https://discord.com/channels/533407895010803753/984068680386232330)
[Discord server IA](https://discord.gg/geWMPCVT)
[Random Meme](
https://user-images.githubusercontent.com/90725541/174470588-852bcfce-645b-4fe8-881f-f9e39bf4d11d.png)
[LoneDevs Donation program](http://a.devs.beer/lonedevdonate)
