### ISSUE TITLE
Furniture can be destroyed in adventure mode

### ISSUE THREAD

**Issue by buchaosi** [PluginBugs/Issues-ItemsAdder#1785]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

I'm testing the furniture
I tried to destroy him in adventure mode
Then I found out that furniture can be destroyed in adventure mode
Then I tried to place furniture in adventure mode
but failed
I don't think furniture should be destroyed in adventure mode

### Steps to reproduce the issue

Place furniture
Mode changed to Adventure
Break furniture | succeed
Place furniture  |failed

### ItemsAdder Version

ItemsAdder Version 3.2.0b-beta4

### ProtocolLib Version

ProtocolLib Version 4.8.0

### LoneLibs Version

LoneLibs Version 1.0.19

**Comment by LoneDev6** [comment]
duplicate https://github.com/PluginBugs/Issues-ItemsAdder/issues/1725
