### ISSUE TITLE
Gradient for texts in configs (plugin language file, display name and lore)

### ISSUE THREAD

**Issue by LavivaNW** [PluginBugs/Issues-ItemsAdder#1791]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Profesör#7037

### Describe the solution you'd like

"<gradient:&#046EFB:&#ADF3FD>Ice Sword"

Making color transitions provides serious convenience and name parts look less confused. it would be really useful. It is great that he chooses 2 colors and completes it himself. 

Since there is no such feature in itemsadder, you have to color code each letter to prepare color transition texts.
and for example, you will get an ugly image like the example below. and you'll also have to deal with a lot more.

"&#046EFBI&#986ERBc&#666BRBe &#356ESBS&#276KKBw&#346TRBo&#0066FBr&#996EYYd"

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

I didn't think of an alternative.

**Comment by LoneDev6** [comment]
Implemented using Minimessage: #2224
Example: `<b><color:#57ff5c>test</color></b><gradient:#ff00ee:#f79459>Amogus</gradient>`
