### ISSUE TITLE
1.19 fonts images bug

### ISSUE THREAD

**Issue by LuluxClient** [PluginBugs/Issues-ItemsAdder#1792]
### Discord tag (optional)

Lulux#4614

### What happened?

When logging on 1.19 on a 1.18.2 some font images have a weird [] icon next to the actual image

### Steps to reproduce the issue

1. log in a 1.18 server under a proxy with bungeepackfix
2. join with 1.19

### Server version

This server is running Pufferfish version git-Pufferfish-72 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 8f05a00 on HEAD)
You are on the latest version!

### ItemsAdder Version

3.2.0b-beta4

### ProtocolLib Version

5.0.0 b569

### LoneLibs Version

1.0.18

### Screenshots/Videos (you can drag and drop files or paste links)

First I log in on 1.19 and after I join 1.18 https://gyazo.com/86263e6799d7180a1542d62d950ced69

**Comment by LoneDev6** [comment]
There is a discussion on Discord about that:
https://discord.com/channels/533407895010803753/984068680386232330/988770206874742804


Seems to be a Minecraft 1.19 limitation.
Please read more on Discord.
