### ISSUE TITLE
Custom hats on animated emotes

### ISSUE THREAD

**Issue by Toinetoine1** [PluginBugs/Issues-ItemsAdder#1797]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Is it possible to show custom cosmetics like hats (or armor) when playing an emotes (gesture animated player)

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

can may be use locator bone as slot for the custom cosmetic ?

**Comment by LoneDev6** [comment]
Good idea, will be implemented.
For now it supports hand items.
