### ISSUE TITLE
thin-font garbled

### ISSUE THREAD

**Issue by HoneyBearc** [PluginBugs/Issues-ItemsAdder#1808]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

HoneyBearc#9030

### What happened?

thin-font:
    enabled: true
https://upload.cc/i1/2022/06/27/IpObMr.png
https://upload.cc/i1/2022/06/27/NGQwud.png

### Steps to reproduce the issue

no

### Server version

paper-1.19-39

### ItemsAdder Version

3.2.0c-beta6

### ProtocolLib Version

#570

### LoneLibs Version

1.0.19

### LightAPI Version (optional)

no

**Comment by HoneyBearc** [comment]
Same problem after setup
not solved

**Comment by LoneDev6** [comment]
Disable thin-font in config.yml and open default.json, then set this content:

```json
{
    "providers": [
        {
            "type": "space",
            "advances": {"\u0020": 4}
        },
        {
            "type": "legacy_unicode",
            "sizes": "minecraft:font/glyph_sizes.bin",
            "template": "minecraft:font/unicode_page_%s.png"
        }
    ]
}
```

**Comment by HoneyBearc** [comment]
thanks problem solved
