### ISSUE TITLE
Configuration of ridden custom entity properties

### ISSUE THREAD

**Issue by DanikVitek** [PluginBugs/Issues-ItemsAdder#1809]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Danik Vitek#9110

### Describe the solution you'd like

I'd like to have a configuration section for the movement settings of a ridden entity in the custom entity config file. There should be such parameters as speed and jump, and maybe something else, depending on the entity type (flying speed, etc).

### Is your feature request related to a problem?

When developing some plugins, there is a need in synchronizing the animation and movement speed, as well as balance some stuff, related to the movement, so that would be really useful if not required

### Describe alternatives you've considered

There could probably be some programming API methods for controlling such things, but not required, I suppose

**Comment by LoneDev6** [comment]
This will be fixed in the next update:
- fixed custom entities walk and fly speed always being `value - 0.7`, now it will be used the exact speed value
- fixed custom entities walk and fly speed ignored when riding them
