### ISSUE TITLE
Some methods are missing in the new version of the api.

### ISSUE THREAD

**Issue by FrancoBM12** [PluginBugs/Issues-ItemsAdder#1810]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

FrancoBM#2980

### What happened?

In the current api there are no methods such as the following:
```java
CustomEntity.setColorAllBones(color);
CustomEntity.setEnchantedAllBones(enchanted);
CustomEntity.Bone.setColor(color);
CustomEntity.Bone.setEnchanted(enchanted);
```
The developer had already added it, however these methods are not found in the current api... maybe he forgot?

As a last request, as I said in the previous topic... I would like you to add as a last feature to the api a method to know if an animation exists in a custom entity without the need to spawn it... (if it is possible, great, if not, too bad.)

### Steps to reproduce the issue

1. Go to https://github.com/LoneDev6/API-ItemsAdder/blob/3.1.6/src/main/java/dev/lone/itemsadder/api/CustomEntity.java
2. You will not see the methods described.

### ItemsAdder Version

Irrelevant.

### ProtocolLib Version

Irrelevant.

### LoneLibs Version

Irrelevant.

**Comment by LoneDev6** [comment]
Fixed: https://github.com/LoneDev6/API-ItemsAdder/releases/tag/3.2.0c-beta6-fix1
Thanks a lot for the help
