### ISSUE TITLE
minecraft lang overwrite hex color support

### ISSUE THREAD

**Issue by Truongvv10** [PluginBugs/Issues-ItemsAdder#1813]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Wassabi#0317

### Describe the solution you'd like

Make minecraft_lang_overwrite esc_menu_texts support hex colors!
![image](https://user-images.githubusercontent.com/67742370/176473422-76cd3a30-7d34-4f21-ba75-c8ac97d9e028.png)

### Is your feature request related to a problem?

no

### Describe alternatives you've considered

Hex colors can be formatted like:
<#color>
{#color}
&#color

**Comment by LoneDev6** [comment]
Minecraft doesn't allow using HEX colors into language files.
It's a limitation of the game itself.
Only these colors are supported:
![immagine](https://user-images.githubusercontent.com/27242001/176478677-e07b5981-52c9-4e85-aa36-bd0158e184c8.png)

Info:
https://www.reddit.com/r/mcresourcepack/comments/htydza/how_to_i_use_new_hex_color_formatting_116_to_lang/
