### ISSUE TITLE
Placeable_on 2D ICONS FOR BLOCKS/FURNITURE

### ISSUE THREAD

**Issue by paulreob** [PluginBugs/Issues-ItemsAdder#1817]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

! Pau#9216

### Describe the solution you'd like

https://streamable.com/o7i316
As seen in the video
It would be great if when placed on the floor or on the ceiling, the model is different

maybe the configuration is something like this:
![image](https://user-images.githubusercontent.com/71041139/176726509-df521958-c690-49b0-a896-03de52cde8f6.png)

### Is your feature request related to a problem?

*

### Describe alternatives you've considered

*

**Comment by LoneDev6** [comment]
It's a bit complex to implement in the current system.

Also don't forget that this would make a lot of artists abuse the blocks system creating multiple models per-block.
This will cause the blocks slots to finish very fast. (same issue applies to custom directional blocks).

I don't think this would be implemented that soon.
