### ISSUE TITLE
[BUG] LIQUIDS ON TOP/FACES OF CUSTOMS BLOCKS

### ISSUE THREAD

**Issue by paulreob** [PluginBugs/Issues-ItemsAdder#1833]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

! Pau#9216

### What happened?

Liquids cannot be placed on top/faces of custom blocks, buckets of water, lava, axolotls, fish, etc etc

### Steps to reproduce the issue

Watch video

### Server version

Current: git-Purpur-1632 (MC: 1.18.2)*

### ItemsAdder Version

ItemsAdder version 3.2.2-beta5

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.19

### Screenshots/Videos (you can drag and drop files or paste links)

https://user-images.githubusercontent.com/71041139/177908155-7dce4712-a405-4efd-955f-12c51c7e3619.mp4

**Comment by LoneDev6** [comment]
Will be fixed, thanks.
Note that you won't be able to place liquids on REAL_WIRE and REAL_CHORUS blocks to avoid server lag.
