### ISSUE TITLE
World Populators for Schematics

### ISSUE THREAD

**Issue by dercraftnetwork** [PluginBugs/Issues-ItemsAdder#1837]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

DerVillion

### Describe the solution you'd like

I't's very self explanatory.

Being able to build our own "RogueDungeons" using schematics, and world populators.
Could work as a single plugin, but would recommend with IA because of custom blocks.
maybe a way to save these "schematics" in-game and not just with WE

### Is your feature request related to a problem?

just a suggestion

### Describe alternatives you've considered

hmmmm not doing this suggestion?

**Comment by LoneDev6** [comment]
This plugin should be the solution
https://www.spigotmc.org/resources/custom-structures.38249/

Also install ItemsAdder-WorldEdit
https://www.spigotmc.org/resources/addon-itemsadder-worldedit.79012/
