### ISSUE TITLE
replace_propertys: Add the option to replace the material of an item

### ISSUE THREAD

**Issue by JaHollTV** [PluginBugs/Issues-ItemsAdder#1841]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

JaHoll#5429

### Describe the solution you'd like

"copy_from_item:" in the replace_properties section should also copy and change the Material of an item.

Very useful: 
For example, for an flashlight you can turn on and off. (The Material when its turned on is a torch and when its turned off a Stick).

### Is your feature request related to a problem?

no

### Describe alternatives you've considered

no alternatives

### Additional context

Context of the Config:
![image](https://user-images.githubusercontent.com/48917504/178336316-9e9124c8-d620-4760-ba7e-84e54899bc1c.png)

**Comment by LoneDev6** [comment]
This is not how the replace_properties logic works.
CustomModelData and Material are an unique key in the game, you can't swap them
