### ISSUE TITLE
Crafting recipes not suggesting items

### ISSUE THREAD

**Issue by adelando** [PluginBugs/Issues-ItemsAdder#1843]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Adelando#1988

### What happened?

After the 1.19 update permissions for crafting recipes have had some errors.

When clicking on a crafting recipe in vanilla GUI it doesnt show the required items needed to craft. Also if the recipe is made manually in the crafting table the itemsadder item is not dispensed.

### Steps to reproduce the issue

1. open a crafting table (be sure to have permissions eg "ia.user.recipe.buildersbasics"
2. click on the item in the recipe book.
3. thats the issue.

### Server version

Current: git-Purpur-1708 (MC: 1.19)*
Previous: git-Purpur-1669 (MC: 1.19)
* You are running the latest version

### ItemsAdder Version

Itemsadder Version 3.2.0c-beta6

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b575

### LoneLibs Version

LoneLibs version 1.0.20

### FULL server log

No error logs when clicking crafting recipes 

### Other files, you can drag and drop them here to upload. (optional)

.

### Screenshots/Videos (you can drag and drop files or paste links)

https://www.veed.io/view/e5fd2bd6-6d2d-4a78-acbe-4e2cf9452e66

**Comment by adelando** [comment]
[custom_blocks.yml.txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/9091538/custom_blocks.yml.txt)

Forgot to upload

**Comment by LoneDev6** [comment]
Can't reproduce the issue

https://user-images.githubusercontent.com/27242001/181020071-038c58f2-3004-410f-9f81-85f1b2fa3493.mp4

**Comment by adelando** [comment]
Permission issue? 
I’ve been trying to use “ia.user.recipe.(permission)” but still nothing
Is there another permission node I can use?

**Comment by LoneDev6** [comment]
Maybe this can clarify some things since there are some examples: https://itemsadder.devs.beer/plugin-usage/permissions/example-permissions
