### ISSUE TITLE
[1.19] Unhandled exception occurred in onPacketSending

### ISSUE THREAD

**Issue by Ecilpse** [PluginBugs/Issues-ItemsAdder#1856]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

updated 

### Steps to reproduce the issue

https://user-images.githubusercontent.com/25452835/179551747-bc1f03ff-d499-4238-a4ac-858086200785.mp4

when i use quickshop, server has error
[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/9133439/latest.log)
.

### Server version

Purpur 1.19-RO.1-SNAPSHOT

### ItemsAdder Version

ItemsAdder_3.2.2-beta5

### ProtocolLib Version

5.0.0-SNAPSHOT-b577 (for 1.19 lastest dev build)

### LoneLibs Version

1.0.20

**Comment by LoneDev6** [comment]
I'll check this as soon as possible, thanks for the report

**Comment by LoneDev6** [comment]
Seems to be caused by the lib I use to parse Minecraft JSON messages.
I contacted its developers, let's wait.
https://github.com/KyoriPowered/adventure/issues/801

**Comment by LoneDev6** [comment]
Answer from the adventure lib devs:
> Looks like badly formed JSON to me. Head into the Discord if you need more support.

You must contact Quickshop developer about this malformed JSON problem.
Feel free to link them this issue report because it has some information.

Have a nice week!

**Comment by LoneDev6** [comment]
Read more here, it will be fixed: https://github.com/PluginBugs/Issues-ItemsAdder/issues/1884
