### ISSUE TITLE
1.17.1 /ia's armor doesn't work

### ISSUE THREAD

**Issue by angeldocraft** [PluginBugs/Issues-ItemsAdder#1857]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

Hello, the armor does not work. When I craft it and use it everything is fine, but when I take it off it disappears.

### Steps to reproduce the issue

Hello, the armor does not work. When I craft it and use it everything is fine, but when I take it off it disappears.

### ItemsAdder Version

last

### ProtocolLib Version

last

### LoneLibs Version

last

**Comment by LoneDev6** [comment]
Please post a proper bug report with all the required information.
I cannot identify the issue without any information.
You left every field blank or generic.
