### ISSUE TITLE
furniture orientation

### ISSUE THREAD

**Issue by Cha-Shao** [PluginBugs/Issues-ItemsAdder#1861]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

All itemframe furniture will face south when placed against the wall

### Steps to reproduce the issue

place itemframe furniture

### Server version

This server is running Paper version git-Paper-344 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 31ccc57)
You are 43 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-187 (MC: 1.18.1)

### ItemsAdder Version

3.2.2-beta5

### ProtocolLib Version

4.8.0

### LoneLibs Version

1.0.20

### LightAPI Version (optional)

bukkit-5.2.0(build SNAPSHOT)

### FULL server log

https://pastebin.ubuntu.com/p/TxxQKwrVmb/

### Screenshots/Videos (you can drag and drop files or paste links)

https://discord.com/channels/@me/999352815086469220/999687763089698896

**Comment by LoneDev6** [comment]
Seems related to this: https://github.com/PluginBugs/Issues-ItemsAdder/issues/1872
