### ISSUE TITLE
[Bug] Major lag spikes coming from ItemsAdder's Tab Emoji replacer

### ISSUE THREAD

**Issue by Maroon28** [PluginBugs/Issues-ItemsAdder#1862]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Maroon#1461

### What happened?

ItemsAdder (and its dependencies) cause random lag spikes, taking the server TPS down to almost 6 and spiking the mspt up to 90 on average.  I've done multiple spark profilers, and all of them point to the same issue being Itemsadder, protocollib, and lonelibs as the main sources of lag, which are all intertwined with each other.

Here's the spark for reference, click on 'all' in the top right until it becomes 'sources', and you'll see the plugins mentioned above on the top. https://spark.lucko.me/UXlTZaBjvx 

I have other sparks generated if needed, but they were using older versions of the plugin, or had other sources of lag included (all of which have been fixed). 

### Steps to reproduce the issue

Not sure what the reproduction steps would be. All of the code is obfuscated so its hard to tell what's causing it. 

### Server version

[18:18:55 INFO]: Checking version, please wait...
[18:18:56 INFO]: Current: git-Purpur-1612 (MC: 1.18.2)*
Previous: git-Purpur-1547 (MC: 1.18.1)
* You are 20 version(s) behind

### ItemsAdder Version

ItemsAdder version 3.2.2-beta5

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.20

### FULL server log

https://paste.gg/p/anonymous/d99877a40da14538955015659b30c8da

### Error (optional)

```shell
None
```

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: xxxxxxxxxx
      pack-port: xxxx
    external-host:
      enabled: false
      url: http://matteodev.it/spigot/itemsadder/res/v2/precompressed/precompressed_example_pack_5.zip
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
    protect-file-from-unzip:
      enabled: true
      extreme: true
    overwrite-vanilla-models: true
    overwrite-vanilla-lang-json: true
    compress-png-files: true
    compress-json-files: true
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: false
    disable-overwrite-leather-armor-layers-textures: false
  self-host: {}
  external-host: {}
  command:
    usage-cooldown-seconds: 60
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-resources: false
  extract-default-configs: false
  legacy_pack: true
blocks:
  light-api: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    seach-also-in-these-biomes: {}
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: false
    allow-any-item: false
  disable-REAL: false
  disable-REAL_TRANSPARENT: true
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
  fix-liquids-flow: true
  fix-floating-blocks: true
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: true
liquids:
  enabled: true
huds:
  enabled: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    replace-only-packets: true
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    interval-rendering-packets-ticks: 1
    emotes: true
    optimized-packets: true
recipes:
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
  hide-vanilla-unrecognized-recipe-errors: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  fix-packet-too-large-kick: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
    log-recipes-unknown-item: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-generation: false
    log-loading-no-world: true
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-generation: false
    log-loading-no-world: true
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-generation: false
    log-loading-no-world: true
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
chat-preview: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

Other spark reports where the plugin is lagging
https://spark.lucko.me/TqrzTmsqTR
https://spark.lucko.me/VCgejWHVzR

**Comment by Maroon28** [comment]
Here's another spark report, the lag spikes are much more major in this one. 17 players on. 
https://spark.lucko.me/gBe3ReelGz

**Comment by LoneDev6** [comment]
Hello!
This probably is due to the tab emojis/effects replacer.
It can have some issues if you have a TAB plugin installed which sends a lot of TAB packets to the clients.

![immagine](https://user-images.githubusercontent.com/27242001/180397929-129efcd8-ece4-4d8d-872f-84be1ebdb792.png)

![immagine](https://user-images.githubusercontent.com/27242001/180397977-03301d0b-6820-4f92-8c86-82c7cbf5a80e.png)


Disable it and let me know, thanks!

**Comment by Maroon28** [comment]
Ah yep, that was the exact issue! We had a little logo emoji on our tablist to make it look a bit more stylish, and we were using the TAB plugin so that makes perfect sense. 

However though I believe there should be some sort of comment as a warning above both of those options, and maybe have them disabled by default? The lag spikes are way too major to be worth it imo, and I don't think many people will be able to pin down the issue to those emojis, especially due to the obfuscation of the plugin and not many knowing how to use spark etc.

**Comment by LoneDev6** [comment]
Yes you're right.
This is the only part of ItemsAdder which cannot be optimized because of how the TAB packets work.
I will eventually totally remove this replace feature because it's more harmful than helpful.

I'll also work on finding a way to optimize that but I really doubt there is.

**Comment by LoneDev6** [comment]
I'm thinking about removing this feature since it just causes confusion
