### ISSUE TITLE
Ores exposed to air

### ISSUE THREAD

**Issue by Truongvv10** [PluginBugs/Issues-ItemsAdder#1865]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Wassabi#0317

### Describe the solution you'd like

Option for blocks generating in 
- Exposed air only
- Exposed air and in not exposed air
- Not in exposed air

### Is your feature request related to a problem?

Yes

### Describe alternatives you've considered

spawn_condition:
  exposed_air: true/false (true, will spawn in exposed air and in ground | false, will only spawn in ground with no exposure of air)
  exposed_air_only: true/false

**Comment by LoneDev6** [comment]
This is a bit hard to implement without making the generation heavier on CPU.
I'd avoid implementing this feature sincerely.
