### ISSUE TITLE
Better resourcepack management

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#1866]
# Moved to https://github.com/PluginBugs/Issues-ItemsAdder/issues/2097 because to cleanup comments.

(check comment history to read old ideas)

**Comment by ProfessionalBoatDrifter** [comment]
I think it sounds good 👍

**Comment by ItzASecret** [comment]
I like this a lot, but it also seems like it's really complicated for no reason. I ended up just removing the water bar from my server, because we couldn't use water bottles in crafting or make water bottles give thirst or drink directly from a water block itself. So we ended up using boiled water buckets instead, but in terms of player progression, I wouldn't want my player to have to mine and get iron before they can simply drink water. Same thing here for the redstone requirement for the water purifier, players would have to seek redstone before they could drink water properly which isnt that hard I imagine but still, the alternative is drink normal water and get poisioned. I also dont think that its very "vanilla" feeling, not saying don't add it, but add a way to disable it or tweak it or something. In terms of the recource pack management, that sounds great.

sorry for the long comment lmao

**Comment by LoneDev6** [comment]
Sorry I don't understand how this comment has something to do with the new resources management idea

**Comment by fnrcum** [comment]
The better resource pack management is (imo) a great idea as it would make IA almost by default compatible with any other plugins that have their own resource packs that were not built by default to be compatible with IA.

This is great as it's useful regardless of where that resource pack comes from (be it datapack or plugin)

**Comment by LoneDev6** [comment]
`plugins/ItemsAdder/content/`
``` 
content
     |- pack1
     |    |- configs/
     |    |    |- some-file.yml
     |    |    |- some-file-2.yml
     |    |    |- some-recipes-file.yml
     |    |    |- ...
     |    |
     |    |- resourcepack/
     |         |- namespace/
     |         |    |- ... # The usually asset directories (textures/, models/, ...)
     |         |- ... # other namespaces perhaps...
     |
     |
     |- pack2
     |    |- configs/
     |    |    |- some-file.yml
     |    |    |- some-file-2.yml
     |    |    |- some-recipes-file.yml
     |    |    |- ...
     |    |
     |    |- resourcepack/
     |         |- namespace/
     |         |    |- ... # The usually asset directories (textures/, models/, ...)
     |         |- ... # other namespaces perhaps...
     |
```

This allows you to basically just delete `packX` and have all the files about a single pack deleted without worrying about finding them in the resourcepack.


This update will also make ItemsAdder stop generating json data (fonts, translations, items) in the minecraft namespace, it will just merge them all and put them in the zip during compression.
This will avoid confusion and potential unwanted data.
Another idea is to make ItemsAdder generate the blockstates and item files (with CustomModelData) inside a temp folder, for debug purposes and to keep track of used IDs.

**Comment by mschoenUsp** [comment]
You have to merge conflicting JSON files as well. If multiple folders contain the same JSON file, with different custom extensions, they need to be merged intelligently. Similar to merge changes with systems like GIT. Ideally, there should be an option to either abort on merge conficts, or ignore them.

**Comment by Andre601** [comment]
> You have to merge conflicting JSON files as well. If multiple folders contain the same JSON file, with different custom extensions, they need to be merged intelligently. Similar to merge changes with systems like GIT. Ideally, there should be an option to either abort on merge conficts, or ignore them.

I think by default should IA cancel any JSON merging if two files have the same values... Or if it doesn't take too much of a toll on performance merge values that are different and skip those that are equal.

**Comment by LoneDev6** [comment]
> You have to merge conflicting JSON files as well. If multiple folders contain the same JSON file, with different custom extensions, they need to be merged intelligently. Similar to merge changes with systems like GIT. Ideally, there should be an option to either abort on merge conficts, or ignore them.

The plugin will skip duplicate entries and warn about it in the logs. Duplicate entries will be added only one time based on the folders priority (which can be forced in a particular configuration).

**Comment by LoneDev6** [comment]
# How to merge a resourcepack

## 1

Create a new folder inside `plugins/ItemsAdder/contents/`, for example call it `pack_to_merge_1`

## 2

Open the resourcepack zip you want to merge, for example download this https://www.planetminecraft.com/texture-pack/kapteyn-s-new-12x12-resource-pack-early-access/

## 3 

Create a new folder called `resourcepack` inside the new folder created on **step 1**, in this example `plugins/ItemsAdder/contents/pack_to_merge_1/resourcepack/`

## 4
Extract the assets folder inside `plugins/ItemsAdder/contents/pack_to_merge_1/resourcepack`

![image](https://user-images.githubusercontent.com/27242001/202170055-9434cb51-d782-4eeb-a542-749277118313.png)


## 5 

Run /iazip

## Done

![image](https://user-images.githubusercontent.com/27242001/202170662-3a521ac4-24e7-4a9c-9e5a-d08bd3cef0b0.png)
![image](https://user-images.githubusercontent.com/27242001/202170679-9d315677-c868-4c63-8ad5-9c30b6cc00d9.png)

**Comment by LoneDev6** [comment]
# Common questions 

## Are old contents in `ItemsAdder/data/resource_pack` and `ItemsAdder/data/items_packs` folders still compatible?

Yes. ItemsAdder will load them automatically, but you should consider moving them to the new format to avoid mistakes and get a better organized pack.

**Comment by LoneDev6** [comment]
# Moved to https://github.com/PluginBugs/Issues-ItemsAdder/issues/2097 because to cleanup comments.
