### ISSUE TITLE
REAL_TRANSPARENT arrow bug

### ISSUE THREAD

**Issue by cats-love** [PluginBugs/Issues-ItemsAdder#1868]
### Discord tag (optional)

cats#0935

### What happened?

Arrows drop when using a bow on a REAL_TRANSPARENT block.
It is important to note that infinite arrows will also drop as arrows.
Is there any way to prevent arrow copying?

### Steps to reproduce the issue

If you shoot an arrow at the leaf of a tree with REAL_TRANSPARENT , the arrow will drop.
Same goes for infinite arrows.

### Server version

1.19

### ItemsAdder Version

[3.2.2-beta5]

### ProtocolLib Version

# 577

### LoneLibs Version

[1.0.20]

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/87476958/180650465-a3c87a19-96ba-4ed1-8edb-eac1f73de7e2.png)
![image](https://user-images.githubusercontent.com/87476958/180650487-4ee035ab-78b1-4051-b825-2b6fddab3a7c.png)
![image](https://user-images.githubusercontent.com/87476958/180650490-94613ae2-1673-4ed0-b85b-5740d7837dde.png)

**Comment by LoneDev6** [comment]
Please make a video

**Comment by cats-love** [comment]
https://user-images.githubusercontent.com/87476958/180653225-d5a0ea4f-cc9f-4860-ad64-d12cfbe66822.mp4
