### ISSUE TITLE
Customizable Event Cooldown

### ISSUE THREAD

**Issue by Herobrine15432** [PluginBugs/Issues-ItemsAdder#1871]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Herobrine15432#0887

### Describe the solution you'd like

I wish it were possible to customize the cooldown of the ItemsAdder events. What I would like is to be able to change the cooldown message in a more customizable way, being able to **specify the text to show and how to show the tex**t (_ex: action bar, title, chat or other_). Also I would like it to be possible to **specify different cooldowns for individual actions** because reading in the wiki it seems possible to specify a general cooldown but I would like to have for example a cooldown for the left click separate from that for the right click
This would make it easier to create custom weapons as it is difficult right now to make weapons other than swords or bows

### Is your feature request related to a problem?

It is very bad to see the cooldown text as title in some cases, this reduce the possibility of customizable the items that use actions

### Describe alternatives you've considered

.

**Comment by LoneDev6** [comment]
I think would be nice to add a proper HUD for that instead.
This will allow to show cooldown on screen for a better immersion, instead of text.

For example something like this which will be shown only when you try to use an item which has cooldown.

![image](https://user-images.githubusercontent.com/27242001/230136620-49c365c2-8a78-40cb-8625-29bb5ed89af1.png)
