### ISSUE TITLE
Placing solid furniture next to blocks only allows placement in one direction

### ISSUE THREAD

**Issue by Mike5357** [PluginBugs/Issues-ItemsAdder#1872]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Mike🎤#5357

### What happened?

Placing solid/rotatable item frame furniture up against a wall/another solid block causes its rotation to be locked.

### Steps to reproduce the issue

1. Create an item frame furniture that is solid:true and rotatable
2. Place it normally, away from any blocks and it rotates and places correctly. But when placing it on the ground next to any solid block (like up against a wall) it will not place rotated correctly- it always faces south(?)

### Server version

CraftBukkit version 3096a-Spigot-9fb885e-af1a232 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
    - another Discord thread showed this also happening in 1.19 as well: https://discord.com/channels/533407895010803753/995762303792336957

### ItemsAdder Version

ItemsAdder version 3.2.3

### ProtocolLib Version

5.0.0-SNAPSHOT-b577 

### LoneLibs Version

LoneLibs version 1.0.20

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: "classic_hotel"
items:
  classic_hotel_bar_counter_middle:
    display_name: "Bar Counter Middle"
    permission: props.admin
    resource:
      material: PAPER
      generate: false
      model_path: classic_hotel_bar_counter_middle
    behaviours:
      furniture:
        entity: item_frame
        small: false
        solid: true
        fixed_rotation: false
        placeable_on:
          walls: false
          ceiling: false
          floor: true
```

### Screenshots/Videos (you can drag and drop files or paste links)

In the attached video, I first placed this furniture with solid:FALSE, showing that it places correctly. Then I did /iareload to switch it to solid:TRUE and it no longer places facing in the correct direction when next to another solid block.
https://user-images.githubusercontent.com/12630858/180813567-3e1b7a12-505e-421f-a094-894863094840.mp4

**Comment by LoneDev6** [comment]
Seems introduced by this bugfix: https://github.com/PluginBugs/Issues-ItemsAdder/issues/1456

I'll publish an update, thanks

**Comment by Mike5357** [comment]
Confirmed resolved, thank you!
