### ISSUE TITLE
Problem when teleporting a custom entity with API.

### ISSUE THREAD

**Issue by FrancoBM12** [PluginBugs/Issues-ItemsAdder#1873]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

FrancoBM#2980

### What happened?

Hi, I am using the api to create an entity that only one player can view.
```java
CustomEntity.spawn(namespaceId, location, viewers, frustumCulling, function)
```
![](https://cdn.discordapp.com/attachments/1000556522587312289/1000556525095493712/unknown.png)

and finally I teleport the entity.
```java
customEntity.teleport(Location)
```
![](https://cdn.discordapp.com/attachments/1000556522587312289/1000556525565247498/unknown.png)

the complete code to spawn the entity and teleport it:
![image](https://user-images.githubusercontent.com/36641683/180820991-3b45fc87-52dc-4be8-a8b8-9f92c5c0277e.png)

The problem is when I do this.
In ItemsAdder_3.2.2-beta5 version it works fine, but in ItemsAdder_3.2.3 version it stops working....
I would like to know if I am doing something wrong?

ItemsAdder_3.2.2-beta5:
https://youtu.be/ArgEWTAnzW8

ItemsAdder_3.2.3:
https://youtu.be/wJ5XEQcfL2U

### Steps to reproduce the issue

1. teleports to the single player entity in the ItemsAdder version ItemsAdder_3.2.2-beta5
2. and then in the ItemsAdder version ItemsAdder_3.2.3
3. done.

### ItemsAdder Version

ItemsAdder_3.2.3

### ProtocolLib Version

4.8.0

### LoneLibs Version

1.0.20

**Comment by LoneDev6** [comment]
Spigot/Paper version?

**Comment by FrancoBM12** [comment]
Paper 1.18.2

**Comment by LoneDev6** [comment]
Basically the entity rotations are not updated, correct?

**Comment by LoneDev6** [comment]
Anyway, the entity doesn't need to be teleported after spawn, it's already in the specified spawn location.
