### ISSUE TITLE
ItemsAdder + ViaVersion Issue

### ISSUE THREAD

**Issue by Renadra** [PluginBugs/Issues-ItemsAdder#1876]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Ren.#1990

### What happened?

Hello

I asked about this issue on the IA discord a good while back and was told I just had to update dependencies most likely - this never worked. 

When I use ViaVersion to try and add 1.19 support to my 1.18 server (Keeping it 1.18 as a bunch of things I use hasnt been updated to 1.19 yet), I get "kicked" when I try to join the server. This happens when it tries to load a resource pack. 

Disabling the automatic resourcepack loading allows me to get on the server, so I know it is something related/happening in the step where it sends a resourcepack to a user and when they start downloading it. 

The error I get is the following: "Internal Exception: io.netty.handler.codec.DecoderExeption: Received unexpected null component"

I obviously can't say whether this is related to IA or something else - I am here because it seemed to be related to the RP loading.

### Steps to reproduce the issue

Install latest version of IA + Dependencies on 1.18.2 Server.
Load up the game and try to connect.
Get kicked with error when you attempt to download a resourcepack.

### Server version

[26.07 20:31:41] [Server] [INFO] Checking version, please wait...
[26.07 20:31:42] [Server] [INFO] This server is running Paper version git-Paper-387 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: df630a2 on ver/1.18.2)
[26.07 20:31:42] [Server] You are running the latest version
[26.07 20:31:42] [Server] Previous versiongit-Paper-386 (MC: 1.18.2)

### ItemsAdder Version

ItemsAdder Version 3.2.3

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.20

### LightAPI Version (optional)

LightApi Version bukkit-5.3.0 (build SNAPSHOT)

### LibsDisguises Version (optional)

LibsDisguises version 10.0.29

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/9192429/latest.log)

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: true
    self-host:
      enabled: false
      server-ip: 127.0.0.1
      pack-port: 8163
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: false
  delay-ticks: 5
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: true
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    - bbmodel
    - iaentitymodel
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-resources: false
  extract-default-configs: false
  legacy_pack: true
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: false
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: false
liquids:
  enabled: false
huds:
  enabled: false
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: false
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
    tab-header-footer:
      enabled: false
entities:
  max-furniture-vehicles-per-chunk: 35
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: false
    emotes: false
    interval-rendering-packets-ticks: 1
    optimized-packets: true
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
    log-recipes-unknown-item: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
chat-preview: false
```

**Comment by LoneDev6** [comment]
> I asked about this issue on the IA discord a good while back and was told I just had to update dependencies most likely - this never worked.

You actually have to always have the latest versions of the dependencies, it's not a myth.
Anyway don't update ProtocolLib until I release IA 3.2.3c since ProtocolLib introduced a change which removes some features I use in IA, so I have to push a fix for that. 


> The error I get is the following: "Internal Exception: io.netty.handler.codec.DecoderExeption: Received unexpected null component"

I received some reports about that, I can't reproduce the issue so it's hard to for me to identify it.

So basically if 1.19 client joins 1.18 server it gets kicked on resourcepack apply?

**Comment by Renadra** [comment]
That is correct LoneDev6 - there are no errors or anything at all on console when it happens. I recorded a video so I can show you the whole "process" if that helps - if it does, please send me a DM on Discord so I can send you the link if possible!

As far as I can tell, everything on my server is fully updated and things are how they should be.

**Comment by LoneDev6** [comment]
The strange thing is that I tried to setup a 1.18.2 server with ViaVersion+ViaBackwards, join with a 1.19 client and I don't get kicked

**Comment by Renadra** [comment]
Mhm I havent got a clue haha. Just tried reinstalling viaversion, viabackwards, IA and all depdencies. I used ProtocolLib 4.6.0 (Should it be lower/higher in this case? I tested with 4.8.0 which was latest too, but downgraded to test again after your comment).

It joins the server, i see it gets a texture prompt, where it states itll download/apply the resourcepack from your plugin, then i get the red Mojang loading screen, once that is done, i get the disconnect/error that I mentioned.

These are all the plugins present on the server: [27.07 15:46:35] [Server] [INFO] Plugins (49): AquaticCrates, BattlePass, BetterRTP, BKCommonLib, Chunky, ChunkyBorder, Citizens, CMILib, ConsoleSpamFix, DeluxeMenus, Essentials, EssentialsSpawn, FastAsyncVoxelSniper, FastAsyncWorldEdit (WorldEdit), GCore, goBrush, HeadDatabase, HolographicDisplays, ItemsAdder, Jobs, Lands, LibsDisguises, LightAPI, LoneLibs, LPC, LuckPerms, MCCosmetics, mcMMO, mcmmo-placeholders, MCPets, MMOItems, ModelEngine, Multiverse-Core, MVdWPlaceholderAPI*, MyCommand, MythicLib, MythicMobs, PlaceholderAPI, PlayerWarps, PlugMan, ProtocolLib, QuestCreator, Shopkeepers, ShopkeepersAddon, TAB, Vault, ViaBackwards, ViaVersion, WorldGuard

**Comment by LoneDev6** [comment]
Another customer has the same issue.
I'm sure it's not about the resourcepack apply since I get kicked even before accepting the pack.

Can you try to check if disabling this option fixes the issue?
```yml
  title:
    enabled: false
```

**Comment by Renadra** [comment]
Many apologies for the slow reply! Been out of the house.

I just tested this right now, and disabling the title fixed it for me! 

I havent checked whether or not you have already released a fix for this, so it was tested on versions and such that i used when i originally started the support ticket.

**Comment by LoneDev6** [comment]
Interesting, so seems that the title packet somehow is making clients kicked, might it be a ViaVersion bug?

**Comment by Renadra** [comment]
It could very well be! I never contacted them about it as I had no clue
where it originated from haha. I can try reach out to them and see what
they think

man. 8. aug. 2022 15.20 skrev LoneDev ***@***.***>:

**Comment by LoneDev6** [comment]
Cannot reproduce the issue.

```
[17:48:33 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b569
[17:48:33 INFO]: Provides read/write access to the Minecraft protocol.
[17:48:33 INFO]: Authors: dmulloy2 and comphenix
> version viaversion
[17:48:35 INFO]: ViaVersion version 4.4.2-SNAPSHOT
[17:48:35 INFO]: Allow newer clients to join older server versions.
[17:48:35 INFO]: Authors: _MylesC, creeper123123321, Gerrygames, kennytv and Matsv
> version viabackwards
[17:48:41 INFO]: ViaBackwards version 4.4.1
[17:48:41 INFO]: Allow older Minecraft versions to connect to a newer server version.
[17:48:41 INFO]: Website: https://github.com/ViaVersion/ViaBackwards
[17:48:41 INFO]: Authors: Matsv, kennytv, Gerrygames, creeper123123321 and ForceUpdate1
> version
[17:48:43 INFO]: This server is running Paper version git-Paper-387 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: df630a2 on ver/1.18.2)
You are running the latest version
```

**Comment by Euphonique** [comment]
I have the latest Viaversion too, and it works on my server without problems. Guess the problem has to be something else.

**Comment by mitchngwen** [comment]
Issue https://github.com/PluginBugs/Issues-ItemsAdder/issues/1951 is not a duplicate please reopen and get it fixed

**Comment by LoneDev6** [comment]
Solved on: https://github.com/PluginBugs/Issues-ItemsAdder/issues/1964

```yml
items:
  give_death_location_maps: false
```
