### ISSUE TITLE
Get furniture by its hitbox barrier blocks

### ISSUE THREAD

**Issue by bckd00r** [PluginBugs/Issues-ItemsAdder#1879]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

if#0011

### Describe the solution you'd like

I want an API to control hitboxes of furniture.

boolean - CustomFurniture.byAlreadyHitBox(Block block)

ArrayList block or location - CustomFurniture.getHitBoxBlocks("namespacedID")

### Is your feature request related to a problem?

yes furniture

### Describe alternatives you've considered

I think that this will be added to the API in a simple way, this has been said before and you said that you can add it too. on the #coding channel

### Additional context

://

**Comment by LoneDev6** [comment]
Please explain why you need this api method, provide some details
