### ISSUE TITLE
[Suggestion] Allow for placeholderapi

### ISSUE THREAD

**Issue by ampaddon** [PluginBugs/Issues-ItemsAdder#188]
**Is your feature request related to a problem? Please describe.**
I have a problem getting survivalplus's placeholderapi to enter the thrust system.  It thinks its own with a new values, but it cant except it for other placeholder.

other features that could benefit from this, is emoticons in the scoreboard, and other values around.

**Describe the solution you'd like**
I would like it so that the thrust system, could us placeholderapi so that i can have it get it from other places.

**Describe alternatives you've considered**
As we are going to use ItemsAdder for the server, and as slimefun is getting taken from our server, the idea is to get more universal, and custom texture system.

**Additional context**
The ability to go both ways is cool, but getting the placeholderapi to work in the trust system first, is more important in my thoughts.

**Comment by LoneDev6** [comment]
Thanks for the suggestion, I added the placeholder in the new update.
https://itemsadder.plugin.ga/plugin-usage/placeholderapi
