### ISSUE TITLE
Some textures dont load (custom and vanilla ones)

### ISSUE THREAD

**Issue by Palgia** [PluginBugs/Issues-ItemsAdder#1885]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

I tried to create my first sword on this version of ItemsAdder. After that, I've done /iazip to load my pack.

The result is my texture doesn't load AND the texture of vanilla diamond sword is gone. Tried the same thing with diamond axe, it was the same result. 

Just to see if I've done something wrong, I installed the default pack. A lot of swords doesn't load. (I touched nothing).

Finally, I deleted my sword file and all lost vanilla textures were still... lost. I tried /iacleancache items and /iazip. There's nothing I can do to fix my pack.

### Steps to reproduce the issue

- Create a sword or whatever
- /iazip
- done

### Server version

This server is running Paper version git-Paper-66 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: b7faa65)
You are 15 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-387 (MC: 1.18.2)

### ItemsAdder Version

3.2.3e-2

### ProtocolLib Version

5.0.0-SNAPSHOT-b577

### LoneLibs Version

1.0.20

### FULL server log

No erros shown in console

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: osmonia
items:
  test-sword:
    enabled: true
    display_name: Test sword
    resource:
      material: DIAMOND_SWORD
      generate: true
      textures:
        - item/custom_epee/fracas_des_geants
```

### Screenshots/Videos (you can drag and drop files or paste links)

![2022-08-03_04 00 34](https://user-images.githubusercontent.com/76446516/182510151-65ffc5f6-19bd-4367-84e4-307500b080b2.png)
![2022-08-03_04 05 08](https://user-images.githubusercontent.com/76446516/182510152-3017cd42-75cc-43c4-827d-0fa3c66e9a8e.png)

**Comment by LoneDev6** [comment]
https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown#enable-output-log

**Comment by LoneDev6** [comment]
This basically happens because the game will stop loading every texture for a particular material (for example PAPER, DIAMOND_SWORD...) if it can't load a texture/model of a single custom item.

The default pack was tested before publishing so I'm sure they load correctly, so there surely is a misconfigured item in your pack
