### ISSUE TITLE
Emojis no longer working in chat after updating.

### ISSUE THREAD

**Issue by Cobalt246** [PluginBugs/Issues-ItemsAdder#1886]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Dr. Terror#0222

### What happened?

Hello, after recently updating protocollib, I also had to update ItemsAdder (so it still functions).

After doing so emojis in chat stopped working. This is all I did.

I don't have any chat management plugin other than VaultChatFormatter, which I really don't think is the problem since it's recommended by you and I didn't update it at all.

Emojis still work on signs.

### Steps to reproduce the issue

1. Update to latest protocollib version.

2. Update to latest Itemsadder version.

3. Restart server

4. Try to use emojis in chat.

### Server version

This server is running Paper version git-Paper-39 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 37afe98)
You are 42 version(s) behind

### ItemsAdder Version

ItemsAdder version 3.2.3e-2

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b587

### LoneLibs Version

LoneLibs version 1.0.19

### LightAPI Version (optional)

LightAPI version bukkit-5.3.0 (build SNAPSHOT)

### LibsDisguises Version (optional)

LibsDisguises version 10.0.29-SNAPSHOT

### FULL server log

[latest (4).log](https://github.com/PluginBugs/Issues-ItemsAdder/files/9250488/latest.4.log)

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: 91.109.116.4
      pack-port: 8001
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: false
    lock-player: false
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: false
      extreme: false
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    - bbmodel
    - iaentitymodel
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-resources: false
  extract-default-configs: false
  legacy_pack: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    search-also-in-these-biomes:
      enabled: false
      biomes:
      - BEACH
      - BIRCH_FOREST
      - BIRCH_FOREST_HILLS
      - FOREST
      - MOUNTAINS
      - MOUNTAIN_EDGE
      - GRAVELLY_MOUNTAINS
      - PLAINS
      - RIVER
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: false
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: false
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 50
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    interval-rendering-packets-ticks: 1
    emotes: false
    optimized-packets: true
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: true
      on-pickup:
        any: true
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
    log-recipes-unknown-item: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: false
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: true
    log-single-loaded-overwrite: true
    log-single-skip: true
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
chat-preview: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

Plugins List
![list](https://user-images.githubusercontent.com/89671879/182587653-10e8c980-2fba-4181-9aaa-c85ca0fbe2a7.PNG)

**Comment by Cobalt246** [comment]
Also just to note: I NEVER use PlugMan to load or unload ItemsAdder, or any of its dependencies.

**Comment by LoneDev6** [comment]
> Emojis no longer working in chat after updating

after updating what?
I mean, what did you update in order to make them stop working?

**Comment by Cobalt246** [comment]
> > Emojis no longer working in chat after updating
> 
> after updating what? I mean, what did you update in order to make them stop working?

Itemsadder.

**Comment by Cobalt246** [comment]
My players have also found:

Hammers no longer work.

Crafting cheese kicks them from the server.

**Comment by LoneDev6** [comment]
So you basically updated just ItemsAdder and ProtocolLib?
What happens if you downgrade to the previous versions?

**Comment by Cobalt246** [comment]
> 

Downgrading breaks the plugin entirely. Nothing works anymore.

I was using ItemsAdder 3.2.0c-beta6 and ProtocolLib-5.0.0-SNAPSHOT (I have no idea which build specifically.)

**Comment by Cobalt246** [comment]
Should you have the time, feel free to contact me on discord and I'll gladly give you access to my Pterodactyl panel, as well as operator on the server.

**Comment by Cobalt246** [comment]
?

**Comment by play275** [comment]
> ?
I had the same problem, so I rolled back to ItemsAdder_3.2.3c, the emoji can be displayed, the hammer can be used, but the peeled potatoes cannot be crafted, and once crafted, they will be kicked out of the server.

**Comment by Cobalt246** [comment]
> play275

what version of protocollib are you using?

**Comment by play275** [comment]
https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by Cobalt246** [comment]
> https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

This fixed my emojis, but it still seems like hammers aren't working.

Nonetheless, thanks a bunch!

**Comment by Cobalt246** [comment]
So.... just not getting a reply anymore?

**Comment by LoneDev6** [comment]
This whole issues report is extremely vague, confusing and doesn't include useful information.
I'm always open to fixing issues and helping people but this report absolutely doesn't allow me to understand how to reproduce the reported issue.


I need also a log of when the issue occurred, not a random log.
Thanks

**Comment by LoneDev6** [comment]
So basically updating ProtocolLib is the cause of the issue?

**Comment by LoneDev6** [comment]
So it seems something changed in ProtocolLib?

**Comment by TonyMontero** [comment]
Actually updating to the latest protocollib doesn't fix the issue (at the moment)

**Comment by LoneDev6** [comment]
Seems Mojang changed again how chat works in 1.19.2.
A fix will be published, thanks
