### ISSUE TITLE
NoSuchMethodError: 'boolean net.minecraft.world.entity.Entity.du()'

### ISSUE THREAD

**Issue by DarkyCat** [PluginBugs/Issues-ItemsAdder#1888]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

I recently ported a build to 1.19.1 and found that the ItemsAdder was kicking players on login with the reason "boolean net.minecraft.world.entity.Entity.du()". If I remove the ItemsAdder the problem is fixed. I think this is some kind of problem with the NMS.

### Steps to reproduce the issue

just join to server

### Server version

This server is running Mirai version git-Mirai-17 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: 82b4175 on HEAD)
You are on the latest version!

### ItemsAdder Version

[20:30:20 INFO]: ItemsAdder version 3.2.3e-2
[20:30:20 INFO]: Customized Minecraft without client mods!
[20:30:20 INFO]: Website: devs.beer
[20:30:20 INFO]: Author: LoneDev

### ProtocolLib Version

[20:30:32 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b587
[20:30:32 INFO]: Provides read/write access to the Minecraft protocol.
[20:30:32 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[20:30:54 INFO]: LoneLibs version 1.0.20
[20:30:54 INFO]: Collection of libs used by my plugins
[20:30:54 INFO]: Authors: LoneDev and others

**Comment by LoneDev6** [comment]
Is your Spigot build updated to the latest version?
The plugin was tested on 1.19.1 and works fine

**Comment by DarkyCat** [comment]
Fixed by recreating plugin configuration

**Comment by LoneDev6** [comment]
What did you change?
Thanks
