### ISSUE TITLE
[Api] add the possibility to add or get from a bar

### ISSUE THREAD

**Issue by NotCatto25** [PluginBugs/Issues-ItemsAdder#1890]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

From the api get and add to a bar for example the thrist bar 

### Is your feature request related to a problem?

No.

### Describe alternatives you've considered

none

**Comment by NotCatto25** [comment]
`new PlayerQuantityHudWrapper((PlayerHudsHolderWrapper) player, "thirst").getFloatValue()` i tried already something like this but it is not working and I tried seeing it in the docs and I asked to my client to search on the discord but he didn't find nothing

**Comment by LoneDev6** [comment]
I confirm the stat name is `thirst`: https://github.com/ItemsAdder/DefaultPack/blob/c39c55df8b4556f143a6c2aac17d3fbc9a6ef8a8/data/items_packs/iasurvival/thirst/hud_thirst.yml#L28

> i tried already something like this but it is not working 

This is very vague.
I also have no idea why you're casting player to PlayerHudsHolderWrapper, what?
Please read the guide: https://itemsadder.devs.beer/developers/java-api/huds-guis#access-mana-bar-value-example
