### ISSUE TITLE
[API] CustomBlockBreakEvent invalid in new version ItemsAdder

### ISSUE THREAD

**Issue by Caishangqi** [PluginBugs/Issues-ItemsAdder#1891]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Caihuashe#6817

### What happened?

When I update ItemsAdder to the latest version 3.2.3e-2, the API CustomBlockBreakEvent is not triggered when I break a custom block. In version 3.2.0c the CustomBlockBreak API works fine. 

### Steps to reproduce the issue

1. Register a Listener
2. Let the listener inspect CustomBlockBreakEvent 
3. print anything under the listener
4. Break a custom block
5. nothing happend

### Server version

This server is running Paper version git-Paper-359 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 78e6431)

### ItemsAdder Version

3.2.3e-2

### ProtocolLib Version

4.8.0

### LoneLibs Version

1.0.19

### Screenshots/Videos (you can drag and drop files or paste links)

https://user-images.githubusercontent.com/39553613/183042676-0dcdab6b-1ee7-46e9-b811-16590e21662f.mp4

**Comment by LoneDev6** [comment]
For me it's triggered correctly.
I can't see your video, it seems it has only audio.

```java
    @EventHandler
    private void onCustomBlockBreakEvent(CustomBlockBreakEvent e)
    {
        System.out.println(e.getClass().getName() + " " + e.getPlayer().getName() + " " + e.getNamespacedID());
    }
```

**Comment by Caishangqi** [comment]
https://user-images.githubusercontent.com/39553613/183511996-b173ebcf-016d-4442-af7b-0a006f9f244a.mp4

**Comment by Caishangqi** [comment]
https://github.com/Caishangqi/homeward-plugin-cooking/blob/8abf1faabfce5639651105784674782adf3033e3/src/main/java/homeward/plugin/homewardcooking/compatibilities/provided/itemsadder/ItemsAdderCompatibility.java#L95

I register 3 Listeners in one class, the other two are `CustomBlockInteractEvent`, and `CustomBlockPlaceEvent`, only `CustomBlockBreakEvent` can not trigger

**Comment by Caishangqi** [comment]
> For me it's triggered correctly. I can't see your video, it seems it has only audio.
> 
> ```java
>     @EventHandler
>     private void onCustomBlockBreakEvent(CustomBlockBreakEvent e)
>     {
>         System.out.println(e.getClass().getName() + " " + e.getPlayer().getName() + " " + e.getNamespacedID());
>     }
> ```

https://github.com/Caishangqi/homeward-plugin-cooking/blob/8abf1faabfce5639651105784674782adf3033e3/src/main/java/homeward/plugin/homewardcooking/compatibilities/provided/itemsadder/ItemsAdderCompatibility.java#L95

I register 3 Listeners in one class, the other two are `CustomBlockInteractEvent`, and `CustomBlockPlaceEvent`, only `CustomBlockBreakEvent` can not trigger

**Comment by LoneDev6** [comment]
I can't manage to trigger the issue.
Maybe you didn't register the listener class?

`Bukkit.getPluginManager().registerEvents(listener, plugin);`
