### ISSUE TITLE
[BUG] Shaders core with custom armor color with opengl rendering not working

### ISSUE THREAD

**Issue by NotCatto25** [PluginBugs/Issues-ItemsAdder#1892]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

when my client tries to add the shaders core I made don't work but in singleplayer works

### Steps to reproduce the issue

1. Make shaders core
2. Load it on the texture
3. Try the color inputted
4. don't work

### ItemsAdder Version

3.2.3e-2

### ProtocolLib Version

4.7.0

### LoneLibs Version

1.0.20

**Comment by LoneDev6** [comment]
How is this related to ItemsAdder?
