### ISSUE TITLE
[BUG] Bypassing smelting permissions

### ISSUE THREAD

**Issue by spathizilla** [PluginBugs/Issues-ItemsAdder#190]
**Describe the bug**
With IA 2.0.14 you can bypass any of the smelting permissions by simply having the ores loaded by a hopper into the furnace. Any player trying to put items in will be given the permission denied message. Through using the hopper to load items to smelt, you can obtain the output items without having the correct permissions.

**To Reproduce**
1. Remove all permissions on self
2. Place furnace with hopper on top
3. Put fuel in furnace
4. Put in mysterious ore into hopper
5. Watch as it smelts into mysterious material

**Info (please complete the following information):**
[00:52:25 INFO]: [PlugMan] Plugin Information: ItemsAdder
[00:52:25 INFO]: - Version: 2.0.14

[00:52:35 INFO]: Server version: Paper(226) 1.15.2-R0.1-SNAPSHOT

**Comment by LoneDev6** [comment]
Do you have any idea to fix that?
They can put these ores also in chests and then in hoppers, I cannot keep track of these items as it would cause heavy lag on the server

**Comment by LoneDev6** [comment]
A solution would be to implement a new property which blocks some items to be automatically put into the furnace by hoppers, but this would cause a lot of CPU processing because of how ticking works.
