### ISSUE TITLE
Furniture can't be placed on Beehives

### ISSUE THREAD

**Issue by konfix** [PluginBugs/Issues-ItemsAdder#1902]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Konfix#3113

### What happened?

Hi,
I don't know if this is actually a bug, furniture can't be placed on beehive blocks for some reason. I've searched everywhere but seems like no one has reported this yet.

### Steps to reproduce the issue

1. Place a beehive block;
2. Try to place a piece of furniture on it.

### Server version

1.19.2 (Purpur-1752)

### ItemsAdder Version

IA 3.2.3d

### ProtocolLib Version

5.0.0-SNAPSHOT-b588

### LoneLibs Version

1.0.20

### Screenshots/Videos (you can drag and drop files or paste links)

![bee](https://user-images.githubusercontent.com/66477781/183980429-6029225c-6f8c-4de5-916c-4c7b834b2b39.gif)

**Comment by LoneDev6** [comment]
Because it's marked as interactable block by Minecraft, you have to shift click to place the furniture.
