### ISSUE TITLE
heads textura bug

### ISSUE THREAD

**Issue by Trypal** [PluginBugs/Issues-ItemsAdder#1907]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Trypal#0001

### What happened?

Hey,
I ran into an issue where after loading the resource pack via ItemsAdder, custom player heads start to glitch out and some of them have also some messages on them. Without ItemsAdder I don't have this issue.

### Steps to reproduce the issue

1. put in the plugin

### Server version

1.18.2 purpur

### ItemsAdder Version

ItemsAdder version 3.2.3f

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.21

### Screenshots/Videos (you can drag and drop files or paste links)

![unknown](https://user-images.githubusercontent.com/74048438/184660997-72551478-5ad2-48d2-a7b7-c65a045f23d6.png)
![unknown2](https://user-images.githubusercontent.com/74048438/184661078-672f451d-5ed1-4f98-b797-23a2ec73d26d.png)

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1606#issuecomment-1096293136
