### ISSUE TITLE
Playerstat compatibility for MMOCore

### ISSUE THREAD

**Issue by MelonCraftDE** [PluginBugs/Issues-ItemsAdder#1909]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Just compatibility with the MMOCore Plugin for playerstats (manabar, in example)
imo, no one really uses magiccraft anymore. mmocore is much better.

### Is your feature request related to a problem?

Yea, because this disallows cool playerstat features from ItemsAdder

### Describe alternatives you've considered

i doubt there is an alternative.
there is an outdated plugin from Dec 2021 to get bars instead of just text. but i'm 100% sure it would collide with IA, because it uses a texturepack.
(Plugin is called "MMOBars")

**Comment by LoneDev6** [comment]
MMOCore developer can easily hook into the ItemsAdder API in order to create HUDs.
https://github.com/LoneDev6/API-ItemsAdder

Example usage:
https://github.com/LoneDev6/RPGhuds/
