### ISSUE TITLE
Placing item frames on top of furniture barrier blocks causes them to break/pop off.

### ISSUE THREAD

**Issue by luke-devs** [PluginBugs/Issues-ItemsAdder#1913]
### Discord tag (optional)

Holmes#6657

### What happened?

Basically if you place an item frame on top of the top face of a barrier block that is tied to a furniture item it will pop off/break.

### Steps to reproduce the issue

1. Place a furniture with a solid hitbox.
2. Place an item frame on top of the top face (doesn't occur when placed on sides of barrier block)
3. It will break/pop off

### Server version

Current: git-Purpur-1735 (MC: 1.19)*

### ItemsAdder Version

ItemsAdder version 3.2.3d

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b583

### LoneLibs Version

LoneLibs version 1.0.20

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: settlerstavern
items:
  treasure_pedestal:
    display_name: Treasure Pedestal
    resource:
      material: PAPER
      generate: false
      model_path: furniture/treasure_pedestal
    behaviours:
      furniture:
        entity: item_frame
        small: false
        solid: true
        fixed_rotation: false
        hitbox:
          length: 1
          width: 1
          height: 2
        placeable_on:
          walls: false
          ceiling: false
          floor: true
```

**Comment by LoneDev6** [comment]
Please provide the YML configuration of your furniture, probably it has to do with the hitbox size of the furniture.

Thanks

**Comment by LoneDev6** [comment]
I suspect it's a Minecraft behaviour, I think the game is forcefully making itemframe removed because it is inside another entity, in this case the furniture itemframe.
Note that furniture itemframes have a big hitbox, that's why.

I'll now try to find a solution, probably it's enough to just make the hitbox a little smaller.
