### ISSUE TITLE
Option go disable Shift+Right Click Itemframes

### ISSUE THREAD

**Issue by ArgonGaming** [PluginBugs/Issues-ItemsAdder#1914]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Argon#1001

### Describe the solution you'd like

As the title says, a new feature was added recently for this to be possible, but it'd be nice if it was made an option.

### Is your feature request related to a problem?

The problem of having players rotate furnitures is pretty massive for spawn builds, etc.

### Describe alternatives you've considered

There are no alternatives

**Comment by Mike5357** [comment]
#1915 related; shift+right-clicking on an item frame should check if the player actually has permission for the area which the item frame is in before allowing the rotation.

**Comment by LoneDev6** [comment]
Thanks, a new property per-furniture will be implemented. 



> #1915 related; shift+right-clicking on an item frame should check if the player actually has permission for the area which the item frame is in before allowing the rotation.

Should already check for permissions, I'll try to reproduce the issue and let you know

**Comment by LoneDev6** [comment]
@ArgonGaming 
`shift_interact_rotate: false` will be added in the next update as furniture property

**Comment by SirCraftypants** [comment]
> shift_interact_rotate: false

Where would this be placed, as an action, under behaviour or specific properties?

**Comment by LoneDev6** [comment]
>  `shift_interact_rotate: false` will be added in the next update as **furniture property**

Under furniture properties
