### ISSUE TITLE
Shift+Right-Clicking item frames in claims with ItemsAdder installed allows rotating items in claims

### ISSUE THREAD

**Issue by Mike5357** [PluginBugs/Issues-ItemsAdder#1915]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Mike🎤#5357

### What happened?

When ItemsAdder is installed, holding Shift and right-clicking an item frame (any item frame; doesnt even need to be a Furniture piece) allows you to rotate the item inside, including inside of GriefDefender claims where the player should otherwise not have permission to. I have not confirmed if this only happens with GriefDefender or if it also affects other land-protection plugins such as WorldGuard.

Left clicking an item frame and right clicking it normally are blocked correctly in claims, however holding shift and right clicking allows the claims flags to be bypassed and the item to be rotated.

### Steps to reproduce the issue

1. Install GriefDefender (and Luckperms as it is required)- or presumably any land protection plugin
2. Create a claim with a golden shovel. 
3. Place an item frame in the claim, and put an item in it.
4. Have another player who is not trusted to the claim try to interact with the item frame. If they left or right click normally, it should be blocked. However, when holding shift and right clicking the item will rotate.

### Server version

CraftBukkit version 3096a-Spigot-9fb885e-af1a232 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### ItemsAdder Version

3.2.3f

### ProtocolLib Version

5.0.0-SNAPSHOT-b577

### LoneLibs Version

1.0.19

### FULL server log

https://mclo.gs/hWrjL4p

### Screenshots/Videos (you can drag and drop files or paste links)

https://user-images.githubusercontent.com/12630858/185724656-34a9f155-3257-430a-a056-93795fdbcde4.mp4

**Comment by LoneDev6** [comment]
I don't own GriefDefender which is premium.

Anyway I do check if the `PlayerInteractAtEntityEvent` event is cancelled or not, I don't allow rotation if it's cancelled so I guess GriefDefender is somehow not cancelling the event.
![image](https://user-images.githubusercontent.com/27242001/185885049-9a599333-25b7-4bf1-a06f-4863218c2cf9.png)

**Comment by LoneDev6** [comment]
Do you have WorldGuard installed by any chance?

**Comment by Mike5357** [comment]
Using 3.2.3i it appears to have resolved the issue of normal item frames being rotatable in GriefDefender claims thankfully, however Furniture can still be rotated by players without permission for the claim

**Comment by LoneDev6** [comment]
> Using 3.2.3i it appears to have resolved the issue of normal item frames being rotatable in GriefDefender

I don't see how since I don't handle normal itemframes, I only handle furniture itemframes

**Comment by Mike5357** [comment]
Sorry for the misunderstand; What I meant was the issue with *normal* item frames no longer occurs after updating, but the issue IS still present with furniture item frames in claims.
