### ISSUE TITLE
api method to get all of the items adder itemstacks

### ISSUE THREAD

**Issue by jman13378** [PluginBugs/Issues-ItemsAdder#1921]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Jonathan_Nathan#9938

### Describe the solution you'd like

a get method we can use to get a custom item stack without having the namespace so something like `getItems.get(#)` and this will let us get an item in a location of the gui without having the namespace or maybe a way to get the ia gui to take a look at all of the items but allow us to edit the actions of them

### Is your feature request related to a problem?

sorta i want to get an item and put it in one of my guis from the api 

### Describe alternatives you've considered

none

### Additional context

none

**Comment by LoneDev6** [comment]
Sorry I don't understand why you need the actual ItemStacks, why don't you use `CustomStack.getNamespacedIdsInRegistry()` then iterate it and call `CustomStack.getInstance(name).getItemStack()` for each one?


The ItemsAdder API is a wrapper for the internal api, i cannot expose ItemStacks directly

**Comment by jman13378** [comment]
> `CustomStack.getNamespacedIdsInRegistry()` 
This doesnt seem to exist
![image](https://user-images.githubusercontent.com/101841938/185796904-ab2ff236-5a40-4a36-9616-496c45a9bc41.png)
