### ISSUE TITLE
durability bug

### ISSUE THREAD

**Issue by cats-love** [PluginBugs/Issues-ItemsAdder#1922]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

cats#0935

### What happened?

If you set max durability and cook, the item will disappear with 1 durability remaining.

### Steps to reproduce the issue

I made an item with 5 durability in this configuration -> If you combine items with durability 1, the item will evaporate.
![image](https://user-images.githubusercontent.com/87476958/185773572-ba5b4ff5-b1f8-4c97-bd59-a535b99bac47.png)

### ItemsAdder Version

3.2.3f

### ProtocolLib Version

1.19 #598 

### LoneLibs Version

1.0.21

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/87476958/185773460-55038e84-de34-449f-ad88-fff6e1d2d6e6.png)
![image](https://user-images.githubusercontent.com/87476958/185773468-dde4ec31-3485-409b-acb9-3cb897fd01a8.png)

https://user-images.githubusercontent.com/87476958/185773507-dc0e2a18-8b67-4e92-bd2f-027f81baed44.mp4

**Comment by LoneDev6** [comment]
It's normal, the item has 0 durability after the last usage.

1 -> 0
