### ISSUE TITLE
Summon Entity induced IA exception

### ISSUE THREAD

**Issue by YouMing233** [PluginBugs/Issues-ItemsAdder#1923]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

I was kicked out by the server when I summon a entity.
Console does not throw any error.

I tried to rollback itemsadder to version below 3.2.3c, and found that it can load normally.
However, this problem will happen as long as the version 3.2.3c or higher is used.

Unfortunately, due to some plugin requirements of my server, I cannot rollback it to version lower than 3.2.3c

![image](https://user-images.githubusercontent.com/53418995/185787381-f6d195e0-28dc-48de-8cfa-2ec04705e15c.png)

### Steps to reproduce the issue

As long as you use itemsadder 3.2.3c and protocollib 4.8.0, you will see error when you summon a entity

### Server version

![~LXI 9XJ %~ `TKE_UHUFVD](https://user-images.githubusercontent.com/53418995/185787308-4620330e-7e67-4b37-b791-f459877a68d5.png)

### ItemsAdder Version

ItemsAdder version 3.2.3f

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.21

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: magic_crates
entities:
  magic_crate:
    display_name: ""
    type: ARMOR_STAND
    model_folder: entity/magic_crate
    silent: true
    can_sun_burn: false
    speed:
      movement: 1
      flying: 0
    max_health: 20
font_images:
  crate_magic_crate:
    show_in_gui: true
    path: "crate/gui_crates/magic_crate.png"
    scale_ratio: 255
    y_position: 45
  crate_magic_crate_ico:
    show_in_gui: true
    path: "crate/gui_crates/magic_crate_ico.png"
    scale_ratio: 9
    y_position: 8
  crate_magic_crate_ico2:
    show_in_gui: true
    path: "crate/gui_crates/magic_crate_ico2.png"
    scale_ratio: 9
    y_position: 8
  crate_screen:
    show_in_gui: true
    path: "crate/gui_crates/screen.png"
    scale_ratio: 1500
    y_position: 70
items:
  crate_magic_key:
    display_name: crate_magic_key
    resource:
      material: PAPER
      generate: true
      textures:
      - crate/misc_items/crate_magic_key.png
```

**Comment by LoneDev6** [comment]
Thanks, this is already fixed in the next update
