### ISSUE TITLE
[Suggestion] Multi-version resourcepack creation

### ISSUE THREAD

**Issue by Padlick** [PluginBugs/Issues-ItemsAdder#193]
**Is your feature request related to a problem? Please describe.**
I would like to have the possibility to create multi-versioned resourcepacks because my server is multi-versioned. My players are asking why ia doesn't work for 1.13 and under.

**Describe the solution you'd like**
Create subfolders for versions in "plugins/ItemsAdder/data/resource_pack";
Like "plugins/ItemsAdder/data/resource_pack/1.15/<PACKDATA>", "plugins/ItemsAdder/data/resource_pack/1.14/<PACKDATA>", "plugins/ItemsAdder/data/resource_pack/1.13/<PACKDATA>" and so on. And yes I know that 1.15 packs are compatible with 1.14 - that was just an example. 1.15 packs are sadly not compatible with 1.13 - that's why I would like to have this possibility.

**Describe alternatives you've considered**
Don't know atm

**Comment by LoneDev6** [comment]
As you know itemsadder is not compatible with spigot 1.13, only 1.14+ because it uses CustomModelData and other features available only in 1.14-1.15.

To do that I'd have to add support for Optifine custom textures, but it breaks the purpose of the plugin: no mods.

I hope you can understand

**Comment by Padlick** [comment]
Then, could you disable sending resourcepack to players using 1.13 and under?
Because they get the resourcepack but it fails because of no compatibility.
Should be just a condition of a player's protocolversion before you send the resourcepack to the player ;-;

**Comment by LoneDev6** [comment]
Yes I can for sure.
May I know why you want your 1.13 players to join when they cannot see textures? Just curious.
I mean 1.15 game client is not that heavy compared to 1.13, they are almost the same

**Comment by Padlick** [comment]
Because we have an multi versioned network. We have some minigame servers that are on 1.8 (with protocolhack for versions above) because of bad pvp in 1.9 and above (I know there are plugins but that doesn't make server performance better) and so they would have to change every time the version when they want to player on our survival. Also, many users don't like 1.9 and above because of bad performance.

**Comment by LoneDev6** [comment]
Okay but why do your users join survival with ItemsAdder installed using 1.13 client?
They won't see textures

**Comment by Padlick** [comment]
Our survival is 1.8 and above, with 1.13 was just an example. How I said, we have minigame servers on 1.8 because of better performance. Player's plays with 1.8 on them because of better performance. When they want to play survival after that they would have to change the version before and that just annoys players; and as I said, our survival is playable also without ia;
