### ISSUE TITLE
Items in hand continue to be combined even when the maximum quantity is reached

### ISSUE THREAD

**Issue by cats-love** [PluginBugs/Issues-ItemsAdder#1930]
### Discord tag (optional)

cats#0935

### What happened?

Even if the item in your hand reaches the maximum quantity, it will continue to be combined. Originally, the combination should stop at 64 items in your hand, but it doesn't. I'm guessing it's an error in the latest version

### Steps to reproduce the issue

1. Hold items with durability (ex. kitchen knives) and keep combining them
2. It does not stop even if the number of items in your hand reaches the maximum!

### ItemsAdder Version

3.2.3g

### ProtocolLib Version

# 598

### LoneLibs Version

1.0.21

### Screenshots/Videos (you can drag and drop files or paste links)

https://user-images.githubusercontent.com/87476958/186045364-c0412707-4a37-45f5-85a7-53d4342542d2.mp4

**Comment by LoneDev6** [comment]
> I'm guessing it's an error in the latest version

please test with previous versions and let me know
