### ISSUE TITLE
Being able to delete messages

### ISSUE THREAD

**Issue by EspartaProJunior** [PluginBugs/Issues-ItemsAdder#1932]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

I would like the possibility to delete messages from the console as for example those of iaplayerstat since when changing many times the console fills up with messages and ends up annoying.

### Is your feature request related to a problem?

yes

### Describe alternatives you've considered

Add a specific option for it in the configuration

### Additional context

that's all

**Comment by LoneDev6** [comment]
Why are you calling it many times?
ItemsAdder has an API, you can use it to change the stats values without using commands.

**Comment by EspartaProJunior** [comment]
How is it done with the api?

**Comment by LoneDev6** [comment]
check the wiki please https://itemsadder.devs.beer/developers/java-api/huds-guis#access-mana-bar-value-example
