### ISSUE TITLE
Auto generated files not being removed from their respected jsons

### ISSUE THREAD

**Issue by NoobcoreNetwork** [PluginBugs/Issues-ItemsAdder#1936]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

#joshie0644

### What happened?

So basically, as explained on discord, Whenever I have anything that is set to auto generate within IA, If i then remove that auto generated item as seen in the picture, We use the example of  GMA music disc, I remove the item_packs reference completely then When I rezip IA, it stays hard baked into the stick Json and the only way to remove it is manually removing it from the json itself. This happens for every single item that was auto generated by default for me and some others mentioned, Now, I don't use auto generated anymore, But there is a few hundred auto generated IA files cooked into my jsons from when I initially installed IA which has lead to this 
![upload](https://user-images.githubusercontent.com/62724418/186720278-53ec3f93-168c-4c11-b53c-6f5bbbfc0468.png)

I'm 100% sure there isn't anything in item_packs generating these files because If I go into the jsons myself and removed an instance of one of them and rezip, it doesn't reappear, so can be removed manually

### Steps to reproduce the issue

Set an item to auto generate
iazip so it does
Obtain and confirm item works in game
Remove the auto generated item from item_packs then Iazip
then check client logs/json file to see it is still there

### Server version

1.19

### ItemsAdder Version

3.2.3g

### ProtocolLib Version

Build #600 

### LoneLibs Version

LoneLibs 1.0.21

**Comment by LoneDev6** [comment]
Thanks a lot, this will be fixed in the next update.
The `/iacleancache` command will clean these leftovers too and you won't have these errors anymore after regenerating the pack (with `/iazip`).


Note that this won't work if you already ran `/iacleancache` command before. This decision was made to avoid manually added entries to be removed by this command.
The command will remove only the unused custommodeldata entries which were previously known by ItemsAdder.
