### ISSUE TITLE
[Blockus Resources] Itemsadder failed to apply textures on placed block

### ISSUE THREAD

**Issue by SteelsSystem** [PluginBugs/Issues-ItemsAdder#1938]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Steels#9381

### What happened?

if I Place any Blockus Reimagined tile block, either in survival or creative,
 
I encounter this problem
  block instantly turns to spawner and if i place another block(in creative if you got 1 block in your hand it disappears, then you can still build and those textures look fine.)
Survival if you try to place more than one you can't because the block disappears and you can't build, quick youtube showcase 

### Steps to reproduce the issue

Place any Blockus Reimagined tile block, to test the bug
with following setup of plugins
![obrazek](https://user-images.githubusercontent.com/92061582/187042071-ec9af978-748e-4831-aac1-678accc16411.png)
(I decided to use my resource pack through Nova plugin different from previous problem) but might it be just the resource being old?

### Server version

git-purpur-1766 (MC: 1.19.2)

### ItemsAdder Version

Itemsadder 3.2.3h

### ProtocolLib Version

5.0.0-SNAPSHOT-B598

### LoneLibs Version

LoneLibs version 1.0.21

### LibsDisguises Version (optional)

not currently present on server

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/rtHbSjEYCuI

**Comment by SteelsSystem** [comment]
[]https://mclo.gs/6Xg81GH(url)

**Comment by SteelsSystem** [comment]
https://mclo.gs/6Xg81GH
https://mclo.gs/6lQer0I

**Comment by SteelsSystem** [comment]
i am wondering if it's normal for TILE to do this, if i change them do note block, they worked normally again. but i would love to add more through TILE type of blocks

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1933#issuecomment-1228490679
