### ISSUE TITLE
Support for CMI in the Player Heads Addon

### ISSUE THREAD

**Issue by Cokenpizza** [PluginBugs/Issues-ItemsAdder#1947]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Cokenpizza#5684

### Describe the solution you'd like

Support for the CMI /head command in the same way that Essential's /skull command is utilized for the Custom player heads IA Addon.

https://www.spigotmc.org/resources/cmi-298-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/
https://www.spigotmc.org/resources/items-custom-player-heads-2d-head-big-wearable-head.99121/

### Is your feature request related to a problem?

Heads added by this addon have no texture when using CMI rather than EssentialsX.

### Describe alternatives you've considered

Convert to EssentialsX

**Comment by LoneDev6** [comment]
Ask CMI developer to fix their command to allow setting the current player texture to the hold player head item, just like Essentials work.
