### ISSUE TITLE
[ItemsAdder] [Pack] Finished uploading resourcepack: null

### ISSUE THREAD

**Issue by Zanzo88** [PluginBugs/Issues-ItemsAdder#1948]
### Discord tag (optional)

Zanzo#8211

### What happened?

When i try to push resource pack with /iazip command in console appear:

[ItemsAdder] [Pack] Finished uploading resourcepack: null

External host service maybe offline?

### Steps to reproduce the issue

auto-external-host:
      enabled: true

Push resource pack with /iazip

### Server version

This server is running Paper version git-Paper-111 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: 02831e3)
You are running the latest version
Previous version: git-Paper-94 (MC: 1.19.1)

### ItemsAdder Version

ItemsAdder version 3.2.3i

### ProtocolLib Version

ProtocolLib version 5.0.0 SNAPSHOT b600

### LoneLibs Version

LoneLibs version 1.0.21

**Comment by LoneDev6** [comment]
Back online
