### ISSUE TITLE
Allow manual install of packs

### ISSUE THREAD

**Issue by WarnDa** [PluginBugs/Issues-ItemsAdder#1950]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

WarnD#0001

### Describe the solution you'd like

Currently, player need to load a pack everytime they connect, so I want to manually gives the pack to players that play often, while still forcing packs to new players, so they can't deny it.
That's why I want an option to force the pack to players (and they can't deny it) and add a command to whitelist player, and theses whitelisted players don't have to load the pack everytime.

I think a lot of server would use it, my goal would be :
- force new player to use the pack (to avoid kids saying "bUgEd sErveR I doN'T gET thE PacK" because they declined it)
- if the player stay, and do not want to load the pack everytime, I create a discord tutorial where he can download it, and in game type a command like "/Idownloadedthepack"
- and now, this player won't have to load the pack everytime.

Only problem : as server can't detect player ressource pack, the player can do "/Idownloadedthepack" and not install the pack, so he will play without pack, but then it's the players' fault, and I don't care about theses stupid people.
(or add a way to detect the pack, with a custom texture and server detect if the player see it or not.. not possible currently but a solution could be find later I think)

Hope you like this idea, and hope it will be implemented !

### Is your feature request related to a problem?

The only drawbacks of ressource pack is the loading screen, it's frustrating to load a pack everytime you connect "lmao it's just 7s to load, ez", yes but it could be 0s, and player would be happier, and would accept to play with a pack without any issue.

### Describe alternatives you've considered

- set `decline-kick: false` and put the pack on discord, but some people will accidently or not decline the pack, and cry because they don't get the pack, and staff will need to always tell "yes, do /iapack...", so not optimal

**Comment by LoneDev6** [comment]
Even big servers like OriginRealms don't have this feature, this seems to be a pretty personal request.
It can be implemented as a separate plugin, I don't think that it would be a great thing to add this feature into ItemsAdder.

>  "lmao it's just 7s to load, ez", yes but it could be 0s, and player would be happier,

This is just placebo since the game loading would be increased by 7 seconds as the pack still will be applied but on game start.
Note that players will have issues if they join another server with the pack on.


This feature is not suitable for ItemsAdder, that's why I think it must be implemented as separate plugin.
