### ISSUE TITLE
API method to retrieve block model files

### ISSUE THREAD

**Issue by NichtStudioCode** [PluginBugs/Issues-ItemsAdder#1959]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

StudioCode#3416

### Describe the solution you'd like

An API method to retrieve a ``Map<NamespacedKey, String>`` (or similar) representing block id and a path to their item model in the ItemsAdder resource pack.

### Is your feature request related to a problem?

I'm currently working on a WAILA-like overlay for Spigot. In order for it to be compatible with ItemsAdder, I would need to render ItemsAdder's blocks.

### Describe alternatives you've considered

None

### Additional context

The WAILA-like overlay I've been working on:
![](https://i.imgur.com/NNiSCbZ.gif)

**Comment by LoneDev6** [comment]
Will be added in the upcoming update

**Comment by LoneDev6** [comment]
Example usage:
```java
System.out.println(ItemsAdder.Advanced.getItemModelResourceLocation("iasurvival:ruby"));
System.out.println(ItemsAdder.Advanced.getItemModelResourceLocation("iasurvival:ruby_block"));
```
