### ISSUE TITLE
the furniture can execute event and action normally when I have op permission, but not if I don't. 

### ISSUE THREAD

**Issue by Meawerful** [PluginBugs/Issues-ItemsAdder#1963]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Meawerful#7634

### What happened?

the furniture can execute event and action normally when I have op permission, but not if I don't. 

### Steps to reproduce the issue

1.make a furniture
2.test

### Server version

This server is running Mirai version git-Mirai-6 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 1272af0 on HEAD)
You are running 8 versions beyond. Please update your server when possible to maintain stability, security, and receive the latest optimizations.
>Previous version: git-Paper-134 (MC: 1.19.2)

### ItemsAdder Version

ItemsAdder version 3.2.3m

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b600

### LoneLibs Version

LoneLibs version 1.0.21

### LightAPI Version (optional)

none

### LibsDisguises Version (optional)

LibsDisguises version 10.0.31-SNAPSHOT

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: block
items:
  moon_chest:
    display_name: "新月箱"
    resource:
      material: "PAPER"
      generate: false
      model_path: "block:chest/mystery_box"
    behaviours:
      furniture:
        fixed_rotation: false  
        entity: armor_stand    
        solid: true
        small: false
        placeable_on:
          walls: false
          ceiling: false
          floor: true
        sound:
          place:
            name: block.metal.fall
          break:
            name: block.metal.break          
    events:
      placed_armorstand:
        interact:
          execute_commands:
            the_first_command:
              command: deluxemenu open new_moon {player}
              as_console: true
```

**Comment by LoneDev6** [comment]
I cannot reproduce the issue, you probably don't have the correct deluxemenu permissions, I'm not deluxemenu developer so you have to ask them.
