### ISSUE TITLE
ItemsAdder failed to register skript API

### ISSUE THREAD

**Issue by YouMing233** [PluginBugs/Issues-ItemsAdder#1968]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

When server starts, ItemsAdder failed to register skript API.
ItemsAdder dont output message "registered skript API" when loading.

### Steps to reproduce the issue

At startup, you can find that ItemsAdder does not register Skript API

### Server version

Purpur-1566 (MC: 1.18.1)

### ItemsAdder Version

ItemsAdder version 3.2.3g

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.21

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/53418995/189605948-bc70a954-336d-4260-89b3-827519829b9c.png)
![image](https://user-images.githubusercontent.com/53418995/189606113-ed818fa9-7c93-4f89-ae49-20ff18c14dc1.png)

**Comment by LoneDev6** [comment]
Did you try to update ItemsAdder?

**Comment by YouMing233** [comment]
![image](https://user-images.githubusercontent.com/53418995/190294624-9ae1ca38-2971-4f82-8181-aff38e219eac.png)
I tried to update ItemsAdder to the latest version, but still did

**Comment by YouMing233** [comment]
> Did you try to update ItemsAdder? You're not using the latest version
Incredibly, when I delete Residence, ItemsAdder can normally register Skript API
I'm using Residence 5.0.2.1, which is latest version, but this problem still exists

**Comment by LoneDev6** [comment]
Ask residence developer
