### ISSUE TITLE
All parsing of :: doesn't work, version 1.19purpur, but I'm on the same file with 1.18 and it works fine

### ISSUE THREAD

**Issue by lizheyo77** [PluginBugs/Issues-ItemsAdder#1969]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

oranges77#3767

### What happened?

All parsing of :: doesn't work, version 1.19purpur, but I'm on the same file with 1.18 and it works fine

### Steps to reproduce the issue

Various places to call::output

### Server version

1.19purpur

### ItemsAdder Version

ItemsAdder_3.2.3m

### ProtocolLib Version

5.0.0-SNAPSHOT-b600

### LoneLibs Version

1.0.21

**Comment by LoneDev6** [comment]
It normally works fine, you might have a plugin interfering, for example: chat plugin, outdated server or something else.
Without a full log of when the issue occurred I have no absolute way to help you.

**Comment by lizheyo77** [comment]
> It normally works fine, you might have a plugin interfering, for example: chat plugin, outdated server or something else. Without a full log of when the issue occurred I have no absolute way to help you.

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/9567543/latest.log)
这是我的日志

**Comment by LoneDev6** [comment]
Update to Purpur 1.19.2
Why are you still on 1.19? It's old and broken.

**Comment by lizheyo77** [comment]
是因为版本的问题吗,请问?毕竟升级版本也挺麻烦

LoneDev ***@***.***> 于2022年9月14日周三 23:53写道：

**Comment by LoneDev6** [comment]
Yes, update.
You must never keep an old version, it has no sense to use outdated and bugged versions.
