### ISSUE TITLE
IAEmotes add more cubes

### ISSUE THREAD

**Issue by Lerphie** [PluginBugs/Issues-ItemsAdder#1970]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Coder#6926

### Describe the solution you'd like

I want you to add 2 times more cubes for emotions.

Your emotions have too few polygons. I suggest adding them 2 times more. Like for example here. (sorry for my language, I'm Russian (Gust's friend))

Example of large cubes:
https://mcmodels.net/model/emotes-pack-for-mccosmetics/

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

https://mcmodels.net/model/emotes-pack-for-mccosmetics/

**Comment by Lerphie** [comment]
@LoneDev6

**Comment by LoneDev6** [comment]
https://itemsadder.devs.beer/faq/emotes-bugs/emotes-with-more-joins
