### ISSUE TITLE
IA WorldEdit doesn't support undo for custom blocks

### ISSUE THREAD

**Issue by fnrcum** [PluginBugs/Issues-ItemsAdder#1973]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Xafnir#1337

### What happened?

Tried copying a selection with world edit that holds custom blocks and furniture

1. It works to copy custom blocks and paste them
2. Using the WE `//undo` feature undoes the normal vanilla blocks and furnitures but leaves the custom blocks as is

### Steps to reproduce the issue

1. Create a selection that has the following:
    - vanilla blocks
    - custom blocks (made out of note blocks or mushroom faces)
    - custom furniture items that stand on top of barrier blocks
2. Copy the selection using world edit while having the IA worldedit plugin installed
3. Paste the selection
    - you will see the vanilla blocks are pasted
    - you will see the custom blocks (made out of note blocks or mushroom faces) are pasted
    - you will see custom furniture items that stand on top of barrier blocks are pasted
4. Use the `//undo` command from WE
    - you will see the vanilla blocks removed
    - custom IA furnitures are also removed
    - you will see all custom blocks are NOTE removed

### Server version

paper-1.19.2-138

### FAWE Version
2.4.5-SNAPSHOT-276

### ItemsAdder Version

ItemsAdder_3.2.3m

itemsadder-blocks-injector_0.0.5

ItemsAdder-WorldEdit_1.1.2

Builder's basics pack

### ProtocolLib Version

v500-SNAPSHOT-b600

### LoneLibs Version

1.0.21

### LightAPI Version (optional)

bukkit-530 SNAPSHOT

### FULL server log

No errors or logs to show

### Error (optional)

```shell
no error
```

### ItemsAdder config.yml

```shell
no configs
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://imgur.com/a/BPeXjdn

![image](https://user-images.githubusercontent.com/10963542/190643986-f8a2d742-ad16-4e17-a125-72ea931b759f.png)
![image](https://user-images.githubusercontent.com/10963542/190644053-bf3f938c-7bbd-4b41-9fdd-68fb5ac544ff.png)

**Comment by Lerphie** [comment]
Download addon for IA (WorldEdit)

**Comment by fnrcum** [comment]
It is there `ItemsAdder-WorldEdit_1.1.2`

**Comment by LoneDev6** [comment]
Last time I checked it worked fine, I'll do some tests with latest version of WorldEdit
