### ISSUE TITLE
custom block incompatibilities

### ISSUE THREAD

**Issue by cats-love** [PluginBugs/Issues-ItemsAdder#1977]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

cats #0935

### What happened?

ebp plugin and itemsadder are not compatible

https://www.spigotmc.org/resources/%E2%9C%85-epic-backpacks.28981/

### Steps to reproduce the issue

Place the backpack on the block created by itemsadder.
The item disappears, leaving only the head block.
!! Item evaporates !!!

### Server version

Purpur git-Purpur-1778 (MC: 1.19.2)

### ItemsAdder Version

ItemsAdder v3.2.3n

### ProtocolLib Version

#600

### LoneLibs Version

 LoneLibs 1.0.21

### Screenshots/Videos (you can drag and drop files or paste links)

https://user-images.githubusercontent.com/87476958/190883415-aa4cbc71-f3f3-4f8c-b693-f1a26f3acf43.mp4

**Comment by LoneDev6** [comment]
Will be fixed in the next update!
Update both EpicBackpacks and ItemsAdder.

Related to:
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1162
https://github.com/PluginBugs/Issues-ItemsAdder/issues/866
