### ISSUE TITLE
A simpler way to add armor or items

### ISSUE THREAD

**Issue by mitchngwen** [PluginBugs/Issues-ItemsAdder#1978]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

I would like a more simple way to just add more armor, as the plugin stands now it is quite literally a nightmare to add new armor, items aren't too bad, but armor aaahhhhhh! Every time I buy a new armor pack to add it screws all the old armor up without fail. There needs to be some sort  of automated way to add new armor. It could ask you the type and the name etc. then just tell you place your textures in such n such folder and to run /iaz after.

### Is your feature request related to a problem?

The difficulty of adding new armor and it take hours to diagnose what the problem is.

### Describe alternatives you've considered

using oraxen

**Comment by LoneDev6** [comment]
ItemsAdder automates the armors atlas creation. 
Without ItemsAdder you would have to create a single armor file with all the armors textures slapped inside and add the correct pixels to store armors information.
Imagine having to do this manually.

There is a step by step tutorial which is extremely easy to follow: https://itemsadder.devs.beer/plugin-usage/adding-content/armors/texture
