### ISSUE TITLE
[Suggestion] new furniture entity type "modelengine"

### ISSUE THREAD

**Issue by ArtifactyNight** [PluginBugs/Issues-ItemsAdder#1980]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

NightKunGz#1757

### Describe the solution you'd like

Add new option to spawn ModelEngine's mob instead of item frame or  armor stand

### Is your feature request related to a problem?

`modelengine` entity type is useful for furniture which have animation like this:

https://user-images.githubusercontent.com/53427253/191253302-ab5696d1-82b3-43fb-88b4-47989b97fe18.mp4

### Describe alternatives you've considered

-

**Comment by LoneDev6** [comment]
It's a good idea but imagine people placing these furnitures all over the server, it would make it lag like crazy.
I don't think it's a good idea to make this kind of furniture
