### ISSUE TITLE
Furniture removal `hardness` property

### ISSUE THREAD

**Issue by Lennord** [PluginBugs/Issues-ItemsAdder#1984]
### What happened?

When I break the model, it breaks it for me directly and not in several moves.

### Steps to reproduce the issue

1. Create Model "Furniture".
2. Create configuration model.
3. Added "hardness: 5".

### Server version

[19:01:22 INFO]: Checking version, please wait...
[19:01:22 INFO]: This server is running Paper version git-Paper-387 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: df630a2 on ver/1.18.2)

### ItemsAdder Version

ItemAdder version 3.2.3n

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b600

### LoneLibs Version

LoneLibs version 1.0.21

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: ipialife

items:
  oak_table:
    display_name: "Table en chêne"
    resource:
      material: PAPER
      generate: false
      model_path: oak_table
    behaviours:
      furniture:
        hardness: 5
        light_level: 0
        solid: true
        small: false
        fixed_rotation: true
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 1
        sound:
          place:
            name: BLOCK_WOOD_PLACE
          break:
            name: BLOCK_WOOD_BREAK
```

**Comment by Lennord** [comment]
Okay i thought it was a bug but as you say it will be a great feature.

**Comment by LoneDev6** [comment]
I will try to add this feature in the next update, but I don't really know how to let the player know that they are breaking the furniture.

I can spawn the block cracking animation but I cannot customize the hitbox shape, it would be a block.
It might not look really great.

**Comment by Lennord** [comment]
Okay, on the contrary even if you can't target the furniture hitbox, it's a feature that will be really useful for those who will use it.
But don't worry, take your time, if it's not the next update, it will be later.
In any case, your plugin is really interesting for modding the game.

PS: I am doing a French Minecraft RolePlay server project and so your plugin is really useful for adding lots of functionality, good luck finding the right method.

**Comment by LoneDev6** [comment]
I decided to code this feature in the simplest and most intuitive way possible.
Double click to remove the furniture, it also plays an animation to give the player a feedback.

https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/00b8b10a-cc08-40de-afe1-88cad5779d81
