### ISSUE TITLE
ItemsAdder Offhand + RealDualWield - Seemingly Broken Function

### ISSUE THREAD

**Issue by NMLEthereal** [PluginBugs/Issues-ItemsAdder#1987]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

NeoWS#9999

### What happened?

So I stumbled across the issue of using the "offhand" attribute on an ItemsAdder item with Dual Wielding. (example below)

Instead of the intended effect, where the damage is different or disabled for off-hand weapons, any weapon with the "off-hand" attribute instead breaks the mainhand function, only allowing the offhand weapon to be used.

The weapon lowers down and does not come up again, rendering it unusable, larger models will look like they are being held at knee height. (see image)

### Steps to reproduce the issue

1) Run the latest ItemsAdder & RealDualWield
2) Create a custom item in IA set to a WOODEN_SWORD
3) Set the mainhand and offhand attributes.
4) Attempt to equip both items in-game.

### Server version

Current: git-Purpur-1668 (MC: 1.19)*

### ItemsAdder Version

ItemsAdder version 3.2.3n

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b600

### LoneLibs Version

LoneLibs version 1.0.20

### LightAPI Version (optional)

LightAPI version bukkit-5.3.0 (build SNAPSHOT)

### LibsDisguises Version (optional)

LibsDisguises version 10.0.31-SNAPSHOT

### FULL server log

[latest (13).log](https://github.com/PluginBugs/Issues-ItemsAdder/files/9638634/latest.13.log)

### Error (optional)

```shell
N/A
```

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: 198.27.108.35
      pack-port: 8165
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: true
  delay-ticks: 0
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: altfont.ttf
    shift: '[0,6]'
    size: 12.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-resources: false
  extract-default-configs: false
  legacy_pack: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
effects:
  hide-scoreboard-numbers: true
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: false
    interval-rendering-packets-ticks: 1
    emotes: true
    optimized-packets: true
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: true
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
    log-recipes-unknown-item: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
chat-preview: false
```

### Problematic items yml configuration file (optional)

```shell
nh_knife_sword_2:
    display_name: ':nh_weapon: &8| &7Pocket Knife'
    permission: DLSum
    lore:
    - '&8[&fOne-Handed&8]'
    - '&a+2 Damage'
    - '&a+50% Attack-Speed'
    - '&7Level :lv_2:'
    - '&8---------'
    - '&7Rarity: :rt_common:'
    - '&7Source: &fQuest'
    - '&8---------'
    resource:
      material: WOODEN_SWORD
      generate: false
      model_path: item/1h_knife
    durability:
      max_custom_durability: 100
      unbreakable: true
    attribute_modifiers:
      mainhand:
        attackDamage: 2
        attackSpeed: 2
      offhand:
        attackDamage: 1
        attackSpeed: 2
    item_flags:
    - HIDE_ENCHANTS
    - HIDE_UNBREAKABLE
    - HIDE_ATTRIBUTES
    behaviours:
      keep_on_death: true
```

### Screenshots/Videos (you can drag and drop files or paste links)

![iais](https://user-images.githubusercontent.com/56793821/192096833-329cf21f-b7bc-4600-aefc-ed095c2993e3.png)

**Comment by LoneDev6** [comment]
>  The weapon lowers down and does not come up again, larger models will look like they are being held at knee-height


This is extremely strange!
Seems to be a client glitch.
Can you run /iatag while holding only the main item?
Post (text please) the console result here

**Comment by NMLEthereal** [comment]
Sure thing!

{AttributeModifiers:[{Amount:0.0d,AttributeName:"minecraft:generic.attack_damage",Name:"itemsadder",Operation:0,Slot:"mainhand",UUID:[I;-630824991,35016629,-1949487167,619884272]},{Amount:-2.0d,AttributeName:"minecraft:generic.attack_speed",Name:"itemsadder",Operation:0,Slot:"mainhand",UUID:[I;-1412098539,2092778881,-1820474789,1347861982]},{Amount:0.0d,AttributeName:"minecraft:generic.attack_damage",Name:"itemsadder",Operation:0,Slot:"offhand",UUID:[I;2003217907,-452246300,-1831551490,2011696844]},{Amount:-2.0d,AttributeName:"minecraft:generic.attack_speed",Name:"itemsadder",Operation:0,Slot:"offhand",UUID:[I;-759700894,977619589,-1244039310,-1406800831]}],CustomModelData:10025,Damage:0,HideFlags:7,Unbreakable:1b,display:{Lore:['{"italic":false,"extra":[{"color":"dark_gray","text":"["},{"color":"white","text":"One-Handed"},{"color":"dark_gray","text":"]"}],"text":""}','{"italic":false,"color":"green","text":"+2 Damage"}','{"italic":false,"color":"green","text":"+50% Attack-Speed"}','{"italic":false,"extra":[{"color":"gray","text":"Level "},{"color":"white","text":""}],"text":""}','{"italic":false,"color":"dark_gray","text":"---------"}','{"italic":false,"extra":[{"color":"gray","text":"Rarity: "},{"color":"white","text":""}],"text":""}','{"italic":false,"extra":[{"color":"gray","text":"Source: "},{"color":"white","text":"Quest"}],"text":""}','{"italic":false,"color":"dark_gray","text":"---------"}'],Name:'{"italic":false,"extra":[{"color":"white","text":""},{"text":" "},{"color":"dark_gray","text":"| "},{"color":"gray","text":"Pocket Knife"}],"text":""}'},itemsadder:{custom_durability:100,fake_durability:59.0d,id:"nh_knife_sword_2",max_custom_durability:100,namespace:"dlequipment"}}

**Comment by LoneDev6** [comment]
Does this happen with a vanilla client with no mods?

**Comment by NMLEthereal** [comment]
First client used was Lunar, with Optifine.

This client is pure vanilla- but the issue remains exactly the same.

I will try to replicate this on a fresh server just to wager results (it might be a compatibility issue with another plugin?)

**Comment by NMLEthereal** [comment]
Most curious! Leaving the server and joining with two of these weapons equipped seems to cause the player's main hand to be empty upon joining back even whilst the weapon is still in their inventory.
![image](https://user-images.githubusercontent.com/56793821/192776474-9a109b3b-852b-44ed-940a-f05697d3fe89.png)

**Comment by NMLEthereal** [comment]
(2 week reminder)
