### ISSUE TITLE
CustomEntity do no appear instantly after being spawned

### ISSUE THREAD

**Issue by Acterax** [PluginBugs/Issues-ItemsAdder#1989]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

As you can see at the end of the record, on the latest version of ItemsAdder when I convert an Entity the entity may appear or not and then disappear, to finally appear 1 or 2 seconds after the player throw the entity.

This bug only occur in the latest version of ItemsAdder (3.2.2n)

### Steps to reproduce the issue

1. spawn an entity
2. convert the entity
3. apply velocity to the entity

### Server version

git-Purpur-1632 (MC: 1.18.2)

### ItemsAdder Version

ItemsAdder version 3.2.3n

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.21

### LightAPI Version (optional)

LightAPI version bukkit-5.2.0 (build SNAPSHOT)

### Screenshots/Videos (you can drag and drop files or paste links)

https://www.youtube.com/watch?v=v7x-z2iZ2Gg

**Comment by LoneDev6** [comment]
> spawn an entity
convert the entity
apply velocity to the entity

Can you be more specific on how you do that?
API? Commands?

Provide your code

**Comment by Acterax** [comment]
I'am using the API

Here is the code I use to spawn the Entity
`
 private fun spawnEntity(location: Location): Entity {
        val world = (location.world as CraftWorld).handle
        val customEntitySheep = CustomEntitySheep(location)
        world.tryAddFreshEntityWithPassengers(customEntitySheep)

        val bukkitEntity = customEntitySheep.bukkitEntity

        if (useModel()) {
            activeModel = CustomEntity.convert("moutons:${type.namespace!!}", bukkitEntity as LivingEntity)
        }

        return bukkitEntity
    }
`

And here is the code that throw sheep
`
vector = eyeLocation.direction

        val playerLineOfSight = shooter!!.getLineOfSight(null, 2) // avoid player launching sheep behind blocks

        val sheepLocation =
            shooter!!.eyeLocation.add(shooter!!.eyeLocation.direction.multiply(if (playerLineOfSight.isEmpty()) 2.0 else 0.3))

        entity = spawnEntity(sheepLocation)

        this.sheep = entity as Sheep

        this.sheep.getAttribute(Attribute.GENERIC_MAX_HEALTH)!!.baseValue = 16.0
        this.sheep.health = 16.0

        sheep.teleport(sheep.location.also { it.direction = shooter!!.location.direction })

        sheep.color = this.color
        sheep.velocity = eyeLocation.direction.clone().multiply(3.4)
        sheep.safeFallDistance = 50f
`

**Comment by Acterax** [comment]
Thanks :)
