### ISSUE TITLE
PlayerInteractEvent not triggered if entity is between 5 and 6 blocks of distance from player

### ISSUE THREAD

**Issue by castozen** [PluginBugs/Issues-ItemsAdder#1993]
### Discord tag (optional)

castozen#4619

### What happened?

When using the interact.left event and damage_entity_in_sight it wont activate if the mob is exactly 4 blocks away from player. If closer, or further it will activate fine. 

It will work as expected when in creative, but not in survival.

The item also needs an attack event as without this it would not trigger if player were close enough to hit the mob with the item.

I have included a streamable link to demonstrate and a copy of the item file.

### Steps to reproduce the issue

Copy my item file with any model.
In survival mode stand exactly 4 blocks from a mob.
Neither attack, nor interact.left events will trigger when left clicking while aiming at mob.

### Server version

Paper version git-Paper-173 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 3.2.3n

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b600

### LoneLibs Version

LoneLibs version 1.0.21

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/9666463/latest.log)

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: weapons
items:
  dark_queen_staff:
    display_name: Test
    resource:
      material: STICK
      generate: false
      model_path: darkqueenset/dark_queen_staff
    events:
      attack:
        shoot_particle:
          name: SPELL
          distance: 20
        damage_entity_in_sight:
          damage: 1
          distance: 20
      interact.left:
        shoot_particle:
          name: SPELL
          distance: 20
        damage_entity_in_sight:
          damage: 3
          distance: 20
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://streamable.com/meycev

**Comment by LoneDev6** [comment]
For some reason Spigot is not triggering the interact event if an entity is near but not that near to be attacked.
I'm trying to find a way to mitigate this but I'm not sure if it's fixable on my end, seems a Spigot bug.

https://user-images.githubusercontent.com/27242001/193013563-26480f6e-750f-44c4-ae00-4e689d3f9d99.mp4

**Comment by LoneDev6** [comment]
https://www.spigotmc.org/threads/playerinteractevent-not-called-when-entity-is-in-sight.574671/#post-4486378

Seems to be an actual client bug.
I will have to address this in a different way.
