### ISSUE TITLE
Color problem with emotes

### ISSUE THREAD

**Issue by Chrqmated** [PluginBugs/Issues-ItemsAdder#1995]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Chrqmated#0001

### What happened?

When using an emote while the player has a color in the chat, if the emote is placed in the middle of the message, after the emote the message will be white again.

Is it possible to fix this, maybe with a meta luckperms? 

### Steps to reproduce the issue

Create your rank with a colorchat (&c for example)
Send a message, with in middle, the emote
View the problem and enjoy for fix that ! :D

### Server version

Current: git-Purpur-1632 (MC: 1.18.2)*

### ItemsAdder Version

ItemsAdder version 3.2.1b

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.20

**Comment by LoneDev6** [comment]
Please share a screenshot, I can't understand the issue
