### ISSUE TITLE
Java - Modifying the item in furniture's item frame results in furniture not working properly

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#1996]

**Comment by VergilPrime** [comment]
Modifying the item in furniture's item frame results in furniture not working properly.

I use the following code to change a furniture's model:

`ItemStack stack = itemFrame.getItem();
ItemMeta meta = stack.getItemMeta();
meta.setCustomModelData(integer);
stack.setItemMeta(meta);
itemFrame.setItem(stack);`

After doing this, right clicking to sit on the furniture doesn't work, breaking the barrier block doesn't remove the item frame.

Note: CustomStack.byItemStack can still determine the type using the item stack in the item frame. Issue must be with data on the item frame entity.

[Video](https://youtu.be/TV0IXVDp6CI)

**Comment by LoneDev6** [comment]
Seems the `itemFrame.setItem(stack);` Bukkit API function is refreshing the boundingbox of the entity causing the interact event to not find any entity (because the boundingbox is reverted back to the original vanilla small one of itemframes).

This will be addressed in the 3.2.5 update.
