### ISSUE TITLE
Allow IA optifine custom armor textures to work without IA nbt

### ISSUE THREAD

**Issue by Sixsoul** [PluginBugs/Issues-ItemsAdder#1997]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

I think a configuration option to remove the IA nbt check from the shaders generated by IA would be ideal.

### Is your feature request related to a problem?

Can't use custom armors in other plugins.

### Describe alternatives you've considered

Just have it as a true/false option in config that when enabled removes the
```
nbt.itemsadder.namespace=
nbt.itemsadder.id=
```
from the shader files and replaces it with a `nbt.CustomModelData.X`

**Comment by LoneDev6** [comment]
This suggestion has no sense to me.
I don't understand what you mean by "shader" by discussing about nbt and CustomModelData.
They are 2 separate things.

Please elaborate your suggestion more by adding:
what you want
why you want it, what is the issue that requires you to have such functionality
what is the solution you have in mind
