### ISSUE TITLE
Multiverse-Core generated worlds do not spawn custom blocks

### ISSUE THREAD

**Issue by ProfessionalBoatDrifter** [PluginBugs/Issues-ItemsAdder#2000]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

Worlds which are generated by Multiverse-Core (both regenerated or created) do not seem to spawn custom REAL_NOTE blocks.

I've searched the Discord channels, the Discord forums and Github for issues related to Multiverse but with no active results.

### Steps to reproduce the issue

Optional pre-requisites:
- WorldEdit/FastAsyncWorldEdit

1. Install any custom blocks IA addons (I've tested using different ores)
2. Ensure they spawn in`world_nether` . Recommend testing using either the vanilla generated Nether for convenience.
3. (Optional) Set the generation chance to be high/guaranteed.
4. Generate a normal world.
5a. Verify the blocks spawn correctly, OR
5b. (Optional) Verify using `//replacenear 100 netherrack,soul_sand,soul_soil,_basalt,blackstone,gravel,lava air` to quickly clear a large area.
6. Add a custom world to the block's `worlds:` setting.
7. Create the world from step 5 using `/mvcreate [name] [environment]`
8. (Optional) Verify use `//replacenear 100 netherrack,soul_sand,soul_soil,_basalt,blackstone,gravel,lava air` to quickly clear a large area.
9. Note the lack of custom blocks.

### Server version

git-Paper-183 (MC: 1.19.2)

### ItemsAdder Version

ItemsAdder version 3.2.3-r9

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b600

### LoneLibs Version

LoneLibs version 1.0.21

**Comment by LoneDev6** [comment]
Is the issue still valid?
Did the SirCraftypants method work?

**Comment by ProfessionalBoatDrifter** [comment]
Sorry, didn't notice the reply.

@LoneDev6 while that could work (have not tested), the whole point of Multiverse is being able to create worlds on-demand on running servers (with the same plugins/setup/etc). Since IA is meant to provide content through populators (e.g. ores, trees), this should be looked into.

**Comment by SirCraftypants** [comment]
> 

I think you may have misunderstood how Itemsadder populates. many servers use custom world generators to pre generate custom worlds, this is another reason why Mutliverse Core has an import function. The only time you have to import a world with multiverse is if you pre generate a world. If you are not pregenerating which in 99% of cases is what every experienced server administrator does, unless it's just a server for you and a few friends.

If you are not pre-generating then It's really simple.

1. Generate world with Multiverse Core
2. Enter the files where your IA Populator configs are (somewhere in Items_Packs) and add the newly generated worlds name to them
3. Save your changes.
4. Restart your Server

When a player enters the new world and travels outside the worlds Spawn area in to newly generating chunks
Itemsadder will generate custom ores/decorations.

Pre Generating is another matter entirely, in which case i would refer to the IA Wiki to see which world gen plugins are compatible. [https://itemsadder.devs.beer/compatibility-with-other-plugins/compatible](url)

**Comment by LoneDev6** [comment]
Pregenerated worlds cannot get ores spawned in their chunks because of how the game works.
Did I misunderstood the issue report?

**Comment by ProfessionalBoatDrifter** [comment]
> 

Sorry about the delay.

I just tested it again on a world created after setting up the IA, this time using the world name "test". No custom ores have generated apprx 32 chunks away from 0, 0, specifically looking in a 100~ block radius around 512, 512.

I tested it again, this time around 1024, 1024. Looking around the same block radius. Still no custom blocks.

**Comment by LoneDev6** [comment]
I don't really have a clear vision on how to reproduce this issue.
My generator works fine based on my tests with MultiverseCore created worlds.

**Comment by SirCraftypants** [comment]
works fine for me also and my server specifically uses Multiverse Core

Under each custom ores configuration in blocks.yml you have 

`    worlds:
    - exampleworld`

Itemsadder generates custom blocks when a player uncovers a new chunk, so long as the correct world name is under the ores config it should spawn, each ore config also has the blocks it replaces. So ores spawn in unexplored chunks that are uncovered, ores so not spawn in a worlds spawn area at 0.

If they're not spawning then something else must be preventing them from spawning because Itemsadders spawning them fine for both me and lonedev. Like you i too am on Paper 1.19.2.

**Comment by ProfessionalBoatDrifter** [comment]
It's been a while since I've looked at this issue. I suppose I can try again on a new server instance using latest IA/LoneLib, Multiverse and Paper versions. Unfortunately my tests will have to wait as I'm unavailable until next weekend.
