### ISSUE TITLE
Spam an error in the console

### ISSUE THREAD

**Issue by EiderFC** [PluginBugs/Issues-ItemsAdder#2001]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Eider#8898

### What happened?

I have an error spamming the console

### Steps to reproduce the issue

I have an error spamming the console

### ItemsAdder Version

ItemsAdder version 3.2.3-r9

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b600

### LoneLibs Version

LoneLibs version 1.0.21

**Comment by LoneDev6** [comment]
> I have an error spamming the console

Without any details about the error I cannot do anything, I don't have access to your PC.

Next time please provide a valid log.
