### ISSUE TITLE
Itemsadder console spam

### ISSUE THREAD

**Issue by EiderFC** [PluginBugs/Issues-ItemsAdder#2005]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

itemsadder sends a spammy error message in the console

### Steps to reproduce the issue

itemsadder sends a spammy error message in the console

### Server version

git-Purpur-1778 (MC: 1.19.2)*

### ItemsAdder Version

 ItemsAdder version 3.2.3-r9

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b600

### LoneLibs Version

LoneLibs version 1.0.21

### FULL server log

[latest (1).log](https://github.com/PluginBugs/Issues-ItemsAdder/files/9699935/latest.1.log)

### Error (optional)

```shell
[ItemsAdder] Task #14987 for ItemsAdder v3.2.3-r9 generated an exception
```

**Comment by LoneDev6** [comment]
```
[14:41:11] [Server thread/ERROR]: [ItemsAdder] [0;31mFailed to load positive font_image for hud thirst_bar. font_image doesn't exists. /data/items_packs/realcraft/huds.yml[0m
[14:41:11] [Server thread/ERROR]: [ItemsAdder] [0;31mFailed to load half font_image for hud thirst_bar. font_image doesn't exists. /data/items_packs/realcraft/huds.yml[0m
[14:41:11] [Server thread/ERROR]: [ItemsAdder] [0;31mFailed to load negative font_image for hud thirst_bar. font_image doesn't exists. /data/items_packs/realcraft/huds.yml[0m
```

Try to fix this, it should be the cause of the errors

**Comment by EiderFC** [comment]
Is it possible because I have removed Durection, x_position_pixels, show from the huds.yml? since I wanted to keep the sed system but remove the hud.

**Comment by EiderFC** [comment]
https://mclo.gs/4016jVd
this is my huds.yml

**Comment by LoneDev6** [comment]
You can try restoring it from: https://github.com/ItemsAdder/DefaultPack/blob/c39c55df8b4556f143a6c2aac17d3fbc9a6ef8a8/data/items_packs/iasurvival/thirst/hud_thirst.yml
and just set `auto: false`, this will hide it completely form the game.

**Comment by EiderFC** [comment]
![image](https://user-images.githubusercontent.com/88196950/194119695-d13a9cbd-7a0e-42b3-ac69-604c727cc83a.png)
