### ISSUE TITLE
A new configuration option for ItemsAdder to finish loading items in the main thread

### ISSUE THREAD

**Issue by Hex27** [PluginBugs/Issues-ItemsAdder#2010]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Hex_26#8780

### Describe the solution you'd like

A config option to force ItemsAdder to load all items before world initialisation, regardless of how long it takes instead of on a separate thread like it does now.

### Is your feature request related to a problem?

Currently ItemsAdder finishes loading in a separate thread, allowing some main-thread processes like Chunk Generation to out-race item loading, causing a race condition that is hard to develop around. A config option like this would make it more simple to develop world generation populators with ItemsAdder blocks.

As I understand it, the feature of loading asynchronously is for a faster start-up time, but in this case, the optimisation does not speed up the server's startup as the world must be locked in some extent until ItemsAdder is loaded for BlockPopulator to have access to custom blocks.

https://discord.com/channels/533407895010803753/1022382995056898148

### Describe alternatives you've considered

Holding all chunks generated in an arraylist before items adder initialises, then populating them later is an option that can be done to circumvent the race condition, but it is very messy compared to simply using the normal world generation API given by spigot.

**Comment by LoneDev6** [comment]
I'll add a new setting in config.yml: `force-sync-loading: true`
