### ISSUE TITLE
Chorus plant model is broken

### ISSUE THREAD

**Issue by KioProject123** [PluginBugs/Issues-ItemsAdder#2018]
### Discord tag (optional)

针织薄外套#0277

### What happened?

I have disabled REAL_TRANSPARENT, but when fix-glitched-blocks is enabled, model will still be broken.
Is there any way to keep the chorus_plant model intact when fix-glitched-blocks is enabled?
![image](https://user-images.githubusercontent.com/61594596/194756083-1ec8c6e3-bdf0-4b2b-b135-907049564840.png)

### Steps to reproduce the issue

1. disable-REAL_TRANSPARENT: true
2. fix-glitched-blocks.enabled: true

Go to The End to view

### Server version

I can't connect well to foreign networks

Current: git-Purpur-1814 (MC: 1.19.2)*
Previous: git-Purpur-1809 (MC: 1.19.2)
* Error obtaining version information

### ItemsAdder Version

ItemsAdder version 3.2.3-r9

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b600

### LoneLibs Version

LoneLibs version 1.0.21

### ItemsAdder config.yml

```shell
metrics: false
update-checker: false
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: *hide*
      pack-port: 39302
    external-host:
      enabled: false
      url: 
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    - bbmodel
    - iaentitymodel
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: zh_cn
  dictionaries-lang: zh_cn
  extract-default-configs: true
  legacy_pack: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: false
    only-new-chunks: false
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: true
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: true
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
chat-preview: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: false
    commandblocks: false
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: false
  inventory-title:
    enabled: false
  vault-prefix-suffix:
    enabled: false
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: false
    update-every-ticks: 1200
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: false
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    emotes: true
    interval-rendering-packets-ticks: 1
    optimized-packets: true
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: false
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-recipes-unknown-item: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
```

**Comment by LoneDev6** [comment]
Already generated blocks won't revert back to their vanilla blockstate attributes.
You have to regenerate the end world.

Anyway (personal opinion) I think no one would really care about a seeing few chorus blocks with this blockstate, I don't think it would affect your users experience that much.

Note: this is the only way to create transparency supporting custom blocks with hitbox, there is no other way to do that, it's a limitation of the game.

**Comment by KioProject123** [comment]
> Already generated blocks won't revert back to their vanilla blockstate attributes. You have to regenerate the end world.
> 
> Anyway (personal opinion) I think no one would really care about a seeing few chorus blocks with this blockstate, I don't think it would affect your users experience that much.
> 
> Note: this is the only way to create transparency supporting custom blocks with hitbox, there is no other way to do that, it's a limitation of the game.

Thank you for your reply.

I have a pre-generated TheEnd world before installing the plugin，all chorus plant blocks are normal.
After I installed the plugin, chorus plant blocks was changed to an abnormal state.
When I disable fix-glitched-blocks, I find that chorus plant blocks will not be changed. (it also affects the mushroom blocks)

Is there a way to keep chorus plant blocks unchanged alone？
(I can understand what you said, but I don't need any transparency blocks, so I want to minimize unnecessary changes)



My statement may not be accurate. In general, how to prevent changing existing chorus plant blocks, but keep fix mushroom blocks and note block blocks. All worlds are pre-generated before installing the plugin.

**Comment by LoneDev6** [comment]
You must disable `disable-REAL_TRANSPARENT`  blocks in config.yml and regenerate the end world.
It's the only way to revert this behaviour.

Wait...
Are you saying that `fix-glitched-blocks` option will always change chorus blocks even if `disable-REAL_TRANSPARENT` block is set to `false`?
This is not intended if the answer is yes, let me know

**Comment by KioProject123** [comment]
> You must disable `disable-REAL_TRANSPARENT` blocks in config.yml and regenerate the end world. It's the only way to revert this behaviour.
> 
> Wait... Are you saying that `fix-glitched-blocks` option will always change chorus blocks even if `disable-REAL_TRANSPARENT` block is set to `true`? This is not intended if the answer is yes, let me know

Yes. `disable-REAL_TRANSPARENT` is set to true and `fix-glitched-blocks` also set to true.
Normal chorus blocks will be changed into abnormal ones.

**Comment by LoneDev6** [comment]
Thanks, I'll try to find a solution for the next update
