### ISSUE TITLE
block_trade_machine items cannot be accepted if they have additional NBT tags

### ISSUE THREAD

**Issue by purejosh** [PluginBugs/Issues-ItemsAdder#2020]
### Discord tag (optional)

purejosh#2047

### What happened?

I have a custom upgrade table which trades a base weapon and an upgrade item, to get an upgraded weapon. If the base weapon has been used or enchanted, it refuses to work in the trade. Even repairing the item doesn't work. 

Please add some method of passing NBT from the base item, to the resultant item, if a config item is set in the item.yml, such as "keep-nbt-data" in either slot 1 or slot 2, but not both. Alternatively, if that is too much to develop, you could add an option that ignores NBT data, though that's a workaround and not a true solution. 

I understand I'm using the block_trade_machine in an abnormal way, but there are no alternatives that I'm aware of, unless you've added something recently that I didn't catch. 

Alternatively, you could add smithing table recipes which will keep NBT data from slot 1 to slot 3 when smithed. This is possible, as I've seen it in other plugins, though I assume that it's not easy. This would be the true solution, however. 

### Steps to reproduce the issue

Use a block_trade_machine to upgrade a wooden sword to an iron sword, using 1 iron in slot 2. 
Observe that it works. 
Damage or enchant the wooden sword, and attempt to upgrade it again in the same method. 
Observe that it does not work. 

### Server version

This server is running Paper version git-Paper-111 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: 02831e3)
You are running the latest version
Previous version: git-Paper-387 (MC: 1.18.2

### ItemsAdder Version

3.2.3-R9

### ProtocolLib Version

5.0.0-SNAPSHOT-b587

### LoneLibs Version

1.0.20

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: pureweapons
#
recipes:
  crafting_table:
    upgrade_table:
      permission: pureweapons.upgrade_table
      enabled: true
      pattern:
      - xlx
      - xix
      - xsx
      ingredients:
        s: SMITHING_TABLE
        i: itemsadder:iron_plate
        l: LAVA_BUCKET
      result:
        item: pureweapons:upgrade_table
        amount: 1
#
items:
  upgrade_table:
    display_name: Upgrade Table
    permission: upgrade_table
    resource: 
      material: PAPER
      generate: false
      model_path: block/upgrade_table
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
    behaviours:
      block_trade_machine:
        title: Upgrade Table
        trades_list:
#-----NETHERITE-----
          netherite_katana:
            ingredients:
              slot1:
                item: pureweapons:diamond_katana
                amount: 1
              slot2:
                item: NETHERITE_INGOT
                amount: 1
            result:
              item: pureweapons:netherite_katana
              amount: 1
```

**Comment by LoneDev6** [comment]
I don't think this is possible since the game CLIENT does the matching, there is no way to force the client to update trade GUI ingredient slots because the client overrides them.

I might have to implement an alternative trade machine with a completely custom coded GUI.
The only downside is that it will be limited and won't have a scrollbar.

**Comment by purejosh** [comment]
Instead of coding a custom GUI, would adding smithing table recipes be easier? The smithing table seems to handle NBT data easier. 

This plugin was made by an absolute idiot, and I'm not entirely certain if this code would work in such a dynamic environment like itemsadder, but it may be worth looking at. If you can even find it... 
https://www.spigotmc.org/resources/combat-weaponry-plus-1-16-x.84248/

**Comment by LoneDev6** [comment]
I think this is the same suggestion: https://github.com/PluginBugs/Issues-ItemsAdder/issues/524
Planned for 3.2.5
