### ISSUE TITLE
A very serious flaw with the generation

### ISSUE THREAD

**Issue by Lerphie** [PluginBugs/Issues-ItemsAdder#2025]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Many plugins, including this one, will spawn ores from IA-Populators with a curve. Look at the screenshot taken in the plugin "Terra form Generator [Alpha] 9.0.3", what do you advise me to do? I understand that the problem is that the "ItemsAdder" plugin cannot read if there is a block in place of the structure. Because of this, a failure occurs

https://www.spigotmc.org/resources/terraformgenerator-alpha.75132/
![image](https://user-images.githubusercontent.com/66962762/194786632-0202d87d-945c-4f82-9f8c-307426f7d6b2.png)

### Is your feature request related to a problem?

yes

### Describe alternatives you've considered

Contact the plugin developer

**Comment by Lerphie** [comment]
Please, just don't write to me that I will spawn them in the air. It's not like that! Spawn occurs by replacing the stone

**Comment by Lerphie** [comment]
I know that you have been responding to user requests for a long time, so sorry for the ping. This problem is critical and many users suffer from it @LoneDev6

**Comment by LoneDev6** [comment]
Hello, this bug report was opened at 2AM so I had no way to answer it faster even by receiving multiple bumps.

> will spawn ores from IA-Populators with a curve

I sincerely have no idea what you mean

> Please, just don't write to me that I will spawn them in the air. It's not like that! Spawn occurs by replacing the stone

Same

> This problem is critical and many users suffer

Where did you get this information? It's the first time I get a similar report.
Please share the links and/or screenshots of where you read these reports.


Thanks a lot, I'll obviously fix the issue as soon as I get valid information about the problem

**Comment by Lerphie** [comment]
@LoneDev6 
https://youtu.be/ghWu9iQGiJU

**Comment by Lerphie** [comment]
@LoneDev6 https://youtu.be/cC__Pp5wRl8
![image](https://user-images.githubusercontent.com/66962762/196804925-d006b0e7-cf43-4c59-bcff-0218ed6a74c9.png)

**Comment by Lerphie** [comment]
I also noticed these problems
![image](https://user-images.githubusercontent.com/66962762/196805013-b86a908c-514f-438e-8a94-aa28e338d3e8.png)

![image](https://user-images.githubusercontent.com/66962762/196804978-df6c5077-35f6-43f8-8db3-b081c2f2424a.png)

**Comment by LoneDev6** [comment]
Did you actually sent this issue page to the developer?
I explained a possible cause of the issue.
So please take your time to provide this issue page link to the developer.

Thanks

**Comment by Hex27** [comment]
Yeah this was sent to me. The issues with the ores being un-carved when I create a cave has to do with my plugin and I will try to handle that.

However there's a second and third bug which was also posted here (with this video from above: https://www.youtube.com/watch?v=cC__Pp5wRl8 as well as ores turning into noteblocks) that I doubt is related to my plugin.

**Comment by Lerphie** [comment]
@LoneDev6 The developer answered you. So can you fix it?

**Comment by Lerphie** [comment]
@LoneDev6 ?

**Comment by LoneDev6** [comment]
@Lerphie Each bug must have its own bug report page.
Please avoid sharing multiple problems in the same Github issue page.

Thanks.

@Hex27 thanks!
Let me know if you need some changes on my side.
