### ISSUE TITLE
Random textures or models for 1 block

### ISSUE THREAD

**Issue by Rejze69** [PluginBugs/Issues-ItemsAdder#2027]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Fiupivko#6499

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/37219827/194932175-5ea376b3-ebfb-4cb7-b9d5-0e53d413db0c.png)
This. This is a must for block variants that will be randomly set while being as 1 item in inventory

### Is your feature request related to a problem?

I'm frustrated that I have to make every block separatedly and that I'm having them inside my inventory.

### Describe alternatives you've considered

None

**Comment by LoneDev6** [comment]
Seems the same request: https://github.com/PluginBugs/Issues-ItemsAdder/issues/1282

Planned for 3.2.4
