### ISSUE TITLE
TILE blocks shifting making spawner visible 

### ISSUE THREAD

**Issue by 32bitx64bit** [PluginBugs/Issues-ItemsAdder#2031]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

When placing down a TILE block the texture will sometimes shift
![2022-10-11_15 23 26](https://user-images.githubusercontent.com/86190528/195192385-8e88e24c-55f7-406b-9464-d8dcb1f9b92c.png)

### Steps to reproduce the issue

Place down a TILE block.

### Server version

Current: git-Purpur-1765 (MC: 1.19.2)*
Previous: git-Purpur-1762 (MC: 1.19.2)
* You are 54 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### ItemsAdder Version

ItemAdder version 3.2.3-r9 (latest)

### ProtocolLib Version

5.0.0 Snapshot b598

### LoneLibs Version

1.0.21

### LightAPI Version (optional)

5.3.0

**Comment by LoneDev6** [comment]
It's a client bug, I sadly cannot fix this in any way.
The only way to fix this is change world, teleport or quit and join again.

It's a Minecraft bug.
