### ISSUE TITLE
Disable hud if player has bypass permission

### ISSUE THREAD

**Issue by PystoyPlayer** [PluginBugs/Issues-ItemsAdder#2034]
### Discord tag (optional)

Пустой#7677

### Describe the solution you'd like

I want to disable some huds (thirst) not completely in the world or for creative, but for one permission group. Or a way to not waste/auto-fill the thirst bar for players with thirst.bypass perm

### Is your feature request related to a problem?

Sorry for my English, that is not my native language

### Describe alternatives you've considered

thirst.bypass permission / disable thirst for Admin group / auto-fill thirst bar for [same]

**Comment by LoneDev6** [comment]
You can already disable/enable huds per world.
https://itemsadder.devs.beer/plugin-usage/adding-content/huds#disable-enable-huds-in-worlds


Use the vscode extension to edit your configs.
https://marketplace.visualstudio.com/items?itemName=LoneDev.ia-vscode

**Comment by PystoyPlayer** [comment]
> You can already disable/enable huds per world. https://itemsadder.devs.beer/plugin-usage/adding-content/huds#disable-enable-huds-in-worlds
> 
> Use the vscode extension to edit your configs. https://marketplace.visualstudio.com/items?itemName=LoneDev.ia-vscode

but... did u even read my post ? I **don't** want to disable it completely in the whole **world**
I need to disable it for **certain group** of people everywhere (e.g. for RolePlaying)

**Comment by LoneDev6** [comment]
Chill, I will implement that in the future

**Comment by PystoyPlayer** [comment]
at first you put the tag Already Implemented and closed the post)  Thanks

**Comment by LoneDev6** [comment]
# What I'd implement

## Show hud permission
`ia.user.hud.show`
Permission for the player to see the hud (true by default for everyone).

## Bypass processing hud increase/decrease called by triggers (in yml files)
`ia.user.hud.bypass.triggers`
Stops the player hud value from increasing or decreasing based on events.
Not true by default for OP.

## Bypass processing hud increase/decrease commands
`ia.user.hud.bypass.commands`
Stops the player hud value from increasing or decreasing called by commands.
Not true by default for OP.

## Bypass processing hud increase/decrease API
`ia.user.hud.bypass.api`
Stops the player hud value from increasing or decreasing called by API.
Not true by default for OP.

**Comment by PystoyPlayer** [comment]
sadly you didn't implement it before 3.3
