### ISSUE TITLE
Add an Event for held in the offhand

### ISSUE THREAD

**Issue by BrytonBro** [PluginBugs/Issues-ItemsAdder#2035]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

I saw a post that was made around a year ago, asking for the same thing. Would you mind taking another look at it? I think that making an event for holding an item in the off hand should be added, and it would benefit more people than just me. Thank you for your time.

### Is your feature request related to a problem?

I want to add an item that gives the player a potion effect while the player is holding the item in the main hand, or the off hand. For example, they can hold the item while they're mining and get a haste effect.

### Describe alternatives you've considered

I don't think there is another alternative to this, because I don't know how to code.

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/857
