### ISSUE TITLE
 Renaming custom item can't use color code in anvil

### ISSUE THREAD

**Issue by patatoplugin** [PluginBugs/Issues-ItemsAdder#2037]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

I have report this bug 15 days ago.But seems you have forget it.

I test this again in my local sever,only use Itemsadder,protocolib and lonelib and CMI

I can rename vanilla item using color code(&a),but can't rename custom item
![2022-10-16_20 57 08](https://user-images.githubusercontent.com/62246956/196037095-03513bc7-7a4b-4046-aaa3-54c956c412f5.png)
![2022-10-16_20 57 16](https://user-images.githubusercontent.com/62246956/196037250-ec00c1b0-7ddb-4e21-a0af-ef6d40b82a5d.png)

### Steps to reproduce the issue

rename a custom item in anvil.for example rename it to be "&atest"

### Server version

purpur-1.19.2-1814

### ItemsAdder Version

ItemsAdder version 3.2.3m

### ProtocolLib Version

 ProtocolLib version 5.0.0-SNAPSHOT-b600

### LoneLibs Version

LoneLibs version 1.0.20

**Comment by LoneDev6** [comment]
Anvil doesn't support `&` color codes, this seems to be an issue of another plugin?

**Comment by AllayBreeze** [comment]
Purpur has a configuration to allow anvils to rename items with color codes. I'm using this and also meet this issue, which also only occurs on IA custom items.
So I guess the problem is most likely from itemsadder itself?

**Comment by patatoplugin** [comment]
Can you tell me why you can't reproduce?
What's your version,tell me and you don't need sovle this bug.
Server version?

ItemsAdder Version?

ProtocolLib Version?

LoneLibs Version?

**Comment by LoneDev6** [comment]
It's impossible for me to fix this issue without knowing how to reproduce it.

Do I need CMI? Which config do I have to enable?
Do I need Purpur? Which config do I have to enable?

ItemsAdder has a code which basically makes sure that the custom item name is not lost after using the anvil (without writing in the name field).
This is the only thing that might cause incompatibility with CMI and Purpur custom rename logic.
