### ISSUE TITLE
Destroys the characteristics of the original note box.

### ISSUE THREAD

**Issue by xiaozhangup** [PluginBugs/Issues-ItemsAdder#2039]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Miyazono#6455

### What happened?

Destroys the characteristics of the original note box.
For example, they can't make a sound. When I point the detector at the note box, the detector will constantly output the redstone signal.

### Steps to reproduce the issue

1.Start the server

### Server version

[22:03:28 INFO]: This server is running Mirai version git-Mirai-"3da1a73" (MC: 1.19.2) (Implementing API version 1.19.2-R
0.1-SNAPSHOT) (Git: 3da1a73 on ver/1.19.2)

### ItemsAdder Version

3.2.3-r9

### ProtocolLib Version

5.0.0-SNAPSHOT-b600

### LoneLibs Version

1.0.21

**Comment by LoneDev6** [comment]
> Mirai version git-Mirai-"3da1a73"

I have no idea of what is this fork.
Please use Spigot or Paper and let me know if the problem still occurs.

Anyway also attach a video.

**Comment by xiaozhangup** [comment]
> > Mirai version git-Mirai-"3da1a73"
> 
> You are using an unofficial Spigot fork which is probably the cause of the incompatibility. ItemsAdder does support noteblocks correctly. Please use Spigot or Paper and let me know if the problem still occurs.
> 
> Anyway also attach a video.

3.2.3-r10 don't have the problem,thanks!
