### ISSUE TITLE
[Suggestion] Gun magazine sizes

### ISSUE THREAD

**Issue by Sylvenight** [PluginBugs/Issues-ItemsAdder#204]
**Is your feature request related to a problem? Please describe.**
This feature request is not related to a problem as this is just something that adds difference to guns.

**Describe the solution you'd like**
So, the guns would have different magazine sizes, the shotgun would have 2, (it looks like a double barrel) the pistol would have 14 rounds, and the revolver would have 6 rounds. Maybe if you press Q while the gun is still loaded, it will reload the gun manually with a shorter time, but if you drain all the ammo and it reloads automatically, it will take slightly longer.

**Describe alternatives you've considered**
I have not found any alternatives.

**Additional context**
I do not have any additional context.

**Comment by LoneDev6** [comment]
A better solution would be to implement something to reload weapons by directly mixing weapon + ammo item, to avoid having to carry it in the offhand, since the game inventory is already very small.
