### ISSUE TITLE
Can I change the recipe sort order?

### ISSUE THREAD

**Issue by cats-love** [PluginBugs/Issues-ItemsAdder#2040]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Is there a way to set the sort order that appears in the recipe list of items?

### Is your feature request related to a problem?

![image](https://user-images.githubusercontent.com/87476958/196281643-a2ebafc5-d331-4804-8444-a4bc42d956c9.png)

I want to sort those categories, but I don't know how to figure out the sort order.

### Describe alternatives you've considered

https://user-images.githubusercontent.com/87476958/196282191-1b669393-bf3d-47d0-a4e8-8ec6fdb66d1a.mp4

Also, in the case of items that are grilled with a brazier or smoker, they are located at the bottom of the page rather than appearing immediately when you click on the item. Can you arrange the brazier a little forward?

**Comment by LoneDev6** [comment]
They are ordered based on the name
