### ISSUE TITLE
It affects the growth of chorus plants.

### ISSUE THREAD

**Issue by xiaozhangup** [PluginBugs/Issues-ItemsAdder#2042]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Miyazono#6455

### What happened?

https://streamable.com/w44gcd

### Steps to reproduce the issue

1. plant a chorus 

### Server version

git-petal-"b2aa817" (MC: 1.19.2)*

### ItemsAdder Version

3.2.3-r10

### ProtocolLib Version

5.0.0-SNAPSHOT-b600

### LoneLibs Version

1.0.21

**Comment by LoneDev6** [comment]
Cannot reproduce.
It's surely an issue of the `petal` unofficial Spigot fork you are using.

https://user-images.githubusercontent.com/27242001/196909001-f3ce2275-59e5-4d97-9fc9-e332884dbd2e.mp4

**Comment by xiaozhangup** [comment]
> 无法重现。这肯定是您正在使用的非官方Spigot分叉的问题。`petal`
> 
>  Minecraft_.1.19.84.-.Multiplayer.3rd-party.Server.2022-10-20.11-16-01.mp4_compressed.mp4

Can I use Purpur?

**Comment by xiaozhangup** [comment]
> Cannot reproduce. It's surely an issue of the `petal` unofficial Spigot fork you are using.
> 
>  Minecraft_.1.19.84.-.Multiplayer.3rd-party.Server.2022-10-20.11-16-01.mp4_compressed.mp4

Can I use Purpur?
