### ISSUE TITLE
On/off sound of custom-created crops

### ISSUE THREAD

**Issue by cats-love** [PluginBugs/Issues-ItemsAdder#2045]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

It has been modified to make the sound of digging by specifying the sound of the crop. Is there a function to turn this function on/off? If not, I would like to request additional suggestions.

### Is your feature request related to a problem?

![image](https://user-images.githubusercontent.com/87476958/196966802-d6a0162f-9a4f-4e32-b74c-9d939ce94ec9.png)
Enables users to turn event sounds on and off

### Describe alternatives you've considered

..

**Comment by LoneDev6** [comment]
Sorry I don't understand the request.

**Comment by cats-love** [comment]
Can you turn on and off the sound per player when picking up an item using itemadders?

**Comment by cats-love** [comment]
In other ways, such as authority or command.When the player picks up an item, only the user who turned on the sound can hear the sound, and when the sound is turned off, the sound is blocked

**Comment by LoneDev6** [comment]
You cannot stop the pickup sound, it's client-side
