### ISSUE TITLE
It affects the growth of chorus plants [New]

### ISSUE THREAD

**Issue by xiaozhangup** [PluginBugs/Issues-ItemsAdder#2046]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Miyazono#6455

### What happened?

You should remember the issue I raised yesterday.
https://github.com/PluginBugs/Issues-ItemsAdder/issues/2042

### Steps to reproduce the issue

1. set 'disable-chorus-plant-updates: true' in purpur.yml
2. plant some chorus plants

### Server version

I tested it on the latest purpur and the problem still exists.
But when I tested it in paper, there was no problem.
So I thought of the phrase mentioned in your wiki: https://itemsadder.devs.beer/faq/blocks-minerals-issues/custom-blocks-glitch-texture/avoid-glitched-blocks#optional-settings-on-purpur

So I disable it,and then the problem sloved.
But new problem is: https://streamable.com/9aqvqj

### ItemsAdder Version

same as https://github.com/PluginBugs/Issues-ItemsAdder/issues/2042

### ProtocolLib Version

same as https://github.com/PluginBugs/Issues-ItemsAdder/issues/2042

### LoneLibs Version

same as https://github.com/PluginBugs/Issues-ItemsAdder/issues/2042

**Comment by LoneDev6** [comment]
Thanks I will add a note on the wiki which specifies this downside.

Did you test with Paper instead of other forks?

**Comment by xiaozhangup** [comment]
> Thanks I will add a note on the wiki which specifies this downside.
> 
> Did you test with Paper instead of other forks?

https://streamable.com/sh0fr2
