### ISSUE TITLE
No Mob damage

### ISSUE THREAD

**Issue by Silphyy** [PluginBugs/Issues-ItemsAdder#2051]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

Since I put the plugin on the server, a saber no longer does damage to all entitys. It seems to me that the vanilla functions are off. How can I fix this?

### Steps to reproduce the issue

There is no special procedure it's just hit with a sword into a group of e.g. zombies and then all of them should get a hit through the Minecraft mechanics but it doesn't happen as if it was off.

### Server version

Current: git-Purpur-1814 (MC: 1.19.2)*
Previous: git-Purpur-1800 (MC: 1.19.2)

### ItemsAdder Version

ItemsAdder version 3.2.4-beta1
Customized Minecraft without client mods!
Website: devs.beer
Author: LoneDev

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b595
Provides read/write access to the Minecraft protocol.
Authors: dmulloy2 and comphenix

### LoneLibs Version

LoneLibs version 1.0.21
Collection of libs used by my plugins
Authors: LoneDev and others

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/9847072/latest.log)

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: 5.253.244.221
      pack-port: 25647
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: true
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      enabled: true
      extreme: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    - bbmodel
    - iaentitymodel
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: de
  dictionaries-lang: de
  extract-default-resources: false
  extract-default-configs: false
  legacy_pack: false
  force-sync-loading: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: false
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    interval-rendering-packets-ticks: 1
    emotes: true
    optimized-packets: true
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
    log-recipes-unknown-item: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: false
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: true
    log-single-loaded-overwrite: true
    log-single-skip: true
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
chat-preview: false
```

**Comment by LoneDev6** [comment]
1. test with only itemsadder and its dependecies installed
2. test with paper instead of purpur
3. make a video

**Comment by Silphyy** [comment]
https://workupload.com/file/5P3GqcqKcjA


The file is with 22mb too big therefore as a link.

**Comment by Justy135** [comment]
I have the exact same thing happening.
Swords/Axes do little to no damage, but bows etc do the right amount of damage.
Its very strange.

**Comment by LoneDev6** [comment]
I sincerely don't see how this has to do with ItemsAdder.
This plugin doesn't change any of the vanilla items damage attributes. I have no way to reproduce the issue, I tried to reproduce the issue and I cannot.

Make sure it's not another plugin interfering.
Try with another player too.

**Comment by Silphyy** [comment]
All players on our server have this problem, when we turn off ItemsAdder the normal mob damage is immediately there and everything goes back to normal. But since we like to work with ItemsAdder we would be happy if we could find out the problem and fix it.

**Comment by LoneDev6** [comment]
Did you try to remove EVERY other plugin as I asked?
It might somehow be a plugin interfering with ItemsAdder for some unknown reason.

**Comment by Silphyy** [comment]
Yes I do this.

**Comment by Silphyy** [comment]
Can you pls send me an old Version of ItemsAdder and i show if it works then?

**Comment by LoneDev6** [comment]
Download it from the plugin page versions history:
https://www.spigotmc.org/resources/73355/history/

**Comment by Silphyy** [comment]
The problem also exists with older versions. I ask for a way to fix this because it definitely comes from ItemsAdder. I can be reached via Discord under Dr. Blank ღ#2396.

**Comment by LoneDev6** [comment]
> Yes I do this.

Did you remove every other plugin and kept only ItemsAdder + its dependencies?

**Comment by LoneDev6** [comment]
https://user-images.githubusercontent.com/27242001/197764881-66176e79-ab8e-47c8-8417-387fc884c951.mp4

**Comment by LoneDev6** [comment]
it's 3.2.5 simply because it's the under development version which didn't change anything about the reported issue, so ignore the version.

**Comment by Silphyy** [comment]
https://workupload.com/file/Enbex6yHDrY

Here is a video with all the info again.

**Comment by Justy135** [comment]
Silphyy, what all plugins are you using? And we can see if you have a few similar to mine, and can maybe try eliminate them.

**Comment by Justy135** [comment]
Can confirm it is not multiverse causing this issue. I removed it.

**Comment by Silphyy** [comment]
@Justy135 my discord is Dr. Blank ღ
#2396

**Comment by Silphyy** [comment]
I have this problem with the ItemsAdder plugin without having changed anything in it. I deleted everything and redid it and the problem is still there.

**Comment by Justy135** [comment]
> I have this problem with the ItemsAdder plugin without having changed anything in it. I deleted everything and redid it and the problem is still there.

I am the same, im not sure what it is, I have literally tried everything at this stage.

**Comment by Justy135** [comment]
@LoneDev6 it appears to just be melee damage as a whole. Bows and crossbows do normal damage. But punching, and any tool seems to do very little damage to the mobs for whatever reason.

**Comment by LoneDev6** [comment]
I cannot trigger the issue, as shown in the video, so I cannot fix it.
Remove every plugin from your server, test with: ItemsAdder, LoneLibs, ProtocolLib installed and NOTHING ELSE.

Also please test with a single mob and not 165138465 mobs in a little spot.
Set night, spawn a zombie, attack it, exactly how I did in my video.

**Comment by LoneDev6** [comment]
`Plugins (17): Essentials, LoneLibs, LuckPerms, MotionCapture, Multiverse-Core, PlaceholderAPI, PlugManX (PlugMan), ProtocolLib, SkinsRestorer, spark, SpigotPing, TAB, Vault, ViaBackwards, ViaVersion, WorldEdit, WorldGuard`

https://user-images.githubusercontent.com/27242001/198075738-8044ea0a-6de3-4b4e-b2fc-fe99b1276d45.mp4

**Comment by Justy135** [comment]
I have just tested with only items adder and its dependencies, and it is still an issue.
@LoneDev6 I will give you full access to my server if you want to take a look?
See below video. 

https://user-images.githubusercontent.com/116603856/198248993-eab678f8-2cc4-4843-a488-8615f8d79916.mp4

**Comment by LoneDev6** [comment]
@Justy135 provide your Discord username, I will add you to the new beta testing channel so that you can try the new version and let me know if it fixes the issue.
I have no way to reproduce it but I might have had an idea of why this happens only on some servers.

**Comment by Justy135** [comment]
@LoneDev6 
I am in the discord server and my discord tag is - Justy135#9917

Appreciate it.

**Comment by Silphyy** [comment]
Kannst du mich bitte auch in der Gruppe hinzufügen damit ich es bei mir ausprobieren kann?

Dr. Blank ღ#2396

**Comment by Silphyy** [comment]
Can you please add me to the group as well so I can try it on myself?

Dr. Blank ღ#2396

**Comment by LoneDev6** [comment]
Both added! :D

**Comment by RodgeMiner10** [comment]
Hi all, I am experiencing this issue as well. Has there been a fix for it yet? My mobs seem to have a lot of health, but it now seems like it is melee weapons that are the issue, so glad I found this bug report.

**Comment by RodgeMiner10** [comment]
Could I also get the development build, does it fix the issue?

**Comment by LoneDev6** [comment]
We are trying to find a solution, currently I cannot reproduce the issue on my test servers and it's happening only on some particular servers setups of some customers.

I'll keep you updated here.

**Comment by LoneDev6** [comment]
Solution update ProtocolLib to `ProtocolLib version 5.0.0-SNAPSHOT-b602`, [download here](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/).
ProtocolLib broken version `ProtocolLib v5.0.0-SNAPSHOT-b597`.
