### ISSUE TITLE
Hats not executing once worn.

### ISSUE THREAD

**Issue by ChefJisoo** [PluginBugs/Issues-ItemsAdder#2052]
### Discord tag (optional)

Chef Jisoo#7199

### What happened?

I was speaking to a member of the support team, and they have confirmed that this issue seems to be happening where commands are not beong executed when a hat is worn, despite all the config being correct

### Steps to reproduce the issue

All I can say is set it up so that a hat runs a particular command and youll see in game that command wont run.

### Server version

Our server is running paper 1.18.2

### ItemsAdder Version

Items Adder version 3.2.3-r10

### ProtocolLib Version

4.8.0

### LoneLibs Version

LoneLibs version 1.0.19

**Comment by LoneDev6** [comment]
You always have to provide the item configuration for me to reproduce the issue.
And remember to provide it as text not screenshot.

Anyway is this supposed to trigger the interact event?
You're interacting with your hand items not helmet.

This seems like a feature request, you need to execute commands if the player is wearing the helmet.
