### ISSUE TITLE
When a object has multiple crafting recipes, it should scroll through options like vanilla does.

### ISSUE THREAD

**Issue by ItzASecret** [PluginBugs/Issues-ItemsAdder#2059]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

ItzASecretBoi#1300

### Describe the solution you'd like

Exactly what the title says. When a object has multiple crafting recipes, it should scroll through recipe options like vanilla does in the recipe book.

Normal items do this, but custom items do not, they do however change if you click on them multiple times, but I don't think every player is gonna do that. I don't know if this is possible but it would be nice, and make it closer to a vanilla experience.
![shield-crafting](https://user-images.githubusercontent.com/82130468/198376421-18844363-a2b8-416f-b748-ef9733318fa5.gif)

### Is your feature request related to a problem?

Players cant see all crafting variants of one item, unless they go into the /ia menu.

### Describe alternatives you've considered

None.

### Additional context

<3

**Comment by LoneDev6** [comment]
Very strange, the client should handle that automatically.
I'll find the cause, thanks

**Comment by LoneDev6** [comment]
I didn't find the cause for this issue, I wouldn't be surprised if it was a Minecraft client bug.
