### ISSUE TITLE
creeper/TNT dupes real_transparent blocks

### ISSUE THREAD

**Issue by Xiao-MoMi** [PluginBugs/Issues-ItemsAdder#2061]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

https://user-images.githubusercontent.com/70987828/198508861-ae214275-5935-492f-9824-f98dea3f8f56.mp4

see the video

**Comment by LoneDev6** [comment]
Anyway the next time (for now it's ok, no need to reopen it) please avoid reporting duplication bugs in public reports.

![image](https://user-images.githubusercontent.com/27242001/198541410-08f6916b-bd81-4794-ab12-65f4b450a48e.png)

![image](https://user-images.githubusercontent.com/27242001/198541421-e453e185-997f-468e-a1df-d428ea258e28.png)

**Comment by LoneDev6** [comment]
I cannot reproduce the issue.
`Paper version git-Paper-372 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 214a8c5)`
`ItemsAdder version 3.3.0b-r5`
https://streamable.com/sha35e
