### ISSUE TITLE
Furniture itemframe playing "entity.item_frame.add_item" sound when placed

### ISSUE THREAD

**Issue by Boy0000** [PluginBugs/Issues-ItemsAdder#2066]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Boy#8008

### Describe the solution you'd like

Consider making ItemFrame.setItem(item, false) so the sound from setting the item isnt there

### Is your feature request related to a problem?

The sound should be silenced as it also plays over place sounds

### Describe alternatives you've considered

no other solution really

**Comment by LoneDev6** [comment]
Nice idea! Thanks a lot
