### ISSUE TITLE
Mixing vanilla items with ia items in a shapeless recipe

### ISSUE THREAD

**Issue by Wupin** [PluginBugs/Issues-ItemsAdder#2068]
### Discord tag (optional)

Wupin #8643

### What happened?

When I mix vanilla items with ia items in a shapeless recipe, the recipe breaks and doesn't work as it should. There is an example video https://discord.com/channels/533407895010803753/1036652784809947197

### Steps to reproduce the issue

Just mix vanilla items with ia items in shapeless recipe

### Server version

Paper version git-Paper-199 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 77a50b9)

### ItemsAdder Version

ItemsAdder version 3.2.5-beta5

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b600

### LoneLibs Version

LoneLibs version 1.0.21

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: food
recipes:   
  crafting_table:
    kakao:
      shapeless: true
      enabled: true
      ingredients:
        M: food:sklenice_mleka
        L: cocoa_beans
        B: sugar
        C: cocoa_beans
      result:
        item: food:kakao
        amount: 1
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://discord.com/channels/533407895010803753/1036652784809947197

**Comment by DayzDuck** [comment]
still does not work in 3.0.0

**Comment by LoneDev6** [comment]
It hasn't been worked on, it's planned for 3.3.1 as you can see on the top right of this page.

**Comment by LoneDev6** [comment]
Btw this will be fixed in the new update :D
