### ISSUE TITLE
Ability to have custom itemsadder blocks respawn on a cooldown after being mined

### ISSUE THREAD

**Issue by nomad1154** [PluginBugs/Issues-ItemsAdder#2071]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Nomad#1000

### Describe the solution you'd like

A feature where custom itemsadder blocks can be placed and when they are mined the block is changed to stone a cooldown is triggered, when the cooldown reaches 0 the block turns from stone back into the custom block. This could be set up either per block or per region

### Is your feature request related to a problem?

not related to a problem

### Describe alternatives you've considered

tried https://www.spigotmc.org/resources/%E2%9C%A8-ore-regenerator-%E2%9C%A8-supports-all-blocks-1-8-1-19-%E2%AD%90-all-gui-controlled-%E2%AD%90.71743/ and it did not work with itemsadder blocks

Also tried MMOcore and could not get the blocks to work

**Comment by BookWyrm114** [comment]
I forget the names of the plugins but there are already plugins that allow you to do this that I’ve seen and they usually have compatibility with not only Itemsadder but also Oraxen blocks. Just search through spigot for a bit or do a quick google search and you should be able to find one.

**Comment by LoneDev6** [comment]
There are some plugins:
https://itemsadder.devs.beer/compatibility-with-other-plugins/compatible/ore-regenerator
