### ISSUE TITLE
mount Vehicles will disapper if you set Residence monsters flag false

### ISSUE THREAD

**Issue by minecraft-dripdrop** [PluginBugs/Issues-ItemsAdder#2078]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

neverlag#6619

### What happened?

If you set Residence flag "monster" false, mean that monster can't summon.When you click a vehicle,the vehicle will disapper .

### Steps to reproduce the issue

1. create a Residence and use /res set ,find monster flag and set it 'false'
2. put a vehicle on ground
3. click the vehicle, and it disappper

### Server version

Current: git-Purpur-1825 (MC: 1.19.2)*
Previous: git-Purpur-1809 (MC: 1.19.2)
* You are 10 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### ItemsAdder Version

3.2.5-beta5

### ProtocolLib Version

5.0.0-SNAPSHOT-b600

### LoneLibs Version

1.0.21

### Screenshots/Videos (you can drag and drop files or paste links)

you can see it in the discord
https://discord.com/channels/533407895010803753/1038692006647570463

**Comment by SirCraftypants** [comment]
Your residence flag is likely declaring armorstands as mobs, talk to the residence dev about exempting armorstands.

**Comment by LoneDev6** [comment]
https://itemsadder.devs.beer/faq/vehicles-bugs/towny-vehicles-bug#residence
