### ISSUE TITLE
All Recipes no longer working after update.

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-ItemsAdder#2079]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

sircraftypants#4875

### What happened?

As of updating to 3.2.5-r3, none of my hundreds of recipes work anymore, not a single one. All can be seen in the menu as usual but go to create in a workbench and nothing.

### Steps to reproduce the issue

I have no steps to issue other than updating from 3 versions back to the latest and recipes no longer functioning as they should. I notice permissions have changed on the wiki but despite that i still have access to them all on the menu, something is broken because they were working fine 3 versions ago.

I've not added any new plugins for a year at least and have no other plugins that deal with recipes other than IA, in fact nothing has changed since they were last working other than updates to existing plugins.

### Server version

[12:27:48 INFO]: This server is running Paper version git-Paper-256 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: e30b082)
You are 5 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-211 (MC: 1.19.2)

### ItemsAdder Version

[12:29:37 INFO]: ItemsAdder version 3.2.5-r3
[12:29:37 INFO]: Customized Minecraft without client mods!
[12:29:37 INFO]: Website: devs.beer
[12:29:37 INFO]: Author: LoneDev

### ProtocolLib Version

[12:30:01 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b595
[12:30:01 INFO]: Provides read/write access to the Minecraft protocol.
[12:30:01 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[12:30:19 INFO]: LoneLibs version 1.0.21
[12:30:19 INFO]: Collection of libs used by my plugins
[12:30:19 INFO]: Authors: LoneDev and others

### FULL server log

Nothing in server log, everything is fine, no warns, no errors, no misconfigurations.

### ItemsAdder config.yml

```shell
metrics: false
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: 173.225.103.171
      pack-port: 19755
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: false
    hide-hud: false
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      protection_1: false
      protection_2: false
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: true
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
    compress-png-files: true
    compress-json-files: false
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: false
    disable-overwrite-leather-armor-layers-textures: true
  items:
    CustomModelData-starting-value:
      ALL: 1
      DIAMOND: 1
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-resources: false
  extract-default-configs: false
  legacy_pack: false
  force-sync-loading: false
blocks:
  light-api: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: false
    allow-any-item: false
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
  fix-liquids-flow: true
  fix-floating-blocks: true
  convert-vanilla-blocks:
    enabled: false
    only-new-chunks: true
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: false
liquids:
  enabled: false
huds:
  enabled: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: false
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: false
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
entities:
  max-furniture-vehicles-per-chunk: 999
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    interval-rendering-packets-ticks: 1
    emotes: false
    optimized-packets: true
recipes:
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
  hide-vanilla-unrecognized-recipe-errors: true
  custom-recipes:
    unlock:
      all-on-join: true
      on-pickup:
        any: false
        ingredients: true
  fix-packet-too-large-kick: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
    log-recipes-unknown-item: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
    log-convert-vanilla-blocks: false
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
chat-preview: false
ignore-server-compatibility-check: false
```

**Comment by SirCraftypants** [comment]
since updating it's the second issue to arise and the first still isn't solved.

**Comment by SirCraftypants** [comment]
I just reverted to Ia version r10 and all recipes are working again

**Comment by SirCraftypants** [comment]
I'd like to get this problem solved as i am unable to update to fix another problem i have where all my old custom armor works but my new custom armor will not load it's custom textures despite the fact they are setup the exist same way, ive literally checked about 30 times.

**Comment by SirCraftypants** [comment]
Updated to latest 3.2.5-r3 again, this time deleting the old config and regenerating a fresh updated config, didn't make the slightest bit of difference, gave default group under luckperms the new permissions listed below and still no change. Still can't use any recipes, not even when opped. not a single recipe works and to top that off all the new custom rendered armors i've just added will not load their custom textures despite the fact my already present customer armor work perfectly fine. Not a single problem with my configurations, i've checked them over and over a million times.

definitely huge issues with the latest versions. reverting back to 3.2.3-r10 when at least recipes still work until all this is fixed.

**Comment by SirCraftypants** [comment]
Everything has gone to shit, i can't even unzip my resource pack without it throwing errors.

  zip:
    protect-file-from-unzip:
      protection_1: false
      protection_2: false
      enabled: false
      extreme: false
    compress-png-files: false
    compress-json-files: false
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: false
    disable-overwrite-leather-armor-layers-textures: false

My new custom armors won't even load their custom textures.

**Comment by LoneDev6** [comment]
> without it throwing errors.

provide such errors

**Comment by SirCraftypants** [comment]
there are no errors in the console

**Comment by nhanledev** [comment]
This is urgent and cause duplication bug with crafting table, please fix!!!

**Comment by LoneDev6** [comment]
> This is urgent and cause duplication bug with crafting table, please fix!!!

Create a proper bug report and provide recipes configurations and a video to trigger the issue.

**Comment by LoneDev6** [comment]
Always create a single Github issue per issue, do not slap multiple issue reports in the same page.

**Comment by SirCraftypants** [comment]
> Always create a single Github issue per issue, do not slap multiple issue reports in the same page.

first i have no idea who nhanledev is or what their issue is but this github does not represent their issue.

Next you couldn't even help me with my first issue so you closed it. 

This is for the second issue with the recipes not working after updating from r10 to r3, as i said there are not errors in the console. All recipes, every single one does not work if i update to r3, the latest.

I will do another github for the custom armor texture issue once you solve this issue.

**Comment by LoneDev6** [comment]
Provide 2-3 recipes and their required items configurations in order to allow me to test.
Provide also a video showing how to trigger the issue.

**Comment by SirCraftypants** [comment]
> Provide 2-3 recipes and their required items configurations in order to allow me to test. Provide also a video showing how to trigger the issue.

https://paste.helpch.at/hajimatubi.yaml


Just try to create the item here in a workbench with the latest IA version, no video required, i gave myself the correct permissions according to the wiki and it wouldn't craft the item, result is an empty result slot.

**Comment by LoneDev6** [comment]
3.3.0-beta-r5 works fine, I might have fixed that in the meantime, wait for the update.

Please use shapeless recipes for that, do not create 9 recipes.
```yml
info:
  namespace: test
recipes:
  crafting_table:
    fossil:
      enabled: true
      permission: test.fossil
      shapeless: true
      ingredients:
        F: test:fossil
      result:
        item: BONE_MEAL
        amount: 2
loots:
  blocks:
    stone:
      type: STONE
      items:
        fossil:
          item: fossil
          min_amount: 1
          max_amount: 1
          chance: 2
  mobs:
    witch:
      type: WITCH
      items:
        item_1:
          item: GOLDEN_APPLE
          min_amount: 1
          max_amount: 1
          chance: 0
items:
  fossil:
    display_name: Fossil
    permission: fossil
    resource:
      material: IRON_INGOT
      generate: true
      textures:
      - item/fossil.png
```

**Comment by SirCraftypants** [comment]
Right, you've solved the multiple patterns issue but what about the hundreds of other recipes that don't work. I'm not a new user of Itemsadder, i've been using it for years. All my custom content was fine until i reached 3.2.0b-beta4, then some point from there between there and r10 it went to shit. So as it stands i have 3 issues that have all been reported on Github that have not to the best of my knowledge been solved.
