### ISSUE TITLE
API for - Chat preview (1.19+)

### ISSUE THREAD

**Issue by Lerphie** [PluginBugs/Issues-ItemsAdder#2080]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Coder#6926

### Describe the solution you'd like

I have my own plugin for chat and emoji. How can I attach them to the function of your plugin? "Chat preview (1.19+)"

### Is your feature request related to a problem?

Update the API for this task

### Describe alternatives you've considered

Update the API for this task

**Comment by LoneDev6** [comment]
Please add some details, I don't know what you are trying to do

**Comment by Lerphie** [comment]
@LoneDev6 Can I attach my chat plugin to your plugin?

**Comment by LoneDev6** [comment]
Mojang [removed chat preview](https://www.minecraft.net/en-us/article/minecraft-java-edition-1-19-3) in 1.19.3, this feature can't be added to ItemsAdder then.
![image](https://user-images.githubusercontent.com/27242001/206512585-af3e2a4a-0074-4990-a8b9-12900c2d216e.png)
