### ISSUE TITLE
Sugar cane block loots don't work well.

### ISSUE THREAD

**Issue by MCMANY** [PluginBugs/Issues-ItemsAdder#2083]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

냥집사#5330

### What happened?

Diamonds no  drop when destroying sugar canes. (please see yml file)

### Steps to reproduce the issue

Diamonds no  drop when destroying sugar canes. (please see yml file)

### Server version

This server is running Paper version git-Paper-235 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 1c1aeb2)
You are 29 version(s) behind
Download the new version at: https://papermc.io/downloads

### ItemsAdder Version

itemsadder 3.2.5-r3

### ProtocolLib Version

protocollib 5.0.0-SNAPSHOT-b602

### LoneLibs Version

LoneLibs 1.0.21

### LibsDisguises Version (optional)

LibsDisguises 10.0.31

### Problematic items yml configuration file (optional)

```shell
loots:
  blocks:
    test:
      type: SUGAR_CANE
      items:
        result_1:
          item: DIAMOND
          min_amount: 1
          max_amount: 1
          chance: 100
          ignore_fortune: true
```

**Comment by LoneDev6** [comment]
Seems to be caused by a Spigot incompatibility I can't fix.
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1594
