### ISSUE TITLE
No need to forcing unicode:false but show font-image right?

### ISSUE THREAD

**Issue by patatoplugin** [PluginBugs/Issues-ItemsAdder#2085]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

I use your plugin 'CosmeticCore' and find when I set unicode:true,the font-image can show right

I don't know how you make it true,Is it possbile for ItemsAdder's emoji and gui?

### Is your feature request related to a problem?

![QQ截图20221111003643](https://user-images.githubusercontent.com/62246956/201153849-0c0e7a57-ece0-461c-a5fd-b80e57137c88.png)
![QQ截图20221111003846](https://user-images.githubusercontent.com/62246956/201154511-81cdbc69-a165-498c-bf95-040e83787cf4.png)

### Describe alternatives you've considered

sorry but I don't know

**Comment by nhanledev** [comment]
+1 for this. I have seen this on Origin Realms which still shows some custom font images on the bossbar and action bar when FORCE UNICODE is on.

**Comment by LoneDev6** [comment]
It's not possible to do so with emojis because of some limitations.
