### ISSUE TITLE
incompatibility with Plugin ChestSort

### ISSUE THREAD

**Issue by JaHollTV** [PluginBugs/Issues-ItemsAdder#2090]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

Hey,
there is a Plugin ChestSort to sort inventories. 

The Problem is, that also ItemsAdder GUI`s can be sortet and so items can be cheated.

The ChestSort Developer also have a solution you can use:
https://github.com/JEFF-Media-GbR/ChestSort/issues/157

### Steps to reproduce the issue

install chestsort and sort the /ia gui

### Server version

all versions, cause of general plugin incompatibility

### ItemsAdder Version

ItemsAdder version 3.2.3-r10

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.21

**Comment by LoneDev6** [comment]
Answered on https://github.com/JEFF-Media-GbR/ChestSort/issues/157
