### ISSUE TITLE
ItemsAdder Recipe Book - Custom crafts are saved in the book and generate bugs.

### ISSUE THREAD

**Issue by matsitox** [PluginBugs/Issues-ItemsAdder#2098]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Rologod#4939

### What happened?

I need help with an ITEM DUPLICATION error in itemsadder.
The problem occurs with the recipe book, for some reason AI recipes appear in the vanilla minecraft recipe book (that shouldn't happen, I don't like it happening, I'd like to disable it).
The problem is that as soon as you enter the server and craft normally, the error does not occur.
But if you select an AI recipe inside the cookbook and close the GUI, from then on you will be able to craft Custom recipes with vanilla items like papers, sticks, etc.
As shown in the video.I need help with an ITEM DUPLICATION error in itemsadder.
The problem occurs with the recipe book, for some reason AI recipes appear in the vanilla minecraft recipe book (that shouldn't happen, I don't like it happening, I'd like to disable it).
The problem is that as soon as you enter the server and craft normally, the error does not occur.
But if you select an AI recipe inside the cookbook and close the GUI, from then on you will be able to craft Custom recipes with vanilla items like papers, sticks, etc.
As shown in the video.
Video 1: https://i.imgur.com/uEg2VXf.mp4

The problem is when you learn crafting.
If I craft any AI items, that crafting will be saved in the vanilla minecraft recipe book, allowing me to run the above bug that reports creating items with vanilla minecraft resources.

The solution would be that no AI crafting is saved in the recipe book.
(I have seen forums and lonedev clarified that this is deactivated, that it is not possible for it to happen, however it happens to me).

Video 2:
https://i.imgur.com/i7Rm7Hn.mp4

It should be noted that I don't have any other custom crafting plugins and I also don't have AI crafting by placing a single paper or stick in exchange for materials.
The plugin simply detects paper or sticks, or any basic minecraft material as if it were a custom ore or custom resource.

### Steps to reproduce the issue

1. You must craft any custom AI items within the crafting table.
2. You will see that this elaboration will be saved in the recipe book.
3. Without having the materials to run that custom craft again, you need to click on the custom item in the recipe book and it will appear in red (Because you don't have the materials to craft it).
4. Next you need to close the crafting GUI.
5. It should open the crafting table again and it will allow you to craft any custom items from itemsadder without having to have the plugin material, it will allow you to craft any items with sticks, papers or any vanilla minecraft materials.

### ItemsAdder Version

PaperMC 1.19.2

### ProtocolLib Version

Protocolib 1.19 Latest build. (Build: 602)

### LoneLibs Version

LoneLibs 1.0.21

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10023227/latest.log)

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: true
    self-host:
      enabled: false
      server-ip: 127.0.0.1
      pack-port: 8163
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      protection_1: true
      protection_2: true
    compress-png-files: true
    compress-json-files: true
    overwrite-vanilla-models: false
    overwrite-vanilla-lang-json: false
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    - bbmodel
    - iaentitymodel
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-configs: true
  legacy_pack: false
  force-sync-loading: false
blocks:
  light-api: false
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: true
  disable-FIRE: false
  convert-vanilla-blocks:
    enabled: false
    only-new-chunks: true
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
chat-preview: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    emotes: true
    interval-rendering-packets-ticks: 1
    optimized-packets: true
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-recipes-unknown-item: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
    log-convert-vanilla-blocks: false
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
ignore-server-compatibility-check: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

Video 1: https://i.imgur.com/uEg2VXf.mp4
Video 2:
https://i.imgur.com/i7Rm7Hn.mp4

**Comment by nhanledev** [comment]
Same problem as I reported in https://github.com/PluginBugs/Issues-ItemsAdder/issues/2093

The crafting recipe feature has been bugged since its support of shapeless crafting recipe to me.

**Comment by matsitox** [comment]
Unfortunately I couldn't fix the error.
So I was forced to create a custom plugin that cancels the recipe save event.
Use the itemsadder API and any vanilla item will save it in the Recipe book, in case it detects that it is an AI item it will remove the recipe saved to the user.

I will have to use this plugin that I create temporarily until the bug is fixed.

In the same way I wanted to report this error because many other users are having it too.

**Comment by nhanledev** [comment]
Can I have that plugin too? I'm still on 3.2.3 because of this bug.

**Comment by matsitox** [comment]
> Can I have that plugin too? I'm still on 3.2.3 because of this bug.

I'll upload it to Spigot as IaRecipeFixer while lonedev fixes the problem!

**Comment by matsitox** [comment]
@nhanledev https://www.spigotmc.org/resources/itemsadder-recipebook-fixer.106301/
:)

**Comment by nhanledev** [comment]
Thank you so much!

**Comment by nhanledev** [comment]
Looks like that plugin is not a proper fix for me, who unlocked the IA recipe before.

```
[23:31:42 INFO]: [IARecipeFixer] Enabling IARecipeFixer v1.0-SNAPSHOT
```

```
[23:31:41 INFO]: 
  ___  ___        __        __   __   ___  __      ItemsAdder 3.2.5-r3
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.21
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Paper git-Paper-271 (MC: 1.19.2)
```

https://user-images.githubusercontent.com/28459250/202504142-3d4cd1e8-cad0-4536-974d-6c8ab442889b.mp4

**Comment by matsitox** [comment]
> Looks like that plugin is not a proper fix for me, who unlocked the IA recipe before.
> 
> ```
> [23:31:42 INFO]: [IARecipeFixer] Enabling IARecipeFixer v1.0-SNAPSHOT
> ```
> 
> ```
> [23:31:41 INFO]: 
>   ___  ___        __        __   __   ___  __      ItemsAdder 3.2.5-r3
> |  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.21
> |  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Paper git-Paper-271 (MC: 1.19.2)
> ```
> 
>  2022-11-17.23-35-39.mp4

If you previously unlocked recipes.
You can remove them with
/recipe take (your user) *

**Comment by matsitox** [comment]
with the command
/recipe take user *

That will remove all previously learned recipes.
What the plugin does is that users cannot save the AI recipes to the recipe book.

**Comment by nhanledev** [comment]
Thank you so much for the instruction. I would run that command on user join event. I hope this get fixed soon ❤️

**Comment by LoneDev6** [comment]
Is the issue still occurring on the new update?
Anyway duplication bugs must not be reported publicly... I stated it clearly, you must create a private ticket on my Discord.

**Comment by matsitox** [comment]
Hi Lonedev!
Sorry for making this ticket public, and sorry if I miscreated it.

The error still persists in the most recent version of Itemsadder.
Here I attach all my configuration in case you want to try it.
https://www.mediafire.com/file/q3a8h4l1oyuu15l/ItemsAdderCONFIG.rar/file

**Comment by matsitox** [comment]
> Is the issue still occurring on the new update? Anyway duplication bugs must not be reported publicly... I stated it clearly, you must create a private ticket on my Discord.

Hi Lonedev!
Sorry for making this ticket public, and sorry if I miscreated it.

The error still persists in the most recent version of Itemsadder.
Here I attach all my configuration in case you want to try it.
https://www.mediafire.com/file/q3a8h4l1oyuu15l/ItemsAdderCONFIG.rar/file
