### ISSUE TITLE
ItemsAdder produces malformed JSON for default.json font file

### ISSUE THREAD

**Issue by Andre601** [PluginBugs/Issues-ItemsAdder#2099]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Andre_601#0601

### What happened?

Checking the `default.json` font file generated by ItemsAdder, it seems like the JSON itself is malformed, as shown by this screenshot:
![image](https://cdn.discordapp.com/attachments/1042098842297978890/1042533779002114048/image.png)

### Steps to reproduce the issue

1. Create a resource pack using `/iazip` (Make sure it's not protected to extract files)
2. Extract the JSON file `default.json` located in `assets/minecraft/font/`
3. Run the JSON through a JSON validator

### Server version

[21:22:32 INFO]: This server is running Paper version git-Paper-256 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: e30b082)
You are 15 version(s) behind

### ItemsAdder Version

[21:22:45 INFO]: ItemsAdder version 3.2.5-r3
[21:22:45 INFO]: Customized Minecraft without client mods!
[21:22:45 INFO]: Website: devs.beer
[21:22:45 INFO]: Author: LoneDev

### ProtocolLib Version

[21:23:01 INFO]: ProtocolLib version 5.0.0-SNAPSHOT
[21:23:01 INFO]: Provides read/write access to the Minecraft protocol.
[21:23:01 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[21:23:06 INFO]: LoneLibs version 1.0.21
[21:23:06 INFO]: Collection of libs used by my plugins
[21:23:06 INFO]: Authors: LoneDev and others

### FULL server log

https://mclo.gs/2bHd1s7

### Other files, you can drag and drop them here to upload. (optional)

The malformed JSON file (Uploaded as TXT due to GitHub restrictions):
[default.json.txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/10025438/default.json.txt)

**Comment by nhanledev** [comment]
I have the same problem

![image](https://user-images.githubusercontent.com/28459250/202365607-08187c22-3342-487c-ba30-04d11b80df63.png)

**Comment by nhanledev** [comment]
Hi, can you please delete the file at `plugins/ItemsAdder/storage/cache/tmp/resource_pack/assets/minecraft/font/.default.json` and do `/iaz` again to check if it still broken? Mine was broken but looks like that fix the problem

**Comment by Andre601** [comment]
It got fixed for me too...
I *would* suggest that IA would do a basic check for the default.json file and print warnings if it got malformed, but LoneDev is changing the way resource packs are made in IA, which would from what I understand remove the default.json file completely from its cache stuff... If that won't be the case, then I'll reopen this (Or LoneDev can do that in such a case).

**Comment by LoneDev6** [comment]
New version implements validation on font files and skips malformed entries or whole files if needed.
