### ISSUE TITLE
[BUG] Preview sharpness enchantment on anvil

### ISSUE THREAD

**Issue by alejandro0256** [PluginBugs/Issues-ItemsAdder#210]
**Describe the bug**
This isn't an important bug but it would be nice to see updated the attack damage lore on the preview when you are enchanting with books on an anvil

**To Reproduce**
1. Enchant a sword of the plugin whit sharpness using an anvil

**Screenshots**
https://imgur.com/a/RXXYVO3

**Info (please complete the following information):**
Server version: paper 1.15.2 (Build: 220)
Client version: minecraft Optifine
Plugin version: 2.0.18

**Comment by LoneDev6** [comment]
Thanks for the report, I will see if I can update it without making the server laggy as i'd have to wait 1 tick before updating the result slot, so if a lot of players are using anvil it will probably be laggy.

i will leave this report open until i've done further tests

**Comment by LoneDev6** [comment]
fixed https://github.com/PluginBugs/Issues-ItemsAdder/issues/748
