### ISSUE TITLE
Emotes features

### ISSUE THREAD

**Issue by D-Captain-WAIS** [PluginBugs/Issues-ItemsAdder#2106]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

D. Captain#2487

### Describe the solution you'd like

Emotes being able to be done in the air as well as not being interrupted by damage.

### Is your feature request related to a problem?

I've got some player animations I'm trying to make be available sometimes during the air but when I proc the command, the emote doesn't play. As well as when the emote is playing, it stops when the player is damaged. 

### Describe alternatives you've considered

I can't think of any alternatives at the moment

**Comment by LoneDev6** [comment]
Do you have any idea on how to implement that?
Would they be command arguments? 
`/emote death LoneDev ignore-air ignore-damage` ?

**Comment by D-Captain-WAIS** [comment]
> Do you have any idea on how to implement that?
> 
> Would they be command arguments? 
> 
> `/emote death LoneDev ignore-air ignore-damage` ?

I think the ignore-air command isn't necessarily needed, as the emote should play regardless of whether you're on the ground or not, but it is a good way to give the users options. The ignore-damage parameter though sounds like a great way to implement that part.

**Comment by D-Captain-WAIS** [comment]
> Do you have any idea on how to implement that? Would they be command arguments? `/emote death LoneDev ignore-air ignore-damage` ?

Just to be clear: ignore-damage still allows you to take damage it just doesn't stop the emote

**Comment by LoneDev6** [comment]
Continues here: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2170

**Comment by LoneDev6** [comment]
Implemented and will be available in the next release
