### ISSUE TITLE
World not loading for vanilla clients

### ISSUE THREAD

**Issue by BookWyrm114** [PluginBugs/Issues-ItemsAdder#2110]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

Since updating to the latest version of IA, any vanilla clients are stuck on the world loading screen, or the world will load but not render, downgrading back to 3.2.5-r3 did not fix the issue. I've only encountered this issue with vanilla clients though, and the server has no errors, so I've included the errors from the vanilla client log as well.

### Steps to reproduce the issue

start a sever on 3.3.0-beta-r4, or upgrade an older version of IA to that version, and try to join the server with a vanilla client

### Server version

git-Purpur-1845 (MC: 1.19.2)

### ItemsAdder Version

3.2.5-r4

### ProtocolLib Version

5.0.0-SNAPSHOT-b602

### LoneLibs Version

1.0.21

### FULL server log

THIS IS THE VANILLA CLIENT ERROR

[error.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10060729/error.log)

**Comment by BookWyrm114** [comment]
And yes, I know that this issue was caused by the IA update, I joined my server with a vanilla client just earlier today and everything worked fine, after the update however, one of my players informed me that the world was not loading for them and upon joining with a vanilla client the world failed to load for me as well.

**Comment by LoneDev6** [comment]
The new ItemsAdder update didn't change anything about world loading or related things.
I don't see how it can cause this issue sincerely.

**Comment by LoneDev6** [comment]
What you can do is send here your server address so that I can join and read the deobfuscated error, since vanilla clients show the obfuscated error and it's not possible for me to guess what can be the issue.
```
java.lang.IllegalArgumentException: No value with id 21603
	at hf.b(SourceFile:19) ~[1.19.2.jar:?]
	at cxr.a(SourceFile:74) ~[1.19.2.jar:?]
	at cya.a(SourceFile:174) ~[1.19.2.jar:?]
	at cxu.a(SourceFile:169) ~[1.19.2.jar:?]
	at cxt.a(SourceFile:448) ~[1.19.2.jar:?]
	at eut.a(SourceFile:102) ~[1.19.2.jar:?]
	at euw.a(SourceFile:709) ~[1.19.2.jar:?]
	at euw.a(SourceFile:704) ~[1.19.2.jar:?]
	at uo.a(SourceFile:45) ~[1.19.2.jar:?]
	at uo.a(SourceFile:12) ~[1.19.2.jar:?]
	at te.a(SourceFile:22) ~[1.19.2.jar:?]
	at ayz.d(SourceFile:157) [1.19.2.jar:?]
	at azd.d(SourceFile:23) [1.19.2.jar:?]
	at ayz.x(SourceFile:131) [1.19.2.jar:?]
	at ayz.bq(SourceFile:116) [1.19.2.jar:?]
	at efu.f(SourceFile:1129) [1.19.2.jar:?]
	at efu.e(SourceFile:768) [1.19.2.jar:?]
	at net.minecraft.client.main.Main.a(SourceFile:244) [1.19.2.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:51) [1.19.2.jar:?]
```

**Comment by BookWyrm114** [comment]
Sure thing: dragon-craft.club

**Comment by BookWyrm114** [comment]
Actually, I’m using iris and itemsadder block injector, do you think that could have caused the issue somehow?

**Comment by BookWyrm114** [comment]
The block id files still have all block in them, and all custom blocks work fine, I've enabled debug mode but haven't seen any errors from it. Vanilla clients are still unable to load the world: 
![2022-11-22_09 11 58](https://user-images.githubusercontent.com/79489385/203335739-ec32e707-408e-4222-b767-8ac4df46bbea.png)
But for some reason modded clients work fine, it may be something patched by sodium or lithium or something. It also seems to be completely unrelated to the resourcepack since it still occurs if the client does not load the pack.

Here is the server log:
[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10068146/latest.log)

**Comment by LoneDev6** [comment]
Probably modded clients simply discard not-existing blocks to avoid kick/crash.

The block injector is not even printing anything in console for some reason. This is not normal. Did you create the config file?

**Comment by BookWyrm114** [comment]
thanks!

**Comment by LoneDev6** [comment]
This fixes some little issues and allows the config.yml file to work.
Create the file if it doesn't exists.
`plugins/ItemsAdderBlocksInjector/config.yml`
```yml
debug: true
```

[itemsadder-blocks-injector_0.0.6.jar.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/10068576/itemsadder-blocks-injector_0.0.6.jar.zip)

**Comment by BookWyrm114** [comment]
Here's the new log, debug mode seems to be working now.

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10068640/latest.log)

**Comment by BookWyrm114** [comment]
no, I don't get kicked, but when joining in vanilla the world simply won't render, and I'm unable to move

**Comment by LoneDev6** [comment]
> but when joining in vanilla the world simply won't render

Did you delete any custom block from configurations?
Do they actually exit in itemsadder configurations? Can you try /iaget command to get some of the blocks?

**Comment by BookWyrm114** [comment]
I have since downgraded to 3.2.5-r4, but the issue still persists, maybe the block injector caused a problem with iris after the update?

**Comment by LoneDev6** [comment]
Mmh.. I sincerely have no idea, the blocks work fine for me.
I don't see how the ItemsAdder update has to do with that issue since the blocks cache files ware untouched.
There is something else which is not clear

**Comment by BookWyrm114** [comment]
what it is it?

**Comment by LoneDev6** [comment]
Itemsadder block injector reads the cache files inside storage folder, as i said before.
These files contain the registered itemsadder blocks ids.

**Comment by BookWyrm114** [comment]
oh, various/cache.nbt and various/fix_glitched_blocks.nbt are empty, however real_note_block_ids_cache.yml is normal

**Comment by LoneDev6** [comment]
Seems that for some reason the injector is assigning different internal IDs, this is causing the plugin to not recognized previously generated blocks and is skipping them.

`fix_glitched_blocks.nbt` ignore it

**Comment by BookWyrm114** [comment]
is there a way to easily fix this issue?

**Comment by LoneDev6** [comment]
Not that I can think of since mine is just a supposition, I sincerely have no idea why this happened and I cannot reproduce it.
Note that the whole injector thing is an hack and I coded it just to add Iris support since there is no other way to do so.

**Comment by BookWyrm114** [comment]
I can also enable debug mode on iris and send you the server log as well as the real_note_block_ids_cache.yml if that would help figure out the issue

**Comment by BookWyrm114** [comment]
ok, I can upload those so you can test them, I can also upload my modified overworld pack for iris that generates the ores.

**Comment by BookWyrm114** [comment]
[overworld.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/10068981/overworld.zip)
[storage.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/10068985/storage.zip)
The world file (zipped) is 2.5 GB, I'll try uploading it to dropbox but it might be a while

**Comment by BookWyrm114** [comment]
wait nevermind it's too big for dropbox

**Comment by BookWyrm114** [comment]
Ok, I found the issue

**Comment by BookWyrm114** [comment]
Apparently it is somehow caused by viaversion, I noticed a strange error log about 1.18 -> 1.19 blockstates and decided to remove ViaVersion and Viabackwards, and now everything works for some reason.

**Comment by BookWyrm114** [comment]
[2022-11-24-1.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10086092/2022-11-24-1.log)

**Comment by BookWyrm114** [comment]
ok I realized that removing that messed up the block injector so I re-installed viaversion but regenerated the config and also didn't add viabackwards and it works. I still have no idea what the issue was but I'll just I assume it was something I misconfigured.

**Comment by BookWyrm114** [comment]
Ok nevermind, as long as itemsadderblocksinjector is active, vanilla clients can't join. Should I make an issue on the itemsadderblocksinjector github instead?

**Comment by LoneDev6** [comment]
> Ok nevermind, as long as itemsadderblocksinjector is active, vanilla clients can't join. Should I make an issue on the itemsadderblocksinjector github instead?

Yep
