### ISSUE TITLE
wrong mushroom block textures

### ISSUE THREAD

**Issue by patatoplugin** [PluginBugs/Issues-ItemsAdder#2114]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

neverlag#6619

### What happened?

the new resourcepack have wrong mushroom textures
I don't use any REAL BLOCKS,and my contents have deleted blockstate,but new resourcepack still wrong
![2022-11-22_15 10 26](https://user-images.githubusercontent.com/62246956/203248600-17628243-a1ff-4b89-b0fa-c7b4198b5d8a.png)
![2022-11-22_15 10 14](https://user-images.githubusercontent.com/62246956/203248571-6726e53a-9bf4-4e41-b40d-948d09482708.png)

### Steps to reproduce the issue

1. iazip
2. find a  big red mushroom

### Server version

git-Purpur-1765 (MC: 1.19.2)*

### ItemsAdder Version

 3.3.0-beta-r4

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b602

### LoneLibs Version

 LoneLibs version 1.0.21

**Comment by LoneDev6** [comment]
> have deleted blockstate

Are you sure you deleted the blockstates file? `minecraft/blockstates/red_mushroom_block.json`
Check in every `contents` subfolder.

Also make sure to regenerate your zip file.

The plugin doesn't generate and add `red_mushroom_block` file in the zip if `disable-REAL: true` is in config.yml.

**Comment by LoneDev6** [comment]
Very good! :D
