### ISSUE TITLE
Using emotes will override player_head.json

### ISSUE THREAD

**Issue by patatoplugin** [PluginBugs/Issues-ItemsAdder#2115]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

I tried to change the player_head's display in blockbench.
And it is ok 
![2022-11-22_02 00 29](https://user-images.githubusercontent.com/62246956/203250722-d3895d9b-7779-49a3-9dbe-9baf8d1d05b4.png)
![2022-11-22_02 02 14](https://user-images.githubusercontent.com/62246956/203250746-311b3a1c-2dfd-48b9-9238-09b6dcd42d09.png)

But after I set emotes: true, the auto-generate resourcepack will override it.

### Steps to reproduce the issue

1.change the player_head.json (for example copy my file and change txt to json)
[player_head.txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/10064898/player_head.txt)

2.put it in minecraft/models/item
3.use /iazip
4. see the head is bigger
5. set emotes: true in config.yml
6. use /iazip
7. the head is default size (because the player_head.json is override)

### Server version

git-Purpur-1765 (MC: 1.19.2)*

### ItemsAdder Version

ItemsAdder version 3.3.0-beta-r4

### ProtocolLib Version

 ProtocolLib version 5.0.0-SNAPSHOT-b602

### LoneLibs Version

LoneLibs version 1.0.21

**Comment by LoneDev6** [comment]
Will be fixed, thanks
