### ISSUE TITLE
self-host not working!

### ISSUE THREAD

**Issue by R3voolt** [PluginBugs/Issues-ItemsAdder#2118]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Revoolt#7867

### What happened?

New IA folder, using latest IA, using same server ip /pack port that i used 2 days ago with the 3.2.5 version where it was working perfectly!

### Steps to reproduce the issue

New IA folder, using latest IA, using same server ip /pack port that i used 2 days ago with the 3.2.5 version where it was working perfectly!

### Server version

https://gyazo.com/430f2f27557d0ecf42a78e5b62247ded

### ItemsAdder Version

https://gyazo.com/7ad29b604d47984cf82b1dd7e138a861

### ProtocolLib Version

https://gyazo.com/66a022faa48262ced81c3d3110d0b797

### LoneLibs Version

https://gyazo.com/90004216e6af93d7044c8bbd3025bd0c

### LibsDisguises Version (optional)

https://gyazo.com/4ed0b1848ecb5cb8b2755a117dc1a821

### FULL server log

https://pastebin.com/5zxw9fHq

### ItemsAdder config.yml

```shell
https://pastebin.com/72J3c4E3
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://gyazo.com/403699bdf3179d9cd8e8333a065ecdff

**Comment by TaakoOfficial** [comment]
I too am having this issue on Self hosting

**Comment by iqtesterr** [comment]
me either

**Comment by evilsaloon** [comment]
When I run /iainfo and follow the resourcepack download URL, it says that the file doesn't exist, even though it exists on the server.

/iainfo output:
```
[22:00:12 INFO]: -=[ ItemsAdder ]=-
[22:00:12 INFO]: Version: 3.3.0-beta-r5
[22:00:12 INFO]: ResourcePack
[22:00:12 INFO]:      Path: /container/plugins/ItemsAdder/output/generated.zip
[22:00:12 INFO]:      Download: http://eu-16.enviromc.net:25643/generated.zip#0734f74ff158c19fcf1053a9e2f27c01fdc76e0d
[22:00:12 INFO]:      Size: 427 KB/250 MB
[22:00:12 INFO]:      Last update: 2022-11-22 22:00:09
[22:00:12 INFO]:      Host type: self-host
[22:00:12 INFO]: Data
[22:00:12 INFO]:      Items: 168
[22:00:12 INFO]:      Items in /ia: 128
[22:00:12 INFO]:      Namespaces: 5
[22:00:12 INFO]:      Materials: 9
[22:00:12 INFO]:      REAL block IDs: 0/191
[22:00:12 INFO]:      REAL_NOTE block IDs: 121/750
[22:00:12 INFO]:      REAL_TRANSPARENT block IDs: 2/63
[22:00:12 INFO]:      REAL_WIRE block IDs: 4/127
[22:00:12 INFO]:      FIRE block IDs: 0/14
[22:00:12 INFO]:      Font images: 60/6608
[22:00:12 INFO]: Loaded chunks (1587)
[22:00:12 INFO]:      Armorstands: 0
[22:00:12 INFO]:      Mobs: 0
```

A few minutes after visiting the URL, this message pops up in the console:
```
[22:02:36 ERROR]: [ItemsAdder] Unexpected I/O error while handling webserver request: 
[22:02:36 WARN]: java.io.FileNotFoundException
[22:02:36 WARN]:        at ItemsAdder_3.3.0-beta-r5.jar//dev.lone.itemsadder.main.iC.run(SourceFile:38)
```

I've checked the folder, and the file exists. I think the issue is a missing "/" before the file path in the code, but without access to the source I can't check. Good luck!

**Comment by TaakoOfficial** [comment]
> When I run /iainfo and follow the resourcepack download URL, it says that the file doesn't exist, even though it exists on the server.
> 
> /iainfo output:
> 
> ```
> [22:00:12 INFO]: -=[ ItemsAdder ]=-
> [22:00:12 INFO]: Version: 3.3.0-beta-r5
> [22:00:12 INFO]: ResourcePack
> [22:00:12 INFO]:      Path: /container/plugins/ItemsAdder/output/generated.zip
> [22:00:12 INFO]:      Download: http://eu-16.enviromc.net:25643/generated.zip#0734f74ff158c19fcf1053a9e2f27c01fdc76e0d
> [22:00:12 INFO]:      Size: 427 KB/250 MB
> [22:00:12 INFO]:      Last update: 2022-11-22 22:00:09
> [22:00:12 INFO]:      Host type: self-host
> [22:00:12 INFO]: Data
> [22:00:12 INFO]:      Items: 168
> [22:00:12 INFO]:      Items in /ia: 128
> [22:00:12 INFO]:      Namespaces: 5
> [22:00:12 INFO]:      Materials: 9
> [22:00:12 INFO]:      REAL block IDs: 0/191
> [22:00:12 INFO]:      REAL_NOTE block IDs: 121/750
> [22:00:12 INFO]:      REAL_TRANSPARENT block IDs: 2/63
> [22:00:12 INFO]:      REAL_WIRE block IDs: 4/127
> [22:00:12 INFO]:      FIRE block IDs: 0/14
> [22:00:12 INFO]:      Font images: 60/6608
> [22:00:12 INFO]: Loaded chunks (1587)
> [22:00:12 INFO]:      Armorstands: 0
> [22:00:12 INFO]:      Mobs: 0
> ```
> 
> A few minutes after visiting the URL, this message pops up in the console:
> 
> ```
> [22:02:36 ERROR]: [ItemsAdder] Unexpected I/O error while handling webserver request: 
> [22:02:36 WARN]: java.io.FileNotFoundException
> [22:02:36 WARN]:        at ItemsAdder_3.3.0-beta-r5.jar//dev.lone.itemsadder.main.iC.run(SourceFile:38)
> ```
> 
> I've checked the folder, and the file exists. I think the issue is a missing "/" before the file path in the code, but without access to the source I can't check. Good luck!

When I click my link it trys to go to this link http://generated.zip#eeecf7a9Ø647a7b2Ø3b8a5?fe1564468bce94a1?

**Comment by LoneDev6** [comment]
does this file exists? `home/container/plugins/ItemsAdder/output/generated.zip not found`

> When I click my link it trys to go to this link [http://generated.zip#eeecf7a9Ø647a7b2Ø3b8a5?fe1564468bce94a1](http://generated.zip/#eeecf7a9%C3%98647a7b2%C3%983b8a5?fe1564468bce94a1)?

Minecraft chat bug. Ignore it.

**Comment by TaakoOfficial** [comment]
> 

Yeah it's all there and in the right areas 
![image](https://user-images.githubusercontent.com/4751889/203442682-72cf29cb-7456-40db-ab4c-5ab079f8b76c.png)

**Comment by LoneDev6** [comment]
Somehow it doesn't like it for some reason. Might be because of the panel type.
I will do some research now.

**Comment by evilsaloon** [comment]
> Does this file exists? `home/container/plugins/ItemsAdder/output/generated.zip` Is the server path correct? `home/container/` ? If not, well, seems somehow ItemsAdder is recognizing the wrong server folder in the new update, for some reason.

The path is correct, and the file exists there. Probably a panel problem. The panel I'm using is Pterodactyl.

**Comment by LoneDev6** [comment]
Interesting, and it worked fine on 3.2?

**Comment by LoneDev6** [comment]
@evilsaloon what is your Discord username? I can add you to the beta testing channel so that you can test on your server and let me know how it goes

**Comment by evilsaloon** [comment]
> Interesting, and it worked fine on 3.2?

Yep. I didn't change the config at all when I updated.

**Comment by evilsaloon** [comment]
> @evilsaloon what is your Discord username? I can add you to the beta testing channel so that you can test on your server and let me know how it goes

evilsaloon#3438

**Comment by TaakoOfficial** [comment]
> Interesting, and it worked fine on 3.2?

Yep worked fine on beta r4 So yeah, I'd also like to be added to the beta channel to help with this testing

**Comment by LoneDev6** [comment]
@TaakoOfficial provide your Discord username.
Anyway strange, I doubt it worked on r4 but not on r5, I didn't change anything about respack hosting.

**Comment by TaakoOfficial** [comment]
Sure thing it's Taako#1337

> @TaakoOfficial provide your Discord username. Anyway strange, I doubt it worked on r4 but not on r5, I didn't change anything about respack hosting.

**Comment by ArubikU** [comment]
> > Interesting, and it worked fine on 3.2?
> 
> Yep worked fine on beta r4 So yeah, I'd also like to be added to the beta channel to help with this testing

strangue for you work the r4? because for me not and well the actual version dont work more bugs but this related to "bad config" but is strangue the config is the same of the 3.2 only moved files

**Comment by R3voolt** [comment]
damn, was sleeping and missed all this! r8 fixed it and self hosting works perfectly for me now !
Thanks you !

**Comment by Lidorking1** [comment]
Doesn't work for me either and I'm on the ItemsAdder v4.0.2-beta-release-10 version

**Comment by LoneDev6** [comment]
@Lidorking1 
Do not comment on 2 years old issues, thanks.
This is probably a misconfiguration of the resourcepack port (might not be reachable, check if open), wrong ip or your hosting is blocking it.
