### ISSUE TITLE
3.3.0 broken

### ISSUE THREAD

**Issue by HakanUnsalP** [PluginBugs/Issues-ItemsAdder#2119]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Hakan#4089

### What happened?

I installed it fresh and it doesn't work

### Steps to reproduce the issue

.

### Server version

1.19.2 Purpur

### ItemsAdder Version

3.3.0-beta-r5

### ProtocolLib Version

5.0.0-SNAPSHOT-b600

### LoneLibs Version

1.0.21

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10070687/latest.log)

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/2120
