### ISSUE TITLE
Eco Enchants bug

### ISSUE THREAD

**Issue by Invalid-Z** [PluginBugs/Issues-ItemsAdder#2122]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Invalid Z#0001

### What happened?

Eco Enchants compatibility issue. If a player combines two identical items that have separate enchants, the enchants from EcoEnchants are lost while vanilla ones are not. Only happens with ItemsAdder items and EcoEnchants enchants

### Steps to reproduce the issue

Apply Eco Enchants to "CustomSword", in this example we will call "A". Get another "CustomSword" of the same itemsadder item, we will call it "B". Apply different eco enchants to B. Then combine A and B in an anvil and the resulting item loses ALL Eco enchants

### Server version

git-Paper-258 (MC: 1.19.2)

### ItemsAdder Version

ItemsAdder version 3.2.5-r3

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b602

### LoneLibs Version

LoneLibs version 1.0.21

**Comment by LoneDev6** [comment]
> Apply Eco Enchants to "CustomSword"

how?

Please make a video.
