### ISSUE TITLE
Better command `/ia`

### ISSUE THREAD

**Issue by Akiranya** [PluginBugs/Issues-ItemsAdder#2131]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [x] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Nailm#9364

### Describe the solution you'd like

Currently the `/ia` command directly opens the GUI of **all** categories.

I would like this command to have the following new features:

1. Players can use `/ia <category name>` to directly opens a GUI for a specific category
2. GUI opened this way does not have "back" button to go back to the main GUI (opened by `/ia`)
3. Console/OP can use `/ia <category name> <playername>` to **force open** a specific category for a specific player
4. This command respects the permission `ia.menu.seecategory.<category name>` so if the player doesn't have the permission IA will send a proper message (**but** when Console/OP uses `/ia <category name> <playername>` the player can bypass the permission)

### Is your feature request related to a problem?

None

### Describe alternatives you've considered

I was thinking about a alternative but none of them can fulfill all my needs, but for completeness I just post an alternative:

I considered creating a new category (let's call it `X`) and only giving the permission `ia.menu.seecategory.X` to players so when they type `/ia` they only see this category and can only view the items in this category. But it's kinda cumbersome - having a GUI that only has a single available option is not so intuitive. And tweaking the permission to achieve this is also a bit hassle. Most importantly, console cannot run `/ia` to force open the GUI, which limits the interactions between IA and other "script" plugins

### Additional context

I was creating a in-game tutorial for my server and I wanted to force open a GUI from the console/other plugin scripts, to show a list of important recipes for the new players. But the alternatives couldn't fulfill the need (cuz console cannot run `/ia` currently) that's mainly why I requested this feature. The requested feature shouldn't be difficulty to implement but I believe it will be quite useful because it will definitely improve the interactions between IA and other "script" plugins and therefore the server developers will be able to easily present the recipes of specific custom items to their players in a more flexibale way!

**Comment by LoneDev6** [comment]
Will be implemented, thanks.

What do you think about these permissions? Based on the [already existing ones](https://itemsadder.devs.beer/plugin-usage/permissions) structure.
`ia.user.ia.categories`
`ia.user.ia.categories.others`

**Comment by Akiranya** [comment]
Not sure if I understand correctly..

If
`ia.user.ia.categories`
controls whether the player has access to `/ia` for themselves

and
`ia.user.ia.categories.others`
controls whether the player has access to `/ia` for opening gui for other players

then I think all good!

**Comment by LoneDev6** [comment]
`ia.user.ia`
allows accessing `/ia` without categories argument

`ia.user.ia.categories`
controls whether the player has access to `/ia <category>` for themselves

`ia.user.ia.categories.others`
controls whether the player has access to `/ia` for opening gui for other players

**Comment by Akiranya** [comment]
Hey Lone, I just found some features are not implemented:

> 1. Players can use `/ia <category name>` to directly opens a GUI for a specific category
> 2. GUI opened this way does not have "back" button to go back to the main GUI (opened by `/ia`)
> 3. Console/OP can use `/ia <category name> <playername>` to **force open** a specific category for a specific player
> 4. This command respects the permission `ia.menu.seecategory.<category name>` so if the player doesn't have the permission IA will send a proper message (**but** when Console/OP uses `/ia <category name> <playername>` the player can bypass the permission)

2 and 3 are not fully implemented...

For 2, it still has a `back button` if the category GUI is opened by `/ia <category name>`
For 3, the console couldn't run the command.

Could you also implement these features as well? These are really important to seamlessly interact with other scripts/plugins

**Comment by LoneDev6** [comment]
Thanks this will be addressed in the upcoming update
https://github.com/PluginBugs/Issues-ItemsAdder/issues/2310
