### ISSUE TITLE
Losing items when crafting at last durability

### ISSUE THREAD

**Issue by frim23** [PluginBugs/Issues-ItemsAdder#2132]
### What happened?

If you make a craft that lowers the durability of the specified item, and the specified item is at its last durability, the craft is not made and all the resources are simply lost.

https://user-images.githubusercontent.com/74869618/203871004-aca8c26b-cda5-42ed-9397-d646cdc5bdab.mp4

### Steps to reproduce the issue

1. Create a craft with "decrement_durability" feature
2. Break specified "decreament_durability" item to its last durability
3. Try to perform created craft

### Server version

Paper version git-Paper-273 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: b4c1ae6)

### ItemsAdder Version

ItemsAdder Version 3.3.0-beta-r8

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b602

### LoneLibs Version

LoneLibs version 1.0.21

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/AQLyJPpF0LM

**Comment by LoneDev6** [comment]
Update to r9 and let me know.

Related: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2143 https://github.com/PluginBugs/Issues-ItemsAdder/issues/2144 https://github.com/PluginBugs/Issues-ItemsAdder/issues/2140

**Comment by frim23** [comment]
Still not working
