### ISSUE TITLE
The chorus and copy bugs

### ISSUE THREAD

**Issue by cats-love** [PluginBugs/Issues-ItemsAdder#2134]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

If you use half-block, barrel (important), or attic door, the chorus is copied.

If you use drop2inv, the chorus part is copied

![2022-11-18_04 15 35](https://user-images.githubusercontent.com/87476958/203914231-54a2427b-e1c9-4cb3-aeac-68e9ea5f3864.png)
![Uploading 2022-11-18_04.17.39.png…]()

### Steps to reproduce the issue

drop2inv auto-pickup enabled
Interact with barrels, attic doors, etc. in front of custom leaves
Chorus and drop for each interaction

### Server version

1.19.2

### ItemsAdder Version

[3.2.5-r3]

### ProtocolLib Version

602 build 

### LoneLibs Version

1.0.21

**Comment by LoneDev6** [comment]
Update ItemsAdder, this issue might have been fixed before.

**Comment by LoneDev6** [comment]
Also I have no idea of what drop2inv is

**Comment by cats-love** [comment]
https://www.spigotmc.org/resources/%E2%AD%90-drop2inventory-plus-%E2%AD%90.87784/ 
This is the appropriate plug-in. 
Changing the settings of the plug-in only allows temporary actions and does not find a solution to the underlying bug.

**Comment by LoneDev6** [comment]
Please can you make a video?
This is not really clear, thanks

**Comment by mfnalex** [comment]
Hi, I am actually confused. I got no idea what an attic door is, nor how ItemsAdder works in the first place (like, is this bug here reporting issues about furnitures that use chorus plants internally? Or what is this issue about?)

I'd also love to see about video so I can understand what the actual problem is, thanks :)

**Comment by mfnalex** [comment]
Just to explain how D2I works: Drop2InventoryPlus listens to ItemSpawnEvent, then calls an EntityPickupItemEvent. If that is not cancelled by any plugin, the ItemSpawnEvent is cancelled, and the item is added to the player's inventory.

**Comment by LoneDev6** [comment]
I too have no idea about how the issue can be reproduced.
I need a proper video which shows exactly how to reproduce the problem.
