### ISSUE TITLE
THE TRIPWIRE.JSON IS NOT UPDATED.

### ISSUE THREAD

**Issue by PanBimboBoy** [PluginBugs/Issues-ItemsAdder#2136]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Bimbo#6698

### What happened?

The tripwire.json is not updated when creating a model with the block type REAL_WIRE, when I try to place it in the world it is as if it were a normal rope, check the tripwire.json and it is not updated when doing /iazip.

### Steps to reproduce the issue

You can use the clean WorldDeco addon to check it.
https://www.spigotmc.org/resources/deco-worlddeco-add-autogenerating-decorations-on-your-world-surface-for-itemsadder.95207/
PS: it appears on certain worlddeco models

### Server version

git-petal-"d448170" (MC: 1.19.2)*

### ItemsAdder Version

ItemsAdder version 3.3.0-beta-r8

### ProtocolLib Version

 ProtocolLib version 5.0.0-SNAPSHOT-b600

### LoneLibs Version

LoneLibs version 1.0.21

### ItemsAdder config.yml

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: 127.0.0.1
      pack-port: 2342
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      protection_1: true
      protection_2: true
    compress-png-files: true
    compress-json-files: true
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    - bbmodel
    - iaentitymodel
    fix_transparent_noteblocks: false
    contents-folders-priority:
    - vanilla
    - _iainternal
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  force-sync-loading: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: false
  disable-FIRE: false
  convert-vanilla-blocks:
    enabled: false
    only-new-chunks: true
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
chat-preview: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: false
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: false
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: false
    replace-in-customitems-name-and-lore: false
    chat:
      enabled: false
    sign:
      enabled: false
    book:
      enabled: false
    anvil:
      enabled: false
entities:
  max-furniture-vehicles-per-chunk: 60
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    emotes: true
    interval-rendering-packets-ticks: 1
    optimized-packets: true
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-recipes-unknown-item: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
    log-convert-vanilla-blocks: false
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
ignore-server-compatibility-check: false
```

### Problematic items yml configuration file (optional)

```shell
#banana_stage
  banana_stage_1:
    display_name: ""
    resource:
      generate: false
      material: PAPER
      model_path: plants/cultivos/banana/banana_stage_1
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true
        sound:
          place:
            name: block.azalea.place
          break:
            name: block.azalea.break
```

### Screenshots/Videos (you can drag and drop files or paste links)

![2022-11-25_14 11 55](https://user-images.githubusercontent.com/119075484/204043525-1d52cbd5-4cf3-4154-bcbd-d3c3f677d40e.png)

**Comment by iqtesterr** [comment]
This is what I got either, now I manually to replace the tripwire block state from before to let my resourcepack work.

**Comment by Akiranya** [comment]
I'm using a custom crops plugin that use tripwires for creating custom crops, and I got this issue too.

**Comment by LoneDev6** [comment]
I cannot reproduce the issue.
Set `disable-REAL_WIRE: false` in config.yml and then run `/iazip` to regenerate your resourcepack.

**Comment by Akiranya** [comment]
Hi LoneDev, I can confirm I have `disable-REAL_WIRE: false` and I've run `/iazip` to use the latest pack, but I still got this issue.

I extracted the `assets/minecraft/blockstates/tripwire.json` file and I found some patterns that may help:

![9343da38989658e71e5800ddca325364](https://user-images.githubusercontent.com/14846342/204558133-f6ca3093-8c62-4a1d-917b-d6089751b637.png)

To conclude, not all tripwire states are not updated; only the blockstates in the **green box** are properly updated in the generated.zip; the rest of blockstates are intact. Also I can confirm these config and resoucepack files worked with IA 3.2.5-r3. The issue occured after I updated to 3.3.0-beta-r3.

**Comment by LoneDev6** [comment]
Clean up your cache, seems you removed some configurations.
ItemsAdder keeps them because you might have disabled blocks by mistake, this avoid blocks from losing the correct ID.

Run /iacleancache blocks command and run /iazip again to refresh the pack.

**Comment by Akiranya** [comment]
> Clean up your cache, seems you removed some configurations. ItemsAdder keeps them because you might have disabled blocks by mistake, this avoid blocks from losing the correct ID.
> 
> Run /iacleancache blocks command and run /iazip again to refresh the pack.

I already tried removing cache of items/blocks and `/iazip` but none of them work :(

**Comment by LoneDev6** [comment]
Wait, what do you mean by this?
These blockstates are correctly set to `block/tripwire_attached_n`. Why do you say they are wrong? I don't understand the issue here.

![image](https://user-images.githubusercontent.com/27242001/204575601-660cc69e-5694-4810-b549-daea19458f93.png)

**Comment by Akiranya** [comment]
> Wait, what do you mean by this? These blockstates are correctly set to `block/tripwire_attached_n`. Why do you say they are wrong? I don't understand the issue here.
> 
> ![image](https://user-images.githubusercontent.com/27242001/204575601-660cc69e-5694-4810-b549-daea19458f93.png)

I have set 88/127 blocks which use the tripwire (if you see the output of `/iainfo`). So theoretically in the `tripwire.json` file these states should be set to the path to some custom model files like `custom_crops:agave/agave_stage_1` instead of the `block/tripwire_attached_n`. The weird thing is that only the lines from 119-129 (~11 blocks/states) are set to my custom models, which is much less than the 88 blocks/states in theory.

**Comment by iqtesterr** [comment]
@LoneDev6 It requires you setup a lot real wire. Not less than 50.

**Comment by LoneDev6** [comment]
You might have a tripwire.json file laying around in another content folder maybe?

**Comment by LoneDev6** [comment]
I might have found a possible cause, @iqtesterr send here your discord username, i'll share a new build

**Comment by PanBimboBoy** [comment]
i have the same problem as iqtesterr, all the new real_wire i add are not updated, also i removed the old tripwire.json but the problem persists

**Comment by Akiranya** [comment]
> You might have a tripwire.json file laying around in another content folder maybe?

![image](https://user-images.githubusercontent.com/14846342/204579450-c748cfcf-1cd6-4840-8951-b91b2f0a2f6a.png)

Sadly none...

**Comment by LoneDev6** [comment]
> > I might have found a possible cause, @iqtesterr send here your discord username, i'll share a new build
> 
> iqtester#9024

can't find you

@PanBimboBoy I'll share a beta in the 330 channel

**Comment by iqtesterr** [comment]
> 

I just realized I got banned because some problem with mcmodel. So just fix it in the next version, thank you:D

**Comment by LoneDev6** [comment]
> > 
> 
> I just realized I got banned because some problem with mcmodel. So just fix it in the next version, thank you:D

Oh I see, I don't recall you so I have no idea.
It will be fixed, have a nice day!
