### ISSUE TITLE
Bedrock resource pack for the ItemsAdder Default and other pack

### ISSUE THREAD

**Issue by ofunny** [PluginBugs/Issues-ItemsAdder#2141]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

A lot of users would like to use ItemsAdder with GeyserMC for Bedrock players, GeyserMC/Kas-tle also provides a converter Script including Github actions: https://github.com/Kas-tle/java2bedrock.sh/issues/new?assignees=&labels=conversion&template=pack-conversion.yml&title=%5BPack%5D%3A+

Unfortunately the conversion will not work out of the box. So it would be nice if we could maintain a Bedrock version for the ItemsAdder "Default pack" and "Other pack"  – maybe open source and community driven including Geyser mappings.

Including a list of incompatible things and some basic FAQ.

### Is your feature request related to a problem?

Bedrock support via GeyserMC

### Describe alternatives you've considered

Everybody tries to convert and maintain his/her/them own version with a lot of people asking over and over again for help with the conversion.

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/206
