### ISSUE TITLE
Bug when showing the prefix in the console with hex color

### ISSUE THREAD

**Issue by PanBimboBoy** [PluginBugs/Issues-ItemsAdder#2151]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Bimbo#6698

### What happened?

Change the prefix to the name of the server and it appears gray only in the console, in chat-ingame it looks fine
This did not happen in previous versions.

### Steps to reproduce the issue

1. Go to en.yml folder
2. Open en.yml
3. change `prefix: '&x&f&b&0&1&3&7&lGENKIRU &8| '`

### Server version

git-petal-"d448170" (MC: 1.19.2)*

### ItemsAdder Version

ItemsAdder version 3.3.0-beta-r8

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b600

### LoneLibs Version

LoneLibs version 1.0.21

### Other files, you can drag and drop them here to upload. (optional)

https://paste.helpch.at/ewoyijitel.pl

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/119075484/204592831-9761d360-a86e-4f09-bfe4-7483b7a80ea1.png)

**Comment by LoneDev6** [comment]
Hex colors are not supported in console.
