### ISSUE TITLE
Bug when placing custom blocks in creative

### ISSUE THREAD

**Issue by PanBimboBoy** [PluginBugs/Issues-ItemsAdder#2152]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Bimbo#6698

### What happened?

When trying to place custom blocks in creative the inventory item disappears but somehow it's there.
watch attached video
[https://streamable.com/9eckky](url)

### Steps to reproduce the issue

up

### Server version

git-petal-"d448170" (MC: 1.19.2)*

### ItemsAdder Version

ItemsAdder version 3.3.0-beta-r8

### ProtocolLib Version

 ProtocolLib version 5.0.0-SNAPSHOT-b600

### LoneLibs Version

LoneLibs version 1.0.21

### Screenshots/Videos (you can drag and drop files or paste links)

[https://streamable.com/9eckky](url)

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/2089
