### ISSUE TITLE
Break-tools blacklist does not work with partial custom item name

### ISSUE THREAD

**Issue by nhanledev** [PluginBugs/Issues-ItemsAdder#2153]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

Block `specific_properties.break_tools_blacklist` does not recognize and block breaking action of custom items.

Given a custom item name as `my_sword`, if I add `sword` into `break_tools_blacklist`, the block should not be broken by any custom item that have `sword` in their name as described in https://itemsadder.devs.beer/plugin-usage/adding-content/item-properties/blocks#break_tools_blacklist

![image](https://user-images.githubusercontent.com/28459250/204700592-e9c1c995-5c28-46ea-9197-b55a10db1cf9.png)

### Steps to reproduce the issue

1. Create a custom item with the name `test` and a custom block with `specific_properties.break_tools_blacklist` of `test`
2. Try to break the block with that item. The block breaks.

### Server version

Paper 1.19.2 build 300

### ItemsAdder Version

ItemsAdder_3.3.0-beta-r9

### ProtocolLib Version

ProtocolLib-b602

### LoneLibs Version

LoneLibs-1.0.21

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: debugitem
items:
  debug_ore:
    display_name: '&fDebug Ore'
    resource:
      generate: true
      material: PAPER
      textures:
        - items/debug_ore
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
        cancel_drop: true
        no_explosion: true
        hardness: 2.0
        break_tools_blacklist:
        - HAND
        - WOODEN_
        - STONE_
        - _AXE
        - _SWORD
        - _SHOVEL
        - _HOE
        - sword
  debug_sword:
    display_name: Debug Sword
    lore:
    - '&f'
    resource:
      material: DIAMOND_SWORD
      generate: true
      textures:
      - items/debug_sword
    attribute_modifiers:
      mainhand:
        attackDamage: 10
        attackSpeed: 5.6
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://user-images.githubusercontent.com/28459250/204700852-9b1d8225-3ecb-44f7-a213-eaa8e4bfe254.mp4

**Comment by LoneDev6** [comment]
I'll try to reproduce it but it's strange as it should work just fine based on my code.

**Comment by LoneDev6** [comment]
I can't believe how no one ever found out about this issue.
It has been there since v1.

Fixed! Thanks.

**Comment by nhanledev** [comment]
Thank you so much ❤️

**Comment by LoneDev6** [comment]
No worries, thank you for the detailed report, I wish more people take the time to properly write down all the information instead of blaming me.

Thanks again!
I hope you'll consider leaving a good review, it would help me so much :D 
Happy new year
