### ISSUE TITLE
Better translation support (per-client item names, lores, etc.)

### ISSUE THREAD

**Issue by Andre601** [PluginBugs/Issues-ItemsAdder#2154]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Andre_601#0601

### Describe the solution you'd like

This has been suggested already on Discord ([Link](https://discord.com/channels/533407895010803753/1046429524369350738)) and LoneDev already said it will be added eventually, so this issue is mostly for allowing tracking and/or inclussion in a future Milestone.

The original idea:
ItemsAdder's current way of translation support is very limited. You can only set a global language to be used across supported add-ons, which makes it kinda limited.

Instead, or in addition to that, should ItemsAdder offer a way to define per-client translations.
Resource packs already allow to define language files with custom translation keys to be used in item names, lores, etc.
So an option to define such a key and use the provided files instead of a "hardcoded" name would actuall help a lot in making add-ons more inclusive and accessible to everyone.

How ItemsAdder should recognize a name to be a translation key is up for discussion. The simplest could be to check if the name includes dots `like.this` to then use as the translation key. However, this isn't quite fool-proof in the end. Another idea could perhaps be a dedicated prefix like `t=` to indicate the text being a translation key.

### Is your feature request related to a problem?

Items, blocks, etc. currently have one set language, based on the setting within the config.yml

This is somewhat limiting the experience for players.

### Describe alternatives you've considered

At most a (probably hacky) overriding of items with a plugin and some packet manipulation (Which I won't touch... ever!).

**Comment by LoneDev6** [comment]
Duplicate https://github.com/PluginBugs/Issues-ItemsAdder/issues/591
