### ISSUE TITLE
Bug with FurniturePlaceSuccessEvent

### ISSUE THREAD

**Issue by HighVirus** [PluginBugs/Issues-ItemsAdder#2157]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

iVirus_#7499

### What happened?

I want to get CustomFurniture from FurniturePlaceSuccessEvent with FurniturePlaceSuccessEvent#getFurniture but it returns null.
If I check on FurnitureInteractEvent the furniture exists.

### Steps to reproduce the issue

```
@EventHandler
    public void onPlacePos(FurniturePlaceSuccessEvent event) {
        Entity entity = event.getBukkitEntity();
        System.out.println(entity);
        CustomFurniture customFurniture = event.getFurniture();
        System.out.println(customFurniture);
    }  
    @EventHandler
    public void onPlayerInteractPos(FurnitureInteractEvent event){
        Player player = event.getPlayer();
        ItemStack itemInHand = player.getInventory().getItemInMainHand();
        CustomFurniture customFurniture = event.getFurniture();
        System.out.println("poco prima del check");
        if (!PosUtil.isPosBlock(customFurniture)) return;
        System.out.println("check fatto");
    }
```

![code](https://user-images.githubusercontent.com/64657892/205022911-f4d53071-2047-4bde-b5fd-0d5ed8cd9324.png)
![debug](https://user-images.githubusercontent.com/64657892/205022931-3a02f7e6-5b8c-4818-a6d5-68f068a077f6.png)

### Server version

 Paper version git-Paper-794 (MC: 1.16.5)

### ItemsAdder Version

ItemsAdder version 3.3.0-beta-r10

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.21

**Comment by LoneDev6** [comment]
Will be checked as soon as possible and fixed in the next update

**Comment by HighVirus** [comment]
I solved FurniturePlaceSuccessEvent (it shouldn't be solved exactly like this...) in order to return a non-null value all the operations you want to do must be done with a delay of a few ticks (I set a delay of 4 ticks and works) 

getFurniture method returns a new object every time so I had to use the getBukkitEntity and perform the operations there, I know that the code sucks and I have to fix it but it is for demonstration purposes only.

![fix](https://user-images.githubusercontent.com/64657892/205364423-783de759-404e-42b9-8700-e1a3fccc3361.png)

**Comment by LoneDev6** [comment]
Will be fixed in the next update.
The game spawns entities asynchronously so the event doesn't provide the entity object in time.
