### ISSUE TITLE
add replace-furniture action and remove-furniture action

### ISSUE THREAD

**Issue by Meawerful** [PluginBugs/Issues-ItemsAdder#2161]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Meawerful#7634

### Describe the solution you'd like

add replace-furniture action and remove-furniture action

### Is your feature request related to a problem?

For example, you can change the shape of furniture by right-clicking on it via the replace-furniture action

### Describe alternatives you've considered

none

**Comment by LoneDev6** [comment]
For example to create a furniture customizer?
Add some context please

**Comment by Meawerful** [comment]
> For example to create a furniture customizer? Add some context please

  toilet_opening:
......
    behaviours:
      furniture:
        small: true
    events:
      interact:
        right:
          furniture_replace:
            type: toilet_closed
          execute_commands:
            the_first_command:
              command: tell {player} toilet closed
              as_console: trueFor 
Example, this action converts a toilet with the lid open into a toilet with the lid closed.You can set the furniture to be converted to another furniture when it is operated by left or right click

**Comment by LoneDev6** [comment]
Interesting idea, I will implement it

**Comment by LoneDev6** [comment]
You can already do that:
```yml
    events:
      placed_furniture:
        interact:
          replace_properties:
            custom_model_data:
              copy_from_item: toilet_closed
```
And do the same on the `toilet_open` config but with `copy_from_item: toilet_open`
