### ISSUE TITLE
Emotes always get canceled when player are taking damage.

### ISSUE THREAD

**Issue by glutaminus** [PluginBugs/Issues-ItemsAdder#2170]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

emotes not get canceled if player is damaged.

### Is your feature request related to a problem?

Yes, the problem is while playing the player emotes, if player took the damage in the meantime the emote will get canceled. 

### Describe alternatives you've considered

making the emotes not canceled if player took damage would be great

**Comment by LoneDev6** [comment]
I'll make this configurable per-emote in the BB extension.

Anyway it seems it's also related to that: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2106

**Comment by glutaminus** [comment]
ye configurable per-emote would be nice. 
but also, there is a problem that the emote will get canceled if you press shift, can we make a option that allow emote to keep playing even if you press shift ? or is it just impossible?

**Comment by LoneDev6** [comment]
> ye configurable per-emote would be nice. but also, there is a problem that the emote will get canceled if you press shift, can we make a option that allow emote to keep playing even if you press shift ? or is it just impossible?

This would be a problem for looping emotes right?
Would that option possible only for non-looping emotes? Right?

**Comment by glutaminus** [comment]
> > ye configurable per-emote would be nice. but also, there is a problem that the emote will get canceled if you press shift, can we make a option that allow emote to keep playing even if you press shift ? or is it just impossible?
> 
> This would be a problem for looping emotes right? Would that option possible only for non-looping emotes? Right?

yeah  it will be problem for looping emote if you can't stop running it.
should have be the option for non-looping only

**Comment by LoneDev6** [comment]
Continues here https://github.com/PluginBugs/Issues-ItemsAdder/issues/2106
