### ISSUE TITLE
ItemsAdder causes a heavy load

### ISSUE THREAD

**Issue by Lerphie** [PluginBugs/Issues-ItemsAdder#2172]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Coder#6926

### Describe the solution you'd like

Sorry I'm using the wrong Issue. I have a question, why is my server lagging? Spark shows that ItemsAdder is to blame, but I don't understand. Can you please see what the reason is? ItemsAdder 3.2.5r3 https://spark.lucko.me/5KvLpNZAr4

### Is your feature request related to a problem?

Maybe the problem is in the new ores, I use about 30 types of new ores

### Describe alternatives you've considered

Just name the reason for the lags

### Additional context

ItemsAdder 3.2.5r3 https://spark.lucko.me/5KvLpNZAr4

**Comment by LoneDev6** [comment]
How many players are online on this server?
It seems related to physics, somewhere in your server there is something causing an extremely high frequency physics update.
Use this plugin to possibly detect where.
https://www.spigotmc.org/resources/blockphysicseventdetector.84854/

Anyway ItemsAdder v3.3+ implemented some performance improvements about this kind of events, so I'd update.

**Comment by Lerphie** [comment]
> Anyway ItemsAdder v3.3+ implemented some performance improvements about this kind of events, so I'd update.

I can't update the plugin due to the fact that Cosmetics Core crashes on the new version of ItemsAdder. If you fix this error, then I will be happy to upgrade to the new version.

**Comment by Lerphie** [comment]
> How many players are online on this server? It seems related to physics, somewhere in your server there is something causing an extremely high frequency physics update. Use this plugin to possibly detect where. https://www.spigotmc.org/resources/blockphysicseventdetector.84854/

![image](https://user-images.githubusercontent.com/66962762/206322263-ceb21ff2-21bd-4250-aff6-26b4c0ef57cc.png)

**Comment by Lerphie** [comment]
I don't understand. This number is constantly increasing
![image](https://user-images.githubusercontent.com/66962762/206322603-e79428e2-68b2-486e-bec3-c6908f2224a6.png)

**Comment by Lerphie** [comment]
It is strange that this happens at zero coordinates. Maybe the generation of ores is to blame for this? My ore type changes at these coordinates, from "stone" to "deeslate"

**Comment by LoneDev6** [comment]
Well the event is triggered at height 0, please teleport there and check what's there.

**Comment by Lerphie** [comment]
> Well the event is triggered at height 0, please teleport there and check what's there.
There's nothing there, either new ores or default blocks from minecraft

**Comment by LoneDev6** [comment]
I checked my plugin code now.
The height 0 is normal.

It just tells you that the chunk at this location is causing the heavy physics load.
Check all the chunk.

I think it's because of the trees you have there in the screenshot.
I think it's related to this issue fixed in 3.3.0-beta-r10. https://github.com/PluginBugs/Issues-ItemsAdder/issues/2133

**Comment by Lerphie** [comment]
> I checked my plugin code now. The height 0 is normal.
> 
> It just tells you that the chunk at this location is causing the heavy physics load. Check all the chunk.
> 
> I think it's because of the trees you have there in the screenshot. I think it's related to this issue fixed in 3.3.0-beta-r10. #2133

Thank you very much! You are the best developer! I really hope that you will fix the problem with the incompatibility of Cosmetics Core 1.0.5 and ItemsAdder 3.3.0

**Comment by Lerphie** [comment]
> I checked my plugin code now. The height 0 is normal.
> 
> It just tells you that the chunk at this location is causing the heavy physics load. Check all the chunk.
> 
> I think it's because of the trees you have there in the screenshot. I think it's related to this issue fixed in 3.3.0-beta-r10. #2133

Can I contact you by Discord? I want to enter beta testers. I have a server with 1000+ online, thanks to this I can test your plugin for performance.

**Comment by Lerphie** [comment]
I updated your plugin to 3.3.0r11, still writes coordinates to the chat. I noticed that the coordinates that he writes to me are the angular coordinates of the chunk. Very strange

![image](https://user-images.githubusercontent.com/66962762/206592872-a421f9d4-957f-4e44-9133-7a19d4dec12c.png)


![image](https://user-images.githubusercontent.com/66962762/206592859-2961c36d-503c-407a-a376-2b0bf1a76388.png)

**Comment by Lerphie** [comment]
It seems to me that the trees are not to blame. For example, there was 1 update in this chunk, and this is the taiga biome

![image](https://user-images.githubusercontent.com/66962762/206593308-840e3f7d-8876-4069-add0-9d8f3f426dbf.png)

**Comment by Lerphie** [comment]
1416 updates 
![image](https://user-images.githubusercontent.com/66962762/206601333-628481d7-a4c9-40ab-8f90-0abb9427fd31.png)

**Comment by Lerphie** [comment]
![image](https://user-images.githubusercontent.com/66962762/206613856-f2270e42-e4e7-4566-9cea-de0f5a816afb.png)
I found the reason! It's about these 4 blocks. All trees that have these blocks cause a HIGH load. Updating chunks reaches 1000

**Comment by LoneDev6** [comment]
Send a new spark report of when this happened.
Thanks!

Also make sure to use the latest version of ItemsAdder.
Before updating make a server backup and read here carefully, a lot of things changed in v3.3: https://itemsadder.devs.beer/3-3-vs-3-2

**Comment by Lerphie** [comment]
> Send a new spark report of when this happened. Thanks!
> 
> Also make sure to use the latest version of ItemsAdder. Before updating make a server backup and read here carefully, a lot of things changed in v3.3: https://itemsadder.devs.beer/3-3-vs-3-2

The problem has not disappeared. ItemsAdder latest version
https://spark.lucko.me/VOy2cMA5fW

**Comment by Lerphie** [comment]
@LoneDev6 Excuse me if I'm distracting you, but can you take my problem as a priority? More than 500 players can't play on my server because of this performance bug

**Comment by LoneDev6** [comment]
You are not distracting me, but I cannot be available 24/7.
Don't forget about time zone and about the fact that support is not available on weekends (as clearly stated on Discord).

**Comment by LoneDev6** [comment]
Are you getting any lag or TPS drops?
I don't see anything related to that in your spark report.
Why are you trying to fix something if it's not broken? I cannot see any TPS drop in the spark report you shared.

![image](https://user-images.githubusercontent.com/27242001/207059490-15ae69c7-eaa9-4366-b315-de49389aec40.png)
