### ISSUE TITLE
Vehicles API

### ISSUE THREAD

**Issue by Olzie-12** [PluginBugs/Issues-ItemsAdder#2174]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Olzie-12#6912

### Describe the solution you'd like

To be able to interact with a Vehicle API, that be events and objects to get vehicles a player is riding or a vehicle from its namespace.

### Is your feature request related to a problem?

No, its not.

### Describe alternatives you've considered

There isn't really an alternative, unless you can give me one.

### Additional context

For your info: Im not a customer of the ItemsAdder plugin, but I've got a client that is so I cannot test or experiment

**Comment by LoneDev6** [comment]
This is very vague, I don't know what API features you need

**Comment by Olzie-12** [comment]
> This is very vague, I don't know what API features you need

Right I understand, but there’s nothing included in the API to be able to interact with vehicles.

For example; spawn, despawn, teleport, set the passenger etc

**Comment by LoneDev6** [comment]
Vehicles might need a recode before being exposed to the API, they might also support multiple seats in the future.
Coding an API for a thing that might change in the future is not something I'm comfortable doing for now

**Comment by LoneDev6** [comment]
Actually you can also create vehicles using the new custom entities feature, which have an API
