### ISSUE TITLE
Diamond tools giving themselves a texture

### ISSUE THREAD

**Issue by mitchngwen** [PluginBugs/Issues-ItemsAdder#2177]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

This is being added to the end of all of my diamond tools {"predicate":{"custom_model_data":2200277},"model":"minecraft:item/diamond_axe"}]}

Under:
plugins/ItemsAdder/data/resource_pack/assets/minecraft/models/item/diamond_axe.json
plugins/ItemsAdder/data/resource_pack/assets/minecraft/models/item/diamond_pickaxe.json
plugins/ItemsAdder/data/resource_pack/assets/minecraft/models/item/diamond_shovel.json
plugins/ItemsAdder/data/resource_pack/assets/minecraft/models/item/diamond_hoe.json

I just need to know where to look to fix this issue. Because this is causing these tools to have a custom texture that I do not want.

### Steps to reproduce the issue

N/A

### ItemsAdder Version

N/A

### ProtocolLib Version

N/A

### LoneLibs Version

N/A

**Comment by LoneDev6** [comment]
> Because this is causing these tools to have a custom texture that I do not want.

This is a fix to avoid Minecraft from setting custom texture to each item with CustomModelData value greater than the last one, in this case 2200276. Each item with 2200276+ CMD will have the last custom item texture which is wrong. My fix will allow them to have the vanilla texture, as they should.
This is working as intended and I sincerely don't know what is the issue here.
