### ISSUE TITLE
[BUG] Conflict between the plugin "Residence" and "ItemsAdder". (Reopen)

### ISSUE THREAD

**Issue by Deathroner** [PluginBugs/Issues-ItemsAdder#218]
**I start this ticket in "ItemsAdder" and "Residence".**

_ItemsAdder is a plugin that simulates a minecraft mod, and in this you will find vehicles such as planes, cars, among others._

**When boarding a vehicle in an area protected by "Residence", the following error is generated in the console:**

`[Server] ERROR POI data mismatch: never registered at BlockPosition{x=-4801, y=64, z=2432}`
`[Server] INFO Attempt to teleport dead player Deathroner_ restricted`

This had happened to me in another plugin called "Towny", but no solution was reached because it was not found what is causing the failure.

**Zrips**, Could you help us find fault with this?
I want to keep both plugins working on my server because I consider them very complete and stable; It is also annoying that I have to migrate my users to another plugin :(

**PS: When getting into a vehicle in an area protected by "Residence", it won't let me send messages or apply commands; the only solution is to re-enter the server, but the vehicles disappear.**

**Comment by Deathroner** [comment]
https://github.com/Zrips/Residence/issues/469

**Comment by LoneDev6** [comment]
@Jirsaacek
Moved here

**Comment by 100petr** [comment]
Hi, I still have this problem on paperspigot 1.16.1 (latest version - auto-update enabled)

**Comment by 100petr** [comment]
https://youtu.be/zqxHm6_p0Zc
![Screenshot_1](https://user-images.githubusercontent.com/29830635/89038180-24fab800-d340-11ea-899a-92d0f678d205.png)
![Screenshot_2](https://user-images.githubusercontent.com/29830635/89038199-304de380-d340-11ea-8526-05713cd177bb.png)

**Comment by LoneDev6** [comment]
> 
> 
> Hi, I still have this problem on paperspigot 1.16.1 (latest version - auto-update enabled)
> https://youtu.be/zqxHm6_p0Zc
> ![Screenshot_1](https://user-images.githubusercontent.com/29830635/89038180-24fab800-d340-11ea-899a-92d0f678d205.png)
> ![Screenshot_2](https://user-images.githubusercontent.com/29830635/89038199-304de380-d340-11ea-8526-05713cd177bb.png)
> ![Screenshot_1](https://user-images.githubusercontent.com/29830635/89099836-7a8f9d00-d3f2-11ea-8ac9-b14beaad6b98.png)
> //EDIT 1.8. :
> I tried it on a clean server and it works, interesting.

I really have no idea on how to fix this nor what is the cause.
To me seems an obscure Spigot bug which interferes with ItemsAdder and Residence events

**Comment by LoneDev6** [comment]
closed due to inactivity

**Comment by 100petr** [comment]
I still have this problem on my server

**Comment by LoneDev6** [comment]
Thanks for the report.
Anyway the POI mismatch is not related with the issue you see.

Please check if residence is deleting slime / armorstands entities inside residence, check if there is a way to prevent this since i'm 99% sure it's the issue: https://itemsadder.plugin.ga/faq/vehicles-bugs/towny-vehicles-bug

**Comment by 100petr** [comment]
Hmm, it occurs to me that this is done by the AutoMobRemoval function. I'll try to do some tests.

**Comment by 100petr** [comment]
If I turned it on on the test server, it throws me out of the car, but I can still write. But I'll try to do some more tests.

**Comment by 100petr** [comment]
I found it! It causes the flag monsters. https://youtu.be/Tn9PxUV_7gg

**Comment by LoneDev6** [comment]
NO problem so basically you just need to execute /res set monsters ?
anyway please report that to the plugin author to avoid removing monsters with custom name or invulnerable monsters as my SLIME is invulnerable and has custom name,

**Comment by LoneDev6** [comment]
https://github.com/Zrips/Residence/issues/469#issuecomment-801425643

**Comment by 100petr** [comment]
res set monsters f - cannot send message
res set monsters t/r - no problem
