### ISSUE TITLE
Bug with player model and skin on MacOs

### ISSUE THREAD

**Issue by DarkyCat** [PluginBugs/Issues-ItemsAdder#2182]
### What happened?

After installing the resource pack, some players lose their heads or display the head texture incorrectly. Also, when using animation from the plugin, the player model becomes translucent.

### Steps to reproduce the issue

After installing the resource pack

### Server version

git-Purpur-1857 (MC: 1.19.2)*

### ItemsAdder Version

Version: 3.3.0-beta-r11

### ProtocolLib Version

[09:58:17 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b605

### LoneLibs Version

[09:58:25 INFO]: LoneLibs version 1.0.21

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/27242001/221879598-36905cb4-a5c8-43a0-b390-ac82e8de2fda.png)

**Comment by LoneDev6** [comment]
This has to do with MacOS GPU drivers which have a bug.
I cannot fix this issue. You have to disable emotes in config.yml and regenerate your pack for now.

**Comment by LoneDev6** [comment]
Took from: https://github.com/PluginBugs/Issues-ItemsAdder/issues/1831
![image](https://user-images.githubusercontent.com/27242001/224268378-10aaf5b0-fc02-4cb3-a010-503a9534ed85.png)
![image](https://user-images.githubusercontent.com/27242001/224268398-6e8b88da-5e52-4d87-8c21-b507f54ac71b.png)
