### ISSUE TITLE
Texture don't being load in 1.19.3 client

### ISSUE THREAD

**Issue by RickyLaChow** [PluginBugs/Issues-ItemsAdder#2187]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Rickylachow#9809

### What happened?

Inserendo viaversion e giocando il server tramite 1.19.3 non carica le texture, in 1.19.2 non presenta questo problema

### Steps to reproduce the issue

//

### Server version

[16:25:44 INFO]: This server is running Paper version git-Paper-302 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 425baed)

### ItemsAdder Version

[16:26:06 INFO]: ItemsAdder version 3.3.0
[16:26:06 INFO]: Customized Minecraft without client mods!
[16:26:06 INFO]: Website: devs.beer
[16:26:06 INFO]: Author: LoneDev

### ProtocolLib Version

[16:26:18 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b607
[16:26:18 INFO]: Provides read/write access to the Minecraft protocol.
[16:26:18 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[16:26:59 INFO]: LoneLibs version 1.0.21
[16:26:59 INFO]: Collection of libs used by my plugins
[16:26:59 INFO]: Authors: LoneDev and others

### LightAPI Version (optional)

//

### LibsDisguises Version (optional)

//

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10252147/latest.log)

### Other files, you can drag and drop them here to upload. (optional)

https://pastebin.com/F0zhx5Vy Client

### Screenshots/Videos (you can drag and drop files or paste links)

![2022-12-17_17 14 52](https://user-images.githubusercontent.com/25041502/208251707-74e037b5-e65c-4065-86f5-9d91b632a514.png)
![2022-12-17_17 14 49](https://user-images.githubusercontent.com/25041502/208251708-b11c2386-5354-4920-a6d0-721bbbccca33.png)

**Comment by LoneDev6** [comment]
You have to regenerate the pack to apply 1.19.3 compatibility.

**Comment by RickyLaChow** [comment]
Quando rigenero la texture non cambia niente 
https://pastebin.com/W5kKURDz 

@LoneDev6

**Comment by RickyLaChow** [comment]
https://www.youtube.com/watch?v=F3dyri8qTMs

**Comment by LoneDev6** [comment]
https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown

**Comment by LoneDev6** [comment]
Manda il log del client qui

**Comment by LoneDev6** [comment]
Duplicate https://github.com/PluginBugs/Issues-ItemsAdder/issues/2188#event-8062951460
