### ISSUE TITLE
Useless properties added to display name and lore lines of custom items

### ISSUE THREAD

**Issue by minecraft-dripdrop** [PluginBugs/Issues-ItemsAdder#2189]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

I use shopkeepers to trade items to items.
But after update plugin,the item's NBT all changed,and the old item can't trade,can't stack
You can see the new and old item's nbt
OLD
![old](https://user-images.githubusercontent.com/62246956/208280755-fbf8b6f4-e9b9-4f53-aea2-0cf020c12b04.png)
NEW
![new](https://user-images.githubusercontent.com/62246956/208280759-c4e0253d-1add-4387-97cb-fdfc9ba728e5.png)

old item can't trade anymore
![2022-12-18_12 07 18](https://user-images.githubusercontent.com/62246956/208280798-53567065-b507-4aa7-b896-36aa6e0c024b.png)

### Steps to reproduce the issue

find a old item and new item

check this two item's NBT

### Server version

git-purpur-1825(1.19.2)

### ItemsAdder Version

3.3.0-beta-r11

### ProtocolLib Version

5.0.0-snapshot-b600

### LoneLibs Version

1.0.21

**Comment by LoneDev6** [comment]
I'll try to find the cause, anyway this is a known issue of the trading GUI because the game is very strict on items matching.

**Comment by Akiranya** [comment]
Some functions of my server also rely on the vanilla trade GUI but I don't see this issue after I updated IA (so the strict itemMeta matching also appies to my server).

Specifically, I updated IA from 3.2 to 3.3 and I also updated IA as soon as there is a newer minor version of 3.3 (i.e. r5,6,7..). I guess it's some other plugins causing this issue.

**Comment by LoneDev6** [comment]
Well, depends.
This game is a total shit when it comes to reliability of text generation for lores and display names.
Sometimes it adds some tags, sometimes not. 

This causes various issues on GUIs and logics which require a PRECISE nbt check.
In this case the text is the same but the internal JSON text is not.

**Comment by minecraft-dripdrop** [comment]
when you use anvil to rename item,the item's NBT will just like the New format.So the only problem is to make sure that NBT doesn't change

**Comment by LoneDev6** [comment]
Another solution (cleaner) would be to try to fork the Shopkeepers plugin and somehow add a proper ItemsAdder match code to avoid having to deal with the unstable NBT matching logic.

But I'll try to find the cause of this issue before trying to work on Shopkeepers directly.

**Comment by LoneDev6** [comment]
The next update will revert back the NBT display name removing the new useless properties.

**Comment by Darkseno** [comment]
I have the impression that this update to break something else.

When I give myself two tickets for example with /iagive and I do a /inv (with CMI) to give one of the tickets to another player and well the NBT changes and the ticket I keep is not the same as the player's.

It didn't do that before

**Comment by LoneDev6** [comment]
Post the two different NBT, I can't do anything without proper data.
Use `/iatag` while holding each one of the items and copy the result printed in the server console.

**Comment by LoneDev6** [comment]
The last update was exactly made to fix this.
This was the initial report here on the first message.
Anyway next time make a new Github issue don't comment on closed issue reports.
I opened a new one.
