### ISSUE TITLE
Folder structure v3.3 doesn't allow creating special section items and recipes in the same file

### ISSUE THREAD

**Issue by luizsusin** [PluginBugs/Issues-ItemsAdder#2191]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Luiz Susin#5457

### What happened?

Crafting page on wiki says:
```
To create a recipe you have to create a special section in one of your .yml files.
This section can be added in all and any of your .yml files for better organization of recipes.
```

This was true while using 3.2 folder structure, but not exactly with 3.3. Using 3.3, a separate file with the recipe section is needed in order to make it work. It can be anywhere inside the configs folder, but it needs to have this section only (and not an items section inside too, for instance).
This actually messes things up for me quite a lot, since I've made the recipes all inside the items, and each item has its own file.

### Steps to reproduce the issue

An example:
1. Create a file named `boiled_egg.yml`;
2. Add inside of it the **items** section;
3. Run `/iazip`;
4. The item should be working;
5. Go back to the `boiled_egg.yml` and add the **recipes** section with a recipe;
6. Run `/iazip`;
7. The item will still be working, but not the recipe.

This exact same thing was working perfectly on folder structure 3.2. Why it doesn't work on 3.3?
PS: The `boiled_egg.yml` example can be found in the "problematic yml" section down below.

### Server version

**Server Version:** git-Purpur-1845 (MC: 1.19.2)

### ItemsAdder Version

**ItemsAdder Version:** 3.3.0

### ProtocolLib Version

**ProtocolLib Version:** 5.0.0-SNAPSHOT-b600

### LoneLibs Version

**LoneLibs version:** 1.0.21

### LightAPI Version (optional)

**LightAPI Version:** bukkit-5.3.0 (build SNAPSHOT)

### LibsDisguises Version (optional)

**LibsDisguises Version:** 10.0.31-SNAPSHOT

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: mycustomthings
items:
  boiled_egg:
    display_name: "&rBoiled Egg"
    permission: ia.boiled_egg
    resource:
      material: BAKED_POTATO
      generate: true
      textures:
        - item/food/boiled_egg
recipes:
  cooking:
    boiled_egg:
      ingredient:
        item: EGG
      machines:
        - SMOKER
      cook_time: 100
      result:
        item: mycustomthings:boiled_egg
        amount: 1
```

**Comment by luizsusin** [comment]
**Important Information:**
Using underline on file name also won't work! 
So using a separate file for recipes named, for instance, `boiled_egg_recipes.yml` also won't work.

**Comment by LoneDev6** [comment]
I literally used your provided file and tried to use the recipe in a SMOKER:

I can say that the recipe indeed is loaded by ItemsAdder, checking my log:
`[13:08:05 INFO]: [ItemsAdder] Loading cooking recipe: boiled_egg`

I enabled some settings in config.yml
```yml
  recipes:
    log-recipes-loading: true
    log-recipes-loading-disabled: true
    log-recipes-removed-vanilla: true
    log-recipes-unknown-item: true
```

And it works fine.
![image](https://user-images.githubusercontent.com/27242001/211018570-bdc72213-f352-4d21-8470-2d04ab44e649.png)
