### ISSUE TITLE
Vanilla textures replaced when executableitem option is enabled.

### ISSUE THREAD

**Issue by DoZysGuy** [PluginBugs/Issues-ItemsAdder#2192]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

DoZys#8192

### What happened?

When the executableitem option on the item.yml, all vanilla item texture are replaced by the itemadder texture. Here all netherite sword are replace by my custom texture.
![image](https://user-images.githubusercontent.com/119410319/208428510-696886fe-37bf-481f-953c-9cc06cc1a65b.png)
![image](https://user-images.githubusercontent.com/119410319/208428720-7aef0dc7-4a87-4486-9b9b-85df1ccd6212.png)

Here is the netherite-sword.json result on the pack when executable is merged.
`{ "predicate": { "custom_model_data": 0 }, "model": "onepiece:item/yoru" },`

### Steps to reproduce the issue

1. Add Itemsadder and Executableitem + Score on the server plugin folder.
2. Create item on executable item
3. Create item on itemsadder and add the executable item id.
4. Use /iazip

### Server version

This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version
Previous version: git-Paper-300 (MC: 1.19.2)

### ItemsAdder Version

ItemsAdder version 3.3.0

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b605

### LoneLibs Version

LoneLibs version 1.0.21

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: onepiece
items:
  yoru:
    display_name: Yoru
    durability:
      max_custom_durability: 4062
    resource:
      material: NETHERITE_SWORD
      generate: false
      model_path: item/yoru
    executableitem:
      id: yorupower
```

### Other files, you can drag and drop them here to upload. (optional)

Json not acepted.

Here is the netherite-sword.json

{"parent":"minecraft:item/handheld","textures":{"layer0":"minecraft:item/netherite_sword"},"overrides":[{"predicate":{"custom_model_data":0},"model":"onepiece:item/yoru"},{"predicate":{"custom_model_data":1},"model":"item/netherite_sword"}]}

**Comment by LoneDev6** [comment]
Should be fixed in the upcoming release
