### ISSUE TITLE
Plugin will not load

### ISSUE THREAD

**Issue by Snicket66** [PluginBugs/Issues-ItemsAdder#2193]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Snicket66#6666

### What happened?

In STEP 1:
The final step: Wait for the plugin to load fully
 This cannot be completed it will not load it comes up with the message:
﻿ [ItemsAdder] Plugin is still loading... Please wait before using /ia

### Steps to reproduce the issue

Download the file from polymart
install it on server
restart server
load in
execute /ia
recive this message forever: ﻿ [ItemsAdder] Plugin is still loading... Please wait before using /ia

### Server version

﻿

This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)

### ItemsAdder Version

﻿

ItemsAdder version 3.3.0
Customized Minecraft without client mods!
Website: devs.beer
Author: LoneDev

### ProtocolLib Version

﻿

ProtocolLib version 4.8.0
Provides read/write access to the Minecraft protocol. Authors: dmulloy2 and comphenix

### LoneLibs Version

﻿

LoneLibs version 1.0.21
Collection of libs used by my plugins Authors: LoneDev and others

### LightAPI Version (optional)

N/A

### LibsDisguises Version (optional)

N/A

### FULL server log

https://pastes.dev/K58NzQX2K2

### Error (optional)

```shell
N/A
```

### Problematic items yml configuration file (optional)

```shell
N/A
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/120325902/208474047-1c9c85f1-b55f-40e7-90cf-708ff491e870.png)
This pops up ^ not sure if it has anything to do with items adder (its been coming up since before the server started)

![image](https://user-images.githubusercontent.com/120325902/208474221-e630199c-3b49-4faa-baa9-fa337a97269a.png)
I havent done Step 2 yet - will this affect the loading - but i cant do step 2 without having acsess to /iazip and it will come up: ﻿ [ItemsAdder] Plugin is still loading... Please wait before using /ia

**Comment by nullXer0** [comment]
Looks like the issue isn't caused by ItemsAdder. You're using an outdated version of ProtocolLib that doesn't support 1.19. Try downloading the newest dev build for ProtocolLib from their Spigot page.

**Comment by Snicket66** [comment]
![image](https://user-images.githubusercontent.com/120325902/208619157-ffa1ed52-1a47-4b6c-9fc1-c3e0f9df80a5.png)
So wherre it says download now not that but go to:
Use the [latest dev build](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) for Minecraft 1.19

![image](https://user-images.githubusercontent.com/120325902/208619265-baf555b1-fd14-421b-a8bd-76998d75eb53.png)
which takes me to this, where do i download it from there?

**Comment by Snicket66** [comment]
IT WORKED!!!!
TYSM honestly i was trying that for months - im not too experiences
