### ISSUE TITLE
New two parameters in config (minecraft font)

### ISSUE THREAD

**Issue by vladislavvc** [PluginBugs/Issues-ItemsAdder#2196]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Vladislavv#8247

### Describe the solution you'd like

There are two types of fonts in Minecraft: **regular** and **Unicode**. The regular font (which is also pixel-based) uses the default.json file, and the Unicode font uses the uniform.json file (still in the font folder). I suggest two new parameters in the config:
- "standart-font" which will replace the thin unicode font with a font without unicode by adding some lines to uniform.json (check screenshots)
- "autogenerate-uniform-font-file" which automatically generates uniform.json file in /minecraft/font folder in addition to default.json, so that custom font-textures are not replaced by squares

### Is your feature request related to a problem?

Maybe, because there is a small percent of players who play with a thin font

### Describe alternatives you've considered

 ** **

### Additional context

![image](https://user-images.githubusercontent.com/74511592/208757030-518f3aec-5824-4456-8257-f4fd9882e982.png)
![image](https://user-images.githubusercontent.com/74511592/208757115-f6fe8db5-c6e8-4771-a6af-8d423a4b7859.png)
![image](https://user-images.githubusercontent.com/74511592/208757152-dcf1abe1-523f-49cb-ba5b-f5c4aa40eaff.png)

**Comment by LoneDev6** [comment]
Hello, this suggestion is not really clear.
Also avoid sharing screenshots, post the actual files.

Please explain what I'd need to implement.
Thanks

**Comment by vladislavvc** [comment]
I meant to add 2 new lines in the plugin's config, which will either allow you to use font-images with unicode on, or automatically generate a uniform.json file (minecraft font folder), which will be completely identical to default.json, but will remove thin font and allow you to use font-images with unicode on. Attached file (resourcepacks), if it makes more sense
[2 resourcepacks.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/10366641/2.resourcepacks.zip)

**Comment by LoneDev6** [comment]
So basically if I create a copy of `default.json` and call it `uniform.json` it will allow people with "FORCE UNICODE: ON" to see custom characters anyway without having the [] issue?

**Comment by vladislavvc** [comment]
Exactly!

**Comment by LoneDev6** [comment]
That's dope.
I'll do some testing definitely

**Comment by Akiranya** [comment]
> So basically if I create a copy of `default.json` and call it `uniform.json` it will allow people with "FORCE UNICODE: ON" to see custom characters anyway without having the [] issue?

It would work but I hope there would be an option to toggle it as it's not the most ideal way to handle the square issue with custom fonts. The most appropriate way to deal with it is to embrace the `Text Component` for all text configs and then use the `font` property of json text introduced in MC1.16. I came up an related suggestion #2224 for it, where the end-users can use MiniMessage syntax to easily write Minecraft json text

The main issue of just using default.json / uniform.json is that, players could simply type the chars, which are "big pictures" like GUIs defined in the resourcepack, in the chat or in item name, to ruin the chat box or anywhere they can type in text. This issue cannot be avoided unless the server has some text filter system for anywhere the player can type in text

**Comment by LoneDev6** [comment]
I think you're confused about how this works.
ItemsAdder does prevent users without permission to write emojis in chat.

Obviously if you manually add characters to default.json you will have to handle some permissions logic on your own.

**Comment by Akiranya** [comment]
> I think you're confused about how this works. ItemsAdder does prevent users without permission to write emojis in chat.
> 
> Obviously if you manually add characters to default.json you will have to handle some permissions logic on your own.
> 
> This is an off topic message I'd say.

Sorry if it's off topic and thanks for your reply! Just wanted to let you know how I think of these fancy features

I know how font works in Minecraft and I know adding font config to `unform.json` does not add pressure on the CPU / network if implemented properly because it's just client side rendering. What i'm concerned is that IA would consume more CPU time to handle the chat/ text display filtering even if I don't use any chat / text features provided by IA, especially when the server has hundreds of players online and there are heavy text display tasks (hope there's already an option for this but I missed out..?)

I have my own plugins to handle all the chat / text display stuff carefully so that's why I would like to see there's an option to turn it off completely

**Comment by LoneDev6** [comment]
> What i'm concerned is that IA would consume more CPU time to handle the chat/ text display filtering

The feature is already implemented in ItemsAdder so you should not really worry about that.
It's optimized as much as possible due to how messages work in Minecraft.

> even if I don't use any chat / text features provided by IA

You can disable font images replacing in config.yml of the plugin, it won't run any code about it.

**Comment by LoneDev6** [comment]
New option in config.yml regenerate your zip after setting it to `true`.
`fix_force_unicode_font_images: true`
