### ISSUE TITLE
WeaponMechanics Compatibility Help

### ISSUE THREAD

**Issue by CJCrafter** [PluginBugs/Issues-ItemsAdder#2197]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

`CJCrafter#4522`

### What happened?

Hello! I am a developer for WeaponMechanics. Users with Explosions are having trouble breaking your blocks. Here is the [GitHub issue](https://github.com/WeaponMechanics/MechanicsMain/issues/210) they created. I tried joining discord but the verification system locks evildoers like me out. 

here is where I break blocks:
https://github.com/WeaponMechanics/MechanicsMain/blob/master/WeaponMechanics/src/main/java/me/deecaad/weaponmechanics/weapon/damage/BlockDamageData.java#L243-L288

Here is where I regenerate blocks:
https://github.com/WeaponMechanics/MechanicsMain/blob/master/WeaponMechanics/src/main/java/me/deecaad/weaponmechanics/weapon/damage/BlockDamageData.java#L290-L298

works great for vanilla blocks, not so much itemsadder. Any tips would be much appreciated, thanks. 

### Steps to reproduce the issue

1. get a wm explosive `/wm get rpg`
2. blow up itemsadder blocks

**Comment by LoneDev6** [comment]
Hello and happy new year.

> not so much itemsadder.

Please add details, I don't know what you mean, maybe post a video too.

**Comment by CJCrafter** [comment]
In the video in the [original issue](https://github.com/WeaponMechanics/MechanicsMain/issues/210), you can see that blocks drop as if they were broken but aren't broken. This duplicates the block.

**Comment by CJCrafter** [comment]
Hey @LoneDev6, is there an API for breaking items adder blocks?
