### ISSUE TITLE
Plugin will not load for some reason after a server restart

### ISSUE THREAD

**Issue by millson1** [PluginBugs/Issues-ItemsAdder#2199]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

synapse#1000

### What happened?

My server has regular restarts at like 2am, today my players complained of textures not loading. So i investigated, turns out the plugin just isn't loading. I can't find anything except some DisguiseAPI error in the console, i've also updated ProtocolLib to the dev version, downloaded DisguiseAPI, removed ViaVersion, and updated my itemsadder to the latest version

### Steps to reproduce the issue

Start the server

### Server version

Current: git-Purpur-1845 (MC: 1.19.2)*
Previous: git-petal-"d448170" (MC: 1.19.2)
* You are 13 version(s) behind

### ItemsAdder Version

[21:02:07 INFO]: ItemsAdder version 3.3.0
[21:02:07 INFO]: Customized Minecraft without client mods!
[21:02:07 INFO]: Website: devs.beer
[21:02:07 INFO]: Author: LoneDev

### ProtocolLib Version

[21:02:23 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b608
[21:02:23 INFO]: Provides read/write access to the Minecraft protocol.
[21:02:23 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[21:02:38 INFO]: LoneLibs version 1.0.21
[21:02:38 INFO]: Collection of libs used by my plugins
[21:02:38 INFO]: Authors: LoneDev and others

### LibsDisguises Version (optional)

[21:02:50 INFO]: LibsDisguises version 10.0.31-SNAPSHOT
[21:02:50 INFO]: A disguise plugin with various disguises.
[21:02:50 INFO]: Authors: libraryaddict, Byteflux and Navid K.

### FULL server log

[log.txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/10281525/log.txt)

**Comment by ElMoha943** [comment]
+1 lastestes version doesnt work on 1.19.2

**Comment by LoneDev6** [comment]
You are running an old version of ItemsAdder

**Comment by LoneDev6** [comment]
Also you are using itemsadder-blocks-injector without ViaVersion installed which is not possible.

> [20:51:45] [Server thread/ERROR]: Could not load 'plugins/itemsadder-blocks-injector_0.0.5 (1).jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [ViaVersion]. Please download and install these plugins to run 'ItemsAdderBlocksInjector'.
