### ISSUE TITLE
Nag author

### ISSUE THREAD

**Issue by MinecollYT** [PluginBugs/Issues-ItemsAdder#2200]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Jonas L. | Minecoll_YT#0741

### What happened?

Error message on shutdown

### Steps to reproduce the issue

1. Install IA
2. Shutdown Server

### Server version

This server is running Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)

### ItemsAdder Version

3.3.0

### ProtocolLib Version

5.0.0-SNAPSHOT-b607

### LoneLibs Version

1.0.21

### Error (optional)

```shell
[17:09:08] [Server thread/ERROR]: Nag author: 'LoneDev' of 'ItemsAdder' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.
```

**Comment by LoneDev6** [comment]
Provide the full server log.

**Comment by MinecollYT** [comment]
[2022-12-22-8.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10288977/2022-12-22-8.log)

**Comment by MinecollYT** [comment]
it seems like now the server also crashes

**Comment by MinecollYT** [comment]
> it seems like now the server also crashes

Found the issue... when there are like 20+ noteblocks in the spawn chunk that are connected to a clock itemsadder seems to crash

**Comment by LoneDev6** [comment]
Your server ran out of memory and so it causes all sort of issues to happen.
There is nothing I can do, increase your server RAM.
