### ISSUE TITLE
Players crashing server with noteblock clocks

### ISSUE THREAD

**Issue by MinecollYT** [PluginBugs/Issues-ItemsAdder#2202]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Jonas L. | Minecoll_YT#0741

### What happened?

Players are crashing my server with noteblocks

### Steps to reproduce the issue

1. Place many noteblocks
2. Power them with clock

### Server version

This server is running Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)

### ItemsAdder Version

3.3.0b

### ProtocolLib Version

5.0.0-SNAPSHOT-b608

### LoneLibs Version

1.0.22

### FULL server log

https://github.com/PluginBugs/Issues-ItemsAdder/files/10288977/2022-12-22-8.log

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/43142792/209189813-6e0f2b8a-fc7f-4683-bdf0-5ffe250c1dca.png)

**Comment by MinecollYT** [comment]
(This only works with normal note blocks, not the REAL_NOTE blocks)

**Comment by LoneDev6** [comment]
Post a timings report of when the machine is on.

**Comment by LoneDev6** [comment]
And send me this file:
`crash-reports/crash-2022-12-22_17.53.21-server.txt`

**Comment by MinecollYT** [comment]
[crash-2022-12-22_17.53.21-server.txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/10296279/crash-2022-12-22_17.53.21-server.txt) (The server is not running out of memory, just as a side note)

Video:
https://youtu.be/h9N-vVj-otE

Server-Log: 
[2022-12-23-3.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10296306/2022-12-23-3.log)

Crash-Log: 
[crash-2022-12-23_17.53.21-server.txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/10296304/crash-2022-12-23_17.53.21-server.txt)

Timings: 
unable to provide (or is there any other way)

**Comment by MinecollYT** [comment]
uhm

**Comment by LoneDev6** [comment]
Will be checked this week.
Thanks for the patience and happy new year.

**Comment by LoneDev6** [comment]
Can you somehow provide the schematic for this?

**Comment by LoneDev6** [comment]
I have fixed the issue.

https://user-images.githubusercontent.com/27242001/210806408-1055a6e1-408b-4a85-8b45-a3b25db30a34.mp4
