### ISSUE TITLE
Drop2inv-itemsAdder corous bug 

### ISSUE THREAD

**Issue by cats-love** [PluginBugs/Issues-ItemsAdder#2205]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

A custom leaf with a lamp or a barrel. If you use another interaction item, the chorus is copied

### Steps to reproduce the issue

It's the same as the video

### ItemsAdder Version

3.3.0

### ProtocolLib Version

606

### LoneLibs Version

1.0.22

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/7pELwaSrPIo

**Comment by cats-love** [comment]
https://www.spigotmc.org/resources/%E2%AD%90-drop2inventory-plus-%E2%AD%90.87784/

**Comment by LoneDev6** [comment]
Why did you close the issue? Was it solved? by the other plugin author?
