### ISSUE TITLE
Requesting a helmets/offhand hide option for emoting

### ISSUE THREAD

**Issue by NoobcoreNetwork** [PluginBugs/Issues-ItemsAdder#2208]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Joshie#0644

### What happened?

https://streamable.com/0jy9d3- Helmet + offhand issue,

So, I'm having an issue where, The offhand and helmet still show, the offhand is a cosmetic but I'd prefer for it to also hide due to the nature of my cosmetics, and I know you mentioned a while back to me to open a ticket on github if I need to disable helmets also, I know you kept this in due to cosmetics plugins using hats but yeah, I could really do with it also hiding helmets, Basically hiding everything, Thanks!

### Steps to reproduce the issue

Install lonelibs + IA
Emote with a helmet on
or something in offhand.

### Server version

Purpur 1857 1.19.2

### ItemsAdder Version

3.3.0-beta-r10

### ProtocolLib Version

5.0.0-snapshot-b600

### LoneLibs Version

1.0.21

**Comment by LoneDev6** [comment]
I'll add some options in config.yml to hide hand, offhand and hat during emotes.

**Comment by LoneDev6** [comment]
Continue on: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2106
