### ISSUE TITLE
emote cancellable/uncancelleable option

### ISSUE THREAD

**Issue by glutaminus** [PluginBugs/Issues-ItemsAdder#2209]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

emote will get canceled if you press sneak button, can we make a option that allow emote to keep playing even if you sneak ? 

### Is your feature request related to a problem?

yes, when using a long animation emote for some mmorpg skill, if player sneak the emote will be canceled.

### Describe alternatives you've considered

I think there's no alternatives

**Comment by LoneDev6** [comment]
This would be possible only for non-looping animations or the player would be stuck into the animation forever, correct?

**Comment by Kokolochnik** [comment]
EXAMPLE: 
shift = stop animation
shift + f = animation with sneak

> This would be possible only for non-looping animations or the player would be stuck into the animation forever, correct?

**Comment by glutaminus** [comment]
> This would be possible only for non-looping animations or the player would be stuck into the animation forever, correct?

yeah correct, looping animations should be cancelable. but non-looping should have option to make it uncancellable.

**Comment by Septicuss** [comment]
Ideally this would also be revealed in the API (whether or not it can be cancelled). A boolean in the #playEmote method could do.

` public static void playEmote(Player player, String emoteName, boolean cancellable)`

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/2106

```yml
    cancel_conditions:
      sneak: false
      take_damage: false
      deal_damage: false
      in_air: false
```
