### ISSUE TITLE
more bones for emote

### ISSUE THREAD

**Issue by glutaminus** [PluginBugs/Issues-ItemsAdder#2210]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

making the plugin able to read more bones for something like like forearm instead of just full arm.
![image](https://user-images.githubusercontent.com/90768288/209423266-74137386-479c-4bc9-aa79-be9e4fd90af4.png)
here is example of what i meant.  what I done here is I add more bone on this template, but when i try adding animations to resourcepack and play with /iaemote it didn't read the forearm.(it play normally but the forearm keyframes is not moving)
so i suggest make it read more of these bones.(left forearm/right forearm/left foreleg/right foreleg)
 it's probably low priority things to do but, MCCosmetics's template and their plugin also have more bone. but I prefer using itemsadder's so it would be so good if you add more bones for forearm and foreleg.

### Is your feature request related to a problem?

not really, but with this will allow for more versatile and better emotes.

### Describe alternatives you've considered

no alternatives

### Additional context

![image](https://user-images.githubusercontent.com/90768288/209423380-6f14906c-96a5-499d-bc1d-d99dfb562f0f.png)
![image](https://user-images.githubusercontent.com/90768288/209423403-3168d41e-0ac0-4a47-9810-2d44c614c6fb.png)

**Comment by LoneDev6** [comment]
It's currently not possible because of various reasons, had been asked some times before.
https://itemsadder.devs.beer/faq/emotes-bugs/emotes-with-more-joins
