### ISSUE TITLE
NPC heads not showing while itemsadder enabled

### ISSUE THREAD

**Issue by NFDCPP** [PluginBugs/Issues-ItemsAdder#2212]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

𝖓𝖔𝖙𝕱𝖆𝖑𝖑𝖎𝖓𝖌𝕯𝖊𝖛𝖎𝖑#7479

### What happened?

I'm using ZNPC npc plugin and while using itemsadder heads of npc are invisible (when itemsadder disabled npc heads are visible)

### Steps to reproduce the issue

1. Create npc
2. Npc head is invisible

### Server version

This server is running Paper version git-Paper-358 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: f26e9cc)
You are running the latest version

### ItemsAdder Version

Itemsadder version: 3.3.0b-r2

### ProtocolLib Version

protocollib ver: 5.0.0-SNAPSHOT-b608

### LoneLibs Version

lonelibs ver: 1.0.22

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10299276/latest.log)

### Screenshots/Videos (you can drag and drop files or paste links)

<img width="411" alt="Zrzut ekranu 2022-12-25 o 01 05 54" src="https://user-images.githubusercontent.com/54818384/209453642-34fb4b69-b394-4ef4-b67c-fae9e94041e4.png">

**Comment by NFDCPP** [comment]
> Are you using a Mac or a PC to play Minecraft? I've encountered this issue before and it's related to a bug in the Mac GPUs: #1831
> 
> Let me know, I might be able to find a solution.

I'm using MacOs Ventura 13.1 on my MacBook Pro 13inch 2017 intel core i5 , intel iris graphics 650

**Comment by NFDCPP** [comment]
Also it's worth mentioning that even after disabling emotes you can only see the inner layer of skins head.

**Comment by LoneDev6** [comment]
> Also it's worth mentioning that even after disabling emotes you can only see the inner layer of skins head.

You have to regenerate the pack to completely get rid of emotes after you disabled them.
Anyway I'm working on a hotfix for that but I cannot guarantee it will work fine.

**Comment by LoneDev6** [comment]
@NFDCPP Hello where did you download ItemsAdder?
I need to know the market account name and the market URL where you got the plugin, to know exactly which JAR file you downloaded.

Thanks!

**Comment by NFDCPP** [comment]
I got it on spigotmc :D

**Comment by LoneDev6** [comment]
I cannot find your license: `Notfallingdevil`
![image](https://user-images.githubusercontent.com/27242001/211056661-38ecd918-cbc9-4c32-a1d5-a4c0db851253.png)

**Comment by NFDCPP** [comment]
I got it on another account but i can proof i paid for it

**Comment by LoneDev6** [comment]
Please next time correctly verify your payments.
Do it here: https://forum.devs.beer/t/private-payment-issue
