### ISSUE TITLE
Command for easier submission of required data for bug reports

### ISSUE THREAD

**Issue by Andre601** [PluginBugs/Issues-ItemsAdder#2214]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Andre_601#0601

### Describe the solution you'd like

It's always a tedious and time consuming task to fill out the entire bug report form with information such as IA version, LoneLib version, etc.

It would be a huge improvement, if ItemsAdder would receive a command to collect this common information, put it on a paste and then give you the paste URLs to share.

This would improve bug reports because A) the URL will have all the necessary info you need and B) it's a much easier setup for the user to report something.

Given the usefulness of it, and that other plugins you own may also benefit from, should this perhaps be a command in LoneLibs, so that it could be used for CosmeticsCore, ItemsAdder, etc.

### Is your feature request related to a problem?

Ad mentioned is reporting bugs a tedious task as you constantly have to go back to console, copy the data from it, paste it in the right field and repeat.

### Describe alternatives you've considered

See previous section for the alternative.

### Additional context

I've reported a few things here in the past and filling out the form was always the most annoying part when it came to filling in all the `/version <plugin>` info.
This would help me (And probably other people) a lot in the future when implemented.

**Comment by LoneDev6** [comment]
This would introduce lazy reporters who just use a command to dump data without even reading it.
I prefer people to actually gather data and possibly find the cause of the issue in the meantime.
