### ISSUE TITLE
Customblock expression for skript api 

### ISSUE THREAD

**Issue by ElayDev** [PluginBugs/Issues-ItemsAdder#2220]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

My solution is simple add a new expression same a customitem but customblock, i need that because the setblock and compare blocks is more complicated and the setblock directly give me problems, should be exist this function.

### Is your feature request related to a problem?

Yeah i try to programme some mechanics with blocks and i can't directly

### Describe alternatives you've considered

I see one alternative but is directly with skript work team but is more simple add this mechanic

### Additional context

![image](https://user-images.githubusercontent.com/98564343/209799788-d621d44e-465e-4eec-86e8-7f905aaa14d2.png)

**Comment by LoneDev6** [comment]
Well you can try skript reflect:
https://itemsadder.devs.beer/developers/skript-api/expert-users-1
