### ISSUE TITLE
resourcepack pre-loader

### ISSUE THREAD

**Issue by PortableGames** [PluginBugs/Issues-ItemsAdder#2223]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Improve RP loading. Make it load between login phase and game phase. It looks more professional. and the player's world only loads after the RP is loaded correctly.

### Is your feature request related to a problem?

no

### Describe alternatives you've considered

for example this server-side fabric mod uses it and it's a great solution https://github.com/Patbox/polymer

**Comment by PortableGames** [comment]
So I don't know 🤣 before you get to it so it will probably be useless.. mojang implemented the pre-loader in the last snapshot 1.20.3 Pre-Release 1

**Comment by LoneDev6** [comment]
Amazing! 
More info: https://www.minecraft.net/en-us/article/minecraft-1-20-3-pre-release-1
