### ISSUE TITLE
[Emotes Issue] I loaded my own emote-pack and it's not loading up

### ISSUE THREAD

**Issue by amonalllls** [PluginBugs/Issues-ItemsAdder#2226]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

AMON#8858

### What happened?

Can't use the emote-pack i load into the animations folder.

### Steps to reproduce the issue

1. I went to the Itemsadder folder
2. Headed to resource_pack [data]
3. I went to the minecraft folder and then animations
4. Dropped the .player_animations file in

### Server version

This server is running Paper version git-Paper-387 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: df630a2 on ver/1.18.2)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-265 (MC: 1.18.2)

### ItemsAdder Version

ItemsAdder version 3.3.0b-r2

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b589

### LoneLibs Version

LoneLibs version 1.0.22

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10322401/latest.log)

**Comment by LoneDev6** [comment]
You have tons of errors of other plugins.
Please fix them before opening an issue report.
