### ISSUE TITLE
Broke after updating from 3.2.5 to 3.3.0

### ISSUE THREAD

**Issue by NaTorOG** [PluginBugs/Issues-ItemsAdder#2229]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

After updating from 3.2.5 to 3.3.0 the resourcepack is ""broken"" and I get these errors in console.
https://pastebin.com/cP78Eebr

### Steps to reproduce the issue

1) Server OFF
2) Delete old itemsadder.jar and folder(but back upping only the DATA folder)
3) Install new ItemsAdder and new dependencies and run the server
4) Put in the new folder the old "data" folder with items,blocks etc etc
5) Run again /iazip

### Server version

This server is running Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)
You are running the latest version

### ItemsAdder Version

3.3.0b-r2

### ProtocolLib Version

5.0.0-SNAPSHOT-b602

### LoneLibs Version

1.0.22

**Comment by LoneDev6** [comment]
Fix this file namespace.
> Non [a-z0-9_.-] character in namespace 'Overseer Tools' in yml file: /data/items_packs/overseer_tools/overseer_tools_categories.yml


You also seem to have multiple duplicate files in different folders.
Please make sure to clean your resourcepack based on the errors provided.
