### ISSUE TITLE
Old items are rewritten.

### ISSUE THREAD

**Issue by ookami0104** [PluginBugs/Issues-ItemsAdder#2231]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

I am Japanese and use a translator, so I apologize if my sentences are not correct.

Now, here are the details of the bug that occurred this time.
Previously, adding a new item and updating the resource pack did nothing.
But suddenly, when I add a new item and update the resource pack, the values of the already added item custom model data change and the item installed in the world changes to something else.

### Steps to reproduce the issue

Add new items and activate [/iazip].

### Server version

paper388　1.18.2

### ItemsAdder Version

3.2.3c

### ProtocolLib Version

5.0.0-SNAPSHOT-b605

### LoneLibs Version

1.0.20

### LightAPI Version (optional)

bukkit-5.3.0

### LibsDisguises Version (optional)

10.0.31

**Comment by LoneDev6** [comment]
Sorry i don't understand the issue.
