### ISSUE TITLE
Paper notick armorstands

### ISSUE THREAD

**Issue by Spliterash** [PluginBugs/Issues-ItemsAdder#2233]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Spliterash#4116

### Describe the solution you'd like

Papermc has a method in ArmorStand that allows you to significantly reduce the impact of the stand on the cpu.

![image](https://user-images.githubusercontent.com/22550546/210275601-6100705d-7b36-47f0-8ab7-ff695eeb1c09.png)

I didn't find any mention or recommendation on the wiki to use papermc, and so i'm not sure if itemsadder uses this

### Is your feature request related to a problem?

Only server perfomance

### Describe alternatives you've considered

...

**Comment by LoneDev6** [comment]
It already uses it
