### ISSUE TITLE
Bug in crafting and zipping RP in 3.3.0b-r2

### ISSUE THREAD

**Issue by DarthZeroX** [PluginBugs/Issues-ItemsAdder#2235]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Darth#1042

### What happened?

The first bug is when I want to craft an item using empty water bottles (glass_bottle) and a bucket of water. When you want to grab the item, it doesn't let you do it.

The second bug is when zipping the resource pack in versions higher than 3.3.0-beta-r11. When you try to zip it stays compressing and never finishes. Using 3.3.0-beta-r11 I have no problem zipping my RP.

### Steps to reproduce the issue

First bug:
1. Go to the crafting table
2. Place the items in their corresponding positions
3. Try to grab the resulting item, and you will see that you will not be able to do it

Second bug:
1. Type /iazip and wait
2. You will see how it never finishes compressing and when you rewrite /iazip it says that you must wait for it to finish compressing

### Server version

git-Purpur-1850 (MC: 1.19.2)

### ItemsAdder Version

ItemsAdder version 3.3.0b-r2

### ProtocolLib Version

ProtocolLib v5.0.0-SNAPSHOT-b608

### LoneLibs Version

LoneLibs version 1.0.22

### FULL server log

https://pastebin.com/xwYqvCQu

### Screenshots/Videos (you can drag and drop files or paste links)

https://www.youtube.com/watch?v=Ysuwx471M5Y

**Comment by SirCraftypants** [comment]
Here is the Recipe that is not working https://paste.helpch.at/zijehigazo.yaml

I can confirm that there is nothing wrong with the configuration, it was working perfectly fine under Itemsadder V2, tested with latest V3 as of today and although the recipe seems to be working, when you attempt to take the result it prevents you from dragging it to your inventory. 

I tested this on a test server with only itemsadder and it's dependencies.

**Comment by LoneDev6** [comment]
Will be checked

**Comment by LoneDev6** [comment]
> Failed to validate model: /contents/knightcraft/resourcepack/assets/minecraft/models/custom/drops/cookeddragonmeat.json
> malformed JSON at line 5 column 2

The plugin clearly tells you there is an issue in this file.

**Comment by LoneDev6** [comment]
The recipe doesn't work because of the amount of the bottle. It works fine if you set 1 instead of 3.
This is caused by the fact that the bottle max stack size is 1 in vanilla Minecraft.

I'll add compatibility for this particular case.
