### ISSUE TITLE
[Bug] emoji change chat color

### ISSUE THREAD

**Issue by TUCAOEVER** [PluginBugs/Issues-ItemsAdder#2237]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

Chat color changed after emoji, i found related issue which could be solved by setting "reset-color-to-white" to false, but this option didn't show in latest version.
![image](https://user-images.githubusercontent.com/43756134/210564760-b53f44f3-636e-404e-be65-3beb8df23af5.png)

### Steps to reproduce the issue

1.type :horse:123
2.type:123

### ItemsAdder Version

![image](https://user-images.githubusercontent.com/43756134/210564892-d61471cf-abc0-496e-ba5a-eb4d4988f8d2.png)

### ProtocolLib Version

![image](https://user-images.githubusercontent.com/43756134/210565338-402256f3-e1a7-4c0b-a542-ef6ac42261b8.png)

### LoneLibs Version

![image](https://user-images.githubusercontent.com/43756134/210565018-38ef745f-4e7e-4f5c-9e02-a48737a70f20.png)

**Comment by LoneDev6** [comment]
Strange, I'll try to reproduce it and find a solution.

**Comment by LoneDev6** [comment]
This might actually be caused by the chat plugin you are using.
Can you make sure changing chat plugin doesn't trigger the issue?
