### ISSUE TITLE
Custom Textures Change To Note Blocks Once Right Clicked, Or Other Custom Blocks Around Them Have Been Destroyed.

### ISSUE THREAD

**Issue by Clarence21Clarence21** [PluginBugs/Issues-ItemsAdder#2241]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Clarence21#4211

### What happened?

I noticed that when I break the custom blocks and there's other custom blocks around it they all turn into note blocks. Also when I right click the custom blocks they turn into note blocks and loose their appearances and properties. 

### Steps to reproduce the issue

1. Place custom blocks in a wall shaped pattern
2. Break One of Them
3. See note blocks

### Server version

Spigot 1.15.2

"This server is running CraftBukkit version git-Spigot-a99063f-8731c97 (MC 1.15.2) (Implementing API Version 1.15.2-R0.1-Snapshot)

### ItemsAdder Version

version 3.3.0b-r2

### ProtocolLib Version

version 4.8.0

### LoneLibs Version

version 1.0.22

### LightAPI Version (optional)

version bukkit-5.3.0 (build SNAPSHOT)

### Screenshots/Videos (you can drag and drop files or paste links)

https://user-images.githubusercontent.com/93635096/210871056-dbe29a90-096a-437b-8441-5fe2e21efe41.mp4

![2023-01-05_12 18 53](https://user-images.githubusercontent.com/93635096/210872660-57f0e159-01c8-44ee-aaf6-b52dd68e6b5a.png)

Another user has the same issue:

![proofitsnotjustme](https://user-images.githubusercontent.com/93635096/210873581-13119af1-b9a0-4a30-8a26-0f78db86281b.png)

**Comment by LoneDev6** [comment]
I cannot reproduce the issue.
Try to remove all other plugins.

https://user-images.githubusercontent.com/27242001/211034958-f6a2c2d3-5ce1-465c-8239-eb010fad8fe0.mp4
