### ISSUE TITLE
[Suggestion]  Support AOneblock (BentoBox)

### ISSUE THREAD

**Issue by maxlehot1234** [PluginBugs/Issues-ItemsAdder#225]
Is it possible for you to support AOneblock plugin?

Right now, custom pickaxes from idemadder dont lost durability when players break the magic block from AOneblock plugin.

Bentobox: https://github.com/BentoBoxWorld/BentoBox
AOneblock: https://github.com/BentoBoxWorld/AOneBlock

I think it can be nice if you can support it or let me know how if its already the case. Thanks in advance and have a nice day/night to you

**Comment by LoneDev6** [comment]
Thanks!
Really strange, probably this is the problem: https://github.com/BentoBoxWorld/BentoBox/blob/1429c0a763b1ddebe410d0ddb4270c857d3402a9/src/main/java/world/bentobox/bentobox/listeners/flags/protection/BlockInteractionListener.java#L264
They have to set listen priority to LOW
