### ISSUE TITLE
Emotes item glitch

### ISSUE THREAD

**Issue by NaTorOG** [PluginBugs/Issues-ItemsAdder#2250]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Basically, when a player emote using /emote, the item in the main hand in the hotbar(la barra degli items) disappear and after the emote doesn't appear again, its there but its glitched and if someone move another item in the main hand, it disappear forever.

IT
In sostanza, quando faccio /emote ed ho un oggetto in mano o ne muovo uno nella mano durante l'emote l'ogetto sparisce per sempre dalla mano/inventario del giocatore.

USO IA 3.3.0 beta r-10, ho controllato i changelogs prima ma non ho visto un eventuale fix.
Pufferfish 1.19.2

### Steps to reproduce the issue

Basically, when a player emote using /emote, the item in the main hand in the hotbar(la barra degli items) disappear and after the emote doesn't appear again, its there but its glitched and if someone move another item in the main hand, it disappear forever.

### Server version

This server is running Pufferfish+ version git-PufferfishPlus-32 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: dc803d7 on HEAD)

### ItemsAdder Version

3.3.0 beta r-10

### ProtocolLib Version

5.0.0 b608 SNAPSHOT

### LoneLibs Version

1.0.20

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/2227
