### ISSUE TITLE
Destroying REAL_WIRE drops strings

### ISSUE THREAD

**Issue by konfix** [PluginBugs/Issues-ItemsAdder#2251]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Konfix#3113

### What happened?

Destroying placed REAL_WIRE models when running the latest version of IA and latest Paper (Purpur) 1.19.2 causes the plugin to drop strings, as well as custom drops (if added).

Please note that the gif includes a mechanic from another plugin, I have tested it without that plugin and IA still drops strings, so it doesn't affect this issue (even their support has confirmed that it's an issue probably caused by IA)

### Steps to reproduce the issue

1. Make a new REAL_WIRE block (cancel_drop: true)
2. Obtain a block and place it
3. Destroy it, it should drop the string item as well.

### Server version

git-Purpur-1858 (MC: 1.19.2)*
* You are running the latest version

### ItemsAdder Version

IA 3.3.0b-r2

### ProtocolLib Version

ProtocolLib 5.0.0-SNAPSHOT-b608

### LoneLibs Version

LoneLibs 1.0.22

### Problematic items yml configuration file (optional)

```shell
jabuka_stage_1:
    display_name: ""
    resource:
      generate: false
      material: PAPER
      model_path: farma/jabuka/faza_1
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
        cancel_drop: true
        sound:
          place:
            name: block.azalea.place
          break:
            name: block.azalea.break
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://imgur.com/y2mz9hd

**Comment by LoneDev6** [comment]
I can't reproduce the issue.
I think you're using some sort of crops plugin which is not official and I have no control of.
Contact its authors.

https://user-images.githubusercontent.com/27242001/212096923-792c1216-6c69-4dce-b0cc-a20f318cc4b2.mp4

**Comment by konfix** [comment]
I tried it again without that plugin and I still get strings

> Please note that the gif includes a mechanic from another plugin, I have tested it without that plugin and IA still drops strings, so it doesn't affect this issue (even their support has confirmed that it's an issue probably caused by IA)
