### ISSUE TITLE
2x2 recipe does not work in 2x2 crafting table

### ISSUE THREAD

**Issue by nhanledev** [PluginBugs/Issues-ItemsAdder#2253]
### What happened?

Because of recent bug of shapeless recipe (reported in https://forum.devs.beer/d/80-shapeless-recipe-duplication-bug), I am trying to make a new recipe that allow crafting 1 (one) ingredient to other item.

Using this config:
REDACTED

This config does not allow crafting in 2x2, but in 3x3 it works normally.

REDACTED
Recipe with 2 ingredients or more still works perfectly.

### Steps to reproduce the issue

REDACTED

### ItemsAdder Version

ItemsAdder 3.3.0b-r3-pre1

### ProtocolLib Version

ProtocolLib snapshot build 608

### LoneLibs Version

LoveLib 1.0.22

**Comment by LoneDev6** [comment]
Will be checked, thanks

**Comment by LoneDev6** [comment]
I cannot reproduce the issue, disable all plugins and test again.
Try also to disable ANY other recipe (make a backup of your itemsadder folder) and test.

https://user-images.githubusercontent.com/27242001/212098035-259a23a9-9e99-4f73-b8a4-ce8522967a9e.mp4

**Comment by nhanledev** [comment]
Hello again,
I tested it on the latest version of all plugins and the server, screenshots below
It still can be reproduced; Can you please try to look at it again?

![image](https://user-images.githubusercontent.com/28459250/212102830-34411f6f-16ad-4728-b028-dd4c4df5cde0.png)

The issue
![image](https://user-images.githubusercontent.com/28459250/212102877-b679a38a-bf3d-44d3-879c-c44869ffebbd.png)
![image](https://user-images.githubusercontent.com/28459250/212102904-8fe40dae-b4ce-46c1-bf57-7dc46e2c5339.png)

The yml file
```
info:
  namespace: debugitem
items:
  debug_ore:
    display_name: '&fDebug Ore'
    resource:
      generate: true
      material: PAPER
      textures:
        - items/debug_ore
  debug_sword:
    display_name: Debug Sword
    lore:
    - '&f'
    resource:
      material: DIAMOND_SWORD
      generate: true
      textures:
      - items/debug_sword
    attribute_modifiers:
      mainhand:
        attackDamage: 10
        attackSpeed: 5.6
  debug_block:
    display_name: Debug Block
    resource:
      generate: true
      material: PAPER
      textures:
      - items/debug_block
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: BLOCK
        hardness: 2
        blast_resistance: 1000
        break_tools_blacklist:
          - WOODEN_PICKAXE
          - STONE_PICKAXE
recipes:
  crafting_table:
    debug_sword:
      enabled: true
      pattern:
      - BXX
      - BXX
      - AXX
      pattern_2:
      - XBX
      - XBX
      - XAX
      pattern_3:
      - XXB
      - XXB
      - XXA
      ingredients:
        A: STICK
        B: debugitem:debug_ore
      result:
        item: debugitem:debug_sword
        amount: 1
    debug_block:
      enabled: true
      pattern:
      - AAA
      - AAA
      - AAA
      ingredients:
        A: debugitem:debug_ore
      result:
        item: debugitem:debug_block
        amount: 1
    debug_block_to_gui_2:
      enabled: true
      pattern:
      - XX
      - AX
      ingredients:
        A: debugitem:debug_block
      result:
        item: debugitem:debug_ore
        amount: 9
  anvil_repair:
    debug_sword:
      ingredient: debugitem:debug_ore
      item: debugitem:debug_sword
```

**Comment by LoneDev6** [comment]
@nhanledev please in the future avoid writing the same thing on every social media.

Duplication bugs need to be reported only on the forum via private ticket.
Thanks!
