### ISSUE TITLE
When using an emote, the texture comes out broken.

### ISSUE THREAD

**Issue by Liskrunner** [PluginBugs/Issues-ItemsAdder#2254]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Liskrunner#8941

### What happened?

When executing an emote, the player texture is replaced with Steve Head. Also, if you set the resource pack URL, the itemsadder does not work.

### Steps to reproduce the issue

1. start server
2. and run emotes and
3. 

### Server version

api version 1.19.2-R0.1-SNAPSHOT

### ItemsAdder Version

3.3.0b-r2

### ProtocolLib Version

5.0.0-SNAPSHOP-b608

### LoneLibs Version

1.0.22

### LightAPI Version (optional)

5.3.0(build SNAPSHOT)

### FULL server log

[2023-01-10-7.log.gz](https://github.com/PluginBugs/Issues-ItemsAdder/files/10381684/2023-01-10-7.log.gz)

### Screenshots/Videos (you can drag and drop files or paste links)

![2023-01-10_19 18 49](https://user-images.githubusercontent.com/122357598/211524635-84091fa6-a12e-4a90-8af8-0e49a2973512.png)
![2023-01-10_19 18 22](https://user-images.githubusercontent.com/122357598/211524645-484af64f-48e5-4707-b280-f562d2d56a5a.png)
![2023-01-10_19 18 25](https://user-images.githubusercontent.com/122357598/211524648-ae929b34-c676-4522-a005-ada999181d10.png)

**Comment by LoneDev6** [comment]
- If you are using a cracked launcher try to change it
- Try to update SkinsRestorer if you are using it
- Try to remove shaders if your have installed any
