### ISSUE TITLE
Add an option to make the font_image not appear in autocompletition.

### ISSUE THREAD

**Issue by WMGameLive** [PluginBugs/Issues-ItemsAdder#2255]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

切西瓜#9050

### Describe the solution you'd like

I hope font_images can add an option to decide whether this font_image should appear in autocompletition, or just do not appear for players who don't have the permission.
Because I am using font_images to make some guis, now the autocompletition will show those images that are not emoji, this is not a big problem, just weird for me.

### Is your feature request related to a problem?

No.

### Describe alternatives you've considered

No.

**Comment by LoneDev6** [comment]
`suggest_in_command: false`

**Comment by WMGameLive** [comment]
Sorry, I already try that before I report this, so I thought that doesn't work.
Now I know I need to re-join server when I set it to false, or it will still appear in autocompletition.
Thank you anyway.

**Comment by LoneDev6** [comment]
I'll refresh the autocompletion on plugin reload, thanks
