### ISSUE TITLE
Add an option to turn off emojis autocompletition on chat

### ISSUE THREAD

**Issue by Akiranya** [PluginBugs/Issues-ItemsAdder#2257]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Nailm#9364

### Describe the solution you'd like

Provide an option to turn off emojis autocompletition on chat.

This new feature is added in [3.3.0b-r3](https://github.com/PluginBugs/Issues-ItemsAdder/milestone/70).

### Is your feature request related to a problem?

I have my own chat plugin to specifically handle the "emoji" stuff. This new autocompletion feature is kinda annoyed as it cannot be turned off... as long as you type `:` and `[TAB]` the autocompetions pop up.

### Describe alternatives you've considered

Delete all the emojis files in ItemsAdder probly??? but I think that would be very cumbersome since emoji might have other usage..

**Comment by LoneDev6** [comment]
Will be added as `tab-autocompletion_1_19_1_plus: false` in config.yml
