### ISSUE TITLE
Item name hex colour bug

### ISSUE THREAD

**Issue by elkoyofficial** [PluginBugs/Issues-ItemsAdder#2258]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Joel#8965

### What happened?

Hex colours do not work for the name of the item on the latest version of ItemsAdder (ItemsAdder_3.3.0b-r3.jar)
![image](https://user-images.githubusercontent.com/63325580/211833048-2b4cc9cc-a46d-4ae9-a19d-972476e6d233.png)
As you can see it works completely fine for the lore.

What I have found out is that the legacy format still works
![image](https://user-images.githubusercontent.com/63325580/211833477-98508a18-57da-4b30-8728-1483c9ceff52.png)

and that the default format is broken
![image](https://user-images.githubusercontent.com/63325580/211833567-3a11ea43-c4b7-4441-bc1d-3891afc612d3.png)

### Steps to reproduce the issue

Set a display name to `    display_name: '&x&f&4&e&2&a&cN&x&f&1&d&c&a&5e&x&e&d&d&6&9&dw &x&e&a&d&0&9&6Y&x&e&6&c&a&8&ee&x&e&3&c&4&8&7a&x&d&f&b&e&7&fr&x&d&c&b&8&7&8s &x&d&8&b&2&7&0A&x&d&5&a&c&6&9x&x&d&1&a&6&6&1e'`

/iazip and then hover over the name of the item. 

### Server version

![image](https://user-images.githubusercontent.com/63325580/211833681-dd04843c-823b-4663-b890-531dca55d295.png)

### ItemsAdder Version

![image](https://user-images.githubusercontent.com/63325580/211833734-e32b6b5a-b8b2-44ee-ba88-bc6f1f922038.png)

### ProtocolLib Version

![image](https://user-images.githubusercontent.com/63325580/211833797-e248f262-2726-4416-ac7d-0155f9e42e97.png)

### LoneLibs Version

![image](https://user-images.githubusercontent.com/63325580/211833832-d169c13f-4795-4643-b582-14ff6f5430b2.png)

### FULL server log

https://pastebin.com/3J0mGXw5

### Problematic items yml configuration file (optional)

```shell
items:
  festival_axe:
    display_name: '&x&f&4&e&2&a&cN&x&f&1&d&c&a&5e&x&e&d&d&6&9&dw &x&e&a&d&0&9&6Y&x&e&6&c&a&8&ee&x&e&3&c&4&8&7a&x&d&f&b&e&7&fr&x&d&c&b&8&7&8s &x&d&8&b&2&7&0A&x&d&5&a&c&6&9x&x&d&1&a&6&6&1e'
    lore:
      - "&#f4e2ac✦ &#f2dea7N&#efd9a1e&#edd59cw &#ead197Y&#e8cd91e&#e5c88ca&#e3c487r&#e0c081s &#debb7cC&#dbb776r&#d9b371a&#d6af6ct&#d4aa66e &#d1a661✦"
    permission: permission_model
    resource:
      material: NETHERITE_AXE
      generate: false
      model_id: 50300
      model_path: axe
```

**Comment by LoneDev6** [comment]
I'll try to find a solution, thanks

**Comment by LoneDev6** [comment]
![image](https://user-images.githubusercontent.com/27242001/212097359-039bd933-01ab-4c2f-93c4-1d0ccfcb5288.png)
![image](https://user-images.githubusercontent.com/27242001/212097416-5139d08d-373c-4538-b987-5209dbe0b22b.png)


I can't reproduce the issue.
There is something else interfering.
