### ISSUE TITLE
Craft items that can be brushed

### ISSUE THREAD

**Issue by MuMuMuCODE** [PluginBugs/Issues-ItemsAdder#2260]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Lucky One#2407

### What happened?

if the item has lore，When synthesizing, put items without lore together, and it will become an item with lore

### Steps to reproduce the issue

watch video

### Server version

purpur 1.18.2

### ItemsAdder Version

ItemsAdder_3.3.0b-r3

### ProtocolLib Version

ProtocolLib 5.0.0-SNAPSHOT-b602

### LoneLibs Version

LoneLibs 1.0.23

### Screenshots/Videos (you can drag and drop files or paste links)

https://user-images.githubusercontent.com/90955673/211977320-b5d3788f-3779-4c61-a94d-5b12ca29ce9c.mp4

**Comment by LoneDev6** [comment]
The video is blank. It tells me it's an audio.
![image](https://user-images.githubusercontent.com/27242001/212043054-2bb3db3f-bb0c-448d-a4be-c636338fa663.png)

**Comment by MuMuMuCODE** [comment]
https://user-images.githubusercontent.com/90955673/212211705-4961eec1-bfc1-4f3e-8167-2027aff983dc.mp4

**Comment by MuMuMuCODE** [comment]
Can I private message to your Discord account?

**Comment by LoneDev6** [comment]
You can open a thread on the forum and try to share the video there.
I have no idea why Github is breaking your video, it might be caused by your recording software.

https://forum.devs.beer/
