### ISSUE TITLE
Useless properties added to display name and lore lines of custom items - reopened

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#2261]
Reopened https://github.com/PluginBugs/Issues-ItemsAdder/issues/2189 by @Darkseno

> I have the impression that this update to break something else.
> 
> When I give myself two tickets for example with /iagive and I do a /inv (with CMI) to give one of the tickets to another player and well the NBT changes and the ticket I keep is not the same as the player's.
> 
> It didn't do that before

> Here is the /iatag: https://pastebin.com/hjFik48y
>
> Here how to reproduce the bug: https://www.youtube.com/watch?v=zj86n24K5cs
>
> EDIT: Attention, I also use the Shopkeeper & Eco plugin (it's a kind of api for the Ecocrates, EcoEnchants etc.. plugin) I also believe it handles NBT.
>
> But in this case I don't see why Eco or Shoopkeeper would be a problem.
>
> Also be careful, with your last update you broke all the AI items on my server, I had to redo all my shopkeeper and create debug NPCs so that players could exchange the old items for the new ones, it was long and exhausting.

**Comment by LoneDev6** [comment]
@Darkseno I think it has to do with another plugin.
There is another plugin which is editing the display name of your item.
I suspect it's the `/inv` plugin you are using.

**Comment by Darkseno** [comment]
The /inv is the CMI plugin, I would be surprised if it is the cause of the problem but I should also notify the developer.

I'll keep looking, but I also suspect the Eco plugin (API) to be the cause, it seems to me that it manages the NBT of items

**Comment by LoneDev6** [comment]
What I'd do is:
- enable whitelist so that no player joins
- remove ALL plugins (keep only itemsadder and its dependencies)
- try to reproduce the issue, move the item between inventories, drop it, get it again, check if the issue occurs
- try to add ONLY CMI and test the /inv command


If the issue is CMI please contact CMI developer and tell them that in order to fix this they have to avoid editing the display name of items. Probably they are doing some strange stuff with NBT loading of items which causes optional formatting properties to be added to the display name of item:
`"bold":false,"underlined":false,"strikethrough":false,"obfuscated":false`
