### ISSUE TITLE
Totem Animation CANNOT Be used

### ISSUE THREAD

**Issue by BlueSoar** [PluginBugs/Issues-ItemsAdder#2263]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

When the player excuse "iaplaytotemanimation animatedtitles:xxx xxx" It doesn't work and a totem appears on the player's left hand.Then, the console starts to spam "at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.stopSound(CraftPlayer.java:505) ~[forge:?]",and never stop.
This may because I'm using a forge-bukkit server called CatServer(https://github.com/Luohuayu/CatServer or https://jenkins.rbqcloud.cn:30011/job/CatServer-1.16.5/lastSuccessfulBuild/).

### Steps to reproduce the issue

Using CatServer and excuse "iaplaytotemanimation animatedtitles:xxx xxx"

### Server version

CatServer-da9654d4 (MC: 1.16.5) 1.16.5-R0.1-SNAPSHOT

### ItemsAdder Version

ItemsAdder version 3.3.0b_r4

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.23

### Error (optional)

```shell
https://pastebin.com/W0KcMiqV
```

**Comment by LoneDev6** [comment]
It probably is an issue with CatServer (unofficial spigot fork).
I'll take a look as soon as I can.

**Comment by LoneDev6** [comment]
Please provide your full server log instead of a partial error.
I cannot identify the incompatibility issue otherwise.
