### ISSUE TITLE
More furniture api methods

### ISSUE THREAD

**Issue by Spliterash** [PluginBugs/Issues-ItemsAdder#2264]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Spliterash#4116

### Describe the solution you'd like

Hello. I need an event when a player tries to install furniture so that I can cancel it, get what item it place, and also change the final location where the furniture place will be

### Is your feature request related to a problem?

Yes, i want write helper plugin, that allow place armorstand furniture in custom location, not only block center

### Describe alternatives you've considered

Only catch PlayerInteractEvent, and then check item is furnitre, cancel interact, and then place furniture by self

**Comment by LoneDev6** [comment]
Please write a proper ordered list of what you'd add to the current API.

**Comment by Spliterash** [comment]
Event like this
```java
public class FurnitePlaceEvent implements Cancellable {
    private final Player player;
    private final CustomFurniture furniture;
    // Because player can change color
    private final ItemStack stack;
    private Location location;
    private boolean canceled = false;


    public FurnitePlaceEvent(Player player, CustomFurniture furniture, ItemStack stack, Location location) {
        this.player = player;
        this.furniture = furniture;
        this.stack = stack;
        this.location = location;
    }

    // Getters and setters for location, cancelled
}
```

**Comment by LoneDev6** [comment]
You already have this [FurniturePlaceSuccessEvent](https://lonedev6.github.io/API-ItemsAdder/dev/lone/itemsadder/api/Events/FurniturePlaceSuccessEvent.html)

Then call getItemStack() method on [CustomFurniture](https://lonedev6.github.io/API-ItemsAdder/dev/lone/itemsadder/api/CustomFurniture.html).

**Comment by Spliterash** [comment]
Okay, please update maven api, im not found it inside

**Comment by LoneDev6** [comment]
Because you have an old api in your maven file.
3.2.5 is the latest.

Please make sure to to better checks before opening issue reports.
