### ISSUE TITLE
Saturation fill empty hunger cells

### ISSUE THREAD

**Issue by Reeferx7** [PluginBugs/Issues-ItemsAdder#2266]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Hello, i think there is a problem with saturation doesn't work like normal minecraft food it fills empty hunger cell before the actual hunger value, example i create a food with same stats with steak:

    events:
      eat:
        feed:
          amount: 8
          saturation: 12.8

In the first photo, it's just fill saturation above hunger the second one is just with cooked beef, in both photos i eat the food with empty hunger bar.

![food](https://user-images.githubusercontent.com/8740881/212541409-2c8abf04-f3ad-4b59-84e7-e3f0fa483e5d.jpg)

### Steps to reproduce the issue

Install mod https://www.curseforge.com/minecraft/mc-mods/appleskin (reads saturation)

Empty hunger bar and eat itemsadder food with saturation bigger than hunger
like this:
    events:
      eat:
        feed:
          amount: 8
          saturation: 12.8

Test the same with normal mc food cookbeef

### ItemsAdder Version

ItemsAdder version 3.3.0b-r4

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b610

### LoneLibs Version

LoneLibs version 1.0.23

### Other files, you can drag and drop them here to upload. (optional)

info:
  namespace: cfoods
items:
  toast:
    enabled: true
    display_name: Toast
    permission: toast
    resource:
      material: COOKED_PORKCHOP
      model_id: 411
      generate: true
      textures:
        - breakfast/toast
    events:
      eat:
        feed:
          amount: 8
          saturation: 12.8

**Comment by LoneDev6** [comment]
Apple skin mod is not reliable with ItemsAdder foods since the mod doesn't know the ItemsAdder item real food stats.
It reads the vanilla food stats which are wrong.

**Comment by Reeferx7** [comment]
Hello, no it works like this i found other way to test it with placeholder api:
/papi parse player %player_saturation% Saturation

Here first test with food:
    events:
      eat:
        feed:
          amount: 8
          saturation: 12.8

![εικόνα](https://user-images.githubusercontent.com/8740881/213149284-b3a38b05-de07-455e-a897-3f7fb74372a5.png)

Another example with crazy amount saturation:
    events:
      eat:
        feed:
          amount: 8
          saturation: 100

![εικόνα](https://user-images.githubusercontent.com/8740881/213151320-7e54f85b-7268-4818-84a4-60ac81701d09.png)

Normal minecraft steak example have exactly the same food valuers like in first screenshot above:

![εικόνα](https://user-images.githubusercontent.com/8740881/213152671-704ff926-1470-42a0-9819-72f679072ca1.png)

the effect give @a minecraft:hunger 200 255 takes a lot of time to make the player starve.

from minecraft wiki reference:

For example, if a [golden carrot](https://minecraft.fandom.com/wiki/Golden_carrot) (giving 6 (🍗🍗🍗) and 14.4 saturation points) is eaten by a player whose hunger bar is at 9 (🍗🍗🍗🍗🍗🍗🍗🍗🍗🍗) and saturation is below 1, its value increases to 15 (🍗🍗🍗🍗🍗🍗🍗🍗🍗🍗), and the golden carrot's saturation potential is fully used. However, if the hunger level is 8 (🍗🍗🍗🍗🍗🍗🍗🍗🍗🍗), its value increases to 14 (🍗🍗🍗🍗🍗🍗🍗🍗🍗🍗) and only 14 saturation points are used.

**Comment by Reeferx7** [comment]
Well I find a little abuse the player can eat 4 custom foods like a minecraft steak values and the saturation goes up to 38,4, ~ 4x normal minecraft saturation "bar", and potions with saturation value can endless abused because doesn't stop the hunger bar a player to drink, a good solution maybe is a condition to stop player take extra saturation above config value? But as I see, the plugin doesn't use conditions like "placeholder api conditions"

In other worlds with this system, if the players find what happens with saturation, they can use only one food type for the entire game and the other custom foods become useless.

**Comment by LoneDev6** [comment]
> your report is about the fact that saturation value is not the same unit as Minecraft saturation values?

Please answer clearly

**Comment by LoneDev6** [comment]
Maybe Minecraft wiki has a different unit to represent saturation compared to the Spigot API?
https://helpch.at/docs/1.13/org/bukkit/entity/Player.html#setSaturation-float-

This is the default saturation and food level of player.
```java
public class FoodData {
    public int foodLevel = 20;
    public float saturationLevel = 5.0F;
```

So setting 12+ is not a great idea.


Check my example food items to see some valid saturation values based on the vanilla values.
https://github.com/ItemsAdder/DefaultPack/search?q=saturation

An example: [goldfish](https://github.com/ItemsAdder/DefaultPack/blob/2f9297e8c2a6242c441d5d4d52509323447406f8/contents/iasurvival/configs/food/items/fishes/goldfish.yml)

```yml
    events:
      eat:
        feed:
          amount: 1
          saturation: 0.2
```

Same exact value of the vanilla **tropical fish**.
 
![image](https://user-images.githubusercontent.com/27242001/213207272-1bc07bba-be82-4248-a3f0-2f8b6fb22a67.png)

https://user-images.githubusercontent.com/27242001/213207109-8bfce882-b6c7-4474-ad99-2f6cbd7ba481.mp4
