### ISSUE TITLE
Player head as font image

### ISSUE THREAD

**Issue by Olthoo** [PluginBugs/Issues-ItemsAdder#2269]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Olthoo#0322

### Describe the solution you'd like

As the player head already exist for gui as items (https://www.spigotmc.org/resources/items-custom-player-heads-2d-head-big-wearable-head-for-itemsadder.99121/)

Id like to be able to get font image of the head/skin of the players

### Is your feature request related to a problem?

I would like to use font image in chat here is an example :
![image](https://user-images.githubusercontent.com/86952294/212723015-cd0b5308-d76b-4810-9342-c56ad05d752b.png)

### Describe alternatives you've considered

this plugin already do it, but I try to limit the already huge collection of plugins on my server

https://polymart.org/resource/magic-avatars-40-off.2762

**Comment by LoneDev6** [comment]
This seems to be a niche feature request which can be implemented with an external plugin or addon for ItemsAdder bth

**Comment by Olthoo** [comment]
I don't have any dev knowledge but maybe you could add it to the addon you've created ? ([heads](https://www.spigotmc.org/resources/items-custom-player-heads-2d-head-big-wearable-head-for-itemsadder.99121/)

Thanks in advance

**Comment by LoneDev6** [comment]
![image](https://user-images.githubusercontent.com/27242001/230388846-98ec3045-d8d1-4bb7-8dab-8aca312d2592.png)

This review is valid since the method used by MagicAvatar (the same method I'd use) has a flaw: it causes the game to process a lot of characters to render the heads on screen.
Imagine a server with lot of players, this will cause too much FPS drop.
I cannot implement that.
