### ISSUE TITLE
how to install addon

### ISSUE THREAD

**Issue by YALI1122-coder1** [PluginBugs/Issues-ItemsAdder#2272]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

YaliFR#5369

### What happened?

i dont know how to install the addon

### Steps to reproduce the issue

nothing

### ItemsAdder Version

3.3.0b-r4

### ProtocolLib Version

5.0.0

### LoneLibs Version

1.0.23

**Comment by LoneDev6** [comment]
I don't even know which addon are you trying to install.
Anyway ask on the Discord or check the installation guide provided by the addon author.
