### ISSUE TITLE
Command to delete single items completely

### ISSUE THREAD

**Issue by NaTorOG** [PluginBugs/Issues-ItemsAdder#2273]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

A good and very cool feature could be a command in game to delete a single item from the resourcepack.
Tons and tons of authors make a lot of items and maybe you only need few of them.
Running /iadelete with the item in hand, ItemsAdder will delete from the itemspacefile.yml the configuration section of that item and then will also delete related models and textures of that item.

### Is your feature request related to a problem?

Nope

### Describe alternatives you've considered

Nope

**Comment by NaTorOG** [comment]
Im dumb, I believe there is already

**Comment by NaTorOG** [comment]
After checking, yeah it only remove the config section but not textures and models

**Comment by LoneDev6** [comment]
It's complex to remove item assets.
Imagine other items using the same textures of an item, I cannot simply delete them, it would be risky and can cause the pack to break.
That's why manual deletion is required.
