### ISSUE TITLE
Mushroom Blocks Texture Bug

### ISSUE THREAD

**Issue by MomoLilya** [PluginBugs/Issues-ItemsAdder#2275]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Ponquin#1234

### What happened?

Mushroom blocks textures are bugged. Their top texture turned into the interior texture.

### Steps to reproduce the issue

1. /iazip
2. Find a giant mushroom

### Server version

[05:35:17 INFO]: This server is running Paper version git-Paper-379 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 567ff90)

### ItemsAdder Version

ItemsAdder version 3.3.0b-r5

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b612

### LoneLibs Version

LoneLibs version 1.0.23

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10444911/latest.log)

### Screenshots/Videos (you can drag and drop files or paste links)

![2023-01-18_05 39 24](https://user-images.githubusercontent.com/54742840/213150485-15aacc20-5be4-4bf7-929d-1bf947c03ee4.png)
![2023-01-18_05 40 07](https://user-images.githubusercontent.com/54742840/213150644-9a2ca221-b2c4-4a23-9641-89facd960b48.png)

**Comment by LoneDev6** [comment]
https://itemsadder.devs.beer/faq/blocks-minerals-issues/custom-blocks-glitch-texture/avoid-glitched-blocks

**Comment by MomoLilya** [comment]
This is a default installation with 0 custom blocks added, and with the default ItemsAdder plugin file. The solution you linked does not work.
![image](https://user-images.githubusercontent.com/54742840/213637067-48b4cf93-48c0-48dd-a7dc-b660e1bd6c43.png)
![image](https://user-images.githubusercontent.com/54742840/213637278-d84fec4d-87e5-4a81-aabb-c2423ddbb438.png)
![image](https://user-images.githubusercontent.com/54742840/213637323-c5ccbc89-a59c-4025-8e2b-26351b4d045f.png)

**Comment by MomoLilya** [comment]
I need to set disable-REAL: true even with a clean installation in order to fix it.
