### ISSUE TITLE
PlayerInteractEvent does not seem to work.

### ISSUE THREAD

**Issue by dinobossytnew** [PluginBugs/Issues-ItemsAdder#2277]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

DinoBoss#6985

### What happened?

Hello good morning/afternoon/evening, It seems that when I try to use the interact event following the wiki as I always do in my videos it doesn't seem to work because when I try to apply a change model event by right clicking it doesn't work.

I can send you a video if you want but for now I will send you the settings and log where you can see that I have everything in order in the /iareload and /iazip.

### Steps to reproduce the issue

1 Install ItemsAdders
2 Using 2 models 1 the same and 1 different as a katana guard and a katana.
3 Once installed the 2 items to the one of the guard with the sword you put an interact event right click
4 to the right click event you add an event to modify the model that is to say a change of the 3d model when you right click..

### Server version

[13:13:19 INFO]: This server is running Paper version git-Paper-375 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 7a64b85)
You are 4 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-365 (MC: 1.19.3)

### ItemsAdder Version

[13:13:33 INFO]: ItemsAdder version 3.3.0b-r5
[13:13:33 INFO]: Customized Minecraft without client mods!
[13:13:33 INFO]: Website: devs.beer
[13:13:33 INFO]: Author: LoneDev

### ProtocolLib Version

[13:13:53 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b608
[13:13:53 INFO]: Provides read/write access to the Minecraft protocol.
[13:13:53 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[13:14:02 INFO]: LoneLibs version 1.0.23
[13:14:02 INFO]: Collection of libs used by my plugins
[13:14:02 INFO]: Authors: LoneDev and others

### FULL server log

https://mcpaste.io/1351affe586792c1

### Error (optional)

```shell
no
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: katanadenkipiru
dictionary:
  display-name-katana-1: "&f太刀-刀鞘ꎇ"
  display-name-katana-2: "&f太刀-始刀灼赫"
  lore-1-katana_lore01: "&73D model by Naoxia"
categories:
  swords:
    enabled: true
    skip_if_already: false
    name: katanadenkipiru
    permission: ia.menu.seecategory.swords
    icon: "lantern_rpg_weapon:katana-2"
    items:
      - lantern_rpg_weapon:katana-2
items:
  katana-1:
    display_name: display-name-katana-1
    lore:
      - lore-1-katana_lore01
    enabled: true
    resource:
      material: STONE_SWORD
      generate: false
      model_path: katana/1
  katana-2:
    display_name: display-name-katana-2
    lore:
      - lore-1-katana_lore01
    enabled: true
    resource:
      material: STONE_SWORD
      generate: false
      model_path: katana/2
    durability:
      max_custom_durability: 2562
    attribute_modifiers:
      mainhand:
        attackDamage: 8
        attackSpeed: 1.2
    events:
      attack:
        play_sound:
          name: lantern_rpg_weapon:item.katana.attack
          volume: 1
          pitch: 1
      interact:
        right:
          replace_properties:
            custom_model_data:
              copy_from_item: lantern_rpg_weapon:katana-1
              restorable: true
          play_sound:
            name: lantern_rpg_weapon:item.katana.extracting
            volume: 1
            pitch: 1
#=====================================================================#
```

### Screenshots/Videos (you can drag and drop files or paste links)

null

**Comment by LoneDev6** [comment]
You are using the wrong namespace.
`lantern_rpg_weapon`, shouldn't it be `katanadenkipiru`?
