### ISSUE TITLE
Ability to add a comment to the ZIP-File, similiar to Oraxen

### ISSUE THREAD

**Issue by Gebuildet** [PluginBugs/Issues-ItemsAdder#2279]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Gebuildet#1289

### Describe the solution you'd like

I would like to be able to add a comment to the ZIP-File of the Resource-Pack generated by ItemsAdder, because i can't add it manually after compressing and protecting it with ItemsAdder. Oraxen, an ItemsAdder-clone, has a similiar feature and I would like to have it in ItemsAdder too. (See: https://docs.oraxen.com/configuration/plugin-settings#generation)

### Is your feature request related to a problem?

I want to add a comment, including a copyright notice and credits, to the ZIP-File of my resourcepack. Currently this is not possible with the plugin by default and is only archievable by disabling the pack protection of ItemsAdder and doing it manually, which will make it more easy for thiefs and script-kiddies to steal your textures, model, sounds and more.

### Describe alternatives you've considered

Doing it manually by removing the protection. But as already said above, it's not a great solution.

**Comment by LoneDev6** [comment]
If the purpose of this copyright note is to stop people from stealing your work you're missing the main point.
You can't stop them, this is just useless, trivially the same thing applies to my products JARs.

People can extract your zip to remove protection and then re-compress it which causes comments and other flags to be removed.

If you want it as a cosmetic thing to make people know who made the resources then it's a valid suggestion.
What you can do is create a custom entry inside the pack.mcmeta called "copyright".

```json
{ 
    "pack": {
      "pack_format": 12,
      "description": "My Resource Pack"
    },
    "copyright": {
        "textures": "artist 1",
        "models": "artist 2"
    }
  }
```
