### ISSUE TITLE
Cannot write text when place signs on custom block

### ISSUE THREAD

**Issue by nhanledev** [PluginBugs/Issues-ItemsAdder#2281]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

When place a sign on a custom block, the game does not show the "form" to enter text.
It should show a screen to enter text after placing the sign.

### Steps to reproduce the issue

1. Create a custom block with note block
2. Place that custom block down
3. Place a sign onto that custom block
4. Sign is placed but it does not have a way to write text on it

### Server version

Paper 1.19.2 build 307

### ItemsAdder Version

ItemsAdder 3.3.0b-r5

### ProtocolLib Version

ProtocolLib SNAPSHOT 606

### LoneLibs Version

LoneLibs 1.0.23

**Comment by Millionary** [comment]
https://user-images.githubusercontent.com/105462545/213845273-d81fdffe-06e1-47af-b081-3ab4dd8250a2.mp4

Hey, it's true

**Comment by LoneDev6** [comment]
Will be checked

**Comment by LoneDev6** [comment]
Fixed in upcoming version
