### ISSUE TITLE
Custom emotes are now unavailable 

### ISSUE THREAD

**Issue by glutaminus** [PluginBugs/Issues-ItemsAdder#2283]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

(this happen after i update my 3.3.0b-r3 to 3.3.0-r5)
when using iaemote now I can only use the default emotes even though all the setup are the same as i did in 3.3.0b-r3, did the locations of where to read the animation change? I already look but still don't know.
![image](https://user-images.githubusercontent.com/90768288/213877653-4c4b7026-9b1a-4329-bea7-9a2c87cbd9b2.png)
(ItemsAdder/data/resource_pack/assets/minecraft/animations)

if i removed all these files, the default emotes are still playable, but i can't use my custom emotes anyway

### Steps to reproduce the issue

1. Add my custom emotes with the same method followed by itemsadder wiki.
2. use /iaemote 
3. it only suggest the defaults from itemsadder and i can't use all my custom emotes 

### ItemsAdder Version

ItemsAdder version 3.3.0b-r5

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b602

### LoneLibs Version

 LoneLibs version 1.0.22

**Comment by LoneDev6** [comment]
Thanks for the report, this is a known issue and will be fixed in the upcoming 3.3.1 update!
