### ISSUE TITLE
Block drops still having issues

### ISSUE THREAD

**Issue by Babzy955** [PluginBugs/Issues-ItemsAdder#2286]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

In reference to this since I posted it in the wrong spot

https://github.com/LoneDev6/Wiki-ItemsAdder/issues/72

I got rid of cancel_drop: true like you said and now its dropping both items 

In reference to your last help with this its not the drops it's the block not breaking lol.

![image](https://user-images.githubusercontent.com/72581096/213946088-691cef78-d572-4970-81cc-fca36e2d3970.png)

### Steps to reproduce the issue

I don't know.

### Server version

Paper build #307 1.19.2

### ItemsAdder Version

3.3.0b-r5

### ProtocolLib Version

cannot do /version

### LoneLibs Version

cannot do /version

### LightAPI Version (optional)

5.3.0

### LibsDisguises Version (optional)

no using

### FULL server log

no need

### Error (optional)

```shell
no error
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: mcp
items:
  ruby_ore:
    enabled: true
    display_name: Ruby Ore
    permission: iasurvival.items.ruby_ore
    resource:
      material: PAPER
      generate: true
      textures:
        - blocks/ruby_ore.png
    specific_properties:
      block:
        hardness: 4
        placed_model:
          type: REAL_NOTE
          break_particles_material: REDSTONE_ORE
        break_tools_blacklist:
          - WOODEN_PICKAXE
          - STONE_PICKAXE
        break_tools_whitelist:
          - PICKAXE
          - pickaxe
```

**Comment by LoneDev6** [comment]
I'll check your request as soon as possible

**Comment by Babzy955** [comment]
Thank you man. I dont know how to recreate this at all. I'm sorry

**Comment by LoneDev6** [comment]
I still don't understand what the issue is.

If you want the block to drop ONLY the loot you have to set `cancel_drop: true` in your block configuration.
Make a video of the issue and explain WHAT you expect to happen and WHAT instead happens.
