### ISSUE TITLE
Texture pack is displayed in the wrong version

### ISSUE THREAD

**Issue by DayzDuck** [PluginBugs/Issues-ItemsAdder#2287]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Raccoon#4485

### What happened?

As soon as I generate a texturepack via /iaz all textures work. However, in the texturepack selection I get the message that my texturepack from Itemsadder is in the wrong version (it is highlighted in red and when I try to activate it I get the warning that it is the wrong version).

### Steps to reproduce the issue

1. i have updated itemsadder to 1.19.3
2. BOOM There was the error

I tried to find the error with the help of the community. 
The only thing that would be suggested to me is to change the version number in the pack.mcdata.
I have tried all numbers from 7 to 20.

### Server version

![grafik](https://user-images.githubusercontent.com/62447455/214166606-06c0ec74-6c7b-43dc-8183-7988e4cb613b.png)

### ItemsAdder Version

![grafik](https://user-images.githubusercontent.com/62447455/214169908-d12646a6-34f8-4b0f-bf03-35e31a3852dd.png)

### ProtocolLib Version

![grafik](https://user-images.githubusercontent.com/62447455/214166868-d52e3361-42a0-49be-976f-131043877854.png)

### LoneLibs Version

![grafik](https://user-images.githubusercontent.com/62447455/214166999-e60fb5da-87e0-4ed7-9f6b-8e4304935687.png)

### LibsDisguises Version (optional)

![grafik](https://user-images.githubusercontent.com/62447455/214167246-8f96d5f0-a186-4b17-bdda-3265490be534.png)

### FULL server log

[latest(1).log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10484242/latest.1.log)

### Other files, you can drag and drop them here to upload. (optional)

Reuploaded (see below)

**Comment by DayzDuck** [comment]
[ItemsAdder.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/10484263/ItemsAdder.zip)

**Comment by DayzDuck** [comment]
Also:
Reinstalled Itemsadder and added NOTHING.
Same issue

**Comment by LoneDev6** [comment]
Will be fixed, thanks
