### ISSUE TITLE
Worldedit Itemsadder

### ISSUE THREAD

**Issue by Truongvv10** [PluginBugs/Issues-ItemsAdder#2289]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Wassabi#0317

### What happened?

When using Itemsadder WorldEdit (FastAsync) 

You cannot replace the custom blocks of itemsadder with, //replace or //replacenear. You can also not //undo the custom blocks that have been placed.

### Steps to reproduce the issue

//set itemsadder:test_block
//undo

### Server version

![image](https://user-images.githubusercontent.com/67742370/214286678-97e5b05e-808a-4f04-ac13-99875009e71a.png)

### ItemsAdder Version

![image](https://user-images.githubusercontent.com/67742370/214287136-b4d5370a-bfe8-48a0-a5cc-8c728ff53526.png)

### ProtocolLib Version

![image](https://user-images.githubusercontent.com/67742370/214287162-c59717fd-598c-4ea9-836f-c112fd848722.png)

### LoneLibs Version

![image](https://user-images.githubusercontent.com/67742370/214287199-3c737743-17bc-470b-ae7b-7205ffe3399e.png)

**Comment by LoneDev6** [comment]
Will be checked

**Comment by LoneDev6** [comment]
https://www.spigotmc.org/resources/addon-itemsadder-worldedit.79012/
