### ISSUE TITLE
JetsPrisonMines Compatibility 

### ISSUE THREAD

**Issue by Truongvv10** [PluginBugs/Issues-ItemsAdder#2290]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Wassabi#0317

### Describe the solution you'd like

Would want JetsPrisonMines to support custom blocks. This way we can have more unique ways of having prison/skyblock or even survival servers to use itemsadder. It would be a good addition to both plugins as having texture pack on the server is more and more popular.

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

They use a drag and drop feature, where you drag click on an item and it will recognize it.

**Comment by LoneDev6** [comment]
Contact the developer of JetPrisons, they have to implement the itemsadder api.
Ask them to answer here providing their Spigot username so that I can give them a free copy of the plugin to implement the compatibility.

The API is freely available here: https://github.com/LoneDev6/API-ItemsAdder

**Comment by Truongvv10** [comment]
> Contact the developer of JetPrisons, they have to implement the itemsadder api. Ask them to answer here providing their Spigot username so that I can give them a free copy of the plugin to implement the compatibility.
> 
> The API is freely available here: https://github.com/LoneDev6/API-ItemsAdder

This is what he said
![image](https://user-images.githubusercontent.com/67742370/214366999-660884eb-7772-4b53-8732-eacf790dc714.png)

**Comment by LoneDev6** [comment]
![image](https://user-images.githubusercontent.com/27242001/214541929-5269f134-a02c-4414-8c2b-ce0631c7b13a.png)

I already added this user in the past to the buyers list, they can download the plugin and check the API.
The API is documented and it's extremely simple to use.

Ask them to follow the installation tutorial and read the API.
https://itemsadder.devs.beer/first-install
https://github.com/LoneDev6/API-ItemsAdder
https://itemsadder.devs.beer/developers/java-api
