### ISSUE TITLE
External-host no longer working

### ISSUE THREAD

**Issue by LuluxClient** [PluginBugs/Issues-ItemsAdder#2293]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Lulux#4614

### What happened?

When doing /iazip I've noticed that the pack is no longer getting applied and after checking the console I'm getting this :

[09:59:37 INFO]: [ItemsAdder] [Pack] Resource pack successfully compressed. Uploading...
[09:59:37 INFO]: [ItemsAdder] [Pack] Uploading resourcepack...
[09:59:37 INFO]: [ItemsAdder] [Pack] Finished uploading resourcepack: null
[09:59:37 INFO]: [ItemsAdder] [Pack] Compressed in 222ms

### Steps to reproduce the issue

1. go to the config.yml
2.   auto-external-host:
      enabled: true
      
3. /iareload
4. /iazip

### Server version

This server is running Pufferfish version git-Pufferfish-46 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 5e6e1ad on HEAD)

### ItemsAdder Version

ItemsAdder_3.3.0b-r5

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b612

### LoneLibs Version

LoneLibs version 1.0.23

### FULL server log

private

### Error (optional)

```shell
none
```

### Problematic items yml configuration file (optional)

```shell
auto-external-host:
      enabled: true
```

**Comment by LoneDev6** [comment]
Thanks, I'll do some checks, probably the hosting is not working correctly for some reason.

Maybe it was related to that:
![image](https://user-images.githubusercontent.com/27242001/214545781-ffbb7ac1-a636-41f4-9591-5421cf5783ba.png)


Anyway I will also make some tests to see if something changed on the upload system.

**Comment by LoneDev6** [comment]
Yes their hosting is under maintenance.

**Comment by LoneDev6** [comment]
In the next update I'll add a clear message on the plugin console to state that the upload failed because the hosting is under maintenance.
