### ISSUE TITLE
Make loot drops that come from leave blocks, also drop upon leaf decay.

### ISSUE THREAD

**Issue by ItzASecret** [PluginBugs/Issues-ItemsAdder#2298]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

ItzASecretBoi#1300

### Describe the solution you'd like

After testing, I've found that tree decay doesn't drop loot that is supposed to drop from trees, such as custom fruit etc.. If mining with fist, then it will drop, but leaf decay doesn't drop it by itself. Add pls. Apologies if i'm wrong, but I removed my only tree plugin so testing should be correct.

### Is your feature request related to a problem?

Kinda, no drops from leaf decay, only from player fist/tool

### Describe alternatives you've considered

None.

### Additional context

LoneDev is a hard worker!

**Comment by LoneDev6** [comment]
I don't think there is a clean way to detect decay without having to deal with the high CPU consuming Physics even of Spigot.
I'd avoid implementing that risky code.

For now ItemsAdder catches only player block break event.
