### ISSUE TITLE
Ability to manually add some specific folders to the resources to be merged - for example ModelEngine

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#2299]
Similar to this plugin: https://www.spigotmc.org/resources/model-engine-merger-model-engine-itemsadder-bridge.107246/

Would be nice to be able to specify some folders external to the contents `resourcepack` sub-folders to be added to the list of folders which will be merged by ItemsAdder.
This will allow to support plugins like ModelEngine and Space without having to copy and paste on each edit.

Would be also nice to add support to zip packs directly and not only folders.

**Comment by GabrielTK** [comment]
This is a nice new feature; thanks for implementing it! Is there any documentation on how we can make use of it?
