### ISSUE TITLE
Delete log for Iaplayerstat 

### ISSUE THREAD

**Issue by EspartaProJunior** [PluginBugs/Issues-ItemsAdder#2300]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

I wish they would remove the "value of x has been changed" log, when modifying an iaplayerstat, sometimes it is used a lot and having that come up in the console makes it so there is only that in everything. 

### Is your feature request related to a problem?

Yes

### Describe alternatives you've considered

Perhaps an option in the config 

### Additional context

no

**Comment by LoneDev6** [comment]
New optional attribute "silent":
`/iaplayerstat write LoneDev thirst 0 silent`
