### ISSUE TITLE
Emotes shader issue, player & mob heads not rendered from inside

### ISSUE THREAD

**Issue by Septicuss** [PluginBugs/Issues-ItemsAdder#2302]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Septicuss#4273

### What happened?

A visual bug, where the head of an entity is not rendered **from the inside**. Using spectator mode, F5 or any other way of spectating an entities head from the inside, with the option `entities.custom-entities.emotes` set to true (emotes enabled), will result in the heads not being rendered properly.

This may happen with other mobs too, but is sure to happen on all piglins & players (other, nearby players as well as the host).

**No significant client mods.**

### Steps to reproduce the issue

1. Create a fresh install with latest version of ItemsAdder
2. Enable emotes through the `entities.custom-entities.emotes` option
3. Observe the bug, by going inside any entity with a head texture layer

### Server version

This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version

### ItemsAdder Version

ItemsAdder version 3.3.0b-r5

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b608

### LoneLibs Version

LoneLibs version 1.0.22

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10523955/latest.log)

### Screenshots/Videos (you can drag and drop files or paste links)

Screenshots of the issue:
[https://imgur.com/a/h5K6zX1](https://imgur.com/a/h5K6zX1)

Screenshots from Origin Realms, without the mentioned issue:
![image](https://user-images.githubusercontent.com/40741898/215228500-34bf7eb8-e091-4aae-8bad-7e2742db9e97.png)

**Comment by LoneDev6** [comment]
Did you test it on multiple PCs?
It might be an issue of your GPU driver.
As you can see in the showcase video is works fine (time: 0:39)
https://youtu.be/posxlbudF8I?t=39

**Comment by Septicuss** [comment]
Yes. The issue has occured on more than one PC with different specs. I should note that the issue happens on the normal player mob, not on the emote model.

**Comment by LoneDev6** [comment]
Can you send me the server IP so that I can join and test the emotes?
Don't forget to give me permissions to trigger the emotes, my username is LoneDev.

**Comment by Septicuss** [comment]
I'm not sure whether that is relevant infomation, since the problem happens on more than one skin and even on other vanilla mobs. 
![87207a7950a8fdf6](https://user-images.githubusercontent.com/40741898/215497483-d09fd746-8c8b-48ea-bb4e-ccf738c493c1.png)

**Comment by LoneDev6** [comment]
Thanks a lot this will be helpful for my tests.
Also please provide the precise GPU name which used by the player who has the issue.
Read this guide if you need: https://winbuzzer.com/2020/08/21/how-to-check-what-graphics-card-you-have-on-windows-10-xcxwbt/

**Comment by Septicuss** [comment]
1) NVIDIA GeForce GTX 1060
2) NVIDIA GeForce GTX 960

Two different GPUs, on which this bug was noticed.

**Comment by LoneDev6** [comment]
Sorry for the wait.

Tested on GTX 980 Ti and I cannot reproduce the issue with your skin.
Please feel free to join my Discord server again so that I can add you to the beta testers channel, you'll be able to download a beta to test if the issue still occurs.
I sadly cannot do more tests as I own only 1 GPU.

**Comment by LoneDev6** [comment]
Also you can try updating your GPU drivers to the very latest version. Let me know.
