### ISSUE TITLE
Bug where dozens of emoji can't be used

### ISSUE THREAD

**Issue by madebygood** [PluginBugs/Issues-ItemsAdder#2304]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

When holding an emoji, it is out of the book due to the number of characters.

Players do not know which emoji they have because they do not appear in the book.

![image](https://user-images.githubusercontent.com/43653581/215275333-f74db0d1-25eb-4ff1-89af-6785b3505f10.png)
There are too many characters, so it goes beyond the scope of the book.

### Steps to reproduce the issue

1. get emoji
2. /emoji
3. do not apear

### ItemsAdder Version

.

### ProtocolLib Version

.

### LoneLibs Version

.

**Comment by LoneDev6** [comment]
This issue is not clear.
Please rephrase it and provide more info.
