### ISSUE TITLE
Clearing nbt tags during crash

### ISSUE THREAD

**Issue by Lerphie** [PluginBugs/Issues-ItemsAdder#2307]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Coder#6926

### What happened?

LoneDev hello! I faced such a problem 3 months ago, all my custom ores with generation (about 30 ores) began to turn into musical blocks. All this time I've been trying to figure out how this happens. Today I found out the cause of this problem! The fact is that when you crash, your plugin does not have time to save NBT tags in chunks. Because of this, when entering the server, the musical blocks reset their nbt tag (texture). Watch the video and you'll understand everything. (sorry for my English)

### Steps to reproduce the issue

1) Put any block with a new texture. 
2) Crash the server. 
3) Log in to the server and click the pcm on the block.

### Server version

Current: git-Purpur-1894 (MC: 1.19.3)

### ItemsAdder Version

3.3.0b-r5

### ProtocolLib Version

5.0.0-SNAPSHOT-b612

### LoneLibs Version

1.0.23

### LibsDisguises Version (optional)

10.0.31-SNAPSHOT

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/PWFIvM1jeAY

**Comment by LoneDev6** [comment]
Well this is normal, you're not supposed to crash the server and expect it to save data correctly. This applies to any plugin.
I simply cannot save the file each time you place/remove a blocks, this would make the server slow as hell.
