### ISSUE TITLE
Bug where emojis are not visible in the book

### ISSUE THREAD

**Issue by madebygood** [PluginBugs/Issues-ItemsAdder#2309]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Before get permission the emoji:
![image](https://user-images.githubusercontent.com/43653581/215497262-5a690c71-0b33-4866-b568-fef2ec767e08.png)

After get permission the emoji:
![image](https://user-images.githubusercontent.com/43653581/215497295-29f04160-b1d4-4370-98d9-4bd523047cb7.png)

Originally, :mc_crossbow_pulling_2: should be followed by :mc_cyan_dye: .

However, there is not enough space for text in the book.

This emoji will not moving to the next page, and will not be visible.

(If you look at the top right, you can see that both are equally up to 42 pages.)

![image](https://user-images.githubusercontent.com/43653581/215498731-30146008-8dba-4e7f-b421-cc3b666d7df0.png)

![image](https://user-images.githubusercontent.com/43653581/215498800-a06431cc-b72a-4e2f-8cb0-24185566b6be.png)
In the picture above, there is a problem that potion, kelp, egg, elytra, and emerald are not visible under the diamond sword.

### Steps to reproduce the issue

1. Enter /emoji.

2. If there is not enough space to display text at this time, some emojis at the bottom are not output.

### Server version

![image](https://user-images.githubusercontent.com/43653581/215499297-a78f49bb-2bc8-46aa-b65a-c1163f3a8528.png)

### ItemsAdder Version

![image](https://user-images.githubusercontent.com/43653581/215499336-a18fa909-f01f-46c5-b16d-3717d57a51dc.png)

### ProtocolLib Version

![image](https://user-images.githubusercontent.com/43653581/215499378-f72076cc-4006-4c33-be15-bca416744b5c.png)

### LoneLibs Version

![image](https://user-images.githubusercontent.com/43653581/215499406-8867ceb8-ed19-4522-9897-60f1b2d23067.png)

**Comment by thefourcraft** [comment]
> Before get permission the emoji:
if you don't have permission you can't see the emoji's code
not sure what is the issue

**Comment by madebygood** [comment]
1) Minecraft books have a limit on the number of characters that can be written.

2) :mc_diamond_chestplate: :mc_diamond_helmet:
etc...

In this way, the number of emoji characters is longer than the limit.

3) Then, the emojis at the bottom of the book do not move to the next page.

(just disappear)

4) Then the emojis below will not be visible to the player in /emoji.

**Comment by madebygood** [comment]
Not sure yet? Maybe you need a bit more explanation?

**Comment by LoneDev6** [comment]
Will be checked in the next days
