### ISSUE TITLE
Better command `/ia` - fixes

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#2310]
@Akiranya

> Hey Lone, I just found some features are not implemented:
> 
> 1. Players can use `/ia <category name>` to directly opens a GUI for a specific category
> 2. GUI opened this way does not have "back" button to go back to the main GUI (opened by `/ia`)
> 3. Console/OP can use `/ia <category name> <playername>` to **force open** a specific category for a specific player
> 4. This command respects the permission `ia.menu.seecategory.<category name>` so if the player doesn't have the permission IA will send a proper message (**but** when Console/OP uses `/ia <category name> <playername>` the player can bypass the permission)
> 
> 2 and 3 are not fully implemented...
> 
> For 2, it still has a `back button` if the category GUI is opened by `/ia <category name>`
> For 3, the console couldn't run the command.
> 
> Could you also implement these features as well? These are really important to seamlessly interact with other scripts/plugins

**Comment by thefourcraft** [comment]
cool suggestion  💪🏻

**Comment by thefourcraft** [comment]
YES!
