### ISSUE TITLE
Set custom blocks and bug happen...

### ISSUE THREAD

**Issue by KingTatouille** [PluginBugs/Issues-ItemsAdder#2312]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

HillTea#5027

### What happened?

Hi 🚶 
I created an plugin for prisonMines generator. I use vanilla blocks and your plugin for this generator but I see a problem when i crash test somes functionnality's in this...

When i generate a large region with itemsadder blocks and i replace the blocks i obtain this result, please follow the video.

### Steps to reproduce the issue

Do the command : //wand
- Select two corners
- Set 1 (stone)
- With my plugin i can full put your blocks so i fill the region with ItemsAdder blocks
- and I do again //set 1
- after this I break a block and your block spawn so i need to break again your block.

### Server version

Previous version: git-Paper-265 (MC: 1.19.3)

### ItemsAdder Version

Version 3.3.1

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b612

### LoneLibs Version

LoneLibs version 1.0.23

### FULL server log

Nothing happen in

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/XBLVvhM09Mg

**Comment by LoneDev6** [comment]
You have to make sure to call the api remove method of CustomBlock class when you want to remove a custom block to replace it with a vanilla block.

https://github.com/LoneDev6/API-ItemsAdder/blob/master/src/main/java/dev/lone/itemsadder/api/CustomBlock.java

**Comment by LoneDev6** [comment]
You might also need to install the worldedit addon https://www.spigotmc.org/resources/addon-itemsadder-worldedit.79012/
