### ISSUE TITLE
After death, a strange map comes in.

### ISSUE THREAD

**Issue by repiece** [PluginBugs/Issues-ItemsAdder#2316]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

If the player dies in a way other than command /kill, a map will appear showing where the player died.

### Steps to reproduce the issue

1. Install the itemsadder plugin.
2. Install the LoneLibs plugin.
3. Install the ProtocolLib plugin.
4. Run Minecraft.
5. Kill the player character.

### Server version

This server is running CraftBukkit version 3638-Spigot-d90018e-7dcb59b (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 3.3.1

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b612

### LoneLibs Version

LoneLibs version 1.0.23

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/112340274/216201939-5f2df169-e3ea-4540-bf81-218d2b6e519c.png)

**Comment by madebygood** [comment]
Configurable in config.

However, most servers turn off this death map function, so I hope this plugin set the default value to false.
