### ISSUE TITLE
[Suggestion] Add storage blocks

### ISSUE THREAD

**Issue by chimal1994** [PluginBugs/Issues-ItemsAdder#2317]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Chimal1994#7902

### Describe the solution you'd like

Add the possibility of creating blocks and furniture with storage

  Closed:
    display_name: display-name-closed
    permission: closed
    resource:
      material: PAPER
      generate: false
      model_path: item/closed
    behaviours:
      furniture:
        solid: true
      furniture_storage:
        title: Closed
        slots: 27

### Is your feature request related to a problem?

Itemsadder allows you to create trade machines but not blocks to store items

### Describe alternatives you've considered

I can't think of any alternative at the moment

### Additional context

![Снимок экрана 2023-02-02 141642](https://user-images.githubusercontent.com/71217933/216311556-5a997322-3379-42ba-85d9-a766b41dfda9.png)

**Comment by AllayBreeze** [comment]
You can try StorageMechanics plugin. Link: https://polymart.org/resource/storage-mechanics.2978

**Comment by LoneDev6** [comment]
Duplicate https://github.com/PluginBugs/Issues-ItemsAdder/issues/777
