### ISSUE TITLE
/iaplayerstat command isn't working

### ISSUE THREAD

**Issue by Millionary** [PluginBugs/Issues-ItemsAdder#2323]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Millionary#3711

### What happened?

I have notice that my stats are not decrementing or augmenting, /iaplayerstat isn't working.

### Steps to reproduce the issue

1. Use /iaplayerstat command
2. Notice that the values are not changing

### Server version

This server is running Paper version git-Paper-386 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 4da844f)
You are running the latest version
Previous version: git-Paper-381 (MC: 1.19.3)

### ItemsAdder Version

ItemsAdder version 3.3.1

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b612

### LoneLibs Version

LoneLibs version 1.0.23

### Screenshots/Videos (you can drag and drop files or paste links)

https://user-images.githubusercontent.com/105462545/216773370-9aaf4f31-2a64-45aa-a227-66d21486ae51.mp4

**Comment by LoneDev6** [comment]
Seems related to this: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2321
