### ISSUE TITLE
I can't use the ressource pack with my MacBook Pro

### ISSUE THREAD

**Issue by C4ptainFoxy** [PluginBugs/Issues-ItemsAdder#2324]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I'm trying to use my own itemsadder pack on my macbook pro but every textures turn to black. And everything works on my windows. i'm using the same version too, do someone know how to fix this ? 

Cordialy

### Steps to reproduce the issue

Launch the RP, go back to the game..

### Server version

1.17.1 purpur

### ItemsAdder Version

ItemsAdder version 3.3.1

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.23

### LightAPI Version (optional)

nah

### LibsDisguises Version (optional)

nah

### FULL server log

Client side bug, not server

### Error (optional)

```shell
don't see anything
```

### Problematic items yml configuration file (optional)

```shell
nope
```

### Screenshots/Videos (you can drag and drop files or paste links)

I don't have my mac, but imagine all textures (include vanilla textures) fading to black

**Comment by thefourcraft** [comment]
I am using the MacBook Pro (M1), and it's not working with Minecraft, let alone servers...
MacBooks aren't for gaming @C4ptainFoxy

**Comment by LoneDev6** [comment]
It's hard to help you without any proper screenshot, video and your client log.
Obtain the client log here: https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown

Anyway Macs are known to have issues with gaming in general because of their GPU architecture.
There is really nothing I can do to prevent this since Mojang and Apple are the only ones with access to this low level stuff.

I wish things were simpler but it's not always like that.

**Comment by C4ptainFoxy** [comment]
Hiya! Here's the latest.logs file:

[IAlatest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10686223/IAlatest.log)

**Comment by LoneDev6** [comment]
Check the log, it's filled with errors related to misconfigured models/textures.
Fix them, you must have a clean log before shipping your resourcepack to players.

Let me know how it goes, have a nice day
