### ISSUE TITLE
Single resourcepack Bungeecord problem

### ISSUE THREAD

**Issue by Saharo4eks** [PluginBugs/Issues-ItemsAdder#2325]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Zopka))0)#2628

### What happened?

I have two servers: survival and lobby. I used the tutorial "https://itemsadder.devs.beer/faq/single-resourcepack-bungeecord", I got no results.

### Steps to reproduce the issue

1. Install ItemsAdder on Survival and lobby servers;
2. Set self-host in config.yml lobby and address and port;
3. /iareload and /iazip in lobby (Puck is successful work in the lobby)
4. Set external-host in config.yml survival, /iainfo in lobby and set this url without that part after #.
5. /iareload and /iazip in survival
6. Get error (https://imgur.com/a/boj32hw)

### Server version

Survival:
Current: git-Purpur-1906 (MC: 1.19.3)*
* You are 1 version(s) behind
Download the new version at: https://purpurmc.org/downloads

Lobby:
Current: git-Fusion-"5bbfcd5" (MC: 1.19.3)*
* You are 11 version(s) behind
Download the new version at: https://github.com/IPECTER/Fusion/releases

### ItemsAdder Version

Survival: ItemsAdder version 3.3.1
Lobby: ItemsAdder version 3.3.1

### ProtocolLib Version

Lobby: 5.0.0-SNAPSHOT-b612
Survival: 5.0.0-SNAPSHOT-b612

### LoneLibs Version

Lobby: 1.0.23
Survival: 1.0.23

### LightAPI Version (optional)

-

### LibsDisguises Version (optional)

-

### FULL server log

Survival: 
[log.txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/10609442/log.txt)

Lobby: 
[log_lobby.txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/10609445/log_lobby.txt)

### Problematic items yml configuration file (optional)

```shell
-
```

### Other files, you can drag and drop them here to upload. (optional)

I followed the link that is generated in the lobby, the pac is successfully downloaded. But on the survival server I still recommend somewhere to download my pack. I do not know why.

### Screenshots/Videos (you can drag and drop files or paste links)

-

**Comment by LoneDev6** [comment]
This is not an error, it's just a warning and explains newbies how to host the resourcepack to avoid them forgetting about reuploading the resourcepack.

You are using Bungeepackfix so the warning  message can be ignored.

**Comment by Saharo4eks** [comment]
> This is not an error, it's just a warning and explains newbies how to host the resourcepack to avoid them forgetting about reuploading the resourcepack.
> 
> You are using Bungeepackfix so the warning message can be ignored.

You don't get it. I'm not just getting this message, the problem is that on the second server the texture pack is NOT loading.

**Comment by LoneDev6** [comment]
What do you mean by "not loading"?
Nothing happens?

The tutorial was tested hundred of times and worked fine for me, did you skip any step?
