### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to ItemsAdder v3.3.1

### ISSUE THREAD

**Issue by ofunny** [PluginBugs/Issues-ItemsAdder#2332]
### What happened?

I was testings sounds while converting the "default" and "other" pack to Bedrock for Geyser and noted a bug with the light sabers. When I hit a mob (e.g. Zombie) it will trigger the following error: https://mcpaste.io/2b888d884d98487a

The light saber is also the only weapon what of the two packs using a sound effect on attack – this sound is not working and might be related to the problem of passing the EntityDamageByEntityEvent event.

### Steps to reproduce the issue

1. Install the pack including the light saber
2. Spawn some mobs (e.g. Zombie)
3. Hit them with the light saber

Result: No sound and error in console (EntityDamageByEntityEvent)

### Server version

This server is running Paper version git-Paper-392 (MC: 1.19.3)

### ItemsAdder Version

ItemsAdder version [3.3.1]

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b612

### LoneLibs Version

LoneLibs version 1.0.23

### Error (optional)

```
[02:21:47] [Server thread/INFO]: ofunny issued server command: /spawnmob zombie
[02:21:49] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to ItemsAdder v3.3.1
java.lang.StackOverflowError: null
	at ia.m.dI.a(SourceFile:53) ~[ItemsAdder.jar:?]
```

```shell
https://mcpaste.io/2b888d884d98487a
```

**Comment by LoneDev6** [comment]
> Install the pack including the light saber

Which pack?
