### ISSUE TITLE
Can't take any items in the /ia 

### ISSUE THREAD

**Issue by Tom13122331** [PluginBugs/Issues-ItemsAdder#2333]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Nextix o mcdo 2#0001

### What happened?

When me or any others staff try to take a item adder item, no gui open.

### Steps to reproduce the issue

go in /ia
click on any category 
click on any block
nothing happen

### Server version

I can't run this command ( we are using spigot 2.1.0-SNAPSHOT in 1.17.1 ) 

### ItemsAdder Version

3.3.1

### ProtocolLib Version

5.0.0-SNAPSHOT-b612

### LoneLibs Version

1.0.23

### Screenshots/Videos (you can drag and drop files or paste links)

https://user-images.githubusercontent.com/69093020/218107637-a7288859-8b5a-4db4-aa31-c3da184cb76d.mp4

**Comment by LoneDev6** [comment]
Remove all plugins and tests, probably there is an interfering plugin.
Also check your server log for errors.

> we are using spigot 2.1.0-SNAPSHOT in 1.17.1

I see no reason to stay on 1.17.1, but if you really want to you should switch to paper since spigot 1.17.1 is not updated.
https://papermc.io/legacy
