### ISSUE TITLE
Executable Blocks support

### ISSUE THREAD

**Issue by Reeferx7** [PluginBugs/Issues-ItemsAdder#2336]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Hello, can you add support on Executable Blocks plugin like Executable items?

example:

info:
  namespace: customblocks
items:
  drink:
    display_name: customblock
    executableblock:
      id: customblock
      textures:
      - customblocks/customblock.png

https://www.spigotmc.org/resources/%E2%AD%90-executable-blocks-%E2%AD%90-custom-traps-generators-builders-triggers-animated-effect-blocks.94696/

### Is your feature request related to a problem?

-

### Describe alternatives you've considered

-

**Comment by LoneDev6** [comment]
https://docs.ssomar.com/executableitems/compatible-plugins#itemsadder

**Comment by LoneDev6** [comment]
ssomar implemented the compatibility some time ago
