### ISSUE TITLE
Missing textures in model minecraft:paper#inventory:

### ISSUE THREAD

**Issue by Siouldlh** [PluginBugs/Issues-ItemsAdder#2339]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

minecraft:textures/atlas/blocks.png:_iainternal:icons/icon_arrow_chest
    minecraft:textures/atlas/blocks.png:_iainternal:icons/icon_back_orange
    minecraft:textures/atlas/blocks.png:_iainternal:icons/icon_cancel
    minecraft:textures/atlas/blocks.png:_iainternal:icons/icon_left_blue
    minecraft:textures/atlas/blocks.png:_iainternal:icons/icon_next_orange
    minecraft:textures/atlas/blocks.png:_iainternal:icons/icon_right_blue
    minecraft:textures/atlas/blocks.png:_iainternal:icons/icon_search

### Steps to reproduce the issue

launch the plugin

### Server version

This server is running Paper version git-Paper-396 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: bd77b78)

### ItemsAdder Version

ItemsAdder version 3.3.1

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b612

### LoneLibs Version

LoneLibs version 1.0.23

### Error (optional)

```shell
minecraft:textures/atlas/blocks.png:_iainternal:icons/icon_arrow_chest
    minecraft:textures/atlas/blocks.png:_iainternal:icons/icon_back_orange
    minecraft:textures/atlas/blocks.png:_iainternal:icons/icon_cancel
    minecraft:textures/atlas/blocks.png:_iainternal:icons/icon_left_blue
    minecraft:textures/atlas/blocks.png:_iainternal:icons/icon_next_orange
    minecraft:textures/atlas/blocks.png:_iainternal:icons/icon_right_blue
    minecraft:textures/atlas/blocks.png:_iainternal:icons/icon_search
Image not found for font_image '_iainternal:no_recipe'. assets/_iainternal/textures/gui/no_recipe.png
12.02 20:45:30 [Server] ERROR Image not found for font_image '_iainternal:crafting'. assets/_iainternal/textures/gui/crafting.png
12.02 20:45:30 [Server] ERROR Image not found for font_image '_iainternal:cooking'. assets/_iainternal/textures/gui/cooking.png
12.02 20:45:30 [Server] ERROR Image not found for font_image '_iainternal:blank_menu'. assets/_iainternal/textures/gui/blank_menu.png
12.02 20:45:30 [Server] ERROR Image not found for font_image '_iainternal:anvil_repair'. assets/_iainternal/textures/gui/anvil_repair.png
12.02 20:45:30 [Server] ERROR Image not found for font_image '_iainternal:smithing'. assets/_iainternal/textures/gui/smithing.png
```

**Comment by LoneDev6** [comment]
Another customer had a similar issue.
It was about the fact that the server hosting used is setting wrong files permissions.

They should be `775` or `770`, instead they probably are set to `755`.

If your hosting doesn't allow you to change files permissions using an FTP client you have to use this trick:
Download, delete from the server and reupload these files manually via FTP to force the server to set the correct files permissions to `770`, but this is not ideal in the long term.


If this is the case I suggest you to ask to your hosting why they are setting the wrong permission and why they don't allow you to change them (if you can't).

**Comment by Siouldlh** [comment]
Ok it works thank you very much but the problem is that now I don't have any more errors in the console but there is this that appears on top and I don't have the emojis anymore I have checked the configuration, the files and the directions are right but it doesn't work 
<img width="414" alt="Capture d’écran 2023-02-15 à 16 11 41" src="https://user-images.githubusercontent.com/55910809/219068399-dc7fe177-c160-42c7-acd9-99146764bd23.png">

**Comment by Siouldlh** [comment]
I don't have addons (esc)

**Comment by LoneDev6** [comment]
Regenerate your pack, accept the resourcepack.

https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown

https://itemsadder.devs.beer/faq/resourcepack-not-loading
