### ISSUE TITLE
Loading screen cannot be customized.

### ISSUE THREAD

**Issue by JFla4024** [PluginBugs/Issues-ItemsAdder#2340]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

discordts

### What happened?

Is the Loading screen in wiki outdated?
My server version is 1.19.2.

Wiki said：
Edit my file: contents\loading_screen\resourcepack\minecraft\textures\gui\title\mojangstudios.png
Save the file in the same location

But I can't find any files under contents\.
So I added my own resource directory folder. And made a picture with a size of 512*512.

C:\Users\YF\Desktop\1.19.2\plugins\ItemsAdder\contents\loading_screen\resourcepack\minecraft\textrues\gui\title

Then I entered /iazip in the game, but there was no custom loading effect.

### Steps to reproduce the issue

Wiki said：
Edit my file: contents\loading_screen\resourcepack\minecraft\textures\gui\title\mojangstudios.png
Save the file in the same location

But I can't find any files under contents\.
So I added my own resource directory folder. And made a picture with a size of 512*512.

C:\Users\YF\Desktop\1.19.2\plugins\ItemsAdder\contents\loading_screen\resourcepack\minecraft\textrues\gui\title

Then I entered /iazip in the game, but there was no custom loading effect.

### Server version

[18:59:20] [Server thread/INFO]: This server is running CraftBukkit version 3566-Spigot-584b459-c379a6b (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT)                                                                            

### ItemsAdder Version

ItemsAdder version 3.3.1

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b612   

### LoneLibs Version

LoneLibs version 1.0.23   

### LightAPI Version (optional)

LightAPI version bukkit-5.3.0

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/125266109/218441315-c2009a08-2f37-4801-b738-85726ae031aa.png)

**Comment by LoneDev6** [comment]
Are you using optifine?
This is an optifine only feature as clearly noted in the wiki.
https://itemsadder.devs.beer/plugin-usage/adding-content/optifine-only-features/loading-screen

It's a limitation of the game, I can't do anything to fix that.
