### ISSUE TITLE
Add an option to be able to place the two types of liquids in the game

### ISSUE THREAD

**Issue by chimal1994** [PluginBugs/Issues-ItemsAdder#2342]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Chimal1994#7902

### Describe the solution you'd like

Add an option to be able to place the two types of liquids in the game, right now we can only place colored water, I would like the liquids to also include the lava.

For example, add a new action that allows us to choose the type of liquid that we are going to place:

  interact:
    right:
      place_liquid: WATER (or LAVA)

### Is your feature request related to a problem?

Yes, currently we cannot place the two liquids in a simple way

### Describe alternatives you've considered

none

**Comment by LoneDev6** [comment]
You should already be able to do that, please let me know.
```yml
    events:
      interact:
        left:
          set_block:
            block: LAVA
```
