### ISSUE TITLE
Chinese cannot be recognized

### ISSUE THREAD

**Issue by tygh78071388** [PluginBugs/Issues-ItemsAdder#2343]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

冰拿鐵去咖啡#4333

### What happened?

3.2.5 normal
3.3.1 error

Chinese cannot be recognized, I have a lot of furniture, and some other magical things, I hope to keep the Chinese names.

Please! Thank you

### Steps to reproduce the issue

1.write items_packs
2./lazip
3.error

### Server version

Paper version git-Paper-279 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: a7df847)

### ItemsAdder Version

3.3.1

### ProtocolLib Version

5.0.0-SNAPSHOT-b600

### LoneLibs Version

1.0.23

### Error (optional)

```shell
Non [a-z0-9_.-] character in custom item name '鐮刀-1' in yml file: /data/items_packs/damge/武器.yml
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: damge
items:
  鐮刀:
    display_name: "鐮刀"
    permission: myitems.decorative.鐮刀
    resource:
      material: netherite_sword
      model_id: 1
      generate: false
      model_path: sickle
```

**Comment by LoneDev6** [comment]
You can't have chinese names without causing issues with the game.
Minecraft doesn't support chinese names in files, it's a limitation of the game.

It might have been permitted before but wasn't stable, now it's not allowed anymore to avoid incompatibility with Minecraft itself.

**Comment by tygh78071388** [comment]
> You can't have chinese names without causing issues with the game. Minecraft doesn't support chinese names in files, it's a limitation of the game.
> 
> It might have been permitted before but wasn't stable, now it's not allowed anymore to avoid incompatibility with Minecraft itself.
> 
> Sadly there is nothing I can do about it, it's how the game works.

i know resourcepacks can't use text other than English.
Is there a way for me to switch whether to detect [a-z0-9_.-]?
Because of the current modification, the furniture that was once placed will cause problems

**Comment by LoneDev6** [comment]
Not really because it can cause issues on future updates, you were not supposed to create items with chinese names.
I clearly posted on the wiki long time ago to avoid doing that.

https://itemsadder.devs.beer/plugin-usage/adding-content/item-properties/resource

![image](https://user-images.githubusercontent.com/27242001/221241143-fa17c869-2c93-4f3e-87da-d118b88cfca8.png)

https://itemsadder.devs.beer/plugin-usage/important-notes#file-and-items-names
![image](https://user-images.githubusercontent.com/27242001/221241255-700bddcd-9755-4b8e-b2fe-50669ec7cdbd.png)
