### ISSUE TITLE
Placed ia items invisible after updating server version from 1.18.2 to 1.19.2

### ISSUE THREAD

**Issue by jeffry1829** [PluginBugs/Issues-ItemsAdder#2344]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

jeffry1829#0568

### What happened?

After updating server version from 1.18.2 to 1.19.2.
All placed ia items before are gone.
I used the same texture pack, and run /iazip already.
Other behavior of ia works well. For example, I can place new ia items without problems.
But the items placed before are invisible, (e.g. transparent barrier block)

### Steps to reproduce the issue

1. Place ia items in 1.18.2
2. Update server version to 1.19.2

### Server version

This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version
Previous version: git-Paper-177 (MC: 1.19.2)

### ItemsAdder Version

3.3.1

### ProtocolLib Version

5.0.0-SNAPSHOT-b606

### LoneLibs Version

1.0.23

### LightAPI Version (optional)

bukkit-5.3.0 (build SNAPSHOT)

### LibsDisguises Version (optional)

10.0.32-SNAPSHOT

**Comment by LoneDev6** [comment]
I need to see some screenshots and if possible attach your resourcepack providing the name of the not showing items.

**Comment by jeffry1829** [comment]
For example, there was a bench 
![2023-02-15_12 22 37](https://user-images.githubusercontent.com/6897769/218929669-f728482b-21b4-4ca6-8e24-dc69669b9a41.png)
Like this bench 
![2023-02-15_12 23 20](https://user-images.githubusercontent.com/6897769/218929754-64b3fbc1-062b-4ca1-b860-1fb089c118f7.png)

This bench is in 
plugins/ItemsAdder/data/resource_pack/assets/itemsadder/models/item/acacia_wood_park_bench.json
with data:
{"parent":"itemsadder:item/template_wood_park_bench","textures":{"0":"block/acacia_planks","1":"block/black_concrete","particle":"block/acacia_planks"}}

This is just one example, as far as I can tell, all ia items placed before I remembered are invisible, for example, ia vegetable in  the item-frame, ia vending machine.
But, in NPC shops, these items are still present, no problem at all.

Thanks!

**Comment by LoneDev6** [comment]
This is strange since I don't see how this could happen.
Can you use spectator mode to see if the actual furniture invisible entity is there or not?

**Comment by jeffry1829** [comment]
> This is strange since I don't see how this could happen. Can you use spectator mode to see if the actual furniture invisible entity is there or not?

Hi, I don't get what do you mean by "use spectator mode to see"?
The furniture I placed before are now ordinary barrier blocks.
Do I have a way to see detail metadata for the barrier blocks?

Thanks for the help!

**Comment by LoneDev6** [comment]
There is no metadata in the blocks but in the entities, which seem to not exist at all, they would have been noticeable using the spectator mode.
An external plugin removed these entities for some reason or someone used /kill command.
ItemsAdder doesn't remove placed furniture between updates for any reason.
I can't really do anything to help since something deleted the placed furniture.

Have a nice day
