### ISSUE TITLE
ItemsAdder and MMOItems item tags

### ISSUE THREAD

**Issue by Pelmen1S7Avgana** [PluginBugs/Issues-ItemsAdder#2345]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

𝑃𝑒𝑙𝑚𝑒𝑛_𝑆_𝐴𝑣𝑔𝑎𝑛𝑎#5220

### What happened?

Have a problem with chat tags in items from MMOItems. Everything works fine until I trying to add GEM_STONE from MMOItems to item with tags. 
![2023-02-15_00 10 27](https://user-images.githubusercontent.com/122327637/218864949-35c25ace-1108-43bb-b42c-125bff331078.png)
![2023-02-15_00 09 10](https://user-images.githubusercontent.com/122327637/218864960-5485b1b2-8fa6-4e23-9a7e-e2d060d06cb4.png)

### Steps to reproduce the issue

1. Make item with tags and GEM_STONE feature
2. Use GEM_STONE on it
3. Tags are broken(((

### Server version

This server is running Paper version git-Paper-368 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: de5b1da)
You are 31 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-408 (MC: 1.17.1)

### ItemsAdder Version

ItemsAdder version 3.3.0b-r2
Customized Minecraft without client mods!
Website: devs.beer
Author: LoneDev

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b608
Provides read/write access to the Minecraft protocol.
Authors: dmulloy2 and comphenix

### LoneLibs Version

LoneLibs version 1.0.23
Collection of libs used by my plugins
Authors: LoneDev and others

### LightAPI Version (optional)

LightAPI version bukkit-5.3.0 (build SNAPSHOT)
Bukkit library for edit light levels
Website: https://github.com/BeYkeRYkt/LightAPI
Authors: BeYkeRYkt and other contributors in GitHub

### FULL server log

Not a log error

### Problematic items yml configuration file (optional)

```shell
#MMOItems config
LUCERNE_WARHAMMER:
  base:
    material: IRON_AXE
    name: '&fКлементúн'
    displayed-type: ':tag_hammer: :tag_save:'
    lore:
    - §fПротивокавалерийский молот
    ability:
      ability1:
        type: HEAVY_CHARGE
        mode: RIGHT_CLICK
        damage: 11.2
        cooldown: 12.0
    two-handed: true
    gem-sockets:
    - ':blue_gem:'
    attack-speed: 0.7
    attack-damage: 9.7
    critical-strike-chance: 14.3
    critical-strike-power: 21.4
    tier: RARE
    unbreakable: true
    disable-death-drop: true
```

### Screenshots/Videos (you can drag and drop files or paste links)

![2023-02-15_00 10 27](https://user-images.githubusercontent.com/122327637/218875243-abafb7a8-df83-4b88-9da0-0821c2522ef4.png)
![2023-02-15_00 09 10](https://user-images.githubusercontent.com/122327637/218875247-7f62dca8-5e49-4392-b865-d6c1ff81f612.png)

**Comment by Pelmen1S7Avgana** [comment]
%img_name% doesnt work too

**Comment by vpttyn** [comment]
use unicode
