### ISSUE TITLE
No esta hacciendo el evento de ataque.

### ISSUE THREAD

**Issue by JesusAntonioCB** [PluginBugs/Issues-ItemsAdder#2347]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

AntonioSoul15#7855

### What happened?

Es un error que por lo que experimente solo aparece cuando se tiene que ejecutar un evento de ataque.
no hace la acción y marca un montón de veces el mismo error en la consola.
En la versión anterior no pasaba funcionaba correctamente.

### Steps to reproduce the issue

1. tener un item con las propiedades de evento attack:
2. atacar a alguien.

### Server version

This server is running Paper version git-Paper-365 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 90750a6)

### ItemsAdder Version

Itemsadder version 3.3.1

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b614

### LoneLibs Version

LONELibs version 1.0.23

### LightAPI Version (optional)

LightAPI version bukkit-5.3.0 (build SNAPSHOT)

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10758179/latest.log)

### Error (optional)

```shell
[16:09:19] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to ItemsAdder v3.3.1
java.lang.StackOverflowError: null
	at ia.m.dI.a(SourceFile:53) ~[ItemsAdder_3.3.1.jar:?]
	at ia.m.dI.a(SourceFile:53) ~[ItemsAdder_3.3.1.jar:?]
	at ia.m.dI.a(SourceFile:53) ~[ItemsAdder_3.3.1.jar:?]
	at ia.m.dI.a(SourceFile:53) ~[ItemsAdder_3.3.1.jar:?]
	at ia.m.dI.a(SourceFile:53) ~[ItemsAdder_3.3.1.jar:?]
	at ia.m.dI.a(SourceFile:53) ~[ItemsAdder_3.3.1.jar:?]
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: drugs
items:
  alcohol:
    enabled: true
    display_name: "&6&lCERVEZA"
    lore:
      - "&aEfectos"
      - "&6- Velocidad"
      - "&6- Vision Nocturna"
      - "&6- Hambre"
      - "&6- Confusión"
      - "&8- Si golpeás a alguien los"
      - "&8- efectos se aplicaran a él"
    permission: item.default
    resource:
      material: HONEY_BOTTLE
      generate: true
      textures:
        - items/beer
    events:
      eat:
        potion_effect_1:
          type: SPEED
          duration: 1800
          amplifier: 1
        potion_effect_2:
          type: NIGHT_VISION
          duration: 1800
          amplifier: 1
        potion_effect_3:
          type: HUNGER
          duration: 1800
          amplifier: 1
        potion_effect_4:
          type: CONFUSION
          duration: 1800
          amplifier: 1
      attack:
        play_effect:
          name: POTION_BREAK
        play_sound:
          name: entity.splash_potion.break
          volume: 1
          pitch: 1
        target_potion_effect_1:
          type: SPEED
          duration: 1800
          amplifier: 1
        target_potion_effect_2:
          type: NIGHT_VISION
          duration: 1800
          amplifier: 1
        target_potion_effect_3:
          type: HUNGER
          duration: 1800
          amplifier: 1
        target_potion_effect_4:
          type: CONFUSION
          duration: 1800
          amplifier: 1
        decrement_amount:
          amount: 1
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/YbQNZC3YCHA

**Comment by LoneDev6** [comment]
I don't speak in spanish, write in english.
