### ISSUE TITLE
Duping bug!

### ISSUE THREAD

**Issue by ChefJisoo** [PluginBugs/Issues-ItemsAdder#2349]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Chef Jisoo#7199

### What happened?

Whenever a player uses a custom furniture placeable, it replaces the leggings in their inventory aswell as places on the ground.

### Steps to reproduce the issue

1. Wear some diamond leggings (or any other)
2. Use the /ia command to get a furniture piece
3. Place the furniture piece on the ground
4. The furniture should be placed, aswell as being in your leggings slot. Consequently you now have 2 of that furniture.

### Server version

Paper_1.18.2.Jar

### ItemsAdder Version

[ItemsAdder_3.3.1.jar]

### ProtocolLib Version

This command doesnt work, but it is the latest possible version as of 17/02/23

### LoneLibs Version

This command doesnt work, but it is the latest possible version as of 17/02/23

### FULL server log

[latest (8).log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10770054/latest.8.log)

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/rrMOUNFht7s

**Comment by Akiranya** [comment]
I can't reproduce it in my server. Can you try it again with a clean setup (with only ItemsAdder + other necessary plugins required by ItemsAdder)

Note that dupe bug should not be reported thru github issues: https://github.com/PluginBugs/Issues-ItemsAdder/security/policy

**Comment by ChefJisoo** [comment]
> I can't reproduce it in my server. Can you try it again with a clean setup (with only ItemsAdder + other necessary plugins required by ItemsAdder)
> 
> Note that dupe bug should not be reported thru github issues: https://github.com/PluginBugs/Issues-ItemsAdder/security/policy

Hi, i did see that and lonedev has removed the option to report it on his server so i did it here

**Comment by LoneDev6** [comment]
Do not report duplication issues on Github.
I updated the policy with the new link where you can post about duplication issues.
Report it on the forum.
https://forum.devs.beer/t/private-duplication-bug


Also test without any other plugin since the other user Akiranya cannot reproduce the issue, so it might be another plugin interfering (which we need to find out more about).
