### ISSUE TITLE
Shaders remove mob bones

### ISSUE THREAD

**Issue by ZConnorZ** [PluginBugs/Issues-ItemsAdder#2350]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

When "custom-entitites.emotes" is enabled, "rendertype_entity_translument" shader files added to texture pack will remove fragments from some mobs, for example, Piglin removes an ear, Allay removes a hand.

### Steps to reproduce the issue

1. Enable custom-entitites.emotes
2. Use comand /iazip.
3. Install output texturepack.
4. Check mobs: Allay and Piglin

### Server version

Current: git-Purpur-1907 (MC: 1.19.3)*

### ItemsAdder Version

3.3.1

### ProtocolLib Version

5.0.0-SNAPSHOT-b612

### LoneLibs Version

1.0.23

### LightAPI Version (optional)

no

### LibsDisguises Version (optional)

no

### FULL server log

no

### Problematic items yml configuration file (optional)

```shell
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    emotes: true #<---
    interval-rendering-packets-ticks: 1
    optimized-packets: true
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/45974097/219880126-62ca54e1-b96d-4f81-ac20-7b4994b599b0.png)

**Comment by LoneDev6** [comment]
Thanks a lot for the report, I'll try to see if I can fix this.
It might not be possible because of how the emotes work and how the game renders the entities ingame.
I'll keep you updates
