### ISSUE TITLE
Display bug

### ISSUE THREAD

**Issue by Yonox1234** [PluginBugs/Issues-ItemsAdder#2351]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Yonox#9407

### What happened?

When you are in survival and you do /ai there are ovens that are displayed

### Steps to reproduce the issue

1: put yourself in survival
2: and here it is
![bug itemadder](https://user-images.githubusercontent.com/125759515/219880740-728888cf-14eb-410a-a056-7627b916e6a2.png)

### Server version

Spigot 1.16.5

### ItemsAdder Version

Itemadder version 3.1.5

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.23

**Comment by LoneDev6** [comment]
Your pack is probably not synchronized with the configurations.
Regenerate it using /iazip and follow the hosting tutorials.
https://itemsadder.devs.beer/plugin-usage/resourcepack-hosting
This is the only reason why this could happen.
