### ISSUE TITLE
Placing custom IA block (NoteBlock) generates two blockPlaceEvent

### ISSUE THREAD

**Issue by ssomar1607** [PluginBugs/Issues-ItemsAdder#2352]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Ssomar#2000

### What happened?

When I place a custom block of IA that is in reality a NoteBlock, it produces 2 BlockPlaceEvent:
- 1 for the NoteBlock...... logic 👍🏼 
- 1 for the block where the noteblock is placed on..... why ? not logic 👎🏼 

Here it's a video https://youtu.be/ICstZ8DWXCg

### Steps to reproduce the issue

Install only ItemsAdder, and dependencies.

+ I create a simple plugin to listen the block place event:

```
public class TestPlugin extends JavaPlugin implements Listener {

    /* HIGHTEST to pass after worldguard flag */
    @EventHandler(priority = EventPriority.HIGHEST, ignoreCancelled = true)
    public void onBlockPlaceEvent(BlockPlaceEvent e) {

        Bukkit.getServer().broadcastMessage("BlockPlaceEvent cancel "+e.isCancelled());


        Player p = e.getPlayer();
        Block b = e.getBlockPlaced();
        Bukkit.getServer().broadcastMessage("block place: " + b.getType() + " against: " + e.getBlockAgainst().getType());
        Bukkit.getServer().broadcastMessage("hand place: " + e.getHand());
    }

    @Override
    public void onEnable() {

        /* Events instance part */
        this.getServer().getPluginManager().registerEvents(this, this);
    }
}
```

Place a IA Block NoteBlock

### Server version

This server is running Paper version git-Paper-381 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 42fecd0)
You are 23 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-372 (MC: 1.19.3)/ver

### ItemsAdder Version

3.3.1

### ProtocolLib Version

5.0.0.-SNAPSHOT-b614

### LoneLibs Version

1.0.23

**Comment by LoneDev6** [comment]
Will be checked, I'll let you know the cause of this and if it can be fixed

**Comment by ssomar1607** [comment]
> Will be checked, I'll let you know the cause of this and if it can be fixed

Bump, can you check this problem ?

**Comment by LoneDev6** [comment]
It's planned for 3.4.1, no need to bump
![image](https://user-images.githubusercontent.com/27242001/223162322-8115f50f-4799-46da-8130-0f40a27c9b93.png)
