### ISSUE TITLE
Inquiry for future versions

### ISSUE THREAD

**Issue by PortableGames** [PluginBugs/Issues-ItemsAdder#2354]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

You probably have a lot of work ahead of you for the next release 1.20

https://www.minecraft.net/en-us/article/minecraft-snapshot-23w06a
https://www.minecraft.net/en-us/article/minecraft-snapshot-23w07a

If it allows you to do things like this.

https://twitter.com/TruePatbox/status/1623436131449843712?t=v6u0FsjS9X0nfwUJSt9rkA&s=19

How do you plan to deal with all this?

### Is your feature request related to a problem?

.

### Describe alternatives you've considered

.

**Comment by LoneDev6** [comment]
Very cool feature and can allow me to implement some impressive features
