### ISSUE TITLE
Does ItemsAdder lag the server when loading a world on the server?

### ISSUE THREAD

**Issue by xiaozhangup** [PluginBugs/Issues-ItemsAdder#2355]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

If I have a world with a lot of IA items placed in it, I unload the world while the server is running and then load the world again. Ignoring the time it takes for the server to load the world itself, does ItemsAdder will take extra time to load it? And if so, how long would this consume approximately? Is it synchronous or asynchronous?

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

No any,I just wonder know that.

**Comment by LoneDev6** [comment]
World are not actually "loaded" by the game.
The game loads the needed chunks once requested, not the whole world.
The only thing itemsadder is loading are the custom blocks data for each loaded chunk of the world.
Without any spark or timing report I can't really tell you what is causing this.

Anyway the new upcoming update makes custom blocks region data files more lightweight and will eventually fix the issues you're having.

**Comment by xiaozhangup** [comment]
> 

I'm not actually having any problems, I'm only asking because I'm developing a project that requires loading and unloading the world while the server is running. I would like to use itemsadder, but I am worried that this will cause problems.

The new storage method you are talking about, is it PDC?

**Comment by LoneDev6** [comment]
You should not really have problems, at least with the new upcoming regions format since I'm benchmarking it and performance is very high compared to the old system.

**Comment by xiaozhangup** [comment]
> You should not really have problems, at least with the new upcoming regions format since I'm benchmarking it and performance is very high compared to the old system.

Another problem, if I am between two servers with the same Itemsadder configuration. I place IA blocks in one world on one server and then put that world on the other server to load, will those IA blocks display properly?

**Comment by xiaozhangup** [comment]
When the now regions format will came out?

**Comment by LoneDev6** [comment]
> When the now regions format will came out?

As soon as the beta testing team lets me know it has no issues


> Another problem, if I am between two servers with the same Itemsadder configuration. I place IA blocks in one world on one server and then put that world on the other server to load, will those IA blocks display properly?

yes if you use the same `storage` folder and the same resourcepack zip.
that's the `storage` folder purpose.
