### ISSUE TITLE
Armor Renders weird with Itemsadder on 1.19.3

### ISSUE THREAD

**Issue by PlumoMon** [PluginBugs/Issues-ItemsAdder#2356]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

PlumoMon#4351

### What happened?

An visual bug with armors from optifine cit they just go to the default Itemsadder file.

A temporarily fix is to set this in the config.yml but then the IA armors won't generate; 

    generate-custom-armors-textures:
      vanilla_1_17: false
      optifine: false

### Steps to reproduce the issue

Add any item in 'minecraft/textures/models/armor/'
It will replace the leather armor layer with the itemsadder default.
And the texture will not work it will show just a normal leather armor with color code

### Server version

Current: git-Purpur-1912 (MC: 1.19.3)*

### ItemsAdder Version

Itemsadder version 3.3.1

### ProtocolLib Version

ProtocolLib 5.0.0-SNAPSHOT-b612

### LoneLibs Version

Lonelibs 1.0.23

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/61025621/220450004-a4cebaf6-0123-43b9-afa0-4800e9fbf4db.png)

**Comment by LoneDev6** [comment]
Please be more clear when you report an issue, I don't understand what is not working, I only see a screenshot of an armor not rendered and I have no idea of when this was taken, when you disabled the `vanilla_1_17`, when you disabled `optifine` option, no idea.

Obviously if you disable it won't show any custom texture.
`vanilla_1_17: false`

Provide a proper preconfigured pack for me to test. I want to be able to drag and drop a contents folder and see the issue.

**Comment by LoneDev6** [comment]
This is basically a compatibility feature request with Space plugin resourcepack armors?
Last time I tested they worked fine.

Try to set this in config.yml of itemsadder and regenerate your resourcepack: `disable-overwrite-leather-armor-layers-textures: true`

**Comment by PlumoMon** [comment]
> This is basically a compatibility feature request with Space plugin resourcepack armors? Last time I tested they worked fine.
> 
> Try to set this in config.yml of itemsadder and regenerate your resourcepack: `disable-overwrite-leather-armor-layers-textures: true`

That didn't work

The only thing that worked for me is to disable every armor 'redering' from itemsadder.

Because the both renders use minecraft/textures/models/armor/leather_layer_1.png
It will take the default file from itemsadder thats leather armor.

**Comment by LoneDev6** [comment]
I have no idea sincerely, last time I checked it worked fine with Space.
They might have changed something in their plugin which breaks ItemsAdder armors.
