### ISSUE TITLE
furniture hitbox BUG

### ISSUE THREAD

**Issue by Kokolochnik** [PluginBugs/Issues-ItemsAdder#2360]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

kl1styy's#6069

### What happened?

when I want to use furniture, I set hitboxes in the config (code below), but in the game they are not displayed correctly if they are set in a certain way (screenshots below)

### Steps to reproduce the issue

1. place the furniture, make sure the hitbox is correct 2. place the furniture in a different position and see that the hitbox is not in the correct position

### Server version

This server is running Pufferfish version git-Pufferfish-46 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 5e6e1ad on HEAD)
You are running 13 versions beyond. Please update your server when possible to maintain stability, security, and receive the latest optimizations.

### ItemsAdder Version

3.3.1

### ProtocolLib Version

5.0.0-SNAPSHOT-b608

### LoneLibs Version

1.0.22

### LightAPI Version (optional)

5.3.0

### LibsDisguises Version (optional)

10.0.32

### Problematic items yml configuration file (optional)

```shell
garden_bench:
    display_name: garden_bench
    permission: 
    lore:
    - garden_bench
    resource:
      material: LEATHER_HORSE_ARMOR
      generate: false
      model_path: furniture/garden_bench
    behaviours:
      furniture:
        entity: item_frame
        light_level: 7
        solid: true
        small: true
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          height: 1
          width: 2
        sound:
          place:
            name: block.metal.fall
          break:
            name: block.metal.break
      furniture_sit:
        sit_height: 0.7
        sit_all_solid_blocks: true
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/114332828/221155386-0a8493e7-96d6-4fe8-9f43-d323b376d512.png)
![image](https://user-images.githubusercontent.com/114332828/221155733-140111a8-66e0-493b-b9ad-23d726127f01.png)

**Comment by dinobossytnew** [comment]
hitbox:
          height: 1
          width: -2
edit.

**Comment by LoneDev6** [comment]
Did you read the tutorial?
https://itemsadder.devs.beer/plugin-usage/adding-content/furniture/furniture-collisions#show-the-hitbox

**Comment by Kokolochnik** [comment]
> Did you read the tutorial? https://itemsadder.devs.beer/plugin-usage/adding-content/furniture/furniture-collisions#show-the-hitbox

yes

**Comment by Kokolochnik** [comment]
> Did you read the tutorial? https://itemsadder.devs.beer/plugin-usage/adding-content/furniture/furniture-collisions#show-the-hitbox

the hitbox changes depending on the position of the subject, this should not be so I think.
