### ISSUE TITLE
ItemsadderBlockInjector Bug!! pls help

### ISSUE THREAD

**Issue by GALLETI799** [PluginBugs/Issues-ItemsAdder#2361]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Galleti#5923

### What happened?

When i use itemsadder blocks with iris world gen it looks like note blocks please help :(

### Steps to reproduce the issue

Installed ItemsadderBlockInjector  
then i do exactly how https://itemsadder.devs.beer/compatibility-with-other-plugins/compatible/iris says
but it just shows blocks like this 

### Server version

This server is running Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)
You are running the latest version
Previous version: git-Purpur-1632 (MC: 1.18.2)

### ItemsAdder Version

Itemsadder Ver - 3.3.1
ItemsadderBlockInjector  Ver - 0.0.9

### ProtocolLib Version

5.0.0-SNAPSHOT-b612

### LoneLibs Version

1.0.23

### LightAPI Version (optional)

5.3.0

### Screenshots/Videos (you can drag and drop files or paste links)

![Captura de pantalla 2023-02-24 183603](https://user-images.githubusercontent.com/86858769/221332248-0bb2848e-d5e8-4df7-8c14-f597e89d493f.png)

**Comment by LoneDev6** [comment]
Enable log in the config.yml of the blocks injector and post the log (create a new world).
https://github.com/ItemsAdder/ItemsAdderBlocksInjector/blob/master/itemsadder-blocks-injector-core/src/main/resources/config.yml

**Comment by LoneDev6** [comment]
Note: the plugin was tested and working fine, so the issue probably is easy to fix, maybe caused by a misconfiguration or a rare case.

**Comment by GALLETI799** [comment]
I fix it thanks!!!

**Comment by LoneDev6** [comment]
Would you like to share some information on which was the issue and how did you fix?
This will be helpful for other users who might encounter the same problem.

Thanks!
