### ISSUE TITLE
WorldGuard circular loading

### ISSUE THREAD

**Issue by ipl-adm** [PluginBugs/Issues-ItemsAdder#2363]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

borgir#2716

### What happened?

I installed IA to a buyed plugin setup. When i try to start server at papermc and another forks i got an error:
https://pastebin.com/CfrZ2zed

### Steps to reproduce the issue

Install IA to SmartSurvival plugins setup. I can provide setup to DM

### ItemsAdder Version

IA 3.3.1

### ProtocolLib Version

ProtocolLib v5.0.0-SNAPSHOT-b612

### LoneLibs Version

LoneLibs v1.0.23

### LightAPI Version (optional)

not installed

**Comment by LoneDev6** [comment]
Add this to your server startup parameters.
-Dpaper.useLegacyPluginLoading=true`
Seems Paper added a useless check for circular dependencies.
