### ISSUE TITLE
"black-screen: true" doesn't work

### ISSUE THREAD

**Issue by IvanVNL** [PluginBugs/Issues-ItemsAdder#2365]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

IvanV#6270

### What happened?

When I try to enable the black-screen feature to protect my server against seeing my unloaded textures it just didn't work?

### Steps to reproduce the issue

1. Fresh minecraft server running purpur with ItemsAdder, LoneLibs and ProtocolLib
2. Fresh 1.19.3 client (no mods)
3. Join server and observe

### Server version

git-Purpur-1920 (MC: 1.19.3)

### ItemsAdder Version

ItemsAdder version 3.3.1

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b612

### LoneLibs Version

LoneLibs version 1.0.23

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10832700/latest.log)

### Screenshots/Videos (you can drag and drop files or paste links)

![2023-02-26_02 01 44](https://user-images.githubusercontent.com/61555419/221387208-c0abb4b9-dc12-407a-8f98-ff53d68ddbf1.png)

**Comment by LoneDev6** [comment]
Black screen seems to be a little unreliable on some servers.
I'll do some more tests on recent versions.
