### ISSUE TITLE
armor_stand's hitbox seem doesn't work now

### ISSUE THREAD

**Issue by xiaozhangup** [PluginBugs/Issues-ItemsAdder#2366]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

armor_stand's hitbox seem doesn't work now
but item_frame's hitbox work well

### Steps to reproduce the issue

1.Add a item that use armor_stand and set a hitbox like 1x1x1
2.try to place it and break
3.you can't break when you don't click the block under the item

https://streamable.com/09cwis

### Server version

Current: git-Purpur-1858 (MC: 1.19.2)*
Previous: git-Purpur-1870 (MC: 1.19.3)
* You are running the latest version

### ItemsAdder Version

Version: 3.3.1

### ProtocolLib Version

ProtocolLib v5.0.0-SNAPSHOT-b606
[06:33:54 INFO]: Authors: dmulloy2 and Comphenix
[06:33:54 INFO]: Issues: https://github.com/dmulloy2/ProtocolLib/issues

### LoneLibs Version

1.0.23

### FULL server log

https://mclo.gs/Ozm51j9

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: "players"

items:
  xiaozhangup:
    enabled: true
    display_name: "xiaozhangup 玩偶"
    permission: iaplayers.xiaozhangup
    resource:
      material: PAPER
      generate: false
      model_path: xiaozhangup
    behaviours:
      furniture:
        gravity: false
        fixed_rotation: false
        light: 4
        hitbox:
          length: 1
          width: 1
          height: 1
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://streamable.com/09cwis

**Comment by LoneDev6** [comment]
This is vague, please make a video about the issue.
Also use /iahitbox command to debug.

**Comment by xiaozhangup** [comment]
> This is vague, please make a video about the issue. Also use /iahitbox command to debug.

![图片](https://user-images.githubusercontent.com/68374769/221914543-a8613b33-191c-44c1-afca-3b6dcb3361d9.png)
OMG

**Comment by LoneDev6** [comment]
Use the /iadebug command and send me a screenshot.

**Comment by LoneDev6** [comment]
I think I may have found the issue! Thanks for the report
