### ISSUE TITLE
Animated titles

### ISSUE THREAD

**Issue by Arvinnnnnn** [PluginBugs/Issues-ItemsAdder#2367]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Arvinizdabest#4837

### Describe the solution you'd like

I would like to ask how this feature is used in the latest version of ItemsAdder, on Wiki I see it is old and not updated

### Is your feature request related to a problem?

I would like to ask how this feature is used in the latest version of ItemsAdder, on Wiki I see it is old and not updated

### Describe alternatives you've considered

I would like to ask how this feature is used in the latest version of ItemsAdder, on Wiki I see it is old and not updated

### Additional context

I would like to ask how this feature is used in the latest version of ItemsAdder, on Wiki I see it is old and not updated

**Comment by LoneDev6** [comment]
It works just fine.
The addon is old and uses the old folders structure, but the plugin still loads it since it has backwards compatibility.
The commands are the same, check the addon page to know how to use it. Command: `/iaplaytotemanimation`.
