### ISSUE TITLE
Implement PlaceholderAPI for text effects

### ISSUE THREAD

**Issue by DarkFort** [PluginBugs/Issues-ItemsAdder#2373]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Add placeholders for the text effect in order to use it in other plugins that don't support it, like the TAB plugin.
https://github.com/NEZNAMY/TAB/issues/834

### Is your feature request related to a problem?

Yes, TAB plugin does not see animated text

### Describe alternatives you've considered

Unfortunately there is no alternative

### Additional context

![image](https://user-images.githubusercontent.com/25278617/221436114-040d33bc-1813-4097-95b7-5f13be5ae8e4.png)

**Comment by LoneDev6** [comment]
I'll implement PlaceholderAPI support which is already handled by the TAB plugin, this will avoid useless processing. 
The placeholder will be for example `%texteffect_rw example text here%`

**Comment by LoneDev6** [comment]
It's not doable because of how text effects work. Seems PlaceholderAPI cannot allow replacing with HEX colors.
To use the text effects everywhere please read here: https://itemsadder.devs.beer/plugin-usage/text-effects-1.17+#using-text-effects-without-the-placeholders
(make sure your scoreboard plugin supports hex colors, ask to the author if not.
