### ISSUE TITLE
(API) Add ability to parse Emojis

### ISSUE THREAD

**Issue by thecenters** [PluginBugs/Issues-ItemsAdder#2374]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

centers#0420

### Describe the solution you'd like

I have a chat plugin that integrates with various other APIs. The chat makes gradient text which means a color code is inserted before each character of the message. This causes emojis to break because it can't be read by the plugin. 

I would like to see the ItemsAdder API offer a way to parse IA emojis for seamless integration.

### Is your feature request related to a problem?

N/A

### Describe alternatives you've considered

N/A

**Comment by LoneDev6** [comment]
Depends what you need to do, this is very vague.
Here the placeholder replacement API.
https://github.com/LoneDev6/API-ItemsAdder/blob/master/src/main/java/dev/lone/itemsadder/api/FontImages/FontImageWrapper.java#L42

Anyway ItemsAdder emojis are replaced on the packet level, they are not changed in the actual message.
So I don't understand what is the issue/request exactly.

**Comment by thecenters** [comment]
There is a color code that is applied before each character in the chat (see below)

![image](https://user-images.githubusercontent.com/1264853/222935387-fb7c01ba-22b0-428d-8b2d-5e0af396010c.png)

So instead of ItemsAdder seeing it as :happy: it sees it as &b:&bh&ba&bp&bp&by&b: that means ItemsAdder can't add the emoji in the chat because it can't match it.

**Comment by LoneDev6** [comment]
ItemsAdder doesn't care about color code, it should replace it despite of the color or formatting.
There is some other reason why this happens.

The plugin does the replacement on packet side, so it won't touch the real message.
For some reason it cannot catch this message.
Provide some info about your server, I have no idea about your server/plugins versions.
Mojang changed like 4 times how chat packets work between 1.16 and 1.19.
