### ISSUE TITLE
Hover for font images in /iaemoji

### ISSUE THREAD

**Issue by Andre601** [PluginBugs/Issues-ItemsAdder#2376]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Andre_601#0601

### Describe the solution you'd like

There should be a hover text for the font images in `/iaemoji` telling you the font image name to use.

### Is your feature request related to a problem?

Depending on what font images are displayed and how long the respective text is, will the `:name:` pattern be lost due to the Book GUI only having that much space available.

As an example, here is `/iaemoji` while displaying some custom font images in it:
![grafik](https://user-images.githubusercontent.com/11576465/221916827-bf2b1b43-530f-4ce4-b905-56e94154f744.png)

As you can see are the names either partially covered by the next font image, or completely gone due to the page height being too small (See last entry).

### Describe alternatives you've considered

There isn't really any good alternatives.

**Comment by LoneDev6** [comment]
You're not supposed to show custom tags into the GUI.
That gui is meant only to show emojis and icons which are usable in chat, so people can preview it easily.
It's like expecting a GUI item to be shown correctly in this GUI, not possible.

There is no proper solution for that other than showing only like 2-3 icons per page which is not ideal for usability.

**Comment by Andre601** [comment]
Would still be better, as /iaemoji is useful to preview such things rather than adding it to something (i.e. chat), zip RP, test out by tiping or smth, adjusting it and repeat...

It's also a good way to showcase it without extra work.
