### ISSUE TITLE
Itemadder does not load with the latest lightAPI on 1.19.3

### ISSUE THREAD

**Issue by RealisticThreat** [PluginBugs/Issues-ItemsAdder#2378]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

RealisticCarrot#1234

### What happened?

Itemadder does not load upon server startup due to lightAPI. Error log: https://pastebin.com/2Dqi81fQ

### Steps to reproduce the issue

1. Install the latest Itemadder
2. Install the latest lightAPI
3. Turn on compatibility mode in lightAPI config so it loads on 1.19.3

### Server version

This server is running Paper version git-Paper-426 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 08e6622)

### ItemsAdder Version

3.4.0 beta-r11

### ProtocolLib Version

5.0.0 SNAPSHOT-b614

### LoneLibs Version

1.0.23

### LightAPI Version (optional)

bukkit 5.3.0 build SNAPSHOT

**Comment by maxedrom** [comment]
enable this in configuration of lightapi  
 enable-compatibility-mode: true

**Comment by RealisticThreat** [comment]
> enable this in configuration of lightapi enable-compatibility-mode: true

I did, but it's itemadder that doesn't load upon server startup.

**Comment by LoneDev6** [comment]
I'll do some tests, probably lightapi changed something in their code between versions and it breaks itemsadder loading.

> I did, but it's itemadder that doesn't load upon server startup.

itemsadder fails to load because an unexpected error is triggered by lightapi. it's not an issue of itemsadder.

**Comment by LoneDev6** [comment]
Hello, currently I'm working on an implementation of the light code to avoid having to rely on the unstable one provided by LightAPI.
