### ISSUE TITLE
EcoItems compatibility

### ISSUE THREAD

**Issue by Exanthiax** [PluginBugs/Issues-ItemsAdder#2379]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Exanthiax#6969

### What happened?

When booting server with ItemsAdder and EcoItems, ItemsAdder fails and causes EcoItems to fail.
I am confident that it is not the fault of EcoItems/Eco as all the other Eco plugins load perfectly.

### Steps to reproduce the issue

Have ItemsAdder + Dependancies
Have EcoItems + Dependancies
Boot Server
Cry

### Server version

This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 3.4.0-beta-r11

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b614

### LoneLibs Version

LoneLibs version 1.0.23

### FULL server log

https://mclo.gs/GnLEvLg

**Comment by LoneDev6** [comment]
EcoItems is trying to load some items before ItemsAdder finished loading.
You have to ask EcoItems developers to hook into ItemsAdder API load event which is async.
ItemsAdder loads items asynchronously to avoid locking the server.

The alternative is to enable SYNC load of ItemsAdder which is not really advised to avoid slower server startup.
config.yml of ItemsAdder 
```yml
config_files:
  lang: 'en'
  dictionaries-lang: 'en'
  force-sync-loading: true ### <--- HERE
```

**Comment by Exanthiax** [comment]
Thanks for reply. I spoke with Eco and they expressed that changing the API will break other integrations with ItemsAdder and Eco. I will enable the SYNC option.

Thanks for the help.

**Comment by Exanthiax** [comment]
Hi, turned on SYNC and it hasn't made a difference.

Eco references the same thing: "Could not initialize class ia.m.I"

"[12:12:03] [Server thread/ERROR]: Error occurred while enabling ItemsAdder v3.4.0-beta-r11 (Is it up to date?)
--
1492 | java.lang.NoClassDefFoundError: Could not initialize class ia.m.I
1493 | at dev.lone.itemsadder.Main.onEnable(SourceFile:435) ~[ItemsAdder_3.4.0-beta-r11.jar:?]
1494 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
1495 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
1496 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
1497 | at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-307]
1498 | at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-307]
1499 | at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-307]
1500 | at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-307]
1501 | at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-307]
1502 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-307]
1503 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
1504 | at java.lang.Thread.run(Thread.java:833) ~[?:?]"

Thanks

**Comment by LoneDev6** [comment]
Please send eco developer this page url so we can discuss on finding a solution for that compatibility issue.

the main issue: eco is trying to access itemsadder api before it's available.
