### ISSUE TITLE
RPGHud format other problems 1.19.3

### ISSUE THREAD

**Issue by maxedrom** [PluginBugs/Issues-ItemsAdder#2386]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

All this info is in: https://forum.devs.beer/d/151-rpghud-format-problem/10

I have ins:talled RPGHuds, and for some reason there is a bad format in the text on the HUD, can you tell me how i can fix that?
Server: Papper
Version: 1.19.3
![image](https://user-images.githubusercontent.com/6577300/222919125-43d20fb1-810a-41a3-866d-eba3b1e87a5e.png)

I made a fresh install of ittemsadder and RPGHuds.
No working or showing: compas/quiver/arrow target
Problem showing money using placeholder api.
![image](https://user-images.githubusercontent.com/6577300/222919172-63527cc2-d172-4daf-898f-23e5796bbb51.png)

ollowing commands where performed:

iazip
iareload
iatexture

Still the same. No errors in logs.

Those plugins are installed:
![image](https://user-images.githubusercontent.com/6577300/222919185-6249c556-c58b-40d6-a592-31f632bbfd9a.png)

This server is running Paper version git-Paper-399 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: f2f9e8c)

Configuration of itemsadder
[config.txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/10889218/config.txt)

Configuration of rpghuds:
[config.txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/10889219/config.txt)
Remember is a fresh install without the defaultpacl

Now with the default pack installed:

https://github.com/ItemsAdder/DefaultPack/releases/tag/2.0.8

![image](https://user-images.githubusercontent.com/6577300/222919437-702295ac-3e03-4a99-bbc9-3412c32ea212.png)

Still happend the same, adding coin/money not showing overlapped. I know that i can fix the position of the coin icon using the documentation in the wiki. But in this case is the same, not showing the RPG HUDS.

I have to said that i performed the iazip, iareload, and iatexture all.

Additional: LightApi where failing at the start, not loading. To fix this i enabled the Compatibility mode to True, then Light api loaded okey.

enable-compatibility-mode: true

no errors in logs. Sorry about my english.

### Steps to reproduce the issue

All in in What happened?

### Server version

This server is running Paper version git-Paper-399 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: f2f9e8c)

You are 13 version(s) behind

### ItemsAdder Version

ItemsAdder_3.4.0-beta-r11.jar

### ProtocolLib Version

![image](https://user-images.githubusercontent.com/6577300/222919315-19135b02-8402-49a4-950f-24ed13f76612.png)

### LoneLibs Version

![image](https://user-images.githubusercontent.com/6577300/222919318-83e97a22-14c0-4cac-95e6-f275b562a867.png)

### LightAPI Version (optional)

![image](https://user-images.githubusercontent.com/6577300/222919321-d02716bb-8b3f-4f70-8615-0d0b479862ee.png)

### LibsDisguises Version (optional)

![image](https://user-images.githubusercontent.com/6577300/222919324-d8b11c49-f487-4685-a0ee-bb7710708485.png)

### FULL server log

[server-log.txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/10889210/server-log.txt)

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/6577300/222919487-046100a6-801a-4708-baf5-a2ba9cf73b3b.png)
![image](https://user-images.githubusercontent.com/6577300/222919491-f08ce07a-a918-49ac-ac8d-9e60a6f0101b.png)

![image](https://user-images.githubusercontent.com/6577300/222919494-8053ab2c-7c76-46ac-8541-c555836bdcdf.png)

Perfomed with %vault_eco_balance_formatted% :
still the same

**Comment by LoneDev6** [comment]
I already explained.
There is an issue in your Economy plugin placeholder setting.
Contact the economy plugin developer to know how to setup the `vault_eco_balance_formatted` placeholder and remove the currency indicator.

This is what you should see:
`/papi parse me %vault_eco_balance_formatted%`

![image](https://user-images.githubusercontent.com/27242001/223155785-21722f37-270c-468c-bfcd-d62ecc3b5246.png)
