### ISSUE TITLE
Fire Textures Missing

### ISSUE THREAD

**Issue by AtmosphereRGS** [PluginBugs/Issues-ItemsAdder#2387]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

After installing the two default packs as well as the amethyst gear pack my fire texture is missing. I looked on the forum and saw another person with this issue but no resolution

### Steps to reproduce the issue

Install the plugin
Install the 2 default packs
Install the amethyst items - https://www.spigotmc.org/resources/amethyst-for-itemsadder.102532/
Fire missing

### Server version

1.19.2 Paper

### ItemsAdder Version

3.4.0-beta-r11

### ProtocolLib Version

5.0.0-SNAPSHOT-b606

### LoneLibs Version

1.0.23

**Comment by LoneDev6** [comment]
- provide the forum link
- provide screenshots of the issue
