### ISSUE TITLE
Furniture glitch bug

### ISSUE THREAD

**Issue by AhmetJR** [PluginBugs/Issues-ItemsAdder#2388]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I reached a high number of players in the game, 450 500 instantly, and all the furniture was bugled
https://cdn.discordapp.com/attachments/923248222368067676/1081682934051901450/Minecraft_1.19.2_-_Multiplayer_3rd-party_Server_2023-03-05_00-01-17.mp4

### Steps to reproduce the issue

I reached a high number of players in the game, 450 500 instantly, and all the furniture was bugled

### Server version

1.19.2

### ItemsAdder Version

3.3.1

### ProtocolLib Version

5.0.0

### LoneLibs Version

1.0.23

### FULL server log

https://cdn.discordapp.com/attachments/923248222368067676/1081682934051901450/Minecraft_1.19.2_-_Multiplayer_3rd-party_Server_2023-03-05_00-01-17.mp4

### Screenshots/Videos (you can drag and drop files or paste links)

https://cdn.discordapp.com/attachments/923248222368067676/1081682934051901450/Minecraft_1.19.2_-_Multiplayer_3rd-party_Server_2023-03-05_00-01-17.mp4

**Comment by LoneDev6** [comment]
I don't think this is related to ItemsAdder at all since these are entities managed by the game itself not by the plugin.
Please do some tests:
- try to restart the server
- try to remove some plugins until the issue is fixed
- make sure to check the logs to check for errors and post them here if any is found
- check if you are running the latest build for your server version
