### ISSUE TITLE
/iaguide from the console

### ISSUE THREAD

**Issue by Wupin** [PluginBugs/Issues-ItemsAdder#2389]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Wupin#0001

### Describe the solution you'd like

I just want to use /iaguide <item> <player> from console, that's all

### Is your feature request related to a problem?

nope

### Describe alternatives you've considered

I was looking at the API, but didnt find any methods on how to get recipes, or open menus like /iaguide does.

**Comment by LoneDev6** [comment]
I will implement a new argument for the command:
`/iaguide [item name] [player]`

This will allow you to open the guide for a particular user from console.
