### ISSUE TITLE
Hello bro :)

### ISSUE THREAD

**Issue by MrJorman** [PluginBugs/Issues-ItemsAdder#2392]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

CrackedLix

### Describe the solution you'd like

After so many years, you still haven't added sounds and strength to the blocks))) handsome)

### Is your feature request related to a problem?

After so many years, you still haven't added sounds and strength to the blocks))) handsome)

### Describe alternatives you've considered

After so many years, you still haven't added sounds and strength to the blocks))) handsome)

**Comment by MrJorman** [comment]
By the way, I saw an addon for sounds, but it doesn't work, can you fix it?

**Comment by LoneDev6** [comment]
It's planned for 3.4.2, learn to search.
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1268
And 3.4.3
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1260
