### ISSUE TITLE
No Fire

### ISSUE THREAD

**Issue by xiaozhangup** [PluginBugs/Issues-ItemsAdder#2394]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Fire can't display

### Steps to reproduce the issue

https://streamable.com/43dgeu

### Server version

![图片](https://user-images.githubusercontent.com/68374769/223155179-e1522be3-cd1e-4ba7-afa7-a3e36219a647.png)

### ItemsAdder Version

![图片](https://user-images.githubusercontent.com/68374769/223155257-290072f8-22c4-4d93-a81b-7eddc65aadd0.png)

### ProtocolLib Version

![图片](https://user-images.githubusercontent.com/68374769/223155353-73654c82-12da-4aa9-895f-147ae00dd758.png)

### LoneLibs Version

![图片](https://user-images.githubusercontent.com/68374769/223155307-871d99b0-f8e1-479e-8218-420e15096d12.png)

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10899808/latest.log)

**Comment by LoneDev6** [comment]
You must run /iazip using 3.4.0c in order to apply the fix.
Thanks!
