### ISSUE TITLE
Cannot completely disable campfire module when specified

### ISSUE THREAD

**Issue by Flandreqwq** [PluginBugs/Issues-ItemsAdder#2397]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Two problems.
When I try to place campfire to replace some blocks (such as grass/snow and so on) on the ground, the place block event will be canceled. 
And I use a block right click the campfire, just want to put the block on the top of the campfire, the place block event will be canceled, too. (Also, use flint and steel cannot lit the campfire, the event will be canceled.)
I just want the campfire to be the same as the vanilla, but it seems that the functions related to campfire cannot be completely disable in the config.yml.
And this is how I set the config.yml about the campfire:

  campfire:
    unlit-on-place: false
    allow-any-item: false

### Steps to reproduce the issue

1.Put a snow(or glass) on the ground.
2.Put a campfire, just try to replace the snow(or glass).
3.The block place event will be canceled

### Server version

[12:21:49 INFO]: Current: git-Purpur-1632 (MC: 1.18.2)*
Previous: git-Paper-152 (MC: 1.18.1)

### ItemsAdder Version

[12:21:11 INFO]: ItemsAdder version 3.3.1
[12:21:11 INFO]: Customized Minecraft without client mods!
[12:21:11 INFO]: Website: devs.beer
[12:21:11 INFO]: Author: LoneDev

### ProtocolLib Version

[12:22:28 INFO]: ProtocolLib version 4.8.0-SNAPSHOT-b540
[12:22:28 INFO]: Provides read/write access to the Minecraft protocol.
[12:22:28 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[12:22:59 INFO]: LoneLibs version 1.0.23
[12:22:59 INFO]: Collection of libs used by my plugins
[12:22:59 INFO]: Authors: LoneDev and others

**Comment by LoneDev6** [comment]
The new update will completely disable this module if you set the two properties to false.
campfire:
unlit-on-place: false
allow-any-item: false
