### ISSUE TITLE
[SUGGEST] Custom Leaves

### ISSUE THREAD

**Issue by matyasvane** [PluginBugs/Issues-ItemsAdder#2399]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

SinFileX#7759

### Describe the solution you'd like

Hi, I would like LoneDev to implement and improve the code from the HMCLeaves plugin. Unfortunately, this plugin is no longer active and is the only way to use special leaves and such without problems. I think this is still missing. The plugin is not well optimized when saving leaves and worldedit doesn't work through it.

Plugin: https://github.com/HibiscusMC/HMCLeaves

### Is your feature request related to a problem?

N/A

### Describe alternatives you've considered

N/A

**Comment by LoneDev6** [comment]
Hello!
Leaves blockstates are a bit risky to be added because of how frequent the updates events are triggered.
They will make server lag.

I can make some more tests but last time I checked this feature wasn't worth implementing.

ItemsAdder already offers transparency on custom blocks by using REAL_TRANSPARENT block type.
https://itemsadder.devs.beer/plugin-usage/adding-content/block/transparent-block

**Comment by matyasvane** [comment]
@LoneDev6 So how does Origin Realms do it? They have a really large number of players

**Comment by LoneDev6** [comment]
They have a custom fork of Spigot created for their server which don't trigger some events.
It's impossible to do such customization using a plugin.
It would require me to write a custom fork for spigot.

**Comment by matyasvane** [comment]
Hey @LoneDev6 thank you for this information, but you ar really good dev - can u wrote me more info about that? What triggers u mean? if its possible, i can make for it custom fork (via any devs discords). Thank you for your time.
