### ISSUE TITLE
Skipped file. Already added as stream: assets/minecraft/models/item/killer_bunny_spawn_egg.json

### ISSUE THREAD

**Issue by Olthoo** [PluginBugs/Issues-ItemsAdder#2401]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Olthoo#0322

### What happened?

I get errors when doing iaz

### Steps to reproduce the issue

merge this pack (exemple) https://www.planetminecraft.com/texture-pack/1-13-1-16-unique-spawn-eggs/

do iaz

### Server version

Current: git-Purpur-1924 (MC: 1.19.3)*
Previous: git-Purpur-1858 (MC: 1.19.2)

### ItemsAdder Version

3.4.0b-beta

### ProtocolLib Version

5.0.0-b608

### LoneLibs Version

1.0.23

### FULL server log

https://mclogs.minestrator.com/je83Pso

**Comment by LoneDev6** [comment]
Fixed, thanks
