### ISSUE TITLE
Fabric server-side mod

### ISSUE THREAD

**Issue by PortableGames** [PluginBugs/Issues-ItemsAdder#2406]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

You should start thinking about abandoning the spigot and switching to a more modern fabric. It will be entirely preferable in the future.

### Is your feature request related to a problem?

..

### Describe alternatives you've considered

..

**Comment by LoneDev6** [comment]
This is a spigot plugin not a fabric mod, it would require a complete rewrite.
Fabric already offers plenty of customization mods, it would be not useful to have itemsadder for fabric.
