### ISSUE TITLE
Ressource Pack Merge

### ISSUE THREAD

**Issue by Trippzad** [PluginBugs/Issues-ItemsAdder#2407]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

No_RuleZz#9999

### What happened?

I merged 2 ressource packs like the guide told me but, Bedrock players can't see the pack. Do I have to do smt else?

### Steps to reproduce the issue

Just the ressource pack merge

### ItemsAdder Version

This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b598

### LoneLibs Version

LoneLibs version 1.0.23

### Error (optional)

```shell
Just no ressource pack
```

**Comment by LoneDev6** [comment]
This is not a bedrock plugin
