### ISSUE TITLE
Custom items cannot be disenchanted in grindstone.

### ISSUE THREAD

**Issue by nhanledev** [PluginBugs/Issues-ItemsAdder#2409]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I update ItemsAdder to 3.4.0c-beta and LoneLib to 1.0.23 and custom items that has enchantments cannot be disenchant in the grindstone. Vanilla items still can be disenchanted.

### Steps to reproduce the issue

1. Run ItemsAdder 3.4.0c-beta and LoneLib 1.0.23
2. Get a custom item (sword)
3. Enchant that item `/enchant @p mending`
4. Put that item into the grindstone. It doesn't work.

### ItemsAdder Version

ItemsAdder 3.4.0c-beta

### ProtocolLib Version

ProtocolLib Snapshot build 614

### LoneLibs Version

LoneLib 1.0.23

### Problematic items yml configuration file (optional)

```shell
debug_sword:
    display_name: Debug Sword
    lore:
    - '&f'
    resource:
      material: DIAMOND_SWORD
      generate: true
      textures:
      - items/debug_sword
    attribute_modifiers:
      mainhand:
        attackDamage: 10
        attackSpeed: 5.6
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/28459250/224536546-da51e438-2df1-46bb-992f-891b63316e6f.png)

![image](https://user-images.githubusercontent.com/28459250/224536555-6fdb099e-43c3-4019-aa1c-ba60c3d6997c.png)

![image](https://user-images.githubusercontent.com/28459250/224536564-8659be27-7dc2-4aee-a79c-8ff355ef53c6.png)

![image](https://user-images.githubusercontent.com/28459250/224536567-d42e8be9-df3c-4c42-80af-0a663fce6a6d.png)

**Comment by LoneDev6** [comment]
I'll work on it.

**Comment by LoneDev6** [comment]
Will be fixed in the next release
