### ISSUE TITLE
REAL_WIRE Blocks Bug When Using Water to Replace Them

### ISSUE THREAD

**Issue by Flandreqwq** [PluginBugs/Issues-ItemsAdder#2410]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

When I use a water bucket to right click a REAL_WIRE block's position, the block will be destroyed by water and drop a string. Then 
I use bucket to recover water, the REAL_WIRE block will appear again. Use dispenser to put water can also cause such problems. And when water flows on REAL_WIRE blocks, they will drop themselves instead of disappearing. This makes players can get REAL_WIRE blocks without slik touch. It seems better that if they can be configured to drop or not drop when water flows on REAL_WIRE blocks. (qwq)

### Steps to reproduce the issue

1.creat a custom block with REAL_WIRE type.
2.put the REAL_WIRE block.
3.use a water bucket to right click the REAL_WIRE block's position. (or using dispenser to put water)
4.the block will be destroyed by water and drop a string.
5.recover water by bucket.
6.the REAL_WIRE block appears again.
(The video I uploaded completely reproduced this process)

### Server version

[12:21:49 INFO]: Current: git-Purpur-1632 (MC: 1.18.2)*
Previous: git-Paper-152 (MC: 1.18.1)

### ItemsAdder Version

[12:21:11 INFO]: ItemsAdder version 3.3.1
[12:21:11 INFO]: Customized Minecraft without client mods!
[12:21:11 INFO]: Website: devs.beer
[12:21:11 INFO]: Author: LoneDev

### ProtocolLib Version

[12:22:28 INFO]: ProtocolLib version 4.8.0-SNAPSHOT-b540
[12:22:28 INFO]: Provides read/write access to the Minecraft protocol.
[12:22:28 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[12:22:59 INFO]: LoneLibs version 1.0.23
[12:22:59 INFO]: Collection of libs used by my plugins
[12:22:59 INFO]: Authors: LoneDev and others

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: vkblocks
items:
  deep_dark_rock1:
    display_name: '&f深暗小石子堆'
    permission: block.deep_dark_rock1
    resource:
      material: PAPER
      generate: false
      model_path: decoration/deep_dark_rock1
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
          break_particles: BLOCK
        cancel_drop: true
        hardness: 0
        blast_resistance: 0
        no_explosion: false
        sound:
          break:
            name: BLOCK_DEEPSLATE_BREAK
            volume: 1
            pitch: 0.8
          place:
            name: BLOCK_DEEPSLATE_PLACE
            volume: 1
            pitch: 0.8
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://user-images.githubusercontent.com/127276917/224538609-2b24f1bf-83a0-459d-bd84-cbc51fbff194.mp4

**Comment by LoneDev6** [comment]
Fixed in the upcoming update

**Comment by Flandreqwq** [comment]
Thanks！
“And when water flows on REAL_WIRE blocks, they will drop themselves instead of disappearing. This makes players can get REAL_WIRE blocks without slik touch. It seems better that if they can be configured to drop or not drop when water flows on REAL_WIRE blocks.”
Could you add this as a configuration option or just fixed it? I would appreciate it if you did. (qwq)

**Comment by LoneDev6** [comment]
Yes! Fixed
