### ISSUE TITLE
Items will still drop from the blocks that have not been destroyed by the explosion

### ISSUE THREAD

**Issue by Flandreqwq** [PluginBugs/Issues-ItemsAdder#2412]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I create a REAL_NOTE block and place some on the ground. Then I make an explosion. Some of the blocks have not been destroyed by the explosion, but they still drop items.

### Steps to reproduce the issue

1.crete a REAL_NOTE block.
2.place some block on the ground.
3.make an explosion.
4.all the blocks affected by the explosion drop items. (Including those not destroyed by the explosion)
(The video I uploaded completely reproduced this process)

### Server version

[12:21:49 INFO]: Current: git-Purpur-1632 (MC: 1.18.2)*
Previous: git-Paper-152 (MC: 1.18.1)

### ItemsAdder Version

[12:21:11 INFO]: ItemsAdder version 3.3.1
[12:21:11 INFO]: Customized Minecraft without client mods!
[12:21:11 INFO]: Website: devs.beer
[12:21:11 INFO]: Author: LoneDev

### ProtocolLib Version

[12:22:28 INFO]: ProtocolLib version 4.8.0-SNAPSHOT-b540
[12:22:28 INFO]: Provides read/write access to the Minecraft protocol.
[12:22:28 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[12:22:59 INFO]: LoneLibs version 1.0.23
[12:22:59 INFO]: Collection of libs used by my plugins
[12:22:59 INFO]: Authors: LoneDev and others

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: vkblocks
items:
  depthrock_pillar:
    display_name: '&f深渊石柱'
    permission: block.building
    resource:
      material: PAPER
      generate: true
      textures:
        - building/depthrock_pillar_top.png
        - building/depthrock_pillar.png
        - building/depthrock_pillar.png
        - building/depthrock_pillar.png
        - building/depthrock_pillar_top.png
        - building/depthrock_pillar.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: BLOCK
        break_tools_whitelist:
          - gang_p
        hardness: 3
        blast_resistance: 9
        no_explosion: false
        sound:
          break:
            name: BLOCK_STONE_BREAK
            volume: 1
            pitch: 0.8
          place:
            name: BLOCK_STONE_PLACE
            volume: 1
            pitch: 0.8
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://user-images.githubusercontent.com/127276917/224763478-b1090f75-0124-4343-be3e-a2e7a81c4dee.mp4

**Comment by LoneDev6** [comment]
Fixed! Thanks for the detailed video

**Comment by LoneDev6** [comment]
I can add you as beta tester if you share your Discord username

**Comment by Flandreqwq** [comment]
芙兰朵露·斯卡蕾特#4453

**Comment by LoneDev6** [comment]
Added!
