### ISSUE TITLE
Right click the REAL_NOTE block will consume the entire flint and steel

### ISSUE THREAD

**Issue by Flandreqwq** [PluginBugs/Issues-ItemsAdder#2413]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

When I use the flint and steel right click the REAL_NOTE block in survival mode, the whole flint and steel disappears.

### Steps to reproduce the issue

1.place a REAL_NOTE block.
2.use a flint and steel right click it in survival mode.
3.the flint and steel disappear.
(The video I uploaded completely reproduced this process)
(I accidentally found this small bug after I reported the last bug)

### Server version

[12:21:49 INFO]: Current: git-Purpur-1632 (MC: 1.18.2)*
Previous: git-Paper-152 (MC: 1.18.1)

### ItemsAdder Version

[12:21:11 INFO]: ItemsAdder version 3.3.1
[12:21:11 INFO]: Customized Minecraft without client mods!
[12:21:11 INFO]: Website: devs.beer
[12:21:11 INFO]: Author: LoneDev

### ProtocolLib Version

[12:22:28 INFO]: ProtocolLib version 4.8.0-SNAPSHOT-b540
[12:22:28 INFO]: Provides read/write access to the Minecraft protocol.
[12:22:28 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[12:22:59 INFO]: LoneLibs version 1.0.23
[12:22:59 INFO]: Collection of libs used by my plugins
[12:22:59 INFO]: Authors: LoneDev and others

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: vkblocks
items:
  depthrock_pillar:
    display_name: '&f深渊石柱'
    permission: block.building
    resource:
      material: PAPER
      generate: true
      textures:
        - building/depthrock_pillar_top.png
        - building/depthrock_pillar.png
        - building/depthrock_pillar.png
        - building/depthrock_pillar.png
        - building/depthrock_pillar_top.png
        - building/depthrock_pillar.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: BLOCK
        break_tools_whitelist:
          - gang_p
        hardness: 3
        blast_resistance: 9
        no_explosion: false
        sound:
          break:
            name: BLOCK_STONE_BREAK
            volume: 1
            pitch: 0.8
          place:
            name: BLOCK_STONE_PLACE
            volume: 1
            pitch: 0.8
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://user-images.githubusercontent.com/127276917/224772767-87be1140-4dfc-484e-b75d-32d7559e96f6.mp4

**Comment by LoneDev6** [comment]
Will be fixed, thanks
