### ISSUE TITLE
Building Error

### ISSUE THREAD

**Issue by Bootsjangles** [PluginBugs/Issues-ItemsAdder#2415]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Bootsjangles#0001

### What happened?

Some players continue to attempt to place a block. The block is never placed but used in their inventory. They must relog for the block to appear again. Does not happen at all times, only affects certain players.

### Steps to reproduce the issue

Attempting to place a block.

### Server version

Pufferfish version git-Pufferfish-60 (MC 1.19.3)

### ItemsAdder Version

3.4.oc-beta (Already tried udating, issue persisted)

### ProtocolLib Version

5.0.0-SNAPSHOT-b614

### LoneLibs Version

1.0.23

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10961458/latest.log)

### Error (optional)

```shell
https://media.discordapp.net/attachments/840269234624921632/1084539184917774436/image.png
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://media.discordapp.net/attachments/840269234624921632/1084539184917774436/image.png

**Comment by LoneDev6** [comment]
Do not post errors as screenshots please, thanks.
Also can you test using Paper instead of Pufferfish?

**Comment by LoneDev6** [comment]
Also you shared a log where the issue didn't happen, it doesn't contain the reported error in the screenshot.
Send text not images when you share an error.
