### ISSUE TITLE
`fix-glitched-blocks` not working for all chunks

### ISSUE THREAD

**Issue by Millionary** [PluginBugs/Issues-ItemsAdder#2418]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Millionary#3711

### What happened?

I went to the End and saw that the chorus plants were replaced with random REAL_TRANSPARENT blocks.

I tried with and without a datapack that changes the End generation and the issue continue to happen.

### Steps to reproduce the issue

1. Go to The End
2. Go to End Islands 1000 blocks away from spawn
3. See that the chorus plants are being replaced by random REAL_TRANSPARENT blocks

### Server version

This server is running Paper version git-Paper-448 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 155aa36)
You are running the latest version
Previous version: git-Paper-431 (MC: 1.19.3)

### ItemsAdder Version

ItemsAdder Version 3.4.0c-beta

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b612

### LoneLibs Version

LoneLibs Version 1.0.23

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10975984/latest.log)

### Screenshots/Videos (you can drag and drop files or paste links)

![2023-03-14_22 05 15](https://user-images.githubusercontent.com/105462545/225206005-b2d79be7-2bc8-4192-a63b-6818688f50a3.png)

**Comment by LoneDev6** [comment]
itemsadder should already fix these if you set these options in config.yml file:
```yml
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
```

**Comment by Millionary** [comment]
fix-glitched-blocks:
    enabled: true
    only-new-chunks: false

It's activated, but the problem persist.

**Comment by Millionary** [comment]
I don't know if this is part of the same issue but some trees are spawning with other trees leaves

![2023-03-15_13 46 47](https://user-images.githubusercontent.com/105462545/225425811-1fafb0bf-14ea-40fd-8fed-1491c8245e50.png)

**Comment by dinobossytnew** [comment]
Bug confirmed and tested Beta Tester DinoBossYT.

**Comment by dinobossytnew** [comment]
Bug confirmed and tested Beta Tester DinoBossYT. @LoneDev6

**Comment by LoneDev6** [comment]
This could be caused by another plugin, it's strange.
I tested and I cannot reproduce the issue on a normal setup.

**Comment by Millionary** [comment]
I don't know what plugin can cause trouble with this, these are my server plugins:

![image](https://user-images.githubusercontent.com/105462545/225809066-9260028f-7e21-40b6-b90b-7d1dcd8c394d.png)

**Comment by Millionary** [comment]
I will try to generate the end only with ItemsAdder on the server

**Comment by LoneDev6** [comment]
The only way to find the plugin causing this is removing them all and test.
I cannot know which plugin is the cause.

**Comment by Millionary** [comment]
I made a test server, only with ItemsAdder and the issue persist @LoneDev6 
![2023-03-20_14 51 04](https://user-images.githubusercontent.com/105462545/226463112-a87b9eba-ae79-453c-ba76-2b288c11c9ce.png)

**Comment by Millionary** [comment]
![image](https://user-images.githubusercontent.com/105462545/226463270-11304ba6-e87d-4c16-8de2-de193358941d.png)
The config it's set to true, i also delete the blockstate and model file for the chorus plant in the resourse pack and regenerate it, but it's the same.

**Comment by Millionary** [comment]
I've made 20 types of trees with items adder, and other 3 REAL_TRANSPARENT blocks
![image](https://user-images.githubusercontent.com/105462545/226466416-669da216-ec63-422c-a121-2db2fe7e51ba.png)

**Comment by LoneDev6** [comment]
I'll test again as soon as possible, thanks.
