### ISSUE TITLE
Replacement of furniture with each other occurs only once

### ISSUE THREAD

**Issue by Radmir52** [PluginBugs/Issues-ItemsAdder#2422]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

 
Testing issue #2337
The furniture is changed to another once.
After that, you can pick it up, put it back in - but the second time the replacement is no longer valid.

```info:
  namespace: myitems
items:
  stavny_oak_open:
    display_name: Ставни из дуба
    lore:
      - '&7Для окон 2✕2 блока'
      - '&7Установка в левый'
      - '&7верхний угол.'
    resource:
      material: oak_trapdoor
      generate: false
      model_path: stavny/stavny_oak_open
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: false
          ceiling: false
          walls: true
    events:
      placed_armorstand:
        interact:
         replace_properties:
           custom_model_data:
             copy_from_item: myitems:stavny_oak_close
             restorable: false
         play_sound:
           name: block.chest.close
           volume: 1
           pitch: 1
  stavny_oak_close:
    display_name: Ставни из дуба закрытые
    resource:
      material: oak_trapdoor
      generate: false
      model_path: stavny/stavny_oak_close
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: false
          ceiling: false
          walls: true
    events:
      placed_armorstand:
        interact:
         replace_properties:
           custom_model_data:
             copy_from_item: myitems:stavny_oak_open
             restorable: false
         play_sound:
           name: block.chest.open
           volume: 1
           pitch: 1
```
### Steps to reproduce the issue

1. Install furniture
2. click right mouse button
3. Make sure the furniture has been replaced
4. Press again to reverse the replacement. Here's the error, it's not happening anymore. Even if you pick up the item in inventory and put it back.

### Server version

1.19.2

### ItemsAdder Version

ItemsAdder_3.4.0c-r2

### ProtocolLib Version

5.5.0 - b606

### LoneLibs Version

1.0.23

**Comment by Radmir52** [comment]
I pasted the code above incorrectly.

`info:
  namespace: myitems
items:
  stavny_oak_open:
    display_name: Ставни из дуба
    lore:
      - '&7Для окон 2✕2 блока'
      - '&7Установка в левый'
      - '&7верхний угол.'
    resource:
      material: oak_trapdoor
      generate: false
      model_path: stavny/stavny_oak_open
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: false
          ceiling: false
          walls: true
    events:
      placed_armorstand:
        interact:
         replace_properties:
           custom_model_data:
             copy_from_item: myitems:stavny_oak_close
             restorable: false
         play_sound:
           name: block.chest.close
           volume: 1
           pitch: 1
  stavny_oak_close:
    display_name: Ставни из дуба закрытые
    resource:
      material: oak_trapdoor
      generate: false
      model_path: stavny/stavny_oak_close
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: false
          ceiling: false
          walls: true
    events:
      placed_armorstand:
        interact:
         replace_properties:
           custom_model_data:
             copy_from_item: myitems:stavny_oak_open
             restorable: false
         play_sound:
           name: block.chest.open
           volume: 1
           pitch: 1`

**Comment by Radmir52** [comment]
I pasted the code above incorrectly.

```info:
  namespace: myitems
items:
  stavny_oak_open:
    display_name: Ставни из дуба
    lore:
      - '&7Для окон 2✕2 блока'
      - '&7Установка в левый'
      - '&7верхний угол.'
    resource:
      material: oak_trapdoor
      generate: false
      model_path: stavny/stavny_oak_open
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: false
          ceiling: false
          walls: true
    events:
      placed_armorstand:
        interact:
         replace_properties:
           custom_model_data:
             copy_from_item: myitems:stavny_oak_close
             restorable: false
         play_sound:
           name: block.chest.close
           volume: 1
           pitch: 1
  stavny_oak_close:
    display_name: Ставни из дуба закрытые
    resource:
      material: oak_trapdoor
      generate: false
      model_path: stavny/stavny_oak_close
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: false
          ceiling: false
          walls: true
    events:
      placed_armorstand:
        interact:
         replace_properties:
           custom_model_data:
             copy_from_item: myitems:stavny_oak_open
             restorable: false
         play_sound:
           name: block.chest.open
           volume: 1
           pitch: 1
 ```

**Comment by Radmir52** [comment]
Addition.
The item only gets the texture of the second item. But it stays the same by ID

**Comment by LoneDev6** [comment]
You set `restorable: false`.
set it to true.
