### ISSUE TITLE
Protocollib Error

### ISSUE THREAD

**Issue by InFlames153** [PluginBugs/Issues-ItemsAdder#2423]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

protocollib plugin throws item drop issue

### Steps to reproduce the issue

It only happens when you press the Q key.

### Server version

spigot-1.19.2-R0.1-SNAPSHOT

### ItemsAdder Version

3.4.0c-r2

### ProtocolLib Version

Use build 606 for Minecraft 1.19-1.19.2

### LoneLibs Version

1.0.23

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10994723/latest.log)

**Comment by LoneDev6** [comment]
Will be checked as soon as possible.
