### ISSUE TITLE
Wobble animation when placing a block

### ISSUE THREAD

**Issue by MrJorman** [PluginBugs/Issues-ItemsAdder#2425]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

CrackedLix

### What happened?

Just watch the video and the blocks in the hot bar

### Steps to reproduce the issue

Just watch the video and the blocks in the hot bar

### Server version

This server is running Paper version git-Paper-442 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 5cc78f2)

### ItemsAdder Version

3.4.0c-r2

### ProtocolLib Version

5.0.0-b616

### LoneLibs Version

1.0.23

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/VfQIiibK5QI

**Comment by LoneDev6** [comment]
Will be checked

**Comment by LoneDev6** [comment]
Was caused by this previous fix: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2089

**Comment by MrJorman** [comment]
> Was caused by this previous fix: #2089

hm, bro, optifine custom armor no working.

**Comment by MrJorman** [comment]
```type=armor
items=leather_helmet\ leather_chestplate\ leather_leggings\ leather_boots
texture.leather_layer_1=necromium_layer_1
texture.leather_layer_1_overlay=necromium_layer_1
texture.leather_layer_2=necromium_layer_2
texture.leather_layer_2_overlay=necromium_layer_2
nbt.CustomModelData=1
weight=1```

**Comment by MrJorman** [comment]
It used to work on 1.18, but now it doesn't.
