### ISSUE TITLE
IA-Entity Despawn

### ISSUE THREAD

**Issue by DerVillion** [PluginBugs/Issues-ItemsAdder#2428]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

DerVillion#0420

### What happened?

For DerCrates plugin, we summon an entity for citizens and apply it an iaentity model.

When the chunks get unloaded, the NPCs disappear.
They later reappear with /iazip.

Everything remains functional with the crates when they comeback.

### Steps to reproduce the issue

1. summon NPC with citizens
2. apply model to NPC /iaentity citizens <id> model <model>
3. everything is fine.
4. unload chunks
5. NPCs disappear
6. /iazip makes them reappear

### Server version

This server is running Paper version git-Paper-134 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: aabf676)

Hoping this doesn't apply, since the plugin is used by other users and they are on the latest (1.19.3 at time of publishment)

### ItemsAdder Version

ItemsAdder 3.4.0c-r2

### ProtocolLib Version

Build #606 - 1.19.2
Build #616 - 1.19.3

### LoneLibs Version

LoneLibs 1.0.23

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11009666/latest.log)

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: dercrates
entities:
  legendary_crate:
    display_name: "&6Legendary Crate"
    type: ARMOR_STAND
    model_folder: entity/legendary_crate
    silent: true
    shadow: false
    can_sun_burn: false
    speed:
      movement: 0
      flying: 0
    max_health: 20
  obsessed_crate:
    display_name: "&4Obsessed Crate"
    type: ARMOR_STAND
    model_folder: entity/obsessed_crate
    silent: true
    shadow: false
    can_sun_burn: false
    speed:
      movement: 0
      flying: 0
    max_health: 20
  mythical_crate:
    display_name: "&5Mythical Crate"
    type: ARMOR_STAND
    model_folder: entity/mythical_crate
    silent: true
    shadow: false
    can_sun_burn: false
    speed:
      movement: 0
      flying: 0
    max_health: 20
  warlord_crate:
    display_name: "&4Warlord Crate"
    type: ARMOR_STAND
    model_folder: entity/warlord_crate
    silent: true
    shadow: false
    can_sun_burn: false
    speed:
      movement: 0
      flying: 0
    max_health: 20
  vote_crate:
    display_name: "&7Vote Crate"
    type: ARMOR_STAND
    model_folder: entity/vote_crate
    silent: true
    shadow: false
    can_sun_burn: false
    speed:
      movement: 0
      flying: 0
    max_health: 20
  enchanting_crate:
    display_name: "&dEnchanting Crate"
    type: ARMOR_STAND
    model_folder: entity/enchanting_crate
    silent: true
    shadow: false
    can_sun_burn: false
    speed:
      movement: 0
      flying: 0
    max_health: 20
  fancy_crate:
    display_name: "&bFancy Crate"
    type: ARMOR_STAND
    model_folder: entity/fancy_crate
    silent: true
    shadow: false
    can_sun_burn: false
    speed:
      movement: 0
      flying: 0
    max_health: 20
  random_crate:
    display_name: "&aRandom Crate"
    type: ARMOR_STAND
    model_folder: entity/random_crate
    silent: true
    shadow: false
    can_sun_burn: false
    speed:
      movement: 0
      flying: 0
    max_health: 20
  celestial_crate:
    display_name: "&fCelestial Crate"
    type: ARMOR_STAND
    model_folder: entity/celestial_crate
    silent: true
    shadow: false
    can_sun_burn: false
    speed:
      movement: 0
      flying: 0
    max_health: 20
  ancient_crate:
    display_name: "&7Ancient Crate"
    type: ARMOR_STAND
    model_folder: entity/ancient_crate
    silent: true
    shadow: false
    can_sun_burn: false
    speed:
      movement: 0
      flying: 0
    max_health: 20
  lucky_crate:
    display_name: "&6Lucky Crate"
    type: ARMOR_STAND
    model_folder: entity/lucky_crate
    silent: true
    shadow: false
    can_sun_burn: false
    speed:
      movement: 0
      flying: 0
    max_health: 20
```

### Other files, you can drag and drop them here to upload. (optional)

[DerCrates-0.8.3.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/11009672/DerCrates-0.8.3.zip)

### Screenshots/Videos (you can drag and drop files or paste links)

![2023-03-18_23 04 14](https://user-images.githubusercontent.com/95658352/226142675-e1cc6719-45cb-42d9-9f20-3b6585875d02.png)
![2023-03-18_23 04 59](https://user-images.githubusercontent.com/95658352/226142677-03fefb18-ca44-4a38-a032-56a922c3891f.png)

**Comment by LoneDev6** [comment]
Make sure you're running the latest citizens and itemsadder version.
It was tested and working fine.

Anyway since you're making a standalone plugin why not using itemsadder api to spawn custom crates?
https://github.com/LoneDev6/API-ItemsAdder/blob/master/src/main/java/dev/lone/itemsadder/api/CustomEntity.java
