### ISSUE TITLE
Wrong textures for a lot of items

### ISSUE THREAD

**Issue by marcjoancr** [PluginBugs/Issues-ItemsAdder#2430]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Twaia#0001

### What happened?

Apparently the textures of the items seem to have moved and the texture corresponding to the items does not appear, for example the "ruby" appears as "cassiterite" and vice versa, and so on with various items.

### Steps to reproduce the issue

1. Added the ItemAdder.
2. Followed the install instructions.
3. Then added RPG Huds following the install instructions (https://www.spigotmc.org/resources/addon-rpghuds-for-itemsadder.97486/).
4. After zip again and reload the problem appeared.

### Server version

`
This server is running CraftBukkit version 3670-Spigot-454acb7-bd29f41 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT)
`

### ItemsAdder Version

`ItemsAdder version 3.4.0c-r2`

### ProtocolLib Version

`ProtocolLib version 5.0.0-SNAPSHOT-b615`

### LoneLibs Version

`LoneLibs version 1.0.23`

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/14807142/226196868-40496db1-c209-4517-95b1-5e6a7621998a.png)
The item I'm highlighting is Dirt Gold Ore

![2023-03-19_18 55 36](https://user-images.githubusercontent.com/14807142/226196963-4cd40ff8-e8ca-4870-891c-c8ad84789184.png)
Those are dirt gold ore placed and coal dirt placed

![2023-03-19_18 56 50](https://user-images.githubusercontent.com/14807142/226197058-f5e2c28d-a412-4815-b39c-65d6ba9bc88d.png)
When I do `/iarecipe mcicons:icon_unlock`

![2023-03-19_18 58 56](https://user-images.githubusercontent.com/14807142/226197172-ba314807-1f2c-439a-a314-1fb531cc89ac.png)
When I do `/iaemoji `

**Comment by marcjoancr** [comment]
I tried reinstalling the plugin again without RPGHuds and the problem still there

**Comment by LoneDev6** [comment]
Regenerate your resourcepack and follow the hosting guide.
This happens if your resourcepack zip file is not synchronized with the changes on the server.

**Comment by marcjoancr** [comment]
Yup! Now I saw that lsyncd stopped tracking the generated resourcepack... I was getting mad, sorry and thanks for helping!

**Comment by LoneDev6** [comment]
No worries! I'm happy you managed to find the cause ;)
Have a nice week
