### ISSUE TITLE
Add on Interact, check if item is still held/held_offhand

### ISSUE THREAD

**Issue by BetterMobs** [PluginBugs/Issues-ItemsAdder#2439]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

pmalys#0585

### What happened?

Events like held or held_offhand still works even when i put item into item frame

### Steps to reproduce the issue

1. Create item with held event thats for example adds potion effect that is infinite(also unheld)
2. Add potion effect clear when unheld
3. Click on itemframe
4. Item is not in hand, but effect is still here

### Server version

This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version
Previous version: git-Paper-386 (MC: 1.19.3)

### ItemsAdder Version

3.3.1

### ProtocolLib Version

5.0.0-SNAPSHOT-b612

### LoneLibs Version

1.0.23

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11033777/latest.log)

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: deritems
items:
  everlasting_beef:
    display_name: "Everlasting Beef"
    resource:
      material: PAPER
      generate: false
      model_path: item/everlasting_beef
    events:
      held:
        potion_effect:
          type: SATURATION
          amplifier: 0
          duration: 9999999
      unheld:
        remove_potion_effect:
          type: SATURATION
      held_offhand:
        potion_effect:
          type: SATURATION
          amplifier: 0
          duration: 9999999
      unheld_offhand:
        remove_potion_effect:
          type: SATURATION
```

### Other files, you can drag and drop them here to upload. (optional)

https://user-images.githubusercontent.com/108685269/226743842-671bef7c-ef82-48cc-ba74-983a70e7c519.mp4

**Comment by LoneDev6** [comment]
Update to 3.4.1 and check if the issue still persists please.
Always use the latest version when reporting issues.
