### ISSUE TITLE
HEADS GLITCH - Very buggy

### ISSUE THREAD

**Issue by Distolfix** [PluginBugs/Issues-ItemsAdder#2440]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Disto#4781

### What happened?

In my server, I only have the essential plugins to verify that the problem is with ItemsAdder, specifically ItemsAdder LoneLibs Protocollib spark.

### Steps to reproduce the issue

Step-by-step explanation to replicate the bug:

1) Get a command block.

2) Give yourself a head, for example, I used: /give @p minecraft:player_head{display:{Name:"{"text":"Popcorn — 31"}"},SkullOwner:{Id:[I;296557135,-574995120,-1411967960,-1892254320],Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTQ5N2IxNDdjZmFlNTIyMDU1OTdmNzJlM2M0ZWY1MjUxMmU5Njc3MDIwZTRiNGZhNzUxMmMzYzZhY2RkOGMxIn19fQ=="}]}}} 1

Place them in a row and they will all glitch...

P.S Itemsadder also has no custom textures to verify if it was a buggy texture.

![image](https://user-images.githubusercontent.com/73421268/226904604-df4b26d2-bffb-40bc-9310-8c46ab07ce46.png)

### Server version

![image](https://user-images.githubusercontent.com/73421268/226904688-c087a70d-090b-45bf-82e8-b4ac469d3a9e.png)

Look the immage

### ItemsAdder Version

![image](https://user-images.githubusercontent.com/73421268/226904731-c9a42264-9efa-4dbb-bf57-e7cf8fe0d4e4.png)

Look the immage

### ProtocolLib Version

![image](https://user-images.githubusercontent.com/73421268/226904776-72fc0124-4159-40fd-8f24-b5cae51876ed.png)

Look the immage

### LoneLibs Version

![image](https://user-images.githubusercontent.com/73421268/226904857-0051926b-c064-433e-aa5b-cb6f6d4e5d99.png)

Look the immage

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11039884/latest.log)

Here is the logs

### Error (optional)

```shell
No
```

### Problematic items yml configuration file (optional)

```shell
No
```

### Other files, you can drag and drop them here to upload. (optional)

Pastebin of the config 

https://pastebin.com/0JVmZrAx

### Screenshots/Videos (you can drag and drop files or paste links)

This bug is with ALL HEADS. 

https://user-images.githubusercontent.com/73421268/226905993-11ca2425-e200-4c7b-83fa-706eaea7861a.mp4

**Comment by LoneDev6** [comment]
Please use the wiki.
https://itemsadder.devs.beer/faq/placed-heads-texture-glitched
