### ISSUE TITLE
Invalid >15 light value causes issues

### ISSUE THREAD

**Issue by madebygood** [PluginBugs/Issues-ItemsAdder#2443]
REDACTED

**Comment by LoneDev6** [comment]
1. Do share errors using screenshots. Share the log file or the error as text.
2. Do not report duplication bugs on Github. It's clearly noted in bold text in the issue creation page... report them on the proper place.
https://forum.devs.beer/t/private-duplication-bug

![image](https://user-images.githubusercontent.com/27242001/227168637-cfd0ef29-1ddd-4aa9-a5f3-85183fbb1ba2.png)
