### ISSUE TITLE
Emote invisibility bug

### ISSUE THREAD

**Issue by ArtemysShorts** [PluginBugs/Issues-ItemsAdder#2445]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Artemys#2762

### What happened?

I bought the ItemsAdder plugin, but when I use /emote fortinayt for example, it does this: 
https://user-images.githubusercontent.com/120270951/227214436-a2af496a-0836-41bd-aada-d104e7c04f93.mp4

The invisibility effect is flashing and I don't know why... It's not because of my resource pack, I try /emote on mc.devs.beer server with MY resource pack (I refused the server pack), and it works completely on the test server.

How can I fix this?

_(Sorry for my bad english, i'm french)_

### Steps to reproduce the issue

I just type /emote fortinayt
And then it happens

### Server version

This server is running Paper version git-Paper-399 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d4318a6 on ver/1.17.1)
You are 12 version(s) behind
Download the new version at: https://papermc.io/downloads

### ItemsAdder Version

3.4.1

### ProtocolLib Version

Protocolib 4.8.0

### LoneLibs Version

1.0.24

**Comment by LoneDev6** [comment]
Also please update your server... **You are 12 version(s) behind.**
It's clearly stated in the log you send:
```
This server is running Paper version git-Paper-399 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d4318a6 on ver/1.17.1)
You are 12 version(s) behind
```

https://papermc.io/downloads/all
