### ISSUE TITLE
RPGBank Page Limits Broken

### ISSUE THREAD

**Issue by TylBurxyz** [PluginBugs/Issues-ItemsAdder#2449]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

TylBur#4120

### What happened?

_To preface: My server is still running on 1.19.3 and has not updated plugins to 1.19.4 as of yet._

I've been having an issue with rpgbank, where for some reason it doesn't have the option to change pages.
Having discussed this briefly in the support discord with LoneDev, the following solutions have been tested:
- Check plugin config to verify max page is set correctly.
- Make sure permissions are set correctly.
- Remove all *extra* page rank permissions, which have players unlocking more pages per rank, and replace with just the one max page permission.

Both steps above were verified and no difference happened with the bug.

### Steps to reproduce the issue

Unaware of a way to reproduce unless someone else with RPGBank is encountering the same issue.

### Server version

git-Purpur-1933 (MC 1.19.3)

### ItemsAdder Version

ItemsAdder 3.4.0c-beta
RPGBank 1.0.16-r2

### ProtocolLib Version

ProtocolLib 5.0.0-SNAPSHOT-b614

### LoneLibs Version

LoneLibs 1.0.23

### FULL server log

[2023-03-24-3.log.gz](https://github.com/PluginBugs/Issues-ItemsAdder/files/11065815/2023-03-24-3.log.gz)

### Problematic items yml configuration file (optional)

```shell
lang: en
bank-gui:
  max-pages: 13
  unlock-slot-price: 500.0
  sounds:
    open-bank: CLICK
    take-item: ITEM_PICKUP
    put-item: ENTITY_CHICKEN_EGG
    deposit-money: NOTE_PLING
    deposit-exp: LEVEL_UP
    error: NOTE_BASS
    unlock-slot: ORB_PICKUP
    edit-banker: LEVEL_UP
  deposit-money-buttons:
    enabled: true
    amounts:
      '1': 1
      '2': 5
      '3': 10
      '4': 50
      '5': 100
      '6': 1000
      '7': 10000
  deposit-exp-buttons:
    enabled: true
  icons:
    money-indicator: EMERALD
    deposit-exp: EXPERIENCE_BOTTLE
    next-page: ARROW
    previous-page: SPIDER_EYE
    page-indicator: BLACK_STAINED_GLASS_PANE
    locked: RED_STAINED_GLASS_PANE
    deposit-money: YELLOW_STAINED_GLASS_PANE
    blank: LIGHT_GRAY_STAINED_GLASS_PANE
    _:
    - You can customize GUI icons. This plugin supports Minecraft materials (1.16
      names)
    - and also support ItemsAdder custom items names! :D
    - 'EXAMPLE: You can set for example money-indicator: GOLD_NUGGET or money-indicator:
      ruby'
items:
  bank-check:
    _: You can add as many thresholds as you want. It also supports ItemsAdder items.
    item-icon-threshold:
      '0': PAPER
      '150': PAPER
      '1000': PAPER
    sounds:
      receive: ITEM_PICKUP
      use: LEVEL_UP
  exp-bottle:
    _: You can add as many thresholds as you want. It also supports ItemsAdder items.
    item-icon-threshold:
      '0': EXPERIENCE_BOTTLE
      '400': EXPERIENCE_BOTTLE
      '800': EXPERIENCE_BOTTLE
    sounds:
      receive: ORB_PICKUP
      drink-1: DRINK
      drink-2: LEVEL_UP
commands-fees:
  exp:
    amount: 1
    fee: 3.03
  bank-check:
    amount: 1000
    fee: 100
deposit-fees:
  exp:
    amount: 1
    fee: 1.5
  bank-check:
    amount: 1000
    fee: 50
npc:
  silent: true
```

### Screenshots/Videos (you can drag and drop files or paste links)

![2023-03-24_15 11 39](https://user-images.githubusercontent.com/13821703/227618720-9d777c81-9b8e-4cb3-8139-9f3e7761c6d7.png)
![2023-03-24_15 11 38](https://user-images.githubusercontent.com/13821703/227618726-b398dde4-f92b-49c2-9a67-5e601bf40cbf.png)
![rb1](https://user-images.githubusercontent.com/13821703/227618754-28f04815-b07a-4d56-bfdb-39faecd7b4bd.PNG)
![rb2](https://user-images.githubusercontent.com/13821703/227618755-6061acd1-676d-42e0-8226-1ceeb43bdc76.PNG)
![rb3](https://user-images.githubusercontent.com/13821703/227618757-8ff2d149-63c6-4b5f-93f1-5c454784d4a8.PNG)
![rb4](https://user-images.githubusercontent.com/13821703/227618758-1194cb40-61d1-4bc1-ab13-ebfd5f82097b.PNG)

**Comment by LoneDev6** [comment]
Will be checked as soon as possible, thanks

**Comment by LoneDev6** [comment]
Next time use the correct Github page please.
Anyway I now recall someone had a similar issue, I cannot reproduce it tho.
I'll try again to make some tests and let you know.
Thanks for the patience.

https://github.com/PluginBugs/Issues-RPGBank/issues/12
