### ISSUE TITLE
LibsDisguises compatibility fix

### ISSUE THREAD

**Issue by robtbs** [PluginBugs/Issues-ItemsAdder#2452]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

25.03 04:07:25 [Server] ERROR Could not pass event ItemsAdderLoadDataEvent to ItemsAdder v3.4.1-r2
25.03 04:07:25 [Server] INFO java.lang.NoClassDefFoundError: me/libraryaddict/disguise/utilities/DisguiseUtilities
25.03 04:07:25 [Server] INFO at ia.m.cM.<init>(SourceFile:85) ~[ItemsAdder_3.4.1-r2 (1).jar:?]
25.03 04:07:25 [Server] INFO at ia.m.bS.a(SourceFile:164) ~[ItemsAdder_3.4.1-r2 (1).jar:?]
25.03 04:07:25 [Server] INFO at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
25.03 04:07:25 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-468]
25.03 04:07:25 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
25.03 04:07:25 [Server] INFO at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-468]
25.03 04:07:25 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-468]
25.03 04:07:25 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
25.03 04:07:25 [Server] INFO at ia.m.kR.a(SourceFile:68) ~[ItemsAdder_3.4.1-r2 (1).jar:?]
25.03 04:07:25 [Server] INFO at ia.m.I.c(SourceFile:2419) ~[ItemsAdder_3.4.1-r2 (1).jar:?]
25.03 04:07:25 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-468]
25.03 04:07:25 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-468]
25.03 04:07:25 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1482) ~[paper-1.19.4.jar:git-Paper-468]
25.03 04:07:25 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-468]
25.03 04:07:25 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1396) ~[paper-1.19.4.jar:git-Paper-468]
25.03 04:07:25 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.4.jar:git-Paper-468]
25.03 04:07:25 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.19.4.jar:git-Paper-468]
25.03 04:07:25 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
25.03 04:07:25 [Server] INFO Caused by: java.lang.ClassNotFoundException: me.libraryaddict.disguise.utilities.DisguiseUtilities
25.03 04:07:25 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
25.03 04:07:25 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
25.03 04:07:25 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
25.03 04:07:25 [Server] INFO ... 18 more

### Steps to reproduce the issue

In server start up

### Server version

Paper 468 , 1.19.4 api version 1.19.4.R0.1

### ItemsAdder Version

3.4.1-r2

### ProtocolLib Version

5.0.0 snapshot b618

### LoneLibs Version

1.0.24

**Comment by robtbs** [comment]
25.03 04:22:52 [Server] WARN [PlaceholderAPI] Failed to load expansion img. Identifier is already in use.
25.03 04:22:52 [Server] WARN [PlaceholderAPI] Failed to load expansion iaplayerstat. Identifier is already in use.
25.03 04:22:52 [Server] INFO [ItemsAdder] Reloading ItemsAdder Custom Entities Citizens NPCs
25.03 04:22:52 [Server] ERROR Could not pass event ItemsAdderLoadDataEvent to ItemsAdder v3.4.1-r2
25.03 04:22:52 [Server] INFO java.lang.NoClassDefFoundError: me/libraryaddict/disguise/utilities/DisguiseUtilities
25.03 04:22:52 [Server] INFO at ia.m.cM.<init>(SourceFile:85) ~[ItemsAdder_3.4.1-r2 (1).jar:?]
25.03 04:22:52 [Server] INFO at ia.m.bS.a(SourceFile:164) ~[ItemsAdder_3.4.1-r2 (1).jar:?]
25.03 04:22:52 [Server] INFO at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
25.03 04:22:52 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-468]
25.03 04:22:52 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
25.03 04:22:52 [Server] INFO at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-468]
25.03 04:22:52 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-468]
25.03 04:22:52 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
25.03 04:22:52 [Server] INFO at ia.m.kR.a(SourceFile:68) ~[ItemsAdder_3.4.1-r2 (1).jar:?]
25.03 04:22:52 [Server] INFO at ia.m.I.c(SourceFile:2419) ~[ItemsAdder_3.4.1-r2 (1).jar:?]
25.03 04:22:52 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-468]
25.03 04:22:52 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-468]
25.03 04:22:52 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1482) ~[paper-1.19.4.jar:git-Paper-468]
25.03 04:22:52 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-468]
25.03 04:22:52 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1396) ~[paper-1.19.4.jar:git-Paper-468]
25.03 04:22:52 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.4.jar:git-Paper-468]
25.03 04:22:52 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.19.4.jar:git-Paper-468]
25.03 04:22:52 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
25.03 04:22:52 [Server] INFO Caused by: java.lang.ClassNotFoundException: me.libraryaddict.disguise.utilities.DisguiseUtilities
25.03 04:22:52 [Server] INFO ... 18 more


this happens when i use /iareload

**Comment by LoneDev6** [comment]
Which LibsDisguises version do you have?
Is it the latest?

(note: it's not mandatory to install it to make ItemsAdder work)

**Comment by robtbs** [comment]
yeah is the latest

**Comment by robtbs** [comment]
28.03 04:00:50 [Server] ERROR Could not pass event EntityDamageByBlockEvent to ItemsAdder v3.4.1-r2
28.03 04:00:50 [Server] INFO java.lang.NoClassDefFoundError: me/libraryaddict/disguise/DisguiseAPI
28.03 04:00:50 [Server] INFO at ia.m.bS.a(SourceFile:226) ~[ItemsAdder_3.4.1-r2 (2).jar:?]
28.03 04:00:50 [Server] INFO at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
28.03 04:00:50 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-468]
28.03 04:00:50 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
28.03 04:00:50 [Server] INFO at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-468]
28.03 04:00:50 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-468]
28.03 04:00:50 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
28.03 04:00:50 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:249) ~[paper-1.19.4.jar:git-Paper-468]
28.03 04:00:50 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1059) ~[paper-1.19.4.jar:git-Paper-468]
28.03 04:00:50 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:964) ~[paper-1.19.4.jar:git-Paper-468]
28.03 04:00:50 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1190) ~[paper-1.19.4.jar:git-Paper-468]
28.03 04:00:50 [Server] INFO at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2148) ~[?:?]
28.03 04:00:50 [Server] INFO at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1383) ~[?:?]
28.03 04:00:50 [Server] INFO at net.minecraft.world.entity.animal.IronGolem.hurt(IronGolem.java:224) ~[?:?]
28.03 04:00:50 [Server] INFO at net.minecraft.world.level.block.SweetBerryBushBlock.entityInside(SweetBerryBushBlock.java:89) ~[?:?]
28.03 04:00:50 [Server] INFO at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.entityInside(BlockBehaviour.java:1069) ~[?:?]
28.03 04:00:50 [Server] INFO at net.minecraft.world.entity.Entity.checkInsideBlocks(Entity.java:1532) ~[paper-1.19.4.jar:git-Paper-468]
28.03 04:00:50 [Server] INFO at net.minecraft.world.entity.Entity.tryCheckInsideBlocks(Entity.java:1236) ~[paper-1.19.4.jar:git-Paper-468]
28.03 04:00:50 [Server] INFO at net.minecraft.world.entity.Entity.move(Entity.java:1163) ~[paper-1.19.4.jar:git-Paper-468]
28.03 04:00:50 [Server] INFO at net.minecraft.world.entity.LivingEntity.handleRelativeFrictionAndCalculateMovement(LivingEntity.java:2867) ~[?:?]
28.03 04:00:50 [Server] INFO at net.minecraft.world.entity.LivingEntity.travel(LivingEntity.java:2800) ~[?:?]
28.03 04:00:50 [Server] INFO at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3365) ~[?:?]
28.03 04:00:50 [Server] INFO at net.minecraft.world.entity.Mob.aiStep(Mob.java:670) ~[?:?]
28.03 04:00:50 [Server] INFO at net.minecraft.world.entity.animal.IronGolem.aiStep(IronGolem.java:116) ~[?:?]
28.03 04:00:50 [Server] INFO at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2975) ~[?:?]
28.03 04:00:50 [Server] INFO at net.minecraft.world.entity.Mob.tick(Mob.java:432) ~[?:?]
28.03 04:00:50 [Server] INFO at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1210) ~[?:?]
28.03 04:00:50 [Server] INFO at net.minecraft.world.level.Level.guardEntityTick(Level.java:926) ~[?:?]
28.03 04:00:50 [Server] INFO at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:731) ~[?:?]
28.03 04:00:50 [Server] INFO at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.4.jar:git-Paper-468]
28.03 04:00:50 [Server] INFO at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:711) ~[?:?]
28.03 04:00:50 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1545) ~[paper-1.19.4.jar:git-Paper-468]
28.03 04:00:50 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-468]
28.03 04:00:50 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1396) ~[paper-1.19.4.jar:git-Paper-468]
28.03 04:00:50 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.4.jar:git-Paper-468]
28.03 04:00:50 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.19.4.jar:git-Paper-468]
28.03 04:00:50 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
28.03 04:00:50 [Server] INFO Caused by: java.lang.ClassNotFoundException: me.libraryaddict.disguise.DisguiseAPI
28.03 04:00:50 [Server] INFO ... 37 more

**Comment by LoneDev6** [comment]
Please share your full log.
