### ISSUE TITLE
Event Deprecated Error

### ISSUE THREAD

**Issue by BearCaveGit** [PluginBugs/Issues-ItemsAdder#2453]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Drugs#1101

### What happened?

Hello, today I've been having some server TPS issues and noticed this error, not sure if it's the cause but it does say to notify and that performance will be affected. I've looked around for any information but can't seem to locate much, sorry if I overlooked anything.

### Steps to reproduce the issue

Notified upon server start.

### Server version

25.03 06:03:08 [Server] INFO This server is running Paper version git-Paper-378 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: ec9dba8)

### ItemsAdder Version

25.03 06:08:28 [Server] INFO ItemsAdder version 3.4.1-r2
25.03 06:08:28 [Server] INFO Customized Minecraft without client mods!

### ProtocolLib Version

25.03 06:11:29 [Server] INFO ProtocolLib version 5.0.0-SNAPSHOT-b612

### LoneLibs Version

25.03 06:12:24 [Server] INFO LoneLibs version 1.0.24

### FULL server log

  [Sat 05:20:04 INFO  io.lumine.mythic.utils.reflections.Reflections] Reflections took 9 ms to scan 1 urls, producing 9 keys and 152 values 
  [Sat 05:20:04 INFO  io.lumine.mythic.utils.reflections.Reflections] Reflections took 4 ms to scan 1 urls, producing 2 keys and 11 values 
  [Sat 05:20:04 INFO  MythicMobs] [36mLOADED
  [Sat 05:20:04 INFO  MythicMobs] Loading Packs...
  [Sat 05:20:04 INFO  MythicMobs] PACK /home/minecraft/multicraft/servers/server667948/plugins/MythicMobs/Packs/Nocsy/packinfo.yml
  [Sat 05:20:04 INFO  MythicMobs] Loading Items...
  [Sat 05:20:04 INFO  MythicMobs] Loading Item Groups...
  [Sat 05:20:04 INFO  MythicMobs] Loading Skills...
  [Sat 05:20:04 INFO  MythicMobs] Loading Drop Tables...
  [Sat 05:20:04 INFO  MythicMobs] Loading Random Spawns...
  [Sat 05:20:04 INFO  MythicMobs] Loading Spawn Blocks...
  [Sat 05:20:04 INFO  MythicMobs] [32m✓[37m Loaded 8 mobs.
  [Sat 05:20:04 INFO  MythicMobs] [32m✓[37m Loaded 0 vanilla mob overrides.
  [Sat 05:20:04 INFO  MythicMobs] [32m✓[37m Loaded 0 mob stacks.
  [Sat 05:20:04 INFO  MythicMobs] [32m✓[37m Loaded 78 skills.
  [Sat 05:20:04 INFO  MythicMobs] [32m✓[37m Loaded 0 random spawns.
  [Sat 05:20:04 INFO  MythicMobs] [32m✓[37m Loaded 0 mythic items.
  [Sat 05:20:04 INFO  MythicMobs] [32m✓[37m Loaded 0 drop tables.
  [Sat 05:20:04 INFO  MythicMobs] [32m✓[37m Loaded 0 mob spawners.
  [Sat 05:20:04 INFO  MythicMobs] MythicMobs configuration file loaded successfully.
  [Sat 05:20:04 INFO  MythicMobs] Started up bStats Metrics
  [Sat 05:20:04 INFO  MythicMobs] [32m✓ MythicMobs v5.2.1 ( build fd1d0777 ) has been successfully loaded!
  [Sat 05:20:04 INFO  AdvancedTeleport] Enabling AdvancedTeleport v5.6.6
  [Sat 05:20:04 INFO  AdvancedTeleport] Advanced Teleport is now enabling...
  [Sat 05:20:04 INFO  sleep-most] Enabling sleep-most v5.2.5
  [Sat 05:20:04 INFO  Minecraft] Hooked to PlaceholderAPI
  [Sat 05:20:04 INFO  Minecraft] Hooked to GSit
  [Sat 05:20:04 INFO  sleep-most] Hooked to GSit!
  [Sat 05:20:04 INFO  sleep-most] Hooked to PAPI!
  [Sat 05:20:04 INFO  PlaceholderAPI] Successfully registered expansion: sleepmost [5.2.5]
  [Sat 05:20:04 INFO  DiscordSRV] Enabling LuckPerms hook
  [Sat 05:20:04 INFO  TAB] Enabling TAB v3.2.4
  [Sat 05:20:04 INFO ] [TAB] Server version: 1.19.3 (v1_19_R2)
  [Sat 05:20:04 INFO ] [TAB] Loaded NMS hook in 31ms
  [Sat 05:20:04 INFO ] [TAB] Enabled in 66ms
  [Sat 05:20:04 INFO  DiscordSRV] Enabling PlaceholderAPI hook
  [Sat 05:20:04 INFO  ModelEngine] Enabling ModelEngine vR3.1.5
  [Sat 05:20:05 INFO  MythicMobs] Model Engine Compatibility Loaded.
  [Sat 05:20:05 INFO  ModelEngine] [S] Compatibility applied: MythicMobs
  [Sat 05:20:05 INFO  ModelEngine] [S] Compatibility applied: Citizens
  [Sat 05:20:05 INFO  CoreProtect] Enabling CoreProtect v21.3
  [Sat 05:20:05 INFO ] [CoreProtect] CoreProtect has been successfully enabled! 
  [Sat 05:20:05 INFO  Minecraft] [CoreProtect] Using SQLite for data storage.
  [Sat 05:20:05 INFO  Minecraft] --------------------
  [Sat 05:20:05 INFO  Minecraft] [CoreProtect] Enjoy CoreProtect? Join our Discord!
  [Sat 05:20:05 INFO  Minecraft] [CoreProtect] Discord: www.coreprotect.net/discord/
  [Sat 05:20:05 INFO  Minecraft] --------------------
  [Sat 05:20:05 INFO  OreAnnouncer] Enabling OreAnnouncer v2.8.3
  [Sat 05:20:05 INFO  Minecraft] [[32mOreAnnouncer] Initializing OreAnnouncer v2.8.3
  [Sat 05:20:05 INFO  Minecraft] [[32mOreAnnouncer] Hooked into DiscordSRV
  [Sat 05:20:05 INFO  PlaceholderAPI] Successfully registered expansion: oreannouncer [2.8.3]
  [Sat 05:20:05 INFO  Minecraft] [[32mOreAnnouncer] Hooked into PlaceholderAPI
  [Sat 05:20:05 INFO  Minecraft] [[32mOreAnnouncer] OreAnnouncer v2.8.3 enabled
  [Sat 05:20:05 INFO  Denizen] Enabling Denizen v1.2.6-SNAPSHOT (build 1783-REL)
  [Sat 05:20:05 INFO ] +> [DenizenCore] Initializing Denizen Core v1.90.2-SNAPSHOT (Build 1308), impl for Spigot v1.2.6-SNAPSHOT (build 1783-REL) 
  [Sat 05:20:05 INFO ] +> [Denizen] Running on java version: 17.0.1 
  [Sat 05:20:05 INFO ] +> [Denizen] Running on fully supported Java 17. 
  [Sat 05:20:05 INFO ] +> [Denizen] +-------------------------+ 
  [Sat 05:20:05 INFO ] +> [Denizen]  Denizen  scriptable minecraft 
  [Sat 05:20:05 INFO ] +> [Denizen]  
  [Sat 05:20:05 INFO ] +> [Denizen] by: The DenizenScript team 
  [Sat 05:20:05 INFO ] +> [Denizen] Chat with us at: https://discord.gg/Q6pZGSR 
  [Sat 05:20:05 INFO ] +> [Denizen] Or learn more at: https://denizenscript.com 
  [Sat 05:20:05 INFO ] +> [Denizen] version: 1.2.6-SNAPSHOT (build 1783-REL) 
  [Sat 05:20:05 INFO ] +> [Denizen] +-------------------------+ 
  [Sat 05:20:06 INFO ] +> [TriggerRegistry] Loaded 4 core triggers 
  [Sat 05:20:06 INFO ] +> [PaperModule] Loading Paper support module... 
  [Sat 05:20:06 INFO ] +> [Denizen] Loaded 148 core commands and 28 core object types, at 1068ms from start. 
  [Sat 05:20:06 INFO ] +> [ScriptHelper] No scripts in /plugins/Denizen/scripts/ to load! 
  [Sat 05:20:06 INFO ] +> [ScriptRegistry] Loading 0 script files... 
  [Sat 05:20:06 INFO ] +> [DenizenCore] Scripts loaded! File load took 2ms, processing 8ms. 
  [Sat 05:20:06 INFO ] +> [Denizen] Final full init took 1140ms. 
  [Sat 05:20:06 INFO  MCPets] Enabling MCPets v3.0.2
  [Sat 05:20:06 INFO  Minecraft] [MCPets] : Language file reloaded.
  [Sat 05:20:06 INFO  Minecraft] [MCPets] : Blacklist file reloaded.
  [Sat 05:20:06 INFO ] Loading pets... 
  [Sat 05:20:06 INFO ]   - crow_pet loaded succesfully.
  [Sat 05:20:06 INFO ]   - Utahraptor loaded succesfully.
  [Sat 05:20:06 INFO ]   - Nocsy_Cat-Halloween loaded succesfully.
  [Sat 05:20:06 INFO ]   - Otter loaded succesfully.
  [Sat 05:20:06 INFO ]   - TofNocsy_Capybara loaded succesfully.
  [Sat 05:20:06 INFO ]   - Nocsy_Corgi loaded succesfully.
  [Sat 05:20:06 INFO  Minecraft] [MCPets] : 6 pets registered successfully !
  [Sat 05:20:06 INFO  Minecraft] [MCPets] : 0 categories registered successfully !
! [Sat 05:20:06 WARN  MCPets] Loaded class com.alessiodp.oreannouncer.libs.h2.Driver from OreAnnouncer v2.8.3 which is not a depend or softdepend of this plugin.
- [Sat 05:20:06 ERROR MCPets] Could not reach SQL database. Please configure your database parameters.
- [Sat 05:20:06 ERROR MCPets] [Database] Can't initialize MySQL.
- [Sat 05:20:06 ERROR MCPets] [Database] Will be using YAML support instead.
  [Sat 05:20:06 INFO  Minecraft] -=-=-=-= MCPets loaded =-=-=-=-
  [Sat 05:20:06 INFO  Minecraft]       Plugin made by Nocsy
  [Sat 05:20:06 INFO  Minecraft] -=-=-=-= -=-=-=-=-=-=- =-=-=-=-
  [Sat 05:20:06 INFO  Minecraft] -=- Launching Flags -=-
  [Sat 05:20:06 INFO  Minecraft] 0 flags launched.
  [Sat 05:20:06 INFO  CustomVoting] Enabling CustomVoting v10.0.0
  [Sat 05:20:06 INFO ] [CustomVoting] 
  [Sat 05:20:06 INFO ] [CustomVoting]                       CustomVoting
  [Sat 05:20:06 INFO ] [CustomVoting] >----------------------------------------------------
  [Sat 05:20:06 INFO ] [CustomVoting]                      By sd_master92
  [Sat 05:20:06 INFO ] [CustomVoting] 
  [Sat 05:20:06 INFO ] [CustomVoting] | checking for updates
  [Sat 05:20:06 INFO ] [CustomVoting] |
  [Sat 05:20:07 INFO ] [CustomVoting] |___up to date!
  [Sat 05:20:07 INFO ] [CustomVoting] 
  [Sat 05:20:07 INFO ] [CustomVoting] | checking for Votifier
  [Sat 05:20:07 INFO ] [CustomVoting] |
  [Sat 05:20:07 INFO ] [CustomVoting] |___dependency 'Votifier' found!
  [Sat 05:20:07 INFO ] [CustomVoting] 
  [Sat 05:20:07 INFO ] [CustomVoting] | checking Minecraft version
  [Sat 05:20:07 INFO ] [CustomVoting] |
  [Sat 05:20:07 INFO ] [CustomVoting] |___up to date!
  [Sat 05:20:07 INFO ] [CustomVoting] 
  [Sat 05:20:07 INFO ] [CustomVoting] | checking for Vault
  [Sat 05:20:07 INFO ] [CustomVoting] |
  [Sat 05:20:07 INFO ] [CustomVoting] |___Vault found
  [Sat 05:20:07 INFO ] [CustomVoting] 
  [Sat 05:20:07 INFO ] [CustomVoting] | checking for economy hook
  [Sat 05:20:07 INFO ] [CustomVoting] |
  [Sat 05:20:07 INFO ] [CustomVoting] |___economy hook not found
  [Sat 05:20:07 INFO ] [CustomVoting] 
  [Sat 05:20:07 INFO ] [CustomVoting] | checking for permission hook
  [Sat 05:20:07 INFO ] [CustomVoting] |
  [Sat 05:20:07 INFO ] [CustomVoting] |___successfully hooked into 'LuckPerms'
  [Sat 05:20:07 INFO ] [CustomVoting] 
  [Sat 05:20:07 INFO ] [CustomVoting] | checking for PlaceholderAPI hook
  [Sat 05:20:07 INFO ] [CustomVoting] |
  [Sat 05:20:07 INFO  PlaceholderAPI] Successfully registered expansion: CV [10.0.0]
  [Sat 05:20:07 INFO ] [CustomVoting] |___successfully hooked into PlaceholderAPI
  [Sat 05:20:07 INFO ] [CustomVoting] 
  [Sat 05:20:07 INFO ] [CustomVoting] | checking for Citizens hook
  [Sat 05:20:07 INFO ] [CustomVoting] |
  [Sat 05:20:07 INFO ] [CustomVoting] |___successfully hooked into Citizens
  [Sat 05:20:07 INFO ] [CustomVoting] 
  [Sat 05:20:07 INFO ] [CustomVoting] | connecting to database
  [Sat 05:20:07 INFO ] [CustomVoting] |
  [Sat 05:20:07 INFO ] [CustomVoting] |___database is disabled in the config
  [Sat 05:20:07 INFO ] [CustomVoting] 
  [Sat 05:20:07 INFO ] [CustomVoting] | caching player data
  [Sat 05:20:07 INFO ] [CustomVoting] |
  [Sat 05:20:07 INFO ] [CustomVoting] |___finished caching in 0s
  [Sat 05:20:07 INFO ] [CustomVoting] 
  [Sat 05:20:07 INFO ] [CustomVoting] v10.0.0 has been enabled.
  [Sat 05:20:07 INFO ] [CustomVoting] 
  [Sat 05:20:07 INFO ] [CustomVoting] >----------------------------------------------------
  [Sat 05:20:07 INFO  ItemsAdder] Enabling ItemsAdder v3.4.1-r2
  [Sat 05:20:07 INFO  NBTAPI] [NBTAPI] Found Spigot: v1_19_R2! Trying to find NMS support
  [Sat 05:20:07 INFO  NBTAPI] [NBTAPI] NMS support 'MC1_19_R2' loaded!
  [Sat 05:20:07 INFO  NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
  [Sat 05:20:07 INFO  Minecraft] [ItemsAdder] 
  ___  ___        __        __   __   ___  __      ItemsAdder 3.4.1-r2
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.24
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Paper git-Paper-378 (MC: 1.19.3)
                                               
! [Sat 05:20:07 WARN  ItemsAdder] "ItemsAdder v3.4.1-r2" has registered a listener for com.destroystokyo.paper.event.inventory.PrepareGrindstoneEvent on method "private void ia.m.fE.a(org.bukkit.event.inventory.PrepareGrindstoneEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [LoneDev].
  [Sat 05:20:07 INFO  Minecraft] [ItemsAdder] Registered Citizens NPC Trait: customentity
  [Sat 05:20:07 INFO  VotingPlugin] Enabling VotingPlugin v6.11.3
  [Sat 05:20:08 INFO  VotingPlugin] Giving VotingPlugin.Player permission by default, can be disabled in the config
  [Sat 05:20:08 INFO  VotingPlugin] Enabled VotingPlugin 6.11.3
  [Sat 05:20:09 INFO  PlaceholderAPI] Placeholder expansion registration initializing...
  [Sat 05:20:09 INFO  Server] Running delayed init tasks
  [Sat 05:20:09 INFO  PlaceholderAPI] Successfully registered expansion: discordsrv [1.26.2]
  [Sat 05:20:09 INFO  Minecraft] [CoreProtect] WorldEdit logging successfully initialized.
  [Sat 05:20:09 INFO  Minecraft] [ItemsAdder] [Pack] Extracting internal contents from .jar
  [Sat 05:20:09 INFO  Minecraft] [ItemsAdder] [Pack] DONE extracting internal contents from .jar
  [Sat 05:20:09 INFO ] [ImageFrame] Loading ImageMap ID 0
  [Sat 05:20:09 INFO  ModelEngine] [A] 
  [Sat 05:20:09 INFO  ModelEngine] [A] [1m[36m[Importing models]
  [Sat 05:20:09 INFO  ModelEngine] [A] 
  [Sat 05:20:09 INFO  ModelEngine] [A] [36mImporting md_crow.bbmodel.
  [Sat 05:20:09 INFO  Minecraft] [ItemsAdder] [License] Spigot product licensed to: jeszabear (1727767)
 
  [Sat 05:20:09 INFO  ModelEngine] [A] 
  [Sat 05:20:09 INFO  ModelEngine] [A] [36mImporting nocsy_corgi.bbmodel.
  [Sat 05:20:09 INFO  Vault] Checking for Updates ... 
  [Sat 05:20:09 INFO  ModelEngine] [A] 
  [Sat 05:20:09 INFO  ModelEngine] [A] [36mImporting nocsy_magic_cat.bbmodel.
  [Sat 05:20:09 INFO  Vault] No new version available
  [Sat 05:20:09 INFO  DiscordSRV] Cleared all pre-existing slash commands in 1/1 guilds (0 cancelled)
! [Sat 05:20:09 WARN  PlaceholderAPI] Loaded class net.milkbowl.vault.Vault from Vault v1.7.3-b131 which is not a depend or softdepend of this plugin.
  [Sat 05:20:09 INFO  ModelEngine] [A] 
  [Sat 05:20:09 INFO  ModelEngine] [A] [36mImporting nocsy_otter_v2.bbmodel.
  [Sat 05:20:09 INFO  ModelEngine] [A] 
  [Sat 05:20:09 INFO  ModelEngine] [A] [36mImporting toffy_capybara.bbmodel.
  [Sat 05:20:09 INFO  ModelEngine] [A] 
  [Sat 05:20:09 INFO  ModelEngine] [A] [36mImporting toffy_toy_bone.bbmodel.
  [Sat 05:20:09 INFO  ModelEngine] [A] 
  [Sat 05:20:09 INFO  ModelEngine] [A] [36mImporting toffy_yarn.bbmodel.
  [Sat 05:20:09 INFO  ModelEngine] [A] 
  [Sat 05:20:09 INFO  ModelEngine] [A] [36mImporting utahraptor.bbmodel.
  [Sat 05:20:09 INFO  ModelEngine] [A] 
  [Sat 05:20:09 INFO  ModelEngine] [A] [1m[35m[Generating assets]
  [Sat 05:20:09 INFO  ModelEngine] [A] 
  [Sat 05:20:09 INFO  ModelEngine] [A] [35mGenerating md_crow.
  [Sat 05:20:09 INFO  AdvancedTeleport] Plugin is up to date!
  [Sat 05:20:09 INFO  ModelEngine] [A] 
  [Sat 05:20:09 INFO  ModelEngine] [A] [35mGenerating nocsy_corgi.
  [Sat 05:20:09 INFO  ModelEngine] [A] 
  [Sat 05:20:09 INFO  ModelEngine] [A] [35mGenerating nocsy_magic_cat.
  [Sat 05:20:09 INFO  ModelEngine] [A] 
  [Sat 05:20:09 INFO  ModelEngine] [A] [35mGenerating nocsy_otter_v2.
  [Sat 05:20:09 INFO  ModelEngine] [A] 
  [Sat 05:20:09 INFO  ModelEngine] [A] [35mGenerating toffy_capybara.
  [Sat 05:20:09 INFO  ModelEngine] [A] 
  [Sat 05:20:09 INFO  ModelEngine] [A] [35mGenerating toffy_toy_bone.
  [Sat 05:20:09 INFO  ModelEngine] [A] 
  [Sat 05:20:09 INFO  ModelEngine] [A] [35mGenerating toffy_yarn.
  [Sat 05:20:09 INFO  ModelEngine] [A] 
  [Sat 05:20:09 INFO  ModelEngine] [A] [35mGenerating utahraptor.
  [Sat 05:20:10 INFO  ModelEngine] [A] 
  [Sat 05:20:10 INFO  ModelEngine] [A] Resource pack zipped.
  [Sat 05:20:10 INFO  Server/LoginListener] UUID of player AsixnKid is 87405c07-f5a7-4470-80a9-5b9785d6899a
  [Sat 05:20:10 INFO  HeadDatabase] Successfully loaded 51600 heads!
  [Sat 05:20:10 INFO  HeadDatabase] Successfully loaded 18 featured tags!
  [Sat 05:20:11 INFO  Minecraft] [Citizens] Loaded 32 NPCs.
  [Sat 05:20:11 INFO ] +> [ScriptEvent] Processed 0 script event paths. 
  [Sat 05:20:11 INFO ] +> [Denizen] +-------------------------+ 
  [Sat 05:20:11 INFO  Server/LoginListener] UUID of player DTWalrus is a57986db-5e97-4ea5-bdc1-3c5e004f6057
  [Sat 05:20:11 INFO ] +> [Denizen] Denizen fully loaded at: 2023/03/25 05:20:05 
  [Sat 05:20:11 INFO  Server] Done (32.663s)! For help, type "help"
  [Sat 05:20:11 INFO  Minecraft] Timings Reset
  [Sat 05:20:11 INFO  Minecraft] [ItemsAdder] Loaded 7 items
  [Sat 05:20:11 INFO  Minecraft] [ItemsAdder] Used 0/188 REAL block IDs
  [Sat 05:20:11 INFO  Minecraft] [ItemsAdder] Used 29/750 REAL_NOTE block IDs
  [Sat 05:20:11 INFO  Minecraft] [ItemsAdder] Used 0/63 REAL_TRANSPARENT block IDs
  [Sat 05:20:11 INFO  Minecraft] [ItemsAdder] Used 0/127 REAL_WIRE block IDs
  [Sat 05:20:11 INFO  Minecraft] [ItemsAdder] Used 0/14 FIRE block IDs
  [Sat 05:20:11 INFO  Minecraft] [ItemsAdder] Used 591/6608 font_images
  [Sat 05:20:11 INFO ] [ImageFrame] Loading ImageMap ID 1
  [Sat 05:20:11 INFO ] [ImageFrame] Loading ImageMap ID 2
  [Sat 05:20:11 INFO  Minecraft] [ItemsAdder] [Init] Loaded 1 categories
  [Sat 05:20:11 INFO  Minecraft] [ItemsAdder] [Init] Loaded successfully.
  [Sat 05:20:11 INFO  Server/LoginListener] com.mojang.authlib.GameProfile@10756486[id=<null>,name=Reflex_MC,properties={},legacy=false] (/removed) lost connection: Disconnected
  [Sat 05:20:11 INFO  Server/LoginListener] com.mojang.authlib.GameProfile@12e4534[id=<null>,name=Taymwun,properties={},legacy=false] (/removed) lost connection: Disconnected
  [Sat 05:20:11 INFO  Server] AsixnKid joined the game
  [Sat 05:20:12 INFO  Server/PlayerList] logged in with entity id 168 at ([TheBearCave]246.30000001192093, 52.0, -827.317940856884)
  [Sat 05:20:12 INFO  Server] DTWalrus joined the game
  [Sat 05:20:12 INFO  Server/PlayerList] logged in with entity id 169 at ([TheBearCave]1266.5, 55.0, -691.5)
  [Sat 05:20:12 INFO ] [ImageFrame] Loading ImageMap ID 3
  [Sat 05:20:12 INFO  PlaceholderAPI] Successfully registered expansion: img [1.0.1]
  [Sat 05:20:12 INFO  PlaceholderAPI] Successfully registered expansion: iaplayerstat [1.0.1]
  [Sat 05:20:12 INFO  Server/LoginListener] com.mojang.authlib.GameProfile@35b[id=<null>,name=Jesza,properties={},legacy=false] (/removed) lost connection: Disconnected
  [Sat 05:20:12 INFO  Server/LoginListener] UUID of player victricemque is 7ce7ead6-3911-465a-8ed3-fdf20b9e3dd7
  [Sat 05:20:12 INFO  Server] victricemque joined the game
  [Sat 05:20:12 INFO  Server/PlayerList] victricemque[/removed] logged in with entity id 174 at ([TheBearCave_nether]-65.17885006617556, 77.0, -104.41228585219439)
  [Sat 05:20:12 INFO ] [ImageFrame] Data loading completed! Loaded 4 ImageMaps!
! [Sat 05:20:12 WARN  VotingPlugin] Failed to hook into vault economy
  [Sat 05:20:12 INFO  VotingPlugin] Hooked into vault permissions
  [Sat 05:20:13 INFO  VotingPlugin] VotingPlugin is up to date! Version: 6.11.3
  [Sat 05:20:14 INFO  PlaceholderAPI] Successfully registered expansion: player [2.0.3]
 
! [Sat 05:20:14 WARN  PlaceholderAPI] Loaded class net.buycraft.plugin.bukkit.BuycraftPlugin from BuycraftX v12.0.8 which is not a depend or softdepend of this plugin.
  [Sat 05:20:14 INFO  BuycraftAPI] Successfully connected to bstats
  [Sat 05:20:14 INFO  BuycraftAPI] Successfully hooked into Vault for BuyCraftAPI v4.1
  [Sat 05:20:14 INFO  BuycraftAPI] Loading API Tasks...
  [Sat 05:20:14 INFO  PlaceholderAPI] Successfully registered expansion: buycraftAPI [4.1]
  [Sat 05:20:14 INFO  PlaceholderAPI] Successfully registered expansion: vault [1.7.1]
  [Sat 05:20:14 INFO  PlaceholderAPI] Successfully registered expansion: server [2.6.1]
! [Sat 05:20:14 WARN  PlaceholderAPI] Loaded class com.bencodez.votingplugin.VotingPluginMain from VotingPlugin v6.11.3 which is not a depend or softdepend of this plugin.
  [Sat 05:20:14 INFO  PlaceholderAPI] Successfully registered expansion: votingplugin [1.5]
  [Sat 05:20:14 INFO  PlaceholderAPI] Successfully registered expansion: statistic [2.0.1]
! [Sat 05:20:14 WARN  PlaceholderAPI] Loaded class net.luckperms.api.LuckPerms from LuckPerms v5.4.58 which is not a depend or softdepend of this plugin.
  [Sat 05:20:14 INFO  PlaceholderAPI] Successfully registered expansion: luckperms [5.4-R2]
  [Sat 05:20:14 INFO ] 7 placeholder hook(s) registered! 3 placeholder hook(s) have an update available.
  [Sat 05:20:14 INFO  BuycraftAPI] Successfully loaded payments
! [Sat 05:20:15 WARN  Server] Can't keep up! Is the server overloaded? Running 5020ms or 100 ticks behind
  [Sat 05:20:19 INFO  Server/LoginListener] UUID of player bigbear8899 is 180e9d36-3c52-43cd-a995-9a42cac65bb2
  [Sat 05:20:19 INFO  Server] bigbear8899 joined the game
  [Sat 05:20:19 INFO  Server/PlayerList] bigbear8899[/removed] logged in with entity id 1189 at ([TheBearCave]-3155.2214089075246, 76.0, -2450.009151425011)
 
  [Sat 05:20:22 INFO  Minecraft] [ItemsAdder] [Pack] Resourcepack URL is valid (auto-external-host), LastEdit: 2023-03-25_05-20. Url: http://resourcepack.host/dl/46cqj605B595EA6N6MMbn0IYvj07yQ0S/pack.zip
  [Sat 05:20:37 INFO  Server/LoginListener] UUID of player Reflex_MC is 020dc9af-7eac-4966-84a6-0f8dcf33f72e
  [Sat 05:20:37 INFO  Server] Reflex_MC joined the game
  [Sat 05:20:37 INFO  Server/PlayerList] Reflex_MC[/removed] logged in with entity id 3130 at ([TheBearCave]-45.35705878088384, -4.875686897951768, -1843.3814842707627)
  [Sat 05:20:46 INFO  Server] Reflex_MC was blown up by Creeper
  [Sat 05:20:53 INFO  Server/LoginListener] UUID of player Frndlyy is 525002ba-2776-463a-936a-582d1763dbed
  [Sat 05:20:53 INFO  Server] Frndlyy joined the game
  [Sat 05:20:53 INFO  Server/PlayerList] Frndlyy[/removed] logged in with entity id 4777 at ([TheBearCave]182.69999998807907, 31.0, -28.69999998807907)
  [Sat 05:20:55 INFO  Server/LoginListener] UUID of player SuperMegaIV_ is fd5d9631-0444-40d6-87e0-9f7c295f2a27
  [Sat 05:20:55 INFO  Server] SuperMegaIV_ joined the game
  [Sat 05:20:55 INFO  Server/PlayerList] SuperMegaIV_[/removed] logged in with entity id 5198 at ([TheBearCave]-86.69999998807907, -5.0, -1837.699999988079)
  [Sat 05:20:57 INFO  Server/LoginListener] UUID of player dandymcgee is e67dccc9-37b4-4b3f-b6e8-6a6d2af7bcbe
  [Sat 05:20:57 INFO  Server] dandymcgee joined the game
  [Sat 05:20:57 INFO  Server/PlayerList] dandymcgee[/removed] logged in with entity id 5648 at ([TheBearCave]1836.699999988079, 1.0, 4397.848991954735)
! [Sat 05:20:57 WARN  Server] Can't keep up! Is the server overloaded? Running 12243ms or 244 ticks behind
! [Sat 05:20:58 WARN  MessageOverHead] Loaded class dev.lone.itemsadder.api.FontImages.FontImageWrapper from ItemsAdder v3.4.1-r2 which is not a depend or softdepend of this plugin.
  [Sat 05:20:58 INFO  Server] bigbear8899 : LOL

### Error (optional)

```shell
[Sat 05:20:07 INFO  ItemsAdder] Enabling ItemsAdder v3.4.1-r2
  [Sat 05:20:07 INFO  NBTAPI] [NBTAPI] Found Spigot: v1_19_R2! Trying to find NMS support
  [Sat 05:20:07 INFO  NBTAPI] [NBTAPI] NMS support 'MC1_19_R2' loaded!
  [Sat 05:20:07 INFO  NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
  [Sat 05:20:07 INFO  Minecraft] [ItemsAdder] 
  ___  ___        __        __   __   ___  __      ItemsAdder 3.4.1-r2
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.24
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Paper git-Paper-378 (MC: 1.19.3)
                                               
! [Sat 05:20:07 WARN  ItemsAdder] "ItemsAdder v3.4.1-r2" has registered a listener for com.destroystokyo.paper.event.inventory.PrepareGrindstoneEvent on method "private void ia.m.fE.a(org.bukkit.event.inventory.PrepareGrindstoneEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [LoneDev].
  [Sat 05:20:07 INFO  Minecraft] [ItemsAdder] Registered Citizens NPC Trait: customentity
```

### Other files, you can drag and drop them here to upload. (optional)

![image](https://user-images.githubusercontent.com/128884512/227701310-50a2a069-a57d-431c-9610-243c22f0b3fe.png)

Also this was an error received earlier, not sure if related but currently there are no issues with any textures / resource pack loading.

**Comment by LoneDev6** [comment]
> ! [Sat 05:20:07 WARN ItemsAdder] "ItemsAdder v3.4.1-r2" has registered a listener for com.destroystokyo.paper.event.inventory.PrepareGrindstoneEvent on method "private void ia.m.fE.a(org.bukkit.event.inventory.PrepareGrindstoneEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [LoneDev].

The error is just a Paper bug. I reported it to them and they fixed it in the latest Paper update.
https://github.com/PaperMC/Paper/issues/9035

This has nothing to do with TPS drops.
