### ISSUE TITLE
HUD not working with new version

### ISSUE THREAD

**Issue by Maxlego08** [PluginBugs/Issues-ItemsAdder#2454]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Maxlego08#2021

### What happened?

In the new version of ItemAdder the HUD does not work properly anymore. You can see the before and after pictures.

Before: https://prnt.sc/GH8YXrU0TARv
After: https://prnt.sc/Kso47STsLVZN

### Steps to reproduce the issue

We use a custom HUD with code based on RpgHUD.

### Server version

Current: git-Purpur-1632 (MC: 1.18.2)*
* You are running the latest version

### ItemsAdder Version

3.4.1

### ProtocolLib Version

5.0.0-SNAPSHOT-b612

### LoneLibs Version

1.0.24

### FULL server log

No logs or errors.

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: w_icons
huds:

  money:
    enabled: true
    show:
      auto: false
    type: CUSTOM

  money_gold:
    enabled: true
    show:
      auto: false
    type: CUSTOM


  team_hud:
    enabled: true
    show:
      auto: false
      creative: true
    type: FRAMES
    x_position_pixels: -42
    value:
      player_stat_name: team
      start: 0
      min: 0
      max: 12
    images:
      frames:
      - w_icons:transp
      - w_icons:bs_bleu #bleu float 1
      - w_icons:bs_rouge #rouge float 2
      - w_icons:blue_team #bw float 3
      - w_icons:lime_team #bw float 4 
      - w_icons:red_team #bw float 5
      - w_icons:team_cyan #bw float 6 
      - w_icons:team_jaune #bw float 7
      - w_icons:team_orange #bw float 8 
      - w_icons:team_rose #bw float 9 
      - w_icons:team_violet #bw float 10  
      - w_icons:passe #bw float 11 
      - w_icons:passe_zero #bw float 12
```

**Comment by LoneDev6** [comment]
Before after what?
Please provide the versions you used in the screenshots.

**Comment by Maxlego08** [comment]
The version we are currently using is the following: 3.3.0b-r5
https://prnt.sc/T2wthyYY7oi-

**Comment by LoneDev6** [comment]
Do RPGhuds work fine?
Test it please.

Also did you try to regenerate your resource pack?

**Comment by Yassounou** [comment]
Hello Lone, its Yassou, Maxlego is a dev in our project, I did update to itemsadder 3.4.1-r5 and lonelibs 1.0.24, but custom hud that we did dev using api wont show any more,

this is what they should looks like usine itemsadder 3.3.0b-r5 :
![image](https://user-images.githubusercontent.com/69685202/229872873-9e82ab75-52ac-468f-aab2-6612ff5d66cf.png)

and this is what they lookslike using the last version ( itemsadder 3.4.1-r5 and lonelibs 1.0.24)
![image](https://user-images.githubusercontent.com/69685202/229873132-9865f5ab-09d0-4494-aae3-b2e8624a0448.png)

I have this error whene I regenerated the pack :
[message (4).txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/11151340/message.4.txt)

Thank you in advance

**Comment by Yassounou** [comment]
Ohay my bad seems that i did somthing wrong, so I did reinstall the plugins and refreshing once again the pack its fixed for hud display, but I have this error again https://pastebin.pl/view/de271131
