### ISSUE TITLE
[BUG] Rotated heads on 1.19.4 clients/servers

### ISSUE THREAD

**Issue by adelando** [PluginBugs/Issues-ItemsAdder#2465]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Adelando#1988

### What happened?

Whilst updating to 1.19.4, all heads on 1.19.4 clients are rotated the incorrect way.
whilst all 1.19.x clients below 1.19.4 show correct head orientation.

Checked the Wiki and turned off Emotes in itemsadder and currently disabled modelengine

### Steps to reproduce the issue

Simply log in with a client on any version and the head models are correct, but login on 1.19.4 and heads are not modeled correctly

### Server version

Current: git-Purpur-1948 (MC: 1.19.4)*\n
You are 1 version(s) behind\nDownload the new version at: https://purpurmc.org/downloads

### ItemsAdder Version

ItemsAdder version 3.4.1

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b606

### LoneLibs Version

LoneLibs version 1.0.24

### FULL server log

na

### Other files, you can drag and drop them here to upload. (optional)

na

### Screenshots/Videos (you can drag and drop files or paste links)

![2023-03-28_15 13 34](https://user-images.githubusercontent.com/11265974/228157498-c0c38740-b438-469c-8663-5e70febc5c8c.png)

![2023-03-28_15 12 28](https://user-images.githubusercontent.com/11265974/228157558-15e7f5dd-d305-4e53-9459-6c29e01f9487.png)

**Comment by adelando** [comment]
Also disabling Lonelibs (So itemsdder nd cosmeticscore) the heads are rendered properly.
These are both in vanilla 1.19.4 clients
![2023-03-29_13 54 03](https://user-images.githubusercontent.com/11265974/228440062-7a831022-441c-45ef-ae29-22a31ec7755c.png)


![2023-03-29_13 59 27](https://user-images.githubusercontent.com/11265974/228440213-076b153c-907c-4f9d-a21a-64e5f93fe409.png)

**Comment by LoneDev6** [comment]
Will be checked, that's very strange since last time I tested the plugin emotes worked fine on 1.19.4.

**Comment by AydaaCraft** [comment]
I'll continue testing on my side too, see if it's a hook of some sort

**Comment by adelando** [comment]
I'll continue testing on my side and see if it's a hook or some sort

**Comment by adelando** [comment]
I've tried disabling other plugins that effect models or resoursepacks or entities and still no result, only when itemsadder is disabled

here is my list of plugins

![2023-03-30_06 54 01](https://user-images.githubusercontent.com/11265974/228687016-48eaffce-0dbb-4eac-856b-277c9b7acbdd.png)

**Comment by LoneDev6** [comment]
It's surely related to the emotes.
I will do some tests in the next days but last time I ran the plugin on 1.19.4 and tested emotes I didn't get this issue.

**Comment by LoneDev6** [comment]
Please try to teleport far from there, you might have some player heads placed in the area and they are known to mess up the emotes.
https://itemsadder.devs.beer/faq/placed-heads-texture-glitched

Fabric 1.19.4

![image](https://user-images.githubusercontent.com/27242001/228838022-e45bd69f-435d-46ed-823d-7c86ffc42e00.png)

Vanilla 1.19.4

![image](https://user-images.githubusercontent.com/27242001/228838455-2ddf1dbf-0937-4a3b-b8dc-0de00783cf36.png)

**Comment by ArubikU** [comment]
![image](https://user-images.githubusercontent.com/102335860/228986181-200dce33-b8d3-4fc1-a3e0-60f5d20cae07.png)
@LoneDev6 The error ocurre when gesture are enabled
reason:
![image](https://user-images.githubusercontent.com/102335860/228986251-970e215d-861d-4582-94b5-3d618566d299.png)

**Comment by adelando** [comment]
This is my current config file

`metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: [REDACTED]
      pack-port: 8030
    external-host:
      enabled: false
      url: http://127.0.0.1:8091/pack.zip
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: true
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: false
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
    protect-file-from-unzip:
      protection_1: true
      protection_2: false
    compress-png-files: true
    compress-json-files: false
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: false
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks: false
    extract_internal_utility_assets: true
    contents-folders-priority:
    - vanilla
    - minecraft
    - _iainternal
  command:
    usage-cooldown-seconds: 60
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
  1_19_3_atlas_support: true
  fix_force_unicode_font_images: true
config_files:
  lang: en
  dictionaries-lang: en
  extract-default-resources: false
  force-sync-loading: false
blocks:
  light-api: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    seach-also-in-these-biomes: {}
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: false
    allow-any-item: true
    drop_when_broken: false
  disable-REAL: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_NOTE: false
  disable-REAL_WIRE: false
  disable-FIRE: false
  fix-liquids-flow: true
  fix-floating-blocks: true
  convert-vanilla-blocks:
    enabled: false
    only-new-chunks: true
  convert-legacy-ia-region-files: true
  remove-unused-palettes-on-region-save: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: false
liquids:
  enabled: false
huds:
  enabled: false
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: false
    tab-autocompletion_1_19_1_plus: false
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  replace-in-customitems-name-and-lore: true
  iaimage-book:
    max-line-length: 18
    placeholder-font: minecraft:default
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: true
  custom-entitites:
    enabled: true
    interval-rendering-packets-ticks: 1
    emotes: false
    optimized-packets: false
recipes:
  remove-vanilla-recipes:
    enabled: false
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
  hide-vanilla-unrecognized-recipe-errors: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: false
        ingredients: false
  fix-packet-too-large-kick: true
  show-no-permission-popup-in-recipebook: true
  show-no-permission-chat-message: false
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-fix-packet-too-large: false
    log-recipes-unknown-item: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-mined-unknown-blocks: false
    log-convert-vanilla-blocks: false
    log-save-load:
      enabled: false
      min-ms: 0
    log-fix-bugged-blocks: false
    log-unusual-block-break: false
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-generation: false
    log-loading-no-world: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-generation: false
    log-loading-no-world: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-generation: false
    log-loading-no-world: false
  player-stats:
    log-save: false
  performance:
    loading-ms: false
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: false
    log-generation: false
  benchmark: false
effects:
  hide-scoreboard-numbers: true
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: false
chat-preview: false
ignore-server-compatibility-check: false
`

**Comment by LoneDev6** [comment]
> @LoneDev6 The error ocurre when gesture are enabled reason: ![image](https://user-images.githubusercontent.com/102335860/228986251-970e215d-861d-4582-94b5-3d618566d299.png)


I don't see how it's working fine on my game then...
I tested on Vanilla and Fabric 1.19.4 and I correctly see the head texture.

> This is my current config file, I have entities enabled but emotes disabled

Because you have to run /iazip as explained in the link I shared.
