### ISSUE TITLE
Attribute modifier conflict with enchantement

### ISSUE THREAD

**Issue by Darkseno** [PluginBugs/Issues-ItemsAdder#2466]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Darkseno#9099

### What happened?

I modified the damage and attack speed attributes of a custom sword (netherite) except that when I decide to enchant this sword the attributes underneath don't change and stay at the ones I put in the basic config.

So my players are confused.

### Steps to reproduce the issue

1. Open a server
2. Take a weapon with /ia
3. /enchant sharpness 5
4. The attribute do not change

### Server version

[14:39:18 INFO]: Current: git-Purpur-1933 (MC: 1.19.3)*
Previous: git-Purpur-1916 (MC: 1.19.3)

### ItemsAdder Version

[14:39:48 INFO]: ItemsAdder version 3.4.1-r2
[14:39:48 INFO]: Customized Minecraft without client mods!
[14:39:48 INFO]: Website: devs.beer
[14:39:48 INFO]: Author: LoneDev

### ProtocolLib Version

[14:40:13 INFO]: ------------------------
[14:40:13 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b606
[14:40:13 INFO]: Provides read/write access to the Minecraft protocol.
[14:40:13 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[14:40:25 INFO]: LoneLibs version 1.0.24
[14:40:25 INFO]: Collection of libs used by my plugins
[14:40:25 INFO]: Authors: LoneDev and others

### FULL server log

https://pastebin.com/LDG3qbtC

### Error (optional)

```shell
No error
```

### Problematic items yml configuration file (optional)

```shell
https://pastebin.com/ehMzhUDQ
```

### Screenshots/Videos (you can drag and drop files or paste links)

![bug1](https://user-images.githubusercontent.com/99391020/228239464-403eee47-e1c8-4b10-b63d-2ad8198c2f25.jpg)
![bug2](https://user-images.githubusercontent.com/99391020/228239476-d4404488-d4bc-4646-bedb-7d1cdb025ec8.jpg)

**Comment by LoneDev6** [comment]
I think it's because the /enchant command won't update the lore info of the custom item.
I will have to implement some trick to intercept the command and refresh the lore.

I'll do some tests and let you know if I can fix it or now.
Is it EssentialsX command or CMI command?

I'm sure that it works fine if you enchant it in the anvil or enchantment table.

**Comment by LoneDev6** [comment]
I could implement a command `/iarefreshitem` to force refresh properties of the held item, what do you think?
