### ISSUE TITLE
Issues with armors not loading for some players, blocks randomly changing texute

### ISSUE THREAD

**Issue by SinistersGrin** [PluginBugs/Issues-ItemsAdder#2469]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Sinisters Grin#4934

### What happened?

Ill try to be as detailed as I can.
First issue: Textures are different for everyone, I can see things others cant, they can see things I cant, and its different for almost every player new or old.

What I can see 
https://i.imgur.com/GNpWxtA.png
https://i.imgur.com/PPt84Ca.png
https://i.imgur.com/MhVIVXb.png
https://i.imgur.com/84b8ixX.png
https://i.imgur.com/AgOdO2T.png
https://i.imgur.com/h8yebgp.png

What another staff can see
https://i.imgur.com/bHDU5D0.png
https://i.imgur.com/ACtLl8p.png
https://i.imgur.com/BM5frah.png

What two other members can see
https://i.imgur.com/7P2JQ8c.png
https://i.imgur.com/GU572B0.png

And other members can see all of it like they are supposed to, it is completely random on who gets to see what, sometime i can see the foods other times i cant.

Another issue happened after updating to version (3.4.1-r2) which is when you place a block under or on a note block it changes to a random block texture every time like this
https://i.imgur.com/TjzrGFv.jpg
https://i.imgur.com/spidYT8.jpg

Also Mushroom trees sometimes randomly look like a bunch of different ia textures, you get vanilla loot when you break them, no screenshot sadly.

### Steps to reproduce the issue

First issue i have no idea as it is completely random and is different for every player.

Second issue with noteblocks
1- place stone right under a noteblock and it changes texture

Thirds issue with trees
1- fly to unloaded chunks and sometimes they randomly change textures

### Server version

This server is running Paper version git-Paper-215 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 236a296)

### ItemsAdder Version

ItemsAdder version 3.4.1-r2

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b618

### LoneLibs Version

LoneLibs version 1.0.24

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11095112/latest.log)

**Comment by SinistersGrin** [comment]
as a quick update cause been testing things, i dont know how relevant this is but when i upload textures to Contents it works for everyone, the second i upload any textures using the old method (data) folder it does what is said above

**Comment by LoneDev6** [comment]
If players who cannot see the armors correctly are running 1.19.3+ with Optifine then it's a known Optifine bug.
The Optifine developer needs to fix CIT feature of its mod in order for armors to work fine on Optifine.
What you can do in the meantime is disable Optifine armors in config.yml of ItemsAdder and run the /iazip command again, then join and see armors working fine.

Anyway based on your screenshots some of your players are using an insane amount of mods. I'd kindly ask them to join using a vanilla client to see that armors work fine.
It's impossible for me to know about every possible mod existing out there, but most likely one is causing the black armors bug for your players.

ItemsAdder armors were tested and working correctly on vanilla client 1.17 to 1.19.4 and Optifine 1.17 to 1.19.2.

More info about common issues:
https://itemsadder.devs.beer/faq/armors-bugs

**Comment by SinistersGrin** [comment]
Completly understandable i should've been more specific thats on me sorry, The other staff member has tried about 6 hours ago on the newest release on the test server, all she had in mods as fabric api and simple voice chat, before that she never used Optifine or shaders, she does use Iris, Lithium, Sodium, and Xaeros's minimap, its the same as another staff member, the players who gave me the screenshots use our modpack which i use too and its working fine on my side aside from the foods only loading textures when i hold them. Both staff members tried joining on a fabric launch (1.19.2 & 1.19.3 & 1.19.4) and just plain vanilla (same versions) 

Already tried disabling Optifine armors in config.yml, i tried completely reinstalling the plugin and redoing it all step by step and adding the textures one by one, and ive already read the wiki multiple times over and took a decent amount of time going through the Github and i cant really find much to help with it, this has been an issue for a while so i promise im not wasting your time, ive spent hours looking for ways to fix it before ever bothering you cause i assume you dont have much time as it is, im sorry for the inconvenience, if there are any other questions ill reply as fast as i can

**Comment by SinistersGrin** [comment]
"I see no reason to waste 6 hours without first trying joining with vanilla Minecraft to be honest."  I think you misread what i wrote, that was one of the things we did test.

- on vanilla client 1.17 to 1.19.4   

 (tried still the same)

 
- on Optifine client 1.17 to 1.19.2. Optifine 1.19.3+ [is bugged](https://itemsadder.devs.beer/faq/armors-bugs/optifine-cit-not-working) and I can't do anything about that.

(Server is 1.19.2 , tried still the same)

- Fabric 1.17 to 1.19.4 with [Fabulously Optimized modpack](https://www.curseforge.com/minecraft/modpacks/fabulously-optimized) which shows armors just fine.

(I am unsure how to go about this as most of us dont use curse forge)

- some mods might interfere so if you really want to find out the cause of the issue you have to remove ALL mods from your client and add 1 by one until you find out which one triggers the issue.
(Tried today with 4 different people and the issue is still the same)


Weirdly enough even on another server with a fresh install of the plugin and no mods what so ever its the exact same issue with me personally being able to see everything except foods in the menu, and only can see them when holding in hand, i am sorry for the inconvenience and i hope i really am not messing anything up like i said i tried everything i could to try to fix this before ever bothering you.

**Comment by LoneDev6** [comment]
>  am sorry for the inconvenience 

No need to apologize, I just am pretty confused because we are missing something obvious here since the plugin works fine on 3400+ servers.

**Comment by SinistersGrin** [comment]
Ok so after having so many members test things this is what we've managed to figure out as a temp fix, for some reason one of the members had a very old version of the resource pack (before the Contents) folder was even a thing, today he sent it to one of the members that had the issue with the armors and if they use that resource pack along with enabling the server resource pack it fixes everything, if they only use the resource pack or the server pack the issue is there, if they use a new generated resource pack the issues is still there too, ive tried taking off the Protection1 and 2, still the same, hopefully this leads to some ideas


things that were added since the pack he has
![image_2023-04-08_121552675](https://user-images.githubusercontent.com/115602637/230713730-256e81f7-e668-4456-ab8e-41417df86f44.png)

its late and we spend the last 4-5 hours doing this so tomorrow we will removed them one by one and see if its a specific one causing the issues
