### ISSUE TITLE
Black cube when logging in and /iazip

### ISSUE THREAD

**Issue by zermarvt** [PluginBugs/Issues-ItemsAdder#2472]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

When you log in to the server, you get a Black Cube. This only goes away when you remove or place a block (in the near vicinity). I use neither a shader nor a texture pack.

### Steps to reproduce the issue

1.1 Log in -> Cube is here
1.2 Place or break a block and the cube is disappeared

Other occurrences
2.1 Use /iazip and the cube is suddenly there
2.2 Place or break a block and the cube is disappeared

### Server version

This server is running Paper version git-Paper-474 (MC: 1.19.4 (Implementing version 1.19.4-R0.1-Snapshot) (Git:bd62f2c)

### ItemsAdder Version

ItemsAdder Version 3.4.1-r3

### ProtocolLib Version

ProtocolLib 5.0.0-SNAPSHOT-b616

### LoneLibs Version

LoneLibs version 1.0.24

### FULL server log

There is no error in the log

### Screenshots/Videos (you can drag and drop files or paste links)

https://ibb.co/J5GBWMF
https://ibb.co/bmdqy5w
https://ibb.co/n1LRr6v

**Comment by zermarvt** [comment]
I use Fabric. As far as I know, that also worked with 1.19.3.

**Comment by LoneDev6** [comment]
Can you test with vanilla client for some minutes to see if it happens?
Thanks

**Comment by zermarvt** [comment]
Tested in vanilla, nothing happened. The black cube is not there. Hm strange. It's only like that with Fabric. I only have Fabric with the Xaeros minimap.
