### ISSUE TITLE
Item Tag Changed

### ISSUE THREAD

**Issue by ninesik** [PluginBugs/Issues-ItemsAdder#2473]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

나인#1927

### What happened?

1. Acquire an item.
2. Drop the item on the floor through the Q key.
3. Acquire items dropped on the floor.
4. The item tag has been changed.

### Steps to reproduce the issue

1. Acquire an item.
2. Drop the item on the floor through the Q key.
3. Acquire items dropped on the floor.
4. The item tag has been changed.

### Server version

1.19.4

### ItemsAdder Version

3.4.1-r3

### ProtocolLib Version

`

### LoneLibs Version

`

**Comment by LoneDev6** [comment]
Remove every other plugin (keep LoneLibs, ProtocolLib and ItemsAdder) and test if it still happens.
ItemsAdder doesn't edit dropped items NBT tag.

**Comment by LoneDev6** [comment]
Cannot reproduce. NBT data is always the same otherwise they wouldn't stack.

https://user-images.githubusercontent.com/27242001/228868149-5acd2389-4ea6-41ad-8d8a-70cebccfa2d7.mp4

**Comment by ninesik** [comment]
This problem occurs if you create an item using mmoitems plugin.
ia config

  items36:
    display_name: '&f&l욕망의 구슬'
    permission: items
    mmoitem:
      type: material
      id: test
    resource:
      material: STICK
      generate: true
      textures:
      - item/36.png

mmoitems config
test:
  base:
    material: STICK


1. Discard the item.

**Comment by ninesik** [comment]
Item Tag Before Throwing Away

{Count:9b,id:"minecraft:stick",tag:{AttributeModifiers:[{Amount:0.0d,AttributeName:"minecraft:generic.attack_speed",Name:"mmoitemsDecoy",Operation:0,UUID:[I;-2021319128,-1357757450,-1987131861,-563359508]}],CustomModelData:10098,HSTRY_ENCHANTS:'{"Stat":"ENCHANTS","OGStory":[{"MMOITEMS_ENCHANTS_ñstr":"[]"}]}',HideFlags:2,MMOITEMS_DYNAMIC_LORE:'["&c재료"]',MMOITEMS_ENCHANTS:"[]",MMOITEMS_ITEM_ID:"욕망의구슬",MMOITEMS_ITEM_TYPE:"MATERIAL",display:{Lore:['{"italic":false,"color":"red","text":"재료"}'],Name:'{"bold":true,"italic":false,"color":"white","text":"욕망의 구슬"}'},itemsadder:{id:"items36",namespace:"inmc"}}}

Item tag after discarding

{Count:1b,id:"minecraft:stick",tag:{AttributeModifiers:[{Amount:0.0d,AttributeName:"minecraft:generic.attack_speed",Name:"mmoitemsDecoy",Operation:0,UUID:[I;-2021319128,-1357757450,-1987131861,-563359508]}],CustomModelData:10098,HSTRY_ENCHANTS:'{"Stat":"ENCHANTS","OGStory":[{"MMOITEMS_ENCHANTS_ñstr":"[]"}]}',HideFlags:2,MMOITEMS_DYNAMIC_LORE:'["&c재료"]',MMOITEMS_ENCHANTS:"[]",MMOITEMS_ITEM_ID:"욕망의구슬",MMOITEMS_ITEM_TYPE:"MATERIAL",display:{Lore:['{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"재료"}],"text":""}'],Name:'{"bold":true,"italic":false,"color":"white","text":"욕망의 구슬"}'},itemsadder:{id:"items36",namespace:"inmc"}}}

**Comment by ninesik** [comment]
욕망의구슬 = test

**Comment by ninesik** [comment]
@LoneDev6

**Comment by LoneDev6** [comment]
This seems to be a MMOitems bug not ItemsAdder bug.
As I said:
> ItemsAdder doesn't edit dropped items NBT tag.

This is not an ItemsAdder bug.
