### ISSUE TITLE
Server error related

### ISSUE THREAD

**Issue by Surtryyds** [PluginBugs/Issues-ItemsAdder#2478]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Surtr#6495

### What happened?

The server background keeps brushing and reporting errors...

### Steps to reproduce the issue

An error will be reported after normal startup.

### Server version

An error will be reported after normal startup.

### ItemsAdder Version

git-Purpur-1858 (MC: 1.19.2)*

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b606

### LoneLibs Version

LoneLibs version 1.0.24

### FULL server log

https://mclo.gs/g8QObZX

**Comment by LoneDev6** [comment]
Update to Purpur 1.19.3 or 1.19.4 and test.

**Comment by Surtryyds** [comment]
My server is created based on 1.19.2, and I cannot replace the version at will, which will invalidate most of my existing plugins. Is there any other way to solve it?

**Comment by LoneDev6** [comment]
In the first place the error you are reporting is strange. The plugin was tested on 1.19.2 and worked fine.
Can you try installing Paper 1.19.2 instead of Purpur and test?

**Comment by Surtryyds** [comment]
Could this be a problem with iris? I used it to survive a custom world, and configured the natural generation of ia blocks in iris.

**Comment by LoneDev6** [comment]
No, it has nothing to do with Iris but with the server itself.

**Comment by Surtryyds** [comment]
Ok, thanks for the tip, I'll try it out, I also noticed that every time I start the server it automatically stops once for no reason, and immediately after stopping it starts a second time to start normally.

**Comment by LoneDev6** [comment]
There seem to be something pretty broken in your server then

**Comment by Surtryyds** [comment]
I've tried deleting all other files except the plugins folder and regenerating the core, but the problem persists, I'll try again now, thanks for your help.

**Comment by Surtryyds** [comment]
After using the paper core, most of my plugins seem to be unavailable. Here's a link to the relevant log:
[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11120100/latest.log)

**Comment by Surtryyds** [comment]
I redownloaded the purpur core and deleted everything except the plugin folder, but the error persists, here is the relevant link: https://mclo.gs/e18exW3

**Comment by LoneDev6** [comment]
You can try deleting this folder:
`plugins\ItemsAdder\storage\players\`

**Comment by Surtryyds** [comment]
> You can try deleting this folder while server is offline, then start again. `plugins\ItemsAdder\storage\players\`

Ok, thanks for your help, the problem is solved after updating the version.
