### ISSUE TITLE
Request to add itemsadder compatibility for happyhud

### ISSUE THREAD

**Issue by Surtryyds** [PluginBugs/Issues-ItemsAdder#2479]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Surtr#6495

### Describe the solution you'd like

Currently itemsadder and happyhud are not compatible. I made this request in happyhud. Ehhthan said that only cooperation can solve the compatibility problem. This is the link of issues: https://github.com/Ehhthan/HappyHud-Issues/issues/45
I hope that itemsadder can be compatible with happyhud in the future, which will bring infinite possibilities to the server.

### Is your feature request related to a problem?

Currently itemsadder doesn't seem to be able to customize the player's health and hunger bars.

### Describe alternatives you've considered

There doesn't seem to be an alternative at the moment. I want to customize health and hunger bars with happyhud. I found that the trigger of itemsadder does not seem to support it, so I bought happyhud and wanted to realize this function through happyhud. At this time, I found that when I generated happyhud, when the material generated by itemsadder and the material generated by itemsadder were fused together, neither the hud of itemsadder nor the hud of happyhud could be displayed normally.

**Comment by LoneDev6** [comment]
It's impossible to make happyhud and itemsadder huds working at the same time.
You have to disable itemsadder huds in config.yml in order to make happyhud work.

**Comment by Surtryyds** [comment]
> It's impossible to make happyhud and itemsadder huds working at the same time. You have to disable itemsadder huds in config.yml in order to make happyhud work.
> 
> It's a limitation of the game and not a limitation of itemsadder or happyhud. I would have preferred Minecraft to make things easier but sometimes we cannot achieve everything. I hope you understand.

Ok, thanks for your help!
