### ISSUE TITLE
Integration with PlayerNPC

### ISSUE THREAD

**Issue by DxrkCat** [PluginBugs/Issues-ItemsAdder#2486]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Hello could you help with using custom itemsadder models on npc made with PlayerNPC. 
If you can not implement this in your plugin, you can suggest how to use custom models and emotions dancing and other, on this NPC made with the use of this library.

Translated with www.DeepL.com/Translator (free version)

### Is your feature request related to a problem?

Because of terrible optimization and problems with missing models on Citizens I had to leave this plugin, the plugin has a lot of problems since 2017. 

### Describe alternatives you've considered

So I decided to propose the idea with integration with PlayerNPC (https://github.com/SergiFerry/PlayerNPC / https://www.spigotmc.org/resources/93625/).

**Comment by LoneDev6** [comment]
It's impossible to make ItemsAdder emotes compatible with this NPCs plugin.
It would basically require me to write an NPCs plugin.

What do you need these NPCs to do? How are you using this API?
Add some context please, thanks.

**Comment by DxrkCat** [comment]
> It's impossible to make ItemsAdder emotes compatible with this NPCs plugin. It would basically require me to write an NPCs plugin.
> 
> What do you need these NPCs to do? How are you using this API? Add some context please, thanks.

It's impossible to make ItemsAdder emotes compatible with this NPCs plugin.
It would basically require me to write an NPCs plugin.

What do you need these NPCs to do? How are you using this API?
Add some context please, thanks.

javadocs https://sergiferry.github.io/PlayerNPC/dev/sergiferry/playernpc/api/package-summary.html

**Comment by LoneDev6** [comment]
I agree with you about Citizens.
Anyway you can just use my API to create NPCs.
You just have to spawn them and remove AI.

https://github.com/LoneDev6/API-ItemsAdder/blob/master/src/main/java/dev/lone/itemsadder/api/CustomEntity.java
