### ISSUE TITLE
Furniture Event error

### ISSUE THREAD

**Issue by yoonsuyong** [PluginBugs/Issues-ItemsAdder#2487]
### Discord tag (optional)

ifyouz#5247

### What happened?
```java
@EventHandler(priority = EventPriority.HIGHEST) 
void customBlockBreakEvent(FurnitureBreakEvent e) {
  String key = e.getFurniture().getArmorstand().getEntityId() + "";
  if (!Allvar.userBlock.containsKey(key)) {
    return;
  }
  String value = e.getPlayer().getUniqueId() + ":" + e.getPlayer().getName();
  if (!Allvar.userBlock.get(key).equals(value)) {
    String info = Allvar.info.replace("&nick$", Allvar.userBlock.get(key).split(":")[1]);
    e.getPlayer().sendMessage(ChatColor.translateAlternateColorCodes('&', info));
    e.setCancelled(true);
  } else {
    Allvar.userBlock.remove(key);
  }
}
```

I want to protect the furniture.
If "setcanceled(true)", the opponent event will not work.

### Server version

git-paper-383 (MC:1.19.3) (Implementing api version 1.19.3-r0.1-snapshot) (git:b082d89)

### ItemsAdder Version

3.4.1-r4

### ProtocolLib Version

5.0.0-snapshot-b612

### LoneLibs Version

1.0.24

**Comment by LoneDev6** [comment]
Next time please do not post text in a single line...

Anyway, are you sure the event is called? is this message shown in console?
`e.getPlayer().sendMessage(ChatColor.translateAlternateColorCodes('&', info));`
