### ISSUE TITLE
Shopping

### ISSUE THREAD

**Issue by PriestOfTerror** [PluginBugs/Issues-ItemsAdder#2490]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

PriestOfTerror#9992

### What happened?

Hello, I just want to ask how is it possible to sell items from itemsadder? can they be added to the shop using an ID, or is there a plugin needed?
Thanks for the advice and sorry to ask this way but it's really confusing and hard to find the right option to write.

### Steps to reproduce the issue

no steps

### ItemsAdder Version

3 4 1 r2

### ProtocolLib Version

5.0.0 (b614)

### LoneLibs Version

everything latest

**Comment by LoneDev6** [comment]
itemsadder doesn't offer an ingame shop to buy and sell items.
There are some shop plugins in the official list, you can check them
https://itemsadder.devs.beer/compatibility-with-other-plugins/compatible

**Comment by LoneDev6** [comment]
Anyway this is not a place to ask for advices or information, it's a place to report issues and suggest enhancements for the plugin.
Thanks!

Read more here: https://forum.devs.beer/d/16-getting-support
