### ISSUE TITLE
Hitbox Touch Event

### ISSUE THREAD

**Issue by Vooogle** [PluginBugs/Issues-ItemsAdder#2492]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Dr.Phil#0698

### Describe the solution you'd like

A feature where you could do something when you touch a hitbox of a thing.

### Is your feature request related to a problem?

Nah

### Describe alternatives you've considered

Nope

### Additional context

Was asking on the discord if there was a way to detect if someone was touching something so i could make a bear trap which would slow them completely for a couple seconds and then a slowness where they can move for a couple minutes.

**Comment by LoneDev6** [comment]
>  when you touch a hitbox of a thing.

This is more like a feature for an addon other than ItemsAdder itself
