### ISSUE TITLE
MMOITEMS incompatibility with custom armor models using OPTIFINE

### ISSUE THREAD

**Issue by Bobbyharron** [PluginBugs/Issues-ItemsAdder#2494]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

bobby_harron#7548

### What happened?

When using optifine, all the armor made in mmoitems lose the textures, i speaked with mmoitems staff and the problem seems to be on the itemsadder side, wich uses something different to match the armor model.

Without using optifine both works properly but when using it, mmoitems cant check the itemsadder armor color.

### Steps to reproduce the issue

use optifine
make custom textured armor on itemsadder
make custom armor on mmoitems
apply the ia armor color to mmoitems (hex to rgb)
armor from mmoitems wont show textures when using optifine, just without.

### Server version

Current: git-Purpur-1952 (MC: 1.19.4)*
Previous: git-Purpur-1886 (MC: 1.19.3)
* You are running the latest version

### ItemsAdder Version

3.4.1-r4

### ProtocolLib Version

5.0.0 SNAPSHOT b627

### LoneLibs Version

1.0.24

**Comment by LoneDev6** [comment]
Disable optifine compatibility in config.yml of itemsadder and regenerate you resourcepack.
Optifine 1.19.4 is currently bugged and doesn't support custom CIT armors, it does support the vanilla method armors.
So they will look fine if you don't use shaders in your game.

https://itemsadder.devs.beer/faq/armors-bugs/textures-broken-by-shaders-mod

![image](https://user-images.githubusercontent.com/27242001/229771451-e7a4f832-fa5f-4de2-b1f2-5e601fc950aa.png)
