### ISSUE TITLE
Adding a new configuration will mess up the custommodeldata value of the original item.

### ISSUE THREAD

**Issue by Surtryyds** [PluginBugs/Issues-ItemsAdder#2495]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Surtr#6495

### What happened?

I found that when adding some new ia configuration will mess up the custommodeldata value of the original item, after my test I found that when adding a class of item configuration, there is a probability that this will trigger this situation, which will cause the cmd value of my previously configured item to be messed up, is this a bug?

### Steps to reproduce the issue

When adding a new configuration to a class of items, make sure there is no conflicting custommodeldata configuration in the material package, everything is the cmd value automatically generated by itemsadder.

### Server version

git-Purpur-1858 (MC: 1.19.2)*

### ItemsAdder Version

 ItemsAdder version 3.4.1-r5

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b606

### LoneLibs Version

LoneLibs version 1.0.24

**Comment by Surtryyds** [comment]
Here the class of the item refers to the material of a particular original minecraft item.

**Comment by LoneDev6** [comment]
Sorry I don't understand this report at all.
Are you trying to merge some other resourcepack? ItemsAdder will clearly warn you about conflicting custommodeldata values if that's the case.
