### ISSUE TITLE
consol error after generating the pack

### ISSUE THREAD

**Issue by Yassounou** [PluginBugs/Issues-ItemsAdder#2499]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Yassou#0001

### What happened?

I did update to itemsadder 3.4.1-r5 and lonelibs 1.0.24
The pack works fine , but I have this consol error every time I /iaz or everytime I join the server as the pack is loading on my client
https://pastebin.pl/view/de271131

also it tells this [21:22:10 WARN]: [ItemsAdder] File compression skipped: duplicate entry: assets/modelengine/models/wyntale_cristal/cristalhaut.json

its not duplicated, its tells also after /iacleancash items and blocs

### Steps to reproduce the issue

update items adder from 3.3.0b-r5 to 3.4.1-r5 and lonlibs from 1.0.23 to 1.0.24 do restart than do /iaz

### Server version

![image](https://user-images.githubusercontent.com/69685202/229897958-8ee12311-c88d-440f-a70e-5d1a7c63475f.png)

Git-Purpur-1625 MC 1.18.2

### ItemsAdder Version

ItemsAdder Version 3.4.1-r5

### ProtocolLib Version

ProtocolLib Version 4.8.0

### LoneLibs Version

1.0.24

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11152310/latest.log)

**Comment by LoneDev6** [comment]
> [19:18:18 ERROR]: [ItemsAdder] Unhandled exception occured in onPacketSending(PacketEvent) for ItemsAdder
java.lang.NoSuchFieldError: SYSTEM_CHAT

Update ProtocolLib.
https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by LoneDev6** [comment]
> also it tells this [21:22:10 WARN]: [ItemsAdder] File compression skipped: duplicate entry: assets/modelengine/models/wyntale_cristal/cristalhaut.json

Make sure to read the new tutorial about modelengine.
https://itemsadder.devs.beer/compatibility-with-other-plugins/compatible/modelengine

The merging is now automatic, you don't need each time to copy and paste the modelengine folder into `ItemsAdder/contents/modelengine/...`.
Delete the old modelengine folder from `ItemsAdder/contents` and regenerate your zip file.
