### ISSUE TITLE
File compression skipped: duplicate entry:

### ISSUE THREAD

**Issue by Truongvv10** [PluginBugs/Issues-ItemsAdder#2500]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I updated itemsadder from `3.4.1-r4` to `3.4.1-r5` and had lots of duplicate issues with modelengine. In `3.4.1-r4` I did not have it
![image](https://user-images.githubusercontent.com/67742370/229908658-8f972c48-23df-4a85-96ae-3dc025d55fa3.png)

### Steps to reproduce the issue

I update from `3.4.1-r4` to `3.4.1-r5` and `/iaz` with modelengine textures uploaded.

Uploaded the leather horse armor in minecraft folder
And uploaded modelengine in content folder

These 2 folders are conflicting eachother

### Server version

![image](https://user-images.githubusercontent.com/67742370/229908774-3edde134-2f3a-4833-b5ff-19c0e0d68a98.png)

### ItemsAdder Version

![image](https://user-images.githubusercontent.com/67742370/229908855-92e31931-f5e2-4dc2-8898-3c8881773296.png)

### ProtocolLib Version

![image](https://user-images.githubusercontent.com/67742370/229908884-bedb6cb8-f614-4e29-8fb1-870f72d5b018.png)

### LoneLibs Version

![image](https://user-images.githubusercontent.com/67742370/229908928-c510535e-2190-4a86-9d38-484c3afd8699.png)

### FULL server log

[latest (1).log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11152650/latest.1.log)

**Comment by LoneDev6** [comment]
The merging is now automatic, you don't need each time to copy and paste the modelengine folder into `ItemsAdder/contents/modelengine/...`.
Delete the old modelengine folder from `ItemsAdder/contents` and regenerate your zip file.
