### ISSUE TITLE
Crafting Table will be lose after server crash

### ISSUE THREAD

**Issue by mclk623** [PluginBugs/Issues-ItemsAdder#2504]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Crafting Table will be lost after server crash by use itemsadders
I need to delete storage/cache that recover it

### Steps to reproduce the issue

1.crash server
2.restart server
3.Crafting lose

### ItemsAdder Version

ItemsAdder version 3.4.1-r5

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b627

### LoneLibs Version

 LoneLibs version 1.0.24

**Comment by LoneDev6** [comment]
I don't understand what you mean sincerely.
Please add more information and also post the COMPLETE LOG of when the issue occurred.
