### ISSUE TITLE
vulcan plugin Bad Packets (Type V)

### ISSUE THREAD

**Issue by DohyunKF** [PluginBugs/Issues-ItemsAdder#2509]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

greatbb11#1027

### What happened?

After applying the vulcan anti-cheat, I was sometimes kicked out as a Bad Packet when I entered /iatexture and a resource pack was applied.

Translated with Google Translator.

### Steps to reproduce the issue

1. Apply the vulcan plugin.
2. Enter the /iatexture command.

### Server version

This server is running Paper version git-Paper-366 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 8d7d927)
You are 82 version(s) behind
Download the new version at: https://papermc.io/downloads

### ItemsAdder Version

Itemsadder - 3.4.1-r5

### ProtocolLib Version

ProtocolLib - 5.0.0-SNAPSHOT-b615

### LoneLibs Version

LoneLibs - 1.0.24

### Screenshots/Videos (you can drag and drop files or paste links)

![123231image](https://user-images.githubusercontent.com/104108680/230633779-bc09201c-b0cd-4796-9c60-53cab0ccb9f9.png)

**Comment by LoneDev6** [comment]
Will be checked, thanks.

**Comment by JugadoraNalgona** [comment]
any update on this? I keep getting it on the last version.
