### ISSUE TITLE
Furniture upper limit BUG

### ISSUE THREAD

**Issue by p82183645** [PluginBugs/Issues-ItemsAdder#2514]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Doge村長#6969

### What happened?

When a block has a limited number of furniture, placed > remove
will be stuck with a quantity
repeat this action
The furniture in this area will reach the limit, but there is actually no furniture

### Steps to reproduce the issue

When a block has a limited number of furniture, placed > remove
will be stuck with a quantity
repeat this action
The furniture in this area will reach the limit, but there is actually no furniture

### Server version

![image](https://user-images.githubusercontent.com/5382252/230712338-df624fe4-df65-4fc4-97fd-a45bd4d19e40.png)

### ItemsAdder Version

3.4.1-r5

### ProtocolLib Version

![image](https://user-images.githubusercontent.com/5382252/230712369-e2f0e0f2-bc3d-438e-90d0-64c198d0b9e0.png)

### LoneLibs Version

![image](https://user-images.githubusercontent.com/5382252/230712377-34b920f0-b58e-4d68-8144-4e0d568ed0e0.png)

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/5382252/230712412-efeec316-79fa-4966-af7a-19398251fd75.png)

**Comment by LoneDev6** [comment]
Make sure you don't have other mobs and entities in the area. You probably have some monsters or animals around.
The amount is calculated directly by checking the entities amount in that chunk, using the Spigot API. There is no way it would count removed furniture.

**Comment by p82183645** [comment]
> Make sure you don't have other mobs and entities in the area. You probably have some monsters or animals around. The amount is calculated directly by checking the entities amount in that chunk, using the Spigot API. There is no way it would count removed furniture.

no , is bug

**Comment by LoneDev6** [comment]
This is the code.
```java
if (maxPerChunk > 0 && loc.getChunk().getEntities().length + 1 > maxPerChunk)
{
    if (player != null)
        Msg.message(player, Main.lang.getLocalized("max-furnitures-vehicles-reached").replace("{value}", maxPerChunk + ""));
    return;
}
```

As you can see I clearly use the Spigot API to get the count of entities in the current chunk.
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Chunk.html#getEntities()
```java
loc.getChunk().getEntities().length
```

**Comment by p82183645** [comment]
> This is the code.
> 
> ```java
> if (maxPerChunk > 0 && loc.getChunk().getEntities().length + 1 > maxPerChunk)
> {
>     if (player != null)
>         Msg.message(player, Main.lang.getLocalized("max-furnitures-vehicles-reached").replace("{value}", maxPerChunk + ""));
>     return;
> }
> ```
> 
> As you can see I clearly use the Spigot API to get the count of entities in the current chunk. https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Chunk.html#getEntities()
> 
> ```java
> loc.getChunk().getEntities().length
> ```

I can't read the code
But I tested, there are no creatures or objects nearby
the bug still exists
you can test it

**Comment by LoneDev6** [comment]
Use spectator mode to see invisible entities too.
Let me know.

**Comment by p82183645** [comment]
> Use spectator mode to see invisible entities too. Let me know.

yes, the neighborhood is empty

**Comment by p82183645** [comment]
Also, I found that after some furniture is removed, the invisible armor stand will remain there

**Comment by LoneDev6** [comment]
> I found that after some furniture is removed, the invisible armor stand will remain there

This seems to be a bug caused by another plugin.
ItemsAdder always removes the entity when the furniture is broken by the player.

**Comment by p82183645** [comment]
> > I found that after some furniture is removed, the invisible armor stand will remain there
> 
> This seems to be a bug caused by another plugin. ItemsAdder always removes the entity when the furniture is broken by the player.

I don't have another plugin controlling this behavior
can you fix it

It's getting worse and these areas can no longer be used for furniture
Moreover, furniture like chairs will leave an invisible armor stand after removal

**Comment by p82183645** [comment]
hallo this?

**Comment by LoneDev6** [comment]
> can you fix it

I can't fix issues if I cannot reproduce them on my own server.
Please open a private thread here on my forum and provide your server IP.
https://forum.devs.beer/t/private-payment-issue
