### ISSUE TITLE
Can't use namespaces and item IDs with `.` character

### ISSUE THREAD

**Issue by Lerphie** [PluginBugs/Issues-ItemsAdder#2521]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Coder#6926

### What happened?

When adding new blocks, this error pops up. After that I can not use the ItemsAdder plugin in any way. I add content correctly, the problem is 100% in the plugin

### Steps to reproduce the issue

1. Add any block
2. Write /iareload or restart the server.
3. Go in and see that the plugin does not work

### Server version

git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### ItemsAdder Version

3.4.1-r5

### ProtocolLib Version

5.0.0-SNAPSHOT-b616

### LoneLibs Version

1.0.24

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/66962762/230955675-8f4255a3-3d79-41a9-b804-20d1af417f1c.png)

**Comment by Lerphie** [comment]
I need to fix this as soon as possible, I didn't expect a tank like this to happen. Please take the time to look into this issue

**Comment by Andre601** [comment]
This is 100% a configuration issue and 100% an issue with your furniture having a wrong height and length. They only accept **whole numbers**, so 0.5 and 0.2 is not valid values.

Also, usually do you use `/iazip` to refresh the resource pack and not just `/iareload`

**Comment by Lerphie** [comment]
So even when I make a block, the problem is the same

**Comment by Lerphie** [comment]
> This is 100% a configuration issue and 100% an issue with your furniture having a wrong height and length. They only accept **whole numbers**, so 0.5 and 0.2 is not valid values.
> 
> Also, usually do you use `/iazip` to refresh the resource pack and not just `/iareload`
In the video, I added 1 new block as an example, and even so I am all out. 
https://youtu.be/aAKtJtgYvi8

**Comment by LoneDev6** [comment]
Please share your configuration, seems it's broken and causing the plugin to fail to load.
Also always make sure to use the official files editor of the plugin to avoid mistakes. https://itemsadder.devs.beer/plugin-usage/files-editor

**Comment by LoneDev6** [comment]
Please open `ItemsAdder/storage/items_ids_cache.yml` and upload it here.
Thanks.

**Comment by Lerphie** [comment]
> Please open `ItemsAdder/storage/items_ids_cache.yml` and upload it here. For some reason it contains broken data.
> 
> Thanks

I've already found the reason. The folder was not named correctly, namely "update_1.16", because of the fact that there is ". Now I renamed the folder + cleared "storage"

**Comment by LoneDev6** [comment]
Amazing!
I'll do some tests and add a proper warning about this misconfiguration, so people can find out the issue more easily!

I hope you'll consider leaving a 5 stars review on my plugin page, it would help me so much with the future updates :D
Thanks my friend.
