### ISSUE TITLE
Title command not showing on screen after loading in with itemsadder

### ISSUE THREAD

**Issue by gidgud** [PluginBugs/Issues-ItemsAdder#2527]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Manbearpig#7522

### What happened?

Minecraft title command broken when loading in with title: enabled in config
title command works fine after disabling this feature, 
to be specific its not the command its just the text not showing up on the screen
![image](https://user-images.githubusercontent.com/26629860/231306920-32847d31-0515-420b-9fcd-f14ec88e7287.png)

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/26629860/231306956-f95eb9f8-428e-48e0-b887-dc1b047a50e3.png)
setting this to enabled

### Server version

![image](https://user-images.githubusercontent.com/26629860/231307105-16b14944-3f2e-430a-b669-75cc5c675d4c.png)

### ItemsAdder Version

3.4.1-r5

### ProtocolLib Version

4.8.0

### LoneLibs Version

1.0.24

**Comment by LoneDev6** [comment]
> Minecraft title command broken when loading in with title: enabled in config

You probably have forgot to set the `times`.
https://www.digminecraft.com/game_commands/title_command.php#:~:text=to%20fade%20in.-,The%20default%20is%2020%20game%20ticks%20(1%20second).,screen%20takes%20to%20fade%20out.

`/title @p times 40 120 60`
`/title @a actionbar {"text":"Get Ready!", "color":"light_purple"}`
