### ISSUE TITLE
being able to put furniture where there is solid blocks that are in the furniture hitbox

### ISSUE THREAD

**Issue by hazexo** [PluginBugs/Issues-ItemsAdder#2535]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

it lets me to put the furniture in a place that has solid blocks that are in the hitbox of the furniture. and when breaking the block it doesnt put the barrier back and you cant sit if its chair.

### Steps to reproduce the issue

just get the furniture solid hitbox and dont let people put it if there are blocks in that hitbox of the furniture

### Server version

Current: git-Purpur-1933 (MC: 1.19.3)*
* You are running the latest version

### ItemsAdder Version

3.4.1-r6

### ProtocolLib Version

5.0.0-SNAPSHOT-b614

### LoneLibs Version

1.0.24

### FULL server log

[latest (1).log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11222172/latest.1.log)

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/128522438/231757387-353ff3d0-72c7-414a-a9ca-1bf6f442701e.png)

**Comment by LoneDev6** [comment]
Please make a video, I don't understand what you mean.
