### ISSUE TITLE
blocks events feature to apply cooldown for everyone

### ISSUE THREAD

**Issue by umutardafiliz** [PluginBugs/Issues-ItemsAdder#2538]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

djarda2#4247

### Describe the solution you'd like

so i have a block that when you right click it executes a command. when i right click it it goes on cooldown for me. but other people don't have to wait it. i want a toggle option for other people to wait for it too.

### Is your feature request related to a problem?

no

### Describe alternatives you've considered

maybe something can be done with using skript but for every block a new object should be created

**Comment by LoneDev6** [comment]
This is more like something that must be integrated using Java and the ItemsAdder API other than something that must be added as a feature of the plugin.
I think you're trying to make an advanced machinery with some special behaviour, you'll encounter other limitations in the future so I think that it's better to implement it using a standalone plugin.

ItemsAdder API: https://itemsadder.devs.beer/developers/java-api
