### ISSUE TITLE
Players without permission are also able to destroy furniture.

### ISSUE THREAD

**Issue by Surtryyds** [PluginBugs/Issues-ItemsAdder#2542]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Surtr#6495

### What happened?

I found that players are able to destroy furniture even if they don't have permission to do so.

### Steps to reproduce the issue

Configuration of associated furniture:
royal_vase_3:
    display_name: royal_vase_3
    permission: royal.admin
    resource:
      material: PAPER
      generate: false
      model_path: royal_vase_3
    behaviours:
      furniture:
        fixed_rotation: true
        solid: false
        small: false
        entity: item_frame
        placeable_on:
          walls: false
          ceiling: false
          floor: true
I made sure I didn't have "royal.admin" access nor was it op, but I was able to drop it by left clicking on the home.

### Server version

git-Purpur-1858 (MC: 1.19.2)*

### ItemsAdder Version

ItemsAdder version 3.4.1-r6

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b606

### LoneLibs Version

LoneLibs version 1.0.24

**Comment by LoneDev6** [comment]
Permission tag is not meant for breaking/placing permission checking but for `/ia` command permissions.
For example:
`ia.user.ia.seeitem.royal.admin`

**Comment by Surtryyds** [comment]
> Permission tag is not meant for breaking/placing permission checking but for `/ia` command permissions. For example: `ia.user.ia.seeitem.royal.admin`
> 
> If you don't want people to break furniture in a specific area (like decorative spawn) you have to setup a worldguard region.

I want to use Residence to stop players from destroying ia's decorations, and after I set the flag to prohibit the destruction of the placement players can still destroy these decorations, is it only the worldgurad plugin that can do this to prohibit players from destroying decorations in itemsadder?
