### ISSUE TITLE
Use 2x2, 1x3, 1x2, 1x1 etc. recipes in any corner of the crafting table like in vanilla Minecraft

### ISSUE THREAD

**Issue by konfix** [PluginBugs/Issues-ItemsAdder#2545]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Hello,
I have defined custom 2x2 recipes for my custom blocks. The issue with them is that they don't work properly.
They work fine in survival inventory's 2x2 crafting table, but they don't work in the 3x3 crafting table (block).

The only way you can make them work in 3x3 crafting tables is by using upper-right slots. Upper-left, down-left, down-right slots don't work, the result item is empty. However, when I try to get the item from the result (even though it's empty), it will play a sound as if something is there.

I have tried both methods from the wiki for creating 2x2 recipes, but none of them work properly.

See video for explanation.

### Steps to reproduce the issue

1. Survival gamemode, open the inventory and create a 2x2 custom item -> works
2. Place a crafting table block, open it, try making the 2x2 shape for that custom item -> doesn't work
3. Move the items to the top-right corner -> works

### Server version

Current: git-Purpur-1962 (MC: 1.19.4)*
Previous: git-Purpur-1956 (MC: 1.19.4)
* You are running the latest version

### ItemsAdder Version

ItemsAdder version 3.4.1-r6

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b631

### LoneLibs Version

LoneLibs version 1.0.24

### FULL server log

Not needed, there are 0 errors/notes/warnings

### Problematic items yml configuration file (optional)

```shell
----------
METHOD 1
----------
recipes:
  crafting_table:
    red_concrete_bricks:
      enabled: true
      pattern:
      - XZZ
      - XZZ
      ingredients:
        Z: RED_CONCRETE
      result:
        item: mystic:red_concrete_bricks
        amount: 1
----------
METHOD 2
----------
recipes:
  crafting_table:
    red_concrete_bricks:
      enabled: true
      pattern:
      - ZZ
      - ZZ
      ingredients:
        Z: RED_CONCRETE
      result:
        item: mystic:red_concrete_bricks
        amount: 1
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://user-images.githubusercontent.com/66477781/232333511-4a017e98-7e66-4545-b786-50041839aff1.mp4

**Comment by LoneDev6** [comment]
Will be checked, anyway the feature was tested extensively so it's strange, it should work just fine.

**Comment by IPECTER** [comment]
@LoneDev6 I have same problem.

**Comment by LoneDev6** [comment]
> @LoneDev6 I have same problem.
> 
> ```yaml
> - A
> - A
> - S
> ```
> 
> ![image](https://user-images.githubusercontent.com/80433772/233966474-0cc161cf-08c7-46c5-bc01-a8c0d2368609.png)

Please provide more details of why this is not working and how you expect the recipe to work.

To be honest I don't see why your players would need to craft the sword like that, just create a 3x3 recipe in this case.
```yml
- XAX
- XAX
- XSX
```

The 2x2 recipes were extensively tested and worked fine.
Some examples can be found on the wiki and on my default pack.
https://itemsadder.devs.beer/plugin-usage/adding-content/recipes/crafting#2x2-recipe
https://github.com/search?q=repo%3AItemsAdder%2FDefaultPack+recipes&type=code

**Comment by IPECTER** [comment]
> > @LoneDev6 I have same problem.
> > ```yaml
> > - A
> > - A
> > - S
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/80433772/233966474-0cc161cf-08c7-46c5-bc01-a8c0d2368609.png)
> 
> Please provide more details of why this is not working and how you expect the recipe to work.
> 
> To be honest I don't see why your players would need to craft the sword like that, just create a 3x3 recipe in this case.
> 
> ```yaml
> - XAX
> - XAX
> - XSX
> ```
> 
> The 2x2 recipes were extensively tested and worked fine. Some examples can be found on the wiki and on my default pack. https://itemsadder.devs.beer/plugin-usage/adding-content/recipes/crafting#2x2-recipe https://github.com/search?q=repo%3AItemsAdder%2FDefaultPack+recipes&type=code

If you do this, there's a problem that's different from the vanilla method
In the first place, this problem is with ItemsAdder

**Comment by LoneDev6** [comment]
I still don't understand why you're not creating the recipe like this:
> ```yaml
> - XAX
> - XAX
> - XSX

**Comment by IPECTER** [comment]
> 왜 다음과 같은 레시피를 만들지 않는지 여전히 이해가 되지 않습니다.
> 
> > ```yaml
> > - XAX
> > - XAX
> > - XSX
> > ```
> 
> 또한 이 문제 보고서는 2x2 레시피 문제에 관한 것이므로 보고하는 문제는 해당 문제와 관련이 없습니다.

I will make  a new issue.

**Comment by LoneDev6** [comment]
Is this implementation really needed?
People since 1.13 use the recipebook to craft items.
This would just increase the amount of work to do on the server side to calculate recipes.

**Comment by konfix** [comment]
> Is this implementation really needed? People since 1.13 use the recipebook to craft items, no one remembers them all. This would just increase the amount of work to do on the server side to calculate recipes.

Were you referring to my issue or the issue of the person above? I need the 2x2 recipes working

**Comment by LoneDev6** [comment]
I was referring to the 2x2 issue report.
Basically I'm asking if it's something really needed to be implemented since 2x2 recipes work fine if yoiu fit ingredients in the top slots.

I ask because I'd avoid implementing this since it would increase the workload on the server (recipes are heavy).
People use the recipebook to craft stuff since 1.13 so I don't really think it's something players would be bothered with.

Let me know what you think

**Comment by LoneDev6** [comment]
Various examples of the fix:

![image](https://github.com/user-attachments/assets/0f585236-268f-478b-a1ca-201ae13a07d2)
![image](https://github.com/user-attachments/assets/4ce0f904-0a52-4dbf-9764-f5e913d0d4ff)
![image](https://github.com/user-attachments/assets/04ecb40c-72a4-4fcf-980f-d4e4051808fd)
![image](https://github.com/user-attachments/assets/e7e342cd-b2fe-499e-843b-7e58928d68ca)
![image](https://github.com/user-attachments/assets/72e8c5d4-485d-43b1-96c6-296f9955093c)
![image](https://github.com/user-attachments/assets/f9d2baef-1975-440e-8d61-b906e11968b7)
![image](https://github.com/user-attachments/assets/511a4458-813b-4944-be0f-9f04f0c722c0)
![image](https://github.com/user-attachments/assets/43649b6f-92e9-4053-ae6b-3b33d01b363a)

**Comment by IPECTER** [comment]
Very good job 1.5 year :)
Never changed things is very awesome tlqkf

**Comment by LoneDev6** [comment]
> Very good job 1.5 year :) Never changed things is very awesome tlqkf

Better than never 🗿❤️
