### ISSUE TITLE
smooth transition between entity animations

### ISSUE THREAD

**Issue by kl1sty** [PluginBugs/Issues-ItemsAdder#2546]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

kl1styy's#6069

### Describe the solution you'd like

I would like the transition between animations to not be as abrupt as it is now. I mean that when walking, attacking, etc. the animation changes very quickly and abruptly, which hurts my eyes and others. i would like you to add smooth transition between animations as it will be much easier for my players to live with it :) hope you can add this and don't reject this suggestion as it will solve suicides all over the world ))))

### Is your feature request related to a problem?

most likely yes than no, because this feature will be very useful

### Describe alternatives you've considered

so far haven't found any alternatives

### Additional context

I hope for you dear LoneDev

**Comment by LoneDev6** [comment]
The easiest solution is to basically make sure your animations all end with the same frame.
This prevents the issue.
