### ISSUE TITLE
Bypass permissions to use emojis in chat

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#2555]
Continuation of: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2330#issuecomment-1513469360

> Hi, I know it's closed and I'm sorry but still happens to me on version [3.4.1-r5] of IA, Purpur 1.19.3, LoneLibs 1.0.24, any solutions? Could be Purpur 1.19.3? Thanks and sorry again

> Im using Purpur 1.19.3-1933, latest Items Adder and LoneLibs, I was using ChatManager plugin for chat, I changed it to normal EssentialsChat, and still the same problem. Plugins that may conflict with chat could be NoEncryption 1.19.3-5.1. I have '*' permissions and this does not affect to me, but the default people can write ::\heart:: and it appears the emoji. And that's it, sorry again to write on this closed issue.
> 
> SERVER LOG: [LOG](https://pastebin.com/3ywNQwQn)
> 
>  https://user-images.githubusercontent.com/46499704/232843381-227ac183-99a2-4b3f-8d9a-7d50df85e7aa.mp4

**Comment by LoneDev6** [comment]
I'll do some tests and let you know, very strange

**Comment by TnTVlogs** [comment]
Hi, any news?

**Comment by TnTVlogs** [comment]
Sorry, I didn't saw the message, my fault. Just to add something, when I'm on vanish (Essentials vanish), players can't see my rank or emojis or text effects, it appears like ":founder:", ":\heart:" and "r Ranibow test".
Thanks for all.

**Comment by LoneDev6** [comment]
> Sorry, I didn't saw the message, my fault. Just to add something, when I'm on vanish (Essentials vanish), players can't see my rank or emojis or text effects, it appears like ":founder:", ":\heart:" and "r Ranibow test". Thanks for all.

I don't understand.
Anyway please open a new issue, do not use the same issue report for various reports.
