### ISSUE TITLE
REAL_TRANSPARENT block switch to different model when copy&paste with rotate.

### ISSUE THREAD

**Issue by CactusMikaz** [PluginBugs/Issues-ItemsAdder#2558]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Marcus#4607

### What happened?

REAL_TRANSPARENT block switch to different model when copy&paste with rotate.

I know the custom block with REAL_TRANSPARENT is using different blockstates to create lot of block.
because of that, copy and rotate will change blockstates and paste it, I think that cause model switch to another.

### Steps to reproduce the issue

1. copy a building with REAL_TRANSPARENT block int it.
2. rotate 90.
3. paste it.

### ItemsAdder Version

3.3.0b-r5

### ProtocolLib Version

v5.0.0-SNAPSHOT-b614

### LoneLibs Version

1.0.22

### Screenshots/Videos (you can drag and drop files or paste links)

Uploading Minecraft 1.17.1 - 多人遊戲（第三方伺服器） 2023-04-19 22-59-48.mp4…

**Comment by LoneDev6** [comment]
Are you using the worldedit addon? Install it if you don't have it.
https://www.spigotmc.org/resources/addon-itemsadder-worldedit.79012/
