### ISSUE TITLE
Armor knockback Resistance Attribute Modifier set to 10 instead of 1

### ISSUE THREAD

**Issue by tyepavitt** [PluginBugs/Issues-ItemsAdder#2561]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Set armors Knockback Resistance attribute modifier to 1 in custom armors yml file and when I go into the ia menu and get the armor, the Knockback Resistance for the armor is set to 10. I have 3 attribute modifiers set. armor, armor toughness and knockback resistance. Seems to only effect the knockback resistance attribute modifier though as when I tried setting the armor one to 1, it sets correctly.

### Steps to reproduce the issue

1. Create custom armor yml file.
2. Add knockback resistance attribute modifier and set it to 1
3. Go into minecraft and get the custom armor piece
4. Check the knockback resistance attribute for the armor piece

### Server version

Server is running Pufferfish+ version git-PufferfishPlus-53 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 70d4ad0 on HEAD)

### ItemsAdder Version

ItemsAdder version 3.4.1-r6

### ProtocolLib Version

ProtocolLIB version 5.0.0-SNAPSHOT-b626

### LoneLibs Version

LoneLibs version 1.0.24

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: lifesteal
armors_rendering:
  god_armor:
    color: '#ddb804'
    layer_1: armor/god_armor_layer_1
    layer_2: armor/god_armor_layer_2
    emissive_1: armor/god_armor_layer_1_e
    emissive_2: armor/god_armor_layer_2_e
    use_color: false
items:
  god_helmet:
    display_name: "&bKing's Helmet" #Put the name of your armor here
    resource:
      model_id: 1004
      generate: true
      textures:
      - item/armor/god_helmet.png
    durability:
      max_custom_durability: 407
    specific_properties:
      armor:
        slot: head
        custom_armor: god_armor
    enchants:
      - PROTECTION_EXPLOSIONS:4
      - PROTECTION_FIRE:4
      - MENDING
      - PROTECTION_PROJECTILE:4
      - PROTECTION_ENVIRONMENTAL:4
      - DURABILITY:3
    attribute_modifiers:
      head:
        armor: 3
        armorToughness: 3
        knockbackResistance: 1
  god_chestplate:
    display_name: "&bKing's Chestplate" #Put the name of your armor here
    resource:
      model_id: 1005
      generate: true
      textures:
      - item/armor/god_chestplate.png
    durability:
      max_custom_durability: 592
    specific_properties:
      armor:
        slot: chest
        custom_armor: god_armor
    enchants:
      - PROTECTION_EXPLOSIONS:4
      - PROTECTION_FIRE:4
      - MENDING
      - PROTECTION_PROJECTILE:4
      - PROTECTION_ENVIRONMENTAL:4
      - DURABILITY:3
    attribute_modifiers:
      chest:
        armor: 8
        armorToughness: 3
        knockbackResistance: 1
  god_leggings:
    display_name: "&bKing's leggings" #Put the name of your armor here
    resource:
      model_id: 1006
      generate: true
      textures:
      - item/armor/god_leggings.png
    durability:
      max_custom_durability: 555
    specific_properties:
      armor:
        slot: legs
        custom_armor: god_armor
    enchants:
      - PROTECTION_EXPLOSIONS:4
      - PROTECTION_FIRE:4
      - MENDING
      - PROTECTION_PROJECTILE:4
      - PROTECTION_ENVIRONMENTAL:4
      - DURABILITY:3
    attribute_modifiers:
      legs:
        armor: 6
        armorToughness: 3
        knockbackResistance: 1
  god_boots:
    display_name: "&bKing's Boots" #Put the name of your armor here
    resource:
      model_id: 1007
      generate: true
      textures:
      - item/armor/god_boots.png
    durability:
      max_custom_durability: 481
    specific_properties:
      armor:
        slot: FEET
        custom_armor: god_armor
    enchants:
      - PROTECTION_EXPLOSIONS:4
      - PROTECTION_FIRE:4
      - MENDING
      - PROTECTION_PROJECTILE:4
      - PROTECTION_ENVIRONMENTAL:4
      - DURABILITY:3
    attribute_modifiers:
      feet:
        armor: 3
        armorToughness: 3
        knockbackResistance: 1
```

**Comment by LoneDev6** [comment]
Is this fixed?

**Comment by tyepavitt** [comment]
> Is this fixed? Why did you close the report? Thanks

Yeah managed to find out how to fix it by setting the knockback resistance value to 0.1

**Comment by IanRockwell** [comment]
Would have never found the solution to this problem if this issue didn't exist. There's no way this is intended behavior, this is definitely a bug.

**Comment by LoneDev6** [comment]
This is how it works in vanilla, seems.
https://minecraft.wiki/w/Attribute
> The scale of horizontal knockback resisted from attacks and projectiles. Vertical knockback is not affected. Does not affect explosions. 
1.0 is 100% knockback resistance. 0.4 means 60% of knockback is applied.
