### ISSUE TITLE
Translate NBT tag does not apply

### ISSUE THREAD

**Issue by evilsaloon** [PluginBugs/Issues-ItemsAdder#2563]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

evilsaloon#3438

### What happened?

Item with custom NBT tag that contains "translate" attribute does not apply.

### Steps to reproduce the issue

1. Add item from sample items.yml
2. /iazip
3. /iaget item
4. NBT tag does not apply

### Server version

Current: git-Purpur-1962 (MC: 1.19.4)*
Previous: git-Purpur-1858 (MC: 1.19.2)
* You are 1 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### ItemsAdder Version

ItemsAdder version 3.4.1-r6

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-636

### LoneLibs Version

LoneLibs version 1.0.24

### FULL server log

https://pastebin.com/Jnyc1Rmd

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: testserv
items:
  testium:
    #display_name: testium
    permission: testserv
    nbt: "{MYTHIC_ITEM_VERSION:1,MYTHIC_TYPE:\"testium\", display:{Name:'{\"italic\":false,\"translate\":\"item.testserv.testium\"}'}}"
    resource:
      material: IRON_INGOT
      generate: true
      textures:
      - item/testium.png
```

### Other files, you can drag and drop them here to upload. (optional)

This is the bugged NBT tag:

```shell
[12:10:04] [Render thread/INFO]: [CHAT] evilsaloon has the following entity data: {id: "minecraft:iron_ingot", tag: {itemsadder: {id: "testium", namespace: "testserv"}, MYTHIC_ITEM_VERSION: 1, display: {Name: '{"italic":false,"color":"white","text":"testium"}'}, CustomModelData: 10000, MYTHIC_TYPE: "testium"}, Count: 1b}
```

This is how the NBT tag should be:

```shell
[12:38:08] [Render thread/INFO]: [CHAT] evilsaloon has the following entity data: {id: "minecraft:iron_ingot", tag: {itemsadder: {id: "testium", namespace: "testserv"}, MYTHIC_ITEM_VERSION: 1, display: {Name: '{"italic":false,"translate":"item.testserv.testium"}'}, CustomModelData: 10000, MYTHIC_TYPE: "testium"}, Count: 1b}
```

**Comment by evilsaloon** [comment]
Seems to be #2155 recurring again :/

**Comment by LoneDev6** [comment]
Will be checked, thanks!
