### ISSUE TITLE
Random Namespace Item Give Command.

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-ItemsAdder#2567]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

sircraftypants#4875

### Describe the solution you'd like

Based on a specific namespace, the ability to run a namespace give command that will choose at random, item(s) under that namespace with a random number.

This will allow players to setup clickable blocks/items that can randomly reward them.
This will allow players to set one reward command for game plugins by placing the rewards all under the same namespace.
This will allow players to set one command for vault crates and crates instead of multiple commands if they wished.
This will allow Admins to setup multiple namespace categories so they can reward players at will using each namespace.

Lets say i have an armor and weapon set i want to allow players to be able to win and collect. I can just ad the random namespace command to the games rewards. Or Admin can run the one command for live events.

The possibilities are numerous and all it takes is a random namespace give command.

`/iagiverandom %player_name% namespace:random_item 1-64`

Each Item under the namespace could also be given a % chance.

`  chance:`
 `    namespace:item_name
      chance: 30%`

### Is your feature request related to a problem?

no

### Describe alternatives you've considered

nothing out there that does it so no alternatives.

### Additional context

I think this would be a game changer for Itemsadder which already runs the namespace system and has a give command.

**Comment by LoneDev6** [comment]
I think this is an out of scope feature which can be integrated with an external plugin.
I don't think it's something that is worth implementing directly into ItemsAdder itself.
You might try asking on the Discord #coding channel, someone might help you coding that.
I wish I had the time to help everyone, sadly it's not possible.
