### ISSUE TITLE
MMOITEM Custom Blocks Resource Pack now supported

### ISSUE THREAD

**Issue by BearLeonLight** [PluginBugs/Issues-ItemsAdder#2571]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

不知道在做啥的貓#9224

### Describe the solution you'd like

"Enable automatic conversion of multipart to variants or allow multipart to continue to be used."

### Is your feature request related to a problem?

"I use MMOITE for my custom items and blocks, but my texture pack uses 'multipart' and I don't know how to convert it to 'variants'. I have searched for information online, but I still don't know how to convert it. I was using version 3.3.1 before, but after updating, it requires the use of variants and I don't know how to handle it."

### Describe alternatives you've considered

"I have tried to convert it, but I really cannot. It is difficult for me to understand how to convert it. I only know how to set up a simple texture pack."

**Comment by BearLeonLight** [comment]
> `multipart` method to create blocks was always been a bad idea because it has downsides. The `variants` method is better.
> 
> You can get an example here, you basically just have to set the blockstate in a single string instead of using the list.
> 
> ```java
> {
>   "variants": {
>     "west=true,up=true,south=true,north=true,east=true,down=true": {
>       "model": "block/original/brown_mushroom_block"
>     },
>     "down=false,east=false,north=false,south=false,up=false,west=false": {
>       "model": "newtrees:ia_auto_gen/orange_tree_log"
>     },
>     "down=false,east=false,north=false,south=false,up=false,west=true": {
>       "model": "newtrees:ia_auto_gen/end_tree_leaves"
>     }
>   }
> }
> ```

"Request for Document Update:

After testing, I found that in order to use MMOITEM properly, the following settings need to be adjusted:
- disable-REAL: true
- disable-REAL_TRANSPARENT: true

Please update the document accordingly."

**Comment by LoneDev6** [comment]
https://itemsadder.devs.beer/compatibility-with-other-plugins/compatible/mmoitems/fix-blocks-problem
`disable-REAL_TRANSPARENT: true` shouldn't be needed if MMOItems is not using chorus to create blocks.

**Comment by BearLeonLight** [comment]
But after I turned off the above two, I was able to place MMITEM Block correctly.
