### ISSUE TITLE
Colored liquids do not work on 1.19.4

### ISSUE THREAD

**Issue by 100petr** [PluginBugs/Issues-ItemsAdder#2577]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

pitilon#6950

### What happened?

Colored liquids do not work on 1.19.4

### Steps to reproduce the issue

Install Colored liquids
Start the server
The server writes errors and does not turn on

### Server version

purpur-1.19.4. 1963

### ItemsAdder Version

3.4.1-r6

### ProtocolLib Version

5.0.0-SNAPSHOT-636

### LoneLibs Version

1.0.24

### FULL server log

https://pastebin.com/Xa6NLMfC

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/2525
