### ISSUE TITLE
Fullscreen GUI

### ISSUE THREAD

**Issue by EbaaCode** [PluginBugs/Issues-ItemsAdder#2579]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Ebaa#7925

### Describe the solution you'd like

Hey, I stumbled across your new plugin CosmeticsCore, and I think it looks great! and I was particularly impressed with the full-screen menus and was wondering if there was any way we could achieve something similar with AI.

I tried creating a custom GUI using a large black font image to achieve the black background, but I had trouble finding a way to hide the inventory items. So, if it's not possible to get a way to replicate the CosmeticsCore menus in AI, I would really appreciate a way for hiding inventory items maybe.

Clearing the players inventory and then placing them back after the menu is closed could be one way I thought.

Thanks so much for your time and great work!

Images attached are: 
- My own attempt with the large black font image and inventory items showing.
- Screenshot from OriginRealms with a fullscreen GUI (Press Esc to close).
- Screenshot of menu from the CosmeticsCore trailer.

![my_attempt](https://user-images.githubusercontent.com/62425957/235328372-74c42b03-66dc-414e-acd0-ce31d829f059.png)
![originrealms](https://user-images.githubusercontent.com/62425957/235328374-72decc71-a6cd-4bf2-a9c7-50de940059aa.png)
![CosmeticsCore](https://user-images.githubusercontent.com/62425957/235328371-6d4def5f-8b97-46c0-8445-b0fa002e1227.png)

### Is your feature request related to a problem?

.

### Describe alternatives you've considered

.

### Additional context

.

**Comment by LoneDev6** [comment]
Hello, this is not a place to ask for support or ideas for other plugins.
Anyway it just uses packets to hide inventory, nothing impossible to do. You can find a solution reading the packets documentation.
https://wiki.vg/Protocol
