### ISSUE TITLE
Incompitable with Cosmetics core (ballons) and sitiable block

### ISSUE THREAD

**Issue by DxrkCat** [PluginBugs/Issues-ItemsAdder#2581]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

If a player has a ball and sits on a custom block that can be siton, then the player sits in place of the ball. Where the ball is in position, that's where the player will sit on the Armorstand.

### Steps to reproduce the issue

1. Take ballon in wardrobe
2. Click to sitable block
MAGIC

### Server version

> ver
[12:20:04 INFO]: Checking version, please wait...
[12:20:04 INFO]: Current: git-Purpur-1966 (MC: 1.19.4)*
Previous: git-Purpur-1963 (MC: 1.19.4)

### ItemsAdder Version

> ver ItemsAdder
[12:20:12 INFO]: ItemsAdder version 3.4.1-r6
[12:20:12 INFO]: Customized Minecraft without client mods!
[12:20:12 INFO]: Website: devs.beer
[12:20:12 INFO]: Author: LoneDev

### ProtocolLib Version

> ver ProtocolLib
[12:20:18 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-636
[12:20:18 INFO]: Provides read/write access to the Minecraft protocol.
[12:20:18 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

> ver LoneLibs
[12:20:23 INFO]: LoneLibs version 1.0.24
[12:20:23 INFO]: Collection of libs used by my plugins
[12:20:23 INFO]: Authors: LoneDev and others

### Other files, you can drag and drop them here to upload. (optional)

> ver CosmeticsCore
[12:20:31 INFO]: CosmeticsCore version 1.2.2

### Screenshots/Videos (you can drag and drop files or paste links)

https://user-images.githubusercontent.com/124828932/235352640-880f8f8d-62b4-4b34-b01e-3816351ca38d.mp4

**Comment by DxrkCat** [comment]
Addendum: When you turn on /emote, cosmetics are not lost

**Comment by LoneDev6** [comment]
What is `Click to sitable block`?
How was it created?

**Comment by DxrkCat** [comment]
> What is `Click to sitable block`? Please share the YML ItemsAdder configuration to create that sittable block.

sitable (click rmb sit)

**Comment by DxrkCat** [comment]
I right-click on the bench and have a cosmetic in the form of a ballon and I sit on the position where the ballon was.
  outdoor_bench:
    display_name: "Уличная скамейка"
    permission: outdoor
    resource:
      material: PAPER
      generate: false
      model_path: furniture/outdoor/outdoor_bench
    behaviours:
      furniture:
        gravity: false
        fixed_rotation: true
        small: false
        solid: true
        opposite_direction: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 2
          height: 1
          width_offset: -0.5
        sound:
          place:
            name: block.wood.place
          break:
            name: block.wood.break
      furniture_sit:
        sit_height: 0.9
