### ISSUE TITLE
Missing "texture" file - only texture.png

### ISSUE THREAD

**Issue by wryel2000** [PluginBugs/Issues-ItemsAdder#2588]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

i create a custom mob with a itemadder,

when i create new mob, missing 1 file on this locations >
/plugins/ItemsAdder/contents/cut/resourcepack/assets/custom/textures/entity/cutzombie_converted
in folder only create a "texture.png, not create other texture.file

Im using correct version blockbench, and last version extensions itemadders

i follow the process correct.

I was able to create once and see with i need this "file" to mob work correct.

Any one have a ideia why de blockbench "itemadders extesniso' not create this file?

### Steps to reproduce the issue

1- in block bench
2- go to convert
2 - in-convert export itemadders sasession
3 - open de ASSETS create and search a "textura/../entity/"mobname" (have only "texture.png, dont have a texture.file"

### Server version

This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### ItemsAdder Version

 ItemsAdder version 3.4.1-r5

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-636

### LoneLibs Version

LoneLibs version 1.0.24

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: cutzombie
entities:
  cutzombie:
    display_name: "cutzombie"
    type: ZOMBIE
    model_folder: entity/cutzombie_converted
    silent: true
    can_sun_burn: false
    speed:
      movement: 0.3
      flying: 0
    max_health: 20
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/101683845/235703276-78c562cd-63a9-4f6a-91a9-deb693b87012.png)

only create this img, not create other file

**Comment by LoneDev6** [comment]
Try again by creating your project in another folder, it works fine for me and was tested with plenty of models.
There is probably a little mistake.

**Comment by wryel2000** [comment]
i save .iaentitymodel and export on itemadders. but not create the file when i need,
i try in other machine and not work.

dont create a "file" texture, only "texture.png"

**Comment by wryel2000** [comment]
Lone, i need solution for this, i buy this plugin to use this.

model.itemadders link to u see: https://drive.google.com/file/d/1GSE83KLNmbUFpnJWg5X7iYYLlVSsobI4/view?usp=share_link

i tryng any options, forms, versions blockbench, execution mode e nothing.
dont create a "file texture" em texture/entity/, only create "texture.png"
