### ISSUE TITLE
Texture ModelEngine Broken

### ISSUE THREAD

**Issue by ynnniV** [PluginBugs/Issues-ItemsAdder#2590]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

So i followed that: https://itemsadder.devs.beer/compatibility-with-other-plugins/compatible/modelengine
The error, i think, is from model engine. But just want to know if is fixable in some way.

If i do the /meg reload and after the /iazip and do the things for dropbox and reload and texture, the custom mobs doesnt show in game with a texture. If i join with a Optifine version, it will show in a good way. Those problems is after the 1.19.3. So i think the change of loading texture from minecraft doing something. If i dont touch anything the mob showing me like that:

![image](https://user-images.githubusercontent.com/9847632/235784152-7bbce998-7d74-4460-97c7-471a1062947c.png)

If i change the things on the texture folders the mobs (all of them) showing me with some pieces of texture and not full textured. Im doing wrong something?

**LibsDisguises Version**
LibsDisguises 10.0.32 SNAPSHOT

**Model Engine**
Model Engine R3.1.7

**MythicMobs**
MythicMobs 5.2.6-0819d467

### Steps to reproduce the issue

Just followed that tutorial: https://itemsadder.devs.beer/compatibility-with-other-plugins/compatible/modelengine

### Server version

git-Pufferfish-67 (MC: 1.19.4)

### ItemsAdder Version

ItemsAdder 3.4.1-r6

### ProtocolLib Version

ProtocolLib 5.0.0 SNAPSHOT 638

### LoneLibs Version

LoneLibs 1.0.24

**Comment by ynnniV** [comment]
There is no bug at all.  Fixed it.
ModelEngine overwriting when u do /iazip. I just edited the mobs from entity to item and removed the "resource pack" of ModelEngine and the texture showing good. Example:

![image](https://user-images.githubusercontent.com/9847632/235796372-62137cdb-cc86-4d3c-a453-b081e149ef3d.png)

**Comment by LoneDev6** [comment]
Both the issue and the solution are not clear

**Comment by ynnniV** [comment]
Sorry, my bad to explain bad.
When i'll do a /iazip and configured in a good way the path of modelengine the texture loaded on server (to 1.19.3 to 1.19.4) are black and purple (missing texture).
To fix this i just removed the modelengine path into the config of the ItemsAdder, like that i needed just to edit the modelengine folders from entity to item. Like that in newers version the texture is showing.

If you doesnt remove modelengine path into the config and you will do item edit and do the /iazip the ItemsAdder will load two types of texture and would be like a 50% of loading when is not true.

Hope i did a good explain.
