### ISSUE TITLE
MSPT value high is itemsadder?

### ISSUE THREAD

**Issue by Distolfix** [PluginBugs/Issues-ItemsAdder#2601]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Disto

### What happened?

I think your plugin itemsadder have a problem make me MSPT value high 

![image](https://user-images.githubusercontent.com/73421268/236408011-4500e60b-5464-41c4-be60-3c06b7f05fb4.png)

![image](https://user-images.githubusercontent.com/73421268/236408087-c76a2905-0daf-42b6-9487-278eac21ef83.png)

### Steps to reproduce the issue

spark profiler:

https://spark.lucko.me/4Rhaxrsm11

### Server version

![image](https://user-images.githubusercontent.com/73421268/236408185-26d03e1f-a142-45a7-b998-fdb9d72d6f4f.png)

### ItemsAdder Version

![image](https://user-images.githubusercontent.com/73421268/236408298-3358fce2-b643-409f-93f7-af6903aaed1c.png)

### ProtocolLib Version

![image](https://user-images.githubusercontent.com/73421268/236408731-81ebf3d5-2a4c-4ff8-a0a8-2a9187a0bd14.png)

### LoneLibs Version

![image](https://user-images.githubusercontent.com/73421268/236408751-84f67895-ffb2-4970-8677-2cea338acdaa.png)

**Comment by LoneDev6** [comment]
Your link doesn't work.
![image](https://user-images.githubusercontent.com/27242001/236792011-fd08b36e-1b92-471f-a071-d7d0d8849b2b.png)

Somewhere you have A LOT of things going on fire.
If you don't use custom fire you can disable it in config.yml of ItemsAdder, this will stop that event from being called a lot.
`disable-FIRE: true`
