### ISSUE TITLE
ResourcePackBroadcast message & colors not being replaced

### ISSUE THREAD

**Issue by 100petr** [PluginBugs/Issues-ItemsAdder#2608]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

ResourcePackBroadcast does not display colors (&) after updating placeholderapi

### Steps to reproduce the issue

Download ia + Resource Pack Broadcast + papi.
Connect to the server
See what the sent message looks like

### Server version

Current: git-Purpur-1967 (MC: 1.19.4)

### ItemsAdder Version

3.4.1b

### ProtocolLib Version

5.0.0-SNAPSHOT-639

### LoneLibs Version

1.0.24

### Screenshots/Videos (you can drag and drop files or paste links)

https://www.spigotmc.org/threads/resourcepackbroadcast.485929/#post-4446623
How it looks now (it takes the color from essentials via the placeholder %essentials_nickname%)
![image](https://user-images.githubusercontent.com/29830635/236615311-1d6b0dcf-2f71-41de-9b12-be892119e333.png)

How it should look (the color of the name from the placeholder should apply only to it and the rest of the text should have the set color)
![image](https://user-images.githubusercontent.com/29830635/236615314-81f3e0c9-fd2d-4cc4-9233-6636b9f33929.png)

**Comment by LoneDev6** [comment]
Will be checked, sorry I had too many requests to handle

**Comment by LoneDev6** [comment]
Why is it preventing you to update PAPI? It's not clear

**Comment by LoneDev6** [comment]
Hello,
Your report will be looked into as soon as possible, I'm just back from the summer break and I finally have access to my PC.
Rest assured that your questions won't be ignored.
Thanks a lot for the patience!

**Comment by LoneDev6** [comment]
I scheduled it for the upcoming update

**Comment by LoneDev6** [comment]
Thanks a ton for your huge patience.
I published an update (tested it and working correctly).
Download it here: https://www.spigotmc.org/resources/resourcepackbroadcast.88318/
