### ISSUE TITLE
[Suggestion] Hi i'm opening this suggestion for a textures with Optifine Mod 1.15.2

### ISSUE THREAD

**Issue by TnoZamas** [PluginBugs/Issues-ItemsAdder#261]
I wanna make a custom items like Elytra with a red color but it only show on item, and not im displayed when u equipped it. Thx u for u time LoneDev :)

**Comment by LoneDev6** [comment]
Thanks I will add a lot of optifine only features in the next updates, I want to add also 1.8 to 1.13 support with optifine.

**Comment by Deathroner** [comment]
> Gracias Agregaré muchas características de optifine solo en las próximas actualizaciones, quiero agregar también soporte 1.8 a 1.13 con optifine.

Me parece excelente!!
