### ISSUE TITLE
Authme is showing passwords in console probably due to ItemsAdder

### ISSUE THREAD

**Issue by EpicPlayerA10** [PluginBugs/Issues-ItemsAdder#2623]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

EpicPlayerA10#3800

### What happened?

When someone execute `/login somepassword` then AuthMe prevents to print this in console. AuthMe adds [its own Log4j filter](https://github.com/AuthMe/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/output/Log4JFilter.java)

I wrote a small plugin to show all added log4j filters and it printed these three filters:
```
[15:25:44 INFO]: [TestPlugin] org.apache.logging.log4j.core.filter.MarkerFilter
[15:25:44 INFO]: [TestPlugin] ia.nms.aX.ca
[15:25:44 INFO]: [TestPlugin] fr.xephi.authme.output.Log4JFilter
```
And here you can see that ItemsAdder also has its own log4j filter.

So I'm writing here because maybe ItemsAdder is simply allowing to log all messages and skipping other filters.

Without ItemsAdder, Authme works fine.

### Steps to reproduce the issue

1. Install ItemsAdder and [AuthMe](https://ci.codemc.io/job/AuthMe/job/AuthMeReloaded/)
2. Register or login using `/register somepasswd somepasswd` or `/login somepasswd`

! In console you should see: `SomePlayer issued server command: /login somepasswd`

### Server version

This server is running Paper version git-Paper-530 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 9daa019)

### ItemsAdder Version

ItemsAdder version 3.4.1c

### ProtocolLib Version

ProtocolLib version 5.0.0

### LoneLibs Version

LoneLibs version 1.0.24

**Comment by LoneDev6** [comment]
Strange since I make sure to avoid breaking other filters.
I'll make some tests directly with Authme.

**Comment by LoneDev6** [comment]
This is strange since I do make sure to avoid breaking other loggers.

Filter code: https://gist.github.com/LoneDev6/a39e90df630ecf9e96c894ef7685ad74
Registering / unregistering code: https://gist.github.com/LoneDev6/45f71d4e1ba6ca41db9fb352d43282d4

**Comment by EpicPlayerA10** [comment]
You should replace all `Filter.Result.ACCEPT` with `Filter.Result.NEUTRAL`

**Comment by LoneDev6** [comment]
Ah fuck, thanks for the tip! I'll make this change in the next release :D
