### ISSUE TITLE
INF pack load

### ISSUE THREAD

**Issue by tomdebom1** [PluginBugs/Issues-ItemsAdder#2629]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I have been trouble shooting fro 6 hours between 2 days and im having the same issue of the pack inf load  i tried all the fixes with no succes reinstalled it 2 times nothing watched 3 vids nothing did the guided wrote literal notes on it of what to do went over this page looking for the same problem the plugins i use are AdvancedEnchantments AdvancedRegionMarket AUpdater BetterRTP bStats BuycraftX ChestShop CommandSigns  CratesPlus CrazyAuctions DeadChest DropHeads Essentials Factions Geyser-Spigot GeyserSkinManager Graves ItemsAdder LandClaiming LifeSteal LPC LuckPerms MCStatsXY MMOItems MMOItemsMana MTVehicles Multiverse-Core Multiverse-Inventories Multiverse-PortalsMythicLib MythicMobs NametagEdit PlaceholderAPI PluginMetrics ProtocolLib pStats QualityArmory SimpleScore SimpleTpa SuperVanish TAB Timber TradeSystem update Updater Vault ViaBackwards ViaRewind ViaVersion voicechat Vulcan WorldEdit WorldGuard please help me ive been doing this for hours dont blow me off

### Steps to reproduce the issue

follow the guide the website has with the lastest version of itemadder

### Server version

paper 1.17.1

### ItemsAdder Version

ItemsAdder version 3.4.1c

### ProtocolLib Version

ProtocolLib Version 4.8.0

### LoneLibs Version

LoneLibs wont work

### FULL server log

it wont let me

**Comment by LoneDev6** [comment]
The only way to find out why the pack is infinitely loading is reading the CLIENT log. It contains info why the pack failed to load and entered the load loop bug (game bug, not ItemsAdder bug).

Read here how to do that: https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown
Read carefully please. It's the only way to fix the issue.

**Comment by tomdebom1** [comment]
i cant get lonelib to work it wont download on my many test server and my main also my texture pack log said nothing

**Comment by tomdebom1** [comment]
I've also tried this on like 4 different computers on different accounts its not that

**Comment by LoneDev6** [comment]
https://github.com/LoneDev6/SpigotUtilities/raw/master/LoneLibs.jar

**Comment by tomdebom1** [comment]
that doesn't help it wont work

**Comment by LoneDev6** [comment]
What do you mean by "it wont work"? Please explain.
- it doesn't download the file?
- the plugin gives an error? share it please.
- another issue?

please be specific when you answer or it will take more time to get helped.

**Comment by LoneDev6** [comment]
Also please share the FULL SERVER LOG.

**Comment by tomdebom1** [comment]
it doesn't download the file this one and ill send the server log might take a bit sorry

**Comment by LoneDev6** [comment]
I reuploaded it for you here, download it.
https://anonfiles.com/ue1763s5z7/LoneLibs_jar

Try to change connection and PC if you still can't download it.
More than [4673 ](https://pstats.devs.beer/plugin/bukkit/LoneLibs/5) server owners downloaded it correctly.

**Comment by LoneDev6** [comment]
Post your whole server log, I will help you.
