### ISSUE TITLE
Make armor and tools behave like in IC2 mod (with charge)

### ISSUE THREAD

**Issue by WataLaker37821** [PluginBugs/Issues-ItemsAdder#2631]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

DOGE#1690

### Describe the solution you'd like

Make tools and armor work while needed durability (charge) is left, but stop protecting player when there is no charge and stop digging (for example) when durability is 0 or not enough to perform one action

### Is your feature request related to a problem?

I wanted to make tools and armor like in a Industrial Craft 2 mod to make them being chargeable.

### Describe alternatives you've considered

I dont know any alternatives that i can suggest, its just what i've tried to make

### Additional context

If possible can you think about adding smth like behaviour of energy storages or energy generators for those armor / tools, just asking, cos it would be nice to use

**Comment by LoneDev6** [comment]
For now you can add `disappear_when_broken` to your armor pieces:
```yml
    durability:
      max_custom_durability: 1562
      disappear_when_broken: false
```

The only thing left to implement is to block the armor from protecting the player if `disappear_when_broken` is `false` and if durability is 0.

Do you think it would work for your idea?

**Comment by WataLaker37821** [comment]
> For now you can add `disappear_when_broken` to your armor pieces:
> 
> ```yaml
>     durability:
>       max_custom_durability: 1562
>       disappear_when_broken: false
> ```
> 
> The only thing left to implement is to block the armor from protecting the player if `disappear_when_broken` is `false` and if durability is 0.
> 
> Do you think it would work for your idea?

Thats what i've done, but armor keeps protection when durability is 0 or lower that value i've specified too, needed for taking one hit, i sent config of my armor on forum, got answer from a helper and he said that your plugin doesnt have such features yet. And if its possible, disable tools ability to dig/damage or any other things they do usually, when durability of a tool becomes lower than needed amount for one action, that would be great

**Comment by WataLaker37821** [comment]
do you still need more info about that enchancement? (just asking cos i dont know how you decide to take suggestions in your to-do list or not to take them)

**Comment by LoneDev6** [comment]
> The only thing left to implement is to block the armor from protecting the player if `disappear_when_broken` is false and if durability is 0.

This will be implemented in the next updates, as soon as I am able to

**Comment by LoneDev6** [comment]
I can't find a way to avoid the armor from protecting the player since it's a vanilla behaviour and can't be really changed.
For now I have no solution.

**Comment by WataLaker37821** [comment]
okay man, no problem, i found my solution by using your plugin for texturing (but once i had some error that wouldnt let me reload plugin even after the server restart so i removed some contents and added them back step by step so all ids and model data were a mess, every model switched ... that was a pain) but a new solution for item's functionality is ExecutableItems plugin

**Comment by LoneDev6** [comment]
Does ExecutableItems allow to stop armors from protecting the player when durability is 0?
