### ISSUE TITLE
Internal Exception: io.netty.handler.codec.DecoderException: Received unexcepted null component

### ISSUE THREAD

**Issue by QuestionCatcher** [PluginBugs/Issues-ItemsAdder#2636]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

QuestionCatcher#1480

### What happened?

**Problem was tested on two different Skyblock plugins:
SuperiorSkyblock2
Iridium Skyblock**

Server is on 1.16.5 with possibility to join on higher minecraft version(ViaVersion plugin).
Problem is only on higher version(1.19+. Tested with 1.16, 1.17, 1.18 and 0 problems)
Problem occurs when the resource pack(basic from the plugin wiki) is uploaded and properly configured on the server and also without it.

When a player dies on a world with islands created by the skyblock plugin he is kicked off the server. 
It is not possible to return to the server until the server is shut down and restarted.

In console/logs i have message that player disconnected from the server(in all logs, Skyblock server, proxy server) but player has message like in Title

### Steps to reproduce the issue

1. Add SuperiorSkyblock2/Iridium Skyblock plugin to your server
2. Add ItemsAdder, ProtocolLibs and Lonelibs to your server
3. Add(or not) resourcpack to ItemsAdder and set it up(without it there is a problem anyway)
4. Create and teleport to your island. 
5. Die.

### Server version

This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 3.4.1c

### ProtocolLib Version

ProtocolLib version 5.0.0

### LoneLibs Version

LoneLibs version 1.0.24

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11502913/latest.log)

### Screenshots/Videos (you can drag and drop files or paste links)

https://www.youtube.com/watch?v=HGAwr0jjjaY&ab_channel=QuestionCatcher
![kick message](https://github.com/PluginBugs/Issues-ItemsAdder/assets/73604198/b4516a47-b884-456e-82f2-814aacb050ed)

**Comment by LoneDev6** [comment]
Please let me know if this fixes the issue: https://github.com/PluginBugs/Issues-ItemsAdder/issues/1876#issuecomment-1243505369

> Solved on: https://github.com/PluginBugs/Issues-ItemsAdder/issues/1964

```yml
items:
  give_death_location_maps: false
```

**Comment by QuestionCatcher** [comment]
> Please let me know if this fixes the issue: [#1876 (comment)](https://github.com/PluginBugs/Issues-ItemsAdder/issues/1876#issuecomment-1243505369)
> 
> > Solved on: #1964
> 
> ```yaml
> items:
>   give_death_location_maps: false
> ```

Problem fixed. Sorry for creating a new thread and bothering you
 but I was sure there was no similar problem to mine.
 Thank you for help

**Comment by LoneDev6** [comment]
Was it fixed using the setting I sent? Or was it fixed in another way? Please explain how you fixed, thanks a lot
