### ISSUE TITLE
Player Emote

### ISSUE THREAD

**Issue by uploadx10** [PluginBugs/Issues-ItemsAdder#2640]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

XOXO#5678

### Describe the solution you'd like

+ head tracking hat item

### Is your feature request related to a problem?

no

### Describe alternatives you've considered

for more quality work

**Comment by LoneDev6** [comment]
Please elaborate.
