### ISSUE TITLE
Player Emote Support Hat Fashion

### ISSUE THREAD

**Issue by uploadx10** [PluginBugs/Issues-ItemsAdder#2642]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

XOXO#5678

### Describe the solution you'd like

I want Hat Fashion to follow the player's head while playing the emote. 

example video:
https://i.imgur.com/4G0qnai.gifv

### Is your feature request related to a problem?

Relevant, since it's supposed to follow the player's head while wearing a cosmetic item. In the future, I want to support both off hand / back.

### Describe alternatives you've considered

As a matter of fact, this should be resolved.

### Additional context

no more

**Comment by LoneDev6** [comment]
This bug was fixed long time ago.
Please update your plugin.
Delete your emotes file to make them regenerate, you might have some old broken emotes files. 

More info here: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2232#issuecomment-1418923784

**Comment by LoneDev6** [comment]
You have to ask the author to add the missing bone, they can get it from the new player emotes file included in the plugin.
Or you can do it if you have access to the blockbench emotes project.
