### ISSUE TITLE
to be able to have more than 1 item in a slot

### ISSUE THREAD

**Issue by DeathRyder35** [PluginBugs/Issues-ItemsAdder#2644]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

DeathRyder#0327

### Describe the solution you'd like

to be able to add stackable crafting for an item, EX have one item take 4 ingots for 1 slot.

### Is your feature request related to a problem?

no

### Describe alternatives you've considered

tryed to add it in config for that item and only accepted a single. 

### Additional context

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/134020884/d4c61479-f930-4ed7-8233-2f45525881b5)

**Comment by LoneDev6** [comment]
I already got asked about that on Discord and I cannot implement this without introducing duplication bugs and performance issues.

This also would probably require me to restructure the whole current recipes system and most likely introduce duplication bugs.
It's not something I'd generally do, considering now recipes system is polished and were tested for years.

If I were you I'd create a new type of item which can be crafted with, let's say, 3 ruby. It will be something like ruby_group.
You can the use ruby_group to craft some other complex recipe.
This simulates recipes which require an ingredient to have amount > 1.
And looks more vanilla.
It's exactly what I do for energy orbs in my default pack.
https://github.com/search?q=repo%3AItemsAdder%2FDefaultPack+energy&type=code
