### ISSUE TITLE
Text effects and hide scoreboard numbers feature don't seem to work with .ttf font's .

### ISSUE THREAD

**Issue by ItzASecret** [PluginBugs/Issues-ItemsAdder#2645]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

ItzASecretBoi#1300

### What happened?

I've realized for awhile now even with the scoreboard feature enabled to hide scoreboard numbers, I still had them, additionally I also couldn't use text effects such as "<rw Example!>", It just shows as "Example!" (No rainbow effect). I thought it was just some chat plugin interfering at first but after disabling custom-fonts it worked perfectly fine.

This a Minecraft limitation or bug? Didn't see anything about text effects + fonts on the wiki.

I was using the Terraria font if it matters, i'll link the exact file in the **"Other files, you can drag and drop them here to upload. (optional)"** Box.

### Steps to reproduce the issue

1. Enable custom font on Minecraft server.

2. Enable the hide scoreboard numbers feature with a scoreboard enabled. (I'm using TAB if that matters)

3. Attempt to talk in chat using chat effects, such as <rw BRUH!>

You'll see in steps 2. and 3. the features are not working.

### Server version

19.05 01:45:57 [Server] [INFO] Checking version, please wait...
19.05 01:45:57 [Server] [INFO] This server is running Paper version git-Paper-"bcd8dc2" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: bcd8dc2)
19.05 01:45:57 [Server] [INFO] You are running the latest version
19.05 01:45:57 [Server] [INFO] Previous version: git-Paper-"155aa36" (MC: 1.19.3)

### ItemsAdder Version

19.05 01:46:13 [Server] [INFO] ItemsAdder version 3.4.1c
19.05 01:46:13 [Server] [INFO] Customized Minecraft without client mods!
19.05 01:46:13 [Server] [INFO] Website: devs.beer
19.05 01:46:13 [Server] [INFO] Author: LoneDev

### ProtocolLib Version

19.05 01:46:36 [Server] [INFO] ProtocolLib version 5.0.0-SNAPSHOT-b633
19.05 01:46:36 [Server] [INFO] Provides read/write access to the Minecraft protocol.
19.05 01:46:36 [Server] [INFO] Authors: dmulloy2 and comphenix

### LoneLibs Version

19.05 01:46:55 [Server] [INFO] LoneLibs version 1.0.24
19.05 01:46:55 [Server] [INFO] Collection of libs used by my plugins
19.05 01:46:55 [Server] [INFO] Authors: LoneDev and others

### Other files, you can drag and drop them here to upload. (optional)

[terraria.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/11512830/terraria.zip)

**Comment by LoneDev6** [comment]
It probably renders the text using another shader so the current shader doesn't intercept the text to be modified, I don't have a solution for now, I have to investigate, but mine is just a supposition.

**Comment by MelonCraftDE** [comment]
depends on own resolution & GUI scale setting.
i do have this problem too, but only with a too big gui-scale
