### ISSUE TITLE
[ADDON] ItemsAdder WorldEdit

### ISSUE THREAD

**Issue by NoHere32** [PluginBugs/Issues-ItemsAdder#2653]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

NoHere#7644

### What happened?

After upgrading my development server to 1.19.4 with the latest version of itemsadder (3.4.1-c) without any problems I decided after 1 week to upgrade my Build server to the latest version.

The problem with the addon is that it only puts non-textured note blocks when they exist.

### Steps to reproduce the issue

1 - Upgrade your server to 1.19.4
2 - Have the plugin versions as such:
     - ItemsAdder : 3.4.1-c
     - LoneLibs : 1.0.24
     - Addon : 1.1.3
     - FAWE : 2.5.2-SNAPSHOT-437;362f6cc
3 - Selected an area
4 - //set 10block:xxxxxxx
5 - Result : Note Block not textured

### Server version

This server is running Pufferfish version git-Pufferfish-69 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 19a70d2 on HEAD)
You are running 1 version beyond. Please update your server when possible to maintain stability, security, and receive the latest optimizations.
Previous version: git-Pufferfish-58 (MC: 1.19.3)

### ItemsAdder Version

- ItemsAdder version : 3.4.1-c

### ProtocolLib Version

- ProtocolLib version : 5.1.0-SNAPSHOT-645

### LoneLibs Version

- LoneLibs version : 1.0.24

### FULL server log

[18:51:14 INFO]: NoHere issued server command: //set 10blocs:acacia_planks
[18:51:21 INFO]: NoHere issued server command: //undo
[18:51:21 INFO]: [ItemsAdder] Loaded chunk '14,-75' of 'r.0.-3.pregion' in 0ms | SSSS -> /itemsadder/region/r.0.-3.pregion
[18:51:21 INFO]: [ItemsAdder] Loaded chunk '14,-76' of 'r.0.-3.pregion' in 0ms | SSSS -> /itemsadder/region/r.0.-3.pregion
[18:51:28 INFO]: NoHere issued server command: //set 10blocs:acacia_planks
[18:51:29 INFO]: NoHere issued server command: //set 10blocs:acacia_planks
[18:51:30 INFO]: NoHere issued server command: //undo
[18:51:31 INFO]: NoHere issued server command: //undo

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/IZFvgVJ-6Lo

**Comment by NoHere32** [comment]
So I switched to a less recent version (FAWE 2.6.0) not in snapshot and the only thing that remains is the fact that the //undo does not work on custom blocks
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/123643370/cee161ae-3ee2-44a3-ac70-f020d079a50a)

**Comment by LoneDev6** [comment]
Try with normal Worldedit and let me know.

**Comment by NoHere32** [comment]
So after testing with the version quoted in the screen above, the problem is that the //undo doesn't work on custom blocks, and the //mask doesn't work either. 

step :
1 - /br sphere <patern> <radius>
2 - //mask minecraft:stone

This doesn't replace the stone but just makes the sphere.

**Comment by LoneDev6** [comment]
> Try with normal Worldedit and let me know.

**Comment by NoHere32** [comment]
hey, 
I've come to give you some news about how it works with normal worldedit...

small question isn't it possible to make the //undo and //mask work with fastasyncworldedit? because the latter is compatible with everything that is ARCEON, BuilderUtilities ... unlike classic worldedit

**Comment by LoneDev6** [comment]
I'll check and let you know if I find a solution.
Thanks

**Comment by NoHere32** [comment]
Hello, I'm here to find out if there's anything new about this?

**Comment by LoneDev6** [comment]
I can't find the cause of the issue.
It worked fine some FAWE versions ago, they again probably changed something internally.
I have no control over what other plugins change in their code...

For some reason //copy and //paste work fine.

I confirm the plugin works fine on normal WorldEdit.

**Comment by evilsaloon** [comment]
Tested with WorldEdit version 7.2.15+6463-5ca4dff, ItemsAdder version 3.5.0c-r2, ItemsAdder-WorldEdit version 1.1.3. //undo and //set indeed are bugged when lots of custom IA blocks are present in a given area. Sometimes I had to run //set multiple times in order to have IA blocks of any type be replaced. //undo removes vanilla blocks normally but for some reason ignores IA blocks.

//copy and //paste work fine, though, as do schematics.

Video: https://youtu.be/WEUADs-Yo1g

**Comment by LoneDev6** [comment]
@evilsaloon please do not use the same issue report for different kind of issues.
This issue page is for FastAsyncWorldEdit compatibility.
Thanks!
I created a new issue for you: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2906

**Comment by emmanuelvlad** [comment]
Is this an issue on FAWE's side?

**Comment by LoneDev6** [comment]
I guess so as it works fine on WorldEdit.
Sadly both WorldEdit and FAWE API do not introduce an easy straightforward way to add custom blocks to their registry, so trickery was implemented and it's going to break on each WorldEdit/FAWE update without my control.
In the past I already tried contacting WE and FAWE devs without any collaborative response.

**Comment by BN-2K9** [comment]
Is there been any developments around this? or is the plugin now deprecated. If so an i allowed to use your code that you made and try to update the plugin? (ofc i will give u the credits)

**Comment by LoneDev6** [comment]
@BN-2K9 yes you are allowed
