### ISSUE TITLE
[ItemsAdder] REAL_TRANSPARENT Added a feature to make a corner connection

### ISSUE THREAD

**Issue by NoHere32** [PluginBugs/Issues-ItemsAdder#2655]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Added an option in the block to enable the interconnection between choruses  
Interconnection : true or false

Is it also possible to add the possibility to put the texture on the center of the block ?

### Is your feature request related to a problem?

This is not really a problem but more a possibility to do custom glass_pane interconnection

### Describe alternatives you've considered

re-textured glass_pane vanilla, but the concern is that we want to leave access to glass_pane vanilla to our players because we are a Skyblock server

**Comment by LoneDev6** [comment]
There is no way to add a connection between REAL_TRANSPARENT blocks.
This would require occupying 3 custom blocks "slots" for each custom glass you'd create, this would limit the max amount of blocks you can add.
You should can alternatively create blocks similar to normal "glass", a cube.
