### ISSUE TITLE
Custom textured armor not working

### ISSUE THREAD

**Issue by realaj** [PluginBugs/Issues-ItemsAdder#2660]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

realaj#4400

### What happened?

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/38167759/b6c925a3-e7d6-489f-9d2e-67313a0edb42)

I've been attempting to add custom armor sets to a server for quite a while, and every time I try to, it throws this error with seemingly no explanation. I've tried to base it off of example hierarchies, even repurposing an addon to try to get the texture to show up. This has gone to the point of previously working armor breaking because of this error. Is this any way I can fix this? Thanks in advance

(copy and pasted from forums)

### Steps to reproduce the issue

1. Make armor ( I used the example provided )
2. Zip the pack
3. Error gets thrown

### Server version

git-Purpur-1976 (MC: 1.19.4)

### ItemsAdder Version

ItemsAdder version 3.4.1c

### ProtocolLib Version

ProtocolLib version 5.0.0

### LoneLibs Version

LoneLibs version 1.0.24

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11561123/latest.log)

### Error (optional)

```shell
[04:22:19 ERROR]: [ItemsAdder] Failed to generate armor atlas.
java.lang.ArrayIndexOutOfBoundsException: Coordinate out of bounds!
	at java.desktop/sun.awt.image.IntegerInterleavedRaster.setDataElements(IntegerInterleavedRaster.java:298)
	at java.desktop/java.awt.image.BufferedImage.setRGB(BufferedImage.java:1017)
	at ItemsAdder_3.4.1c.jar//ia.m.iM.a(SourceFile:477)
	at ItemsAdder_3.4.1c.jar//ia.m.iM.a(SourceFile:378)
	at ItemsAdder_3.4.1c.jar//ia.m.iM.a(SourceFile:256)
	at ItemsAdder_3.4.1c.jar//ia.m.iM.cD(SourceFile:244)
	at ItemsAdder_3.4.1c.jar//ia.m.iA.ct(SourceFile:653)
	
at ItemsAdder_3.4.1c.jar//ia.m.I.a(SourceFile:2653)	at ItemsAdder_3.4.1c.jar//ia.m.hH.a(SourceFile:86)
	at ItemsAdder_3.4.1c.jar//ia.m.I.a(SourceFile:2452)
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)

	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	
	at java.base/java.lang.Thread.run(Thread.java:833)at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)[04:22:19 INF
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: ice_set
items:
  ice_helmet:
    display_name: Ice Helmet
    resource:
      generate: true
      textures:
      - item/ice_helmet.png
      - item/ice_helmet.png
    durability:
      max_custom_durability: 264
    specific_properties:
      armor:
        slot: head
        custom_armor: ice
    attribute_modifiers:
      head:
        armor: 3
        armorToughness: 1
  ice_chestplate:
    display_name: Ice Chestplate
    resource:
      generate: true
      textures:
      - item/ice_chestplate.png
      - item/ice_chestplate.png
    durability:
      max_custom_durability: 384
    specific_properties:
      armor:
        slot: chest
        custom_armor: ice
    attribute_modifiers:
      chest:
        armor: 8
        armorToughness: 1
  ice_leggings:
    display_name: Ice Leggings
    resource:
      generate: true
      textures:
      - item/ice_leggings.png
      - item/ice_leggings.png
    durability:
      max_custom_durability: 360
    specific_properties:
      armor:
        slot: legs
        custom_armor: ice
    attribute_modifiers:
      legs:
        armor: 6
        armorToughness: 1
  ice_boots:
    display_name: Ice Boots
    resource:
      generate: true
      textures:
      - item/ice_boots.png
      - item/ice_boots.png
    durability:
      max_custom_durability: 312
    specific_properties:
      armor:
        slot: FEET
        custom_armor: ice
    attribute_modifiers:
      feet:
        armor: 3
        armorToughness: 1
armors_rendering:
  ice:
    color: '#5eafb8'
    layer_1: models/armor/ice_armor_layer_1
    layer_2: models/armor/ice_armor_layer_2
    use_color: false
```

**Comment by LoneDev6** [comment]
Please provide all your armors textures, they probably have some issues like bad dimensions.
I made your forum thread private so you can share them there and only I can read the chat.
https://forum.devs.beer/d/549-custom-textured-armor-not-working
