### ISSUE TITLE
replace near blocks respect worldguard, towny etc and replace near blocks from all not a specific block

### ISSUE THREAD

**Issue by umutardafiliz** [PluginBugs/Issues-ItemsAdder#2662]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

djarda2#4247

### Describe the solution you'd like

for block in region
if region is protected
dont place block when using the replace near blocks
if not place the block
so players cant grief protected areas with this method
and next feature i want is
replace_near_blocks:
  radius:
    x: 2
    y: 2
    z: 2
  from: ALL
  to: OBSIDIAN
  decrement_durability: 8
  no_physics: false
so when you write ALL to from, it will replace every block and not only 1 block type
or perhaps a whitelist/blacklist feature for this and add a list input

### Is your feature request related to a problem?

grief problem and time waste problem. if i want to replace all blocks i shouldnt type each one of them

### Describe alternatives you've considered

not possible unless i create a new plugin that depends on itemsadder and checks if the interacted block is itemsadder block. then does what i request

**Comment by LoneDev6** [comment]
> if region is protected

Protected with which plugin?
WorldGuard is already supported and my plugin also checks if the block can be broken by the player before breaking it (this is meant to support any protection plugin).

In this case it means that the protection plugin you're using is not correctly cancelling BlockBreakEvent for some reason.

**Comment by umutardafiliz** [comment]
oh ok i thought the first was not implemented. however what about the blacklist-whitelist for the FROM blocks on the replace near blocks? so i can choose every block to replace from
