### ISSUE TITLE
Resource Pack Not Applying To Players !

### ISSUE THREAD

**Issue by imbnc** [PluginBugs/Issues-ItemsAdder#2664]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

MBN#0252

### What happened?

- First: New Players should have a menu opened in there join which asks them to accept or decline the resource pack, in my case this is not working players join without even getting answered by the plugin to accept or decline the available resource pack used in the server, where I already have it on force players and kick when declined.

- Second: I have to manually (/iazip all) every time a new player joins to make him actually play the server with resource pack that should apply and force players to have to play in the server. In my case this is not working and again I must (/iazip all) every time a new players join.

- Third: I had one of the Items Adder support team {ItzASecretBoi} see my issue/config files and he can confirm that there is something wrong and this is definitely not a typical issue, and there is something wrong here.

- Players should be forced and asked by the plugin to accept/proceed the resource pack the server offers and work fine. In My case none of this is happening for some reason players are not being asked or get message on screen once they join the server and they just can see any of the packs I am using instead see weird Hore armors and off looking items. Which is actually making me struggle to (/iazip all) every single time a player join so they get the chance to see and have the resource pack applied which is making me go crazy.

### Steps to reproduce the issue

1. Join My Server
2. Resource pack is not working/bugged + You won't even be asked to accept or decline the resource pack the server offers to play

### Server version

This server is running Paper version git-Paper-538 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: bcd8dc2)
You are running the latest version

### ItemsAdder Version

ItemsAdder version 3.4.1d
Customized Minecraft without client mods!
Website: devs.beer
Author: LoneDev

### ProtocolLib Version

ProtocolLib version 5.0.0
Provides read/write access to the Minecraft protocol
Authors: dmulloy2 and comphenix

### LoneLibs Version

LoneLibs version 1.0.24
Collection of libs used by my plugins
Authors: LoneDev and others

**Comment by LoneDev6** [comment]
Did you read the official troubleshooting guide CAREFULLY?
It tells you how to identify the cause of the issue.
https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown

**Comment by imbnc** [comment]
This log is from {ItzASecretBoi} the ItemsAdder Support team. This is his log when he joined and didn’t even get the option to accept or decline the pack the server offers, Which is not supposed to happen and there should be a proceed and decline option.


[Client Log:]

21:15:06.473
Missing sound for event: minecraft:item.goat_horn.play
21:15:06.473
Missing sound for event: minecraft:entity.goat.screaming.horn_break
21:15:06.473
Missing sound for event: minecraft:music.overworld.cherry_grove
21:15:06.500
OpenAL initialized on device OpenAL Soft on Headphones (SteelSeries Arctis 9 Game)
21:15:06.500
Sound engine started
21:15:06.517
Created: 2048x2048x4 minecraft:textures/atlas/blocks.png-atlas
21:15:06.521
Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
21:15:06.521
Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
21:15:06.522
Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
21:15:06.523
Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
21:15:06.524
Created: 64x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
21:15:06.524
Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
21:15:06.525
Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
21:15:06.526
Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
21:15:06.557
Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
21:15:06.604
Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
21:15:06.604
Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
21:15:06.605
Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas

**Comment by imbnc** [comment]
+ I just had new member join for the first time I guess, And it seems that the resource pack worked for him which is more confusing now that shows that not all players get forced for the pack which i am just going crazy now trying to understand


![ss](https://github.com/PluginBugs/Issues-ItemsAdder/assets/131328229/a7efcf8b-1840-4264-a4ef-9bc8e34ab6d2)

**Comment by imbnc** [comment]
-Here is my config if that might help, I just censored the (Server-IP) / (Pack-Port).

                                                                                       [Config.yml]
                           <<<=======================================================>>>
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
ignore-server-compatibility-check: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: *********
      pack-port: *********
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: true
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  1_19_3_atlas_support: true
  fix_force_unicode_font_images: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      protection_1: true
      protection_2: true
    compress-png-files: true
    compress-json-files: true
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    extract_internal_utility_assets: true
    contents-folders-priority:
    - vanilla
    - _iainternal
    merge_other_plugins_resourcepacks_folders:
    - ModelEngine/resource pack
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  force-sync-loading: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
    drop_when_broken: false
  disable-REAL: false
  disable-REAL_NOTE: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_WIRE: true
  disable-FIRE: false
  convert-vanilla-blocks:
    enabled: false
    only-new-chunks: true
  convert-legacy-ia-region-files: true
  remove-unused-palettes-on-region-save: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    doublecheck-permission__disable-for-more-performance: false
    add-hover-suggestion: true
    tab-autocompletion_1_19_1_plus: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  iaimage-book:
    max-line-length: 18
    placeholder-font: minecraft:default
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    emotes: false
    interval-rendering-packets-ticks: 1
    optimized-packets: true
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  show-no-permission-popup-in-recipebook: true
  show-no-permission-chat-message: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: true
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  benchmark: false
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-recipes-unknown-item: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save-load:
      enabled: false
      min-ms: 0
    log-mined-unknown-blocks: true
    log-convert-vanilla-blocks: false
    log-fix-bugged-blocks: false
    log-unusual-block-break: false
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
                           <<<=======================================================>>>

**Comment by LoneDev6** [comment]
Please read the guide again.
There are some causes which trigger this particular issue.
https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown
Let me know if it was the cause, otherwise we will have to test again and
I'll find a solution for your particular server.

*From the last lines of the guide:*

*Make sure you don't have any inventory (GUI) or book opening on join. This
can cause the resourcepack prompt to disappear and the player won't be able
to click on it. In order to fix this you can use the free plugin
ResourcePackBroadcast
<https://www.spigotmc.org/resources/resourcepackbroadcast.88318/>. This
allows you to run commands as soon as the resourcepack is accepted (and
various other features). You can also try increasing the delay-ticks in
config.yml of ItemsAdder to 10 or greater.*



Il Ven 26 Mag 2023, 14:14 imbnc ***@***.***> ha scritto:

**Comment by LoneDev6** [comment]
Please read the guide again. 
There are some causes which trigger this particular issue.
https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown
Let me know if it was the cause, otherwise we will have to test again and I'll find a solution for your particular server.

**From the last lines of the guide:**

> Make sure you don't have any inventory (GUI) or book opening on join. This can cause the resourcepack prompt to disappear and the player won't be able to click on it. In order to fix this you can use the free plugin ResourcePackBroadcast. This allows you to run commands as soon as the resourcepack is accepted (and various other features). You can also try increasing the delay-ticks in config.yml of ItemsAdder to 10 or greater.

**Comment by imbnc** [comment]
I really tried trust me I would really appreciate you giving me some of your time and taking a look at this I have tried reaching out to you, but it seems you don't allow messages my discord tag is MBN#0252 I would appreciate your assistance and understanding where this issue is causing multiple issues.

**Comment by imbnc** [comment]
So just to update you,

I fixed this by myself, where i am really sad to say I expected better support in my issue, Anyways what i did is i had to purchase a ForceResourcePack Plugin and disable the applyonjoin in the ItemsAdder Config and used the generated.zip and place it on MCPack website and copy and past the url and hash and past it in my ForeResourcePack plugin which actually worked 🙂.

I struggled so much fixing this issue and i said why not update, where this might help other people facing the same issue i faced and solved.

**Comment by LoneDev6** [comment]
I don't allow private messaging anymore because the community has now 6600 members.
I cannot give personal support to everyone.
Also as noted on the Discord server and on the forum I don't work on the weekends and I'm available from 8AM to 18PM.

To fix the issue you don't need another premium resource. I never told you to buy ForceResourcePack.
You could have waited the weekend and I could have helped you.

What I need to identify the issue is that you remove ForceResourcePack, enable the itemsadder pack apply functionality, join the server and send here your CLIENT log (not server). Make sure to join the server and trigger the issue.
I need a log of when the issue happen, not of when the pack gets applied correctly.
