### ISSUE TITLE
The Emojis {placeholder} returns the image

### ISSUE THREAD

**Issue by paulreob** [PluginBugs/Issues-ItemsAdder#2665]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

In ItemsAdder version 3.4.1d when the hover of the emoji written in the chat is displayed, the duplicate image appears, which suggests that the {placeholder} also returns the image

In previous versions it worked fine, it returned `:sus:`

should show
[EMOJI] :sus: /emojis
but it shows
[EMOJI] [EMOJI] /emoji

### Steps to reproduce the issue

1. Write an emoji in the chat
2. Notice that the emoji image is displayed twice

### Server version

git-Purpur-1975 (MC: 1.19.4)*

### ItemsAdder Version

ItemsAdder version 3.4.1d

### ProtocolLib Version

 ProtocolLib version 5.0.0

### LoneLibs Version

LoneLibs version 1.0.24

### Problematic items yml configuration file (optional)

```shell
font-image-chat-hover: '&f{font_image} &7{placeholder} &x&f&b&0&1&3&7/emojis'
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/71041139/30864702-6eca-478b-8810-90c30196021f)

**Comment by LoneDev6** [comment]
Please make a video of the issue since I don't understand your step by step explanation of how to trigger the issue.

**Comment by paulreob** [comment]
> Please make a video of the issue since I don't understand your step by step explanation of how to trigger the issue.

I mean the hover of the emoji when you hover the mouse pointer over the emoji
You should see `[EMOJI] :sus: /emojis`
but it is seen with double emoji which means that the `{placeholder}` returns the image what it should return is `:sus:`

**Comment by LoneDev6** [comment]
> Please make a video of the issue since I don't understand your step by step explanation of how to trigger the issue.

**Comment by paulreob** [comment]
> ```shell
> ```shell
> font-image-chat-hover: '&f{font_image} &7{placeholder} &x&f&b&0&1&3&7/emojis'
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

._.
1. WRITE AN EMOJI IN THE CHAT
2. PLACE THE MOUSE ON THE EMOJI SO THAT THE HOVER APPEARS
3. NOTICE THAT DOUBLE EMOJI IS DISPLAYED ON HOVER
THIS MEANS THAT THE {PLACEHOLDER} of `font-image-chat-hover:` in the lang/en.yml file is sending the emoji image and not the emoji name which is :sus:

**Comment by paulreob** [comment]
I already sent you a video

**Comment by LoneDev6** [comment]
Thanks for the video ❤️ 
I'm going to make some tests and see why this happens.

**Comment by paulreob** [comment]
please open this issues again so that it is not forgotten xd

**Comment by paulreob** [comment]
This bug was assigned to milestone: 3.5.0 but it is not closed or open, and version 3.5.0 has been released.
`ItemsAdder/lang/en.yml`
`font-image-chat-hover: '&f{font_image} &7{placeholder} &x&f&b&0&1&3&7/emojis'`
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/71041139/cf5b9c2c-986b-4b35-8bfc-b0fcd3052896)

**Comment by LoneDev6** [comment]
Was not forgotten, I cannot reproduce the issue.
There is probably one plugin interfering.

I'll have to do more tests but for now I cannot find the cause on a normal server installation.

**Comment by paulreob** [comment]
> Was not forgotten, I cannot reproduce the issue. There is probably one plugin interfering.
> 
> I'll have to do more tests but for now I cannot find the cause on a normal server installation.
> 
> It is still marked as "Todo", it doesn't have a milestone though due to the previous reason. ![image](https://user-images.githubusercontent.com/27242001/247704179-c521c7df-d87e-4dfd-bbea-e02fea4b21f3.png)

Oh I already noticed the bug, it's because I also updated the Carbon chat plugin, and it's a problem with that plugin
https://github.com/Hexaoxide/Carbon
Now change the plugin to TrChat and this does support customfonts from ItemsAdder.
https://github.com/TrPlugins/TrChat
Forgive me, I thought it was an ItemsAdder error
