### ISSUE TITLE
`/iacleancache items` is deleting player model (`iainternal:player`)

### ISSUE THREAD

**Issue by EpicPlayerA10** [PluginBugs/Issues-ItemsAdder#2666]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

EpicPlayerA10#3800

### What happened?

When I create a new fresh server on an ItemsAdder, and I type `/iacleancache items` and `/iareload`, then the exception is thrown. The exception is in the `Error` section

Probably a player model is deleted by `/iacleancache items`. The `/emote` stopped working. Even after restarting a server, the exception is still thrown and `/emote` isn't working.

### Steps to reproduce the issue

1. Create a new fresh server with an ItemsAdder
2. Run `/iacleancache items` and `/iareload`

! The exception is thrown

### Server version

Current: git-Purpur-1976 (MC: 1.19.4)*

### ItemsAdder Version

ItemsAdder version 3.4.1d

### ProtocolLib Version

ProtocolLib version 5.0.0

### LoneLibs Version

LoneLibs version 1.0.24

### Error (optional)

```shell
[00:21:16 ERROR]: [ItemsAdder] Failed to load: iainternal:player
[00:21:16 WARN]: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
[00:21:16 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[00:21:16 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[00:21:16 WARN]:        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
[00:21:16 WARN]:        at java.base/java.util.Objects.checkIndex(Objects.java:359)
[00:21:16 WARN]:        at java.base/java.util.ArrayList.get(ArrayList.java:427)
[00:21:16 WARN]:        at ItemsAdder_3.4.1d(2).jar//ia.m.I.a(SourceFile:2918)
[00:21:16 WARN]:        at ItemsAdder_3.4.1d(2).jar//ia.m.am.a(SourceFile:109)
[00:21:16 WARN]:        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[00:21:16 WARN]:        at ItemsAdder_3.4.1d(2).jar//ia.m.am.b(SourceFile:71)
[00:21:16 WARN]:        at ItemsAdder_3.4.1d(2).jar//ia.m.X.a(SourceFile:185)
[00:21:16 WARN]:        at ItemsAdder_3.4.1d(2).jar//ia.m.X.u(SourceFile:319)
[00:21:16 WARN]:        at ItemsAdder_3.4.1d(2).jar//ia.m.I.a(SourceFile:2321)
[00:21:16 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[00:21:16 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[00:21:16 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[00:21:16 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[00:21:16 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[00:21:16 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[00:21:16 ERROR]: [ItemsAdder] Failed to read player animation data. player model is null.
```

**Comment by LoneDev6** [comment]
iacleancache doesn't delete the emotes file.
The issue relies somewhere else.
Anyway you're not supposed to run /iacleancache on the first plugin installation, it has no sense.
This command must be used only when you are running the server for some weeks or months and you deleted items, then you want to clean the unused IDs slots.

**Comment by EpicPlayerA10** [comment]
It DOESN'T work ONLY on a new server. This bug <ins>**also**</ins> occurs when you really want to clean caches on a real server that is running for some time.

Especially `/iacleancache items` deletes from `items_ids_cache.yml` these entries:
- `__manually_handled:iainternal__player_hat_slot`
- `__manually_handled:iainternal__player_left_arm_slot`
- `__manually_handled:iainternal__player_right_arm_slot`
- `__manually_handled:iainternal__player_phead_0`
- `__manually_handled:iainternal__player_parm_left_3`
- `__manually_handled:iainternal__player_pbody_2`
- `__manually_handled:iainternal__player_pleg_left_1`
- `__manually_handled:iainternal__player_pleg_right_5`
- `__manually_handled:iainternal__player_parm_right_4`

**Comment by LoneDev6** [comment]
I'll do some checking, it should regenerate these entries right after you run the command.
Thanks

**Comment by Andre601** [comment]
One thing I want to add to this is the following:

The cleancache command prints outputs similar to the above (The `__manually_handled:...`) for all kinds of custom entities it seems.
Meanwhile, the success message reports that "0 unused items" were removed, acting like the ones it reported to have removed for being unused don't exist at all.

Not sure if that's an intentional behaviour, but I kinda doubt that.

**Comment by HappyKrazy** [comment]
> ### Terms
> * [x]  I'm using the very latest version of ItemsAdder and its dependencies.
> * [x]  I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
> * [x]  I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
> * [x]  I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
> * [x]  I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
> 
> ### Discord tag (optional)
> EpicPlayerA10#3800
> 
> ### What happened?
> When I create a new fresh server on an ItemsAdder, and I type `/iacleancache items` and `/iareload`, then the exception is thrown. The exception is in the `Error` section
> 
> Probably a player model is deleted by `/iacleancache items`. The `/emote` stopped working. Even after restarting a server, the exception is still thrown and `/emote` isn't working.
> 
> ### Steps to reproduce the issue
> 1. Create a new fresh server with an ItemsAdder
> 2. Run `/iacleancache items` and `/iareload`
> 
> ! The exception is thrown
> 
> ### Server version
> Current: git-Purpur-1976 (MC: 1.19.4)*
> 
> ### ItemsAdder Version
> ItemsAdder version 3.4.1d
> 
> ### ProtocolLib Version
> ProtocolLib version 5.0.0
> 
> ### LoneLibs Version
> LoneLibs version 1.0.24
> 
> ### FULL server log
> _No response_
> 
> ### Error (optional)
> ```shell
> [00:21:16 ERROR]: [ItemsAdder] Failed to load: iainternal:player
> [00:21:16 WARN]: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
> [00:21:16 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
> [00:21:16 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
> [00:21:16 WARN]:        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
> [00:21:16 WARN]:        at java.base/java.util.Objects.checkIndex(Objects.java:359)
> [00:21:16 WARN]:        at java.base/java.util.ArrayList.get(ArrayList.java:427)
> [00:21:16 WARN]:        at ItemsAdder_3.4.1d(2).jar//ia.m.I.a(SourceFile:2918)
> [00:21:16 WARN]:        at ItemsAdder_3.4.1d(2).jar//ia.m.am.a(SourceFile:109)
> [00:21:16 WARN]:        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
> [00:21:16 WARN]:        at ItemsAdder_3.4.1d(2).jar//ia.m.am.b(SourceFile:71)
> [00:21:16 WARN]:        at ItemsAdder_3.4.1d(2).jar//ia.m.X.a(SourceFile:185)
> [00:21:16 WARN]:        at ItemsAdder_3.4.1d(2).jar//ia.m.X.u(SourceFile:319)
> [00:21:16 WARN]:        at ItemsAdder_3.4.1d(2).jar//ia.m.I.a(SourceFile:2321)
> [00:21:16 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
> [00:21:16 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
> [00:21:16 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
> [00:21:16 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> [00:21:16 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> [00:21:16 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
> [00:21:16 ERROR]: [ItemsAdder] Failed to read player animation data. player model is null.
> ```
> 
> ### Problematic items yml configuration file (optional)
> _No response_
> 
> ### Other files, you can drag and drop them here to upload. (optional)
> _No response_
> 
> ### Screenshots/Videos (you can drag and drop files or paste links)
> _No response_

I havI have the same problem as you.e the same problem
