### ISSUE TITLE
exp dupe glitch with Aurelium Skills

### ISSUE THREAD

**Issue by Ecilpse** [PluginBugs/Issues-ItemsAdder#2671]
REDACTED

**Comment by LoneDev6** [comment]
Next time avoid reporting duplication bugs publicly, a new violation will lead to a termination of your account.
People can abuse duplication bugs if they are published publicly online.
I explicitly wrote that you must not report this kind of bugs on Github. 


![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/a59e99cd-e272-4a18-ab0b-5f9ced9b291f)

**Comment by Ecilpse** [comment]
> Next time avoid reporting duplication bugs publicly, a new violation will lead to a termination of your account.
> People can abuse duplication bugs if they are published publicly online.
> I explicitly wrote that you must not report this kind of bugs on Github.

I couldn't check it. I'm sorry.

**Comment by LoneDev6** [comment]
No problem, I'll try to reproduce the issue and fix it

**Comment by LoneDev6** [comment]
Please make sure to enable this in the **AureliumSkills** plugin.
`forging.check-cancelled`

Found it by reading the plugin code.
https://github.com/Archy-X/AureliumSkills/blob/d1e28fdf11faa0815e5593e7fd5c3ef48ebfa0be/bukkit/src/main/java/com/archyx/aureliumskills/skills/forging/ForgingLeveler.java#L40


----


If that doesn't work it's a bug of the other plugin.
They must make sure to check if the item in the result slot is not AIR and avoid giving exp if the result is AIR.
ItemsAdder uses [PrepareGrindstoneEvent](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/inventory/PrepareGrindstoneEvent.html) to catch the event and cancel it for items which must not be used in the grindstone, **AureliumSkills** should really start doing the same (1.19+ only).

**Comment by Ecilpse** [comment]
> Please make sure to enable this in the **AureliumSkills** plugin. `forging.check-cancelled`
> 
> Found it by reading the plugin code. https://github.com/Archy-X/AureliumSkills/blob/d1e28fdf11faa0815e5593e7fd5c3ef48ebfa0be/bukkit/src/main/java/com/archyx/aureliumskills/skills/forging/ForgingLeveler.java#L40
> 
> If that doesn't work it's a bug of the other plugin. They must make sure to check if the item in the result slot is not AIR and avoid giving exp if the result is AIR. ItemsAdder uses [PrepareGrindstoneEvent](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/inventory/PrepareGrindstoneEvent.html) to catch the event and cancel it for items which must not be used in the grindstone, **AureliumSkills** should really start doing the same (1.19+ only).
![1](https://github.com/PluginBugs/Issues-ItemsAdder/assets/25452835/1a7f9df0-b44a-46a2-9046-dda3d630e0d3)
![2](https://github.com/PluginBugs/Issues-ItemsAdder/assets/25452835/1be85354-ec6e-470a-bfde-73cf61f7d313)

already enabled in check-cancelled: true in foging. and result are not air.

**Comment by LoneDev6** [comment]
Thanks for the info!
Seems related to this: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2684
I'll fix that issue as soon as possible.
