### ISSUE TITLE
custom block turned into note block

### ISSUE THREAD

**Issue by Ecilpse** [PluginBugs/Issues-ItemsAdder#2678]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

EclipseMC#7777

### What happened?

![2023-05-29_21 09 03](https://github.com/PluginBugs/Issues-ItemsAdder/assets/25452835/52183881-4afe-4e42-aca4-a5d8c8fe1139)

i use customcrops plugin with IA.
sometimes pot was turned into juke box.
i updated lastest version of IA, customcrops, but still same.
also i reported this issue at customcrops, but he said it's IA's issue.
can you check this?

And there is a dupe glitching issue related to this, but the link to the view policy button you gave me is not valid.
Can you check it?

### Steps to reproduce the issue

I can't reproduce this. It happens frequently without notice.

### Server version

purpur 1.19.2 RO.1

### ItemsAdder Version

 3.4.1b

### ProtocolLib Version

5.0.0-SNAPSHOT-b606

### LoneLibs Version

 1.0.24

**Comment by LoneDev6** [comment]
Please remove the custom crops plugin and make sure that you can still reproduce the blocks bug even without custom crops installed.
Obviously to do that you have to place custom blocks and test if they get corrupted from time to time.

**Comment by Ecilpse** [comment]
> Please remove the custom crops plugin and make sure that you can still reproduce the blocks bug even without custom crops installed. Obviously to do that you have to place custom blocks and test if they get corrupted from time to time.
> 
> > And there is a dupe glitching issue related to this, but the link to the view policy button you gave me is not valid.
> > Can you check it?
> 
> It works just fine. https://github.com/PluginBugs/Issues-ItemsAdder/security/policy
> 
> Anyway this is a duplicate of #2403
![화면 캡처 2023-05-29 233343](https://github.com/PluginBugs/Issues-ItemsAdder/assets/25452835/aad894b3-b017-4768-a066-67283743737f)
 page says "The pages you request could not be found."
and what is the conclusion of that #2403 ? just can't reproduce?

**Comment by LoneDev6** [comment]
Because you have to verify your purchase before posting on the forum.
Thanks for the info, I added a more clear warning about it.
https://forum.devs.beer/d/17-how-to-report-duplication-bugs

**Comment by LoneDev6** [comment]
> Please remove the custom crops plugin and make sure that you can still reproduce the blocks bug even without custom crops installed.
Obviously to do that you have to place custom blocks and test if they get corrupted from time to time.

**Comment by LoneDev6** [comment]
Any news on this issue?

**Comment by Ecilpse** [comment]
> Any news on this issue?


https://github.com/PluginBugs/Issues-ItemsAdder/assets/25452835/451c1120-b59f-41b0-9d36-09e7bb892537

There seems to be a problem with the custom block with tripwire.
(3.6.4-release-2)

**Comment by LoneDev6** [comment]
This is a different issue, I opened a new report: #3705
