### ISSUE TITLE
Vulcan anticheat incompatibility

### ISSUE THREAD

**Issue by kolderz** [PluginBugs/Issues-ItemsAdder#2693]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Failed to check Vulcan anticheat compatibility

### Steps to reproduce the issue

1. Install Vulcan 2.7.3 and ItemsAdder 3.4.1e

### Server version

purpur 1.18.2

### ItemsAdder Version

3.4.1e

### ProtocolLib Version

5.0.0

### LoneLibs Version

1.0.24

### Error (optional)

```shell
https://pastes.dev/o7fXJb0Adb
```

**Comment by LoneDev6** [comment]
Will be checked.
Anyway make sure you are using the latest Vulcan plugin and you downloaded it from the official website/store.

**Comment by LoneDev6** [comment]
Tested on Vulcan-2.7.5 and it works fine.
