### ISSUE TITLE
font_image can be used without permission anvils or books

### ISSUE THREAD

**Issue by Flandreqwq** [PluginBugs/Issues-ItemsAdder#2694]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

芙兰朵露·斯卡蕾特#4453

### What happened?

By copy & paste the original characters of the font_images (Ctrl c + Ctrl v on the keyboard), players can use any font_image in anvils and books without the appropriate permission. 
I reported this bug before (https://github.com/PluginBugs/Issues-ItemsAdder/issues/2470), but it doesn't seem to be fully fixed. I update the ItemsAdder to 3.4.1e and test this again. Now player can't use font_images without permission in command. But can use font_images without permission in anvils and books. 
And there will be a very strange phenomenon when pasting font_images in the books. When player has no permission, font_images sometimes disappear, sometimes they don't. When player has permission, font_images will always become "#".
(There is a video I upload to show this bug)

### Steps to reproduce the issue

1.creat a font_image and set a permission for it.
2.copy the original character of it. (Ctrl c)
3.paste it in anvil, book or command. (Ctrl v)
4.player can use it without permission in anvils and books.

### Server version

[19:33:09 INFO]: Current: git-Purpur-1632 (MC: 1.18.2)*
Previous: git-Paper-152 (MC: 1.18.1)

### ItemsAdder Version

[19:34:00 INFO]: ItemsAdder version 3.4.1e
[19:34:00 INFO]: Customized Minecraft without client mods!
[19:34:00 INFO]: Website: devs.beer
[19:34:00 INFO]: Author: LoneDev

### ProtocolLib Version

[19:34:46 INFO]: ProtocolLib version 4.8.0-SNAPSHOT-b540
[19:34:46 INFO]: Provides read/write access to the Minecraft protocol.
[19:34:46 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[19:35:06 INFO]: LoneLibs version 1.0.24
[19:35:06 INFO]: Collection of libs used by my plugins
[19:35:06 INFO]: Authors: LoneDev and others

### Problematic items yml configuration file (optional)

```shell
font_images:
  admin:
    permission: "rank.admin"
    show_in_gui: false
    suggest_in_command: false
    path: "admin.png"
    scale_ratio: 9
    y_position: 8
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://github.com/PluginBugs/Issues-ItemsAdder/assets/127276917/b62fe217-0e64-40db-a60f-3c36164c42e3

**Comment by LoneDev6** [comment]
I tested that for an hour and couldn't reproduce the issue before releasing `3.4.1e`.
I'll test again and let you know, but this is very strange.
Please make sure to test without any other plugin installed.
