### ISSUE TITLE
Emotes shader doesn't work on 1.19.3 and lower (missing `fog_distance` function)

### ISSUE THREAD

**Issue by 1821698021** [PluginBugs/Issues-ItemsAdder#2696]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

none

### What happened?

My core is the 1.18.2 version purpur server, and when I enter the server with the 1.16-1.18.1 client, the material package is not sent successfully, and the client will crash

I didn't have this issue in items 3.4.1-r6 version.
I didn't have this issue in items 3.4.1-r6 version.
I didn't have this issue in items 3.4.1-r6 version.

### Steps to reproduce the issue

1.My server core uses purpur version 1.18.2
2.I entered the game using a client of 1.18.1
3.The client crashes when loading a texture pack

### Server version

Current: git-Purpur-1632 (MC: 1.18.2)*
* You are running the latest version

### ItemsAdder Version

itemsadder v3.4.1e

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-636
Provides read/write access to the Minecraft protocol.
Authors: dmulloy2 and comphenix

### LoneLibs Version

LoneLibs version 1.0.24
Collection of libs used by my plugins
Authors: LoneDev and others

### FULL server log

No errors are reported

### Other files, you can drag and drop them here to upload. (optional)

[crash-2023-06-04_18.07.50-client.txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/11645377/crash-2023-06-04_18.07.50-client.txt)

**Comment by LoneDev6** [comment]
## 1

Do not let your players join with outdated builds of clients.
It has no sense to let people join with 1.17.0, 1.18.0, 1.18.1. Let them join only with 1.17.1, 1.18.2, 1.19.4.
Old clients have issues and I have no control over that.


## 2

You're using a modded client, it probably is the issue.
I have no control over mods.
Vanilla client doesn't crash if a shader error is found.
```
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2340!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2340!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2340!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2340!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2340!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2340!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2340!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
```

## 3

This `fog_distance` issue will be fixed in the next update.

**Comment by 1821698021** [comment]
> ## 1
> Do not let your players join with outdated builds of clients. It has no sense to let people join with 1.17.0, 1.18.0, 1.18.1. Let them join only with 1.17.1, 1.18.2, 1.19.4. Old clients have issues and I have no control over that.
> 
> ## 2
> You're using a modded client, it probably is the issue. I have no control over mods. Vanilla client doesn't crash if a shader error is found.
> 
> ```
> at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2340!/:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2340!/:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2340!/:?] {}
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2340!/:?] {}
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2340!/:?] {}
> 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2340!/:?] {}
> 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2340!/:?] {}
> 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
> ```
> 
> ## 3
> This `fog_distance` issue will be fixed in the next update. Note: you'll have to run /iazip again to fix the pack.


[13:12:57 WARN]: [ItemsAdder] "ItemsAdder v3.4.1f" has registered a listener for com.destroystokyo.paper.event.inventory.PrepareGrindstoneEvent on method "private void ia.m.fz.a(com.destroystokyo.paper.event.inventory.PrepareGrindstoneEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [LoneDev].

**Comment by LoneDev6** [comment]
Paper bug fixed long time ago.
https://github.com/PaperMC/Paper/issues/9035

**Comment by 1821698021** [comment]
> Paper bug fixed long time ago. [PaperMC/Paper#9035](https://github.com/PaperMC/Paper/issues/9035)
> 
> Anyway in the future avoid reporting multiple errors and bugs in the same issue report. It just makes things very hard to manage.

Thank you
