### ISSUE TITLE
IA not finding texture in modelengine path when compressing

### ISSUE THREAD

**Issue by paulreob** [PluginBugs/Issues-ItemsAdder#2698]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I am trying to reuse a texture from a mob in the modelengine folder but when I use the /iazip command it tells me that the texture was not found and the model is not generated
I have activated the option of merge_other_plugins_resourcepacks_folders
IA doesn't seem to detect the path of the ModelEngine folder texture

In short, I have a .json that loads a texture from the modelengine route but IA doesn't generate it as it says it doesn't exist
it may not be made for this but it would be a great help for reusing textures `:)`

### Steps to reproduce the issue

1. Create a .json that connects the texture to the modelengine path
ItemsAdder: 
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/71041139/7c86498b-a195-4a57-8e4e-e8e5e268b9e5)
ModelEngine:
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/71041139/9998880e-d5a0-4bf9-a53e-51332f594d56)

2. Create the model configuration in itemsadder
```yaml
info:
  namespace: souleaf
items:
  icon_panda:
    display_name: "icon_panda"
    permission: icon_panda
    resource:
      material: BRICK
      generate: false
      model_path: ui/icon_panda
```
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/71041139/14860db8-b6c4-4342-ab11-5286fc419496)

3. Use command /iazip
[12:04:42 ERROR]: [ItemsAdder] Model file 'souleaf/models/ui/icon_panda.json' not found in any pack for item 'souleaf:icon_panda'. File: /contents/souleaf/configs/ui/iconos_mascotas.yml

### Server version

This server is running Paper version git-Paper-545 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: bacbf86)

### ItemsAdder Version

ItemsAdder version 3.4.1e

### ProtocolLib Version

ProtocolLib version 5.0.0

### LoneLibs Version

LoneLibs version 1.0.24

**Comment by LoneDev6** [comment]
I'll take a look into that, seems somehow the plugin is not searching for models in the folders under `merge_external_resourcepacks_folders` during YML items loading.

**Comment by paulreob** [comment]
@LoneDev6  I meant that the icon_panda.json model is trying to use texture from the modelengine path.
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/71041139/faed8fbb-238d-4066-b09c-84be8d3cb297)

**Comment by LoneDev6** [comment]
I don't understand what is the issue report here.

Anyway if you have two pngs in the same resourcepack path but one in ItemsAdder contents and one in ModelEngine contents they will obviously create conflict.
if you feel like this is a bug please provide a proper set of folders to me to drag and drop into my plugin folder and test it out.
