### ISSUE TITLE
Merge _iainternal and iainternal and more

### ISSUE THREAD

**Issue by paulreob** [PluginBugs/Issues-ItemsAdder#2699]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

The generated.zip has 2 namespaces the `_iainternal` which is used for essential things in the AI guis and the `iainternal` namespace which is only used for the emote models, I highly recommend that you can merge both namespaces as it doesn't I see it well that they look separated, in addition to being able to rename it to a custom name

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/71041139/838647dd-0320-4dac-987b-5894506cb072)

### Is your feature request related to a problem?

I don't think so

### Describe alternatives you've considered

...

**Comment by LoneDev6** [comment]
The `iainternal` without `_` is not intentional.
I'll check why this happened, thanks.
