### ISSUE TITLE
Note block item duplication

### ISSUE THREAD

**Issue by ayssiwa** [PluginBugs/Issues-ItemsAdder#2701]
REDACTED

**Comment by LoneDev6** [comment]
Next time avoid reporting duplication bugs publicly, a new violation will lead to a termination of your account.
People can abuse duplication bugs if they are published publicly online.
I explicitly wrote that you must not report this kind of bugs on Github. 


![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/a59e99cd-e272-4a18-ab0b-5f9ced9b291f)
