### ISSUE TITLE
[BUG] Seeds from iasurvival crafting bug

### ISSUE THREAD

**Issue by yorik100** [PluginBugs/Issues-ItemsAdder#2704]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

yorik100#5011

### What happened?

Cannot craft any iasurvival seeds without a crafting table and it only works if you put the vegetable in the middle of the crafting table

### Steps to reproduce the issue

1. Try to craft garlic seeds with garlic with the inventory crafting table, it doesn't work
2. Open the crafting table
3. Try to craft garlic seeds with garlic while putting garlic in a slot that isn't the middle slot, it doesn't work

### Server version

"CraftBukkit version 3762-Spigot-7d7b241-2270366 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT)"

### ItemsAdder Version

3.4.1e

### ProtocolLib Version

v5.1.0-SNAPSHOT-645

### LoneLibs Version

1.0.24

### FULL server log

Unrelated to the actual issue

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: iasurvival
recipes:
  crafting_table:
    tomato_seeds:
      permission: iasurvival.crops.tomato_seeds
      enabled: true
      pattern:
        - XXX
        - XOX
        - XXX
      ingredients:
        O: iasurvival:tomato
      result:
        item: iasurvival:tomato_seeds
        amount: 2
    garlic_seeds:
      permission: iasurvival.crops.garlic_seeds
      enabled: true
      pattern:
        - XXX
        - XOX
        - XXX
      ingredients:
        O: iasurvival:garlic
      result:
        item: iasurvival:garlic_seeds
        amount: 2
    lettuce_seeds:
      permission: iasurvival.crops.lettuce_seeds
      enabled: true
      pattern:
        - XXX
        - XOX
        - XXX
      ingredients:
        O: iasurvival:lettuce
      result:
        item: iasurvival:lettuce_seeds
        amount: 2
    chili_pepper_seeds:
      permission: iasurvival.crops.chili_pepper_seeds
      enabled: true
      pattern:
        - XXX
        - XOX
        - XXX
      ingredients:
        O: iasurvival:chili_pepper
      result:
        item: iasurvival:chili_pepper_seeds
        amount: 2
    rice_seeds:
      permission: iasurvival.crops.rice_seeds
      enabled: true
      pattern:
        - XXX
        - XOX
        - XXX
      ingredients:
        O: iasurvival:rice
      result:
        item: iasurvival:rice_seeds
        amount: 2
    tobacco_seeds:
      permission: iasurvival.crops.tobacco_seeds
      enabled: true
      pattern:
        - XXX
        - XOX
        - XXX
      ingredients:
        O: iasurvival:tobacco
      result:
        item: iasurvival:tobacco_seeds
        amount: 2
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/16320315/6f08f598-8cd7-43bc-bb97-046efbafdecd)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/16320315/af4420c6-cbb9-46dc-a152-41d761a00860)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/16320315/eb474d61-54c7-4174-80e7-700c5abac5aa)

**Comment by LoneDev6** [comment]
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/3907297c-5505-4cbb-b7e5-0f37748c85ff)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/47d7dccb-f868-446c-adad-c12e1e93c5b4)


![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/4e405559-bc19-4e69-b22f-01414d99c95d)
