### ISSUE TITLE
[Request] Better sharpness damage for weapons

### ISSUE THREAD

**Issue by yorik100** [PluginBugs/Issues-ItemsAdder#2712]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

yorik100#5011

### Describe the solution you'd like

Since weapons use lore to show damage and attackspeed, they don't get updated with sharpness
This is a normal sword with no enchant :
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/16320315/cab4483f-c56f-4e77-b0e4-b42e0565ffc0)
This is the same sword with sharpness :
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/16320315/9444f366-8015-46b7-8528-5acb88cb5a48)
This is what it should show :
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/16320315/6a2f2c2e-9c2f-4a34-b85d-773a80b9d18c)

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

No alternative is possible since it's in the plugin

**Comment by LoneDev6** [comment]
This is probably the same issue, since you didn't provide any information how you enchant the item.
https://github.com/PluginBugs/Issues-ItemsAdder/issues/2466

**Comment by yorik100** [comment]
> This is probably the same issue, since you didn't provide any information how you enchant the item. #2466

Yes, this is a pain when you sell enchantments in a shop, I don't see how I could sell sharpness 6 since using the command wont update the damage and using a book will put sharpness 5 instead of sharpness 6

**Comment by LoneDev6** [comment]
Which plugin are you using to enchant the item?

**Comment by yorik100** [comment]
> Which plugin are you using to enchant the item?

Essentials, same thing happens with /minecraft:enchant too
