### ISSUE TITLE
First/Join Custom Book feature

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-ItemsAdder#2714]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

sircraftypants#4875

### Describe the solution you'd like

I was thinking, seeing as Itemsadders offers Emoji's, Custom Text and apply join feature for resource packs, that it would be cool to have first join or every join pop up advertising/info book feature we can customise that supports IA emoji, custom text and hyperlink and such.

### Is your feature request related to a problem?

no

### Describe alternatives you've considered

There are plugins that provide books but seems a bit much having to have a plugin just for a simple join book and if i recall Itemsadder already utilizes it's own book for install.

**Comment by LoneDev6** [comment]
You can run commands on first join using some other plugins, for example EssentialsX.
You can run a command which opens a custom book created with another plugin.
For example: 
https://www.spigotmc.org/resources/interactivebooks.45604/
https://www.spigotmc.org/resources/custombooks-archived.90931/
They support PlaceholderAPI so you can use font images inside (example `%img_smile%`).

I think this is a niche feature and is not something that should be implemented in the plugin itself.
