### ISSUE TITLE
`REAL_TRANSPARENT` blocks trigger particles and break sound in some cases

### ISSUE THREAD

**Issue by Distolfix** [PluginBugs/Issues-ItemsAdder#2715]
### What happened?

Ciao, ti inoltro un video. Quando uso una trapdoor su un blocco che dovrebbe simulare un blocco di cherry, e uso una trapdoor sembra come se il blocco si rompe e si ripiazza, non solo fa partire l'animazione ma anche il rumore (che può a mio avviso essere fastidioso) questo bug è una sciocchezza, ma lo segnalo così magari puoi risolverlo. Inoltre ho timore che potrebbe causare una "performance issue" siccome a me sembra (magari erro) che il blocco si rimuove e si ripiazza da solo è possibile??

### Steps to reproduce the issue

https://youtu.be/4w0n47tQIvY

### Server version

This server is running Pufferfish version git-Pufferfish-61 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 47c34ca on HEAD)
You are running 12 versions beyond. Please update your server when possible to maintain stability, security, and receive the latest optimizations.
Previous version: git-Purpur-1933 (MC: 1.19.3)

### ItemsAdder Version

3.4.1f2

### ProtocolLib Version

ProtocolLib version 5.0.0
[18:48:15 INFO]: Provides read/write access to the Minecraft protocol.
[18:48:15 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

1.0.24

**Comment by Distolfix** [comment]
https://www.spigotmc.org/resources/trees-newtrees-for-itemsadder.84604/

**Comment by Distolfix** [comment]
Ciao a questo ho appena scoperto che è anche correllato un bug per givvarsi dei frutti. Te lo mando sul forum poichè è irrispettoso nei tuoi confronti

https://forum.devs.beer/d/601-bug-give-frutti

**Comment by LoneDev6** [comment]
> https://youtu.be/4w0n47tQIvY

Non si può fixare.
E' un bug grafico di Minecraft, dato che per evitare che i blocchi perdano la texture devo cancellare gli eventi del gioco si crea questo bug visivo di tanto in tanto.
Non c'è modo di correggerlo, il gioco funziona così.

Comunque non interferisce con il gameplay.

Farò dei controlli per essere sicuro che non si possa correggere con qualche trucchetto, ma ne sono sicuro al 99% dato che il gioco predice tanti eventi del server, quando il server li cancella però l'evento è già stato predetto dal gioco quindi i suoni e le particles del blocco non vengono annullati, ovviamente.

--

Per il resto per favore reporta sempre i bug in thread/issue separati, per facilitare la gestione.
Li ho separati: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2717

**Comment by yorik100** [comment]
I fixed this by setting "disable-chorus-plant-updates" in pupur settings to true, if you're using purpur, you might want to do the same, this fixed the particle spam issue for me.

**Comment by Distolfix** [comment]
Thank you, you have been extremely kind! Let's wait and see if the very kind developer can fix it in his plugin first!

**Comment by LoneDev6** [comment]
More info here: https://itemsadder.devs.beer/faq/blocks-minerals-issues/custom-blocks-glitch-texture/avoid-glitched-blocks#optional-settings-on-purpur

**Comment by Distolfix** [comment]
so, i have pufferfish not purpur

**Comment by LoneDev6** [comment]
Then you have to wait for me to check if there is any solution on server implementations which lack of this option.

**Comment by LoneDev6** [comment]
https://itemsadder.devs.beer/faq/blocks-minerals-issues/custom-blocks-glitch-texture/chorus-plants-real_transparent
