### ISSUE TITLE
Infinite mining/drinking `REAL_TRANSPARENT` blocks

### ISSUE THREAD

**Issue by yorik100** [PluginBugs/Issues-ItemsAdder#2716]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

yorik100#5011

### What happened?

Sometimes, when you mine something from IA, the block never gets broken ever until you stop mining and start mining again, this is not a TPS issue as my server is running on 20 TPS permanently. This also happens when drinking something from IA.

### Steps to reproduce the issue

No steps to reproduce, happens semi-frequently, easy to notice when breaking a tree because sometimes you'll get stuck mining one leaves block until you stop mining and start mining again, again, this is not a TPS issue as mobs can attack me in the meantime and mobs around me move without any lag at all. Note that if I go through the approx 1 minute of trying to break a block in this state, the block will instantly reappear back and will stay impossible to break until I stop and start breaking again.

### Server version

git-Purpur-1982 (MC: 1.19.4)

### ItemsAdder Version

3.4.1f2

### ProtocolLib Version

5.1.0-SNAPSHOT-645

### LoneLibs Version

1.0.24

### FULL server log

https://pastebin.com/hKrHXrN9

**Comment by yorik100** [comment]
Here's me reproducing the issue with a 100% 1.19.4 vanilla client https://streamable.com/g7ji4e
You can see me throw snowballs while the bug happens which means that the server was not lagging at all

**Comment by LoneDev6** [comment]
This can be reproduced only using axe, right?

**Comment by yorik100** [comment]
> This can be reproduced only using axe, right?

Also happens when mining with hand

**Comment by yorik100** [comment]
> This can be reproduced only using axe, right?

I have found a way to replicate it 99% of the time, start mining, move your cursor away and back to the block while still holding the click
This footage shows me reproducing it, F3 enabled so you can see that I'm on vanilla, I'm also throwing snowballs at some point of the vid so you know that server TPS is fine https://streamable.com/hpw1tc

**Comment by yorik100** [comment]
Footage of me reproducing both infinite mining and infinite drinking https://streamable.com/8jb7td
Infinite drinking is made by using a drinkable item on IA leaves

**Comment by LoneDev6** [comment]
I'll do some tests and see if it can be fixed.
I'm not sure since I have little control over client predictions.

> the vid so you know that server TPS is fine https://streamable.com/hpw1tc

Never said it has to do with TPS by the way.

**Comment by yorik100** [comment]
> I'll do some tests and see if it can be fixed. I'm not sure since I have little control over client predictions.
> 
> > the vid so you know that server TPS is fine https://streamable.com/hpw1tc
> 
> Never said it has to do with TPS by the way.

I can't read your mind but it isn't uncommon for people to think that an issue like that could be linked to TPS as a server lag would have had the same effect, just making it clear that it's not the issue in this case
