### ISSUE TITLE
Honey bottles and milk buckets

### ISSUE THREAD

**Issue by yorik100** [PluginBugs/Issues-ItemsAdder#2718]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

yorik100#5011

### What happened?

Unlike potions, honey bottles generate an empty bottle after the item gets consumed. Milk buckets also generate a bucket after the item gets consumed. Another bug is that in creative, if you drink objects that are "material: POTION", they get removed even though in creative you can drink infinitely the same potion/drink.

### Steps to reproduce the issue
Issue with honey bottles and milk buckets :
1. Change "diamonds_finder_potion" -> "material: POTION" to "material: HONEY_BOTTLE" or "material: MILK_BUCKET"
2. Consume the potion
3. There is a leftover (empty glass bottle/empty bucket) unlike the potion

Issue with potions :
1. Get in creative mode
2. Drink any "material: POTION" from IA
3. The "potion" disappears even though in creative you can drink the same thing over and over infinitely

### Server version

git-Purpur-1982 (MC: 1.19.4)

### ItemsAdder Version

4.4.1f2

### ProtocolLib Version

5.1.0-SNAPSHOT-645

### LoneLibs Version

1.0.24

### FULL server log

https://pastebin.com/8wJLF8fi

**Comment by yorik100** [comment]
Same issue happens with suspicious stew, another issue being objects that are golden apples still give regeneration and absorption even though I didn't put that effect on them and objects being chorus fruits still teleporting even though I didn't specify that in the item configuration

**Comment by yorik100** [comment]
> 

That's silly because I want to make an item that's always eatable even when full hunger and that makes a eating sound not a drinking sound, plus you can't stack potions, I want an item that you can always eat and that can be stacked

**Comment by LoneDev6** [comment]
Which material ingame has this behavior?
- eatable even when full hunger
- makes a eating sound not a drinking sound
- stackable

HONEY_BOTTLE? Also SUSPICIOUS_STEW?
Let me know

**Comment by yorik100** [comment]
> 

Both aren't stackable, that's the main issue

**Comment by LoneDev6** [comment]
Well, changing items stack size is not possible without introducing graphical glitches, then I don't think these items are a solution for what you want to achieve.

**Comment by yorik100** [comment]
> Well, changing items stack size is not possible without introducing graphical glitches, then I don't think these items are a solution for what you want to achieve.

What would be nice is a way to cancel default golden apple effects for itemsadder items, I also want to add a "diamond apple" that doesn't give regeneration but I'm stuck with it giving regeneration, I could make a bandaid fix to cancel these effects by using lore and another plugin but that doesn't seem like a proper solution to me

**Comment by LoneDev6** [comment]
> What would be nice is a way to cancel default golden apple effects for itemsadder items

you can try using the cancel event action.
```yml
    events:
      eat:
        cancel: true
        # your actions here.
```

**Comment by yorik100** [comment]
> > What would be nice is a way to cancel default golden apple effects for itemsadder items
> 
> you can try using the cancel event action.
> 
> ```yaml
>     events:
>       eat:
>         cancel: true
>         # your actions here.
> ```

Looks like something that would work except that if you cancel eating, you'll end up eating forever, didn't try though

**Comment by yorik100** [comment]
> > What would be nice is a way to cancel default golden apple effects for itemsadder items
> 
> you can try using the cancel event action.
> 
> ```yaml
>     events:
>       eat:
>         cancel: true
>         # your actions here.
> ```

Ok I can work with that, I also tried with drink event but I can't cancel it, at least for potions

**Comment by LoneDev6** [comment]
You then have to remove the item.
Try it.
```yml
    events:
      eat:
        cancel: true
        decrement_amount:
          amount: 1
```

**Comment by yorik100** [comment]
> > just pointing out that if I do the same thing with drink event, it doesn't get cancelled/potion object still disappears even if I don't decrement the amount
> 
> item material? Please also provide a configuration for me to test the issue.

https://pastebin.com/hQxA7sPm

**Comment by LoneDev6** [comment]
I really don't understand what you want to achieve with the POTION item type.
Drinkable items examples are available here:

## Coffee

When drunk it gives an empty cup.

https://github.com/ItemsAdder/DefaultPack/blob/82a3d2fa786a8901f86c7fc7ea580bbc58fb2ce8/contents/iasurvival/configs/thirst/items/coffee.yml#L4

## Hot chocolate

When drunk it doesn't give back any empty container.

https://github.com/ItemsAdder/DefaultPack/blob/82a3d2fa786a8901f86c7fc7ea580bbc58fb2ce8/contents/iasurvival/configs/thirst/items/hot_chocolate.yml

**Comment by yorik100** [comment]
> I really don't understand what you want to achieve with the POTION item type. Drinkable items examples are available here:
> 
> ## Coffee
> When drunk it gives an empty cup.
> 
> https://github.com/ItemsAdder/DefaultPack/blob/82a3d2fa786a8901f86c7fc7ea580bbc58fb2ce8/contents/iasurvival/configs/thirst/items/coffee.yml#L4
> 
> ## Hot chocolate
> When drunk it doesn't give back any empty container.
> 
> https://github.com/ItemsAdder/DefaultPack/blob/82a3d2fa786a8901f86c7fc7ea580bbc58fb2ce8/contents/iasurvival/configs/thirst/items/hot_chocolate.yml

Drinkable potion that you can drink infinitely, cancelling drink event would do that, it doesn't cancel it though

**Comment by LoneDev6** [comment]
> Drinkable potion that you can drink infinitely

Give the item back using the give_item action

**Comment by yorik100** [comment]
> > Drinkable potion that you can drink infinitely
> 
> Give the item back using the give_item action

Did you fix drink event not being cancellable?

**Comment by LoneDev6** [comment]
You could give a copy of the item back using the `give_item` action instead, isn't it a solution?
