### ISSUE TITLE
glow_near_blocks duration

### ISSUE THREAD

**Issue by yorik100** [PluginBugs/Issues-ItemsAdder#2721]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

yorik100#5011

### Describe the solution you'd like

Add a way to add a duration to "glow_near_blocks" effect for potions for example
Example :
```shell
  diamonds_finder_potion:
    enabled: true
    display_name: display-name-diamonds_finder_potion
    permission: iaalchemy.items.potions.diamonds_finder_potion
    lore:
      - lore-1-diamonds_finder_potion
    resource:
      material: POTION
      generate: true
      textures:
        - item/diamonds_finder_potion
    specific_properties:
      potion:
        type: SPEED
        color: WHITE
    item_flags:
      - HIDE_POTION_EFFECTS
    events:
      drink:
        glow_near_blocks:
          duration: 60
          decrement_durability:
            amount: 1
          radius:
            x: 50
            'y': 50
            z: 50
          material: DIAMOND_ORE
```
### Is your feature request related to a problem?

No

### Describe alternatives you've considered

None

**Comment by LoneDev6** [comment]
Implemented with `ticks` property
