### ISSUE TITLE
itemsadder 

### ISSUE THREAD

**Issue by JIMIN0402** [PluginBugs/Issues-ItemsAdder#2726]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

JIMIN#0402

### What happened?

https://paste.helpch.at/baxujakiso.md

### Steps to reproduce the issue

I do not know

### Server version

1.19.2

### ItemsAdder Version

3.4.1f2

### ProtocolLib Version

5.0.0-SNAPSHOT-b606

### LoneLibs Version

1.0.24

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11712522/latest.log)

**Comment by SirCraftypants** [comment]
They are a fresh install, they are running their server from their computer.

I helped them install my fishing pack which is installed correctly.

They are getting this resource pack generation error i asked them to report.  I believe they are Korean and are using a translator.

I've checked their resource pack and made sure they installed it correctly, i'm guessing it's something to do with them running it on their computer?

**Comment by LoneDev6** [comment]
`다른 프로세스가 파일을 사용 중이기 때문에 프로세스가 액세스 할 수 없습니다`
Translated: `The process cannot access the file because another process is using it`

You probably have the `generated.zip` file opened using another program while ItemsAdder is trying to edit it.
Close that program.
