### ISSUE TITLE
REAL_WIRE block with cancel_drop enabled will not drop item when broken with shears

### ISSUE THREAD

**Issue by evilsaloon** [PluginBugs/Issues-ItemsAdder#2728]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

evilsaloon#3438

### What happened?

I have made a custom block that is meant to act like grass. When the block is broken with shears, the custom loot I have set up does not drop. The offending block will drop the custom loot if you change shears to something like a pickaxe or a regular axe.

Might be a consequence of fixing #1225.

### Steps to reproduce the issue

1. Add item from items.yml config
2. /iazip
3. Try to break the item with shears

### Server version

Current: git-Purpur-1985 (MC: 1.19.4)*
Previous: git-Purpur-1769 (MC: 1.19.2)
* You are running the latest version

### ItemsAdder Version

ItemsAdder version 3.4.1f2

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-636

### LoneLibs Version

LoneLibs version 1.0.24

### FULL server log

https://pastebin.com/4nGysCqf

### Error (optional)

```shell
No error logged in chat.
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: testserv
items:
  fake_grass_block:
    nbt: "{display:{Name:'{\"italic\":false,\"translate\":\"item.testserv.fake_grass_block\"}'}}"
    permission: testserv
    resource:
      generate: false
      material: PAPER
      model_path: fake_grass
    specific_properties:
      block:
        cancel_drop: true
        placed_model:
          type: REAL_WIRE
          break_particles: BLOCK
          rotx: 0
          roty: 0
        break_tools_whitelist:
          - SHEARS
          - shears
        hardness: 1.5
        blast_resistance: 1.5
        sound:
          break:
            name: block.grass.place
          place:
            name: block.grass.break
  fake_grass_item:
    nbt: "{display:{Name:'{\"italic\":false,\"translate\":\"item.testserv.fake_grass\"}'}}"
    permission: testserv
    resource:
      generate: true
      material: PAPER
      textures:
      - block/fake_grass.png
    events:
      interact:
        right:
          set_block:
            block: testserv:fake_grass_block
            decrement_amount: true
loots:
  blocks:
    fake_grass_block:
      type: testserv:fake_grass_block
      items:
        fake_grass_item:
          item: testserv:fake_grass_item
          min_amount: 1
          max_amount: 1
          chance: 100
```

### Other files, you can drag and drop them here to upload. (optional)

N/A

### Screenshots/Videos (you can drag and drop files or paste links)

N/A

**Comment by LoneDev6** [comment]
Will be checked as soon as possible, thanks
