### ISSUE TITLE
Ialiquids

### ISSUE THREAD

**Issue by Arrandirs** [PluginBugs/Issues-ItemsAdder#2731]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Ell1pse#7291

### What happened?

the problem from this: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2525 
Is still not fixed ! 

### Steps to reproduce the issue

Start your server

### Server version

1.19.4

### ItemsAdder Version

Tried on 3.4.1b to 3.4.1f2

### ProtocolLib Version

5.0.0.SNAPSHOT.b630

### LoneLibs Version

1.0.24

**Comment by LoneDev6** [comment]
- stop the server
- open the folder `datapacks` on each of your worlds
- delete all folders which start with `ia_`
- start the server
- load the plugin
- restart the server

everything should work fine now.
Let me know please
