### ISSUE TITLE
1.20.1 compatibility

### ISSUE THREAD

**Issue by CCjun6** [PluginBugs/Issues-ItemsAdder#2732]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

This plugin is not available in version 1.20
Please update the author if you have time

### Is your feature request related to a problem?

This plugin is not available in version 1.20
Please update the author if you have time

### Describe alternatives you've considered

This plugin is not available in version 1.20
Please update the author if you have time

**Comment by dinobossytnew** [comment]
give it to the dev if it's not even in spigot yet.

**Comment by dinobossytnew** [comment]
https://getbukkit.org/download/spigot api dev

**Comment by LoneDev6** [comment]
I already announced on Discord that I'll add support in the next weeks.
