### ISSUE TITLE
Issues with MyPet

### ISSUE THREAD

**Issue by TUCAOEVER** [PluginBugs/Issues-ItemsAdder#2737]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I got this error when player's pets got killed.
https://pastebin.com/jnapCqvv

### Steps to reproduce the issue

1.Player's pets got killed by some mobs with MyPet intergration.

### Server version

 This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### ItemsAdder Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/43756134/e82266b5-ac66-4523-9e0e-939fdba667ad)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/43756134/046082a8-0812-44c4-941a-854477ace240)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/43756134/0e49e10a-7caa-44a7-b4ae-9b0a1100b597)

**Comment by LoneDev6** [comment]
Seems the json message from mypets is malformed.
Test if this still happens with latest version of itemsadder, lonelibs, spigot/paper and mypet.
