### ISSUE TITLE
Sound and Particle with "REAL_NOTE"

### ISSUE THREAD

**Issue by Weyl1** [PluginBugs/Issues-ItemsAdder#2747]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I'm trying to create custom blocks but I don't understand why when I left-click I always get the sound and the music block particle, I don't think this is normal.

### Steps to reproduce the issue

Check this video: 
https://www.youtube.com/watch?v=pVkWYC8N3Yg

### Server version

Purpur-1995 1.20.1

### ItemsAdder Version

3.5.0

### ProtocolLib Version

5.1.0-SNAPSHOT-652

### LoneLibs Version

1.0.25

### Problematic items yml configuration file (optional)

```shell
iridium_ore:
    display_name: "&fIridium Ore"
    resource:
      material: PAPER
      generate: true
      textures:
        - iridium_ore.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
        cancel_drop: true
        break_tools_whitelist:
        - PICKAXE
        - amethyst_pickaxe
        - iridium_pickaxe
        - amber_pickaxe
        - malachite_pickaxe
        - ruby_pickaxe
        - jade_pickaxe
        - silver_pickaxe
        - mythril_pickaxe
        hardness: 1
```

**Comment by LoneDev6** [comment]
Will be checked asap
