### ISSUE TITLE
Inability to pick berries 

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#2748]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/2670
> Also, when planting berries and growing them 2 times with bone meal, it is impossible to collect them.

https://github.com/PluginBugs/Issues-ItemsAdder/issues/2670#issuecomment-1593640616
> issue to pick berries in my server when they are growth level 1.

**Comment by LoneDev6** [comment]
Can't reproduce. Might need another plugin interfering.

https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/2521d666-332b-44e2-bfb1-2f002a20df4f

**Comment by auyylaso** [comment]
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/70453553/f081702d-0194-4377-bc0e-c099bd6064f6)
Tier one berries can't be collected. Tier two growth can be collected just fine.

https://github.com/PluginBugs/Issues-ItemsAdder/assets/70453553/6db9d8a9-a636-4079-9b3e-363e8673cc6e
