### ISSUE TITLE
I'm not able to see the new trim armor 1.20

### ISSUE THREAD

**Issue by matipoirierg** [PluginBugs/Issues-ItemsAdder#2749]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

emoticones#5498

### What happened?

I'm not able to see the new trim textures of 1.20 armor when equipped.
![2023-06-16_11 06 47](https://github.com/PluginBugs/Issues-ItemsAdder/assets/97362850/65a4dc32-6e1f-4119-9258-2b6e70f5ce4a)

### Steps to reproduce the issue

Equip new trim armor with items adder resourcepack

### Server version

Current: git-Purpur-1995 (MC: 1.20.1)*
Previous: git-Purpur-1990 (MC: 1.20)
* You are running the latest version

### ItemsAdder Version

ItemsAdder Version 3.5.0

### ProtocolLib Version

5.1.0-653

### LoneLibs Version

1.0.25

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11771776/latest.log)

### Other files, you can drag and drop them here to upload. (optional)

[generated.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/11771779/generated.zip)

**Comment by LoneDev6** [comment]
I'll check this, thanks for the report

**Comment by matipoirierg** [comment]
Thanks! Could you confirm me if you can reproduce it when you test it?

**Comment by LoneDev6** [comment]
Works fine for me.

## Trimmed Netherite armor

![Image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/6ead5d0c-718e-4c64-b946-2b3e27ad33fc)

## Custom armor


Downloaded from the [example pack](https://www.spigotmc.org/resources/addon-more-itemsadder-minerals-and-custom-armors-for-itemsadder.97688/).

![Image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/0ae3592d-cea5-46f5-9d8c-fd299c7301cd)
