### ISSUE TITLE
Itemsadder Emote

### ISSUE THREAD

**Issue by 21MX** [PluginBugs/Issues-ItemsAdder#2754]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

21mx

### What happened?

I have updated to the 1.20 then the emotes were broken

### Steps to reproduce the issue

1.20
/emote

### Server version

This server is running Paper version git-Paper-32 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 3885666)
You are running the latest version
Previous version: git-Paper-307 (MC: 1.19.2)

### ItemsAdder Version

ItemsAdder version .5.0

### ProtocolLib Version

ProtocolLib version .1.0-SNAPSHOT-654

### LoneLibs Version

LoneLibs version .0.25

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11778630/latest.log)

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/114404655/2f1c7fd9-7acc-453c-8ac4-d7e4df23d7a6)

**Comment by LoneDev6** [comment]
Update to the latest version and make sure to run /iazip to refresh your pack.
