### ISSUE TITLE
Models in emotes

### ISSUE THREAD

**Issue by TheSPREEGuy** [PluginBugs/Issues-ItemsAdder#2756]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

spreeguy

### What happened?

When playing an emote that has custom models it breaks your skin

### Steps to reproduce the issue

1. make a advance emote with models
2. then use it in game

### Server version

This server is running Paper version git-Paper-32 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 3885666)
You are running the latest version

### ItemsAdder Version

ItemsAdder version 3.5.0

### ProtocolLib Version

ProtocalLib version 5.1.0-SNAPSHOT-654

### LoneLibs Version

LoneLibs version 1.0.25

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11779367/latest.log)

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/23518058/0e8d7b86-f055-4638-8944-8860bc2c643e)

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/2766
