### ISSUE TITLE
Trees spawned with trees_populators generate floating in the air

### ISSUE THREAD

**Issue by evilsaloon** [PluginBugs/Issues-ItemsAdder#2758]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

evilsaloon#3438

### What happened?

Newly generated trees via trees_populators spawn floating several blocks above the ground. Sometimes it's just one block, but other times it can be 5 or 6 (I attached a funny screenshot to this issue)

trees_populators were working fine before 1.20.1, could be a 1.20-related bug.

### Steps to reproduce the issue

1. Add trees_populators from config below
2. /iareload
3. Go into new chunks
4. Funny

### Server version

Current: git-Purpur-1995 (MC: 1.20.1)*
Previous: git-Purpur-1985 (MC: 1.19.4)
* You are 1 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### ItemsAdder Version

ItemsAdder version 3.5.0

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-636

### LoneLibs Version

LoneLibs version 1.0.25

### FULL server log

https://pastebin.com/WGzeS3eS

### Error (optional)

```shell
No error in console.
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: testserv
trees_populators:
  floating_tree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    - SNOW
    - SNOW_BLOCK
    chance: 40.0
    max_height: 100
    min_height: 50
    amount: 1
    iterations: 1
    tree_type: TREE
    leaves: testserv:floating_leaves
    log: testserv:floating_log
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/80675840/82ee0657-8ae4-494a-a602-9e2ebfad746d)

**Comment by LoneDev6** [comment]
This seems to be caused by some shitty Minecraft internal code updates since I use the internal game code to spawn trees.
I'll check this to see if I can fix this, thanks.

**Comment by yorik100** [comment]
> This seems to be caused by some shitty Minecraft internal code updates since I use the internal game code to spawn trees. I'll check this to see if I can fix this, thanks.

Bugs like that also happen
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/16320315/dddb95f4-cb0a-4ae1-b88e-1120a1153d17)

**Comment by LoneDev6** [comment]
Fixed!
Anyway if you ever encounter this kind of issue please don't report it as I cannot fix it. It's something to do how world generation is handled by Spigot and I can't find out why this happens only occasionally.

![Image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/5c3c5596-a616-4c85-8fbc-72301d24b1ee)
