### ISSUE TITLE
Issue with texture on 1.20.1

### ISSUE THREAD

**Issue by SinistersGrin** [PluginBugs/Issues-ItemsAdder#2760]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

sinistersgrin

### What happened?

Attempting to update our server from 1.19.2 to 1.20.1

The issue is with textures not loading properly, using Viaversion and Viabackwards if you connect to the server on 1.19.2 it works fine but logging in on 1.20.1 the textures will not load 

This was tested on 3 different account on different computers, any version under 1.20.1 textures load properly and work
If you want access to the test server to see it yourself please let me know

### Steps to reproduce the issue

1. Using ItemsAdder version 3.5.0 
2. upload a pack and do /iazip when its done do /ia
3. some textures like the normal ones that come with IA work but the custom ones for the most part do not

Side note if you'd like one of our own custom textures to test we can send it

### Server version

This server is running Paper version git-Paper-32 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 3885666)
You are 4 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-21 (MC: 1.20.1)

### ItemsAdder Version

ItemsAdder version 3.5.0

### ProtocolLib Version

ProtocolLib version 5.1.0-SNAPSHOT-654

### LoneLibs Version

LoneLibs version 1.0.25

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11780223/latest.log)

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/115602637/12bd22e8-68da-4b42-a0dc-e8d9b575fa46)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/115602637/53c4cce5-7a53-4552-aa97-8cae285e4afb)

**Comment by SinistersGrin** [comment]
Just tried this with Itemsadder version 3.5.0-r2 and still the same result

**Comment by LoneDev6** [comment]
1. make sure you enabled `1_19_3_atlas_support: true` in config.yml of itemsadder and regenerate your resourcepack using /iazip
2. read here https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown


There is no way for me to identify why your models/textures don't load.
The CLIENT log (as explained in the tutorial) will show you exactly why textures and models don't load and you can easily fix it.
Anyway ItemsAdder should print on the SERVER log warning you about issues in your pack, so the client log can contain additional information but common misconfigurations are already detected by ItemsAdder.

**Comment by SinistersGrin** [comment]
1_19_3_atlas_support: true was what the config already had, tried disabling it, restarting and zipping, same thing.
Turned it on did the same thing still the same result. 
Im confused as to how the issue is even a thing, literally nothing was changed aside from the server jar and updating ItemsAdder then starting the server.

I could me missing things here but i really just need the help cause it makes no sense to me that connecting to the server on 1.18 to 1.19.4 works perfectly, but if you log onto the exact same server on 1.20.1 the textures all just break.... there are no restarts, no config changes or re zipping it just works for lower versions that are not 1.20.x

As for the Client Logs when joining on 1.19.4 it shows very few missing textures and thats fine all the textures that worked previously still work, on 1.20.1 the Client Logs throw thousands of line with literally EVERY every pack we have as "Missing textures in model"? 

This is the only thin holding us back from updating so really any help i can get here id appreciate

**Comment by LoneDev6** [comment]
Keep it enabled please, you're not supposed to disable it.
I let it configurable because some customers wanted to create the atlas manually (which is a special file).
This is a thing because Mojang introduced a new feature in the resourcepack and requires this atlas file to be created in order to load textures which are not in the usual Minecraft textures folders: `item`, `block`.

Please read again the guide I sent you. You really have to read your client log, it tells you EXACTLY why stuff didn't load.
If you can't really find the issue in the CLIENT log please attach it here and I'll take a look for you, but please at least try.
Send me both your CLIENT and SERVER logs of when you run /iazip.

Remember to read the guide, I explained in detail how to get the CLIENT log, don't send me your SERVER log only.

**Comment by SinistersGrin** [comment]
I am really sorry if this is a mistake on my side but i've read the wiki page and i mean REALLY tried, ive been trying since it was updated and i cant for the life of me figure this out, so i do really appreciate you taking the time to have a look, and again if it is an error on my side i do genuinely apologize

Client logs
[latest Client.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11782584/latest.Client.log)

Server logs
[latest Server.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11782585/latest.Server.log)

**Comment by SinistersGrin** [comment]
These are the Client logs when i log in using 1.19.2 on the same server
[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11782600/latest.log)

What i see when i do /ia
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/115602637/48744a0c-0c95-4b92-bb2b-cd923efa50be)

**Comment by LoneDev6** [comment]
> [23:18:43] [Worker-Main-2/ERROR]: Failed to load model myitems:models/ia_auto_gen/stone_mossy3.json
com.google.gson.JsonParseException: myitems:blocks/Stone_Mossy3 is not valid resource location

and so on.

You have lot of malformed texture names, for example: `Stone_Mossy3`
Minecraft doesn't allow uppercase names or special characters other than `_`.

**Comment by SinistersGrin** [comment]
.............. thats a response i guess.... thanks for the help? 
works and has worked since 1.19.2 came out, update to 1.20.1 and it all breaks....

honestly dont know how to fix it and expected ANY kind of help but sadly got "go fix it" when it previously worked and still does on every version that isnt 1.20, it is what it is i guess.. thanks.

**Comment by LoneDev6** [comment]
I have no control on how the game works. There are the rules of the game resourcepack and were decided by Mojang.
I clearly noted in the wiki in multiple places to make sure people know this, I really can't do anything more than this.

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/4dac74d9-60f4-4480-817d-45269d84e34e)
https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown#resourcepack-not-loading-i-get-an-error-in-chat
https://itemsadder.devs.beer/plugin-usage/adding-content/item-properties/resource

Also I tried my best to create the easiest to read log, the errors are detailed and tell you exactly what you change in order to fix the pack.

I can't edit the game code to fix this, Mojang decided to break stuff during updates adding this kind of rules, I wish there was more control but it's not possible.

Have a nice week!

**Comment by SinistersGrin** [comment]
for some reason 1.20.1 wont load textures and every version down to 1.16 that i tested will, what changed? why is me joining the same server on 1.20.1 an issue but not lower? there are thousands of files that i have to go find, rename and hope that it works ? what the difference in the version why does joining on the latest have this issue ? it literally makes no sense to work if you join on 1.19.4 but then on the same exact server to break on 1.20.1...

**Comment by LoneDev6** [comment]
They are different game versions.
Mojang is known to recode core game parts between updates, you can't expect the game to work exactly the same on each game version.

I sadly have no control over this and I try my best to make sure the plugin works fine on every version of the game listed in the compatibility list.
