### ISSUE TITLE
Users can destroy blocks

### ISSUE THREAD

**Issue by Naghell** [PluginBugs/Issues-ItemsAdder#2762]
### What happened?

Users can remove placed blocks from ItemsAdder.

### Steps to reproduce the issue

1. Go to the block
2. Hit the block
3. Destroy the block

### Server version

git-Paper-549 (MC: 1.19.4)

### ItemsAdder Version

ItemsAdder v3.5.0

### ProtocolLib Version

ProtocolLib version 5.1.0-SNAPSHOT-654

### LoneLibs Version

LoneLibs version 1.0.25

**Comment by LoneDev6** [comment]
Make a video please.
Anyway this error is not related to blocks but another bug which happens if you delete a vehicle from configurations and you still have it in the world, then when you hit it to remove it you get the error.
