### ISSUE TITLE
No saturation limit issue

### ISSUE THREAD

**Issue by yorik100** [PluginBugs/Issues-ItemsAdder#2763]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

yorik100

### What happened?

Eating food can result in food (or saturaturation) to go past 20

Using the /whois command from essentials
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/16320315/b4df3c22-00be-447c-93f3-a9336d37db71)

### Steps to reproduce the issue

1. Use items that feed even if your hunger bar is full
2. Your hunger bar will go past 20

### Server version

git-Purpur-"6886272" (MC: 1.19.4)

### ItemsAdder Version

3.4.1f2

### ProtocolLib Version

5.1.0-SNAPSHOT-645

### LoneLibs Version

1.0.24

### FULL server log

Not needed

### Problematic items yml configuration file (optional)

```shell
https://pastebin.com/sumeYbFE
```

**Comment by LoneDev6** [comment]
It's a bug of Spigot itself, I have no idea why it doesn't check for saturation max value internally.
Food level seems to do that under the hood.
```java
p.setSaturation(p.getSaturation() + saturation);
```

Will be fixed.
