### ISSUE TITLE
WorldEdit issue

### ISSUE THREAD

**Issue by Distolfix** [PluginBugs/Issues-ItemsAdder#2769]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Quando tolgo con la worledit per esempio il blocco di Cherry, https://www.spigotmc.org/resources/trees-newtrees-for-itemsadder.84604/ che può essere con sp area 5, con //set 0 ecc... si crea un comportamento imprevisto che può essere molto grave

### Steps to reproduce the issue

https://youtu.be/m8VdCRbKilI

### Server version

This server is running Pufferfish version git-Pufferfish-73 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: cadfa71 on HEAD)
You are on the latest version!
Previous version: git-Pufferfish-61 (MC: 1.19.3)

### ItemsAdder Version

3.5.0

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/73421268/a0bfe59e-e385-4ddf-832d-5d7a107444e8)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/73421268/51fd6eb7-17b5-45bf-a25a-f1c2c7fd244f)

**Comment by LoneDev6** [comment]
Hai installato il plugin per la compatibilità di worldedit o no?
https://www.spigotmc.org/resources/addon-itemsadder-worldedit.79012/

**Comment by Distolfix** [comment]
Avevi ragione. grazie

**Comment by LoneDev6** [comment]
Di nulla! Comunque sappi che ci sono alcuni problemi che devo correggere per aggiungere compatibilità all'ultima versione di WorldEdit.
Sono riportati qui e verranno fixati nei prossimi giorni:
https://github.com/PluginBugs/Issues-ItemsAdder/issues/2713
https://github.com/PluginBugs/Issues-ItemsAdder/issues/2653
