### ISSUE TITLE
Emote should support alex model

### ISSUE THREAD

**Issue by ArtifactyNight** [PluginBugs/Issues-ItemsAdder#2770]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

nightkungz

### What happened?

For now, Itemsadder's Emote not support alex model but some plugin like HMCCosmetic does
Can you fix this? Emote feature from Itemsadder is very nice but I don't use this feature yet because of this reason 😅

https://streamable.com/e4anzu

### Steps to reproduce the issue

Just play emote

### Server version

Current: git-Purpur-1996 (MC: 1.20.1)*
Previous: git-Paper-38 (MC: 1.20.1)
* You are running the latest version

### ItemsAdder Version

3.5.0 R2

### ProtocolLib Version

5.0.0

### LoneLibs Version

1.0.25

**Comment by LoneDev6** [comment]
by alex you mean slim model?
i'll definitely look into fixing that, but will require some work to the current logic

**Comment by ArtifactyNight** [comment]
> by alex you mean slim model? i'll definitely look into fixing that, but will require some work to the current logic

Yes! i mean slim model
