### ISSUE TITLE
Option for silent cooldown

### ISSUE THREAD

**Issue by yorik100** [PluginBugs/Issues-ItemsAdder#2779]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

yorik100

### Describe the solution you'd like

An option to disable this message for specific objects
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/16320315/f41cc776-9be6-4bc0-a315-45b71a08b45a)
Currently I just set the message to empty in the config which makes the cooldown not show up for every items but I just want to make the cooldown silent for a single item

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

None

**Comment by LoneDev6** [comment]
Might be part of this other idea: https://github.com/PluginBugs/Issues-ItemsAdder/issues/1670

**Comment by LoneDev6** [comment]
```yml
    events_settings:
      cooldown:
        indicator: HIDDEN
        ticks: 60
```
