### ISSUE TITLE
Add silent iaplaysound option

### ISSUE THREAD

**Issue by yorik100** [PluginBugs/Issues-ItemsAdder#2790]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

yorik100

### Describe the solution you'd like

Just like with other commands, silent with no output

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

None

**Comment by LoneDev6** [comment]
You can use the normal Minecraft playsound by the way, there is no need to use iaplaysound command.
This command was introduced because some user requested it as the console doesn't autocomplete vanilla `/playsound`.

**Comment by LoneDev6** [comment]
Now `/iaplaysound` won't print any message and will just play the sound to the specified player
