### ISSUE TITLE
API `replaceFurniture` makes ItemFrame-Furniture to show/appear CustomNameDisplay

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#2794]
More info: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2630

**Comment by IPECTER** [comment]
After using replace, can continue to install it in the same location with right-clicking edge.
I think it'll be solved if solve the problem with CustomNameTag

**Comment by IPECTER** [comment]
If you use ItemFrame#set 
Instead of `set(ItemStack)`, please use `set(ItemStack, false)`
This will eliminate the sound that comes out during replacement

**Comment by IPECTER** [comment]
@LoneDev6 any news? check above

**Comment by IPECTER** [comment]
I love you!!!

**Comment by LoneDev6** [comment]
Will be fixed, please stop bumping this thread, it's planned for the upcoming update

**Comment by IPECTER** [comment]
Thx! ..
