### ISSUE TITLE
 disable /e

### ISSUE THREAD

**Issue by chrydin** [PluginBugs/Issues-ItemsAdder#2798]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

kimchifriedbrain

### Describe the solution you'd like

TItle, i use advanced enchantments and the main command to open the enchant is /enchanter but everyone uses /e b/c its shorter.
With the new itemsadder update /e now opens a blank page of a book rendering it useless.

Was wondering if i could disable this?

Thanks!

### Is your feature request related to a problem?

no

### Describe alternatives you've considered

removed itemsadder and /e works fine, but i need itemsadder for other plugins

**Comment by SirJben** [comment]
+1 Would love to get this done :D

**Comment by LoneDev6** [comment]
- open ItemsAdder jar with 7zip or a zip editor
- extract plugin.yml
- rename the /e command to something else, like ee
- put the plugin.yml back into the jar file
- done

Do this on each update.
There is no clean solution to support multiple plugins which register the same command, it's a limitation of Spigot/Minecraft.
