### ISSUE TITLE
Armor durability does not decrease upon taking fall damage

### ISSUE THREAD

**Issue by evilsaloon** [PluginBugs/Issues-ItemsAdder#2800]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

evilsaloon#3438

### What happened?

When wearing custom IA armor, the durability doesn't decrease when the player takes fall damage.

### Steps to reproduce the issue

1. Add item .yml
2. /iazip
3. Take fall damage
4. Durability remains the same

### Server version

Current: git-Purpur-1996 (MC: 1.20.1)*
Previous: git-Purpur-1995 (MC: 1.20.1)
* You are 4 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### ItemsAdder Version

ItemsAdder version 3.5.0b

### ProtocolLib Version

ProtocolLib version 5.1.0-SNAPSHOT-654

### LoneLibs Version

LoneLibs version 1.0.25

### FULL server log

https://pastebin.com/3Qf7GSDc

### Error (optional)

```shell
No error in console.
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: testserv
items:
  testium_helmet:
    nbt: "{display:{Name:'{\"italic\":false,\"translate\":\"item.testserv.testium_helmet\"}'}}"
    #display_name: "testium Helmet"
    permission: testserv
    durability:
       max_custom_durability: 121
    specific_properties:
      armor:
        slot: HEAD
        custom_armor: testium
    attribute_modifiers:
      head:
        armor: 2
        armorToughness: 0
    resource:
      generate: true
      textures:
        - testium/testium_helmet.png
  testium_chestplate:
    nbt: "{display:{Name:'{\"italic\":false,\"translate\":\"item.testserv.testium_chestplate\"}'}}"
    #display_name: "testium Chestplate"
    permission: testserv
    durability:
       max_custom_durability: 176
    specific_properties:
      armor:
        slot: CHEST
        custom_armor: testium
    attribute_modifiers:
      chest:
        armor: 5
        armorToughness: 0
    resource:
      generate: true
      textures:
        - testium/testium_chestplate.png
  testium_leggings:
    nbt: "{display:{Name:'{\"italic\":false,\"translate\":\"item.testserv.testium_leggings\"}'}}"
    #display_name: "testium Leggings"
    permission: testserv
    durability:
       max_custom_durability: 165
    specific_properties:
      armor:
        slot: LEGS
        custom_armor: testium
    attribute_modifiers:
      legs:
        armor: 3
        armorToughness: 0
    resource:
      generate: true
      textures:
        - testium/testium_leggings.png
  testium_boots:
    nbt: "{display:{Name:'{\"italic\":false,\"translate\":\"item.testserv.testium_boots\"}'}}"
    #display_name: "testium Boots"
    permission: testserv
    durability:
       max_custom_durability: 143
    specific_properties:
      armor:
        slot: FEET
        custom_armor: testium
    attribute_modifiers:
      feet:
        armor: 1
        armorToughness: 0
    resource:
      generate: true
      textures:
        - testium/testium_boots.png
armors_rendering:
  testium:
    color: "#000001"
    layer_1: testium/armor/testium_layer_1
    layer_2: testium/armor/testium_layer_2
    use_color: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://github.com/PluginBugs/Issues-ItemsAdder/assets/80675840/65aff0eb-4717-49aa-b1ab-6c88893ccd5c

**Comment by LoneDev6** [comment]
Can you confirm vanilla armors durability lowers down when taking fall damage?

**Comment by evilsaloon** [comment]
Sorry, had a Mandela effect moment. Turns out it doesn't happen.
