### ISSUE TITLE
The slabs not placed correctly

### ISSUE THREAD

**Issue by Weyl1** [PluginBugs/Issues-ItemsAdder#2807]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Slabs do not place properly on REAL NOTE blocks
When I click on the top of a block with a tile, it places the tile towards the bottom of the block.

### Steps to reproduce the issue

https://www.youtube.com/watch?v=PTQN1_zvAIM

### Server version

git-Purpur-1996 (MC: 1.20.1)*

### ItemsAdder Version

3.5.0b

### ProtocolLib Version

5.1.0 SNAPSHOT-654

### LoneLibs Version

1.0.25

### Screenshots/Videos (you can drag and drop files or paste links)

https://www.youtube.com/watch?v=PTQN1_zvAIM

**Comment by evilsaloon** [comment]
+1 on 3.5.0c. Slabs cannot be placed in the top position, they are automatically placed on the lower portion of the block.
