### ISSUE TITLE
custom_variants doesnt generate

### ISSUE THREAD

**Issue by wolfawwent** [PluginBugs/Issues-ItemsAdder#2814]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

custom_variants not working
and i check the blockstate tripwire in resources pack found it didnt generate variants
other staff is fine

### Steps to reproduce the issue

https://pastebin.com/pKFE1svC

### Server version

paper 1.19.4-550

### ItemsAdder Version

itemsadder 3.5.0

### ProtocolLib Version

ProtocolLib 5.0.0

### LoneLibs Version

LoneLibs 1.0.25

### FULL server log

not show any error log

**Comment by LoneDev6** [comment]
Will be checked, strange. It was working correctly on first release.

**Comment by wolfawwent** [comment]
😥

**Comment by LoneDev6** [comment]
![Image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/7c3e375d-75fc-4847-9b1d-4e68d5668c76)

Wrong indentation, you have to shift it:



![Image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/6475d47a-9cbf-4df0-8127-c4ced18af0c0)



Please use the official files editor to write files so you get correct autocomplete.
https://itemsadder.devs.beer/plugin-usage/files-editor
