### ISSUE TITLE
`held` `unheld` not triggered when pressing hotkey numbers to replace the current item in inventory (chests)

### ISSUE THREAD

**Issue by Distolfix** [PluginBugs/Issues-ItemsAdder#2818]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

whiteombrah

### What happened?

Volevo segnalarti che vi è un altro modo per far rimanere gli effetti degli items, non so se con il nuovo aggiornamento previsto 3.5.1 sarà risolto da solo, però ti mando un nuovo metodo che ho scoperto. Anche perchè da quel che so, hai rilasciato una patch per risolvere un bug simile. Fammi sapere.

### Steps to reproduce the issue

https://www.youtube.com/watch?v=SC8s1dcV_Js

### Server version

This server is running Pufferfish version git-Pufferfish-73 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: cadfa71 on HEAD)
You are on the latest version!
Previous version: git-Pufferfish-61 (MC: 1.19.3)

### ItemsAdder Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/73421268/74b7955f-ef21-4d33-876e-0fa9be164efc)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/73421268/ab8b3bcd-f42d-4a6f-b793-1b0835688fb8)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/73421268/74542b11-7563-4385-91df-fe5b2b98722e)

### Other files, you can drag and drop them here to upload. (optional)

Related to

https://github.com/PluginBugs/Issues-ItemsAdder/issues/2620

**Comment by LoneDev6** [comment]
Per favore mandami anche il config degli/dello oggetto che applicano questo effetto altrimenti non so cosa fare per testare.

**Comment by Distolfix** [comment]
https://forum.devs.beer/d/1634-haste-bug

**Comment by LoneDev6** [comment]
`held` `unheld` not triggered when pressing hotkey numbers to replace the current item in inventory.
This happens only on chests, works fine on player inventory.

https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/4b38c788-a275-41c8-9f76-352af081e6fc
