### ISSUE TITLE
Shopping carts can't jump on dirt paths

### ISSUE THREAD

**Issue by yorik100** [PluginBugs/Issues-ItemsAdder#2822]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

yorik100

### What happened?

Can't jump with shopping carts (and probably more vehicles) if shopping cart is on dirt path, maybe ItemsAdder ground check is wrong, every blocks have a size that is a multiple of 0.015625

### Steps to reproduce the issue

1. Get into shopping cart
2. Go in the middle of a 4 by 4 dirt path area
3. Can't exit it, can't jump

### Server version

git-Purpur-"625e4ad" (MC: 1.20.1)

### ItemsAdder Version

3.5.0c

### ProtocolLib Version

5.0.0

### LoneLibs Version

1.0.25

### FULL server log

Not needed

**Comment by DexterSK** [comment]
Can you use Go-Carts? When i mount it, i get stuck 1 block under ground and when pressing space it just disappear

**Comment by LoneDev6** [comment]
> and probably more vehicles

Please test

**Comment by LoneDev6** [comment]
Can't reproduce.
`This server is running Paper version git-Paper-57 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 437e8da)`

https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/e23ebdbd-67b7-44ab-b2d2-2cac066c3492
