### ISSUE TITLE
1.20.1 Texture pack not loading

### ISSUE THREAD

**Issue by Truongvv10** [PluginBugs/Issues-ItemsAdder#2823]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Wassabi#0317

### What happened?

When joining the server on 1.20.1 server, it kicks me out when loading texture pack saying that "Resource reload failed". When joining on just 1.20 on a 1.20.1 server, that works to load the texture pack.
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/67742370/d6f1bdbf-fd55-41eb-8965-f4bb7413dca0)

### Steps to reproduce the issue

1. Join on 1.20.1 server
2. Get the resource pack downloaded

### Server version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/67742370/90f35574-1eb1-44bd-8f8f-f07a11dbbc14)

### ItemsAdder Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/67742370/2c11ba3a-5869-4b6f-8a43-5edc820f129a)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/67742370/78efac69-07eb-4011-96d3-6d004113cbc5)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/67742370/151e88a5-4805-43dc-9588-41b58c1498b8)

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11895046/latest.log)

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/67742370/d6f1bdbf-fd55-41eb-8965-f4bb7413dca0)

**Comment by LoneDev6** [comment]
1. update ProcotolLib
2. update ViaVersion and ViaBackwards
3. update Paper/Spigot itself
4. read here https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown

**Comment by Truongvv10** [comment]
> 1. update ProcotolLib
> 2. update ViaVersion and ViaBackwards
> 3. update Paper/Spigot itself
> 4. read here https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown

I'm using the latest dev build of protocolib, with viaversion and viabackwards on my bungee
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/67742370/b7b8f6f7-ecf1-4d5f-8930-80e969110afb)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/67742370/0b522837-2880-46be-9ab7-778526fd8ea1)

**Comment by Truongvv10** [comment]
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/67742370/8ee78825-79e4-481d-aa65-7cc340c01ca1)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/67742370/394cca9d-246a-4a98-b2d7-789d2d4b85ba)
On my test server

**Comment by LoneDev6** [comment]
Post your CLIENT log of when the issue occurred.
How to get it: https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown

**Comment by Truongvv10** [comment]
> Post your CLIENT log of when the issue occurred. How to get it: https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/67742370/f90db1f0-5a9d-4fe0-89e5-996c3de1ec1a)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/67742370/1e079c3d-2502-47c1-b6f9-b73e63fb7a9f)

**Comment by LoneDev6** [comment]
Check if your pack port is open.
Check if the URL provided can be accessed via browser.

**Comment by Truongvv10** [comment]
If it works on 1.19.4 and 1.20 then it should be open no?

Only issue is it doesnt work on 1.20.1

**Comment by Truongvv10** [comment]
Wait I take it back, it does work. Had to do /iaz
