### ISSUE TITLE
Return replace items called even when reduce durability wasn't successfully called because some items don't satisfy the recipe

### ISSUE THREAD

**Issue by yorik100** [PluginBugs/Issues-ItemsAdder#2827]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

yorik100

### What happened?

Craft arcane ring with empty philosopher stone, it replaces diamond with crystal but the ring instantly disappears and doesn't get crafted

### Steps to reproduce the issue

1. Craft Arcane Ring with empty philosopher stone
2. Wont work and diamond will be replaced by crystal

### ItemsAdder Version

3.5.0c

### ProtocolLib Version

5.0.0

### LoneLibs Version

1.0.25

### FULL server log

Not needed

### Problematic items yml configuration file (optional)

```shell
recipes:
  crafting_table:
    arcane_ring:
      permission: iaalchemy.arcane_ring
      enabled: true
      pattern:
        - XXX
        - XPD
        - XTX
      ingredients:
        P: iaalchemy:philosopher_stone
        D: DIAMOND
        T: TOTEM_OF_UNDYING
      result:
        item: iaalchemy:arcane_ring
        amount: 1
      return_items:
        decrement_durability:
          philosopher_stone:
            item: philosopher_stone
            amount: 8
        replace:
          DIAMOND: crystal
```

**Comment by yorik100** [comment]
> Was it working fine on 3.5.0?

I didn't try at all, all I know is that since it requires 8 durability to stone, craft gets cancelled but diamond still gets replaced

**Comment by LoneDev6** [comment]
Fixed, thanks



https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/9dcfd971-221a-49a8-bd8c-4184eae72ed4
