### ISSUE TITLE
Arrow Damage doesn't make any sense

### ISSUE THREAD

**Issue by yorik100** [PluginBugs/Issues-ItemsAdder#2829]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

yorik100

### What happened?

Astral Bow deals less damage to protection 4 diamond armor players than normal bows HOWEVER, Astral Bow deals MORE damage to mobs than normal bows, same enchants obviously

### Steps to reproduce the issue

1. Use Astral Bow on someone wearing protection 4 armor (natural regeneration off)
2. Wait for them to be full HP, splash them with heal even to make sure that they're on 100% max health
3. Use Bow on that same person, they take more damage
4. Do the same with for example, an Iron Golem, the golem will take way more damage with Astral Bow

### Server version

git-Purpur-"625e4ad" (MC: 1.20.1)

### ItemsAdder Version

3.5.0c

### ProtocolLib Version

5.0.0

### LoneLibs Version

1.0.25

### FULL server log

Not needed

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: iaalchemy
items:
  astral_bow:
    enabled: true
    display_name: display-name-astral_bow
    permission: iaalchemy.items.astral_bow
    resource:
      material: BOW
      generate: true
      textures:
        - item/astral_bow
    enchants:
      - ARROW_FIRE:1
    durability:
      max_custom_durability: 512
    specific_properties:
      bow:
        arrow_damage: 4
    events:
      bow_shot:
        play_sound:
          name: iaalchemy:item.astral_bow.shot
          volume: 1
          pitch: 1
```

**Comment by LoneDev6** [comment]
```java
            int customMaxDamage = e.getDamager().getMetadata("IAArrowDamage").get(0).asInt();

            //finalDamage : 2 = x : customDamage
            //2 = default arrow damage
            e.setDamage((e.getFinalDamage() * customMaxDamage) / 2);
```

**Comment by yorik100** [comment]
> ```java
>             //finalDamage : 2 = x : customDamage
>             //2 = default arrow damage
>             e.setDamage((e.getFinalDamage() * customMaxDamage) / 2);
> ```

Just tried, Astral Bow power 5 deals half a heart to full diamond protection 4 while normal bow power 5 deals 1 heart and a half
However, Astral Bow power 5 deals more damage than bow power 5 to unarmored things like Iron Golem for example

**Comment by LoneDev6** [comment]
This is strange, the formula is correct..

> Also, how to change crossbow damage? I can't find anything to do that

`specific_properties.crossbow.arrow_damage`
