### ISSUE TITLE
Offhand Item is not working

### ISSUE THREAD

**Issue by Focus098xdd** [PluginBugs/Issues-ItemsAdder#2830]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

focus098xdd

### What happened?

I can put Minecraft shield in left hand but I can not take it out I don't it is bug or not

### Steps to reproduce the issue

-

### Server version

Purpur 1.19.2

### ItemsAdder Version

3.4.1f

### ProtocolLib Version

4.8.0

### LoneLibs Version

1.0.24

**Comment by LoneDev6** [comment]
Do not report issues while using old plugin versions. Update before reporting issues.
Also provide your FULL server log of when the issue occurred.
