### ISSUE TITLE
Custom Armor limit on some Hardwares

### ISSUE THREAD

**Issue by Mirayii** [PluginBugs/Issues-ItemsAdder#2833]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

mirayi

### What happened?

This is kinda limitation of Hardware and presumably used FancyPants shaders.
There is a limit of how many custom armors can be added to the game by the Graphics Card.
We tested it with like 4 players on these Graphics Cards:
- Nvidia RTX 3070 - Working
- AMD Radeon RX 580 - Not Working
- Intel UHD 617 - Not Working
- Intel UHD 630 - Not Working

Not really sure what the limit is since i couldn't locate the file which contains the stitched textures.
Maybe use the new "lessfancypants" for armors?

### Steps to reproduce the issue

1. Add a lot of Custom Armors
2. Eventually some players will hit the rendering limit on their Hardware

### Server version

Current: git-Purpur-1966 (MC: 1.19.4)* (Bug doesn't depend on the server side)

### ItemsAdder Version

ItemsAdder version 3.5.0c

### ProtocolLib Version

ProtocolLib version 5.1.0-SNAPSHOT-654

### LoneLibs Version

LoneLibs version 1.0.25

### Screenshots/Videos (you can drag and drop files or paste links)

https://imgur.com/a/6aZ0uSn < Contains multiple screenshots from different machines

**Comment by LoneDev6** [comment]
It's a known issue and can't be fixed.
This happens if you add too many armors or too big armors.
ItemsAdder should warn you when you reach the known standard GPU max texture dimensions when you run `/iazip`.
