### ISSUE TITLE
CanDestroy support stopped working with 3.5.0c

### ISSUE THREAD

**Issue by Foxagone** [PluginBugs/Issues-ItemsAdder#2837]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

peetfoxx#1578

### What happened?

I'm aware ItemsAdder didn't support CanDestroy flags, but in one world on my server I used CanDestroy: minecraft:note_block on an item so that the player can break all of the ItemsAdder blocks. This might seem as a weird solution but it worked well until the 3.5.0c version.

### Steps to reproduce the issue

1. Use version 3.5.0b
2. Give yourself an item with CanDestroy: minecraft:note_block flag
3. Give yourself any IA block with REAL_NOTE
4. Try breaking the block with the given tool in Adventure mode, it should work perfectly
5. Switch to version 3.5.0c
6. Repeat steps 2-4, it won't work anymore

### Server version

Current: git-Purpur-2001 (MC: 1.20.1)*
Previous: git-Purpur-2000 (MC: 1.20.1)
Download the new version at: https://purpurmc.org/downloads

### ItemsAdder Version

ItemsAdder version 3.5.0c
Customized Minecraft without client mods!
Website: devs.beer
Author: LoneDev

### ProtocolLib Version

ProtocolLib version 5.1.0-SNAPSHOT-654
Provides read/write access to the Minecraft protocol.
Authors: dmulloy2 and comphenix

### LoneLibs Version

LoneLibs version 1.0.25
Collection of libs used by my plugins
Authors: LoneDev and others

**Comment by LoneDev6** [comment]
Please specify the last ItemsAdder version on which the feature worked correctly.

**Comment by LoneDev6** [comment]
Command used to test:
`/minecraft:give @p minecraft:iron_axe{CanDestroy:["minecraft:note_block"]}`
`/minecraft:give @p minecraft:iron_pickaxe{CanDestroy:["minecraft:note_block"]}`

---

The bug is caused by the fact that Spigot function `PlayerInteractEvent#hasBlock()`, for some unknown obscure stupid reason, returns false in ADVENTURE gamemode even if a block was interacted.

Fixed:

https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/d615846a-7eeb-4dbf-b900-785c32b5fa45
