### ISSUE TITLE
resourcepack bypass kick not working

### ISSUE THREAD

**Issue by 100petr** [PluginBugs/Issues-ItemsAdder#2838]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

pitilon

### What happened?

Permission ia.resourcepack.bypasskick doesn't work - it still requires the resourcepack to be loaded

### Steps to reproduce the issue

Start a server with IA and add luckperms
Add the ia.resourcepack.bypasskick permission to luckperms
In IA config, set kick-player-on-decline: true
Try connecting to a server with resourcepack disabled
It will kick you if you reject the resourcepack

### Server version

This server is running Paper version git-Paper-61 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 171ba7c)

### ItemsAdder Version

 ItemsAdder version 3.5.0c (I don't know when the last time it worked for me personally, but it's been at least a year)

### ProtocolLib Version

5.0.0-SNAPSHOT-639

### LoneLibs Version

LoneLibs version 1.0.25

### Screenshots/Videos (you can drag and drop files or paste links)

i looked on github but no one asked about it. But some people asked about it on discord, so I hope it's not a problem on my end
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/29830635/9d0f5e15-8d9f-4415-b670-11c6d88073c4)

**Comment by LoneDev6** [comment]
I'll check today, strange no one reported it.
