### ISSUE TITLE
Off hand Item not working

### ISSUE THREAD

**Issue by Focus098xdd** [PluginBugs/Issues-ItemsAdder#2840]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

@focus098xdd

### What happened?

Off hand Item not working

### Steps to reproduce the issue

-

### Server version

purpur 1.19.4

### ItemsAdder Version

3.5.0c

### ProtocolLib Version

5.0.0

### LoneLibs Version

1.0.25

### FULL server log

-

### Error (optional)

```shell
-
```

### Problematic items yml configuration file (optional)

```shell
-
```

### Other files, you can drag and drop them here to upload. (optional)

-

### Screenshots/Videos (you can drag and drop files or paste links)

-

**Comment by LoneDev6** [comment]
It's impossible to help without any video, log and any itemsadder item configuration for me to reproduce the issue.
