### ISSUE TITLE
Custom Tree will generate above some unintended blocks

### ISSUE THREAD

**Issue by DarrienZ** [PluginBugs/Issues-ItemsAdder#2841]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

darrienz

### What happened?

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/108975040/958e0b54-96fa-4ce2-b424-e25a4b712d24)

### Steps to reproduce the issue

No error

### Server version

[15:45:50 INFO]: Current: git-Purpur-2005 (MC: 1.20.1)*
Previous: git-Purpur-1985 (MC: 1.19.4)
* You are 1 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### ItemsAdder Version

[15:46:08 INFO]: ItemsAdder version 3.5.0c
[15:46:08 INFO]: Customized Minecraft without client mods!
[15:46:08 INFO]: Website: devs.beer
[15:46:08 INFO]: Author: LoneDev

### ProtocolLib Version

[15:46:17 INFO]: ProtocolLib version 5.1.0-SNAPSHOT-654
[15:46:17 INFO]: Provides read/write access to the Minecraft protocol.
[15:46:17 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[15:46:25 INFO]: LoneLibs version 1.0.25
[15:46:25 INFO]: Collection of libs used by my plugins
[15:46:25 INFO]: Authors: LoneDev and others

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: cubimod
trees_populators:
  sakura_tree:
    worlds:
    - world
    chance: 30.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    log: cubimod:sakura_log
    leaves: cubimod:sakura_leaves
    tree_type: TREE
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
  wisteria_tree:
    worlds:
    - world
    chance: 30.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    log: cubimod:wisteria_log
    leaves: cubimod:wisteria_leaves
    tree_type: ACACIA
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
  twilight_tree:
    worlds:
    - world
    chance: 30.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    log: cubimod:twilight_log
    leaves: cubimod:twilight_leaves
    tree_type: REDWOOD
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
  maple_tree:
    worlds:
    - world
    chance: 30.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    log: cubimod:maple_log
    leaves: cubimod:maple_leaves
    tree_type: TALL_BIRCH
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
```

**Comment by LoneDev6** [comment]
Will be checked

**Comment by DarrienZ** [comment]
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/108975040/b91c750a-e50c-49a8-ab6e-654cb096f653)

**Comment by LoneDev6** [comment]
Please provide configuration for these blocks.

**Comment by DarrienZ** [comment]
Provided ^ The sourceb.in

**Comment by DarrienZ** [comment]
https://sourceb.in/qz0s6eoR6J
https://sourceb.in/ONPQr2AkO6

**Comment by LoneDev6** [comment]
Thanks

**Comment by LoneDev6** [comment]
I have fixed this in the upcoming update

**Comment by DarrienZ** [comment]
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/108975040/9bc14d61-29f5-4e09-96ac-c64f7d6d4375)
Already reset the world & updated ia to lastest version.
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/108975040/213523a8-9903-48a4-9b35-30be26b325cc)

**Comment by DarrienZ** [comment]
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/108975040/5eca52ea-7a3a-4af6-8a6a-1369ddbb8a7e)
