### ISSUE TITLE
Infinite mining issue

### ISSUE THREAD

**Issue by yorik100** [PluginBugs/Issues-ItemsAdder#2843]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

yorik100

### What happened?

Infinite mining if swapping items while holding left click

### Steps to reproduce the issue

1. Hold right click to mine ia block
2. Swap item while mining

### Server version

git-Purpur-"625e4ad" (MC: 1.20.1)

### ItemsAdder Version

3.0.5c

### ProtocolLib Version

5.0.0

### LoneLibs Version

1.0.25

### FULL server log

Not needed

### Screenshots/Videos (you can drag and drop files or paste links)

https://cdn.discordapp.com/attachments/1121810868817113128/1124456832606425180/2023-06-30_23-46-06.mp4

**Comment by LoneDev6** [comment]
Thanks I'll make sure to do some tests and possibly fix that

**Comment by LoneDev6** [comment]
The issue will be fixed, thanks.

----
Anyway I find it quite strange for someone to croll while mining a block, it has no sense to do that during gameplay...
It also is extremely hard to trigger on my test server, took me 5 minutes to reproduce the issue spamming hotbar change key.
Bug reports are good for the plugin to grow and become stable, but some are just some edge cases which require lot of time to be fixed and don't really break the gameplay.
