### ISSUE TITLE
Crashing Server

### ISSUE THREAD

**Issue by Wubzi** [PluginBugs/Issues-ItemsAdder#2848]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Wubzi#3887

### What happened?

Every time I add ItemsAdder plugin to the server, it shuts the server down as the server is just about to start up, causing a crash loop. I remove it (keeping the depends in place) and the server works normally without. I have set up all the self-hosting and changed all of these config files. This is the first issue I have had with this plugin.

### Steps to reproduce the issue

1. Place plugin in plugin folder.
2. Start/Restart Server
3. Set Config for Self-host.
4. Check FZ for updated changes (check).
5. Server Crashing repeatedly 

### Server version

This server is running CraftBukkit version 3766-Spigot-81b9def-a345bb9 (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT)
05.07 20:55:42 [Server] Server thread/INFO Checking version, please wait...
05.07 20:55:43 [Server] Thread-41/INFO You are 37 version(s) behind

### ItemsAdder Version

ItemsAdder version 3.5.0c-r2

### ProtocolLib Version

ProtocolLib version 5.0.0
05.07 20:58:20 [Server] Server thread/INFO Provides read/write access to the Minecraft protocol.
05.07 20:58:20 [Server] Server thread/INFO Authors: dmulloy2 and comphenix

### LoneLibs Version

LoneLibs version 1.0.25
05.07 20:59:18 [Server] Server thread/INFO Collection of libs used by my plugins
05.07 20:59:18 [Server] Server thread/INFO Authors: LoneDev and others

**Comment by LoneDev6** [comment]
Please provide a full server log and a crash log.
It's impossible to help you otherwise.

**Comment by LoneDev6** [comment]
> 05.07 20:55:43 [Server] Thread-41/INFO You are 37 version(s) behind

Update
