### ISSUE TITLE
when someone dies they get kicked and cant rejoin

### ISSUE THREAD

**Issue by EfeBrr** [PluginBugs/Issues-ItemsAdder#2849]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

efebrr

### What happened?

When someone dies they get kicked and cant rejoin the server, i tried every plugin by putting them out of the plugins folder, nothing changed until i put itemsadder out of the plugins folder.

### Steps to reproduce the issue

when i look at the console it just says 
"%player% disconnected"

### Server version

This server is running Paper version git-Paper-411 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 3.5.0c

### ProtocolLib Version

ProtocolLib version 5.0.0

### LoneLibs Version

LoneLibs version 1.0.25

### FULL server log

[2023-07-04-4.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11968198/2023-07-04-4.log)

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/138161109/4df368c9-2238-4d92-961a-59278c894a40)

**Comment by SirCraftypants** [comment]
Looks to me like Retrospektif is losing connection every time they try to run the command `/register`?

**Comment by EfeBrr** [comment]
its not working, they get kicked when they try to join not after they run the command /register, they dont see anything just the problem comes to screen just like the one i send as a screenshot

**Comment by EfeBrr** [comment]
i fixed it by downloading the latest protocollib build version
