### ISSUE TITLE
Bossbar stops working when ItemsAdder is installed

### ISSUE THREAD

**Issue by MaxGameDev** [PluginBugs/Issues-ItemsAdder#2853]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

@macsworks

### What happened?

I'm working on a modified version of a plugin which uses a bossbar compass for the NotQuests plugin. The bossbar cannot appear when ItemsAdder is loaded, and only works whenever IA is unloaded via any plugin manager.

### Steps to reproduce the issue

Download the modified NotQuests from: http://macsworks.eu/files/NotQuests-5.15.0.jar

Create a quest via: https://www.notquests.com/docs/tutorials/getting-started with one ReachLocation objective.

Try starting the quest via /nq first without then with IA on the server.

### Server version

This server is running Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)

### ItemsAdder Version

ItemsAdder version 3.5.0c-r2

### ProtocolLib Version

ProtocolLib version 5.1.0-SNAPSHOT-660

### LoneLibs Version

LoneLibs version 1.0.25

### FULL server log

https://pastebin.com/N79Dtd1M

**Comment by LoneDev6** [comment]
> The bossbar cannot appear when ItemsAdder is loaded, and only works whenever IA is unloaded via any plugin manager.

please show a screenshot of the bossbar issue with itemsadder installed and another screenshot without itemsadder installed.

**Comment by ItsMacs** [comment]
Hi there! Macs here from another profile.

Footage without IA: https://www.youtube.com/watch?v=ZpX9DBWavpM
Footage with IA: https://www.youtube.com/watch?v=TndxTgnvDQM

**Comment by LoneDev6** [comment]
I'll do some tests but this seems very strange to me.
Make sure you're running the latest Spigot/Paper version and latest ProtocolLib.

**Comment by LoneDev6** [comment]
> Download the modified NotQuests

Is it working with an unmodified version of NotQuests?

I don't have any code in ItemsAdder which intercepts bossbars and removes them or generally interfere with bossbars.
