### ISSUE TITLE
IA Entities reset after Updating

### ISSUE THREAD

**Issue by konfix** [PluginBugs/Issues-ItemsAdder#2855]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

@konfa

### What happened?

Hello,
I have added some IA Entities to my Citizens NPCs, with playerskin option. I've wanted to make them run emotes on click, and that works fine.

However, after each IA update, they all turn into Zombies and I have to redo them again. Is there a way to prevent this? It's really annoying since I always have to redo all my NPCs after the new update is out.

### Steps to reproduce the issue

1. Make an IA entity with playerskin on older version
2. Update IA to newer version
3. NPCs should turn into Zombies

### Server version

git-Purpur-2013, MC 1.20.1

### ItemsAdder Version

3.5.0c-r2

### ProtocolLib Version

5.0.0

### LoneLibs Version

1.0.25

**Comment by LoneDev6** [comment]
> after each IA update

what do you mean?
I tested and they don't lose the model on plugin restart, /iareload or on plugin update.

**Comment by konfix** [comment]
> > after each IA update
> 
> what do you mean? I tested and they don't lose the model on plugin restart, /iareload or on plugin update.

They lost their models after every plugin jar update for me. Not sure why.

**Comment by LoneDev6** [comment]
They lose models only when you update ItemsAdder jar?
How do you update it? You must update it only when the server is offline, not while running.

**Comment by LoneDev6** [comment]
I find it quite impossible to be caused by each update, probably something changed between ItemsAdder versions or Citizens.
Please check if it happens in the next update too.

**Comment by konfix** [comment]
> I find it quite impossible to be caused by each update, probably something changed between ItemsAdder versions or Citizens. Please check if it happens in the next update too.

I'll let you know.
