### ISSUE TITLE
max_custom_durability: 1, there seems to be a problem, the item will regain its original durability after getting the first item.

### ISSUE THREAD

**Issue by NEIKI19914** [PluginBugs/Issues-ItemsAdder#2858]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

max_custom_durability: 1, there seems to be a problem, the item will regain its original durability after getting the first item.

### Steps to reproduce the issue

The first time I use the ia command to get the item, it works as expected and only has a maximum durability of 1, but when I use the ia command to get the item again, its durability will become the original version, and it will reappear every time I use iareload to reload.

### Server version

[02:42:25 INFO]: Current: git-Purpur-2014 (MC: 1.20.1)*
Previous: git-Purpur-2011 (MC: 1.20.1)
* You are running the latest version

### ItemsAdder Version

ItemsAdder version 3.5.0c-r2
Customized Minecraft without client mods!
Website: devs.beer
Author: LoneDev

### ProtocolLib Version

[02:40:19 INFO]: ProtocolLib version 5.1.0-SNAPSHOT-660
[02:40:19 INFO]: Provides read/write access to the Minecraft protocol.
[02:40:19 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[02:40:49 INFO]: LoneLibs version 1.0.25
[02:40:49 INFO]: Collection of libs used by my plugins
[02:40:49 INFO]: Authors: LoneDev and others

### FULL server log

No error message appears

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: panda
items:
  mystic_pickaxe:
    display_name: 神秘镐
    permission: 神秘镐
    lore:
      - "有10%概率可以采集刷怪笼!"
    durability:
      unbreakable: false
      custom_durability: 1
      max_custom_durability: 1
      usages: 1
    drop:
      glow:
        enabled: true
        color: DARK_RED
      show_name: true
    enchants:
    - SILK_TOUCH:2
    blocked_enchants:
    - ALL
    resource:
      material: DIAMOND_PICKAXE
      generate: false
      model_path: 'pickaxes/cosmic_horror_pickaxe'
categories:
  pandatools:
    enabled: true
    icon: panda:mystic_pickaxe
    name: '工具'
    items:
      - panda:mystic_pickaxe
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/59737752/2eaa2ee4-4137-46b5-8155-23fb2231d144)

**Comment by LoneDev6** [comment]
Strange, will be checked.

**Comment by NEIKI19914** [comment]
> Strange, will be checked.

There's also the possibility of becoming indestructible...
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/59737752/30c843e3-c831-4ef0-a69d-1b8668767b36)

**Comment by LoneDev6** [comment]
> There's also the possibility of becoming indestructible...

Please add more details on how to trigger this indestructible issue.

**Comment by NEIKI19914** [comment]
> > There's also the possibility of becoming indestructible...
> 
> Please add more details on how to trigger this indestructible issue.

    durability:
      max_custom_durability: 1
      usages: 1
Only max_custom_durability: 1 is used, the first item taken from the ia menu is normal, and the durability of the subsequent items is changed back to the original version or no longer loses durability... I can’t confirm whether there is a plugin conflict, but there is no error in the background .I only use custom_durability: 1 now and these problems will not occur.

**Comment by LoneDev6** [comment]
Make a video where you trigger the issue please, thanks

**Comment by NEIKI19914** [comment]
> Make a video where you trigger the issue please, thanks


https://github.com/PluginBugs/Issues-ItemsAdder/assets/59737752/772a7014-cc24-44e1-bd7f-8f979a46cc55

**Comment by NEIKI19914** [comment]
> > Make a video where you trigger the issue please, thanks
> 
>  2023-07-12.17-54-47.mp4

With items with max_custom_durability: 1, using it after restarting the server will not consume durability..

**Comment by LoneDev6** [comment]
Please remove all other plugins and keep only ItemsAdder, ProtocolLib, LoneLibs and test.
This is strange, I don't think it's an ItemsAdder bug but seems another plugin is interfering and we need to find the cause.

Please let me know, thanks

**Comment by NEIKI19914** [comment]
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/59737752/825bf2ab-2e93-4f82-98c7-ffdde4c6ffe4)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/59737752/227d3181-5482-4430-b2fd-07a3fddd491b)
I left only these 3 plugins and deleted the archive to test on a new server and still have this problem.

> Please remove all other plugins and keep only ItemsAdder, ProtocolLib, LoneLibs and test. This is strange, I don't think it's an ItemsAdder bug but seems another plugin is interfering and we need to find the cause.
> 
> Please let me know, thanks
