### ISSUE TITLE
region files from itemsadder not release after world unload or delete

### ISSUE THREAD

**Issue by WindUnwaken** [PluginBugs/Issues-ItemsAdder#2872]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

https://mythiccraft.io/index.php?pages/official-mythicdungeons-download/&version=1.1.1
There is a free version for test.
Mythicdungeon plugin create a new world , and delete it when player don't need it.
Itemsadder should release region file and let [chunkmanager] delete the file.

### Steps to reproduce the issue

1. /md edit, /md join 
2. stay a whil, let itemsadder make a file
3. /md leave

### Server version

paper-550 

### ItemsAdder Version

3.5.0c-r2

### ProtocolLib Version

5.0.0

### LoneLibs Version

1.0.25

### FULL server log

[02:05:26 INFO]: [MythicDungeons] [STDOUT] §d-= Cleaning up FireCryptCreeper_0 processed in 46ms. =-
[02:05:26 WARN]: org.apache.commons.io.IOExceptionList: .\FireCryptCreeper_0
[02:05:26 WARN]:        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:331)
[02:05:26 WARN]:        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1192)
[02:05:26 WARN]:        at MythicDungeons-1.1.1.jar//net.playavalon.mythicdungeons.dungeons.Instance.lambda$dispose$3(Instance.java:442)
[02:05:26 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[02:05:26 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[02:05:26 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[02:05:26 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[02:05:26 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[02:05:26 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[02:05:26 WARN]: Caused by: java.io.IOException: Cannot delete file: .\FireCryptCreeper_0\itemsadder
[02:05:26 WARN]:        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1344)
[02:05:26 WARN]:        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:324)
[02:05:26 WARN]:        ... 8 more
[02:05:26 WARN]: Caused by: java.nio.file.FileSystemException: .\FireCryptCreeper_0\itemsadder\region\r.-1.0.pregion: 程序無法存取檔案，因為檔案正由另一個程序使用。
[02:05:26 WARN]:        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
[02:05:26 WARN]:        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[02:05:26 WARN]:        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[02:05:26 WARN]:        at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
[02:05:26 WARN]:        at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
[02:05:26 WARN]:        at java.base/java.nio.file.Files.deleteIfExists(Files.java:1191)
[02:05:26 WARN]:        at org.apache.commons.io.file.DeletingPathVisitor.visitFile(DeletingPathVisitor.java:161)
[02:05:26 WARN]:        at org.apache.commons.io.file.DeletingPathVisitor.visitFile(DeletingPathVisitor.java:37)
[02:05:26 WARN]:        at java.base/java.nio.file.Files.walkFileTree(Files.java:2811)
[02:05:26 WARN]:        at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
[02:05:26 WARN]:        at org.apache.commons.io.file.PathUtils.visitFileTree(PathUtils.java:971)
[02:05:26 WARN]:        at org.apache.commons.io.file.PathUtils.deleteDirectory(PathUtils.java:434)
[02:05:26 WARN]:        at org.apache.commons.io.file.PathUtils.delete(PathUtils.java:391)
[02:05:26 WARN]:        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1341)
[02:05:26 WARN]:        ... 9 more

**Comment by LoneDev6** [comment]
Reintroduced: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2417#issuecomment-1633026405

**Comment by LoneDev6** [comment]
This will be checked.
How can I trigger the issue using `MythicDungeons` exactly?

Please write down a step by step guide on how to use `MythicDungeons` to trigger the ItemsAdder world issue.
Thanks!

**Comment by WindUnwaken** [comment]
1. /md import test-world
2./md edit test-world

Mythicdungeon will create a temp world
3. Build anything, break or place block, itemsadder now create its own
region file

4. /md save
    /md leave

Mythicdungeon will unload and delete temp world,maybe called test-world_0
test-world_1

5. Error shows in console,yep we can't delete a file which is on use

LoneDev ***@***.***> 於 2023年7月13日 週四 15:45 寫道：

**Comment by LoneDev6** [comment]
I can't reproduce the issue, the file is correctly deleted and no error is thrown.
```
version itemsadder
ItemsAdder version 3.5.0c-r5-beta-1
Customized Minecraft without client mods!
Website: devs.beer
Author: LoneDev

version protocollib
ProtocolLib version 5.1.0-SNAPSHOT-652
Provides read/write access to the Minecraft protocol.
Authors: dmulloy2 and comphenix

version mythicdungeon
MythicDungeons version 1.2.0F
Authors: MarcatoSound and Aestrus

version
Checking version, please wait...
This server is running Paper version git-Paper-57 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 437e8da)
```


https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/f8cb2759-d5b8-4bb3-9955-dee99bbad219

Console:
```
LoneDev issued server command: /md import dungeon1
[Multiverse-Core] World 'dungeon1' was unloaded from Multiverse.
Waiting 60s for chunk system to halt for world 'dungeon1'
Halted chunk system for world 'dungeon1'
[STDOUT] Creating fresh config file for dungeon1
LoneDev issued server command: /md edit dungeon1
No key layers in MapLike[{}]
-------- World Settings For [dungeon1_0] --------
Mob Spawn Range: 5
Item Despawn Rate: 6000


////////////// world loading, I omitted these lines to avoid useless information

[WorldGuard] (dungeon1_0) TNT ignition is PERMITTED.
[WorldGuard] (dungeon1_0) Lighters are PERMITTED.
[WorldGuard] (dungeon1_0) Lava fire is PERMITTED.
[WorldGuard] (dungeon1_0) Fire spread is UNRESTRICTED.
[WorldGuard] Loaded configuration for world 'dungeon1_0'
[STDOUT] §d-= Loading map dungeon1_0 processed in 100ms. =-
LoneDev issued server command: /iablock
LoneDev issued server command: /md save
LoneDev issued server command: /iablock
LoneDev issued server command: /md leave
[STDOUT] §dCleaning up instance 'dungeon1_0'...
[STDOUT] §d-= Saving of dungeon1 processed in 10ms. =-
[Multiverse-Core] Hmm Multiverse does not know about this world but it's loaded in memory.
[Multiverse-Core] To let Multiverse know about it, use:
[Multiverse-Core] /mv import dungeon1_0 NORMAL
Waiting 60s for chunk system to halt for world 'dungeon1_0'
Halted chunk system for world 'dungeon1_0'
[STDOUT] §d-= Unloading world dungeon1_0 processed in 13ms. =-
[STDOUT] §d-= Cleaning up dungeon1_0 processed in 23ms. =-

```

**Comment by yhdev7935** [comment]
i saw same problem.
update **LoneLibs** and ItemsAdder plugin.

**Comment by Ecilpse** [comment]
> I can't reproduce the issue, the file is correctly deleted and no error is thrown.
> 
> ```
> version itemsadder
> ItemsAdder version 3.5.0c-r5-beta-1
> Customized Minecraft without client mods!
> Website: devs.beer
> Author: LoneDev
> 
> version protocollib
> ProtocolLib version 5.1.0-SNAPSHOT-652
> Provides read/write access to the Minecraft protocol.
> Authors: dmulloy2 and comphenix
> 
> version mythicdungeon
> MythicDungeons version 1.2.0F
> Authors: MarcatoSound and Aestrus
> 
> version
> Checking version, please wait...
> This server is running Paper version git-Paper-57 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 437e8da)
> ```
> 
>  Minecraft_.version.hidden.from.driver.-.Multiplayer.3rd-party.Server.2023-09-13.15-27-49.mp4_compressed.mp4 
> Console:
> 
> ```
> LoneDev issued server command: /md import dungeon1
> [Multiverse-Core] World 'dungeon1' was unloaded from Multiverse.
> Waiting 60s for chunk system to halt for world 'dungeon1'
> Halted chunk system for world 'dungeon1'
> [STDOUT] Creating fresh config file for dungeon1
> LoneDev issued server command: /md edit dungeon1
> No key layers in MapLike[{}]
> -------- World Settings For [dungeon1_0] --------
> Mob Spawn Range: 5
> Item Despawn Rate: 6000
> 
> 
> ////////////// world loading, I omitted these lines to avoid useless information
> 
> [WorldGuard] (dungeon1_0) TNT ignition is PERMITTED.
> [WorldGuard] (dungeon1_0) Lighters are PERMITTED.
> [WorldGuard] (dungeon1_0) Lava fire is PERMITTED.
> [WorldGuard] (dungeon1_0) Fire spread is UNRESTRICTED.
> [WorldGuard] Loaded configuration for world 'dungeon1_0'
> [STDOUT] §d-= Loading map dungeon1_0 processed in 100ms. =-
> LoneDev issued server command: /iablock
> LoneDev issued server command: /md save
> LoneDev issued server command: /iablock
> LoneDev issued server command: /md leave
> [STDOUT] §dCleaning up instance 'dungeon1_0'...
> [STDOUT] §d-= Saving of dungeon1 processed in 10ms. =-
> [Multiverse-Core] Hmm Multiverse does not know about this world but it's loaded in memory.
> [Multiverse-Core] To let Multiverse know about it, use:
> [Multiverse-Core] /mv import dungeon1_0 NORMAL
> Waiting 60s for chunk system to halt for world 'dungeon1_0'
> Halted chunk system for world 'dungeon1_0'
> [STDOUT] §d-= Unloading world dungeon1_0 processed in 13ms. =-
> [STDOUT] §d-= Cleaning up dungeon1_0 processed in 23ms. =-
> ```

I've also recreated it several times, can you stay 10min after create instance dungeon map?
I also tested it, and if you leave as soon as you create it, it will be deleted normally.
But players typically play the game for about 10 minutes in a generated map.

**Comment by Ecilpse** [comment]
![2](https://github.com/PluginBugs/Issues-ItemsAdder/assets/25452835/a089ab59-b71e-48ef-b220-06aae6a40dd3)
![1](https://github.com/PluginBugs/Issues-ItemsAdder/assets/25452835/85cb1996-fb90-454f-9b26-cdf0ad3ae6f2)

this issues was continues about almost 2 years.

**Comment by Ecilpse** [comment]
> I can't reproduce the issue, the file is correctly deleted and no error is thrown.
> 
> ```
> version itemsadder
> ItemsAdder version 3.5.0c-r5-beta-1
> Customized Minecraft without client mods!
> Website: devs.beer
> Author: LoneDev
> 
> version protocollib
> ProtocolLib version 5.1.0-SNAPSHOT-652
> Provides read/write access to the Minecraft protocol.
> Authors: dmulloy2 and comphenix
> 
> version mythicdungeon
> MythicDungeons version 1.2.0F
> Authors: MarcatoSound and Aestrus
> 
> version
> Checking version, please wait...
> This server is running Paper version git-Paper-57 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 437e8da)
> ```
> 
>  Minecraft_.version.hidden.from.driver.-.Multiplayer.3rd-party.Server.2023-09-13.15-27-49.mp4_compressed.mp4 
> Console:
> 
> ```
> LoneDev issued server command: /md import dungeon1
> [Multiverse-Core] World 'dungeon1' was unloaded from Multiverse.
> Waiting 60s for chunk system to halt for world 'dungeon1'
> Halted chunk system for world 'dungeon1'
> [STDOUT] Creating fresh config file for dungeon1
> LoneDev issued server command: /md edit dungeon1
> No key layers in MapLike[{}]
> -------- World Settings For [dungeon1_0] --------
> Mob Spawn Range: 5
> Item Despawn Rate: 6000
> 
> 
> ////////////// world loading, I omitted these lines to avoid useless information
> 
> [WorldGuard] (dungeon1_0) TNT ignition is PERMITTED.
> [WorldGuard] (dungeon1_0) Lighters are PERMITTED.
> [WorldGuard] (dungeon1_0) Lava fire is PERMITTED.
> [WorldGuard] (dungeon1_0) Fire spread is UNRESTRICTED.
> [WorldGuard] Loaded configuration for world 'dungeon1_0'
> [STDOUT] §d-= Loading map dungeon1_0 processed in 100ms. =-
> LoneDev issued server command: /iablock
> LoneDev issued server command: /md save
> LoneDev issued server command: /iablock
> LoneDev issued server command: /md leave
> [STDOUT] §dCleaning up instance 'dungeon1_0'...
> [STDOUT] §d-= Saving of dungeon1 processed in 10ms. =-
> [Multiverse-Core] Hmm Multiverse does not know about this world but it's loaded in memory.
> [Multiverse-Core] To let Multiverse know about it, use:
> [Multiverse-Core] /mv import dungeon1_0 NORMAL
> Waiting 60s for chunk system to halt for world 'dungeon1_0'
> Halted chunk system for world 'dungeon1_0'
> [STDOUT] §d-= Unloading world dungeon1_0 processed in 13ms. =-
> [STDOUT] §d-= Cleaning up dungeon1_0 processed in 23ms. =-
> ```

I've also recreated it several times, can you stay 10min after create instance dungeon
 map?
I also tested it, and if you leave as soon as you create it, it will be deleted normally.
But players typically play the game for about 10 minutes in a generated map.

1. leave immediately
![1](https://github.com/PluginBugs/Issues-ItemsAdder/assets/25452835/d0b9e0ed-9b61-4ece-8582-f9bb058c88df)

2. leave dungeon after 10 min
![2](https://github.com/PluginBugs/Issues-ItemsAdder/assets/25452835/429fe59c-8fe8-4e0b-92b8-f69b6c78b46f)
