### ISSUE TITLE
duplicate and skipped resource of model engine

### ISSUE THREAD

**Issue by budur01** [PluginBugs/Issues-ItemsAdder#2875]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

budur09#8750

### What happened?

why dupclite CustomModelData and file compres skiped ?

### Steps to reproduce the issue

ı put blueprints in modelengine and 
/meg reload
and
/mem merge
and 
/iareload and /iazip 
then give error

### Server version

Current: git-Purpur-1975 (MC: 1.19.4)*

### ItemsAdder Version

ItemsAdder version 3.5.0c-r2

### ProtocolLib Version

ProtocolLib version 5.0.0

### LoneLibs Version

 LoneLibs version 1.0.25

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/90689319/31a5a5a8-99ce-4f0f-9450-f3e448e8fd7f)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/90689319/82eb26e8-5ef8-430e-b610-e62c021bd016)

**Comment by LoneDev6** [comment]
You probably have copied the model engine folder into itemsadder contents.
Delete it and read the tutorial: https://itemsadder.devs.beer/compatibility-with-other-plugins/compatible/modelengine

**Comment by budur01** [comment]
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/90689319/8d865c90-1ec1-4944-a3dd-8b05749303c6)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/90689319/e1357f25-0908-488b-9dfe-e172f8ed3566)

dont work

**Comment by budur01** [comment]
it didn't work either way
