### ISSUE TITLE
can't register emoji font with other language.

### ISSUE THREAD

**Issue by Ecilpse** [PluginBugs/Issues-ItemsAdder#2876]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Eclipse

### What happened?

can't register emoji font with other language.

### Steps to reproduce the issue

i made emoji config like this, "meme_emoji_4" worked but "페페" was not worked.

info:
  namespace: "planet"
font_images:
  페페:
    permission: emoji
    show_in_gui: true
    path: "font/emoji/meme_emoji_11.png"
    scale_ratio: 9
    y_position: 8
  meme_emoji_4:
    permission: emoji
    show_in_gui: true
    path: "font/emoji/meme_emoji_4.png"
    scale_ratio: 9
    y_position: 8

### Server version

PurPur-1.20.1

### ItemsAdder Version

ItemsAdder_3.5.0c-r2

### ProtocolLib Version

5.0.0

### LoneLibs Version

1.0.25

### Screenshots/Videos (you can drag and drop files or paste links)

![1](https://github.com/PluginBugs/Issues-ItemsAdder/assets/25452835/1ec3bc30-e5ef-41c3-9ad2-a89730ccf487)

![2](https://github.com/PluginBugs/Issues-ItemsAdder/assets/25452835/529fb546-9af3-454d-a009-2dd063b50497)

**Comment by LoneDev6** [comment]
Do not use special characters in names.
`페페` is bad.

Use only `a-z` `0-9` and `_`, as specified in the wiki everywhere.
https://itemsadder.devs.beer/plugin-usage/adding-content/item-properties/resource
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/d610886b-2a77-4034-9c70-de68b8e2c455)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/0d1a37ef-40cb-4de9-8d43-0d49bf03f6d1)
