### ISSUE TITLE
Could not pass event PlayerResourcePackStatusEvent

### ISSUE THREAD

**Issue by cconfi** [PluginBugs/Issues-ItemsAdder#2881]
### Discord tag (optional)

cconfi

### What happened?

Good morning. I bought the plugin today and wanted to try it on a test server on my pc
The server is in 1.15.2, it does not include any plugin apart from those necessary for the use of Itemsadders and itself of course.

The error occurs after enabling self-host in the plugin config when I join with an account
The error is at the bottom

Thank you very much for taking the time to help me
Cordially,

### Steps to reproduce the issue

I don't know but this is my configuration :  
1 - Go on minecraft spigot server 1.15.2
2 - Put the plugin in "plugins" and start the server
3 - Put "self-host" on true on config.yml and make /iareload and /iazip
4 - Join with a minecraft account and the server stop

### Server version

[Server thread/INFO]: This server is running CraftBukkit version git-Spigot-a99063f-8731c97 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 3.5.0c-r2

### ProtocolLib Version

ProtocolLib version 5.0.0

### LoneLibs Version

LoneLibs version 1.0.25

### FULL server log

[2023-07-16-4.log.gz](https://github.com/PluginBugs/Issues-ItemsAdder/files/12063048/2023-07-16-4.log.gz)

**Comment by LoneDev6** [comment]
Thanks for the report.
In the meantime disable black screen in config.yml of itemsadder, seems it's not working on 1.15.
```yml
  protect-player:
    black-screen: false
```
