### ISSUE TITLE
ItemsAdder is lagging the whole server

### ISSUE THREAD

**Issue by TUCAOEVER** [PluginBugs/Issues-ItemsAdder#2882]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

ItemsAdder is lagging the whole server.

### Steps to reproduce the issue
https://timings.aikar.co/dev/?id=6148f22b72d94d9a84556e811c3aad06#timings
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/43756134/3148642e-34ca-4dc0-8c53-e854f159d4e3)

### Server version

This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Error obtaining version information
Previous version: git-Paper-794 (MC: 1.16.5)

### ItemsAdder Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/43756134/62f376a0-ba04-4107-ac79-d96217b19c8e)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/43756134/2e0f10eb-0056-4b72-8b36-cdd93315689f)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/43756134/498dbf05-14bc-434a-890e-7e8cb5c25a31)

**Comment by LoneDev6** [comment]
Answer some questions:
- how many players did you had online at the time of this report?
- are your players in ADVENTURE gamemode or SURVIVAL?

**Comment by TUCAOEVER** [comment]
> Answer some questions:
> 
> * how many players did you had online at the time of this report?
> * are your players in ADVENTURE gamemode or SURVIVAL?

1. Around 20
2. All players are in SURVIVAL gamemode

**Comment by LoneDev6** [comment]
This is very strange as the code shown in the timings report is triggered only when players are in adventure gamemode.


Basically this is telling you that for some reason the server is loading a chunk each time a player is interacting.
The code highlighted in the ItemsAdder section of the log is triggered when players are in adventure mode to find the target block in front of them.

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/73b6610b-779f-4d42-b2ed-56db00114c0b)

**Comment by TUCAOEVER** [comment]
> This is very strange as the code shown in the timings report is triggered only when players are in adventure gamemode.
> 
> Basically this is telling you that for some reason the server is loading a chunk each time a player is interacting. The code highlighted in the ItemsAdder section of the log is triggered when players are in adventure mode to find the target block in front of them.
> 
> ![image](https://user-images.githubusercontent.com/27242001/253897694-73b6610b-779f-4d42-b2ed-56db00114c0b.png)

Weird, the server only have 3 world available for players, spawn, survival and nether, in mv settings they all been set to SURVIVAL gamemode, so it should be none players in ADVENTURE.

**Comment by LoneDev6** [comment]
is the issue happening very frequently?

**Comment by TUCAOEVER** [comment]
Is there any possible for players 

> is the issue happening very frequently?

Each time server lag, whether it is caused by IA, i noticed that BlockPhysicsEvent triggered very often(almost every time on the top list) and i doubt that thing has some influence to server performance. Despite of that, the issue metioned above happen just once after i update IA from 3.4.2 to 3.5.0(about 1 week), but i am keep checking it.

**Comment by LoneDev6** [comment]
3.5.0? Are you sure? The code shown in the timings report of 3.5.0c-r2 was added only on 3.5.0c-r2, wasn't there in 3.5.0.
Please test with exactly 3.5.0 and generate a new timings report if lag happens.

**Comment by TUCAOEVER** [comment]
> 3.5.0? Are you sure? The code shown in the timings report of 3.5.0c-r2 was added only on 3.5.0c-r2, wasn't there in 3.5.0. Please test with exactly 3.5.0 and generate a new timings report if lag happens.

just miss to type it... u got what i mean

**Comment by LoneDev6** [comment]
Okay perfect.
Anyway please test with exactly `3.5.0` and generate a new timings report if lag happens.
You can download it [from Spigot](https://www.spigotmc.org/resources/%E2%9C%A8itemsadder%E2%AD%90emotes-mobs-items-armors-hud-gui-emojis-blocks-wings-hats-liquids.73355/history).

**Comment by TUCAOEVER** [comment]
Okey.

**Comment by TUCAOEVER** [comment]
> Okay perfect. Anyway please test with exactly `3.5.0` and generate a new timings report if lag happens. You can download it [from Spigot](https://www.spigotmc.org/resources/%E2%9C%A8itemsadder%E2%AD%90emotes-mobs-items-armors-hud-gui-emojis-blocks-wings-hats-liquids.73355/history).

Things works "fine" on v3.5.0, but i found something more strange.
Due to timings report and spark https://spark.lucko.me/qyoBQlSDTR profile
CPU keep run at high percentange usage, which is caused by chunk loading and unloading but as my hardware is totally fine for 50 players that should not happen.
I google for the "IAsyncTaskHandler" and found a thread which locates at https://forums.papermc.io/threads/help-to-find-lag-causes.625/ tells the lag causing by getChunk() method on main thread
while i didn't install some plugin related to chunk so does anyone could find in spark profile, and the only one plugin use getChunk() method is ItemsAdder, though it takes low percentage, i doubt it is realted to the CPU high usage issue. Itemsadder code has obfuscation, so i can't really know what it's going inside the plugin, so probably author should check that on your side.
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/43756134/7a9d0abf-5bcd-4115-9c29-afeb9c4b3e61)

**Comment by TUCAOEVER** [comment]
This issue were not found when i am using ia 3.4(or maybe i didn't notice and after i changing to IA 3.5 this issue becomes prominent which finally causing this issue)

**Comment by LoneDev6** [comment]
I cannot load the https://spark.lucko.me/qyoBQlSDTR profile:

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/0c3cadb8-f1d4-4068-96c7-c52e1f4b44e1)


> Anyway please test with exactly 3.5.0 and generate a new timings report if lag happens.

And provide a timings report while using 3.5.0 if you experience lag.

**Comment by TUCAOEVER** [comment]
> I cannot load the https://spark.lucko.me/qyoBQlSDTR profile:
> 
> ![image](https://user-images.githubusercontent.com/27242001/256194382-0c3cadb8-f1d4-4068-96c7-c52e1f4b44e1.png)
> 
> > Anyway please test with exactly 3.5.0 and generate a new timings report if lag happens.
> 
> And provide a timings report while using 3.5.0 if you experience lag.
> 
> Anyway, it could have been caused by this same issue #2864 which I'm going to fix, so please wait for the next update and let me know if the issue you reported is fixed too.

And both the lag happens in 3.5.0c-r2
