### ISSUE TITLE
Custom Items don't trigger PlayerItemBreakEvent due to implementation of custom damage/durability

### ISSUE THREAD

**Issue by VergilPrime** [PluginBugs/Issues-ItemsAdder#2888]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

VergilPrime

### What happened?

Custom Items don't trigger PlayerItemBreakEvent due to implementation of custom damage/durability

### Steps to reproduce the issue

Create another plugin that listens to PlayerItemBreakEvent, it works with normal items but not custom ones.

### Server version

Paper version git-Paper-80 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: de3f149)

### ItemsAdder Version

ItemsAdder version 3.5.0c-r2

### ProtocolLib Version

ProtocolLib version 5.1.0-SNAPSHOT-653

### LoneLibs Version

ProtocolLib version 5.1.0-SNAPSHOT-653

**Comment by LoneDev6** [comment]
Strange, it's supposed to do that.
I will do some tests and let you know.
