### ISSUE TITLE
Emote lock can be circumvented

### ISSUE THREAD

**Issue by HielkeMaps** [PluginBugs/Issues-ItemsAdder#2890]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

HielkeMaps

### What happened?

Emotes can lock the player's movement, but this lock can be broken by simply double jumping, in which case you'll be free to move around again.

I already messed around with the players AllowFlight property, but this does not seem to make a difference.

### Steps to reproduce the issue

1. Play any emote that locks your position.
2. Double jump
3. Now you're free to move!

### Server version

This server is running Paper version git-Paper-84 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: c016e03)
You are running the latest version
Previous version: git-Paper-83 (MC: 1.20.1)

### ItemsAdder Version

ItemsAdder version 3.5.0c-r2

### ProtocolLib Version

ProtocolLib version 5.1.0-SNAPSHOT-661

### LoneLibs Version

LoneLibs version 1.0.25

### Screenshots/Videos (you can drag and drop files or paste links)

https://github.com/PluginBugs/Issues-ItemsAdder/assets/62292398/94b92204-7a51-426b-b5da-aacbe034bc3a

**Comment by LoneDev6** [comment]
Do you have fly permissions?
Please try with a non-OP user without fly permissions.

**Comment by HielkeMaps** [comment]
Can confirm the problem remains the same without fly perms.

**Comment by LoneDev6** [comment]
This will be checked again, last time I tested I wasn't able to reproduce the issue.
