### ISSUE TITLE
Trap not placed correctly

### ISSUE THREAD

**Issue by Weyl1** [PluginBugs/Issues-ItemsAdder#2892]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

When a player places a trapdoor on a custom block, it always positions itself upwards, on the **east** and **south** side

### Steps to reproduce the issue

1. place a custom block 
2. place a trapdoor on the side east or south of the block

### Server version

purpur-2015   1.20.1

### ItemsAdder Version

3.5.0c r2

### ProtocolLib Version

5.1.0 snapshot 654

### LoneLibs Version

1.0.25

**Comment by LoneDev6** [comment]
Please make a video to showcase the issue.

**Comment by Weyl1** [comment]
https://youtu.be/3IsPjukrtLs
