### ISSUE TITLE
When renaming an item, we can't smelt it

### ISSUE THREAD

**Issue by AxDevv** [PluginBugs/Issues-ItemsAdder#2897]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

When a player renames a custom item (ores for example) and tries to cook it normally it no longer works

But if the player does not rename the item it can be cooked normally in an furnace

### Steps to reproduce the issue

1. setup a item smeltable dans la config
2. give the custom item
3. rename the item with anvil for example or rename command
4. place item on the furnace

### Server version

purpur 2015 1.20.1

### ItemsAdder Version

3.5.0c r2

### ProtocolLib Version

5.1.0 snapshot 661

### LoneLibs Version

1.0.25

### Screenshots/Videos (you can drag and drop files or paste links)

https://www.youtube.com/watch?v=vVWolvoDXzc

**Comment by LoneDev6** [comment]
Strange it should work fine anyway.
I'll do some testing.
