### ISSUE TITLE
Quick question about ia.m.cu.a()

### ISSUE THREAD

**Issue by matipoirierg** [PluginBugs/Issues-ItemsAdder#2901]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Hi just wanted to know what's the function of ia.m.cu.a(), I'm just paranoid about performance, the plugin is not performing badly at all is just that function takes 4% of my tick and I wanted to know if it's something I can disable from config, as I said the plugin doesn't perform badly I just want to reduce the load of my server the maximum that I can.

### Steps to reproduce the issue

no steps

### ItemsAdder Version

3.5.0c-r2

### ProtocolLib Version

661

### LoneLibs Version

1.0.25

**Comment by LoneDev6** [comment]
Please post a proper timings report to show your concerns.
Anyway the method you shared handles the custom hardness logic.
You might have lot of players breaking blocks or spamming clicks around the world.

**Comment by matipoirierg** [comment]
You can close it, as I said I just wanted to reduce the max load that I can for my server but the function itself is not performing bad.
