### ISSUE TITLE
ItemsAdder exceptionally overwrites the results of anvil even if the items don't have any custom anvil recipes

### ISSUE THREAD

**Issue by Akiranya** [PluginBugs/Issues-ItemsAdder#2902]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Nailm#9364

### What happened?

I'm a plugin developer so we may discuss about this issue more technically :)

Put it simply, I have an custom enchant plugin that modifies the result of anvil. But, if there are ItemsAdder items (say, a custom pickaxe) in the anvil, _in some cases (see below)_ my code will not be able to modify the results of anvil. So the anvil result ends up like being overwritten by ItemsAdder.

More specifically, during the test if we were just merging an enchanted book into the tool/weapons it would just work fine, even if the tool/weapons come from ItemsAdder. But if we were merging a random item (say, a stick) into the IA tool/weapons, it wouldn't work then.

Side notes:

- This issue exists even if the ItemsAdder pickaxes don't have any anvil recipes in IA config.
- If all the items in anvil slots are not from ItemsAdder, the anvil will just work fine in _all_ cases.

My proposal fixes:

- If the ItemsAdder items don't have any anvil recipies, then ItemsAdder should not touch the anvil results (and let other plugin handle it).

----

The code logic of my custom enchantment plugin is basically as following:

> When using anvil :
> 
> Check if there are "rechargable" enchantments on the item in the _first_ slot. If so, we consume the item in the _second_ slot and then set the new item in the _result_ slot.
> 
> The item in the _second_ slot are items consumed to charge the "rechargeable" enchantments.

Related source code: https://github.com/nulli0n/ExcellentEnchants-spigot/blob/master/Core/src/main/java/su/nightexpress/excellentenchants/enchantment/listener/EnchantAnvilListener.java

### Steps to reproduce the issue

1. Install ItemsAdder
2. Install ExcellentEnchants (and dependencies: NexEngine)
3. Add an ItemsAdder tool (say, a custom pickaxe)
4. Get the IA pickaxe and put an "rechargable" enchantment on it (using command: /excellentenchants enchant veinminer 1)
5. Initially, the "rechargeable" enchantment on the IA pickaxe don't have any charges
6. So we need to charge the enchantment using anvil (technically, we change the nbt data of the pickaxe)
7. Put the pickaxe in the anvil's first slot
8. Put the materials used to charge the enchantment in the anvil's second slot
9. Ideally, a new item should appear in the anvil's result slot, but it doesn't

### Server version

Current: git-Purpur-2017 (MC: 1.20.1)*

### ItemsAdder Version

ItemsAdder version 3.5.0c-r2

### ProtocolLib Version

ProtocolLib version 5.1.0-SNAPSHOT-661

### LoneLibs Version

LoneLibs version 1.0.25

**Comment by LoneDev6** [comment]
Hello please make a video showing the issue clearly and.
Also test without any other plugin installed, keep only ItemsAdder and its dependencies.

**Comment by Akiranya** [comment]
Hello thanks for the considering this issue!

I will show how I charge the enchantments on an item. If you need more details please let me know.

**Expected behaviors**

The diamond pickaxe and cherry log are both vanilla items.
The cherry log is the material used to charge the enchantments on the item.
The result item correctly appears in the anvil's result slot (as it can be seen, the enchantment charges has become 512)

https://github.com/PluginBugs/Issues-ItemsAdder/assets/14846342/21ffcaff-3258-4c7e-9437-0e67b526b308

**Wrong behaviors**
The diamond pickaxe is a custom pickaxe from ItemsAdder (namespaced id: `rpgitems:dragon_crystal_pickaxe`).
The cherry log is the same as that in the previous video.
The result item doesn't appear in the anvil's result slot.
This only happens when the pickaxe is from ItemsAdder, so clearly ItemsAdder modifies the results of anvil when there are ItemsAdder items in the anvil slots.

https://github.com/PluginBugs/Issues-ItemsAdder/assets/14846342/ddbac322-5d31-4ac6-b2ca-9d364b960ed5

**Side notes**

Also I can confirm that the "dragon_crystal_pickaxe" doesn't have any custom anvil recipes. It's just a plain pickaxe with a custom texture.
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/14846342/df23cc97-e51f-4cc5-a3a6-4a20deeffd25)

**Comment by LoneDev6** [comment]
> The cherry log is the material used to charge the enchantments on the item.

What do you mean?
Is it an ItemsAdder anvil repair recipe? Is it another plugin recipe?

**Comment by Akiranya** [comment]
> > The cherry log is the material used to charge the enchantments on the item.
> 
> What do you mean? Is it an ItemsAdder anvil repair recipe? Is it another plugin recipe?

Hi, LoneDev. Glad you are back!

The cherry log is just a random item from my own plugin recipe, not ItemsAdder. It could be any other item else.
In my ItemsAdder config, the pickaxe doesn't have any anvil repair recipe. The ItemsAdder pickaxe in the example is just a "plain " item - it just has a custom texture and nothing else.

**Comment by LoneDev6** [comment]
Can you please make an example config.yml containing everything for me to reproduce the bug?
Thanks

**Comment by LoneDev6** [comment]
Quoting your first message:
> If the ItemsAdder items don't have any anvil recipies, then ItemsAdder should not touch the anvil results (and let other plugin handle it).

This feature was implemented some updates ago: #2998
Open `config.yml` and set this:
```yml
recipes:
### .....
  anvil:
    enabled: false #<--- set to false
```

**Comment by Akiranya** [comment]
Yea yea that new option should solve this issue in theory. I'll try it when I got time. Thank you for taking care of this issue and letting me know that

**Comment by LoneDev6** [comment]
No problem!
It's always a pleasure to help my customers
