### ISSUE TITLE
After importing the material package according to the file structure 1, there is no error in the console, but the icon cannot be displayed normally, including your default package.

### ISSUE THREAD

**Issue by FZDNSZYT** [PluginBugs/Issues-ItemsAdder#2903]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

fzdnszyt

### What happened?

![2023-07-25](https://github.com/PluginBugs/Issues-ItemsAdder/assets/86947716/d68ee3e4-bcdd-415c-b16d-d061f56fca8e)
There is no error message in the console, and everything is normal. There is no error when using /iazip and /iareload. It is this icon that cannot be displayed normally. This is the case with your default icon pack import and the import of other authors. I tried all known methods. Discord submitted the error. But no one has dealt with it for two days, so I came here to ask questions.

### Steps to reproduce the issue

There is no error message, it is always like this and cannot be displayed normally

### Server version

Previous version: git-Paper-62 (MC: 1.20.1)

### ItemsAdder Version

 ItemsAdder version 3.5.0c-r2

### ProtocolLib Version

ProtocolLib version 5.1.0-SNAPSHOT-661

### LoneLibs Version

LoneLibs version 1.0.25

**Comment by LoneDev6** [comment]
There is something wrong here...
If you literally follow the installation tutorial step by step you won't have any of the shown issues.
https://itemsadder.devs.beer/first-install

Please do it on a clean ItemsAdder folder, do not skip any step and do not install other packs in the meantime.
There is something in the pack which was misconfigured.
I am 100% sure the installation tutorial and the default pack work fine on normal conditions and if you follow the guide correctly step by step.
