### ISSUE TITLE
Can't Enchant Custom Items using enchanted books

### ISSUE THREAD

**Issue by AlecMcCutcheon** [PluginBugs/Issues-ItemsAdder#2904]
### Discord tag (optional)

mixtapelife

### What happened?

Basically as the name suggests, we have some custom items that have enchantment enabled in the config, and when used directly in the enchantment table they seemingly get enchanted just fine, however it doesn't seem to work with enchanted books and if it does from my memory I only recall it ever happening with a specific book, although I can't recall what it was at the moment.

Just wondering if I'm doing something wrong or if there's a fix for this.  I see there are ways of blocking enchantments but my items don't have that section in them so I assume if not present wouldn't block any enchantments.

There are no errors in the console when this happens and I'm not sure where the issue is was just hoping you guys might have some insight I can provide anything that might be helpful if you ask. also as for this: "I am sure this is a bug and it is not caused by a misconfiguration or by another plugin. *"  if we are assuming that your documentation is not missing anything then yes

### Steps to reproduce the issue

Create a custom item that has enchantment enabled and try to enchant it with enchanted books.

### Server version

Paper Vanilla 1.19.4

### ItemsAdder Version

3.5.0c-r2

### ProtocolLib Version

661

### LoneLibs Version

1.0.25

**Comment by AlecMcCutcheon** [comment]
It also seems like you can not combine custom armor together in an anvil. custom tools work fine tho, which is odd

**Comment by AlecMcCutcheon** [comment]
idk what you did but this seems to be fixed in the lastest update. also IDK if you know a fix for this but when playing through geyser on bedrock, some blocks seemingly take forever to break with custom items like for example nether rack and nether quartz, speed is great on other blocks but those blocks had a few others are painfully slow on bedrock.

**Comment by AlecMcCutcheon** [comment]
Also the recipes for custom items are not showing up on bedrock, however I have a custom recipes plugin that unfortunately can't interact with custom items that does show its recipes on bedrock so that makes me think something is missing from your plugin that does not translate to bedrock.

**Comment by LoneDev6** [comment]
Geyser is not officially supported and never will be as it's unstable and unreliable. It's impossible to have a 1:1 experience on both clients.

If you still have issues with anvil/enchants please open a new issue report.
Thanks!
