### ISSUE TITLE
Emojis don't work in chat for players without op

### ISSUE THREAD

**Issue by Saharo4eks** [PluginBugs/Issues-ItemsAdder#2910]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

If the player is not an operator - he cannot use emoji via /e + [tab], the message is simply not sent. An operator does not have any problems with this. At the same time through :[emoji]: emoji is displayed in the chat without any problems. I attach a screenshot of the granted permissions, everything worked on 1.19 with similar settings.

### Steps to reproduce the issue

1. send emoji to chat

### Server version

git-Purpur-2015 (MC: 1.20.1)*

### ItemsAdder Version

3.5.0c-r3

### ProtocolLib Version

5.1.0 snapshot 654

### LoneLibs Version

1.0.25

### FULL server log

-

### Error (optional)

```shell
-
```

### Problematic items yml configuration file (optional)

```shell
-
```

### Other files, you can drag and drop them here to upload. (optional)

-

### Screenshots/Videos (you can drag and drop files or paste links)

https://imgur.com/a/J30rw0m
![Сохраненное изображение 2023-7-27_22-43-34 691](https://github.com/PluginBugs/Issues-ItemsAdder/assets/64433500/886d5da4-e6f0-49a3-bf63-f6585664a322)

**Comment by LoneDev6** [comment]
You might have a plugin interfering with tab complete, please remove all plugins and check with only ItemsAdder installed and its dependencies.
Let me know
