### ISSUE TITLE
item's display_name in font images and placeholderAPI Support

### ISSUE THREAD

**Issue by paiow** [PluginBugs/Issues-ItemsAdder#2916]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

성진#5316

### Describe the solution you'd like

How do I use font images or placeholder inside the display_name of an item?

display_name : "%img_acbd%"
display_name : ":acbd:"

now not working
can update?

### Is your feature request related to a problem?

I want to insert an image into the display name of the item.

### Describe alternatives you've considered

display_name : "%img_acbd%"
display_name : ":acbd:"

**Comment by LoneDev6** [comment]
> display_name : ":acbd:"
