### ISSUE TITLE
Hiding player bones in player emote (size `0-0-0`) causes player model rendering issues

### ISSUE THREAD

**Issue by glutaminus** [PluginBugs/Issues-ItemsAdder#2917]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

when using emotes with custom model, rendering is weird, like in the video, the left leg took the texture from arm instead.

### Steps to reproduce the issue

1. make emotes with custom model
2. /iaemote sand_skill3

### Server version

git-Purpur-1858 (MC: 1.19.2)

### ItemsAdder Version

3.5.0c-r3

### ProtocolLib Version

5.1.0-SNAPSHOT-660

### LoneLibs Version

1.0.25

### Other files, you can drag and drop them here to upload. (optional)

[sandcustom.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/12206893/sandcustom.zip)

### Screenshots/Videos (you can drag and drop files or paste links)

https://github.com/PluginBugs/Issues-ItemsAdder/assets/90768288/236c1fa1-c0b7-4556-8371-31b3ed4ec26b

**Comment by glutaminus** [comment]
#2766

**Comment by LoneDev6** [comment]
Will be checked but this is strange, I couldn't reproduce the issue back when I coded emotes, they worked fine.
Make sure to join without mods if you have any installed.

**Comment by glutaminus** [comment]
Yes, now I have tried without mods (ShoulderSurfing) by using default client and it's still the same issue.

**Comment by LoneDev6** [comment]
Can you update to r4 and run /iazip to regenerate the pack?

**Comment by glutaminus** [comment]
Thanks you, I knew you'd look on this issue again some day don't worry, you always looked into every issue. I know it's important having a break.

So I tried r4 and test again, the issue still happen. I will looking forward for your update. 

your plugin and all these features really mean a lots to me as a Minecraft Java Edition user. make my life a lots easier and better. 👍keep up your good work & support!

**Comment by LoneDev6** [comment]
Thanks!
I found the cause.
You will need to update both ItemsAdder and the Blockbench extension in order to fix the issue.

https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/1a5db810-3cfd-49aa-a463-72a012f8811e
