### ISSUE TITLE
Emotes with custom models doesn't follow the customization

### ISSUE THREAD

**Issue by glutaminus** [PluginBugs/Issues-ItemsAdder#2918]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

```
info:
  namespace: custom
emotes:
  sand_skill3:
    id: sand_skill3
    cancel_conditions:
      sneak: false
      take_damage: false
      deal_damage: false
      in_air: false
    can_player_move: true
```   
 player can still use sneak to cancel, can't use this emote in air, etc. 
 while the normal emotes follow these rules normally

### Steps to reproduce the issue

1. make emotes with custom model
2. make customization for emotes
3. /iaemote sand_skill3  and the emotes doesn't follow these rules.

### Server version

git-Purpur-1858 (MC: 1.19.2)

### ItemsAdder Version

3.5.0c-r3

### ProtocolLib Version

5.1.0-SNAPSHOT-660

### LoneLibs Version

1.0.25

**Comment by LoneDev6** [comment]
Thanks, will be fixed
