### ISSUE TITLE
Custom entities memory leak

### ISSUE THREAD

**Issue by LuluxClient** [PluginBugs/Issues-ItemsAdder#2919]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

For some reasons after checking a heap dump, we saw itemsadder stuff eating everything

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/62576432/9e6ce574-8ef4-4493-869d-37d222be3b1a)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/62576432/3a94211d-e976-4226-b252-be474159b30e)

### Steps to reproduce the issue

1. Have 100 players
2. Have 2 itemsadder entities per island (average 500-700 loaded and 8k islands)
3. wait 10-20h 
4. boom server lags and itemsadder uses all the ram

### Server version

[22:59:17 INFO]: Checking version, please wait...
[22:59:17 INFO]: This server is running Pufferfish version git-Pufferfish-73 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: cadfa71 on HEAD)
You are on the latest version!
Previous version: git-Pufferfish-72 (MC: 1.19.4)

### ItemsAdder Version

[23:00:26 INFO]: ItemsAdder version 3.5.0c-r3
[23:00:26 INFO]: Customized Minecraft without client mods!
[23:00:26 INFO]: Website: devs.beer
[23:00:26 INFO]: Author: LoneDev

### ProtocolLib Version

[23:00:44 INFO]: ProtocolLib version 5.1.0-SNAPSHOT-654
[23:00:44 INFO]: Provides read/write access to the Minecraft protocol.
[23:00:44 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[23:00:34 INFO]: LoneLibs version 1.0.25
[23:00:34 INFO]: Collection of libs used by my plugins
[23:00:34 INFO]: Authors: LoneDev and others

### FULL server log

private

### Error (optional)

```shell
none
```

### Problematic items yml configuration file (optional)

```shell
none
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/62576432/9e6ce574-8ef4-4493-869d-37d222be3b1a)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/62576432/3a94211d-e976-4226-b252-be474159b30e)

**Comment by LuluxClient** [comment]
> /iaentity count

the command gives 0 output

**Comment by LuluxClient** [comment]
Also in peak hours it should be around 200-300 entities loaded I forgot to mention that since we have 6 island servers so it's like 200-300 x 6 but they all are on a diff server and all have a decent amout of ram allocated too

**Comment by LoneDev6** [comment]
Means there is no custom entity loaded in the world.
Was there any memory leak at the time of the command execution? Please check in your dump to be 100% sure.
Thanks

**Comment by LuluxClient** [comment]
> Means there is no custom entity loaded in the world. Was there any memory leak at the time of the command execution? Please check in your dump to be 100% sure. Thanks

currently when i'm doing the command, no the ram is fine: 
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/62576432/700420d4-b3df-4a07-a4a4-966b633154e4)

**Comment by LuluxClient** [comment]
> Execute the command during a suspected memory leak phase.

Sure will do !

**Comment by LuluxClient** [comment]
After some digging your /iaentity count doesn't work with iaentities that are citizens npcs, only works without it

**Comment by LuluxClient** [comment]
> After some digging your /iaentity count doesn't work with iaentities that are citizens npcs, only works without it. I don't know if there is a command where I could count the citizens number

UPDATE: 
You can do /iaentity inspect to see the loaded iaentities but I need to manually count them xd

**Comment by LuluxClient** [comment]
So ram is almost full and server is starting to lag: 
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/62576432/3c8e6ebf-afed-49c0-bdd6-43f1ccc500b6)
And looks like 100+ iaentities are loaded: https://gyazo.com/59277c3f40d84fd6920f933fadfe8dd7

**Comment by LuluxClient** [comment]
I have now whitelisted the server and removed every players and the ram is still super high and the iaentities are getting unloaded (only 6 loaded). 

Spark heapsummary; https://spark.lucko.me/PWkezqih3w
Spark profiler: https://spark.lucko.me/QSRzBFGpiw

**Comment by LoneDev6** [comment]
Then seems to be an issue with CItizens compatibility.
I'm now checking if I can find the cause of the issue.

**Comment by LoneDev6** [comment]
I probably have found the cause of the issue! :D Thanks a lot for the detailed information

**Comment by LoneDev6** [comment]
Sent you a message on Discord in a private thread:
https://discord.com/channels/533407895010803753/1136584470414241834/1136584474281394186
