### ISSUE TITLE
Custom blocks are generated in loaded chunks

### ISSUE THREAD

**Issue by 1821698021** [PluginBugs/Issues-ItemsAdder#2922]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

none

### Describe the solution you'd like

Can I add an option to mineral refresh? Minerals can also be generated in loaded blocks.

### Is your feature request related to a problem?

Can I add an option to mineral refresh? Minerals can also be generated in loaded blocks.

### Describe alternatives you've considered

Can I add an option to mineral refresh? Minerals can also be generated in loaded blocks.

### Additional context

Can I add an option to mineral refresh? Minerals can also be generated in loaded blocks.

**Comment by 1821698021** [comment]
I want to preload the world in advance, but I find that the custom block cannot be generated

**Comment by LoneDev6** [comment]
This was already requested multiple times, sadly it's not possible.
It's a limitation of how the game works and how the Spigot API works.
You cannot in any way generate ores in already generated chunks.

**Comment by 1821698021** [comment]
> 这已经多次要求，可悲的是这是不可能的。这是游戏工作方式和Spigot API工作方式的限制。您不能以任何方式在已经生成的块中生成矿石。





> This was already requested multiple times, sadly it's not possible. It's a limitation of how the game works and how the Spigot API works. You cannot in any way generate ores in already generated chunks.



> This was already requested multiple times, sadly it's not possible. It's a limitation of how the game works and how the Spigot API works. You cannot in any way generate ores in already generated chunks.

Thanks for the reply, can custom blocks dock mmoitems pickaxe power attributes?
