### ISSUE TITLE
make HUDs and actionbar message compatible

### ISSUE THREAD

**Issue by Flandreqwq** [PluginBugs/Issues-ItemsAdder#2927]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

芙兰朵露·斯卡蕾特#4453

### Describe the solution you'd like

When the HUDs are running while occupying the actionbar, both the vanilla and other plugins can send and display actionbar messages normally, and the HUDs will not disappear as a result.

### Is your feature request related to a problem?

When players have other message inputs in their actionbar, HUDs always disappear for a moment, which makes them visually imperfect. 

### Describe alternatives you've considered

I am trying to ensure that other plugins do not occupy the actionbar to ensure the continuous and normal display of HUDs. However, some vanilla operations (such as skipping the night by sleeping) still send messages to the player's actionbar, causing HUDs to flash.
In addition, I also attempted to modify the packet received by the player. I tried to attach the font_images of HUDs to the actionbar message received by the player. But due to my limited coding ability, I was unable to implement it.

**Comment by LoneDev6** [comment]
It's impossible to have both actionbar and custom huds working together.
If you want to use actionbar you have to disable huds in config.yml of ItemsAdder.
