### ISSUE TITLE
Entity textures bugs

### ISSUE THREAD

**Issue by DanRubMaster** [PluginBugs/Issues-ItemsAdder#2928]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

danrub

### What happened?

I'm facing a problem that I absolutely do not know how to solve, it's about creating an entity where the entity spawn works but I can't see its texture and it's all buggy, I tried all kinds of help, I did it exactly according to your wiki tutorial but still it's the same..

### Steps to reproduce the issue

1. Make sure all plugins are updated
2. Convert my entity to "ItemsAdder entity model" format
3. Do the setup according to the itemsadder wiki
4. type `/iareload` in game
5. type `/iaentity summon mobs:ninja_skeleton`

### Server version

This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)
You are running the latest version
Previous version: git-Paper-307 (MC: 1.19.2)

### ItemsAdder Version

ItemsAdder version 3.5.0c-r3

### ProtocolLib Version

ProtocolLib version 5.0.0

### LoneLibs Version

LoneLibs version 1.0.25

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/12232007/latest.4.log)

### Screenshots/Videos (you can drag and drop files or paste links)

This is what it looks like, it should be a ninja xd
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/132781517/70d1c586-e59f-4e86-b25b-b935fdbe051d)

**Comment by LoneDev6** [comment]
Make sure you are following the resourcepack hosting tutorial, this kind of issues happens when the pack is not regenerated or if you didn't re-upload the pack if you are not using self host.

**Comment by DanRubMaster** [comment]
Well, im not sure how that works, but i guess im using self host, or atleast i have it checked as true if we mean the same thing
https://ctrlv.cz/Myr8

**Comment by LoneDev6** [comment]
Run /iazip to regenerate the pack.
Also check if you correctly decompressed the folders of the ninja pack.
