### ISSUE TITLE
Make custom shaders can be use in HUDs

### ISSUE THREAD

**Issue by Flandreqwq** [PluginBugs/Issues-ItemsAdder#2931]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

芙兰朵露·斯卡蕾特#4453

### Describe the solution you'd like

Just add a HUDs configuration option that allows the HUD to be rendered to a specific color for the custom shader to work.

### Is your feature request related to a problem?

Because HUDs are essentially actionbar messages, there are text shadows without modifying the shaders.
(The thirst bar example on wiki doesn't have text shadows, but text shadows appear when I create a HUD myself.)

### Describe alternatives you've considered

No alternative comes to mind for the time being.

### Additional context

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/127276917/72199eb7-dbea-4d33-9621-a3bcd079389f)

**Comment by LoneDev6** [comment]
Which shader are you using?

**Comment by Flandreqwq** [comment]
> Which shader are you using?

A shader that can remove the text shadows by using a specific color. At the same time, it is compatible with ItemsAdder's text effects. (This shader is not my original. I'll show it below)

**Comment by Flandreqwq** [comment]
`#version 150
#moj_import <fog.glsl>

in vec3 Position;
in vec4 Color;
in vec2 UV0;
in ivec2 UV2;

uniform sampler2D Sampler0,Sampler2;
uniform mat4 ModelViewMat;
uniform mat4 ProjMat;
uniform mat3 IViewRotMat;
uniform float GameTime;
uniform int FogShape;
uniform vec2 ScreenSize;

out float vertexDistance;
flat out vec4 vertexColor;
out vec2 texCoord0;

void main(){
    vec4 vertex = vec4(Position, 1.0);
    vertexDistance = fog_distance(ModelViewMat, IViewRotMat * Position, FogShape);
    texCoord0 = UV0;
    if (Color.xyz == vec3(255., 255., 254.) / 255.) {
        gl_Position = ProjMat * ModelViewMat * vertex;
        vertexColor = ((.6 + .6 * cos(6. * (gl_Position.x + GameTime * 1000.) + vec4(0, 23, 21, 1))) + vec4(0., 0., 0., 1.)) * texelFetch(Sampler2, UV2 / 16, 0);
    } else if(Color.xyz == vec3(255., 255., 253.) / 255.) {
        gl_Position = ProjMat * ModelViewMat * vertex;
        vertexColor = Color * texelFetch(Sampler2, UV2 / 16, 0);
        gl_Position.y = gl_Position.y + sin(GameTime * 12000. + (gl_Position.x * 6)) / 150.;
    } else if (Color.xyz == vec3(255., 255., 252.) / 255.) {
        gl_Position = ProjMat * ModelViewMat * vertex;
        vertexColor = ((.6 + .6 * cos(6. * (gl_Position.x + GameTime * 1000.) + vec4(0, 23, 21, 1))) + vec4(0., 0., 0., 1.)) * texelFetch(Sampler2, UV2 / 16, 0);
        gl_Position.y = gl_Position.y + sin(GameTime*12000. + (gl_Position.x*6)) / 150.;
    } else if (Color.xyz == vec3(255., 255., 251.) / 255.) {
        vertexColor = Color * texelFetch(Sampler2, UV2 / 16, 0);
        float vertexId = mod(gl_VertexID, 4.0);
        if (vertex.z <= 0.) {
            if (vertexId == 3. || vertexId == 0.) vertex.y += cos(GameTime * 12000. / 4) * 0.1;
            vertex.y += max(cos(GameTime*12000. / 4) * 0.1, 0.);
        } else {
            if (vertexId == 3. || vertexId == 0.) vertex.y -= cos(GameTime * 12000. / 4) * 3;
            vertex.y -= max(cos(GameTime*12000. / 4) * 4, 0.);
        }
        gl_Position = ProjMat * ModelViewMat * vertex;
    } else if (Color.xyz == vec3(255., 254., 254.) / 255.) {
        float vertexId = mod(gl_VertexID, 4.0);
        if (vertex.z <= 0.) {
            if (vertexId == 3. || vertexId == 0.) vertex.y += cos(GameTime * 12000. / 4) * 0.1;
            vertex.y += max(cos(GameTime*12000. / 4) * 0.1, 0.);
        } else {
            if (vertexId == 3. || vertexId == 0.) vertex.y -= cos(GameTime * 12000. / 4) * 3;
            vertex.y -= max(cos(GameTime*12000. / 4) * 4, 0.);
        }
        vertexColor = ((.6 + .6 * cos(6. * (gl_Position.x + GameTime * 1000.) + vec4(0, 23, 21, 1))) + vec4(0., 0., 0., 1.)) * texelFetch(Sampler2, UV2 / 16, 0);
        gl_Position = ProjMat * ModelViewMat * vertex;
    } else if (Color.xyz == vec3(255., 254., 253.) / 255.) {
        vertexColor = Color*texelFetch(Sampler2, UV2 / 16, 0);
        vertex.y+= 1;
        vertex.x+= 1;
        gl_Position = ProjMat * ModelViewMat * vertex;
    } else {
        vertexColor = Color*texelFetch(Sampler2, UV2 / 16, 0);
        gl_Position = ProjMat * ModelViewMat * vertex;
    }
    if (Position.z == 0.0
      && gl_Position.x >= 0.94
      && gl_Position.y >= -0.35
      && vertexColor.g == 84.0/255.0
      && vertexColor.g == 84.0/255.0
      && vertexColor.r == 252.0/255.0
      && gl_VertexID <= 7
    ) {
        gl_Position = ProjMat * ModelViewMat * vec4(ScreenSize + 100.0, 0.0, ScreenSize + 100.0);
    }
}`

**Comment by LoneDev6** [comment]
I'll check if it's easy to add this feature without making the plugin heavy

**Comment by LoneDev6** [comment]
Done!
Sorry for the wait, I hope this is still useful for your project.
Thanks a lot for your patience! I hope you will consider leaving a 5 stars review, it would help me so much.

`config.yml`:
```yml
huds:
  enabled: true
  force_color:
    enabled: true
    color: '#f542d4'
```



![Image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/2795d0df-ee78-4a51-89c8-b382cb3831b1)



![Image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/5c175e88-42a7-449d-99e6-dd197055db36)

**Comment by LoneDev6** [comment]
Color picker: https://g.co/kgs/Pvq3jj
