### ISSUE TITLE
/iagive -> Give items to offline players when they join

### ISSUE THREAD

**Issue by bobhenl** [PluginBugs/Issues-ItemsAdder#2934]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

renzotom

### Describe the solution you'd like

Hello, I suggest adding the items to the queue when the user is offline, and when he joins, then give items to him. Similarly almost all the crates plugins do this, or some vote plugins, as well. 

Cause now when the user is offline & you use /iagive to him, the items are lost.

### Is your feature request related to a problem?

Yeah, when you use /iagive & user is not online, the items are lost.

### Describe alternatives you've considered

Adding items to the queue.

**Comment by LoneDev6** [comment]
Most vote plugins and reward plugins have an option to execute the reward command as soon as the player is online.
This is not really something that ItemsAdder should implement, an example is TEBEX market, I used it in the past and commands can be automatically executed on player join, or the player can use a special command to redeem the prizes (which executes the /iagive command and all your prize commands).
