### ISSUE TITLE
Some player can't see text.

### ISSUE THREAD

**Issue by Ecilpse** [PluginBugs/Issues-ItemsAdder#2935]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

EclipseMC#oing1215

### What happened?

some player's text become invisible after download resourcepack. what is problems?
only a few player has this problems.

### Steps to reproduce the issue

i can't reproduce them. only a few player suffered this.
they has no mods, vanilla launcher, no other resource pack.

### Server version

purpur-2014 (1.20.1)

### ItemsAdder Version

3.5.0 R3

### ProtocolLib Version

5.0.0

### LoneLibs Version

1.0.25

### Other files, you can drag and drop them here to upload. (optional)

![1](https://github.com/PluginBugs/Issues-ItemsAdder/assets/25452835/9926f229-757c-4091-a03b-1ad86691804d)

**Comment by LoneDev6** [comment]
This seems to be a client issue caused by bad GPU drivers, some mod incompatibility or a broken resourcepack.
Read the CLIENT log to understand the cause of the issue: https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown
