### ISSUE TITLE
Add support for vanilla Item display system

### ISSUE THREAD

**Issue by adelando** [PluginBugs/Issues-ItemsAdder#2939]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Adelando#1988

### Describe the solution you'd like

Adding support for vanilla item/block/text displays could open up a wide variety of options for displaying static icons/models/images etc in a more easier way. These are all non-interactive, non-entities which display whatever NBT you give it.

Heres alittle more info.
https://minecraft.fandom.com/wiki/Display

### Is your feature request related to a problem?

Currently have to create an image, give it a unicode character, and then use said code in either character form, shortcode form " :img_name: " or placeholderapi

### Describe alternatives you've considered

na

**Comment by LoneDev6** [comment]
I don't understand what you want me to implement, display entities can already be spawned via commands and other plugins, and you can put custom items into the display by using their custommodeldata (obtainable via [`/iacustommodeldata`](https://itemsadder.devs.beer/plugin-usage/commands)).

**Comment by adelando** [comment]
Implementing a better way to register custom display models within itemsadder would make managing them alot easier. They could be loaded on plugin load or deleted from within itemsadder and easier to create and place the displays.

They have the potential to reduce the amount of armor stands that get loaded within chunks and could be a better alternative to tripwire items.

example of a simple command: /iadisplay remove|place|edit|list [namespace:item] {here|coords}

**Comment by adelando** [comment]
There is a plugin I use for custom crops and they have an option to use another item managing plugin to use vanilla displays to reduce lag. It could have potential to be a really useful tool.
