### ISSUE TITLE
Disable some plugins reloading by itemsadder plugin in config

### ISSUE THREAD

**Issue by WataLaker37821** [PluginBugs/Issues-ItemsAdder#2940]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

DOGE#1690

### Describe the solution you'd like

I want to be able to disable some big plugins (mythic mobs for example) from reloading when i reload itemsadder plugin, cos on my server's startup mythicmobs loads, but then itemsadder idk why reloads it when starts itself

### Is your feature request related to a problem?

I dont like when i see: cant keep up, is your server overloaded, at least on my server's startup, cos i have 2 x Ryzen, 16Gb RAM, 60Gb NVME (as for me, not so bad configuration, if compare to cheaper servers), so thats why i want to control what plugins being reloaded when i reload itemsadder

### Describe alternatives you've considered

I dont know any other alternatives, but set some options for all plugins that are being reloaded on IA reload, so i could easily disable any of them in some cases

**Comment by WataLaker37821** [comment]
Could this be implemented? cos i get purpur's server overload message on every startup, cos i have mythicmobs, citizens, customcrafting and much more plugins, so itemsadder reloading them all after their first load, thats kinda worrying

**Comment by LoneDev6** [comment]
It's impossible to avoid reloading Citizens NPCs when ItemsAdder is reloaded as there might be ItemsAdder custom entities spawned in Citizens.

About mythicmobs same thing, i cannot avoid reloading it because it might be hooked into itemsadder items and i have to refresh it.

Anyway I don't see why it's a problem, you shouldn't really reload while players are playing, you should work on the server while in maintenance mode.
