### ISSUE TITLE
How to make entity immortal?

### ISSUE THREAD

**Issue by lammmyyy** [PluginBugs/Issues-ItemsAdder#2943]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

I made my entity, but it is killed with one blow. How to make her immortal?

### Is your feature request related to a problem?

no

### Describe alternatives you've considered

no

**Comment by LoneDev6** [comment]
Set `max_health` to 999999, in the next update I will add the `invulnerable: true` property.
