### ISSUE TITLE
Itemsadder World Edit updated to 1.20

### ISSUE THREAD

**Issue by zunkerman** [PluginBugs/Issues-ItemsAdder#2944]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Zunker

### Describe the solution you'd like

Attempting to use IAWE on 1.19.4 seems to cause several bugs, including copied blocks turning into vanilla blocks when pasted. As I'm using a 1.19.4 server I'm unable to use the reccomended world edit version I believe updating the plugin to 1.20 and a newer WE version could fix these issues, on top of just generally updating the plugin for newer version use.

### Is your feature request related to a problem?

Currently copying a block and then pasting it causes it to revert to the vanilla version of the base block. This breaks schematic use with anything IA related.

### Describe alternatives you've considered

NA

**Comment by LoneDev6** [comment]
Will be checked again, but last time I tested the plugin was working fine

**Comment by LoneDev6** [comment]
I cannot reproduce the issue.


https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/480fd112-afd6-43ca-b5f6-cbf6b6507b16


```
ItemsAdder version 3.5.0c-r5-beta-1
Customized Minecraft without client mods!
Website: devs.beer
Author: LoneDev

version protocollib
ProtocolLib version 5.1.0-SNAPSHOT-652
Provides read/write access to the Minecraft protocol.
Authors: dmulloy2 and comphenix

version worldedit
WorldEdit version 7.2.15+6463-5ca4dff
Website: https://enginehub.org/worldedit
Author: EngineHub

version
Checking version, please wait...
This server is running Paper version git-Paper-57 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 437e8da)
```
