### ISSUE TITLE
REAL_WIRE performance problem 1.17.1

### ISSUE THREAD

**Issue by Kosta-TV** [PluginBugs/Issues-ItemsAdder#2947]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

kostatv

### What happened?

Sometimes, when using your plugin, we see a sharp increase in MSPT from the normal 35 for us to about 200. We are sure that it is IA that is involved here. We investigated and saw it in the spark:

- https://cdn.discordapp.com/attachments/1014832986727923782/1138125279076831375/2023-08-07_152758.png
- https://cdn.discordapp.com/attachments/1014832986727923782/1138125279349444718/2023-08-07_152928.png
- https://cdn.discordapp.com/attachments/1014832986727923782/1138125279626276964/2023-08-07_152940.png
- https://cdn.discordapp.com/attachments/1014832986727923782/1138125279924080640/2023-08-07_153034.png

### Steps to reproduce the issue

This happens randomly.

### Server version

This server is running Pufferfish version git-Pufferfish-22 (МС: 1.17.1) (Implementing API version 1.17.1-R01-SNAPSHOT)

### ItemsAdder Version

ItemsAdder 3.5.0c-r3

### ProtocolLib Version

ProtocolLib 5.0.0

### LoneLibs Version

LoneLibs 1.0.25

**Comment by LoneDev6** [comment]
Thanks a ton for the reports screenshots although it's impossible for me to identify the issue precisely with only screenshots, I need the links to read these timings reports.
Thanks, I wait for news.

**Comment by LoneDev6** [comment]
@Felson999 
Yes update the plugin
