### ISSUE TITLE
Customheads Compatibility

### ISSUE THREAD

**Issue by RashDonkey1** [PluginBugs/Issues-ItemsAdder#2950]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

RashDonkey1

### What happened?

After reading the compatibility list for ItemsAdder in which the CustomHeads plugin did not appear on that list.

ItemsAdder is changing the texture on most heads around my world (a few hundreds) leaving them black and green, purple and grey, white and black, plain black or just flashing between black and its own texture.

Is there any fix to this issue?

### Steps to reproduce the issue

Most heads will lose texture. (some don't)

### Server version

This server is running Paper version git-Paper-115 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 98c567f)
You are running the latest version
Previous version: git-Paper-111 (MC: 1.20.1)

### ItemsAdder Version

3.5.0c-r3

### ProtocolLib Version

5.0.0

### LoneLibs Version

1.0.25

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/12298300/latest.log)

### Screenshots/Videos (you can drag and drop files or paste links)

![2023-08-05_08 41 52](https://github.com/PluginBugs/Issues-ItemsAdder/assets/141801235/71142f0c-0bfd-457a-863a-74bd1b470230)

**Comment by CryptoXB** [comment]
Read this FAQ page, I believe this will be able to help.

https://itemsadder.devs.beer/faq/placed-heads-texture-glitched
