### ISSUE TITLE
can't fishing rod cast with sitting

### ISSUE THREAD

**Issue by Ecilpse** [PluginBugs/Issues-ItemsAdder#2956]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

EclipseMC#oing1215

### What happened?

player can't cast fishing rod below 1.1 sit height.
and can't retrieve fishing rod with sitting down.

### Steps to reproduce the issue

make chair with armorstand type
set sit_height: 1.1

cast fishing rod with sitting down

### Server version

purpur-2025 mc 1.20.1

### ItemsAdder Version

ItemsAdder_3.5.0c-r3

### ProtocolLib Version

5.0.0

### LoneLibs Version

 1.0.25

**Comment by LoneDev6** [comment]
I doubt it's possible to fix that because of how game hitboxes work
