### ISSUE TITLE
ItemsAdder sometimes fails to load properly

### ISSUE THREAD

**Issue by aaa8881** [PluginBugs/Issues-ItemsAdder#2960]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

signition

### What happened?

ItemsAdder sometimes fail to load properly. 
It is enabled, but /doing any ia related command (such as /ia) gives message output

"itemsadder is still loading please try again or /iareload" or something like that ( forgot to screenshot )

not sure if it'll ever be related but
```
[06:02:04] [Craft Scheduler Thread - 17 - ItemsAdder/INFO]: [ItemsAdder] [License] Spigot product licensed to: aaa8881 (34519)
[06:02:04] [Server thread/INFO]: [ItemsAdder] [Pack] DONE extracting internal contents from .jar
[06:02:04] [Server thread/WARN]: [ItemsAdder] Detected legacy ItemsAdder pack (pre 3.3.0).
[06:02:04] [Server thread/WARN]: [ItemsAdder] Trying to load files, unexpected results might occur.
[06:02:04] [Server thread/WARN]: [ItemsAdder] It's adviced to follow the new guidelines: https://a.devs.beer/ia-new-guidelines-330
```

and 
```
[06:02:06] [Craft Scheduler Thread - 15 - ItemsAdder/WARN]: [ItemsAdder] Plugin ItemsAdder v3.5.0c-r2 generated an exception while executing task 5958
java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /app/live/minecraft/survival2/plugins/ModelEngine/resource pack/assets/modelengine/textures/entity/roman_soldier.png
	at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:87) ~[?:?]
	at java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:103) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:132) ~[?:?]
```

those two are only exceptions...well first one is not even exception, I can find from ia. 

it sometimes happen, and I can't reproduce in any dev enviornment. 

would it be related to that 10 servers are using ia from same license in one bungeecord network, and they all restart at same time? 

unsure what information to provide

### Steps to reproduce the issue

not sure

### Server version

1.20

### ItemsAdder Version

3.5.0c-r2

### ProtocolLib Version

#660

### LoneLibs Version

1.0.25

**Comment by aaa8881** [comment]
this is technically causing dupe glitch in my server as I'm relying some of items to be created from ia, and use those items as ingredient of custom crafting system. I've no idea why this is happening, but this happens pretty often, almost once every two days.

It does not happen in one specific server , but technically happens randomly in one of servers that are rebooting at the same time. subject server differs time by time, which indicates some sort of racing condition.

problem is there is no console error or whatsoever to specify what failed during loadup. I sus it may do something with id verification when two or more servers are sending request at the same time. If that's the case, I can try to change time for different server loadup, but I first need confirmation that this may be the cause of this problem.

**Comment by aaa8881** [comment]
I changed automatic reboot time so that servers are rebooting slightly differently with short interval of time. will see if it resolves issue.

**Comment by LoneDev6** [comment]
There is something wrong with FTP files permissions or something similar.
`java.nio.file.NoSuchFileException: /app/live/minecraft/survival2/plugins/ModelEngine/resource pack/assets/modelengine/textures/entity/roman_soldier.png` shouldn't really trigger since the file exists. There is something wrong in your files permissions.

**Comment by aaa8881** [comment]
I know log is about file perm, still didn't bother to touch, but issue never rehappened after I changed automatic restart time. Previously all servers started at exactly same time using cron, but I gave 1min interval between servers now. I highly suspect it has something to do with ia authentication server issue.

**Comment by aaa8881** [comment]
considering issue happened almost every day in some server, I would say it's resolved from the fact it never happend more than a week.

**Comment by aaa8881** [comment]
@LoneDev6 is it not planned because you think this is incorrect issue, or just too minor thing to fix? It still happens, and seems like happening even if significant delay ( 30s in difference )
