### ISSUE TITLE
1.20.1 Kick Issue

### ISSUE THREAD

**Issue by magef1x** [PluginBugs/Issues-ItemsAdder#2961]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Hi, players aren't kicked on cancel resource pack loading and black scren isn't working.

### Steps to reproduce the issue

1. Create a 1.20.1 test server
2. Download itemsadder with depends
3. Enable `kick-player-on-decline`, `kick-player-on-fail`, `black-screen`
4. Decline the loading of resource pack
5. Check will you kicked from server and did black screen worked

### Server version

This server is running Paper version git-Paper-126 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: a73ed95)
You are running the latest version

### ItemsAdder Version

3.5.0c-r4

### ProtocolLib Version

5.1.1-SNAPSHOT-665

### LoneLibs Version

1.0.25

### FULL server log

The logs are too long so i make a paste link [https://paste.helpch.at/dogiguqeru.makefile](https://paste.helpch.at/dogiguqeru.makefile)

### Problematic items yml configuration file (optional)

```shell
metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
ignore-server-compatibility-check: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: true
      server-ip: 5.180.104.57
      pack-port: 8163
    external-host:
      enabled: false
      url: ''
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: true
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  1_19_3_atlas_support: true
  fix_force_unicode_font_images: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      protection_1: true
      protection_2: true
    compress-png-files: true
    compress-json-files: true
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    extract_internal_utility_assets: true
    contents-folders-priority:
    - vanilla
    - _iainternal
    merge_other_plugins_resourcepacks_folders:
    - ModelEngine/resource pack
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  force-sync-loading: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire_enhancements:
    enable: true
    unlit_on_place: true
    allow_any_item: true
    drop_when_broken: false
  disable-REAL: false
  disable-REAL_NOTE: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_WIRE: true
  disable-FIRE: false
  convert-vanilla-blocks:
    enabled: false
    only-new-chunks: true
  convert-legacy-ia-region-files: true
  remove-unused-palettes-on-region-save: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
  hide-custom-durability-lore: false
  handle-wear-held-actions-on-unexpected-inventory-changes: true
liquids:
  enabled: true
huds:
  enabled: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
compatibility:
  worldguard:
    show_legacy_furniture_flags: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    add-hover-suggestion: true
    tab-autocompletion_1_19_1_plus: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  iaimage-book:
    max-line-length: 18
    placeholder-font: minecraft:default
effects:
  hide-scoreboard-numbers: false
  text-effects:
    enabled: true
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    emotes: true
    interval-rendering-packets-ticks: 1
    optimized-packets: true
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  show-no-permission-popup-in-recipebook: true
  show-no-permission-chat-message: false
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: true
        ingredients: true
      on-item-click:
        any: true
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  benchmark: false
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-recipes-unknown-item: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save-load:
      enabled: false
      min-ms: 0
    log-mined-unknown-blocks: true
    log-convert-vanilla-blocks: false
    log-fix-bugged-blocks: false
    log-unusual-block-break: false
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
```

**Comment by LuxCubeX** [comment]
same problem here

**Comment by LoneDev6** [comment]
Can you provide a video? I cannot reproduce the issue.

**Comment by magef1x** [comment]
I'll provide a info but it'll took a few days. It's an easy issue and it shouldn't be happened. I'm using itemsadder from 2.5 versions and i got this problem first time

**Comment by JohnKillswitch** [comment]
same problem.
plugin version: 3.5.0c-r5b
i use pterodactyl
minecraft version: 1.20.1

**Comment by LoneDev6** [comment]
> Can you provide a video? I cannot reproduce the issue.

**Comment by JohnKillswitch** [comment]
i cant make a video. its happens randomly with random players

**Comment by JohnKillswitch** [comment]
i check this problem in server without pterodactyl and it works well. seems like problem with pterto compability

**Comment by JohnKillswitch** [comment]
and some more info:
this happens only on first join. if player rejoin to server then resourcepack downloading successfully

**Comment by LoneDev6** [comment]
It's strange, I don't see how Pterodactyl can be an issue

**Comment by LuxCubeX** [comment]
> It's strange, I don't see how Pterodactyl can be an issue

Mine is not on pterodactyl and it happens ONLY if I add some specific texture packs I can send them to you so you can try if you want to. Discord: milk_and_cereal

**Comment by LoneDev6** [comment]
> it happens ONLY if I add some specific texture packs

In this case you have to check if it's a kick caused by the client itself, so it's not the server kicking but the client leaving the server because the pack can't be applied as it has some issues.

To read the CLIENT log and find out the issue cause you have to read this guide which is a life saver, I use it too when I have similar issues:
https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown

**Comment by LuxCubeX** [comment]
> Yes, send them. Both CLIENT and SERVER logs.
As I said it's weird, it started a few months ago some players have been reporting that they couldn't join (I was able to join) so I removed the specific texture packs that caused it.

I tried to add these recently again and it would let my friend join and not me so we removed them again.

and now that I imported them again to send you the logs it just works for me so I don't know.
Have in mind that I did not change the client or version of client I always use the same.

**Comment by JohnKillswitch** [comment]
ok, i can add more info now:
EVERY player cant download RP on first join. they need to rejoin to server and then RP downloading properly

**Comment by JohnKillswitch** [comment]
maybe something blocking RP packet on first join?

**Comment by LuxCubeX** [comment]
> maybe something blocking RP packet on first join?

This is another issue, not the same issue as the one that kicks the player but I think I had that before as well.

**Comment by LoneDev6** [comment]
> EVERY player cant download RP on first join. they need to rejoin to server and then RP downloading properly

Might be some of these causes:
https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown

- Make sure you don't have any inventory (GUI) or book opening on join.
This can cause the resourcepack prompt to disappear and the player won't be able to click on it.
In order to fix this you can use the free plugin [ResourcePackBroadcast](https://www.spigotmc.org/resources/resourcepackbroadcast.88318/). This allows you to run commands as soon as the resourcepack is accepted (and various other features).
- You can also try increasing the delay-ticks in config.yml of ItemsAdder to 10 or greater.
