### ISSUE TITLE
Replace the model of arrow or create a bow that doesn't shoot arrows

### ISSUE THREAD

**Issue by microvencn** [PluginBugs/Issues-ItemsAdder#2965]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Dear author of ItemsAdder,
I wanna use the plugin to create a gun whose material is BOW, so that I can play the animation when holding the gun to shoot. I am aware that ItemsAdder has the capability to execute MythicMobs abilities through the use of MMOItems, and I can play particle effect as the bullet. 
What bothers me is that I don't want the player to shoot an arrow when they release the bow, but just execute the skill. I attempted to disable the BOW_SHOT event in the configuration, but this action resulted in MMOItems being unable to handle said event.
How can I fix this issue? Thanks for your assistance.

### Is your feature request related to a problem?

 I don't want the player to shoot an arrow when they release the bow, but just execute the skill.

### Describe alternatives you've considered

 I attempted to disable the BOW_SHOT event in the configuration, but this action resulted in MMOItems being unable to handle said event.

**Comment by LoneDev6** [comment]
The only way to disable arrow shooting is to cancel the shoot event, this will cause MMOItems to skip the event as it's cancelled.
There is no way to fix the issue you're facing I'm afraid.
Maybe MMOItems dev can confirm that or provide a solution.

Thanks for the patience.
