### ISSUE TITLE
Issue with resource-packs merge

### ISSUE THREAD

**Issue by Miluek** [PluginBugs/Issues-ItemsAdder#2966]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

146991497886171136

### What happened?

Hi, I have a problem with the resource-pack generation, during the /iazip command, an error occurs, which concerns the merging of the resource-pack of the QualityArmoryVehicles plugin.

I followed the instructions on the wiki, I created the "qualityarmory" folder in the ItemsAdder/contents directory, I uploaded the "assets" folder from the resource-pack of the QualityArmory plugin to the folder, I am also sending screenshots...

<img width="1201" alt="Snimek_obrazovky_2023-08-18_v_0 09 48" src="https://github.com/PluginBugs/Issues-ItemsAdder/assets/79774929/bfecd1cf-93e1-49ea-a4bc-bf5f200535e7">
<img width="1201" alt="Snimek_obrazovky_2023-08-18_v_0 09 54" src="https://github.com/PluginBugs/Issues-ItemsAdder/assets/79774929/6a07564c-925f-4b1a-a71e-6be46cbcfc1d">
<img width="1201" alt="Snimek_obrazovky_2023-08-18_v_0 10 09" src="https://github.com/PluginBugs/Issues-ItemsAdder/assets/79774929/525fb642-431a-4c6d-aac4-aef79566f20a">

Everything works correctly in the game, the textures of the ItemsAdder plugin work correctly, the textures of the QualityArmoryVehicles plugin also work correctly, only when I generate the resource-pack with the /iazip command, I get the error that I have attached below...

How can I fix the error, or what am I doing wrong to cause this error? I'm afraid that it may have some consequences later if the error is not addressed...

Thanks for help! 🙂 

### Steps to reproduce the issue

I am asking for advice…

### Server version

Current: git-Purpur-2035 (MC: 1.20.1)*
* You are running the latest version

### ItemsAdder Version

ItemsAdder version 3.5.0c-r4

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-665

### LoneLibs Version

LoneLibs version 1.0.25

### FULL server log

https://mclo.gs/4up8T4J

### Error (optional)

```shell
[22:36:58] [Craft Scheduler Thread - 9 - ItemsAdder/ERROR]: [ItemsAdder] PNG 'qualityarmory:all/whitenorange' not found for model. File: /home/********/plugins/ItemsAdder/contents/qualityarmory/resourcepack/assets/qualityarmory/models/gun/dis9.json
[22:36:58] [Craft Scheduler Thread - 9 - ItemsAdder/ERROR]: [ItemsAdder] PNG 'qualityarmory:all/whitenorange' not found for model. File: /home/********/plugins/ItemsAdder/contents/qualityarmory/resourcepack/assets/qualityarmory/models/gun/dis9.json
[22:36:58] [Craft Scheduler Thread - 9 - ItemsAdder/ERROR]: [ItemsAdder] PNG 'qualityarmory:all/grenades' not found for model. File: /home/********/plugins/ItemsAdder/contents/qualityarmory/resourcepack/assets/qualityarmory/models/gun/medkit.json
```

**Comment by LoneDev6** [comment]
Are you sure the files exist and the path is correct?
Can you try deleting them and reuploading them using another FTP program?
I think it can be a FTP files permissions/ownership issue.
Try to change permissions and ownership.
