### ISSUE TITLE
1.19+ Secure chat conflicts with ItemsAdder Emojis/Colored chat

### ISSUE THREAD

**Issue by AGuyNamedJens** [PluginBugs/Issues-ItemsAdder#2967]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

aguynamedjensbot

### What happened?

1.19.4 with plugins that MODIFY the chat, including the whole "chat secure" garbage, breaks the custom placeholders ItemsAdder adds in the default pack, which means Emojis and the colored chat do not work.

I have also tried REMOVING EssentialsXChat which did not solve the issue, InteractiveChat functions as usual, when DISABLING the force unsigned packets, same goes for every other chat modifying plugin out there disabling packets, seems to break ItemsAdder's custom emojis and colored chats..

This does NOT however, happen when the placeholders are sent by the SERVER. Same with DiscordSRV chats coming into the server, works fine! Only happends on PLAYER sent messages

### Steps to reproduce the issue

1. Make sure you're on 1.19 or higher
2. Install ItemsAdder's default pack
3. Install InteractiveChat (or basically any other chat format plugin that disables the secured chat logic Minecraft introduced in 1.19 AND enable the feature in the configuration; 
` | ForceUnsignedChatPackets: true`
` | HideServerUnsignedStatus: true`
4. Use any chat plugin (such as EssentialsX + EssentialsXChat or whatever) ??optional??
5. Send an emoji or text format, such as `<r rainbows!>` for rainbow text.
6. Notice how it doesn't work?

### Server version

Checking version, please wait...
Current: git-Purpur-1982 (MC: 1.19.4)

### ItemsAdder Version

ItemsAdder version 3.5.0c-rc4

### ProtocolLib Version

ProtocolLib version 5.0.0

### LoneLibs Version

LoneLibs version 1.0.25

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/34610614/bb782659-6b91-4f94-b454-7704d63951f5)

First one, normal chat.
Second one, using Essentials's `/me` command, which basically is the same as any server-sided message (which doesn't force unsigned packets)

**Comment by AGuyNamedJens** [comment]
https://github.com/LOOHP/InteractiveChat/issues/163#issuecomment-1685023248

**Comment by LoneDev6** [comment]
Hello,
Your report will be looked into as soon as possible, I'm just back from the summer break and I finally have access to my PC.
Rest assured that your questions won't be ignored.
Thanks a lot for the patience!

I will do some tests since it might be possible that I'm not intercepting this particular packet, but it's strange as the chat was tested extensively.

**Comment by AGuyNamedJens** [comment]
> Hello, Your report will be looked into as soon as possible, I'm just back from the summer break and I finally have access to my PC. Rest assured that your questions won't be ignored. Thanks a lot for the patience!
> 
> I will do some tests since it might be possible that I'm not intercepting this particular packet, but it's strange as the chat was tested extensively.

Yeah I've noticed it's not working if the chat gets intercepted by, in this case the chat plugin InteractiveChat to bypass clients showing the chat is insecure (because it's a useless function and could keep players away from the game due to security settings accounts can have).
