### ISSUE TITLE
Block/place sound not correct with Solid Custom Blocks (REAL_NOTE)

### ISSUE THREAD

**Issue by LeLuniXx** [PluginBugs/Issues-ItemsAdder#2971]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

master_leprimex

### What happened?

Hello, I recently tried to adjust the sounds for my custom blocks. (Everything according to Wiki) Unfortunately, I kept encountering a problem with the break sound that I couldn't solve and in Discord I was told to report it. My custom block consisted of the REAL_NOTE type. Unfortunately, I haven't tried other types, so I can only say that it occurs there. Attached is a video where you can hear two different sounds being played at the end of the break animation.

### Steps to reproduce the issue

1. Make an Config with Real_Note Type
2. Make a Sound (Break/Place) config type
3. You can see. Dont work (for me)

### Server version

This server is running Paper version git-Paper-131 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 307d05b)
You are 14 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-98 (MC: 1.20.1)

### ItemsAdder Version

ItemsAdder Version: 3.5.0c-r4

### ProtocolLib Version

5.1.0-SNAPSHOT-652

### LoneLibs Version

1.0.25

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: blocks
items:
  quicksand:
    enabled: true
    display_name: Treibsand
    permission: block.quicksand
    resource:
      material: PAPER
      generate: true
      textures:
        - block/decorative/quicksand_down.png
        - block/decorative/quicksand_east.png
        - block/decorative/quicksand_north.png
        - block/decorative/quicksand_south.png
        - block/decorative/quicksand_up.png
        - block/decorative/quicksand_west.png
      solid: false
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
        break_tools_whitelist:
        - HAND
        - PICKAXE
        - AXE
        - HOE
        - SHEARS
        sound: #customizable sounds of the block
          break:
            name: BLOCK_SAND_BREAK
            volume: 5
            pitch: 0.9
          place:
            name: BLOCK_SAND_PLACE
            volume: 1
            pitch: 0.9
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://github.com/PluginBugs/Issues-ItemsAdder/assets/39627389/ef3970df-bf3b-42d9-99f4-5f05f29d267b

**Comment by LoneDev6** [comment]
Thanks, it's a known limitation and will be addressed in the future: https://github.com/PluginBugs/Issues-ItemsAdder/issues/1260
The request is very old but this is a non game breaking issue so it was not a priority.
I hope to find the time to implement that by the end of the year.
