### ISSUE TITLE
pack.mcmeta After compression is fixed at 12

### ISSUE THREAD

**Issue by bear78425** [PluginBugs/Issues-ItemsAdder#2974]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

ItemsAdder\output\generated

pack.mcmeta
{
  "pack": {
    "pack_format": 15, <  After compression, it is fixed at 12, and there will be no change
    "description": "XXXXXXXXXXXX"
  }
}

### Steps to reproduce the issue

1.contents\_iainternal\resourcepack\pack.mcmeta
{
  "pack": {
    "pack_format": 15, <  After compression, it is fixed at 12, and there will be no change
    "description": "XXXXXXXXXXXX"
  }
}

### Server version

This server is running Paper version git-Paper-156 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 3716832)
You are running the latest version
Previous version: git-Paper-155 (MC: 1.20.1)

### ItemsAdder Version

3.5.0c-r4

### ProtocolLib Version

5.1.0

### LoneLibs Version

1.0.25

### FULL server log

No

### Error (optional)

```shell
No
```

### Problematic items yml configuration file (optional)

```shell
{
  "pack": {
    "pack_format": 15,
    "description": "§6XXXXXXXXXXX"
  }
}
```

### Other files, you can drag and drop them here to upload. (optional)

No

### Screenshots/Videos (you can drag and drop files or paste links)

No

**Comment by Slarof** [comment]
Also faced with this 

I would also like to get support for "supported_formats" in pack.mcmeta :)

**Comment by HoneyBearc** [comment]
ItemsAdder_3.6.2-beta-r4 
Version 1.20.2 The same problem occurs again and cannot be changed to
{
  "pack": {
    "pack_format": 18,
    "description": "§6XXXXXXXXXXX"
  }
}

**Comment by LoneDev6** [comment]
@HoneyBearc please open a new issue report and explain exactly what happens and what you'd expect instead.
Thanks.
https://github.com/PluginBugs/Issues-ItemsAdder/issues/new/choose
