### ISSUE TITLE
Add PocketMobs and EpicBackPack to Itemsadder so they can be used as result in recipes or within item trades or menus.

### ISSUE THREAD

**Issue by ofunny** [PluginBugs/Issues-ItemsAdder#2977]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

ofunny

### Describe the solution you'd like

It would be awesome if Itemsadder would add compatibility with PocketMobs and EpicBackPacks so that one could reference PocketMobs and EpicBackPacks items within Itemsadders recipes or in menus.

That way it would be possible to create a lot of cool stuff, for example a vending machine for PocketMob balls.
Right now I would have to add all back packs and balls as redundant items in Itemsadder and even copy textures, name, lore description to achieve a similar effect what adds just a lot of complexity and also is more or less a dirty solution. 

### Is your feature request related to a problem?

no

### Describe alternatives you've considered

none

**Comment by LoneDev6** [comment]
Related to this issue: #2507
