### ISSUE TITLE
Custom item repair in anvil other plugin development compatibility issue

### ISSUE THREAD

**Issue by Flandreqwq** [PluginBugs/Issues-ItemsAdder#2978]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

芙兰朵露·斯卡蕾特#4453

### What happened?

When both items on the anvil are durable custom item, the anvil event is handled entirely by ItemsAdder and cannot be handled by other plugins. This may be due to the ItemsAdder event priority. At the same time, I guess the issue(https://github.com/PluginBugs/Issues-ItemsAdder/issues/2969) is also related to this problem. I wish there was an option to control whether custom items could be repaired using anvils or grindstone.
By the way, the grindstone has the same problem, but if I set my plugin event priority to HIGH can solved it.

### Steps to reproduce the issue

1.create a custom item that has durability.
2.using two of the items on the anvil to repair.
3.the problem arises, other plugins cannot modify the results of the anvil.

### Server version

[02:57:42 INFO]: Current: git-Purpur-2004 (MC: 1.20.1)*
Previous: git-Purpur-1632 (MC: 1.18.2)

### ItemsAdder Version

[01:49:24 INFO]: ItemsAdder version 3.5.0c-r2
[01:49:24 INFO]: Customized Minecraft without client mods!
[01:49:24 INFO]: Website: devs.beer
[01:49:24 INFO]: Author: LoneDev

### ProtocolLib Version

[01:49:41 INFO]: ProtocolLib version 5.1.0-SNAPSHOT-654
[01:49:41 INFO]: Provides read/write access to the Minecraft protocol.
[01:49:41 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[01:49:56 INFO]: LoneLibs version 1.0.25
[01:49:56 INFO]: Collection of libs used by my plugins
[01:49:56 INFO]: Authors: LoneDev and others

**Comment by Akiranya** [comment]
Related issue: #2902

**Comment by LoneDev6** [comment]
Hello,
Your report will be looked into as soon as possible, I'm just back from the summer break and I finally have access to my PC.
Rest assured that your questions won't be ignored.
Thanks a lot for the patience!

**Comment by LoneDev6** [comment]
It depends on your code.
ItemsAdder listens to the `InventoryClickEvent` and `PrepareAnvilEvent` with `MONITOR` priority and ignores cancelled events.
```java
	@EventHandler(priority = EventPriority.MONITOR, ignoreCancelled = true)
	public void onClickAnvilResultSlot(InventoryClickEvent e)

////....

	@EventHandler(ignoreCancelled = true, priority = EventPriority.MONITOR)
	private void onPrepareAnvil(PrepareAnvilEvent e)
```

So your plugin can use any priority but `MONITOR` and you could cancel the events and handle them on your own.

ItemsAdder must set the result to AIR if there is no recipe for the custom item otherwise vanilla repair recipe will trigger for the custom items and I don't want that.
This is why you see your anvil result deleted.
There is no other clean way to add compatibility because of how the Spigot API handles anvil events.

NOTE: in case you might think so, no, ItemsAdder using MONITOR is not the issue.

**Comment by Flandreqwq** [comment]
I understand ItemsAdder must set the result to AIR if there is no recipe for the custom item. But that's not my problem. My problem is that when the leftItemStack and rightItemStack of the Anvil Inventory are the same ItemsAdder item (e.g. both are a custom pickaxe), ItemsAdder will set the result to the item after the combined durability of the two. This prevents my plugin from participating in modifying the result.

**Comment by LoneDev6** [comment]
Just cancel the PrepareAnvilEvent and InventoryClickEvent events, should be enough to avoid ItemsAdder from handling the recipe

**Comment by Flandreqwq** [comment]
But PrepareAnvilEvent doesn't have a Cancellable interface. It seems impossible to cancel it.

**Comment by LoneDev6** [comment]
Can you try if the issue still occurs in the latest version of ItemsAdder?

**Comment by Flandreqwq** [comment]
In ItemsAdder 3.6.0, this issue doesn't occur. Well down!
