### ISSUE TITLE
Item interactions

### ISSUE THREAD

**Issue by jmalloy125** [PluginBugs/Issues-ItemsAdder#2982]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Laskod

### Describe the solution you'd like

Allow interaction between items, such as dropping a repair kit on an item in your inventory for it to restore durability if it matches the repair group assigned when creating both items.
Iron chest plate: repair group IRON
Copper repair kit: repair group COPPER
If the copper repair kit is dropped on the iron chest plate, nothing would happen, but if a repair kit with the IRON repair group was created, dropping it on the chest plate would restore xx durability (possibly chosen in action/event)

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

Lack of item interaction is currently the only reason I use MMOitems with Itemsadder

**Comment by LoneDev6** [comment]
This seems to be something out of the scope of ItemsAdder since it's not a very vanilla behaviour.
This can be implemented using the [ItemsAdder API](https://itemsadder.devs.beer/developers/java-api).
