### ISSUE TITLE
ItemsAdder does not respect Cooking Recipe Machine Type

### ISSUE THREAD

**Issue by democracycraft** [PluginBugs/Issues-ItemsAdder#2984]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

technofied

### What happened?

I tried to make a faster sand smelting recipe for a specific group of players, that is unique to blast furnaces. Here is the recipe I used:
    mason_1: #1 sand -> 1 glass (blast furnace; 100 ticks, 0.1 exp)
      permission: miner.recipes
      ingredient:
        item: sand
      machines:
      - BLAST_FURNACE
      exp: 0.1
      cook_time: 100
      result:
        item: glass
        amount: 1

Unfortunately, it applies to both Smokers and Furnaces. As a result, it overrides the default Furnace smelting recipe and doesn't allow regular players without permission to use the Minecraft furnace smelting recipe.

To fix this, have "machines:" respect which machines are specified. 

### Steps to reproduce the issue

See above recipe.
Try and smelt sand in a regular furnace with that recipe loaded and without the permission node.
You are unable to smelt the sand, no permission.

### Server version

[15:27:20 INFO]: This server is running Paper version git-Paper-169 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: b4e3b3d)
You are running the latest version

### ItemsAdder Version

[15:27:45 INFO]: ItemsAdder version 3.5.0c-r4
[15:27:45 INFO]: Customized Minecraft without client mods!
[15:27:45 INFO]: Website: devs.beer
[15:27:45 INFO]: Author: LoneDev

### ProtocolLib Version

[15:28:00 INFO]: ProtocolLib version 5.1.1-SNAPSHOT-665
[15:28:00 INFO]: Provides read/write access to the Minecraft protocol.
[15:28:00 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[15:28:00 INFO]: ProtocolLib version 5.1.1-SNAPSHOT-665
[15:28:00 INFO]: Provides read/write access to the Minecraft protocol.
[15:28:00 INFO]: Authors: dmulloy2 and comphenix

### FULL server log

I can provide this if needed, but otherwise I choose to withhold it at this time if that's ok. 

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: jobs
recipes:
  cooking:
    mason_1: #1 sand -> 1 glass (blast furnace; 100 ticks, 0.1 exp)
      permission: miner.recipes
      ingredient:
        item: sand
      machines:
      - BLAST_FURNACE
      exp: 0.1
      cook_time: 100
      result:
        item: glass
        amount: 1
```

**Comment by LoneDev6** [comment]
Did you try to restart the server?
You might have created a recipe before which included all machines, then removed the recipe and the game might still have it loaded.
A server restart will fix this if that's the case.

Let me know!

**Comment by democracycraft** [comment]
> Did you try to restart the server? You might have created a recipe before which included all machines, then removed the recipe and the game might still have it loaded. A server restart will fix this if that's the case.
> 
> Let me know!

Hiya! We tried restarting but unfortunately the problem was not resolved. :(

**Comment by LoneDev6** [comment]
Fixed in the upcoming update, thanks for the report

**Comment by democracycraft** [comment]
Hugely appreciated!
