### ISSUE TITLE
Urgent: ItemsAdder has a memory leak

### ISSUE THREAD

**Issue by qlow** [PluginBugs/Issues-ItemsAdder#2986]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

janrabek

### What happened?

Hey,
we have issues with a couple of servers of us dying because of memory leaks. We have a heapdump which shows that it has to do with ItemsAdder, unfortunately.

Here you can see the map of ItemsAdder containing all the Player objects:
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/20094418/3a273c75-61ce-44a8-9720-f43c3ae14e4c)

In general there are even 85 players in the RAM:
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/20094418/f6e3034e-a2c6-436f-a7c0-bc1fd2f13c8a)

But one can see in the CraftServer, that there are actually only 8 players online on the server:
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/20094418/a446ac52-51d2-4311-bd24-c868321fabfd)

The memory leak is probably caused by the HashMap using the Player as the key and somehow not deleting it always. In the decompiler it seems that the map "n" is written to but never removed from.

It's mainly caused by lots of instances of ChunkTaskScheduler which are there because of all the old players with old worlds loaded (around 40 worlds even though they shouldn't be all loaded):
<img width="874" alt="Bildschirmfoto 2023-09-04 um 12 24 25" src="https://github.com/PluginBugs/Issues-ItemsAdder/assets/20094418/4bf10123-d03b-4da9-b9b4-0a04e882437f">

Here you can see that these take 5GB of the total 8GB ram of the server:
<img width="829" alt="Bildschirmfoto 2023-09-04 um 12 25 02" src="https://github.com/PluginBugs/Issues-ItemsAdder/assets/20094418/afc72951-0128-44fb-9aa5-820fce2b18f5">

Looking forward to your help!

Best regards
Jan

### Steps to reproduce the issue

1. Load and unload lots of worlds
2. See the memory leak coming

### Server version

This server is running Paper version git-Paper-"140fb42" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 140fb42)
Error obtaining version information

### ItemsAdder Version

<img width="390" alt="Bildschirmfoto 2023-09-04 um 12 28 35" src="https://github.com/PluginBugs/Issues-ItemsAdder/assets/20094418/ea935d6b-f6c9-406a-a44c-0c64f9a9e8a2">

### ProtocolLib Version

<img width="507" alt="Bildschirmfoto 2023-09-04 um 12 29 11" src="https://github.com/PluginBugs/Issues-ItemsAdder/assets/20094418/eb208568-5cf3-42a5-9253-b0d587eab460">

### LoneLibs Version

<img width="322" alt="Bildschirmfoto 2023-09-04 um 12 29 19" src="https://github.com/PluginBugs/Issues-ItemsAdder/assets/20094418/bdf28582-b823-42c5-9d8d-46d0809151ce">

**Comment by LoneDev6** [comment]
> In the decompiler it seems that the map "n" is written to but never removed from.

Can you highlight where you found this information?
It would be very helpful for me, thanks!
I plan to post an hotfix today if you succeed into providing all the information

**Comment by qlow** [comment]
I see no removal of the entry in the n map

<img width="764" alt="Bildschirmfoto 2023-09-04 um 14 20 30" src="https://github.com/PluginBugs/Issues-ItemsAdder/assets/20094418/0b529edd-f40e-4550-a972-185276a245f3">
<img width="923" alt="Bildschirmfoto 2023-09-04 um 14 20 43" src="https://github.com/PluginBugs/Issues-ItemsAdder/assets/20094418/8acffae7-231b-4677-9422-1c09022ab7aa">
<img width="792" alt="Bildschirmfoto 2023-09-04 um 14 20 49" src="https://github.com/PluginBugs/Issues-ItemsAdder/assets/20094418/64ab7ceb-3518-4bf6-80e5-f55aadc3eada">

**Comment by qlow** [comment]
Any update on this? @LoneDev6 

Spigot doesn't have any update since August 8th

**Comment by LoneDev6** [comment]
The update will be posted today! Thanks for the patience.
I'm just back from the summer break and I finally have access to my PC.
Rest assured that your questions won't be ignored.
Thanks a lot for the patience!
