### ISSUE TITLE
Can not Launch newest Itemsadder

### ISSUE THREAD

**Issue by Domas2** [PluginBugs/Issues-ItemsAdder#2993]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Domas 2#0646

### What happened?

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/144318807/563161f6-025c-4397-9ef0-c698dd7bf1ec)
I am just trying to items adder from 3.4.1-r6 to the latest version. But everytime it gives me these same errors I even try whiping the config and still keeps saying something missing.

### Steps to reproduce the issue

Download the plugin and run it on the server. 

### Server version

1.19.3-1.20.1

### ItemsAdder Version

3.5.0c-r4b.jar

### ProtocolLib Version

latest version

### LoneLibs Version

latest version

### FULL server log

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/144318807/44717376-37a6-4710-9fc3-021caca0dc8b)

**Comment by LoneDev6** [comment]
update lonelibs.
