### ISSUE TITLE
Text Effects Incomptible with Shaders

### ISSUE THREAD

**Issue by DuneSciFye** [PluginBugs/Issues-ItemsAdder#2996]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Text Effects don't work when you have Shaders enabled

### Steps to reproduce the issue

1. Enable text effects
2. Enable shaders
3. Use Text Effects

### ItemsAdder Version

ItemsAdder version 3.5.0c-r2

### ProtocolLib Version

ProtocolLib version 5.1.0

### LoneLibs Version

LoneLibs version 1.0.25

**Comment by LoneDev6** [comment]
I have no control over mods as they modify how the client renders the game and servers have no control over this.
You should contact the authors of the shader or of the shaders loader.
Anyway last time I tested text effects worked just fine even with Optifine shaders and Iris shaders enabled, so it might be a particular shader that is breaking the text effects, so try to install a different shader.
