### ISSUE TITLE
Add possibility to use GIF

### ISSUE THREAD

**Issue by Distolfix** [PluginBugs/Issues-ItemsAdder#2997]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Ho visto in un server inglese che, appunto si possono aggiungere tramite la texture delle simpatiche gif (?) o almeno credo siano gif. Volevo chiederti se fosse possibile aggiungere la possibilità di implementare delle gif anche piccole per fare degli effetti abbastanza carini, proprio come il video che ora ti mostro

### Is your feature request related to a problem?

no

### Describe alternatives you've considered

.

### Additional context

https://github.com/PluginBugs/Issues-ItemsAdder/assets/73421268/bc4f2da1-c435-4d2f-a25a-5477ef3b4ce1

Guarda, noti i granchi nella tab, noti che si muovono?

**Comment by paulreob** [comment]
They are not gifs, they are an effect from a resource called TextEffects, they basically use coreshaders that are applied using a specific #hexcolor

https://mcmodels.net/model/very-cool-text-effects/

**Comment by LoneDev6** [comment]
These are not gif, they use text effects which are already implemented in the plugin.
You should be able to trigger them by using `<w hello>`, in your case with an emoji: `<w :smile:>`
