### ISSUE TITLE
Disabling ItemsAdder recipe system

### ISSUE THREAD

**Issue by imh3ro** [PluginBugs/Issues-ItemsAdder#2998]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

.herodev

### Describe the solution you'd like

Hi. I am making an rpg plugin. I have my own item and recipe system but items has the ability to use other items as base from other plugins. I want to be able to disable ItemsAdder recipe system in order to use my own recipe system.

### Is your feature request related to a problem?

When i use ItemsAdder items in my recipes, it overrides the recipe result in the PlayerPreCraft event if the crafting matrix contains an IA item. I am not sure what would be the best solution but i need a solution to this.

My tests and more info about this can be found in this forum post:
https://forum.devs.beer/d/1806-cannot-use-itemsadder-items-for-recipes-in-my-own-plugin

(It has been almost a week come on😭)

### Describe alternatives you've considered

I tried to override the override but sadly the override happens at the HIGHEST event priority.

**Comment by LoneDev6** [comment]
You want to completely disable custom ItemsAdder recipes of ItemsAdder?
I can add an option for that.

**Comment by imh3ro** [comment]
Yes. Or maybe for specific items.

**Comment by LoneDev6** [comment]
Not possible for specific items, I can disable it completely only.
Let me know if you need this feature for real so I start implementing it.
Thanks

**Comment by imh3ro** [comment]
Yes i do need it. I want to handle recipes in my own plugin.

**Comment by LoneDev6** [comment]
Added in config.yml in the upcoming update:
```yml
  crafting:
    enabled: true
  cooking:
    enabled: true
  anvil:
    enabled: true
  smithing:
    enabled: true
```
