### ISSUE TITLE
More Block Sounds

### ISSUE THREAD

**Issue by kristophergeou** [PluginBugs/Issues-ItemsAdder#2999]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

I have noticed that we can only edit the place, and break sounds of a block. https://itemsadder.devs.beer/plugin-usage/adding-content/block#sounds. But what about the `HIT, STEP, FALL` sounds? can these also be added as options? It will make the customization of a block not only look but also sound 100% like a vanilla one.

Pic Reference:
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/114158743/02eeead4-e2a5-4c0a-bc67-ded0ae42adf2)

### Is your feature request related to a problem?

-

### Describe alternatives you've considered

-

**Comment by paulreob** [comment]
There is already an addon for this, but I would ask LoneDev to fix the existing bugs that the BlockSounds addon has, or just add support directly in the ItemsAdder plugin

https://github.com/Boy0000/BlockSounds-ItemsAdder

**Comment by kristophergeou** [comment]
direct support in the ia is way better in my opinion :/

**Comment by paulreob** [comment]
+1 up, I've been asking for years xd

**Comment by LoneDev6** [comment]
Note: this will be available only on 1.17+ because Minecraft 1.16 doesn't have any event for entities steps so I cannot detect steps without using lot of server processing.

**Comment by LoneDev6** [comment]
Info about the new feature:
https://itemsadder.devs.beer/plugin-usage/adding-content/block/enabling-custom-blocks-sounds

Tutorial on how to add sounds:
https://itemsadder.devs.beer/plugin-usage/adding-content/block/create-a-block#sounds
