### ISSUE TITLE
Please add a parameter to disable autoloading _iainternal

### ISSUE THREAD

**Issue by shiksyt** [PluginBugs/Issues-ItemsAdder#3001]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

sh1kcs

### Describe the solution you'd like

I want to disable autoloading of the default resource package from itemsadder, because my tab and other things conflict with it

### Is your feature request related to a problem?

Add a parameter to the config that disables autoloading of this parameter

### Describe alternatives you've considered

Tried to delete the folder, but it was restored

**Comment by LoneDev6** [comment]
`extract_internal_utility_assets: true`
it's already implemented
