### ISSUE TITLE
Keep_on_Death ability is not compatible with any combatlogger plugin

### ISSUE THREAD

**Issue by MoGGaming** [PluginBugs/Issues-ItemsAdder#3005]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

mog.gaming

### What happened?

Suppose custom swords from have the 'soulbound/keep_on_Death' ability and are not dropped when players die. However, when players disconnect during combat, they lose their tools with the 'soulbound/keep_on_Death' enchantment.
Its should dnt get desappear any how.

combatlogger plugin dev wanted to make their plugin compatible with itemsadder but they are unable to find this API behaviours.

### Steps to reproduce the issue

1. apply keep_on_death behaviour on your any item
2. add any combatlogger plugin that prevent player disconnecting from game while in combat
3. after reconnect to the server items is disappear from inventory its not even dropping ground after disconnect.

### Server version

[13:31:22 INFO]: Current: git-Purpur-2050 (MC: 1.20.1)*
* You are 6 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### ItemsAdder Version

about itemsadder
[13:31:46 INFO]: ItemsAdder version 3.5.0c-r4b
[13:31:46 INFO]: Customized Minecraft without client mods!
[13:31:46 INFO]: Website: devs.beer
[13:31:46 INFO]: Author: LoneDev

### ProtocolLib Version

about protocollib
[13:32:01 INFO]: ProtocolLib version 5.1.0
[13:32:01 INFO]: Provides read/write access to the Minecraft protocol.
[13:32:01 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

about lonelibs
[13:32:27 INFO]: LoneLibs version 1.0.25
[13:32:27 INFO]: Collection of libs used by my plugins
[13:32:27 INFO]: Authors: LoneDev and others

### FULL server log

https://paste.helpch.at/orokeveqem.makefile

**Comment by LoneDev6** [comment]
This is my code:
```java
@EventHandler(priority = EventPriority.LOWEST)
private void onDeath(PlayerDeathEvent e)
{
    Player player = e.getEntity();

    Iterator<ItemStack> iterator = e.getDrops().iterator();
    ItemStack item;
    while(iterator.hasNext())
    {
        item = iterator.next();
        if () // if it's a custom item and if it has `keep_on_death` tag
        {
            iterator.remove();
            keptItems.computeIfAbsent(player.getUniqueId(), k -> new ArrayList<>()).add(item);
        }
    }
}

    @EventHandler(priority = EventPriority.MONITOR)
    private void onPlayerRespawnEvent(PlayerRespawnEvent e)
    {
        /// Give the item back to the player on spawn
    }
```


The issue relies in the fact that the player might not trigger respawn event when they die?
I might have to actually save the items into a temporary file and load it on Join and on Respawn.

Do you agree? You can also send this Github issue page link to the combat log plugin developer to get an opinion about it.

**Comment by Ramgaming** [comment]
Hello LoneDev6

Thanks for response, I have shared this issue with combatlog plugin dev
btw I m using deluxcombat plugin

**Comment by Badbird5907** [comment]
> This is my code:
> 
> ```java
> @EventHandler(priority = EventPriority.LOWEST)
> private void onDeath(PlayerDeathEvent e)
> {
>     Player player = e.getEntity();
> 
>     Iterator<ItemStack> iterator = e.getDrops().iterator();
>     ItemStack item;
>     while(iterator.hasNext())
>     {
>         item = iterator.next();
>         if () // if it's a custom item and if it has `keep_on_death` tag
>         {
>             iterator.remove();
>             keptItems.computeIfAbsent(player.getUniqueId(), k -> new ArrayList<>()).add(item);
>         }
>     }
> }
> 
>     @EventHandler(priority = EventPriority.MONITOR)
>     private void onPlayerRespawnEvent(PlayerRespawnEvent e)
>     {
>         /// Give the item back to the player on spawn
>     }
> ```
> 
> The issue relies in the fact that the player might not trigger respawn event when they die? I might have to actually save the items into a temporary file and load it on Join and on Respawn.
> 
> Do you agree? You can also send this Github issue page link to the combat log plugin developer to get an opinion about it.

The issue is there is no API to tell if an item can be kept on death, as the player doesn't actually trigger a PlayerDeathEvent when they log out.
AdvancedEnchantments has an API `AEAPI.hasWhitescroll(ItemStack)` that allows me to only add drops without a whitescroll (keep specific items on death)
Example:
```java
if (Bukkit.getPluginManager().isPluginEnabled("AdvancedEnchantments")) {
                        event.getDrops().addAll(trait.getItems().stream()
                                .filter(item -> !AEAPI.hasWhitescroll(item)).collect(Collectors.toList()));
                    } else {
                        event.getDrops().addAll(trait.getItems());
                    }
                    ```

**Comment by LoneDev6** [comment]
Would a simple static utility API method to check if the item has `keep_on_death` would work? Would it be okay for you to use it?

**Comment by LoneDev6** [comment]
Added in the API version: `3.6.2-beta-r3-b`

`ItemsAdder#hasKeepOnDeath(...)`
