### ISSUE TITLE
Error getting server minor version on AdvancedSlimePaper

### ISSUE THREAD

**Issue by EpicPlayerA10** [PluginBugs/Issues-ItemsAdder#3006]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

epicplayera10

### What happened?

When I run server on AdvancedSlimePaper then ItemsAdder will print this into console:
```
[18:55:00 ERROR]: [ItemsAdder] Error getting server minor version: For input string: "20-R0"
[18:55:00 WARN]: [ItemsAdder] Custom player emotes require Minecraft 1.17+. Feature disabled.
```
Player emotes don't work.

### Steps to reproduce the issue

1. Follow guide from [AdvancedSlimePaper](https://github.com/InfernalSuite/AdvancedSlimePaper) to install build (you need to download build from their [discord](https://discord.gg/YevvsMa))
2. Run AdvancedSlimePaper server with ItemsAdder

### Server version

This server is running SlimeWorldManager version git-SlimeWorldManager-15305 (MC: 1.20.1) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: 5fd6a2f on paper_upstream)

### ItemsAdder Version

ItemsAdder version 3.5.0c-r5

### ProtocolLib Version

ProtocolLib version 5.1.0

### LoneLibs Version

LoneLibs version 1.0.25

**Comment by LoneDev6** [comment]
It's because your server implements 1.20 and not 1.20.1.
Update your server jar or contact its developers to fix the version string.

For example my server has this:
`This server is running Paper version git-Paper-57 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 437e8da)`

As you can see it shows `API version 1.20.1-R0.1-SNAPSHOT`

**Comment by EpicPlayerA10** [comment]
Well, I'm using the latest AdvancedSlimePaper 1.20.1. As you can see here:
```
This server is running SlimeWorldManager version git-SlimeWorldManager-15305 (MC: 1.20.1) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: 5fd6a2f on paper_upstream)
```
The AdvancedSlimePaper runs on __<ins>minecraft version</ins>__ `1.20.1` with __<ins>api version</ins>__ `1.20-R0.1-SNAPSHOT` so it does not mean that server runs on `1.20` but on version `1.20.1`. You can see here that developers forgot to bump the api version. I will obviously tell them to bump it.

But anyway I recommend you to use PaperLib for fetching minecraft version. PaperLib is compatible with Bukkit, Spigot, Paper, and all other forks. For example if you want to get minor version, you can just call `PaperLib#getMinecraftVersion()` ([method doc](https://github.com/PaperMC/PaperLib/blob/master/src/main/java/io/papermc/lib/PaperLib.java#L250C9-L250C9)) and you have the minor version :D
