### ISSUE TITLE
Blocks turn to Noteblock temporarily

### ISSUE THREAD

**Issue by Xiao-MoMi** [PluginBugs/Issues-ItemsAdder#3007]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

https://github.com/PluginBugs/Issues-ItemsAdder/assets/70987828/5909c782-1a54-4bc4-8006-c3aa295685bc

https://github.com/PluginBugs/Issues-ItemsAdder/assets/70987828/0f48c888-a8bf-42f5-9ac5-fd089fa5f87d

### Steps to reproduce the issue

Follow the video :)
I think it's caused by some async methods so client received two block update packets

### ItemsAdder Version

 3.5.0c-r5

### ProtocolLib Version

 5.1.1-SNAPSHOT-668

### LoneLibs Version

1.0.25

**Comment by LoneDev6** [comment]
It's impossible to fix.
The client predicts blocks changes and ItemsAdder is reverting the change.
You see the noteblock for a brief moment because of client->server connection delay which is impossible to prevent.
