### ISSUE TITLE
New Behavior suggestion

### ISSUE THREAD

**Issue by EchocallingEarth** [PluginBugs/Issues-ItemsAdder#3013]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

297596704935378945

### Describe the solution you'd like

Item behavior where the Item changes or is removed when interacting with Water or Lava

New behavior:
if a player were to enter water with a custom item, the item would vanish, be broken, or revert to a specified state. 

Using a custom item, this item would have a reaction with water or lava depending on the behavior setting.

Example: a custom fire item that would have a fire aspect would be affected by water. This effect could be set in the behavior section and result in anything from the item being cleared from the player's inventory to being reset to a specified item or just having its effects/enchants removed. This would be known as a water effect.

In the same example, the item could be used to give fire_walker or fire protection or some other buff when entering lava in which case it protects the user from any damage so long as in the mainhand.

### Is your feature request related to a problem?

More related to a limit currently with ItemsAdder

### Describe alternatives you've considered

I did a bunch of searching and there are no plugins that seem to do this.

### Additional context

I can try to create screen shots that would show the concept if it would help.

**Comment by LoneDev6** [comment]
Hello, this is a cool idea but would require the plugin to constantly iterate over all the players and check if they are in water/lava.
This is an intensive task for the server, so are you sure this feature is actually really needed?
Thanks!

**Comment by EchocallingEarth** [comment]
After consideration and the realization of how this could negatively affect a server, I would agree a cool idea but not a good one at this time. Thanks for considering it I will close this as acceptably resolved.
