### ISSUE TITLE
Add Color overload for replaceFurniture method

### ISSUE THREAD

**Issue by Mike5357** [PluginBugs/Issues-ItemsAdder#3026]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

mike5357

### Describe the solution you'd like

Add an overload method for replaceFurniture where a color can be passed through for a tintable (leather horse armor) furniture.

### Is your feature request related to a problem?

Yes; I would like to replaceFurniture to custom items which are leather horse armor with a specific color code.

### Describe alternatives you've considered

I have not

**Comment by LoneDev6** [comment]
`public void replaceFurniture(String newFurnitureNamespacedId, Color color)`

Will be available in the next API update.
