### ISSUE TITLE
Hide custom sound playback message

### ISSUE THREAD

**Issue by paulreob** [PluginBugs/Issues-ItemsAdder#3030]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

What happens is that I am using DeluxeMenus and there is no function to play custom sounds, only vanilla (spigot api), so I am using the `/iaplaysound` command
`- '[console] iaplaysound souleaf:souleaf.miselaneo.fail %player_name%'`

But when using it it throws the following message in the console, is it possible to hide this message, just like iagive does?
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/71041139/59734910-3b76-4035-b7bb-6b84a96bb869)

### Is your feature request related to a problem?

Nop

### Describe alternatives you've considered

Nop

**Comment by paulreob** [comment]
In addition, the pitch and volume can be adjusted.
example:
`iaplaysound souleaf:souleaf.miselaneo.fail [pitch] [volum] %player_name%`

**Comment by LoneDev6** [comment]
Already implemented in the upcoming update: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2790
The other attributes will be implemented.
