### ISSUE TITLE
Fantom Chorus blocks and weird chorus plant textures

### ISSUE THREAD

**Issue by WataLaker37821** [PluginBugs/Issues-ItemsAdder#3031]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

DOGE#1690

### What happened?

After i place chorus on end stone and break it, players who were near me at the moment, will still be able to see chorus plant block and stand on it (detected as phantom block by Vulcan anti-cheat)
Also, why could it be such weird shape? I tried to change updating of a chorus in purpur.yml but it did not help

### Steps to reproduce the issue

1. Place a chorus plant near a player
2. Break it
3. Player is able to walk on it and see it, he will need to tp somewhere else, not to see a block anymore

### Server version

git-Purpur-2060 (MC 1.20.1)

### ItemsAdder Version

3.5.0c-r6

### ProtocolLib Version

5.1.0

### LoneLibs Version

1.0.25

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/12705932/latest.log)

### Problematic items yml configuration file (optional)

```shell
reinforced_glass:
    enabled: true
    display_name: '&fУкреплённое стекло'
    permission: ic2.craft
    resource:
      material: PAPER
      generate: true
      textures:
        - item/blocks/reinforced_glass.png
    specific_properties:
      block:
        placed_model:
          type: REAL_TRANSPARENT
          break_particles_material: GLASS
        break_tools_whitelist:
          - IRON_PICKAXE
          - DIAMOND_PICKAXE
          - NETHERITE_PICKAXE
        hardness: 10 #hardness of the block
        blast_resistance: 1 #explosion resistance (by default is hardness*3)
        no_explosion: true #totally immune from explosions, ignoring blast_resistance
        sound: #customizable sounds of the block
          place:
            name: BLOCK_GLASS_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_GLASS_BREAK
            volume: 1
            pitch: 0.9


(Could be a problem, cos i added it myself)
```

### Other files, you can drag and drop them here to upload. (optional)

[config.txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/12705938/config.txt)

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/121085310/bb38f5f5-a487-4241-a628-04517cfdc3b7)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/121085310/22a120f3-ce84-49f2-b8fd-722d05832534)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/121085310/dffe0db4-4a4f-4efd-9ab8-2b393cba2dd7)

**Comment by LoneDev6** [comment]
The "weird texture" is normal, it's the downside of enabling REAL_TRANSPARENT blocks.
If you don't want this to happen you have to disable REAL_TRANSPARENT blocks in the config.yml file of ItemsAdder and run /iazip to regenerate the pack.

About the ghost block: I will test and let you know, thanks.

**Comment by WataLaker37821** [comment]
thanks a lot, will know in the future, will wait for results of the tests, hope will be able to reproduce, if needed some of my configs or pack files, let me know, maybe smth wrong with them

**Comment by LoneDev6** [comment]
I cannot reproduce the issue, I can place the block and the other player can see it.
I can mine it and the other player sees it removed from the world.

There probably is something interfering or you're running an old version of the plugin.
