### ISSUE TITLE
Placeholder for player_name to execute commands from console via furniture, for specific player

### ISSUE THREAD

**Issue by WataLaker37821** [PluginBugs/Issues-ItemsAdder#3036]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

DOGE#1690

### Describe the solution you'd like

I tried to make a laptop (for example), so when a player rightclicks it, a command would open him a menu through a console, so i wont need to give him direct acess to that menu, so player will need to use this furniture item to grant access to specific action that is available when using it.

### Is your feature request related to a problem?

I could not set a placeholder to specify player's name (tried %player_name%, %player%, etc.)

### Describe alternatives you've considered

i think it might be helpful to implement a placeholder to specify player's name for making some sort of content, based on console command executions for specific players, there are no other alternatives i could think about

**Comment by ShizuArt** [comment]
Have you tried with `{player}` as specified on the wiki?
It works very well for me

https://itemsadder.devs.beer/plugin-usage/adding-content/item-properties/events/actions#list-of-actions-properties

Under `execute_commands:` part

**Comment by WataLaker37821** [comment]
> Have you tried with `{player}` as specified on the wiki? It works very well for me
> 
> https://itemsadder.devs.beer/plugin-usage/adding-content/item-properties/events/actions#list-of-actions-properties
> 
> Under `execute_commands:` part

no, i didnt, im sorry, will try and immediately close issue if it will work, much thanks man
