### ISSUE TITLE
Important bug with the iaremove command

### ISSUE THREAD

**Issue by paulreob** [PluginBugs/Issues-ItemsAdder#3040]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

The iaremove command does not remove renamed items or if the item's nbt is modified

I use the iaremove command to take items from the player's inventory in an item sales menu, but I realized if I rename or change the nbt the iaremove command fails to remove it, this is a big problem because the logic of the menu he thinks he always has the itemcustom but it will never be taken, managing to give him money as much as he wants

The command should only detect the Namespace and ID of the item

### Steps to reproduce the issue

1. Get a custom item
2. Rename/Enchat it or add a custom nbt
3. Try using the `iaremove` command to remove that custom item

### Server version

git-Purpur-2035 (MC: 1.20.1)*

### ItemsAdder Version

ItemsAdder version 3.5.1

### ProtocolLib Version

ProtocolLib version 5.1.0

### LoneLibs Version

LoneLibs version 1.0.26

**Comment by LoneDev6** [comment]
Use `/iatag` command while holding an unmodified custom item and a modified custom item, then open the console and copy and paste the output here.

**Comment by paulreob** [comment]
Unmodified
`{Count:1b,id:"minecraft:baked_potato",tag:{CustomModelData:10000,display:{Name:'{"italic":false,"color":"white","text":"Banana "}'},itemsadder:{id:"banana_1star",namespace:"souleaf"}}}`

Modified (Renamed to Banana => Bananitas)
`{Count:1b,id:"minecraft:baked_potato",tag:{CustomModelData:10000,display:{Name:'{"extra":[{"text":"Bananitas "}],"text":""}'},itemsadder:{id:"banana_1star",namespace:"souleaf"}}}`

**Comment by paulreob** [comment]
😭😭

**Comment by LoneDev6** [comment]
Don't worry I'm working on the update and I'll check your issue too
