### ISSUE TITLE
Duplication issue

### ISSUE THREAD

**Issue by potapenchikov** [PluginBugs/Issues-ItemsAdder#3048]
REDACTED

**Comment by LoneDev6** [comment]
Do not report duplication bug publicly.
Your account will be suspended if further duplication issues will be reported from your account.
Please make sure to use the correct section to report this kind of issues.

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/7746f10b-555d-4c67-ba40-84381a2d71b9)

Thanks.
