### ISSUE TITLE
Cave decorators are not working on the Overworld (default world)

### ISSUE THREAD

**Issue by Millionary** [PluginBugs/Issues-ItemsAdder#3051]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Millionary28

### What happened?

I've tried to add decorations to caves, and custom caves, but those aren't being generating.
Any decorators are generating in the Overworld, in any block.

I have other cave decorations on other worlds (even datapack worlds) and those are working well.

When i configure the decorators to spawn on other worlds than "world" it works just fine, but if it's on world "world" it doesn't work.

### Steps to reproduce the issue

1. Create various cave generators.
2. Re generate the world.
3. See that those aren't generating.

### Server version

This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version

### ItemsAdder Version

ItemsAdder 3.5.1

### ProtocolLib Version

ProtocolLib 5.1.0

### LoneLibs Version

LoneLibs 1.0.27

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/12770895/latest.log)

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: decoradores
cave_decorators:
  champinon_brillante:
    block: champinon_brillante
    bottom_blocks:
    - BROWN_GLAZED_TERRACOTTA
    - STONE
    - DEEPSLATE
    worlds:
    - world
    chance: 99.9
    max_height: 60
    min_height: -50
    amount: 10
    position: SURFACE

  champinon_brillante_2:
    block: champinon_brillante_2
    bottom_blocks:
    - BROWN_GLAZED_TERRACOTTA
    - STONE
    - DEEPSLATE
    worlds:
      - world
    chance: 99.9
    max_height: 60
    min_height: -50
    amount: 10
    position: SURFACE

  colmillo_corrupto_1:
    block: colmillo_corrupto_1
    bottom_blocks:
    - PURPLE_GLAZED_TERRACOTTA
    - STONE
    - DEEPSLATE
    worlds:
    - world
    chance: 99.9
    max_height: 60
    min_height: -50
    amount: 10
    position: SURFACE

  malahierba_1:
    block: malahierba_1
    bottom_blocks:
    - PURPLE_GLAZED_TERRACOTTA
    - STONE
    - DEEPSLATE
    worlds:
    - world
    chance: 99.9
    max_height: 60
    min_height: -50
    amount: 10
    position: SURFACE

  colmillo_carmesi_1:
    block: colmillo_carmesi_1
    bottom_blocks:
    - RED_GLAZED_TERRACOTTA
    - STONE
    - DEEPSLATE
    worlds:
    - world
    chance: 99.9
    max_height: 60
    min_height: -50
    amount: 10
    position: SURFACE

# If i configure these to spawn in other world than "world" it works fine.
```

### Screenshots/Videos (you can drag and drop files or paste links)

![2023-09-29_13 26 31](https://github.com/PluginBugs/Issues-ItemsAdder/assets/105462545/1afeb194-6909-415e-bae4-62bb21dacb52)
Note: This block is BROWN_GLAZED_TERRACOTTA with a custom texture and i configure ItemsAdder to spawn a fungus on it but it's not working as intended.

![2023-09-29_13 27 05](https://github.com/PluginBugs/Issues-ItemsAdder/assets/105462545/ed0d3a01-cebf-4c70-a058-b35781a8235d)
Note: This block is PURPLE_GLAZED_TERRACOTTA, the same history for this one.

![2023-09-29_13 30 28](https://github.com/PluginBugs/Issues-ItemsAdder/assets/105462545/8f3201bd-fb42-454c-b621-e56cbb058e78)
Note: The same, this is RED_GLAZED_TERRACOTTA but there's nothing on it.

![2023-09-29_13 35 14](https://github.com/PluginBugs/Issues-ItemsAdder/assets/105462545/3489986c-2ec5-4ece-9bec-7a0c7fc3fa92)
Note: These are the decorators, i configure them to spawn in the nether on NETHERRACK and it works fine, but not in the overworld "world".

**Comment by LoneDev6** [comment]
Strange, I don't see how the world name would affect the generation.
I'll do some tests and let you know, thanks for the file

**Comment by Millionary** [comment]
Now i restarted the server and some of them generate and others don't, i will continue testing

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/105462545/f8c740b8-3264-42fe-a1f5-bb7756523199)

I configured some more decorators that i made but those are not spawning

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/105462545/36a114a1-5587-4256-b12e-b9a01d1f1cd0)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/105462545/cb1e0010-30ca-4d32-917c-9453fa98e70f)

These ones are not in the generation log, the chance of spawning it's not too low to be the couse of this but i will continue testing.

I searched those decorators in the log but aren't present, only apears on the registration of the decorator.

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/105462545/c3c46497-32d5-4108-b53c-e8d73f608588)

If it works for something, the log: 
[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/12799611/latest.log)

**Comment by LoneDev6** [comment]
Maybe these bottom blocks are rare so the custom blocks cannot spawn as they can't find space?
Let me know
