### ISSUE TITLE
BUG GRAVE - BYPASS BLOCKED - ENCHANT

### ISSUE THREAD

**Issue by Distolfix** [PluginBugs/Issues-ItemsAdder#3053]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Bypass Blocked - Enchant

### Steps to reproduce the issue

https://forum.devs.beer/d/1862-bug-bypass-blocked-enchant

### Server version

This server is running Pufferfish version git-Pufferfish-73 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: cadfa71 on HEAD)
You are on the latest version!
Previous version: git-Pufferfish-61 (MC: 1.19.3)

### ItemsAdder Version

3.5.1

### ProtocolLib Version

5.1.1 - 669

### LoneLibs Version

1.027

**Comment by Distolfix** [comment]
Scusa se lo ho caricato su più piattaforme, penso però che facendolo in questa maniera ti semplifico il lavoro

**Comment by LoneDev6** [comment]
Sì grazie, avrei creato io poi questa issue con link al forum altrimenti <3

**Comment by LoneDev6** [comment]
Guardando bene la issue di per se non dovresti avere quell'oggetto con enchant in primis.
Comunque sia ho corretto, il risultato manterrà lo stesso livello di enchant invece che aumentarlo, nel caso in cui in qualche modo l'oggetto abbia un enchant bloccato, probabilmente aggiunto con dei comandi dagli admin.

**Comment by Distolfix** [comment]
Invece si, perché per esempio un kit vip ha affilatezza 1 ma non voglio che l’utente poi possa mettersi affilatezza 2
