### ISSUE TITLE
After mining the block, the custom name is not shown

### ISSUE THREAD

**Issue by Desmordss** [PluginBugs/Issues-ItemsAdder#3054]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

desmoo#3218

### What happened?

I'm making ore for my server, and after mining I get an item with the name "Paper" instead of a custom one. How do I fix this?

### Steps to reproduce the issue

-

### Server version

Purpur 1.20.1

### ItemsAdder Version

ItemsAdder 3.5.1

### ProtocolLib Version

ProtocolLib 5.1.0

### LoneLibs Version

LoneLibs 1.0.25

### Problematic items yml configuration file (optional)

```shell
ORE CONFIG:
items:  
  chlorophyte_ore:
    display_name: display-name-chlorophyte_ore
    sound:
      break:
        name: BLOCK_STONE_BREAK
        volume: 1
        pitch: 0.9
      place:
        name: BLOCK_STONE_PLACE
        volume: 1
        pitch: 0.9
    resource:
      generate: true
      material: PAPER
      textures: 
      - "block/chlorophyte_ore"
    specific_properties:
      block:
        hardness: 2
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
        cancel_drop: true
        break_tools_blacklist:
          - HAND
          - "_AXE"
          - WOODEN_PICKAXE
          - STONE_PICKAXE
loots:
  blocks:
    chlorophyte_ore:
      type: chlorophyte_ore
      items:
        raw_chlorophyte:
          item: raw_chlorophyte
          min_amount: 1
          max_amount: 2
          chance: 100
      exp:
        exp_1:
          min_amount: 0
          max_amount: 3
          chance: 100

INGOTS CONFIG:
  raw_chlorophyte:
    display_name: display-name-raw_chlorophyte
    resource:
      material: PAPER
      generate: true
      textures:
      - item/raw_chlorophyte

LANG:
display-name-raw_chlorophyte: "&fChlorophyte Raw"
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/78231435/dd812f17-f284-4ee0-a14b-cea0bc0889d3)

**Comment by LoneDev6** [comment]
I think this is related to your holograms plugin, not ItemsAdder.
Please confirm that the items names are correct when in inventory.

**Comment by Desmordss** [comment]
> I think this is related to your holograms plugin, not ItemsAdder.
Please confirm that the items names are correct when in inventory.

I left the screenshot with the holograms for ease of understanding.
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/78231435/e66dd081-a600-49b2-b929-f86092e0f1e0)

I'm using the Terraria addon (https://www.spigotmc.org/resources/ia-addon-terraria-pack-18-new-armors-tools-new-blocks-and-fishes.102194/)

**Comment by LoneDev6** [comment]
Does this happen only with the terraria drops?
Because I cannot trigger it.

Also please as I said remove your holograms plugin and test again.
