### ISSUE TITLE
Changing world break RP asking prompt 

### ISSUE THREAD

**Issue by JohnKillswitch** [PluginBugs/Issues-ItemsAdder#3055]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

If player joined the server and teleported to another world RP asking prompt  is breaking and player can play without kicking with 
  kick-player-on-decline: true
  kick-player-on-fail: true

### Steps to reproduce the issue

join server
change world
done.

### Server version

1.20.1

### ItemsAdder Version

3.5.1

### ProtocolLib Version

5.1.1

### LoneLibs Version

1.0.26

**Comment by LoneDev6** [comment]
I'll do some checks but this is an edge case.
You shouldn't teleport your players on join before they applied the resourcepack.

**Comment by JohnKillswitch** [comment]
UPD after some tests:
I create a new clear server with only ItemsAdder. When player join this server he need to accept RP and after that he can join main server. BUT, some players still not get a RP install prompt on first join for some reason.
I create a 3 accounts and try to join and all 3 accounts have a asking prompt 

Players dont teleports now and IDK what can be a reason for this weird bug...

**Comment by LoneDev6** [comment]
Can you increase the delay in config.yml of itemsadder as shown in the guide?
