### ISSUE TITLE
Noteblocks not showing custom texture for some reason

### ISSUE THREAD

**Issue by DonKolia** [PluginBugs/Issues-ItemsAdder#3058]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

DonKolia

### What happened?

My block texture never updates, I restart the server and the REAL_NOTE texture is visible.
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/55564649/1dcf6d6b-9e9f-44a8-bba1-5c09ee23da7b)

This has been tested on a bare Vanilla client and on a server with ItemsAdder_3.6.0, LoneLibs and ProtocolLib. No more plugins.

### Steps to reproduce the issue

If I break the block and put it back the texture comes back, but then when I restart it disappears.

### Server version

This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version
Previous version: git-Paper-167 (MC: 1.20.1)

### ItemsAdder Version

ItemsAdder version 3.6.0
[16:09:54 INFO]: Customized Minecraft without client mods!
[16:09:54 INFO]: Website: devs.beer
[16:09:54 INFO]: Author: LoneDev

### ProtocolLib Version

[16:10:30 INFO]: ProtocolLib version 5.1.1-SNAPSHOT-668
[16:10:30 INFO]: Provides read/write access to the Minecraft protocol.
[16:10:30 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[16:10:48 INFO]: LoneLibs version 1.0.27
[16:10:48 INFO]: Collection of libs used by my plugins
[16:10:48 INFO]: Authors: LoneDev and others

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/12783324/latest.log)

**Comment by paulreob** [comment]
`/iacleancache blocks`
`/iazip`

**Comment by DonKolia** [comment]
I unistall and i put only the block and texture in a new server, everything is clean server, the new version is bug

**Comment by DonKolia** [comment]
Now is working, idk why, really. Dont close this, put in "pending" is really weird.

**Comment by DonKolia** [comment]
I removed this folders and restart the server
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/55564649/8007aa35-3324-4c1b-8e97-6ac64676b4fb)

**Comment by LoneDev6** [comment]
Hello!
Thanks for the patience, I'm here to assist you,

> Now is working, idk why, really. Dont close this, put in "pending" is really weird.

Difficult to say, probably your resourcepack wasn't regenerated?

> I removed this folders and restart the server ![image](https://user-images.githubusercontent.com/55564649/272072151-8007aa35-3324-4c1b-8e97-6ac64676b4fb.png)

These folders have nothing to do with itemsadder so I think it was just a coincidence.

Let me know if if the issue occurs again so that I can further investigate, the plugin works fine on more than 5000 servers so I bet it's a simple mistake :D 

Have a nice day

**Comment by DonKolia** [comment]
At the moment it is working, now I don't know why it has happened. Thanks for the help anyway.
