### ISSUE TITLE
Add walk on event

### ISSUE THREAD

**Issue by nolway** [PluginBugs/Issues-ItemsAdder#3064]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

When an entity is walking on the furniture hitbox you can do an action.

### Is your feature request related to a problem?

I want trigger when a entity is walking on a furniture armorstand hitbox by implementing a new event like "placed_armorstand.walk_on".

### Describe alternatives you've considered

I don't know.

**Comment by LoneDev6** [comment]
This would be very performance demanding for the server, I don't think it's safe implementing this kind of feature, it would make the server very slow due to how the game works.
