### ISSUE TITLE
Updating ItemsAdder from 3.4.1r6 to 3.6.0 breaks iaentities models 

### ISSUE THREAD

**Issue by chamo572** [PluginBugs/Issues-ItemsAdder#3067]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

chamo572

### What happened?

Before update the plugin my iaentities looked like this:
![2023-10-04_14 44 23](https://github.com/PluginBugs/Issues-ItemsAdder/assets/69493452/ce2618df-ab68-4a5d-b91b-83b70d7644aa)

After updating:
![2023-10-04_14 39 06_2](https://github.com/PluginBugs/Issues-ItemsAdder/assets/69493452/23850c7d-5e68-4520-b449-43ce0b766883)

I didn't changed config or .json of models, I only updated the plugin

### Steps to reproduce the issue

1. Return to 3.4.1-r6
2. Put iaentites in the resourcepack
3. make /iazip and verify that the entities work well
4. Update the plugin and its dependencies to the latest versions (in this case 3.6.0)

### Server version

1.19.4

### ItemsAdder Version

3.4.1-r6

### ProtocolLib Version

5.1.1-SNAPSHOT-669

### LoneLibs Version

1.0.26

**Comment by LoneDev6** [comment]
Can you regenerate your resourcepack using /iazip?

**Comment by chamo572** [comment]
Yes I used /iazip to check, but still the same

**Comment by LoneDev6** [comment]
Are you sure the pack is updated?
I'm sure i made some changes to the emotes generation, they require you to regenerate the pack to apply in-game.
Let me know
