### ISSUE TITLE
[Suggestion] Add AdvancedEnchantments compatibility

### ISSUE THREAD

**Issue by Zangerine** [PluginBugs/Issues-ItemsAdder#307]
**Is your feature request related to a problem? Please describe.**
Not a problem, but something that would be a welcome addition.

**Describe the solution you'd like**
Add AdvancedEnchantments compatibility to craft already enchanted custom items. AdvancedEnchantments uses custom NBT tags to "enchant" items so it would be cool if we could craft them with the enchants.

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1061
