### ISSUE TITLE
Inconsistency with the speed of breaking blocks with efficiency

### ISSUE THREAD

**Issue by VacAge** [PluginBugs/Issues-ItemsAdder#3070]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

VacAge

### What happened?

I found a possible bug related to the breaking speed under efficiency enchants on picks. 

During my development I stumbled upon an inconsistency: 
iron_pickaxe with efficiency 1 was quicker in breaking custom blocks than stone_pickaxe with efficiency 3. 

A stone pickaxe, in theory, should dig faster, which happens with ordinary blocks, but with custom ones the opposite happens - the iron one digs faster than the stone one.

### Steps to reproduce the issue

I made a custom block with Hardness 1.0, also made 5 different picks with different efficiencies from 1 to 5. 

When doing my tests I found out that breaking speeds were increasing in this order of pickaxe efficiencies: 3 > 2 > 1 > 4 > 5.

I also tested this on vanilla pickaxes, which led to the same problem, but with ordinary vanilla blocks everything is fine and we get a predictable 1 > 2 > 3 > 4 > 5 progression.

### Server version

Current: git-Purpur-2062 (MC: 1.20.1)
Previous: git-Purpur-2060 (MC: 1.20.1)
You are running the latest version

### ItemsAdder Version

ItemsAdder version 3.6.0

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-669

### LoneLibs Version

LoneLibs version 1.0.27

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/12838297/latest.log)

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: prison
items:
#1
  1:
    display_name: "1"
    enchants:
      - DIG_SPEED:1
    resource:
      material: netherite_pickaxe
#2
  2:
    display_name: "2"
    enchants:
      - DIG_SPEED:2
    resource:
      material: netherite_pickaxe
#3
  3:
    display_name: "3"
    enchants:
      - DIG_SPEED:3
    resource:
      material: netherite_pickaxe
#4
  4:
    display_name: "4" #128
    enchants:
      - DIG_SPEED:4
    resource:
      material: netherite_pickaxe
#5
  5:
    display_name: "5" #190
    enchants:
      - DIG_SPEED:5
    resource:
      material: netherite_pickaxe
```

### Other files, you can drag and drop them here to upload. (optional)

[Block config](https://mclo.gs/EYIioU1)
[Pickaxe config](https://mclo.gs/hEXgn4C)

### Screenshots/Videos (you can drag and drop files or paste links)

[YouTube example](https://youtu.be/hHUkqxFgP-8)

**Comment by LoneDev6** [comment]
I'll do some testing but this is very strange as I use the same formula used by the game to calculate hardness of vanilla blocks.

**Comment by PortableGames** [comment]
Maybe the simplest solution is the truth. You probably replaced lines 1,2,3 in the code with 3,2,1 😎🐧😎

**Comment by VacAge** [comment]
> Maybe the simplest solution is the truth. You probably replaced lines 1,2,3 in the code with 3,2,1 😎🐧😎

Your comment is inappropriate and unnecessary.

**Comment by VacAge** [comment]
Is there any way I can help speed up the issue process?

**Comment by LoneDev6** [comment]
I'll check this issue this week, thanks for the patience

**Comment by LoneDev6** [comment]
Thanks a lot for your extremely detailed tests and configurations.
I'm now trying to find the cause of the issue.

**Comment by LoneDev6** [comment]
Fixed!

https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/dc3a451a-3ec2-47c2-9161-c3035a83275a
