### ISSUE TITLE
Replace one furniture with another

### ISSUE THREAD

**Issue by ShizuArt** [PluginBugs/Issues-ItemsAdder#3075]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

shizua.

### What happened?

Following this issue https://github.com/PluginBugs/Issues-ItemsAdder/issues/2337 this has already been fixed but it seems that the issue has returned.
`replace_properties` no longer works and makes the armor stand invisible and impossible to break.
However, in the latest beta version (3.6.1-beta-2) the invisible armor stand problem seems to be fixed but it remains non-functional

### Steps to reproduce the issue

Use this event :

```
    events:
      placed_armorstand:
        interact:
          replace_properties:
            custom_model_data:
              copy_from_item:
```

### Server version

This server is running CraftBukkit version 3870-Spigot-d2eba2c-78796c9 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 3.6.0

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-669

### LoneLibs Version

 LoneLibs version 1.0.27

### Problematic items yml configuration file (optional)

```shell
lampe_grande:
    enabled : true
    permission: ""
    display_name: "%#00f6ff%Grande lampe"
    lore:
    - ''
    behaviours:
      furniture:
        entity: armor_stand
        solid: true
        hitbox:
          height: 2
        cancel_drop: false
        sound:
          place:
            name: block.wood.place
          break:
            name: block.wood.break
    events:
      placed_armorstand:
        interact:
          replace_properties:
            custom_model_data:
              copy_from_item: lampe_grande2
          play_sound:
            name: block.lever.click
            volume: 0.5
            pitch: 1
    resource:
      material: PAPER
      generate: false
      model_path: lampes/lampe_grande
      model_id: 24011

  lampe_grande2:
    enabled : true
    permission: ""
    display_name: "%#00f6ff%Grande lampe"
    lore:
    - ''
    behaviours:
      furniture:
        entity: armor_stand
        solid: true
        hitbox:
          height: 2
        cancel_drop: false
        light_level: 15
        sound:
          place:
            name: block.wood.place
          break:
            name: block.wood.break
    resource:
      material: PAPER
      generate: false
      model_path: lampes/lampe_grande
      model_id: 24012
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/98397139/1b04425e-2d1a-4733-b9a5-282099de3c0e)

After interact event : 

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/98397139/2d881c72-26c4-428c-b64d-d6e822dd3456)

**Comment by LoneDev6** [comment]
Will be checked, I tested before release and worked fine, strange

**Comment by LoneDev6** [comment]
Thanks a lot!
Will be fixed in the upcoming update.
