### ISSUE TITLE
ActionBar characters

### ISSUE THREAD

**Issue by daniel-skopek** [PluginBugs/Issues-ItemsAdder#3086]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

When I don't use the server resource pack, the characters are displayed in the actionbar: https://i.imgur.com/97EFrfx.png

### Steps to reproduce the issue

1. Disable server resource pack
2. Join to the server

### ItemsAdder Version

3.6.1-beta

### ProtocolLib Version

5.1.0

### LoneLibs Version

1.0.27

**Comment by LoneDev6** [comment]
It's a known behaviour since you're not supposed to join without a resourcepack, but I'll avoid this in the next update.
Thanks
