### ISSUE TITLE
ItemsAdder giving a bunch of errors in 1.17.1

### ISSUE THREAD

**Issue by SiruisFR** [PluginBugs/Issues-ItemsAdder#3091]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

siruis.

### What happened?

Having a bunch of errors in 1.17.1 paper using all the latest versions i got.

https://pastebin.com/TcwHLz7q <- Error when loading itemsadder

-------

https://pastebin.com/9ANpE3qW <- Error when summonning an entity

-------

https://pastebin.com/g5WZsVTq <- Error when i log in

### Steps to reproduce the issue

Create a 1.17.1 paper spigot and get the same plugins with versions

### Server version

This server is running CraftBukkit version 3284a-Spigot-3892929-0ab8487 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder 3.6.1-beta.r2

### ProtocolLib Version

Protocol Lib 5.1.0

### LoneLibs Version

LoneLibs 1.0.27

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/13034534/latest.log)

**Comment by LoneDev6** [comment]
Install Paper 1.17.1 instead of Spigot.
Spigot 1.17.1 is outdated and doesn't implement the latest fixes introduced by Paper 1.17.1.
There is no reason to keep using Spigot if you're running an outdated version of the game.
This will fix your issue :D
