### ISSUE TITLE
Items with event cooldowns won't execute events on first try

### ISSUE THREAD

**Issue by nroj95** [PluginBugs/Issues-ItemsAdder#3097]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

nroj

### What happened?

My items with event cooldowns won't work on first try. Is this intended?

### Steps to reproduce the issue

PaperMC
Only IA, protocollib and lonelibs
Use an item with added cooldown for events, for instance:
    events_settings:
      cooldown:
        indicator: BOSSBAR
        ticks: 400
        bossbar:
          color: WHITE
          style: SOLID

Need to use that item twice for the events to start

### ItemsAdder Version

ItemsAdder version 3.6.1-beta-r2

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-669

### LoneLibs Version

LoneLibs version 1.0.27

**Comment by LoneDev6** [comment]
Please provide a test item configuration for me to precisely test the issue since last time I tried they worked fine.
Thanks

**Comment by nroj95** [comment]
I uploaded a test config to dropbox. I hope that's okey. https://www.dropbox.com/scl/fi/shgl5we77bl581hcllzpt/test.zip?rlkey=1stizxulw403biz2wa3o0ups9&dl=0

**Comment by nroj95** [comment]
It works on 3.6.0, just not the newest betas.
