### ISSUE TITLE
Textures are in the wrong direction

### ISSUE THREAD

**Issue by Kinuro** [PluginBugs/Issues-ItemsAdder#3101]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Textures are in the wrong direction

### Steps to reproduce the issue

1 Input a texture in the server
2 Give item
3 Hold item
4 See Bug

### Server version

This server is running CraftBukkit version 3755-Spigot-7d7b241-b346a5f (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT)

### ItemsAdder Version

3.4.1-r6

### ProtocolLib Version

5.1.0

### LoneLibs Version

1.0.25

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/148623848/08c6fdc0-9cda-4cc0-8f85-694715be8fcb)

**Comment by LoneDev6** [comment]
It's hard to tell without your yml item file and your image file.
Example axes and swords are correctly aligned, are you sure your image also is?

https://github.com/ItemsAdder/DefaultPack/blob/main/contents/iasurvival/resourcepack/iasurvival/textures/item/tools/ruby_pickaxe.png

https://github.com/ItemsAdder/DefaultPack/blob/0994b2cd3708d9c63c6fdfaee0519152a7733f2d/contents/iasurvival/configs/tools/items/ruby_pickaxe.yml#L4
