### ISSUE TITLE
[GitHub Suggestion] Add Discussions section here

### ISSUE THREAD

**Issue by DonKolia** [PluginBugs/Issues-ItemsAdder#3104]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

DonKolia

### Describe the solution you'd like

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/55564649/71e2b93f-fbb4-458c-874d-fdddb9a3b960)
I dont understand why u dont put it here, more fast, and best to vinculate the pulls, merge and rest....

### Is your feature request related to a problem?

Nothing.

### Describe alternatives you've considered

Nothing. Add.

### Additional context

Add a GitHub link in the Wiki header https://itemsadder.devs.beer/

**Comment by LoneDev6** [comment]
> I dont understand why u dont put it here

This can't be done because of how the whole projects system works.
It is also not convenient since it's basically Discord, which revealed to be extremely difficult to handle and slowed down project management.

https://github.com/orgs/PluginBugs/projects/3/views/1
