### ISSUE TITLE
CustomFurniture missing getNamespacedIdsInRegistry implementation

### ISSUE THREAD

**Issue by Shawn11564** [PluginBugs/Issues-ItemsAdder#3105]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

mrshawn.

### What happened?

CustomFurniture is missing an implementation for the method getNamespacedIdsInRegistry, instead it uses the method from the CustomStack parent object which returns all item ids instead of only furniture ids.

### Steps to reproduce the issue

1. Call `CustomFurniture.getNamespacedIdsInRegistry()`
2. Call `CustomStack.getNamespacedIdsInRegistry()`
3. Compare the two sets, they are exactly the same

### ItemsAdder Version

ItemsAdder version 3.6.0

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-669

### LoneLibs Version

LoneLibs version 1.0.27

**Comment by LoneDev6** [comment]
Thanks, i implemented that in the upcoming update.
Test code:
```java


    @EventHandler
    private void asd(ItemsAdderLoadDataEvent e)
    {
        System.out.println(" ");

        System.out.println("CustomFurniture:");
        for (String s : CustomFurniture.getNamespacedIdsInRegistry())
        {
            System.out.println(s);
        }

        System.out.println(" ");
        System.out.println(" ");
        System.out.println("CustomStack:");
        for (String s : CustomStack.getNamespacedIdsInRegistry())
        {
            System.out.println(s);
        }
        System.out.println(" ");
    }
```
