### ISSUE TITLE
external-host does not work correctly

### ISSUE THREAD

**Issue by ciliomine** [PluginBugs/Issues-ItemsAdder#3106]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I set up ItemsAdder in 2 servers:

Lobby and survival (bungue)

In survival I set self-host
In lobby I set external host and http://ip:8163/generated.zip

when you dont have the server-resource pack downloaded in your appdata folder
You join at the lobby and it download the last version from the survival correctly
but once you download the pack it is never updated again, it just loads it from your appdata folder, doesn't matter if you are updating it with more textures in spawn, it doesn't detect it.

I also tried a thousand ways and with bunguepackfix but nothing, the plugin loads in the bungue but it doesn't seem to do anything

### Steps to reproduce the issue

simply when you are updating in your main and you do iazip it will download it again to the people, how it works with normal selfhost

### Server version

lobby paper 1.16
survival 1.19.2

### ItemsAdder Version

3.6.1

### ProtocolLib Version

5.0.0

### LoneLibs Version

1.0.27

**Comment by LoneDev6** [comment]
Are you using bungeepackfix?
Anyway you should put the complete link with also the # part in your external host property.
Example: `http://127.0.0.1:8163/generated.zip#aa9a6c1dbe99e2a1ca651396622924d034ff8405`
The # part changes each time you regenerate your resourcepack.
