### ISSUE TITLE
support breakNaturally 

### ISSUE THREAD

**Issue by h14turkiye** [PluginBugs/Issues-ItemsAdder#3108]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [ ] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

ahmetdinc

### What happened?

I'm using cdropcollector, I don't have the source code, but using jadx decompiler, I am certain that it uses block.breakNaturally(pickaxe). The problem is block is not breaked, drops note block (Im using real_note).

If by hand block drops the item I have set in the loot section.

### Steps to reproduce the issue

Use breaknaturally method on noteblock.

### Server version

Current: git-Plazma-"8348420" (MC: 1.20.1)*
Previous: git-Pufferfish-27 (MC: 1.20.1)
* You are running the latest version

### ItemsAdder Version

3.5.0b

### ProtocolLib Version

5.1.0-snapshot-660

### LoneLibs Version

1.10.25

### Error (optional)

```shell
no errors.
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: hyronic
loots:
  blocks:
    gem_ore:
      items:
        gem_ingot:
          chance: 100
          item: hyronic:gem_ingot
          max_amount: 1
          min_amount: 1
      type: hyronic:gem_ore

,
info:
  namespace: hyronic
items:
  gem_ingot:
    display_name: Mücevher Külçesi
    resource:
      generate: true
      material: PAPER
      model_id: 201
      textures:
      - custom/minerals/gem
  gem_ore:
    display_name: Mücevher Cevheri
    events:
      placed_block:
        break:
          drop_exp:
            chance: 100
            max_amount: 3
            min_amount: 0
    resource:
      generate: true
      material: PAPER
      model_id: 200
      textures:
      - custom/minerals/gem_ore
    specific_properties:
      block:
        break_tools_whitelist:
        - PICKAXE
        - pickaxe
        cancel_drop: true
        hardness: 1
        placed_model:
          type: REAL_NOTE
```

**Comment by LoneDev6** [comment]
They have to ask the developer to uses ItemsAdder API to break custom blocks instead.
https://itemsadder.devs.beer/developers/java-api

There seem to be no way to support the `breakNaturally` method as it doesn't trigger any event.

**Comment by h14turkiye** [comment]
```java
List<ItemStack> loot = customBlock.getLoot();
                                		customBlock.remove();
                                		Bukkit.getScheduler().runTaskLater(this.plugin, () -> {
                                			for(ItemStack dropitem : loot)
                                				block.getWorld().dropItem(block.getLocation(), dropitem);
                                		},2l);
                                                this.plugin.getRegionManager().updateLevel(block);
  ``` 
  This is working at removing and dropping the loot. But this was a generator, and after removing the block the generator doesnt get updated as it stays air.

**Comment by h14turkiye** [comment]
Removing and the drops work! There is a slight problem tho. This was used in an generator(blocktoevent) and it stays air. This is what i have tried so far:
```java
List<ItemStack> loot = customBlock.getLoot();
                                		customBlock.remove();
                                		Bukkit.getScheduler().runTaskLater(this.plugin, () -> {
                                			for(ItemStack dropitem : loot)
                                				block.getWorld().dropItem(block.getLocation(), dropitem);
                                		},2l);
                                		Bukkit.getScheduler().runTaskLater(this.plugin, () -> {
                                			block.getWorld().getBlockAt(block.getLocation()).setType(Material.AIR);
                                			block.breakNaturally(this.item);
                                            this.plugin.getRegionManager().updateLevel(block);
                                		},1l);
```
