### ISSUE TITLE
geyser and itemadder conflict

### ISSUE THREAD

**Issue by SrMonsterYT** [PluginBugs/Issues-ItemsAdder#3114]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

mauriciooficial

### What happened?

when i updated geyser to version 1.20.40 and now every time i try to enter the server which is java edition and has itemadder i get kicked out

### Steps to reproduce the issue

have 1 java edition server with itemadder, update geyser to the latest version 1.20.40

video: https://youtu.be/-_pQIiXVHwE

### Server version

Pufferfish version git-Pufferfish-27 (MC: 1.20.1)

### ItemsAdder Version

3.6.2-beta-r2

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### LoneLibs Version

1.0.27

### FULL server log

no error

### Error (optional)

```shell
no error console
```

**Comment by LoneDev6** [comment]
Provide your full server log

**Comment by SrMonsterYT** [comment]
> Provide your full server log

there is no error in it nothing, i just get kicked, i talked to geyser about it, some players said that the forcepack plugin has the option to ignore bedrock players, could you add that to the itemadder?

if you want the logs I can give them to you but I can assure you that there is nothing in them

**Comment by SrMonsterYT** [comment]
full logs: https://mclo.gs/YxGZiaW

I only changed the IP of the itemadder for security ok, but it's working perfectly the problem is only in the bedrock, but as you suggested to me to add the option to skip bedrock would be perfect.

one person's suggestion: https://prnt.sc/S79RwI5uDbt8

**Comment by LoneDev6** [comment]
> when i updated geyser to version 1.20.40

This means that it's a Geyser issue.
I need more info from its developers to check what they changed.

**Comment by SrMonsterYT** [comment]
> > when i updated geyser to version 1.20.40
> 
> This means that it's a Geyser issue. I need more info from its developers to check what they changed.
> 
> There is no setting to ignore Geyser players. Probably Geyser needs to stop sending resourcepack packets to Bedrock players as they can't receive Java resourcepacks.

geyser players have 1 dot in front of their name or some prefix so yes just add an option that ignores nicknames with dots at the beginning

**Comment by LoneDev6** [comment]
Geyser needs to stop sending resourcepack packets to Bedrock players as they can't receive Java resourcepacks, I wonder why they send invalid resourcepacks to Bedrock players instead of cancelling the sending.
