### ISSUE TITLE
Itemsadder cant merge perfectly ModelEngine's models and create texture superposition

### ISSUE THREAD

**Issue by 3zekielZorr** [PluginBugs/Issues-ItemsAdder#3115]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

cleedthefat

### What happened?

I tried to create a ressourcepack from itemsadder and modelengine content with the Itemsadder pack generator feature. But like 50% of the models don't have their appereance, when i try to load the generated pack from modelengine they all work perfectly. I use a lot of custom model with my team because we're creating an RPG game server. I think that the problem is that we can't increase what we call in modelengine config the "compartment size" and itemsadder uses a default one which is making the result like the screen:

### Steps to reproduce the issue

Have a lot of Itemsadder and Modelengine content (Note that i use MEG3)
Verify that the ressource pack folder is automatically merged by checking on the IA config file
Type /iazip
Put the ressourcepack
Try to do some /meg disguise until you find something like the screen
Cry because your life is made of a lot of nonsences
Ask the LoneDev god if he can save us

### Server version

Current: git-Purpur-2062 (MC: 1.20.1)*

You are running the latest version

### ItemsAdder Version

3.6.2-beta-r2

### ProtocolLib Version

5.1.1-SNAPSHOT-668

### LoneLibs Version

1.0.27

### FULL server log

It's not a server side error i don't have any error when starting the server

### Screenshots/Videos (you can drag and drop files or paste links)

A working model
![277842899-a33a7778-8c95-474d-b28f-ddff6c47dd62](https://github.com/PluginBugs/Issues-ItemsAdder/assets/149005269/136c34e6-a4c1-49

A depression-maker non working model
![277843217-9ce682f3-e861-4af5-98ff-66767412a8a0](https://github.com/PluginBugs/Issues-ItemsAdder/assets/149005269/e1638550-2ed8-40e0-89c5-a9a2ad35b168)
31-9093-1c781d03eaba)

And this, is Elon... Hum, seriously this is my model number, i have a lot of tiny and huge creations (also bought models lol) i need them to all work perfectly...
![277842979-1433dd28-6482-4eee-a0fe-c873dcdd05b7](https://github.com/PluginBugs/Issues-ItemsAdder/assets/149005269/8defbec9-5b35-4e24-a192-31cbc168d88b)

NB: 
**In the modelengine config, all my models seems to work when i set the compartment-Size to 1000000**
So i think it might work if i was able to set a compartment-size option in the itemsadder config file

**Comment by LoneDev6** [comment]
ModelEngine 3 and 4 were tested and working correctly with ItemsAdder.
Did you read the tutorial? https://itemsadder.devs.beer/compatibility-with-other-plugins/compatible/modelengine

**Comment by 3zekielZorr** [comment]
Hey! Yes i've setup both plugin perfectly like i was supposed to.

What i am saying with the "compartment-size" is that in modelengine, increase this value from X number to 1000000 allow me to have a fully working ressourcepack (modelengine only !) So i supposed that the problem was that ItemsAdder uses a default value for this compartment-size variable and because this default value is not high enough, then the ressourcepack generated by ItemsAdder dont' work completly.

**Comment by LoneDev6** [comment]
What is "compartment-size"? It's not something available in ItemsAdder nor Minecraft itself.

**Comment by 3zekielZorr** [comment]
the plugin is not directly influenced - it influences the resourcepack, specifically the custommodeldata that each bone has. Making that value bigger increases the "spacing" between values under some circumstances, so it's good to not make the rs implode in short

**Comment by 3zekielZorr** [comment]
Thanks to modelengine support for giving me this information

**Comment by LoneDev6** [comment]
I still don't understand what you're talking about since it is nothing related to ItemsAdder itself and ModelEngine was tested and working correctly on multiple environments.
Please take your time to explain or give this Github page link to the ModelEngine support team so we can discuss and find a solution for the issue.

Have a nice week and thanks for the patience.
