### ISSUE TITLE
Missing texture/model

### ISSUE THREAD

**Issue by DarrienZ** [PluginBugs/Issues-ItemsAdder#3116]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Darrien #0022

### What happened?

Texture worked inside the server

### Steps to reproduce the issue

I don't know how to explain. Here the elytra files
[elytras.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/13170834/elytras.zip)

### Server version

Current: git-Purpur-2062 (MC: 1.20.1)*

### ItemsAdder Version

ItemsAdder version 3.6.2-beta-r2

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-669

### LoneLibs Version

LoneLibs version 1.0.27

### FULL server log

https://pastebin.com/Twq3UJ4d

### Error (optional)

```shell
https://pastebin.com/BRCZ5ZAk
```

### Problematic items yml configuration file (optional)
```shell
https://pastebin.com/2XUM8nKh
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/108975040/e97bbb90-f893-45d7-b212-f3535aa2ebe2)

**Comment by DarrienZ** [comment]
The Elytra texture is functioning, but there's a problem in the console where it says the Elytra is missing its texture and model.

```
generate-custom-armors-textures:
  vanilla_1_17: true
  optifine: true
```

**Comment by DarrienZ** [comment]
**Optifine installed** ✅
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/108975040/b1e4e582-128c-4b6c-a853-75e9a8b836df)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/108975040/824d7875-99ce-46a2-a511-eb35a2b7be2c)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/108975040/87719530-5cba-49a2-bd21-882dd34f3b3f)

**Comment by LoneDev6** [comment]
I am not its author nor I have control over his pack, please contact its author to get it fixed.
Thanks for understanding!
