### ISSUE TITLE
Lines around the chat when using &k format in chat

### ISSUE THREAD

**Issue by naikyys** [PluginBugs/Issues-ItemsAdder#3130]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

When I use &k in chat, a bunch of weird lines start appearing around the chat. When I put the itemsadder away it wasn't there. So I'm sure ItemsAdder is the problem here. This problem is also with default configuration without any textures.

https://github.com/PluginBugs/Issues-ItemsAdder/assets/67881641/3e39f9b3-82d6-43bf-aaeb-ba61d905a5d9

### Steps to reproduce the issue

1. Join the server
2. Use &k format with any chat plugin'
3. Type some text after the &k
4. For example &kasdjkhdaadsjokas
5. Spam a little bit so you can see it more clearly
6. You can see now bunch of lines around the chat.

### Server version

Current: git-Purpur-1632 (MC: 1.18.2)*
Previous: git-Paper-386 (MC: 1.18.2)
* You are running the latest version

### ItemsAdder Version

ItemsAdder 3.6.2-beta-r2

### ProtocolLib Version

ProtocolLib version 5.1.0

### LoneLibs Version

LoneLibs version 1.0.27

### FULL server log

Not needed

**Comment by notsuntm** [comment]
![image_2023-11-03_054915915](https://github.com/PluginBugs/Issues-ItemsAdder/assets/63513116/0b4bb43d-d238-4149-b27b-ee180d7bec98)

It appears to be the new cooldown indicators.
