### ISSUE TITLE
Broken armor textures optifine

### ISSUE THREAD

**Issue by gabriel262m** [PluginBugs/Issues-ItemsAdder#3132]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

gabrielc_26

### What happened?

My problem is the following.
After several hours of turning on the server, when reloading the textures, the armor stops having its textures, I don't think it is a configuration, just restarting the server and reloading itemsadder again, they are fixed, this has happened to me since the last version from itemsadder and it really is problematic

### Steps to reproduce the issue

Wait 6-8 hours, have previous charged armors whit custom textures
/iareload
/iazip
starts to get textures broken but whit their default colors

### Server version

This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)

### ItemsAdder Version

[23:49:43 INFO]: ItemsAdder version 3.6.2-beta-r2
[23:49:43 INFO]: Customized Minecraft without client mods!
[23:49:43 INFO]: Website: devs.beer
[23:49:43 INFO]: Author: LoneDev

### ProtocolLib Version

[23:50:02 INFO]: ProtocolLib version 5.0.0
[23:50:02 INFO]: Provides read/write access to the Minecraft protocol.
[23:50:02 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[23:50:14 INFO]: LoneLibs version 1.0.27
[23:50:14 INFO]: Collection of libs used by my plugins
[23:50:14 INFO]: Authors: LoneDev and others

### FULL server log

cant upload full server log, i got some errors using mythicmobs so is so high, i will upload it to another place for check
https://www.dropbox.com/scl/fi/q5vqq1y8q6670qz8lfcep/latest-3.log?rlkey=796bwqdgumedr45habpgwuz1n&dl=0

### Error (optional)

```shell
https://pastebin.com/ejhSYHUp
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: kingdrag
armors_rendering:
  iridio:
    color: "#9438d6"
    layer_1: armas-armaduras/armaduras/iridium_armor_layer_1
    layer_2: armas-armaduras/armaduras/iridium_armor_layer_2
    use_color: false
  malaquita:
    color: "#32c79f"
    layer_1: armas-armaduras/armaduras/malachite_armor_layer_1
    layer_2: armas-armaduras/armaduras/malachite_armor_layer_2
    use_color: false
  ambar:
    color: "#e8a438"
    layer_1: armas-armaduras/armaduras/amber_armor_layer_1
    layer_2: armas-armaduras/armaduras/amber_armor_layer_2
    use_color: false
  amatista:
    color: "#c947bc"
    layer_1: armas-armaduras/armaduras/amethyst_armor_layer_1
    layer_2: armas-armaduras/armaduras/amethyst_armor_layer_2
    use_color: false
  mythril:
    color: "#262aab"
    layer_1: armas-armaduras/armaduras/mythril_armor_layer_1
    layer_2: armas-armaduras/armaduras/mythril_armor_layer_2
    use_color: false
  platino:
    color: "#9ddde0"
    layer_1: armas-armaduras/armaduras/silver_armor_layer_1
    layer_2: armas-armaduras/armaduras/silver_armor_layer_2
    use_color: false
  jade:
    color: "#33d12e"
    layer_1: armas-armaduras/armaduras/jade_armor_layer_1
    layer_2: armas-armaduras/armaduras/jade_armor_layer_2
    use_color: false
  ruby:
    color: "#fc031e"
    layer_1: armas-armaduras/armaduras/ruby_armor_layer_1
    layer_2: armas-armaduras/armaduras/ruby_armor_layer_2
    use_color: false
  tenebroso:
    color: '#221e26'
    layer_1: armas-armaduras/armaduras/tenebroso_layer_1
    layer_2: armas-armaduras/armaduras/tenebroso_layer_2
    use_color: false
  glacia:
    color: "#8cd6eb"
    layer_1: armas-armaduras/armaduras/layer_1
    layer_2: armas-armaduras/armaduras/layer_2
    use_color: false
items:
  casco_iridio:
    display_name: "Casco de Iridio"
    resource:
      generate: true
#      model_id: 27
      textures:
      - armas-armaduras/armaduras/iridium_helmet.png
      - armas-armaduras/armaduras/iridium_helmet.png
    durability:
      max_custom_durability: 407
    specific_properties:
      armor:
        slot: head
        custom_armor: iridio
    attribute_modifiers:
      head:
        armor: 4
        knockback_resistance: 0.1
        armorToughness: 3
  peto_iridio:
    display_name: "Peto de Iridio"
    resource:
      generate: true
#      model_id: 27
      textures:
      - armas-armaduras/armaduras/iridium_chestplate.png
      - armas-armaduras/armaduras/iridium_chestplate.png
    durability:
      max_custom_durability: 592
    specific_properties:
      armor:
        slot: chest
        custom_armor: iridio
    attribute_modifiers:
      chest:
        armor: 9
        knockback_resistance: 0.1
        armorToughness: 3
  pantalones_iridio:
    display_name: "Pantalones de Iridio"
    resource:
      generate: true
#      model_id: 27
      textures:
      - armas-armaduras/armaduras/iridium_leggings.png
      - armas-armaduras/armaduras/iridium_leggings.png
    durability:
      max_custom_durability: 555
    specific_properties:
      armor:
        slot: legs
        custom_armor: iridio
    attribute_modifiers:
      legs:
        armor: 7
        knockback_resistance: 0.1
        armorToughness: 3
  botas_iridio:
    display_name: "Botas de Iridio"
    resource:
      generate: true
#      model_id: 27
      textures:
      - armas-armaduras/armaduras/iridium_boots.png
      - armas-armaduras/armaduras/iridium_boots.png
    durability:
      max_custom_durability: 481
    specific_properties:
      armor:
        slot: FEET
        custom_armor: iridio
    attribute_modifiers:
      feet:
        armor: 4
        knockback_resistance: 0.1
        armorToughness: 3
##################################################################################################################################################################################
  casco_malaquita:
    display_name: "Casco de Malaquita"
    resource:
      generate: true
#      model_id: 28
      textures:
      - armas-armaduras/armaduras/malachite_helmet.png
      - armas-armaduras/armaduras/malachite_helmet.png
    durability:
      max_custom_durability: 407
    specific_properties:
      armor:
        slot: head
        custom_armor: malaquita
    attribute_modifiers:
      head:
        armor: 7
        knockback_resistance: 0.1
        armorToughness: 3
  peto_malaquita:
    display_name: "Peto de Malaquita"
    resource:
      generate: true
#      model_id: 28
      textures:
      - armas-armaduras/armaduras/malachite_chestplate.png
      - armas-armaduras/armaduras/malachite_chestplate.png
    durability:
      max_custom_durability: 592
    specific_properties:
      armor:
        slot: chest
        custom_armor: malaquita
    attribute_modifiers:
      chest:
        armor: 12
        knockback_resistance: 0.1
        armorToughness: 3
  pantalones_malaquita:
    display_name: "Pantalones de Malaquita"
    resource:
      generate: true
#      model_id: 28
      textures:
      - armas-armaduras/armaduras/malachite_leggings.png
      - armas-armaduras/armaduras/malachite_leggings.png
    durability:
      max_custom_durability: 555
    specific_properties:
      armor:
        slot: legs
        custom_armor: malaquita
    attribute_modifiers:
      legs:
        armor: 10
        knockback_resistance: 0.1
        armorToughness: 3
  botas_malaquita:
    display_name: "Botas de Malaquita"
    resource:
      generate: true
#      model_id: 28
      textures:
      - armas-armaduras/armaduras/malachite_boots.png
      - armas-armaduras/armaduras/malachite_boots.png
    durability:
      max_custom_durability: 481
    specific_properties:
      armor:
        slot: FEET
        custom_armor: malaquita
    attribute_modifiers:
      feet:
        armor: 7
        knockback_resistance: 0.1
        armorToughness: 3
##################################################################################################################################################################################
  casco_platino:
    display_name: "Casco de Platino"
    resource:
      generate: true
#      model_id: 32
      textures:
      - armas-armaduras/armaduras/silver_helmet.png
      - armas-armaduras/armaduras/silver_helmet.png
    durability:
      max_custom_durability: 400
    specific_properties:
      armor:
        slot: head
        custom_armor: platino
    attribute_modifiers:
      head:
        armor: 6
        knockback_resistance: 0.1
        armorToughness: 2.5
  peto_platino:
    display_name: "Peto de Platino"
    resource:
      generate: true
#      model_id: 32
      textures:
      - armas-armaduras/armaduras/silver_chestplate.png
      - armas-armaduras/armaduras/silver_chestplate.png
    durability:
      max_custom_durability: 595
    specific_properties:
      armor:
        slot: chest
        custom_armor: platino
    attribute_modifiers:
      chest:
        armor: 11
        knockback_resistance: 0.1
        armorToughness: 2.5
  pantalones_platino:
    display_name: "Pantalones de Platino"
    resource:
      generate: true
#      model_id: 32
      textures:
      - armas-armaduras/armaduras/silver_leggings.png
      - armas-armaduras/armaduras/silver_leggings.png
    durability:
      max_custom_durability: 560
    specific_properties:
      armor:
        slot: legs
        custom_armor: platino
    attribute_modifiers:
      legs:
        armor: 9
        knockback_resistance: 0.1
        armorToughness: 2.5
  botas_platino:
    display_name: "Botas de Platino"
    resource:
      generate: true
#      model_id: 32
      textures:
      - armas-armaduras/armaduras/silver_boots.png
      - armas-armaduras/armaduras/silver_boots.png
    durability:
      max_custom_durability: 490
    specific_properties:
      armor:
        slot: FEET
        custom_armor: platino
    attribute_modifiers:
      feet:
        armor: 6
        knockback_resistance: 0.1
        armorToughness: 2.5
##################################################################################################################################################################################
  casco_ambar:
    display_name: "Casco de Ambar"
    resource:
      generate: true
#      model_id: 29
      textures:
      - armas-armaduras/armaduras/amber_helmet.png
      - armas-armaduras/armaduras/amber_helmet.png
    durability:
      max_custom_durability: 363
    specific_properties:
      armor:
        slot: head
        custom_armor: ambar
    attribute_modifiers:
      head:
        armor: 3
        armorToughness: 2.4
  peto_ambar:
    display_name: "Peto de Ambar"
    resource:
      generate: true
#      model_id: 29
      textures:
      - armas-armaduras/armaduras/amber_chestplate.png
      - armas-armaduras/armaduras/amber_chestplate.png
    durability:
      max_custom_durability: 528
    specific_properties:
      armor:
        slot: chest
        custom_armor: ambar
    attribute_modifiers:
      chest:
        armor: 8
        armorToughness: 2.4
  pantalones_ambar:
    display_name: "Pantalones de Ambar"
    resource:
      generate: true
#      model_id: 29
      textures:
      - armas-armaduras/armaduras/amber_leggings.png
      - armas-armaduras/armaduras/amber_leggings.png
    durability:
      max_custom_durability: 495
    specific_properties:
      armor:
        slot: legs
        custom_armor: ambar
    attribute_modifiers:
      legs:
        armor: 6
        armorToughness: 2.4
  botas_ambar:
    display_name: "Amber Boots"
    resource:
      generate: true
#      model_id: 29
      textures:
      - armas-armaduras/armaduras/amber_boots.png
      - armas-armaduras/armaduras/amber_boots.png
    durability:
      max_custom_durability: 429
    specific_properties:
      armor:
        slot: FEET
        custom_armor: ambar
    attribute_modifiers:
      feet:
        armor: 3
        armorToughness: 2.4
##################################################################################################################################################################################
  casco_amatista:
    display_name: "Casco de Diamantina"
    resource:
      generate: true
#      model_id: 30
      textures:
      - armas-armaduras/armaduras/amethyst_helmet.png
      - armas-armaduras/armaduras/amethyst_helmet.png
    durability:
      max_custom_durability: 450
    specific_properties:
      armor:
        slot: head
        custom_armor: amatista
    attribute_modifiers:
      head:
        armor: 7
        knockback_resistance: 0.1
        armorToughness: 3
  peto_amatista:
    display_name: "Peto de Diamantina"
    resource:
      generate: true
#      model_id: 30
      textures:
      - armas-armaduras/armaduras/amethyst_chestplate.png
      - armas-armaduras/armaduras/amethyst_chestplate.png
    durability:
      max_custom_durability: 650
    specific_properties:
      armor:
        slot: chest
        custom_armor: amatista
    attribute_modifiers:
      chest:
        armor: 12
        knockback_resistance: 0.1
        armorToughness: 3
  pantalones_amatista:
    display_name: "Pantalones de Diamantina"
    resource:
      generate: true
#      model_id: 30
      textures:
      - armas-armaduras/armaduras/amethyst_leggings.png
      - armas-armaduras/armaduras/amethyst_leggings.png
    durability:
      max_custom_durability: 600
    specific_properties:
      armor:
        slot: legs
        custom_armor: amatista
    attribute_modifiers:
      legs:
        armor: 10
        knockback_resistance: 0.1
        armorToughness: 3
  botas_amatista:
    display_name: "Botas de Diamantina"
    resource:
      generate: true
#      model_id: 30
      textures:
      - armas-armaduras/armaduras/amethyst_boots.png
      - armas-armaduras/armaduras/amethyst_boots.png
    durability:
      max_custom_durability: 500
    specific_properties:
      armor:
        slot: FEET
        custom_armor: amatista
    attribute_modifiers:
      feet:
        armor: 7
        knockback_resistance: 0.1
        armorToughness: 3
##################################################################################################################################################################################
  casco_mythril:
    display_name: "Casco de Mythril"
    resource:
      generate: true
#      model_id: 31
      textures:
      - armas-armaduras/armaduras/mythril_helmet.png
      - armas-armaduras/armaduras/mythril_helmet.png
    durability:
      max_custom_durability: 363
    specific_properties:
      armor:
        slot: head
        custom_armor: mythril
    attribute_modifiers:
      head:
        armor: 3
        armorToughness: 2.5
  peto_mythril:
    display_name: "Peto de Mythril"
    resource:
      generate: true
#      model_id: 31
      textures:
      - armas-armaduras/armaduras/mythril_chestplate.png
      - armas-armaduras/armaduras/mythril_chestplate.png
    durability:
      max_custom_durability: 528
    specific_properties:
      armor:
        slot: chest
        custom_armor: mythril
    attribute_modifiers:
      chest:
        armor: 8
        armorToughness: 2.5
  pantalones_mythril:
    display_name: "Pantalones de Mythril"
    resource:
      generate: true
#      model_id: 31
      textures:
      - armas-armaduras/armaduras/mythril_leggings.png
      - armas-armaduras/armaduras/mythril_leggings.png
    durability:
      max_custom_durability: 495
    specific_properties:
      armor:
        slot: legs
        custom_armor: mythril
    attribute_modifiers:
      legs:
        armor: 6
        armorToughness: 2.5
  botas_mythril:
    display_name: "Botas de Mythril"
    resource:
      generate: true
#      model_id: 31
      textures:
      - armas-armaduras/armaduras/mythril_boots.png
      - armas-armaduras/armaduras/mythril_boots.png
    durability:
      max_custom_durability: 429
    specific_properties:
      armor:
        slot: FEET
        custom_armor: mythril
    attribute_modifiers:
      feet:
        armor: 3
        armorToughness: 2.5
##################################################################################################################################################################################
  casco_jade:
    display_name: "Casco de Jade"
    resource:
      generate: true
#      model_id: 33
      textures:
      - armas-armaduras/armaduras/jade_helmet.png
      - armas-armaduras/armaduras/jade_helmet.png
    durability:
      max_custom_durability: 363
    specific_properties:
      armor:
        slot: head
        custom_armor: jade
    attribute_modifiers:
      head:
        armor: 3
        armorToughness: 2.3
  peto_jade:
    display_name: "Peto de Jade"
    resource:
      generate: true
#      model_id: 33
      textures:
      - armas-armaduras/armaduras/jade_chestplate.png
      - armas-armaduras/armaduras/jade_chestplate.png
    durability:
      max_custom_durability: 528
    specific_properties:
      armor:
        slot: chest
        custom_armor: jade
    attribute_modifiers:
      chest:
        armor: 8
        armorToughness: 2.3
  pantalones_jade:
    display_name: "Jade Leggings"
    resource:
      generate: true
#      model_id: 33
      textures:
      - armas-armaduras/armaduras/jade_leggings.png
      - armas-armaduras/armaduras/jade_leggings.png
    durability:
      max_custom_durability: 495
    specific_properties:
      armor:
        slot: legs
        custom_armor: jade
    attribute_modifiers:
      legs:
        armor: 6
        armorToughness: 2.3
  botas_jade:
    display_name: "Botas de Jade"
    resource:
      generate: true
#      model_id: 33
      textures:
      - armas-armaduras/armaduras/jade_boots.png
      - armas-armaduras/armaduras/jade_boots.png
    durability:
      max_custom_durability: 429
    specific_properties:
      armor:
        slot: FEET
        custom_armor: jade
    attribute_modifiers:
      feet:
        armor: 3
        armorToughness: 2.3
##################################################################################################################################################################################
  casco_ruby:
    display_name: "Casco de Ruby Antiguo"
    resource:
      generate: true
#      model_id: 34
      textures:
      - armas-armaduras/armaduras/ruby_helmet.png
      - armas-armaduras/armaduras/ruby_helmet.png
    durability:
      max_custom_durability: 400
    specific_properties:
      armor:
        slot: head
        custom_armor: ruby
    attribute_modifiers:
      head:
        armor: 3.5
        armorToughness: 2.6
  peto_ruby:
    display_name: "Peto de Ruby Antiguo"
    resource:
      generate: true
#      model_id: 34
      textures:
      - armas-armaduras/armaduras/ruby_chestplate.png
      - armas-armaduras/armaduras/ruby_chestplate.png
    durability:
      max_custom_durability: 550
    specific_properties:
      armor:
        slot: chest
        custom_armor: ruby
    attribute_modifiers:
      chest:
        armor: 8.5
        armorToughness: 2.6
  pantalones_ruby:
    display_name: "Pantalones de Ruby Antiguo"
    resource:
      generate: true
      textures:
      - armas-armaduras/armaduras/ruby_leggings.png
      - armas-armaduras/armaduras/ruby_leggings.png
    durability:
      max_custom_durability: 530
    specific_properties:
      armor:
        slot: legs
        custom_armor: ruby
    attribute_modifiers:
      legs:
        armor: 6.5
        armorToughness: 2.6
  botas_ruby:
    display_name: "Botas de Ruby Antiguo"
    resource:
      generate: true
#      model_id: 34
      textures:
      - armas-armaduras/armaduras/ruby_boots.png
      - armas-armaduras/armaduras/ruby_boots.png
    durability:
      max_custom_durability: 480
    specific_properties:
      armor:
        slot: FEET
        custom_armor: ruby
    attribute_modifiers:
      feet:
        armor: 3.5
        armorToughness: 3
##################################################################################################################################################################################
  casco_tenebroso:
    display_name: "Cabeza de Señor Oscuro"
    resource:
      material: PAPER
      generate: false
      model_path: armas-armaduras/armaduras/midnight_haunt_skull
    behaviours:
      hat: true
    attribute_modifiers:
      head:
        armor: 7
        knockback_resistance: 0.1
        armorToughness: 3
    durability:
      max_custom_durability: 500
  peto_tenebroso:
    display_name: 'Peto de Señor Oscuro'
    resource:
      generate: true
      textures:
      - armas-armaduras/armaduras/peto_tenebroso
    durability:
      max_custom_durability: 592
    specific_properties:
      armor:
        slot: chest
        custom_armor: tenebroso
    attribute_modifiers:
      chest:
        armor: 12
        knockback_resistance: 0.1
        armorToughness: 3
  pantalones_tenebrosos:
    display_name: '&fPantalones de Señor Oscuro'
    resource:
      generate: true
      textures:
      - armas-armaduras/armaduras/pantalones_tenebrosos
    durability:
      max_custom_durability: 555
    specific_properties:
      armor:
        slot: legs
        custom_armor: tenebroso
    attribute_modifiers:
      legs:
        armor: 10
        knockback_resistance: 0.1
        armorToughness: 3
  botas_tenebrosas:
    display_name: '&fBotas de Señor Oscuro'
    resource:
      generate: true
      textures:
      - armas-armaduras/armaduras/botas_tenebrosas
    durability:
      max_custom_durability: 481
    specific_properties:
      armor:
        slot: FEET
        custom_armor: tenebroso
    attribute_modifiers:
      feet:
        armor: 7
        knockback_resistance: 0.1
        armorToughness: 3
##################################################################################################################################################################################
  casco_gelido:
    display_name: "Casco Gelido"
    resource:
      generate: true
      textures:
      - armas-armaduras/armaduras/casco_gelido.png
      - armas-armaduras/armaduras/casco_gelido.png
    durability:
      max_custom_durability: 390
    specific_properties:
      armor:
        slot: head
        custom_armor: glacia
    attribute_modifiers:
      head:
        armor: 3.2
        knockback_resistance: 0.2
        armorToughness: 2.3
  peto_gelido:
    display_name: 'Peto Gelido'
    resource:
      generate: true
      textures:
      - armas-armaduras/armaduras/peto_gelido
    durability:
      max_custom_durability: 480
    specific_properties:
      armor:
        slot: chest
        custom_armor: glacia
    attribute_modifiers:
      chest:
        armor: 4.3
        knockback_resistance: 0.2
        armorToughness: 2.3
  pantalones_gelidos:
    display_name: '&fPantalones Gelidos'
    resource:
      generate: true
      textures:
      - armas-armaduras/armaduras/pantalones_gelidos
    durability:
      max_custom_durability: 430
    specific_properties:
      armor:
        slot: legs
        custom_armor: glacia
    attribute_modifiers:
      legs:
        armor: 3.8
        knockback_resistance: 0.2
        armorToughness: 2.3
  botas_gelidas:
    display_name: '&fBotas Gelidas'
    resource:
      generate: true
      textures:
      - armas-armaduras/armaduras/botas_gelidas
    durability:
      max_custom_durability: 380
    specific_properties:
      armor:
        slot: FEET
        custom_armor: glacia
    attribute_modifiers:
      feet:
        armor: 3.1
        knockback_resistance: 0.2
        armorToughness: 2.3
```

### Other files, you can drag and drop them here to upload. (optional)

metrics: true
update-checker: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
ignore-server-compatibility-check: false
resource-pack:
  hosting:
    no-host:
      enabled: false
    auto-external-host:
      enabled: false
    self-host:
      enabled: false
      server-ip: 104.224.55.2
      pack-port: 4758
    external-host:
      enabled: true
      url: https://www.dropbox.com/scl/fi/oc8qjdvz8xwtlb2g9awvl/generated.zip?rlkey=p5toq59s3vel39b66fnrt44ev&dl=0
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: true
  delay-ticks: 1
  notify-other-plugins-interfering: true
  title:
    enabled: true
  1_19_3_atlas_support: true
  fix_force_unicode_font_images: true
  protect-player:
    black-screen: true
    hide-hud: true
    cancel-movement: true
    lock-player: true
  command:
    usage-cooldown-seconds: 60
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip:
      protection_1: true
      protection_2: true
    compress-png-files: true
    compress-json-files: true
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    extract_internal_utility_assets: true
    contents-folders-priority:
    - vanilla
    - _iainternal
    merge_other_plugins_resourcepacks_folders:
    - ModelEngine/resource pack
  items:
    CustomModelData-starting-value:
      ALL: 10000
      DIAMOND: 11000
config_files:
  lang: en
  dictionaries-lang: en
  force-sync-loading: false
blocks:
  light-api: true
  fix-liquids-flow: true
  fix-floating-blocks: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire_enhancements:
    enable: true
    unlit_on_place: true
    allow_any_item: true
    drop_when_broken: false
  disable-REAL: false
  disable-REAL_NOTE: false
  disable-REAL_TRANSPARENT: false
  disable-REAL_WIRE: true
  disable-FIRE: false
  convert-vanilla-blocks:
    enabled: false
    only-new-chunks: true
  convert-legacy-ia-region-files: true
  remove-unused-palettes-on-region-save: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: true
  handle-wear-held-actions-on-unexpected-inventory-changes: true
liquids:
  enabled: true
huds:
  enabled: true
  force_color:
    enabled: false
    color: '#FFFFFF'
  hide_if_pack_not_accepted: true
loots:
  allow-loots-drop-from-spawners-using-silk-touch: true
mobs:
  disable-MOB-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
compatibility:
  worldguard:
    show_legacy_furniture_flags: false
font_images:
  replace-in-customitems-name-and-lore: true
  chat:
    enabled: true
    add-hover-suggestion: true
    tab-autocompletion_1_19_1_plus: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: false
    update-every-ticks: 3600
  player-display-name:
    enabled: true
    update-every-ticks: 1200
  iaimage-book:
    max-line-length: 18
    placeholder-font: minecraft:default
effects:
  hide-scoreboard-numbers: true
  text-effects:
    enabled: false
    replace-in-customitems-name-and-lore: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true
entities:
  max-furniture-vehicles-per-chunk: 30
  allow-removing-old-furnitures_2_3_11: false
  custom-entitites:
    enabled: true
    emotes: true
    interval-rendering-packets-ticks: 1
    expert_users:
      fast_packets_creation: true
      bundle_packets: false
      delay_packets: false
recipes:
  hide-vanilla-unrecognized-recipe-errors: true
  fix-packet-too-large-kick: false
  show-no-permission-popup-in-recipebook: false
  show-no-permission-chat-message: true
  crafting:
    enabled: true
  cooking:
    enabled: true
  anvil:
    enabled: true
  smithing:
    enabled: true
  custom-recipes:
    unlock:
      all-on-join: false
      on-pickup:
        any: true
        ingredients: true
      on-item-click:
        any: true
        ingredients: true
  remove-vanilla-recipes:
    enabled: true
    list:
      DIAMOND_SWORD: false
      IRON_INGOT: false
debug:
  benchmark: false
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-recipes-unknown-item: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save-load:
      enabled: false
      min-ms: 0
    log-mined-unknown-blocks: true
    log-convert-vanilla-blocks: false
    log-fix-bugged-blocks: false
    log-unusual-block-break: false
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
cooldown_bars:
  enabled: true
  refresh_ticks: 1
  bossbar:
    color: WHITE
    style: SOLID

**Comment by LoneDev6** [comment]
> After several hours of turning on the server, when reloading the textures, the armor stops having its textures

Are you sure it's related to that?
This is very strange, armors won't lose their texture on their own. Maybe it's a client issue? I tested that and I cannot reproduce the issue.
Also try removing some other plugins.

Anyway there is an issue with the itemsadder world region files.
This is probably caused by the fact that your server was shut down or killed and itemsadder couldn't save files correctly.
You should delete the corrupted region files (make a backup before doing that).
`/home/container/isla2/itemsadder`

Also fix your MythicMobs issues, your log is huge and might be the cause of the various strange issues you're facing.

NOTE: next time post your long configurations as file not text, thanks!

**Comment by gabriel262m** [comment]
Lone thanks for reply me, i can tell that this issue is recently, more especific, last beta version on spigot, never have this problem before, is like a memory leak issue, in the console says that not enought space in device for save png, so it could be the problem?Also the region "isla2" is also recent added whit that i mean 3 days, and i have this issue for more than 3 weeks

My client is not edited, i dont have weird plugins as u can see in logs, theres no other plugin adding texture more than modelengine and not for armors. This just happen when the server have 6-8 hours online, if i restart the server i got this fixed, i talk whit my host (bloomhost) and i have more than enought ram and memory, so i really dont know where to start now...i gona try your recomendations for try to fix something but as i told u in this message, this errors are recent and the armor problem is 3 weeks old as low.

**Comment by gabriel262m** [comment]
[Uploading latest (2).log…]()

**Comment by gabriel262m** [comment]
``
[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/13273185/latest.log)

**Comment by LoneDev6** [comment]
Fix also safarinet issues:
> [12:35:24] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to SafariNet v1.15.52-SNAPSHOT
com.google.gson.JsonIOException: Abstract classes can't be instantiated! Register an InstanceCreator or a TypeAdapter for this type. Class name: io.lumine.mythic.core.skills.variables.Variable

> Caused by: java.io.IOException: No space left on device

You have no more space on disk it seems.
This causes tons of unpredictable issues for many plugins because they can't save data.

**Comment by gabriel262m** [comment]
Lone but i have enought space as i comment in last reply, my hosting are checking and yeah i have enought space, maybe gonna try talk whit them again

**Comment by notsuntm** [comment]
It is worth mentioning even though you have a lot of space, you max out on RAM from the picture you have shared on discord.
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/63513116/b831e5a7-848d-4aee-b0f9-7fc0946948d7)

**Comment by LoneDev6** [comment]
It probably is related to ram then, it might be related to the extremely long logs.
Anyway reading online it seems it might have to do with the temp folder of your system which gets filled and has no more space.
https://stackoverflow.com/questions/25707784/why-does-a-job-fail-with-no-space-left-on-device-but-df-says-otherwise
It might be unrelated though.

Please note that I've never received any complain about this issue, it's the first time in years, so there is something wrong on the server and I'm sure it's easy to fix, we just need to find the cause.
