### ISSUE TITLE
Furniture cannot be destroyed

### ISSUE THREAD

**Issue by HoneyBearc** [PluginBugs/Issues-ItemsAdder#3136]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

honeybearc

### What happened?

Furniture cannot be destroyed after being placed
Install MythicMobsPremium-5.4.4-SNAPSHOT Build 4819, This problem arises
video: [https://www.veed.io/view/54f45d5e-27a5-4c09-afd8-7cde0cc4cff5?panel=share&sharingWidget=true](url)

### Steps to reproduce the issue

video: [https://www.veed.io/view/54f45d5e-27a5-4c09-afd8-7cde0cc4cff5?panel=share&sharingWidget=true](url)

### Server version

This server is running Paper version git-Paper-280 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 4675152)
You are running the latest version
Previous version: git-Paper-17 (MC: 1.20)

### ItemsAdder Version

ItemsAdder_3.6.2-beta-r2

### ProtocolLib Version

ProtocolLib 5.1.1-SNAPSHOT-673

### LoneLibs Version

LoneLibs 1.0.27

**Comment by GeneralSarcasam** [comment]
Just wanted to add to this that I am experiencing the same issue and tried out some different versions of ItemsAdder. The issue for me began with version 3.6.0. Using the same version for ProtocolLib and LoneLibs as above.

**Comment by LoneDev6** [comment]
It seems to be related to Mythicmobs, maybe they are cancelling the removal somehow?

**Comment by HoneyBearc** [comment]
In this version MythicMobs-5.4.1 there is no problem
But using MythicMobs-5.4.4-SNAPSHOT will cause problems

**Comment by LoneDev6** [comment]
Seems an issue related to MythicMobs then.

Their team wasn't collaborative at all during the past years so it surely will be a waste of time trying to deal with them to collaborate and find the cause of the issue, but you should try to contact them to make them check if they changed anything between these updates that could have caused this issue to start happening.

**Comment by HoneyBearc** [comment]
This issue can be closed. MythicMobs has processed it and the fix is ​​complete...

**Comment by LoneDev6** [comment]
Perfect, thanks!
If you have any details about that fix please share it here so that I can have it for archive purposes in case it happens again in the future.

**Comment by HoneyBearc** [comment]
![1700055188718](https://github.com/PluginBugs/Issues-ItemsAdder/assets/42526263/6b41a59f-dc23-45e3-bb40-484def23cc18)

**Comment by LoneDev6** [comment]
Thanks a lot! <3
