### ISSUE TITLE
Non-materialized black blocks & Texture pack

### ISSUE THREAD

**Issue by Snow123159** [PluginBugs/Issues-ItemsAdder#3141]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

snowtha

### What happened?

Hello, 

We carried out a migration on our Minecraft server between the Oraxen and Itemsadder plugins. The migration went well and we had no apparent errors (console, plugin itself...). However, we were able to notice some bugs and the plugin documentation and the bugs already dealt with did not allow us to determine where our various problems were coming from.

The first problem concerns non-materialized black blocks that some players may see appear when connecting to the server. The blocks are temporary and disappear quickly but it is still disruptive.

Our second problem concerns loading the texture pack (iazip). Indeed, the server restarts automatically in the morning and during this restart, the texture pack is not taken into account in the game and we must manually use the /iazip command on each restart.

We are counting on your professionalism to enlighten us on these various problems in order to improve the quality of the services we offer through your plugin.

Thanking you in advance for the help you will give us.

### Steps to reproduce the issue

1. Automatic restart of server infrastructures.
2. Having to manually use the command to recover the texture pack which did not load with reboot.
3. Connect to the server to temporarily see unmaterialized black blocks appear.

### Server version

[13:35:38 INFO]: Current: git-Purpur-1982 (MC: 1.19.4)*
Previous: git-Purpur-1708 (MC: 1.19)

### ItemsAdder Version

Version: 3.6.2-beta-r2

### ProtocolLib Version

ProtocolLib v5.1.0-SNAPSHOT-649

### LoneLibs Version

LoneLibs 1.0.27

### FULL server log

N/A (No error)

### Error (optional)

```shell
N/A (No error)
```

### Problematic items yml configuration file (optional)

```shell
N/A (It's not an item)
```

### Screenshots/Videos (you can drag and drop files or paste links)

![2023-11-10_17 02 58](https://github.com/PluginBugs/Issues-ItemsAdder/assets/80066749/b105c65a-d738-4012-801d-818bf47b923a)
![2023-11-10_17 04 38](https://github.com/PluginBugs/Issues-ItemsAdder/assets/80066749/fa152c82-f2ce-49e0-923d-120e43dd7d53)
![2023-11-10_17 02 51](https://github.com/PluginBugs/Issues-ItemsAdder/assets/80066749/e74519ee-ddae-42e6-bf8e-cdaa971b026d)

**Comment by LoneDev6** [comment]
> The first problem concerns non-materialized black blocks that some players may see appear when connecting to the server. The blocks are temporary and disappear quickly but it is still disruptive.

Strange, I think it's the client mod which causes the black screen not to disappear after resourcepack installation is complete, so please disable it.

```yml
  protect-player:
    black-screen: false
```

> Our second problem concerns loading the texture pack (iazip). Indeed, the server restarts automatically in the morning and during this restart, the texture pack is not taken into account in the game and we must manually use the /iazip command on each restart.

This is strange, I don't see how it has to do with the restart as the plugin will work fine after restarts.
There is something wrong here, probably some plugin interfering? Can you please elaborate more what you mean by: "the texture pack is not taken into account in the game"



> We are counting on your professionalism to enlighten us on these various problems in order to improve the quality of the services we offer through your plugin.

Thanks a lot for your trust, I do my best.

**Comment by Snow123159** [comment]
> Strange, I think it's the client mod which causes the black screen not to disappear after resourcepack installation is complete, so please disable it. 

This seems to work. Thank you so much.

> This is strange, I don't see how it has to do with the restart as the plugin will work fine after restarts.
There is something wrong here, probably some plugin interfering? Can you please elaborate more what you mean by: "the texture pack is not taken into account in the game"

Concerning the texture pack, it seems that it is a problem with the font-images. Indeed, the items appear correctly but not the font images.

Here is an extract from our logs relating to the use of the plugin.

[logs itemsadder.txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/13400454/logs.itemsadder.txt)

Thanking you in advance for the help you will give us.

**Comment by LoneDev6** [comment]
No problem!
Please read here to find out the cause of font images not loading.
https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown

**Comment by LoneDev6** [comment]
> Concerning the texture pack, it seems that it is a problem with the font-images. Indeed, the items appear correctly but not the font images.

Provide screenshots of the issue.

**Comment by Snow123159** [comment]
Up

**Comment by Snow123159** [comment]
Up

**Comment by LoneDev6** [comment]
Did you read the tutorial to identify why these textures are not loading?
https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown

About the black box, disable protection in config.yml of itemsadder.
`black-screen: false`
