### ISSUE TITLE
bug report - itemsadder when i put block

### ISSUE THREAD

**Issue by IlayX5G** [PluginBugs/Issues-ItemsAdder#3152]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

wolfrizon

### What happened?

When I put a block it seems to me something strange on the screen. (title)

### Steps to reproduce the issue

1. i put block
2. shows me something strange on the screen. (title)

### Server version

the server is running paper version git-paper-"33bec7f" (MC: 1.20.1)

### ItemsAdder Version

itemsadder version 3.5.0c-r4

### ProtocolLib Version

ProtocolLib version 5.0.0

### LoneLibs Version

LoneLibs verseion 1.0.25

### FULL server log

[latest (1).log](https://github.com/PluginBugs/Issues-ItemsAdder/files/13377594/latest.1.log)

### Other files, you can drag and drop them here to upload. (optional)

https://cdn.discordapp.com/attachments/1053295328968847401/1174687146469228606/Minecraft_2023.11.16_-_14.21.16.116.mp4

### Screenshots/Videos (you can drag and drop files or paste links)

https://cdn.discordapp.com/attachments/1053295328968847401/1174687146469228606/Minecraft_2023.11.16_-_14.21.16.116.mp4

**Comment by LoneDev6** [comment]
It's hard to tell.
ItemsAdder is not putting any text in the title bar by default.
Did you install any addon?

**Comment by IlayX5G** [comment]
I do not think
