### ISSUE TITLE
ItemFrame Furnitures can be overlapped in same locations

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#3160]
#3014

> @LoneDev6 
Still problems)
Not all sides of the world work (only floor works correctly)
Something is wrong with the angle N W
I worked with the hitbox in every possible way (does not help)
> 
> https://github.com/PluginBugs/Issues-ItemsAdder/assets/123487110/e4e21154-8dcb-4d58-99e9-d585fb02ace0
> 
> 
> 
> https://github.com/PluginBugs/Issues-ItemsAdder/assets/123487110/5dee1807-9695-4893-8da0-1dfaf991b889
> 
> Is it possible to find out if there is an opportunity to fix the feature that I showed in the second video in the mention of what is above
The furniture element can be ignored and put a block (by the way, it also works on the edges)

**Comment by LoneDev6** [comment]
Fixed:

https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/257dc030-2f48-43e6-86f6-fc4ff5c68df0

**Comment by potapenchikov** [comment]
walls
![y6ucp1Eklyc](https://github.com/PluginBugs/Issues-ItemsAdder/assets/123487110/9bcb3db4-dfd8-4e79-a0f6-64a2e596e841)
ceiling
![dTguEhVvUWk](https://github.com/PluginBugs/Issues-ItemsAdder/assets/123487110/5a8e9a86-566f-4ccd-91fc-2e8c29d34c9d)

**Comment by LoneDev6** [comment]
Thanks for the details but it's already fixed, I'm going to publish the update in some minutes, it was a simple mistake :D

**Comment by LoneDev6** [comment]
Also nice pen! Very cute :D

**Comment by potapenchikov** [comment]
Thanks)

**Comment by potapenchikov** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/assets/123487110/56c6e580-2d3d-47b4-b149-0fce02f4bb44

The furniture element can be ignored and put a block
I don't quite understand if I can fix it somehow

**Comment by LoneDev6** [comment]
Please open a separate Github issue and also specify if you can trigger this issue also on previous versions of the plugin and not only on the last one.
Thanks!
