### ISSUE TITLE
Option to show emoji suggestions in chat

### ISSUE THREAD

**Issue by HielkeMaps** [PluginBugs/Issues-ItemsAdder#3183]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

hielkemaps

### Describe the solution you'd like

At the moment, using tab emoji suggestions in chat only suggests the :emoji: text. Using the /e command actually shows the emoji's in chat. I would like the option to show those emoji suggestions in normal chat as well, since it's way more user friendly.

This must be possible, since after clicking a suggestion in /e, I can copy paste the emoji to normal chat and it works just fine!

How it currently works:

**In chat:**
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/62292398/0e2b3fe2-6eef-496d-a3ca-5546033265d4)

**Using /e:**
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/62292398/c6d26509-2a5a-492c-9ee1-74f1fab397ca)

### Is your feature request related to a problem?

Not really a problem, but for the user showing the actual images would be way more user friendly.

### Describe alternatives you've considered

None.

**Comment by LoneDev6** [comment]
It's currently not possible to do that because of how Minecraft works, sadly.
