### ISSUE TITLE
Custom entities not showing if no player was around during the base entity spawn event

### ISSUE THREAD

**Issue by DivContainer** [PluginBugs/Issues-ItemsAdder#3186]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

dosenoeffner124

### What happened?

I developed a plugin spawning custom entities across the map as soon as a player joins. If the CustomEntity spawns in a chung not currently loaded by the player animations do not show. This also happens if i spawn the tower in the player loaded chunk without any delay. I also noticed that the CustomEntities all have the desired animation (CustomEntity.HasAnimation...) but it wont display them to the current player or any other player joining later...

### Steps to reproduce the issue

1. Spawn a CustomEntity 256 blocks away in a chunk that is not loaded by any player (doesn`t matter if it has been loaded before or not)
2. Go to the CustomEntity (as a player) and make the CustomEntity play an animation
3. Animation will not appear

### Server version

1.19.2

### ItemsAdder Version

3.3.1

### ProtocolLib Version

5.1.0

### LoneLibs Version

1.0.27

### FULL server log

container@pterodactyl~ Server marked as running...
[19:40:20 INFO]: Timings Reset
[19:40:20 INFO]: [ItemsAdder] Loaded 9 items
[19:40:20 INFO]: [ItemsAdder] Used 0/188 REAL block IDs
[19:40:20 INFO]: [ItemsAdder] Used 1/750 REAL_NOTE block IDs
[19:40:20 INFO]: [ItemsAdder] Used 0/63 REAL_TRANSPARENT block IDs
[19:40:20 INFO]: [ItemsAdder] Used 0/127 REAL_WIRE block IDs
[19:40:20 INFO]: [ItemsAdder] Used 0/14 FIRE block IDs
[19:40:20 INFO]: [ItemsAdder] Used 14/6608 font_images
[19:40:20 INFO]: [ItemsAdder] [Init] Loaded 1 categories
[19:40:20 INFO]: [ItemsAdder] [Init] Loaded successfully.
[19:40:20 INFO]: [ItemsAdder] [Pack] Checking resourcepack url... 
[19:40:22 INFO]: [ItemsAdder] [Pack] Resourcepack URL is valid (external-host). Url: https://www.dropbox.com/scl/fi/****

**Comment by LoneDev6** [comment]
Please post a video to showcase how to reproduce the issue in detail.
Thanks.

**Comment by LoneDev6** [comment]
I think I managed to reproduce the same issue on my test server, but happens only sometimes.

- add a Citizens NPC or spawn a custom entity using /iaentity summon
- teleport very far away, or change world
- quit
- stop my server
- start my server
- join 
- teleport where you spawned the entitites
- see that some of the entities are not showing, but their base entity is correctly hidden and not showing
- run /iareload and you will see the custom entities

I'm working on finding the cause of the issue, thanks for the report

**Comment by DivContainer** [comment]
Hi, I fixed the issue for me:

1. Getting the locations of alle custom entities before spawning them

2. Set the Chunk to forceLoaded true

3. Spawn the entity

**Comment by LoneDev6** [comment]
The citizens issue seems to be fixed by fixing this other issue: https://github.com/PluginBugs/Issues-ItemsAdder/issues/3263

About the API issue, I cannot reproduce the issue anymore in the latest version of the plugin.
What I did:
- spawned an entity with this code very far from the player, on an unloaded chunk
```java
CustomPlayer customPlayer = CustomPlayer.spawn("https://minesk.in/5f1e7ff6409e428bb500cc9315bf7ffb", new Location(world, 4992, 63, 5002));
customPlayer.getEntity().setInvulnerable(true);
```

- teleported to the location
- I can see the custom entity

Only noticeable bug: The entity is not immediately showing, it first shows the vanilla entity for some seconds, then it loads the custom model, which will be fixed:  #3288

**Comment by DivContainer** [comment]
But do animations still work? This bug was not only related to the entity not appearing but also caused animation to not being played.

**Comment by LoneDev6** [comment]
> But do animations still work? This bug was not only related to the entity not appearing but also caused animation to not being played.

Seems so, please report this issue again if it's still reproducible after the update (I will release it as soon as possible).

**Comment by DivContainer** [comment]
I think theres a difference between a CustomPlayer and a CustomEntity.

**Comment by LoneDev6** [comment]
Animations seems to play fine, please bump this issue if the issue persists after the new update will be published, approximately today.
Thanks!

**Comment by DivContainer** [comment]
Hi @LoneDev6 ... issues persists on version 3.6.3-bet-9.

Spawn custom entity with custom model. Fly far away, model disappears but base entity is still there and hidden. /iareload and the models appear again.

Everything is on the latest persion.

Thank you in advance.

**Comment by LoneDev6** [comment]
Strange, I will make another test, I tested it extensively and I couldn't trigger it anymore.
https://github.com/PluginBugs/Issues-ItemsAdder/issues/3369
