### ISSUE TITLE
Cannot invoke "org.bukkit.command.PluginCommand.setTabCompleter

### ISSUE THREAD

**Issue by SuprClan** [PluginBugs/Issues-ItemsAdder#3187]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I restarted my server and upon a restart ItemsAdder broke and now says 

### Steps to reproduce the issue

All i did was update LoneLibs and Itemsadder and restart

### Server version

This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version

### ItemsAdder Version

ItemsAdder version 3.6.2-beta-r4

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-673

### LoneLibs Version

1.0.30

### FULL server log

https://mclo.gs/FB9jp2P#L1188

### Error (optional)

```
[11:20:01] [Craft Scheduler Thread - 25 - ItemsAdder/WARN]: [ItemsAdder] Plugin ItemsAdder v3.6.2-beta-r4 generated an exception while executing task 5129
java.lang.NullPointerException: Cannot invoke "org.bukkit.command.PluginCommand.setTabCompleter(org.bukkit.command.TabCompleter)" because the return value of "dev.lone.itemsadder.Main.a(String)" is null
	at ia.m.hs.<init>(SourceFile:80) ~[ItemsAdder_3.6.2-beta-r4.jar:?]
	at ia.m.G.a(SourceFile:921) ~[ItemsAdder_3.6.2-beta-r4.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-196]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by LoneDev6** [comment]
For some reason ItemsAdder can't find the command `/iaimage` which is strange.
I am trying to find the cause since it seems to happen only on some servers. I cannot reproduce it on my server.

It's a mystery why the Bukkit API function fails to find the ItemsAdder command.
The Bukkit API MUST return the correct command, so there is something wrong going on here.

There might be another plugin interfering or a bug of Spigot itself.
Try to update it to the latest build available for your game version.

**Comment by SuprClan** [comment]
I found the issue, it was another plugin that wouldn't let ItemsAdder load properly. Thank you for looking into it though

**Comment by LoneDev6** [comment]
No problem @SuprClan but please provide more details on which plugin is causing this issue, thanks!
This will help other customers too.

**Comment by Kiritoita75** [comment]
I test that on my server, the problem Is caused by PerWorldPlugin, I had the same problem caused by that plugin, Just remove start the server and reinstallo PerWorldPlugin. It gonna male itemsadder work with PerWorldPlugin
