### ISSUE TITLE
There is no falling sound in vanilla blocks and more things

### ISSUE THREAD

**Issue by paulreob** [PluginBugs/Issues-ItemsAdder#3190]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

When you jump on the edge of a block the stone fall sound is played, this in OriginRealms and in vanilla it does not play any sound when jumping on the edge, however with ItemsAdder it seems that by default it plays that, it is somewhat disturbing because If you jump over sand, leaves, dirt, etc., the stone fall sound will play.

And the second thing is that no falling sound is played when jumping in the same location, however in the custom blocks the sound is played.

### Steps to reproduce the issue

Check video
https://streamable.com/yn1zka

### Server version

Paper version git-Paper-297 (MC: 1.20.2)

### ItemsAdder Version

ItemsAdder version 3.6.2b

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-669

### LoneLibs Version

LoneLibs version 1.0.31

**Comment by paulreob** [comment]
About jumping in the same location it seems that in vanilla it doesn't play either xD, sorry about that

On the other hand, jumping on the edge of a block does have to be seen.

**Comment by paulreob** [comment]
The video also shows that the stone break sound is played when you right click on a custom block... although I couldn't play it again...

**Comment by LoneDev6** [comment]
Checking the Minecraft source code I found out that the game plays fall sound only if player actually gets fall damage.
I will fix that, thanks! :D

About the interaction sound I cannot trigger it.

**Comment by paulreob** [comment]
I don't think I realized this other mistake, but when you walk on the edge of a block the step stone sound sounds
[https://streamable.com/5bg1fc](url)

**Comment by LoneDev6** [comment]
I will try to reproduce it in the upcoming update and let you know.
Thanks!
Opened a separate issue report for that #3192
