### ISSUE TITLE
Adding Server Context just like World Context

### ISSUE THREAD

**Issue by DanimalzCup** [PluginBugs/Issues-ItemsAdder#3196]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

DanimalzCup

### Describe the solution you'd like

Would it be possible to have server context as well? I know we have a world context defined by world name where ore generates or how things are being crafted etc. Possible to make crafting recipes as well as world generation and even maybe whole armor sets or tools or any item be server specific?

### Is your feature request related to a problem?

We have multiple servers. We edit the resourcepack on 1 server, then are able to copy and paste the solution. As of right now we have a specific couple of "armor sets" we do not need that exists on server A and do not need to be on Server B. Also the ore generates in the end but both servers A and B have an end. We would have to rename one of the end world to like end1 or something. We also do not want said armor sets to be able to be crafted with the recipes from server A to server B.

### Describe alternatives you've considered

The only solution I have figured out is to delete the specific folder that contains the items from Server A when I am pasting the itemsadder config in server B so that they do not exist, or generate everytime. Seams like too much of a hastle.

### Additional context

Like luckperms, being able to have a server =  option be able to be added to the config of items, and then define in main config the server. For instance, SMP and factions. In the items config, an extra value that can by typed would be like server: SMP. Then in the main config, I'd add another line of server = SMP or something. (Any items with nothing defining server would be considered global) then when IA is generating, for instance in SMP, would read for global items, and server specific. If server = SMP, generate else if server = anything other than SMP, do not generate, else generate (global).

**Comment by LoneDev6** [comment]
I see I see, this is a very edge case so I want to make sure to understand the situation in the best possible way.

Which items, properties, generators etc. are you exactly expecting to be disabled on a server, for example?
Can you make a rough list?

**Comment by DanimalzCup** [comment]
Sure. At the moment what I can 100% think of being per server would be like:
- Custom Armors (should be either allowed for all severs, multiple servers but one, Only one server, or no servers at 
   all)
- Custom Ore world generation (should be either allowed for all severs, multiple servers but one, Only one server, or no servers at 
   all - people might have things like special events coded in already all you have to do is enable it and allow it to generate, disable 
   upon event being over or removing that ore from that server)
- Recipes per Server (Be able to enable/disable recipes either allowed for all severs, multiple servers but one, Only one server, or 
   no servers at - Some servers having the recipe on server A but have the same armor set on server B but don't want it craftable)

Please enlighten me, I do not know much about what Regex is or its functionality.

**Comment by LoneDev6** [comment]
Regex is basically a special text to match names based on special characters.
A very simple example: `*_helmet` will match any item of which its name ends with `_helmet`.

I would basically add a new setting in the config.yml file similar to this:

```yml
enable_override:
  rule_1:
    mode: enable
    items:
      - _helmet # matches all items of which name ends with _helmet
      - special_items:* # matches all items of namespace special_items
      - ....
  rule_2:
    mode: disable
    items:
      - my_magical_items:* # matches all items of namespace my_magical_items
      - ....
    world_populators:
      - ruby_ore
      - my_ore
    crafting_recipes:
      - my_crafting
```

Anyway is this still needed?
I still think it's not a great addition as it's an edge case
