### ISSUE TITLE
Custom Model Data work properly ?

### ISSUE THREAD

**Issue by Alexh2807** [PluginBugs/Issues-ItemsAdder#3198]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Hello,
I would like to be able to add a template to a plugin to use a plugin with a custom element.
I tried to create a template with the plugin wiki but I can't, I don't have the same file names and maybe I'm wrong, I don't know.

Here is what I use:
My config of my personalized elements which are located in: ItemsAdder\contents\my_items\configs\items\decorations\atm.yml

![atm yml](https://github.com/PluginBugs/Issues-ItemsAdder/assets/96073870/e0a76ba7-2874-4ec7-ada0-14ee40d59618)

And location of my model, created with blockbench, is located in :
ItemsAdder\contents\my_items\resourcepack\my_items\models\atm.json

![atm json](https://github.com/PluginBugs/Issues-ItemsAdder/assets/96073870/5a8fcba8-169d-431c-86c3-b782fa5af566)

Do you see an error? And what should I put instead to be able to use my custom element in a config folder of another plugin?

### Steps to reproduce the issue

All in the screen

### Server version

Current: git-Purpur-2092 (MC: 1.20.2)*
* You are 3 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### ItemsAdder Version

3.6.2-beta-r4

### ProtocolLib Version

5.1.1

### LoneLibs Version

1.0.30

**Comment by LoneDev6** [comment]
Wrong path:
`ItemsAdder\contents\my_items\resourcepack\my_items\models\atm.json`

Should be:
`ItemsAdder\contents\my_items\resourcepack\my_items\models\item\atm.json`
since you set this:
`model_path: "item/atm"`
and not this:
`model_path: "atm"`
