### ISSUE TITLE
pack.mcmeta new features

### ISSUE THREAD

**Issue by ColorsASD** [PluginBugs/Issues-ItemsAdder#3209]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Hello! Now that the overlay has been added to the pack.mcmeta, I am using version 1.20.2, so in addition to the assets, pack.mcmeta, and pack.png, I also need a custom folder, let's call it gui1202. In this folder, there is also an assets folder, which overrides the original assets folder under the appropriate version, enabling support between different versions. Unfortunately, ItemsAdder does not generate or include this folder in the generate.zip file. I don't know how to include it.

### Is your feature request related to a problem?

So, my problem is that ItemsAdder is not willing to include the gui1202 folder in the generated.zip file, which is necessary for me. Is there any way to resolve this issue?

### Describe alternatives you've considered

One solution is to replace the directory section in the pack.mcmeta from gui1202 to assets. Then, there should be another assets folder inside the assets folder, but this is not ideal if I want more than one override in the future.

### Additional context

pack.mcmeta:
```
{
   "pack": {
    "pack_format": 22,
    "supported_formats": {
      "min_inclusive": 7,
      "max_inclusive": 22
      },
      "description": "CENSOR"
    },
  "overlays": {
    "entries": [
      {
        "formats": {
          "min_inclusive": 16,
          "max_inclusive": 22
        },
        "directory": "gui1202"
      }
    ]
  }
}
```
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/12263156/ee008813-89d9-4b57-9a52-acf5802bf5ab)
generated.zip:
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/12263156/eef79b1b-f516-4218-95f8-71e930b10c62)
And one more thing: as far as I know, there is no option for a subfolder in the "directory": "gui1202" section. I tried, for example, "directory": "assets/gui1202" or the same with a backslash, but unfortunately, it is not possible. Only the folders that exist next to the pack.mcmeta file can be specified. I really wish I could be wrong about this.

**Comment by LoneDev6** [comment]
I consider this feature useless to be honest as ItemsAdder already provides a very simple way to merge resourcepacks.
This "overlays" feature also doesn't merge files, it just overrides them.
For example if you have multiple folders with "diamond_sword.json" it won't merge them all, it will use only the top one. ItemsAdder allows multiple json files to be merged and working correctly.
Can you elaborate more why you wish this feature to be implemented?

Please check the resourcepack merging tutorial: https://itemsadder.devs.beer/plugin-usage/merge-resourcepacks#how-to-merge

**Comment by ColorsASD** [comment]
There is no such feature in ItemsAdder; yours has a function that combines textures independently of the version, meaning multiple textures are grouped together. Overlays' functions are version-specific. So, what you want in 1.20.2 won't appear in 1.19.3. There have been many recent changes regarding the GUI, so this is useful for servers supporting multiple versions.

**Comment by ColorsASD** [comment]
![Screenshot_20231215-130405_Chrome](https://github.com/PluginBugs/Issues-ItemsAdder/assets/12263156/5f725a84-2460-4e97-8c34-e9b2cef49c2b)
![Screenshot_20231215-130430_Chrome](https://github.com/PluginBugs/Issues-ItemsAdder/assets/12263156/99645b6c-d479-466b-a505-870e55c204be)

**Comment by LoneDev6** [comment]
I see, this is definitely interesting.
I can implement that but keep in mind that it might take time.
Thanks for clearing things up!

**Comment by LoneDev6** [comment]
One big drawback of this vanilla feature is that the client will download the whole zip file, am I correct?
This is a bad decision as because if you have created a pack with multiple overlays there is a big issue:
If each overlay is for a different version the client would have to download the whole zip containing useless packs for their game version.

Am I correct?

**Comment by ColorsASD** [comment]
I only need basic vanilla functions, requiring a custom folder generated by the plugin. However, if you're willing to invest time and effort, you can create your own improved overlay that downloads the specific package with users based on brand or version.

I'm not looking for a new function, just the ability to use this basic function. Just like using pack.png and pack.mcmeta, I believe there is no need for any development. It would be sufficient if, as I described above, it generates folders outside of assets.

**Comment by ColorsASD** [comment]
Otherwise, the package is limited to 50MB, I think 250MB, I don't know, I don't think downloading this would be a problem for anyone. The overlays feature was essentially introduced because the GUI was completely broken into pieces. Under 1.19.2, the textures slide, and above 1.20.2, the texture names are different. I use the overlay for this purpose.

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/12263156/2264fe42-86dc-461d-9191-ea65221d6620)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/12263156/18b1ebde-4c25-42ae-a71e-1fe8f1b18ad5)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/12263156/65d4feba-13a7-4ec1-882e-3990bb10eb39)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/12263156/41faafa8-47fd-47e2-9298-1111f7f01411)

**Comment by ColorsASD** [comment]
So, I use the overlays feature to address the errors caused by the GUI from 1.20.2 and onwards. If you look around on CurseForge, you'll find the overlays in more and more texture packs because of the GUI issues.

**Comment by ColorsASD** [comment]
This function is needed more and more because of the rapid version changes.

**Comment by LoneDev6** [comment]
I sadly don't understand the urge to have multi-version compatibility on servers.
You can read more about what I think about multi-version here: https://itemsadder.devs.beer/itemsadder-v4
For now I have to discard this compatibility, what you can do is manually create a pack.mcmeta and let ItemsAdder put it into the zip automatically, which should already be able to do that without issues.

**Comment by ColorsASD** [comment]
This is still not about whether **YOU** support the other versions or not; it's about the fact that **YOU** are not allowing this. You didn't create this, **MOJANG** did. It's a basic feature, just like how you can add an image to the texture named `pack.png`.

The modification you need to create in the file structure is simply to generate custom folders alongside the `assets`, `pack.png`, and `pack.mcmeta` files, like this:

The following texture elements should be placed in the **assets** folder:
`contents/<your_name>/resourcepack/assets`

The following texture elements should be placed in a **custom** folder where the assets are located:
`contents/<your_name>/resourcepack/custom`

So, the main directory of the texture pack would look like this:

- `assets`
- `custom`
- `pack.png`
- `pack.mcmeta`

So, this isn't about **YOU** doing the support; you just need to keep up with **MOJANG's** basic texture developments. **THIS IS A BASIC FEATURE SINCE 1.19.4, PLEASE.**

**Comment by Andre601** [comment]
And YOU need to learn that ItemsAdder is done by one single dev while Mojang has a group of developers behind itself, doing ONLY work on Minecraft as their daily job.

LoneDev has to do absolutely nothing here. This plugin isn't his only priority in life and there is no obligation for him to do anything to support whatever Mojang throws out the next week.

Also, multi-version support on Servers is absolute cancer if it is done for anything but allowing multiple versions on a local lobby server.
MC was and never will be designed for multi-version support and LoneDev shouldn't need to bend over backwards here just to satisfy a single individual (you) here.

Stop acting like this is a company you own or that LoneDev owes you because you bought a plugin from him. He owes you absolutely nothing and could stop working on IA at any time here, so be happy he hasn't yet.

**Comment by ColorsASD** [comment]
Go ahead. You don't know anything about me, and I don't know anything about you either. Those who think of everything as work know that it’s more important for me to keep 20k people up to date in the best possible way. If I can’t do that, I’ll switch, it’s that simple. I’m not here to make demands, as YOU said. You don’t have to do anything, you can stop, we’re not dependent on anyone. The issue here is that a basic Minecraft function has been REMOVED, not that it’ll be fixed in 3-4 years; it has been literally deleted. Have a nice day.

**Comment by LoneDev6** [comment]
As I said before you can already do that manually by creating a pack.mcmeta file inside a directory, for example:
`plugins\ItemsAdder\contents\my_custom_packmcmeta\resourcepack\pack.mcmeta`.
ItemsAdder should already merge it automatically.
