### ISSUE TITLE
Font images bug on signs - black font images

### ISSUE THREAD

**Issue by Fizz-Mechanic** [PluginBugs/Issues-ItemsAdder#3216]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Fizz_Mechanic

### What happened?

I think this is a bug, I've created custom images, which are directly linked with a symbol that you can use on the server. It works everywhere, in the chat, in the menus etc... but not on the signs, my image is all black and turns into a # symbol when I press enter.
![Screenshot_57](https://github.com/PluginBugs/Issues-ItemsAdder/assets/148489186/a439397b-f109-4ae5-847f-1b124cccc00b)
![Screenshot_56](https://github.com/PluginBugs/Issues-ItemsAdder/assets/148489186/418f0a5c-b912-4665-b1fb-ed611d3710fc)
![Screenshot_55](https://github.com/PluginBugs/Issues-ItemsAdder/assets/148489186/682d0539-21f3-4983-a76e-04cde571aa6d)

### Steps to reproduce the issue

1. Create a custom font images with a symbol
2. Paste symbol on a sign
![Screenshot_56](https://github.com/PluginBugs/Issues-ItemsAdder/assets/148489186/3cb57c3e-2972-4fba-8ba3-0f66ad0db29b)

### Server version

This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version

### ItemsAdder Version

3.6.2-beta-r2

### ProtocolLib Version

5.1.0-SNAPSHOT-660

### LoneLibs Version

1.0.27

**Comment by LoneDev6** [comment]
Depends how you write the font images in signs.
In my case they work fine.
You  have to use their placeholder, you might are copying and pasting them, this causes them to not be white colored.
Remember that the default text color is black on signs.
Another way to fix that is use a plugin to change the signs text color, but the easiest way is to just use the placeholders.

For example: `:smile:`.
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/5d6d1636-7b31-403c-a472-92a7385b87ff)
