### ISSUE TITLE
Pistons break trying to push custom blocks

### ISSUE THREAD

**Issue by Fizz-Mechanic** [PluginBugs/Issues-ItemsAdder#3223]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Fizz_Mechanic

### What happened?

The pistons break when trying to push the custom blocks. I think it's a bug, quite annoying, if it's possible to fix it quickly please.

https://github.com/PluginBugs/Issues-ItemsAdder/assets/148489186/8c16de36-ef5a-424a-9731-ac7fa4f7bbca

(url)

### Steps to reproduce the issue

1. Place a custom block.
2. Try to push it with a piston.
3. The piston breaks.

### ItemsAdder Version

This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version

### ProtocolLib Version

5.1.0-SNAPSHOT-660

### LoneLibs Version

1.0.27

**Comment by LoneDev6** [comment]
This is working as intended because I don't want people to push custom blocks are they might cause performance issue due to the high amount of events triggered by vanilla pistons.
Anyway the feature was requested here, I will try to implement it in the future: #3211
