### ISSUE TITLE
Adding unwanted characters to the lore

### ISSUE THREAD

**Issue by Zzheyd** [PluginBugs/Issues-ItemsAdder#3225]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Have update IA from ItemsAdder_3.5.0c-r5b to ItemsAdder_3.6.2c.
And now have little problem, the new items don't stack with the old ones, it comes from the lore which is different.

### Steps to reproduce the issue

In my items pack file, I have lore: 
`    lore:
    - '&7[%#d4741d%Halloween&7]'
    resource:`

But in game, the item writes: 
`§f§7[§x§D§4§7§4§1§DHalloween§7]`

Before the update it was:
`§7[§x§D§4§7§4§1§DHalloween§7]`

Have a "§f" now in lore.

### Server version

This server is running Pufferfish version git-Pufferfish-27 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 979d3a2 on HEAD)

### ItemsAdder Version

ItemsAdder version 3.6.2c

### ProtocolLib Version

ProtocolLib version 5.1.0

### LoneLibs Version

LoneLibs version 1.0.31

### FULL server log

No error in log serv

**Comment by LoneDev6** [comment]
Why not using the minimessage format instead?
https://itemsadder.devs.beer/plugin-usage/hex-colored-texts-1.16+
