### ISSUE TITLE
Craftorithm cannot use items from itemsadder as recipe ingredients

### ISSUE THREAD

**Issue by YufiriaMazenta** [PluginBugs/Issues-ItemsAdder#3230]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

YufiriaMazenta

### What happened?

The Craftorithm plugin is unable to use items from ItemsAdder as ingredient.

I'm the author of Craftorithm, and I have confirmed that the issue lies with ItemsAdder. After removing ItemsAdder, I was able to create recipes using the items from ItemsAdder still present on the server and successfully craft them.

Regarding compatibility, here is some potentially useful information: The namespace for Craftorithm recipes is 'craftorithm'.

### Steps to reproduce the issue

1. Use the command /iaget to get an item from ItemsAdder.
2. Use this item to create a recipe in Craftorithm.
3. Open the crafting table and arrange according to the recipe.
4. Unable to craft the item.

### Server version

Current: git-Purpur-2014 (MC: 1.20.1)*

### ItemsAdder Version

ItemsAdder version 3.6.2d-beta2

### ProtocolLib Version

ProtocolLib version 5.1.0

### LoneLibs Version

LoneLibs version 1.0.40

**Comment by LoneDev6** [comment]
https://www.spigotmc.org/resources/%E2%9C%A8craftorithm-1-13-1-20-4-%E2%9A%99%EF%B8%8Fcustomize-your-crafting-system%E2%9A%99%EF%B8%8F-%E2%9A%A1folia-support%E2%9A%A1.108429/updates

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/7603e2c5-0cd8-4323-b174-c987f84a68b7)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/33853692-552d-4e8e-95bc-b779a9a83c94)
