### ISSUE TITLE
inoperable vehicles

### ISSUE THREAD

**Issue by 100petr** [PluginBugs/Issues-ItemsAdder#3242]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

pitilon

### What happened?

Today I updated the server from 1.20.1 to 1.20.2 and the vehicles stopped working - planes, cars. I sit in the vehicle, but there is no way to move it. 

### Steps to reproduce the issue

Start the server with IA on 1.20.2 and try moving the vehicle

### Server version

[17:53:11 INFO]: Current: git-Purpur-2095 (MC: 1.20.2)*
Previous: git-Purpur-2062 (MC: 1.20.1)
* You are running the latest version

### ItemsAdder Version

ItemsAdder version 3.6.2d-beta-2

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.40

**Comment by SirCraftypants** [comment]
Are you using worldguard, if you are, are you aware of the [Flags](https://itemsadder.devs.beer/compatibility-with-other-plugins/compatible/worldguard-flags)

Do you have any other plugins that deal with Armorstands that may be causing a conflict?

**Comment by LoneDev6** [comment]
I will try to do some testing but last time I checked vehicles were working fine
