### ISSUE TITLE
Thirst won't get synced

### ISSUE THREAD

**Issue by imparium-de** [PluginBugs/Issues-ItemsAdder#3246]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

derMiepz#5898

### What happened?

We're using this in our join listener method to sync the thirst from players upon joining, but even with a delay it doesn't seem to work.
 
 ```
         Bukkit.getScheduler().runTaskLater(plugin, () -> {
            if(plugin.getServer().getPluginManager().getPlugin("ItemsAdder") != null ){
                PlayerHudsHolderWrapper playerHudsHolderWrapper = new PlayerHudsHolderWrapper(p);
                PlayerQuantityHudWrapper hud = new PlayerQuantityHudWrapper(playerHudsHolderWrapper, "iasurvival:thirst_bar");
  
                hud.setFloatValue(10.0F);

            }
        }, 120L);
```

Implementing https://github.com/PluginBugs/Issues-ItemsAdder/issues/621 would make things a lot easier, especially since MySQL Player Data Bridge is one the more popular player data sync plugins from a well known dev. 

### Steps to reproduce the issue

See above

### Server version

This server is running Paper version git-Paper-47 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 3.6.2d-beta-2
Customized Minecraft without client mods!
Website: devs.beer
Author: LoneDev

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-669

### LoneLibs Version

LoneLibs version 1.0.40

**Comment by LoneDev6** [comment]
Hello!
I added a warning in the API tutorials about that:
> NOTE
Make sure that you don't have the permission ia.user.hud.bypass.api.* or setFloatValue the code won't do anything. 
https://itemsadder.devs.beer/developers/java-api/huds-guis-images-and-more#access-mana-bar-value-example
