### ISSUE TITLE
1.20.4 - `Block 'GRASS' not found for loot 'grass'

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#3248]
`Block 'GRASS' not found for loot 'grass'. File: /contents/iasurvival/configs/crops/loots.yml`.
Anyway I will implement a trick to convert GRASS to SHORT_GRASS, to avoid to update all packs configurations.

**Comment by Slarof** [comment]
The "grass" item has been renamed to "short_grass" 

Just change the "grass" configuration to "short_grass" and the problem is solved)

**Comment by Snipy44** [comment]
> The "grass" element has been renamed to "short_grass"
> 
> Just change the "grass" item to "short_grass" in the configuration, and the problem is solved)

is possible to more precise ? i try and i dont workd for me :/
