### ISSUE TITLE
Block Place Bug

### ISSUE THREAD

**Issue by ELpixell** [PluginBugs/Issues-ItemsAdder#3256]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

@elpixel__

### What happened?

I created a block through itemsadder, called oxygen_block.
When a user has that block in his hand, and goes to an area protected by worldguard (it cannot be placed or destroyed), if he starts clicking with the right button to simulate the placement of the block, he is not rightly placed the block, but if there is snow or grass where he clicked, it is eliminated.

I tried to solve with permissions, but without any success. I'm waiting for help on this.

### Steps to reproduce the issue

I don't have any error

### Server version

git-Tentacles-"99cccce" (MC: 1.20.1)

### ItemsAdder Version

ItemsAdder version 3.6.2-beta-r2

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-669

### LoneLibs Version

LoneLibs version 1.0.27

### Problematic items yml configuration file (optional)

```shell
oxygen_block:
    enabled: false
    display_name: '&fBlocco di Ossigeno'
    permission_suffix: oxygen_block
    resource:
      material: PAPER
      model_id: 4014
      generate: true
      textures:
        - luckyblock/oxygen_block
    specific_properties:
      block:
        placed_model:
          type: REAL
          break_particles: BLOCK
        cancel_drop: true
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://github.com/PluginBugs/Issues-ItemsAdder/assets/140637303/0e0805d2-a60d-4526-b831-32d540116464

**Comment by LoneDev6** [comment]
Can't reproduce

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/2ce6a2d8-ecc9-481d-92c9-21e34e2b16c8)


https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/7e3937a7-57cd-4b2c-a56c-65d1db4ec039

**Comment by ELpixell** [comment]
Can u send me your configuration of block? I have controlled worldguard flags, and I just have block-place on DENY.

**Comment by LoneDev6** [comment]
@ELpixell 
https://github.com/ItemsAdder/DefaultPack/blob/087bae5c2ddea5aa4e7f760586e4bc18e3436117/contents/iasurvival/configs/blocks/items/minerals/aqua_aura_block.yml#L4
