### ISSUE TITLE
Playing 2 emotes one near the other causes player not to appear again after 2nd emote ends

### ISSUE THREAD

**Issue by glutaminus** [PluginBugs/Issues-ItemsAdder#3261]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

using 2 or more emotes at the same time (even with 1 tick delay) will make player not reappear after emotes end.
I think this might not sound like a problem since emote was meant to be use only once, but however I don't think anybody would like it to happen in their server. if there's a case where player use emote twice.

### Steps to reproduce the issue

1. made a skript to use emote twice just for testing purpose
```
command /twiceemote [<string>] [<string>] [<player>]:
    trigger:
        execute console command "iaemote %arg-1% %arg-3%"
        wait 1 tick
        execute console command "iaemote %arg-2% %arg-3%"
```
2. use twiceemote.
3. player aren't being unhide after emotes end

### Server version

git-Purpur-1985 (MC: 1.19.4)

### ItemsAdder Version

3.6.2d-beta-2

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### LoneLibs Version

1.0.27

### Screenshots/Videos (you can drag and drop files or paste links)

https://github.com/PluginBugs/Issues-ItemsAdder/assets/90768288/36b21edc-b07b-463f-bc92-180408505942

**Comment by LoneDev6** [comment]
I don't see why you're trying to play two emotes at the same time nor why there is 1 tick of delay.
There is no way to fix that since emotes have some delayed code execution, so triggering two emotes at the same time very fast will cause this issue.

If you want two emotes to play near each other why not waiting more ticks?
Or why not creating a new emote which consists of both emotes movements? You can do it by selecting all emote keyframes, pressing CTRL+C and CTRL+V in the other emote to paste the keyframes.

**Comment by glutaminus** [comment]
> I don't see why you're trying to play two emotes at the same time nor why there is 1 tick of delay. There is no way to fix that since emotes have some delayed code execution, so triggering two emotes at the same time very fast will cause this issue.
> 
> If you want two emotes to play near each other why not waiting more ticks? Or why not creating a new emote which consists of both emotes movements? You can do it by selecting all emote keyframes, pressing CTRL+C and CTRL+V in the other emote to paste the keyframes.

@LoneDev6 sorry for the ping, I don't know if you can see this anymore because it's closed. The reason to why is because there are some case when emote gonna be played twice, like I If I have made a way to left click for an emote, and right click for another emote, for player to choose, when player do left and then fast right click manually that will make emote bug.
I didn't try to achieve two emotes at the same time, I want new emote to be played without disappearing bugs. I just can't accept that player can hide character abusing this bug. 

What should happen:
Playing 1st emote -> 2nd emote come in fast before 1st emote end -> 2nd emote played - > unhide the player

Actually when I use 1.19.2 with older IA I think this bug doesn't happen. So I hope there's a way out to this.

**Comment by LoneDev6** [comment]
Well

**Comment by LoneDev6** [comment]
Tested using this plugin: https://www.spigotmc.org/resources/customcommands-new-1-20-support.14363/
I can reproduce the issue and I fixed it in the upcoming update.
Hopefully no bug is introduced by this change, I tested it and works fine on normal conditions.
Maybe edge cases will trigger some new bugs but I doubt.

```yml
aliases: [twiceemote]
patterns:

  - pattern: ''
    description: brop
    actions:
      - type: EXECUTE_COMMANDS
        as_player: true
        commands: |
          iaemote death
      - type: EXECUTE_COMMANDS
        as_player: true
        commands: |
          iaemote no
```
