### ISSUE TITLE
Image not found for font_image '_iainternal:no_recipe'

### ISSUE THREAD

**Issue by Aneekgammer** [PluginBugs/Issues-ItemsAdder#3262]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

The bug is that it showing some error that I can't understand at all
![Screenshot_20231229_153942_Chrome](https://github.com/PluginBugs/Issues-ItemsAdder/assets/155150058/665fd422-ed5b-4bf5-8391-bf4bd7f8b905)
![Screenshot_20231229_153942_Chrome](https://github.com/PluginBugs/Issues-ItemsAdder/assets/155150058/b919697e-bd57-4eab-850f-cb2ceb6668f7)

### Steps to reproduce the issue

[10:09:04 ERROR]: [ItemsAdder] Image not found for font_image '_iainternal:no_recipe'. assets/_iainternal/textures/gui/no_recipe.png

### Server version

1.20.1

### ItemsAdder Version

3.2.6c

### ProtocolLib Version

Latest

### LoneLibs Version

Latest

### FULL server log

[archive-2023-12-29T101405Z.tar.gz](https://github.com/PluginBugs/Issues-ItemsAdder/files/13792594/archive-2023-12-29T101405Z.tar.gz)

### Screenshots/Videos (you can drag and drop files or paste links)

![Screenshot_20231229_153942_Chrome](https://github.com/PluginBugs/Issues-ItemsAdder/assets/155150058/98b26d3a-2d0b-437a-92ad-eddb5b115806)

**Comment by LoneDev6** [comment]
Make sure you enabled `extract_internal_utility_assets: true` in config.yml and run /iazip.
Seems it's disabled.

Another reason might be some files permission issue.
Try to delete this folder `contents/_iainternal/` and run /iazip again.

If that doesn't work try to delete it again and create these folders manually using your FTP editor or the hosting web view.
`contents/_iainternal/textures/gui/`
`contents/_iainternal/font/`

But generally speaking, this should be an FTP permissions issue.
