### ISSUE TITLE
dupe glitch through itemsadder's block (Aurelium skills)

### ISSUE THREAD

**Issue by Ecilpse** [PluginBugs/Issues-ItemsAdder#3267]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Eclipse

### What happened?

video : https://youtu.be/z2DxLjQ0jlY

i use AureliumSkills plugin. (such as MCMMO)
that plugin has passive skill like 2x drops.
By default, the skill does not apply to a block that placed by player,
But it is applied when player place it on the custom block.

### Steps to reproduce the issue

1. place CustomBlock made by IA.
2. place block that apllied 2x drops skills (ore, woods, etc)
3. break them.

### Server version

Paper(318) 1.20.2-RO.1-SNAPSHOT

### ItemsAdder Version

3.6.2c

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### LoneLibs Version

v1.0.31

**Comment by LoneDev6** [comment]
I don't understand the issue.
In the video you start with a specific amount of items and you end up with the same amount of items.
I see no duplication.

**Comment by Ecilpse** [comment]
> I don't understand the issue. In the video you start with a specific amount of items and you end up with the same amount of items. I see no duplication.

https://youtu.be/0m3Tz7fiFHI

i reuploaded video. The skill level is not high, so player not activate the double drop.
