### ISSUE TITLE
Custom Loading Screen

### ISSUE THREAD

**Issue by demirium** [PluginBugs/Issues-ItemsAdder#3268]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

demirium

### What happened?

Hello there!

I can't customize the loading screen on my server version 1.19.4 where I use ItemsAdder (I had the same problem in my previous server projects and experiments). 

It didn't work with the optifine method or shaders as written in this wiki. The colors can change, but the "Mojang" logo does not change in any way, even though the logos are set as described.

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/94578511/0c73018b-24cc-4383-9f18-b6d7bf560239)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/94578511/ad6ef9b5-9503-4ca4-b313-a38661fd8717)

### Steps to reproduce the issue

1 - In plugins\ItemsAdder\contents\doge\resourcepack\assets\minecraft\textures\gui I add my logo "mojang.png" or "mojangstudios.png" in 512x512, made as shown in the wiki.
2 - I use the /iareload and /iazip commands
3 - I keep seeing the mojang logo on the loading screen.

### Server version

[16:32:10 INFO]: Checking version, please wait...
[16:32:10 INFO]: This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4) You are running the latest version

### ItemsAdder Version

ItemsAdder version 3.6.3-beta-3

### ProtocolLib Version

ProtocolLib version 5.0.0

### LoneLibs Version

LoneLibs version 1.0.40

**Comment by LoneDev6** [comment]
Please read the wiki before creating Github issues, I wrote two pages about that.
https://itemsadder.devs.beer/plugin-usage/loading-screen
Thanks.

**Comment by demirium** [comment]
Hey,

I know what has been written about this, I created an issue on github because of the response I received on discord. Sorry for unnecessary busyness. Thank you.

https://discord.com/channels/533407895010803753/533413171403292712/1189880003391934485

**Comment by LoneDev6** [comment]
It's okay! I just feel bad when people waste their time as I wrote the wiki exactly to avoid customers from wasting time waiting for me :D 

It's probably an Optifine bug btw. I really have no control over it, the loading screen is known to have issues as Mojang didn't officially provide a way to customize it due to the fact that they care about their copyright.
What you can do in the vanilla game is use the new guide to change the color of the loading screen and hide the logo completely, which I'm sure works without Optifine: https://itemsadder.devs.beer/plugin-usage/loading-screen

**Comment by demirium** [comment]
I understand, thank you for your interest and help. 

Have a nice day and good work!
