### ISSUE TITLE
1.20.2 - Unknown packet ADD_RESOURCE_PACK

### ISSUE THREAD

**Issue by nroj95** [PluginBugs/Issues-ItemsAdder#3272]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

[ProtocolLib] [PacketFilterManager] Plugin ItemsAdder tried to register listener for unknown packet ADD_RESOURCE_PACK[PLAY, SERVER, 68, classNames: [net.minecraft.network.protocol.game.PacketPlayOutResourcePackPushPacket, net.minecraft.network.protocol.game.ClientboundResourcePackPushPacketPacket] (unregistered)] [direction: from SERVER]

### Steps to reproduce the issue

1. Just start the server....

### Server version

This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
You are running the latest version
Previous version: git-Paper-309 (MC: 1.20.2)

### ItemsAdder Version

3.6.3-beta-5

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.42

**Comment by LoneDev6** [comment]
Update ProtocolLib and let me know.
https://ci.dmulloy2.net/job/ProtocolLib/
