### ISSUE TITLE
Add option to disable freezing/walking on powder snow for custom armor

### ISSUE THREAD

**Issue by CrazyCoder9** [PluginBugs/Issues-ItemsAdder#3275]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

The custom armor should have an option to turn off the immunity to powder snow.

### Is your feature request related to a problem?

Yes, I cannot disable the powder snow immunity for custom armors.

(which is a big problem for me because I want to make custom weapons that freeze people)

### Describe alternatives you've considered

I have tried using other plugins and datapacks to disable the immunity, but they did not work or caused further problems.

**Comment by LoneDev6** [comment]
I will make some tests to check if this is actually possible since it might be clientsided.
