### ISSUE TITLE
item_flags is not working in new version

### ISSUE THREAD

**Issue by Slowedgg** [PluginBugs/Issues-ItemsAdder#3276]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I just updated the plugin to the latest version 3.6.3-beta-5 and the item flags stopped working, before updating it worked perfectly. 

### Steps to reproduce the issue

???

### Server version

Current: git-Purpur-2095 (MC: 1.20.2)*
* You are running the latest version

### ItemsAdder Version

3.6.3-beta-5

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.42

### Problematic items yml configuration file (optional)

```shell
steel_ingot_drop:
    display_name: '&#D7D6D4Steel Ingot'
    lore:
    - ':tradable_tag:'
    - ""
    - ' &f◇  &#CCC8C3Steel zombie ingot &f◇ '
    enchants:
      - ARROW_FIRE:1
    item_flags:
      - HIDE_ATTRIBUTES
      - HIDE_DESTROYS
      - HIDE_ENCHANTS
      - HIDE_PLACED_ON
      - HIDE_POTION_EFFECTS
      - HIDE_UNBREAKABLE
    resource:
      material: PAPER
      generate: true
      textures:
      - drops/steel_ingot.png
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/75852372/b3b80db8-04cd-42dd-9b2b-c201e4ba69ba)

**Comment by Slowedgg** [comment]
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/75852372/a031ffef-7bd1-488c-8358-26fda4780e32)

**Comment by LoneDev6** [comment]
Thanks! I will check this as soon as possible
