### ISSUE TITLE
Player stats saving performance optimization on world save

### ISSUE THREAD

**Issue by w1th0utme** [PluginBugs/Issues-ItemsAdder#3286]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/137961937/b8e8f77f-0156-4e99-917f-752670861e73)

I noticed a strange behavior when viewing the Spark profiler with the `--only-ticks-over 100` flag. Is there any way to fix this?

### Steps to reproduce the issue

To make a spark profiler..
`/spark profiler start --only-ticks-over 100`

### Server version

1.20.1

### ItemsAdder Version

3.6.3-beta-5

### ProtocolLib Version

5.1.0

### LoneLibs Version

1.0.42

**Comment by LoneDev6** [comment]
Please post the spark report instead of screenshots.
Thanks
