### ISSUE TITLE
Bug with the hitbox of the furnitures, does not return the expected values.

### ISSUE THREAD

**Issue by paulreob** [PluginBugs/Issues-ItemsAdder#3290]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Hello, I am using the Tooltip plugin (which is open source), which consists in displaying information about the furniture you are looking at by means of a title.

The problem is that if it is stacked or if it is next to another hitbox of another furniture it will show incorrect information, as if it belongs to a single furniture.

It also shows the information instead of the walls, which should not happen (although this seems to be a problem of the plugin itself or not).

I contacted the dev about this problem and he told me that everything was fine and that it is possibly ItemsAdder.

Only happens with furnitures that have a hitbox

Plugin Tooltip: [https://www.spigotmc.org/resources/⭐tooltips.109912/](https://www.spigotmc.org/resources/%E2%AD%90tooltips.109912/)
Code: https://github.com/Septicuss/tooltips/blob/master/src/main/java/fi/septicuss/tooltips/integrations/itemsadder/ItemsAdderFurnitureProvider.java

PD: I tried it with oraxen and it works fine, it shows correctly even if they are stacked (although the info showing through the walls is still visible).

### Steps to reproduce the issue

Furniture stacked or side by side, displayed as if it were a single piece of furniture:
https://streamable.com/59t4s7

Information is displayed through the walls:
https://cdn.discordapp.com/attachments/1161360271604973698/1162866761935360060/2023-10-14_16-36-24.mp4?ex=65a30291&is=65908d91&hm=a4eaa88b5711820893712f498f259799336282588de85036579cdf130a766913&

### Server version

git-Paper-196 (MC: 1.20.1)

### ItemsAdder Version

3.6.3-beta-5

### ProtocolLib Version

5.1.1-SNAPSHOT-669

### LoneLibs Version

 LoneLibs version 1.0.42

**Comment by LoneDev6** [comment]
Should be fixed in 4.0.4
