### ISSUE TITLE
[Suggestion] IA recipes book

### ISSUE THREAD

**Issue by 100petr** [PluginBugs/Issues-ItemsAdder#330]
**Describe alternatives you've considered**
Create a book that players would receive the first time they connect to open the GUI. Players would know about IA items from the beginning. 

**Additional context**
Slimefun already has /sf guide when it first connects, so players know about it right away. I would like the same for IA

**Comment by BlitzGamer-88** [comment]
You could use the plugin ItemJoin to make a custom book which is given to players when they join for the first time and make that book execute the command "/ia" when its clicked.

**Comment by 100petr** [comment]
Resolved via item which opens /ia and I added item to kits via essentials.
