### ISSUE TITLE
textures after /iazip /iatexture /iapack isn´t working

### ISSUE THREAD

**Issue by mario638** [PluginBugs/Issues-ItemsAdder#3300]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

The texture isn´t updating after doing /iazip or /iapack or /iatexture

### Steps to reproduce the issue

Join the server
The texturepack loads perfectly
Use the command /iazip or /iapack or /iatexture
The texturepack isn´t updating in the client

### Server version

Purpur(1985) 1.19.4-R0.1-SNAPSHOT-

### ItemsAdder Version

3.6.3-beta-6

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.43

### Error (optional)

```shell
No errors
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/86148117/cd45ee25-a94c-4afa-9b02-07fd43a3ba5d)

**Comment by LoneDev6** [comment]
> The texturepack isn´t updating in the client

Hard to help you without any information about which hosting method are you using.

also can you reproduce this issue on previous ItemsAdder versions or only 3.6.3-beta-6?

**Comment by mario638** [comment]
@LoneDev6 it happens to a lot of people in this version the other versions works perfectly

**Comment by LoneDev6** [comment]
Strange.
I will do some tests but I didn't change anything in this version about resourcepacks.

**Comment by LoneDev6** [comment]
Fixed, thanks.
Strange it happens only on beta-6. The code didn't change.

**Comment by mario638** [comment]
Also @LoneDev6 if you want add me as beta tester so I can try the plugin if you want

**Comment by LoneDev6** [comment]
Added, in the future you will see pre-release versions on Discord
