### ISSUE TITLE
Head Texture Glitch even after diabling emotes

### ISSUE THREAD

**Issue by tomhmagic** [PluginBugs/Issues-ItemsAdder#3303]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

tomhmagic

### What happened?

Disabling emotes does not fix the head texture glitch and worsens the issue.
Glitches the player head texture

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/80466923/5bb1d079-baa4-4ca4-acc9-05358946c2bf)
the first image before disabling emotes

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/80466923/1b4cc16a-4919-44d7-bb19-d23d2839a427)
second image after disabling emotes

### Steps to reproduce the issue

Install IA
observe head texture glitch
diable emotes
observer persistent glitch and player skins glitch

### Server version

git-Purpur-2090 (MC: 1.20.2)

### ItemsAdder Version

3.6.2-beta-r4

### ProtocolLib Version

5.1.1-SNAPSHOT-669

### LoneLibs Version

1.0.30

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/13851562/latest.log)

**Comment by LoneDev6** [comment]
Regenerate your resourcepack using /iazip after you disable the emotes

**Comment by tomhmagic** [comment]
I have done, as shown in the image, sorry I should have stated that

**Comment by LoneDev6** [comment]
Check if somewhere in the itemsadder contents folder you have the `rendertype_entity_translucent.fsh` or `rendertype_entity_translucent.vsh` file.
Delete them.

**Comment by tomhmagic** [comment]
Fixed the skin issue but head texture glitch still persists with emotes false and /iazip

Now my custom models are broken
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/80466923/ef0cb339-9439-4d21-acb0-770b038f3766)

**Comment by tomhmagic** [comment]
nope, re logging fixed. Heads are back to normal and skin is not glitched
Thank you
