### ISSUE TITLE
Missing skins from the heads. The problem with rendertype_entity_translument

### ISSUE THREAD

**Issue by sungurami** [PluginBugs/Issues-ItemsAdder#3305]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Everything is indicated on the video. By deleting 2 files, I fixed this error. Something is wrong with these files.

> rendertype_entity_translucent.fsh
> rendertype_entity_translucent.vsh

https://github.com/PluginBugs/Issues-ItemsAdder/assets/155883665/b84dc046-e79d-4d19-a3dd-b68b3e0f233d

### Steps to reproduce the issue

1. I have installed the latest version of the plugin
2. Created a standard resource pack itemsadder
3. I got an error. I decided to go through everything that is created in the resource pack and found out that 2 files cause a problem with displaying textures on the heads of players.

### Server version

Paper version git-Paper-319 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder_3.6.3-beta-5

### ProtocolLib Version

ProtocolLib v5.1.1-SNAPSHOT-673

### LoneLibs Version

LoneLibs v1.0.42

**Comment by LoneDev6** [comment]
Disable emotes.
https://itemsadder.devs.beer/faq/placed-heads-texture-glitched
