### ISSUE TITLE
Issue with 3.6.3-beta-7

### ISSUE THREAD

**Issue by RickyLaChow** [PluginBugs/Issues-ItemsAdder#3309]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

rickylachow

### What happened?

Non riesco più a zippare la mia resourcepack dopo l'aggiornamento alla versione 3.6.3.-beta-7 e anche se provo a tornare nella versione beta-6 mi da lo stesso errore come se avesse modificato qualcosa 

### Steps to reproduce the issue

/iazip

### Server version

git-PufferfishPlus-23 (MC: 1.20.2)

### ItemsAdder Version

3.6.3-beta-7

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.44

### FULL server log

https://mclo.gs/cwsOEh8

**Comment by Keebsz** [comment]
I have this same issue too. I tried to delete the ItemAdder folder and my bukkit.yml to see if that fixed the issue, and change back the ItemAdder and LoneLib Versions and had the same error

**Comment by RickyLaChow** [comment]
Yeah, same i have completly deleted the folder and nothing changed now i'm trying with a backup and old jars

**Comment by LoneDev6** [comment]
Update LoneLibs to 1.0.45, thanks for the report
https://www.spigotmc.org/resources/lonelibs.75974
