### ISSUE TITLE
Text color

### ISSUE THREAD

**Issue by BronzWarq** [PluginBugs/Issues-ItemsAdder#3311]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

sholomon

### What happened?

Hi, I just updated ItemsAdder and LoneLibs then did a /iazip.

### Steps to reproduce the issue

for RPGcolor i use https://www.birdflop.com/resources/rgb/

### Server version

git-Purpur-2095 (MC: 1.20.2)

### ItemsAdder Version

ItemsAdder version 3.6.3-beta-7

### ProtocolLib Version

ProtocolLib v5.1.1-SNAPSHOT-673

### LoneLibs Version

LoneLibs v1.0.45

### FULL server log

https://paste.helpch.at/roxokomuko.makefile

### Screenshots/Videos (you can drag and drop files or paste links)

![2024-01-10_00 08 05](https://github.com/PluginBugs/Issues-ItemsAdder/assets/123677392/4065d9db-ea02-4b3b-b1bb-34b3ba29cac3)

**Comment by LoneDev6** [comment]
Use this instead: `<gradient:#ff00ee:#f79459>Broooooo`
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/9db2d631-f3a0-42c6-a871-8d3a41495f04)

I used this website to preview: https://webui.advntr.dev/
I updated my wiki with an example: <https://itemsadder.devs.beer/plugin-usage/hex-colored-texts-1.16+>
