### ISSUE TITLE
Plugin turns red

### ISSUE THREAD

**Issue by Bohneeeeee** [PluginBugs/Issues-ItemsAdder#3312]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

After a time the Plugin dont work and it Turn red without something in the Console

### Steps to reproduce the issue

1. Console Check
2. Console check after Startup
3. Resetup the whole plugin

### Server version

1.19.4

### ItemsAdder Version

3.6.1

### ProtocolLib Version

5.2.0

### LoneLibs Version

1.0.27

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/13886775/latest.log)

**Comment by LoneDev6** [comment]
This log doesn't contain any info about ItemsAdder.
Post a complete log of when you run the plugin.

**Comment by Bohneeeeee** [comment]
[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/13891105/latest.log)
