### ISSUE TITLE
Emoji not parsing on 1.20.4

### ISSUE THREAD

**Issue by RickyLaChow** [PluginBugs/Issues-ItemsAdder#3313]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

rickylachow

### What happened?

Se scrivo :emoji: viene l'emoji corretta, mentre se viene mandato dal server non viene fatto il parsing, ho fatto anche iareload e non me la imposta come tag 

### Steps to reproduce the issue

sendMessage from server

### Server version

[12:51:44 INFO]: This server is running Paper version git-Paper-381 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 07b956e)
You are running the latest version

### ItemsAdder Version

[12:52:00 INFO]: ItemsAdder version 3.6.3-beta-7

### ProtocolLib Version

[12:52:08 INFO]: ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

[12:52:15 INFO]: LoneLibs version 1.0.45

### Screenshots/Videos (you can drag and drop files or paste links)

https://imgur.com/a/IafzzRs

**Comment by LoneDev6** [comment]
Mojang continua a cambiare come funzionano i pacchetti della chat, quindi devo di nuovo capire cosa hanno cambiato e correggere.
Grazie
