### ISSUE TITLE
resource pack issue

### ISSUE THREAD

**Issue by Hanna2513** [PluginBugs/Issues-ItemsAdder#3314]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I cant find the resource pack

### Steps to reproduce the issue

when I go to itemadder wiki and go to installation and try to find the resource pack I just cant find it 

### ItemsAdder Version

3.6.3-beta-7

### ProtocolLib Version

1.20.1

### LoneLibs Version

1.20.1

**Comment by LoneDev6** [comment]
Please do not use this to ask for support about installation, this is a place to report bugs and issues of the plugin.
Thanks!

There is a step by step tutorial on how to configure the plugin and takes less than 5 minutes to complete.
Install tutorial: https://itemsadder.devs.beer/first-install
Resourcepack hosting guides: https://itemsadder.devs.beer/plugin-usage/resourcepack-hosting

If you are searching for the default items/configurations you can download them by reading the installation tutorial.
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/9be1542a-178d-416d-9138-9638ddecc731)

**Comment by Hanna2513** [comment]
No Thats not what I mean I know there is a wiki but I cant find the installation button for the resource pack


![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/103963090/a8955fc5-dd4f-4615-9ec5-62bba2d243ae)

**Comment by Hanna2513** [comment]
> Please do not use this to ask for support about installation, this is a place to report bugs and issues of the plugin. Thanks!
> 
> There is a step by step tutorial on how to configure the plugin and takes less than 5 minutes to complete. Install tutorial: https://itemsadder.devs.beer/first-install Resourcepack hosting guides: https://itemsadder.devs.beer/plugin-usage/resourcepack-hosting
> 
> If you are searching for the default items/configurations you can download them by reading the installation tutorial. ![image](https://private-user-images.githubusercontent.com/27242001/295620844-9be1542a-178d-416d-9138-9638ddecc731.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MDI0OTksIm5iZiI6MTcwNDkwMjE5OSwicGF0aCI6Ii8yNzI0MjAwMS8yOTU2MjA4NDQtOWJlMTU0MmEtMTc4ZC00MTZkLTkxMzgtOTYzOGRkZWNjNzMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDE1NTYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhMmFlNzY2NGZiZWIwMzRjMzc0ZmFmM2FhYTc1NWIyOGIxZGMzZGYzNzc5MWU2MTk4MjNkMzJlZmQ3ZjU0ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8gYi5NUI78zcNnuvCFaaH7ccao0HHMJ7IuKiZkJXXIc)

No Thats not what I mean I know there is a wiki but I cant find the installation button for the resource pack 
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/103963090/fe587d21-dae1-4ec5-b5f3-5b7ced24008f)

**Comment by LoneDev6** [comment]
What do you mean by "installation button"?

The default assets can be downloaded here https://github.com/ItemsAdder/DefaultPack/releases/tag/2.0.10
More precisely press on the button [default_pack_2.0.10.zip](https://github.com/ItemsAdder/DefaultPack/releases/download/2.0.10/default_pack_2.0.10.zip) and complete the installation steps.

> Download the latest version of the DefaultPack: [DOWNLOAD](https://github.com/ItemsAdder/DefaultPack/releases/latest)
Extract the content into the ItemAdder folder and overwrite the files if asked
Run the /iazip command (and follow your [hosting method](https://github.com/plugin-usage/resourcepack-hosting) if you're not using self-host).

**Comment by Hanna2513** [comment]
I mean the resource pack installation button for the item adder

**Comment by LoneDev6** [comment]
>  I cant find the installation button for the resource pack

Please read here: https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown#my-players-cant-see-textures-but-ive-followed-the-whole-tutorial

More specifically:

> - Enable the resourcepack in the server list settings: http://imgur.com/a/SG0AU
> - Make sure you don't have any inventory (GUI) or book opening on join.
>

**Comment by Hanna2513** [comment]
If you mean the when the plugin is loaded it will ask me to load the
resource pack  or If I am enabled to this server to load resource pack with
out ask , I have a problem cause when I go to resource pack to check all
the loaded resource pack I dont see the item adder resource pack so If you
can , please send me the resource pack file

**Comment by Hanna2513** [comment]
I Edit the server to make it enable resource pack but it's not even
working [image:
image.png]this is what I see cause there isn't a resource pack , so for the
second time please if you can give me the resource pack file , and If that
will help you I'm using the https://exaroton.com server hosting

**Comment by LoneDev6** [comment]
I don't see any image in your message.

I cannot send you the resourcepack, the plugin must generate it from the files in your contents folder of ItemsAdder.
Please follow the tutorial, it's clear and more than [7500 servers](https://pstats.devs.beer/plugin/bukkit/ItemsAdder/6) are using it without issues.
I wrote the tutorial exactly to avoid customers from waiting for me or to have difficulties understanding the configuration process.
I even made some videos which are available on the wiki.

If you're not satisfied with the plugin and you feel like it's too difficult please confirm and I will refund you as soon as possible.
Provide me your PayPal email or your market profile URL and name so I can issue the refund.
Please let me know.

**Comment by Hanna2513** [comment]
That's Not what I mean, I Need help so first 1. Does this plugin work on
the https://exaroton.com server, the server hosting that I use, 2. Where
can I find the resource pack in the plugin file,3. Is there a tutorial
video to set up the plugin cause I didn't find a helpfully video

**Comment by LoneDev6** [comment]
1. you have to use external host, for example dropbox to host your pack.
2. `output/generated.zip`
3. https://itemsadder.devs.beer/plugin-usage/resourcepack-hosting/resourcepack-on-dropbox
Or you can read the [LobFile tutorial](https://itemsadder.devs.beer/plugin-usage/resourcepack-hosting/lobfile-hosting), it's not really hard if you read carefully.

**Comment by Hanna2513** [comment]
I have positive news . I load the resource pack but I didn’t work on the
server I tried the Dropbox , drive way . But I tried to load it to My
Minecraft files and it loaded . but what way do you prefer to use to load
the resource pack ??

**Comment by Hanna2513** [comment]
Hello, I've been waiting for your response, Could You help me with what I
sent you 5 days ago?
