### ISSUE TITLE
vehicle and plants improvement

### ISSUE THREAD

**Issue by RitsuElAnti** [PluginBugs/Issues-ItemsAdder#3315]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Ritsu#9014

### Describe the solution you'd like

having vehicles with different particles visible in the exhaust or surrounding the vehicle,have infinite fuel to test the vehicle and be able to give it as something special, being able to create ships where you can sail with a friend, being able to have more variety of crops just by changing their textures.

### Is your feature request related to a problem?

I would like more particles to be used with vehicles, in addition to "smoke", the possibility of giving a vehicle the option of "infinite fuel", I would also like it to be possible to add boat or submarine type vehicles in some way, and It would also be nice to have plants whose growth textures could be changed.
From already thank you very much

### Describe alternatives you've considered

for particles add an option where you can write the particle to use,with boats you cannot spawn a pig and an invisible boat to have
,and the texture of the plants cannot be given another loading path in order

**Comment by LoneDev6** [comment]
Please do not report multiple issues/requests on the same page, I separated them:
https://github.com/PluginBugs/Issues-ItemsAdder/issues/3319
https://github.com/PluginBugs/Issues-ItemsAdder/issues/3320

The crops idea is already planned, not straight forward to be implemented but definitely will work on it.
https://github.com/PluginBugs/Issues-ItemsAdder/issues/554
