### ISSUE TITLE
Color code is not applied

### ISSUE THREAD

**Issue by cyclsunmark** [PluginBugs/Issues-ItemsAdder#3324]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

cyclsunmark

### What happened?

The color code does not seem to be applied.

### Steps to reproduce the issue

1. Use the latest ITEMSADDER
2. Do /IA
3. See the color code written items

### Server version

Current: git-Purpur-2062 (MC: 1.20.1)*
Previous: git-Purpur-2060 (MC: 1.20.1)
* You are running the latest version

### ItemsAdder Version

ItemsAdder version 3.6.3-beta-7
Customized Minecraft without client mods!
Website: devs.beer
Author: LoneDev

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679
Provides read/write access to the Minecraft protocol.
Authors: dmulloy2 and comphenix

### LoneLibs Version

LoneLibs version 1.0.43
Collection of libs used by my plugins
Authors: LoneDev and others

### Screenshots/Videos (you can drag and drop files or paste links)

![스크린샷 2024-01-12 230610](https://github.com/PluginBugs/Issues-ItemsAdder/assets/107739755/deb5ae77-3ef7-42ae-9111-7eb66eee3b1c)

**Comment by LoneDev6** [comment]
Update LoneLibshttps://www.spigotmc.org/resources/lonelibs.75974/

**Comment by cyclsunmark** [comment]
RGB doesn't work even if you upgrade the version.

**Comment by LoneDev6** [comment]
Use this for RGB: <https://itemsadder.devs.beer/plugin-usage/hex-colored-texts-1.16+>

Example: `<#FE5A00>Magic Fuel`

**Comment by cyclsunmark** [comment]
That's how it is.

**Comment by LoneDev6** [comment]
Works, correct? The hex example was tested and working

**Comment by cyclsunmark** [comment]
&aFrog's <#424242>Netherite Coin!
It doesn't work

**Comment by LoneDev6** [comment]
Because you're mixing colors methods, there should also be a warning in console about that if you mix colors methods.
`<green>Frog's <#424242>Netherite Coin!`
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/d934e7f3-470d-4d7f-96f3-c4126b03578c)

You can use this editor as shown in the tutorial: https://webui.advntr.dev/

**Comment by LoneDev6** [comment]
No problem, happy new year to you too! :D
Good luck with your server project
