### ISSUE TITLE
Learn all recipes from a single namespace

### ISSUE THREAD

**Issue by ImNotASpy** [PluginBugs/Issues-ItemsAdder#3325]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

imnotaspy

### Describe the solution you'd like

Thanks for your awesome plugin and effort put into it. As far as I know from my searches for this feature, I was unable to find something similar. Maybe it is called something else that I am not aware of.

I want to give my players all recipes in a namespace, instead of going through 1 by one. I want people to have the recipes for this specific namespace "munchies" but not my other items in IA. I want those to be natural recipe learning. Players do not have access to see the ItemsAdder interface. 

I am only aware of two ways to give all recipes: the permissions and when the player picks up the ingredient it appears or by single recipe command. I am looking for an all recipes command per namespace. In this particular namespace "munchies," there are nearly 200 recipes and not all players are online at all times for me to give them one by one.

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/100103655/16d7e300-e75d-4b3c-bc04-fb283fc97ae6)

### Is your feature request related to a problem?

no

### Describe alternatives you've considered

Doing one by one method while the most players are online.  Unfortunately, this is too time consuming. 

Also have considered not giving them the recipe, but then the players do not know the extent of the recipes from the namespace.

I have also considered giving the players permission to see these recipes in the IA interface, but I want to create a server where players do not need to use a lot of commands. 

It is possible that I could make a specific "crafting table" that shows only the recipes from this namespace, but I am not sure how to do this. 

### Additional context

Please let me know if you have any ideas or workarounds, or if there can be such a command implemented :) Thank you so much!

**Comment by LoneDev6** [comment]
This should work: `/recipe give PLAYER munchies:*`
