### ISSUE TITLE
Import of ModelEngine Resourcepack messes with models

### ISSUE THREAD

**Issue by mkhansen981017** [PluginBugs/Issues-ItemsAdder#3326]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

mkhansen981017

### What happened?

When running `/iazip` and having the plugin configured to merge the resource pack generated to ModelEngine, The import/ merge of the resource pack of ModelEngine into ItemsAdder seems to mess with the models.

I have tried to only install one "pack" to rule out any misconfiguration.

Above is states that running the latest version is required - I did update to the latest beta of ItemsAdder 3.6.3-beta-7 as well as the LoneLibs 1.0.45 which changed nothing - issue still persisted

### Steps to reproduce the issue

- Run /meg reload models
- run /iazip
- get messed up models

### Server version

[21:26:02 INFO]: Current: git-Purpur-2095 (MC: 1.20.2)*
Previous: git-Purpur-1985 (MC: 1.19.4)

### ItemsAdder Version

[21:25:29 INFO]: ItemsAdder version 3.6.2c
[21:25:29 INFO]: Customized Minecraft without client mods!
[21:25:29 INFO]: Website: devs.beer
[21:25:29 INFO]: Author: LoneDev

### ProtocolLib Version

[21:25:12 INFO]: ProtocolLib version 5.2.0-SNAPSHOT-679
[21:25:12 INFO]: Provides read/write access to the Minecraft protocol.
[21:25:12 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[21:26:33 INFO]: LoneLibs version 1.0.31
[21:26:33 INFO]: Collection of libs used by my plugins
[21:26:33 INFO]: Authors: LoneDev and others

### Error (optional)

```shell
No errors are thrown in the console
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/13025353/31c13652-3945-4abc-b839-bbaa039873b5)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/13025353/e8558d99-2d58-42a5-a5ea-b920d10c02a3)

**Comment by GramatonsSan** [comment]
I faced the same problem. Adding additional information does not matter, since everything is identical to the author of the request

**Comment by mkhansen981017** [comment]
Ran a binary for the 16 thousand time and found a sneaky little leather_horse_armor.json file in a folder it was not supposed to be in.

**Comment by LoneDev6** [comment]
ItemsAdder generates only one `leather_horse_armor.json` file so probably it was from another pack merged manually.
Thanks for updating me on the issue cause.

Have a nice week! :D
