### ISSUE TITLE
Add hook to zNPCsPlus for ia entity

### ISSUE THREAD

**Issue by NoltoxGit** [PluginBugs/Issues-ItemsAdder#3329]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

jonquille

### Describe the solution you'd like

Hello,
Would it be possible to add [zNPCsPlus](https://github.com/Pyrbu/ZNPCsPlus) plugin support in addition to [Citizens](https://github.com/CitizensDev/Citizens2) please ?

### Is your feature request related to a problem?

No, but it would make it possible to replace the Citizens plugin (which is quite performance-hungry) with zNPCs, which is much lighter.

### Describe alternatives you've considered

There are no alternatives.

**Comment by LoneDev6** [comment]
I will have to check if their API is easy to use and I'll let you know.
Thanks for the idea

**Comment by NoltoxGit** [comment]
> I will have to check if their API is easy to use and I'll let you know. Thanks for the idea

Hello,
Do you have any news about this ? It will be a verry good idea :D
