### ISSUE TITLE
Console error spam when achievement pops up

### ISSUE THREAD

**Issue by SnowBlitzz** [PluginBugs/Issues-ItemsAdder#3331]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

SnowBlitzz

### What happened?

A long error pops up in console when someone gets an achievement
error: https://pastebin.com/LirTNSNZ

### Steps to reproduce the issue

1. Get an achievement in-game
2. This error will pop up and spam console

### Server version

1.16.5

### ItemsAdder Version

ItemsAdder_3.6.2c

### ProtocolLib Version

5.1.0

### LoneLibs Version

1.0.45

### FULL server log

https://pastebin.com/LirTNSNZ

**Comment by LoneDev6** [comment]
Can you update ItemsAdder and LoneLibs?
I fixed this issue some time ago: https://github.com/PluginBugs/Issues-ItemsAdder/issues/3282
