### ISSUE TITLE
Failed to check ClientboundSystemChatPacket for adventure Component field

### ISSUE THREAD

**Issue by Zocamingg** [PluginBugs/Issues-ItemsAdder#3334]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Zocaming#0001

### What happened?

![Screenshot_2024-01-14-20-43-31-89_2665fb67b16260a8d818298cef8dc107](https://github.com/PluginBugs/Issues-ItemsAdder/assets/94791135/97007ba8-a05b-49be-b8b1-9d8fe139e906)

### Steps to reproduce the issue

I'm getting this error when opening the server

### Server version

1.17.1 Pufferfish 

### ItemsAdder Version

ItemsAdder 3.6.3-beta-7

### ProtocolLib Version

Protocollib Version 5.2.0-SNAPSHOT-679

### LoneLibs Version

Lonelibs version 1.0.45

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/13932547/latest.log)

**Comment by LoneDev6** [comment]
Update [ProtocoLib](https://ci.dmulloy2.net/job/ProtocolLib/).

**Comment by Zocamingg** [comment]
> Update [ProtocoLib](https://ci.dmulloy2.net/job/ProtocolLib/).

already latest

**Comment by Zocamingg** [comment]
Already up-to-date

**Comment by LoneDev6** [comment]
Thanks, it's due to 1.17.1 missing a particular packet.
I will fix that as soon as possible.

**Comment by Zocamingg** [comment]
Thanks
