### ISSUE TITLE
No permission to craft a particular recipe

### ISSUE THREAD

**Issue by Lerphie** [PluginBugs/Issues-ItemsAdder#3341]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

mc_coder

### What happened?

It's a very strange bug. Player cannot create a saber in the workbench. But the server administrator can do it. Below I have discounted you the full configuration of recipes. All rights to the recipe the player has.
https://youtu.be/P4fHCBmxC5w

### Steps to reproduce the issue

*

### Server version

This server is running GuardSpigot 1.16.5 version git-Airplane-"e37fa86" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### ItemsAdder Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/66962762/20ce1a8c-f411-4057-b276-8dba53aaf7c9)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/66962762/56513d35-beda-434c-9d67-133b4a736ce1)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/66962762/e8292174-ce1f-4461-98e7-7090ffa535e3)

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: myitems
recipes:
  crafting_table:

    diamond_sai:
      permission: diamond_weapon
      enabled: true
      pattern:
        - XXD
        - DDX
        - SDX
      ingredients:
        D: diamond
        S: stick
      result:
        item: diamond_sai
        amount: 1

    diamond_rapier:
      permission: diamond_weapon
      enabled: true
      pattern:
        - XXD
        - XDX
        - WXX
      ingredients:
        D: diamond
        W: diamond_sai
      result:
        item: diamond_rapier
        amount: 1


    diamond_saber:
      permission: diamond_weapon
      enabled: true
      pattern:
        - XXD
        - DDX
        - WXX
      ingredients:
        D: diamond
        W: diamond_rapier
      result:
        item: diamond_saber
        amount: 1
```

**Comment by Lerphie** [comment]
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/66962762/4c4b2779-ac58-407c-988d-dcf87669f088)

**Comment by LoneDev6** [comment]
> All rights to the recipe the player has.

Please make sure to read the permissions wiki page and double check if you actually have permissions.
For example you should have `ia.user.recipe.diamond_weapon`

Info on recipes permissions: https://itemsadder.devs.beer/plugin-usage/adding-content/item-properties/permission#recipes-permissions
More info on permissions: https://itemsadder.devs.beer/plugin-usage/permissions#permissions


> Other diamond weapons the player can craft, but the saber cannot. Here is proof that the player has permission:

`ia.user.craft.*` is old, should not be used anymore, although it should work fine... strange.
I see you're using a plugin to preview recipes, can you try to delete it?

**Comment by Lerphie** [comment]
Still the recipes don't work. I'm going to try deleting my plugin
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/66962762/a365d6e0-af98-4f23-89d3-019950bb8c0e)

**Comment by Lerphie** [comment]
I uninstalled the plugin on recipes, didn't help. I also noticed that the item can not be moved to the inventory when opening the workbench
https://youtu.be/kEumPmdGkCQ

**Comment by Lerphie** [comment]
Don't you think it's strange that other weapons with similar authorization can be created, but this particular saber cannot?

**Comment by LoneDev6** [comment]
> Don't you think it's strange that other weapons with similar authorization can be created, but this particular saber cannot?

Yes it is.
Can you try to create another recipe with different ingredients and with a new permission name and test?
Let me know

**Comment by Lerphie** [comment]
> Yes it is. Can you try to create another recipe with different ingredients and with a new permission name and test? Let me know

I even made more, watch the clip carefully and to the end ;d
https://youtu.be/OxvgcZi2Cc0

**Comment by Lerphie** [comment]
@LoneDev6 Why don't I give you my ItemsAdder folder so you can test it on your own server?

**Comment by LoneDev6** [comment]
Create a private "payment issue" thread on my forum and share the file there, so no one can download it other than me.
Thanks.
https://forum.devs.beer/

**Comment by Lerphie** [comment]
> Create a private "payment issue" thread on my forum and share the file there, so no one can download it other than me. Thanks. https://forum.devs.beer/

I sent you my files

**Comment by LoneDev6** [comment]
I cannot reproduce the issue with your files, there might be another plugin interfering.

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/a7aea785-7975-4067-be99-ffc6e42ae3e0)

https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/bbae146a-0bcf-4a81-8ca7-1d8bfd2c748c

**Comment by Lerphie** [comment]
@LoneDev6 
Hi. I found another problem with the recipes. Please check this out:
https://forum.devs.beer/d/1975-cosmeticscore-private-help-optimization-issue-176/5
