### ISSUE TITLE
Duplication bug with ores

### ISSUE THREAD

**Issue by Belceebuh** [PluginBugs/Issues-ItemsAdder#3342]
Discord tag (optional)
belzzebuh

What happened?
you can duplicate custom minerals from itemsadder by placing a block on top of it and making it break, this only happens with spikes with a series of enchantments, so I don't know what it can be but I leave an attached image with the enchantments, they are from the EcoEnchants plugin.

Steps to reproduce the issue
follow the video

Server version
No response

ItemsAdder Version
ItemsAdder version 3.6.3-beta-5

ProtocolLib Version
ProtocolLib version 5.1.1-SNAPSHOT-668

LoneLibs Version
LoneLibs version 1.0.42

FULL server log
No response

Error (optional)
No response

Problematic items yml configuration file (optional)
No response

Other files, you can drag and drop them here to upload. (optional)
No response

Screenshots/Videos (you can drag and drop files or paste links)
Video: https://youtu.be/6ExdNYZiutI

![](https://github.com/PluginBugs/Issues-ItemsAdder/assets/90662594/bc19e3b9-087e-4d2d-b972-aaa9b0b6bc9a)

**Comment by LoneDev6** [comment]
Next time avoid reporting duplication bugs publicly, a new violation will lead to a termination of your account.
People can abuse duplication bugs if they are published publicly online.
I explicitly wrote that you must not report this kind of bugs on Github. 


![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/a59e99cd-e272-4a18-ab0b-5f9ced9b291f)

**Comment by LoneDev6** [comment]
I see that the enchants are from EcoEnchants.
This most likely is an issue caused by the other plugin, please consider sending this report also to the dev of EcoEnchants so that we can discuss about it here.

**Comment by Belceebuh** [comment]
I had forgotten about this, now I will tell the owner since this problem is still going on. @LoneDev6
