### ISSUE TITLE
Invalid Player Data

### ISSUE THREAD

**Issue by Zocamingg** [PluginBugs/Issues-ItemsAdder#3345]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Zocaming

### What happened?

https://drive.google.com/file/d/1OrSaGEOvgHa8xF0u_uHrWC34erFFmm0o/view?usp=drivesdk

### Steps to reproduce the issue

Unable to enter the server while Itemsadder is active

### Server version

Pufferfish 1.17.1

### ItemsAdder Version

ItemsAdder 3.6.3-beta-8

### ProtocolLib Version

Protocollib Version 5.2.0-SNAPSHOT-679

### LoneLibs Version

Lonelibs version 1.0.45

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/13963021/latest.log)

**Comment by LoneDev6** [comment]
You're using an unofficial fork of Spigot.

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/45836f49-769f-4923-acfb-66e611a19339)

Anyway I can't find anything in the logs.
This might be caused by Bungeecord. Try to update it.
Try to remove GrimAC and other packet related plugins.
Try to update ProtocolLib.

Let me know.

**Comment by PortableGames** [comment]
It's funny how you try to please everyone. The same functionality as your plugin we can achieve today via fabric server side even in datapack . Think about upgrading and abandoning old versions of mc

**Comment by minecraft-dripdrop** [comment]
please look this https://github.com/dmulloy2/ProtocolLib/issues/2644

I have the same issue,and someone said "The problem is that some plugins sends a list of recipes to the client while the login has not been completed yet."So maybe itemsadder's recipe?

**Comment by LoneDev6** [comment]
Thanks for the info.
I'm almost sure that I don't do that as I just intercept the packet and change it, so the server is responsable to send it at the right time. I don't send any extra packet. I will double check later and let you know.

**Comment by LoneDev6** [comment]
The only thing I do is sending the recipes packet when PlayerJoinEvent event is triggered.
I expect the Spigot server to have already completed every join related packet before that event, if not then it's a bad design.

Anyway I don't see why i cannot trigger this issue on a test server with ItemsAdder only installed.
Maybe it's related to ProtocoLib not being updated to the latest version?
