### ISSUE TITLE
[Suggestion] Allows configuration to restore thirst by eating some default foods

### ISSUE THREAD

**Issue by yebanme** [PluginBugs/Issues-ItemsAdder#335]
When players eat watermelon or drink milk, restore their own thirst value

Add configuration such as
`melon_slice: 4
milk_bucket: 8`
'melon_slice' and 'milk_bucket' can be customized to any edible item,4 and 8 indicate how much thirst the item restores

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/413
