### ISSUE TITLE
Having Problems with tags ( emojis )

### ISSUE THREAD

**Issue by KianRMC** [PluginBugs/Issues-ItemsAdder#3353]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

soo im new to these stuff so im not sure that if this is a bug or im the one whos doing this wrong ._.
my problem is that emojis are just not working .. like i use : smile : in the chat but all i get is something like that [] i don't know whats wrong with it and i tested everything i could even did the youtube tutorials also did it in a different version of spigot and still nothing ..

### Steps to reproduce the issue

1. im using the default pack
2. and im trying to use the emojis ( in the chat , tab , scoreboard )
3. and its just not working for no reason
4. not working in any other versions as well

### Server version

my server version is 1.20.4 spigot
and i also tested this on my 1.19.2 spigot server still not working

### ItemsAdder Version

3.6.3-beta-8 ( i also tested the latest version 3.6.3-beta-9 ) still not working

### ProtocolLib Version

ProtocolLib : 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs : 1.0.45

**Comment by LoneDev6** [comment]
Please refer to the wiki to know why your particular emoji is not loading.
It's the same tutorial I'd read to help you directly, there is no other way.
https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown
https://itemsadder.devs.beer/faq/characters

Basically read both CLIENT and SERVER log of when you run /iazip and when you install the resourcepack on join to find details of why the emoji/rank texture didn't load.
