### ISSUE TITLE
1.20.4 players have to download the resource pack on every join

### ISSUE THREAD

**Issue by RoVaSte** [PluginBugs/Issues-ItemsAdder#3360]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Players have to download the resource pack on every join

### Steps to reproduce the issue

1. Join the server and download the resourcepack
2. Leave the server
3. Rejoin the server

### Server version

This server is running Paper version git-Paper-"07b956e" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 07b956e)
You are 36 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-"b4e3b3d" (MC: 1.20.1)

### ItemsAdder Version

3.6.3-beta-9

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

### FULL server log

https://paste.denizenscript.com/View/119640

**Comment by LoneDev6** [comment]
Post your itemsadder configuration file.
Post the output of `/iainfo` command.
Anyway for some reason your server has no internet access, this might be the issue.
I see lot of plugins have issues connecting to the web.

**Comment by RoVaSte** [comment]
What would be the problem with the connection? I am currently using Pebble Host 🤔 

/iainfo:
23.01 12:58:51 [Server] [INFO] -=[ ItemsAdder ]=-
23.01 12:58:51 [Server] [INFO] Version: 3.6.3-beta-9
23.01 12:58:51 [Server] [INFO] ResourcePack
23.01 12:58:51 [Server] [INFO] Path: /server591401/plugins/ItemsAdder/output/generated.zip
23.01 12:58:51 [Server] [INFO] Download: https://lobfile.com/file/VdBF.zip
23.01 12:58:51 [Server] [INFO] Size: 13 MB/250 MB
23.01 12:58:51 [Server] [INFO] Last update: 2024-01-21 18:17:25
23.01 12:58:51 [Server] [INFO] Host type: lobfile
23.01 12:58:51 [Server] [INFO] Data
23.01 12:58:51 [Server] [INFO] Items: 182
23.01 12:58:51 [Server] [INFO] Items in /ia: 169
23.01 12:58:51 [Server] [INFO] Namespaces: 14
23.01 12:58:51 [Server] [INFO] Materials: 6
23.01 12:58:51 [Server] [INFO] REAL block IDs: 0/191
23.01 12:58:51 [Server] [INFO] REAL_NOTE block IDs: 0/750
23.01 12:58:51 [Server] [INFO] REAL_TRANSPARENT block IDs: 0/63
23.01 12:58:51 [Server] [INFO] REAL_WIRE block IDs: 0/127
23.01 12:58:51 [Server] [INFO] FIRE block IDs: 0/14
23.01 12:58:51 [Server] [INFO] Font images: 672/6608
23.01 12:58:51 [Server] [INFO] Loaded chunks (3692)
23.01 12:58:51 [Server] [INFO] Armorstands: 36
23.01 12:58:51 [Server] [INFO] Mobs: 0

Config: 
https://paste.denizenscript.com/View/119663

**Comment by LoneDev6** [comment]
> Players have to download the resource pack on every join

By "download" you mean that the game clearly tells you "downloading"?
Because if you mean that is shows the progress bar it's normal, it's applying the pack, not redownloading it each time.


Let me know

**Comment by RoVaSte** [comment]
Yes, it tells "downloading 1../100%"

**Comment by Li2424** [comment]
I have the same issue, I even tried it on a server with only ItemsAdder and the default pack installed using a completely vanilla 1.20.4 client and the bug still occured. This also seems to only happen in 1.20.4.

**Comment by LoneDev6** [comment]
Do you have BungeePackFix installed? (if you're using Bungeecord)

**Comment by Li2424** [comment]
I'm not using bungecoord, so that can't be the issue...
I tried to change all related ItemsAdder config options, I also created a new test server and switched the resource pack but the bug still occured. It isn't really possible to reproduce this bug when using localhost because it almost instantly downloads the pack.

It could probably be related to the file hash, there's this line on the 1.20.3 update page: _"If the hash of a pack is not set, this pack will be redownloaded before every application. Previously, if the hash was missing, the latest downloaded version of pack was applied."_

**Comment by RoVaSte** [comment]
hi, do you have an ETA for the 3.6.3-beta-10 version?

**Comment by LoneDev6** [comment]
I had to change PC due to issues so I'm setting it up.
It might take a week or so.

I will have to do some other tests but last time I tested I couldn't reproduce the issue noted here.

**Comment by RoVaSte** [comment]
have you tried using 1.20.4? 🤔

**Comment by LoneDev6** [comment]
Yes

**Comment by RoVaSte** [comment]
that's strange

**Comment by Li2424** [comment]
The strangest thing is that I didn't change anything in the IA config besides enabling self-host and setting the server IP when testing this. Like I already said, if you tested the issue on localhost, the download is way too quick to see the downloading screen, so that could be the reason why you weren't able to reproduce it... I tested it on a server host and you could clearly see the download progress everytime (yes, I opened the port there and everything worked fine before updating to 1.20.3)...

**Comment by LoneDev6** [comment]
Found the issue.
The new 1.20.4 resourcepacks work in a different way and they don't accept empty hash anymore.
I have to implement something for 1.20.4 but might slowdown processing.

**Comment by RoVaSte** [comment]
Great to hear that you have found the issue! Nice work.
