### ISSUE TITLE
Add Durability Change Event to ItemsAdder API

### ISSUE THREAD

**Issue by Flandreqwq** [PluginBugs/Issues-ItemsAdder#3363]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

芙兰朵露·斯卡蕾特#4453

### Describe the solution you'd like

I'd like ItemsAdder API to provide some events related to custom durability changes. This allows for some cool features, such as the ability to create a debuff that increases the durability of the player's items.

### Is your feature request related to a problem?

When the player uses a tool with custom durability to break a custom block, the tool loses durability, but does not trigger PlayerItemDamageEvent. I'm guessing it's the code inside the ItemsAdder that deducts the durability of the tool, but frustratingly, I can't get the event directly.

### Describe alternatives you've considered

I've tried listening the PlayerItemDamageEvent event, but as mentioned above, breaking a custom block by a tool with custom durability won't trigger this event.

**Comment by LoneDev6** [comment]
ItemsAdder already triggers the vanilla durability change, so you can refer to it and change the durability amount change.
It should work, let me know.
