### ISSUE TITLE
Error about merchant recipes: java.util.ConcurrentModificationException: null

### ISSUE THREAD

**Issue by Blskk** [PluginBugs/Issues-ItemsAdder#3364]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

In the transaction with the villagers, an error occurred. I don't know the reason for this. Can you tell me
My English is not good, I hope you can understand it

### Steps to reproduce the issue

Trading with Vanilla Villagers

### Server version

This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)

### ItemsAdder Version

[16:44:54 INFO]: ItemsAdder version 3.6.3-beta-9
[16:44:54 INFO]: Customized Minecraft without client mods!
[16:44:54 INFO]: Website: devs.beer
[16:44:54 INFO]: Author: LoneDev

### ProtocolLib Version

[16:45:23 INFO]: ProtocolLib version 5.2.0-SNAPSHOT-679
[16:45:23 INFO]: Provides read/write access to the Minecraft protocol.
[16:45:23 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[16:45:46 INFO]: LoneLibs version 1.0.45
[16:45:46 INFO]: Collection of libs used by my plugins
[16:45:46 INFO]: Authors: LoneDev and others

### Problematic items yml configuration file (optional)

```shell
https://mclo.gs/Ye9XjhH
```

**Comment by LoneDev6** [comment]
Any idea how to trigger this issue?
Maybe multiple players accessing the same trading GUI at the same time?
Please let me know, thanks!
