### ISSUE TITLE
Add `armors_hex_colors_cache.yml`. Let ItemsAdder to automatically pick hex color for `armors_rendering`

### ISSUE THREAD

**Issue by EpicPlayerA10** [PluginBugs/Issues-ItemsAdder#3377]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

epicplayera10

### Describe the solution you'd like

Add `armors_hex_colors_cache.yml`. The itemsadder would automatically pick hex color for `armors_rendering`, instead of manually picking hex color. It would be very helpful, because a hex color acts like an indentifier for custom armor.

### Is your feature request related to a problem?

Sometimes when I upload some custom armor packs, then it would clash with existing custom armors hex colors. Then itemsadder tries to fix this by shifting hex colors of some custom armors to free up space for new custom armors. And then custom armors that are in players' inventories are now displaying different armor when equipped.

### Describe alternatives you've considered

.

**Comment by LoneDev6** [comment]
It already does that automatically without the need of a cache file.
The plugin will automatically find a similar color when a color is already used by an armor and makes sure it's not used by another renderer.
