### ISSUE TITLE
Add an ability to cancel `PlayerEmoteEndEvent` in API if emote was stopped but not finished

### ISSUE THREAD

**Issue by EpicPlayerA10** [PluginBugs/Issues-ItemsAdder#3378]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

epicplayera10

### Describe the solution you'd like

Add an ability to cancel `PlayerEmoteEndEvent` in API if emote was stopped by something but not finished.

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

.

**Comment by LoneDev6** [comment]
This wouldn't be possible as some events would trigger this an indefinite amout of times. The original code which was responsible for the end event trigger would continously trigger it over and over causing issues.
I can't implement that.

Anyway please be more specific on why you want this feature to be implemented, there might be another solution.

**Comment by EpicPlayerA10** [comment]
> Anyway please be more specific on why you want this feature to be implemented, there might be another solution.

I wanted to create a plugin that will add a command (for example `/startevent`). That command would start playing music and force players to dance (aka it will play emote for all players). And I wanted to make so players couldn't cancel dancing until the command `/stopevent` is executed.

**Comment by LoneDev6** [comment]
You should already be able to do that by disabling all cancellations.
```yml
    cancel_conditions:
      deal_damage: false
      in_air: false
      sneak: false
      take_damage: false
```
