### ISSUE TITLE
/iazip broken

### ISSUE THREAD

**Issue by ChefJisoo** [PluginBugs/Issues-ItemsAdder#3382]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

The pack in older versions remains okay but anytime we try to add new models and run iazip it breaks for a majority of players, we have tried various versions, adding/removing the models and even on a working pack version we ran just iazip to see if it still broke and it did meaning it definitely isn't any models but a bug with /iazip. There is a picture further below showing the error message.

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/109172266/73df7c42-1129-4bd8-85e9-a7e1c4786489)

### Steps to reproduce the issue

Upload new models and try run iazip. It doesn't work for a lot of people, but we cannot find a link between the people who it doesn't work for and people it does.

### Server version

Paper 1.20.1

### ItemsAdder Version

ItemsAdder3.6.3-beta-9.

### ProtocolLib Version

/version does not work but the latest version from the website.

### LoneLibs Version

/version does not work but the latest version from the website.

### FULL server log

[latest (8).log](https://github.com/PluginBugs/Issues-ItemsAdder/files/14088672/latest.8.log)

### Screenshots/Videos (you can drag and drop files or paste links)

![forgitticket](https://github.com/PluginBugs/Issues-ItemsAdder/assets/109172266/855956e0-7730-4dfe-9d67-1c5355134cf1)

**Comment by LoneDev6** [comment]
The only way to know why the resourcepack failed to load is to read the client log, as explained in the wiki, and also by reading the output of /iazip.
https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown
This is the same tutorial I'd have to read to help you directly, there is nothing more.

Let me know
