### ISSUE TITLE
Characters being replaced by others when zipped

### ISSUE THREAD

**Issue by KajusLion** [PluginBugs/Issues-ItemsAdder#3388]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

kajuslion

## I have
I have the `emojis.png` file which contains all of these emojis:
![emojis](https://github.com/PluginBugs/Issues-ItemsAdder/assets/92986514/08914016-c311-4f4b-bb12-958958aec745)

There is also `/_emojis/assets/minecraft/font/default.json` with this information:
```json
{
    "providers": [

    {
        "type": "bitmap",
        "file": "minecraft:font/emojis.png",
        "ascent": 7,
        "height": 8,
        "chars": [
          "ꌵꌶꌷꌸꌹ臜爟灿辉煓耀数舡舾舸艋咭嘻嘭喤嗥",
          "ꌺꌻꌼꌽꌾ胝爅烟煨焯煺熵艇舲艅舴唣噢响咱哝",
          "ꌿꍀꍁꍂꍃ胍炷炕炆熥熇焞舱虒舭鸼啾咯咚呼哌",
          "ꍄꍅꍆꍇꍈ脾爙燧焙炫土埘咎篙舠艉唾听噬叽哚",
          "ꍉꍊꍋꍌ섰舀声坦垾堤埸堨簇笠艨艏嘚吒吽哦兄",
          "ꍍꍎꍏꍐꍑ腴塌垠墁冉堋埒艚舢篱航嗅呱啤嗖唆",
          "ꍒꍓꍔꍕꍖ膊壳觳悫坥壸垌舫舻艟舷嘛嘁哞喊吮",
          "ꍗꍘꍙꍚꍛ朘壹垺坝坰壶坍戈、丶良啷哺吠咙咏",
          "ꍜꍝꍞꍟꍠ脏赫赭郝赦坋赧宀塱鵏郙唉咍唳叶嘟",
          "ꍡꍢꍣꍤꍥ脯丧增啬赪坡榖能翩廞床嗔哱嗦嚓喃",
          "鄀鄁鄂鄐鄑胈寺块瞽墚馨鼙术麻糜黁嚏囔味吱咤",
          "鄒鄓鄔鄕鄖胧磬罄謦埫縠垙麽麾魔靡喀戢嘲哮喧",
          "鄗鄘鄙鄚鄿脉款垱圭堎墙封磨摩书縻咛啶嗜哓嘧",
          "縢塍螣腾媵消垚邽恚卦垧垍昶盚皴姿嗐咕噻喷嘹",
          "肚氍貔腯貊盍墦坂垎塮圲塅裘禔视祖咴喹呔唏唵",
          "貆肌冗股貅埌埵圻垢甏坼垛禅社祾祛咦愍啭另叻",
          "豹胜貂貘见圹圫埠坻坬埤去禧卬睾鷭跗踟跄趵跸",
          "莙节茝蓼荨荩薜苣芑井并並荆苷萁葚瓶鹢善荓蒴",
          "岣崿岷崌岖嶍岠岂屺崛嵘崂嵌嵁酆嵯嵫嶟出屾觊",
          "族施旎旗於旒鸬避旞立音竟章意竭遒亲竦产飒坢",
          "迟旃旌旄旅旆放旖旐旋婁婄婅ꑝ娿囁囂囃囄囅囈"
          
          
        ]
    }
  ]
}
```
## What's generated
so when I `/iazip` it and check what's in the `default.json`, I see this (among with some `_iainternal` stuff too):
```json
    {
      "type": "bitmap",
      "file": "minecraft:font/emojis.png",
      "ascent": 7,
      "height": 8,
      "chars": [
        "êŒµêŒ¶êŒ·êŒ¸êŒ¹è‡œçˆŸç�¿è¾‰ç…“è€€æ•°èˆ¡èˆ¾èˆ¸è‰‹å’­å˜»å˜­å–¤å—¥",
        "êŒºêŒ»êŒ¼êŒ½êŒ¾èƒ�çˆ…çƒŸç…¨ç„¯ç…ºç†µè‰‡èˆ²è‰…èˆ´å”£å™¢å“�å’±å“�",
        "êŒ¿ê�€ê��ê�‚ê�ƒèƒ�ç‚·ç‚•ç‚†ç†¥ç†‡ç„žèˆ±è™’èˆ­é¸¼å•¾å’¯å’šå‘¼å“Œ",
        "ê�„ê�…ê�†ê�‡ê�ˆè„¾çˆ™ç‡§ç„™ç‚«åœŸåŸ˜å’Žç¯™èˆ è‰‰å”¾å�¬å™¬å�½å“š",
        "ê�‰ê�Šê�‹ê�Œì„°èˆ€å£°å�¦åž¾å ¤åŸ¸å ¨ç°‡ç¬ è‰¨è‰�å˜šå�’å�½å“¦å…„",
        "ê��ê�Žê��ê��ê�‘è…´å¡Œåž å¢�å†‰å ‹åŸ’è‰šèˆ¢ç¯±èˆªå—…å‘±å•¤å—–å”†",
        "ê�’ê�“ê�”ê�•ê�–è†Šå£³è§³æ‚«å�¥å£¸åžŒèˆ«èˆ»è‰Ÿèˆ·å˜›å˜�å“žå–Šå�®",
        "ê�—ê�˜ê�™ê�šê�›æœ˜å£¹åžºå��å�°å£¶å��æˆˆã€�ä¸¶è‰¯å•·å“ºå� å’™å’�",
        "ê�œê��ê�žê�Ÿê� è„�èµ«èµ­éƒ�èµ¦å�‹èµ§å®€å¡±éµ�éƒ™å”‰å’�å”³å�¶å˜Ÿ",
        "ê�¡ê�¢ê�£ê�¤ê�¥è„¯ä¸§å¢žå•¬èµªå�¡æ¦–èƒ½ç¿©å»žåºŠå—”å“±å—¦åš“å–ƒ",
        "é„€é„�é„‚é„�é„‘èƒˆå¯ºå�—çž½å¢šé¦¨é¼™æœ¯éº»ç³œé»�åš�å›”å‘³å�±å’¤",
        "é„’é„“é„”é„•é„–èƒ§ç£¬ç½„è¬¦åŸ«ç¸ åž™éº½éº¾é­”é�¡å–€æˆ¢å˜²å“®å–§",
        "é„—é„˜é„™é„šé„¿è„‰æ¬¾åž±åœ­å Žå¢™å°�ç£¨æ‘©ä¹¦ç¸»å’›å•¶å—œå““å˜§",
        "ç¸¢å¡�èž£è…¾åªµæ¶ˆåžšé‚½æ�šå�¦åž§åž�æ˜¶ç›šçš´å§¿å—�å’•å™»å–·å˜¹",
        "è‚šæ°�è²”è…¯è²Šç›�å¢¦å�‚åžŽå¡®åœ²å¡…è£˜ç¦”è§†ç¥–å’´å–¹å‘”å”�å”µ",
        "è²†è‚Œå†—è‚¡è²…åŸŒåŸµåœ»åž¢ç”�å�¼åž›ç¦…ç¤¾ç¥¾ç¥›å’¦æ„�å•­å�¦å�»",
        "è±¹èƒœè²‚è²˜è§�åœ¹åœ«åŸ å�»å�¬åŸ¤åŽ»ç¦§å�¬ç�¾é·­è·—è¸Ÿè·„è¶µè·¸",
        "èŽ™èŠ‚èŒ�è“¼è�¨è�©è–œè‹£èŠ‘äº•å¹¶ä¸¦è�†è‹·è��è‘šç“¶é¹¢å–„è�“è’´",
        "å²£å´¿å²·å´Œå²–å¶�å² å²‚å±ºå´›åµ˜å´‚åµŒåµ�é…†åµ¯åµ«å¶Ÿå‡ºå±¾è§Š",
        "æ—�æ–½æ—Žæ——æ–¼æ—’é¸¬é�¿æ—žç«‹éŸ³ç«Ÿç« æ„�ç«­é�’äº²ç«¦äº§é£’å�¢",
        "è¿Ÿæ—ƒæ—Œæ—„æ—…æ—†æ”¾æ—–æ—�æ—‹å©�å©„å©…ê‘�å¨¿å›�å›‚å›ƒå›„å›…å›ˆ"
      ]
    }
```
## Issue
These are clearly not the characters I set in the contents folder, and my Emojis do not work.

This is what I get when pasting the stuff that's generated (1st line) and stuff that I set (2nd line)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/92986514/6488867e-4476-4998-bfd1-c7ce2365ebe4)

This is not some special trick with packs or anything. It's just how png's and json's work. If you have a large image (2x2) you can set 4 chars (in 2 lines, so 2 chars per lines) and it will divide the png into 4 equal parts and assign a quarter of it for each char.

## Other
I've uploaded 3 zip files bellow:
- `Emojis.zip` contains vanilla Minecraft's version of what I need;
- `generated.zip` is the generated file from `plugins/ItemsAdder/output`
- `contents.zip` is the contents folder from `plugins/ItemsAdder`(/contents)

[Emojis.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/14137432/Emojis.zip)
[generated.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/14137353/generated.zip)
[contents.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/14137312/contents.zip)

### Steps to reproduce the issue

Everything should be explained in the `What happened?` section.
I tried writing in conclusion, but for further details check the `What happened?` section

- Make a folder in contents with `default.json`;
- add an image;
- set some characters for that image;
- run `/iazip`;
- see that the characters were changed by other characters when the `generated.zip` is generated.

### Server version

`This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version`

### ItemsAdder Version

`ItemsAdder version 3.6.3-beta-11`

### ProtocolLib Version

`ProtocolLib version 5.1.1-SNAPSHOT-668`
Edit: Updated to `5.2.0-SNAPSHOT-679`. Didn't help with the issue.

### LoneLibs Version

`LoneLibs version 1.0.45`

### FULL server log

~~[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/14137550/latest.log)~~
This isn't really needed, because there is nothing much said in here
> Edit: This is from my main server ^, I made a new one, empty (with just ItemsAdder, ProtocolLib and LoneLibs), this is the log file
> [latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/14137777/latest.log)

**Comment by LoneDev6** [comment]
First: 
Why are you manually creating emojis when ItemsAdder offers an easy way to create 1 emoji per png file and handle them easier

Second:
Try to check if your file is correctly saved with the correct encoding, this doesn't happen on my server.
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/6b067137-6f02-4603-ae67-66f0c3967478)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/498d49f9-f83e-4935-9bcf-5b251c5288d8)

**Comment by KajusLion** [comment]
Firstly: 
As you can see I have a 21x21 emojis file and to separate them and then add 400 emojis one by one is just too much work.

Secondly:
How do you check if your file is correctly saved with the correct encoding?

**Comment by KajusLion** [comment]
I just created a brand new, empty server
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/92986514/8d407673-6779-4198-978d-48b107683839)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/92986514/fd3f8111-f483-4fd8-8035-a85e68f396ca)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/92986514/e8b63be9-120f-46d8-99ed-80723f1e2ff8)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/92986514/4a2800c9-579b-42a7-8b9c-407fce484e1f)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/92986514/a775c86b-51d4-4199-bfcb-6d249244aaae)

I didn't edit **ANYTHING** except set self-host to true (cuz I host on local server)

This is the structure of the `plugins` folder:
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/92986514/515a3f2f-1429-4f50-a144-318271018a10)

### The issue is still there!

Take the whole plugins folder:
[plugins.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/14144951/plugins.zip)

I can't get it to work.

**Comment by KajusLion** [comment]
@LoneDev6 Please! I've been struggling with this for a long LONG time :(

**Comment by KajusLion** [comment]
Is there any chance that you would send me the folder which you put into the `contents` of IA? Maybe I'm doing something wrong :(

**Comment by SirCraftypants** [comment]
The only minecraft folder that should exist is the one located  in `plugins/itemsadder/contents/_iainternal/resourcepack`

You should not be making content with the `minecraft` namespace in your contents folder.

Create a new namespace folder  like say `myemojis` and place your emoji's in that folder, then in your `contents` folder.

Try that, see if it fixes it.

As i mentioned to you previously, Itemsadder has always dealt with emoji's separately, not all combined in to 1 png.

I provided you links to some premade free emoji addons, if you separated all those emoji's, then paste then over to one of those emoji addons that would reduce the amount of work you have to do. Or you could pay someone else to do it for you.

There's no quick fix, Itemsadder has never claimed to support emoji's sharing a singular png.

**Comment by LoneDev6** [comment]
> As you can see I have a 21x21 emojis file and to separate them and then add 400 emojis one by one is just too much work.

Yes I know, I was just saying that usually people would like to avoid carrying disabled emojis and having the big atlas would not allow people to do so, they would be shipped with the pack anyway.
The game itself generates the font atlas at runtime, so it's pointless to create it manually.

> How do you check if your file is correctly saved with the correct encoding?

Text editor.
For example VSCODE:
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/3a8296e0-7697-4bdb-8b2b-7a9a3c009d06)

Anyway I cannot reproduce the issue by loading your files, as you can see, so I'm trying to identify the cause, my first thought was about the encoding, as seems it's wrong.

Another cause might be your PC/server system language, what language are you using?


> Please! I've been struggling with this for a long LONG time :(

Yea I know, it's getting hard to keep up with all the support requests I get and day life, I try my best.
