### ISSUE TITLE
HEXCOLOR BUG

### ISSUE THREAD

**Issue by WhiteProject1** [PluginBugs/Issues-ItemsAdder#3389]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

batuhan____

### What happened?

https://github.com/PluginBugs/Issues-ItemsAdder/assets/103301275/bc2c527b-b33a-4c07-8433-de750b57a11e

### Steps to reproduce the issue

I show on video

### Server version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/103301275/f13d1e64-fe6d-4474-9255-765f60f6f7a2)

### ItemsAdder Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/103301275/d3fbf8eb-3f3d-401a-bfc3-097f5edcf14c)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/103301275/753978f4-586c-479a-a9f2-4f41609f3ea9)
.

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/103301275/21014ce3-404b-42d5-8a44-610e60a382eb)
.

**Comment by LoneDev6** [comment]
<https://itemsadder.devs.beer/plugin-usage/hex-colored-texts-1.16+>

```
<#FE5A00>Example Colored Text
```

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/01703efb-2571-490d-8d38-db06fa49c610)

**Comment by WhiteProject1** [comment]
I tryed but dont works

**Comment by LoneDev6** [comment]
Provide your item configuration

**Comment by pmgalileo** [comment]
I also have this problem, hex works in the lore of items but not in their names.

`info:
  namespace: atlas
items:
  dekorativni_kavez1:
    display_name: "&f <#b4b4b4>Dekorativni kavez" ❌
    lore:
    - "<#ffffff> <#e4a00c>Dekorativni blok" ✅
    resource:
      material: PAPER
      generate: false
      model_path: namestaj/dunge...`

**Comment by LoneDev6** [comment]
You are mixing & notation and <#xxx> notation.
Use only one of them. https://itemsadder.devs.beer/plugin-usage/hex-colored-texts-1.16+
