### ISSUE TITLE
Plugin doesn't load + error in console

### ISSUE THREAD

**Issue by Nunchakin** [PluginBugs/Issues-ItemsAdder#3402]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

nunchakin

### What happened?

ItemsAdder plugin doesn't load and it gives and error in console.

### Steps to reproduce the issue

Put the ItemsAdder version 3.6.3-beta-11 into plugins folder and load the server.

### Server version

This server is running Paper version git-Paper-408 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: c5d168c)
You are running the latest version

### ItemsAdder Version

[15:55:16 INFO]: ItemsAdder version 3.6.3-beta-11

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.45

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/14157277/latest.log)

### Error (optional)

```shell
[15:32:20] [Server thread/INFO]: [ItemsAdder] Loading server plugin ItemsAdder v3.6.3-beta-11
[15:32:20] [Server thread/WARN]: Cannot load file: config.yml
[15:32:20] [Server thread/WARN]: [ItemsAdder] Error: org.yaml.snakeyaml.error.YAMLException: Nesting Depth exceeded max 50
[15:32:20] [Server thread/ERROR]: [ItemsAdder] Error initializing plugin 'ItemsAdder_3.6.3-beta-11.jar' in folder 'plugins' (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.file.FileConfiguration.getString(String, String)" because "this.a" is null
	at ia.m.re.d(SourceFile:473) ~[ItemsAdder_3.6.3-beta-11.jar:?]
	at dev.lone.itemsadder.Main.bP(SourceFile:576) ~[ItemsAdder_3.6.3-beta-11.jar:?]
	at dev.lone.itemsadder.Main.onLoad(SourceFile:180) ~[ItemsAdder_3.6.3-beta-11.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.20.4.jar:git-Paper-408]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.20.4.jar:git-Paper-408]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.4.jar:git-Paper-408]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.4.jar:git-Paper-408]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:505) ~[paper-1.20.4.jar:git-Paper-408]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.4.jar:git-Paper-408]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-408]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-408]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by Nunchakin** [comment]
We found this in config.yml, it may be bug from updating:

fix_trades_guis_match_custom_items:
    itemsadder_trade_machines:
      itemsadder_trade_machines:
        itemsadder_trade_machines:
          itemsadder_trade_machines:
            itemsadder_trade_machines:
              itemsadder_trade_machines:
                itemsadder_trade_machines:
                  itemsadder_trade_machines:
                    itemsadder_trade_machines:
                      itemsadder_trade_machines:
                        itemsadder_trade_machines:
                          itemsadder_trade_machines:
                            itemsadder_trade_machines:
                              itemsadder_trade_machines:
                                itemsadder_trade_machines:
                                  itemsadder_trade_machines:
                                    itemsadder_trade_machines:
                                      itemsadder_trade_machines:
                                        itemsadder_trade_machines:
                                          itemsadder_trade_machines:
                                            itemsadder_trade_machines:
                                              itemsadder_trade_machines:
                                                itemsadder_trade_machines:
                                                  itemsadder_trade_machines:
                                                    itemsadder_trade_machines:
                                                      itemsadder_trade_machines:
                                                        itemsadder_trade_machines:
                                                          itemsadder_trade_machines:
                                                            itemsadder_trade_machines:
                                                              itemsadder_trade_machines:
                                                                itemsadder_trade_machines:
                                                                  itemsadder_trade_machines:
                                                                    itemsadder_trade_machines:
                                                                      itemsadder_trade_machines:
                                                                        itemsadder_trade_machines:
                                                                          itemsadder_trade_machines:
                                                                            itemsadder_trade_machines:
                                                                              itemsadder_trade_machines:
                                                                                itemsadder_trade_machines:
                                                                                  itemsadder_trade_machines:
                                                                                    itemsadder_trade_machines:
                                                                                      itemsadder_trade_machines:
                                                                                        itemsadder_trade_machines:
                                                                                          itemsadder_trade_machines:
                                                                                            itemsadder_trade_machines:
                                                                                              itemsadder_trade_machines:
                                                                                                itemsadder_trade_machines:
                                                                                                  itemsadder_trade_machines:
                                                                                                    itemsadder_trade_machines: true
                                                                                                    vanilla_villagers: false
                                                                                                    other_plugins: true
                                                                                                  vanilla_villagers: false
                                                                                                  other_plugins: true
                                                                                                vanilla_villagers: false
                                                                                                other_plugins: true
                                                                                              vanilla_villagers: false
                                                                                              other_plugins: true
                                                                                            vanilla_villagers: false
                                                                                            other_plugins: true
                                                                                          vanilla_villagers: false
                                                                                          other_plugins: true
                                                                                        vanilla_villagers: false
                                                                                        other_plugins: true
                                                                                      vanilla_villagers: false
                                                                                      other_plugins: true
                                                                                    vanilla_villagers: false
                                                                                    other_plugins: true
                                                                                  vanilla_villagers: false
                                                                                  other_plugins: true
                                                                                vanilla_villagers: false
                                                                                other_plugins: true
                                                                              vanilla_villagers: false
                                                                              other_plugins: true
                                                                            vanilla_villagers: false
                                                                            other_plugins: true
                                                                          vanilla_villagers: false
                                                                          other_plugins: true
                                                                        vanilla_villagers: false
                                                                        other_plugins: true
                                                                      vanilla_villagers: false
                                                                      other_plugins: true
                                                                    vanilla_villagers: false
                                                                    other_plugins: true
                                                                  vanilla_villagers: false
                                                                  other_plugins: true
                                                                vanilla_villagers: false
                                                                other_plugins: true
                                                              vanilla_villagers: false
                                                              other_plugins: true
                                                            vanilla_villagers: false
                                                            other_plugins: true
                                                          vanilla_villagers: false
                                                          other_plugins: true
                                                        vanilla_villagers: false
                                                        other_plugins: true
                                                      vanilla_villagers: false
                                                      other_plugins: true
                                                    vanilla_villagers: false
                                                    other_plugins: true
                                                  vanilla_villagers: false
                                                  other_plugins: true
                                                vanilla_villagers: false
                                                other_plugins: true
                                              vanilla_villagers: false
                                              other_plugins: true
                                            vanilla_villagers: false
                                            other_plugins: true
                                          vanilla_villagers: false
                                          other_plugins: true
                                        vanilla_villagers: false
                                        other_plugins: true
                                      vanilla_villagers: false
                                      other_plugins: true
                                    vanilla_villagers: false
                                    other_plugins: true
                                  vanilla_villagers: false
                                  other_plugins: true
                                vanilla_villagers: false
                                other_plugins: true
                              vanilla_villagers: false
                              other_plugins: true
                            vanilla_villagers: false
                            other_plugins: true
                          vanilla_villagers: false
                          other_plugins: true
                        vanilla_villagers: false
                        other_plugins: true
                      vanilla_villagers: false
                      other_plugins: true
                    vanilla_villagers: false
                    other_plugins: true
                  vanilla_villagers: false
                  other_plugins: true
                vanilla_villagers: false
                other_plugins: true
              vanilla_villagers: false
              other_plugins: true
            vanilla_villagers: false
            other_plugins: true
          vanilla_villagers: false
          other_plugins: true
        vanilla_villagers: false
        other_plugins: true
      vanilla_villagers: false
      other_plugins: true

**Comment by Nunchakin** [comment]
We found this in config.yml, it may be bug from updating:
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/151460657/8de2def9-311d-49a6-a78d-6bc73021f605)

**Comment by Nunchakin** [comment]
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/151460657/9d092537-8b18-4233-a366-a0032fd0d27d)

**Comment by Nunchakin** [comment]
We only left these 3 settings and it works now

**Comment by LoneDev6** [comment]
Duplicate of: https://github.com/PluginBugs/Issues-ItemsAdder/issues/3390
Remove these lines and restart, I will today release a fix for that issue.
Thanks!
