### ISSUE TITLE
Characters are duplicated in newly generated resource packs

### ISSUE THREAD

**Issue by aml2023529** [PluginBugs/Issues-ItemsAdder#3407]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

liangys233

### What happened?

Characters in newly generated resource packs will be duplicated leading to problems such as :: not being able to be used.

### Steps to reproduce the issue

![QQ图片20240206031201](https://github.com/PluginBugs/Issues-ItemsAdder/assets/134866994/48196bff-6027-4f08-8732-7429c45069ed)

### ItemsAdder Version

[03:24:45 INFO]: Current: git-Purpur-2136 (MC: 1.20.4)*
Previous: git-Purpur-2134 (MC: 1.20.4)
* You are running the latest version

### ProtocolLib Version

[03:25:04 INFO]: ProtocolLib version 5.2.0-SNAPSHOT-679
[03:25:04 INFO]: Provides read/write access to the Minecraft protocol.
[03:25:04 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[03:25:17 INFO]: LoneLibs version 1.0.45
[03:25:17 INFO]: Collection of libs used by my plugins
[03:25:17 INFO]: Authors: LoneDev and others

### FULL server log

https://mclo.gs/kQ7mg5k

**Comment by LoneDev6** [comment]
Did you manually set the character in the yml file for that font image?
Might be the cause of the issue, anyway the plugin should already avoid that situation.

Please do not send screenshots, instead update the cache file as text file here so that I can check it.

**Comment by aml2023529** [comment]
> 您是否在 yml 文件中为该字体图像手动设置了字符？可能是问题的原因，无论如何插件应该已经避免了这种情况。
> 
> 请不要发送屏幕截图，而是在此处将缓存文件更新为文本文件，以便我检查它。
[storage.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/14173542/storage.zip)

**Comment by aml2023529** [comment]
/
![QQ截图20240211014520](https://github.com/PluginBugs/Issues-ItemsAdder/assets/134866994/ffdf3075-98a7-4d81-b59b-168af2d73c99)
[storage.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/14230017/storage.zip)

**Comment by aml2023529** [comment]
I changed the other characters manually everything is back to normal in older versions this problem does not occur only in the latest bate12

**Comment by Seeroh** [comment]
I have a similar problem to this. 3.6.3 Beta 12 (Was experiencing same issue on 3.6.3 Beta 7 as well), where when adding new items to the resource pack, it will generate swapped characters for font items.

For instance, :skills_1: is showing the gui for :skills_stats_2:

This means that all my guis are completely messed up, as well as other places I use font items.

**Comment by LoneDev6** [comment]
For some reason your YML files have wrong characters, they then were saved into the cache file.
This is very strange, no idea why it happend.

Can you confirm that the issue is fixed after you manually restored the correct characters, saved and regenerated the resourcepack?
