### ISSUE TITLE
Please delete the post. It didn't work because I didn't write it well. sorry.

### ISSUE THREAD

**Issue by ffddf111** [PluginBugs/Issues-ItemsAdder#3409]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

cyclsunmark

### Describe the solution you'd like

I hope you will support Multiverse-Core.

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

When using worlds-populators

     worlds:
     -build
     
  Please support other worlds in this way.

### Additional context

Because I am conveying this using a translator.
I didn't understand this “Is your feature request related to a problem?”.

**Comment by LoneDev6** [comment]
Multiverse is already supported, I use it to manage multiple worlds in my test servers.
