### ISSUE TITLE
Internal Exception io.netty.handler.codec.decoderException: Uknown serializer type 19

### ISSUE THREAD

**Issue by cabruzumaki** [PluginBugs/Issues-ItemsAdder#3410]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

When I take things from the creative, I use /summon, /effect, /op it kicks all the players I'm sure it's the items adder's fault

### Steps to reproduce the issue

User /op
Use /effect
use /summon
grab creative items

### Server version

This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) 

### ItemsAdder Version

3.6.2

### ProtocolLib Version

 ProtocolLib version 5.1.0

### LoneLibs Version

LoneLibs version 1.0.45

**Comment by LoneDev6** [comment]
Can you please post the full error?
Also post the server log if it contains any error.

Thanks.

one suggestion: update to 1.19.4 as 1.19.2 is very old and has issues.
