### ISSUE TITLE
Surface decorators do not work in the nether

### ISSUE THREAD

**Issue by cm4500** [PluginBugs/Issues-ItemsAdder#3422]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

cm4500

### What happened?

I am unable to get surface decorators to generate in the nether world. 

In the overworld, surface decorators work as expected. And even world populator blocks generate correctly in the nether. But only surface decorators do not appear to generate at all. 

I have checked the formatting, spelling, the world name, the chance value, all that. I have even turned on the logs to show if anything generates in the nether, but no decorators will generate. 

### Steps to reproduce the issue

Provided below is a configuration I am using in yml format.

### Server version

This server is running Paper version git-Paper-422 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: cde5587)
You are running the latest version
Previous version: git-Paper-"a80d31b" (MC: 1.20.4)

### ItemsAdder Version

3.6.3-beta-12

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

### FULL server log

Logs showing that surface decorators in the overworld work fine, but no nether ones generate despite having explored the nether in this time. 

11.02 18:54:18 [Server] [INFO] [ItemsAdder] Generated worlddeco:fallen_leaves surface decoration at coords: 221, 69, 148 in world world ( /tppos 221 69 148)
11.02 18:54:18 [Server] [INFO] [ItemsAdder] Generated worlddeco:fallen_leaves surface decoration at coords: 220, 69, 147 in world world ( /tppos 220 69 147)
11.02 18:54:18 [Server] [INFO] [ItemsAdder] Generated worlddeco:fallen_leaves surface decoration at coords: 221, 69, 147 in world world ( /tppos 221 69 147)
11.02 18:54:18 [Server] [INFO] [ItemsAdder] Generated worlddeco:fallen_leaves surface decoration at coords: 220, 69, 148 in world world ( /tppos 220 69 148)
11.02 18:54:19 [Server] [INFO] [ItemsAdder] Generated flowers:rose_placed surface decoration at coords: 219, 71, 170 in world world ( /tppos 219 71 170)
11.02 18:54:19 [Server] [INFO] [ItemsAdder] Generated worlddeco:small_rocks surface decoration at coords: 209, 71, 171 in world world ( /tppos 209 71 171)
11.02 18:54:19 [Server] [INFO] [ItemsAdder] Generated worlddeco:small_rocks surface decoration at coords: 209, 71, 172 in world world ( /tppos 209 71 172)
11.02 18:54:19 [Server] [INFO] [ItemsAdder] Generated worlddeco:small_rocks surface decoration at coords: 210, 71, 171 in world world ( /tppos 210 71 171)
11.02 18:54:19 [Server] [INFO] [ItemsAdder] Generated worlddeco:small_rocks surface decoration at coords: 210, 71, 172 in world world ( /tppos 210 71 172)
11.02 18:54:19 [Server] [INFO] [ItemsAdder] Generated worlddeco:mossy_small_rocks surface decoration at coords: 220, 71, 165 in world world ( /tppos 220 71 165)

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: flowers
  enabled: true
surface_decorators:
  hydrangea_blue:
    block: flowers:hydrangea_blue_placed
    bottom_blocks:
    - CRIMSON_NYLIUM
    - WARPED_NYLIUM
    biomes:
    - CRIMSON_FOREST
    - WARPED_FOREST
    worlds:
      - world_nether
    chance: 100
    max_height: 118
    min_height: 10
    amount: 3
```

**Comment by LoneDev6** [comment]
Are the biomes correct?
Can you try to remove the biomes rule so that they generate in every biome?
Thanks

**Comment by cm4500** [comment]
Yes, the biomes IDs are taken from the Spigot API page for 1.20.4. It is also evident that they work because the world populators in the nether spawn as intended. It is only the surface decorators that do not appear to generate.

I have also tested it without any biome rules, but still no generation.

**Comment by LoneDev6** [comment]
Thanks a lot for the info, I will test this as soon as possible, probably is some edge case caused by how the game works.

**Comment by LoneDev6** [comment]
This was caused by the fact that surface in the nether is always at 128, due to the top bedrock layer.
I reimplemented the height check for nether to manually find the height, as the Minecraft code always provides height at 128.
