### ISSUE TITLE
No warning is displayed when using points in namespaces which causes buggy behavior 

### ISSUE THREAD

**Issue by codingcat2468** [PluginBugs/Issues-ItemsAdder#3431]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I recently found a rather small bug affecting namespaces of IA contents. I was making a test server to try some stuff, and while doing so, I created a namespace that contained a point in its name. I also added two REAL_NOTE blocks with two different textures. When joining the server and running /iazip, I noticed that the two blocks had the same texture when placed, but not in the inventory. According to the console log, I also had only used one REAL_NOTE  block ID.
I tried a lot of things to fix this, from cleaning the cache to changing the IDs of the blocks. At some point I looked into the _real_blocks_note_ids_cache.yml_ file and saw that there was a seperated section that shouldn't have been there. This also happend when using other block types than REAL_NOTE.

I think the issue here is that when modifying bukkit config files (yml files) through code, the point creates a new YML object. (I've code plugins myself, so I'm familiar with how config files are handled in the code) This probably creates some bugs while reading this cache file, resulting in the buggy behavior I experienced. After I replaced the point in the namespace with an underscore, everything worked as intended, it just took really long to figure this problem out.

_(Also sorry for writing such a long report on such a small bug)_

### Steps to reproduce the issue

1. Start a new server with only ItemsAdder and the dependencies installed.
2. Create a new namespace folder containing a point, like "test.namespace"
3. Add some config files, including two blocks with different textures
4. Run /iazip and look at the console (it should say something like _Used 1/750 [...] block IDs_ instead of 2, look at the one that matches the block type you chose)
5. The two blocks should have the same texture
6. Look into *real_blocks_note_ids_cache.yml* (or the cache file for the block type you chose), it should look similar to the one I sent below
7. Rename the folder and namespace in the config files to something without points, like "test_namespace"
8. Run /iazip, clean the block cache and run /iazip again
9. The two blocks should now have the correct textures and the console should say _"Used 2/750 [...] block IDs"_  (also the cache file should be fixed)

### Server version

This server is running Paper version git-Paper-373 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: b2a6d57)

### ItemsAdder Version

ItemsAdder version 3.6.3-beta-12

### ProtocolLib Version

 ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.45

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: test.namespace

items:
  test_block_01:
    display_name: Test Block 01
    resource:
      generate: true
      material: PAPER
      textures:
        - block/test.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM

  test_block_02:
    display_name: Test Block 02
    resource:
      generate: true
      material: PAPER
      textures:
        - block/test2.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
```

### Other files, you can drag and drop them here to upload. (optional)

**real_blocks_note_ids_cache.yml** content (I created a namespace with and one without a point in the name to show the difference):
```yml
test_namespace:test_block_01: 258
test_namespace:test_block_02: 259
test:
  namespace:test_block_01: 260
  namespace:test_block_02: 260
```

**Comment by LoneDev6** [comment]
I'm more than sure that Minecraft doesn't allow dots in namespaces or items names, so avoid doing that.
Only special character supported is underscore: `_` and `-`, but I'd use only `_`.
This is not something related to ItemsAdder but to minecraft itself.
Anyway note: in YML `.` is a special character, a separator, so it shouldn't be used in naming and properties.

**Comment by codingcat2468** [comment]
Like I said, I was just testing things. But anyways, the only reason that it took so long for me to figure that out was that there was no error message anywhere... You could just implement some kind of system that warns the user in the console about invalid characters in namespaces for the people who don't know about this.

Anyways, thank you for actually responding so quick and have a good day!

**Comment by LoneDev6** [comment]
Thank you, it probably can't detect the bad character because it thinks it's a special separator in YML, so it skips the check, which is already coded.
I will fix that in the upcoming update.
