### ISSUE TITLE
1.20.1 Shopkeepers Bug - `items.fix_trades_guis_match_custom_items` can't be disabled

### ISSUE THREAD

**Issue by xShyo** [PluginBugs/Issues-ItemsAdder#3454]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

https://github.com/PluginBugs/Issues-ItemsAdder/assets/98056847/777f903b-95a7-4aaa-8f8f-484650a252dc

### Steps to reproduce the issue

Include an 'itemsadder' item as part of the trade. The item must be modified with a lore or renamed.
To perform the trade, make sure you have only the unedited item in your inventory. 
When you click on the trade, it will automatically become the edited item that the villager is requesting. 
It is important to note that both items must be of the same type for the process to work correctly.

### Server version

This server is running UniverseSpigot version git-UniverseSpigot-"fe2588e" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: fe2588e on ver/1.20.1-stable)
Universe-git-UniverseSpigot-"fe2588e" (MC: 1.20.1)

### ItemsAdder Version

 ItemsAdder version 3.6.3-beta-13

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-668

### LoneLibs Version

LoneLibs version 1.0.45

**Comment by LoneDev6** [comment]
Because ItemsAdder implements a custom way to match villager recipes ingredients so that it matches the item namespace+id instead of relying on the NBT data.
This was introduced to fix this: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2294

If you're not interested into having that feature on you can disable it in config.yml 

```yml
  fix_trades_guis_match_custom_items:
    itemsadder_trade_machines: true
    vanilla_villagers: false
    other_plugins: false # <----In your case this
```

**Comment by xShyo** [comment]
Currently, I find myself with the server turned off. When I try to change the status to 'false', when I turn on the server, the path configuration is automatically reset to 'true'.

**Comment by LoneDev6** [comment]
This will be checked as soon as possible, thank you for the patience

**Comment by RainfallHaruno** [comment]
This bug is casing a lot of problems on our server, making us unfunctional. Please put this at the highest priority.

**Comment by LiveJunye** [comment]
Have the same issues

**Comment by RainfallHaruno** [comment]
I believe this happened after the 3.6.3-beta-9 update, and I saw some similar reports on this issue. **#2294** mixes things with the same texture and is not useful for most of the serves. This setting in config.yml should not be set to true by default.

**Comment by LoneDev6** [comment]
> Because ItemsAdder implements a custom way to match villager recipes ingredients so that it matches the item namespace+id instead of relying on the NBT data.
> This was introduced to fix this: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2294
> 
> If you're not interested into having that feature on you can disable it in config.yml 
> 
> ```yml
>   fix_trades_guis_match_custom_items:
>     itemsadder_trade_machines: true
>     vanilla_villagers: false
>     other_plugins: false # <----In your case this
> ```

The option currently can't be disabled due to a bug, it will be fixed in the next update.

**Comment by LiveJunye** [comment]
Still have the same bug. config is set to false are not change to true, But still automatically become the edited item that the villager is requesting.
<img width="397" alt="847193649163511134" src="https://github.com/PluginBugs/Issues-ItemsAdder/assets/26696869/d0f99f69-5050-45ad-9c71-7b99dfd43ad7">
This is the config.yml screenshot

**Comment by Andre601** [comment]
> Still have the same bug. config is set to false are not change to true, But still automatically become the edited item that the villager is requesting. <img alt="847193649163511134" width="397" src="https://private-user-images.githubusercontent.com/26696869/325786029-d0f99f69-5050-45ad-9c71-7b99dfd43ad7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwODUzOTIsIm5iZiI6MTcxNDA4NTA5MiwicGF0aCI6Ii8yNjY5Njg2OS8zMjU3ODYwMjktZDBmOTlmNjktNTA1MC00NWFkLTljNzEtN2I5OWRmZDQzYWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDIyNDQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1ZjdjNGM3YjU0YTAyYWJhODA3MTUyZDEzOThjMjMzN2YwNWNkNDQwNDBlMjhjZWUxMmZkNjEwMTliYmNmOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8buCmwWXJPAqsAK6ky1P8ZMQx8FMoD_yrE0vSTTn4lo"> This is the config.yml screenshot

Please share additional info such as ItemsAdder version, LoneLibs version, ProtocolLib version and Server version (Please provide the output of the `/version <plugin>` and `/version` command respectively and not just say "latest" or what you think is the version you use).
