### ISSUE TITLE
My mounts hurt me and my arrows work backwards.

### ISSUE THREAD

**Issue by RitsuElAnti** [PluginBugs/Issues-ItemsAdder#3462]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Ritsu#9014

### What happened?

My mounts hurt me when I mount them and when using the arrows they work backwards from right to left, back goes forward etc.
I honestly don't know if it's an error, but I've also tried vanilla horses and haven't had a problem.

### Steps to reproduce the issue

1 - I get on the saddle
2 - it hurts me
3 - use WASD keys
4 - I'm going backwards

### Server version

This server is running Paper version git-Paper-393 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: b48d737)
You are 42 version(s) behind

### ItemsAdder Version

3.6.3-beta-13

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: custom
entities:
  lobo_montura:
    display_name: "Lobo Montura"
    type: HORSE
    model_folder: entity/lobo_montura_converted
    max_health: 20
    silent: true
```

### Screenshots/Videos (you can drag and drop files or paste links)

![ezgif-5-9fa0bd7c1d](https://github.com/PluginBugs/Issues-ItemsAdder/assets/119564188/b3a9090a-08ec-4984-9935-a12f7da29306)

**Comment by LoneDev6** [comment]
This is not normal.
Mounts were tested on each game update and didn't have this issue.
I will do some test again.
