### ISSUE TITLE
trying to update but models get bugged

### ISSUE THREAD

**Issue by Cimejes1** [PluginBugs/Issues-ItemsAdder#3464]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Cimejes

### What happened?

Im at vertion 3.4.1f2 (items adder) and trying to update but doing so bugs the custom models (of iaentities)
since vertion 3.5.0 bug appeared out of nowere. Already updated before without error dk why bugs appears now. Bug didnt disappear with newer vertion 3.6.3-beta-13. Id like to hear that at least you are looking to what the error could be coz its strange and as a paid pluggin its frustrating it doesnt work

### Steps to reproduce the issue

from vertion 3.4.1f2
Put iaentites in the resourcepack
make /iazip and verify that the entities work well
Update the plugin and its dependencies to the latest versions 

### Server version

1.19.4

### ItemsAdder Version

3.4.1f2

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

### Screenshots/Videos (you can drag and drop files or paste links)

before: 
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/161375557/ae36f40e-e62c-4b4a-b74b-aa9d9389f96a)
after:
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/161375557/377a92f8-51c7-4443-8ab7-345eda6b9768)

**Comment by LoneDev6** [comment]
Regenerate your resourcepack using /iazip

if that doesn't work try also this:
- update the blockbench extension
- export all your custom itemsadder entities models using the blockbench extension
- regenerate your resourcepack using /iazip

anyway you shouldn't really need to do that, entities should work just fine.
This is very strange, for some reason your custom entities models had their custommodeldata messed up.
Maybe due to manual editing? deletion of the cache files?

**Comment by LoneDev6** [comment]
- stop the server
- open `plugins\ItemsAdder\storage\items_ids_cache.yml`
- remove every line that starts with `__manually_handled:`
- start the server
- regenerate the resourcepack using /iazip

I cannot reproduce this issue on my test server by the way, so this is quite strange.

Another issue might be that you're using the external host hosting so resourcepack is not automatically updated when you run /iazip.
