### ISSUE TITLE
BlockFromToEvent CHORUS_PLANT

### ISSUE THREAD

**Issue by SkriptStudy** [PluginBugs/Issues-ItemsAdder#3466]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

10멸의 꿈#10_want

### What happened?

It is normal that it cannot be destroyed when installed in sprinkled water.

type: REAL_TRANSPARENT
The block that sets CHORUS_PLANT as
Install.

But bug! Spray water on the side or underneath.
It's been destroyed.
When you spray water underneath, it is sometimes protected so that it does not spray, but if you click it multiple times, it will eventually spray.

### Steps to reproduce the issue

It is normal that it cannot be destroyed when installed in sprinkled water.

type: REAL_TRANSPARENT
The block that sets CHORUS_PLANT as
Install.

But bug! Spray water on the side or underneath.
It's been destroyed.
When you spray water underneath, it is sometimes protected so that it does not spray, but if you click it multiple times, it will eventually spray.

### Server version

This server is running Paper version git-Paper-407 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 8bc5be8)
You are 28 version(s) behind
Download the new version at: https://papermc.io/downloads/paper

### ItemsAdder Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/157591881/c1e0a06a-55ca-4c07-888b-a9d70fd5e847)

3.6.3-beta-13

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/157591881/057b6952-4058-44fe-8ad6-a9f772074868)

5.2.0-SNAPSHOT-679

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/157591881/2de36dff-32af-4c64-8e85-7f09e6874ecc)

1.0.45

### FULL server log

no log

### Error (optional)

```shell
no log
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: small_blocks
items:
  small_quartz_pillar:
    enabled: true
    display_name: display-name-small_quartz_pillar
    resource:
      material: OAK_FENCE
      generate: false
      model_path: block/small_quartz_pillar
    specific_properties:
      block:
        placed_model:
          type: REAL_TRANSPARENT
          break_particles: ITEM
        cancel_drop: false
        sound:
          break:
            name: minecraft:block.amethyst_block.break
          place:
            name: minecraft:block.amethyst_block.place
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/bjGWsTWZNbU

**Comment by LoneDev6** [comment]
It's normal.
The plugin must cancel these events and there is no better way for me to do so without causing extreme CPU usage because physics events are triggered very frequently.
The easiest way is to drop the block to avoid excessive constant physics events to be triggered by water near custom REAL_WIRE blocks.
I can't do anything against that and it's a normal behavior due to how the game works.
