### ISSUE TITLE
Get a headstart on implementing support for the new NBT System coming in 1.20.5/1.21

### ISSUE THREAD

**Issue by Asleeepp** [PluginBugs/Issues-ItemsAdder#3467]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

asleepp

### Describe the solution you'd like

The newest minecraft snapshot revealed to players a new NBT system, that is a massive breaking change, and will definitely break code. This Issue aims to give you a headstart on implementing this new system early.

This is the page they put out:
[snapshot](https://www.minecraft.net/en-us/article/minecraft-snapshot-24w09a)

### Is your feature request related to a problem?

A breaking change.

### Describe alternatives you've considered

N/A

**Comment by Asleeepp** [comment]
Realised you need paper/spigot to update their api first, this issue still stands though.

**Comment by LoneDev6** [comment]
bruh
