### ISSUE TITLE
Cannot load emojis

### ISSUE THREAD

**Issue by alazeprt** [PluginBugs/Issues-ItemsAdder#3474]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

After installing the itemsAdder according to the installation method in the wiki, the item display is normal, while emojis display is abnormal, displaying as a small white square

### Steps to reproduce the issue

1. Install ItemsAdder, LoneLibs, and Protocollib
2. Add default pack
3. Change the resource packet hosting mode to self host
4. Execute /iazip command

### Server version

This server is running Leaves version git-Leaves-"e52beae" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: e52beae)

### ItemsAdder Version

ItemsAdder version 3.6.3-beta-13

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.45

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/14461214/latest.log)

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/92018941/b7a6f110-a985-4e24-ac34-09952b423b5a)

**Comment by enesop** [comment]
Does any of your other resources work, also have you checked your server console at all after running /iazip, I cannot reproduce the issue?

It could also possibly be a protocol patch from your Leaves jar.

**Comment by LoneDev6** [comment]
Client log always provides info why the textures didn't load.

Also the server log when you run /iazip contains info on what failed to load an why, most of the times.

Please refer to the tutorial to find out the cause: https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown
