### ISSUE TITLE
Add option to place item frame furniture on the opposite side

### ISSUE THREAD

**Issue by EpicPlayerA10** [PluginBugs/Issues-ItemsAdder#3478]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

epicplayera10

### Describe the solution you'd like

Add option to place item frame furniture on the opposite side.

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/62206933/4d2e3b59-3117-4a55-b945-6c227d597f4b)

### Is your feature request related to a problem?

When you create a large model and item frame is placed at the bottom then the model would disappear when you look up a little.
when you use flipped model and flipped item frame, then it wouldn't disappear in most cases because the item frame is in your field of view.

OriginRealms also makes some furniture in this way (flipped model, flipped item frame).

### Describe alternatives you've considered

Move model in blockbench a little down and in game place furniture a little up. But it isn't very practical because the hitbox also moves up and it is very hard to break that kind of furniture, because you need to find where the item frame was originally placed. The solution for what would be the `interaction entity` #3193 in future update.

**Comment by LoneDev6** [comment]
This will be fixed when using item_display as they don't have this rendering issue.
#2458
