### ISSUE TITLE
Bug when rejoin to server

### ISSUE THREAD

**Issue by SliderKP** [PluginBugs/Issues-ItemsAdder#3480]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

exxslider

### What happened?

When i relogin to the server without enterely disconect, the texturepack dosnt download again and im freeze

another problem is this:
https://forum.devs.beer/d/2272-error-with-displayname-in-items
if i remove the img_ice the gradient works fine.

### Steps to reproduce the issue

1- Connect to server with texturepack
2- go to another server in the network
3- connect again to the server with texture pack
4- you are freeze and cant move,
5- to solve disconnect from server and join again (leaving to minecraft menu)

https://jumpshare.com/s/ENHERuqFnOI4L2Ce7Wed

### Server version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/6493041/6ee81832-a2ff-4616-9293-b3d0ca5cc66b)
[13:55:37 INFO]: SliderKP issued server command: /pufferfish
[13:55:37 INFO]: SliderKP: Pufferfish » This server is running Pufferfish version git-Pufferfish-46 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT)

### ItemsAdder Version

[14:00:30 INFO]: -=[ ItemsAdder ]=-
[14:00:30 INFO]: Version: 3.6.3-beta-13

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/6493041/fcf2fbc9-4058-4f94-8ea4-49bbdcf10131)
[14:01:46 INFO]: ProtocolLib v5.2.0-SNAPSHOT-679
[14:01:46 INFO]: Authors: dmulloy2 and Comphenix
[14:01:46 INFO]: Issues: https://github.com/dmulloy2/ProtocolLib/issues

### LoneLibs Version

my version command is disabled, but the version is:
LoneLibs 1.0.45

### FULL server log

[latest (2).log](https://github.com/PluginBugs/Issues-ItemsAdder/files/14482533/latest.2.log)

### Error (optional)

```shell
not neccesary
```

### Problematic items yml configuration file (optional)

```shell
not neccesary
```

### Other files, you can drag and drop them here to upload. (optional)

not neccesary

### Screenshots/Videos (you can drag and drop files or paste links)

aasdasd

**Comment by SliderKP** [comment]
aparently solved with the new update of viaversion

**Comment by LoneDev6** [comment]
> aparently solved with the new update of viaversion

So is it fixed?

**Comment by SliderKP** [comment]
Fixed, thanks a lot.
