### ISSUE TITLE
durability is ruined

### ISSUE THREAD

**Issue by QuitoYT** [PluginBugs/Issues-ItemsAdder#3482]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I modified the durability of my armor but when they attack me it returns to the durability of leather armor. Does anyone know why?

### Steps to reproduce the issue

1.- get item from /ia
2.- equip it
3.- that a zombie attacks me

### Server version

spigot 1.20.2

### ItemsAdder Version

3.6.3-beta-13

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

### FULL server log

no log, no log is created in the console

### Problematic items yml configuration file (optional)

```shell
All my items
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/93755355/3c6aad46-841d-4800-b598-76cc2cb6a8bf)
![image2](https://github.com/PluginBugs/Issues-ItemsAdder/assets/93755355/ffea3a92-1733-4222-bc77-29da95132650)

**Comment by potapenchikov** [comment]
It's not broken. The visual displays the strength of leather armor, but it is spent much more slowly than if it were leather armor
