### ISSUE TITLE
Add "rotatable" option to furnitures

### ISSUE THREAD

**Issue by Xiao-MoMi** [PluginBugs/Issues-ItemsAdder#3486]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

I've searched the wiki but there's nothing related to furniture rotations. 
I know that players can rotate the furniture by sneaking, but sometimes we don't want players to do that so an option to control rotations is necessary.

### Is your feature request related to a problem?

.

### Describe alternatives you've considered

.

**Comment by LoneDev6** [comment]
This is already implemented
Set this property in your furniture behaviour.
`shift_interact_rotate: false`
