### ISSUE TITLE
Feature: ItemsAdder#getNamespacedIDByStack

### ISSUE THREAD

**Issue by Plinkie03** [PluginBugs/Issues-ItemsAdder#3487]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Alizee

### Describe the solution you'd like

Title

### Is your feature request related to a problem?

Yes

### Describe alternatives you've considered

None.

### Additional context

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/153200269/71745168-f5d4-4f6c-85b8-7d5004f57678)

**Comment by LoneDev6** [comment]
> when a custom model data of the item changes, this does no longer recognize it as a custom item

This is quite strange, it should work anyway. Are you sure it's the cause?

By the way try to use this method instead: [ItemsAdder#getCustomItemName(itemstack)](https://github.com/LoneDev6/API-ItemsAdder/blob/master/src/main/java/dev/lone/itemsadder/api/ItemsAdder.java#L206)
