### ISSUE TITLE
Both custom and official vehicles not moving

### ISSUE THREAD

**Issue by shradinx** [PluginBugs/Issues-ItemsAdder#3495]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Shradinx

### What happened?

Any vehicle, both custom ones I configure and ones from the iavehicles addon, do not move and are stuck in place. The sounds also do not seem to be working

### Steps to reproduce the issue

1. Add iavehicles to ItemsAdder
2. Place down any vehicle, such as a plane or shopping cart
3. Get in the vehicle and attempt to move

### Server version

This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
You are running the latest version

### ItemsAdder Version

ItemsAdder version 3.6.3-beta-13

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.45

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/14594077/latest.log)

### Screenshots/Videos (you can drag and drop files or paste links)

[Video of bug](https://youtu.be/E1OVSbOq4kI)

**Comment by LoneDev6** [comment]
Update to 1.20.3 or 1.20.4 and remove all plugins, keep only ItemsAdder (+its dependencies) and test if the issue still occurs.

**Comment by shradinx** [comment]
After updating to 1.20.4 and removing all plugins except ItemsAdder and its dependencies, the issue does not occur. However, the issue appears again when downgrading to 1.20.2 and removing all plugins except for ItemsAdder and its dependencies.

**Comment by LoneDev6** [comment]
It's hard to tell why it doesn't work on your 1.20.2 installation as it works fine on mine.
What I suggest you is to update to 1.20.4 or install Paper 1.20.2 or try Purpur 1.20.2.
You can also try to remove all other plugins on 1.20.2 and test if the issue still occurs, but shouldn't.
