### ISSUE TITLE
Posting a message using the /emoji command does not add a colour code in front of the emoji

### ISSUE THREAD

**Issue by enesop** [PluginBugs/Issues-ItemsAdder#3496]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/60015283/81696b42-a687-49f6-9c15-732284420ea2)
When I post a message with, /emoji <emoji> Hi, the emoji will be greyed out as the chat format is grey colour. If I post the message normally, simply type out :emoji: Hi, the emoji is white.

### Steps to reproduce the issue

1. Set the default chat message colour to grey
2. Use the /emoji command to post a message
3. Emoji should be grayed out

### Server version

This server is running Paper version git-Paper-450 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 62b220a)

### ItemsAdder Version

3.6.3-beta-13

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

**Comment by LoneDev6** [comment]
Do you use any chat message?
If yes, please provide the configuration for it so that I can test.
