### ISSUE TITLE
getting textures from servers

### ISSUE THREAD

**Issue by SrMonsterYT** [PluginBugs/Issues-ItemsAdder#3505]

**Comment by paulreob** [comment]
Read this
[https://itemsadder.devs.beer/plugin-usage/resourcepack-hosting/protect-resourcepack-from-unzip](url)

**Comment by SrMonsterYT** [comment]
> Read this [https://itemsadder.devs.beer/plugin-usage/resourcepack-hosting/protect-resourcepack-from-unzip](url)

No results matched your search.

**Comment by paulreob** [comment]
> No results matched your search.

douh, read the wiki
https://itemsadder.devs.beer/plugin-usage/resourcepack-hosting/protect-resourcepack-from-unzip

**Comment by SrMonsterYT** [comment]
> > No results matched your search.
> 
> douh, read the wiki https://itemsadder.devs.beer/plugin-usage/resourcepack-hosting/protect-resourcepack-from-unzip
