### ISSUE TITLE
Cannot be like a normal plant, if the square below is broken, the plant will drop

### ISSUE THREAD

**Issue by xingfujiuhao** [PluginBugs/Issues-ItemsAdder#3507]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

0001

### Describe the solution you'd like

Cannot be like a normal plant, if the square below is broken, the plant will drop.  I don't know how to become like a normal plant

### Is your feature request related to a problem?

yes

### Describe alternatives you've considered

There is nothing to preview

### Additional context

I don't know how to become like a normal plant

**Comment by LoneDev6** [comment]
Please add more details and post a video and/or screenshots to explain the issue.
