### ISSUE TITLE
I cannot play the added sounds or execute them by commands

### ISSUE THREAD

**Issue by RitsuElAnti** [PluginBugs/Issues-ItemsAdder#3508]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Ritsu#9014

### What happened?

I interact with a piece of furniture or execute the "playsound" command and the custom audio is not heard
I also added it to a piece of furniture so that it plays the sound when interacting and you can't hear it either.

### Steps to reproduce the issue

1- I execute "/playsound minecraft:toilet ambient myname"
2- can't be heard

### Server version

This server is running Paper version git-Paper-450 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 62b220a)
You are 5 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-436 (MC: 1.20.4)

### ItemsAdder Version

3.6.3-beta-13

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: mismuebles
items:
  toilet:
    template: true 
    enabled: true
    display_name: toilet
    lore:
    - Electrodoméstico
    - Interactivo
    permission: all
    resource:
      material: PAPER
      generate: false
      model_path: toilet
    behaviours:
      furniture:
        solid: true
        small: true
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          height: 1
          length: 1
          width: 1
    events:
      placed_armorstand:
        interact:
          play_sound:
            name: itemsadder:missonidos.toilet
            volume: 1
            pitch: 1
  toilet_blanca:
    variant_of: toilet
    enabled: true
    display_name: Inodoro Blanca
    resource:
      material: LEATHER_HORSE_ARMOR
      generate: false
      model_path: toilet
```

### Other files, you can drag and drop them here to upload. (optional)

[sounds.json](https://github.com/PluginBugs/Issues-ItemsAdder/files/14670497/sounds.json)

**Comment by LoneDev6** [comment]
`/playsound itemsadder:missonidos.toilet ambient myname`

Also make sure you put the ogg file and the json in the correct folders.
Please follow the tutorial correctly, you surely made a little mistake: https://itemsadder.devs.beer/plugin-usage/adding-content/sounds/adding-sounds

**Comment by RitsuElAnti** [comment]
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/119564188/4adbb8e3-6f0d-4adf-92fc-eb13078dabb8)
Follow the entire guide on the page, surely, it is my fault, I checked the location, as in the photo, but I cannot execute them, thank you very much for the help and inconvenience, sorry for the inconvenience here since I cannot ask.
Also, unfortunately the existing tutorials are outdated to be able to guide me with them, an example is this:
https://www.youtube.com/watch?v=pvFT6wdqp0Y&list=PL58WCyprowcGxLjXlIX4Ez4JUzZAQ4acv&index=7&ab_channel=Edward%27sThings

**Comment by LoneDev6** [comment]
Hello, I am not the author of the video tutorials, they are unofficial.
Anyway checking the client log will definitely tell you why some sounds didn't load, there is no other way to find out the cause of the misconfiguration.
You can try to download the default pack and execute some of my example sounds, I'm sure they will work fine so you can guess the mistake in your pack files.
https://github.com/ItemsAdder/DefaultPack
`contents\iasurvival\resourcepack\iasurvival\sounds.json`

**Comment by RitsuElAnti** [comment]
Great, I'll be testing it, and as soon as I solve it I'll let you know, given that for example in emotes if you play the sound but not with the command, would there be some way you can see a reel of a person who shares your plugin for free, so you can report it
