### ISSUE TITLE
Can't set file file attribute ia_compression_handled: 

### ISSUE THREAD

**Issue by ciliomine** [PluginBugs/Issues-ItemsAdder#3512]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/99097647/c5a5042e-dcde-455b-a9ef-5f40a481728a)
https://pastebin.com/EuudMW2B

it dont happen to me in localhost. 

### Steps to reproduce the issue

i dont know i just go to add other textures 

### Server version

pufferfish-paperclip-1.20.4-R0.1-SNAPSHOT-reobf

### ItemsAdder Version

ItemsAdder_3.6.3-beta-13

### ProtocolLib Version

version: 5.2.0-SNAPSHOT-679

### LoneLibs Version

version: 1.0.45

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1383#issuecomment-1004952183
