### ISSUE TITLE
No permission to use recipes that don't have a permission

### ISSUE THREAD

**Issue by xDec0de** [PluginBugs/Issues-ItemsAdder#3513]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

xdec0de

### What happened?

I createad a recipe that doesn't have a permission set, assuming this makes it available to every player as "all-on-join" is set to true on the config. I'm using a rank system that doesn't use permissions, so I don't a permission plugin, I don't even have Vault installed. Here is a sreenshot of what happens when I try to craft the item (The recipe is unlocked, it shows on the recipe book)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/63256529/a9d8bacc-e14f-47b9-9a36-589a97d327bf)

### Steps to reproduce the issue

1. Create a new item.
2. Add a recipe to it, without a permission.
3. Try to craft the item.

### Server version

This server is running Paper version git-Paper-459 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 88419b2)
You are running the latest version

### ItemsAdder Version

ItemsAdder version 3.6.3-beta-13

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.45

### Other files, you can drag and drop them here to upload. (optional)

info:
  namespace: uhc
items:
  golden_head:
    enabled: true
    display_name: "Golden Head"
    resource:
      material: GOLDEN_APPLE
      generate: true
      textures:
      -  food/golden_head.png
recipes:
  crafting_table:
    golden_head:
      enabled: true
      pattern:
      - GGG
      - GHG
      - GGG
      ingredients:
        G: GOLD_INGOT
        H: PLAYER_HEAD
      result:
        item: uhc:golden_head
        amount: 1

**Comment by LoneDev6** [comment]
>  I'm using a rank system that doesn't use permissions, so I don't a permission plugin

You must have a permissions plugin installed on your server. I suggest luckperms which is the best.

**Comment by xDec0de** [comment]
Why would I need a permission plugin if I'm not using permissions though? The recipe is set to not require a permission as far as I know. I'm intentionally not using a permission plugin because I have my own rank system that compares ranks instead of permissions because I use mostly my own plugins with ItemsAdder being an exception (I use it with the API).

This is no longer an issue for me as I resolved it by making the recipes myself, but it may be helpful for someone else.
