### ISSUE TITLE
Different melting times

### ISSUE THREAD

**Issue by mulciberxz** [PluginBugs/Issues-ItemsAdder#3515]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I have tried to develop a recipe for faster melting of iron/gold/copper, which is unique for different furnaces. Here is the recipe I used:

```tml
iron_raw_blast:
 enabled: true
 ingredient:
 item: raw_iron_block
 machines: **BLAST_FURNACE**
 exp: 6.3
 cook_time: **900**
 result:
 item: iron_block
 amount: 1

iron_raw:
 enabled: true
 ingredient:
 item: raw_iron_block
 machines:  **FURNACE**
 exp: 6.3
 cook_time: **1800**
 result:
 item: iron_block
 amount: 1
```

The melting time is different **(Highlighted)**, but for some reason, the melting time in the game itself has not changed in any way (The melting time still becomes the same)

### Steps to reproduce the issue

See above recipe.
Try and smelt "raw iron block" in a regular furnace and blast furnace with that recipe loaded.

### Server version

Current: git-Purpur-2095 (MC: 1.20.2)*

### ItemsAdder Version

[16:32:15 INFO]: ItemsAdder version 3.6.3-beta-13
[16:32:15 INFO]: Customized Minecraft without client mods!
[16:32:15 INFO]: Website: devs.beer
[16:32:15 INFO]: Author: LoneDev

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

### FULL server log

I can provide this if needed, but otherwise I choose to withhold it at this time if that's ok.

### Problematic items yml configuration file (optional)

```shell
recipes:
  cooking:
    iron_raw_blast:
      enabled: true
      ingredient:
        item: raw_iron_block
      machines:
      - BLAST_FURNACE
      exp: 6.3
      cook_time: 10
      result:
        item: iron_block
        amount: 1
    iron_raw:
      enabled: true
      ingredient:
        item: raw_iron_block
      machines:
      - FURNACE
      exp: 6.3
      cook_time: 1800
      result:
        item: iron_block
        amount: 1
```

**Comment by LoneDev6** [comment]
Can you try without any other plugin installed? Last time I tested that it worked just fine.
