### ISSUE TITLE
IaPlayerStats without need of HUD

### ISSUE THREAD

**Issue by PSYCHEER** [PluginBugs/Issues-ItemsAdder#3518]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

PSYCHEER

### Describe the solution you'd like

New system for player stats to use without hud lie events

### Is your feature request related to a problem?

Yes, Im using custom plugin to show HUD and I need then to make a transparent texture for hud bcz how itemsadder works

### Describe alternatives you've considered

Make player stats independent on hud and use hud just as a value show up

**Comment by LoneDev6** [comment]
This breaks the logic of the player stats, they are meant to be used on huds.
If you need to save custom player data you can implement it in your custom plugin.
