### ISSUE TITLE
Iterate over all custom blocks in a chunk

### ISSUE THREAD

**Issue by XLordalX** [PluginBugs/Issues-ItemsAdder#3520]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

I would like a method to get all the custom blocks in a chunk.

### Is your feature request related to a problem?

n/a

### Describe alternatives you've considered

n/a

### Additional context

Related: #3445

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/3445#issuecomment-2072898638
