### ISSUE TITLE
Problems with REAL_NOTE

### ISSUE THREAD

**Issue by potapenchikov** [PluginBugs/Issues-ItemsAdder#3524]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I have been trying for a very long time to solve problems with user blocks (mainly REAL_NOTE) in order to completely give them up for use by players without fear of various bugs, features, and the most important of them, which are most disturbing and which I have not been able to solve for a very long time, I have put in three points below
And so, with custom blocks, you can look at three things forever:
1. How do they lose textures back to a real note or other custom block when interacting with water, lava, etc
2. How the fire burns endlessly on custom blocks
3. How user blocks flicker showing real_note when breaking or just at a random moment in time just like that

I mostly work with REAL_NOTE and I can't speak for other options for custom blocks, but it is he who worries me. It is the most stable and works very well compared to regular vanilla blocks.
(Below are screenshots of the custom mycelium block, its generation and burning)

### Steps to reproduce the issue

1.We create a REAL_NOTE block and set its generation. We fly to see the places where it will appear next to water lava or any other physics in the game without texture
2.Just set fire to the REAL_NOTE custom block and watch it burn endlessly
3. We break the blocks standing next to the user's REAL_NOTE in the creative and observe the appearance of the NOTE_BLOCK texture for a second. And sometimes, just by watching a custom block, you can see the same thing for no reason.

### Server version

This server is running Pufferfish version git-Pufferfish-19 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 2611af8 on HEAD)

### ItemsAdder Version

3.6.3-beta-13

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/123487110/819caec5-44ce-4403-bba2-34cfa521cf10)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/123487110/8920305d-a73b-46cc-a4a9-508ca18a415c)

**Comment by LoneDev6** [comment]
I highly doubt these issues can be fixed because of how custom blocks work.
