### ISSUE TITLE
API - Incompatible with Paper API, gives error: "Failed to register events because event does not exist" when referring to classes when using Paper

### ISSUE THREAD

**Issue by August821** [PluginBugs/Issues-ItemsAdder#3528]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Fresh paper minecraft server, fresh plugin installs, only changes to config were self-hosting resource pack, recreated the bug on two different machines with separate installs. When registering for the event CustomBlockBreakEvent through the api (installed via maven, as per github instructions) server console spits out this message on enable:

[01.04 11:08:17] [Server] [ERROR] [Spawner] Failed to register events for class xxx.xxx.spawner.EventListener because dev/lone/itemsadder/api/Events/CustomBlockBreakEvent does not exist.

`@Override
    public void onEnable() {
        getServer().getPluginManager().registerEvents(new EventListener(), this);
    }`
 
`public class EventListener implements Listener {
    @EventHandler
    public void onCustomBlockBreak(CustomBlockBreakEvent event) {
        event.getPlayer().sendMessage(Component.text("You broke a custom block!"));
    }
}`

If it is just an issue of my own I'd be happy to find out why its not working :)

### Steps to reproduce the issue

1. Fresh install of paper minecraft from papermc.io
2. Accept eula, run and restart server
3. Install latest version of ItemsAdder and its dependencies
4. Configure config, I just added self-host and made a custom block
5. Fresh InteliJ minecraft plugin with latest version of paper, literally only has two classes and two functions. (see above)
6. Do pom.xml

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>xxx.xxx</groupId>
    <artifactId>Spawner</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>Spawner</name>

    <properties>
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <repositories>
        <repository>
            <id>papermc-repo</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
        <repository>
            <id>jitpack-repo</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-api</artifactId>
            <version>1.20.4-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.github.LoneDev6</groupId>
            <artifactId>api-itemsadder</artifactId>
            <version>3.6.2-beta-r3-b</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
`

7. Open project structure, (ctrl + alt + shift + s), artifacts, Add, JAR, From modules with dependencies, Okay, Apply, Okay
8. Build, Build artifacts, Build
9. Copy new plugin to server plugins
10. Restart server
11. Get this wonderful message: `[01.04 14:09:51] [Server] [ERROR] [Spawner] Failed to register events for class xxx.xxx.spawner.EventListener because dev/lone/itemsadder/api/Events/CustomBlockBreakEvent does not exist.`

Being as detailed as possible just so I know if its me being stupid or an actual bug.

UPDATE: Fixed when changed API from Paper to Spigot in IntelliJ, leaving as a bug report because I still believe this is an issue.

### Server version

This server is running Paper version git-Paper-463 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 45d1486)
You are running the latest version

### ItemsAdder Version

[INFO] ItemsAdder version 3.6.3-beta-13
[INFO] Customized Minecraft without client mods!
[INFO] Website: devs.beer
[INFO] Author: LoneDev

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.45

### FULL server log

[01.04 14:09:47] [Server] [INFO] [ItemsAdder] Enabling ItemsAdder v3.6.3-beta-13
[01.04 14:09:48] [Server] [INFO] [NBTAPI] [NBTAPI] Found Spigot: v1_20_R3! Trying to find NMS support
[01.04 14:09:48] [Server] [INFO] [NBTAPI] [NBTAPI] NMS support 'MC1_20_R3' loaded!
[01.04 14:09:50] [Server] [INFO] [ItemsAdder] 
[01.04 14:09:50] [Server]   ___  ___        __        __   __   ___  __      ItemsAdder 3.6.3-beta-13
[01.04 14:09:50] [Server] |  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.45
[01.04 14:09:50] [Server] |  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Paper git-Paper-(MC: 1.20.4)
[01.04 14:09:50] [Server] [INFO] [ItemsAdder] [Host] Starting self-host webserver on port: 8163
[01.04 14:09:51] [Server] [INFO] [Spawner] Enabling Spawner v1.0-SNAPSHOT
[01.04 14:09:51] [Server] [ERROR] [Spawner] Failed to register events for class xxx.xxx.spawner.EventListener because dev/lone/itemsadder/api/Events/CustomBlockBreakEvent does not exist.
[01.04 14:09:51] [Server] [INFO] Running delayed init tasks
[01.04 14:09:51] [Server] [INFO] [ItemsAdder] [Pack] Extracting internal contents from .jar
[01.04 14:09:51] [Server] [INFO] [ItemsAdder] [License] Spigot product licensed to: August821 (1504780)
[01.04 14:09:51] [Server] [INFO] [ItemsAdder] [Pack] DONE extracting internal contents from .jar

**Comment by August821** [comment]
Been asking on the discord too, sent my whole jar file, every file and setting and got no answers.

**Comment by August821** [comment]
Found the issue - It's compatible with the spigot API but breaks when using the paper api.  tysm Block_Eater on discord lmao

**Comment by LoneDev6** [comment]
I doubt it's related to Paper vs Spigot.
For some reason the CustomBlockBreakEvent class is not loaded and not available.
Maybe the plugin failed to load so the API is not available so Java freaks out.

Another cause is that maybe Paper is doing some crazy shit relocating stuff, so the compiled code is different from the server code, for some reason.
Idk.
