### ISSUE TITLE
Furniture after update randomly displays "itemsadder_furniture" holograms.

### ISSUE THREAD

**Issue by pingarss** [PluginBugs/Issues-ItemsAdder#3529]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

After updating to the very latest version, including all of the dependecies, joining server again, i noticed that now all of the custom blocks and funriture displays a hologram on top of it with a text "itemsadder_furniutre". Tho i am not sure if itemsadder is responisble for this, this is the only place i can think of to reach out. I have checked configs on bot contents files and itemsadder config, i thought maybe something new is added and set true by default. 

### Steps to reproduce the issue

1. I'm unsure how to reproduce  this bug/error since it happened randomly after updating all.

### Server version

1.20.4

### ItemsAdder Version

3.6.3-beta-13

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

### FULL server log

There are no errors what so ever.

### Problematic items yml configuration file (optional)

```shell
Nothing in configs shows a problem of any contents folder
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image_2024-04-01_150408085](https://github.com/PluginBugs/Issues-ItemsAdder/assets/151857185/ca10e8cc-1e8d-4049-b35c-5b28e214cb24)
![image_2024-04-01_150444099](https://github.com/PluginBugs/Issues-ItemsAdder/assets/151857185/163759d6-924a-4814-9e3d-7225fa5f2be5)
![image_2024-04-01_150513827](https://github.com/PluginBugs/Issues-ItemsAdder/assets/151857185/0e10d479-41e0-4fcd-beb0-2d925a771924)

**Comment by LoneDev6** [comment]
This probably has to do with some other plugin messing up with armorstands which made them show the display name when they are not supposed to.
ItemsAdder doesn't do that.

Another cause might be a client mod which forces showing the entities names, try to join with a clean vanilla client.

**Comment by pingarss** [comment]
These are the plugins i have:
AdvancedPortals, ajLeaderboards, AutoComposter, BetterRTP, *BlockBall, CharacterDialogue, Chunky, Citizens, CMILib, ConditionalEvents
CosmeticsCore, DecentHolograms, DeluxeHub, DeluxeMenus, DiscordSRV, Essentials, EssentialsChat, EssentialsSpawn, ExcellentCrates, ExcellentShop
FastAsyncWorldEdit, *FriendSystem-Spigot-Standalone, *FriendSystemGUI, Furnish, GPFlags, GriefPrevention, GSit, HMCWraps, Images, InteractiveBooks
 Interface4, ItemEdit, ItemsAdder, ItemsAdderEmojiFixer, Jobs, KitPvP, LoneLibs, LuckPerms, MCPets, ModelEngine
ModelEngineMerger, Multiverse-Core, Multiverse-Inventories, MythicMobs, NamelessMC, NBTAPI, NexEngine, ODailyQuests, PinataParty, PlaceholderAPI
*PlayTime, Polymart, ProtocolLib, Quests, RecyclerPlus, ServerListPlus, Shopkeepers, SkinsRestorer, Skript, Space
spark, *STN-Studios-API, TAB, Tooltips, Vault, Vegas, ViaBackwards, ViaVersion, VoidGen, Votifier
 WorldGuard, WorldGuardExtraFlags
 
 Could DecentHolograms be reposnible for this? I looked in configs and didnt saw anything...
