### ISSUE TITLE
Custom blocks - reduce lag of physics events caused by farms

### ISSUE THREAD

**Issue by Projecki** [PluginBugs/Issues-ItemsAdder#3534]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Projecki

### What happened?

I get a lot of lag when using ItemsAdder.

The only reason I have ProtocolLib installed is for ItemsAdder. No other plugin I use requires ProtocolLib.

https://spark.lucko.me/vKie0lSXfE
https://spark.lucko.me/Yy005e5ZOW

### Steps to reproduce the issue

1. Use ItemsAdder 

### ItemsAdder Version

beta-13

### ProtocolLib Version

5.20-679

### LoneLibs Version

1.0.45

### Other files, you can drag and drop them here to upload. (optional)

[message (37).txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/14839145/message.37.txt)
my IA config, I have mostly everything disabled

I don't use any custom blocks, yet I see methods related to custom blocks in my spark report. Why?

**Comment by LoneDev6** [comment]
You have a place in your map that has a lag machine or some bugged blocks that keep ticking extensively.
Use this plugin to try to find out where the lag originates.
https://www.spigotmc.org/resources/blockphysicseventdetector.84854/

**Comment by Projecki** [comment]
![Screen Shot 2024-04-11 at 5 39 05 PM](https://github.com/PluginBugs/Issues-ItemsAdder/assets/65093423/a8f66760-d119-486a-a13d-bd85851b18ca)

Apologies for the delay. 

I've used the plugin and found these locations - they're mostly large cactus farms & a large redstone lamp build.

So, nothing involving custom blocks from ItemsAdder.

Is this information helpful? Why would cactus & redstone lamps show up as ticks under ItemsAdder plugin on the spark report?

**Comment by LoneDev6** [comment]
Because itemsadder has to check if these physics events are caused by custom blocks and cancel them.
Sadly physics events are triggered a lot so they cause overhead.
There is little I can do to fix that other than you avoid allowing farms on your server (which generally ruin the vanilla experience, but it's my opinion).
I will in the future try to find a way to reduce this but I doubt there is a solution.
This issue is cited also in this idea: https://github.com/PluginBugs/Issues-ItemsAdder/issues/3537

**Comment by Projecki** [comment]
Hmmm, is it not possible to add a toggle for these checks in config or something?

I utilize zero custom blocks on my server, so there's no need for ItemsAdder to be using so much overhead for something it should already know.

**Comment by LoneDev6** [comment]
@Projecki you can already disable custom blocks and they won't register any physics listener.
Disable them in config.yml

**Comment by Projecki** [comment]
Check out my config I linked in the original post, I believe I do have custom blocks disabled. Despite this, the lag issue persists.

**Comment by LoneDev6** [comment]
Set this:
```yml
  disable-REAL: true
  disable-REAL_NOTE: true
  disable-REAL_TRANSPARENT: true
  disable-REAL_WIRE: true
  disable-FIRE: true
```
