### ISSUE TITLE
Custom armors with only armor color without itemsadder NBT won't render texture on Optifine or CIT Resewn

### ISSUE THREAD

**Issue by EpicPlayerA10** [PluginBugs/Issues-ItemsAdder#3535]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

epicplayera10

### What happened?

Custom armors that have only applied armor color without itemsadder nbt won't show armor texture on Optifine or CIT Resewn. I'm using MMOItems that doesn't add itemsadder NBT.

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/62206933/4b6c0117-478b-4e89-a44b-29de40241f78)

#### Solution

This bug is caused in CIT configuration because itemsadder matches itemsadder NBT instead of armor color like in vanilla.

I tested various CIT configs and I figured it out that instead of these lines:
```properties
nbt.itemsadder.namespace=some_namespace
nbt.itemsadder.id=some_custom_armor
```
you would replace with this line:
```properties
nbt.display.color=11127617
```
where these numbers converted to hex (`11127617` -> `A9CB41`) is the armor color for texture rendering.

When I change CIT config with these lines above, then the armor renders correctly on both vanilla and optifine and cit resewn.

### Steps to reproduce the issue

1. Setup a custom armor
2. Join to the server using OptiFine or CIT Resewn mod
3. Get a leather part (for example leather chestplate) and set only armor color that corresponds to your armor renderer.
4. Wear it
5. See that armor texture won't render

### Server version

This server is running Paper version git-Paper-464 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: e709245)

### ItemsAdder Version

ItemsAdder version 3.6.3-beta-13

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.45

**Comment by LoneDev6** [comment]
Is this a really necessary change?

**Comment by EpicPlayerA10** [comment]
> Is this a really necessary change?

Yes, because firstly I use CIT Resewn to show custom armor correctly on shaders, and secondly I use MMOItems for easy management of custom items with skills and Revision ID system. This change won't break anything because changing it to match armor color will match the vanilla behaviour. It is not very hard.

**Comment by umutardafiliz** [comment]
i agree this should be done to make it easier to use with other plugins

**Comment by Tranquilotl** [comment]
Is there a way to handle this issue from clientside? I am experiencing this issue on a server I do not own.
