### ISSUE TITLE
I don't understand, all my textures load but not the emojis.

### ISSUE THREAD

**Issue by DrakoriaDev** [PluginBugs/Issues-ItemsAdder#3540]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

at0m357

### What happened?

I don't understand, all my textures load but not the emojis. But when I use an armor pack, the armors work, but never the emojis.

### Steps to reproduce the issue

I have only seen errors in the latest

### Server version

This server is running Paper version git-Paper-459 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 88419b2)

I also tried with a server with only ItemsAdder and its dependencies, no other plugins, but still the same problem.

### ItemsAdder Version

3.6.3-beta-8
I've tried with several different versions, and it doesn't change anything.

### ProtocolLib Version

5.2.0-SNAPSHOT-679
I've tried with several different versions, and it doesn't change anything.

### LoneLibs Version

1.0.45
I've tried with several different versions, and it doesn't change anything.

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/14886476/latest.log)

### Other files, you can drag and drop them here to upload. (optional)

[ItemsAdder.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/14886493/ItemsAdder.zip)

### Screenshots/Videos (you can drag and drop files or paste links)

https://github.com/PluginBugs/Issues-ItemsAdder/assets/164811219/c394e94d-32f2-4068-bbc8-0d3329d858e9

**Comment by DrakoriaDev** [comment]
I've tried everything: using a later version of Spigot, changing the version of ItemsAdder and its dependencies, trying on a local server, but nothing works. (On the local server, there was only ItemsAdder and its dependencies, and still nothing works)

**Comment by LoneDev6** [comment]
Did you follow the guide to know why something didn't load?
It's the only way to know why assets didn't load correctly: https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown
