### ISSUE TITLE
Furniture bug

### ISSUE THREAD

**Issue by SrMonsterYT** [PluginBugs/Issues-ItemsAdder#3544]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

mauriciooficial

### What happened?

when I get close the bug happens on some models

### Steps to reproduce the issue

video: https://youtu.be/RDT1qG0u0i8

have large models

### Server version

Pufferfish version git-Pufferfish-47 (MC: 1.20.4)

### ItemsAdder Version

ItemsAdder_3.6.3-beta-13.jar

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

### FULL server log

no error

**Comment by LoneDev6** [comment]
It's normal, it can't be fixed because of how Minecraft armorstands work.
It will be fixed when ItemsAdder will support display entities.
