### ISSUE TITLE
Main screen gone after updating lonelibs

### ISSUE THREAD

**Issue by iFranticman** [PluginBugs/Issues-ItemsAdder#3546]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

iFrantic

### What happened?

type /ia and can't see the menu anymore
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/54509048/ccebdf98-af5a-4fb9-b44e-309a6b4b268f)

### Steps to reproduce the issue

type /ia

### Server version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/54509048/63b9910c-1456-481e-8b63-fc31229cda0e)

### ItemsAdder Version

latest

### ProtocolLib Version

latest

### LoneLibs Version

latest

### FULL server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/14899912/latest.log)

**Comment by LoneDev6** [comment]
https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown

**Comment by iFranticman** [comment]
I'm not able to trace it back to anything. I updated cmlib and it broke it. Tried refreshing my font cache again but no luck

**Comment by iFranticman** [comment]
Rolled back cmlib and removed the most recent texture adds i did and it's still broken. I don't know what i did.

**Comment by iFranticman** [comment]
I have isolated the issue to the Space.Jar plugin. When i remove it it comes back working. Not sure what happened on his latest update but it broke your gui main screen.

**Comment by iFranticman** [comment]
I rolled back space.jar to prior version and itemsadder works again. I have reached out to ollie
