### ISSUE TITLE
Itemsadder pack protection.

### ISSUE THREAD

**Issue by Configaking** [PluginBugs/Issues-ItemsAdder#3555]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

gerihh

### Describe the solution you'd like

Itemsadder should get a decent pack protection.

### Is your feature request related to a problem?

_No_

### Describe alternatives you've considered

Itemsadder should use PackSquash's pack protection, because this pack protection is exporting the plugins into corrupt files, so my files cannot be copied or my images cannot be stolen/used, by simply opening the server-resource-pack folder and then rename my server's file. I know you can't fully stop people to stole my pack, but please do it because so many people stole our pack in 1 minute.

**Comment by LoneDev6** [comment]
https://itemsadder.devs.beer/plugin-usage/resourcepack-hosting/protect-resourcepack-from-unzip
