### ISSUE TITLE
Color codes broken on some random pieces of items

### ISSUE THREAD

**Issue by sennby** [PluginBugs/Issues-ItemsAdder#3561]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

senby8

### What happened?

https://forum.devs.beer/d/2288-broken-textures-color-codes/8
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/138246331/c590cd74-a862-4728-ab97-376dd6a12d13)

### Steps to reproduce the issue

these used to work, now they dont out of nowhere.

### Server version

[15:28:14 INFO]: Checking version, please wait...
[15:28:14 INFO]: This server is running UniverseSpigot version git-UniverseSpigot-"ab6ddf5" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: ab6ddf5 on ver/1.20.4-stable)
Universe-git-UniverseSpigot-"ab6ddf5" (MC: 1.20.4)

### ItemsAdder Version

[15:28:38 INFO]: ItemsAdder version 3.6.3-beta-13
[15:28:38 INFO]: Customized Minecraft without client mods!
[15:28:38 INFO]: Website: devs.beer
[15:28:38 INFO]: Author: LoneDev

### ProtocolLib Version

[15:28:50 INFO]: [VariableEnderChests] Loaded enderchest for masterianxd
[15:28:50 INFO]: ProtocolLib version 5.2.0-SNAPSHOT-679
[15:28:50 INFO]: Provides read/write access to the Minecraft protocol.

### LoneLibs Version

version lonelibs
[15:29:08 INFO]: LoneLibs version 1.0.45
[15:29:08 INFO]: Collection of libs used by my plugins
[15:29:08 INFO]: Authors: LoneDev and others

### Other files, you can drag and drop them here to upload. (optional)

info:
  namespace: ec_elitearmors
armors_rendering:
  ecgarnetknightarmor:
    color: '#79d336'
    layer_1: armor/ec_elitearmorsvol25/ecgarnetknightarmor
    layer_2: armor/ec_elitearmorsvol25/ecgarnetknightarmor_2
    emissive_1: armor/ec_elitearmorsvol25/ecgarnetknightarmore_1
    emissive_2: armor/ec_elitearmorsvol25/ecgarnetknightarmore_2
    use_color: false
  ecgoldenwrightarmor:
    color: '#94a218'
    layer_1: armor/ec_elitearmorsvol25/ecgoldenwrightarmor
    layer_2: armor/ec_elitearmorsvol25/ecgoldenwrightarmor_2
    emissive_1: armor/ec_elitearmorsvol25/ecgoldenwrightarmore_1
    emissive_2: armor/ec_elitearmorsvol25/ecgoldenwrightarmore_2
    use_color: false
  ecjadeemperorarmor:
    color: '#053300'
    layer_1: armor/ec_elitearmorsvol25/ecjadeemperorarmor
    layer_2: armor/ec_elitearmorsvol25/ecjadeemperorarmor_2
    emissive_1: armor/ec_elitearmorsvol25/ecjadeemperorarmore_1
    use_color: false
  ecstonesamuraiarmor:
    color: '#f4fba9'
    layer_1: armor/ec_elitearmorsvol25/ecstonesamuraiarmor
    layer_2: armor/ec_elitearmorsvol25/ecstonesamuraiarmor_2
    use_color: false
items:
  ecgarnetknightchest:
    display_name: '&#761717ᴅ&#6E1616ᴇ&#671515ᴍ&#5F1313ᴏ&#581212ɴ &#501111ʟ&#491010ᴏ&#410E0Eʀ&#3A0D0Dᴅ&#320C0Cs Chestplate' #Put the name of your armor here
    resource:
      generate: true
      textures:
      - item/ec_elitearmorsvol25/ecgarnetknightchest.png
    durability:
      max_custom_durability: 1800
    specific_properties:
      armor:
        slot: chest
        custom_armor: ecgarnetknightarmor
    attribute_modifiers:
      chest:
        armor: 8
        armorToughness: 3
        knockbackResistance: 0.1
    enchants:
      - protection:4
      - fire_protection:4
      - blast_protection:4
      - projectile_protection:4
      - thorns:3
      - unbreaking:3
      - mending:1
    lore:
      - ''
      - '          &#FF0000&l✶ &#761717ʜ&#721515ᴀ&#6D1313ᴜ&#691212ɴ&#641010ᴛ&#600E0Eᴇ&#5B0C0Cᴅ &#FF0000&l✶'
      - '&#FFFF70&l✶ &#761717ᴘ&#751616ᴇ&#731616ᴀ&#721515ᴄ&#701515ᴇ &#6F1414ʜ&#6D1414ᴀ&#6C1313s &#6B1212ʙ&#691212ᴇ&#681111ᴇ&#661111ɴ &#651010ʀ&#640F0Fᴇ&#620F0Fs&#610E0Eᴛ&#5F0E0Eᴏ&#5E0D0Dʀ&#5C0D0Dᴇ&#5B0C0Cᴅ &#FFFF70&l✶'
      - ''
  ecgarnetknighthelmet:
    display_name: '&#761717ᴅ&#6E1616ᴇ&#671515ᴍ&#5F1313ᴏ&#581212ɴ &#501111ʟ&#491010ᴏ&#410E0Eʀ&#3A0D0Dᴅ&#320C0Cs Helmet' #Put the name of your armor here
    resource:
      generate: true
      textures:
      - item/ec_elitearmorsvol25/ecgarnetknighthelmet.png
    durability:
      max_custom_durability: 1800
    specific_properties:
      armor:
        slot: head
        custom_armor: ecgarnetknightarmor
    attribute_modifiers:
      head:
        armor: 3
        armorToughness: 3
        knockbackResistance: 0.1
    enchants:
      - protection:4
      - fire_protection:4
      - blast_protection:4
      - projectile_protection:4
      - thorns:3
      - unbreaking:3
      - mending:1
      - respiration:3
      - aqua_affinity:1
    lore:
      - ''
      - '          &#FF0000&l✶ &#761717ʜ&#721515ᴀ&#6D1313ᴜ&#691212ɴ&#641010ᴛ&#600E0Eᴇ&#5B0C0Cᴅ &#FF0000&l✶'
      - '&#FFFF70&l✶ &#761717ᴘ&#751616ᴇ&#731616ᴀ&#721515ᴄ&#701515ᴇ &#6F1414ʜ&#6D1414ᴀ&#6C1313s &#6B1212ʙ&#691212ᴇ&#681111ᴇ&#661111ɴ &#651010ʀ&#640F0Fᴇ&#620F0Fs&#610E0Eᴛ&#5F0E0Eᴏ&#5E0D0Dʀ&#5C0D0Dᴇ&#5B0C0Cᴅ &#FFFF70&l✶'
      - ''
  ecgarnetknightlegs:
    display_name: '&#761717ᴅ&#6E1616ᴇ&#671515ᴍ&#5F1313ᴏ&#581212ɴ &#501111ʟ&#491010ᴏ&#410E0Eʀ&#3A0D0Dᴅ&#320C0Cs Leggings' #Put the name of your armor here
    resource:
      generate: true
      textures:
      - item/ec_elitearmorsvol25/ecgarnetknightleggings.png
    specific_properties:
      armor:
        slot: legs
        custom_armor: ecgarnetknightarmor
    attribute_modifiers:
      legs:
        armor: 6
        armorToughness: 3
        knockbackResistance: 0.1
    lore:
      - ''
      - '          &#FF0000&l✶ &#761717ʜ&#721515ᴀ&#6D1313ᴜ&#691212ɴ&#641010ᴛ&#600E0Eᴇ&#5B0C0Cᴅ &#FF0000&l✶'
      - '&#FFFF70&l✶ &#761717ᴘ&#751616ᴇ&#731616ᴀ&#721515ᴄ&#701515ᴇ &#6F1414ʜ&#6D1414ᴀ&#6C1313s &#6B1212ʙ&#691212ᴇ&#681111ᴇ&#661111ɴ &#651010ʀ&#640F0Fᴇ&#620F0Fs&#610E0Eᴛ&#5F0E0Eᴏ&#5E0D0Dʀ&#5C0D0Dᴇ&#5B0C0Cᴅ &#FFFF70&l✶'
      - ''
    durability:
      max_custom_durability: 1800
    enchants:
      - protection:4
      - fire_protection:4
      - blast_protection:4
      - projectile_protection:4
      - thorns:3
      - unbreaking:3
      - mending:1
  ecgarnetknightboots:
    display_name: '&#761717ᴅ&#6E1616ᴇ&#671515ᴍ&#5F1313ᴏ&#581212ɴ &#501111ʟ&#491010ᴏ&#410E0Eʀ&#3A0D0Dᴅ&#320C0Cs Boots' #Put the name of your armor here
    resource:
      generate: true
      textures:
      - item/ec_elitearmorsvol25/ecgarnetknightboots.png
    specific_properties:
      armor:
        slot: FEET
        custom_armor: ecgarnetknightarmor
    durability:
      max_custom_durability: 1800
    attribute_modifiers:
      feet:
        armor: 3
        armorToughness: 3
        knockbackResistance: 0.1
    lore:
      - ''
      - '          &#FF0000&l✶ &#761717ʜ&#721515ᴀ&#6D1313ᴜ&#691212ɴ&#641010ᴛ&#600E0Eᴇ&#5B0C0Cᴅ &#FF0000&l✶'
      - '&#FFFF70&l✶ &#761717ᴘ&#751616ᴇ&#731616ᴀ&#721515ᴄ&#701515ᴇ &#6F1414ʜ&#6D1414ᴀ&#6C1313s &#6B1212ʙ&#691212ᴇ&#681111ᴇ&#661111ɴ &#651010ʀ&#640F0Fᴇ&#620F0Fs&#610E0Eᴛ&#5F0E0Eᴏ&#5E0D0Dʀ&#5C0D0Dᴇ&#5B0C0Cᴅ &#FFFF70&l✶'
      - ''
    enchants:
      - protection:4
      - fire_protection:4
      - blast_protection:4
      - projectile_protection:4
      - thorns:3
      - unbreaking:3
      - mending:1
      - soul_speed:3
  ecgoldenwrightchest:
    display_name: '&#5B29FFᴘ&#6332F9ᴜ&#6B3BF3ʀ&#7344EDᴘ&#7B4DE8ʟ&#8356E2ᴇ&#8B5FDCᴘ&#9368D6ᴇ&#9B71D0ᴏ&#A277BAᴘ&#AA7DA4ʟ&#B1838Eᴇ&#B88978ᴇ&#BF8E61ᴀ&#C7944Bᴛ&#CE9A35ᴇ&#D5A01Fʀ Chestplate' #Put the name of your armor here
    resource:
      generate: true
      textures:
      - item/ec_elitearmorsvol25/ecgoldenwrightchest.png
    durability:
      max_custom_durability: 1800
    specific_properties:
      armor:
        slot: chest
        custom_armor: ecgoldenwrightarmor
    attribute_modifiers:
      chest:
        armor: 8
        armorToughness: 3
        knockbackResistance: 0.1
    enchants:
      - protection:4
      - fire_protection:4
      - blast_protection:4
      - projectile_protection:4
      - thorns:3
      - unbreaking:3
      - mending:1
      - respiration:3
      - aqua_affinity:1
      - soul_speed:3
      - curse_of_binding:1
      - curse_of_vanishing:1
      - thorns:3
    lore:
      - ''
      - '                &#FF0000&l✶&#9B71D0 ᴇᴀᴛᴇʀ &#FF0000&l✶'
      - '&#FFFF70&l✶ &#5B2EEFᴘᴜʀᴘʟᴇᴘᴇᴏᴘʟᴇᴇᴀᴛᴇʀ ʜᴀs ғᴀʟʟᴇɴ &#FFFF70&l✶'
      - ''
  ecgoldenwrighthelmet:
    display_name: '&#5B29FFᴘ&#6332F9ᴜ&#6B3BF3ʀ&#7344EDᴘ&#7B4DE8ʟ&#8356E2ᴇ&#8B5FDCᴘ&#9368D6ᴇ&#9B71D0ᴏ&#A277BAᴘ&#AA7DA4ʟ&#B1838Eᴇ&#B88978ᴇ&#BF8E61ᴀ&#C7944Bᴛ&#CE9A35ᴇ&#D5A01Fʀ Helmet' #Put the name of your armor here
    resource:
      generate: true
      textures:
      - item/ec_elitearmorsvol25/ecgoldenwrighthelmet.png
    durability:
      max_custom_durability: 1800
    specific_properties:
      armor:
        slot: head
        custom_armor: ecgoldenwrightarmor
    attribute_modifiers:
      head:
        armor: 3
        armorToughness: 3
        knockbackResistance: 0.1
    enchants:
      - protection:4
      - fire_protection:4
      - blast_protection:4
      - projectile_protection:4
      - thorns:3
      - unbreaking:3
      - mending:1
      - respiration:3
      - aqua_affinity:1
      - soul_speed:3
      - curse_of_binding:1
      - curse_of_vanishing:1
      - thorns:3
    lore:
      - ''
      - '                &#FF0000&l✶&#9B71D0 ᴇᴀᴛᴇʀ &#FF0000&l✶'
      - '&#FFFF70&l✶ &#5B2EEFᴘᴜʀᴘʟᴇᴘᴇᴏᴘʟᴇᴇᴀᴛᴇʀ ʜᴀs ғᴀʟʟᴇɴ &#FFFF70&l✶'
      - ''
  ecgoldenwrightlegs:
    display_name: '&#5B29FFᴘ&#6332F9ᴜ&#6B3BF3ʀ&#7344EDᴘ&#7B4DE8ʟ&#8356E2ᴇ&#8B5FDCᴘ&#9368D6ᴇ&#9B71D0ᴏ&#A277BAᴘ&#AA7DA4ʟ&#B1838Eᴇ&#B88978ᴇ&#BF8E61ᴀ&#C7944Bᴛ&#CE9A35ᴇ&#D5A01Fʀ Leggings' #Put the name of your armor here
    resource:
      generate: true
      textures:
      - item/ec_elitearmorsvol25/ecgoldenwrightleggings.png
    attribute_modifiers:
      legs:
        armor: 6
        armorToughness: 3
        knockbackResistance: 0.1
    lore:
      - ''
      - '                &#FF0000&l✶&#9B71D0 ᴇᴀᴛᴇʀ &#FF0000&l✶'
      - '&#FFFF70&l✶ &#5B2EEFᴘᴜʀᴘʟᴇᴘᴇᴏᴘʟᴇᴇᴀᴛᴇʀ ʜᴀs ғᴀʟʟᴇɴ &#FFFF70&l✶'
      - ''
    durability:
      max_custom_durability: 1800
    enchants:
      - protection:4
      - fire_protection:4
      - blast_protection:4
      - projectile_protection:4
      - thorns:3
      - unbreaking:3
      - mending:1
      - respiration:3
      - aqua_affinity:1
      - soul_speed:3
      - curse_of_binding:1
      - curse_of_vanishing:1
      - thorns:3
    specific_properties:
      armor:
        slot: legs
        custom_armor: ecgoldenwrightarmor
  ecgoldenwrightboots:
    display_name: '&#5B29FFᴘ&#6332F9ᴜ&#6B3BF3ʀ&#7344EDᴘ&#7B4DE8ʟ&#8356E2ᴇ&#8B5FDCᴘ&#9368D6ᴇ&#9B71D0ᴏ&#A277BAᴘ&#AA7DA4ʟ&#B1838Eᴇ&#B88978ᴇ&#BF8E61ᴀ&#C7944Bᴛ&#CE9A35ᴇ&#D5A01Fʀ Boots' #Put the name of your armor here
    resource:
      generate: true
      textures:
      - item/ec_elitearmorsvol25/ecgoldenwrightboots.png
    durability:
      max_custom_durability: 1800
    attribute_modifiers:
      feet:
        armor: 3
        armorToughness: 3
        knockbackResistance: 0.1
    lore:
      - ''
      - '                &#FF0000&l✶&#9B71D0 ᴇᴀᴛᴇʀ &#FF0000&l✶'
      - '&#FFFF70&l✶ &#5B2EEFᴘᴜʀᴘʟᴇᴘᴇᴏᴘʟᴇᴇᴀᴛᴇʀ ʜᴀs ғᴀʟʟᴇɴ &#FFFF70&l✶'
      - ''
    enchants:
      - protection:4
      - fire_protection:4
      - blast_protection:4
      - projectile_protection:4
      - thorns:3
      - unbreaking:3
      - mending:1
      - respiration:3
      - aqua_affinity:1
      - soul_speed:3
      - curse_of_binding:1
      - curse_of_vanishing:1
      - thorns:3
    specific_properties:
      armor:
        slot: FEET
        custom_armor: ecgoldenwrightarmor
  ecjadeemperorchest:
    display_name: '&#119577ɢ&#0DB07Bʀ&#09CA80ɪ&#04E584ᴍ&#00FF88ʙ&#09FD69ᴏ&#13FB49ɴ&#1CF92Aᴇ&#25F70As &#2DDF0Cᴊ&#36C80Dᴀ&#3EB00Fᴅ&#469810ᴇ Chestplate' #Put the name of your armor here
    resource:
      generate: true
      textures:
      - item/ec_elitearmorsvol25/ecjadeemperorchest.png
    durability:
      max_custom_durability: 1800
    specific_properties:
      armor:
        slot: chest
        custom_armor: ecjadeemperorarmor
    attribute_modifiers:
      chest:
        armor: 8
        armorToughness: 3
        knockbackResistance: 0.1
    enchants:
      - protection:4
      - fire_protection:4
      - blast_protection:4
      - projectile_protection:4
      - thorns:3
      - unbreaking:3
      - mending:1
      - respiration:3
      - aqua_affinity:1
      - soul_speed:3
      - curse_of_binding:1
      - curse_of_vanishing:1
      - thorns:3
    lore:
      - ''
      - '          &#FF0000&l✶ &#119577ᴊ&#00FF88ᴀ&#25F70Aᴅ&#469810ᴇ &#FF0000&l✶'
      - '&#FFFF70&l✶ &#469810ɢʀɪᴍʙᴏɴᴇ ʜᴀs ғᴀʟʟᴇɴ &#FFFF70&l✶'
      - ''
  ecjadeemperorhelmet:
    display_name: '&#119577ɢ&#0DB07Bʀ&#09CA80ɪ&#04E584ᴍ&#00FF88ʙ&#09FD69ᴏ&#13FB49ɴ&#1CF92Aᴇ&#25F70As &#2DDF0Cᴊ&#36C80Dᴀ&#3EB00Fᴅ&#469810ᴇ Helmet' #Put the name of your armor here
    resource:
      generate: true
      textures:
      - item/ec_elitearmorsvol25/ecjadeemperorhelmet.png
    durability:
      max_custom_durability: 1800
    specific_properties:
      armor:
        slot: head
        custom_armor: ecjadeemperorarmor
    attribute_modifiers:
      head:
        armor: 3
        armorToughness: 3
        knockbackResistance: 0.1
    enchants:
      - protection:4
      - fire_protection:4
      - blast_protection:4
      - projectile_protection:4
      - thorns:3
      - unbreaking:3
      - mending:1
      - respiration:3
      - aqua_affinity:1
      - soul_speed:3
      - curse_of_binding:1
      - curse_of_vanishing:1
      - thorns:3
    lore:
      - ''
      - '          &#FF0000&l✶ &#119577ᴊ&#00FF88ᴀ&#25F70Aᴅ&#469810ᴇ &#FF0000&l✶'
      - '&#FFFF70&l✶ &#469810ɢʀɪᴍʙᴏɴᴇ ʜᴀs ғᴀʟʟᴇɴ &#FFFF70&l✶'
      - ''
  ecjadeemperorlegs:
    display_name: '&#119577ɢ&#0DB07Bʀ&#09CA80ɪ&#04E584ᴍ&#00FF88ʙ&#09FD69ᴏ&#13FB49ɴ&#1CF92Aᴇ&#25F70As &#2DDF0Cᴊ&#36C80Dᴀ&#3EB00Fᴅ&#469810ᴇ Leggings' #Put the name of your armor here
    resource:
      generate: true
      textures:
      - item/ec_elitearmorsvol25/ecjadeemperorleggings.png
    attribute_modifiers:
      legs:
        armor: 6
        armorToughness: 3
        knockbackResistance: 0.1
    lore:
      - ''
      - '          &#FF0000&l✶ &#119577ᴊ&#00FF88ᴀ&#25F70Aᴅ&#469810ᴇ &#FF0000&l✶'
      - '&#FFFF70&l✶ &#469810ɢʀɪᴍʙᴏɴᴇ ʜᴀs ғᴀʟʟᴇɴ &#FFFF70&l✶'
      - ''
    durability:
      max_custom_durability: 1800
    enchants:
      - protection:4
      - fire_protection:4
      - blast_protection:4
      - projectile_protection:4
      - thorns:3
      - unbreaking:3
      - mending:1
      - respiration:3
      - aqua_affinity:1
      - soul_speed:3
      - curse_of_binding:1
      - curse_of_vanishing:1
      - thorns:3
    specific_properties:
      armor:
        slot: legs
        custom_armor: ecjadeemperorarmor
  ecjadeemperorboots:
    display_name: '&#119577ɢ&#0DB07Bʀ&#09CA80ɪ&#04E584ᴍ&#00FF88ʙ&#09FD69ᴏ&#13FB49ɴ&#1CF92Aᴇ&#25F70As &#2DDF0Cᴊ&#36C80Dᴀ&#3EB00Fᴅ&#469810ᴇ Boots' #Put the name of your armor here
    resource:
      generate: true
      textures:
      - item/ec_elitearmorsvol25/ecjadeemperorboots.png
    durability:
      max_custom_durability: 1800
    attribute_modifiers:
      feet:
        armor: 3
        armorToughness: 3
        knockbackResistance: 0.1
    lore:
      - ''
      - '          &#FF0000&l✶ &#119577ᴊ&#00FF88ᴀ&#25F70Aᴅ&#469810ᴇ &#FF0000&l✶'
      - '&#FFFF70&l✶ &#469810ɢʀɪᴍʙᴏɴᴇ ʜᴀs ғᴀʟʟᴇɴ &#FFFF70&l✶'
      - ''
    enchants:
      - protection:4
      - fire_protection:4
      - blast_protection:4
      - projectile_protection:4
      - thorns:3
      - unbreaking:3
      - mending:1
      - respiration:3
      - aqua_affinity:1
      - soul_speed:3
      - curse_of_binding:1
      - curse_of_vanishing:1
      - thorns:3
    specific_properties:
      armor:
        slot: FEET
        custom_armor: ecjadeemperorarmor
  ecstonesamuraichest:
    display_name: '&#FFD400&lᴏ&#FBD51C&lɢ&#F7D738&lʀ&#F3D853&lᴇ&#EFD96F&ls&#EADA8B&lᴛ&#E6DCA7&lᴏ&#E2DDC2&lɴ&#DEDEDE&lᴇ Chestplate' #Put the name of your armor here
    resource:
      generate: true
      textures:
      - item/ec_elitearmorsvol25/ecstonesamuraichest.png
    durability:
      max_custom_durability: 1800
    specific_properties:
      armor:
        slot: chest
        custom_armor: ecstonesamuraiarmor
    attribute_modifiers:
      chest:
        armor: 8
        armorToughness: 3
        knockbackResistance: 0.1
    enchants:
      - protection:4
      - unbreaking:3
      - mending:1
    lore:
      - ''
      - '       &#FF0000&l✶&#FF4B00 &#FFD400&lᴏ&#FBD51C&lɢ&#F7D738&lʀ&#F3D853&lᴇ&#EFD96F&ls&#EADA8B&lᴛ&#E6DCA7&lᴏ&#E2DDC2&lɴ&#DEDEDE&lᴇ &#FF0000&l✶'
      - '&#FFFF70&l✶ &#00FF00&#FFD400&lᴋ&#FCD511&lɪ&#FAD622&lɴ&#F7D633&lɢ &#F5D744&lᴏ&#F2D855&lғ &#F0D966&lᴛ&#EDD978&lʜ&#EBDA89&lᴇ &#E8DB9A&lᴏ&#E6DCAB&lɢ&#E3DCBC&lʀ&#E1DDCD&lᴇ&#DEDEDE&ls &#FFFF70&l✶'
      - ''
  ecstonesamuraihelmet:
    display_name: '&#FFD400&lᴏ&#FBD51C&lɢ&#F7D738&lʀ&#F3D853&lᴇ&#EFD96F&ls&#EADA8B&lᴛ&#E6DCA7&lᴏ&#E2DDC2&lɴ&#DEDEDE&lᴇ Helmet' #Put the name of your armor here
    resource:
      generate: true
      textures:
      - item/ec_elitearmorsvol25/ecstonesamuraihelmet.png
    durability:
      max_custom_durability: 1800
    specific_properties:
      armor:
        slot: head
        custom_armor: ecstonesamuraiarmor
    attribute_modifiers:
      head:
        armor: 3
        armorToughness: 3
        knockbackResistance: 0.1
    enchants:
      - protection:4
      - unbreaking:3
      - mending:1
    lore:
      - ''
      - '       &#FF0000&l✶&#FF4B00 &#FFD400&lᴏ&#FBD51C&lɢ&#F7D738&lʀ&#F3D853&lᴇ&#EFD96F&ls&#EADA8B&lᴛ&#E6DCA7&lᴏ&#E2DDC2&lɴ&#DEDEDE&lᴇ &#FF0000&l✶'
      - '&#FFFF70&l✶ &#00FF00&#FFD400&lᴋ&#FCD511&lɪ&#FAD622&lɴ&#F7D633&lɢ &#F5D744&lᴏ&#F2D855&lғ &#F0D966&lᴛ&#EDD978&lʜ&#EBDA89&lᴇ &#E8DB9A&lᴏ&#E6DCAB&lɢ&#E3DCBC&lʀ&#E1DDCD&lᴇ&#DEDEDE&ls &#FFFF70&l✶'
      - ''
  ecstonesamurailegs:
    display_name: '&#FFD400&lᴏ&#FBD51C&lɢ&#F7D738&lʀ&#F3D853&lᴇ&#EFD96F&ls&#EADA8B&lᴛ&#E6DCA7&lᴏ&#E2DDC2&lɴ&#DEDEDE&lᴇ Leggings' #Put the name of your armor here
    resource:
      generate: true
      textures:
      - item/ec_elitearmorsvol25/ecstonesamuraileggings.png
    attribute_modifiers:
      legs:
        armor: 6
        armorToughness: 3
        knockbackResistance: 0.1
    lore:
      - ''
      - '       &#FF0000&l✶&#FF4B00 &#FFD400&lᴏ&#FBD51C&lɢ&#F7D738&lʀ&#F3D853&lᴇ&#EFD96F&ls&#EADA8B&lᴛ&#E6DCA7&lᴏ&#E2DDC2&lɴ&#DEDEDE&lᴇ &#FF0000&l✶'
      - '&#FFFF70&l✶ &#00FF00&#FFD400&lᴋ&#FCD511&lɪ&#FAD622&lɴ&#F7D633&lɢ &#F5D744&lᴏ&#F2D855&lғ &#F0D966&lᴛ&#EDD978&lʜ&#EBDA89&lᴇ &#E8DB9A&lᴏ&#E6DCAB&lɢ&#E3DCBC&lʀ&#E1DDCD&lᴇ&#DEDEDE&ls &#FFFF70&l✶'
      - ''
    durability:
      max_custom_durability: 1800
    enchants:
      - protection:4
      - unbreaking:3
      - mending:1
    specific_properties:
      armor:
        slot: legs
        custom_armor: ecstonesamuraiarmor
  ecstonesamuraiboots:
    display_name: '&#FFD400&lᴏ&#FBD51C&lɢ&#F7D738&lʀ&#F3D853&lᴇ&#EFD96F&ls&#EADA8B&lᴛ&#E6DCA7&lᴏ&#E2DDC2&lɴ&#DEDEDE&lᴇ Boots' #Put the name of your armor here
    resource:
      generate: true
      textures:
      - item/ec_elitearmorsvol25/ecstonesamuraiboots.png
    durability:
      max_custom_durability: 1800
    attribute_modifiers:
      feet:
        armor: 3
        armorToughness: 3
        knockbackResistance: 0.1
    lore:
      - ''
      - '       &#FF0000&l✶&#FF4B00 &#FFD400&lᴏ&#FBD51C&lɢ&#F7D738&lʀ&#F3D853&lᴇ&#EFD96F&ls&#EADA8B&lᴛ&#E6DCA7&lᴏ&#E2DDC2&lɴ&#DEDEDE&lᴇ &#FF0000&l✶'
      - '&#FFFF70&l✶ &#00FF00&#FFD400&lᴋ&#FCD511&lɪ&#FAD622&lɴ&#F7D633&lɢ &#F5D744&lᴏ&#F2D855&lғ &#F0D966&lᴛ&#EDD978&lʜ&#EBDA89&lᴇ &#E8DB9A&lᴏ&#E6DCAB&lɢ&#E3DCBC&lʀ&#E1DDCD&lᴇ&#DEDEDE&ls &#FFFF70&l✶'
      - ''
    enchants:
      - protection:4
      - unbreaking:3
      - mending:1
    specific_properties:
      armor:
        slot: FEET
        custom_armor: ecstonesamuraiarmor

### Screenshots/Videos (you can drag and drop files or paste links)

tons in the forums post i made

**Comment by LoneDev6** [comment]
Please use the minimessage new way of setting item names.
It was changed some updates ago.
<https://itemsadder.devs.beer/plugin-usage/hex-colored-texts-1.16+>
