### ISSUE TITLE
Name/Lore colour formatting not meshing

### ISSUE THREAD

**Issue by GrimPod** [PluginBugs/Issues-ItemsAdder#3563]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

grimpod

### What happened?

Custom item name and lore werent loading colours and just posting them into the name, 
We eventually found the problem to be the use of both vanilla versions of colours (eg &2), and minimessage colours (eg <color:#57ff5c>)
just using one or the other worked fine, took us a while to figure that out, as theres mentions to both type of colours on the websites examples, but nothing mentioning that they dont work together

### Steps to reproduce the issue

make custom item
set the name/lore to &e testing <color:#57ff5c> testing </color>

### Server version

This server is running Paper version git-Paper-462 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 00fd87a)
You are 23 version(s) behind
Download the new version at: https://papermc.io/downloads/paper

### ItemsAdder Version

3.6.3-beta-13

### ProtocolLib Version

5.2.0

### LoneLibs Version

1.0.45

**Comment by LoneDev6** [comment]
You can't mix them, it's a limitation of Minimessage.
Please use Minimessage editor for easier editing.
https://itemsadder.devs.beer/plugin-usage/hex-colored-texts-1.16+
