### ISSUE TITLE
Armor custom texture is visible only with optifine or modded client

### ISSUE THREAD

**Issue by PSYCHEER** [PluginBugs/Issues-ItemsAdder#3565]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

PSYCHEER

### What happened?

I have one server, on which armor textures works somehow... but last days after restart they suddenly stopped working on vanilla and custom armors are visible trough optifine or modded client with CIT etc... what can be an issue? Bcz on Discord @fasemeow doesnt help and is rude af...

### Steps to reproduce the issue

Idk, just somehow

### Server version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/42911029/01237455-3a99-421c-bf52-72d857ea54f0)

### ItemsAdder Version

3.6.3-beta-13

### ProtocolLib Version

5.2.0 - 679

### LoneLibs Version

1.0.46

### FULL server log

[3ulnNHJ.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/15044164/3ulnNHJ.log)

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: spiritarmor
armors_rendering:
  spiritarmor:
    color: '#234ef7'
    layer_1: armor/spiritarmor_layer_1
    layer_2: armor/spiritarmor_layer_2
    use_color: false
items:
  spirit_chestplate:
    display_name: spirit Chestplate
    permission: simple
    lore:
    - spirit Chestplate
    resource:
      generate: true
      textures:
      - armor/spirit_chestplate
    specific_properties:
      armor:
        slot: chest
        custom_armor: spiritarmor
  spirit_leggings:
    display_name: spirit Leggings
    permission: simple
    lore:
    - spirit Leggings
    resource:
      generate: true
      textures:
      - armor/spirit_leggings
    specific_properties:
      armor:
        slot: legs
        custom_armor: spiritarmor
  spirit_boots:
    display_name: spirit Boots
    permission: simple
    lore:
    - spirit Boots
    resource:
      generate: true
      textures:
      - armor/spirit_boots
    specific_properties:
      armor:
        slot: feet
        custom_armor: spiritarmor
  spirit_helmet:
    display_name: spirit Helmet
    permission: simple
    lore:
    - spirit Helmet
    resource:
      generate: true
      textures:
      - armor/spirit_helmet
    specific_properties:
      armor:
        slot: head
        custom_armor: spiritarmor
```

### Screenshots/Videos (you can drag and drop files or paste links)

![2024-04-19_18 45 47](https://github.com/PluginBugs/Issues-ItemsAdder/assets/42911029/d440184f-f533-4364-b999-e5196aac5ba0)
![2024-04-19_18 45 50](https://github.com/PluginBugs/Issues-ItemsAdder/assets/42911029/0ac2ac9d-7e79-470c-99b4-cfe24db3d992)

**Comment by LoneDev6** [comment]
> but last days after restart they suddenly stopped working on vanilla

Stuff doesn't break randomly (luckly).
Something changed, for example:
- client version
- server version
- server build
- resourcepack contents
- installed some itemsadder addons and regenerated the pack
- installed shaders
- installed another plugin which interferes
etc..

No idea who is fasemeow, it's not part of the support team.
Anyway what you can do is:
- check if you have any shaders files in your itemsadder contents folders which might be added by another itemsadder addon (unofficial ones)
- check if the armors actually have the color set by using /iatag while holding the armor piece, check the output NBT to see if it contains any armor color tag
- regenerate the pack and follow the hosting tutorial based on which method you decided when you installed itemsadder
- get the armor again using the plugin command /iaget and check if they can be seen

I can't do much more to help you other than giving you these advises.

Some useful links:
https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown
https://itemsadder.devs.beer/plugin-usage/adding-content/armors/custom-textured-armor

**Comment by PSYCHEER** [comment]
Lone, problem is, it's not my server, I tried everything :D But via /ia it works, problem had old armors which are like 2-3 months old, I've asked what changed etc....Only armors from ExcelentCrates works so.. idk... close it 💜
