### ISSUE TITLE
Text color format issue

### ISSUE THREAD

**Issue by SwartZCoding** [PluginBugs/Issues-ItemsAdder#3566]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

On 1.20.4 with version 3.6.3-beta-13 of itemsadder this type of color formatting didn't work anymore ...

https://cdn.discordapp.com/attachments/875877231585525761/1231159026985861182/image.png?ex=6635f131&is=66237c31&hm=6a96fbebb7d6b203ddce189ea721b4fd8322c29b96345c3a1d17f14906ae3471&

### Steps to reproduce the issue

1. Create an item with this format color message on title or description
2. try it

### Server version

Current: git-Purpur-2172 (MC: 1.20.4)*
* You are running the latest version

### ItemsAdder Version

3.6.3-beta-13

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

### Problematic items yml configuration file (optional)

```shell
an item test to try the color : 

  guardian_boots:
    display_name: '%#8427d0%✸ %#8225ce%B%#8022cc%o%#7e20ca%t%#7c1ec8%t%#7a1bc6%e%#7819c4%s %#7617c2%d%#7414bf%u %#7212bd%G%#7010bb%a%#6e0db9%r%#6c0bb7%d%#6a09b5%i%#6806b3%e%#6604b1%n'
    lore:
      - ""
    resource:
      material: PAPER
      generate: true
      textures:
        - loots/guardian_boots.png
```

**Comment by LoneDev6** [comment]
https://itemsadder.devs.beer/plugin-usage/hex-colored-texts-1.16+
