### ISSUE TITLE
Death Maps Delete On Drop

### ISSUE THREAD

**Issue by TylorTurner** [PluginBugs/Issues-ItemsAdder#3567]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

tylorturner

### Describe the solution you'd like

Death maps do not delete when dropped, filling every location with tons of maps. 

a solution could make the maps automatically when they are dropped.

### Is your feature request related to a problem?

Maps EVERYWHERE

### Describe alternatives you've considered

Papermc Config to delete filled_map every 3 ticks. (Don't want to lose other filled maps though)

**Comment by LoneDev6** [comment]
Disable death maps in config.yml of itemsadder.
