### ISSUE TITLE
conflict with shader files

### ISSUE THREAD

**Issue by SrMonsterYT** [PluginBugs/Issues-ItemsAdder#3579]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

mauriciooficial

### What happened?

I'm trying to use shader effects on models but it seems that there's a conflict and it doesn't work see

itemsadder: https://youtu.be/J0kUdi86P9s

no itemsadder: https://youtu.be/CzCKaCHQwjY

files shaders: https://www.mediafire.com/file/we46nwv7zg5vfnd/shaders.rar/file

### Steps to reproduce the issue

place shader files inside itemsadder

### Server version

git-Pufferfish-46 (MC: 1.20.4)

### ItemsAdder Version

ItemsAdder_3.6.3-beta-14

### ProtocolLib Version

5.2.0-SNAPSHOT-683

### LoneLibs Version

1.0.46

### Full server log

no error

**Comment by LoneDev6** [comment]
Optifine shaders bug, I can't fix this.
It's a known issue.
