### ISSUE TITLE
Attributes don't work

### ISSUE THREAD

**Issue by SucoBR** [PluginBugs/Issues-ItemsAdder#3581]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

cara_suspeito

### What happened?

The attributes don't work at all, I put them in /iareload or /iazip and again /iareload and nothing, the rest works as custom durability but the attributes don't work at all
![Captura de tela 2024-04-25 082538](https://github.com/PluginBugs/Issues-ItemsAdder/assets/168089657/c1e4e767-c37c-4172-aaaa-cf41cf2a5a7b)
![2024-04-25_07 31 54](https://github.com/PluginBugs/Issues-ItemsAdder/assets/168089657/222377c2-5546-4fbc-a512-d0fb1bb94c2e)

### Steps to reproduce the issue

just put the custom attributes in the armor configuration

### Server version

![2024-04-25_08 26 30](https://github.com/PluginBugs/Issues-ItemsAdder/assets/168089657/f2ec6f30-bc2f-404a-9e91-6815544c6129)

### ItemsAdder Version

![2024-04-25_08 28 04](https://github.com/PluginBugs/Issues-ItemsAdder/assets/168089657/c8db4747-f68d-45bf-a7a9-06ed97d18714)

### ProtocolLib Version

![2024-04-25_08 28 34](https://github.com/PluginBugs/Issues-ItemsAdder/assets/168089657/14367bfb-a08e-4e7f-9a32-c3a4b2a1f4ba)

### LoneLibs Version

![2024-04-25_08 28 51](https://github.com/PluginBugs/Issues-ItemsAdder/assets/168089657/abeb31ba-0cac-46ad-ab21-a6c12d0afd31)

### Full server log

[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/15109131/latest.log)

**Comment by PSYCHEER** [comment]
Please update all updates, on discord u've said u use use spigot, not craftbukkit...
If the issue persist after update and changing server into spigot/paper and official forks of these, then maybe we find the issue 😇
