### ISSUE TITLE
1.20.3 - Use UUID for resourcepack apply

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#3585]
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Player.html#setResourcePack(java.util.UUID,java.lang.String,byte%5B%5D,java.lang.String,boolean)

> The player's client will download the new resource pack asynchronously in the background, and will automatically switch to it once the download is complete. If the client has downloaded and cached a resource pack with the same hash in the past it will not download but directly apply the cached pack. If the hash is null and the client has downloaded and cached the same resource pack in the past, it will perform a file size check against the response content to determine if the resource pack has changed and needs to be downloaded again. When this request is sent for the very first time from a given server, the client will first display a confirmation GUI to the player before proceeding with the download.

I need to do some tests to see exactly how this whole thing works and get rid of most legacy resourcepack hash tricks (URL hash) and similar in favor of a most modern and stable code.

**Comment by Andre601** [comment]
Not sure how important this may be to know, but from what I understand is the client now assigning a unique ID to each server with a resource pack, which seems to be used in the new `downloads` folder (replacement of the server resource pack one) as the folder name where it would then have the resource packs stored.
That change was made to allow multiple server resource packs to be loaded for a server...

I don't know any more details here tho.
