### ISSUE TITLE
How to make ItemsAdder text effects work in ChatControl Red

### ISSUE THREAD

**Issue by HielkeMaps** [PluginBugs/Issues-ItemsAdder#3586]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Normally the ItemsAdder text effects don't work with ChatControl Red.
But if you add this to your `rules` folder of ChatControl Red, they will work. (I put this in `global.rs`)

```
match <r\s([^>]+)>
require perm ia.user.text_effect.use.r
strip colors false
then replace #FFFFFE$1&r
    
match <w\s([^>]+)>
require perm ia.user.text_effect.use.w
strip colors false
then replace #FFFFFD$1&r
    
match <j\s([^>]+)>
require perm ia.user.text_effect.use.j
strip colors false
then replace #FFFFFB$1&r
    
match <rw\s([^>]+)>
require perm ia.user.text_effect.use.rw
strip colors false
then replace #FFFFFC$1&r
    
match <rj\s([^>]+)>
require perm ia.user.text_effect.use.rj
strip colors false
then replace #FFFEFE$1&r
```

Hope this helps others 😄
Maybe this can get added under compatibility in the wiki?

### Is your feature request related to a problem?

ItemsAdder Text Effects normally don't work with ChatControl Red.

### Describe alternatives you've considered

.

**Comment by LoneDev6** [comment]
thanks so much, added to the wiki in the chatcontrol page
