### ISSUE TITLE
[API] TexturedInventoryWrapper mistake?

### ISSUE THREAD

**Issue by Asleeepp** [PluginBugs/Issues-ItemsAdder#3589]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

asleepp

### What happened?

For some reason, TexturedInventoryWrapper#getInternal() is deprecated, however this seems to be the **only** way to get the bukkit inventory of the custom inventory, and thus set slots inside the inventory. (why would you make an inventory for nothing to be inside it?). So im leading to believe that this was a mistake.

### Steps to reproduce the issue

check the api?

### Server version

n/a

### ItemsAdder Version

n/a

### ProtocolLib Version

n/a

### LoneLibs Version

n/a

**Comment by Andre601** [comment]
The deprecation may be related to the warning given in the javadoc, that the inventory may not be displayed/rendered correctly if the `use_custom_font_file` config option is enabled. And this is a way for LoneDev to discourage using the method.

Tho, this is an assumption on my end here and LoneDev may have another reason for why the method is deprecated.

**Comment by Asleeepp** [comment]
> The deprecation may be related to the warning given in the javadoc, that the inventory may not be displayed/rendered correctly if the `use_custom_font_file` config option is enabled. And this is a way for LoneDev to discourage using the method.
> 
> Tho, this is an assumption on my end here and LoneDev may have another reason for why the method is deprecated.

I feel like this should just be a note added onto the method itself, and not a reason for deprecation.

**Comment by Andre601** [comment]
A main issue every API dev faces is the fact that not every user will read the javadocs (I can speak from personal experience) and there is little to no options available within Java itself to tell a user about possible issues.
By having a deprecation annotation, a user sees a warning in their IDE and may inspect the method further to then see the docs. It's not the best option, but it gets the attention of the user (Just like it did in your case 😉).

Tho, again, this is me assuming that this was LoneDev's motivation behind this. There could be other reasons.
