### ISSUE TITLE
_iainternal resourcepack folder won't stop regenerating

### ISSUE THREAD

**Issue by enesop** [PluginBugs/Issues-ItemsAdder#3590]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

The _iainternal folder, inside of `_iainternal/resourcepack/assets` will not stop regenerating as well as the pack.mcmeta inside of `_iainternal/resourcepack`.

I have renamed the namespace of all configs inside of _iainternal to for example `test` then I rename the _iainternal folder inside of assets to `test`, I also rename everything inside of other main configs such as ia_gui.yml to `test:item` yet the _iainternal folder inside of the resourcepack keeps regenerating. This also happens with pack.mcmeta.

Fix:
Don't require the _iainternal pack to re-generate if it is not being using by any of the MAIN configs such as ia_gui.yml
Don't regenerate pack.mcmeta if it is deleted

### Steps to reproduce the issue

Rename everything that uses _iainternal to a different namespace including the resourcepack namespace. You do not need to rename `contents/_iainternal` THAT is not the issue. After doing /iazip the _iainternal folder will appear back in the resourcepack.

### ItemsAdder Version

3.6.3-beta-14

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

### Screenshots/Videos (you can drag and drop files or paste links)

DONT RENAME
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/60015283/852c8f49-703b-48ac-a8ec-e24050f02142)

RENAME
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/60015283/1befe4d1-8818-4a08-b282-6b582d73668d)

**Comment by Andre601** [comment]
Go to the config.yml and navigate to `resource-pack.zip.extract_internal_utility_assets` and change it from `true` to `false`.
This should stop ItemsAdder from regenerating the folder by not extracting it anymore from its internal files.

However, doing so can mess things up if you decide to delete stuff, as `_iainternal` content is used by ItemsAdder for the custom GUI elements (background, icons, etc) amongst other things.
So keep that in mind.
