### ISSUE TITLE
black armor

### ISSUE THREAD

**Issue by SrMonsterYT** [PluginBugs/Issues-ItemsAdder#3599]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

mauriciooficial

### What happened?

when i updated to the latest version the armor of the leather skinned players turned black, and this message also appears on the console:

armor black: https://prnt.sc/gNh9lo37nEPp
console: https://prnt.sc/1pKevWop7OZH

is itemadder creating giant leather armor textures?

### Steps to reproduce the issue

have several leather armors with skin and use /iazip

### Server version

version git-Pufferfish-49

### ItemsAdder Version

ItemsAdder_3.6.3-beta-14.jar

### ProtocolLib Version

ProtocolLib 5.2.0

### LoneLibs Version

LoneLibs 1.0.45

**Comment by Andre601** [comment]
This seems to be related to #3583

Also, please provide a **valid** server version and your server logs. `git-pufferfish-49` doesn't tell us about the actual server version used.

**Comment by SrMonsterYT** [comment]
> This seems to be related to #3583
> 
> Also, please provide a **valid** server version and your server logs. `git-pufferfish-49` doesn't tell us about the actual server version used.

git-Pufferfish-49 (MC: 1.20.4)
