### ISSUE TITLE
1.20.6 - use the new `minecraft:tool` attribute to add the custom breaking speed logic

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#3609]
https://www.minecraft.net/ja-jp/article/minecraft-snapshot-24w12a
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/ffe52ef0-1ac9-479a-9b80-a429b1a36c10)

Note:
I think that this should be updated each time a player starts breaking a block, or better when any inventory is opened, otherwise items might not stack correctly due to the fact that the NBT might change in future settings updates, I think.
Related to: #2247

**Comment by Andre601** [comment]
Another thing to consider would be the new generic attribute to set a player's own mining speed. This in combination with the tool one could be useful for a more fine-tuned mining speed aproach.

**Comment by LoneDev6** [comment]
I think I could just code my own logic by using the player mining speed attribute and do not touch NBT of the item

**Comment by LoneDev6** [comment]
I could just implement this feature instead: https://github.com/PluginBugs/Issues-ItemsAdder/issues/3161
