### ISSUE TITLE
[furniture] No drop when breaking furniture with Silk touch

### ISSUE THREAD

**Issue by NoHere32** [PluginBugs/Issues-ItemsAdder#3612]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

.nohere

### What happened?

As the name suggests, when you break a piece of furniture with a tool that has the vanilla Silk Touch enchantment, it does not drop the furniture.

### Steps to reproduce the issue

- Take a piece of furniture
- Installing furniture
- Enchanting a tool with Silk Touch
- Break a piece of furniture
- realize it doesn't drop

### Server version

This server is running Pufferfish version git-Pufferfish-47 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 9d12215 on HEAD)

### ItemsAdder Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/123643370/322ec381-2d52-4d35-9f0f-bc3b758b8477)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/123643370/37ac56e5-e18f-44f8-aefe-c7090d49bf51)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/123643370/8a497f9a-f2c8-4acf-9302-c136f50d3cdf)

### Full server log

No log

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/SUOLZfnByiU

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/ddbd0d49-d68a-4eac-9fbf-b05b8a89e1d0
