### ISSUE TITLE
help

### ISSUE THREAD

**Issue by yAtomic** [PluginBugs/Issues-ItemsAdder#3614]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

uatomic_

### What happened?

error for join

### Steps to reproduce the issue

join in server

### Server version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/77587831/103aeda0-6501-4939-9d79-2c41f26131b1)

### ItemsAdder Version

3.6.3-beta14

### ProtocolLib Version

5.2.1-snapshot-685

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/77587831/7740e986-e48c-4899-b5e4-5aec45cf36ca)

### Full server log

[latest (1).log](https://github.com/PluginBugs/Issues-ItemsAdder/files/15228391/latest.1.log)

**Comment by Andre601** [comment]
Could you share the full log through a paste site please?
Also, make sure you actually use Spigot or even better Paper.
The screenshot shows CraftBukkit which is a broken server.

**Comment by yAtomic** [comment]
https://mclo.gs/WubGpms

**Comment by yAtomic** [comment]
https://mclo.gs/ojBBcUp

**Comment by Andre601** [comment]
Okay, you seem to use CraftBukkit?
It's recommended to.use Paper instead. Could you try this please?

**Comment by LoneDev6** [comment]
Update to 1.20.4, there is no reason to stay on 1.20.1.
