### ISSUE TITLE
[Bug] Log file spam

### ISSUE THREAD

**Issue by elkoyofficial** [PluginBugs/Issues-ItemsAdder#3628]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

elkoy

### What happened?

This keeps spamming my log file
https://pastebin.com/m2bq0Q9C

Think it's itemsadder. Not sure what's causing it. Log file is currently at 50mb after 10 hours.

### Steps to reproduce the issue

Use IA?

### Server version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/63325580/c134228a-cff0-4f5d-8713-b1b509f06c13)

### ItemsAdder Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/63325580/443aa0e1-5632-40b0-9293-13eeb1f65b88)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/63325580/584d167e-1d0e-42a9-8201-39aaf67c352a)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/63325580/f8a676d3-e6e5-4eb1-8795-6ad7f0acab38)

### Full server log

https://pastebin.com/m2bq0Q9C - part of it but it's just the same spam over and over.

**Comment by Andre601** [comment]
The paste is invalid.
Should this issue no longer be the case, please close it.
Else, please provide an updated paste.

**Comment by elkoyofficial** [comment]
https://pastebin.com/pziLkwv7

**Comment by Andre601** [comment]
> https://pastebin.com/pziLkwv7

Also invalid.

Did you make sure the paste is public?
Maybe try another paste site.

**Comment by elkoyofficial** [comment]
Here is the spam:
[10:02:12] [Craft Scheduler Thread - 190 - ItemsAdder/DEBUG]: [org.apache.http.wire] http-outgoing-2 >> "WY[0xeb]th[0xcc]xk[0xcd][0xab][0xe3][0x99][0x14][0x8a][0x1d][0xd4]7\\lC[0x17][0xb3][0x8a][0xdd][0x81]x,[0x1d][0xc9][0x9a][0xe2]f[0x9a]Y[0xf3][0x18][0x17]9[0xe]#3[0xd5][0xd1]i[0xec].[0x97][0xaa][0x1c][0x95][0xa9][0xba]rr[0x10][0xfb][0x19][0x8e]Qm)[0x13][0xd0][0x95][0xee][0x0][0xca][0xa6][0x4]{[0x8f]b[0x93][0xc5][0x9f][0x0][0x8][0xce][0xbb][0xa5][0x1a]S[0x82]C[0xe9]3[0xdb][0xa8][0x98]jH9[0xa1] [0x18][0x12][0xf6][0xeb][0xb0]4*7<[0xb3][0x19]q[0x92][0x19][\r]([0xc1][0xe1][0x92][0xdd]X4[0xa0][0x14][0xbc][0x8a][0x9c][0x8b]Ek:[0xa7][0x10][0x9a][0xb8]u[0xbe][0x10][0x98][0xc2][0x1b]s[0x1a][0xa9][0x9c][0x89][0x93]R[0xec]X"[0xa5][0xfd]WTSR[0xa9]}Vl[0x19][0xe8][0xd4]\[0xa5]:[0xbe][0xb6]U[0xa4][0xa9][0xc4]BCGT^[0xb9]Z[0xc2][0x91]w[0x90].[0xa8]Wd[0xda][0xd7][0xd6]0[0xa9]*[0xa5]kcCf[0xe7][0xbd]q[0x17]#[0xb][0x97][0xe][0xe][0xd9][0x1b]-c[0xfb][0xc3][0x1b][0xb1]x[0xb1][0x86][0xbd][0xf]5[0xdd][0xfb][0x18]Z[0x96][0xcc][0x17][0x8e][0x8a]b[[0x98][0xe][0x86][0xc1][0x9e]z[0xb1][0xe6][0x93][0xd5]pB[0x12][0xce][0x97][0xf3][0xc1]Q[0x1a][0xbe]X[0x1]/[0xe2]r[0xa1][0xbf][0x86][0xf7][0xdb][0x93][0xb8]@[0xb5][0xe0]V[0xdb]K=[0xe1][0x10]W[0xb8]BR[0xbe][0x84]+[0x16])[0xc4][0xde][0x82]l[0x1b][0xa0][0x8a]fd[0xb9][0xab][0xa9].[0xb8][\r]m}[0x9d][0xa2][0xdc][0x87][0xa2][0x1]3N[0xbb]lH[0xa3][0x8b][0xc4]Ri[0x94][0x93]@[0xf0]YJ9[0xd1]%[0x16][0xe5]9[0x9][0x84]=[0xc9][0x3][0xe8]Y`[0xbe][0xd2][0x83][0xfc][0x85][0xa3][0x16][0x9e][0xb4],T[0xb7][0xb8][0x9f][0xfe][0x82]<Pdf[0xa4]N]PNu[0x89][0xb9][0xab]W[0xe]_[\n]"

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/63325580/b7550b6b-fe1e-4c53-b6f4-933b86ef3f5e)
Over 18000 lines of it

**Comment by Andre601** [comment]
This seems to be a debug line (See the `DEBUG` text) from ItemsAdder, so you must have enabled Debug level logging in your server or ItemsAdder (It seems more to be the first).

**Comment by elkoyofficial** [comment]
Hi, debug is set to false in my server.properties.

Also, my config for IA.
debug:
  benchmark: false
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
    log-armors-loading: false
    log-files-reloading: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
    log-recipes-removed-vanilla: false
    log-recipes-unknown-item: false
    log-fix-packet-too-large: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save-load:
      enabled: false
      min-ms: 0
    log-mined-unknown-blocks: true
    log-convert-vanilla-blocks: false
    log-fix-bugged-blocks: false
    log-unusual-block-break: false
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-loading-no-world: true
    log-generation: false
  surface-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  cave-decorators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-decorators: false
    log-loading-no-world: true
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
    log-icon-failed-load: false
  entities:
    log-files-loading: false
    log-entities-loading: false
    log-entities-loading-disabled: false
  issues:
    log_font_image_replace_json_syntax_exception: true

**Comment by Andre601** [comment]
Please share the file through a paste to preserve indents.

And debug must be enabled by your server. The debug log wouldn't show otherwise.

**Comment by elkoyofficial** [comment]
https://pastebin.com/QZzV2AEq

Where can I find other debug options?

**Comment by Andre601** [comment]
The only other way I can think of is setting it in the startup command itself, or through environment variabls (I'm unsure about that one).

**Comment by elkoyofficial** [comment]
Nothing there for it.. makes no sense lol.
