### ISSUE TITLE
Moving to packetevents or to own alternative

### ISSUE THREAD

**Issue by DxrkCat** [PluginBugs/Issues-ItemsAdder#3644]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

ProtocolLib is not stable now and it is not known when it will be stable, many developers went to packet-events because of the convenience and this puts a lot of pressure on ProtocolLib as it will be less supported by developers because it is not needed. If you haven't switched to packet-events yet, could you do so? Or could you do something of your own?

### Is your feature request related to a problem?

return;

### Describe alternatives you've considered

return;

**Comment by LoneDev6** [comment]
Yea I've been thinking about switching or making my own implementation.
Anyway ProtocolLib latest version works fine on ItemsAdder upcoming 4.0 update.

**Comment by NoltoxGit** [comment]
Hello,
Any news about this implementation ?
