### ISSUE TITLE
some player can't open emoji menu.

### ISSUE THREAD

**Issue by Ecilpse** [PluginBugs/Issues-ItemsAdder#3645]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Eclipse

### What happened?

i don't know why, some player can't open emoji menu.
only given emoji book packet items.
In this case, player hold the item and command /emoji again to open gui

### Steps to reproduce the issue

i can't reproduce with my account&subaccount. idk why this problems happend
 but i have video that some player reproduced.

### ItemsAdder Version

3.6.3-beta-14

### ProtocolLib Version

5.1.1-SNAPSHOT-673

### LoneLibs Version

1.0.46

### Screenshots/Videos (you can drag and drop files or paste links)

https://youtu.be/FVRzJB0D-yI

**Comment by Andre601** [comment]
Your ProtocolLib version is quite outdated. Please update it and see if that fixes the issue.

If not, then check if the issue persists with just the vanilla client, given that a modded client was obviously used here.

**Comment by Ecilpse** [comment]
> Your ProtocolLib version is quite outdated. Please update it and see if that fixes the issue.
> 
> If not, then check if the issue persists with just the vanilla client, given that a modded client was obviously used here.

i updated lastest version of protocollib which version of 5.2.0, but still same
