### ISSUE TITLE
Skulls turn white

### ISSUE THREAD

**Issue by BurningCoolDude** [PluginBugs/Issues-ItemsAdder#3646]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

burnplayz

### What happened?

Skulls are changing to white then back based on how I move head / move around.
https://medal.tv/games/minecraft/clips/2e4EXICKBe5hL2/d1337oNR28M7?invite=cr-MSxpT2UsODYwMzk3MDEs

### Steps to reproduce the issue

Place skull with ItemsAdder installed. I tried without ItemsAdder and it doesn't do this.

### Server version

This server is running Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)
You are running the latest version

### ItemsAdder Version

3.6.3-beta-14

### ProtocolLib Version

5.2.1-SNAPSHOT-686

### LoneLibs Version

1.0.45

### Problematic items yml configuration file (optional)

```shell
Here's my config file.
https://pastebin.com/shj6fZ8M
```

**Comment by Andre601** [comment]
This is an unfixable issue for using the ItemsAdder Emotes system, as it uses core shader manipulation that affects placed player heads close to each other.
The only fix is to disable the emote system and regenerate the texture pack.

This was taken from the wiki: https://itemsadder.devs.beer/faq/placed-heads-texture-glitched
