### ISSUE TITLE
Add support for all the new attribute modifiers added in 1.20.6 in itemsadder 4.0.0!

### ISSUE THREAD

**Issue by HaydoPotato1310** [PluginBugs/Issues-ItemsAdder#3651]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Haydopotato1310

### Describe the solution you'd like

1.20.6 added a bunch of new attributes which I want to use for custom items on my server. Can you please add support for them in the upcoming 4.0.0 itemsadder update????
It would be much appreciated 

### Is your feature request related to a problem?

I haven’t seen anything about it in the update changelog or feature requests so far

### Describe alternatives you've considered

I can’t use modifiers on any other plugin

**Comment by Andre601** [comment]
There already are issues for 1.20.6 features and compat, so this issue has no real use.

**Comment by HaydoPotato1310** [comment]
Ok good
I was just making sure those features would be included :)
