### ISSUE TITLE
İtemsadder Durability Problem

### ISSUE THREAD

**Issue by ArdayraL** [PluginBugs/Issues-ItemsAdder#3661]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

ardayral.

### What happened?

When durability decreases from an item, a new lore is added to the durability lore. Therefore, players cannot change the location of these items.
What could be the solution?

### Steps to reproduce the issue

every time durability decreases

### Server version

git-Pufferfish-49 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 852ea89 on HEAD)

### ItemsAdder Version

3.6.4

### ProtocolLib Version

 5.2.0

### LoneLibs Version

1.0.54

### Full server log

dont need

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/170813036/72d8a4d8-854e-40c2-bec3-f7dd52fdb0cd)

**Comment by ArdayraL** [comment]
can anyone help

**Comment by Andre601** [comment]
> ### Full server log
> 
> dont need

Your server log is actually needed as it gives us important information to debug this problem, so please provide it, preferably through a paste site such as https://mclo.gs

**Comment by ArdayraL** [comment]
https://mclo.gs/XrCdWYp

**Comment by Andre601** [comment]
You are using leaked/stolen plugins. Please actually buy the plugins to support the devs and don't just steal from their hard work.
