### ISSUE TITLE
Event onCommand

### ISSUE THREAD

**Issue by PSYCHEER** [PluginBugs/Issues-ItemsAdder#3666]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

PSYCHEER

### Describe the solution you'd like

Something like
`events:
  on_command: "/heal"
    increment_player_stat: thirst
      amount: 20`
This will make whenever player does /heal thirst will be fullfilled

### Is your feature request related to a problem?

Nope

### Describe alternatives you've considered

Ehm...Idk, deluxemenus?

**Comment by LoneDev6** [comment]
Actually it already detects hunger changes, so /heal should already work as intended.
Test with the itemsadder thirst example bar.
