### ISSUE TITLE
attribute_modifiers option not working

### ISSUE THREAD

**Issue by BackdevHong** [PluginBugs/Issues-ItemsAdder#3673]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

developerhong

### What happened?

I added the attribute_modifiers option to the helmet, and when I went into the server and checked, I saw that all other attributes were not attached and that the armor attribute was set to 1.

### Steps to reproduce the issue

This is an attribute that the original leather helmet had, so attribute_modifiers will not work.

### Server version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/97325091/9cb18526-c9f6-4548-9d45-db629eeee38b)

### ItemsAdder Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/97325091/ab85b16a-500f-40b0-9c30-fc8873954306)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/97325091/88b91281-f211-40ea-806d-342e463743d1)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/97325091/23b75121-285a-41a7-a3aa-41e264547389)

### Full server log

https://mclo.gs/VWLGAMO

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: customarmor

armors_rendering:
  spy_armor:
    color: '#d60001'
    layer_1: armor/spy_armor/layer_1
    layer_2: armor/spy_armor/layer_2
    use_color: false

items:
  spy_helmet:
    display_name: '&c&l???'s helmet'
    attribute_modifiers:
      head:
        armor: 3
        armorToughness: 3
    resource:
      generate: true
      textures:
      - items/spy/helmet
    durability:
      max_custom_durability: 407
    specific_properties:
      armor:
        slot: head
        custom_armor: spy_armor
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/97325091/ae6c4d7a-ad99-46ba-ba17-0dd31bdf2eee)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/97325091/c2aaa4d2-a28d-4364-a2d6-b8ec5ed82ed9)

**Comment by Andre601** [comment]
You use a hybrid server.
ItemsAdder only supports spigot/paper servers without mod support.
