### ISSUE TITLE
cannot read field "a" beacuse "<local3> is null

### ISSUE THREAD

**Issue by jeongys1019** [PluginBugs/Issues-ItemsAdder#3676]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

sik1019

### What happened?

when on right click with item  get error

My guess is that the problem lies here.

meta _ internal 
i'm using skirpt and skirpt yaml , when i save this item 
[intenal] Here is the difference between the item with an error and the item that did not.

can i change this value ??

### Steps to reproduce the issue

1. on right click with cross bow 
2. error 

### Server version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/110158223/b1f5d169-c7b8-4079-997e-5ee134fab87c)

### ItemsAdder Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/110158223/44572f3f-d982-4f84-9d31-300c5f5fe3c9)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/110158223/fe29785b-e292-42ed-867b-4bb03b617153)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/110158223/103ad5f9-058e-411b-8198-53b043d31b6f)

### Other files, you can drag and drop them here to upload. (optional)

item:
    ==: org.bukkit.inventory.ItemStack
    v: 3700
    type: CROSSBOW
    meta:
        ==: ItemMeta
        meta-type: CROSSBOW
        internal: H4sIAAAAAAAA/+NiYOBg4MhJzEksqSxIZRBIKc1LT83Piy9PTSwAUoZcDFyZJam5xYkpKalFQKUsRYl52Qw8rxd0vFnQ8rp3yutla5gh+lOK8gsYgICVgbMkMze1uCQxt8Dv9NkXjAwcxdmZeSBTGBkAibZ6Em8AAAA=
        charged: false

**Comment by LoneDev6** [comment]
Please post the log and the error.
