### ISSUE TITLE
itemsadder resource error

### ISSUE THREAD

**Issue by dafsdfasde** [PluginBugs/Issues-ItemsAdder#3684]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

itemsadder resource error
If you watch the video, it looks like you can't unzip the image, but you can use it by dragging the selected image to the desktop.

Errors caused by BetterHud have been resolved.
The error no longer appears in the log.

### Steps to reproduce the issue

I will attach a video.

### Server version

This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version
Previous version: git-Purpur-2062 (MC: 1.20.1)

### ItemsAdder Version

[07:03:11 INFO]: ItemsAdder version 3.6.4-release-2
[07:03:11 INFO]: Customized Minecraft without client mods!
[07:03:11 INFO]: Website: devs.beer
[07:03:11 INFO]: Author: LoneDev

### ProtocolLib Version

[07:03:19 INFO]: ProtocolLib version 5.2.1-SNAPSHOT-689
[07:03:19 INFO]: Provides read/write access to the Minecraft protocol.
[07:03:19 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[07:03:25 INFO]: LoneLibs version 1.0.54
[07:03:25 INFO]: Collection of libs used by my plugins
[07:03:25 INFO]: Authors: LoneDev and others

### Full server log

No error log

### Problematic items yml configuration file (optional)

```shell
zip:
    protect-file-from-unzip:
      protection_1: true
      protection_2: true
    compress-png-files: true
    compress-json-files: true
    generate-custom-armors-textures:
      vanilla_1_17: true
      optifine: true
    disable-overwrite-leather-armor-layers-textures: false
    fix_transparent_noteblocks: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - psd
    - html
    - gz
    - rar
    - zip
    - 7z
    extract_internal_utility_assets: true
    contents-folders-priority:
    - vanilla
    - _iainternal
    merge_other_plugins_resourcepacks_folders:
    - ModelEngine/resource pack
    - BetterHud/build
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://github.com/PluginBugs/Issues-ItemsAdder/assets/170809526/336db904-7f24-4512-a0c3-1fd670d6440c

**Comment by LoneDev6** [comment]
I don't understand.
Might be related to protection, disable it in config.yml of ItemsAdder and run /iazip again.
https://itemsadder.devs.beer/plugin-usage/resourcepack-hosting/protect-resourcepack-from-unzip

**Comment by dafsdfasde** [comment]
@LoneDev6 Still, resources are not protected.

Servers other than me seem to have this phenomenon. You can also view other server files on Server-Resource-Packs.

**Comment by dafsdfasde** [comment]
@LoneDev6 I'll attach the exact video again. This is a very serious problem.
https://github.com/PluginBugs/Issues-ItemsAdder/assets/170809526/327a9f60-020d-48c5-b540-cbd8e98d7ca9

**Comment by Andre601** [comment]
Please don't tag LoneDev. He WILL see your messages and may reply to it (Not guaranteed).

Also, your upload failed it seems.

**Comment by dafsdfasde** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/assets/170809526/0957a91d-9376-41c9-afbf-3d3fc8a86f1d

**Comment by Andre601** [comment]
> 2024-06-07.22-39-13.mp4

And what is this meant to show us? If you have zip protection disabled can anyone extract the files no problem.
You do a poor job here in explaining the issue you have, so please take your time to describe it.

**Comment by dafsdfasde** [comment]
I didn't disable protection.

  zip:
    protect-file-from-unzip:
      protection_1: true
      protection_2: true
