### ISSUE TITLE
Licence in console

### ISSUE THREAD

**Issue by Mathildeuh** [PluginBugs/Issues-ItemsAdder#3687]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Mathildeuh

### What happened?

When starting i got variable instead of licence user name 

### Steps to reproduce the issue

Just start 1.20.6 server with itemsadder v4.0.0

[21:05:18 ERROR]: [ItemsAdder] [License] Unknown user ID: %%__USER__%%

And got that

### Server version

Purpur latest build (i'm on phone, i can't tell you now)

### ItemsAdder Version

4.0.0

### ProtocolLib Version

5.3.0

### LoneLibs Version

Latest

### Full server log

[21:05:18 ERROR]: [ItemsAdder] [License] Unknown user ID: %%__USER__%%

**Comment by Andre601** [comment]
This is a bug with the Spigot site. It doesn't support Java 21 Bytecode right now, so the placeholder isn't replaced when downloading the jar.

Since this doesn't affect the functionality of the plugin can you safely ignore this problem. I'll leave this issue open until Spigot fixes their stuff.

**Comment by LoneDev6** [comment]
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/86afa657-69f7-4a72-bed1-e7e0bc44fb26)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/f751737c-29d7-4882-8dd6-0a23a1a95090)
