### ISSUE TITLE
The Itemsadder's self-hosted resource pack does not download.

### ISSUE THREAD

**Issue by gclogs** [PluginBugs/Issues-ItemsAdder#3696]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

gosmos_

### What happened?

I am a person operating the 1.20.2 server.
We are currently using `beta-14` for the item editor version.

Some players have reported that the resource pack is not being applied.
We are using the `self-host` option and downloading the resource pack using `localhost`.

What could be the issue?

### Steps to reproduce the issue

1. Update the resourcepack
2. reload Itemsadder
3. run to /iazip 
4. download resourcepack
5. The Itemsadder's self-hosted resource pack does not download.

### Server version

This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
You are running the latest version

### ItemsAdder Version

ItemsAdder version 3.6.3-beta-14
Customized Minecraft without client mods!
Website: devs.beer
Author: LoneDev

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-673
Provides read/write access to the Minecraft protocol.
Authors: dmulloy2 and comphenix

### LoneLibs Version

 LoneLibs version 1.0.45
Collection of libs used by my plugins
Authors: LoneDev and others

### Full server log

The log does not appear separately.

### Error (optional)

```shell
The log does not appear separately.
```

### Problematic items yml configuration file (optional)

```shell
There are no issues with the file.
```

**Comment by Andre601** [comment]
Please share your latest.log through https://mclo.gs and your config.yml.

**Comment by LoneDev6** [comment]
This is the only way to identify why it's not loading: https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown

**Comment by gclogs** [comment]
Thank you. Currently there is no issue, but if it occurs again in the future, I will upload it with the config.yml and log attached.
