### ISSUE TITLE
JavaDocs no longer function

### ISSUE THREAD

**Issue by Asleeepp** [PluginBugs/Issues-ItemsAdder#3697]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

asleepp

### What happened?

trying to access the javadocs now gives a 404 error screen

### Steps to reproduce the issue

go to javadocs
be presented with a 404 error.

### Server version

N/A

### ItemsAdder Version

N/A

### ProtocolLib Version

N/A

### LoneLibs Version

N/A

### Full server log

N/A

### Error (optional)

```shell
N/A
```

### Problematic items yml configuration file (optional)

```shell
N/A
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/119438940/454dca69-5b4c-49f3-8a6a-16dc478ea8b6)

**Comment by Andre601** [comment]
Where did you try to access the Javadocs?

**Comment by Asleeepp** [comment]
> Where did you try to access the Javadocs?

the api-itemsadder repository

**Comment by Andre601** [comment]
https://lonedev6.github.io/API-ItemsAdder/

**Comment by Asleeepp** [comment]
hey, the link on the repo needs to be updated then.

**Comment by LoneDev6** [comment]
Thank you so much, I updated the url
