### ISSUE TITLE
Resource pack not loading

### ISSUE THREAD

**Issue by Matteus130** [PluginBugs/Issues-ItemsAdder#3700]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Monkee130

### What happened?

I am on server version 1.20.6 with the latest itemsadder version, and when someone joins, or if I join, the resource pack does not load. I have tried to regenerate the pack, run the ia zip, reload, then texture commands, but nothing happens. When I was using the external host, it said the URL was valid, but the /iatexture command did nothing. In the console it said applying the textures to the players, but it didnt. I switched to self host, and nothing still happens. When I use the resource pack locally (I uploaded it into my resource pack folder) the textures show up. So the plugin isnt loading the resource pack.

### Steps to reproduce the issue

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/69374279/f7372a27-6efe-4c82-b136-6fe6e8cb1e83)

### Server version

![Screenshot 2024-06-06 at 4 39 15 PM](https://github.com/PluginBugs/Issues-ItemsAdder/assets/69374279/e929749b-2850-439d-a250-14f9aa2b1ec4)

### ItemsAdder Version

![Screenshot 2024-06-06 at 4 39 30 PM](https://github.com/PluginBugs/Issues-ItemsAdder/assets/69374279/3a2046cf-8f68-4a13-9943-6ae06aff3a66)

### ProtocolLib Version

![Screenshot 2024-06-06 at 4 39 41 PM](https://github.com/PluginBugs/Issues-ItemsAdder/assets/69374279/2e2277f2-b310-4f4c-9398-5fdbb4cd4b7c)

### LoneLibs Version

![Screenshot 2024-06-06 at 4 39 52 PM](https://github.com/PluginBugs/Issues-ItemsAdder/assets/69374279/f7700b3f-4cdf-4c36-85fc-fab14cd68366)

### Full server log

https://mclo.gs/cPyhxfo

**Comment by Andre601** [comment]
You aren't using the latest version of IA. Please update.

**Comment by DextralityNetwork** [comment]
Hi, i updated to latest version and i get this error:
https://paste.helpch.at/upoqiyuhan.rb
https://prnt.sc/_hoNkwxo4G54

**Comment by Andre601** [comment]
> dev/lone/itemsadder/Main has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0

Please update your java version. The one you use does not recognize the one ItemsAdder was compiled in, which is Java 21

**Comment by Matteus130** [comment]
I have the latest version of the plugin. The textures show up as the white squares shown above

**Comment by Andre601** [comment]
> I have the latest version of the plugin. The textures show up as the white squares shown above

Based on the logs you provided initially, you didn't. Please always make sure to provide up-to-date logs when reporting an issue to avoid this conflicts of information.
![grafik](https://github.com/PluginBugs/Issues-ItemsAdder/assets/11576465/1a3047e4-a89b-44e3-8a8d-24ffcb9f3b6f)

**Comment by Matteus130** [comment]
![Screenshot 2024-06-06 at 5 36 44 PM](https://github.com/PluginBugs/Issues-ItemsAdder/assets/69374279/f4145985-6861-4c16-83cd-03cf760c332e)
this is my plugin version

**Comment by DextralityNetwork** [comment]
https://prnt.sc/-OF46TWdCY3j

**Comment by Andre601** [comment]
> https://prnt.sc/-OF46TWdCY3j

v4 only supports the latest 1.20 version which right now is 1.20.6, Also please don't repeat replies.



> ![Screenshot 2024-06-06 at 5 36 44 PM](https://private-user-images.githubusercontent.com/69374279/337446960-f4145985-6861-4c16-83cd-03cf760c332e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MTAxMjQsIm5iZiI6MTcxNzcwOTgyNCwicGF0aCI6Ii82OTM3NDI3OS8zMzc0NDY5NjAtZjQxNDU5ODUtNjg2MS00YzE2LTgzY2QtMDNjZjc2MGMzMzJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDIxMzcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwZDE5ZDA1MGE2ZDZmODlkNTViMmVkMTU1NTMyYTNmYmIxNDU0ZTg4NjFkOGQ4NTI4ODFkNmEwYzUzZTZlNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hdIEEGgPjkcTeVDJ26rLkq4gPCwzOqiPTvHPje4rHEE) this is my plugin version

Then please provide up-to-date logs. Again, the ones you gave report you using v4.0.0-alpha-test-1 which is not the latest.
So unless you give the latest logs, we can't help you.

**Comment by DextralityNetwork** [comment]
last version

https://paste.helpch.at/ogokavaxik.makefile

**Comment by Andre601** [comment]
> last version
> 
> https://paste.helpch.at/ogokavaxik.makefile

I just replied to you:
> v4 only supports the latest 1.20 version which right now is 1.20.6, Also please don't repeat replies.

You are NOT using 1.20.6. Please read the changelogs and not just blindly download the latest update.

**Comment by Matteus130** [comment]
heres the latest log https://mclo.gs/894d0dZ

**Comment by DextralityNetwork** [comment]
What can I do now? I'm on 3.6.4 and it doesn't work and you told me to update it ;-;

**Comment by Andre601** [comment]
> What can I do now? I'm on 3.6.4 and it doesn't work and you told me to update it ;-;

[3.6.4-release-3](https://www.spigotmc.org/resources/73355/update?update=546971) is the latest version that still supports 1.20.4 and older.

**Comment by DextralityNetwork** [comment]
Without much bother, I would like you to add support for 1.20.4 as it is the last one that any stable server is on.

3.6.4-realese-3 still with the bug.

**Comment by DextralityNetwork** [comment]
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/99357255/12046bb9-a564-495a-88f2-f46fcdc6afd8)

**Comment by Matteus130** [comment]
heres the latest log https://mclo.gs/894d0dZ

**Comment by Andre601** [comment]
Guys... Don't repost the same message. I **DO** get notified here, so be patient...

**Comment by Andre601** [comment]
> heres the latest log https://mclo.gs/894d0dZ

The URL you set for the resource pack is invalid. Trying it leads to a connection error in the browser instead of downloading the zip file, so please make sure that the domain AND port you set are actually valid. Contact Minehut support if you have problems with setting this up.

**Comment by Andre601** [comment]
> Without much bother, I would like you to add support for 1.20.4 as it is the last one that any stable server is on.
> 
> 3.6.4-realese-3 still with the bug.

v4 won't support 1.20.4 or older. The reasons are A) Newer, much needed features not available in older MC versions, that ItemsAdder benefits from and B) this version is a complete recoding of ItemsAdder, changing pretty much everything. Adding backwards support would require a ton of hacky implementations, which generally would make maintaining the plugin harder.

If you want the latest IA version, update your server to 1.20.6, otherwise you have to live with the currently latest v3 and wait for LoneDev to maybe implement a fix, if there is one.

**Comment by Matteus130** [comment]
For the external host before i used the self host, it said the google drive URL was valid, and when i clicked it, it would download directly, but still showed white squares in game

**Comment by Andre601** [comment]
> For the external host before i used the self host, it said the google drive URL was valid, and when i clicked it, it would download directly, but still showed white squares in game

This usually means that the font images did not apply correctly, which usually is a configuration error.
It's always best to check your console to see if ItemsAdder reports any missing files.

**Comment by Matteus130** [comment]
should I check if its reporting any missing files with the /iareload command?

**Comment by Andre601** [comment]
> should I check if its reporting any missing files with the /iareload command or on the server startup?

Run /iazip
This will rezip the resource pack, reporting any issues with files and configurations in the console.

**Comment by Matteus130** [comment]
these are the only errors that appeared. [22:05:28 ERROR]: [ItemsAdder] [m[0;31;1mInvalid character in namespace '.DS_Store' of file: assets/custom_esc/.DS_Store[m
[22:05:28 ERROR]: [ItemsAdder] [m[0;31;1mInvalid character in namespace '.DS_Store' of file: assets/respackicon/.DS_Store[m

**Comment by Andre601** [comment]
Namespaces are only allowed to have alphanummeric characters (Meaning a-z and 0-9) and underscores. They also need to be all lowercase.

**Comment by Matteus130** [comment]
should i delete the .DS_Store files.. i dont know what they are

**Comment by Matteus130** [comment]
i got rid of those files and did /iazip again. this shows up in console, but theres no pack applied. 
`[22:10:25 INFO]: [ItemsAdder] [m[0;36;1m[Pack] Checking resourcepack url: https://drive.google.com/uc?export=view&id=1p2Xo1DRyuQGIMpDpkHfjzu-avFD9unzf[m
[22:10:25 INFO]: [PlaceholderAPI] Successfully registered internal expansion: img [1.0.1]
[22:10:25 INFO]: [PlaceholderAPI] Successfully registered internal expansion: iaplayerstat [1.0.1]
[22:10:27 INFO]: [ItemsAdder] [m[0;36;1m[Pack] LastEdit: 2024-06-06_19-38[m
[22:10:27 INFO]: [ItemsAdder] [m[0;32;1m[Pack] URL is valid (external). URL: https://drive.google.com/uc?export=view&id=1p2Xo1DRyuQGIMpDpkHfjzu-avFD9unzf[m
[22:10:28 INFO]: Spexzzzz issued server command: /iatexture all
[22:10:28 INFO]: [ItemsAdder] [m[0;36;1m[Pack] Applying every player... [m
[22:10:28 INFO]: [ItemsAdder] [m[0;32;1m[Pack] Applied to [0;33;1m2[0;32;1m players[m`

**Comment by Matteus130** [comment]
also just a note, when I use the resource pack from my computer (I put the zip in my resource pack folder) it works, and I can see all the textures. Just for people joining that dont have the pack downloaded, the plugin doesnt load it for them.

**Comment by LoneDev6** [comment]
This is the only way to know why a pack didn't load, I can't do anything more than providing you the tutorial I too use in these cases: https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown

Anyway the "invalid namespace" errors can be ignored as they don't make your pack fail to generate or download. They seem to be related to the fact that you have some MacOS files in your resourcepack.

-------------

Anyway you both seem to have some misconfiguration, the pack download works fine on a test environment, so please refer to the FAQ page I linked before and read it carefully.
I just tested the plugin and the packs download just fine.
