### ISSUE TITLE
Capes don't show up on emotes

### ISSUE THREAD

**Issue by TheGallium** [PluginBugs/Issues-ItemsAdder#3712]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

the.gallium

### What happened?

When using emotes on ItemsAdder, capes on players are not shown.

### Steps to reproduce the issue

- Log on with a skin that has a cape
- Set you're camera in 3rd person, usually with `F5`
- Use an emote with `/emote`
- The cape is not here anymore

### Server version

```
This server is running Paper version git-Paper-484 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 4445d23)
You are 13 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-196 (MC: 1.20.1)
```

### ItemsAdder Version

`3.6.3-beta-14`

### ProtocolLib Version

`5.2.0`

### LoneLibs Version

`1.0.45`

### Error (optional)

```shell
No error, the cape just disappears.
```

### Screenshots/Videos (you can drag and drop files or paste links)

Back side of my skin, you can see the cape.
![normal](https://github.com/PluginBugs/Issues-ItemsAdder/assets/96748006/1f661837-e26e-48af-88c3-6c8a1eb07dcb)

Back side of my skin, while emoting, you can't see the cape.
![while-emoting](https://github.com/PluginBugs/Issues-ItemsAdder/assets/96748006/70b33f3b-55eb-416c-904a-d38f6a56314c)

**Comment by Andre601** [comment]
This is not a bug.
Emotes aren't player models like on Bedrock Edition, but modified player heads.
It would be (nearly) impossible to display a player's cape.

**Comment by TheGallium** [comment]
Can't you spawn an armor stand with a custom model that looks like a cape and use the [Mojang API](https://wiki.vg/Mojang_API) to get the player's cape's texture and apply it?

**Comment by Andre601** [comment]
It *could* be possible, but this would then be yet another request towards the Mojang API, increasing the risk of causing a rate limit for the server.
In the end is it up to LoneDev to decide on this. I for my part see barely any benefits for this to be added.
