### ISSUE TITLE
Mount point not working properly in v4

### ISSUE THREAD

**Issue by PlayerSchark** [PluginBugs/Issues-ItemsAdder#3720]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

The Player should sit on any mountpoint. Currently in 

### Potential cause:
#3726 

### Steps to reproduce the issue

1. Create an entity
2. Create a mountpoint
3. Ride your entity

### Server version

Paper version 1.20.6-138-master@906df69

### ItemsAdder Version

ItemsAdder version 4.0.1-alpha-test-3

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-713

### LoneLibs Version

LoneLibs version 1.0.54

### Error (optional)

```shell
No stacktrace (Error field is currenlty required)
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/37115511/68fb1774-be48-4993-9392-8236c95b0d84)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/37115511/4bd03c5d-45cf-4681-9434-bdf53067e7ed)

**Comment by Andre601** [comment]
With what version are you joining the server?

**Comment by PlayerSchark** [comment]
1.20.6/vanilla

**Comment by LoneDev6** [comment]
To me works fine with bundle false.
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/064ebc42-710c-44d9-a863-a94953724e34)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/d65180e1-af95-47b3-94ca-6a9e181982a5)
