### ISSUE TITLE
`bundle_packets` - custom entity not moving, only shadow

### ISSUE THREAD

**Issue by PlayerSchark** [PluginBugs/Issues-ItemsAdder#3721]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

When you try to move or push an entity the entity doesn't move.

Research found that if you set `entities.custom-entitites.expert_users.bundle_packets` to `true` several rendering issues occur.
The custom entity is not moving, only the shadow (falling block).
Seems the entity bones are not moving, they are correctly rotating but not moving.

### Steps to reproduce the issue

1. Spawn an entity
2. Move it in any way. eg. water. or pushing it way

### Server version

Paper version 1.20.6-138-master@906df69

### ItemsAdder Version

ItemsAdder version 4.0.1-alpha-test-3

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-713

### LoneLibs Version

LoneLibs version 1.0.54

### Error (optional)

```shell
No stacktrace (Error field is currently required)
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: test
entities:
  cannon:
    display_name: "Cannon"
    type: ZOMBIE
    model_folder: entity/cannon
    silent: true
    can_sun_burn: false
    speed:
      movement: 0
      flying: 0
    max_health: 20
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/37115511/66f8ff02-dee0-4c1b-9da7-e0274020a46f)

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/564a61e3-e461-4f64-9161-c08108f3305f

Can't reproduce.
