### ISSUE TITLE
Discord Verification

### ISSUE THREAD

**Issue by NotTrams** [PluginBugs/Issues-ItemsAdder#3727]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

tramskovi

### What happened?

I have ItemsAdder on polymart and when i do /verify and URL, the bot returns error 403. Please man PLEASE verify me. i can provide screenshots and everything. also uh idk why but i do not remember how or with what email i bought the plugin so cant verify on forums so also need help with that. i can provide videos of my polymart page and everything.

### Steps to reproduce the issue

1. buy IA on polymart
2. try to verify on discord

### Server version

no version

### ItemsAdder Version

no version

### ProtocolLib Version

no version

### LoneLibs Version

no version

### Full server log

no log

### Error (optional)

```shell
no error
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/107796922/41bccd7c-b15b-4330-938b-f0ffd3e4922c)

**Comment by Andre601** [comment]
The issue tracker is meant for reporting bugs with ItemsAdder, not for reporting issues related to verification.
