### ISSUE TITLE
Smithing Table Recipes

### ISSUE THREAD

**Issue by DarioMavilia** [PluginBugs/Issues-ItemsAdder#3728]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Litning11

### Describe the solution you'd like

Please add a way to allow us to create custom recipes for smithing tables 🙏 

### Is your feature request related to a problem?

Yes, because I can't make the crafting path needed for certain custom items.

### Describe alternatives you've considered

Using normal crafting table recipes, but it's no good.

**Comment by jamydariels** [comment]
I think there is actually recipes for smithing table but i'm also almost sure that LoneDev didn't update it for 1.20 trims correctly yet.
I posted my config i made with the VSCode extension in #itemsadder-chat

**Comment by LoneDev6** [comment]
They were added in 2022: https://github.com/PluginBugs/Issues-ItemsAdder/issues/524#issuecomment-1293770123
Please open an issue report if they don't work.
Also an user requested some changes to the smithing recopes, so this might be something you want to check: #2815

**Comment by DarioMavilia** [comment]
> I think there is actually recipes for smithing table but i'm also almost sure that LoneDev didn't update it for 1.20 trims correctly yet. I posted my config i made with the VSCode extension in #itemsadder-chat

Hey, I can't find it. Could you post a link to the message?

**Comment by jamydariels** [comment]
@DarioMavilia here : https://discord.com/channels/533407895010803753/533413171403292712/1249783924109086742
you could have found it by searching "smithing" btw ^^ maybe it helps you next time

**Comment by LoneDev6** [comment]
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/2815
