### ISSUE TITLE
Attributes colors showing incorrectly and being removen on change mode creative 1.20.4

### ISSUE THREAD

**Issue by gabriel262m** [PluginBugs/Issues-ItemsAdder#3733]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

GabrielC_

### What happened?

My items seems to have problems whit attributes, shows wrong, also they being removed when i change to creative

### Steps to reproduce the issue

/iaget item
change to creative

### Server version

[15:49:41 INFO]: This server is running Paper version git-Paper-497 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: d8d54d9 on ver/1.20.4)
You are running the latest version

### ItemsAdder Version

[15:50:00 INFO]: ItemsAdder version 3.6.4-release-3
[15:50:00 INFO]: Customized Minecraft without client mods!
[15:50:00 INFO]: Website: devs.beer
[15:50:00 INFO]: Author: LoneDev

### ProtocolLib Version

[15:50:18 INFO]: ProtocolLib version 5.2.0-SNAPSHOT-679
[15:50:18 INFO]: Provides read/write access to the Minecraft protocol.
[15:50:18 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[15:50:31 INFO]: LoneLibs version 1.0.54
[15:50:31 INFO]: Collection of libs used by my plugins
[15:50:31 INFO]: Authors: LoneDev and others

### Full server log

https://mclo.gs/lXkBRnR

### Error (optional)

```shell
No errors in console
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: mckingdom
items:  
  espada_base:
    display_name: "&fEspada Base"
    resource:
      material: NETHERITE_SWORD
      generate: false
      model_path: armas/espadas/sword9
    attribute_modifiers:
      mainhand:
        attack_damage: 10
        attackSpeed: 1.7
  espada_forjada:
    display_name: "&fEspada Forjada"
    resource:
      material: NETHERITE_SWORD
      generate: false
      model_path: armas/espadas/sword2
###########################################################################################################################################
  espada_infernal:
    display_name: "&fEspada Infernal"
    resource:
      material: NETHERITE_SWORD
      generate: false
      model_path: armas/espadas/espada_infernal
  calamidad_cosmica:
    display_name: "&fCalamidad Cosmica"
    resource:
      material: NETHERITE_SWORD
      generate: false
      model_path: armas/espadas/calamidad_cosmica
```

### Other files, you can drag and drop them here to upload. (optional)

attribute-attack-damage: ' &2{value} Attack Damage'
attribute-attack-speed: ' &2{value} Attack Speed'
attribute-when-in-main-hand: '&7When in Main Hand:'
attribute-when-in-off-hand: '&7When in Off Hand:'
attribute-when-on-body: '&7When on Body:'
attribute-when-on-feet: '&7When on Feet:'
attribute-when-on-head: '&7When on Head:'
attribute-when-on-legs: '&7When on Legs:'
cannot-break-with-this-tool: '&cYou cannot break it with this tool'
cannot-repair: '&cThis item cannot be repaired'
repaired-successfully: '&aItem repaired successfully!'
cannot-set-durability: '&cCannot set durability!'
set-durability-successfully: '&aDurability set successfully!'
crafting-no-recipe: '&eNo recipe is available for this item'
given-item: '&aGiven item &e{item} &ato &e{player}'
removed-item: '&aRemoved item &e{item} &afrom &e{player}'
lost-item: '&aYou lost item &e{item}'
item-not-found: '&cItem &3{item} &cdoesn''t exists'
items-count: '&bItems count: &a{count}'
lore-usages: '&7Usages: {value}'
lore-durability: '&7Durability: {value} / {max}'
model-id: '&bModel ID: {value}'
name-config: '&bName in config: '
no-craft-permission: '&eYou don''t have permission to craft this item!'
no-permission: '&cYou don''t have permission to use this command!'
no-permission-detail: '&cYou don''t have permission &e{permission}'
no-permission-short: '&cNo permission'
now-playing: '&fNow playing: {value}'
obtained-item: '&aObtained item &e{item}'
dropped-item-coords: '&aDropped &e{item} &aat coords {coords}'
dropped-item-player: '&aDropped &e{item} &aat player {player}'
player-full-inventory: '&cPlayer''s inventory is full!'
player-offline: '&eThis player is offline'
prefix: '[ItemsAdder] '
resourcepack-error: '&4An error occurred when enabling the resourcepack. Please contact
  admins or disable resourcepacks.'
resourcepack-kick-declined: '&4You must accept the resourcepack! Also make sure you
  set them to ''Prompt'' or ''Enabled'' in server properties.'
resourcepack-apply-title: '&a&lAplikuje sa resourcepack...'
resourcepack-apply-subtitle: '&6Buď trpezlivý, zaberie to len pár sekúnd!'
resourcepack-popup-message: |-
  &6Vitaj &4{player}, &6prosím prijmi resourcepack aby si si užil server!
   &aJe to treba iba raz a je to povinné.
wrong-command-usage: '&cWrong command usage'
emoji-gui-title: '&3&lEmoji List'
map-death-location: Death Location
fuel-indicator: '&b&lFuel: {value}/{max}'
get-from-trade-machine: '&fGet from trade machines'
ia-button-worlds-populators: '&fBlock spawn info'
worlds: '&bWorlds:'
info: '&bInfo:'
chance: '&f   Chance: &7{value}%'
amount: '&f   Amount: &7{value}'
min-height: '&f   Min Height: &7{value}'
max-height: '&f   Max Height: &7{value}'
biome: '&f   Biome:'
drops-itself: '&e   Drops Itself'
fuel-item: '    &b{type} &7+{amount}'
iarecipe-wrong-usage: '&cWrong command usage. Correct usage: &e/iarecipe <item name>&c,
  &aor hold an item in hand'
iarecipe-no-custom-item: '&cThis is not a custom item! Please hold a custom item in
  hand &aor use this command: &e/iarecipe <item name>'
anvil-repair-info: '&fAnvil Repair Material'
ia-title-menu-categories: '&3&lCategories'
ia-button-search: '&fSearch...'
ia-button-back: '&fBack'
ia-button-next-page: '&fNext page->'
ia-button-previous-page: '&f<-Previous page'
ia-button-next-recipe: '&fNext recipe'
ia-button-previous-recipe: '&fPrevious recipe'
ia-search-results: Search results
ia-smeling: '&fSmelting'
ia-smelting: '&fEdit item'
ia-button-get-item: '&fGet item'
ia-vanilla-type: '&fVanilla type'
ia-model-id: '&fModel ID'
ia-title-crafting-view: '&fMain menu'
player-stat-value-read: '&eValue: &b{value}'
player-stat-value-write: '&eValue changed!'
player-stat-value-write-bypass: '&cPlayer has bypass permission. &cValue NOT changed'
player-stat-value-write-bypass-self: '&cYou have bypass permission. &cValue changed
  anyway because you executed the command on yourself.'
ia-button-loot-blocks: '&fDrop from block'
ia-button-loot-mobs: '&fDrop from mob'
ia-button-loot-fishing: '&fDrop from fishing'
ia-button-vehicle-fuel-items: '&eFuel items'
ia-button-seed-result: '&fFrom seeds'
nbt-rule: '&f   {rule}: &7{value}'
resourcepack-not-ready: '&6Resourcepack is not ready. It will be applied automatically
  in some seconds...'
mob-summon: '&aSpawned mob &6{mob} &aat coords &7{coords}'
mob-kill: '&aKilled &6{mob} &7x{amount} &ain loaded chunks'
mob-kill-all: '&aKilled &7x{amount} &acustom mobs in loaded chunks'
mob-not-found: '&cCan''t find mob &6{mob}'
entity-not-found: '&cCan''t find custom entity &6{entity}'
liquid-analyzer-low-level: '&eThis liquid level is too low. Please check the main
  source block'
liquid-analyzer-no-liquid: '&cThis is not a liquid'
liquid-bucket-place-near-error: '&cThere is a custom liquid of another type too near
  this one. Please place find another location.'
command-ingame-only: '&cYou cannot execute this from console! Use this command ingame'
rightclick-a-block: '&6Now rightclick the surface on where you want to spawn the tree'
spawned-tree: '&aTree spawned successfully!'
spawned-tree-error: '&cCan''t spawn a tree here!'
tree-not-found: '&cTree &3{item} &cdoesn''t exists'
played-totem-animation: '&aPlayed totem &e{totem} &aanimation to &e{player}'
played-sound: '&aPlayed sound &e{sound} &7(if exists) &ato &e{player}'
please-wait-events-cooldown: '&cPlease wait &6{interval} &cto use this item.'
player-stat-value-insufficient: '&cInsufficient {stat}! &7You need {rule}'
max-furnitures-vehicles-reached: '&cMax number of furnitures/vehicles reached in this
  chunk ({value}). Consider removing some mobs/armorstands/furnitures/vehicles from
  this chunk.'
tripwires-disabled: '&cTripwires are disabled on this server.'
font-image-chat-hover: "&fEmoji: {font_image} \nUsage: &7{placeholder} \n\n&eHINT:\
  \ \n&7You can use the &e/e &7command to send public \nmessages/commands with emojis\
  \ easier. \nWrite the emoji name and press &eTAB. \n \nExamples: \n&e/e Hello smile\
  \ \n&7prints &fHello :smile: \n \n&e/e /tell Notch Hello smile \n&7sends the command\
  \ &f/tell Notch Hello :smile:"
ia-button-surface-decorators: '&fSpawn info'
ia-button-trees-populators: '&fSpawn info'
please-wait-command-cooldown: '&cPlease wait &6{interval} &cto use this command.'
renamed-successfully: '&aItem renamed successfully!'
cannot-rename: '&cThis item cannot be renamed'
unknown-category: '&cUnknown category {name}'
not-colorable: '&eNot colorable material. Can''t apply color.'
colored-successfully: '&aItem colored successfully!'
cooldown-bossbar-title: '&fCooldown'
![Sin título](https://github.com/PluginBugs/Issues-ItemsAdder/assets/48396708/af6eef62-a1b0-4f72-a898-9cb51b0bd825)

### Screenshots/Videos (you can drag and drop files or paste links)

https://www.dropbox.com/scl/fi/4b9y6birhc8jtbie8163m/Minecraft-1.20.4-Multijugador-servidor-de-terceros-2024-06-13-10-33-12.mp4?rlkey=g3nw1hw3zlwu7t6rryyxuvd55&st=vai0a2la&dl=1

**Comment by Andre601** [comment]
Please make sure this also happens with just ItemsAdder and no other plugin by having it, ProtocolLib and LoneLibs on your server, without any other plugin.
If the issue doesn't exist there is it most likely another plugin causing the issue you're encountering.

**Comment by gabriel262m** [comment]
Hello Andre! i check this before and yup, still whit no plugins

**Comment by LoneDev6** [comment]
Can't reproduce, it has to do with a mod or another plugin.

https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/fb83e59d-f57f-4f3c-a84c-745fea83b051
