### ISSUE TITLE
Hex color format didn't work on items lore (v3)

### ISSUE THREAD

**Issue by SwartZCoding** [PluginBugs/Issues-ItemsAdder#3738]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

This hex format (describe in itemsadder official doc), didn't work on items lore. BUT on displayname it's work correctly.

<img width="499" alt="image" src="https://github.com/PluginBugs/Issues-ItemsAdder/assets/39431572/773bc89f-139a-402a-9986-71d922515bee">

### Steps to reproduce the issue

1. add item with this hex color format in config
2. reload
3. test

### Server version

Current: git-Purpur-2172 (MC: 1.20.4)*
* You are 4 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### ItemsAdder Version

3.6.4-release-3 (latest v3)

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.54

### Error (optional)

```shell
no
```

### Problematic items yml configuration file (optional)

```shell
carnivoret_weapon_set_pickaxe_ultime:
    display_name: "<#ddcece>✸ <gradient:#d0cdc1:#50c33d>Pioche Ultime"
    lore:
      - "Cet objet peut être <#50C33D>modifié &f!"
      - ""
    resource:
      material: NETHERITE_PICKAXE
      generate: false
```

**Comment by SwartZCoding** [comment]
Btw, gradiant format didn't work too on lore.

**Comment by LoneDev6** [comment]
This happens because you're mixing minimessage with the legacy color codes.
Replace the `&f` with `<white>`.
`"Cet objet peut être <#50C33D>modifié <white>!"`
