### ISSUE TITLE
I'm having a problem with custom ores

### ISSUE THREAD

**Issue by Nestor1996** [PluginBugs/Issues-ItemsAdder#3739]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

kidoakira

### What happened?

i have pb with my custom ore :D
https://streamable.com/n78sd8

### Steps to reproduce the issue

Check my video, Tks

### Server version

Current: git-Purpur-2176 (MC: 1.20.4)*
Previous: git-Purpur-2165 (MC: 1.20.4)
* You are running the latest version

### ItemsAdder Version

3.6.3-beta-13

### ProtocolLib Version

5.2.1-SNAPSHOT-689

### LoneLibs Version

1.0.45

### Error (optional)

```shell
no annouce
```

**Comment by Andre601** [comment]
1. You are outdated. WAY outdated. Latest ItemsAdder for 1.20.4 is 3.6.4-release-3, so please update.
2. If your "issue" is about the custom block changing texture for a brief moment, then this is an unfixable problem.
  ItemsAdder uses Noteblocks and their `instrument` and `note` attributes to apply different textures for the custom blocks. Right-clicking a noteblock will update its `note` attribute, making it now have a different one for a short moment before ItemsAdder can change it back. This results in the brief texture change. Again, it's not a problem by ItemsAdder but by the server itself.
  Purpur should in fact have an option to disable noteblock state changes, which can help mitigate this problem.
3. Finally, always provide Server Logs. We need them to debug issues faster.
