### ISSUE TITLE
 ItemsAdder 1.21

### ISSUE THREAD

**Issue by dinobossytnew** [PluginBugs/Issues-ItemsAdder#3748]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

DinoBoss2001

### Describe the solution you'd like

https://mclo.gs/e6EovPp

### Is your feature request related to a problem?

https://mclo.gs/e6EovPp

### Describe alternatives you've considered

oraxen 🤮 

### Additional context

not :D

**Comment by LoneDev6** [comment]
Will be implemented in the next days

**Comment by TheModdersDen** [comment]
Sweet! Looking forward to it! :)

**Comment by DontMessWithDis** [comment]
Any updates?

**Comment by helloman1244** [comment]
please give me 1.21 itemsadder

**Comment by Andre601** [comment]
> please give me 1.21 itemsadder

Please have patience.
It's one dev working on this plugin and he has quite a few other things to do.

**Comment by helloman1244** [comment]
> > please give me 1.21 itemsadder
> 
> Please have patience. It's one dev working on this plugin and he has quite a few other things to do.

Is there a way to know exactly what lonedev is doing?

**Comment by Yukino12333** [comment]
It's too slow, how to get a refund. I feel like it's time for me to embrace OR

**Comment by Andre601** [comment]
To quote myself:
> Please have patience.
> It's one dev working on this plugin and he has quite a few other things to do.

There is slso no obligation of LoneDev to make any updates.
Buying the plugin does not warrant a guarantee of future updates. The plugin is given "as-is" without any guarantees.

**Comment by TheModdersDen** [comment]
> It's too slow, how to get a refund. I feel like it's time for me to embrace OR

You're more than welcome to "embrace OR," if that makes you happy. Just keep in mind that pestering people into having them work on a project never ends happily (for anyone).

Take a look at the many examples of overworked game devs in AAA studios and you'll see what I mean.

And yes, the dev of this plugin does not fall under this category, but he still **DOES NOT** need to be repeatedly bothered by anyone for an update that is not guaranteed, as previously mentioned.

//TheModdersDen

**Comment by jhqwqmc** [comment]
When will support 1.21 😞

**Comment by LoneDev6** [comment]
Will be implemented at some point, please stop spamming this thread, this doesn't speed up the update at all
