### ISSUE TITLE
1.16.5 Server Problem 

### ISSUE THREAD

**Issue by xBeratE** [PluginBugs/Issues-ItemsAdder#3750]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

xberat

### What happened?

https://mclo.gs/eODmFOA

### Steps to reproduce the issue

https://mclo.gs/eODmFOA

### Server version

1.16.5 Purpur

### ItemsAdder Version

4.0.1-alpha-test-4

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.54

### Full server log

https://mclo.gs/eODmFOA

### Error (optional)

```shell
https://mclo.gs/eODmFOA
```

**Comment by Andre601** [comment]
v4 of ItemsAdder is ONLY for 1.20.6. Please read the changelog before just downloading an update, thanks.
