### ISSUE TITLE
Box 

### ISSUE THREAD

**Issue by Takyu251003** [PluginBugs/Issues-ItemsAdder#3755]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

takyu1003

### What happened?

Im new to itemsadder and watching a full guide one by one on yt tutorial, after downloading the itemsadder plugin, i used /iareload then /iazip then reload again then suddenly it shows this box thingy on the top of my hotbar, i did some research first before making a report.

1. I disabled resource pack on server.properties
2. This only happened after i download itemsadder
3. I did not put any resource pack or mcmodel etc. here since I'm following a tutorial in youtube
4. I only did is download lonelibs, protocol libs and ItemsAdder_3.6.4-release.3 (since that's the only compatible to our server)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/173630607/c87bf661-7fd9-4e59-a793-2f3d1c232db0)

### Steps to reproduce the issue

*

### Server version

*

### ItemsAdder Version

*

### ProtocolLib Version

ItemsAdder_3.6.4-release-3*

### LoneLibs Version

*

### Full server log

*

### Error (optional)

```shell
*
```

### Problematic items yml configuration file (optional)

```shell
*
```

### Other files, you can drag and drop them here to upload. (optional)

*

### Screenshots/Videos (you can drag and drop files or paste links)

*

**Comment by Andre601** [comment]
Fill out the issue as requested. Don't leave blanks.
