### ISSUE TITLE
Did Not Get Customer Role After Being Verified.

### ISSUE THREAD

**Issue by DontMessWithDis** [PluginBugs/Issues-ItemsAdder#3760]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

DontMessWithDis#8784

### What happened?

I got verified by the bot in discord but never received my customer role. 

### Steps to reproduce the issue

Get verified and not receive the role 🤣

### Server version

N/A

### ItemsAdder Version

N/A

### ProtocolLib Version

N/A

### LoneLibs Version

N/A

### Full server log

N/A

### Error (optional)

```shell
N/A
```

### Problematic items yml configuration file (optional)

```shell
N/A
```

### Other files, you can drag and drop them here to upload. (optional)

![IMG_5192](https://github.com/PluginBugs/Issues-ItemsAdder/assets/121703064/fff8ce46-f58b-4cf4-b00f-81ac57736976)

### Screenshots/Videos (you can drag and drop files or paste links)

![IMG_5192](https://github.com/PluginBugs/Issues-ItemsAdder/assets/121703064/48c7c4af-273a-47c9-b752-07fb636fe301)
![Uploading IMG_5193.png…]()
![Uploading IMG_5193.png…]()

**Comment by Andre601** [comment]
GitHub issues are reserved for issues with the plugin, not for customer issues themself.

Either way, the customer role is only cosmetic and doesn't add any beneficial features.
