### ISSUE TITLE
Bedrock pack translator

### ISSUE THREAD

**Issue by AnaNazzDev** [PluginBugs/Issues-ItemsAdder#3761]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Hi, I thought it would be cool via an addon or directly itemsadder that the java pack automatically translates into bedrock format (with fonts, items, models, maybe shaders etc).

### Is your feature request related to a problem?

I want to export my server to the bedrock version but I have so many fonts via the different plugins, so many items etc that doing it manually or with wobbly tools that don't work isn't efficient.

### Describe alternatives you've considered

//

### Additional context

//

**Comment by Andre601** [comment]
ItemsAdder is designed for Java Edition servers. Having it have a feature to convert the RP to a Bedrock compatible one would not only be out of scope, but most likely be very resource intense in the end... And that for a feature most likely nobody would use in the end.

**Comment by AnaNazzDev** [comment]
> ItemsAdder is designed for Java Edition servers. Having it have a feature to convert the RP to a Bedrock compatible one would not only be out of scope, but most likely be very resource intense in the end... And that for a feature most likely nobody would use in the end.

I think such a feature is eagerly awaited by many. Maybe not every IAZIP, but a system/addon or even an external site that allows you to convert a complete java pack to bedrock.

**Comment by Andre601** [comment]
There are sites that can convert JE resource packs to BE ones.

For example: https://modifiedcommand.github.io/ConvertJavaTextureToBedrock/
