### ISSUE TITLE
`nbt` attribute overwrites the components instead of merging them

### ISSUE THREAD

**Issue by konfix** [PluginBugs/Issues-ItemsAdder#3763]
### Discord tag (optional)

@konfa

### What happened?

Furniture doesn't appear as furniture at all in the new update.

### Steps to reproduce the issue

1. open ia menu to get an item or just get it through commands
2. furniture can't be placed

### Server version

Current Purpur Version: 1.20.6-2233-0d6766e (MC: 1.20.6)*
* You are running the latest version
Previous: 1.20.6-2232-f1c87e4 (MC: 1.20.6)

### ItemsAdder Version

ItemsAdder version 4.0.1-alpha-test-5

### ProtocolLib Version

5.3.0-SNAPSHOT-722

### LoneLibs Version

1.0.55

### Problematic items yml configuration file (optional)

```shell
sto_trpezarijski_birch:
    display_name: ":normalno: &7Dining Table (Birch)"
    nbt: '{mn:{farbanje: 0}}'
    lore:
      - "<#d6e3cc>Use furniture to decorate"
      - "<#d6e3cc>all your builds!"
      - ""
      - "&f:klik: &7on the floor!"
    resource:
      material: LEATHER_HORSE_ARMOR
      generate: false
      model_path: namestaj/sto_trpezarijski_birch
    behaviours:
      furniture:
        fixed_rotation: true
        solid: true
        small: false
        entity: item_frame
        placeable_on:
          walls: false
          ceiling: false
          floor: true
        hitbox:
          length: 2
          width: 3
          height: 1
          length_offset: -0.5
        sound:
          place:
            name: block.bamboo_wood.place
          break:
            name: block.bamboo_wood.break
```

### Screenshots/Videos (you can drag and drop files or paste links)

![BdwVW1c](https://github.com/PluginBugs/Issues-ItemsAdder/assets/66477781/948ed925-8f32-4375-b12e-52a312c6411d)

**Comment by LoneDev6** [comment]
Please do not post multiple issues on the same issue page.
I separated them for you: #3766

**Comment by konfix** [comment]
Any update on this? I really need the plugin working, it's been a month

**Comment by konfix** [comment]
The furniture stops working as soon there is a custom NBT tag applied to the item **nbt: '{mn:{farbanje: 0}}'**

**Comment by PSYCHEER** [comment]
> The furniture stops working as soon there is a custom NBT tag applied to the item **nbt: '{mn:{farbanje: 0}}'**

Due to extensive changes in new version of Minecraft are NBTs broken atm.
