### ISSUE TITLE
Hiding particles in potion effects

### ISSUE THREAD

**Issue by sphynxinc** [PluginBugs/Issues-ItemsAdder#3769]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

sphynxinc

### Describe the solution you'd like

An option in creating potions or using potion_effects in events to hide particles and icon(not in gui)

### Is your feature request related to a problem?

In custom item when i see potion particles it's just annoying in pvp, building etc.

### Describe alternatives you've considered

You can only fix this not using potion effects, but attributes.

**Comment by LoneDev6** [comment]
You can try setting `ambient: true`.
