### ISSUE TITLE
From time to time, write things to the folders of other temporary worlds.

### ISSUE THREAD

**Issue by NEIKI19914** [PluginBugs/Issues-ItemsAdder#3772]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/59737752/aeb54606-8ca1-4dac-af30-521e2bb5e1b9)
Occasionally it happens that ia works in a folder that has been deleted from the world.
This happens occasionally, but not necessarily. CustomCrops also uses the world folder to save plug-in data but it does not appear.

### Steps to reproduce the issue

I am testing the compatibility of the MythicDungeons-1.4.1-SNAPSHOT-Build 220 plug-in to create dungeons. After creating the dungeon, most of the time ia works fine.
Only ia will occasionally create a deleted dungeon world folder and work in it, but other plug-ins do not do this.
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/59737752/0dc70371-cb83-4c04-bfae-a55b7c053654)
This is a normal dungeon world folder, completely different from the world folder above which only has the itemsadder folder.

### Server version

Current Purpur Version: 1.20.6-2233-0d6766e (MC: 1.20.6)*
* You are running the latest version

### ItemsAdder Version

4.0.1-alpha-test-5

### ProtocolLib Version

5.3.0-SNAPSHOT-721

### LoneLibs Version

1.0.55

### Error (optional)

```shell
The console does not throw any itemssadder errors
```

**Comment by LoneDev6** [comment]
Seems something related to this issue: #3245
I currently can't find the cause of this issue but I suspect it's caused by a race condition.
Probably CustomCrops is calling ItemsAdder methods accessing custom blocks when the world is already unloaded, or some other obscure little bug.
Currently I have no solution for that.

**Comment by NEIKI19914** [comment]
> Seems something related to this issue: #3245 I currently can't find the cause of this issue but I suspect it's caused by a race condition. Probably CustomCrops is calling ItemsAdder methods accessing custom blocks when the world is already unloaded, or some other obscure little bug. Currently I have no solution for that.

This also happens on my server without CustomCrops installed, in but it seems to only happen after editing the dungeon /md edit id. Playing normally with ItemsAdder_4.0.2-alpha-test-3 does not cause the dungeon's temporary world to fail to be removed.

**Comment by INSide-734** [comment]
> Seems something related to this issue: #3245
> I currently can't find the cause of this issue but I suspect it's caused by a race condition.
> Probably CustomCrops is calling ItemsAdder methods accessing custom blocks when the world is already unloaded, or some other obscure little bug.
> Currently I have no solution for that.

Never think about whether it is their own reason and blindly blame the problem on other plug-ins. This is your only advantage. Maintaining a plug-in with such a large user volume is your own business, not a team. Don't you want to show others the code you wrote? Or don't you want to share some of this considerable income with others?

LOL

**Comment by Andre601** [comment]
> Never think about whether it is their own reason and blindly blame the problem on other plug-ins. This is your only advantage. Maintaining a plug-in with such a large user volume is your own business, not a team. Don't you want to show others the code you wrote? Or don't you want to share some of this considerable income with others?
> 
> LOL

What "considerable income"?
Unless you actually have access to his receipts should you not assume stuff sbout LoneDev.

For all we know is LoneDev not gaining any notable income from plugin sells alone.

Your overall attitude is awful and you shouldn't have such a demanding tone.

**Comment by INSide-734** [comment]
> What "considerable income"?
> Unless you actually have access to his receipts should you not assume stuff sbout LoneDev.
> 
> For all we know is LoneDev not gaining any notable income from plugin sells alone.
> 
> Your overall attitude is awful and you shouldn't have such a demanding tone.

Do I have to speak in a condescending tone as a paying user? Am I inferior?

I'm sure he won't tell the public about his overall income. I'm sure it's not hard to see how much money can be made from this plug-in. 

Are you just a shield as a helper? Shouldn't he answer that?

**Comment by Andre601** [comment]
I answer because I can't stand people like you which have such an attitude that is "I bought this plugin, so the dev must help!"

And before you say anything: No, the fact you bought ItemsAdder doesn't give you any rights outside of downloading and using the plugin.
LoneDev owes you nothing.

**Comment by INSide-734** [comment]
> I answer because I can't stand people like you which have such an attitude that is "I bought this plugin, so the dev must help!"
> 
> And before you say anything: No, the fact you bought ItemsAdder doesn't give you any rights outside of downloading and using the plugin.
> LoneDev owes you nothing.

this is a joke

you is a joker 🤣🤣🤣

**Comment by Andre601** [comment]
I can see that you're not open to reason, so I'll lock this discussion for the time being.

If LoneDev wants to reply will he do that.

**Comment by LoneDev6** [comment]
@INSide-734 you are adding nothing to the conversation, if you don't enjoy my product you're free to seek for alternatives.
There is a 76 comments conversation going on about this issue, I'm not here sitting doing nothing, I tried finding the cause without success, I'll try again when I will have the time.
The only common thing is that other plugins using the ItemsAdder API are triggering similar issues, so probably there is a racing condition in the API I will eventually fix once I find the cause.
The issue is that I already tried setting up the same environment as my customers and can't trigger the issue, so this is why I'm still unable to provide a fix.

**Comment by LoneDev6** [comment]
> I'm sure he won't tell the public about his overall income. I'm sure it's not hard to see how much money can be made from this plug-in.

I don't see how it's related other than showing your frustration, which I'm sorry to hear as I'm doing my best to find the cause of this issue.

**Comment by NEIKI19914** [comment]
I think... There is no need to quarrel, feedback the problem is to solve the problem, and it is a good thing that the problem is improving or being solved. When I was learning to use the Mythic Dungeon in 1.20.4, the problem was even more serious at that time... Even if you play the dungeon, the temporary dungeon may not be able to be removed due to the occupation of IA... Of course, the mythical dungeon also thought that this would happen to some plugins, and they also made their own solutions... When the server is restarted, these temporary dungeon worlds that fail to be deleted will be removed.

**Comment by Projecki** [comment]
My production server is crashing 1-2 times per day due to this issue. I am on ItemsAdder 3.6.4 release-3

Is there any planned fix? I will need to remove ItemsAdder if a fix is not implemented soon.

Thank you
