### ISSUE TITLE
Furniture 2D icon item loss when using placeable_on and decrement_amount

### ISSUE THREAD

**Issue by FaultyFunctions** [PluginBugs/Issues-ItemsAdder#3773]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

FaultyFunctions

### What happened?

Using the 2d furniture item with placeable_on set to false and decrement_amount set to true will result in losing the item when clicking on a block that you aren't allowed to place the furniture on. There should be some sort of check to make sure the furniture was placed before actually decrementing the item.

Relevant wiki page: https://itemsadder.devs.beer/plugin-usage/adding-content/furniture/furniture-2d-icon

### Steps to reproduce the issue

1. Make furniture
2. Make a 2d furniture item
3. Set placeable_on walls to false for the furniture
4. Set decrement_amount to true on the 2D furniture item
5. Try to place the 2D item on a wall
6. Notice the count goes down when it shouldn't.

### Server version

 git-Purpur-2176 (MC: 1.20.4)

### ItemsAdder Version

ItemsAdder version 3.6.4-release-2

### ProtocolLib Version

 ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

 LoneLibs version 1.0.54

### Error (optional)

```shell
N/A
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: myitems
items:
  furniture:
    display_name: furniture
    permission: furniture
    lore:
    - 'lore-decorative-item'
    resource:
      material: PAPER
      generate: false
      model_path: decoration/furniture
    behaviours:
      furniture:
        solid: true
        cancel_drop: true
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          floor: false
          walls: false
          ceiling: false
    events:
      placed_armorstand:
        break:
          drop_item:
            item: 2d_furniture
  2d_furniture:
    display_name: 2d_furniture
    permission: 2d_furniture
    resource:
      material: PAPER
      generate: true
      textures:
      - item/2d_furniture
    events:
      interact:
        right:
          place_furniture:
            furniture: furniture
            decrement_amount: true
        right_shift:
          place_furniture:
            furniture: furniture
            decrement_amount: true
```

**Comment by LoneDev6** [comment]
Will be fixed by implementing this: https://github.com/PluginBugs/Issues-ItemsAdder/issues/4058
