### ISSUE TITLE
Not working items flags

### ISSUE THREAD

**Issue by sphynxinc** [PluginBugs/Issues-ItemsAdder#3775]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Item flags are not hidding, probably because of minecraft updating them 

### Steps to reproduce the issue

1. Create an item with item flags(use spigot ones)
2. Reload configs

### Server version

This server is running Paper version 1.20.6-147-ver/1.20.6@e41d44f (2024-06-17T19:24:35Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 4.0.1-alpha-test-5

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-721

### LoneLibs Version

LoneLibs version 1.0.55

### Error (optional)

```shell
There's no error in console, you should change this to optional not required.
```

### Problematic items yml configuration file (optional)

```shell
darksaber:
    display_name: <b><gradient:#606060:#ABABAB>ᴍʀᴏᴄᴢɴʏ</gradient><gradient:#ABABAB:#353535> ᴍɪᴇᴄᴢ</gradient></b>
    lore:
    - ' &fOstrze wykute w najniższych stopniach &#606060&lᴍ&#737373&lᴀ&#868686&lɴ&#989898&lᴅ&#ABABAB&lᴀ&#848484&lʟ&#5C5C5C&lᴏ&#353535&lʀ&f,'
    - '&fzdobyty z &#606060&lᴡ&#686868&lᴀ&#717171&lᴋ&#797979&lᴀ&#818181&lᴄ&#8A8A8A&lʏ&#929292&lᴊ&#9A9A9A&lɴ&#A3A3A3&lᴇ&#ABABAB&lᴊ'
    - '&#8E8E8E&ls&#7F7F7F&lᴋ&#707070&lʀ&#616161&lᴢ&#535353&lʏ&#444444&lɴ&#353535&lɪ &fpodczas wakacyjnego eventu'
    - ''
    - '&f Właściwości ostrza:'
    - '&8 - &#606060&l1&#6F6F6F&l2&#7E7E7E&l.&#8D8D8D&l5 &#ABABAB&lᴅ&#939393&lᴀ&#7C7C7C&lᴍ&#646464&lᴀ&#4D4D4D&lɢ&#353535&lᴇ'
    - '&8 - &#606060&l1&#696969&l.&#737373&l6 &#868686&lᴀ&#8F8F8F&lᴛ&#989898&lᴛ&#A2A2A2&lᴀ&#ABABAB&lᴄ&#9C9C9C&lᴋ &#7F7F7F&lᴅ&#707070&lᴀ&#616161&lᴍ&#535353&lᴀ&#444444&lɢ&#353535&lᴇ'
    - ''
    - '&c UWAGA! &fPo smierci item zostaje usuniety!'
    - ''
    - '&8(istnieje tylko 1 na serwerze)'
    resource:
      generate: false
      material: NETHERITE_SWORD
      model_path: darksaber/darksaber
    enchants:
    - VANISHING_CURSE:1
    - SHARPNESS:7
    - FIRE_ASPECT:3
    - LOOTING:3
    - MENDING:1
    - SMITE:5
    - UNBREAKING:3
    item_flags:
      - HIDE_ATTRIBUTES
      - HIDE_ENCHANTS
      - HIDE_ADDITIONAL_TOOLTIP
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/123591269/0317bd2e-05da-4528-a965-52c75f38ec59)

**Comment by thedarkonekiller** [comment]
Same problem with me

**Comment by LoneDev6** [comment]
Test the latest version of the plugin and let me know, should have been fixed.
Probably related to #3811
