### ISSUE TITLE
ItemName

### ISSUE THREAD

**Issue by dinobossytnew** [PluginBugs/Issues-ItemsAdder#3777]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

DinoBossYT

### What happened?

It seems that when I use hexcode in gradient or hexcode in a color palette to decorate items, it bugs out and doesn't work. For example, this is why this happens.

### Steps to reproduce the issue

Normal installation only creates 1 item and you give it a name and full hexcode lore. You can do it manually like me or use a tool, for example: https://alonsoaliaga.github.io/generator/

### Server version

Previous version: git-Paper-147 (MC: 1.20.6)

### ItemsAdder Version

[22:28:02 INFO]: 4.0.1-alpha-test-5
[22:28:02 INFO]: Customized Minecraft without client mods!
[22:28:02 INFO]: Website: devs.beer
[22:28:02 INFO]: Author: LoneDev

### ProtocolLib Version

ver ProtocolLib
[22:29:01 INFO]: ProtocolLib version 5.1.1-SNAPSHOT-673
[22:29:01 INFO]: Provides read/write access to the Minecraft protocol.
[22:29:01 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

ver lonelib
[22:29:16 INFO]: LoneLibs version 1.0.45
[22:29:16 INFO]: Collection of libs used by my plugins
[22:29:16 INFO]: Authors: LoneDev and others

### Full server log

https://mclo.gs/MolCJuQ

### Error (optional)

```shell
not
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: kuromi
items:
  kuromi_axe:
    display_name: "&#ffd3fcK&#d4f6ffu&#c9cfffr&#c1b0fco&#bc90ddm&#9689b9i &#d4f6ffAxe"
    permission: kuromi_set
    resource:
      material: NETHERITE_AXE
      generate: false
      model_path: axe
  kuromi_pickaxe:
    display_name: "&#ffd3fcK&#d4f6ffu&#c9cfffr&#c1b0fco&#bc90ddm&#9689b9i &#d4f6ffPickaxe"
    permission: kuromi_set
    resource:
      material: NETHERITE_PICKAXE
      generate: false
      model_path: pickaxe
  kuromi_rod:
    display_name: "&#ffd3fcK&#d4f6ffu&#c9cfffr&#c1b0fco&#bc90ddm&#9689b9i &#d4f6ffFishing Rod"
    permission: kuromi_set
    resource:
      material: FISHING_ROD
      generate: false
      model_path: fishing_rod
  kuromi_staff:
    display_name: "&#ffd3fcK&#d4f6ffu&#c9cfffr&#c1b0fco&#bc90ddm&#9689b9i &#d4f6ffStaff"
    permission: kuromi_set
    resource:
      material: NETHERITE_SWORD
      generate: false
      model_path: staff
  kuromi_sword:
    display_name: "&#ffd3fcK&#d4f6ffu&#c9cfffr&#c1b0fco&#bc90ddm&#9689b9i &#d4f6ffSword"
    permission: kuromi_set
    resource:
      material: NETHERITE_SWORD
      generate: false
      model_path: sword
  kuromi_key:
    display_name: "&#ffd3fcK&#d4f6ffu&#c9cfffr&#c1b0fco&#bc90ddm&#9689b9i &#d4f6ffKey"
    permission: kuromi_set
    resource:
      material: PAPER
      generate: false
      model_path: key
  kuromi_hoe:
    display_name: "&#ffd3fcK&#d4f6ffu&#c9cfffr&#c1b0fco&#bc90ddm&#9689b9i &#d4f6ffHoe"
    permission: kuromi_set
    resource:
      material: NETHERITE_HOE
      generate: false
      model_path: hoe
  kuromi_shovel:
    display_name: "&#ffd3fcK&#d4f6ffu&#c9cfffr&#c1b0fco&#bc90ddm&#9689b9i &#d4f6ffShovel"
    permission: kuromi_set
    resource:
      material: NETHERITE_SHOVEL
      generate: false
      model_path: shovel
  kuromi_backpack:
    display_name: "&#ffd3fcK&#d4f6ffu&#c9cfffr&#c1b0fco&#bc90ddm&#9689b9i &#d4f6ffBackpack"
    permission: kuromi_set
    resource:
      material: PAPER
      generate: false
      model_path: backpack
  kuromi_head:
    behaviours:
      hat: true
    display_name: "&#ffd3fcK&#d4f6ffu&#c9cfffr&#c1b0fco&#bc90ddm&#9689b9i &#d4f6ffHead"
    permission: kuromi_set
    resource:
      material: PAPER
      generate: false
      model_path: head
  kuromi_chest:
    display_name: "&#ffd3fcK&#d4f6ffu&#c9cfffr&#c1b0fco&#bc90ddm&#9689b9i &#d4f6ffChest"
    permission: littelpenguinset
    resource:
      material: PAPER
      generate: false
      model_path: chestkuromi
    behaviours:
      furniture:
        fixed_rotation: true
        solid: true
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          height: 2
          length: 1
          width: 1
```

### Other files, you can drag and drop them here to upload. (optional)

...

### Screenshots/Videos (you can drag and drop files or paste links)

![2024-07-01_19 54 50](https://github.com/PluginBugs/Issues-ItemsAdder/assets/58078116/c16333b0-7ecd-4fbc-b1c6-7f9e42c5e543)
![2024-07-01_19 54 50_2](https://github.com/PluginBugs/Issues-ItemsAdder/assets/58078116/3780b672-9bd2-4359-a1f0-3d7b15bfa3a9)
![2024-07-01_19 54 51](https://github.com/PluginBugs/Issues-ItemsAdder/assets/58078116/67d55e58-8128-4b60-b1e8-1a4a62bcfee2)
![2024-07-01_19 54 52](https://github.com/PluginBugs/Issues-ItemsAdder/assets/58078116/da3aab1c-035e-43c8-82a7-da8ae407b901)

**Comment by Andre601** [comment]
Your Info is very broken. Like you didn't provide the full output of /version ItemsAdder as requested.

**Comment by Andre601** [comment]
Also, Minimessage is used for formatting, including gradients, so make sure to use that instead of the ugly legacy color codes.
