### ISSUE TITLE
Possible Memory Leak due to Furnitures (Too many ConcurrentLinkedQueue nodes)

### ISSUE THREAD

**Issue by WhitehatD** [PluginBugs/Issues-ItemsAdder#3779]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

whitehatd

### What happened?

This issue is related to the API.
There is a memory leak that's been ongoing on our server for quite a while.
This issue is related to furnitures, they are being placed in multiple worlds and there's a lot of them.
I initially noticed that they wouldn't spawn properly in unloaded chunks, and I created a method that caches them to their respective chunk, where they need to be placed, and re-tries placing them on ChunkLoad.

Now the actual problem: after a while, the server simply crashes because it's out of memory. Visually, there are a lot of glitched furnitures placed in the same spot when there should be just one.

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/70808336/ffa2e84d-027a-4ab3-9b74-041d3056fc34)

I would greatly appreciate if we could talk more about this on discord.

### Steps to reproduce the issue

I am not 100% sure how to reproduce it. I want to find out if this is something I'm doing wrong or if there's something wrong with ItemsAdder.

### Server version

Current: git-Purpur-1985 (MC: 1.19.4)*
Previous: git-Pufferfish-73 (MC: 1.19.4)
* You are running the latest version

### ItemsAdder Version

3.6.4-release-3

### ProtocolLib Version

5.2.0

### LoneLibs Version

1.0.54

### Full server log

https://mclo.gs/EzyfReP

### Error (optional)

```shell
There's no error.
```

### Other files, you can drag and drop them here to upload. (optional)

These are two heapdumps taken about 10 minutes apart from eachother.
1st: https://spark.lucko.me/PuoMwhj5XP
2nd: https://spark.lucko.me/4ZtauXgCmN

**Comment by LoneDev6** [comment]
Thank you for the detailed report, I will let you know as soon as possible

**Comment by LoneDev6** [comment]
Sent you a message on Discord in a private ticket
