### ISSUE TITLE
text-effects - Not working

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#3783]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

  text-effects:
    enabled: true
    customitem-name-and-lore:
      enabled: true
    chat:
      enabled: true
    sign:
      enabled: true
    book:
      enabled: true
    anvil:
      enabled: true

### Steps to reproduce the issue

just use the last version and you gonna see it's not working
also emojis in lore not working too

### Server version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/68678154/0777c916-b032-4e37-8cdb-c2cbfc11f777)

### ItemsAdder Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/68678154/04ae56d7-cf88-451b-9d34-2f6291555282)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/68678154/ce8b2082-7d8d-4221-adea-0b48bbbf103a)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/68678154/773ce390-8e61-4f9c-b27a-08604686adf1)

### Full server log

   .

### Error (optional)

```shell
---
```

### Problematic items yml configuration file (optional)

```shell
.
```

### Other files, you can drag and drop them here to upload. (optional)

.

### Screenshots/Videos (you can drag and drop files or paste links)

.

**Comment by Andre601** [comment]
Please provide the server logs and don't just leave it blank. We do need it to properly debug the issue.

**Comment by Andre601** [comment]
A server never runs without logs. While there may not be any errors, there always are logs.
