### ISSUE TITLE
Rename plugin to "ResourcePack manager"

### ISSUE THREAD

**Issue by szarkans** [PluginBugs/Issues-ItemsAdder#3789]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Plugin named "**Items** **Adder**" have less functionality for adding items than a plugin for custom fishing, custom crops or any other **good** plugin for item managment.

No custom NBT/Components support, bad furniture support, bad glyphs feature, that require set up every symbol manually for proper working and many more problems.

As is - rename this "items" "adder" plugin to what it really is - **ResourcePack Manager**. Or start to make it really "items" "adder" plugin.

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/150809885/3d2ee84b-e686-46f5-aa48-bc23d340d705)

### Steps to reproduce the issue

1. Download this plugin
2. Do anything with it harder than adding display name or custommodeldata

### Server version

Every

### ItemsAdder Version

Every

### ProtocolLib Version

Not important

### LoneLibs Version

Not important

### Error (optional)

```shell
No error
```

**Comment by Andre601** [comment]
ItemsAdder does exactly what it says on the tin: It **adds items** you configure.

I can't see your problem here. All I see is you opening an issue to shit on a plugin for no justifiable reason.
Please avoid such issues, thanks.

**Comment by szarkans** [comment]
> ItemsAdder does exactly what it says on the tin: It **adds items** you configure.

Adding display name or attributes that hard-coded to plugin or anything is not exactly **good** adding items feature.
