### ISSUE TITLE
ItemsAdder PlayerInteractEvent causes lag

### ISSUE THREAD

**Issue by Lia-LV** [PluginBugs/Issues-ItemsAdder#3794]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

lia_lv

### What happened?

Server lag occurs from ItemsAdder PlayerInteractEvent

### Steps to reproduce the issue

using ItemsAdder Rightclick (mainhand) event?

### Server version

Paper version 1.20.6-148-ver/1.20.6@20f5165 (Implementing API version 1.20.6-R0.1-SNAPSHOT)

### ItemsAdder Version

4.0.1-alpha-test-5

### ProtocolLib Version

5.3.0-SNAPSHOT-723

### LoneLibs Version

1.0.55

### Error (optional)

```shell
none
```

### Other files, you can drag and drop them here to upload. (optional)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/71797814/0d904f27-d189-4560-a50b-fc09401f3539)

**Comment by Andre601** [comment]
Please use a proper profiler, such as Spark from Lucko, and not the Timings API. It's bad at really showing causes of lag and Paper themself recommend using Spark instead.

**Comment by Lia-LV** [comment]
> Please use a proper profiler, such as Spark from Lucko, and not the Timings API. It's bad at really showing causes of lag and Paper themself recommend using Spark instead.

Yea I know that, Timings isn't cool things. but I can't use Spark. idk why can't use Spark, may Paper latest version isn't installed as a default, I'll put Spark in my plugin folder next time.

**Comment by Lia-LV** [comment]
@Andre601 
![image](https://github.com/user-attachments/assets/2f717378-53b1-468d-be1a-9c23e8e60fa6)
Lag caused by ItemsAdder occurred again. This time, I profiled it with Spark, but it is not clear for me because of code obfuscation. however, lag is severe, so please fix it quickly.

**Comment by LoneDev6** [comment]
Will be fixed, thanks a lot.
