### ISSUE TITLE
Fire being extinguished on a magma block

### ISSUE THREAD

**Issue by PadowYT2** [PluginBugs/Issues-ItemsAdder#3797]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

padowyt2

### What happened?

If you put make a fire above a magma block, it will be extinguished like it would be a normal block (not netherrack). Normal Minecraft behavior is that the fire will stay forever

### Steps to reproduce the issue

1. Create a clean server
2. Upload ItemsAdder, Lonelibs, ProtocolLib
3. Start the server
4. Place a magma block
5. Place a fire on top of the block

### Server version

Paper version git-Paper-497 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: d8d54d9 on ver/1.20.4)

### ItemsAdder Version

3.6.4-release-3

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.55

### Full server log

https://mclo.gs/lMjdhEK

### Error (optional)

```shell
*none*
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://cdn.padow.ru/MpngL.mp4

Also tried without Via*, that did nothing

**Comment by LoneDev6** [comment]
Do you have custom fires enabled?

**Comment by PadowYT2** [comment]
> Do you have custom fires enabled? This might be the reason. I fixed that by adding also MAGMA block to the check instead of only NETHERRACK.

```yaml
  disable-FIRE: false
```
not sure if it's the right configuration though

**Comment by PadowYT2** [comment]
Any way for a fix on v3?
