### ISSUE TITLE
ItemsAdder Model character does not generate & and small nametag errors

### ISSUE THREAD

**Issue by iCrashMix0** [PluginBugs/Issues-ItemsAdder#3798]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

icrashmix

### What happened?

If Citizen's NPC plays an animation and despawns (/npc despawn) and then spawns again (/npc spawn) by command via Citizen's plugin NPC, then character model of ItemsAdder is no longer generated and is bugged. Watch the video just before the end. By the way, there is a small bug with Nametag, if character model is created by ItemsAdder, then the Nametag disappears. If I enter the command /npc despawn and then /npc spawn, then Nametag is there. You would have to manually remove Nametag with /npc name -h. I have not yet played any animation with Nametag, if no animation is played, then everything works without problems except with Nametag.

Would recommend to watch the complete video which I have done completely. There you can see how Nametag causes problems and the model of ItemsAdder is no longer generated at the end.

YouTube Video: [https://youtu.be/zUR_GiKBau8](https://youtu.be/zUR_GiKBau8)

### Steps to reproduce the issue

-

### Server version

![image](https://github.com/user-attachments/assets/4c384c12-d8f4-4542-ae1b-a79b6c392239)

### ItemsAdder Version

![image](https://github.com/user-attachments/assets/51a7938d-db4e-4773-b04e-129e2c32097e)

### ProtocolLib Version

![image](https://github.com/user-attachments/assets/03c00323-9d38-462c-a7fa-9f7f2ba7831c)

### LoneLibs Version

![image](https://github.com/user-attachments/assets/3020ebfb-8dcb-41b7-b6fc-8866b277737b)

### Error (optional)

```shell
-
```

**Comment by Andre601** [comment]
Please use 1.20.4 and not 1.20.2. There is no reason to stick with outdated patch versions.

**Comment by Andre601** [comment]
Also, you're WAY outdated with ItemsAdder. Latest release is 3.6.4-release-3 for 1.20.4
