### ISSUE TITLE
FontImageWrapper#replaceFontImages needs a method for Component

### ISSUE THREAD

**Issue by kangarko** [PluginBugs/Issues-ItemsAdder#3801]
The  "public static String replaceFontImages(Player player, String string)" method inside FontImageWrapper currently takes in a string.

I am updating ChatControl to Adventure. Please add a new method accepting a player and a Component from Adventure. 

You can use Component#replace to replace all occurrences with font images, the namings it should be self explanatory.

Please instruct me if I am wrong and there is a way to do this. Paper has deprecated all non-Adventure methods so moving forward we would need a way to deal with it anyways.

Thanks.
Matej

**Comment by LoneDev6** [comment]
Will be implemented in the next update, anyway I will probably have to mark it as `Object` instead of `Component` due to the fact that not every server has Adventure available and the class load would fail.

Anyway Paper is deprecating these methods but doesn't mean that they will be removed, also I doubt Spigot is interested into moving to Adventure like Paper is doing.

Have a great day

**Comment by kangarko** [comment]
Thank you very much. Yep, object is fine too, you can do failsafe checks on your end too.

Btw, I use adventure platform in my library so we wrap the CommandSender/Player into Audience regardless, works on Spigot too, plus we load the adventure library like luckperms do so it's safe.

**Comment by LoneDev6** [comment]
Will be available in: 4.0.2-alpha-test-8


https://github.com/LoneDev6/API-ItemsAdder/blob/19a65f4ff81e99e6bbae361199c92bf239778fd7/src/main/java/dev/lone/itemsadder/api/FontImages/FontImageWrapper.java#L43

https://github.com/LoneDev6/API-ItemsAdder/blob/19a65f4ff81e99e6bbae361199c92bf239778fd7/src/main/java/dev/lone/itemsadder/api/FontImages/FontImageWrapper.java#L68

**Comment by kangarko** [comment]
Thank you!! Nope, we're not relocating, we're using Libby to download the library if it is missing and use it with the original package path. I will get present with this in the forthcoming major plugin update.

**Comment by kangarko** [comment]
@LoneDev6 your jitpack compile is failing btw, I will just use the jar for now

**Comment by kangarko** [comment]
Also your API has Player.class in the legacy method
![Screenshot 2024-09-09 at 12 12 21](https://github.com/user-attachments/assets/36ba755e-d85e-4774-9fb1-bd23fb6c59d3)


Whereas the jar I got from polymart uses Permissible.class:

![Screenshot 2024-09-09 at 12 12 10](https://github.com/user-attachments/assets/6ef314b9-51b7-4073-b5e0-a37d57182179)
