### ISSUE TITLE
Placeholder supported player heads.

### ISSUE THREAD

**Issue by devastro1** [PluginBugs/Issues-ItemsAdder#3807]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

devastro

### Describe the solution you'd like

TabList requires %ia_player_head% placeholder which we can use in chat or wherever I want.
Such add-ons require additional resource pack and we cannot use them with itemsadder. 

Please do what is necessary, with respect and greetings.

Google Translate Used!

### Is your feature request related to a problem?

I can't say it's a problem, but it's about placeholders.

### Describe alternatives you've considered

An additional addon can be developed, or an existing addon can be updated.

### Additional context

![image](https://github.com/user-attachments/assets/95420820-8115-4aee-b7e5-c3a9d64193e1)
![image](https://github.com/user-attachments/assets/1327db1c-df7f-421a-a670-d986ea6e6b2f)

**Comment by Andre601** [comment]
Not sure what your goal here is exactly.
Please take your time to explain it in detail and use a more competent translator as google translate is complete and utter trash. I suggest using [DeepL](https://deepl.com).

**Comment by devastro1** [comment]
As you know, when we install any TabList plugin on our server, players' heads appear on the left side of their names in the TabList.

Unfortunately, on pirate servers this feature is not possible without using an additional plugin. When we install a plugin to display player heads, we create a resource pack like in itemsadder and we can put the players' heads wherever we want in %placeholder%.

We can't use an additional plugin because the warning message from ItemsAdder says that servers can't use more than one resource pack and we need to disable the resource pack in question.

Please update %placeholder% as I mentioned above so that we can use pictures of players' heads wherever we want, for example TabList, Scoreboard, Chat or menus.

I leave you a reference plugin to understand the logic of what I am saying: https://www.spigotmc.org/resources/%E2%9C%A8-katsuavatars-player-heads-with-placeholders.115998/

That's what it looks like in the pictures:
![image](https://github.com/user-attachments/assets/d65e8fa7-cdc6-4e14-afb0-46fbe0e3e9ff)

**Comment by paulreob** [comment]
This is not an ItemsAdder issue, nor a placeholder issue
Simply disable resourcepack delivery from the KatsuAvatars plugin (if possible) and adapt the KatsuAvatars resourcepack to ItemsAdder
