### ISSUE TITLE
v3 - ia.m blocking netty threads

### ISSUE THREAD

**Issue by Projecki** [PluginBugs/Issues-ItemsAdder#3809]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

My server is experiences crashes when using ItemsAdder. Additionally, when it crashes it will freeze on shutdown.

During this frozen state, I have taken a thread dump: https://pastebin.com/RXebC0G2

I initially suspected an issue with ViaVersion, however KennyTV from ViaVersion informed me that "The only blocked netty threads I see are from whatever ia.m is, using protocollib
That obfuscated plugin is trying to access world state in a protocollib listener, which then blocks the entire thing during shutdown. haven't looked at 1.20.4 sources yet, but my guess is that main is waiting on netty connections to close, so it's blocked by that other plugin"

Could this be an ItemsAdder issue?

### Steps to reproduce the issue

n/a

### Server version

[17:16:03 INFO]: This server is running UniverseSpigot version git-UniverseSpigot-"3fce19c" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 3fce19c on ver/1.20.4-stable)
Universe-git-UniverseSpigot-"3fce19c" (MC: 1.20.4)

### ItemsAdder Version

[17:16:31 INFO]: ItemsAdder version 3.6.4-release-2
[17:16:31 INFO]: Customized Minecraft without client mods!
[17:16:31 INFO]: Website: devs.beer
[17:16:31 INFO]: Author: LoneDev

### ProtocolLib Version

[17:16:47 INFO]: ProtocolLib version 5.2.1-SNAPSHOT-689
[17:16:47 INFO]: Provides read/write access to the Minecraft protocol.
[17:16:47 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[17:17:03 INFO]: LoneLibs version 1.0.54
[17:17:03 INFO]: Collection of libs used by my plugins
[17:17:03 INFO]: Authors: LoneDev and others

### Error (optional)

```shell
provided above
```

**Comment by Andre601** [comment]
Your ItemsAdder is outdated. Please update it and its dependencies and check if the issue persists. If it does, test it with a Spigot or Paper server. If it doesn't show there is this an issue with the fork you use.

**Comment by Projecki** [comment]
@LoneDev6 any comment on this? Why close it?

Is there any more info I can get for you? Anything I need to change?

**Comment by LoneDev6** [comment]
I closed it because you're using an outdated ItemsAdder version and a fork of Spigot/Paper.
Test with the latest ItemsAdder v3 (not v4 as it's for 1.21) and use Paper or Spigot.
Let me know.

**Comment by Projecki** [comment]
I am using the latest ItemsAdder v3 and it is still happening @LoneDev6

**Comment by sennby** [comment]
ive had this issue for quite some time.
1.20.4 on puffer and on paper and on other forks. im on latest v3 as of rn.
Been dealing with it for months on months and losing data bc of it every reboot.

**Comment by DxrkCat** [comment]
some issue

**Comment by sennby** [comment]
@LoneDev6 Could we re-look at this possibly?

**Comment by LoneDev6** [comment]
Will be checked as soon as possible, I did just came back from vacation.

**Comment by LoneDev6** [comment]
For some reason this happens because I call `block.getType()` in `onPacketReceiving` of packet `PacketType.Play.Client.BLOCK_DIG` -> `START_DESTROY_BLOCK`.
This seems strange to be honest, I don't use any lock in this class, so might be a ProtocolLib bug? Or the chunk gets unloaded during digging?
Anyway shouldn't happen on ItemsAdder v4 because that code part is not there anymore, so consider updating in the future.

Let me know if the issue is game breaking and if it happens a lot, in this case I will try to find a solution for legacy v3.

**Comment by Projecki** [comment]
@LoneDev6 I mean ye this happens a few times a week for me. It is a pretty significant bug. Can we get a fix for 1.20? Thank you
