### ISSUE TITLE
Vanilla recipes not working correctly

### ISSUE THREAD

**Issue by iFranticman** [PluginBugs/Issues-ItemsAdder#3810]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

iFrantic

### What happened?

When i go to craft the items it just shows blank in crafting menu.
Can't craft Iron Helmet/Chest/Legs Block or certain tools.

### Steps to reproduce the issue

Craft iron armor

### Server version

1.20.6

### ItemsAdder Version

[401-alpha-test-5](https://forum.devs.beer/d/2584-itemsadder-401-alpha-test-5)

### ProtocolLib Version

#723 (Jun 27, 2024, 3:12:51 AM)

### LoneLibs Version

[1.0.55](https://www.spigotmc.org/resources/lonelibs.75974/update?update=550078)

### Full server log

No error in log

### Error (optional)

```shell
None just won't craft
```

**Comment by iFranticman** [comment]
Any updates if this is replicated?

**Comment by coventix** [comment]
I currently have this issue as-well. same version, same problem.

**Comment by LoneDev6** [comment]
Seems Spigot does't move the last added recipe to the top of the recipes registry anymore, it puts it at the end of the map.
See: RecipeManager#addRecipe.
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/diff/nms-patches/net/minecraft/world/item/crafting/CraftingManager.patch?until=735b2d0d7f10bc3b3a816e103cc86af8cb1ec645

Will be fixed.
