### ISSUE TITLE
CustomModelData-starting-value not working

### ISSUE THREAD

**Issue by jeffry1829** [PluginBugs/Issues-ItemsAdder#3814]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

jeffry1829

### What happened?

I tried update from 1.19.4 to 1.20.6
IA3.3.1 to IA4.0.1-alpha-test-5

The re-generated custom model data changes, and I don't see the cause of it.(Seems like the default order of custom model data changes?)

Since I possess previously generated resource pack, with previous custom model data.
I want to change CustomModelData-starting-value from 10000 to 20000. Such that old items with old custom model data will have correct texture.

However, this change does not affect anything, /iacustommodeldata shows that the custommodeldata still starts from 10000. And the texture are still wrong. (I tried /iacleancache items)

### Steps to reproduce the issue

1. Change CustomModelData-starting-value.ALL to 20000
2. Restart Server
3. iacleancache items
4. iazip

### Server version

This server is running Paper version 1.20.6-148-ver/1.20.6@20f5165 (2024-07-02T15:37:33Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)

### ItemsAdder Version

4.0.1-alpha-test-5

### ProtocolLib Version

5.3.0-SNAPSHOT-723

### LoneLibs Version

1.0.55

### Error (optional)

```shell
No error related to this
```

**Comment by Andre601** [comment]
ItemsAdder does not magically convert pre-existing Item CMD to the new values.
It gives/creates the item with the CMD and that's it.
This isn't a bug, it's an intentional behaviour.

**Comment by jeffry1829** [comment]
> ItemsAdder does not magically convert pre-existing Item CMD to the new values. It gives/creates the item with the CMD and that's it. This isn't a bug, it's an intentional behaviour.

I don’t get it, if IA remembers all item CMD, how come my new CMDs are different from old CMDs?

**Comment by jeffry1829** [comment]
> ItemsAdder does not magically convert pre-existing Item CMD to the new values. It gives/creates the item with the CMD and that's it. This isn't a bug, it's an intentional behaviour.

May you please tell me how to correctly update from IA3 to IA4? Because my CMDs all gone different with the same “data” directory.
Thanks!
