### ISSUE TITLE
Citizens iaentities loose model after restarting the server

### ISSUE THREAD

**Issue by Olthoo** [PluginBugs/Issues-ItemsAdder#3818]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Olthoo

### What happened?

Citizens iaentities loose skin after restarting the server

### Steps to reproduce the issue

/iaentity citizen 1 model robot:robot
restart the server

the model is gone

### Server version

Current Purpur Version: 1.21-2271-032697e (MC: 1.21)*

### ItemsAdder Version

4.0.2-alpha-test-3

### ProtocolLib Version

5.3.0-SNAPSHOT-723

### LoneLibs Version

1.0.55

### Full server log

https://mclo.gs/5SOhAnM

### Error (optional)

```shell
N/A
```

**Comment by LoneDev6** [comment]
Thanks, will be checked ASAP

**Comment by Olthoo** [comment]
I found out that after rebooting the server if I discard the change of Citizens/saves.yml and reload citizens the models reapear, citizens seems to not save the custom trait
![image](https://github.com/user-attachments/assets/9a039fa6-5ccc-471e-bc4a-2b1dda030390)

**Comment by LoneDev6** [comment]
There is still something bad going on with the Citizens compatibility.
I will probably have to restructure it completely and find out the cause, their API is not the best.

**Comment by Olthoo** [comment]
good luck!

**Comment by Olthoo** [comment]
thanks for keeping us updated
