### ISSUE TITLE
1.21 - Legacy custom durability not updated for already crafted items

### ISSUE THREAD

**Issue by matipoirierg** [PluginBugs/Issues-ItemsAdder#3822]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

After updating to the 1.21 plugin version from the latest 1.20.4 one custom armor have leather armor armor durability ignoring the one set on config, this is only for already existing armor, if you get a new one from the /ia menu it will have the custom durability correct.

### Steps to reproduce the issue

Update from a previous version

### Server version

This server is running Paper version 1.21-108-master@73a863b (2024-07-22T13:23:21Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Leaf-"dd62783" (MC: 1.20.4)

### ItemsAdder Version

4.0.2-alpha-test-3

### ProtocolLib Version

4.0.2-alpha-test-3

### LoneLibs Version

1.0.56

### Error (optional)

```shell
No error
```

**Comment by Andre601** [comment]
This is imo normal behaviour.
1.20.6+ changed nbt of items and added custom durability to items, which IA now uses.
It to my knowledge has no automatic conversion from the old durability system to the new one from vanilla.

**Comment by matipoirierg** [comment]
I'm cooked

**Comment by LoneDev6** [comment]
I might implement automatic conversion in the upcoming update, it should be easily doable, forgot to implement that.
I can make it togglable in config.yml in order to avoid useless CPU processing on inventory opening.
