### ISSUE TITLE
replace block from one to an other

### ISSUE THREAD

**Issue by Leahcimkrob** [PluginBugs/Issues-ItemsAdder#3827]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Bloody_Mind

### What happened?

I have redstone_lamp_black_on and redstone_lamp_black_off as models
How exactly do I have to set this in the item config so that the blocks are swapped when I right-click?
I can't seem to get over it

### Steps to reproduce the issue

We have now built the redstone lamps so that they should be blocks. Unfortunately, switching with the right mouse button or with the right mouse button plus shift still doesn't work.
Itemconfig:

### Server version

[22:28:37 INFO]: This server is running Paper version 1.21-109-master@5a5035b (2024-07-23T08:16:30Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### ItemsAdder Version

[22:29:25 INFO]: ItemsAdder version 4.0.2-alpha-test-3

### ProtocolLib Version

[22:29:49 INFO]: ProtocolLib version 5.3.0-SNAPSHOT-726

### LoneLibs Version

[22:30:08 INFO]: LoneLibs version 1.0.56

### Full server log

https://mclo.gs/RadlWpq

### Error (optional)

```shell
no error
```

### Problematic items yml configuration file (optional)

```shell
https://mclo.gs/Yw9sjIt
```

**Comment by Andre601** [comment]
The issue tracker is for bug reports and feature requests, not for help with the API or ItemsAdder itself.

For support, either use the [Forum](https://forum.devs.beer/) or the [Discord Server](https://discord.com/invite/4dfnpUK).

If you can proof that this is in fact a bug, then please provide proper info such as steps to reproduce, actual errors, item configuration/Code setup.

**Comment by Leahcimkrob** [comment]
Several people on Discord told me that it should work, or was possible at some point. So it's a bug.
