### ISSUE TITLE
OFFSET icon error texture not detected

### ISSUE THREAD

**Issue by AntiAradir** [PluginBugs/Issues-ItemsAdder#3832]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

.

### What happened?

Okay a few months ago I created a server (survival) everything was going well with the "itemadder" plugin until I added the add-on https://www.spigotmc.org/resources/addon-custom-esc-menu-and-death-screen-for-itemsadder.88809/ it didn't work correctly the textures were bugged to the max and I fixed it but only for my resolution however not for the others then I tried to fix it but it got worse EYE THE CAPTURE OF THE CUSTOM ESC MENU ADD-ON IS HOW I FOUND IT WHEN INSTALLING IT WITHOUT MODIFYING IT when I modified it as I said it looked good only for my resolution  I left it like that until today when I looked for a solution but not only that I wanted to improve the jobs by adding a menu but the same thing happened to me and also exactly the same in the tab  can someone help me?

### Steps to reproduce the issue

1. descargar el complemento https://www.spigotmc.org/resources/addon-custom-esc-menu-and-death-screen-for-itemsadder.88809/ usar la vercion "sd_version" y subirlo a /home/container/plugins/ItemsAdder/contents si se que tengo que poner la carpeta de sd y poner lo otro lo hice igual que el tutorial y salio eso 

### Server version

Purpur-1985 MC: 1.19.4

### ItemsAdder Version

3.6.3-beta-14

### ProtocolLib Version

5.2.0 SNAPSHOT 679

### LoneLibs Version

1.0.45

### Full server log

Unnecessary

### Error (optional)

```shell
.
```

### Problematic items yml configuration file (optional)

```shell
.
```

### Other files, you can drag and drop them here to upload. (optional)

.

### Screenshots/Videos (you can drag and drop files or paste links)

Tab: https://ibb.co/sycQxWs
Jobs:  https://ibb.co/6XjjrGS
Menu: https://ibb.co/f05dwng

**Comment by Andre601** [comment]
You're using an outdated ItemsAdder version. Please use the latest v3 release available.
Also, issues with add-ons - no matter if from LoneDev or a 3rd-party - are not for this issue tracker, so please ask in the Discord Server or the forum for help.

**Comment by AntiAradir** [comment]
> You're using an outdated ItemsAdder version. Please use the latest v3 release available. Also, issues with add-ons - no matter if from LoneDev or a 3rd-party - are not for this issue tracker, so please ask in the Discord Server or the forum for help.

Hi @Andre601, a question, which version v3 are you referring to?

**Comment by Andre601** [comment]
Check the Version History on Spigot.

**Comment by AntiAradir** [comment]
> Check the Version History on the resource page you purchased IA on.

Okay, I installed 4.0.1-alpha-test-5, is that ok? Or is it another one, sorry, I don't really understand AI versions.

**Comment by Andre601** [comment]
I told you the lates **v3**
4.0.1 is CLEARLY not v4... And even if it was would you use an outdated version still.
