### ISSUE TITLE
Grass blocks play no particle when broken

### ISSUE THREAD

**Issue by CarraGrive** [PluginBugs/Issues-ItemsAdder#3835]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

carragrive

### What happened?

itemsadder's replacing vanilla break block animation of short_grass (could affect other blocks too)
works without the need to config anything or have a pack
can't have the ""issue"" on creative mode

### Steps to reproduce the issue

- install itemsadder and start your server
- put yourself in survival mode
- try to break some short_grass

### Server version

Paper version 1.21-111-master@66165f7 (2024-07-27T14:44:39Z)

### ItemsAdder Version

ItemsAdder_4.0.2-alpha-test-3

### ProtocolLib Version

5.3.0-SNAPSHOT-723

### LoneLibs Version

1.0.56

### Error (optional)

```shell
no error
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://www.youtube.com/watch?v=Nqqj2dgqpDA

**Comment by Andre601** [comment]
Please share your `latest.log` through https://mclo.gs as it help us getting all the necessary info required to solving this issue.

**Comment by CarraGrive** [comment]
https://mclo.gs/pUa5BMw

**Comment by LoneDev6** [comment]
Will be checked, thanks

**Comment by WataLaker37821** [comment]
So there is no solution for that?
