### ISSUE TITLE
Itemsadder error on RP load

### ISSUE THREAD

**Issue by Dewynz** [PluginBugs/Issues-ItemsAdder#3842]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

The texture doesn't work, when I use /iazip it creates the bossbar, but it doesn't reload the player texture

### Steps to reproduce the issue

Reload the texture with "/iazip"

### Server version

The server is running Paper version git-Paper-450 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 62b220a)

### ItemsAdder Version

3.6.4-release-2

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.56

### Error (optional)

```shell
[17:36:36 WARN]: [ItemsAdder] Warning: forcefully setting player resourcepack status to installed because the plugin was reloaded.
```

**Comment by Andre601** [comment]
You are one version behind, so please update. Also, provide your **full** latest.log through https://mclo.gs

**Comment by Dewynz** [comment]
> You are one version behind, so please update. Also, provide your **full** latest.log through https://mclo.gs

One version behind on ItemsAdder?

**Comment by Andre601** [comment]
Yes
