### ISSUE TITLE
NOT a duplicate plugin load error

### ISSUE THREAD

**Issue by OperationTwelve** [PluginBugs/Issues-ItemsAdder#3847]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

LoneDev I am sorry to hear about the health issues. I put an issue in the other day and it was discarded as just a duplicate and pretty much meaningless.
So my question is, was 1.20 the last time itemsadder was going to work on our server? 

I think the short brief explanation I received was because of craftbukkit... Im sorry it's Spigot/Craftbukkit but when I paid for it, it worked just fine... that isnt the issue.. 

So I would like at least an indication of if I should go looking elsewhere for a plugin or when this plugin might be working again. I don't think I am being unreasonable.

I completely wiped out everything from my itemsadder folder, installed the default pack, configured the config file for self hosting. commands aren't working items are pieces of paper

### Steps to reproduce the issue

install plugin
start server
type /plugins
see itemsadder, protocolLib and LoneLibs in the plugin list in green
type /ia
nothing happens
type /iareload
nothing happens
type /iazip
tells me to wait because itemsadder is reloading
wait an hour
type /iazip
tells me to wait because itemsadder is reloading

### Server version

![image](https://github.com/user-attachments/assets/25bef5e8-af43-43a7-a19a-20b362a23861)

### ItemsAdder Version

![image](https://github.com/user-attachments/assets/15e4e86e-418f-4bd1-ba13-e4d76ed19a3f)

### ProtocolLib Version

![image](https://github.com/user-attachments/assets/f8ff789d-996c-436c-a964-07030cdfee37)

### LoneLibs Version

![image](https://github.com/user-attachments/assets/d02e4a94-b9f0-460f-905d-f67ca9ebb2f3)

### Full server log

https://mclo.gs/3Rnfz5y

### Error (optional)

```shell
[13:25:08] [Server thread/ERROR]: [ItemsAdder] Error loading the plugin, something is not configured right or an exception occured. More detail:
[13:25:08] [Server thread/WARN]: java.lang.IllegalAccessError: class lonelibs.dev.lone.fastnbt.nms.nbt.CraftItemStack_v1_21 tried to access field org.bukkit.craftbukkit.v1_21_R1.inventory.CraftItemStack.handle (lonelibs.dev.lone.fastnbt.nms.nbt.CraftItemStack_v1_21 is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @431a979a; org.bukkit.craftbukkit.v1_21_R1.inventory.CraftItemStack is in unnamed module of loader java.net.URLClassLoader @65b3120a)
[13:25:08] [Server thread/WARN]: at lonelibs.dev.lone.fastnbt.nms.nbt.CraftItemStack_v1_21.merge(CraftItemStack_v1_21.java:91)
[13:25:08] [Server thread/WARN]: at lonelibs.dev.lone.fastnbt.nms.nbt.NItem.merge(NItem.java:97)
```

**Comment by Andre601** [comment]
ItemsAdder is designed to work with Spigot and Paper servers, latter is the recommended choice over Spigot due to significant performance and API improvements.

If you really want to use Spigot, which I cannot see any particular reason for why you want that, then please make sure to obtain a copy using the [Build Tools](https://hub.spigotmc.org/jenkins/job/BuildTools/) Spigot provides, or make sure that your server host actually uses Spigot and not Craftbukkit, which based on your screenshots seems to be the case.

The reason why Craftbukkit is not supported is the simple lack of essential API that the others have.

So, the tl;dr is, use Paper if you have access to it, otherwise make sure you actually use Spigot and not Craftbukkit.

**Comment by OperationTwelve** [comment]
Im using the same spigot offered by Gportal that I have always used with itemsadder. The server wasn't started by me so I don't know why they went with Spigot.

**Comment by OperationTwelve** [comment]
but now that you mention it... I could just upload my own spigot.jar file and overide gportal.... what version do you recommend and where would I get it?

**Comment by OperationTwelve** [comment]
https://getbukkit.org/download/spigot would this be right?

**Comment by OperationTwelve** [comment]
well the server uninstalled my version and installed their version.... ugh

**Comment by Andre601** [comment]
> https://getbukkit.org/download/spigot would this be right?

Don't use getbukkit. It violates the Mojang EULA by redistributing modded server jar files, which is not allowed.

I already linked you one option, which is the Build Tools offered by Spigot to build the jar yourself. Info can be found on the [BuildTools Wiki](https://www.spigotmc.org/wiki/buildtools/)
I personally recommend to try and use Paper instead. It's much easier to get and provides various improvements, both in terms of performance and user API-wise. Link is [here](https://papermc.io)
