### ISSUE TITLE
Executable items overrides attribute_modifier and lore for itemsadder, which prevents changing these values in the itemsadder config

### ISSUE THREAD

**Issue by tetanik-x** [PluginBugs/Issues-ItemsAdder#3849]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

tetanik_

### What happened?

Executable items overrides attribute_modifier and lore for itemsadder, which prevents changing these values in the itemsadder config

Example. I deleted the lore from the sword in executable items, put another lore in the itemsadder, but in the end the lore is empty. The second example. I want to set the attack speed to 4, but I can't, because executable items overrides attribute_modifiers
![javaw_hA3w4yj5qb](https://github.com/user-attachments/assets/94241fbe-a75d-4bee-b2ca-ae3e71821c6b)
![notepad++_w9HpkLnnB6](https://github.com/user-attachments/assets/7fbd74f2-6994-44ce-9ca6-6f57872d7627)
![vivaldi_5BjmpSKAt1](https://github.com/user-attachments/assets/acfb1251-714c-4b0d-ba1f-2aa61154f180)

By the way, when I was at 1 20 4, everything worked fine

### Steps to reproduce the issue

1. Create "executable items" item without name and lore
2. Link with itemsadder and write attribute_modifier, lore, name
3. You can see that attribute_modifier and lore are missing

### Server version

 Current Purpur Version: 1.21-2275-82ccc76 (MC: 1.21)*

### ItemsAdder Version

ItemsAdder version 4.0.2-alpha-test-3

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-726

### LoneLibs Version

LoneLibs version 1.0.56

### Full server log

nope

### Error (optional)

```shell
nope
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: base
items:
  copper_glove:
    display_name: Медная перчатка
    lore: 
    - "&7Может ударить молнией"
    - "&7при атаке во время дождя"   
    durability:
      max_custom_durability: 250
    resource:
      material: iron_sword
      generate: false
      model_path: weapon/copper_glove
    attribute_modifiers:
      mainhand:
        attackDamage: 3
        attackSpeed: 4
      offhand:
        armor: 3
    blocked_enchants:
          - sharpness
    executableitem:
      id: copper_glove
```

**Comment by Andre601** [comment]
As was pointed out is this how IA works, so if it works when setting the stuff in EI, then this isn't a bug, but intentional behaviour.

**Comment by tetanik-x** [comment]
> As was pointed out is this how IA works, so if it works when setting the stuff in EI, then this isn't a bug, but intentional behaviour.

So everything worked on 1.20.4 and it was the itemsadder that set these parameters. Moreover, there is no equivalent attribute_modifier in executable items, there is only genericdamage, which sets all the damage, and not specifically to the item

**Comment by tetanik-x** [comment]
> As was pointed out is this how IA works, so if it works when setting the stuff in EI, then this isn't a bug, but intentional behaviour.

itemsadder:
![javaw_UuK97Mwno8](https://github.com/user-attachments/assets/b518bff9-e3ce-4fba-aa9d-59457e920c26)

executable items:
![javaw_Rl9wkUy5hV](https://github.com/user-attachments/assets/4884b9fe-274a-4c46-a0a7-2b470969ef9e)
