### ISSUE TITLE
Issues using command /iaemoji

### ISSUE THREAD

**Issue by DrHeretic** [PluginBugs/Issues-ItemsAdder#3851]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

DrHeretic

### What happened?

When trying to use command /iaemoji there is no trigger of the GUI to the command. When checking console there is no errors being thrown when command is entered. It seems that the IA is still working but not responsive.

This happened after the update to 1.21 with the latest version. 

All the other /ia commands are working. Its just /iaemoji

### Steps to reproduce the issue

Login to server after updating.
Use /iaemoji command
Nothing is produced.

### Server version

This server is running Paper version 1.21-123-master@0a1be9a (2024-07-31T02:57:35Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-109-5a5035b (MC: 1.21)

### ItemsAdder Version

 ItemsAdder version 4.0.2-alpha-test-3
 Customized Minecraft without client mods!
Website: devs.beer
 Author: LoneDev

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-726
Provides read/write access to the Minecraft protocol.
Authors: dmulloy2 and comphenix

### LoneLibs Version

LoneLibs version 1.0.56
Collection of libs used by my plugins
Authors: LoneDev and others

### Full server log

https://api.mclo.gs/1/raw/V9WuCGH

### Error (optional)

```shell
None.
```

**Comment by DrHeretic** [comment]
Still an issue

**Comment by LoneDev6** [comment]
#3934
