### ISSUE TITLE
Transparent block break with water

### ISSUE THREAD

**Issue by Martinou2x** [PluginBugs/Issues-ItemsAdder#3853]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

martinouxx

### What happened?

When I place water next to a transparent block (material: Chorus Plant), the block breaks.

### Steps to reproduce the issue

1. Place water next to a transparent block
2. The block breaks.

### Server version

Current Purpur Version: 1.20.6-2233-0d6766e (MC: 1.20.6)*

### ItemsAdder Version

ItemsAdder version 4.0.1-alpha-test-5

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-721

### LoneLibs Version

LoneLibs version 1.0.54

### Error (optional)

```shell
(optional)
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://www.youtube.com/watch?v=jUfVYY2tNGk

**Comment by Andre601** [comment]
Please update IA. You're outdazed.

**Comment by Martinou2x** [comment]
Same problem

Current Purpur Version: 1.21-2275-82ccc76 (MC: 1.21)
ItemsAdder version 4.0.2-alpha-test-3
ProtocolLib version 5.3.0-SNAPSHOT-726
LoneLibs version 1.0.56
