### ISSUE TITLE
Tile blocks appear as spawners when placed

### ISSUE THREAD

**Issue by FELIXCAT3** [PluginBugs/Issues-ItemsAdder#3859]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

I'm having an issue with the ItemsAdder plugin on Minecraft 1.21. When placing a TILE block, it appears as a spawner with paper. This started after updating to 1.21. Existing blocks work fine, but new blocks appear as spawners. I tested this on a new server with a fresh ItemsAdder install, and the issue persists.``

### Steps to reproduce the issue

1. Add a new TILE block
2. Place it

### Server version

This server is running Paper version 1.21-40-master@b45d9b6 (2024-07-01T08:23:14Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 4.0.2-alpha-test-3

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-726

### LoneLibs Version

LoneLibs version 1.0.56

### Error (optional)

```shell
There are no errors in the console
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: catcraft

items:
  seller:
    display_name: Seller
    permission: catitemsadder.blocks
    resource:
      generate: true
      material: PAPER
      textures:
        - blocks/seller_top
        - blocks/seller_front
        - blocks/seller_side
        - blocks/seller_side
        - blocks/seller_top
        - blocks/seller_side
    specific_properties:
      block:
        placed_model:
          type: TILE
          break_particles: ITEM
```

### Screenshots/Videos (you can drag and drop files or paste links)

![2024-08-03_20 59 32](https://github.com/user-attachments/assets/c027f0a6-eac5-43c6-981f-d8e98a5c1bf3)

**Comment by Andre601** [comment]
Any particular reason of using Tile blocks and not another option such as `REAL_NOTE`?
