### ISSUE TITLE
When I place items, the item quantity does not decrease

### ISSUE THREAD

**Issue by bananaQwQ666** [PluginBugs/Issues-ItemsAdder#3865]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

你的小蕉呀#6658 (bananaqwq)

### What happened?

I put the ItemsAdder block on the ground in survival, but the number of items in the inventory did not decrease. I dug out the block and the number of items in the inventory increased. I am very worried that the player can get unlimited items.

### Steps to reproduce the issue

1. Enter the game, type /ia to take out a custom block
2. Switch the game mode to survival
3. Place the custom block on the ground
4. Found that the number of items did not decrease
5. Dig out the items, the number of items increased

### Server version

[21:51:58 INFO]: This server is running Paper version git-Paper-84 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: c016e03)

### ItemsAdder Version

[21:52:14 INFO]: ItemsAdder version 3.6.4
[21:52:14 INFO]: Customized Minecraft without client mods!
[21:52:14 INFO]: Website: devs.beer
[21:52:14 INFO]: Author: LoneDev

### ProtocolLib Version

[21:52:24 INFO]: ProtocolLib version 5.2.0-SNAPSHOT-679
[21:52:24 INFO]: Provides read/write access to the Minecraft protocol.
[21:52:24 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[21:52:30 INFO]: LoneLibs version 1.0.56
[21:52:30 INFO]: Collection of libs used by my plugins
[21:52:30 INFO]: Authors: LoneDev and others

### Full server log

https://mclo.gs/tmYYYcD

### Error (optional)

```shell
you can check the log
```

### Problematic items yml configuration file (optional)

```shell
idk
```

### Other files, you can drag and drop them here to upload. (optional)

video is uploaded

### Screenshots/Videos (you can drag and drop files or paste links)

https://github.com/user-attachments/assets/a0e33d81-387a-42e5-90c4-fae683a7654d

**Comment by Andre601** [comment]
Please use Paper 1.20.4 and update ItemsAdder to the latest available v3 release.

**Comment by bananaQwQ666** [comment]
> 此外，请不要使用泄露的插件（这里不一定是在谈论 ItemsAdder），因为这样做对那些花时间和精力开发插件的开发人员来说是不礼貌的，因为其他人可能会窃取并重新分发它。
> 
> 在您声称您没有使用泄露的插件之前：
> 
> * 第 3616 行：`*** Downloaded from https://leaks.tf ***`

OK，I know

**Comment by bananaQwQ666** [comment]
> 请使用 Paper 1.20.4 并将 ItemsAdder 更新到最新可用的 v3 版本。

Uhh, Is it the only way to solve the problem? It takes me too much time to update to 1.20.4, and I afraid that there will be something wrong with some plugins.

**Comment by LoneDev6** [comment]
Remove other plugins, this probably is caused by other plugins.
Also provide your item configuration, might be something wrong with events.
