### ISSUE TITLE
`skip` property for TTF font

### ISSUE THREAD

**Issue by zzzyyylllty** [PluginBugs/Issues-ItemsAdder#3868]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

add "skip" option

### Is your feature request related to a problem?

the custom TTF font will misalignment when type Full Width.
![image](https://github.com/user-attachments/assets/13402c99-b10e-4c1e-b329-fcae34dee079)
The minecraft is already fixed use "skip" option.
![image](https://github.com/user-attachments/assets/77f27bdf-adf7-440d-a9fb-5e646e1fb1fd)

But ItemsAdder not add this option.
*_Digression: Minecraft actually supports OpenType fonts (after 1.20.5, only TrueType is supported)_

### Describe alternatives you've considered

manual add skip in default.json

**Comment by Andre601** [comment]
Your feature request doesn't make much sense. Please take your time to properly describe it here.

What is it that you actually want implemented?
Why exactly do you need it?
Any suggestions on how it could be implemented?
Are there pre-existing alternate ways to do this? If so, why not use those?

**Comment by zzzyyylllty** [comment]
Want implemented:
Itemsadder custom TTF font's "skip" option when generating default.json.
![4b93d769a6dc0867564cc3197045446e](https://github.com/user-attachments/assets/89f90247-5a4c-4e0d-90fc-8b35b4af274a)

Why need it:
when using some font,Full widch characters (such as （）【】“” ) will looks strange.
![image](https://github.com/user-attachments/assets/67a5ed60-96ca-463f-b72b-3ae7988e14e4)
This is because Minecraft's font rendering engine converts ttf to bitmap.
When generating,can use "skip" option to skip some character's generation and fix this bug: (In default.json)
![image](https://github.com/user-attachments/assets/7d8cd5f0-f74f-481f-b3d1-200d26a532e5)

But Itemsadder not have this option.
![4b93d769a6dc0867564cc3197045446e](https://github.com/user-attachments/assets/89f90247-5a4c-4e0d-90fc-8b35b4af274a)

pre-existing alternate ways:
Disable Itemsadder custom font,Manually create default.json with "skip" option.
why not use:
I am already using this.

**Comment by LoneDev6** [comment]
Thanks for your suggestion, I will implement that in the next updates.
https://minecraft.wiki/w/Font
> The skip field is either a list of strings, or a string of the characters to which this font has no assignment. If it is a list of strings, the strings are concatenated together and then act as if it were originally a string. This allows the same input as a bitmap provider's chars.
