### ISSUE TITLE
Biome and Loots to show in /ia along with conditions

### ISSUE THREAD

**Issue by spiker5032** [PluginBugs/Issues-ItemsAdder#387]
Was told by Lone to paste this in.

Add showing what biomes ores spawn in

And maybe the same with loots?
For example if i made a legendary ice fish that could only be caught in frozen ocean biomes

Or this
[WHATS MISSING](https://i.gyazo.com/f5e48f39aedde88f55207935f880ecb1.png)

maybe also add a modifier for loots? Like that ice fish for example can be caught more frequently at night time when its raining almost like how mythic mobs sets its spawning parameters
These would be conditions similar to mythic mobs.
[https://www.mythicmobs.net/manual/doku.php/conditions/start](url)

**Comment by LoneDev6** [comment]
This week I will release an update with the biomes info.
The other feature will be introduced in a future update.

Thanks for the ideas
