### ISSUE TITLE
Trees Populators dont work in custom dimensions

### ISSUE THREAD

**Issue by MathiasDPX** [PluginBugs/Issues-ItemsAdder#3884]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

When I join my custom dimension named dreamworld, I see no tree

*Normally* I place a tree on every basalt block

Full code: [MathiasDPX/PluginOpenMC](https://github.com/MathiasDPX/PluginOpenMC) under fr.communaywen.core.dreamdim

### Steps to reproduce the issue

1. Create a custom dimension
2. Try to make a trees populators

### Server version

[22:04:53 INFO]: Current Purpur Version: 1.21-2283-75e81d8 (MC: 1.21)*

Previous: 1.20.6-2233-0d6766e (MC: 1.20.6)

### ItemsAdder Version

ItemsAdder version 4.0.2-alpha-test-3

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-723

### LoneLibs Version

LoneLibs version 1.0.56

### Error (optional)

```shell
Their is no tree
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: aywen
trees_populators:
  dreamtree:
    worlds:
    - dreamworld
    bottom_blocks:
    - BASALT
    chance: 100.0
    max_height: 200
    min_height: 50
    amount: 3
    iterations: 2
    log: aywen:dream_log
    leaves: aywen:cloud
    biomes:
    - PLAINS

items:
  dreamtree_sapling:
    display_name: Pousse d'arbre de rêve
    resource:
      material: WHITE_WOOL
      generate: true
      textures:
      - items/dreamtree_sapling.png
    behaviours:
      sapling:
        tree_populator: dreamtree
```

**Comment by MathiasDPX** [comment]
Sometimes I get
```
[ItemsAdder] Tree populator dreamtree failed to load. Unknown world dreamworld. File: /contents/aywen/trees_populators.yml
```

**Comment by LoneDev6** [comment]
This probably happens because the world loads after the plugin is loaded, so it's not available on start. Can you confirm?

**Comment by MathiasDPX** [comment]
How can I load my plugin before ItemsAdder

**Comment by Andre601** [comment]
In your plugin.yml, add `loadbefore: [ItemsAdder]`. That should make it load before ItemsAdder.
If you use paper-plugin.yml, set the `load` option to `AFTER`

**Comment by MathiasDPX** [comment]
Hello,
I add `loadbefore: [ItemsAdder]` *as Andre601 said* but it generate another error because it cant' find my CustomStacks
![Screenshot_1](https://github.com/user-attachments/assets/f72b57c5-3ded-4fd5-8c93-f7a64d0cbf36)

**Comment by LoneDev6** [comment]
Are your worlds loaded after ItemsAdder is loaded or are they available on server start?

**Comment by MathiasDPX** [comment]
My world is temporary and is created every time I start my plugin
(I have a script in start.sh that delete the dimension before starting the server)

**Comment by MathiasDPX** [comment]
Timeline 1:
- Delete dreamworld
- Start the server
- IA load and don't find dreamworld
- My plugin load and create dreamworld

Timeline 2:
- Delete dreamworld
- Start the server
- My plugin load before IA
- It don't found CustomStacks so disable
- IA load and don't find my world

**Comment by LoneDev6** [comment]
I see, I will try to mitigate the issue.
Provide me your discord username so that I can add you to the beta testing channel.

**Comment by LoneDev6** [comment]
Should have been fixed, I'll send a new JAR in the beta channel as soon as possible.
Also custom biomes support will be added: #3642
