### ISSUE TITLE
Can't instabreak custom ItemsAdder blocks.

### ISSUE THREAD

**Issue by lodylu** [PluginBugs/Issues-ItemsAdder#3887]
### Terms

- [ ] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

lody_lu

### What happened?

I can't instabreak custom ItemsAdder blocks with the pickaxe (with High efficiency)

This is a huge issue for the box server i'm creating, at one point i want players to instabreak blocks.

### Steps to reproduce the issue

Use a only 1.20.4 paper.jar server
Install EssentialsX
Install ItemsAdder 3.6.4-release-3.jar
Install AdvancedEnchantments-9.10.3.jar
Provide your /plugins/ItemsAdder/contents/ with the default_pack and OtherPacks given as ItemsAdder resources on their GitHub ( https://github.com/ItemsAdder/DefaultPack/releases AND https://github.com/ItemsAdder/OtherPacks/releases )
Make sure to use Custom Blocks from ItemsAdder (Ores and Blocks with REAL_NOTE and NOTE are the targeted blocks)
Give yourself a Stone, Iron, Diamond or Netherite Pickaxe with efficiency 25, efficiency 50, efficiency 75, efficiency 100, efficiency 200
Try mining custom ores such as iasurvival ores (command: /ia -> iasurvival OR /iaget iasurvival: then press TAB to autofill)

Screenshots / Videos

### Server version

This server is running Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-"f042be6" (MC: 1.20.1)

### ItemsAdder Version

ItemsAdder version 3.6.4-release-3

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.55

### Full server log

[latest.log](https://github.com/user-attachments/files/16626510/latest.log)

### Error (optional)

```shell
No errors generated from this issue.
```

### Problematic items yml configuration file (optional)

```shell
I'm using the given default pack on ItemsAdder github. (iasurvival for custom ores)
```

**Comment by Andre601** [comment]
> There's no need, no errors generated from this issue.

Logs aren't just needed for when there is an error. Please fill out the issue as requested, including the logs.

**Comment by lodylu** [comment]
@Andre601 done 👍

**Comment by LoneDev6** [comment]
Provide a video of the issue

**Comment by LoneDev6** [comment]
This is normal, there is a delay to avoid excessive CPU usage and to avoid some texture glitches.
Anyway I doubt this would be an issue for any player.

**Comment by lodylu** [comment]
It will be an issue for my box server....
