### ISSUE TITLE
smithing recipe have a bug

### ISSUE THREAD

**Issue by Arvinnnnnn** [PluginBugs/Issues-ItemsAdder#3888]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Arvinizdabest

### What happened?

in custom smithing recipe the name of knife netherite in smithing is right but when put on items in inventory is the name of knife netherite automatic change to knife diamond

### Steps to reproduce the issue

in custom smithing recipe the name of knife netherite in smithing is right but in inventory is the name of knife netherite change to knife diamond

### Server version

git-Paper-497 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT)

### ItemsAdder Version

3.6.3-beta-12

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

### Full server log

no logs

### Error (optional)

```shell
no error
```

### Problematic items yml configuration file (optional)

```shell
smithing:
    knife_netherite:
      enabled: true
      base: gemsurvival:knife_diamond
      addition: NETHERITE_INGOT
      result:
        item: gemsurvival:knife_netherite
        amount: 1
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://cdn.discordapp.com/attachments/533413171403292712/1273221363532042302/2024-08-14_17-05-56.mp4?ex=66bdd34c&is=66bc81cc&hm=3683e7a0b3877da0360c6d540985b0301eef12e32921b2fecbae0e1c81c1d636&

**Comment by Andre601** [comment]
You use an outdated ItemsAdder version.
Please update it to the **latest v3 release** available and also update its dependencies.

**Comment by Arvinnnnnn** [comment]
![image](https://github.com/user-attachments/assets/bd74816b-b26a-4f8e-9ca7-ce2d15c80f12)
![image](https://github.com/user-attachments/assets/03e5eb23-62de-4a04-8ba0-95afaa081991)
Look the name of items

**Comment by Arvinnnnnn** [comment]
IA will automatically rename the item according to its material instead of the display name in the config
