### ISSUE TITLE
Flickering model texture

### ISSUE THREAD

**Issue by AdixePL** [PluginBugs/Issues-ItemsAdder#3889]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

adixepl

### What happened?

I'm creating custom entity for my server. The problem is that eyes of my entity are flickering when rotating head (or entire model) for unknown reason. I've tried changing sizes, rotations, disabling animations but it didn't help. Eyes and eyebrows are bones, because I'm using this to do cool animations. Eyes are also 0.01 cubes in front of the head to prevent overlapping textures from flickering. Other bones of my model works great and I don't see this flickering. It looks like IA turns head and then eyes which causes visual delay.

### Steps to reproduce the issue

1. Create new entity (in the same way as [here](https://itemsadder.devs.beer/plugin-usage/adding-content/mobs/advanced-method)
2. Create new npc via Citizens
3. Run `/iaentity citizens <id> model <model>`
4. Run `/npc pathto here`
5. Watch how the entity's eyes flicker when it turns/moves its head

### Server version

Current Purpur Version: 1.21-2276-72ccfbd (MC: 1.21)

### ItemsAdder Version

4.0.2-alpha-test-3

### ProtocolLib Version

5.3.0-SNAPSHOT-726

### LoneLibs Version

1.0.56

### Full server log

https://mclo.gs/c8MYx4n

### Error (optional)

```shell
No errors found
```

### Screenshots/Videos (you can drag and drop files or paste links)

Video: https://github.com/user-attachments/assets/99027dd7-c2bb-45bb-ace9-ebff21552847
Model: https://github.com/user-attachments/files/16614750/model.zip

**Comment by LoneDev6** [comment]
This is z-fighting, common in all games.
Please make your cubes thicker and move them away from the surface of the head.
https://en.wikipedia.org/wiki/Z-fighting
