### ISSUE TITLE
[4.0.2-alpha-test-3] Armor generating is broken.

### ISSUE THREAD

**Issue by Pattanawaris** [PluginBugs/Issues-ItemsAdder#3896]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Armor 3rd person view displayed as normal leather armor with color

### Steps to reproduce the issue

1.just add any armor content
2.reload and gen the pack
3.apply the pack and you'll see that everything is normal except when wearing(3rd person) it's displayed as normal leather armor with color

### Server version

PAPER 1.21-126

### ItemsAdder Version

[4.0.2-alpha-test-3]

### ProtocolLib Version

5.3.0-726

### LoneLibs Version

1.0.56

### Error (optional)

```shell
no error
```

**Comment by PSYCHEER** [comment]
Hey! Before posting issue try to search on  Discord as solution was written in there!
I know that as I wrote it up!

# ARMORS ARE LEATHER 1.21
Hey everyone, I don't know all of you but surely you know of me
I wanted just to say you, when you'e using 1.21 instance of Minecraft and have custom armors AND you have a problems with it, please follow this tutorial
1. Open `config.yml` in your ItemsAdder folder in plugins folder
2. Search for `generate-custom-armors-textures:`
3. Enable `vanilla` and **DISABLE `vanilla_1_17` **
4. `/iareload` and `/iazip`
5. Enjoy your armor (shaderpacks are still not supported)
PS: when you keep vanilla_1_17 enabled it autodisable the vanilla, when you're new into IA and it's your first install, probably you have not the vanilla_1_17)

**Comment by Pattanawaris** [comment]
Done, but there's some of armor became Invisible when displayed on armorstand.
