### ISSUE TITLE
[Game Breaking] Furnace bug

### ISSUE THREAD

**Issue by petrkeram** [PluginBugs/Issues-ItemsAdder#3899]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

ID: 267774664372256768

### What happened?

Hello,
I have a problem with smelting. When I select an item to smelt and also choose the output, it doesn’t work. There’s a recipe in the green book next to the furnace that shows how to obtain this block, but nothing happens in the furnace. I’ve tried other materials as well, and interestingly, sometimes one of them randomly starts working (it doesn’t matter which item I put in, one worked once, but then stopped after a while).

Thank you for your help.

![Bug1](https://github.com/user-attachments/assets/f6605d63-5735-4ddb-baac-a8ab6e114ff7)
![Bug2](https://github.com/user-attachments/assets/eeafe9de-0855-4fbc-89e5-3649808fdcb4)
![Bug3](https://github.com/user-attachments/assets/d9fb276b-21e3-4331-9dee-024502fcdcac)

### Steps to reproduce the issue

.

### Server version

This server is running Paper version 1.21-127-master@4e6a2a1 (2024-08-07T12:50:10Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are 3 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21.1-DEV-ddf3df8 (MC: 1.21.1)

### ItemsAdder Version

4.0.2-alpha-test-3

### ProtocolLib Version

5.3.0-SNAPSHOT-726

### LoneLibs Version

1.0.56

### Error (optional)

```shell
There was none error in console.
```

**Comment by PSYCHEER** [comment]
Maybe a related issue #3937
