### ISSUE TITLE
Option to disable custom blocks completely in specific worlds

### ISSUE THREAD

**Issue by PGMCgit** [PluginBugs/Issues-ItemsAdder#3905]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

ca.exe

### Describe the solution you'd like

I am wondering if a whitelist option could be implemented so that I can say I want IA blocks to be generated in X,Y,Z worlds. 

### Is your feature request related to a problem?

This feature would (hopefully) remove the need for an ItemsAdder folder & region files in worlds not specified (like instanced worlds created by another plugin). 

### Describe alternatives you've considered

One alternative to a whitelist is to not touch world names with _# appended (such as world_0). Having this filter would save these instanced worlds from memory leaks and inevitable crashes.

**Comment by Andre601** [comment]
Not sure what your proposal is exactly.
World Populator already requires you to set the worlds where the custom blocks are generated.

https://itemsadder.devs.beer/plugin-usage/adding-content/worlds-populators

**Comment by PGMCgit** [comment]
I'm requesting a way to kindly tell IA to not touch worlds I don't want it to. Maybe a blacklist would be more clear?

**Comment by Andre601** [comment]
Okay. And in what way is ItemsAdder right now intefering with your worlds?
You mentioned files it sets in the world folder? Does this affect the worlds in any way? If not, why is it an issue for you?

**Comment by H0tKinsS** [comment]
> Okay. And in what way is ItemsAdder right now intefering with your worlds? You mentioned files it sets in the world folder? Does this affect the worlds in any way? If not, why is it an issue for you?

I have had problems with ItemsAdder not allowing to delete their files from external plugins temporary worlds, for example when i was using a Dungeon plugin where it creates and deletes a lot of worlds. A whitelist / blacklist with regex support would be really appreciated
