### ISSUE TITLE
Fix CraftItemStack cast to CustomItem due to misuse of the clone method and internal changes in the Spigot code

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#3907]
Sometimes I use CustomItem in the Spigot API instead of using generating the corresponding ItemStack, this causes the Spigot API to fail to convert it to CraftItemStack.

**Comment by Jsinco** [comment]
Begging for this update. Lots of my features using ItemsAdder rely on it's API which is broken because of this. Really don't want to have to migrate to Oraxen
