### ISSUE TITLE
Mipmap atlas issue

### ISSUE THREAD

**Issue by bruhhhwarrior** [PluginBugs/Issues-ItemsAdder#3910]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

Im getting Mipmap errors on the atlas file, I have checked all my textures and im sure its not one of the textures in my contents   folder. im not sure what happens but the atlas.png reduces my mipmap, also the fishing hook one i dont understand since i dont have any fishing hook texture or anything like that added to my pack. I tried using vanilla with no mods but sadly its still the same so i think its itemsadder.

```
[03:37:29] [Worker-Main-5/WARN]: Texture minecraft:entity/fishing_hook with size 8x8 limits mip level from 4 to 3
[03:37:29] [Worker-Main-5/WARN]: minecraft:textures/atlas/blocks.png: dropping miplevel from 4 to 3, because of minimum power of two: 8
```

### Steps to reproduce the issue

load my resource pack

### Server version

git-Purpur-2176 (MC: 1.20.4)

### ItemsAdder Version

3.6.4-release-3

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.55

### Full Server Log

https://mclo.gs/G0WjIBB

### Error (optional)

```shell
[03:37:29] [Worker-Main-5/WARN]: Texture minecraft:entity/fishing_hook with size 8x8 limits mip level from 4 to 3
[03:37:29] [Worker-Main-5/WARN]: minecraft:textures/atlas/blocks.png: dropping miplevel from 4 to 3, because of minimum power of two: 8
```
```


### Problematic items yml configuration file (optional)

_No response_

### Other files, you can drag and drop them here to upload. (optional)

https://lobfile.com/file/K5KbbXyy.zip my resource pack 

### Screenshots/Videos (you can drag and drop files or paste links)

_No response_

**Comment by LoneDev6** [comment]
For some reason you have this in your atlases folder.
![image](https://github.com/user-attachments/assets/40bec178-2e64-4ada-9b18-f74b50ef68b3)

You should not.
This is caused by merging of another resourcepack probably, not directly caused by ItemsAdder.

**Comment by ciliomine** [comment]
Is for model engine I have the same problem.
