### ISSUE TITLE
Being able to configure the spawn of a furniture

### ISSUE THREAD

**Issue by Wuason6x9** [PluginBugs/Issues-ItemsAdder#3913]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

wuason

### Describe the solution you'd like

CustomFurniture.spawn(String namespacedId, org.bukkit.block.Block blockLocation, double yaw, double pitch)
CustomFurniture.spawn(String namespacedId, org.bukkit.block.Block blockLocation, double yaw, double pitch, org.bukkit.Rotation rotation) (IF IS ITEMFRAME)

CustomFurniture.spawnPreciseNonSolid(String namespacedId, org.bukkit.Location location, double yaw, double pitch)
CustomFurniture.spawnPreciseNonSolid(String namespacedId, org.bukkit.Location location, double yaw, double pitch, org.bukkit.Rotation rotation) (IF IS ITEMFRAME)

add that or add a method to modify the entity before it is spawned

### Is your feature request related to a problem?

It is related to a problem I have that I need to spawn with a certain rotation and currently I can only make it rotate once spawned then it clearly looks like it rotates for a moment and it is very ugly it needs to be modified the rotation before being spawned

### Describe alternatives you've considered

My current alternative is to modify these things once spawned and it's very ugly as it looks

**Comment by LoneDev6** [comment]
use the consumer argument to run your edits.
```java
    @Nullable
    public static CustomEntity spawn(String namespacedId,
                                     Location location,
                                     List<Player> viewers,
                                     boolean frustumCulling,
                                     @Nullable Consumer<LivingEntity> function)
```

This should work just fine.
Let me know.
