### ISSUE TITLE
Loading screen is not working on 1.19.4

### ISSUE THREAD

**Issue by Hyadens** [PluginBugs/Issues-ItemsAdder#3931]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

hyaden_

### What happened?

I have a server version 1.19.4. I using Optifine. I am trying to set up a loading screen but it is not working. 

When I log in with ViaVersion at version 1.20.1, the loading screen appears. However, it does not work at all in the base version. Can you help me?

(I followed everything written in the tutorial) (color is working btw)

### Steps to reproduce the issue

![image](https://github.com/user-attachments/assets/d95461cd-8f41-46c4-ad8a-dff8aaad0a4f)

### Server version

git-Purpur-1985 (MC: 1.19.4)

### ItemsAdder Version

Itemsadder version 3.6.3-beta-13

### ProtocolLib Version

ProtocolLib version 5.1.0

### LoneLibs Version

LoneLibs version 1.0.45

### Full Server Log

https://mclo.gs/QHrkJVm

**Comment by Andre601** [comment]
Which tutorial did you follow exactly? Please provide the steps you took to set up the screen.

**Comment by Hyadens** [comment]
https://itemsadder.devs.beer/plugin-usage/adding-content/optifine-only-features/loading-screen 

Tutorial is there. I followed 1.16.+ section

**Comment by Hyadens** [comment]
I updated Itemsadder (version 3.6.4-release-3), latest LoneLibs, and latest ProtocolLib. But still not working.

**Comment by Andre601** [comment]
> https://itemsadder.devs.beer/plugin-usage/adding-content/optifine-only-features/loading-screen
> 
> Tutorial from here. I followed 1.16.+ section

There is a big red infobox at the very top you should read, as it clearly states: **Please don't ask support about Optifine features. Thanks!**

So because of that am I closing this issue now as this is not a direct feature of IA and therefore not covered by this Issue Tracker. You may have more luck joining the discord and ask there.

**Comment by Hyadens** [comment]
If the problem was related to Optifine, it would not work in version 1.20.1 either.

screenshot on 1.20.1 (with ViaVersion) still base version 1.19.4
![image](https://github.com/user-attachments/assets/0039e5cd-59cd-4277-86e8-817d67de02f6)
