### ISSUE TITLE
Slimefun Head Turns to textureless head when placed 

### ISSUE THREAD

**Issue by XulaPize** [PluginBugs/Issues-ItemsAdder#3939]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

xulapize (iXula)

### What happened?

i know this issue has been reported and there are a fix suggested in the github (#1606 )
but for some reason when i try to disable anything as said in that fix (emote =false , or disable any other under custom entitie) 
and rezip the rp with /iazip , the issue still remains and insted all my player and npc head will turn 90 degree! 
i'll attach a few SS to show the issue and ia version! (i've tried to upgrade the ia but the latest version doesn't support 1.20.4)

### Steps to reproduce the issue

already exist in #1606 

### Server version

Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)

### ItemsAdder Version

![2024-08-28_15 12 28](https://github.com/user-attachments/assets/acba3175-28c2-4776-80c8-f45531a1c238)

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.54

### Full Server Log

https://mclo.gs/vDD1fik

### Other files, you can drag and drop them here to upload. (optional)

![2024-08-28_15 06 39](https://github.com/user-attachments/assets/971d659e-e596-4cce-ada0-a1e5bde34ce5)
![2024-08-28_15 06 58](https://github.com/user-attachments/assets/cc4417f9-2706-4599-8523-c8eaee6651a5)

**Comment by LoneDev6** [comment]
You have some leftovers shaders in your resourcepack files (for some reason, probably copied and pasted manually) or you're not applying the new pack for some reason.
This is the only cause, if you disable emotes and you run /iazip they will be disabled completely on normal situations.

**Comment by LoneDev6** [comment]
I suspect there is some files manually added in the contents folder which is merged automatically on `/iazip`.
Probably of some other plugin or manual pack added some time ago by your admins.
What you have to check is if you can find a `shaders` folder in your contents folder, then delete it (backup it just in case), and run `/iazip`

**Comment by XulaPize** [comment]
awsome 
thanks
