### ISSUE TITLE
[Suggestion] Adding Collision & Improving Interaction

### ISSUE THREAD

**Issue by Makkief** [PluginBugs/Issues-ItemsAdder#394]
![image](https://user-images.githubusercontent.com/64651364/94115262-6dd47600-fe84-11ea-8bdc-c5301a30ae40.png)

[Feature Request]
I think it would be great if I can fill my furniture models(just for fixed rotation)
with Barrier blocks and people can interact(use, break...) on them.

for example,
The model above is the vending machine I made.
The size of model is 2x1x3. I want to fill the space
with Barrier blocks.

[The reason why I need this Features]
1. I don't want people walk through some of my models.
2. People are easily confused because they don't know where to click to interact furnitures.(They have to click the place where Armorstand stands.)

**Comment by ArgonGaming** [comment]
This would be a very nice feature. I've seen it done before by members of LoneDev's discord, and the possibilities with this would be endless. Would love to see it added!

**Comment by LoneDev6** [comment]
Implemented some months ago
https://github.com/PluginBugs/Issues-ItemsAdder/issues/666#issuecomment-857972735
