### ISSUE TITLE
Add LoneLibs to jitpack

### ISSUE THREAD

**Issue by andrewkm** [PluginBugs/Issues-ItemsAdder#3950]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

Ever since commits:
- https://github.com/LoneDev6/API-ItemsAdder/commit/3a4421726fb6ed0e781eda65dfe245aebdf9b042
- https://github.com/LoneDev6/API-ItemsAdder/commit/19a65f4ff81e99e6bbae361199c92bf239778fd7

I'm no longer able to build the repo:
`[ERROR] Failed to execute goal on project api-itemsadder: Could not resolve dependencies for project dev.lone:api-itemsadder:jar:4.0.2-alpha-test-8: Could not find artifact dev.lone:LoneLibs:jar:1.0.57 in spigot-repo (https://hub.spigotmc.org/nexus/content/repositories/snapshots/) -> [Help 1]`

### Steps to reproduce the issue

Build latest.

### Server version

N/A

### ItemsAdder Version

N/A

### ProtocolLib Version

N/A

### LoneLibs Version

N/A

### Full Server Log

N/A

**Comment by andrewkm** [comment]
We build via Jenkins straight from the public repository.

**Comment by Andre601** [comment]
And how does this change anything regarding my suggested fix?
Your Jenkins has to pull the code to build from somewhere, so change that somewhere?

**Comment by andrewkm** [comment]
I'm aware this is a potential solution, but it doesn't assist us, I'll wait for a proper fix from the developer.

**Comment by LoneDev6** [comment]
Use my own repository.
I just deployed the LoneLibs API for you, should work fine now.

https://github.com/LoneDev6/API-ItemsAdder?tab=readme-ov-file#lonelibs

I currently don't support jitpack for LoneLibs.

**Comment by andrewkm** [comment]
Thanks, this has resolved the issue. :)
