### ISSUE TITLE
show_item_durability config keeps resetting

### ISSUE THREAD

**Issue by lpxoainse** [PluginBugs/Issues-ItemsAdder#3954]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

Changing IA config.yml 
```
show_item_durability:
    in_ia_menu: true
    in_inventory: false <<<< to true
```
then /iareload or restart the server, it goes back to false everytime.

### Steps to reproduce the issue

1. open IA config.yml in text editor
2. change the value to true
3. save the file
4. restart server or /iareload

### Server version

This server is running Paper version 1.21.1-52-master@e08e667 (2024-08-26T18:02:06Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 4.0.2-alpha-test-7

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-726

### LoneLibs Version

LoneLibs version 1.0.57

### Full Server Log

no errors

**Comment by Andre601** [comment]
Please share your `latest.log` through https://mclo.gs as it help us getting all the necessary info required to solving this issue.

**Comment by lpxoainse** [comment]
I wasn't aware this issue gotten a reply

https://mclo.gs/QqApo9x

here's a video showing it resets every single time and of course the img lore not working also still there from my other reported issue:

https://github.com/user-attachments/assets/1d8badc1-4921-4954-ab35-eb6fbaa9de0a
