### ISSUE TITLE
Tripwires aren't working properly

### ISSUE THREAD

**Issue by svaningelgem** [PluginBugs/Issues-ItemsAdder#3957]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

Sensei_Orange

### What happened?

We saw that a string duper farm wasn't working, and it was working perfectly on other servers. So we investigated:
- spawn a new 1.21 paper server
- create the string farm
- **everything works as normal**
- stop the server
- add itemsadder & its dependencies
- start the server
- *the string farm is STILL working properly!*
- break the string
- add the string again
- the string breaks immediately

I checked other tickets and was also playing around with custom-wire-false, but then tripwires simply didn't work at all (it gave a message about tripwires being disabled on the server).

### Steps to reproduce the issue

See above

### Server version

This server is running Paper version 1.21-130-master@b1b5d4c (2024-08-10T10:02:42Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### ItemsAdder Version

version 4.0.2-alpha-test-7

### ProtocolLib Version

version 5.3.0-SNAPSHOT-726

### LoneLibs Version

LoneLibs version 1.0.57

### Full Server Log

https://mclo.gs/c09jwbx

### Screenshots/Videos (you can drag and drop files or paste links)

**Without IA:**
*setting up the string*
![image](https://github.com/user-attachments/assets/f6787eab-e59c-487e-b476-a76fc0daceae)
![image](https://github.com/user-attachments/assets/de3cfb85-6757-416d-9f92-add0467f8783)
*running the farm*
![image](https://github.com/user-attachments/assets/2e8ed57d-1cd2-48f0-9ca2-17929c756367)

**With IA:**
![image](https://github.com/user-attachments/assets/000add09-5f1f-40bc-8fd4-364f388cc7ac)
![image](https://github.com/user-attachments/assets/be4883c4-1ceb-424d-8aca-88b3a7b6b77d)
**running the farm**
![image](https://github.com/user-attachments/assets/5f70f502-ceb2-4d90-9ba5-dc3f45862cf4)

**Comment by LoneDev6** [comment]
This is strange as the plugin shouldn't enable custom wire blocks if you disable them in config.yml
```yml
  custom:
    note: true
    mushroom: true
    chorus: true
    wire: false # <----
    fire: false
```

**Comment by virgil698** [comment]
This is also the case with me, and it affects the players' brush operation

![988978e26c609c450c49396ddaaed2c8](https://github.com/user-attachments/assets/553c9e49-0bfc-4824-b683-c78f2f15fe7a)

![7839b83e320eccd8096239131584dfc1](https://github.com/user-attachments/assets/e61838c3-f4d1-42d0-af2b-aff1f58ff262)

When the wire part of config.yml is set to true, the trip hook works abnormally, as shown below

![a272608c4c6ae47448b74eff280868d5](https://github.com/user-attachments/assets/9acb8b12-3bc2-4aef-a84b-f734ed2c8280)

My server version:

![image](https://github.com/user-attachments/assets/de62f0b1-903b-4ad1-a033-feffeb8c0fc2)

![image](https://github.com/user-attachments/assets/173434a1-2788-4375-941e-69d248da9ad4)

**Comment by LoneDev6** [comment]
disable tripwire from config.yml, you can't safely use tripwires while using custom blocks based on tripwires.
