### ISSUE TITLE
Our rp was hacked through a certain "recaf 3".

### ISSUE THREAD

**Issue by Taks1k** [PluginBugs/Issues-ItemsAdder#3959]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

the person packed the file from minecraft\server-resource-packs into a zip archive and threw it into the program. He gained access to our RP

### Steps to reproduce the issue

-

### Server version

-

### ItemsAdder Version

-

### ProtocolLib Version

-

### LoneLibs Version

-

### Full Server Log

-

### Error (optional)

```shell
-
```

### Problematic items yml configuration file (optional)

```yaml
-
```

**Comment by Taks1k** [comment]
Is there a way to download RP via LobFile?

**Comment by Taks1k** [comment]
If you download the RP via LobFile, will it not work?

**Comment by DxrkCat** [comment]
> ### Terms
> 
>     * [x]  I'm using the very latest version of ItemsAdder and its dependencies.
> 
>     * [x]  I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
> 
>     * [x]  I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
> 
>     * [x]  I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
> 
>     * [x]  I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
> 
>     * [x]  I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.
> 
> 
> ### Discord Username (optional)
> 
> _No response_
> ### What happened?
> 
> the person packed the file from minecraft\server-resource-packs into a zip archive and threw it into the program. He gained access to our RP
> ### Steps to reproduce the issue
> 
> 
> ### Server version
> 
> 
> ### ItemsAdder Version
> 
> 
> ### ProtocolLib Version
> 
> 
> ### LoneLibs Version
> 
> 
> ### Full Server Log
> 
> 
> ### Error (optional)
> 
> ```shell
> -
> ```
> 
> ### Problematic items yml configuration file (optional)
> 
> ```yaml
> -
> ```
> 
> ### Other files, you can drag and drop them here to upload. (optional)
> 
> _No response_
> ### Screenshots/Videos (you can drag and drop files or paste links)
> 
> _No response_

There is no way you can protect the resourcepack without harming the client. If the client can read it, then any protection can be removed. If you don't like it, you should switch to Bedrock Edition.

**Comment by LoneDev6** [comment]
https://itemsadder.devs.beer/plugin-usage/resourcepack-hosting/protect-resourcepack-from-unzip#disclaimer
