### ISSUE TITLE
1.21 Crafter Crafter Removes item and not durability

### ISSUE THREAD

**Issue by Minzilein2003** [PluginBugs/Issues-ItemsAdder#3978]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

jkobs

### What happened?

If you craft an Recipe with Crafter where the durability of an Item should reduce, the item disappear completely.

### Steps to reproduce the issue

1. Place Crafter
2. Put Items in Crafter
3. Give Crafter Redstone
4. Item disappear

### Server version

This server is running Paper version 1.21.1-52-master@e08e667 (2024-08-26T18:02:06Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are 5 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-497 (MC: 1.20.4)

### ItemsAdder Version

4.0.2-alpha-test-7

### ProtocolLib Version

5.3.0-SNAPSHOT-726

### LoneLibs Version

1.0.57

### Full Server Log

No Errors in Console

**Comment by Minzilein2003** [comment]
![image](https://github.com/user-attachments/assets/bf5f3396-639f-4105-9ce0-eea67362e206)
![image](https://github.com/user-attachments/assets/7bce0f23-db85-493b-8b7c-01c63a60b398)
![image](https://github.com/user-attachments/assets/2f37db53-e971-4abf-88b2-1f61f5277a59)
![image](https://github.com/user-attachments/assets/52b18d3d-f4b7-49d0-af6a-24a5446d7153)

**Comment by LoneDev6** [comment]
Crafter will be disabled for custom items because it's flawed.
The Crafter doesn't allow users to select which recipe they want to use, this is an issue because people can't select the correct output item in case some recipes ingredients overlap other recipes.
In the future I will enable custom recipes in the Crafter if Mojang adds the book icon also in the Crafter GUI, which probably will happen as the feature is marked as "experiemental".
