### ISSUE TITLE
Add options for custom Item component values

### ISSUE THREAD

**Issue by killertuling** [PluginBugs/Issues-ItemsAdder#3981]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Adds the ability to define the value of component for an item.
For example:
food using a food component instead of an itemsadder action, it can be compatible with mods such as apple skin..
and most importantly, there are a lot of new features that can be implemented through it

### Is your feature request related to a problem?

yes

### Describe alternatives you've considered

No alternative

**Comment by LoneDev6** [comment]
Food already uses the food component of 1.20.5.
