### ISSUE TITLE
Backport - New setting to stop emotes shaders from being put in the resourcepack, but keep emotes enabled

### ISSUE THREAD

**Issue by EyatMC** [PluginBugs/Issues-ItemsAdder#3987]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

https://github.com/PluginBugs/Issues-ItemsAdder/issues/3961
Please update the new options so they can be used in version 1.20.1 (v3)

`extract_emotes_shaders: true`

### Is your feature request related to a problem?

.

### Describe alternatives you've considered

Currently, the new features are only available in V4. However, they should also be applied to the last version that supports V3

**Comment by Andre601** [comment]
v3 is considered legacy at this point and you shouldn't expect it receiving anything other than bug fixes at this point.
There is barely any reason to not update to 1.21.1 at this point outside of IA v4 being alpha.

**Comment by EyatMC** [comment]
The reason for staying with the previous version is because there is a valid reason for it. Also, the feature I requested does not require complex coding, and I believe my request to add the feature only to the last v3 version is a reasonable compromise.

**Comment by LoneDev6** [comment]
Will be worked on as soon as I can, thanks.
