### ISSUE TITLE
The cosmetics bundle with item adder is not working.

### ISSUE THREAD

**Issue by Zeruxe** [PluginBugs/Issues-ItemsAdder#3999]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

Zeruxe 

### What happened?

Im trying to get the bundle in the discord with cosmetics and item adder but thel link is expired, I also want to you ask you something, can you message me on discord? 

### Steps to reproduce the issue

s

### Server version

s

### ItemsAdder Version

s

### ProtocolLib Version

s

### LoneLibs Version

s

### Full Server Log

s

**Comment by Andre601** [comment]
The issue tracker is reserved for actual issues and feature requests with ItemsAdder and not for requesting to get in touch with the dev. The Discord server or Forums are more suited for such things.
