### ISSUE TITLE
Sounds cannot work in file format of 'contents/<namespace>'

### ISSUE THREAD

**Issue by killertuling** [PluginBugs/Issues-ItemsAdder#4010]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

it can't work , vanilla command "playsounds" can't completion new sounds.

can't work:
![image](https://github.com/user-attachments/assets/3a7b1f6c-d6a6-4b91-b677-0e1356b600ee)

will work:
![image](https://github.com/user-attachments/assets/023f13de-d9d9-4c5c-a011-f53c3b2f402d)

### Steps to reproduce the issue

image

### Server version

This server is running Paper version 1.21.1-52-master@e08e667 (2024-08-26T18:02:06Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are 25 version(s) behind
Download the new version at: https://papermc.io/downloads/paper

### ItemsAdder Version

4.0.2-beta-release-10

### ProtocolLib Version

[09:51:04 INFO]: ProtocolLib version 5.3.0-SNAPSHOT-726
[09:51:04 INFO]: Provides read/write access to the Minecraft protocol.
[09:51:04 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[09:51:18 INFO]: LoneLibs version 1.0.57
[09:51:18 INFO]: Collection of libs used by my plugins
[09:51:18 INFO]: Authors: LoneDev and others

### Full Server Log

null

### Error (optional)

```shell
null
```

**Comment by Andre601** [comment]
1. Provide a latest.log via mclo.gs. we need them.
2. How does the sounds.json actually looks like?

**Comment by killertuling** [comment]
> 1. Provide a latest.log via mclo.gs. we need them.
> 2. How does the sounds.json actually looks like?

1. https://mclo.gs/ldvWuSX  
I don't think it's helpful because there were no error.

2. I am not a novice in resourcepack, I know what I am doing, sounds.json is correct, it can work in the vanilla resource pack
What I mean is, if I place the files like this(Folders structure method 5), IA won't package sounds.json correctly into the Resourcepack.
But this file format is supported by the format you wrote on the ItemAdder wiki, which is undoubtedly an error, and you can easily reproduce it.


![image](https://github.com/user-attachments/assets/1a21cefe-d4e6-4ef3-b02d-0e8ddb5cba00)
![image](https://github.com/user-attachments/assets/edc54e09-fa5d-423e-b6e1-2c5facbcadf7)
![image](https://github.com/user-attachments/assets/445330b9-e3e8-48c3-ab17-3ba22970ceb7)


will work , it correctly into the Resourcepack:
![image](https://github.com/user-attachments/assets/d0fb9699-c5f7-4428-9e59-6853c271c39f)

**Comment by LoneDev6** [comment]
> vanilla command "playsounds" can't completion new sounds.

This is normal, only client can autocomplete this command as the server has no idea about the custom sounds as it can't install the pack itself.

I made /iaplaysound for this reason, to get autocompletition of sounds names in console.
