### ISSUE TITLE
Recipes overlaping between different materials

### ISSUE THREAD

**Issue by ElTuna** [PluginBugs/Issues-ItemsAdder#4011]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

eltuna (ID: 620734023328595979)

### What happened?

Crafting tables recipes are overlaping no matter if materials don't match.

(Sorry if I send images here, it's just I think this is the only way you can understand it fast.)

For example:
Every crafting with pattern:
```
"XAX"
"XAX"
"XBX"
```
Where ingredients are:
        A: `ametrine_pack:ametrine_block`
        B: `fossil_pack:big_stick`
are heading to ametrine_sword... No matter if the "A" item isn't ametrine_block,

This is the correct ametrine_sword crafting: 
![image](https://github.com/user-attachments/assets/4ab83559-af9c-490a-9495-5df8a60958cb)

These are overlaped craftings:
![image](https://github.com/user-attachments/assets/774ed7de-8f67-4344-8167-9735eadd732a)
![image](https://github.com/user-attachments/assets/df057d10-a160-4d32-8ed5-5bb54bc30e3c)
![image](https://github.com/user-attachments/assets/95150aba-b7a7-46ad-93ec-cf262561f00b)

And craftings with pattern:
```
"XAX"
"AAA"
"XBX"
```
are heading to dark_matter.... even if the "A" item is ametrine_block...

This is the correct dark_matter_sword crafting:
![image](https://github.com/user-attachments/assets/93022693-1cee-4f8c-b268-1a79a5e7bfee)

These are overlaped craftings:
![image](https://github.com/user-attachments/assets/25c6a47c-d493-44d9-9951-8e7a4eca02b4)
![image](https://github.com/user-attachments/assets/0694f4bf-5a03-4853-a08c-9a881a255622)
![image](https://github.com/user-attachments/assets/d510a0f0-0dd7-4c7b-bb75-8bcd88e0d19e)

But this is just an example...  no matter what material I use... some materials are overlaping and take priority when crafting.
In first pattern the ametrine takes priority.
And in second the dark_matter does.

but same overlap happens with other tools and armors... (shown in screenshots)

This is the correct crafting for ametrine armor:
![image](https://github.com/user-attachments/assets/0a6aa2be-74fd-4c2d-8f46-163fe38ea433)
But if I use dark_matter... it also gives ametrine armor 
![image](https://github.com/user-attachments/assets/03977783-e168-457b-b736-da655fff5585)
And thats not all... if I use dark_emerald it gives ametrino armor aswell
![image](https://github.com/user-attachments/assets/515bc91c-dfba-4a2b-b5a7-e82b1af878c6)

And last issue i'm having is with fossil_pack recipes:
I have this `recipes.yml`
```yaml
recipes:
  crafting_table:
    big_stick:
      pattern:
        - "XAX"
        - "XAX"
        - "XXX"
      shapeless: true
      result:
        item: fossil_pack:big_stick
        amount: 1
      ingredients:
        A: fossil_pack:broken_big_stick
```
but I'm getting this in the crafting table: (no matter the slot in the crafting table)
- 1 broken_stick giving a big_stick
![image](https://github.com/user-attachments/assets/03fa122d-1f31-4de0-bb3e-b3cf40e15826)
- 1 big_stick giving a big_stick
![image](https://github.com/user-attachments/assets/cf91d3ba-6938-4103-a503-346802964efe)
- And this is the crafting in `recipes.yml`... gives nothing:
![image](https://github.com/user-attachments/assets/32bb2da2-192e-4399-824a-b7548f317cfe)

### Steps to reproduce the issue

1. I think just use the zip I sent.

### Server version

This server is running Paper version 1.21.1-81-master@13a2395 (2024-09-15T20:39:09Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 4.0.2-beta-release-10

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-726

### LoneLibs Version

LoneLibs version 1.0.58

### Full Server Log

https://mclo.gs/HnyjKPw

### Other files, you can drag and drop them here to upload. (optional)

[__.zip](https://github.com/user-attachments/files/17010671/__.zip)

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/user-attachments/assets/583c1149-dd63-430e-a9dd-88f87af8f6ef)
![image](https://github.com/user-attachments/assets/64213a01-2e8f-485d-b05d-d059bdeb56d2)
![image](https://github.com/user-attachments/assets/757998d9-a88d-4b21-9060-690c203dbe76)
![image](https://github.com/user-attachments/assets/a33c34e7-ebcb-49e2-9b0c-352ba1788161)
![image](https://github.com/user-attachments/assets/93de7951-29e8-4f41-bb35-8e6285d0b121)
![image](https://github.com/user-attachments/assets/b886657c-ac90-40d4-aa61-32897440e507)
![image](https://github.com/user-attachments/assets/9f905451-2109-40eb-9565-c73b900d5aea)
![image](https://github.com/user-attachments/assets/e68ca085-f157-4fcf-9545-197435c1fca7)
![image](https://github.com/user-attachments/assets/a029ad91-a8d3-4ec4-9573-f9e9cad0d9bd)
![image](https://github.com/user-attachments/assets/29eabf5e-6894-4620-8c88-95c473028ed4)
![image](https://github.com/user-attachments/assets/11db36a7-173b-4f99-89f2-d445e21e16d3)
![image](https://github.com/user-attachments/assets/a60efd69-1d7a-46eb-bd38-5bb41dac28c4)

**Comment by ElTuna** [comment]
I've been testing downgrades... and the problem doesn't happen in `4.0.2-alpha-test-7`.
![image](https://github.com/user-attachments/assets/3696d88a-11eb-4d58-925f-5ff3bbc3393b)
![image](https://github.com/user-attachments/assets/6f7ff51b-d251-4810-b8f6-628da50dfe7d)

This is also correct because this crafting doesnt exist:
![image](https://github.com/user-attachments/assets/3b48acf0-0cb4-450f-87fb-67eca418770d)
This is its correct crafting:
![image](https://github.com/user-attachments/assets/be56b51e-e073-4c2d-9694-9c360b8ed8bb)
In fact something changed in new versions that affected recipes:
In old version this recipe is correct and not overlaped:
![image](https://github.com/user-attachments/assets/64350987-ec5c-49fb-b648-29369b4e47b4)

**Comment by LoneDev6** [comment]
Will be checked, probably something changed again in the NMS recipes registration code.
