### ISSUE TITLE
AdvancedSlime support broke due to API changes

### ISSUE THREAD

**Issue by LuluxClient** [PluginBugs/Issues-ItemsAdder#4012]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

xdLulux

### What happened?

AdvancedSlimePaper https://github.com/InfernalSuite/AdvancedSlimePaper has made an update to their API, so their hook no longer works. They should follow the information provided here: Migrating the API https://infernalsuite.com/docs/asp/migrating

### Steps to reproduce the issue

1. use the latest of AdvancedslimePaper
2. Hook no longer works
3. sadness :(

### Server version

[20:11:56 INFO]: Checking version, please wait...
[20:11:57 INFO]: This server is running PaperSquid version 1.21.1-DEV-master@b858544 (2024-09-16T16:41:42Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### ItemsAdder Version

4.0.2-beta-release-10

### ProtocolLib Version

5.3.0-SNAPSHOT-726

### LoneLibs Version

LoneLibs version 1.0.58

### Full Server Log

private

### Error (optional)

```shell
[17:19:37 WARN]: Hey! It seems like you're trying to access the old SlimeWorldManager API.
Since 1.21.0 the API is now provided by the server directly.
See the documentation at https://infernalsuite.com/docs/asp/migrating for more information.
```

### Problematic items yml configuration file (optional)

```yaml
none
```

### Other files, you can drag and drop them here to upload. (optional)

none

### Screenshots/Videos (you can drag and drop files or paste links)

Make sure to follow this: https://infernalsuite.com/docs/asp/migrating

**Comment by NoHere32** [comment]
I also have this problem and you can't use both with the latest versions...
It might be a good idea to update it for the next beta? <4.0.3-beta_release-1>

NoHere
