### ISSUE TITLE
AbstractMethodError: Receiver class ia.m.jC does not define or inherit an implementation of the resolved method 'abstract boolean acceptsSuccess()' of interface net.minecraft.commands.CommandSource.

### ISSUE THREAD

**Issue by ciliomine** [PluginBugs/Issues-ItemsAdder#4013]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

The item work but it spam that on console: 
https://pastebin.com/QgwyQ8eG

### Steps to reproduce the issue

`  cocacola:
    display_name: '&cCocacola'
    resource:
      material: POTION
      generate: false
      model_path: snaks/cocacola
    durability:
      usages: 4
    events:
      interact:
        right:
          execute_commands:
            the_first_command:
              command: execute at {player} run playsound minecraft:bebidas ambient {player} 
              as_console: true
          feed:
            amount: 2
            saturation: 0.7
          decrement_usages:
            amount: 1
          shoot_particle:
            name: "FALLING_DRIPSTONE_WATER"
            distance: 1`

### Server version

pufferfish-paperclip-1.21.1-R0.1-SNAPSHOT-mojmap

### ItemsAdder Version

ItemsAdder version 4.0.2-beta-release-10

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-726

### LoneLibs Version

LoneLibs version 1.0.58

### Full Server Log

https://pastebin.com/QgwyQ8eG

**Comment by nico721GD** [comment]
personally have the same problem, but the commands straight up dont work, error code at https://mclo.gs/c1MD9Sp, running the same version. hope it can help figure out the source of the problem

**Comment by Solemadd** [comment]
Hi, I got the same problem but with the command actions, and those don't work at all
So I'm unable to proceed requirements checking for now :/

I tried with the config of the test_flow_setblock to be sure that it wasn't a config problem and still not working.
