### ISSUE TITLE
Recipes overlaping between different materials - #4011 persists in latest IA(release-11)

### ISSUE THREAD

**Issue by jeffry1829** [PluginBugs/Issues-ItemsAdder#4015]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

jeffry1829

### What happened?

The underlying material for IA item is iron_ingot, and then I can use that to create iron block

btw, it's fine in IA alpha-7

### Steps to reproduce the issue

Use iasurvival, and obtain cassiterite_fragment, put 9 of it in the crafting table.

### Server version

Current Purpur Version: 1.21.1-2305-fdfc12e (MC: 1.21.1)*

### ItemsAdder Version

4.0.2-beta-release-11

### ProtocolLib Version

5.3.0-SNAPSHOT-726

### LoneLibs Version

1.0.58

### Full Server Log

https://mclo.gs/vT0duuU

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/user-attachments/assets/99dc0f20-cc3f-4ce7-864d-a398f7dbee98)

**Comment by LoneDev6** [comment]
Can you test the configs of #4011 and let me know if you can still reproduce the issue?
Thanks

**Comment by jeffry1829** [comment]
> Can you test the configs of #4011 and let me know if you can still reproduce the issue? Thanks

Thank you for the reply! That didn't happen in #4011 pack, maybe because I'm still using old folder structure?
I'm sorry, but it's kinda hard for me to migrate from old structure to `contents` structure, because even if I handled folder structure correctly, there're still namespace problems(many .png not found)

**Comment by jeffry1829** [comment]
Also, there're problems that existing items disappear when I use new default pack

**Comment by jeffry1829** [comment]
Seems like it's not due to old itempack

I use latest default pack, and the same recipe still don't work

**Comment by LoneDev6** [comment]
Thanks for the info, I'll make some more tests
