### ISSUE TITLE
iaentity summon doesnt work with ~ ~ ~ coordonates or though console

### ISSUE THREAD

**Issue by nico721GD** [PluginBugs/Issues-ItemsAdder#4035]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

vha. (with the .)

### What happened?

trying to summon a custom entity with the command /iaentity summon [entity] ~ ~ ~ and it simply doesnt summon anything, just gives the standard iaentity error message with possible commands. 

### Steps to reproduce the issue

/iaentity summon [entity] ~ ~ ~
WILL work with specified coordonates like /iaentity summon [entity] 50 40 90 but not with ~ ~ ~
in the video linked below you can also see that the command though the console doesnt work with or without precise coordonates either, doesnt spawn anything

### Server version

this server is running Paper version 1.21.1-83-master@2aaf436 

### ItemsAdder Version

v4.0.2-beta-release-12

### ProtocolLib Version

5.3.0-SNAPSHOT-726

### LoneLibs Version

1.0.57

### Full Server Log

https://mclo.gs/sPsLVzy

**Comment by nico721GD** [comment]
https://youtu.be/1sV8l0Q9swU didnt link the video im stupid

**Comment by LoneDev6** [comment]
You can already spawn the entity on the current location without specifying any coordinate.
`/iaentity summon cosmetics:amogus`.

Anyway console don't have a location so makes no sense to run ~ ~ ~ from console.

**Comment by LoneDev6** [comment]
Can you try this plugin?

**Comment by nico721GD** [comment]
@LoneDev6 dont know if part of the message was missing, but i updated the itemadder version on the server + lonelibs + protolib as said on the page, and the problem is still here.
the simplest way to recreate this problem is this command in a command block : execute at (player) run iaentity summon (entity) ~ ~ ~ world
simply replacing the ~ ~ ~ with exact coodonates will works, showing that it is clearly a bug that it doesnt work with ~ ~ ~

i really like your plugin, but im fully stuck in one of my biggest minigame coding project just because of this bug specificly for now months, so i really would need you to fix it

**Comment by nico721GD** [comment]
@LoneDev6 it works for me ! only thought the console but thats what i needed, it indeed fixed it so thanks !

**Comment by nico721GD** [comment]
@LoneDev6 nope didnt worked, still the same error message (if you received a notif saying it worked i had missunderstood something)

**Comment by nico721GD** [comment]
@LoneDev6 update again, managed to make it work though this plugin, thanks !
