### ISSUE TITLE
1.21 - Crafters permissions and custom items

### ISSUE THREAD

**Issue by Solemadd** [PluginBugs/Issues-ItemsAdder#4041]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

Hi, 
Crafters don't take in charge custom items in their craft. 
So it's actually possible to craft custom items with vanilla items (screenshots underneath)

### Steps to reproduce the issue

1. Create a custom craft that uses custom items
2. Make the recipe pattern in a crafter with the vanilla items used in the config
3. Press the button to craft

### Server version

This server is running UniverseSpigot version 1.21.1-DEV-ver/1.21.1@077c3a9 (2024-10-01T21:31:07Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
Universe-1.21.1-DEV-077c3a9 (MC: 1.21.1)

### ItemsAdder Version

4.0.2-beta-release-12

### ProtocolLib Version

5.3.0-SNAPSHOT-732

### LoneLibs Version

1.0.59

### Full Server Log

Don't have acess right now, I'll send it whenever I can if necessary

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/user-attachments/assets/034d5332-3322-40dd-84ed-892380ed4515)
![image](https://github.com/user-attachments/assets/8e8491b0-03b9-4cc8-97c9-ff6e234a18f9)
![image](https://github.com/user-attachments/assets/a9e480e9-19fc-4cf9-9508-873cd7bb79ff)

**Comment by Zekariaa** [comment]
Hello, same problem , is it normal?

**Comment by LoneDev6** [comment]
Crafter will be disabled for custom items because it's flawed.
The Crafter doesn't allow users to select which recipe they want to use, this is an issue because people can't select the correct output item in case some recipes ingredients overlap other recipes.
In the future I will enable custom recipes in the Crafter if Mojang adds the book icon also in the Crafter GUI, which probably will happen as the feature is marked as "experiemental".
