### ISSUE TITLE
Default IAEntities, Citizens models and MythicMobs models disappearing

### ISSUE THREAD

**Issue by slemmannen** [PluginBugs/Issues-ItemsAdder#4043]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

slemmannen

### What happened?

When entering and exiting the simulation distance of IAEntities in them they sometimes disappear. This happens with ItemsAdder entities. The same thing happens if you try to use Itemsadder entities with Citizens or MythicMobs. 

I have tested this on multiple servers, different computers, different custom models, minecraft versions and it happens everywhere. If you do /iareload everything appears again.

This looks like the same issue as #3369 and #3350

_Love the plugin! Have been using it for over 500 hours now. Thanks for any help!_

### Steps to reproduce the issue

- Spawn a IAEntity
- Fly or walk away
- The models go invisible

See the video down below on how to reproduce. I did it on a fresh server.

### Server version

This server is running Paper version 1.21.1-119-master@7cd4f2c (2024-10-03T15:19:34Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### ItemsAdder Version

4.0.2-beta-release-12

### ProtocolLib Version

5.3.0-SNAPSHOT-732

### LoneLibs Version

1.0.59

### Full Server Log

https://mclo.gs/A2S8yhn

### Screenshots/Videos (you can drag and drop files or paste links)

https://github.com/user-attachments/assets/6f2752d5-a14c-4d87-a7bb-eb2f36ae7e04

**Comment by PSYCHEER** [comment]
That's not a bug, but Minecraft normal thing to not display entities so far (can be changed in server configuration files)

**Comment by LoneDev6** [comment]
Finally managed to reproduce the issue.
Happens when the player is far but not very far from entities, as much as to make them disappear, then they don't get rendered anymore if the player immediately gets back to the rendering area.
