### ISSUE TITLE
Font image is not placed in Lore

### ISSUE THREAD

**Issue by JustRises** [PluginBugs/Issues-ItemsAdder#4044]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

justrises

### What happened?

Font image is not placed in Lore
image: https://cdn.discordapp.com/attachments/1020746448536621106/1292243029385543790/image.png?ex=6703069a&is=6701b51a&hm=f86147ed136a3a49527bf8e0eaa5490ecd1ddd9bf603b5bdb4bae3e66d225980&

It works in the title but not in lore. My friends also tried it on their own server, but it did not work on them either.

```
info:
  namespace: "emoji_icon_totem"
font_images: 
  saldirigucu_logo:
    show_in_gui: true
    path: "font/item_info/ozellikler/saldirigucu_logo.png"
    scale_ratio: 12
    y_position: 8
    
    
info:
  namespace: itemler
items:
  pot_mana_yaygin:
    display_name: "test :saldirigucu_logo:"
    lore:
    - ':saldirigucu_logo: %saldirigucu_logo% %img_saldirigucu_logo% :img_saldirigucu_logo:'
    permission: example_item
    attribute_modifiers:
      mainhand:
        attackSpeed: 100
    resource:
      material: PAPER
      generate: true
      textures:
      - kiliclar/ateskilici/ateskilici1/ateskilici1.png
    durability:
      disappear_when_broken: false
    item_flags:
    - HIDE_ATTRIBUTES
    - HIDE_DESTROYS
    - HIDE_ENCHANTS
    - HIDE_PLACED_ON
    - HIDE_POTION_EFFECTS
    - HIDE_UNBREAKABLE
    - HIDE_DYE
    - HIDE_ARMOR_TRIM
    blocked_enchants:
    - ALL
```

### Steps to reproduce the issue

Font image is not placed in Lore

### Server version

Current Purpur Version: 1.21.1-2315-2a50638 (MC: 1.21.1)*

### ItemsAdder Version

4.0.2-beta-release-12

### ProtocolLib Version

5.3.0-SNAPSHOT-732

### LoneLibs Version

1.0.59

### Full Server Log

https://mclo.gs/bJZeG2a

### Screenshots/Videos (you can drag and drop files or paste links)

https://cdn.discordapp.com/attachments/1020746448536621106/1292243029385543790/image.png?ex=6703069a&is=6701b51a&hm=f86147ed136a3a49527bf8e0eaa5490ecd1ddd9bf603b5bdb4bae3e66d225980&

**Comment by Andre601** [comment]
> There is no problem in our log file. I cannot share due to our privacy.

Please share your log files with mclo.gs. We ask for them for a reason and the fact you don't have any errors is not an excuse to not share them.
Also, privacy isn't a valid argument either as server logs barely have any sensitive info to begin with. At most are there IPs and folder paths, which both are censored by mclo.gs (+ the former can be hidden now via server settings).

**Comment by JustRises** [comment]
https://mclo.gs/bJZeG2a

**Comment by JustRises** [comment]
Will you fix the problem?
