### ISSUE TITLE
[Message] Give Message off

### ISSUE THREAD

**Issue by NoHere32** [PluginBugs/Issues-ItemsAdder#4050]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

.nohere

### Describe the solution you'd like

Being able to give items silently.

### Is your feature request related to a problem?

Message not pretty enough and minimessage impossible in the en.yml language

### Describe alternatives you've considered

There are two possible solutions
1 - Either add a ‘silent’ behind the give command
2 - Add a true or false option in config.yml

### Additional context

![image](https://github.com/user-attachments/assets/cd59d3e2-05aa-409f-a7ac-017c2a4beca8)

**Comment by Andre601** [comment]
Just append the quantity and `silent` to the command itself: `/iagive <player> <item> 1 silent`

This will not send any messages to you or the player that gets the item.

**Comment by NoHere32** [comment]
> Just append the quantity and `silent` to the command itself: `/iagive <player> <item> 1 silent`
> 
> This will not send any messages to you or the player that gets the item.

Sorry, when I tried it, it wouldn't work... 
probably because of the missing quantity...
