### ISSUE TITLE
itemsadder recipe multiple id

### ISSUE THREAD

**Issue by Dexter44444** [PluginBugs/Issues-ItemsAdder#4068]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

when i try to craft sweet sticks from a sweet ingot with the slimefun networks autocrafter, the output is always potato sticks.

### Steps to reproduce the issue

i can upload a short gameplay video of the issue.

### Server version

i am just a player and dont have access to this command.

### ItemsAdder Version

i am just a player and dont have access to this command.

### ProtocolLib Version

i am just a player and dont have access to this command.

### LoneLibs Version

i am just a player and dont have access to this command.

### Full Server Log

i am just a player and dont have access to this command.

**Comment by bobcat4848** [comment]
This sounds like a server issue and not an ItemsAdder issue.

**Comment by Andre601** [comment]
Please tell the server owner to file an issue, so that we get tha necessary info.
