### ISSUE TITLE
Multiple heads appear together and cannot be displayed normally

### ISSUE THREAD

**Issue by 404forever1** [PluginBugs/Issues-ItemsAdder#4075]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

![image](https://github.com/user-attachments/assets/b706f6a3-fc36-426e-9c75-85fc09d96c25)
Just install the default pack and this will happen.

### Steps to reproduce the issue

Just install the default pack and this will happen.

### Server version

1.21.1

### ItemsAdder Version

![image](https://github.com/user-attachments/assets/21904c42-744d-4aa8-af9b-038230fdc6f2)

### ProtocolLib Version

![image](https://github.com/user-attachments/assets/4f3b8451-0516-49ec-974d-9febd7271caf)

### LoneLibs Version

![image](https://github.com/user-attachments/assets/3f30be65-3d8e-4b85-ae5d-47983c72590d)

### Full Server Log

no error

**Comment by Andre601** [comment]
Disable player emotes and rezip resource pack to fix this.

https://itemsadder.devs.beer/faq/placed-heads-texture-glitched
