### ISSUE TITLE
Vanilla blocks not breaking sometimes when mining fast

### ISSUE THREAD

**Issue by Borplesnoots** [PluginBugs/Issues-ItemsAdder#4076]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

borplesnoots

### What happened?

When breaking any blocks, using vanilla enchants - the blocks do not break as expected. This makes any sort of gameplay immediately annoying when breaking blocks. For example, a netherite pickaxe with Eff 5 and haste 2 can easily break ~2-3 blocks when walking back and forth, but when ItemsAdder is on the server there will be blocks intermittently left behind. This is replicatable with anything, e.g. shovel with dirt, sand, etc. 

![image](https://github.com/user-attachments/assets/2ca45f8a-bad7-4c94-a8a8-02175b68b93f)

[With ItemsAdder and dependencies](https://youtu.be/RnmN4RtTy9c)

Without ItemsAdder (zero plugins on server):
[Without ItemsAdder](https://youtu.be/1S1ppIFBhj8)

No other plugins are on the server. I was able to replicate this also on 1.21.1

This was reported in #3835 as "minor", and you stated there was no solution however this has large implications over the ability for any server owner to use ItemsAdder on their server, as this is largely a block breaking game. 

### Steps to reproduce the issue

1. Mine any blocks quickly enough. Either with instant-break blocks like flowers/grass, or with high enough efficiency/haste for other blocks
2. Notice that not all blocks are breaking as expected

### Server version

This server is running Paper version 1.21-130-master@b1b5d4c (2024-08-10T10:02:42Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### ItemsAdder Version

4.0.2-beta-release-12

### ProtocolLib Version

5.3.0

### LoneLibs Version

1.0.59

### Full Server Log

https://mclo.gs/vsO7NT6

**Comment by Borplesnoots** [comment]
Tested and issue is still present in ItemsAdder Version 4.0.3, ProtocolLib Version 5.3.0, and LoneLibs Version 1.0.59

**Comment by LoneDev6** [comment]
Thank you for the very detailed test.
I will check this as soon as possible for a possible mitigation of the issue.

**Comment by LoneDev6** [comment]
Testing with netherite pickaxe with efficiency 5, haste 2 and speed 2.
It's related to latency, will find a way to fix that issue.
NOTE: It's different from #3835 as the other issue refers to particle not being played, which is caused by the current issue probably.

# Tested with 200+ ping - ItemsAdder **NOT** installed

https://github.com/user-attachments/assets/beac989d-a5b5-4fbc-aa91-059f5bfaf6a6

# Tested with 200+ ping - ItemsAdder installed

https://github.com/user-attachments/assets/d18ca5ac-01e0-46d0-aac4-a017b2f162f3

**Comment by LoneDev6** [comment]
@borplesnoots can you please join the Discord server again in order to test the new beta version?
I should have mitigated the issue completely.

**Comment by Borplesnoots** [comment]
> @Borplesnoots can you please join the Discord server again in order to test the new beta version? I should have mitigated the issue completely.

Awesome! I've rejoined.
