### ISSUE TITLE
Sharpness Enchantment Duplicated

### ISSUE THREAD

**Issue by MrMaleficus** [PluginBugs/Issues-ItemsAdder#4079]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

mrm

### What happened?

When a book is enchanted in the enchanting table to obtain the Sharpness enchantment, it duplicates it, (see the image)

### Steps to reproduce the issue

Get a fresh install of ItemsAdder (4.0.3)
Enchant a book to book on the enchanting table to obtain a "Sharpness" enchantment
Done

### Server version

[20:28:18 INFO]: This server is running Paper version 1.21.1-122-master@4430e96 (2024-10-12T21:18:42Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### ItemsAdder Version

[20:28:42 INFO]: ItemsAdder version 4.0.3
[20:28:42 INFO]: Customized Minecraft without client mods!
[20:28:42 INFO]: Website: devs.beer
[20:28:42 INFO]: Author: LoneDev

### ProtocolLib Version

[20:29:08 INFO]: ProtocolLib version 5.3.0-SNAPSHOT-726
[20:29:08 INFO]: Provides read/write access to the Minecraft protocol.
[20:29:08 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[20:29:22 INFO]: LoneLibs version 1.0.59
[20:29:22 INFO]: Collection of libs used by my plugins
[20:29:22 INFO]: Authors: LoneDev and others

### Full Server Log

https://mclo.gs/Mi26HsR

### Screenshots/Videos (you can drag and drop files or paste links)

![2024-10-25_20 24 35](https://github.com/user-attachments/assets/7ac978db-f747-4f6b-a78e-e9c69ac9a274)
![2024-10-25_20 24 34](https://github.com/user-attachments/assets/c66462cb-263c-4d33-a561-386c9af8f703)

**Comment by Andre601** [comment]
Thanks for reporting. I was able to reproduce this bug on a Fresh Test server with just ItemsAdder and its dependencies installed.
LoneDev will look at this as soon as he can find some time. Your patience is apreciated.

**Comment by Ceejuu** [comment]
Can relate, same issue here

**Comment by MrMaleficus** [comment]
The 4.0.4 is still affected.

**Comment by WMGameLive** [comment]
Same issue here, if the book get a set of enchantments from the enchanting table that includes sharpness, the entire `stored_enchantments` list will be duplicated into the `enchantments` list.

![image](https://github.com/user-attachments/assets/4357a81a-c540-4f1c-938c-bedbb975394c)
![image](https://github.com/user-attachments/assets/f9b0fd48-427a-4faf-b175-2818c17d3fbd)

Hope there will be a way to fix existing bugged books once this bug is resolved.
