### ISSUE TITLE
1.21.2 - 1.21.3 Resourcepack error

### ISSUE THREAD

**Issue by LeBlach** [PluginBugs/Issues-ItemsAdder#4082]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

blachtr

### What happened?

Players cannot download the resourcepack in version 1.21.2 and 1.21.3

In version 1.21.1 there is no problem, but in versions 1.21.2 and 1.21.3 the resource pack does not work.

### Steps to reproduce the issue

Join the server with version 1.21.3

### Server version

Pufferfish 1.21.1 #21 
Pufferfish version 1.21.1-21-HEAD@cfa3c61 

### ItemsAdder Version

4.0.3

### ProtocolLib Version

5.3.0-SNAPSHOT-732

### LoneLibs Version

1.0.58

### Full Server Log

https://mclo.gs/

### Error (optional)

```shell
It's a Minecraft log, not a console, there is no error in the console.

10:35:38] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to load required shader programs:
 - minecraft:core/rendertype_entity_translucent (VertexFormat[Position, Color, UV0, UV1, UV2, Normal]): Could not find shader: minecraft:rendertype_entity_translucent (VERTEX)
 - minecraft:core/rendertype_armor_cutout_no_cull (VertexFormat[Position, Color, UV0, UV1, UV2, Normal]): Could not find shader: minecraft:rendertype_armor_cutout_no_cull (VERTEX)
 - minecraft:core/rendertype_text (VertexFormat[Position, Color, UV0, UV2]): Could not find shader: minecraft:rendertype_text (VERTEX)
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
    at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
    at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
    at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
    at awb.a(SourceFile:68) ~[1.21.3.jar:?]
    at bry.d(SourceFile:164) ~[1.21.3.jar:?]
    at bsc.d(SourceFile:23) ~[1.21.3.jar:?]
    at bry.B(SourceFile:138) ~[1.21.3.jar:?]
    at bry.bA(SourceFile:123) ~[1.21.3.jar:?]
    at fmg.c(SourceFile:1307) [1.21.3.jar:?]
    at fmg.f(SourceFile:933) [1.21.3.jar:?]
    at net.minecraft.client.main.Main.main(SourceFile:265) [1.21.3.jar:?]
Caused by: java.lang.RuntimeException: Failed to load required shader programs:
 - minecraft:core/rendertype_entity_translucent (VertexFormat[Position, Color, UV0, UV1, UV2, Normal]): Could not find shader: minecraft:rendertype_entity_translucent (VERTEX)
 - minecraft:core/rendertype_armor_cutout_no_cull (VertexFormat[Position, Color, UV0, UV1, UV2, Normal]): Could not find shader: minecraft:rendertype_armor_cutout_no_cull (VERTEX)
 - minecraft:core/rendertype_text (VertexFormat[Position, Color, UV0, UV2]): Could not find shader: minecraft:rendertype_text (VERTEX)
    at gmc.a(SourceFile:174) ~[1.21.3.jar:?]
    at gmc.a(SourceFile:37) ~[1.21.3.jar:?]
    at awa.a(SourceFile:14) ~[1.21.3.jar:?]
    at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
    ... 9 more
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/user-attachments/assets/f845b512-1bce-43f2-9f24-7d295cd4c8fd)
![image](https://github.com/user-attachments/assets/30a84fb6-6795-48a2-8a38-e10ce247918d)

**Comment by LeBlach** [comment]
I upgraded ItemsAdder to version 4.0.3 and used the iazip command again but it didn't fix it.

**Comment by Andre601** [comment]
Please don't report issues happening on client versions different than the server.

ItemsAdder currently only works on 1.21.1 as its latest version. Any issues that happen on server versions IA doesn't support (yet) are not something we can nor will fix, as we do not recommend using plugins such as ViaVersion for anything other than a multi-version lobby. See #3683

**Comment by pjindras** [comment]
I have the same problem on 4.0.4 version of itemsadder.

**Comment by LoneDev6** [comment]
Duplicate of #4159
