### ISSUE TITLE
Issue with Custom Block removal

### ISSUE THREAD

**Issue by Robotv2** [PluginBugs/Issues-ItemsAdder#4084]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

robotv2

### What happened?

I can't remove a custom block after placing it with the API.

### Steps to reproduce the issue

1. Place a block using CustomBlock#place method (works)
2. Try to remove the block using either, CustomBlock#remove (both static and non-static methods)

### Server version

This server is running Paper version git-Paper-497 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: d8d54d9 on ver/1.20.4)

### ItemsAdder Version

ItemsAdder version 3.6.3-beta-13

### ProtocolLib Version

Protocollib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.45

### Full Server Log

https://mclo.gs/

**Comment by Andre601** [comment]
Please share actual code examples of how you set and remove the block.

**Comment by Robotv2** [comment]
The logs: https://mclo.gs/6P8CdfH

```java
    @Override
    public void place(Block block) {
        CustomBlock.place(namespaceId, block.getLocation());
    }
    
```

```java
    public static void removeCustomBlock(Block block) {
        final CustomBlock customBlock = CustomBlock.byAlreadyPlaced(block);

        AstralaHautFourneau.logger().info("Is placed: " + customBlock.isPlaced());
        AstralaHautFourneau.logger().info("Removing API #1: " + customBlock.remove());
        AstralaHautFourneau.logger().info("Removing API #2: " + CustomBlock.remove(block.getLocation()));
        AstralaHautFourneau.logger().info("Is placed: " + customBlock.isPlaced());
    }
```

**Comment by Robotv2** [comment]
As seen on the logs, the output of the second method is alwayds:

[16:49:19] [Server thread/INFO]: [AstralaHautFourneau] Is placed: true
[16:49:19] [Server thread/INFO]: [AstralaHautFourneau] Removing API #1: true
[16:49:19] [Server thread/INFO]: [AstralaHautFourneau] Removing API #2: false
[16:49:19] [Server thread/INFO]: [AstralaHautFourneau] Is placed: false

Switching the two API methods doesn't change the output, it's always 'true' first and then 'false' but the block is still here visually.

**Comment by Andre601** [comment]
Why are you using a version of ItemsAdder licensed to another user?

On Discord are you robotv2, but the product used is licensed to hysteriox who has the same name set as their discord on their spigot profile.

**Comment by Robotv2** [comment]
Cause I am working on his server as a developer. I need to add support for itemadder inside a custom plugin. And no, i do not own a copy of itemadder myself. Does this answer your question?
