### ISSUE TITLE
Random loading screens (multiple)

### ISSUE THREAD

**Issue by WataLaker37821** [PluginBugs/Issues-ItemsAdder#4091]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

DOGE#1690

### Describe the solution you'd like

I wanted to request / ask  for adding a possibility to add multiple custom loading screens, so it will be possible to randomly show to players when they join/change dimensions or worlds, so there will be possible to add "hints or tips" for players to read while watching a title screen (picture)

### Is your feature request related to a problem?

I just wanted to ask if that feature possible, would be cool to have multiple images and also tips, shown to players!

### Describe alternatives you've considered

I am not sure about, what possibly could be done

**Comment by Andre601** [comment]
If you refer to the actual loading screen for when the client loads the resource pack, then that is not possible and a Minecraft limitation.

And if you simply mean displaying a screen for whenever a player changes dimensions or performs certain tasks, is there no need for adding extra functionality, as something similar is already doable with static images. See the [Screen Effects Add-on](https://www.spigotmc.org/resources/90258/) for how such a thing is done without API.
And with API could you also do this for sure by making a plugin that hooks into ItemsAdder.

**Comment by WataLaker37821** [comment]
> If you refer to the actual loading screen for when the client loads the resource pack, then that is not possible and a Minecraft limitation.
> 
> And if you simply mean displaying a screen for whenever a player changes dimensions or performs certain tasks, is there no need for adding extra functionality, as something similar is already doable with static images. See the [Screen Effects Add-on](https://www.spigotmc.org/resources/90258/) for how such a thing is done without API. And with API could you also do this for sure by making a plugin that hooks into ItemsAdder.

Is there a possibility to make those screens random?
