### ISSUE TITLE
Error when I log in

### ISSUE THREAD

**Issue by ZacianKing** [PluginBugs/Issues-ItemsAdder#4092]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

zacy5

### What happened?

Do you know how to solve this problem? I have a bungeecord vps and before the transfer to another node, it didn't show and let you log in calmly, and now it doesn't let you log in and it takes a long time to then get kicked, and this appears in the console https://mclo.gs/d9UxMOG
I think it's a conflict with something but if in doubt I report it here too

### Steps to reproduce the issue

1 - I start the server
2 - I try to enter
3 - I get kicked for timed out and other messages (+ this error appears in the terminal)

### Server version

This server is running Paper version git-Paper-794 (MC: 1.16.5) Implementing API version 1.16.5-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 3.4.0c-beta 
(I can't update it, if I update it it gives errors and won't work anymore, I've already tried many times with another test server)

### ProtocolLib Version

ProtocolLib version 5.1.0

### LoneLibs Version

LoneLibs version 1.0.42

### Full Server Log

https://mclo.gs/d9UxMOG

**Comment by Andre601** [comment]
1. Provide your **full logs** and not just the error
2. You're severely outdated. There has been a new v3 release for ItemsAdder for quite a while, so please update before making an issue.
