### ISSUE TITLE
1.21.3 - Fix attributes keys

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#4129]
1.21.2 changes the naming of attributes, it removes `generic.` from the keys.

![image](https://github.com/user-attachments/assets/a43b004d-fb0b-4130-9d27-6fbe12f54010)

**Comment by Slarof** [comment]
As of 1.21.2, attributes no longer have any prefixes, not only "generic."
![IMG_20241114_095219](https://github.com/user-attachments/assets/92d90d89-ac1d-40f5-9ee4-a4a5c8d68e8f)
