### ISSUE TITLE
[BUG] Slimefun - Pickaxe of Vein Mining, Pickaxe of the Seeker and Necrotic Skull have bad texture.

### ISSUE THREAD

**Issue by 100petr** [PluginBugs/Issues-ItemsAdder#414]
**Describe the bug**
Pickaxe of Vein Mining, Pickaxe of the Seeker and Necrotic Skull have bad texture.

**To Reproduce**
1. Install the addon for sf https://www.spigotmc.org/threads/addon-slimefun4-compatibility-for-itemsadder.463173
2. Open /sf guide (Tools category)

**Expected behavior**
The pickaxes will not look like a multiblock.

**Screenshots**
![image](https://user-images.githubusercontent.com/29830635/95596277-78c70300-0a4d-11eb-903c-0c0eb810a6ea.png)
![image](https://user-images.githubusercontent.com/29830635/95596292-7c5a8a00-0a4d-11eb-9c59-1841a9197320.png)
![image](https://user-images.githubusercontent.com/29830635/105594483-776add80-5d93-11eb-8930-b001e8c5dcd4.png)

**Info (please complete the following information):**
 - Server version: paper 1.16.3 #216
 - Client version: 1.16.3
 - Plugin version: 2.1.3

**Additional context**
https://www.spigotmc.org/threads/addon-slimefun4-compatibility-for-itemsadder.463173/#post-3966065

**Comment by 100petr** [comment]
I also noticed that tome of knowledge sharing has no texture 
![image](https://user-images.githubusercontent.com/29830635/118299201-bce91d00-b4e0-11eb-9bf6-2b4894bda4b7.png)
but there is in ia this
![image](https://user-images.githubusercontent.com/29830635/118299251-d0948380-b4e0-11eb-8021-63af404d768c.png)

**Comment by 100petr** [comment]
Thanks! I'll leave the issue open, or let lonedev close it - I don't know if he wants to fix it in his addon or not

**Comment by LoneDev6** [comment]
The good news is that the addon is now not needed anymore, you just have to drag and drop the resourcepack files inside itemsadder resourcepack folder and it will be merged automatically.
https://itemsadder.devs.beer/plugin-usage/merge-resourcepacks
