### ISSUE TITLE
Chat Issue - Font images

### ISSUE THREAD

**Issue by Asleeepp** [PluginBugs/Issues-ItemsAdder#4152]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

asleepp

### What happened?

When a player has no permission to use a font image in chat, ItemsAdder removes the colons from the message, making the message look very weird. I'm hoping this can be reverted, or atleast have a config setting to remove this functionality and leave the colon as it is

### Steps to reproduce the issue

1, make font image
2, use it in chat without permission to use it
3, see that it has no colons anymore

### Server version

10:58:51 [INFO] Current Purpur Version: 1.21.1-2301-a43711d (MC: 1.21.1)*
* You are 28 version(s) behind
Download the new version at: https://purpurmc.org/downloads
Previous: 1.21.1-2300-49db849 (MC: 1.21.1)

### ItemsAdder Version

ItemsAdder version 4.0.2-alpha-test-7
10:59:07 [INFO] Customized Minecraft without client mods!
10:59:07 [INFO] Website: devs.beer
10:59:07 [INFO] Author: LoneDev

(outdated, but its the same thing on newer versions of ItemsAdder)

### ProtocolLib Version

ProtocolLib version 5.3.0-SNAPSHOT-726
10:59:41 [INFO] Provides read/write access to the Minecraft protocol.
10:59:41 [INFO] Authors: dmulloy2 and comphenix

### LoneLibs Version

LoneLibs version 1.0.57
11:00:07 [INFO] Collection of libs used by my plugins
11:00:07 [INFO] Authors: LoneDev and others

### Full Server Log

https://mclo.gs/7ma9eK7

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/user-attachments/assets/1d3c4ec8-b454-4527-a348-bcac0c354d42)
![image](https://github.com/user-attachments/assets/d5019606-d74c-4e7e-b8e6-b2acdbeed545)

**Comment by PSYCHEER** [comment]
What instead of removing colons it will be escaped, so IA will not replace it with font image

OR

When no permission found, IA will just not replace it with font_image

**Comment by Asleeepp** [comment]
> What instead of removing colons it will be escaped, so IA will not replace it with font image
> 
> OR
> 
> When no permission found, IA will just not replace it with font_image

I feel like the intended behaviour is just that IA doesn't replace the font image

**Comment by LoneDev6** [comment]
This is not possible to be fixed as the message would be parsed by the packets listener and be replaced.
In order to avoid the packet listener to match the emoji I have to remove the characters.
