### ISSUE TITLE
Setting apply-during-chunk-load-phase has no effect

### ISSUE THREAD

**Issue by EagL3-GIT** [PluginBugs/Issues-ItemsAdder#4154]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

Seems like apply-during-chunk-load-phase option is not working, it still asking for/loading texturepack before join (like on chunk load) when its set to false.

(Using it with apply-on-join: false)

### Steps to reproduce the issue

Set apply-during-chunk-load-phase to false in config
Set apply-on-join to false in config
Try to load in with prompt server setting or just with accepted

### Server version

[19:26:28 INFO]: This server is running Paper version 1.21.1-131-ver/1.21.1@84281ce (2024-10-31T17:43:44Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-119-7cd4f2c (MC: 1.21.1)

### ItemsAdder Version

ItemsAdder version 4.0.4

### ProtocolLib Version

ProtocolLib version 5.3.0

### LoneLibs Version

LoneLibs version 1.0.61

### Full Server Log

-

**Comment by EagL3-GIT** [comment]
// If its meant to be like that, it would be good to add option to disable automatic loading texturepack before join so we can use /iapack whenever we want (more customizable) like it was in legacy versions.

**Comment by Andre601** [comment]
Pretty sure disabling both options to false will make IA default to using one of the two, with applying during chunk load (which probs may be the configuration phase of the client) being the one used.

After all, unless you do no-host is there no reason for why both options should be disabled...

**Comment by EagL3-GIT** [comment]
I tried apply-during-chunk-load-phase false and apply-on-join true, still the same result, its asking/applying before join

**Comment by Andre601** [comment]
Well, asking - as in showing the prompt - would happen during join anyways and usually is something that can't be changed. Or at least not too easily.

**Comment by EagL3-GIT** [comment]
But the prompt message is now before u even join, not like it was on version 3.x of itemsadder, so like u cant delay it or show it when u want, for example make it ask u (prompt) after u register..

**Comment by CCjun6** [comment]
> Well, asking - as in showing the prompt - would happen during join anyways and usually is something that can't be changed. Or at least not too easily.

Have you considered a server that only loads resource packs on the proxy side?
My server has always disabled apply-during-chunk-load-phase and apply-on-join. Players only need to load the resource pack when they first enter the hub.
After using version 4.0.4, now every time a player enters a different sub-server, they have to load the resource pack again. Even though the resource pack configurations are the same, they still need to be loaded. I hope this issue can be fixed soon."

**Comment by LoneDev6** [comment]
This is the correct option, you might have some left over old options in the config.yml, remove them.
```yml
resource-pack:
  uuid: "d69238f2-b7ce-30b0-8262-17cd9490f29d"
  apply_during_chunk_load_phase: true
  apply_on_join:
    enabled: false
    delay_ticks: 1
```
