### ISSUE TITLE
Could not find shader: `minecraft:rendertype_entity_translucent`

### ISSUE THREAD

**Issue by xyzjesper** [PluginBugs/Issues-ItemsAdder#4159]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

xyzjesper

### What happened?

I get this error in the 1.21.3 with the latest Itemsadder and Lonelibs. it coms from shadors.

```java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to load required shader programs:
 - minecraft:core/rendertype_entity_translucent (VertexFormat[Position, Color, UV0, UV1, UV2, Normal]): Could not find shader: minecraft:rendertype_entity_translucent (VERTEX)
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at awb.a(SourceFile:68) ~[minecraft-1.21.3-client.jar:?]
	at bry.d(SourceFile:164) ~[minecraft-1.21.3-client.jar:?]
	at bsc.d(SourceFile:23) ~[minecraft-1.21.3-client.jar:?]
	at bry.B(SourceFile:138) ~[minecraft-1.21.3-client.jar:?]
	at bry.bA(SourceFile:123) ~[minecraft-1.21.3-client.jar:?]
	at fmg.c(SourceFile:1307) [minecraft-1.21.3-client.jar:?]
	at fmg.f(SourceFile:933) [minecraft-1.21.3-client.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:265) [minecraft-1.21.3-client.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Failed to load required shader programs:
 - minecraft:core/rendertype_entity_translucent (VertexFormat[Position, Color, UV0, UV1, UV2, Normal]): Could not find shader: minecraft:rendertype_entity_translucent (VERTEX)
	at gmc.a(SourceFile:174) ~[minecraft-1.21.3-client.jar:?]
	at gmc.a(SourceFile:37) ~[minecraft-1.21.3-client.jar:?]
	at awa.a(SourceFile:14) ~[minecraft-1.21.3-client.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 12 more
```

### Steps to reproduce the issue

use a resourcepack in the 1.21.3 from itemsadder and join a server.

### Server version

![image](https://github.com/user-attachments/assets/4bfa673e-2301-4809-a19f-19e9ba4fad82)

### ItemsAdder Version

![image](https://github.com/user-attachments/assets/a93ccf47-fdb4-47bb-9e20-147b9277dc0e)

### ProtocolLib Version

![image](https://github.com/user-attachments/assets/8c0c3ca5-46e4-46cd-ae4b-f2a93b660d42)

### LoneLibs Version

![image](https://github.com/user-attachments/assets/e6e69fb8-c328-4e52-b157-707d23e0e3a8)

### Full Server Log

https://mclo.gs/lO8dVfF

**Comment by xyzjesper** [comment]
@LoneDev6 Have you any idea?

**Comment by pjindras** [comment]
https://bugs.mojang.com/browse/MC-277887?focusedId=1363166&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel

I have the same problem on 1.21.3.

**Comment by xyzjesper** [comment]
Ah ok but is there a way to fix it because i have in my resourcepack no Shador (in my knowladge)

**Comment by LoneDev6** [comment]
can you confirm:
- you don't have any custom shader from other plugins/packs in your itemsadder resourcepack
-  regenerating the pack using `/iazip` doesn't fix the issue
-  `output/generated.zip` contains the folder `ia_overlay_1_21_2`?

**Comment by pjindras** [comment]
> can you confirm:
> 
> * you don't have any custom shader from other plugins/packs in your itemsadder resourcepack
> * regenerating the pack using `/iazip` doesn't fix the issue
> * `output/generated.zip` contains the folder `ia_overlay_1_21_2`?
> 
> ItemsAdder 4.0.4 implements a new feature that adds a new folder `ia_overlay_1_21_2` in the resourcepack, this folder allows 1.21.2+ clients to load shaders from there instead of the `assets` folder, this fixes the issue.
> 
> If the folder `ia_overlay_1_21_2` exists in your pack you probably have another plugin/pack/asset with shaders that have this issue, so please make sure to fix that.

I can confirm that.

We don't have custom shaders.
/ia zip didn't help.
There is ia_orvelay_1_21_2 folder in output zip file.

**Comment by LoneDev6** [comment]
@pjindras 
model engine probably uses a custom shader that is broken, ask them to fix it or use the new beta version of itemsadder that automatically fixes other plugins/packs shaders: #4177

**Comment by PSYCHEER** [comment]
> > can you confirm:
> > 
> > * you don't have any custom shader from other plugins/packs in your itemsadder resourcepack
> > * regenerating the pack using `/iazip` doesn't fix the issue
> > * `output/generated.zip` contains the folder `ia_overlay_1_21_2`?
> > 
> > ItemsAdder 4.0.4 implements a new feature that adds a new folder `ia_overlay_1_21_2` in the resourcepack, this folder allows 1.21.2+ clients to load shaders from there instead of the `assets` folder, this fixes the issue.
> > If the folder `ia_overlay_1_21_2` exists in your pack you probably have another plugin/pack/asset with shaders that have this issue, so please make sure to fix that.
> 
> I can confirm that.
> 
> We don't have custom shaders. /ia zip didn't help. There is ia_orvelay_1_21_2 folder in output zip file.
> 
> We use modelengine 4, that's only one other plugin. Maybe the issue could be there. Model-Engine-R4.0.8-dev-all Build 2065

Try disabling shader generation in MEG config and repack. So we can be sure

**Comment by pjindras** [comment]
and in this folder, there are the shader data from meg, which I already removed in meg

**Comment by LoneDev6** [comment]
@pjindras 
disable emotes and text effects in config.yml of itemsadder and run /iazip if you don't want shaders to be output in the zip.

**Comment by pjindras** [comment]
Ok, it helped me, thank you.

**Comment by DxrkCat** [comment]
> Try to disable this: `extract_emotes_shaders: false`
> 
> Then recreate resource pack: **/iazip**
> 
> Also, update ItemsAdder to the latest version.

https://mclo.gs/fVm0ae4

**Comment by DxrkCat** [comment]
> Send your config.yml

https://p.reflex.rip/kuke.sql

**Comment by LoneDev6** [comment]
Please do not comment on old issues. Make a new one with your own information instead.
Anyway check the server log, you probably have some duplicate files.

**Comment by LoneDev6** [comment]
A new beta 4.0.6 is available on the Discord server which might fix that particular issue. Remember to regenerate your resourcepack.

**Comment by DxrkCat** [comment]
> A new beta 4.0.6 is available on the Discord server which might fix that particular issue. Remember to regenerate your resourcepack.

Can you post on SpigotMC, I couldn't get verified in discord through your system. And I can't buy the plugin on polymart to go through it to try.

**Comment by Andre601** [comment]
If you have issues verifying, open a ticket about it.

**Comment by DxrkCat** [comment]
![изображение](https://github.com/user-attachments/assets/bbad158f-70c3-4d27-b8f4-b1e68b379574)
https://mclo.gs/XAsZdg6
The problem is current on the latest version.

To retest, I enabled shader creation in the ModelEngine config, deleted the .data and resourcepack folder, wrote /meg reload, and after /iazip.

**Comment by DxrkCat** [comment]
Client log: https://mclo.gs/RHFVgS5
Fabric 1.21.4, mo mods
When I went into the radius of visibility of the model from ModelEngine I crashed the client, previously just the client did not load textures. and there was a label resourcepack failed load.
