### ISSUE TITLE
Darkened Default Backgrounds in Minecraft After Updating to ItemsAdder 4.0.4

### ISSUE THREAD

**Issue by zikehalil3535** [PluginBugs/Issues-ItemsAdder#4169]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

whiskeytr

### What happened?

After updating from ItemsAdder version 4.0.3 to 4.0.4, we noticed that Minecraft's default backgrounds for the Tab list, chat, and scoreboard appear excessively dark. This issue occurs specifically with resource packs generated using ItemsAdder 4.0.4, while previous versions did not exhibit this problem.

We believe this issue might be relatively simple to resolve, and we're requesting support to it. Please let us know if additional details or files are needed.

### Steps to reproduce the issue

1. Update ItemsAdder to version 4.0.4.
2. Generate a new resource pack using the plugin. /iazip
3. Join with older version like 1.20.1-1.19
4. Load the resource pack in Minecraft and observe the Tab list, chat, and scoreboard backgrounds.

### Server version

[14:00:47 INFO]: Current Purpur Version: 1.21.1-2329-803bf62 (MC: 1.21.1)*
* You are running the latest version

### ItemsAdder Version

[14:00:58 INFO]: ItemsAdder version 4.0.4
[14:00:58 INFO]: Customized Minecraft without client mods!
[14:00:58 INFO]: Website: devs.beer
[14:00:58 INFO]: Author: LoneDev

### ProtocolLib Version

[14:01:10 INFO]: ProtocolLib version 5.3.0
[14:01:10 INFO]: Provides read/write access to the Minecraft protocol.
[14:01:10 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[14:01:17 INFO]: LoneLibs version 1.0.61
[14:01:17 INFO]: Collection of libs used by my plugins
[14:01:17 INFO]: Authors: LoneDev and others

### Full Server Log

No Logs Needed

### Other files, you can drag and drop them here to upload. (optional)

Expected Behavior:
The default backgrounds should retain their standard brightness as in previous versions.

Observed Behavior:
The backgrounds are noticeably darker than intended, creating visual inconsistency.

### Screenshots/Videos (you can drag and drop files or paste links)

![Screenshot_4](https://github.com/user-attachments/assets/b568e305-9962-423a-9fb1-61a951858381)
![Untitled-1](https://github.com/user-attachments/assets/75d42bb0-d120-4a61-9508-624c26a2bc67)

**Comment by LoneDev6** [comment]
I cannot reproduce the issue.
```
> version ItemsAdder
[15:41:58 INFO]: ItemsAdder version 4.0.4

[15:42:08 INFO]: This server is running Paper version 1.21.3-44-master@85bfdc0 (2024-11-19T11:26:52Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
You are 16 version(s) behind
```

# 1.20.1
![image](https://github.com/user-attachments/assets/51f12760-5ef5-4e16-b52f-3f1fa595c126)

# 1.21.3
![image](https://github.com/user-attachments/assets/6052e4a6-dc60-43a7-88c2-db545f1ffffc)

**Comment by LeBlach** [comment]
Did you run /iazip or did you just change the version? 

Login with version 1.19.4 and run the /iazip command.

**Comment by LeBlach** [comment]
I can confirm this problem, I tested it too.

**Comment by LoneDev6** [comment]
# 1.19.4

![image](https://github.com/user-attachments/assets/306981b4-3e99-4fa9-86aa-08ecd28b02bf)

**Comment by LoneDev6** [comment]
make sure to test without any mod installed and any other resourcepack, let me know

**Comment by zikehalil3535** [comment]
> Remember, contributions to this repository should follow its [security policy](/PluginBugs/Issues-ItemsAdder/blob/9ca876a1d9c00f67945c7b8b5b7b18e4fbdaad36/SECURITY.md).
> Assignees
> No one assigned
> Labels
> [ verdict: can't reproduce ](/PluginBugs/Issues-ItemsAdder/labels/verdict%3A%20can%27t%20reproduce)
> Projects
> [ ItemsAdder ](/orgs/PluginBugs/projects/3)
> Status: No status
> Milestone
> No milestone
> Development
> No branches or pull requests
> 
> 
> Notifications
> Customize
> 
> Unsubscribe
> You’re receiving notifications because you authored the thread.
> 
> 3 participants
> [ <img alt="@LoneDev6" width="26" height="26" src="https://avatars.githubusercontent.com/u/27242001?s=52&amp;v=4"> ](/LoneDev6) [ <img alt="@LeBlach" width="26" height="26" src="https://avatars.githubusercontent.com/u/46748814?s=52&amp;v=4"> ](/LeBlach) [ <img alt="@zikehalil3535" width="26" height="26" src="https://avatars.githubusercontent.com/u/88826436?s=52&amp;v=4"> ](/zikehalil3535)
> ## Footer
> [ ](https://github.com)
> © 2024 GitHub, Inc.
> ### Footer navigation
> * [Terms](https://docs.github.com/site-policy/github-terms/github-terms-of-service)
> * [Priv](https://docs.github.com/site-policy/privacy-policies/github-privacy-statement)

Sure,

https://www.youtube.com/watch?v=UrV3qSEJ6qM

You can check this video, all plugins is latest version.

**Comment by LeBlach** [comment]
The problem is caused by optifine.
My problem is not as in the video but as in this picture. If I log in with Vanilla 1.19.4 this problem does not exist.
![image](https://github.com/user-attachments/assets/c30fe6cb-7f3a-4dba-bcea-a02d9030ecc3)

**Comment by Godl1nk** [comment]
well same for me, i think its a confirmed issue

![image](https://github.com/user-attachments/assets/dbab2013-2da0-4026-ba90-aca5df27717c)

Some items darkened out
![image](https://github.com/user-attachments/assets/40522a25-5bb0-4e11-8f67-4c34589358ac)

happens after updating to latest ItemsAdder

**Comment by LoneDev6** [comment]
![image](https://github.com/user-attachments/assets/79a3afee-7a21-4e33-bfc5-27ce149fc0f3)

**Comment by zikehalil3535** [comment]
> ![image](https://private-user-images.githubusercontent.com/27242001/390330812-79a3afee-7a21-4e33-bfc5-27ce149fc0f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MDM1MDQsIm5iZiI6MTczMjcwMzIwNCwicGF0aCI6Ii8yNzI0MjAwMS8zOTAzMzA4MTItNzlhM2FmZWUtN2EyMS00ZTMzLWJmYzUtMjdjZTE0OWZjMGYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDEwMjY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5NTIzM2YwYWIxMzY1YTU2MjkyM2RlNTYyZDcwNWJkOGQ0ZWY3NzhmNWI4MjJlOWY0N2E5Yzk3NGY1ZTYwZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5dbcMZXpBCuvA1HiVwGplYCaz9-Xt7E4wUxX95gV-Vw)

I'm not using optifine, so somethings has occurred.

**Comment by LoneDev6** [comment]
> I'm not using optifine, so somethings has occurred.

try to join via vanilla client, if you are using mods

**Comment by zikehalil3535** [comment]
> > I'm not using optifine, so somethings has occurred.
> 
> Try to join via vanilla client, if you are using mods. I'd also check if you have any other pack custom shader installed.

Im already using vanilla client in this video.

**Comment by LoneDev6** [comment]
might be related to the GPU or GPU drivers.
can you join the Discord and open a private urgent ticket, then provide your server IP so that I can join and test?

**Comment by zikehalil3535** [comment]
> might be related to the GPU or GPU drivers. can you join the Discord and open a private urgent ticket, then provide your server IP so that I can join and test?

I tried with localhost (I have GPU) and with my vds (just have CPU) samething.
I will create ticket If you still want of course.

**Comment by ZzPowerTech** [comment]
Hello, I have a similar problem, and it only occurred after updating itemsadder to 4.0.4, but it only occurred on one of my servers.
![image](https://github.com/user-attachments/assets/6cc69523-be4f-41b7-b019-e555c5215ef0)
![image](https://github.com/user-attachments/assets/c95c5acb-2b2a-4250-b79d-f493881ee882)
![image](https://github.com/user-attachments/assets/f8f723bd-86dc-47d0-97d1-342e1f1d9753)

**Comment by zikehalil3535** [comment]
> > I tried with localhost (I have GPU) and with my vds (just have CPU) samething.
> > @zikehalil3535 I meant PC GPU, not server.
> > The Graphical card used to render the game.
> 
> Might be some new shader changes that are not compatible with all GPUs. Try to join with another PC and let me know. Or provide an IP I can join to test.

I already tried same issue with my friends PC.

**Comment by LoneDev6** [comment]
I joined a customer IP which have the issue and I can't reproduce it on my client.
This is indeed caused by an incompatibility with some GPU driver or a GPU hardware bug.

The only way for me to fix it is to ask you to join the beta testing and run the latest JAR, then run `/iazip` and test, as I can't do it because I cannot reproduce the issue on my PC.

**Comment by Godl1nk** [comment]
@LoneDev6 
![image](https://github.com/user-attachments/assets/cf7706a9-31ea-48d2-9f3f-62436c1d4d40)
there are still issue with enchantment glint which becomes dark, using 4.0.5

**Comment by LoneDev6** [comment]
Disable text effects and emotes and regenerate the resourcepack.
If the issue persists it means that it's caused by something else like a mod or a another resourcepack content not related to ItemsAdder.
Let me know.
