### ISSUE TITLE
Armor durability goes below 0

### ISSUE THREAD

**Issue by EimohPvP** [PluginBugs/Issues-ItemsAdder#4194]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

Eimoh

### What happened?

When creating a custom armor set, we use leather armor, and then proceed to change settings to make it replicate netherite armor. In this instance, we changed the durability. After changing the durability, I then proceeded to test the armor set by getting my armor low. On the players end, the armor goes into the negatives, and eventually breaks after it hits the netherite durability point... It leaves the armor like this: 
![image_2024-11-27_142418956](https://github.com/user-attachments/assets/6816d4ae-bf0b-4e1c-a3c1-b73bd92c06f0)

The server version is 1.21.3 (latest paper build), while also having the latest ViaVersion & ViaBackward  Builds. 
THIS BUG ONLY HAPPENS WHEN PLAYING ON 1.20.X, THIS BUG DOES NOT HAPPEN ON 1.21.3

### Steps to reproduce the issue

1. Server Version must be 1.21.3 with latest LoneLib & ItemsAdder
2. Be on Minecraft Version 1.20.1, 1.20.2, 1.20.3
3. Must have latest ViaVersion & Backwards Jars
4. Put on a custom armor set that inherits netherite attributes (must be originally leather armor)
5. Get attacked by a mob / player until armor goes negative.

### Server version

This server is running Paper version 1.21.3-63-master@4190ee7 (2024-11-25T18:59:19Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
You are 3 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21.3-56-bb32b05 (MC: 1.21.3)

### ItemsAdder Version

4.0.5-beta-3

### ProtocolLib Version

5.4.0-SNAPSHOT-736

### LoneLibs Version

1.0.61

### Full Server Log

https://mclo.gs/MkdpMes

### Screenshots/Videos (you can drag and drop files or paste links)

https://github.com/user-attachments/assets/e3997b32-d28c-42e8-8963-faab73d2fa8b

**Comment by LoneDev6** [comment]
This happens because 1.20.4 and lower doesn't have custom vanilla durability tags built in.
This is a bug of ViaVersion and they should address it.
Any other custom durability plugin will have this issue if they use the new max durability component of modern itemstacks.
