### ISSUE TITLE
Armor issues -> texture problem

### ISSUE THREAD

**Issue by pjindras** [PluginBugs/Issues-ItemsAdder#4200]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

detektiv_tank

### What happened?

I have resourcepack with some armors. They worked fine.

But now, I see the armor fine, but when I wear the armor, it's leather armor -> there is no texture.

/Iazip didn't help.
Server restart didn't help.

Clear pack installation didn't help.

There is no error in console.

### Steps to reproduce the issue

I have the same pack as always.
I have made /iazip, loaded pack.
When I take the armor, its leather.

### Server version

1.21.1 paper build #132

### ItemsAdder Version

ItemsAdder version 4.0.4

### ProtocolLib Version

ProtocolLib version 5.3.0

### LoneLibs Version

LoneLibs version 1.0.61

### Full Server Log

https://mclo.gs/IwJe7vg

### Problematic items yml configuration file (optional)

```yaml
IA config: https://mclo.gs/jahHZzf
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/user-attachments/assets/4208b86b-186f-4bd9-b137-706398d031ec)

**Comment by WaterArchery** [comment]
I have the same problem on paper 1.21.3 server.

**Comment by LoneDev6** [comment]
Enable vanilla resourcepack generation in `config.yml` and run `/iazip`

```yml
    generate-custom-armors-textures:
      vanilla: true
```
