### ISSUE TITLE
bug shaders effects

### ISSUE THREAD

**Issue by SrMonsterYT** [PluginBugs/Issues-ItemsAdder#4213]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

mauriciooficial

### What happened?

whenever I use shader files, people on 1.21x get a texture error, but if I go to 1.20.4 it works.

files: https://prnt.sc/fAKfjrNxo6Bg

when adding these 3 files inside assets/minecraft/shaders/core/players in 1.21x the texture crashes, but players in 1.20.4 works perfectly, if I remove these shader files, then 1.21x works

in the console it says there are duplicate files but there aren't, I'm using the default itemsadder without any texture, to make sure there are no duplicates

files shaders:

https://www.mediafire.com/file/kpsl9iy6e33v7xl/shaders.zip/file

### Steps to reproduce the issue

install shader files

### Server version

1.21-124-df3b654

### ItemsAdder Version

ItemsAdder_4.0.4

### ProtocolLib Version

ProtocolLib 5.4.0-SNAPSHOT-736

### LoneLibs Version

LoneLibs_1.0.61

### Full Server Log

no error

### Error (optional)

```shell
[13:07:53 WARN]: [Textura] File compression skipped: duplicate entry: assets/minecraft/shaders/core/rendertype_entity_translucent.vsh
[13:07:54 WARN]: [Textura] File compression skipped: duplicate entry: assets/minecraft/shaders/core/rendertype_entity_translucent.json
[13:07:55 WARN]: [Textura] File compression skipped: duplicate entry: assets/minecraft/shaders/core/rendertype_entity_translucent.fsh
```

**Comment by Andre601** [comment]
Please share your `latest.log` through https://mclo.gs as it help us getting all the necessary info required to solving this issue.

**Comment by SrMonsterYT** [comment]
> Please share your `latest.log` through https://mclo.gs as it help us getting all the necessary info required to solving this issue.

https://mclo.gs/wYD1ytw

**Comment by SrMonsterYT** [comment]
> Update to 4.0.5 and run /iazip. Let me know if it works. Fixed by #4177

I tested it on 1 private server, and now none of the versions work, not even 1.20.4 and 1.20.6, I also tested 1.21 and 1.21.1

video: https://youtu.be/KvTHyCgq9ss

ItemsAdder 4.0.5
LoneLibs 1.0.62

in previous versions at least it worked in 1.20.4

**Comment by Andre601** [comment]
LoneLibs was updated too, so make sure to update that

**Comment by LoneDev6** [comment]
Disable ItemsAdder emotes and run `/iazip` to regenerate the pack.
You can't have two packs that use the same shader enabled at the same time.

**Comment by SrMonsterYT** [comment]
> Disable ItemsAdder emotes and run `/iazip` to regenerate the pack. You can't have two packs that use the same shader enabled at the same time.

that didn't solve it

**Comment by LoneDev6** [comment]
@SrMonsterYT in this case you have another pack that uses shaders that are not compatible.
The latest beta of ItemsAdder 4.0.6 should mitigate this kind of issues by enabling `pre_1_21_2_shaders_fix` in `config.yml` and running `/iazip`.
