### ISSUE TITLE
Some textures disappear

### ISSUE THREAD

**Issue by Karuho** [PluginBugs/Issues-ItemsAdder#4215]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

karuho.

### What happened?

When I restart the server some textures disappear. I have tried the same texture, for example with Vegas, with a local server without itemsadder and it does not have this problem, but when placing it within content in IA the mentioned error occurs. This also happens with other textures, such as furniture or kitchen items, for example. How can I correct it?

I currently don't use the latest version because it doesn't work well with my server version, but it's a mistake I've always had with some textures for a long time.

### Steps to reproduce the issue

1. textures work
2. server restart
3. some textures disappear, for example casino machines, I have 8 and 6 disappear (they become invisible)
4. When you click on the invisible machine, which is an item made of a barrier, it releases the item normally but there are times where the surrounding item also becomes invisible

### Server version

This server is running Paper version 1.21.1-119-master@7cd4f2c (2024-10-03T15:19:34Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### ItemsAdder Version

4.0.2-beta-release-12

### ProtocolLib Version

5.3.0

### LoneLibs Version

1.0.59

### Full Server Log

https://mclo.gs/pWJ49kR

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/user-attachments/assets/5f268627-9f39-4423-aeac-411a4f4ebf79)

**Comment by Andre601** [comment]
Please use latest dependencies (LoneLibs) to see if the issue percists.

**Comment by Karuho** [comment]
> Please use latest dependencies (LoneLibs) to see if the issue percists.

itemsadder 3.6.6-legacy version is compatible with MC 1.21.1?

**Comment by Andre601** [comment]
Obviously not.

**Comment by Karuho** [comment]
> Obviously not.

I was wrong lol I was referring to 4.0.4 version

**Comment by LoneDev6** [comment]
Update to 4.0.4, do not use old versions
