### ISSUE TITLE
Option to disable plugin built-in text shaders in config

### ISSUE THREAD

**Issue by Fanfaryy** [PluginBugs/Issues-ItemsAdder#4226]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

fanfaryy

### Describe the solution you'd like

I would like it to be possible in the config to disable overwriting text shaders from packages with shaders from the plugin.

### Is your feature request related to a problem?

Yes, I can't add my own text effects because the plugin keeps overwriting them with its own ones.

### Describe alternatives you've considered

Restore the ability to not overwrite by simply disabling the "text-effects" option in config (which doesn't work after the update where the blinking effect was added)

**Comment by CarraGrive** [comment]
was about to report the same issue, would be great to have this fixed for the next released

**Comment by Flecksing** [comment]
Is this what's causing my text shaders not to load?

**Comment by LoneDev6** [comment]
It's a bug, will be fixed in the next update.
You will be able to disable that setting like before and regenerate your pack to apply the change.
