### ISSUE TITLE
ItemsAdder 4.0.5 is not compatible with the shader files in Mythichud.

### ISSUE THREAD

**Issue by CCjun6** [PluginBugs/Issues-ItemsAdder#4230]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

Interestingly, these shader files loaded correctly in ItemsAdder 4.0.3, but after upgrading to version 4.0.5, they fail to load.

I'm not sure what is causing this issue. Should Mythichud update these shader files, or should ItemsAdder make them compatible?

Therefore, I’ve decided to report this issue to both parties to pinpoint the cause and find a solution.

[rendertype_text.json](https://github.com/user-attachments/files/18081094/rendertype_text.json)
[rendertype_text.vsh.json](https://github.com/user-attachments/files/18081100/rendertype_text.vsh.json)

### Steps to reproduce the issue

1. Place the two shader files mentioned above into the shader folder.
2. Remember to remove .json from rendertype_text.vsh.json, as uploading .vsh files directly is not allowed.
3. Use ItemsAdder 4.0.5 and run /iazip to reproduce the issue.
4. Using ItemsAdder 4.0.3 and running /iazip will load successfully.

### Server version

1.21.1

### ItemsAdder Version

4.0.5

### ProtocolLib Version

5.3.0

### LoneLibs Version

1.0.62

### Full Server Log

https://mclo.gs/yBF87kn

**Comment by SrMonsterYT** [comment]
similar: https://github.com/PluginBugs/Issues-ItemsAdder/issues/4213

**Comment by LoneDev6** [comment]
Disable ItemsAdder emotes and run `/iazip` to regenerate the pack.
You can't have two packs that use the same shader enabled at the same time.
