### ISSUE TITLE
Blocks become invisible

### ISSUE THREAD

**Issue by Karuho** [PluginBugs/Issues-ItemsAdder#4232]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

karuho.

### What happened?

I had already reported it before and the same problem continues. Blocks made of any material become invisible upon server restart. For example, tables from the Vegas plugin, or even items like the ones I have made that are made of paper or other material become invisible and a barrier remains. I don't know how to solve this and players complain daily.

### Steps to reproduce the issue

1. Textures look and work.
2. I restart the server.
3.Some textures disappear or become barriers.

### Server version

This server is running Paper version 1.21.1-119-master@7cd4f2c (2024-10-03T15:19:34Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are 13 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21.1-128-d348cb8 (MC: 1.21.1)

### ItemsAdder Version

ItemsAdder version 4.0.4

### ProtocolLib Version

ProtocolLibs 5.3.0

### LoneLibs Version

LoneLibs version 1.0.61

### Full Server Log

https://mclo.gs/MR8sXW6

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/user-attachments/assets/499ba761-9996-4609-bfbc-8261caba203e)
![image](https://github.com/user-attachments/assets/52dab4d6-00ec-4b62-8790-dcb5e77ccdac)
![image](https://github.com/user-attachments/assets/7a96a040-0c6e-4eff-87e0-12d983df5c00)
![image](https://github.com/user-attachments/assets/f4c28459-fbe5-4470-a7e9-28754b998d7a)

**Comment by Andre601** [comment]
Please test if this issue appears on a **bare-bones Server Setup** as described in https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187 to eliminate any possability of other plugins causing this problem.

Also, while not likely the issue, try updating your server to the latest 1.21.1 build, which seems to be 132 (You can find it in Paper's [Build Explorer](https://papermc.io/downloads/all))

**Comment by Andre601** [comment]
Also, unrelated to ItemsAdder, but please don't use leaked plugins.
Not only is it rude against the developer to put it mildly, but it opens up risks of infecting your server with malware, as the leaker could just inject malicious code if they wanted.

I've noticed you use leaked versions of the following plugins:

- `HeadDatabase`: https://mclo.gs/MR8sXW6#L458
- `PinataParty`: https://mclo.gs/MR8sXW6#L1310
- `MobFarmManager`: https://mclo.gs/MR8sXW6#L1494
- `RealisticSeasons`: https://mclo.gs/MR8sXW6#L1654
