### ISSUE TITLE
1.20.4 problem

### ISSUE THREAD

**Issue by serpentoi2** [PluginBugs/Issues-ItemsAdder#4235]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

don't have discord :(

### What happened?

keep spammiing on console

### Steps to reproduce the issue

on bedrock geyser when do shifting it gives warning same with the java

### Server version

1.20.4 paper mc

### ItemsAdder Version

latest legacy for 1.20.4 V3.6.6

### ProtocolLib Version

Protocolib 5.20 and tried 5.30 aswell

### LoneLibs Version

Lonelibs [1.0.61] and Lonelibs [1.0.62]

### Full Server Log

https://mclo.gs/AexnKzL

### Screenshots/Videos (you can drag and drop files or paste links)

![Screenshot 2024-12-12 143258](https://github.com/user-attachments/assets/5e3b7e16-a8fd-4c7a-8ef0-c36f17a84bc0)

**Comment by Andre601** [comment]
You didn't provide the full latest.log as requested.
