### ISSUE TITLE
Im getting an error

### ISSUE THREAD

**Issue by alicanerdas** [PluginBugs/Issues-ItemsAdder#4255]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

nightslear

### What happened?

I am getting crash message with itemsadder

### Steps to reproduce the issue

i dont understand this

### Server version

1.20.6

### ItemsAdder Version

4.0.5

### ProtocolLib Version

5.3.0

### LoneLibs Version

1.0.62

### Full Server Log

https://mclo.gs/Dxl6SyS

**Comment by Andre601** [comment]
Please test if this issue appears on a **bare-bones Server Setup** as described in https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187 to eliminate any possability of other plugins causing this problem.

**Comment by LoneDev6** [comment]
This is not caused by ItemsAdder, also other plugins are shown in your error log stating the same thing.
