### ISSUE TITLE
1.21.3 when using the resource pack I become invisible

### ISSUE THREAD

**Issue by belzzebuh** [PluginBugs/Issues-ItemsAdder#4256]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

when you enter and I load the texture pack you become invisible to you and the other players, besides if I place an item in my hand it is also removed.

### Steps to reproduce the issue

idk

### Server version

This server is running Paper version 1.21.3-81-master@da71382 (2024-12-03T14:58:13Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
You are running the latest version

### ItemsAdder Version

ItemsAdder version 4.0.5

### ProtocolLib Version

ProtocolLib version 5.4.0-SNAPSHOT-738

### LoneLibs Version

LoneLibs version 1.0.62

### Full Server Log

https://mclo.gs/wCYVLou

### Error (optional)

```shell
nothing error in console
```

**Comment by LoneDev6** [comment]
```
[00:51:08] [Server thread/INFO]: [ItemsAdder] Loading server plugin ItemsAdder v4.0.5
[00:51:08] [Server thread/WARN]: [ItemsAdder] 'apply_on_join' and 'apply_during_chunk_load_phase' are both enabled. Please, disable one of them.
```

Please enable `apply_during_chunk_load_phase` and disable `apply_on_join.enabled`.

**Comment by Robiakg5** [comment]
I encountered the same issue, including problems with the "apply_during_chunk_load_phase" method not properly applying the texture pack.

I resolved it by using the "apply_on_join" method with a delay of 500 ticks.

I'm not sure what caused the problem, but I’m also using "EliteMobs", which likely applies a custom texture pack using the same "apply_on_join" method.
