### ISSUE TITLE
Hash mismatch error when downloading resource pack via self-host

### ISSUE THREAD

**Issue by whiskeytr** [PluginBugs/Issues-ItemsAdder#4274]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [X] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

whiskeytr

### What happened?

Failed to download https://pack.gladiomc.com/generated.zip  
Hash of downloaded file (249f1874a9998ef6833535a0b1cf04802de6e3d8) did not match requested (f3678f9daedecc20d499a8de4399600eaf22e62c)

Despite running /iazip and ensuring the generated resource pack is updated, the hash mismatch persists.

### Steps to reproduce the issue

Enable self-host in the ItemsAdder config.yml:
resource-pack:
  hosting:
    self-host:
      enabled: true
      server-ip: https://pack.gladiomc.com
Run /iazip to generate a new resource pack.
Confirm the generated.zip file is updated in plugins/ItemsAdder/output/.
Connect to the server using the Minecraft client.
Observe the hash mismatch error in the client logs, and the resource pack fails to download.

### Server version

This server is running Pufferfish version 1.21.1-21-HEAD@cfa3c61

### ItemsAdder Version

ItemsAdder version 4.0.6

### ProtocolLib Version

ProtocolLib version 5.4.0-SNAPSHOT-738

### LoneLibs Version

LoneLibs version 1.0.63

### Full Server Log

No Logs Needed

### Error (optional)

```shell
The generated.zip file's SHA-1 hash matches the expected hash (f3678f9daedecc20d499a8de4399600eaf22e62c) when checked locally.
However, the file served via the domain (https://pack.gladiomc.com/generated.zip) has a different hash (249f1874a9998ef6833535a0b1cf04802de6e3d8).
Using Cloudflare as a CDN for the resource pack. Suspecting a caching or file corruption issue, but unable to resolve it despite purging the cache and re-uploading the file.
Let me know if more information or logs are required!
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/user-attachments/assets/08d5d0b4-c04e-435d-9e6b-659cb6e99386)
![image](https://github.com/user-attachments/assets/8e5b5176-d8ee-4318-9dbf-a903d834e812)

**Comment by Andre601** [comment]
I tested myself using v4.0.6 on 1.21.4 and it works just fine for me when using selfhost.

Such an issue usually indicates that the file got modified somewhere. I suggest trying the direct IP and port of your server instead of a domain, to see if this mismatch remains.

**Comment by Andre601** [comment]
Also: "No logs needed" is an invalid reply here. As stated clearly in the template are we requesting logs for a reason, and it's not your job to decide wether we need them or not.
So please provide your full latest.log via mclo.gs

**Comment by whiskeytr** [comment]
> Such an issue usually indicates that the file got modified somewhere. I suggest trying the direct IP and port of your server instead of a domain, to see if this mismatch remains.

After change the port and domain it will works thank you <3
