### ISSUE TITLE
[Suggestion] Customs animations with mythic mobs

### ISSUE THREAD

**Issue by EgidioBezerra** [PluginBugs/Issues-ItemsAdder#429]
A better integration with mythic mobs, where mobs with custom AI from MythicMobs could trigger a custom animation something like that:

```
Master:
  Type: zombie
  Skills:
  - skill{s=Spell} @NearestPlayer ~onDamaged
```
```
Spell:
  Skills:
  - animationsignal{s=Spell} @Self
  - delay 5
  - shoot{t=arrow}
```

Something just like that, mythicmobs sends a signal to your plugin, telling to activate a custom animation. You could work with mythicmobs dev or with [MythicMobsExtention](https://github.com/BerndiVader/MythicMobsExtension) dev to make this real , it could make your plugin almost limitless. 

Something similar to that plugin [DemoModel](https://www.spigotmc.org/resources/demomodel.68015/) - [Wiki](https://gitlab.com/Ticxo/ModelAPI/-/wikis/Crash-Course/%5B4%5D-Mythic-Mobs-Integration) - [SRC](https://gitlab.com/Ticxo/ModelAPI/-/tree/master/src/com/ticxo/modelapi/api/mythicmobs) or [Model Engine](https://www.spigotmc.org/resources/conxeptworks-model-engine%E2%80%94ultimate-entity-model-manager-1-14-1-16-3.79477/)

Sorry if i couldn't make myself very clear, english isn't my first language.

**Comment by ArgonGaming** [comment]
Agree on this

**Comment by avatario** [comment]
yes please!

**Comment by LoneDev6** [comment]
Currently ModelEngine is used by a lot of servers and earned a lot of notoriety, but at the same time I heard its dev is not trusted by some of his customer, so in the future I might code my own version of ModelEngine and bundle it inside ItemsAdder.

Only time will tell.
