### ISSUE TITLE
[BUG] Missing knockback information in lore

### ISSUE THREAD

**Issue by LoneDev6** [PluginBugs/Issues-ItemsAdder#448]
> Properties are not displayed
knockbackResistance Can you add his translation? 
(HoneyBearc)

**Comment by yebanme** [comment]
attackSpeed maxHealth movementSpeed Can't show on armor

**Comment by LoneDev6** [comment]
can you set this in config.yml and then get the item again using /iaget.
`fix-show-attack-and-damage-as-lore: false`


let me know.

**Comment by yebanme** [comment]
> can you set this in config.yml and then get the item again using /iaget.
> `fix-show-attack-and-damage-as-lore: false`
> 
> let me know.

My problem has been solved. Thank you
