### ISSUE TITLE
[Suggestion] EcoEnchants Compatibility 

### ISSUE THREAD

**Issue by ArgonGaming** [PluginBugs/Issues-ItemsAdder#461]
It would be awesome to have the ability to add custom enchants in general, or at least from this plugin into Custom Items instead of just adding vanilla enchants!

**Comment by zainmz** [comment]
It already works, just enchant the custom enchants using cmi/essentials onto the custom item.

**Comment by LoneDev6** [comment]
Is there any API for this plugin?
To get enchants and apply it to the items

**Comment by zainmz** [comment]
https://ecoenchants.willfp.com/developers/api

**Comment by LoneDev6** [comment]
Thanks

would be nice to get a proper example to avoid losing time testing stuff as the API is basically the EcoEnchants full plugin code..

For example here I can see a method to get enchant by name: https://github.com/Auxilor/EcoEnchants/blob/master/eco-core/core-plugin/src/main/java/com/willfp/ecoenchants/enchantments/EcoEnchants.java#L505

would be good to know if it's correct to use this method and how can I apply the enchant to an ItemStack
