### ISSUE TITLE
[Suggestion] Can't add Nameplates to ItemsAdder?

### ISSUE THREAD

**Issue by mA0w0** [PluginBugs/Issues-ItemsAdder#474]
I found a plugin that is very suitable for a great server.

Nameplates »Completely Unique Customization Mechanic 1.0.2
https://www.spigotmc.org/resources/nameplates-%C2%BB-completely-unique-customization-mechanic.84797/

I thought that being able to customize suffix and prefix means that nameplates are also possible.

It seems that Nameplates also use textures, so I thought it would be possible to do the same with ItemsAdder.

**Comment by LoneDev6** [comment]
Totally doable and really easy to be added, they are just font_images in itemsadder, exactly as emojis and guis

**Comment by mA0w0** [comment]
I made a sample, so please tell me how to configure it with items adder.

I would like to know how to assign it to a name background like the Nameplates plugin.

![sample](https://user-images.githubusercontent.com/72402669/98286186-f0556700-1fe6-11eb-9852-2eb0d4f12b89.png)

**Comment by mA0w0** [comment]
Oh, I've come to understand it.

Do I have to engrave my name on the image?

I engraved the name on the image, but it is difficult to read like the image because the number of pixels is low.

Is there any improvement by lowering the pixel-rich image with scale_ratio?

Is it possible to display the name automatically like the Nameplate plugin?

name-template:'% player_name%'
I want a function like this.
https://itsnathang.me/plugins/nameplates/#/configuration?id=name-template

If you are using the CMI or NickName plugin, you need to replace the name display,
such as'% cmi_user_display_name%'.
![2020-11-06_06 25 35](https://user-images.githubusercontent.com/72402669/98298619-a4f88400-1ff9-11eb-9001-76ab4ca8fd63.png)

**Comment by ArgonGaming** [comment]
This would be an awesome feature to have with similar examples to that plugin! (:

**Comment by ArgonGaming** [comment]
The plugin referenced actually increased their price now LMAO

**Comment by mA0w0** [comment]
Is it possible to fix the ID like an item?
model_id: 10001
font_id: 10001

**Comment by LoneDev6** [comment]
> 
> 
> The plugin referenced actually increased their price now LMAO

Too much for just a tags plugin.
Anyway anyone can create these tags with itemsadder, i hope someone will as I currently have no time.


> 
> 
> Is it possible to fix the ID like an item?
> model_id: 10001
> font_id: 10001

yes.

```
  mc_acacia_boat:
    permission: mc_acacia_boat
    show_in_gui: true
    path: "font/minecraft_emoji/mc_acacia_boat.png"
    scale_ratio: 9
    y_position: 8
    manual_character: "⡧"
```

Keep in mind that this feature is not supposed to be used by everyone as I don't really find good to specify that id manually which can lead to problems if you share your addon online and someone uses the same ID.

Also keep in mind that this doesn't support every character but only characters made with only 1 characeter. For example some emoji and some japanese symbols are made of multiple characters internally, so it won't work.

**Comment by mA0w0** [comment]
> Do I have to engrave my name on the image?
I engraved the name on the image, but it is difficult to read like the image because the number of pixels is low.
Is there any improvement by lowering the pixel-rich image with scale_ratio?
Is it possible to display the name automatically like the Nameplate plugin?
name-template:'% player_name%'
I want a function like this.
https://itsnathang.me/plugins/nameplates/#/configuration?id=name-template
If you are using the CMI or NickName plugin, you need to replace the name display,
such as'% cmi_user_display_name%'.

What about this?

**Comment by ElMoha943** [comment]
> 

Could you make it work for any nickname? if so, could you explain how? thanx in advance.

**Comment by HzDeimos** [comment]
Are there any ways to do this with the current version of ItemsAdder. If not I would really like this to be a feature.

The plugin is now 13 dollars and it is unactive in spigot rn.

**Comment by LoneDev6** [comment]
[Here](https://polymart.org/resource/customnameplates.2543) is an alternative even though seems to have more features than required, so it might feel a bit bloated for some users.
It also is a bit expensive, but there is no other alternative as I'm aware.
I might work on something in the future.
