### ISSUE TITLE
[Suggestion] More Customization for Items

### ISSUE THREAD

**Issue by ArgonGaming** [PluginBugs/Issues-ItemsAdder#492]
**Is your feature request related to a problem? Please describe.**
I believe there is too little customization features with custom items for a plugin that advertises a truly unique and configurable experience

**Describe the solution you'd like**
One would be the compatibility with other popular enchant plugins (in order to enchant items with these custom enchants) 
And the other would be mimicking another similar plugin's level of customization: (https://docs.oraxen.com/configuration/available-mechanics)

**Describe alternatives you've considered**
One would be the compatibility with other popular enchant plugins (in order to enchant items with these custom enchants) This allows for easy access of adding more customization and abilities to items without using additional "MMO" plugins. This would be neat to add regardless.

**Comment by LoneDev6** [comment]
It's not really clear what you need and how the link it's related.
If you need enchants compatibility send me the plugin you want me to implement compatibility for and i'll try to add it

**Comment by LoneDev6** [comment]
https://itemsadder.plugin.ga/plugin-usage/adding-content/advanced/item-properties/basic#enchants

**Comment by ArgonGaming** [comment]
Old suggestion, but here is a good enchants plugin to add compatibility for https://www.spigotmc.org/resources/%E2%9A%A1-1-16-1-16-5-ecoenchants-%E2%9C%A8-220-custom-enchantments-%E2%9C%85-essentials-cmi-support.79573/

**Comment by LoneDev6** [comment]
Hello,, should already work fine as stated in the link I sent before
