### ISSUE TITLE
[Suggestion] Per arrow damage

### ISSUE THREAD

**Issue by SlavWithin** [PluginBugs/Issues-ItemsAdder#514]
My original message on spigot:

"Hello,

Have you considered adding custom arrow damage? So for example we could have an "iron arrow" custom item that does different damage from the default arrow. I know this is extremely hard to do from a command standpoint because it requires changing all arrows, or checking until arrow is shot and then changing it, so being able to do this from this plugin instead of having to rely on custom skript items would be a huge relief. "

Your response:

"This is a very cool suggestion, please post it on github "

Hence, this post.

To elaborate further, the only way to do custom arrows (and they are possible, I have achieved it through Skript) is by creating both a custom arrow entity and a custom arrow item. 

The custom arrow item is crafted via a custom recipe and only used to contain some tag which communicates what the custom arrow entity data will be once the bow is fired. Until the bow is fired, it is just a regular arrow with a weird data tag, nothing special. If the other parts of the skript did not exist, it would just get fired like a regular arrow. This is because you can't define arrow damage and velocity from the arrow item, but only after it is shot. Well, you can, but you have to change it for *all* arrows which defeats the point of having custom arrows.

Once a bow is fired by a player, a skript checks which arrow was used by checking all the inventory slots until it finds the first arrows in the order Minecraft chooses which arrows to fire. 
The tag mentioned before is checked by the skript; if it doesn't exist on the selected arrow item, do nothing. If it does exist and it is a match for an arrow type, then you change the arrow in flight's values to reflect the custom arrow via skript. For example, if the custom arrow item's tag is "iron arrow", a custom arrow item I made craftable using iron nuggets instead of flint, it increases damage by a certain amount the same way the Power enchant increases it. Velocity changes are optional and possible, but I haven't done them personally.

This is how I did it. It'd be really cool to be able to do it via this plugin as it'd be much less of a hassle.

Also; I made it so arrows can't be picked up because unfortunately once you pick up the arrow all the data is lost... another reason why I'd love to see you take a crack at this, maybe you can solve that so I don't have to make all the arrows be unpickupable after hitting something. :)

Creating custom arrow textures / models I think is impossible without changing all of them, but I am not requesting that. Just being able to create arrows with custom stats would be more than enough for me and I imagine a lot of other people.

**Comment by lubek-dc** [comment]
im think its good (im not staff)

**Comment by LoneDev6** [comment]
i will post an update this week, more info here: https://itemsadder.plugin.ga/plugin-usage/adding-content/beginners/creating-a-custom-item/magic-wand/custom-arrows#some-examples-itemsadder-2-2-7
