### ISSUE TITLE
[BUG] Custom mobs despawning

### ISSUE THREAD

**Issue by Jirsaacek** [PluginBugs/Issues-ItemsAdder#541]
**Describe the bug**
When player have custom mob, and name him with nametag, it still after some time converts back to normal mob, I think it should stay custom mob until it is killed (Possibly a option in config to turn that on and off?) :D

**To Reproduce**
1. Get custom mob
2. Name him with nametag
3. Wait
4. After some time it turns back to vanilla mob

**Expected behavior**
It should stay custom, so players can have ZOOs for example :D

**Info (please complete the following information):**
Tuinity version git-Tuinity-"8056d13" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

ItemsAdder version 2.1.21

**Comment by LoneDev6** [comment]
This is definitely not intended behaviour.
Make sure you're using the latest Libsdisguises https://ci.md-5.net/job/LibsDisguises/
Also make sure you're using the latest ProcolLib https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
And if this still happens please use Paper or normal Spigot and check if the issue occurs anyway.

Let me know, thanks

**Comment by LoneDev6** [comment]
Waiting for news

**Comment by Jirsaacek** [comment]
Sorry, I forgot xD
I think everything is ok on our side 

![unknown](https://user-images.githubusercontent.com/63473875/102633900-5d652c00-4151-11eb-8d88-677eb1cd7f20.png)
![unknown-2](https://user-images.githubusercontent.com/63473875/102633904-5e965900-4151-11eb-82a5-285f7dae975d.png)

**Comment by LoneDev6** [comment]
Are mobs still losing their custom skin? Or was it resolved?
