### ISSUE TITLE
[BUG] ItemsAdder Seemingly Causing Login Errors for Certain Users

### ISSUE THREAD

**Issue by MandMDub** [PluginBugs/Issues-ItemsAdder#553]
**Describe the bug**
After implementing ItemsAdder into our Production survival server multiple users have reported receiving "ReadTimeoutException: null" errors on login. Players only receive this error when moving from our Hub to our Survival Server (That is currently running ItemsAdder). The following client logs appear as well: https://pastebin.com/BYz8Lgpg. I have spoken to sircraftypants for the past week reviewing our current ymls and resource pack setup, and all are correct. The above pastebin is from my personal MultiMC client utilizing optifine on 1.16.4. Other players have had issues from both vanilla with the vanilla launcher and with the fabric optimizer.

**To Reproduce**
1. User logs into the network
2. User switched servers from non itemsadder server to server with itemsadder installed
3. The user connects and the client begins to download the texture pack.
4. During the texture pack download screen the client will be disconnected for the server and display a "ReadTimeoutException: null" error

**Expected behavior**
Players are expected to be able to join the minecraft network and switch between itemsadder and non itemsadder servers with the texture pack loading and unloading as needed.

**Screenshots**
https://media.mdub.tech/czKxSnIwtL
https://pastebin.com/BYz8Lgpg (MultiMC w/ Optifine 1.16.4)
https://pastebin.com/2vDTJi6q (Vanilla Launcher w/ 1.16.4)

**Info (please complete the following information):**
 - Server version: Tuinity 1.16.4 & AirplaneLite 1.16.4
 - Client version: OptiFine 1.16.4 and Vanilla 1.16.4
 - Plugin version: 2.1.20

**Additional context**
Both server and proxy logs just show the player logging on and disconnecting from the server without any other information being displayed. sircraftypants and I have double and triple checked both the resource pack and the yml files for the plugin and don't see an issue with either of them.

**Comment by LoneDev6** [comment]
Hello,
Do they still get kicked out if you set `apply-on-join: false` and then asking your players to join?
Does this happens to every player or only some players?
Did that start happening randomly or do you remember if you changed anything?

I also need you to check if the bungeecord logs contain anything about that problem.

Thanks

**Comment by MandMDub** [comment]
Greetings,
I will do some testing this morning with the `apply-on-join: false` setting and get back to you on this one. I am pretty sure we have tested, and that this removed the issue, but I will double-check that. The players affected seem to be different every day, and it is mostly random, but when the player is affected by it, they seem to then have a reoccurring of it a lot more often. This error started happening immediately after adding Item Adder to this server.

Bungeecord doesn't state anything other than that they joined and disconnected from the proxy, but I can also gather these logs for you if you would like.

**Comment by LoneDev6** [comment]
For sure, logs would be helpful.
You can continue this discussion via SpigotMC private message to share sensitive data (bungee logs)

**Comment by MandMDub** [comment]
It doesnt seem like I am able to start a conversation on spigot with you. My spigot profile is https://www.spigotmc.org/members/mandmdub.56861/ or you can add me on discord at MandMDub#4391

**Comment by LoneDev6** [comment]
> 
> 
> It doesnt seem like I am able to start a conversation on spigot with you. My spigot profile is https://www.spigotmc.org/members/mandmdub.56861/ or you can add me on discord at MandMDub#4391

pinged you on discord server
