### ISSUE TITLE
[Suggestion] Use Noteblocks For Real Blocks

### ISSUE THREAD

**Issue by RefioWasTaken** [PluginBugs/Issues-ItemsAdder#579]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Using note blocks as real blocks would add many possibilities for real blocks, though normal note blocks should be disabled.(It can be done Origin Realms done it)
**Describe alternatives you've considered**
Also using tripwires to add new small blocks without hitbox could be a possibility
**Additional context**
![image](https://user-images.githubusercontent.com/42711375/104123177-3239bb00-5352-11eb-8493-8692c62072c4.png)
![image](https://user-images.githubusercontent.com/42711375/104123189-44b3f480-5352-11eb-9558-3d7d1292f19f.png)

**Comment by LoneDev6** [comment]
noteblock: implemented some updates ago
string/tripwire: https://github.com/PluginBugs/Issues-ItemsAdder/issues/741
