### ISSUE TITLE
[Suggestion] MMOitems Support

### ISSUE THREAD

**Issue by ElMoha943** [PluginBugs/Issues-ItemsAdder#585]
Both MMOitems and ItemsAdder are powerful plugins with excellent features, but you cant use both of them togheter. ItemsAdder does not support mmoitems/mmocore stats in their items and mmoitems does not support using items made with itemsadder as base for new items, drops, loottables, etc.

Possible solutions/features:
- An extra config for items where you could set mmoitems stats for itemsadders items.
- Support for dropping mmoitems from items adders blocks
- Support for crafting itemsadders items with mmoitems items and viceversa.

**Comment by RickyLaChow** [comment]
Add ItemsAdder can use MMOitems Models and MMOitems can use ItemsAdder models?

**Comment by ElMoha943** [comment]
Feature was added, thanx Lone :D

**Comment by LoneDev6** [comment]
> 
> 
> Feature was added, thanx Lone :D

no problem ;)
