### ISSUE TITLE
[BUG] Custom crops yield bug

### ISSUE THREAD

**Issue by SlyJacobTheBeast** [PluginBugs/Issues-ItemsAdder#597]
**Describe the bug**
Vanilla crops randomly yield custom crops to players (crops already included in the plugin like garlic, tomato, rice) even though a vanilla seed was planted.

**To Reproduce**
I tried to reproduce the bug without a success, but the issue was reported by many players to me by now its hard not to believe it. It seems that whenever I visit their place and they plant it all again, it doesn't bug anymore.  I wonder if it has to do with OP / permission thing?

**Expected behavior**
Vanilla crops = vanilla yield (wheat seeds > wheat crop > wheat)

**Info (please complete the following information):**
 - Server version:paper 1.16.4
 - Client version: vanilla
 - Plugin version: 2.1.25

**Comment by LoneDev6** [comment]
Very strange.
Make sure to run the latest ItemsAdder, LoneLibs, Paper and let me know how it goes.
Also check if you have any error in console

**Comment by SlyJacobTheBeast** [comment]
There were no console errors, I've just updated everything to their latest versions, including paper 1.16.5. Will see if it still happens.

**Comment by LoneDev6** [comment]
Let me know, thanks a lot, I wait for your answer

**Comment by SlyJacobTheBeast** [comment]
According to the players it is still happening. Vanilla crops beetroot yielded rice. No errors in console.

**Comment by LoneDev6** [comment]
> 
> 
> According to the players it is still happening. Vanilla crops beetroot yielded rice. No errors in console.

Strange.. well I made a video just to show why I have no idea why it happens on your server and not on my test environment.
(I also tried with beetrootseeds)
https://www.youtube.com/watch?v=HS1A4CLMgGs

**Comment by SlyJacobTheBeast** [comment]
> > According to the players it is still happening. Vanilla crops beetroot yielded rice. No errors in console.
> 
> Strange.. well I made a video just to show why I have no idea why it happens on your server and not on my test environment.
> (I also tried with beetrootseeds)
> https://www.youtube.com/watch?v=HS1A4CLMgGs

I should have mentioned it has to be naturally grown, when bone meal is used, it works for players. As I mentioned, I couldn't reproduce the bug even with naturally grown crops, maybe try without op permission?

**Comment by SlyJacobTheBeast** [comment]
@LoneDev6 Another player reported the same bug with the following description:
I planted blueberries in the same air blocks previously, so it may have something to do with that. It's just: I planted carrots and potatoes, but when I harvested them I got blueberries. It kept the crop texture for carrots and potatoes, and hwyla still showed it as carrots and potatoes.

**Comment by LoneDev6** [comment]
> 
> 
> @LoneDev6 Another player reported the same bug with the following description:
> I planted blueberries in the same air blocks previously, so it may have something to do with that. It's just: I planted carrots and potatoes, but when I harvested them I got blueberries. It kept the crop texture for carrots and potatoes, and hwyla still showed it as carrots and potatoes.

I have to investigate on this, that's a very strange behaviour, never got a report about that until now

**Comment by 100petr** [comment]
I have the same problem. 
![image](https://user-images.githubusercontent.com/29830635/107874602-f2b73f00-6eba-11eb-9d5a-2b5871bca7ae.png)
![image](https://user-images.githubusercontent.com/29830635/107874608-fa76e380-6eba-11eb-9172-726b9a05f696.png)
But it rarely happens
https://youtu.be/geqrXJNr5H0
https://youtu.be/pHk91m3uEWY

**Comment by LoneDev6** [comment]
I think I successfully managed to reproduce the issue and fix it.
I will post an update this week!
Thanks a lot :D
