### ISSUE TITLE
[BUG] Vehicles Bug

### ISSUE THREAD

**Issue by Venterok** [PluginBugs/Issues-ItemsAdder#598]
**Describe the bug**
When you click on the refueled transport, the player disappears from the server, can not break/build and do anything. To fix it, you need to re-upload it to the server

**To Reproduce**
1. Spawn Vehicle
2. We fill it up
3. Right click on transport
4. See error in console & game

**Expected behavior**
The player can not do anything in the world, it is not seen by other players

**Screenshots**
https://imgur.com/Hnw7Ykm

**Info (please complete the following information):**
 - Server version: PurPur 1.16.4 & Paper 1.16.4 (i tried any core/ver)
 - Client version: Fabric 1.16.4
 - Plugin version: 2.1.27

![image](https://user-images.githubusercontent.com/67825103/105330354-3c29ac80-5be3-11eb-956a-c729443c1cc0.png)

**Comment by LoneDev6** [comment]
I think it's related to these issues, can you confirm?
https://github.com/PluginBugs/Issues-ItemsAdder/issues/218
https://github.com/PluginBugs/Issues-ItemsAdder/issues/226

**Comment by Venterok** [comment]
We don't use residence/towny, I can send a list of plugins if needed. And yes, I have the same mistake, all right

**Comment by LoneDev6** [comment]
> 
> 
> We don't use residence/towny, I can send a list of plugins if needed. And yes, I have the same mistake, all right

Sure send the plugins list thanks a lot.
Can you also test the plugin on normal spigot 1.16.4? https://serverjars.com/api/fetchJar/spigot/1.16.4
Thanks and let me know

**Comment by Venterok** [comment]
In spigot 1.16.4 the error still remains
And a new error appeared in the console https://pastebin.com/ccsRLEBT

![image](https://user-images.githubusercontent.com/67825103/105346599-dfd08800-5bf6-11eb-8c6a-8955d7ef1786.png)

**Comment by Venterok** [comment]
how do i solve this?

**Comment by LoneDev6** [comment]
Seems to be a spigot bug: https://hub.spigotmc.org/jira/browse/SPIGOT-5710
You can ignore the POI mismatch error, but it's strange that "The player can not do anything in the world, it is not seen by other players", I tested that on my 1.16.5 server and everything works fine.

Can you try removing all the plugins temporarily (keep only itemsadder, lonelibs, protocollib) and check if the issue occurs? (you can put them in a separate folder without deleting the jars)

If not, then you have to add one plugin at time and see which one is incompatible, please let me know if you find it.

thanks for the patience

**Comment by Venterok** [comment]
I found the problem. Vehicle does not work together with the "MobFarmManager" plugin https://www.spigotmc.org/resources/mob-farm-manager-supports-1-7-10-up-to-1-16-hopper-support.15127/

**Comment by LoneDev6** [comment]
> 
> 
> I found the problem. Vehicle does not work together with the "MobFarmManager" plugin https://www.spigotmc.org/resources/mob-farm-manager-supports-1-7-10-up-to-1-16-hopper-support.15127/

I think the mob farm manager is removing my custom vehicle seat, which is a slime.
Can you check if you have any limit set for slimes?


Thanks! Please let me know

**Comment by LoneDev6** [comment]
Waiting for an answer, thanks! :D
