### ISSUE TITLE
resourcepack download multiple times in selfhosting[BUG] 

### ISSUE THREAD

**Issue by Caishangqi** [PluginBugs/Issues-ItemsAdder#599]
**Describe the bug**

The resource pack downloads multiple times when logging in to the server.
When I logging into the server, the resource pack would download into a folder: server-resource-packs, and after you rejoin the server, it would download the same resource pack but a different sha value.

However, when I use the Itemadder in my localhost 127.0.0.1, the resource pack won't download multiple times.

There is no error in the console.
**To Reproduce**
config:
https://paste.ubuntu.com/p/7PPHhdCkZp/
data.yml
`latest-resourcepack-sha1: ''
`

**Expected behavior**
It should download only once, and the client should use the downloaded one to join the game.

**Screenshots**
![image](https://user-images.githubusercontent.com/39553613/105351187-1380c300-5ba1-11eb-9b91-68ab8cc8496b.png)

**Info (please complete the following information):**
 - Server version: 1.16.4
 - Client version: 1.16.4
 - Plugin version: 2.1.23

**Comment by LoneDev6** [comment]
Can you try changing the port in config.yml and restart the server, let me know if it happens again

**Comment by SlyJacobTheBeast** [comment]
Had this happen as well recently, though I haven't checked teh locations mentioned. The resource pack simply downloaded twice in row when joining. Nothing changed on our side, still self hosted on the same address.

**Comment by Caishangqi** [comment]
> Can you try changing the port in config.yml and restart the server, let me know if it happens again

it works well now, it only downloads 1 resoucepack in the folder, but the player must load twice before log in to the server.

**Comment by LoneDev6** [comment]
Very strange situation, did you try to restart the server? Does it fix the issue?
Let me know

**Comment by SlyJacobTheBeast** [comment]
I have changed the port and it seems to have fixed it.

**Comment by Caishangqi** [comment]
> Very strange situation, did you try to restart the server? Does it fix the issue? I have an hypothesis
> Let me know

I had update to the last version of IA, the problem seems fixed :)

**Comment by LoneDev6** [comment]
Very good!
