### ISSUE TITLE
[Suggestion] Change the name of the resource pack zip file

### ISSUE THREAD

**Issue by YouHaveTrouble** [PluginBugs/Issues-ItemsAdder#602]
Self host works perfectly on localhost, but when clients download the resource pack from remote server it hashes its name.
This hash is then used to load resource packs without redownloading them.

Issue is: when name of the resource pack zip doesn't change and the changes are minimal (replaced file or line in config) the hash doesn't change and clients are stuck with outdated resource pack after `/iazip`. Simply replacing pack.rar with <random-uuid>.jar after /iazip should do the trick.

**Comment by YouHaveTrouble** [comment]
The workaround for this is to manually delete hashed resource pack from .minecraft/server-resource-packs, but imagine having to explain this to an average minecraft player.

**Comment by LoneDev6** [comment]
> 
> 
> Self host works perfectly on localhost, but when clients download the resource pack from remote server it hashes its name.
> This hash is then used to load resource packs without redownloading them.
> 
> Issue is: when name of the resource pack zip doesn't change and the changes are minimal (replaced file or line in config) the hash doesn't change and clients are stuck with outdated resource pack after `/iazip`. Simply replacing pack.rar with .jar after /iazip should do the trick.

Yea the only way is to "force" the redownload of the resourcepack when you make a modification, just ask the player to use /iatexture command when you edit the resourcepack, maybe announce it via broadcast or via Discord @ everyone

Changing the resourcepack name on itemsadder seems not a clean solution to me as it may lead to confusion


Let me know how it goes
