### ISSUE TITLE
[BUG] Redstone Lamps Blockus mod

### ISSUE THREAD

**Issue by Fargus5** [PluginBugs/Issues-ItemsAdder#603]
Ci sono molteplici bug legati alle lampade di redstone colorate (OGGETTI CUSTOM):
1) Quando piazzi il blocco, a volte la lampada si accende subito, a volte si accende ma dopo qualche secondo si spegne e a volte non si accende proprio.
2) In teoria dovrebbero attivarsi solo se in contatto con un impulso redstone, invece si attivano appena piazzati come se fossero dei semplici blocchi di glowstone.
3) Non so se è una cosa voluta, ma a livello di intensità luminosa, queste lampade di redstone custom sono meno efficaci delle normali lampade di redstone di minecraft vanilla; infatti la lampada di redstone vanilla ha una intensità di 14, mentre le lampade di redstone custom hanno una intensità di 11 (VALORI CONTROLLABILI TRAMITE MENU F3).
4) Anche se il menù F3 dice che hanno intensità 11, si può notare visibilmente che alcune lampade di redstone custom illuminano molto meno di altre.

**Comment by LoneDev6** [comment]
Le lampade di redstone custom non sono vere lampade di redstone, non sono gestite da Minecraft, sono solo decorative

Renderle attive come lampade di redstone reali renderebbe il server più pesante quindi non posso aggiungere questa funzionalità, mi spiace.

Per quanto riguarda la luce probabilmente è un problema della libreria che uso chiamata LightApi FORK, non è molto pulita come libreria, è un'hack diciamo che permette di creare luci ovunque, ma spesso è inconsistente

**Comment by Fargus5** [comment]
Ok va bene
