### ISSUE TITLE
Add set_amount action[Suggestion] 

### ISSUE THREAD

**Issue by Caishangqi** [PluginBugs/Issues-ItemsAdder#604]
I had read the wiki and found that the only 2 ways to change the amount value are using `increment_amount
`  and `decrement_amount`. When I want to change the thirst bar or mana bar to a specific number by item, it is difficult to do without using some `set_amount ` action.

I could use the command execute action on an item to set the value to a specific value.

**Comment by Caishangqi** [comment]
Besides, the wiki seem doesn't  contain some special variables such as `min_sky_light` and `biome`, `every_ticks` etc. Are these variables codded in plugin?

**Comment by LoneDev6** [comment]
> 
> 
> I had read the wiki and found that the only 2 ways to change the amount value are using `increment_amount ` and `decrement_amount`. When I want to change the thirst bar or mana bar to a specific number by item, it is difficult to do without using some `set_amount ` action.
> 
> I could use the command execute action on an item to set the value to a specific value.

Exactly what are you trying to achieve with HUDs + items?



> 
> 
> Besides, the wiki seem doesn't contain some special variables such as `min_sky_light` and `biome`, `every_ticks` etc. Are these variables codded in plugin?

Yes they are coded in the plugin, you can notice they work as the thirst bar uses these attributes to check if you're inside or outside a building

**Comment by Caishangqi** [comment]
> > I had read the wiki and found that the only 2 ways to change the amount value are using `increment_amount ` and `decrement_amount`. When I want to change the thirst bar or mana bar to a specific number by item, it is difficult to do without using some `set_amount ` action.
> > I could use the command execute action on an item to set the value to a specific value.
> 
> Exactly what are you trying to achieve with HUDs + items?
> 
> > Besides, the wiki seem doesn't contain some special variables such as `min_sky_light` and `biome`, `every_ticks` etc. Are these variables codded in plugin?
> 
> Yes they are coded in the plugin, you can notice they work as the thirst bar uses these attributes to check if you're inside or outside a building

I'd like to use some variables(such as day tick, if the plugin support that), to make a clock that shows the different status on top of the screen. 

could you give me a list of these variables such as `min_sky_light` and 'biome' that can be used in customizing hud?

**Comment by LoneDev6** [comment]
Ohhhh okay, well I think that is too complex to be achieved using only ItemsAdder builtin features.
You may need to implement that in Skript or Java, that would be easier.

Do you have experience on skript or Java?

**Comment by Caishangqi** [comment]
> Ohhhh okay, well I think that is too complex to be achieved using only ItemsAdder builtin features.
> You may need to implement that in Skript or Java, that would be easier.
> 
> Do you have experience on skript or Java?

uhhh, I only have some experience in AP computer science, but I am a noob on making addon or plugin, I don't quite sure I could handle it. Which, implementation is easier?

**Comment by LoneDev6** [comment]
A Skript script would be enough, there are some tutorials online, if you need help you can try asking on my discord server, maybe someone can help you.

you may also partecipate to the addons contest and maybe win :D 

let me know if you manage to make it working, if not I may try to code it for you

**Comment by Caishangqi** [comment]
> A Skript script would be enough, there are some tutorials online, if you need help you can try asking on my discord server, maybe someone can help you.
> 
> you may also partecipate to the addons contest and maybe win :D
> 
> let me know if you manage to make it working, if not I may try to code it for you

Thanks! I would try to start to learning Skript.
