### ISSUE TITLE
[Player join message after accept of the pack] 

### ISSUE THREAD

**Issue by MrmaximoExcssum** [PluginBugs/Issues-ItemsAdder#605]
I would like a feature where if the player joins and accepts the pack it would send a join message.
You would need to configure it at it HAS to support placeholder for prefixes etc.

And if the player joins but doesent accept the pack it would not send any message.
If the player does not accept any and leaves it would not send any message.

REMEBER! it needs to be an option to disable this in config (Just in case)
Thank you!

**Comment by LoneDev6** [comment]
I made a separate plugin for that feature: https://www.spigotmc.org/resources/resourcepackbroadcast.88318/
