### ISSUE TITLE
[BUG] furniture break issue 

### ISSUE THREAD

**Issue by kamyu1537** [PluginBugs/Issues-ItemsAdder#606]
**Describe the bug**
```yaml
small_hitbox: true
solid: true
```
when we try to break the second block, the first is broken while the second seems to be still there but also not collapsible

**To Reproduce**
1. Place the custom furniture(called the first block from now) somewhere and place it again the first block in any directions (called the second block)
2. and when we try to break the second block, the first is broken while the second seems to be still there but also not collapsible (in terms of block is set to solid)

**Expected behavior**
The second should be still there and the first should be broken

**Screenshots**
[gif](https://i.imgur.com/IklAvQR.gif")
[gif2](https://i.imgur.com/jNsLBB6.gifv)

**Info (please complete the following information):**
 - Server version: tuinity 1.16.5
 - Client version: fabric 1.16.5
 - Plugin version: 2.1.27

**Additional context**
the barriers' coordination(or pivot) seems not to be centered

**Comment by LoneDev6** [comment]
Thanks, I will fix this in the next update. Let me know if it works after updating
