### ISSUE TITLE
(Bug) loots don't reload

### ISSUE THREAD

**Issue by tdsacco0122** [PluginBugs/Issues-ItemsAdder#607]
When creating custom loots in minerals, the drops wouldn't update with /iareload.  I was able to remedy this by restarting my server then the change took effect. 

1. go to a materials.yml 
2. edit the drops of any material 
3. do /iareload ingame
4. get the ore you edited and mine it to see the change didn't take effect 

**Expected behavior**
I expected it to update with /iareload but it doesn't. 

**Info (please complete the following information):**
 - Server version: spigot 1.16.5
 - Client version: vanilla 1.16.5
 - Plugin version: 2.1.27

**Comment by LoneDev6** [comment]
Thanks! This should be fixed in the upcoming release of the plugin
