### ISSUE TITLE
[BUG] server crush

### ISSUE THREAD

**Issue by tenpuszek** [PluginBugs/Issues-ItemsAdder#609]
Server is crashing.

https://gist.github.com/tenpuszek/8a4664cf00b796be014fce930ae966a5

1.16.5
paper spigot

plugins
![image](https://user-images.githubusercontent.com/77970089/105705510-9cd12600-5f10-11eb-94c0-25c04d17da14.png)

**Comment by LoneDev6** [comment]
Update itemsadder
