### ISSUE TITLE
[BUG] Unable to update recipes using '/iareload' and '/iazip' 

### ISSUE THREAD

**Issue by killertuling** [PluginBugs/Issues-ItemsAdder#610]
- Server version: paper 1.16.5
 - Client version: 1.16.5
 - Plugin version: 2.1.27

After modifying the **recipe** in the file，
Use '/iareload' and '/iazip' unable to update item recipe.
It is still invalid in workbench 、 furnace and anvil.

But it can be solved by restart.

**Comment by LoneDev6** [comment]
I can't manage to make it happen.
This is my current configuration, I tried for example to change bronze_ingot to emerald_sword, just to test.
Then I used /iareload and the recipe updated correctly.

![immagine](https://user-images.githubusercontent.com/27242001/105837521-1af40200-5fcf-11eb-8cb7-d6f753126fd5.png)


I really suggest you to use this official tool to create and edit your configurations https://ide.plugin.ga/itemsadder/
It has autocomplete capability (CTRL+SPACE) and also checks for mistakes
