### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by xWzino** [PluginBugs/Issues-ItemsAdder#611]
**Describe the bug**
We can duplicate ore block with the mod Scaffold in Inertia Client...

**To Reproduce**

**Expected behavior**

**Screenshots**
https://prnt.sc/xmwcnm
https://prnt.sc/xmwdm9

**Info (please complete the following information):**
 - Server version: Paper 1.16.4
 - Client version:  Fabric 1.16.4 Inertia client
 - Plugin version: (example: 2.0.9 do not write "latest")

**Additional context**
Is very shitty

**Comment by LoneDev6** [comment]
Can you make a video about that?
plugin version?

**Comment by xWzino** [comment]
No sorry but is very very easy to do

________________________________
De : LoneDev <notifications@github.com>
Envoyé : 26 janvier 2021 05:51
À : PluginBugs/Issues-ItemsAdder <Issues-ItemsAdder@noreply.github.com>
Cc : xWzino <xwzino@hotmail.fr>; Author <author@noreply.github.com>
Objet : Re: [PluginBugs/Issues-ItemsAdder] [BUG] (#611)


Can you make a video about that?
plugin version?

**Comment by LoneDev6** [comment]
Please provide a video explaining how to do that and I will fix the issue, thanks a lot.
