### ISSUE TITLE
[BUG]  After mining a custom block the block behind it gets instantly broken.

### ISSUE THREAD

**Issue by LukeAppGuy** [PluginBugs/Issues-ItemsAdder#614]
**Describe the bug**
When mining a custom block with another block behind it, the block behind gets instantly mined once you have broken the custom block in front of it. This seems to be linked to block hardness or something similar.

**To Reproduce**
1. Mine a custom block with another non custom block behind it.
2. The block behind gets instant-mined

**Expected behavior**
The blocks behind custom blocks should not be mined instantly.

**Info (please complete the following information):**
 - Server version: Paper 1.16.5 #444

**Comment by LoneDev6** [comment]
I tried to reproduce the issue but I can't manage to make this happen:
https://youtu.be/-L8-f21atBQ


Please provide a video of the issue so I can check.
If possible: please try the plugin on a clean server to see if it's an incompatibility issue.
Thanks for your patience
