### ISSUE TITLE
[BUG] Replacing a double chest which is adjacent to custom blocks causes a visual bug.

### ISSUE THREAD

**Issue by LukeAppGuy** [PluginBugs/Issues-ItemsAdder#615]
**Describe the bug**
When you place a double chest down either on top or up against custom blocks then break one side of the chest and replace it, a visual bug happens.

**To Reproduce**
1. Place a double chest on top of some custom blocks.
2. Break one side.
3. Replace that side to make it a double chest again.
4. See visual bug happen.

**Expected behavior**
This just seems like a really strange bug to be happening, perhaps there is something wrong on my end. Could you try to replicate this for me and see if its an items adder issue?

**Screenshots**
https://imgur.com/G5P2N65

**Info (please complete the following information):**
 - Server version:  Paper 1.16.5 #444

**Comment by LoneDev6** [comment]
Does this fixes on player relog? or is it permanent?
Thanks

**Comment by LukeAppGuy** [comment]
Hey Lone, no it doesn't fix on relog.

**Comment by LoneDev6** [comment]
I'm sorry but I tried to fix that issue and it requires too much checks that will cause TPS drops, I can't fix that issue.
I noticed that interacting with the chest fixes the issue

**Comment by LoneDev6** [comment]
Seems this doesn't happen anymore.
Tested on Paper 1.18.1 and ItemsAdder 2.5.5
