### ISSUE TITLE
[BUG] Placing Redstone on top of custom blocks can make them update and revert to Mushroom Blocks.

### ISSUE THREAD

**Issue by LukeAppGuy** [PluginBugs/Issues-ItemsAdder#616]
**Describe the bug**
When placing redstone on top of custom blocks this causes the block to update and larger areas of custom blocks break and turn into mushroom blocks. This could be fixed by making it so that the blocks cannot interact with redstone and vice versa.

**To Reproduce**
1. Place some custom blocks for example 4x4 on the ground.
2. Place redstone on top of them.
3. The blocks update and turn into Mushroom Blocks/Stems.

**Expected behavior**

**Screenshots**

https://imgur.com/undefined

**Info (please complete the following information):**
 - Server version: Paper 1.16.5 #444
 - Client version: Vanilla 1.16.5
 - Latest

**Comment by LoneDev6** [comment]
> 
> 
> **Describe the bug**
> When placing redstone on top of custom blocks this causes the block to update and larger areas of custom blocks break and turn into mushroom blocks. This could be fixed by making it so that the blocks cannot interact with redstone and vice versa.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Place some custom blocks for example 4x4 on the ground.
> 
>     2. Place redstone on top of them.
> 
>     3. The blocks update and turn into Mushroom Blocks/Stems.
> 
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> 
> https://imgur.com/undefined
> 
> **Info (please complete the following information):**
> 
>     * Server version: Paper 1.16.5 #444
> 
>     * Client version: Vanilla 1.16.5
> 
>     * Latest

Hello!
I cannot see the screenshot.
Anyway does logout and login fixes the issue? It may be just a graphical glitch (which I cannot fix as some mushroom graphical events are clientside and not serverside, so I cannot avoid them)

let me know

**Comment by LukeAppGuy** [comment]
Yes relogging does fix this issue, although im not sure about the other bug I posted relating to chests that does not get fixed on relog!

**Comment by LoneDev6** [comment]
thanks for the info.
I cannot fix that issue too because the client predicts mushroom events even if I cancel the redstone place event.
Currently I have no solution, I hope they will remove the clientside code that predicts mushroom events or this cannot be fixed

**Comment by LoneDev6** [comment]
Seems this doesn't happen anymore.
Tested on Paper 1.18.1 and ItemsAdder 2.5.5
