### ISSUE TITLE
[BUG] After updating to the latest version of IA, vehicles spawn beds that have to be broken for the vehicles to work

### ISSUE THREAD

**Issue by imparium-de** [PluginBugs/Issues-ItemsAdder#618]
**Describe the bug**
See title

**To Reproduce**
1. Download and install IA 2.1.28
2. Place a vehicle

**Expected behavior**
No visible bed should spawn

**Screenshots**
![image](https://user-images.githubusercontent.com/63745647/106007752-ea879300-60b6-11eb-8f7b-261360ad9758.png)

**Info (please complete the following information):**
 - Server version: Paper 1.16.4
 - Client version: Vanilla 1.16.4 with Optifine HD_U_G5
 - Plugin version: 2.1.28

**Additional context**
Wasn't happening with 2.1.27

**Comment by LoneDev6** [comment]
Fixed thanks https://www.spigotmc.org/resources/%E2%9C%85must-have%E2%9C%85-itemsadder%E2%9C%A8custom-items-huds-guis-mobs-3dmodels-emojis-blocks-wings-hats-liquids.73355/
