### ISSUE TITLE
[Suggestion] Allow barrier blocks to trigger furniture "sit" function 

### ISSUE THREAD

**Issue by ArgonGaming** [PluginBugs/Issues-ItemsAdder#620]
🪑 Pretty self explanatory. When enabling `solid: true` on behaviors under furniture options, as well as enabling `furniture-sit`, this makes it so the player cannot interact with the furniture and right click to sit DUE to the barrier block being in the way.

**A solution** would be to have it when solid = true, and furniture-sit = true, have the barrier block act as a way to sit on the furniture. (When barrier block is right clicked, sit on corresponding furniture)

This should be the expected behavior with solid chair furniture objects.

Thank you ❤️ 

![image](https://user-images.githubusercontent.com/30943826/106053677-11df5f80-60b9-11eb-99c7-02437ead351e.png)

**Comment by LoneDev6** [comment]
Thanks, I added this feature in the new update
