### ISSUE TITLE
[Suggestion] Ability to sync thirst and mana between servers on a BungeeCord network

### ISSUE THREAD

**Issue by imparium-de** [PluginBugs/Issues-ItemsAdder#621]
**Is your feature request related to a problem? Please describe.**
When players switch servers on our network, their thirst doesn't sync and they have to drink more than they should.

**Describe the solution you'd like**
A MySQL database where the files from `\ItemsAdder\storage\players\stats` get saved in would be nice. 

**Describe alternatives you've considered**
Alternatively, a config option to define a path where IA is looking for those files would be fine too. That way, you could select the same path for all IA instances in the network.

**Additional context**
-

**Comment by ArgonGaming** [comment]
Just a tip, you can use something like Velocity for syncing data between servers seamlessly

**Comment by LoneDev6** [comment]
> 
> 
> **Is your feature request related to a problem? Please describe.**
> When players switch servers on our network, their thirst doesn't sync and they have to drink more than they should.
> 
> **Describe the solution you'd like**
> A MySQL database where the files from `\ItemsAdder\storage\players\stats` get saved in would be nice.
> 
> **Describe alternatives you've considered**
> Alternatively, a config option to define a path where IA is looking for those files would be fine too. That way, you could select the same path for all IA instances in the network.
> ## **Additional context**

currently how do you sync inventories and vanilla stats?

**Comment by imparium-de** [comment]
We're currently using the plugin [MySQL Player Data Bridge](https://www.spigotmc.org/resources/mysql-player-data-bridge.8117/) which syncs just about anything (food, XP, inv, money, ender chest and more)

**Comment by LoneDev6** [comment]
Interesting plugin, I bet I can code some useful API method and then contact the plugin author, would be nice to have ItemsAdder data synced with their plugin

**Comment by imparium-de** [comment]
Yeah that would be even better :D

**Comment by imparium-de** [comment]
A quick follow up:
I don't know how much you already did in regards to the API, but I've just noticed something. MPDB claims to sync everything within the `player.dat` file. Would it be possible to set the thirst and mana values in there? If yes, then it'd probably be less stress for you and the MPDB dev :D 
![image](https://user-images.githubusercontent.com/63745647/107293229-875d0f80-6a6b-11eb-8d10-78a696d50192.png)
It looks like Paper and Bukkit store some values in there too. 
![image](https://user-images.githubusercontent.com/63745647/107293305-abb8ec00-6a6b-11eb-84eb-c9e6f878e505.png)

**Comment by imparium-de** [comment]
Seems like this won't be added anytime soon.  :/

**Comment by LoneDev6** [comment]
> A quick follow up:
I don't know how much you already did in regards to the API, but I've just noticed something. MPDB claims to sync everything within the player.dat file. Would it be possible to set the thirst and mana values in there? If yes, then it'd probably be less stress for you and the MPDB dev :D

I need to check if it's possible to write stuff into this file, I'm not aware of an official Spigot API for that, but maybe I'm wrong and they added it

**Comment by imparium-de** [comment]
> > A quick follow up:
> > I don't know how much you already did in regards to the API, but I've just noticed something. MPDB claims to sync everything within the player.dat file. Would it be possible to set the thirst and mana values in there? If yes, then it'd probably be less stress for you and the MPDB dev :D
> 
> I need to check if it's possible to write stuff into this file, I'm not aware of an official Spigot API for that, but maybe I'm wrong and they added it

Thanks for your answer. I just took a second look the said file located at /WORLDNAME/playerdata/PLAYER_UUID.dat and it seems like you're already adding something to that file, maybe related to the emotes? I have never seen that value before the emote update. 

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/63745647/77385449-f948-4585-9142-ba51693e73ad)

**Comment by LoneDev6** [comment]
Seems Spigot persistent API saves this data into the player file, so I guess I can add a configuration to start saving HUDs data into the player file

**Comment by LoneDev6** [comment]
Added a new option in config.yml

```yml
player_stats:
  save_type: CUSTOM_NBT # CUSTOM_NBT, PLAYER_DAT
```


Set it to `PLAYER_DAT` to use the player.dat file.

```yml
player_stats:
  save_type: PLAYER_DAT
```



![Image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/17c75d1c-06d4-45be-b0cb-0cf82b6a99b7)
