### ISSUE TITLE
[BUG] ItemsAdder axes repair themselves when in use with a treefeller plugin like "UltimateTimber"

### ISSUE THREAD

**Issue by imparium-de** [PluginBugs/Issues-ItemsAdder#622]
**Describe the bug**
We couldn't test it with other timber plugins, but when using IA axes in conjunction with the plugin "UltimateTimber", they repair themselves when they're close to the 0 durability mark. 

**To Reproduce**
1. Download and install [UltimateTimber version 2.2.2](https://songoda.com/marketplace/product/ultimatetimber-the-realistic-tree-chopper.18)
2. Download and install ItemsAdder version 2.1.29
3. In the UltimateTimber config, set `protect-tool:` to `false`. Alternatively, use our [config](https://paste.gg/p/anonymous/c5b813e4d7754049a7cf66dc51da5373)
4. Cut down some tress until the axes reach 0 durability.

**Expected behavior**
The IA axes shouldn't repair themselves. UltimateTimber checks if the durability of the tool is high enough to topple the tree. If not, it'll do nothing. But because IA axes repair themselves before reaching 0, you get infinite durability. 

**Screenshots**
Videos:
Ruby Axe: https://s.imparium.de/niho0/RocePAQU69.mp4
Diamond Axe: https://s.imparium.de/niho0/RaYiyoyi54.mp4

**Info (please complete the following information):**
 - Server version: Paper 1.16.4
 - Client version: Vanilla 1.16.4 (Optifine HD_U_G5)
 - Plugin version: 2.1.29

**Additional context**
All ItemsAdder axes seem to be affected. We didn't test it, but there's a good chance that the same thing could happen with IA pickaxes and some kind of VeinMiner plugin.

**Comment by LoneDev6** [comment]
I cannot fix this bug, ItemsAdder doesn't automatically repair the item durability.
You may ask UltimateTimber dev to hook into ItemsAdder API and check for the custom durability, or find the cause of this strange behaviour.

Send them this link. They don't even need to own the plugin to access the API:
https://github.com/LoneDev6/API-ItemsAdder/blob/master/src/main/java/dev/lone/itemsadder/api/CustomStack.java#L135
