### ISSUE TITLE
[BUG] Why ores spawning so near to surface

### ISSUE THREAD

**Issue by OwerWorldPlayer** [PluginBugs/Issues-ItemsAdder#625]
I didnt like Spinel and Ruby ore generating and decided to change them

But when I changed and regenerated the world nothing changed or something changed but not I wanted(idk)

**Comment by ArgonGaming** [comment]
This is not a bug. It is a configuration issue, double check your config and make sure it's working

**Comment by OwerWorldPlayer** [comment]
i tried everything , if you want i can send config

**Comment by LoneDev6** [comment]
please don't erase the configuration template, I need the info required.
open a new issue and provide all the info required + your config, thanks
