### ISSUE TITLE
[Suggestion] Hud Requirement Check/Feature.

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-ItemsAdder#628]
I wish to request a function be added to Itemsadder

Quoting you in a Communication we had on SpigotMC, "currently there is no way to do that with only configuration files, you may ask on github and I will add a new attribute to check for huds values before executing an action."

A requirement attribute to check for Mana before executing an action. Also the ability to tell the player they do not have the required Mana.

Have the attribute check for a specific number, example:   Wands requires 2 Mana to use, check that 2 mana is available.

**Comment by LoneDev6** [comment]
Thanks for the idea, I added this in the new update, please check it out.
I will publish it in some minutes.
https://itemsadder.plugin.ga/plugin-usage/adding-content/advanced/item-properties/basic#events_needed_player_stats

**Comment by SirCraftypants** [comment]
You're awesome, huge thanks.

**Comment by LoneDev6** [comment]
> 
> 
> You're awesome, huge thanks.

let me know if everything works fine, it should as I tested it in normal use cases

**Comment by Fargus5** [comment]
Thanks

**Comment by SirCraftypants** [comment]
Ok i've created my Wand but i have one issue, i'm trying to use the gun_shot event, but i need it to do projectile damage without an actual projectile so to speak.

https://paste.helpch.at/vudujetogo.bash

**Comment by SirCraftypants** [comment]
Or some way to shoot a particle that does damage would be better.
