### ISSUE TITLE
[BUG] items have 2 sets of durability

### ISSUE THREAD

**Issue by Ronglito** [PluginBugs/Issues-ItemsAdder#629]
**Describe the bug**
the bug im having is that items that the itemadder adds to the game that have durability like swords and tools they show two sets of durability one from the custom durability from the item.yml file and the second one is from the original hosting item
for example if the iron sword has 200 durability and I create an item with 400 durability and use the iron sword as the material it will show both numbers when I view the item in-game.
the custom durability is the one that matters not the original but it still shows the original and it just looks confusing.

**To Reproduce**
get any sword from /ia and after a little use hover over it to check the durability

**Expected behavior**
I expect it to show only the custom durability that I set in the yml file not both sets of durability

**Screenshots**
https://media.discordapp.net/attachments/533413171403292712/805750221236731944/unknown.png

**Info (please complete the following information):**
 - Server version: paper 1.16.4
 - Client version: optifine 1.16.4
 - Plugin version: 2.1.29

**Additional context**
I sent the yml file and the host item json file in the discord support and they said they don't see a problem with the code.

**Comment by LoneDev6** [comment]
Hello,
you have the advanced tooltip option on, disable it pressing F3+H.
I cannot hide that since it's clientside. The gray durability is the correct one handled by itemsadder, the white one is the vanilla durability, which is proportional to itemsadder one.

I hope I answered your question

**Comment by SirCraftypants** [comment]
Tooltips being turned off was suggested by someone but, they said it wasn't working for them, that it was still showing despite turning tooltips off.

**Comment by LoneDev6** [comment]
> 
> 
> Tooltips being turned off was suggested by someone but, they said it wasn't working for them, that it was still showing despite turning tooltips off.

Please post a screenshot, vanilla Minecraft will show the durability text indicator only if F3+H feature is triggered, if not it won't show anything beside the item lore (which contains ItemsAdder custom durability)
