### ISSUE TITLE
[Suggestion] Cast Damage with Wand

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-ItemsAdder#632]
A small list of Particles that can be used for Wands and a way to do range damage without the need for projectiles.

**Comment by LoneDev6** [comment]
https://ide.plugin.ga/itemsadder/ should suggest you particles if you press CTRL+SPACE

the range damage will be published when spigotmc website starts working again, currently seems it has some problems.
For now i published it on the wiki https://itemsadder.plugin.ga/plugin-usage/adding-content/beginners/creating-a-custom-item/magic-wand

**Comment by SirCraftypants** [comment]
OK, i'm ready to test out the wand once you've released the update, spigotmc's back up and running btw.

Thanks

**Comment by SirCraftypants** [comment]
Have an issue i can't seem to solve, everything else works accept, i can not increase the attack range, i'm trying to set it to more than 7 blocks, ideally 14 block distance.

https://paste.helpch.at/ropebapefe.bash

**Comment by SirCraftypants** [comment]
I'm reluctant to use bow or crossbow to host this to do range damage and hope there's anothers another way?

**Comment by LoneDev6** [comment]
> 
> 
> Have an issue i can't seem to solve, everything else works accept, i can not increase the attack range, i'm trying to set it to more than 7 blocks, ideally 14 block distance.
> 
> https://paste.helpch.at/ropebapefe.bash

ty, i will fix that



> 
> 
> I'm reluctant to use bow or crossbow to host this to do range damage and hope there's another way?

currently there is no way to do a cast-like thing.
You may try to use trident as item base and cancel the **item_throw** using **cancel** action of itemsadder.
Let me know if it works, it's an untested idea

**Comment by SirCraftypants** [comment]
Ok now that you've fixed damage_near_entities, range damage is working but there's an issue with it, it damages all entities within a radius as opposed to 1 target. if you could get it to target 1 entity that would be awesome.

In the mean time i will test out the Trident idea of yours now.

**Comment by SirCraftypants** [comment]
OK Trident isn't possible as it's thrown as an entity with durability and consists of 3 json files instead of the usual one. you'd effectively be throwing the want at targets and it you prevent the Trident from being thrown the wand isn't thrown thus causing no damage.

I've noticed there are already magic wand plugins on the market, some free version. Not sure how all that stuff works but would it be wrong to check a few out and see how they implement it.

Or is there a way to make a wand act like a Bow but shoot instantly, then create an option in the config allowing mana to regenerate over time.

**Comment by SirCraftypants** [comment]
I found and tried     damage_entity_in_sight    but it didn't work.

**Comment by LoneDev6** [comment]
> 
> 
> OK Trident isn't possible as it's thrown as an entity with durability and consists of 3 json files instead of the usual one. you'd effectively be throwing the wand at targets and if you prevent the Trident from being thrown the wand isn't thrown thus causing no damage.
> 
> I've noticed there are already magic wand plugins on the market, some free versions. Not sure how all that stuff works but would it be wrong to check a few out and see how they implement it.
> 
> Or is there a way to make a wand act like a Bow but shoot instantly, then create an option in the config allowing mana bar
> to regenerate over time.
> 
> The damaging all mobs in a radius is a good option but if you could achieve single target too, then that would mean no having to use Bow to host, if Bow has to be used then is there a way to remove the drawback so the shoot is instant.

isn't the "cancel" action working for the throw trident event?
should work fine

**Comment by SirCraftypants** [comment]
> 
> 
> > OK Trident isn't possible as it's thrown as an entity with durability and consists of 3 json files instead of the usual one. you'd effectively be throwing the wand at targets and if you prevent the Trident from being thrown the wand isn't thrown thus causing no damage.
> > I've noticed there are already magic wand plugins on the market, some free versions. Not sure how all that stuff works but would it be wrong to check a few out and see how they implement it.
> > Or is there a way to make a wand act like a Bow but shoot instantly, then create an option in the config allowing mana bar
> > to regenerate over time.
> > The damaging all mobs in a radius is a good option but if you could achieve single target too, then that would mean no having to use Bow to host, if Bow has to be used then is there a way to remove the drawback so the shoot is instant.
> 
> isn't the "cancel" action working for the throw trident event?
> should work fine

I did not test the cancel throw event so don't know but you've already solved this now with the below wand example.

https://paste.helpch.at/uqofimeruy.bash
