### ISSUE TITLE
[Suggestion] possible to add support for Trmenu or Deluxmenu?

### ISSUE THREAD

**Issue by Caishangqi** [PluginBugs/Issues-ItemsAdder#633]
**Could you add more GUI support for Trmenu or Deluxmenu etc? I recently find that ChestCommand is a little big lag and have less script operation support than Trmenu. It would be cool to make a menu like this:**
![image](https://user-images.githubusercontent.com/39553613/106545898-15ab2180-64bf-11eb-9cb3-fe06a4fb7ff4.png)
The picture above is the support Oraxen to Trmenu.

Trmenu spigot [link](https://www.spigotmc.org/resources/20-off-trmenu-premium-modern-advanced-menu-plugin-1-8-1-16.83120/)

Oraxen documentation [link](https://docs.oraxen.com/compatibility/trmenu-custom-inventories)

If it is troublesome to implement, I don’t mind continuing to use Chestcommand :3

**Comment by ArgonGaming** [comment]
I vouch for this

**Comment by LoneDev6** [comment]
mhhhh well reading the docs seems Oraxen is using the classic retextured item method to make GUIs which is different from ItemsAdder method.
I asked TRMenu author if they can give me a copy of the plugin to implement the compatibility.

**Comment by SirCraftypants** [comment]
I personally use Deluxemenus and it is totally compatible with Itemsadder

**Comment by LoneDev6** [comment]
Still waiting for answer from the dev
![immagine](https://user-images.githubusercontent.com/27242001/110810626-43d20d00-8286-11eb-91d2-7214bd849ce9.png)

**Comment by Caishangqi** [comment]
> Still waiting for answer from the dev
> ![immagine](https://user-images.githubusercontent.com/27242001/110810626-43d20d00-8286-11eb-91d2-7214bd849ce9.png)

He did that, there is v3.0 Trmenu test version had made the compatibility of ItemAdder :).
![image](https://user-images.githubusercontent.com/39553613/110812015-195b6200-823c-11eb-85aa-d440e9bf7fca.png)

**Comment by LoneDev6** [comment]
Cool! Can you please provide an example on how to create a custom icon using itemsadder texture?
Thanks @Caishangqi

**Comment by Caishangqi** [comment]
After these few months, I found that the title part of Trmenu will not read similar to :menu: and placeholders. I can use placeholders like %img_NAME% in Trmenu but I cannot adjust their position.

**Comment by LoneDev6** [comment]
Yes you can
Use `%img_offset-16%`

**Comment by Caishangqi** [comment]
Hi, I still can not use the `%img_offset-16%` to alternate the position in Trmenu. Here is the preview:
![image](https://user-images.githubusercontent.com/39553613/125461835-6e469eb5-ed67-4d06-b626-f2e9cc6147d9.png)
Items namespaces work perfectly, but the picture can't move.
 
**The config of menu title:**
`Title: '&f%img_offset-16% %img_blank_menu%'`

**Comment by LoneDev6** [comment]
`Title: '&f%img_offset_-16%%img_blank_menu%'`

**Comment by Caishangqi** [comment]
> `offset_` not `offset`
> `Title: '&f%img_offset_-16%%img_blank_menu%'`
> 
> Also set the GUI height to be 6 not 3.
> Or make your own smaller texture

Awesome！I could alter the picture position. Thanks for the support and the excellent plugin, which give me the opportunity to add fantastic elements to minecraft!
![image](https://user-images.githubusercontent.com/39553613/125464754-31cc9369-ea75-4ed9-948e-1e69e393e430.png)

**Comment by LoneDev6** [comment]
Amazing! :D
Good thing is that with ItemsAdder you don't have to use items to retexture the GUI, this makes the game more vanilla looking.

I hope you will consider leaving a 5 stars review, it will help me a lot! 
https://www.spigotmc.org/resources/73355/

Have a nice day
