### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by OwerWorldPlayer** [PluginBugs/Issues-ItemsAdder#634]
**Describe the bug**
I didnt like Spinel and Ruby ore generating and decided to change them

But when I changed and regenerated the world nothing changed 

Also in default config:

worlds_populators:
  ruby_ore:
    block: itemsadder:ruby_ore
    worlds:
    - world
    replaceable_blocks:
    - STONE
    - DIRT
    - ANDESITE
    - GRANITE
    - COBBLESTONE
    - GRAVEL
    chance: 70.0
    max_height: 45
    min_height: 25
    amount: 6
    iterations: 1
  spinel_ore:
    block: itemsadder:spinel_ore
    worlds:
    - world
    replaceable_blocks:
    - STONE
    - DIRT
    - ANDESITE
    - GRANITE
    - COBBLESTONE
    - GRAVEL
    chance: 90.0
    max_height: 45
    min_height: 35
    amount: 6
    iterations: 1

**Expected behavior**
Why they are not generating in what is saying to config, they are spawning to near water or surface

**Info (please complete the following information):**
 - Server version: 1.16.3 Paper
 - Plugin version: 2.1.30

**Comment by OwerWorldPlayer** [comment]
why ruby and spinel not listening config

**Comment by LoneDev6** [comment]
> they are spawning to near water or surface

is your surface higher than 45? I see it's set to max_height:45.
I suggest you to lower this down.


Btw you may have to reset your world since there may be some already generated chunks.

**Comment by OwerWorldPlayer** [comment]
i did all of them , first tried to remove dirt , my surface definitely higher than 45 , I was using custom world generator , I removed it and tried in vanilla world , not worked

**Comment by OwerWorldPlayer** [comment]
ruby is spawning in rivers

**Comment by LoneDev6** [comment]
"not working" is very vague.

Please provide screenshots, precise heights and configurations or I cannot help.
Btw this seem not to be a bug, I suggest you to open a ticket on my Discord server.
https://support.plugin.ga/
