### ISSUE TITLE
[BUG] Furniture sit allows for multiple players in same seat

### ISSUE THREAD

**Issue by ArgonGaming** [PluginBugs/Issues-ItemsAdder#635]
**Describe the bug**
When sitting (may involve the hitbox being on), multiple players can sit in same seat.

**To Reproduce**
1. Make a furniture with sit function and "solid: true"
2. Sit on it
3. Get other player to sit on it

**Expected behavior**
Should only allow one player at a time per furniture seat!

**Screenshots**
![image](https://user-images.githubusercontent.com/30943826/106677641-1ad3a380-6587-11eb-991c-9ae346933414.png)

**Info (please complete the following information):**
 - Server version: paper 1.16.5
 - Client version: 1.16.5
 - Plugin version: 2.1.30

**Additional context**

**Comment by SirCraftypants** [comment]
Well that's just down right rude, tell the others to find their own seats lol, sorry couldn't help myself.

**Comment by LoneDev6** [comment]
Lol, I wonder if that way of sitting is comfortable

I will fix it today, thanks
