### ISSUE TITLE
[BUG] Errore in Console

### ISSUE THREAD

**Issue by RickyLaChow** [PluginBugs/Issues-ItemsAdder#637]
Ciao ricevo questo errore in console quando un giocatore muore:
https://pastebin.com/8zM4YNZ6

**Comment by LoneDev6** [comment]
Hai eliminato tutto il template della pagina, mi mancano un sacco di informazioni per aiutarti.

Comunque prova a spegnere il server completamente e aggiornare alla nuova versione.

**Comment by RickyLaChow** [comment]
Si probabilmente era un problema della versione precedente
