### ISSUE TITLE
[BUG] Smithing table netherite sword bug

### ISSUE THREAD

**Issue by Tanimsiz** [PluginBugs/Issues-ItemsAdder#638]
I can convert any itemsadder sword to netherite sword without losing stats. (using smithing table)

How can i disable converting
Server version: 1.16.5 paper build 449
ItemsAdder version: 2.1.29

![bug](https://user-images.githubusercontent.com/29007379/106781133-c6e5bf00-6659-11eb-9a82-dbc0a3a874bf.gif)

**Comment by LoneDev6** [comment]
Thanks, this will be fixed

**Comment by SirCraftypants** [comment]
> 
> 
> Thanks, this will be fixed in the next update

Not sure you can fix it, maybe prevent it. It's part of Minecraft itself. Diamond Swords can be upgraded to Netherite, the simple solution to this would be to use Golden Sword to host your weapons instead. That said if you can create a prevent that would be convenient, though would it not prevent players from upgrading the normal diamond sword from upgrading to netherite like it should?

**Comment by SirCraftypants** [comment]
Maybe you could put a bit of info under weapons on the wiki, advising users to use one of wooden, stone, iron or golden swords as the host instead of a diamond sword so that they dont have this issue, maybe link to this issue so they can understand why? Just an idea for future users.

**Comment by LoneDev6** [comment]
I already fixed the issue, you won't be able to use the smithing table with itemsadder swords only.
I may add a recipe type in the future, but for now I disabled the usage

**Comment by Tanimsiz** [comment]
Bug also works with diamond armors

**Comment by LoneDev6** [comment]
> 
> 
> Bug also works with diamond armors

what do you mean? i'm sure it's a vanilla behaviour

**Comment by Tanimsiz** [comment]
I mean itemsadder armors

**Comment by LoneDev6** [comment]
> 
> 
> I mean itemsadder armors

ohhh, thanks for the info.
Anyway the fix I added in the upcoming update will take in to account also armors
