### ISSUE TITLE
[BUG] Mysterious Amulet 1 usage

### ISSUE THREAD

**Issue by QuentiumYT** [PluginBugs/Issues-ItemsAdder#639]
**Describe the bug**
Clicking with an amulet while having an ender pearl in the inventory makes it usable only once.

**To Reproduce**
1. Get some EP and the Mysterious Amulet in your inventory
2. Right click with the Amulet

**Expected behavior**
Don't consume the whole Amulet

**Info (please complete the following information):**
 - Server version: paper 1.16.5
 - Client version: optifine 1.16.5
 - Plugin version: 2.1.31

**Comment by LoneDev6** [comment]
Seems 1.16+ had changed something on how the throwable items amounts are modified during the throw event.
I now should have fixed that problem adding 1.16+ compatibility to the decrement_usages.
An update will be posted shortly
