### ISSUE TITLE
[BUG] the disc keep playing after destroy the block

### ISSUE THREAD

**Issue by killertuling** [PluginBugs/Issues-ItemsAdder#640]
**Info (please complete the following information):**
 - Server version:1.16.5
 - Client version: 1.16.5
 - Plugin version: latest

 this is the full video.
It's not just hammer, it's also '/ fill', and all kinds of strange ways of destruction.
Vanilla disc doesn't have this problem...

https://www.dropbox.com/s/z90qdhchyb00j8z/test.mp4?dl=0

**Comment by LoneDev6** [comment]
Thanks, this will be fixed in the next update
