### ISSUE TITLE
[BUG] Luminous objects go dark when placing blocks next to them (light update)

### ISSUE THREAD

**Issue by imparium-de** [PluginBugs/Issues-ItemsAdder#642]
**Describe the bug**
When placing blocks next to luminous items / blocks, they go dark. 

**To Reproduce**
1. Place a luminous object (lamp, chandelier)
2. Place a block next to it or cause some kind of light update
3. See error

**Expected behavior**
They shouldn't go dark

**Screenshots**
https://s.imparium.de/niho0/cIJEpoZE47.mp4

**Info (please complete the following information):**
 - Server version: 1.16.4
 - Client version: 1.16.4 (Optifine HD_U_G5)
 - Plugin version: 2.1.31

**Additional context**
Similiar and maybe related to https://github.com/PluginBugs/Issues-ItemsAdder/issues/574

**Comment by LoneDev6** [comment]
Sadly it's a lightapi fork limitation i cannot fix, you have to contact the light api dev
