### ISSUE TITLE
[BUG] Block/Items Material

### ISSUE THREAD

**Issue by Venterok** [PluginBugs/Issues-ItemsAdder#644]
**Describe the bug**
It is not possible to change the block material to an item like paper/diamond. 
After absolutely all blocks do not work

**To Reproduce**
1. Go to plugin folder items_packs/itemsadder(or any another)/blocks.yml
2. Edit any block material to paper or another item
3. /iareload & /iazip in game/or console
4. See error in console

**Expected behavior**
The block in the inventory will be a renamed piece of paper. Thanks to this, there will be no terrible replacement of the block when you put it

**Screenshots**
https://media.discordapp.net/attachments/721030970739916870/808009621817786408/unknown.png
https://media.discordapp.net/attachments/721030970739916870/808010301773316106/unknown.png
![image](https://user-images.githubusercontent.com/67825103/107152664-286b9d80-697a-11eb-983f-203ef3bfcb7e.png)
![image](https://user-images.githubusercontent.com/67825103/107152666-2bff2480-697a-11eb-93aa-a373b2d3f63a.png)

**Info (please complete the following information):**
 - Server version: Paper 1.16.5
 - Client version: Fabric 1.16.4
 - Plugin version: 2.1.32

**Additional context**
Nothing

**Comment by imparium-de** [comment]
You have to change the material to another block like `DIAMOND_BLOCK`, `OAK_PLANKS`, `STONE` etc. Changing it to an item like `PAPER`, `DIAMOND` etc,. only works for ItemsAdder items/entities like hats. That's because you can't "mine" paper or the item diamond.

**Comment by Venterok** [comment]
I know this, I want the block in the inventory to be paper so that there is no replacement of the block on the ground with a mushroom

**Comment by Venterok** [comment]
In another "Oraxen" plugin for adding items, this works. 
![image](https://user-images.githubusercontent.com/67825103/107164376-d5b4d480-69bf-11eb-9a4b-04c9c8232fac.png)
![image](https://user-images.githubusercontent.com/67825103/107164383-db121f00-69bf-11eb-9fc3-b4b52ed47394.png)

**Comment by LoneDev6** [comment]
I sincerly don't understand what you're trying to do...
Please elaborate what you want to obtain.

**Comment by Venterok** [comment]
Ability to change the block material in the inventory to an item (not a block like OAK_PLANKS and etc).Today this works like this, if you have in the Material parameter OAK_PLANKS in block, then at the moment when you put the boards, and they change to custom block. In my opinion, it looks ugly in some moments. I don't know much English, please forgive me.

**Comment by ArgonGaming** [comment]
I think he means he doesn't like the "Flickering" when a custom block is placed (the system used to make custom block placement sounds). He thinks that making the HOLDABLE item NOT a block would fix that, but that is incorrect, it is a completely different issue.

**Comment by LoneDev6** [comment]
Thanks for the suggestion, I'm working on a recode of the blocks part to allow this
