### ISSUE TITLE
[BUG] Error in console when press "F"

### ISSUE THREAD

**Issue by Galakto0r** [PluginBugs/Issues-ItemsAdder#645]
**Describe the bug**
When we are in game and press "F" an error appears in the console.

**To Reproduce**
1. Just connect to your server.
2. Press "F".

**Expected behavior**
I think there is no bad behavior. Only error spam in the console

**Screenshots**
https://pastebin.com/jJ0QcySS
https://i.imgur.com/Ki6Yu3y.png

**Info (please complete the following information):**
 - Server version: 1.16.4
 - Client version: 1.16.5
 - Plugin version: 2.1.34

**Additional context**
This error is displayed only in version 1.16.4. In 1.15.2 everything works fine.

**Comment by 100petr** [comment]
Do you have the latest protocollib? https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by Galakto0r** [comment]
No but now yes, and indeed it was the protocollibs update, it is now solved, thank you very much.
