### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by nderee** [PluginBugs/Issues-ItemsAdder#646]
PERMISSIONS

Running ItemsAdder works when OP. You can see all categories, items, crafting recipes, and can craft any item. 
Trying to give permissions to ItemsAdder through LuckPerms causes problems. Putting the listed permission commands into LuckPerms allows access to the hud, and search GUI, but there's no items in the categories, and you can't craft anything. 

I expected there to be access to all items and crafting recipes for my players to use in survival.

Running ItemsAdder v2.1.34
Luck Perms v5.2.104
Spiggot Server 1.16.5

**Comment by LoneDev6** [comment]
"Trying to give permissions to ItemsAdder through LuckPerms causes problems"

Please be more specific and post your list of itemsadder permissions

**Comment by LoneDev6** [comment]
read here: https://github.com/PluginBugs/Issues-ItemsAdder/issues/647
it may be related to your issue.
Let me know

**Comment by nderee** [comment]
> read here: #647
> it may be related to your issue.
> Let me know

Here's a screenshot of the permissions i've given the group
![image](https://user-images.githubusercontent.com/78706976/107286423-92de1580-6a2e-11eb-8fea-ca38f61f2849.png)

Players open the ItemsAdder GUI, and all that shows up is the all category, with nothing in it except some miscellaneous items like generic and the icons.
