### ISSUE TITLE
[BUG] Recipes Permission Not Working

### ISSUE THREAD

**Issue by NativeC** [PluginBugs/Issues-ItemsAdder#647]
**Describe the bug**
Players cannot craft ANY itemsadder items, regardless of permissions given (I triple-checked: I entered the correct perms in my permission manager).

**To Reproduce**
1. Provide itemsadder crafting to default users
2. Go on server as default player (no op-perms or such)
3. Attempt to craft relevant item
4. See "you do not have permission to craft this" message

**Expected behavior**
Should be able to craft item.

**Screenshots**
Not needed in this case: pretty straightforward issue.

**Info (please complete the following information):**
 - Server version: Spigot 1.16.5
 - Client version: Optifine 1.16.4
 - Plugin version: 2.1.33

**Additional context**
Using luckperms permission system.

**Comment by LoneDev6** [comment]
can you send me your permissions list?
thanks

**Comment by NativeC** [comment]
Exemple permission list for my farmer job license:
https://ibb.co/9hdYjn0

**Comment by LoneDev6** [comment]
Found the issue, correct permission is: ia.user.craft.itemsadder.*
as you can see here:
![image](https://user-images.githubusercontent.com/27242001/107260713-b01ae000-6a3e-11eb-9985-2b3850486e8b.png)


![image](https://user-images.githubusercontent.com/27242001/107260624-98dbf280-6a3e-11eb-8517-ec80a0a23079.png)

**Comment by DrimpyTV** [comment]
i have simmilar problem but with events:
![image](https://github.com/user-attachments/assets/a7819453-43cd-455f-8290-fba07d6fd5cf)

**Comment by Andre601** [comment]
Please do not reply to year old, closed issues.
