### ISSUE TITLE
[BUG] Torches stay in place when breaking the IA block they stand on

### ISSUE THREAD

**Issue by imparium-de** [PluginBugs/Issues-ItemsAdder#648]
**Describe the bug**
When placing a torch on an IA block or on a block that is next to an IA block, the torch stays in place when the block beneath it gets destroyed. When the IA block gets removed _before_ the vanilla block, the torch breaks as expected. 

**To Reproduce**
1. Place a torch on an IA block or a vanilla block that is next to an IA block
2. Break the blocks and see the torch floating

**Expected behavior**
The torch should break. 

**Screenshots**
Bug with vanilla generated blocks: https://s.imparium.de/niho0/gUXAjaci66.mp4
Bug with IA blocks placed by hand: https://s.imparium.de/niho0/PuMariHO70.mp4

Maybe related problem with hammers and water/lava/torches: https://s.imparium.de/niho0/MOguTUna93.mp4

**Info (please complete the following information):**
 - Server version: Paper 1.16.5
 - Client version: 1.16.4 (Optifine HD_U_G5
 - Plugin version: 2.1.31

**Additional context**
There's a similar problem with lava/water when breaking blocks with hammers. Liquids don't start to float until a block update.

**Comment by LoneDev6** [comment]
I will leave this issue report open but I have to tell you that I cannot fix that issue without making the server laggy.
Currently the reason behind that is that I have to cancel every block update near custom blocks to avoid their textures to be changed to mushroom blocks.


I may be able to fix that in the future if Spigot/Minecraft adds a way to stop mushroom from changing their blockstate on every damn block change around them.

**Comment by ArgonGaming** [comment]
This would be a very preferable fix if it applies to the Noteblock method as well! Maybe as an optional feature for it to always update and prevent the torch glitch.

**Comment by LoneDev6** [comment]
No that easy, adding a similar feature would require a complete rewrite of the current system.
Currently code for that is a mess but is optimized a lot to avoid server lag.
Sadly the physics event on Spigot is very resource intensive, for now that is the best I can achieve with a balance on effectiveness and cpu usage
