### ISSUE TITLE
[BUG] Items losing texture on //flip and //rotate

### ISSUE THREAD

**Issue by NativeC** [PluginBugs/Issues-ItemsAdder#649]
**Describe the bug**
I have Itemsadder and the subsequent itemsadder worldedit compatibility addon. When I use //copy ==> //flip ==> //paste, the blocks lose their textures and either become mushroom blocks or some weird ore. What's weird is that some blocks don't seem to care and keep their texture anyway: see the custom black tiles and beige blocks under the window (screenshots).

**To Reproduce**
1. Build something with IA blocks.
2. Have worldedit installed and itemsadder worldedit compatibility addon
3. Select that build and //copy
4. //flip
5. //paste
6. See weird textures

**Expected behavior**
Blocks should be pasted seamlessly and keep textures.

**Screenshots**
Facade of building copied looks like:
[Original Screenshot](https://ibb.co/7WnxK8L)

Flipped result looks like:
[Flipped screenshot](https://ibb.co/GpzHgfX)

**Info (please complete the following information):**
 - Server version: Spigot 1.16.5
 - Client version: OptiFine 1.16.4
 - Plugin version: 2.1.33

**Additional context**
Same goes with //rotate.

**Comment by LoneDev6** [comment]
Are you using original Worldedit?

**Comment by NativeC** [comment]
Yessir. + your compatibility addon.

**Comment by LoneDev6** [comment]
Thanks for the info, please try the addon update, seems latest versions of Worldedit are not compatible anymore.
I should have fixed the issue. Let me know

**Comment by Caishangqi** [comment]
Hi, I had tried the latest version of WE, IA, and IA-WE, with spigot version 1.16.4, It seems still have the problem with command //replace and //set

Here is the video I capture
https://youtu.be/NhstvXftJ9w
