### ISSUE TITLE
[BUG] VehiclesPlus bug

### ISSUE THREAD

**Issue by RickyLaChow** [PluginBugs/Issues-ItemsAdder#650]
Ciao lone! 
Purtroppo c'è incompatibilità tra itemsAdder e VehiclesPlusPro, posso dare il file jar di ItemsAdder al dev di VehiclesPlusPro in modo da fixxare questo problema?

https://github.com/VolmitSoftware/VehiclesPlus/issues/73

**Comment by LoneDev6** [comment]
![immagine](https://user-images.githubusercontent.com/27242001/135716747-e1802810-3b7f-4744-b98f-60d1f7f91305.png)

**Comment by LoneDev6** [comment]
Still no answer from VehiclesPlus developer.
