### ISSUE TITLE
[Suggestion] Show Durability on Items that don't show.

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-ItemsAdder#651]
Hi Lonedev, 

I'm wondering if it's possible to show durability on Items when using hosts like FEATHER as an example and it show the durability decrease or replenish when the items used or mended?

**Comment by LoneDev6** [comment]
currerntly durability bar is not possible to be shown on items that have no durability in vanilla Minecraft, you have to use another item like golden_sword
