### ISSUE TITLE
[Suggestion] Stackable crafting recipes

### ISSUE THREAD

**Issue by JustJP2K** [PluginBugs/Issues-ItemsAdder#652]
I would like to be able to stack crafting recipes of one item to avoid having to duplicate the item recipe 9 times which adds to clutter the config.

Instead i would like to see something like this: 

pattern:
      - XXX
      - XLX
      - XXX
pattern:
      - XXX
      - XXL
      - XXX
pattern:
      - XXX
      - LXX
      - XXX
      
      Would be a great addition :)

**Comment by ArgonGaming** [comment]
Actually good idea, this can save a lot of space in the config and time

**Comment by LoneDev6** [comment]
Will be added in next update
