### ISSUE TITLE
//replace and //set command in WorldEdit still not working[BUG] 

### ISSUE THREAD

**Issue by Caishangqi** [PluginBugs/Issues-ItemsAdder#655]
**Describe the bug**
When I use the command //set and //replace, the block doesn't change, but if you broke the block you changed, the mushroom block would appear.

**To Reproduce**
▪ place IA custom block
▪ choose 2 points
▪ //set 
▪ //replace xxx to custom block
▪ The block does not change but become mushroom when you break the block.

**Expected behavior**
The block should be placed properly like //paste and //rotate 90/180 etc.

**Screenshots**
**[Video]( https://youtu.be/NhstvXftJ9w)**

![image](https://user-images.githubusercontent.com/39553613/107467344-acf52200-6b1a-11eb-8034-2f0fb8713810.png)

**Info (please complete the following information):**
 - Server version: spigot 1.16.4
 - Client version: Optfine E5 1.16.4
 - Plugin version: 
 - Itemsadder WorldEdit 1.0.2
 - Itemsadder 2.1.37
 - worldedit-bukkit 7.2.2

**Additional context**
I had tried the previous version of IA-WorldEdit and WorldEdit, but It has more serious problems.

**Comment by NativeC** [comment]
If I may add to this, my worldedit works even less now than it did before..... since the new update I can't even //replace anything anymore: it sais x blocks have been modified, but absolutely nothing happens texture-wise.

**Comment by LoneDev6** [comment]
I hate world edit. 
I wonder what the hell they modified in the previous updates.

Sorry for the inconvenience, I will try to fix the issues today, it's difficult as my addon is basically an "hack" for world edit to add custom blocks since there is no way to add that using their API (based on what I learnt)

**Comment by LoneDev6** [comment]
should be ok in the new update, let me know
https://www.spigotmc.org/resources/addon-itemsadder-worldedit.79012/

**Comment by Caishangqi** [comment]
> should be ok in the new update, let me know
> https://www.spigotmc.org/resources/addon-itemsadder-worldedit.79012/

NIce! thanks for modifying, it works :)
