### ISSUE TITLE
[BUG] Sounds don't play when pack is encrypted.

### ISSUE THREAD

**Issue by zainmz** [PluginBugs/Issues-ItemsAdder#656]
**Describe the bug**
Music discs and sounds do not play when the pack is encrypted using the option in config.

**To Reproduce**
1. Set protect-file-from-unzip__DISABLE_IF_ANY_PROBLEM: true
2. /iareload
3. /iazip
4. Load pack and play a music disc

**Expected behavior**
Music discs and other sounds should play normally

**Info (please complete the following information):**
 - Server version: paper 1.16.5
 - Client version: Optifine 1.16.5
 - Plugin version: 2.1.37

**Comment by LoneDev6** [comment]
use /iazip again to fix the zip file

this was fixed in one of the recent updates


let me know
