### ISSUE TITLE
[BUG] new minecraft_lang_overwrite feature has no way of removing overwrite

### ISSUE THREAD

**Issue by YouHaveTrouble** [PluginBugs/Issues-ItemsAdder#657]
There is no way to remove lang files overwrites. The only way to delete one is to literally go through every lang file in the pack and remove them one by one. 

**To Reproduce**
1. Add any overwrite for any minecraft translation string
2. Reload the pack
3. Remove the overwrite from the config
4. overwrite is still taking effect

**Expected behavior**
Overwrites generating fresh lang file and removing all possibly deleted overwrites

**Info:**
 - Server version: purpur 1.16.5
 - Client version:  1.16.5
 - Plugin version: 2.1.37

**Comment by LoneDev6** [comment]
Which ones? you mean the default ones?
You may have to disable this option to avoid itemsadder from writing its default language overwriters.
  `extract-default-items: false`

Default ones are to remove trading GUI title and color of armors in lore

**Comment by YouHaveTrouble** [comment]
Not the issue.
Try adding custom config with additional overwrites. Then delete it.

**Comment by LoneDev6** [comment]
> 
> 
> Not the issue.
> Try adding custom config with additional overwrites. Then delete it.
> Translation will keep being overwritten anyway. Without the option to clear it.

Did you set this to false?
`    overwrite-vanilla-lang-json__DISABLE_AT_YOUR_OWN_RISK: true`
This stops itemsadder from wiping out previous entries set in json languages files.
If this is not the case, then it's a bug

**Comment by YouHaveTrouble** [comment]
overwrite-vanilla-models__DISABLE_AT_YOUR_OWN_RISK: true
      protect-file-from-unzip__DISABLE_IF_ANY_PROBLEM: true
      overwrite-vanilla-lang-json__DISABLE_AT_YOUR_OWN_RISK: true

**Comment by LoneDev6** [comment]
thanks, i will fix this in the next update
