### ISSUE TITLE
[BUG] java.util.ConcurrentModificationException: null

### ISSUE THREAD

**Issue by ArgonGaming** [PluginBugs/Issues-ItemsAdder#658]
https://pastebin.com/0XgJN56v

**Info (please complete the following information):**
 - Server version: 1.16.5 Paper
 - Client version: 1.16.5
 - Plugin version: 2.1.37

**Additional context**
Weird error logged on console in the Pastebin above. Would love to get some support on potential causes! Thank you for your time ❤️

**Comment by LoneDev6** [comment]
did you try to reload the plugin multiple times one each another?
seems somehow ti tries to access config files multiple times which can cause that problem but it's rare

**Comment by ArgonGaming** [comment]
Ah okay, it may be that, hopefully does not appear again
