### ISSUE TITLE
[BUG] Console errors 

### ISSUE THREAD

**Issue by ValouProjet** [PluginBugs/Issues-ItemsAdder#659]
**Describe the bug**
When i restart my server or reload it, i have this in my console :
https://pastebin.com/GbGrvCWX

However, the plugin seems to be working fine, i have no bugs in the game.

**To Reproduce**
/

**Expected behavior**
/

**Screenshots**
/

**Info (please complete the following information):**
 - Server version: spigot 1.16.5
 - Client version: minecraft 1.16.5 (basic)
 - Plugin version: 2.1.37

**Additional context**
I spent my server from 1.15.2 to 1.16.5.

**Comment by LoneDev6** [comment]
Try to update your Spigot to the latest 1.16.5 build: https://serverjars.com/

Comment here if it doesn't fix the issue
