### ISSUE TITLE
[错误]Unhandled exception during tab completion for command '/iasummon and/iakill'

### ISSUE THREAD

**Issue by Aggerx** [PluginBugs/Issues-ItemsAdder#660]
**Describe the bug**

**To Reproduce**
1. Use instructions 'iakill'
1. Use instructions 'iasummon'

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - Server version: paper 1.16.5
 - Client version: fabric 1.16.4)
 - Plugin version: 2.1.37

**Additional context**
[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/5965940/latest.log)

**Comment by LoneDev6** [comment]
Thanks, I will fix that

**Comment by LoneDev6** [comment]
This happens when you have no custom mob installed in the plugin, you can get them in the addons website https://addons.plugin.ga/itemsadder
