### ISSUE TITLE
[BUG] Another plugin is trying to load a resourcepack

### ISSUE THREAD

**Issue by SlyJacobTheBeast** [PluginBugs/Issues-ItemsAdder#663]
**Describe the bug**
With the latest update I started seeing this in my console: [07:54:15 ERROR]: [ItemsAdder] !!! Another plugin is trying to load a resourcepack. Plese disable it. Player: 
I dont have any other plugin that uses resource pack, nothing changed with my plugins list, but it started appearing

**To Reproduce**
Install 2.1.37 version
Keep an eye on the console, some of the players joining get this message in console

**Info (please complete the following information):**
 - Server version: Paper 1.16.5
 - Client version: Vanilla 1.16.4
 - Plugin version: 2.1.37

**Comment by Fargus5** [comment]
Buongiorno Matteo, anche io, come l'utente qui sopra ho trovato un bug importante nel sistema di autoapply della resourcepack quando entri nel server
questo bug è sorto dal momento che ho fatto diversi /iareload e /iazip per aggiornare la resourcepack.
ora quando entro mi dice sempre che 
 [ERROR] [ItemsAdder] !!! Another plugin is trying to load a resourcepack. Plese disable it. Player: Fargus
e quindi mi da un failed to load the resourcepack. a me lascia entrare poiché come mi dicesti tu, ho il bypass. ma agli altri utenti no. (quindi là il kick funziona)... vai a capire perché il kick non funziona sul decline...

cmq... per ora disabilito l'autoapply .. come soluzione temporanea e ho rimesso su lo script che avevo creato che esegue un comando custom dopo 10 secondi che hai loggato e gli faccio fare /iatexture
in parole povere è tornato a comportarsi come prima dell'update che hai fatto.... fa due download della resourcepack e nonostante la carichi, e li fa sempre.
https://log.mtxserv.com/A4RJABv

Il mio delay-ticks nella configurazione dell'Apply on join è impostato su 200. che dovrebbero essere 10 secondi.
Invece lui tenta di applicare la resourcepack prima, non ci riesce e poi la riapplica una seconda volta. di fatto io vedo chiaramente che nello schermo fa 2 volte lo scaricamento.
ripeto: il problema non è dato da un altro plugin che tenta di caricare la resourcepack poiché 1. disabilitando l'apply on join di itemsadder nessuno tenta di applicarmi la resourcepack e 2. ho disabilitato i plugin che potrebbero tentare di farlo. Inoltre il problema è sorto dopo che ho modificato  più volte la resourcepack e ho quindi fatto /iareload e /iazip più volte per aggiungere spade.

**Comment by LoneDev6** [comment]
working on a fix for that, seems to be a bug of the resourcepack event loading not being unregistered and registered again after /iazip, so old events are still listening and reporting the error.

**Comment by SlyJacobTheBeast** [comment]
@LoneDev6 I have updated the plugin to the latest version and the error keeps popping up:
[23:27:32 ERROR]: [ItemsAdder] !!! Another plugin is trying to load a resourcepack. Plese disable it. Player: SlyJacob_

**Comment by LoneDev6** [comment]
> 
> 
> @LoneDev6 I have updated the plugin to the latest version and the error keeps popping up:
> [23:27:32 ERROR]: [ItemsAdder] !!! Another plugin is trying to load a resourcepack. Plese disable it. Player: SlyJacob_

Are you 100% sure no other plugin is trying to apply the resourcepack?
Does this happens if you use /iazip command while another /iazip command is processing?
Can I get a full log?
I suggest you to send me the log via discord ticketing to avoid exposing data, since I need the FULL log
