### ISSUE TITLE
[Suggestion] 🪑 Revamped Furniture Methodology

### ISSUE THREAD

**Issue by ArgonGaming** [PluginBugs/Issues-ItemsAdder#666]
### Introduction to the Issue
There are current issues with the method of furniture placement in ItemsAdder. Although, one of the best (if not the best) out there in terms of public plugins, I think it is time for it to be given some love, and upgraded to its full potential.

Currently, via "Behaviors" in the configuration, there are only a limited amount of options for furniture's, they must fit an armor stand and modeled in such a way that it is on the bottom part of it, and the "solid" feature may only apply a hitbox of 1 block size, (furniture should be less than a block size in order to make sense).

This limits a vast potential of options the Furnitures system COULD have.

### Potential Solution to the problem / Proposal
There are 2 methods I want added to the Furniture system that can solve everything, and allow for more options.

- [x] **1. Allow Furniture's to be placed via invisible Item Frames**

This not only helps with easier placement (no need to be limited with a block placement method with "OAK_WOOD"), but it also serves as a much more easier and natural-feeling way for "directional" placement of furniture's. 

> Example: A window panes furniture's placed via item frames will be easier to handle rather then having to adjust the model correctly with an Armor-stand, hit boxes (for breaking the item) will also be easier and more accurate.

- [x] **2. "Solid" / Better barrier blocks system**

As we know, the current "solid = true" behavior under furniture's simply places a barrier block. However, this is sadly limited to only one block. And it would be unrealistic for a plugin to "auto-detect" a models size and attempt to expand the barrier block size, so, I devised a solution.

Instead of letting the plugin figure it out, why not the player? Have the player identify how big (both vertically and horizontally) he wants his "solid" hitbox to be. Let him decide how many barrier blocks are placed, and where, when the furniture is placed.

This is how, as an idea, it would be done manually inside the configuration:

    behaviours:
      furniture:
        small_hitbox: false
        solid: true
            solid-parameters: enabled #Each "B" equals a barrier block, Each "X" equals Air
                vert-pattern: #Vertical axis of block placement defined
                - XXX
                - XBX #This would be the center line/piece
                - XBX
                horz-pattern: #Horizontal axis of block placement defined
                -  XXX
                -  XBX
                -  XBX
        gravity: false
        fixed_rotation: true
        opposite_direction: true
      furniture_sit:
        sit_height: 0.7
        opposite_direction: false

> Example: This would simple make 4 blocks of barrier blocks, 2 on the bottom, 2 on the top, in the same location. This would successfully make a hitbox for anything such as a, Vending machine, for example, as it may be 2x2 blocks tall and wide!

**Note:** I understand that this still has limitations, doing this means only ONE horizontal layer up, and only a few surrounding blocks. I had trouble thinking up a way to do 3D materialization via a text configuration. This is only an example, and a better more intuitive system can be done. I am simply here to put the idea in your head.

**Note:** If "sit = true" is still enabled, ALL barrier blocks should act as a sit function. It would be too complicated and useless to assign those individually.

### Pictures
![barrierblockschair](https://user-images.githubusercontent.com/30943826/107817021-87972c80-6d43-11eb-80be-d4f11d7a643b.png)

**Comment by ArgonGaming** [comment]
Issue #666 , nice.

**Comment by SirCraftypants** [comment]
The Barrier Block Solid function was never added for Chairs, it was added for objects such as Tables and Cupboards so you could place items on them, it was mine and Lonedevs colab. The directional placement works fine as far as my experience goes, I also like the fact you can walk through chairs, makes for easier navigation for the player. major changes like this mean many users having to rework their content and i honestly don't see any issues here. I've personally managed to create almost everything i've needed so far, from 3 seater chairs to 2 block high wardrobes?

**Comment by ArgonGaming** [comment]
> The Barrier Block Solid function was never added for Chairs, it was added for objects such as Tables and Cupboards so you could place items on them, it was mine and Lonedevs colab. The directional placement works fine as far as my experience goes, I also like the fact you can walk through chairs, makes for easier navigation for the player. major changes like this mean many users having to rework their content and i honestly don't see any issues here. I've personally managed to create almost everything i've needed so far, from 3 seater chairs to 2 block high wardrobes?

Yes, but that doesn't really invalidate the feature idea. What if some players / server owners don't want to be walk through? Adding functionality like this does not hurt any current ones, it is only another good option for custom furniture. A plugin such as ItemsAdder should have the ability to have functions for ANYTHING, not just Tables, and Cupboards. Expansion and more options means more ability to do creative things!

**Comment by SirCraftypants** [comment]
> 
> 
> > The Barrier Block Solid function was never added for Chairs, it was added for objects such as Tables and Cupboards so you could place items on them, it was mine and Lonedevs colab. The directional placement works fine as far as my experience goes, I also like the fact you can walk through chairs, makes for easier navigation for the player. major changes like this mean many users having to rework their content and i honestly don't see any issues here. I've personally managed to create almost everything i've needed so far, from 3 seater chairs to 2 block high wardrobes?
> 
> Yes, but that doesn't really invalidate the feature idea. What if some players / server owners don't want to be walk through? Adding functionality like this does not hurt any current ones, it is only another good option for custom furniture. A plugin such as ItemsAdder should have the ability to have functions for ANYTHING, not just Tables, and Cupboards. Expansion and more options means more ability to do creative things! If the ideology for not adding things is "It's not a problem for me, I'm fine with it", then things won't grow or produce even better content. I believe a lot of players would enjoy this type of option.

What you're suggesting makes no sense as if you use a Barrier Block for a Seat, no one's going to be able to sit on the seat unless the seat sit height is the same height as the barrier block itself. You can not sit inside a barrier block. If a Barrier slab existed you could in theory do it but with a barrier block i think it's not possible, everyone would be floating over the seat.  

LoneDev is always more than happy to add more options, more possibilities, i just don't think this particular one makes any sense with you pair the barrier block with a chair, it was never for that specific purpose.

**Comment by SirCraftypants** [comment]
If you can think of another way to make furniture solid then feel free to share it here, it would just need to be a way that doesn't prevent you from sitting below block height.

**Comment by ArgonGaming** [comment]
Actually he added the ability to right click the barrier block to sit inside, it's already tested and works, so this makes sense to me. And it wouldn't be just for chairs, it's multi-use. :)

**Comment by SirCraftypants** [comment]
> 
> 
> Actually he added the ability to right click the barrier block to sit inside, it's already tested and works, so this makes sense to me. And it wouldn't be just for chairs, it's multi-use. :)

Ok well i was unaware he implemented that, must have missed the update. Of course you can use it for anything you like, that was never in question. considering i was unaware of that update, had it not have been added then everything i previously said would in fact be true.

**Comment by SirCraftypants** [comment]
On the Other hand, you wanting to use Item frames instead of Armor Stands, that's an interesting theory.

**Comment by ArgonGaming** [comment]
> On the Other hand, you wanting to use Item Frames instead of Armor Stands, that's an interesting theory.
> 
> As far as the adjusting to the armor stand goes, i don''t find that an issue myself as i do that when i'm in blockbench creating the model itself. I'll be doing a tutorial on blockbench for beginners soon.

Reasons to use Item Frames are brilliantly shown in Origin Realms. It not only makes for a more accurate hitbox (for objects lower than the tall armor stand), but it is a much simpler and intuitive directional placement method. VERY good for one block paintings or window panes as such.

**Comment by LoneDev6** [comment]
Only thing that is not clear to be is how item frames would make things easier for the user / for me and this "Reasons to use Item Frames are brilliantly shown in Origin Realms.".
Hitbox would be even smaller compared to armorstands

**Comment by ArgonGaming** [comment]
Well the way they do it is, for anything that is too small, keep the item frame hitbox, but for anything that is larger, the hitbox corresponds with the barrier blocks (in that case, a need to use barrier blocks for larger assets, which is a good point)

**Comment by ArgonGaming** [comment]
If anything, the same can be said for Armor stands being "too big" of a hit box. For example if someone wanted to create a very small bottle furniture, but had to use armor stands, someone can easily break it without even looking at it. Very usual feature for smaller assets, and very situational, but worth the option.

**Comment by LoneDev6** [comment]
Update will be published in some days
