### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by xSorch** [PluginBugs/Issues-ItemsAdder#667]
**Describe the bug:**
Pretty sure that this bug has been there for a while, maybe not a bug. Basically, if you have two different worlds, one for Spawn and one for the main world and you set the spawn point in the world called "Spawn". As soon as new players connect, they are put in the main world "world" then teleported to the Spawn world "Spawn" just within a few milliseconds. The issue with that is that the prompt thing that pops up on the screen asking them to accept the resource pack disappears. So if you are forcing players to use the resource pack, they will bypass that prompt and will just end up seeing [], without getting kicked. However, it is all fine when they rejoin.

**Comment by SirCraftypants** [comment]
> 
> 
> **Describe the bug:**
> Pretty sure that this bug has been there for a while, maybe not a bug. Basically, if you have two different worlds, one for Spawn and one for the main world and you set the spawn point in the world called "Spawn". As soon as new players connect, they are put in the main world "world" then teleported to the Spawn world "Spawn" just within a few milliseconds. The issue with that is that the prompt thing that pops up on the screen asking them to accept the resource pack disappears. So if you are forcing players to use the resource pack, they will bypass that prompt and will just end up seeing [], without getting kicked. However, it is all fine when they rejoin.

It's not Itemsadder causing this as IA does not deal with spawn points or spawn settings, rather than force your players to teleport within seconds from the spawn world to the main world. place a way for them to teleport themselves to the main world from the spawn world. This gives your players the chance to accept the resource pack before they join the main world. I'd say why not just have them join the main world instead of the spawn world first but i'm guessing you want it that way.

**Comment by xSorch** [comment]
I might have already figured it out, doing som more testing on it, but a way ItemsAdder could

> > **Describe the bug:**
> > Pretty sure that this bug has been there for a while, maybe not a bug. Basically, if you have two different worlds, one for Spawn and one for the main world and you set the spawn point in the world called "Spawn". As soon as new players connect, they are put in the main world "world" then teleported to the Spawn world "Spawn" just within a few milliseconds. The issue with that is that the prompt thing that pops up on the screen asking them to accept the resource pack disappears. So if you are forcing players to use the resource pack, they will bypass that prompt and will just end up seeing [], without getting kicked. However, it is all fine when they rejoin.
> 
> It's not Itemsadder causing this as IA does not deal with spawn points or spawn settings, nor is this a bug. Rather than force your players to teleport within seconds from the spawn world to the main world. place a way for them to teleport themselves to the main world from the spawn world. This gives your players the chance to accept the resource pack before they join the main world. I'd say why not just have them join the main world instead of the spawn world first but i'm guessing you want it that way.

I might have already figured out a way for it, doing some testing on it, however there is also a way ItemsAdder could fix this, by maybe giving us an option in the config for when this "Prompt" should show up, in terms of seconds after join.

**Comment by LoneDev6** [comment]
I'm sorry I have no way to deal with teleports during resourcepack installation as if I add any check on that it will surely desync from the client.
I suggest you to make your player teleport to the right world after the resourcepack is applied, you may make a plugin that listens to the resourcepack event, or a [skript like that](https://forums.skunity.com/threads/resourcepack-deny-skript-mirror.6500/)

or even easier make a portal that teleports them to the right world
