### ISSUE TITLE
[BUG] Resourcepack URL is not valid. Not a zip file. Type: application/x-zip-compressed

### ISSUE THREAD

**Issue by Miuss** [PluginBugs/Issues-ItemsAdder#668]
**Describe the bug**
Why /iazip Command create a X-zip-compressed zip?
`Resourcepack URL is not valid. Not a zip file. Type: application/x-zip-compressed Url: https://download.pan.miuss.pro/uploads/2021/02/13/NHgsIyjC_pack.zip`

**Screenshots**
![image](https://user-images.githubusercontent.com/26337587/107844473-95fe4a80-6e0e-11eb-8a5c-d48440a1cf31.png)

**Info (please complete the following information):**
 - Server version: paper 1.16.5
 - Client version: fabric 1.16.5
 - Plugin version: 2.1.38

**Comment by LoneDev6** [comment]
Worldpress messes up with zip file encoding. I have no idea why it sets it to application/x-zip-compressed which is not correct and won't work on Minecraft

Please use DropBox or this website https://mc-packs.net/
