### ISSUE TITLE
[Suggestion] Compatiblity with Buildcraft style quarry plugin

### ISSUE THREAD

**Issue by o0AzzA0o** [PluginBugs/Issues-ItemsAdder#669]
Compatibility With Buildcraft Quarry Plugin Spigot

[
![image](https://user-images.githubusercontent.com/1347883/107851782-5df20a00-6e04-11eb-9b01-a0b84aa2f3e2.png)
](url)

I would love to see compatibility added with this plugin as it also uses custom textures. As i can see the 2 overlaps with this texture currently is stone.json and spawners.json

Alternative is to migrate this into a custom item within the itemsadder framework then request the developer of the quarry plugin hooks into the ItemsAdder api?

Resource links for plugin and the texturepack:
[https://www.spigotmc.org/resources/quarries-1-14-x-1-15-x-buildcraft-without-mods.72040/](url)
[https://drive.google.com/file/d/1WFLCUwTlKcX4YJjCPazWsAAg48YfQWEP/view](url)

**Comment by LoneDev6** [comment]
Would be cool if the author of the other plugin would create an addon (which would basically be a resourcepack conversion + itemsadder configs) to speed up the process as I don't know the other plugin deeply.

If needed I can provide them a free copy of itemsadder

**Comment by o0AzzA0o** [comment]
Thank you I will ask the dev
