### ISSUE TITLE
[BUG] Mushroom Desync

### ISSUE THREAD

**Issue by williamd002** [PluginBugs/Issues-ItemsAdder#670]
Desync issue with mushroom blocks

1. go to mushroom biome
2. get mushroom block
3. put mushroom blocks anywhere and delete them
4. Other players will still see the blocks there
5. for them to delete the blocks, they simply click on them and then they vanish (see video below)

**Expected behavior**
Mushroom blocks should be destroyed when removed by one player but they still remain

**Screenshots**
https://youtu.be/DjbeiaKHhNo

**Info (please complete the following information):**
 - Server version: Spigot 1.16.4
 - Client version: 2.2.1431
 - Plugin version: 2.1.37

**Additional context**
Problem only seems to be for mushroom blocks. If you look at the YouTube video it shows how it doesnt work properly.
api-version: 1.14

**Comment by davcpas1234** [comment]
Working with @williamd002 on this one this is what we are seeing after deleting the fix_glitched_blocks cache file:
![image](https://user-images.githubusercontent.com/3764587/108147605-1058f400-70c7-11eb-96dc-384050abc1bd.png)

**Comment by davcpas1234** [comment]
Occurs after placing a block on top of the mushroom blocks

**Comment by LoneDev6** [comment]
> 
> 
> Desync issue with mushroom blocks
> 
> Steps to reproduce the behavior:
> 
>     1. go to mushroom biome
> 
>     2. get mushroom block
> 
>     3. put mushroom blocks anywhere and delete them
> 
>     4. Other players will still see the blocks there
> 
>     5. for them to delete the blocks, they simply click on them and then they vanish (see video below)
> 
> 
> **Expected behavior**
> Mushroom blocks should be destroyed when removed by one player but they still remain
> 
> **Screenshots**
> https://youtu.be/DjbeiaKHhNo
> 
> **Info (please complete the following information):**
> 
>     * Server version: Spigot 1.16.4
> 
>     * Client version: 2.2.1431
> 
>     * Plugin version: 2.1.37
> 
> 
> **Additional context**
> Problem only seems to be for mushroom blocks. If you look at the YouTube video it shows how it doesnt work properly.
> api-version: 1.14

I thought I had already fixed that issue, please try to update to the latest version of the plugin.

Also please check if the issue occurs only on creative mode
