### ISSUE TITLE
[BUG] Console Errors

### ISSUE THREAD

**Issue by Agaloth** [PluginBugs/Issues-ItemsAdder#673]
**Describe the bug**
A lot of itemsadder + lonelibs console errors

**Expected behavior**
No console errors

**Screenshots**
https://pastebin.com/BBYzeSHJ

**Info (please complete the following information):**
 - Server version: purplane build #3 https://ci.notom3ga.me/job/Purplane/3/ (fork of airplane which is a fork of tuinity)
 - Client version: Vanilla 1.16.5 (lunar client)
 - Plugin version: 
ItemsAdder version 2.1.38
LoneLibs version 1.0.7

**Comment by LoneDev6** [comment]
the error is pterry clear: java.lang.NoClassDefFoundError: net/tnemc/libs/org/json/simple/JSONObject

something is interfering with lonelibs, seems by overwriting a class.
I suggest you to check if the error disappears when using paper or spigot.
If yes, please remember which plugin did you install recently and remove it.
Let me know.

as always: these forks are not officially supported as i cannot make the plugin working with each fork in the world
