### ISSUE TITLE
[BUG] Items with itemadder in RWG building

### ISSUE THREAD

**Issue by xiaobailoves** [PluginBugs/Issues-ItemsAdder#676]
**Describe the bug**
![image](https://user-images.githubusercontent.com/71917424/108461758-3a4f1980-7273-11eb-8663-46c48beb2c9b.png)

**To Reproduce**
1. See error

**Expected behavior**
RWG generated buildings will form itemadder items
I'm Chinese so my Enlish is not very good. I'm sorry

**Screenshots**
![image](https://user-images.githubusercontent.com/71917424/108461758-3a4f1980-7273-11eb-8663-46c48beb2c9b.png)

**Info (please complete the following information):**
 - Server version: paper 1.16.4
 - Client version: Vanilla 1.16.4
 - Plugin version: latest

**Additional context**
No error report file

**Comment by LoneDev6** [comment]
I don't own RWG and I don't know how it works, so that's what I'd do:
check if you can edit the structure blocks and change the mushroom blocks to something else

let me know
