### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by shmezi** [PluginBugs/Issues-ItemsAdder#677]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Use a custom block that uses the chorus plant as it's block.
2. Place a chorus flower on the block
3. It's able to be placed, and then creates a bunch more broken blocks
**Expected behaviour**
It shouldn't be able to be placed

**Screenshots**
![image](https://user-images.githubusercontent.com/67468040/108496005-3098d680-72b2-11eb-862f-c58425151e2f.png)

**Info (please complete the following information):**
 - Server version: (paper 1.16.5)
 - Client version: (fabric 1.16.4)
 - Plugin version: (2.1.39)

**Additional context**

**Comment by LoneDev6** [comment]
Please check if this happens in survival mode.
It should be only a creative bug (which I cannot fix as some events are clientside).

Let me know

**Comment by shmezi** [comment]
> Please check if this happens in survival mode.
> It should be only a creative bug (which I cannot fix as some events are clientside).
> 
> Let me know

It also happens in survival.

**Comment by LoneDev6** [comment]
Thanks, I fixed that in the new update.
Let me know.
