### ISSUE TITLE
[Suggestion] Add the ability to add craft items in the blacksmith table!

### ISSUE THREAD

**Issue by samodyr** [PluginBugs/Issues-ItemsAdder#678]
This will be a cool feature that will add more space for imagination.

Well, I just want to upgrade my custom diamond items to netherite.
My wish is very simple, but if it is realized, it will give me a lot of joy :)

**Comment by GuazP** [comment]
+1

**Comment by LoneDev6** [comment]
CustomCrafting is compatibile with ItemsAdder, I'd use it in the meantime.
Keep in mind that I didn't code this plugin so I have no idea if it's resource intensive (Minecraft recipes plugins are usually very CPU consuming, ItemsAdder recipes are coded with performance in mind).

https://www.spigotmc.org/resources/customcrafting-advanced-custom-recipe-plugin-1-14-1-17-free.55883/
