### ISSUE TITLE
[BUG] permission ia menu

### ISSUE THREAD

**Issue by istarengwa** [PluginBugs/Issues-ItemsAdder#679]
**Describe the bug**
Hello, on the wiki, the / ia permission system for players is not the same on every page, and is not the same directly in the plugin, I can't find the right permissions to choose which recipe a player can see or not, with the object categories directly (as on the itemadders v1). I just can't find the permissions I need for each itemadders menu like I had before.

Just courtesy "ia.user.ia" players can see 2 sub menus, but empty, Builder's basic and Spooky pack.

**Expected behavior**
Without any perm other than the ia.user.ia there should be no categories displayed and with permission ia.user.ia.armors have the armor crafts, or ia.user.ia.itemsadder have the blocks of base itemsadder.

**Screenshots**
https://zupimages.net/viewer.php?id=21/07/hoti.png.

**Info (please complete the following information):**
 - Server version: purpur (paper 1.16.5)
 - Client version: optifine 1.16.5
 - Plugin version: 2.1.40

**Comment by istarengwa** [comment]
I found out why we were seeing the menus, it didn't have permission to configure. But on the other hand the permissions bug persists or I don't know how to use it.

if I add the permission "ia.user.ia" and "ia.user.ia.itemsadder.ruby_block" or "ia.user.ia.ruby_block" absolutely nothing is displayed when a player use "/ia"

**Comment by LoneDev6** [comment]
Hello,
check the permissions examples https://itemsadder.plugin.ga/plugin-usage/permissions/example-permissions

probably missing this one `ia.menu.*` (see all categories in /ia menu)
