### ISSUE TITLE
[BUG] Farmland "remembers" and saves the first IA crops ever placed

### ISSUE THREAD

**Issue by imparium-de** [PluginBugs/Issues-ItemsAdder#683]
**Describe the bug**
When creating farmland, ItemsAdder remembers the first crops ever placed on that farmland and ignores the crops placed after. Replacing the farmland and restarting the server doesn't fix this issue.

**To Reproduce**
1. Create some farmland
2. Place custom IA crops (i.e. Chilli)
3. Farm the Chilli and place vanilla wheat crops
4. Break the wheat crops
5. See error

**Expected behavior**
You should get vanilla wheat instead of chilli

**Screenshots**
https://s.imparium.de/niho0/duFuVozA30.mp4 (Shows it the best. All crops got planted with vanilla wheat crops)
https://s.imparium.de/niho0/pizOLUle02.mp4 (Issue still occurs after replacing the farmland)

**Info (please complete the following information):**
 - Server version: Paper 1.16.5
 - Client version: Forge 1.16.4 (35.1.36)
 - Plugin version: 2.1.35

**Comment by LoneDev6** [comment]
Thanks, I'm working on a fix.
Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/597
