### ISSUE TITLE
[Suggestion] The order of execution of events, actions

### ISSUE THREAD

**Issue by MrJorman** [PluginBugs/Issues-ItemsAdder#686]
Make a queue or set a delay for the implementation of the events of the subject. For example, I want to get Thaumonomicon from Thaumcraft, so I click Salis Mundus on the bookshelf and there is music with particle effects, after 1-2 seconds the bookshelf turns into an" Object", whether from Minecraft Vanilla or from the ItemsAdder plugin, you need to add support for this function and delay settings.

**Comment by LoneDev6** [comment]
Will be added in next update `delay` attribute of the action (ticks: 20 ticks = 1 second)
