### ISSUE TITLE
[Suggestion] Infinity Food

### ISSUE THREAD

**Issue by MrJorman** [PluginBugs/Issues-ItemsAdder#687]
Add a function so that the food can be infinite, via the commands

first_example:
command: 'iaremove {player} edem_apple'
as_console: true
second:
command: 'iagive {player} edem_apple'
as_console: true

I have a spam console, as well as the player is always displayed messages, in the Botania mod there is an Infinite apple, this is a legendary thing and I want to do something like the same thing, but I can't make the apple infinite. Please fix it or make a function for it.

**Comment by LoneDev6** [comment]
/iaremove has a silent parameter, which is the last one, set it to true.

`/iaremove <player> <itemNameInConfig> [amount] [silent]`
