### ISSUE TITLE
[BUG] Drop EXP in the face from Custom Block

### ISSUE THREAD

**Issue by MrJorman** [PluginBugs/Issues-ItemsAdder#688]
Fix the loss of experience from custom ores, blocks, because the experience does not fall out of the ore, but directly to the player, as if by command, please make it fall out of the ore itself, as in Vanilla Minecraft.

events:
        placed_block:
            break:
                drop_exp:
                    chance: 100
                    min_amount: 5
                    max_amount: 10

**Comment by LoneDev6** [comment]
Thanks, this will be fixed in the next update
