### ISSUE TITLE
[Suggestion] Loots day/night

### ISSUE THREAD

**Issue by MrJorman** [PluginBugs/Issues-ItemsAdder#689]
I have the essence of light and the essence of darkness on the server, like in a terrarium, and I can't make it fall out at night-the essence of darkness, and the essence of light during the day, add the function, please

**Comment by LoneDev6** [comment]
already implemented 
https://itemsadder.plugin.ga/plugin-usage/adding-content/advanced/mobs/itemsadder-internal
            time:
              start: MIDNIGHT

this will spawn only from NIGHT to MIDNIGHT basically
