### ISSUE TITLE
[BUG] PlayerHudWrapper NPE

### ISSUE THREAD

**Issue by ItsMacs** [PluginBugs/Issues-ItemsAdder#690]
**Describe the bug**
A NullPointerException gets thrown by PlayerHudWrapper when accessing a valid bar (manabar)

java.lang.NullPointerException: null
	at dev.lone.itemsadder.api.FontImages.PlayerHudWapper.<init>(SourceFile:13) ~[?:?]
	at dev.lone.itemsadder.api.FontImages.PlayerQuantityHudWapper.<init>(SourceFile:11) ~[?:?]

**To Reproduce**
1. Paste this code onto a plugin:

PlayerHUDsHolderWrapper huds = new PlayerHUDsHolderWrapper(player);
        PlayerQuantityHudWapper manaHud = new PlayerQuantityHudWapper(huds, "magiccraft:mana_bar");
        manaHud.setVisible(true);

2. See error.

**Info (please complete the following information):**
 - Server version: Paper 1.15.2
 - Client version: Lunar Client 1.15.2, even though not applicable
 - Plugin version: 2.1.40

**Comment by LoneDev6** [comment]
make sure you're waiting for the the event ItemsAdderFirstLoadEvent.
huds may not be loaded instantly at server startup.

let me know if it's the case
