### ISSUE TITLE
[Suggestion] Add a sound event for hit_block:

### ISSUE THREAD

**Issue by MrJorman** [PluginBugs/Issues-ItemsAdder#691]
My players and everyone are already tired of the sound of breaking a mushroom block when you break a custom block, so if there is an opportunity in events to play the sound of place and break, why not add the ability to specify block_hit ? When you get a block or hit it, the sound of the block that I specify will play.

**Comment by LoneDev6** [comment]
by "hit" you mean punching it or falling on it?
