### ISSUE TITLE
[Suggestion] Additional `Child` for custom fonts in `config.yml`

### ISSUE THREAD

**Issue by benevolent2012** [PluginBugs/Issues-ItemsAdder#692]
**Is your feature request related to a problem? Please describe.**
It seems if I use custom **ttf** fonts, certain fonts don't display it at the size I wish it to be in. Also, some of the bold fonts are not bold, but rather combined together with spacing in the middle, making it seem like there are two copies of the same letters.

**Describe the solution you'd like**
Allow `config.yml` to specify children to be used to edit the `assets/minecraft/font/default.json` fild. So a place where you can specify values such as

```
"shift": [0, 0],
"size": 12.0,
"oversample": 6.0
 ```
There might be more 'children' flags that may be used, but that's all I have found while trying out different fonts.

so config.yml might look like this:
```yaml
custom-font:
    enabled: true
    name: font.ttf
    shift: [0,0]
    size: 12.0
    oversample: 6.0
```

The **bdcraft** font's `default.json` looks like this
```json
{
	"providers": [
	    {
		   "type": "ttf",
		   "file": "minecraft:comickbookbdcraft.ttf",
 			"shift": [0, 0],
 			"size": 12.0,
 			"oversample": 6.0
	    }
 	]
 }	
```

**Describe alternatives you've considered**
Converting the ttf files into png files. 

**Additional context**
![image](https://user-images.githubusercontent.com/68626312/108647368-54544c00-746d-11eb-89bd-94e162f21e21.png)

(This is a normal bdcraft texturepack (which can be found in [this link](https://bdcraft.net/downloads/purebdcraft-minecraft/font-addon/))

**Comment by LoneDev6** [comment]
Thanks, I added this in the new update.
Let me know if there is any problem.

Remember to use /iazip again in order to refresh the zip
