### ISSUE TITLE
items adder custom items does not work at all

### ISSUE THREAD

**Issue by anthony114669** [PluginBugs/Issues-ItemsAdder#693]
**Describe the bug**
i dunno what happend but nothig is working, i mean the philosepher stone the magic wand the water skin the custom food nothing seems works, and before was working i dunno if is something i did or a bug but nothing seem s wroking with the special effecto of the items and the food the drinks nothing works D: omg i need help thanks in advance

**To Reproduce**
1. Go to ia
2. Click on any item
3. drin water, eat food try magic wand or any custom item with special features and nothing works (atleas on my server)

**Expected behavior**
works the new and custom items features

 - Server version: paper 1.16.5
 - Plugin version: ExecutableItems ⭐ Create Custom Items ⚡ 700+ SERVERS ⚡ [1.12 - 1.16.5] ✅ 2.7.3.4

**Additional context**
before was working fine i guess something get bugged with the new update thanls im advance

**Comment by LoneDev6** [comment]
thanks i'm working on an update
