### ISSUE TITLE
[BUG] Error when i sending message to server

### ISSUE THREAD

**Issue by ArtifactyNight** [PluginBugs/Issues-ItemsAdder#694]
**Describe the bug**
it's error when i chat in-game.
if i installed CMI / Essentials, it's will happen.

yeah.. emoji not working when i installed these plugins

**To Reproduce**
1. Install Essentials or CMI
2. try to sending message / emoji in game
3. See errors

**Expected behavior**
it's should be not have this error :joy:
and emoji gonna displaying in chat

**Logs**
Full logs: https://mclo.gs/0d4ReEM
Error logs: https://mclo.gs/T5CVV1Z

**Screenshots**
![2021-02-22 19-47-55](https://user-images.githubusercontent.com/53427253/108710627-e5e3bc80-7546-11eb-84ba-f21c1da15323.png)

**Info (please complete the following information):**
 - Server version: Paper 1.16.5
 - Client version: Optifine 1.16.5
 - Plugin version: 2.1.39

**Additional context**
Itemsadder 2.1.40 still have this issues

**Comment by LoneDev6** [comment]
Hello,
it has something to do with https://github.com/KyoriPowered/adventure
I have no idea of what is that thing sincerely, surely nothing official

**Comment by ArtifactyNight** [comment]
uh ... ? i don't understand 😓

**Comment by LoneDev6** [comment]
I read the log and noticed that, which means another plugin/code is altering the chat: `net.kyori.adventure.text.TextComponentImpl`
I searched online and it's this thing https://github.com/KyoriPowered/adventure

Seems Paper devs recently introduced that problem, please report that issue on Paper GitHub https://github.com/PaperMC/Paper/issues
Seems to be about that update: https://github.com/PaperMC/Paper/commit/a235c77ce7a535f9ef16c44758f43b58c2547f55

**Comment by LoneDev6** [comment]
There it is, someone else already reported, I hope they will fix it: https://github.com/PaperMC/Paper/issues/5216

**Comment by LoneDev6** [comment]
Fixed in the new update, please let me know

**Comment by ArtifactyNight** [comment]
tuinity is fixed but papermc not

**Comment by ArtifactyNight** [comment]
oh yes it's working rn in `2.1.42`
but if i using Tuinity. so i can use `2.1.41` without that errors

thank you so much!
