### ISSUE TITLE
[BUG] Custom Ore with Blasting Furnace

### ISSUE THREAD

**Issue by MrJorman** [PluginBugs/Issues-ItemsAdder#696]
https://youtu.be/mpYH0vI1z2s pls check video BUGG, and PLS FIIX

**Comment by MrJorman** [comment]
i use SHIFT+LKM from furnace - i'ts okay
i use SHIFT+LKM from Blasting Furnace - i have visual bugg

**Comment by LoneDev6** [comment]
Thanks, fixed in the new release
