### ISSUE TITLE
[BUG] Vehicle bug

### ISSUE THREAD

**Issue by Fantom250YT** [PluginBugs/Issues-ItemsAdder#697]
**Describe the bug**
So it was working fine but now when I place a vehicle, plane for instance it gives this error in console `[14:30:44 ERROR]: POI data mismatch: never registered at BlockPosition{x=-7, y=100, z=0}`, sometimes I can fuel it and that works then I try to enter it and this comes up in chat:
`[14:30:50 INFO]: Attempt to teleport dead player Fantom250YT restricted`
^ this occurs when I try to enter the vehicle after giving it the required resource to fuel, the item then can't be broken or entered and I can't send messages or commands in chat as it says `cannot send chat message`, don't think it's physically there anymore as I log out and log back in and it isn't there.

Started happening on **2.1.39**, not straight away and then I changed to **2.1.40**, but it didn't fix

**Info (please complete the following information):**
 - Server version: paper 1.16.5
 - Client version: 1.16.4
 - Plugin version: **2.1.39**/**2.1.40**
<img width="735" alt="Screenshot 2021-02-22 at 16 29 21" src="https://user-images.githubusercontent.com/73852683/108738157-39e0a800-752b-11eb-8e2b-bde88b358cdd.png">

**Comment by LoneDev6** [comment]
You can ignore the POI data mismatch since it's a spigot warning they should fix in next releases.

About the chat problem please read here and let me know: https://itemsadder.plugin.ga/faq/vehicles-bugs/towny-vehicles-bug

**Comment by 100petr** [comment]
#218 maybe same problem?

**Comment by Fantom250YT** [comment]
I have WorldGuard, might be that problem as I didn't have worldguard in the area when it was working

**Comment by Fantom250YT** [comment]
Yep, it was WorldGuard stopping it from working! Thanks for your help

**Comment by LoneDev6** [comment]
No problem!
Happy you managed to fix the issue.

Have nice day 😄
