### ISSUE TITLE
[BUG] costum food does not fill hunger, no effects

### ISSUE THREAD

**Issue by DayzDuck** [PluginBugs/Issues-ItemsAdder#699]
I updated ItemsAdder from 1.16.4 to 1.16.5. All textures and other self-inserted objects and items work perfect.
Just all the added food gives no effects and no hunger. However, the textures work and the console and logs do not throw any errors.
Here is an example of two different types of food i added to Itemsadder:

  milchmitkeks:
    display_name: "Milch mit Keks"
    permission: food
    resource:
      material: BREAD
      generate: true
      textures:
      - item/milchmitkeks
    events:
      eat:
        feed:
          amount: 7
        potion_effect:
          type: SATURATION
          duration: 400

  kartoffelsuppe:
    display_name: "Kartoffelsuppe"
    permission: food
    resource:
      material: MUSHROOM_STEW
      generate: true
      textures:
      - item/kartoffelsuppe
    events:
      eat:
        feed:
          amount: 8
        potion_effect:
          type: SATURATION
          duration: 3600

**Comment by LoneDev6** [comment]
update the plugin

**Comment by DayzDuck** [comment]
I'm running the newest version(2.1.41) of Itemsadder.

**Comment by LoneDev6** [comment]
Thanks, I will make some tests now, very strange..

Anyway I noticed you're using the potion effect to give saturation, you can use the new attribute "saturation", check this page https://itemsadder.plugin.ga/plugin-usage/adding-content/advanced/item-properties/events/actions#what-are-actions

```yml
feed:
  amount: 6
  saturation: 2
```
Use this editor https://ide.plugin.ga/itemsadder/

**Comment by DayzDuck** [comment]
Ah, thank you. I will do!

**Comment by LoneDev6** [comment]
I tested with pizza, banana and hamburger and it does feed the player.
Can you check your config using my online editor? it may have some errors https://ide.plugin.ga/itemsadder/

If you still have problems please post your files using pastebin or similar, to keep the spaces

**Comment by DayzDuck** [comment]
I will do some tests
