### ISSUE TITLE
[Suggestion] Customizable Pack-loading Title

### ISSUE THREAD

**Issue by ArgonGaming** [PluginBugs/Issues-ItemsAdder#700]
**Is your feature request related to a problem? Please describe.**
The pack loading title has inproper english, and in general, would be a good to have the option to either change what it says, or toggle it off.

**Describe the solution you'd like**
A small configuration line in the main config.yml that can change and toggle the loading title

**Additional context**
![image](https://user-images.githubusercontent.com/30943826/108774091-3b12d480-752d-11eb-95e0-d04993462401.png)

**Comment by LoneDev6** [comment]
Should already be editable in the lang file
```yml
resourcepack-apply-title: '&a&lApplying resourcepack...'
resourcepack-apply-subtitle: '&6Please be patient, it will take only some seconds!'
```

**Comment by ArgonGaming** [comment]
Thank you!
