### ISSUE TITLE
[Suggestion] Allow for Network-wide Resource Pack (Velocity)

### ISSUE THREAD

**Issue by ArgonGaming** [PluginBugs/Issues-ItemsAdder#701]
**Is your feature request related to a problem? Please describe.**
Currently, using the resource pack on a network of servers can be troublesome. Having to update the pack for each server, the reloading of packs, etc. 

**Describe the solution you'd like**
The plugin, IN GENERAL would be so much more awesome if it had a BungeeCord / Velocity version. **HOWEVER** Today I am talking about an open source plugin to implement this feature with.

Velocity is a better performing network method but with drawbacks. No Bungeecord plugins are compatible with it at the moment as it requires some special work.

However, in terms of loading the same resourcepack on the entire network, which is what is being proposed, there is an [OPEN SOURCE plugin](https://forums.velocitypowered.com/t/velocityresourcepacks-manage-resourcepacks-for-servers-and-whole-proxy/515) from Velocity that I think would be awesome to natively incorporate into ItemsAdder.

**Additional context**
https://forums.velocitypowered.com/t/velocityresourcepacks-manage-resourcepacks-for-servers-and-whole-proxy/515

**Comment by LoneDev6** [comment]
I need to add support to my plugin BungeePackFix: https://www.spigotmc.org/resources/%E2%9A%99%EF%B8%8Fbungeepackfix.96794/

Source code is here if anyone wants to help: https://github.com/LoneDev6/BungeePackFix

**Comment by LoneDev6** [comment]
Implemented in bungeepackfix
