### ISSUE TITLE
[BUG] Server Resouce Packs: Prompt - Not working

### ISSUE THREAD

**Issue by Tanerx** [PluginBugs/Issues-ItemsAdder#704]
**Describe the bug**
If server added client as "Server Resouce Packs: Prompt" pack.zip will not downloaded. If admin type /iatexture or /iatexture all prompt screen is coming.  Clicking yes will download the pack.zip and working fine after.

**To Reproduce**
Join the server

**Expected behavior**
Ask client Prompt when join.

This is bug ? Or all users have to set "Server Resouce Packs: Enabled"

**Comment by LoneDev6** [comment]
Sorry but I cannot help you since you basically omitted all the required info for me to identify a possible issue.
Anyway I suggest you to open a ticket on my Discord server providing all the requested info.

Thanks for the patience
