### ISSUE TITLE
[BUG] 2 bugs from 1 item crafting :)

### ISSUE THREAD

**Issue by MrJorman** [PluginBugs/Issues-ItemsAdder#705]
https://youtu.be/drAIppZLIw0 check pls video

**Comment by MrJorman** [comment]
salis_mundus:
    display_name: '&eСоль тауматурга'
    lore:
     - '&7Используйте &eПКМ &7по книжной полке'
     - '&7для получения &eтаумономикона&7.'
    permission: salis_mundus
    resource:
      material: CARROT_ON_A_STICK
      generate: true
      textures:
      - item/salis_mundus.png
    durability:
      max_custom_durability: 1
      custom_durability: 1
      disappear_when_broken: true
    item_flags:
    - HIDE_ATTRIBUTES
    events:
      interact:
        right_shift:
          play_sound:
            name: bossitems:items.salis_mundus
            volume: 1
            pitch: 0.9
          replace_near_blocks_bookshelf:
            radius:
                x: 1
                y: 1
                z: 1
            from: BOOKSHELF
            to: bossitems:thaumonomicon_block
            decrement_durability: 1
            no_physics: true
          replace_near_blocks_stone:
            radius:
                x: 1
                y: 1
                z: 1
            from: STONE
            to: COBBLESTONE
            decrement_durability: 1
            no_physics: true
          replace_near_blocks_glass:
            radius:
                x: 1
                y: 1
                z: 1
            from: SAND
            to: GLASS
            decrement_durability: 1
            no_physics: true
          play_particle:
            name: DRAGON_BREATH

**Comment by MrJorman** [comment]
recipes:
  crafting_table:
    salis_mundus:
      permission: bossitems.salis_mundus
      enabled: true
      pattern:
      - XXX
      - DEF
      - ABC
      pattern2:
      - XXX
      - EDF
      - ABC
      pattern3:
      - XXX
      - EDF
      - BAC
      pattern4:
      - XXX
      - EDF
      - ABC
      ingredients:
        A: BOWL
        B: FLINT
        C: GOLD_INGOT
        D: GLOWSTONE_DUST
        E: REDSTONE
        F: LAPIS_LAZULI
      result:
        item: bossitems:salis_mundus
        amount: 1
      return_items:
        replace:
          BOWL: BOWL
          FLINT: FLINT

**Comment by LoneDev6** [comment]
Can you please share your configuration on a website like pastebin? It's unreadable.
Thanks

**Comment by MrJorman** [comment]
https://pastebin.com/aYj8JtDP

**Comment by MrJorman** [comment]
https://pastebin.com/i7zXj8xd

**Comment by LoneDev6** [comment]
I cannot reproduce the issue using the very latest itemsadder update. I used the same exact recipes you sent me.
Check the videos here: https://imgur.com/a/nk5aKrb
Please make sure nothing failed to load, check your logs and check if any strange error is printed on console.

Thanks
