### ISSUE TITLE
[BUG] Mushrooms are non existant for players with weird behavior

### ISSUE THREAD

**Issue by JustJP2K** [PluginBugs/Issues-ItemsAdder#706]
**Describe the bug**
Mushrooms are bugged, basically non existent 

**To Reproduce**
Use itemsadder with forestry addon

**Expected behavior**

**Screenshots**
mushrooms are broken for players
they are gone
![image0](https://user-images.githubusercontent.com/74447960/108869458-842f5b00-75f7-11eb-9777-19c50c16da5d.jpg)
its just a shadow.
https://youtu.be/3YXGQ3FGFdQ
weird behavior 

**Info (please complete the following information):**
 - Server version: paper 1.16.5
 - Client version: 1.16.5
 - Plugin version: 2.1.41

**Comment by LoneDev6** [comment]
Please don't erase the issue template................

Provide all the asked info.
I edited your message, edit it yourself and include the missing data

**Comment by JustJP2K** [comment]
updated

**Comment by LoneDev6** [comment]
Did you regenerate the pack using /iazip?
Did you read the tutorial about hosting the pack?

Does this happens only in creative mode?

**Comment by JustJP2K** [comment]
i did regenerate the pack multiple times. and i have read the tutorials about hosting. no this is a survival world. happens to both naturally generated and artificially grown mushrooms

**Comment by JustJP2K** [comment]
I also just updated to the latest version. Same issue

**Comment by LoneDev6** [comment]
I mean, does this happens even if you place/remove blocks in survival?
In the video you're in creative (which is known to have "desync" problems in general which I cannot fix easily)

**Comment by JustJP2K** [comment]
Yes also breaking the blocks in survival. They leave behind ghost blocks. The block breaking sound of natural grown mushroom is the stone breaking sound which may suggest they are items adder blocks even though they should be normal mushrooms

**Comment by LoneDev6** [comment]
Any error in console?
Anyway seems that blockstates files are broken for some reason, did you edit them manually?

I'd open a support ticket including your full log (of when the issue happened) + a complete zip file of your WHOLE ItemsAdder configuration folder, not only the resourcepack.
https://support.plugin.ga/

Thanks
