### ISSUE TITLE
[BUG] Compatibility Issue With Craft Enhance

### ISSUE THREAD

**Issue by DabbingEevee** [PluginBugs/Issues-ItemsAdder#709]
**Describe the bug**
Craft Enhance is a plugin that can allow custom recipe creation. When creating a recipe with a custom head in the output, itemsadder somehow "blocks" the recipe. i was unable to find any errors in the logs

**To Reproduce**
1. Create a recipe in crafttweaker with a custom head.
2. install itemsadder
3. attempt the craft.

**Expected behavior**
the custom head crafts

**Screenshots**
<img width="242" alt="Screen Shot 2021-02-23 at 12 54 29 PM" src="https://user-images.githubusercontent.com/57885577/108906887-4706a100-75d6-11eb-9f81-4d990adec59b.png">
<img width="263" alt="Screen Shot 2021-02-23 at 12 55 49 PM" src="https://user-images.githubusercontent.com/57885577/108907045-761d1280-75d6-11eb-8a39-22680f8df87f.png">

**Info (please complete the following information):**
 - paper 1.16.5 
 - Client version: Minecraft java 1.16.5
 - Plugin version: 2.1.27

**Additional context**
n/a

**Comment by DabbingEevee** [comment]
i investigated a bit more, and infact the issue is with any slimefun item, and normal heads work fine

**Comment by LoneDev6** [comment]
I think it's related to slimefun so I cannot fix it on my end, I'm sorry.
If you have any other idea on how to fix it please let me know and I'll reopen the ticket
