### ISSUE TITLE
[BUG] semi di grano = peperoncino

### ISSUE THREAD

**Issue by Fargus5** [PluginBugs/Issues-ItemsAdder#710]
Buongiorno Matteo, come stai?

Mi permetto di segnalarti un ticket aperto da un utente nel mio server:

                                                              
```
A new ticket with the id #15 was just opened!

Ticket Info:
Category: Bug
Author: Takyru
Message: i semi di grano continuano a produrmi peperoncini rossi invece di grano... e li ho piantati tipo un po di minuti fa
```
Per caso sai se c'è qualcosa che non va con i semini di grano?

**Comment by LoneDev6** [comment]
Ciao, è sicuramente riconducibile a questo bug che sto attualmente fixando e sarà disponibile nel canale BETA (che creerò).
https://github.com/PluginBugs/Issues-ItemsAdder/issues/597
https://github.com/PluginBugs/Issues-ItemsAdder/issues/683
