### ISSUE TITLE
[Suggestion] Quality armory support

### ISSUE THREAD

**Issue by BookWyrm114** [PluginBugs/Issues-ItemsAdder#711]
**Is your feature request related to a problem? Please describe.**
It is partially related to a problem, quality armory adds great guns to the game, but some of the items from itemsadder and itemsadder addons have conflicting textures, for example, I'd be holding a glowing staff that fires bullets and takes spawn eggs or something for ammo, the quailty armory mod works, it just looks really weird.

**Describe the solution you'd like**
support for quailty armory would be nice, so the textures would work correctly, and we would have better guns

**Describe alternatives you've considered**
I've just removed quality armory for now, as itemsadder adds more stuff, and does have some guns of it's own

**Comment by LoneDev6** [comment]
Hello!
Actually I got this request in the past, read more here: https://github.com/PluginBugs/Issues-ItemsAdder/issues/310

Basically you can add it, you have to create a namespace for quality armory on itemsadder and create each weapon also there in itemsadder.
This will basically help you merging the resourcepack.

Or you can set this property in config.yml and merge the resourcepacks manually without having to create the weapons also in itemsadder.
Property: `overwrite-vanilla-models__DISABLE_AT_YOUR_OWN_RISK: false`.

I'd be happy to add support but I currently have no time, would be nice if someone takes the time to create an addon like I did for slimefun: https://www.spigotmc.org/resources/addon-slimefun4-textures-for-itemsadder.83877/


let me know if something's not clear, have a nice day
