### ISSUE TITLE
[Suggestion] 💡 Set Item Icon for place-able objects

### ISSUE THREAD

**Issue by ArgonGaming** [PluginBugs/Issues-ItemsAdder#712]
**Is your feature request related to a problem? Please describe.**
Currently you cannot set a "item icon" to placeable objects such as furniture behaviors, or hats.

Vanilla behavior tends to have a mix of the model and it's corresponding icon. It can be a very good feature to utilize for players if the model is too big or small to display in the hotbar or whilst holding.

**Describe the solution you'd like**
It would be nice to set another itemsadder object enacting as an "icon" or the item you hold, and when used, it will place the other itemsadder object corresponding to the MODEL. Perhaps this can go under "behaviors"

Example:
```
pebble:
  behaviors:
      furniture: true
      icon: itemsadder:pebbleicon
```

**Additional context**
![image](https://user-images.githubusercontent.com/30943826/109243184-7e2dab80-77aa-11eb-99f1-b06ee95b935c.png)

**Comment by LoneDev6** [comment]
Same as: https://github.com/PluginBugs/Issues-ItemsAdder/issues/881
