### ISSUE TITLE
[BUG] Near furnitures trade_machine opens other near furniture trade_machine GUI

### ISSUE THREAD

**Issue by MrJorman** [PluginBugs/Issues-ItemsAdder#713]
https://youtu.be/I-pHGKgf1Fs 

OMG WTF MAN?? it's OVER BUGGG Interfaces GUI Furniture (furniture_trade_machine:)

Each mechanism has its own GUI and its own items, when I put them next to each other, they disappear and each has the same GUI

**Comment by LoneDev6** [comment]
As always avoid erasing the issues template.
Provide all the info requested..
Also avoid this kind of reports "OMG WTF MAN BRO WTF", it doesn't help me understanding what's happening, keep the reports clean.

Seems machinery are too near on each other so it takes the most near one.
I will try to find a solution for this, thanks for the report
