### ISSUE TITLE
[BUG] no working events wear/unwear

### ISSUE THREAD

**Issue by MrJorman** [PluginBugs/Issues-ItemsAdder#714]
no working events wear/unwear from armors.. fix pls

**Comment by LoneDev6** [comment]
As always please avoid completely erasing issues templates...
provide all the info asked.

I tested the mysterious_boots and hood and works fine in SURVIVAL mode..

This server is running Paper version git-Paper-497 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

ItemsAdder version 2.1.42

**Comment by SirCraftypants** [comment]
> 
> 
> no working events wear/unwear from armors.. fix pls

It won't work in Creative Mode, it never has. So removing an item with an effect in Creative will not remove the effect. However, the Player can put the item back on, jump into Survival Mode and then remove it and it will then remove the effect. I personally don't allow my players to go into Creative Mode with Custom Items, I use a per world inventory plugin so my Creaitve World Inventories are separate from my Survival World Inventories. If this is what you're referring to then this is your solution.
