### ISSUE TITLE
[BUG] ItemsAdder WorldEdit addon

### ISSUE THREAD

**Issue by MinecollYT** [PluginBugs/Issues-ItemsAdder#716]
**Describe the bug**

**To Reproduce**
1. //set 0
2. /undo
3. error message

**Expected behavior**
Undo the //set 0

**Screenshots**
-

**Info (please complete the following information):**
 - Server version: paper 1.16.5
 - Client version: fabric 1.16.4
 - Plugin version: 2.1.42
 - Addon version: 1.0.3

**Additional context**
Error Log: https://pastebin.com/ujFks88U

**Comment by LoneDev6** [comment]
worldedit version?

use /version worldedit

**Comment by MinecollYT** [comment]
WorldEdit Version: 7.2.3+5680-135941e

And btw. it would be nice if there was asyncworldedit or fastasynworldedit support.

**Comment by LoneDev6** [comment]
Currently it's very difficult to integrate this plugin with worldedit and similar plugin as their API doesn't provide an easy way to "add blocks".
Currently my addon is an hack basically, so it may not work with every worldedit version or plugin.
I'll check and try to fix the issue but it's very difficult

**Comment by LoneDev6** [comment]
anyway in this case seems that the issued command didn't contain a itemsadder block

can i know which command did you write down?
thanks

**Comment by MinecollYT** [comment]
I accidentally removed something from a building that contains a block from itemsadder and because it was a mistake I tried to use /undo but yeah… that was the cause of the error message

**Comment by MinecollYT** [comment]
But I can't reconstruct the error at the moment.

**Comment by LoneDev6** [comment]
okay thanks
