### ISSUE TITLE
Coals nuggets usable in beacons [BUG] 

### ISSUE THREAD

**Issue by Agaloth** [PluginBugs/Issues-ItemsAdder#719]
**Describe the bug**
When upgrading your beacon power, you can choose between diamond, gold, iron ingots etc...
But you can also use coal nugget and fossils for it.

**To Reproduce**
1. Make the pyramid.
2. Place the Beacon
3. You should be able to upgrade it with fossils and coal nuggets.

**Expected behavior**
The beacon should be upgraded with coal nuggets/fossils or other similar items.

**Info (please complete the following information):**
 - Server version: Purplane version git-Purplane-"b5b6595" (MC: 1.16.5) - It also happens on paper build #507
 - Client version: Lunar 1.16.5
 - Plugin version: ItemsAdder version 2.1.42

**Comment by LoneDev6** [comment]
Thanks, this will be fixed in the next update
