### ISSUE TITLE
[BUG] Custom blocks are not protected

### ISSUE THREAD

**Issue by 100petr** [PluginBugs/Issues-ItemsAdder#720]
**Describe the bug**
EssentialsProtect does not protect custom blocks from the ItemsAdder  from explode & destroy

**To Reproduce**
1. Set tnt-explosion to true (Essentials config)
2. Place a block from the ItemsAdder
3. Place and ignite the TNT
4. Vanilla blocks are not destroyed, but ItemsAdder yes

**Expected behavior**
ItemsAdder blocks will not be destroyed

**Screenshots**
![image](https://user-images.githubusercontent.com/29830635/109667442-6bcbbd00-7b70-11eb-82be-ad9cb00b2461.png)
![image](https://user-images.githubusercontent.com/29830635/109667465-71c19e00-7b70-11eb-9346-2ec7e12d8e0b.png)

**Info (please complete the following information):**
 - Server version: 1.16.5-R0.1-SNAPSHOT git-Paper-507 (MC: 1.16.5)
 - Plugin version: 2.1.42

**Additional context**
https://github.com/EssentialsX/Essentials/issues/4027
It doesn't matter if it's REAL or TILE

**Comment by LoneDev6** [comment]
Should be fixed in the next update I will publish. Please comment here again after the update if it still doesn't work
