### ISSUE TITLE
I want to disable the plugin resource pack loader.

### ISSUE THREAD

**Issue by RandomTejpek** [PluginBugs/Issues-ItemsAdder#722]
Hi, please add an option that DISABLES the plugin's resource pack loader. I'm using an alternative pack loader and I want to use it.
It's annoying that it forces me to use the items adder resource pack loader. Add something like pack-enabled false or idk.

What I did:
I have data packs, that need custom textures. I merged the data pack textures, and the items adder textures. But it just FORCES ME to use the items adder resource loader. Also, please remove that stupid thing that disables the data pack on server startup because it says it can't load resource packs from website.
The plugin I use for texture packs I bought is really simple etc and I'm sticking with it.

I wanna use my own things, and not the plugin ones. So please add the pack-enabled thing in the config.
It would help me a lot, and I believe that other advanced server owners too.
Thanks.

(plugin version is leates)

**Comment by 100petr** [comment]
Did you try to apply_on_join to false? Or turn off self-host and external-host?

**Comment by RandomTejpek** [comment]
> Did you try to apply_on_join to false? Or turn off self-host and external-host?

Hej, skúšal ale keď chcem použiť ten Texture loader čo mám, nedovolí mi to. Musia pridať to, čo som napísal.

**Comment by LoneDev6** [comment]
apply_on_join will stop users from getting the resourcepack applied and then you can do whatever you want to apply the pack on your own, in this case using another plugin.

Resourcepack link is available using /iainfo command, copy it and paste it in your other plugin
