### ISSUE TITLE
[Suggestion] Worlds property for the fishing loot (and other loots)

### ISSUE THREAD

**Issue by patatoplugin** [PluginBugs/Issues-ItemsAdder#727]
I want players can fishing custom fishes in special map 
Just like some game DLC,you can get special item in special map
For example, in oringial map players can just fishing vanilla Fish, but in my newworld,they can fishing Shark

Now the plugin have worlds_populators.yml to set BLOCK,can it have fish_populators(even Biome)?

**Comment by patatoplugin** [comment]
I hope this suggestion be true：Fishing in special Map.

**Comment by LoneDev6** [comment]
ItemsAdder already offers biomes rule for each loot.
Do I have to also add a world rule? Is that what you need?
