### ISSUE TITLE
Huge lag issues after 55+ online [BUG] 

### ISSUE THREAD

**Issue by Agaloth** [PluginBugs/Issues-ItemsAdder#728]
**Describe the bug**
Itemsadder seems to take a lot of ticks as seen on the spark profilers

**To Reproduce**
1. Check the spark profiler: https://spark.lucko.me/#WgnkV1Z1Jo

**Screenshots**
![G54VbCQ](https://user-images.githubusercontent.com/33335971/110146666-1d6e2680-7ddb-11eb-84da-905856640f6d.png)

**Info (please complete the following information):**
 - Server version: Purplane version git-Purplane-"b5b6595" (MC: 1.16.5)
 - Client version: Lunar 1.16.5
 - Plugin version: ItemsAdder version 2.1.42

**Comment by LoneDev6** [comment]
This should be fixed in the next update, I now changed the emoji replacing logic to be async and should avoid TPS drops since it won't be on the main thread.
