### ISSUE TITLE
[BUG] Could not pass event BlockPhysicsEvent to ItemsAdder v2.1.42

### ISSUE THREAD

**Issue by Fargus5** [PluginBugs/Issues-ItemsAdder#729]
**Describe the bug**
Stavo usando CoreProtect per fare un rollback e itemsadder è crashato

**To Reproduce**

Il problema è apparso a seguito di un rollback

**Logs**
https://log.mtxserv.com/iLbCyjC#L4014

**Comment by LoneDev6** [comment]
Itemsadder non mi sembra "crashato" noto solo degli errori.
Penso l'errore sia mostrato perché non trova più alcuni blocchi rimossi da un altro plugin, in questo caso CoreProtect.

Puoi tranquillamente ignorare il problema se gli unici errori sono quei due e non uno spam continuo, semplicemente ti segnala che quei blocchi non esistono più.

Se però noti problemi che interferiscono col gameplay scrivi nuovamente su questo report
