### ISSUE TITLE
[Bug] no silk touch mushroom blocks

### ISSUE THREAD

**Issue by tdsacco0122** [PluginBugs/Issues-ItemsAdder#730]
**Describe the bug**
When you mine the three types of mushroom blocks with silk touch you don't receive anything

**To Reproduce**
1. place some red mushroom, brown mushroom, or mushroom stem
2. get a silk touch tool 
3. mine the 3 blocks

**Expected behavior**
You expect to get the silk touched version of the mushroom blocks

**Info (please complete the following information):**
 - Server version: purpur 992 1.16.5
 - Client version: vanilla 1.16.5
 - Plugin version: 2.1.41

**Comment by LoneDev6** [comment]
Thanks, this will be fixed in the next update
