### ISSUE TITLE
[Suggestion] /iatexture

### ISSUE THREAD

**Issue by RickyLaChow** [PluginBugs/Issues-ItemsAdder#735]
**Is your feature request related to a problem? Please describe.**
La feature sarebbe aggiungere la possibilità di caricare la resourcepack a un giocatore o permettere ai giocatori di fare /iatexture senza aggiungere la possibilità di fare /iatexture all

**Comment by LoneDev6** [comment]
è un'ottima idea, lo implemento oggi prima dell'update 2.2 (che aggiungerà un sacco di cose)

**Comment by LoneDev6** [comment]
Nel dubbio te lo ricordo: /iatexture lo si deve usare solo in caso di problemi perché forza lo scaricamento del pack e non solo la sua installazione, quindi gli utenti potrebbero stufarsi a scaricare ogni volta 10-20MB
