### ISSUE TITLE
MythicMobs not loading model on ItemsAdder

### ISSUE THREAD

**Issue by DerVillion** [PluginBugs/Issues-ItemsAdder#739]
Following this tutorial:
https://itemsadder.plugin.ga/plugin-usage/adding-content/advanced/mobs/using-mythicmobs

With the following files that I will send.

I just can't get the mob to spawn with the texture applied to it.

I replaced like it said in the tutorial. making it call on the mob. when I do /mm m spawn Soul
it's still the regular mob and not the textured one that I configured it to be

**Expected behavior**
/mm m spawn Soul would give me a textured mob

**Info (please complete the following information):**
 - Server version: spigot 1.16.5 (latest)
 - Client version: vanilla 1.16.5
 - Plugin version: latest - beta version 5

**Additional context**
Discord if you need me (I also figured out ModelEngine and ItemsAdder) - soooo tutorial soon?
- DerVillion

**Comment by DerVillion** [comment]
https://drive.google.com/drive/folders/1sUufRGimiV-VLvUAFCVPDUrrTKQSYdod?usp=sharing

**Comment by TheMrLhuixx** [comment]
same problem

**Comment by LoneDev6** [comment]
https://www.spigotmc.org/threads/%E2%9C%85must-have%E2%9C%85-itemsadder%E2%9C%A8textures-3d-models-emojis-ores-blocks-wings-tails-hats-more.412279/page-26#post-4204265
