### ISSUE TITLE
[Suggestion] minecraft:tripwire -> type block REAL_STRING

### ISSUE THREAD

**Issue by Venterok** [PluginBugs/Issues-ItemsAdder#741]
- minecraft:tripwire has a lot of blockstates thanks to which it would be possible to make flat custom blocks. 
Through blockbench or other programs, you can change the thread model so that in one of its states you get a custom block
This function would allow you to create your own plants/decor elements, etc.
Examples and other things I posted on the image.

 

- sorry i didn't use the example for the suggestion

![image](https://user-images.githubusercontent.com/67825103/111023184-a511f180-83e8-11eb-87bb-a50f68577fc1.png)

**Comment by MrJorman** [comment]
++++

**Comment by SNokerYT** [comment]
+

**Comment by ArgonGaming** [comment]
Huge Vouch

**Comment by LoneDev6** [comment]
Cool idea, but aren't these used by players? Won't they complain if I remove the functionality?

**Comment by MinecollYT** [comment]
> Cool idea, but aren't these used by players? Won't they complain if I remove the functionality?

Would be useful if it could be turned off in the config, so every server admin can decide on their own.

**Comment by Venterok** [comment]
> Cool idea, but aren't these used by players? Won't they complain if I remove the functionality?

You can make the setting through the config of this all

**Comment by SNokerYT** [comment]
This is a item Frame ، it's really hard to do it right now,  but LoneDev6 will make it in Feature

**Comment by ArgonGaming** [comment]
> This is a item Frame ، it's really hard to do it right now, but LoneDev6 will make it in Feature

It's string, not an item frame

**Comment by SNokerYT** [comment]
Nope it's item Frame 👼but they changed to look's more realistic
![image](https://user-images.githubusercontent.com/68678154/111861092-55857580-8954-11eb-842e-8f5bd722c25d.png)

**Comment by SNokerYT** [comment]
Every Model in origin realms is a itemframe = 0 tick

**Comment by ArgonGaming** [comment]
> Every Model in origin realms is a itemframe = 0 tick

It's a string. They also use item frame models as well. In the naturally generated worlds and place-able versions, it's a string.
![image](https://user-images.githubusercontent.com/30943826/111883176-16751580-8990-11eb-8ebd-f8f9998f86e8.png)

**Comment by TeiBri** [comment]
Now he read the whole conversation suggestion 741, because my suggestion was actually the same. In truth, I have no idea now that LoneDev plans to add "REAL_STRING". Does it plan or not? Is it decided or not?

**Comment by TeiBri** [comment]
> I plan to add this, but as I announced on the Discord server:
> 
> > ⚠️ PLEASE DON'T OPEN SUPPORT TICKETS FOR ANY LITTLE ISSUE OR LITTLE QUESTION.⚠️
> > We have more than 30 tickets per day and this is getting very time consuming.
> > I also have to actually code updates, I can't answer everyone everyday.
> > Thanks
> 
> So I have no idea of when I will find the time since right now support tickets are still a lot even if I posted this announce..

pity :(

**Comment by Venterok** [comment]
Похуй
