### ISSUE TITLE
[BUG] Spawners can be broken with silk touch because of some IA blocks being "TILE"s

### ISSUE THREAD

**Issue by imparium-de** [PluginBugs/Issues-ItemsAdder#742]
**Describe the bug**
When breaking spawners with silk touch, they get dropped. There is no other plugin interfering. Also, after we did some more testing. When breaking a spawner it happened once that an IA block got dropped. 

**To Reproduce**
1. Enchant a pickaxe with silk touch
2. Break a spawner
3. See that it got dropped

**Expected behavior**
The spawner shouldn't get dropped

**Screenshots**
https://s.imparium.de/niho0/PAhucoCu86.mp4

**Info (please complete the following information):**
 - Server version: Paper 1.16.5
 - Client version: Forge 1.16.4
 - Plugin version: 2.2.1

**Comment by Agaloth** [comment]
I can confirm, it dupes spawners.
