### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Gusya-g** [PluginBugs/Issues-ItemsAdder#743]
Add a command **/iatexture [player]** to load a resourcepack for a specific player.

**Comment by JustJP2K** [comment]
thats already implemented

**Comment by Gusya-g** [comment]
No. It isn't

вс, 14 мар. 2021 г. в 18:29, JP2K ***@***.***>:

**Comment by LoneDev6** [comment]
This will be added in the next update

**Comment by Gusya-g** [comment]
<3
