### ISSUE TITLE
[BUG] fix the damage display in the anvil

### ISSUE THREAD

**Issue by MrJorman** [PluginBugs/Issues-ItemsAdder#748]
fix the damage display in the anvil, see my video, vanilla items show damage in the anvil + enchanted_book, and custom items no show damage in the anvil, fix pllss broo

video: https://youtu.be/jhNfP_SZyDw

**Comment by LoneDev6** [comment]
will be fixed, thanks.
as always please do not erase the issue template, write all the info requested
