### ISSUE TITLE
[BUG] Does not decrease the strength of vanilla pickaxe when I break it with custom-blocks or ore

### ISSUE THREAD

**Issue by MrJorman** [PluginBugs/Issues-ItemsAdder#749]
Does not decrease the strength of vanilla pickaxe when I break it with custom-blocks or ore, as well as with other types of custom tools, fix pls

**Comment by LoneDev6** [comment]
I don't understand

**Comment by LoneDev6** [comment]
Also please, I said that 10 times, do not erase the issue template. Write all the info requested.
Create a valid issue report.
