### ISSUE TITLE
REAL block IDs Problem with Ore

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#751]
**Describe the bug**
i have a problem that if i reached to 77/188 REAL block IDs,  ore blocks changed to another one | When it's 76 it's working fine
-  i Delete the storage Every time i adding a Real block
- it's also working fine with REAL_NOTEBLOCK - https://cdn.discordapp.com/attachments/814526811379073074/820751622757154816/g.gif
-i tried on another test server When you use more than 76 REAL Block | include ores the problem comes
- https://imgur.com/a/fAGhGsB
**To Reproduce**
| 1.'Download the | Blockus Reimagined - ItemsAdder addon | install it first | and replace 65 blocks From TILE to REAL'
| 2.'Change all the Ore Blocks to REAL'
| 3. 'Delete the | storage Folder | or Delete Blocks cache | I Deleted it | and Do /iareload | /iazip and theproblem will come'
**Info (please complete the following information):**
 - Server version: (example: paper 1.16.5)
 - Client version: (example: Minecraft Vanilla 1.16.5)
 - Plugin version: (example: **2.2.2)**
**Additional context**
i really Don't use the REAL block anymore after the REAL_BOTEBLOCK but I reported this bug , Because I was using itemadder before you add the Noteblock as real , and also this maybe will Lead you to another problem | also there so many problems with Note block i will make a bug report about it.

**Comment by LoneDev6** [comment]
> ore blocks changed to another one

I don't really understand this sentence, which blocks? already placed ones? inventory blocks?

Anyway, are you sure that if you use the command /iaget to get another copy of the block and place it it bugs? it may be that you have an old block in hand.

**Comment by SNokerYT** [comment]
i did /iaget but still same problem | https://imgur.com/a/OxggsRh
in conclusion the problem just if you reached over 77 real block ,include ores problem comes
When you will try to place any ores | the ores will change to another one like this gif

**Comment by LoneDev6** [comment]
Very strange. I will keep this issue report opened and see if I can fix the issue in future updates.
Anyway the REAL_NOTE blocks are much more stable and less laggy, in the future consider using them :D
(I'm fixing the little bugs you reported me, the ones about placement)

**Comment by SNokerYT** [comment]
Please Don't also Forget | the allow placing non-placeable materials for furniture ^^ 👯

**Comment by LoneDev6** [comment]
The only reason why furnitures do not support non-placeable materials is because they won't support semi-transparent colors in their textures: https://itemsadder.plugin.ga/faq/can-i-create-slabs-stairs/transparent-textures

But I will add this feature as requested.

**Comment by LoneDev6** [comment]
> 
> 
> Very strange. I will keep this issue report opened and see if I can fix the issue in future updates.
> Anyway the REAL_NOTE blocks are much more stable and less laggy, in the future consider using them :D
> (I'm fixing the little bugs you reported me, the ones about placement)

I can't manage to reproduce the issue, probably it's something to do with blocks ids cache as this doesn't work on a fresh new itemsadder installation
