### ISSUE TITLE
bug with REAL_NOTE | include painting and chair and torch and all the furniture ⚠

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#753]
bug with REAL_NOTE | include painting and chair and torch and furniture
- https://imgur.com/a/OYfDhNW

**Comment by LoneDev6** [comment]
As always please avoid deleting the issue template, I need to know server version and plugin version.
Anyway thanks for the report, I will try to fix the issue

**Comment by SNokerYT** [comment]
@LoneDev6 you still did not fix the furniture and painting I can't place it | https://imgur.com/a/1CICSee
Version | 2.2.3 |

**Comment by LoneDev6** [comment]
Thanks I will check also this
