### ISSUE TITLE
[Suggestion] add EcoEnchants plugin integration

### ISSUE THREAD

**Issue by MrJorman** [PluginBugs/Issues-ItemsAdder#756]
add EcoEnchants plugin integration, There are a lot of useful charms that I want to add to my custom items.

**Comment by MrJorman** [comment]
https://www.spigotmc.org/resources/%E2%9A%A1-1-15-1-16-5-ecoenchants-%E2%9C%A8-220-custom-enchantments-%E2%9C%85-essentials-cmi-support.79573/

**Comment by LoneDev6** [comment]
I contacted the developer

**Comment by LoneDev6** [comment]
note for myself:
```java
Enchantment.getByKey(NamespacedKey.minecraft(key name))
```
