### ISSUE TITLE
[Suggestion] Epic Backpacks Feature Request!

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-ItemsAdder#758]
Another feature request if i may.

Ability to set a special loot backpack with preset items, so they can be given out to players with their contents via command.

They can also be placed around hidden by admin for players to find, think it would be cool if we could set the loot backpacks up in their own yml files with set items using material, cmd/nbt it would be awesome.

**Comment by SirCraftypants** [comment]
I understand that i can just put the items in a backpack and just give it to the player but that would be tedious work with lots of players so being able to preset filled backpacks with it's own id and also be able to give via command would i think be amazing.

**Comment by The-Gust** [comment]
Post it in right github page, please.
https://github.com/PluginBugs/Issues-EpicBackpacks/issues
