### ISSUE TITLE
[BUG] Water breaks transparent blocks

### ISSUE THREAD

**Issue by JustJP2K** [PluginBugs/Issues-ItemsAdder#760]
Water can break any item sadder transparent blocks. 

Maybe add another option for blocks to be either breakable by water or not?

break-water: false

would be a neat addition

**Comment by LoneDev6** [comment]
Sorry it's not possible: https://itemsadder.plugin.ga/faq/blocks-minerals-issues/leaves-and-transparent-blocks-problems#real_transparent-blocks-are-dropped-when-water-flows-on-them

> I know this bug and I can't fix it without making your server an oven.
> 
> Details:
> As you already know Minecraft is not that great and most of the cool features require a lot of hacks to be implemented.
> One of these are custom blocks. To fix this water bug I'd have to listen to the water flowing event and check if every block around the water is a custom block. This event is called a looooooot of times in midsized server and I can't make the plugin lag everything.
