### ISSUE TITLE
[BUG] Huuuuge Problem with transparent blocks glitching out, becoming unbreakable with horrendous noise

### ISSUE THREAD

**Issue by JustJP2K** [PluginBugs/Issues-ItemsAdder#761]
The videos speak for themselves.
Latestest Version: 2.2.3
Server version: Paper 1.16.5 

https://www.dropbox.com/s/6zkhxnpsn8fvc3h/Minecraft_%201.16.5%20-%20Multiplayer%20%283rd-party%20Server%29%202021-03-17%2017-54-35.mp4?dl=0
https://www.dropbox.com/s/sa9ty2ve4qvc8ap/Minecraft_%201.16.5%20-%20Multiplayer%20%283rd-party%20Server%29%202021-03-17%2017-55-50.mp4?dl=0

**Comment by LoneDev6** [comment]
Will be fixed, thanks for the report
