### ISSUE TITLE
[BUG] The command iaremove don't remove items thats in off-hand slot.

### ISSUE THREAD

**Issue by Dkavila** [PluginBugs/Issues-ItemsAdder#763]
**Describe the bug**
The iaremove command don't remove the item if it is off-handed.

**To Reproduce**
1. Get any item from ItemsAdder
2. Put it in the off-hand
3. Execute /iaremove trying to remove that item

**Expected behavior**
 - The iaremove command needs to check all the slots to remove the item and remove it wherever it is ...

**Info (please complete the following information):**
 - Server version: paper 1.16.5-550
 - Plugin version: 2.2.2

**Additional context**
 - I have created 2 items named empty_waterskin and waterskin
   The empty is craftable
   And i used BUCKET as the base item
   When the fill_bucket event happen, the IA remove the empty_waterskin and give a waterskin that have 1 use
   If the player drinks, give the empty_waterskin again and the waterskin breaks
   Thats all ok
   but if the empty_waterskin is off-handed the iaremove dont remove...
   
**Additional context screenshot**
![unknown](https://user-images.githubusercontent.com/43159733/111526977-1e3d7b80-873e-11eb-9ddf-619e722e55df.png)

**Comment by LoneDev6** [comment]
Thanks I will fix the bug.
Anyway did you consider decrementing the quantity instead of removing 1 of the item using the /iaremove command?
`decrement_amount: 1`
