### ISSUE TITLE
[Suggestion] Silent feature in the iaremove command

### ISSUE THREAD

**Issue by Dkavila** [PluginBugs/Issues-ItemsAdder#764]
**Is your feature request related to a problem? Please describe.**
 - I really want the Silent feature to iaremove command. Why only in iagive??

**Describe the solution you'd like**
 - When execute the iaremove, dont show any message to the player.
 - As like happened here: Added silent attribute to give command as requested https://github.com/LoneDev6/ItemsAdder/issues/525: /iagive <player> <itemname> [amount] [silent]
 - /iaremove <player> <itemname> [amount] [silent]

**Describe alternatives you've considered**
 - A configuration option to turn off the remove and give action.

**Comment by LoneDev6** [comment]
will be added
