### ISSUE TITLE
Can't Place furniture With | Suvival Mode | 

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#765]
**Describe the bug**
When you try to place a furniture Changed to be a Barrier Block
1. Change the item material you want to be like | LEATHER_HORSE_ARMOR
2. Try to place it with gamemode Creative will Work Fine | with Game mode Survival will Changed to be a Barrier Block 
and any one on the server will Not be able to break it because he is player | Not | Op

Screenshots | https://imgur.com/a/QXtlehG

**Info (please complete the following information):**
 - Server version: (paper 1.16.5)
 - Client version: (Vanilla 1.16.5)
 - Plugin version: (Itemadder 2.2.4)

**Additional context**
With Gamemode **Creative** Can place | furniture 
with Gamemode **Survival** Can't place | furniture

**Comment by SNokerYT** [comment]
Also | it's Not working with all the furniture | not only about the LEATHER_HORSE_ARMOR material all the materials same Problem

**Comment by LoneDev6** [comment]
I'll make some tests on latest 1.16.5, strange..

**Comment by LoneDev6** [comment]
This happens when you have a stack of only 1 item in hand, I will fix this in the next update
