### ISSUE TITLE
[BUG] ScreenEffects Addon Error

### ISSUE THREAD

**Issue by asdf1155** [PluginBugs/Issues-ItemsAdder#767]
**Describe the bug**
Error when executing command

**To Reproduce**
/screeneffect fullscreen #000000 10 10 10 freeze all 1
: Error
/screeneffect fullscreen AQUA 10 10 10 freeze all 1
: Error
/screeneffect fullscreen AQUA 10 10 10 unfreeze nick 1
: Error

**Info (please complete the following information):**
 - Server version: paper 1.16.3
 - Client version: vanila 1.16.3
 - Plugin version: Itemsadder 2.2.5 / ScreenEffects 1.0

Error log : https://pastebin.com/2gPn2m8U

**Comment by LoneDev6** [comment]
I will add compatibility but I suggest you to update to 1.16.5 instead of 1.16.3

**Comment by LoneDev6** [comment]
fixed
