### ISSUE TITLE
[BUG] Trees very buggy when using REAL_NOTE

### ISSUE THREAD

**Issue by spiker5032** [PluginBugs/Issues-ItemsAdder#770]
**Describe the bug**
When using noteblocks as trees the blocks above are always affected by breaking.

**To Reproduce**
1. Make a tree using REAL_NOTE
2. Make a populator for it
3. Chop tree

**Screenshots**
https://gyazo.com/18d2e048763e463dc4ed36566b6c80d5

**Info (please complete the following information):**
 - Server version: Paper 1.16.5
 - Client version: Vanilla 1.16.5
 - Plugin version: 2.2.5

**Comment by LoneDev6** [comment]
Seems to be a clientside blockstate desync, I will try to mitigate that

**Comment by LoneDev6** [comment]
This seem to happen only in creative mode, I will send block update packet to client when in creative mode
