### ISSUE TITLE
[Suggestion] Custom explosion resistance

### ISSUE THREAD

**Issue by MinecollYT** [PluginBugs/Issues-ItemsAdder#772]
**Describe the solution you'd like**
Define a custom explosion resistance value for custom blocks

**Additional context**
https://imgur.com/clFTmxB

**Comment by LoneDev6** [comment]
what do you mean?

**Comment by Sheikins** [comment]
He would like to define the resistance of custom blocks against explosion (TNT). He shows on his screen that the trees do not break due to the fact that this sound of the barrier / spawner

**Comment by LoneDev6** [comment]
you want to set some blocks to be indestructible basically?

**Comment by Sheikins** [comment]
Not on the contrary that it is destructible. The barriers being unbreakable, the TNTs cannot break them. The blocks in barrier or spawner its basic unbreakable by the tnt

**Comment by LoneDev6** [comment]
I will add a new property for blocks: `no_explosion: true`, this will disable explosions.

I also will implement a new calculation in the code to take `hardness` into account when making blocks explode.
Basically like vanilla Minecraft does, so for example a custom block with `hardness: 6` and an explosion of radius 4 (TNT) won't break the custom block.
