### ISSUE TITLE
[Suggestion] Create a behavior called fuel that allows you to define the burning time of an item

### ISSUE THREAD

**Issue by Dkavila** [PluginBugs/Issues-ItemsAdder#778]
**Is your feature request related to a problem? Please describe.**
  -I want to create new types of fuel items, like new coals with a longer burning time.

**Describe the solution you'd like**
 - Add a behavior that sets the burning time of an item when put it on the furnace.

**Additional context**
 - I created some ores that take a long time to burn. So I decided to create new fuels that give the furnace more burning time. Just like a lava bucket burns 20,000 ticks and coal burns 1600 ticks, I thought of creating fuels that burn a specific amount of time, but I haven't found any way to do that.
 
 **Additional context screenshots**
![image](https://user-images.githubusercontent.com/43159733/111930519-e7e26200-8a97-11eb-8847-276d3a0fe021.png)

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/97

> 
> ### Add configuration option to make item a fuel-source
> 
> I suggested this on the Discord already, but it would be nice to have an option to set a custom item as a fuel for furnaces.
> That way could f.e. the Coal nugget be used as a separate fuel for the furnace that can smelt 1/9 of what coal can smelt.
> 
> So the option should perhaps have the following options:
> 
>     * How long it lasts (In ticks or seconds?)
> 
>     * Restrict it to specific furnaces maybe?
> 
>     * If it would return an item (i.e. similar to Lava bucket which gives back the bucket)

**Comment by LoneDev6** [comment]
Will be added in the next update

```yml
    behaviours:
      fuel: 
        burn_ticks: 4
        machines:
          - BLAST_FURANCE
 ```
