### ISSUE TITLE
[BUG] hat behaviour on tools

### ISSUE THREAD

**Issue by Ronglito** [PluginBugs/Issues-ItemsAdder#779]
**Describe the bug**
hat behavior on tools doesn't work properly the only way to wear is to right-click or shift-click the item but when u drag and drop it doesn't work.

**To Reproduce**
1. make a custom helmet with a pickaxe as the source tool
2. add hat behavior to it
3. try to drag and drop and helmet on the player

**Expected behavior**
the player would wear the pickaxe as if it was a hat

**Info (please complete the following information):**
 - Server version: paper 1.16.5
 - Plugin version: Itemsadder 2.2.6

**Comment by LoneDev6** [comment]
will be fixed in next update, thanks!
