### ISSUE TITLE
[BUG] Menu (/ia) and hud textures not loading

### ISSUE THREAD

**Issue by sanderdatema** [PluginBugs/Issues-ItemsAdder#781]
**Description**
When using `/ia` only a normal menu is shown. Textures for things like bows are missing. However, chairs do work fine. The hud is also missing its textures.

**To Reproduce**
1. Setup new minecraft server, no other plugins
2. Install ItemsAdder, either using local hosting if RP or remote
3. Login to minecraft and confirm RP is being downloaded
4. See missing textures when using `/ia`

**Expected behavior**
The menu (and some items like bows and the hud) should use the correct textures.

**Screenshots**
Note: the screenshot is of my server with other plugins and ItemsAdder add-ons, but I did test with a clean server. I just forgot to create a screenshot then.
https://bit.ly/3chc7oL

**Info (please complete the following information):**
 - Server version: Purpur version git-Purpur-1025 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
 - Client version: Vanilla 1.16.5
 - Plugin version: 2.2.6

**Comment by LoneDev6** [comment]
Surely related to this: https://itemsadder.plugin.ga/faq/huds-emojis-guis-font/i-cant-see-emoji-guis-huds

**Comment by sanderdatema** [comment]
I missed the connection when going through the docs, but you're right. Thanks!
