### ISSUE TITLE
[BUG] ChatControlRed channels emoji broken

### ISSUE THREAD

**Issue by Tylwen** [PluginBugs/Issues-ItemsAdder#782]
Hello,
Emojis do not work with ChatControlRed using plugin channels. But it works when I turn them off and use basic chat.

I am using ItemsAdder 2.2.5 and ChatControlRed 10.3.1.
I am under PaperSpigot 1.16.5 - 565.

I have had this problem for several weeks.

I have already contacted the developer of ChatControlRed and told me to direct me to you.
The link to the request is attached:
https://github.com/kangarko/ChatControl-Red/issues/830

Tylwen

**Comment by LoneDev6** [comment]
Hello, can I see your config.yml of ItemsAdder?

**Comment by Tylwen** [comment]
`metrics: true
disable-plugin-loading-messages_DONT_ASK_ME_FOR_SUPPORT_IF_YOU_SET_TRUE__THANKS: false
resource-pack:
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  title:
    enabled: true
  self-host:
    enabled: false
    server-ip: 127.0.0.1
    pack-port: 8163
  external-host:
    enabled: true
    url: https://www.dropbox.com/s/7qvusapranu7p0q/pack.zip?dl=0
  custom-font:
    enabled: false
    name: ipaexg.ttf
    shift: '[0,0]'
    size: 11.0
    oversample: 2.0
  thin-font:
    enabled: false
  zip:
    protect-file-from-unzip__DISABLE_IF_ANY_PROBLEM: true
    overwrite-vanilla-models__DISABLE_AT_YOUR_OWN_RISK: true
    overwrite-vanilla-lang-json__DISABLE_AT_YOUR_OWN_RISK: true
    fix_transparent_noteblocks__disable-for-more-performance: false
    ignore-files-ext:
    - db
    - yml
    - xcf
    - html
config_files:
  lang: fr
  dictionaries-lang: fr
  extract-default-items: false
  extract-default-resources: false
  minify-json: true
blocks:
  light-api: true
  fix-glitched-blocks:
    enabled: true
    only-new-chunks: false
    fix-real-blocks-drops-chorus-water-bug__disable-for-more-performance: false
    seach-also-in-these-biomes:
      enabled: true
      biomes:
      - DARK_FOREST
      - DARK_FOREST_HILLS
      - MUSHROOM_FIELDS
      - MUSHROOM_FIELDS_SHORE
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
  campfire:
    unlit-on-place: true
    allow-any-item: true
  disable-REAL-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
  disable-REAL_TRANSPARENT-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
  disable-REAL_NOTE-behaviour__DISABLE_AT_YOUR_OWN_RISK: false
  disable-CUSTOM_FIRE-behaviour: false
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: false
  hide-custom-durability-lore: false
liquids:
  enabled: true
huds:
  enabled: true
font_images:
  chat:
    enabled: true
    replace-only-packets: true
    doublecheck-permission__disable-for-more-performance: false
    replace-in-customitems-name-and-lore: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
  inventory-title:
    enabled: true
  tab-header-footer:
    enabled: true
  vault-prefix-suffix:
    enabled: true
    update-every-ticks: 1200
  scoreboard-teams:
    enabled: true
  player-display-name:
    enabled: true
    update-every-ticks: 1200
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-items-loading-disabled: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
    log-loots-loading-disabled: false
  recipes:
    log-recipes-loading: false
    log-recipes-loading-disabled: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: false
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-generation: false
  trees-populators:
    log-loading: false
    log-loading-disabled: false
    log-loading-no-populators: false
    log-generation: false
  player-stats:
    log-save: false
  performance:
    loading-ms: true
  huds:
    log-triggers: false
  other:
    log-dictionaries-loading: false
    log-liquids-loading: false
    log-minecraft_lang_overwrite-loading: false
  categories:
    log-total-loaded: true
    log-single-loaded: false
    log-single-loaded-overwrite: false
    log-single-skip: false
`

**Comment by Tylwen** [comment]
https://pastebin.com/nn1w3Uw8
