### ISSUE TITLE
[Suggestion] Hardness custom block per tool

### ISSUE THREAD

**Issue by Venterok** [PluginBugs/Issues-ItemsAdder#793]
### Suggestion
**I believe that the block needs a parameter that allows you to configure "hardness" for a specific tool.
Digging the ore with your hand at the same speed as with a diamond pickaxe is not very good**

### What it looks like now: 
**GIF GYAZO**  https://gyazo.com/9c66f86941b7d90d9c320a8fdda0e67e?token=a1626aca0bc7a0928451c54abb99ad61

**Comment by LoneDev6** [comment]
post the block configuration that allows you to dig with hand with the same speed as diamond pickaxe, thanks.

right now itemsadder follows the same vanilla behaviour to calculate hardness of the tool. Basically you have to set "blacklist" or "whitelist" items to dig the block.
Check my example blocks in itemsadder namespace, you will see that for example ruby_ore can be mined at fullspeed only with pickaxe, and it takes longer if you try to mine using another tool.
