### ISSUE TITLE
[BUG] Different block breaking speed for a single tool

### ISSUE THREAD

**Issue by Venterok** [PluginBugs/Issues-ItemsAdder#794]
**Describe the bug**
Sometimes the block breaks faster, sometimes the opposite is slower.

**To Reproduce**
Look at the video (?), I do not know how to describe it
But, probably, you need to alternate the breaking of the block with the usual minecraft block and the speed will change

• gif  with bug: https://imgur.com/a/P0B5SKt

**Expected behavior**
The block must break correctly

**Info (please complete the following information):**
 - Server version: PurPur 1.16.5
 - Client version: Optifine 1.16.5
 - Plugin version: 2.2.7

**Additional context**
block config & During recording and testing, the TPS was 20
![image](https://user-images.githubusercontent.com/67825103/112859281-57210d00-90bb-11eb-8692-42f17b6a5b50.png)

**Comment by LoneDev6** [comment]
I really can't  manage to reproduce this behaviour, it's very strange.
Only thing that I can imagine is that a plugin is removing slow digging effect somehow, this prevents my custom hardness to work in some cases.
I will try to fix this adding the slow digging effect again each time the user hits the block, I hope it won't cause any lag.
