### ISSUE TITLE
Vehicle sit position feature

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-ItemsAdder#795]
As suggested I hearby submit

To quote yours truly moowaa "Hi Lone, hope all is well, quick question, is there a way to get the player to only sit forward in vehicles and not rotate left to right when turning".

Also  while we are here, is there a way to better position the sitting, instead of setting the model itself to the player sit position?

**Comment by LoneDev6** [comment]
Sadly no there is no way, Minecraft doesn't allow passengers to be set in different positions beside the head location of the armorstand

**Comment by LoneDev6** [comment]
it will be fixed in the next update, it's a bug actually
