### ISSUE TITLE
[BUG] Drinking (error)

### ISSUE THREAD

**Issue by Erestyy** [PluginBugs/Issues-ItemsAdder#798]
Hey, 

I disabled:
**extract-default-items: false
extract-default-resources: false**
in the config, and only deleted Itemsadder, magiccraft & Twitteremoji's.
I deopped myself to test something, and i was getting this error in my console:

https://paste.plugily.xyz/?ae3cc66d20115fda#F5WFA5JxzzWeyJw5uoPMMSuxLEoD4eqfbxcEZm9D7oHC

I deopped myself and was trying to drink. I was looking into my console and was getting this error. (i disabled drinking in the yml file) This message is from a log:

https://paste.plugily.xyz/?57a98eda4c248353#GRQZ3LSCH1BKh9BK6U3RYpYRwvgqTxaW59fZrW3p9ekZ

 - Server version: **Purpur 1.16.5**
 - Client version: **Optifine 1.16.5**
 - Plugin version: **Latest, 2.2.7**

**Comment by LoneDev6** [comment]
Thanks, this will be fixed asap
