### ISSUE TITLE
[BUG] REAL_TRANSPARENT get updated

### ISSUE THREAD

**Issue by xalixilax** [PluginBugs/Issues-ItemsAdder#799]
**Describe the bug**
- First Bug
Having a REAL_TRANSPARENT block beside or over a cauldron and putting/removing water in it update the chorus and make it drop a chorus fruit.

- Second bug
Having a block at water level with a REAL_TRANSPARENT block over it, when you break the block, the water will fill the hole updating the REAL_TRANSPARENT dropping the custom item

- Third Bug
Sending a pulse to an adjascent REAL_TRANSPARENT block make it create chorus fruit

- Fourth Bug
Yo can place chorus flower over REAL_TRANSPARENT and let them grow. They also get a texture with all attribute set to true

**To Reproduce**
- First bug
Place a cauldron
place REAL_TRANSPARENT around it
update the cauldron
All REAL_TRANSPARENT drop a chorus fruit

- Second Bug
Place a block
place water source on all 4 sides
Place a REAL_TRANSPARENT block over the block
Remove the block
This will create an air block then a water source block
The REAL_TRANSPARENT will drop the custom block

- Third Bug
Place 2 observer facing each other so they pulse
Put a block in front of the output so it receive a redstone signal
add REAL_TRANSPARENT around that block
Enjoy infinite chorus fruit

- Forth Bug
Place down a REAL_TRANSPARENT
Place a chorus flower ever it
Wait
Collect

**Expected behavior**
In both instance, REAL_TRANSPARENT should stay in place. 
In the third one, the chorus fruit should not be created.
In the fourth one, you should not be able to plant and they should not grow

**Screenshots**
![2021-03-30_18 55 05](https://user-images.githubusercontent.com/2474569/113067094-b8afad00-9189-11eb-9eaf-b59d5fbcdea9.png)
(In this case, the block to remove is the red concrete)
![2021-03-30_19 06 20](https://user-images.githubusercontent.com/2474569/113068027-74bda780-918b-11eb-8dd4-7e0b450b210c.png)
![2021-03-30_20 00 17](https://user-images.githubusercontent.com/2474569/113071549-f8c75d80-9192-11eb-9cfd-9475b9b8fb70.png)

**Info (please complete the following information):**
 - Server version:  paper 1.16.5 latest
 - Client version:  fabric 1.16.4 & vanilla 1.16.5
 - Plugin version: 2.2.7

**Comment by LoneDev6** [comment]
I can't do much, sorry: https://itemsadder.plugin.ga/faq/blocks-minerals-issues/leaves-and-transparent-blocks-problems#real_transparent-blocks-are-dropped-when-water-flows-on-them

Without a patch directly into Spigot I can't avoid these glitches. We need an option to disable mushroom and chorus updates completely.
I hope you understand

**Comment by xalixilax** [comment]
Oh i am sorry i remember reading that. Then I'm gonna avoid using these blocks too much.

**Comment by LoneDev6** [comment]
it's okay no worries, I just wish I could make them better but right now Minecraft code that handles the chorus stuff is a mess and can't be disabled easily

**Comment by 100petr** [comment]
I would just like to add that the chorus fruit also duplicates it above the daylight detector. 
![image](https://user-images.githubusercontent.com/29830635/113501742-d8e3c100-9527-11eb-8928-00402ce47b99.png)

**Comment by LoneDev6** [comment]
I already asked, only Purpur developer seems to be interested into this stuff.
Anyway I will try to fix this but I don't think I can

**Comment by 100petr** [comment]
Something new?

**Comment by LoneDev6** [comment]
I can't replicate the issue sadly, can you make a video?

**Comment by 100petr** [comment]
Now I'm doing it on a clean server and it works. These are banana tree leaves from https://www.spigotmc.org/resources/trees-fruits-forestry-itemsadder-addon.86963/
![image](https://user-images.githubusercontent.com/29830635/118354954-dc7a5700-b56d-11eb-8404-9e5f002cc8e6.png)

https://user-images.githubusercontent.com/29830635/118354832-4b0ae500-b56d-11eb-8b9f-fc0f3a86abdf.mp4

**Comment by 100petr** [comment]
https://github.com/pl3xgaming/Purpur/issues/256#event-4848640491 🎉

**Comment by LoneDev6** [comment]
OH yea!
