### ISSUE TITLE
[Suggestion] Add Mounts to IAMobs

### ISSUE THREAD

**Issue by loganpenin1** [PluginBugs/Issues-ItemsAdder#801]
I spoke to you a few months ago via spigot, suggesting that you put mounts, and you told me to suggest it on github. So, I'm here. I put AI from a horse in my server, and I can mount it, but not opening his inventory.

I wish you do possible the custom mounts with custom models! That would be nice.

Thanks a lot!

**Comment by LoneDev6** [comment]
Feature was added for the new entities system
