### ISSUE TITLE
[Suggestion] Add option to set multiple blocks to "replace_near_blocks" Action

### ISSUE THREAD

**Issue by SirGlozz** [PluginBugs/Issues-ItemsAdder#804]
**Is your feature request related to a problem? Please describe.**
I tried to make paintable blocks with a custom paint brush item, i want to add multiple blocks to "from:" list.

**Describe the solution you'd like**
Add option to make a list of blocks at the section "from" on the action "replace_near_blocks"
For example:

>     events:
>       interact.right:
>         replace_near_blocks:
>           radius:
>             x: 1
>             y: 1
>             z: 1
>           from:
>            - BLUE_CONCRETE
>            - RED_CONCRETE
>            - GREEN_CONCRETE
>            - YELLOW_CONCRETE
>           to: WHITE_CONCRETE
>           no_physics: false

The item in the example i showed, is for a white paint brush, to replace those 4 blocks to WHITE_CONCRETE block.

**Additional context**
This feature could be useful to replace multiple blocks, it would be nice if we can do this with custom blocks too.
Hope we can have this feature soon, thanks.

**Comment by LoneDev6** [comment]
will be added in the next update
