### ISSUE TITLE
[BUG] Incorrect installation of blocks

### ISSUE THREAD

**Issue by Venterok** [PluginBugs/Issues-ItemsAdder#806]
**Describe the bug**
Incorrect installation of blocks, the bug is very difficult to describe, but everything is shown in our video that I attached

**To Reproduce**
Watch the video, we showed everything in detail in practice there
https://youtu.be/Oie8vrg4eBI

**Info (please complete the following information):**
 - Server version: Purpur 1.16.5
 - Client version: Optifine 1.16.5
 - Plugin version: 2.2.9

**Comment by LoneDev6** [comment]
will be fixed
