### ISSUE TITLE
[BUG] items duplicate in crafting_table

### ISSUE THREAD

**Issue by patatoplugin** [PluginBugs/Issues-ItemsAdder#809]
**Describe the bug**

**To Reproduce**
1. make a custom receipe that have many patterns(I make 3 patterns recepie of emerald_sword)
2. Craft the item in crafting_table(at least prepare double materials)
3. click the result item
4. the material duplicate

**Expected behavior**

**Screenshots**
![2021-04-06_01 10 22](https://user-images.githubusercontent.com/62246956/113602830-b65fbe00-9675-11eb-9a2f-a71d8d8622f7.png)
![QQ截图20210406011713](https://user-images.githubusercontent.com/62246956/113602917-dabb9a80-9675-11eb-88cd-f9ef5535eeb0.png)

**Info (please complete the following information):**
 - Server version: (example: paper 1.16.5)
 - Client version: (example: fabric 1.16.5)
 - Plugin version:2.2.8

**Additional context**
I doubt another plugin InteractionVisualizer make this problem but I delete it，the problem still exist

**Comment by LoneDev6** [comment]
please read here: https://itemsadder.plugin.ga/compatibility-with-other-plugins/not-compatible
![immagine](https://user-images.githubusercontent.com/27242001/113679461-111e0780-96c0-11eb-945b-c4908d7340e6.png)
Probably you have a plugin that is interfering with recipes, I have no way to tell you which one is doing that, you have to disable one plugin by one. I'd be grateful if you provide me the name once you found it.

InteractionVisualizer has nothing to do with this problem, you're right.

have a nice day
