### ISSUE TITLE
[Suggestion] damage_entity_in_sight world guard flags

### ISSUE THREAD

**Issue by alejandro0256** [PluginBugs/Issues-ItemsAdder#810]
**Is your feature request related to a problem? Please describe.**
I create an item with the damage_entity_in_sight event, but I noticed that even with the world guard pvp flag disabled with an item that uses the damage_entity_in_sight you can still damage other players.

**Describe the solution you'd like**
I would be nice if it respects the world guard flags of pvp and damage-animals.

**Describe alternatives you've considered**
Maybe another solution is an option to specify the entities like in the damange_near_entities action with the entity_groups option.

**Comment by LoneDev6** [comment]
thanks, this is a bug in the permissions checking
