### ISSUE TITLE
[BUG] items duplicate again 

### ISSUE THREAD

**Issue by patatoplugin** [PluginBugs/Issues-ItemsAdder#811]
**Describe the bug**
I run a paper sever(1.16.5#582) only use this plugin,and items duplicate again

I test item only one receipe and it is ok ,but two pattern recipe make probelm
**To Reproduce**
1. make a 2 or 3 pattern receipe 
2. craft the item
3. click the result item
4. item duplicate

**Expected behavior**

**Screenshots**
![QQ截图20210407011513](https://user-images.githubusercontent.com/62246956/113751651-bf689200-973e-11eb-9024-983f1b94ab2d.png)

![receipe](https://user-images.githubusercontent.com/62246956/113751409-82040480-973e-11eb-9860-6493cafc19b0.png)

![2021-04-07_01 16 46](https://user-images.githubusercontent.com/62246956/113751879-f76fd500-973e-11eb-824e-9786219b20f7.png)

I only use this plugin to run my local sever 
**Info (please complete the following information):**
 - Server version: 1.16.5
 - Client version: 1.16.5
 - Plugin version: 2.2.10

**Additional context**

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/788

https://github.com/PluginBugs/Issues-ItemsAdder/issues/535
