### ISSUE TITLE
Support Citizens Plugin

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#812]
Support Citizens Plugin to be able to use the custom the mobs as NPC

- Command /npc type {name of the Custom mob}

![image](https://user-images.githubusercontent.com/68678154/113799710-d9fa3580-9755-11eb-86b3-e6afbbe8886b.png)

**Comment by LoneDev6** [comment]
mhhh, if the NPC is stand still and not moving you can just create an invisible ZOMBIE NPC and set the helmet to your soul item

**Comment by SNokerYT** [comment]
it's will be easier if you Support Citizens 😅

**Comment by SirCraftypants** [comment]
> 
> 
> it's will be easier if you Support Citizens 😅

What exactly are you trying to do? please explain.

**Comment by SNokerYT** [comment]
I will be able to make custom npc, with a natural movement

**Comment by SNokerYT** [comment]
it will also make me able to use the Denizen,Sentry plugin, this plugins has so many features also!
- https://wiki.citizensnpcs.co/Sentry
- https://wiki.citizensnpcs.co/Sentinel
- https://www.spigotmc.org/resources/sentry.20489/
![image](https://user-images.githubusercontent.com/68678154/114140224-4ae54d00-9910-11eb-9ef1-e6a18361f1de.png)

**Comment by DarkSumrak** [comment]
Yes indeed the support of Citizens 2 points would be a very cool idea

**Comment by LoneDev6** [comment]
Support was added for the new entities system
