### ISSUE TITLE
Support Plugin Custom Structures

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#813]
this plugin is really important to be able to make a custom structures with itemadder blocks
- https://www.spigotmc.org/resources/custom-structures.38249/
![image](https://user-images.githubusercontent.com/68678154/113800016-7d4b4a80-9756-11eb-8703-750e5150b7d9.png)

**Comment by Sheikins** [comment]
Good Feature +1

**Comment by ArgonGaming** [comment]
Send over the developer's discord so Lone can contact them, or tell the developer to contact Lone via discord. Lone is happy to contact other devs about implementations and compatibility where possible.

**Comment by Bimic332** [comment]
Good Feature +1

**Comment by ArubikU** [comment]
Working That :)

**Comment by LoneDev6** [comment]
ItemsAdder has an API and they can use it to easily add support :D
https://itemsadder.devs.beer/developers/java-api
