### ISSUE TITLE
[BUG]multiple patterns receipe make item duplicate[It is important!]

### ISSUE THREAD

**Issue by patatoplugin** [PluginBugs/Issues-ItemsAdder#814]
**Describe the bug**
I just delete all the plugin file,and world saves,let it auto create,and no other plugin
So pls dont tell me that not compatible with other plugin（NO OTHER PLUGIN）
Then I edit emerald_sword's receipe from
![QQ截图20210408003723](https://user-images.githubusercontent.com/62246956/113902575-9f020b80-9802-11eb-9a22-b382d814c77a.png)

to 
![QQ截图20210408003707](https://user-images.githubusercontent.com/62246956/113902597-a45f5600-9802-11eb-9696-6bce4daba9d7.png)

then Item duplicate 

I hope you tell me if I write any wrong code or your plugin have bug?

I truely hope you can solve this bug or I have to use one receipe,
**To Reproduce**

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - Server version: (example: paper 1.15.2)
 - Client version: (example: fabric 1.15.2)
 - Plugin version: (example: 2.0.9 do not write "latest")

**Additional context**

**Comment by LoneDev6** [comment]
I will check tomorrow and try to reproduce the issue, then I will fix the problem.
Thanks for the patience

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/811

**Comment by LoneDev6** [comment]
Thanks a lot I managed to find the mistake, I will push an update today! Thanks again
