### ISSUE TITLE
[BUG] Fire still having Orange

### ISSUE THREAD

**Issue by Fantom250YT** [PluginBugs/Issues-ItemsAdder#817]
**Describe the bug**
The fire still has the original orange in it sometimes

**To Reproduce**
1. Get Chemical Igniter
2. Click on the original place fire
3. Either doesn't completely remove the orange or works fine
4. It's not the pure colour

**Expected behavior**
It will be the pure colour without the old fire colour

**Screenshots**
<img width="833" alt="Screenshot 2021-04-09 at 13 23 27" src="https://user-images.githubusercontent.com/73852683/114179762-51d38600-9937-11eb-9c73-48eeafca39bd.png">

**Info (please complete the following information):**
 - Server version: Paper 1.16.5
 - Client version: 1.16.4/1.16.5
 - Plugin version: 2.2.7

**Additional context**
I understand that this might just be minecraft limitations etc, just wandering if it's possible to fix

**Comment by LoneDev6** [comment]
Thanks this will be enhanced in next update, you will have to use /iazip command and reupload on dropbox/update url if needed
