### ISSUE TITLE
[Suggestion] Support for Tab Plugin 

### ISSUE THREAD

**Issue by Speedspencer** [PluginBugs/Issues-ItemsAdder#819]
**Is your feature request related to a problem? Please describe.**
 I use Tab Plugin which is the only thing I can't make it work as tab cannot read 2 placholder at the same time? 
Custom Emoji (%img_iron%) <-- Rank Prefix (%vault_prefix%) It happen wit hnametag and 

**Describe the solution you'd like**
Make Tab in a support plugin list , or Fix its compatibility

**Additional context**
![image](https://user-images.githubusercontent.com/36989640/114273950-72d6cc80-9a46-11eb-8985-c4c685644a19.png)

**Comment by Sheikins** [comment]
This feature is already implemented normally. Try with this plugin https://www.spigotmc.org/resources/tab-1-7-x-1-16-5-free-version.57806/

**Comment by LoneDev6** [comment]
>  tab cannot read 2 placholder at the same time

seems to be a bug of the tab plugin, itemsadder doesn't handle replacements in any way, it's the tab plugin job to hook placeholder api correctly
