### ISSUE TITLE
[Suggestion] Add an option to replace any block of that type between the height range instead of spawning only small veins

### ISSUE THREAD

**Issue by MrJorman** [PluginBugs/Issues-ItemsAdder#820]
add the ability to add stones/moss on the surface or in dungeons as in Origin Realms, and also, so that the crystals can be located at 360 degrees when generating

**Comment by LoneDev6** [comment]
From Discord ticket: `239463565814136833/829798038474194956`

![immagine](https://user-images.githubusercontent.com/27242001/114529783-979b9180-9c4a-11eb-96b4-2b4c32c3ba4f.png)
![immagine](https://user-images.githubusercontent.com/27242001/114529800-9c604580-9c4a-11eb-9abb-a04a214e02be.png)
