### ISSUE TITLE
Scoreboard outline not going 

### ISSUE THREAD

**Issue by Fantom250YT** [PluginBugs/Issues-ItemsAdder#827]
**When using the Screen Effects addon the scoreboard outline shows**
When I go into a Screen Effect the scoreboard text gets removed but the outline is still there.

**To Reproduce**
1. Execute a Screen Effects command
2. View the screen effect
3. See that the Scoreboard text has been removed but not the outline
4. scoreboard outline makes it look bad

**Expected behavior**
There is no sign of scoreboard when in a Screen Effect. just the pure colour and text.

**Screenshots**
<img width="1948" alt="Screenshot 2021-04-12 at 20 08 11" src="https://user-images.githubusercontent.com/73852683/114469418-08a85e00-9be5-11eb-83ec-4956633c9513.png">

**Info (please complete the following information):**
 - Server version: 1.16.5
 - Client version: 1.16.4/1.16.5
 - Plugin version: 2.2.7

**Comment by LoneDev6** [comment]
will be fixed in the next update

**Comment by Fantom250YT** [comment]
It is still showing

**Comment by Fantom250YT** [comment]
Maybe make it so you can get a command that gets executed when it appears and then executed again when it re appears so I could just put the scoreboard toggle command in there?
