### ISSUE TITLE
Wailat has placeholders

### ISSUE THREAD

**Issue by Fantom250YT** [PluginBugs/Issues-ItemsAdder#830]
I know you want Wailat addon/plugin to be simple but it would be really cool if you added some placeholders when you hover over the block such as %Wailat_block% etc.

I understand if this is too much for what you want the plugin to feature but it would be cool!

Thanks 😄

**Comment by LoneDev6** [comment]
Please suggest this on the wailat page not here, this is itemsadder issues report page
