### ISSUE TITLE
[Suggestion] Fully disabled custom block feature

### ISSUE THREAD

**Issue by ArtifactyNight** [PluginBugs/Issues-ItemsAdder#835]
**Is your feature request related to a problem? Please describe.**
About #829

it's looks like not fully disabled.
it's still have emulate block break particle

i mean i want to make note block particle is split by vanilla default.
so i want to make custom block by coding themself.

the block break particle will having own particle
like if i make the new custom block texture
i break it, so now the block break particle will display same as block texture.
but Itemsadder not allowed me to do that 😢

i know if i request this feature. the custom block's particle will not displaying because of resourcepack
and i fixed it.

and i can't change note block blockstates in resourcepack too..
can you making it can changes when i disabled that feature ?

**Comment by ArtifactyNight** [comment]
btw sorry for open ticket for many time with same issues :(

**Comment by ArtifactyNight** [comment]
up

**Comment by ArtifactyNight** [comment]
ok! thank you so much
and i'm so sorry about this if i'm making you not satisfied

**Comment by LoneDev6** [comment]
It's okay don't worry
