### ISSUE TITLE
[Suggestion] Big category have small categories

### ISSUE THREAD

**Issue by patatoplugin** [PluginBugs/Issues-ItemsAdder#837]
**Is your feature request related to a problem? Please describe.**
 My English is poor.I mean I have added too many items.When I open a furniture Category,I have 4 pages to find a item.

So Can you make the category just like windows' folder, Furniture/Bathroom.

fisrt open Furniture Category,then open Bathroom Category or Bedroom Category,finally find what I want

I hope you can understand what I say

**Describe the solution you'd like**

make the category just like windows' folder, Furniture/Bathroom.

BIG Category have small categories

**Describe alternatives you've considered**

**Additional context**

**Comment by DarkSumrak** [comment]
Why don't you just use ChestCommand or DeluxMenus to create this idea.
Почему бы вам просто не использовать ChestCommand или DeluxMenus для создания данной идеи.
![image](https://user-images.githubusercontent.com/60610581/115136279-6c88b780-a027-11eb-8b4e-cc51380dace8.png)
![image](https://user-images.githubusercontent.com/60610581/115136282-75798900-a027-11eb-98a7-944a54e99725.png)

**Comment by patatoplugin** [comment]
> Why don't you just use ChestCommand or DeluxMenus to create this idea.
> Почему бы вам просто не использовать ChestCommand или DeluxMenus для создания данной идеи.
> ![image](https://user-images.githubusercontent.com/60610581/115136279-6c88b780-a027-11eb-8b4e-cc51380dace8.png)
> ![image](https://user-images.githubusercontent.com/60610581/115136282-75798900-a027-11eb-98a7-944a54e99725.png)

I have nearly 1000 items,it is a huge work to make Custom GUI,the wiki only tell you how to make the custom background png in gui.

And I want to use the permission （ia.user.ia.<item>） to let players think they are unlock new items.

**Comment by DarkSumrak** [comment]
https://itemsadder.plugin.ga/plugin-usage/ia

**Comment by LoneDev6** [comment]
If I understood correctly this is a "subcategory" feature request, yes it's possible but it may take some time since I have to edit how the GUI code works.
Do you think it's a good idea to create subcategories? I think the user may feel confused because of the high number of subcategories this feature will introduce

**Comment by DarkSumrak** [comment]
I think this is a matter for everyone personally to add such an opportunity or not to their menu, but in general, the idea is good

**Comment by LoneDev6** [comment]
> I think the user may feel confused because of the high number of subcategories this feature will introduce

I decided to discard this idea
