### ISSUE TITLE
[Suggestion] font size for smileys

### ISSUE THREAD

**Issue by 100petr** [PluginBugs/Issues-ItemsAdder#838]
**Describe alternatives you've considered**
Do not distinguish the font size for smileys. For example: :fish : (space due to github) but also :FISH: (:FIsh:, ...) writes emoji
![image](https://user-images.githubusercontent.com/29830635/115043526-e0667b00-9ed4-11eb-95fb-16aaa31cdf82.png)
**Additional context**

Now it works so that if the font size is different from the one set by emoji it will not be written.

**Comment by LoneDev6** [comment]
Thanks I will fix this
