### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by majestiknetwork** [PluginBugs/Issues-ItemsAdder#842]
**Describe the bug**

**To Reproduce**

**Expected behavior**
It should be fixed as soon as possible.

**Screenshots**
https://prnt.sc/11kybra

**Info (please complete the following information):**
 - Server version:  pupur 1.16.4
 - Client version: pupur 1.16.4
 - Plugin version: 2.3.0

**Additional context**
No.

**Comment by LoneDev6** [comment]
1. you didn't write all the info requested in the issue template
2. the error is sent as screenshot, not text. You can send it using pastebin.com
3. I need the full log not a part of it
