### ISSUE TITLE
[Bug] resourcepack loading only with "prompt" client option

### ISSUE THREAD

**Issue by anthony114669** [PluginBugs/Issues-ItemsAdder#843]
i notice with the last update every time on player wanna join the resource pack keep failing and failing to be apply when they have te "edit server options in enable", in order to download well they have to change the option into "prompt" for some strange reazon just works that way. i hope that can be fic, thanks in advance.

items adder version:  2.3.0

papermc version 1.16.5 v.584

**Comment by LoneDev6** [comment]
1. Does it works if you try with the previous update?
2. can I have your complete server log?

**Comment by anthony114669** [comment]
mmm i just realize of another thing, i downgrade the core and test, keep failing, so that means the new update there is nothign to do with the issue, so i was thinking and meditating what i i did before to get this issue, and i remember i repack (izip) the resource pack with some custom thins as always do (optifine textures, i did before successfully with no issues im advance user in itemsadder btw) and then keep failing, so what i did its remade a quick server just with items adder and repack the repsurce and woala, works again, so that means when i install addons/textures or something and repack mayority of the time works, but just sometimes the repack stop working with the "enable mode" and only works with the "prompt" mode. i hope i can make understand my self with this explanation, but i guess there is not fix for this issue because is causing it for external situations (addons) or custom textures. but i gues the "soul" of items adder is that, create new things and manipulate the plugin content. but unfortunelly that mess up the autoload feature and only works with "prompt" so i have to tell all my players: please change the option from "enable" to prompt, and they have to do it every time they wanna joing to the server.

**Comment by LoneDev6** [comment]
Okay so basically something got misconfigured and this started happening.
Feel free to open a support ticket on my Discord server and send:
- FULL SERVER LOG of when the issue occured
- send me your server address so I can join
- whitelist my account `LoneDev` (if your server has whitelist) and add me `ia.*` permission

**Comment by anthony114669** [comment]
ok thanks, of course, ill open rn a ticket in your server and ill atach all the info you need. i will atach also this conversation to follow the track and figure out what topic is the ticket related.

**Comment by LoneDev6** [comment]
# We found out the reason: 

basically the user has added some files into the resourcepack and these files (or one of them, it's not clear) are corrupted.
Minecraft client reports this in its log: `java.util.zip.ZipException: invalid END header (bad central directory size)`
It indicates that a file is corrupted, in their case it was a file in the optifine folder.
