### ISSUE TITLE
[BUG] Textures Critical error.

### ISSUE THREAD

**Issue by zSkyBlack** [PluginBugs/Issues-ItemsAdder#845]
Since I bought the plugin, I have been having a problem with the ItemsAdder, I have a friend who also has it and I told him my problem but his answer was that he never had that problem and he does not know how to solve it. I think the problem has to do with the textures or recipes.

Proofs: https://gyazo.com/b3094ca8f48575304f9b7cb8a72a58db & https://gyazo.com/ba41b55f1a4efb4d0191ad9341b31df9

I don't know if it has something to do with it but I have it as a hamachi server with some friends, for now I have it in hamachi but in a few months I'll have a host.

[configfile.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/6329875/configfile.zip) <--- here my config.yml

Server versión: spigot 1.14
ItemsAdder versión: 2.3.0

Thanks for watching.

**Comment by zSkyBlack** [comment]
I also get an error when a player throws a projectile.

Proofs: https://gyazo.com/179bff081e681bdc3711160950393825

**Comment by zSkyBlack** [comment]
Srry for create another Issues I'm new and idk how to use this xD.

**Comment by DarkSumrak** [comment]
Always use the latest build of the server core in your case install 1.14.4. And better already 1.15.2

**Comment by zSkyBlack** [comment]
Ok works now, thanks!
