### ISSUE TITLE
[Suggestion] Possibility ignore case sensitive letters when you use emojis

### ISSUE THREAD

**Issue by The-Gust** [PluginBugs/Issues-ItemsAdder#848]
Allow ignoring case of symbols. Like - I'm wanna use :Pog: and :poG: or :Kekw: and :KEKW:,  not only :pog: and :kekw:
Thats it, should be useful for twitch/discord users. 
![image](https://user-images.githubusercontent.com/43398430/115153580-d173fa00-a087-11eb-9df7-a9259cf703ee.png)

**Comment by LoneDev6** [comment]
duplicate https://github.com/PluginBugs/Issues-ItemsAdder/issues/838
