### ISSUE TITLE
Option to hide particles of `potion_effect` action

### ISSUE THREAD

**Issue by yebanme** [PluginBugs/Issues-ItemsAdder#849]
**Is your feature request related to a problem? Please describe.**
potion_effect operation displays the particle effect by default. If you can add attributes to hide the particle effect, will have a better experience
https://minecraft.fandom.com/wiki/Commands/effect
**Additional context**

```java
potion_effect:
  type: UNLUCK
  duration: 100
  amplifier: 0
  particle: false

**Comment by potapenchikov** [comment]
I still didn't understand how this function was implemented
