### ISSUE TITLE
[Suggestion] Make New Furniture using Itemframe and barrier 

### ISSUE THREAD

**Issue by patatoplugin** [PluginBugs/Issues-ItemsAdder#852]
Now when you put a furniture,the plugin create an armorstand and put a paper in head.
Can you make another way-----A Barrier and a invisible itemframe?

So maybe the funiture can be this

    behaviours:
      furniture:
        itemframe: true
        solid: false

Becasue Everytime I make a cross model（Just like grass,sapling，the model only have two surfaces），In game the model will be dark even I set "shade":false.

as I know,itemframe can solve this problem

By the way,my another feature requset: https://github.com/PluginBugs/Issues-ItemsAdder/issues/837

Hope you can answer me！

**Comment by LoneDev6** [comment]
Update will be published in some days
