### ISSUE TITLE
 [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name

### ISSUE THREAD

**Issue by anthony114669** [PluginBugs/Issues-ItemsAdder#855]
this is happening when i click on "search" and i get "search results menu" with the last update, i just want to report it :)

**Comment by LoneDev6** [comment]
Thanks I will fix this

**Comment by makarasty** [comment]
I didn't have the main interface of the plugin displayed, I saw an error in the console:
`[ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.categories_view.font_image.name`

**To solve it**, I opened the **.jar** plugin with **winrar** and moved the files ↓
* from `plugins/ItemsAdder_3.6.2-beta-r2.jar/contents/_iainternal`
* to `plugins/ItemsAdder/contents/_iainternal`
