### ISSUE TITLE
[BUG]  Attack large mobs and bounce off the server

### ISSUE THREAD

**Issue by Posvite** [PluginBugs/Issues-ItemsAdder#856]
Version 2.3.2  I used a diamond sword ( master sword ) to attack a large mob and bounce off the server

**Comment by Posvite** [comment]
the server you were previously on went down you have been connected to a fall back server

**Comment by LoneDev6** [comment]
Hello, please provide all the info you basically erased from the message when you created the issue report.
Thanks
