### ISSUE TITLE
[Suggestion] PlaceMob

### ISSUE THREAD

**Issue by danielzinh** [PluginBugs/Issues-ItemsAdder#862]
**Suggestion:**

I may be talking nonsense, but I look for it and I didn't find it...

add a ItemsAdder.spawnCustomMob()

i tried CustomMob.spawn() but returns me that class doesn't exists...

**Comment by LoneDev6** [comment]
CustomMob.spawn("creaturesplus:soul", location) will return a CustomMob instance.
If not, then it's a bug report and report it as a bug report providing ALL the info requested
