### ISSUE TITLE
Invisibility on join bug

### ISSUE THREAD

**Issue by ocyt** [PluginBugs/Issues-ItemsAdder#865]
When you log in, you sometimes get invisibility twice, or even for a long time

**Comment by LoneDev6** [comment]
Thanks for the report, I should have fixed this in the next update.
Seems that if a user leaves during the installation won't get invisibility effect removed.

I have no other explanation about the invisibility problem.
Anyway it will be applied for 120 seconds on join, to avoid people from seeing stuck players while they're installing the pack.
