### ISSUE TITLE
[BUG] can play without pack

### ISSUE THREAD

**Issue by 100petr** [PluginBugs/Issues-ItemsAdder#867]
**Describe the bug**
Players can join without a resourcepack

**To Reproduce**
1. Set kick_player_on_decline in config.yml to true 
2. Restart server
3. You can join and play without resourcepack

**Expected behavior**
It will kick you out of the server if you reject the resourcepack

**Info (please complete the following information):**
 - Server version: Purpur-1065 (MC: 1.16.5)
 - Client version: 1.16.5
 - Plugin version: 2.3.5

**Additional context**
![image](https://user-images.githubusercontent.com/29830635/116583207-655e8500-a916-11eb-9660-3cfdf01e3130.png)

**Comment by LoneDev6** [comment]
Tested on `Yatopia version git-Yatopia-ver/1.16.5-76 (MC: 1.16.5)`
works fine
![immagine](https://user-images.githubusercontent.com/27242001/117162243-e6a89280-adc2-11eb-86b3-92730499caa3.png)

**Comment by 100petr** [comment]
![image](https://user-images.githubusercontent.com/29830635/117163369-dd6bf580-adc3-11eb-8a13-797dd69f8222.png) they dont have this permission

**Comment by LoneDev6** [comment]
This is very strange, you can test on a local test server with only itemsadder?

**Comment by 100petr** [comment]
https://user-images.githubusercontent.com/29830635/117176292-04302900-add0-11eb-944d-b9e5996fa707.mp4

**Comment by 100petr** [comment]
Oh, the problem is probably found. Probably as the structure of the config has sometimes changed, I have some options twice.

**Comment by LoneDev6** [comment]
> 
> 
> Oh, the problem is probably found. Probably as the structure of the config has sometimes changed, I have some options twice.

can you send your config there?

**Comment by 100petr** [comment]
Try https://cdn.discordapp.com/attachments/802962020428152882/839543080336228352/config.yml

**Comment by 100petr** [comment]
So it look like I have such a config on the test server. On normal server, I have this option once, because I recently restarted the config. I don't care much about the test server :D
