### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by xalixilax** [PluginBugs/Issues-ItemsAdder#873]
**Describe the bug**
When installing an addon with over 62 REAL blocks, the real_blocks_ids_cache.yml set every blocks ids over 62 to 64. This mean that the blocks item in hands is fine with the right texture but the block you place will have the wrong texture, but also the texture from another block.

**To Reproduce**
Install buildersbasics as stated on the page
/iazip 
Every blocks after ID 62 will be set to 64

**Expected behavior**
Ids should continue up to 188

**Screenshots**
![image](https://user-images.githubusercontent.com/2474569/116957877-02972180-ac67-11eb-9031-4151c2b8cfdf.png)
![image](https://user-images.githubusercontent.com/2474569/116957949-20fd1d00-ac67-11eb-8edd-be276089d1ff.png)

**Info (please complete the following information):**
Paper 570 MC:1.16.5
Fabric 0.10.8-1.16-4
IA v2.2.10

**Additional context**
Similar issue: 
https://github.com/PluginBugs/Issues-ItemsAdder/issues/751

Also, here's an updated version custom-blocks.yml file with REAL_NOTE and PAPER as material for buildersbasic
https://pastebin.com/5YaXxh3R

**Comment by LoneDev6** [comment]
Thanks you're very helpful!
I will fix this in the next update.

Basically after the update you will have to
- stop server
- delete all the lines with id 64 from the file `real_blocks_ids_cache.yml`
- then start the server and use `/iazip` again

**Comment by TheFantasticLoki** [comment]
What is the max ids available to use now @LoneDev6 ? I also use buildersbasics but I also have blockus installed can I use all 340 something blocks as real blocks to avoid massive client lag when loading large builds with these blocks? If I change a specific block to real after it's been placed there is no easy way to replace the old blocks other than manually.

**Comment by LoneDev6** [comment]
Read here https://itemsadder.plugin.ga/plugin-usage/adding-content/advanced/item-properties/specific-properties/blocks#placed_model

Or in `/iainfo`
```
[10:21:06 INFO]:      REAL block IDs: 0/191
[10:21:06 INFO]:      REAL_NOTE block IDs: 0/750
[10:21:06 INFO]:      REAL_TRANSPARENT block IDs: 0/63
```

**Comment by TheFantasticLoki** [comment]
This is what I got issuing the command iainfo to console gonna try in game just waiting on minecraft to load. Data
[14:38:12 INFO]:      Items: 1160
[14:38:12 INFO]:      Items in /ia: Loading ...
[14:38:12 INFO]:      Namespaces: 22
[14:38:12 INFO]:      Materials: 104
[14:38:12 INFO]:      REAL block IDs: 0/191
[14:38:12 INFO]:      REAL_NOTE block IDs: 0/750
[14:38:12 INFO]:      REAL_TRANSPARENT block IDs: 0/63
[14:38:12 INFO]:      FIRE block IDs: 0/14

**Comment by TheFantasticLoki** [comment]
Same output in game still not showing how many ids are used
