### ISSUE TITLE
[BUG] Incompatibility with BungeeCord (may be critical)

### ISSUE THREAD

**Issue by Feniksovich** [PluginBugs/Issues-ItemsAdder#875]
**Describe the bug**
When a player tries to interact with a block of bronze ore from the standard ItemsAdder stuff (bronze_ore), he is disconnected from the server without any reason or error.

**To Reproduce**
1. Start BungeeCord instance and connect simple Bukkit server to it.
2. Join the server using BungeeCord IP-address (so it would handle your connection while you playing on simple Bukkit server).
3. Get bronze_ore using `/iaget itemsadder:bronze_ore`
4. Place block on the ground.
5. Disable creative mode.
6. Try to click or break block -> you got kick.

**Expected behavior**
No kick/disconnect.

**Video**
https://youtu.be/1sEERVVqyT4

**Info (please complete the following information):**
 - Server version: git-Paper-643 (MC: 1.16.5)
 - Proxy (BungeeCord) version: Build 1559 (https://ci.md-5.net/job/BungeeCord/1559/)
 - Client version: Minecraft 1.16.5 with Optifine
 - Plugin version: 2.3.5

**Additional context**
— BungeeCord server and Bukkit server haven't any plugins that could cause this issue.
— This issue doesn't occur if the player interacts with the block in creative mode.
— This issue doesn't occur if BungeeCord ins't used.
**— It is likely that this issue occurs not only with the bronze ore block. I have no desire to check all other things, this is your duty.**

**Comment by LoneDev6** [comment]
Is there any error in the bungeecord console?
This is very strange.. it doesn't happen on my local test bungeecord network

**Comment by LoneDev6** [comment]
I suspect this was introduced by a recent change in Bungeecord since it never happened to any of my clients until this week.
Another user reported that issue today, but still I can't find the cause of this problem

Can you try downgrading bungeecord or installing waterfall instead of bungeecord?

**Comment by Feniksovich** [comment]
> I suspect this was introduced by a recent change in Bungeecord since it never happened to any of my clients until this week.
> Another user reported that issue today, but still I can't find the cause of this problem
> 
> Can you try downgrading bungeecord or installing waterfall instead of bungeecord?

Can you provide your BungeeCord and Bukkit info so I can recreate this on my own, please?

**Comment by MinecollYT** [comment]
I'm having this issue too, as mention from LoneDev. **This issue is very critical.**

> Can you provide your BungeeCord and Bukkit info so I can recreate this on my own, please?
> And as I said earlier, this issue isn't accompanied by any error in server consoles.
BungeeCord: git:BungeeCord-Bootstrap:1.16-R0.5-SNAPSHOT:a7c6ede:1549 by md_5
Spigot: Paper git-Paper-566 (MC: 1.16.5)
ItemsAdder 2.3.5
LoneLibs 1.0.7

**Comment by MinecollYT** [comment]
https://youtu.be/kBOwzxzSN3s

**Comment by Feniksovich** [comment]
> I suspect this was introduced by a recent change in Bungeecord since it never happened to any of my clients until this week.
> Another user reported that issue today, but still I can't find the cause of this problem
> 
> Can you try downgrading bungeecord or installing waterfall instead of bungeecord?

So, I have updated BungeeCord and Paper to the latest version and created completely new servers.
This issue is still there and I was finally able to get an error message:

**BungeeCord build:** 1559
**Paper build:** 649

BungeeCord console:
```
17:45:18 [INFO] [Feniksovich,/xxx.xxx.xxx.xxx:12312] <-> InitialHandler has connected
17:45:18 [INFO] [Feniksovich] <-> ServerConnector [srv] has connected
17:46:54 [INFO] [Feniksovich] disconnected with: DecoderException : java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): UnpooledSlicedByteBuf(ridx: 0, widx: 0, cap: 0/0, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2, widx: 2, cap: 128)) @ io.netty.handler.codec.MessageToMessageDecoder:98
17:46:54 [INFO] [Feniksovich] -> UpstreamBridge has disconnected
17:46:54 [INFO] [Feniksovich] <-> DownstreamBridge <-> [srv] has disconnected
```

The paper server console does not contain any errors.

———————————————————————————

**Waterfall build:**  415
**Paper build:** 649

There are no errors, works fine.

———————————————————————————

So, is it worth waiting for a fix for BungeeCord?

**Comment by Feniksovich** [comment]
Another third-party bug, btw:
![image](https://user-images.githubusercontent.com/33875970/117477322-afcbab80-af7f-11eb-8a87-c3ce4d408272.png)

**Comment by LoneDev6** [comment]
Indeed a Bungeecord bug, works fine on Waterfall.
I managed to bypass the issue btw, somehow changing the way I register ProtocolLib packet listener fixed the issue.
I will post an update today :D



> 
> 
> Another third-party bug, btw:
> ![image](https://user-images.githubusercontent.com/33875970/117477322-afcbab80-af7f-11eb-8a87-c3ce4d408272.png)

Regenerate your zip file using /iazip and follow the wiki [hosting tutorial](https://itemsadder.plugin.ga/plugin-usage/resourcepack-hosting), your pack is not syncronized

**Comment by Jqnvier** [comment]
Hello I have the same error on my server.

I am under bungee-cord and surprisingly impossible to break a block of ItemsAdder with a tool that will not allow the drop, without being disconnected with the following arror: 

DecoderException : java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledSlicedByteBuf(ridx: 1, widx: 1, cap: 1/1, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2, widx: 2, cap: 352)) @ io.netty.handler.codec.MessageToMessageDecoder:98


this is extremely annoying for new players who quit because of it  : '(

**Comment by LoneDev6** [comment]
@Jqnvier please next time open a new Github issue report instead of commenting another, to avoid other people to get notified.
Anyway, I didn't get any information to identify the issue.
If you have an old itemsadder version update it.

Open a new issue report and provide all the info required: https://github.com/PluginBugs/Issues-ItemsAdder/issues/new/choose
