### ISSUE TITLE
[BUG] Potatoes+knife bug

### ISSUE THREAD

**Issue by a469** [PluginBugs/Issues-ItemsAdder#876]
I seem to have found a bug. When I made peeled potatoes, I used the number shortcut key 2 to put all the finished products together. The number of potatoes and the durability of the knife were reduced, but the number of peeled potatoes was not increase.
The server core version is Purpur-1065, the client version is 1.16.5, the plug-in version is ItemsAdder 2.3.5, and no errors are reported in the log.
[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/6426669/latest.log)

https://user-images.githubusercontent.com/40757206/117133187-733b5c80-ad93-11eb-8ec4-4063dba83887.mp4

**Comment by LoneDev6** [comment]
Strange, I don't have the bug, it may be another plugin interfering.
Try also in survival mode, maybe creative mode is the issue.

Tested on 
Client: Minecraft 1.16.5
Server: Yatopia version git-Yatopia-ver/1.16.5-76 (MC: 1.16.5)


https://user-images.githubusercontent.com/27242001/117159782-dabbd100-adc0-11eb-951e-0f9da8b8ae02.mp4

**Comment by a469** [comment]
Is it convenient to send a list of your plug-ins so that I can confirm if any plug-ins are missing. In the local test server, except for ItemsAdder, only CMI is installed, BlepFishing also has some necessary plugins
![image](https://user-images.githubusercontent.com/40757206/117161644-9c6ae580-adb1-11eb-87e0-1ee08d82090d.png)

**Comment by LoneDev6** [comment]
`EasyClearChat*, Essentials, EssentialsChat, ItemsAdder, LibsDisguises, LightAPI, LoneDevCheck*, LoneLibs, LuckPerms, Multiverse-Core, Multiverse-Portals, packetevents*, PacketListenerApi*, PlaceholderAPI, PlugMan*, ProtocolLib, ResourcePackBroadcast, ScratchIt, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldEdit, WorldGuard`

**Comment by LoneDev6** [comment]
Try to remove CMI, BlepFishing, CMILib

**Comment by a469** [comment]
This problem may be related to the LibsDisguises plugin?

**Comment by LoneDev6** [comment]
try to disable

**Comment by a469** [comment]
CMI, BlepFishing, CMILib have been deleted, the problem remains the same

https://user-images.githubusercontent.com/40757206/117165920-70e9fa00-adb5-11eb-84b8-fc9bf01ced66.mp4

**Comment by a469** [comment]
I mean, is the LibsDisguises plugin related to this recipe? Is it because I didn’t install this plugin and caused the problem?

**Comment by LoneDev6** [comment]
change from purpur to paper or yatopia
https://papermc.io/downloads
https://yatopiamc.org/download.html

**Comment by LoneDev6** [comment]
> 
> 
> I mean, is the LibsDisguises plugin related to this recipe? Is it because I didn’t install this plugin and caused the problem?

it's not needed, it's needed only for custom mobs

**Comment by a469** [comment]
https://user-images.githubusercontent.com/40757206/117166638-14d3a580-adb6-11eb-82e8-6ae81010dcf3.mp4

I also tested this bug on my friend's server, he used the Paper

**Comment by a469** [comment]
I see that in your video, the mouse is used to take out the finished product instead of the number keys. Can you try to use the number keys?

**Comment by LoneDev6** [comment]
I understood the issue, I didn't even know that Minecraft allows you to take items out of the crafting using the numeric keys..

I will try to fix this in the next update

**Comment by a469** [comment]
Okay, hope you can fix this bug as soon as possible

**Comment by LoneDev6** [comment]
will be fixed in the next update
