### ISSUE TITLE
[Suggestion] Function for donators.

### ISSUE THREAD

**Issue by ToxaEagle123** [PluginBugs/Issues-ItemsAdder#877]
It would be nice to add such a setting to the config, which would be responsible for the dropout of cosmetics after the death of the player (**like hats, backpacks, etc.**). For example, I need to give out cosmetics in the form of a hat to my donator, so that it is not like an ordinary thing, for example, he must register the command "**/hat1**" so that a hat appears on his head and so that he cannot manually remove it or throw it away as a drop (**this is necessary so that hats and other cosmetics are available only to donators**).

I do not think that this function can be superfluous, I find it quite useful for those who want to diversify the privileges of their donators.

**P.S I could formulate my idea incomprehensibly, since I do not speak English. So, if it's not difficult for you, you can ask a question!**

**Comment by MinecollYT** [comment]
I think this is an feature for a third party plugin
