### ISSUE TITLE
[Suggestion] - Terra support

### ISSUE THREAD

**Issue by Fantom250YT** [PluginBugs/Issues-ItemsAdder#882]
It would be cool if support for the terrain plugin terra could be added, at the moment I can but the block data into the terra config and the texture will work but none of the itemsadder features as the itemsadder blocks have to be cached to work.

**Comment by LoneDev6** [comment]
Hello,
you should contact Terra developer and ask to use my free api.
If they need help they're free to contact me, I will also send them a copy of itemsadder for free if needed.

RealisticWorldGenerator developer added ItemsAdder compatibility with no issues, so also Terra dev can :D

**Comment by solonovamax** [comment]
Terra has an addon system that allows you to interface directly with the Terra api.
I can't find  the docs for addons (I forget if we made any lol), but [here](https://github.com/PolyhedralDev/TerraAddonTemplate)'s a link to an addon template. And [here](https://github.com/PolyhedralDev/Terra/wiki/Addons)'s a list of some other public FOSS addons.

**Comment by Fantom250YT** [comment]
@LoneDev6 Do you think you could make a addon for this to work with Itemsadder?

**Comment by LoneDev6** [comment]
I don't think I have the time to learn their API, RealisticWorldGenerator added compatibility without requiring me to code an addon for the world generator.

I may in the future but not now, too many support requests to handle

**Comment by solonovamax** [comment]
api should be pretty simple and straight forward.
We also have a support channel in our discord if you need help.

**Comment by Caishangqi** [comment]
> api should be pretty simple and straight forward.
> We also have a support channel in our discord if you need help.



> It would be cool if support for the terrain plugin terra could be added, at the moment I can but the block data into the terra config and the texture will work but none of the itemsadder features as the itemsadder blocks have to be cached to work.

+1 RWG developers seem don't want to spend time on 1.17.1

**Comment by solonovamax** [comment]
that addon is most likely broken with the latest terra version, as there have been several major updates since then

**Comment by LoneDev6** [comment]
Make its developer aware @EVERYPLANET
