### ISSUE TITLE
[BUG] Items swap texutres

### ISSUE THREAD

**Issue by hepnoboi** [PluginBugs/Issues-ItemsAdder#884]
**Describe the bug**
Random items will swap textures with eachother. For example, Vehicles look exactly like furniture, and furniture looks exactly like vehicles. From what ive seen the items that swap textures seem to be diffirent depending on who you ask.

**To Reproduce**
1. Create a 1.16.5 PaperMC Server
2. Get the latest release of ItemsAdder and the required dependencies
3. Launch your server
4. Type /ia, and look untill you find an item that has a bugged texture

**Expected behavior**
Whats supposed to happen is that items have their normal texutres.

**Screenshots**
I already fixed the bug on my server (by downgrading itemsadder versions), and i no longer have access to screenshots.

**Info (please complete the following information):**
 - Server version: Paper 1.16.5
 - Client version: OptiFine 1.16.5
 - Plugin version: (example: 2.0.9 do not write "latest")

**Additional context**
If you downgrade to itemsadder 2.1.47 it fixes itself.

**Comment by LoneDev6** [comment]
Regenerate your resourcepack, it's not syncronized with the server.
https://itemsadder.plugin.ga/plugin-usage/resourcepack-hosting
