### ISSUE TITLE
[BUG] PlayerInteract & BlockBreak Events Errors.

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-ItemsAdder#889]
**Describe the bug**
Hi, when we break Custom Crops using Wheat, Berry bush or any other kind of plant, they're dropping their items and working ok but it's spamming my console with these errors.

**To Reproduce**
Example Item [here](https://paste.helpch.at/bixituhedu.bash)

Plant and farm multiple Crops

**Expected behavior**

[Errors](https://paste.helpch.at/igeyujiqix.sql)

 - Server version: ( paper 1.16.5 #670)
 - Client version: (Minecraft 1.16.5)
 - Plugin version: (2.3.7)

**Comment by LoneDev6** [comment]
Update to 2.3.7 and see if still happens.
Also make sure to read the items loading logs to check if any item failed to load
