### ISSUE TITLE
[BUG] pack size

### ISSUE THREAD

**Issue by 100petr** [PluginBugs/Issues-ItemsAdder#891]
**Describe the bug**
The /iainfo command displays a size of 50MB, although you write that from version 1.15 the size is to 100MB. https://itemsadder.plugin.ga/faq/resourcepack-not-loading#resourcepack-not-loading-i-get-an-error-in-chat
![image](https://user-images.githubusercontent.com/29830635/118302710-d8562700-b4e4-11eb-86f7-37ca56520b25.png)

**To Reproduce**
1. Type /iainfo
2. See pack size
![image](https://user-images.githubusercontent.com/29830635/118302808-f885e600-b4e4-11eb-9671-c15c50a7f992.png)

**Expected behavior**
The size will be displayed according to the server version or 100MB (according to bStats there are only 3 servers on version 1.14.4)

**Screenshots**
![image](https://user-images.githubusercontent.com/29830635/118302808-f885e600-b4e4-11eb-9671-c15c50a7f992.png)
![image](https://user-images.githubusercontent.com/29830635/118303117-5d414080-b4e5-11eb-9ca6-c5fbd7e4a547.png)

**Info (please complete the following information):**
 - Server version: purpur 1.16.5
 - Plugin version: 2.3.7

**Comment by WarrioR151** [comment]
Hello, Minecraft 1.19 allows you pack size 250mb, but /iainfo show 100, can also this ve fixed for 1.19?  (If Its just visual thing And i can use all 250mb, then Its good but if i can use 100mb, please fix 1.19 allows pack size 250mb thank in advance

**Comment by LoneDev6** [comment]
The bug is only visual. Will be fixed in 3.2.5 update.
Anyway please avoid answering old closed issues reports.
