### ISSUE TITLE
[BUG] ItemsAdder and RestrictedCreative

### ISSUE THREAD

**Issue by 100petr** [PluginBugs/Issues-ItemsAdder#892]
**Describe the bug**
Some ia blocks built in creative will drop out even though they shouldn't (restrictedcreative should prevent this)

**To Reproduce**
1. Install IA and RC
2. Place in creative for example mysterious ore (itemsadder) or banana tree leaves (forestry addon)
3. Destroy these blocks in survival.

**Expected behavior**
The blocks will not drop

**Screenshots**
![2021-05-14_19 28 01](https://user-images.githubusercontent.com/29830635/118307232-b1025880-b4ea-11eb-88d2-e8b371fbf02c.png)
![2021-05-14_19 28 37](https://user-images.githubusercontent.com/29830635/118307239-b2338580-b4ea-11eb-8098-c88e920aa98d.png)

**Info (please complete the following information):**
 - Server version: purpur 1.16.5
 - Client version: 1.16.5
 - Plugin version: 2.3.7
 - RC version: 2.4.8

**Additional context**
mysterious ore is REAL, banana tree leaves is REAL_TRANSPARENT, so it probably applies to these types

**Comment by LoneDev6** [comment]
you have to ask restricted creative dev to remove the air check, send them this message: https://github.com/PluginBugs/Issues-ItemsAdder/issues/866#issuecomment-836796376

**Comment by 100petr** [comment]
It should be fixed, thank you for your help.

**Comment by LoneDev6** [comment]
did the author push an update removing the AIR check?
if so, I can remove my hacky stuff from itemsadder
