### ISSUE TITLE
[Suggestion] Pumpkin Vision (if dont have)

### ISSUE THREAD

**Issue by danielzinh** [PluginBugs/Issues-ItemsAdder#893]
It would be very interesting to be able to modify the texture of the pumpkin when it's on the head (https://prnt.sc/12ywe7a) and make several personalized HUDS such as: blood on the screen

If it is already possible to create several custom screens with this, could you please explain to me how?

**Comment by LoneDev6** [comment]
You can't create more than one custom texture for the pumpkin, you would only be able to modify one.
`assets\minecraft\textures\misc\pumpkinblur.png`
