### ISSUE TITLE
[Suggestion] Adding support for custom clock

### ISSUE THREAD

**Issue by xalixilax** [PluginBugs/Issues-ItemsAdder#894]
**Is your feature request related to a problem? Please describe.**
When creating custom model for the clock, it is not possible to make it functional since the model that is created all use the same model instead using 64 models like the original model. I got it working with a texture pack pretty easily but because of the way the plugin work, I can't seem to be able to make it work. Since every predicate was pointing to the same model, I tried to make a model with only predicate pathing to the right model, but it didn't seems to work. (I got invisible texture)

**Describe the solution you'd like**
There is 3 solution that I could see to fix this issue. 

The first one would be to not overwrite the base model into minecraft/models/item/clock.json. Doing so would let us specify the path we want to use and would let us change the predicate (Lets say i only want to use "15min" increment)

The second option could be to create only one predicate to the new model with the customModelData. This way i am pretty confident we could manage all other predicate from there instead of having 64 all pathing to the same model. Still unsure if it would work properly. Might test later. If this work, this might be the best solution.

The third option could be to create multiple model into a folder (For convenience and avoid having duplicate name) to something like NAMESPACE:auto_generated/ITEMNAME/ITEMNAME_00 to ITEMNAME_64. I don't really like this option since I would be stuck with 64 models to use and could not downgrade to 12 if I wanted.

**Additional context**
Current reformated file that is generated containing a given model (CustomModelData:1) and autogenerated from a texture (customModelData:2) 
https://pastebin.com/edSiWRaU

What I would expect to get. This is a working example using a 3D model
https://pastebin.com/P7tyeKM0
![2021-05-16_00 54 32](https://user-images.githubusercontent.com/2474569/118385989-e047c100-b5e1-11eb-9467-f0170567fe34.png)
For testing purposes, I used the default clock as front texture for the block.

A working texture pack. You can get the clock with this command: /give @p clock{CustomModelData:1} 1
[3D clock.zip](https://github.com/PluginBugs/Issues-ItemsAdder/files/6488724/3D.clock.zip)

EDIT: After some testing, the option 2 doesn't seem to work for me. I might be wrong and made a dumb mistake but I don't think you can have overrides in an overrides. I only managed to get invisible or stuck texture (The default one stated into 
"textures":{
       "layer0":"item/clock_00"
    })
instead of the predicate one.

**Comment by LoneDev6** [comment]
ItemsAdder v2 allows you to manually edit the `clock.json` file so you can add your own rules as you would do with a normal resourcepack, this allows you to manage the pack manually and make this kind of customization.

You can also specify a `CustomModelData` for your item manually with the `model_id` property in your YML configuration for that item, also remember to set `generate: false` and specify the `model_path` for the first model of the custom clock.

Let me know if you need help, have a nice day
