### ISSUE TITLE
Bug after resource pack black screen

### ISSUE THREAD

**Issue by vdl19** [PluginBugs/Issues-ItemsAdder#896]
Hello, I have a bug for some time on the panels I did not understand why they erased themselves, then I discovered that if I made a co-inspect on it the writings came back, or if in player in the spawn I tried to break them without being able to do it once broken and given by worldguard automatically the text was there.
My son had the same problem but not on the same panel as me.
And I just found the culprit, it's when I connect and the ItemsAdder resource pack loads and more precisely when the resource pack makes the screen dark that's when the present panels are erased!

before the resource pack
![unknown](https://user-images.githubusercontent.com/80985545/118485708-091ea200-b719-11eb-8afd-c20c567c30e3.png)

just after the resource pack
![unknown2](https://user-images.githubusercontent.com/80985545/118485731-0fad1980-b719-11eb-9d37-a3b40b5c4c74.png)

Here I broke panels without having the authorization for the moment so they break and come back with the text
![unknown3](https://user-images.githubusercontent.com/80985545/118485758-176cbe00-b719-11eb-806a-8be333f3153e.png)

and to confirm that it is indeed the resource pack with the moment of the darkened screen I deactivated the resource pack and restarted the server several times and there no worries with the panels.
I'm on version 2.3.5 I didn't want to update for the moment and I didn't make a backup this morning.
And on Paper 1.16.5 #661

Small complement of information it is not only on the panels the concern I have just seen, it is also on the heads the bug:

![unknown4](https://user-images.githubusercontent.com/80985545/118485794-218ebc80-b719-11eb-846b-50c81351d0d9.png)

![unknown5](https://user-images.githubusercontent.com/80985545/118485808-25224380-b719-11eb-9520-3f8da539c7e7.png)

Is it possible to disable the dark/black screen during the loading of the resource pack? I did not see in the file

**Comment by LoneDev6** [comment]
thanks, this will be fixed
