### ISSUE TITLE
[Suggestion] Chaotic-animated font-pics mechanic

### ISSUE THREAD

**Issue by The-Gust** [PluginBugs/Issues-ItemsAdder#898]
Options to chaotic-animate your font-pics. As you know - you can create chaotic-animated (you can't control speed of this animation and order of frames) group of font-pictures (files from the same namespace) and "K" colorcode. It's work's fine everywhere, even in chat without updating it.

https://cdn.discordapp.com/attachments/777899330203025418/822150576536158248/bandicam_2021-03-18_20-38-17-657.gif

Just wanted to see it automatically with new options for font-pics mechanic like **chaotic-animations**, which one generate new group of frames in generated zip for animation, detects and automatically put "§K" to :example: or %img_example%, and doesn't allow to use frames directly, if it's enabled. Here's a code:

```
info:
  namespace: "animated-font"
chaotic-animations:
  example:     <- name of animated emoji for use ( :example: ) and frames namespace
    frames:                 <- frames (font-pics, which in use)
    - "example_frame1"
    - "example_frame2"
    - "example_frame3"
    block-frames: true         <- doesn't allow you to use frames directly, like :example_frame1:
font_images:
  example_frame1:          <- frames
    permission: 0
    show_in_gui: false
    path: "font/emoji/1.png"
    scale_ratio: 9
    y_position: 8
  example_frame2:
    permission: 0
    show_in_gui: false
    path: "font/emoji/2.png"
    scale_ratio: 9
    y_position: 8
  example_frame3:
    permission: 0
    show_in_gui: false
    path: "font/emoji/3.png"
    scale_ratio: 9
    y_position: 8
```
Thanks, bratan.

**Comment by atcpybd** [comment]
Can you pls tell me, how it works with only the resource pack?
