### ISSUE TITLE
[BUG] Texture not showing if the item is paper

### ISSUE THREAD

**Issue by Fantom250YT** [PluginBugs/Issues-ItemsAdder#900]
**Describe the bug**
It will show up as no texture, texture if the item/block is paper, this happens on the vanilla client, its fine on optifine.

**To Reproduce**
1. Use Vanilla MC Client
2. Have a item/block with a texture
3. You will see the item/block as the no texture, texture

**Expected behavior**
It will show up as the normal texture on Vanilla MC Client and not the no texture, texture.

**Screenshots**
<img width="272" alt="Screenshot 2021-05-18 at 20 38 12" src="https://user-images.githubusercontent.com/73852683/118713157-85001380-b819-11eb-8821-4bfb6e7ad127.png">

**Info (please complete the following information):**
 - Server version: 1.16.5 - Paper
 - Client version: 1.16.5 Vanilla / 1.16.4 Optifine
 - Plugin version: 2.2.7

**Additional context**
I've seen servers able to have paper as the item no problem, showing the texture properly before.

**Comment by LoneDev6** [comment]
Be sure to use IA 2.3.7.
Also check itemsadder logs and client logs (you can get them in %appadata%\.minecraft\logs\latest.log

**Comment by Fantom250YT** [comment]
https://bin.bloom.host/ohurewehog.sql

**Comment by LoneDev6** [comment]
please send it as file, page doesn't load

**Comment by LoneDev6** [comment]
` 'minecraft:paper#inventory' referenced from: minecraft:paper#inventory: v: Non [a-z0-9/._-] character in path of location: mineral:auto_generated/Cobalt_Ore`

rename your Cobalt_Ore to cobalt_ore.


https://itemsadder.plugin.ga/faq/resourcepack-not-loading#my-players-cant-see-textures-but-ive-followed-the-whole-tutorial
![immagine](https://user-images.githubusercontent.com/27242001/118972411-d0790580-b970-11eb-8212-992151cc5563.png)
