### ISSUE TITLE
ItemsAdder Kick On Resource Pack Deny Not Working

### ISSUE THREAD

**Issue by KolakZ** [PluginBugs/Issues-ItemsAdder#901]
**Describe the bug**
it still lets someone play even though he had resource packs turned off when it shouldn't because of the following settings on config.yml.
**apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: true**

**Expected behavior**
I expected the player to get kicked since he didn't load the resource pack.

**Info (please complete the following information):**
 - Server version: Tuinity 1.16.5
 - Client version: Vanilla 1.16.5
 - Plugin version: 2.3.7

**Comment by KolakZ** [comment]
Follow Up: Here is the ItemsAdder config.yml
https://pastebin.com/nNMS6MtG

**Comment by LoneDev6** [comment]
Can you try deleting (make a copy) the config.yml, use /iareload, update the url and use /iareload again?

**Comment by 100petr** [comment]
Don't you just have ia.resourcepack.bypasskick permission? It works for me. 
(can't load)
![image](https://user-images.githubusercontent.com/29830635/118780666-92a2b100-b88c-11eb-91d4-04069c775089.png)
(decline)
![image](https://user-images.githubusercontent.com/29830635/118780825-be259b80-b88c-11eb-86d0-3432321873c3.png)
IA 2.3.7

**Comment by KolakZ** [comment]
It worked, thanks
