### ISSUE TITLE
ItemsAdder Blocks Turning Into Note Blocks

### ISSUE THREAD

**Issue by KolakZ** [PluginBugs/Issues-ItemsAdder#902]
**Describe the bug**
When breaking blocks implemented by ItemsAdder, the surrounding blocks become note blocks.

**To Reproduce**
1. Place any ItemsAdder blocks
2. Start breaking them
3. This doesn't happen everytime but every so often so you might have to do step 1 and 2 a couple times before you can reproduce the bug

**Expected behavior**
I expected the block to break instead of turning the surrounding blocks into note blocks.

**Info (please complete the following information):**
 - Server version: Tuinity 1.16.5
 - Client version: Vanilla 1.16.5
 - Plugin version: ItemsAdder 2.3.7

**Additional context**
Here's a short clip of what's happening
https://drive.google.com/file/d/1Faw_UEQwWPm1KN2PHpr7IjtEdmDFlgrU/view?usp=sharing

**Comment by KolakZ** [comment]
Follow Up: Here are the server logs from when this happened...
[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/6510368/latest.log)

**Comment by LoneDev6** [comment]
Does this happens only in creative?
Test in survival and let me know

**Comment by KolakZ** [comment]
Just clarifying, by "testing in survival", do you mean to try breaking the blocks in survival mode?

**Comment by KolakZ** [comment]
I'll get back to you on that

**Comment by LoneDev6** [comment]
i'll reopen the issue once I get the requested info

**Comment by KolakZ** [comment]
I wasn't able to reproduce this issue in survival mode

**Comment by LoneDev6** [comment]
Creative mode sometimes ignores packets or predicts block changes, that's why I can't fix this issue, it's a Minecraft "bug" or better a feature, to optimize connection.

I hope you understand
