### ISSUE TITLE
[BUG] Mushroom Stem dupe

### ISSUE THREAD

**Issue by sxphirus** [PluginBugs/Issues-ItemsAdder#903]
**Describe the bug**

Mushroom blocks dupe when broken with silk touch

**To Reproduce**

1. Break mushroom with silk touch tool
2. 2 mushrooms drop

**Expected behavior**

Only one mushroom block drops

**Screenshots**
https://imgur.com/a/rNYXwlH

**Info (please complete the following information):**

 - Server version: Purpur 1.16.5
 - Client version: Vanilla 1.16.4
 - Plugin version: 2.3.7

**Additional context**

same bug as the noteblock silk touch dupe i reported on the discord a few months ago

**Comment by LoneDev6** [comment]
very strange.. I had to force drop to fix this bug: https://github.com/PluginBugs/Issues-ItemsAdder/issues/730

but now for some reason it's not needed, I will disable the fix
