### ISSUE TITLE
[BUG] Itemsadder spam Error saving region file

### ISSUE THREAD

**Issue by spedy55** [PluginBugs/Issues-ItemsAdder#904]
**Describe the bug**
Itemsadder have a problem when using with dungeonsXL because dungeonsXL have function when player started playing dungeon, dungeonsXL will create a new world and when player playing until end dungeonXL will delete the world, After that, Itemsadder ran into a problem with dungeonXL because it couldn't put a custom region, causing it to spam this error message like this https://pastebin.com/ix1bi2UD , can I fix it?

**To Reproduce**
1. Just Started dungeon
2. Play for a while
3. End of dungeon
4. Wait a minutes Itemsadder will spam this in console

**Expected behavior**
I hope Itemsadder can fix this spam because it's have many spam in my console

**Screenshots**
![image](https://user-images.githubusercontent.com/76065325/119014025-c3383700-b9c1-11eb-8784-0d0f76651e0a.png)

**Info (please complete the following information):**
 - Server version: Purpur 1.16.5 Git 1051
 - Client version: Optifine 1.16.5
 - Plugin version: 2.3.7 (lastes)

**Additional context**
if u want my logs please tell me, i'll upload to u but it's have size around 150MB

**Comment by spedy55** [comment]
and i have one question Itemsadder have close fucntion overwrite minecraft/font/default.json right ?
i cant write more anything font in default.json

**Comment by call911nowplz** [comment]
I am having the same issue!

**Comment by LoneDev6** [comment]
Thanks. this will be fixed
