### ISSUE TITLE
[Suggestion] Shop Compatibility

### ISSUE THREAD

**Issue by KolakZ** [PluginBugs/Issues-ItemsAdder#905]
It would be great to see compatibility with this plugin
https://www.spigotmc.org/resources/shop-a-simple-intuitive-shop-plugin.9628/

Basically, in the config it would allow you to set this as any ItemsAdder material/item
itemCurrencyName: "Emerald(s)"

This would be especially useful for making something from ItemsAdder the main currency.

**Comment by LoneDev6** [comment]
Hello, itemsadder has a free api every developer can use without owning the plugin, I suggest you to ask this plugin author to check it out: https://itemsadder.plugin.ga/developers/java-api

it's very easy to use
