### ISSUE TITLE
Cancel Break Wrong Tool [BUG] 

### ISSUE THREAD

**Issue by kozankun** [PluginBugs/Issues-ItemsAdder#908]
**Describe the bug**
Not sure if someone has already reported this or explained how to fix this but blocks can still be broken by axes even if the block has only pickaxe whitelisted. And I even enabled   cancel-break-wrong-tool:   enabled: true from the ItemsAdder config.

**To Reproduce**
1. /ia and grab a block from itemsadder. 
2. place the block
3. destroy it with an axe
4. no break cancel, and no block drop

**Expected behavior**
Block break event would be cancelled when you're using the tool that isn't in break_tool_whitelist

**Info (please complete the following information):**
 - Paper 1.16.5
 - Optifine 1.16.5
 - ItemsAdder 2.3.8

**Additional context**

Screenshots & video : 
![image](https://user-images.githubusercontent.com/84431345/119253014-c7429f80-bbe1-11eb-90fc-fe6a7b8ea888.png)
![image](https://user-images.githubusercontent.com/84431345/119253036-d45f8e80-bbe1-11eb-9f08-004d2bb35d0a.png)
https://youtu.be/nJr2hXnscJk

**Comment by LoneDev6** [comment]
Thanks, this will be fixed in the next release
