### ISSUE TITLE
gamemode keeps changing Every time i join the server to survival from Creative ⚠ 

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#909]
**Describe the bug**
gamemode keeps changing Every time i join the server to survival from Creative i think this problem comes after I update Paper for the last Version i tried to remove every plugin and test but it's Same **problem it's only comes from items-adder**
i thought the problem comes from multiverse-Core i removed and try without It but it's not | Same problem

**Screenshots-GIF**

https://i.imgur.com/yOqU8sw.mp4 | ( Watch the full Video )

**Info (please complete the following information):**
 - Server version: (git-Paper-622 MC: 1.16.5)
 - Client version: (vanilla 1.16.5)
 - Plugin version: (2.3.8)

**Comment by SNokerYT** [comment]
i Discovered Where this problem Come from it's not from Paper | it's come from black-screen and hide-hud When I Disabled them the problem is Fixed ( it's bug 💢 )
```
    black-screen: false
    hide-hud: false
```

**Comment by SNokerYT** [comment]
Also Plugin screeneffect Have the same issue

**Comment by SNokerYT** [comment]
this Command i used | /screeneffect fullscreen BLACK 1 1 1 freeze SLoKerYT | after that i will not be able to do /gm 1 anymore I have to type gamemode 2 and than type gamdmode 1
![dwaawdawdwda](https://user-images.githubusercontent.com/68678154/119278961-f7f9f780-bc28-11eb-95d8-f141ad1625a7.gif)

**Comment by LoneDev6** [comment]
Will be fixed in the next update
