### ISSUE TITLE
[Bug] This need fix, it's not normal!

### ISSUE THREAD

**Issue by TheKlimoT** [PluginBugs/Issues-ItemsAdder#911]
![изображение](https://user-images.githubusercontent.com/26817853/119280846-df470d00-bc3b-11eb-856a-69941bd5e919.png)

Fix crafting.

**Comment by kozankun** [comment]
modify the recipe from the .yml file

**Comment by TheKlimoT** [comment]
> 
> 
> modify the recipe from the .yml file

Well, take it and create separate patterns for crafting yourself, it should be optimized.

**Comment by LoneDev6** [comment]
You have to create two recipes, one for the left and one for the right, this can't be automated without making the plugin recipes loading heavy on CPU.
