### ISSUE TITLE
soul problem

### ISSUE THREAD

**Issue by vdl19** [PluginBugs/Issues-ItemsAdder#912]
**Describe the bug**
Hello, I already talked about my problem on the "general-french" but they could not find a solution. 
My problem is from the beginning with the Add-On "[Mobs] CreaturesPlus - ItemsAdder addon 0.1".
I have the "brush_stooge" that spawns well, I even increased its rate and added a loot by taking what was done for the "Soul".
But I never managed to have the "Soul" spawn in the worlds.
The soul egg works.
I also tried to remove the Soul configuration and to modify the brush_stooge configuration so that it spawns the Soul in its place and it worked fine but of course I didn't have a brush_stooge anymore.
My goal is to be able to have the "Soul" spawn by itself like the "brush_stooge" does.
I also did another thing, I made a copy of the configuration of the "brush_stooge" by changing just the references to the Soul so the name etc. but there by cons never could make it spawn!
I also tested with the QuentiumYT settings but nothing either.
So what I would like is that it Spawn but like "brush_stooge" that I can make it less spawning if I want but not the limit of light and current time, because even by putting at midnight often nothing at all! I tried in caves without light a little also but I did not see either.
Did I miss something?
Thanks
----------------------------------------------
QuentiumYT — 20/05/2021
items:
  soul:
    enabled: true
    display_name: display-name-soul
    permission: creaturesplus
    click_in_ia_gui: false
    lore:
      - lore-1-soul
      - lore-life-soul
      - lore-2-soul
      - lore-3-soul
      - lore-4-soul
      - lore-5-soul
      - lore-6-soul
      - lore-7-soul
      - lore-8-soul
    resource:
      generate: false
      material: POTION
      model_path: "mob/soul/soul"
    behaviours:
      mob:
        ai: HUSK
        hit_color: ff7e7e
        max_health: 40
        lock_head_rotation:
          y: 0
        animation:
          attack: soul_attack
          walk: soul_walking
        # potion_effects:
         # SLOW_FALLING:
           # type: SLOW_FALLING
           # amplifier: 100
           # duration: 9999999
        replace_mobs_spawn:
          mob1:
            type: ZOMBIE
            spawn_another: true
            reason: NATURAL
            chance: 100
            # max_sky_light: 0
            # time:
              # start: MIDNIGHT
  soul_walking:
    display_name: soul_walking
    permission: creaturesplus
    show_in_ia_gui: false
    resource:
      generate: false
      material: POTION
      model_path: "mob/soul/walking"
  soul_attack:
    display_name: soul_attack
    permission: creaturesplus
    show_in_ia_gui: false
    resource:
      generate: false
      material: POTION
      model_path: "mob/soul/attack"
Here is what worked to get the "Soul" instead of the "brush_stooge :

 info:
  namespace: creaturesplus
items:
  brush_stooge:
    enabled: true
    display_name: display-name-brush_stooge
    permission: creaturesplus
    click_in_ia_gui: false
    lore:
      - lore-1-soul
      - lore-life-soul
      - lore-2-soul
      - lore-3-soul
      - lore-4-soul
      - lore-5-soul
      - lore-6-soul
      - lore-7-soul
      - lore-8-soul
    resource:
      generate: false
      material: POTION
      model_path: "mob/soul/soul"
    behaviours:
      mob:
        ai: SILVERFISH
        baby: true
        hit_color: ff7e7e
        max_health: 50
        lock_head_rotation:
          y: true
        animation:
          walk: soul_walking
        replace_mobs_spawn:
          mob1:
            type: ZOMBIE
            spawn_another: true
            reason: NATURAL
            chance: 80
            time:
              start: NOON
              end: MIDNIGHT
  brush_stooge_walking:
    display_name: soul_walking
    permission: creaturesplus
    show_in_ia_gui: false
    resource:
      generate: false
      material: POTION
      model_path: "mob/soul/walking"
And the message from QuentiumYT telling me that he can't do anything for me :wink:

**To Reproduce**

**Info (please complete the following information):**
 - Server version: paper 1.16.5#726 (same with all versions for at least 6 months 1.16.4 .....)
 - Plugin version:  2.3.8 (same with all versions for at least 6 months)
 - [Mobs] CreaturesPlus - ItemsAdder addon 0.1

**Additional context**
The worry is on the natural spawn of the Soul only that I never had, I can make them spawn with the eggs but that's all.

**Comment by LoneDev6** [comment]
Thanks! I will fix this in the next update
