### ISSUE TITLE
[BUG] invisible blocks when door is opened

### ISSUE THREAD

**Issue by darkdragon0226** [PluginBugs/Issues-ItemsAdder#913]
there is a bug with new blocks that when placing a door and it is opened by the player, the new blocks that are above become invisible, when it is opened with redstone this does not happen only when a player opens it with right click
![Minecraft_ 1 16 5 - Multijugador (servidor de terceros) 2021-05-23 21-15-48](https://user-images.githubusercontent.com/84732793/119378756-3bce1a80-bc84-11eb-8ee8-38c8e6110460.gif)

paper-1.16.5-715
itemsadder version 2.3.8

**Comment by SNokerYT** [comment]
i have the same issue too, on a difference server | 
![door-problem](https://user-images.githubusercontent.com/68678154/119443239-8bb2ed00-bd29-11eb-80ff-4898c6dae833.gif)

**Comment by LoneDev6** [comment]
I don't think I can fix this without making the server laggy as I'd have to resent the blocks packets continously as the client predicts block changes which I have to revert.
Sadly Minecraft predicts a lot of stuff and having to revert the changes is a pain for the CPU.
