### ISSUE TITLE
light furniture problem 🕯💡

### ISSUE THREAD

**Issue by SNokerYT** [PluginBugs/Issues-ItemsAdder#915]
**Describe the bug**
When you Place light furniture like a candle and put another block next to it the light will gone

**Screenshots**
![light-problem](https://user-images.githubusercontent.com/68678154/119443604-2c091180-bd2a-11eb-92ac-c9b34d8cdd63.gif)

**Info (please complete the following information):**
 - Server version: (Paper-720)
 - Client version: (1.16.5)
 - Plugin version: (2.3.9)

**Comment by LoneDev6** [comment]
Hello,
sadly it's a bug of the LightApi, you have to ask the other author to fix this bug, I already tried asking but they didn't fix it.
https://www.spigotmc.org/resources/lightapi-fork.48247/

it may not be possible, I have no idea on how they spawn light.

Thanks for the patience
