### ISSUE TITLE
[Suggestion] player_head item texture create easy

### ISSUE THREAD

**Issue by Rirbe** [PluginBugs/Issues-ItemsAdder#916]
**Is your feature request related to a problem? Please describe.**

The head database is not compatible.

**Describe the solution you'd like**

I want to make the texture of player_head easy.

**Describe alternatives you've considered**

Could you add headdatabase compatibility? I want to make an item using player_head comfortably. 

**Additional context**

https://minecraft-heads.com/

**Comment by LoneDev6** [comment]
Basically your feature request is:
adding a way to create custom heads with custom texture not using a resourcepack but simply using the heads skin?

in ItemsAdder, right?

**Comment by SirCraftypants** [comment]
They basically want to use PLAYER_HEAD as the Material of an Item but with the ability to have the custom head design of any custom head on https://minecraft-heads.com/

**Comment by LoneDev6** [comment]
I have to reject the feature request, if you want to use custom texture you have to create a custom texture directly in the pack.
It has no sense to use heads textures as itemsadder offers custom texturing for items
