### ISSUE TITLE
[BUG] Error with FAWE

### ISSUE THREAD

**Issue by MinecollYT** [PluginBugs/Issues-ItemsAdder#917]
**Describe the bug**
When replacing itemsadder blocks with minecraft ones and then breaking them the itemsadder block drops

**To Reproduce**
1. Place itemsadder blocks (TILE)
2. Using FAWE to replace them 
3. Break the replaced blocks

**Expected behavior**
Dropping the normal ones

**Info (please complete the following information):**
 - Server version: Paper 1.16.5
 - Client version: LabyMod 1.16.5
 - Plugin version: 2.3.9

**Additional context**
Maybe check if the block is really an itemsadder block

**Comment by MinecollYT** [comment]
Doesn't work when a player has haste 255 btw

**Comment by SirCraftypants** [comment]
Did you true the Gravity attribute, setting it to False?

**Comment by LoneDev6** [comment]
Hello, sadly I can't fix the FAWE / WorldEdit addon as I've tried multiple times to get in touch with the WorldEdit developers without any help so far, they are not interested into supporting this type of custom blocks plugins.

I hope you understand, thanks
