### ISSUE TITLE
SQUID > [Mobs] IAMobs - ItemsAdder addon 0.1.1 

### ISSUE THREAD

**Issue by vdl19** [PluginBugs/Issues-ItemsAdder#919]
**Describe the bug**
Hello, I reported you the bug with the Soul mob of the addon "Creature plus" which did not spawner alone despite all the try of adjustments that I could make, since the update it is perfect a very big thank you I love this mob and not to see it spawner alone annoyed me enormously.
I also have since the beginning the problem with the Addon "[Mobs] IAMobs - ItemsAdder addon 0.1.1" that I had not left on my server ! The Squid doesn't spawn alone either even when set to 100% maybe it's the same problem as for Creature plus. I tried again this morning I put the addon back and set to 100% but nothing, the eggs work fine but I would like to have the light squid spawn alone.
Thanks  

**Info (please complete the following information):**
 - Server version: Paper 1.16.5#735 (but the same since 1.16.4)
 - Plugin version: 2.3.9 (but the same since I have ItemsAdder within 6 months I think)

**Comment by LoneDev6** [comment]
I should have fixed all the custom mobs spawning problems in 2.3.9, are you sure the squid is not spawning based on the settings?
https://www.spigotmc.org/resources/%E2%9C%85must-have%E2%9C%85-itemsadder%E2%9C%A8custom-items-huds-guis-mobs-3dmodels-emojis-blocks-wings-hats-liquids.73355/update?update=404200
> fixed custom mobs of the same type not registered correctly (soul for example)

**Comment by vdl19** [comment]
Good evening, for the Souls no more worries they are there since 2.3.9 it's perfect, but the Squid I still have not seen one spawning by itself. I'm going to reinstall it from 0 tomorrow, I have players on the server and I don't want to bother them. And I'll go back to see if I can find any. 
good evening

**Comment by vdl19** [comment]
Hello, I just did the tests so I can say more about the problem.
I put the octopus at 100% for the test.
- They still do not spawn naturally I walked far enough but still normal octopuses.
- But there is a change with the octopus minecraft eggs (not the AI addon eggs), when I use them they give me 100% light octopus, if I want a normal octopus now I have to do the command /summon minecraft:squid
So no natural spawn of the octopus but the eggs of Minecraft take their settings like there at 100%

**Comment by vdl19** [comment]
Hello, I finally managed to get them but not without doing anything like the Soul I think there is a problem with the mobs.yml files of the add-ons it was not only in IA the problem.
QuentiumYT gave me its configurations, I note mine that I modified and that work.
I had problems for the mobs.yml file of squids, when it finally worked on my test server I just copy/paste it on my game server and nothing to do no squid while everything was identical (server recopied in full!), the restart did not change anything the /iareload either, the /iazip crash me the resourcepack on the test server so I did not try on the game server I changed the chances from 80 to 70 made /reload and there it worked then put back to 80% ok changed again OK!

Translated with www.DeepL.com/Translator (free version)

**Comment by vdl19** [comment]
info:
  namespace: creaturesplus
items:
  soul:
    enabled: true
    display_name: display-name-soul
    permission: creaturesplus
    click_in_ia_gui: false
    lore:
      - lore-1-soul
      - lore-life-soul
      - lore-2-soul
      - lore-3-soul
      - lore-4-soul
      - lore-5-soul
      - lore-6-soul
      - lore-7-soul
      - lore-8-soul
    resource:
      generate: false
      material: POTION
      model_path: "mob/soul/soul"
    behaviours:
      mob:
        ai: HUSK
        hit_color: ff7e7e
        max_health: 50
        lock_head_rotation:
          y: 0
        animation:
          attack: soul_attack
          walk: soul_walking
        # potion_effects:
         # SLOW_FALLING:
           # type: SLOW_FALLING
           # amplifier: 100
           # duration: 9999999
        replace_mobs_spawn:
          mob1:
            type: ZOMBIE
            spawn_another: true
            reason: NATURAL
            chance: 70
            time:
              start: NOON
              end: MIDNIGHT
  soul_walking:
    display_name: soul_walking
    permission: creaturesplus
    show_in_ia_gui: false
    resource:
      generate: false
      material: POTION
      model_path: "mob/soul/walking"
  soul_attack:
    display_name: soul_attack
    permission: creaturesplus
    show_in_ia_gui: false
    resource:
      generate: false
      material: POTION
      model_path: "mob/soul/attack"
  brush_stooge:
    enabled: true
    display_name: display-name-brush_stooge
    permission: creaturesplus
    click_in_ia_gui: false
    lore:
      - lore-1-brush_stooge
      - lore-life-brush_stooge
      - lore-2-brush_stooge
      - lore-3-brush_stooge
      - lore-4-brush_stooge
    resource:
      generate: false
      material: POTION
      model_path: "mob/brush_stooge/brush_stooge"
    behaviours:
      mob:
        ai: SILVERFISH
        baby: true
        hit_color: ff7e7e
        max_health: 40
        lock_head_rotation:
          y: true
        animation:
          walk: brush_stooge_walking
        replace_mobs_spawn:
          mob1:
            type: ZOMBIE
            spawn_another: true
            reason: NATURAL
            chance: 70
            time:
              start: NOON
              end: MIDNIGHT
  brush_stooge_walking:
    display_name: brush_stooge_walking
    permission: creaturesplus
    show_in_ia_gui: false
    resource:
      generate: false
      material: POTION
      model_path: "mob/brush_stooge/walking"
loots:
  mobs:
    soul:
      type: HUSK
      metadata:
        ItemsAdderMob:
          name: "ItemsAdderMob"
          value: "creaturesplus:soul"
          type: "string"
      items:
        LEATHER:
          item: EMERALD
          min_amount: 1
          max_amount: 3
          chance: 30
        SLIME_BALL:
          item: SLIME_BALL
          min_amount: 1
          max_amount: 2
          chance: 100
    brush_stooge:
      type: SILVERFISH
      metadata:
        ItemsAdderMob:
          name: "ItemsAdderMob"
          value: "creaturesplus:brush_stooge"
          type: "string"
      items:
        LEATHER:
          item: EMERALD
          min_amount: 1
          max_amount: 2
          chance: 30
        SLIME_BALL:
          item: SLIME_BALL
          min_amount: 1
          max_amount: 2
          chance: 100

**Comment by vdl19** [comment]
[mobs (creaturesplus).txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/6602297/mobs.creaturesplus.txt)
[mobs (iamobs).txt](https://github.com/PluginBugs/Issues-ItemsAdder/files/6602299/mobs.iamobs.txt)

**Comment by LoneDev6** [comment]
Seems I made a mistake back in the day.
Default glow squid configuration was set to make it spawn only using vanilla eggs and not naturally.
Now this works fine:
```yml
        replace_mobs_spawn:
          mob1:
            type: SQUID
            spawn_another: true
            reason: NATURAL
            chance: 60
            time:
              start: NIGHT
              end: MIDNIGHT
```
Thanks for the help.
