### ISSUE TITLE
[BUG] ItemsAdder autodisabled

### ISSUE THREAD

**Issue by Lonewolfi** [PluginBugs/Issues-ItemsAdder#923]
**(My English is not very well,so the following is from Google Translate)**
**Describe the bug**
Do I have to use the latest version of this plugin? This error did not occur before you updated 2.3.9. It may be a coincidence.
The plugin will be automatically uninstalled after 30 minutes of activation.
I have turned off the update check in config.yml.

**Info (please complete the following information):**

Server version: Paper 1.16.5
Plugin version: 2.3.8

[ItemsAdder/WARN]: java.lang.IllegalThreadStateException: InitializationException
[ItemsAdder/WARN]: 	at dev.lone.itemsadder.k.b.a.a.class.a(a:80)
[ItemsAdder/WARN]: 	at dev.lone.itemsadder.b.x.class.a(a:502)
[ItemsAdder/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ItemsAdder/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[ItemsAdder/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[ItemsAdder/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[ItemsAdder/WARN]: 	at dev.lone.itemsadder.e.d.class.a(a:775)
[ItemsAdder/WARN]: 	at dev.lone.itemsadder.Core.OtherPlugins.d.c.class.a(a:906)
[ItemsAdder/WARN]: 	at dev.lone.itemsadder.Core.f.a.m.class.a(a:456)
[ItemsAdder/WARN]: 	at dev.lone.itemsadder.k.j.b.class.a(a:695)
[ItemsAdder/WARN]: 	at dev.lone.itemsadder.b.u.class.a(a:342)
[ItemsAdder/WARN]: 	atcom.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[ItemsAdder/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[ItemsAdder/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[ItemsAdder/WARN]: 	at java.lang.Thread.run(Unknown Source)
[ItemsAdder/INFO]: [ItemsAdder] Disabling ItemsAdder v2.3.8
[ItemsAdder/INFO]: [ItemsAdder] Saving custom entities...
[ItemsAdder/INFO]: [ItemsAdder] Saved 0 custom entities successfully!

**Comment by LoneDev6** [comment]
Please open a ticket on my discord server, thanks.
