### ISSUE TITLE
[BUG] Can't Drink Cup of Water

### ISSUE THREAD

**Issue by ErtuLord** [PluginBugs/Issues-ItemsAdder#924]
Hello, 
I recently bought ItemsAdder plugin for my server. First times I was able to drink cup of water but then I can't drink it even i'm op. I invited my friend to test it, he couldnt drink it either. So its not filling thirsty bar. Please help..

**Comment by LoneDev6** [comment]
Please don't erase the issue template, provide all the asked information.
Thanks
