### ISSUE TITLE
[Suggestion] Permission to interact with a specific furniture

### ISSUE THREAD

**Issue by NessunoMC** [PluginBugs/Issues-ItemsAdder#925]
Add the possibility to set up a permission to interact with a specify block or furniture (like with the trading machine).
For example, adding the permission on "behaviours:" or on "events:".

**Comment by LoneDev6** [comment]
Will be added in the next update:
https://itemsadder.devs.beer/plugin-usage/adding-content/advanced/item-properties/events/actions#actions-permission
