### ISSUE TITLE
[BUG] FoV doent change when running

### ISSUE THREAD

**Issue by XavierConX** [PluginBugs/Issues-ItemsAdder#926]
**Describe the bug**
Sometimes, after loading the texture pack on join, the game glitches in some way that makes the FoV not change when running (You still run since you can see the particles). You can fix it by relogging or changing gamemodes.

**To Reproduce**
Cant tell how to reproduce it, since it happens at random.

**Expected behavior**
FoV changing when running, without having to change gamemode nor relogging.

**Info (please complete the following information):**
 - Server version: Spigot 1.16.4
 - Plugin version: v2.3.8

**Comment by LoneDev6** [comment]
Will be fixed, thanks
