### ISSUE TITLE
[错误]No permissions

### ISSUE THREAD

**Issue by MCSakuralove** [PluginBugs/Issues-ItemsAdder#933]
My Server work on paper-1.16.3, plugin version is 2.3.9,  permissions plugin: Groupmanager
But there is a problem. I gave the player the required permissions. After the player enters /ia to open the menu, only one modules [ALL] are seen, there is only something in them. What is going on?
![%ZVDBK`NOEQ}EKD3I3}D{ S](https://user-images.githubusercontent.com/58717873/120467778-17381800-c3d3-11eb-9b89-677f989dab17.png)
![image](https://user-images.githubusercontent.com/58717873/120467869-2d45d880-c3d3-11eb-8d7f-a06979db8bfb.png)

**Comment by MCSakuralove** [comment]
[you don't have permissions!]
![MDS4Q)B4IDJ(XVWK AYGNMD](https://user-images.githubusercontent.com/58717873/120468252-97f71400-c3d3-11eb-8514-21fd5caf204e.png)

**Comment by LoneDev6** [comment]
I suggest you to avoid using GroupManager as it doesn't support a lot of plugins.
luckperms is the best one and works fine
