### ISSUE TITLE
[BUG] Corrupted region data error after /iareload

### ISSUE THREAD

**Issue by Venterok** [PluginBugs/Issues-ItemsAdder#934]
**Describe the bug**
After each /iareload, chunks are moved to the _corrupted ' folder. Full server reboots don't help.

**To Reproduce**
1. put a couple of custom blocks in front of you
2. run /iareload
3. blocks are now regular mushrooms and note blocks
4. See error on console https://mcpaste.io/8996cc1511d0dbbb

**Info (please complete the following information):**
 - Server version: Purpur 1.16.5 git-Purpur-1061
 - Client version: Optifine 1.16.5
 - Plugin version: ItemsAdder 2.3.9
 - ItemsAdder Config.yml: https://pastebin.com/ngQvb1W4
 - latest.log: https://mcpaste.io/c3cf8640653dca16
 
**Additional context**
This happens every time, which is why you have to regenerate the world, as the chunk break down because of this problem

**Comment by Homosanians** [comment]
reproducible

**Comment by LoneDev6** [comment]
> 
> 
> reproducible

Are you too using Purpur?

I tried and I can't reproduce the issue.
Fast placed 2-3 blocks, instantly sent /iareload and no corruption happened.
I will try to reproduce the issue again but I suspect it's another cause

**Comment by LoneDev6** [comment]
I think:
- a region file is corrupted some time ago
- you run /iareload
- itemsadder tries to load the region file and reports the error.


iareload is not the cause of the corruption, that's what I think, because reason is in the log:
Corrupted region data! Copying it into '_corrupted' folder. **Loading NBT data**

**Loading NBT data** not saving.

So the server may have been killed, force stopped or something else happened hours before the /iareload command

**Comment by Venterok** [comment]
No, we specifically tried to shut down the server correctly so that this did not happen, we did not kill it. Only /stop and / restart

**Comment by LoneDev6** [comment]
1. No error about corrupted chunks on startup?
2. Is there any other player breaking blocks while you use /iareload?
3. Are you calling the block api methods while you use /iareload?

Anyway if 2 or 3 are true I'd advice not to call iareload while someone is playing the game, do your configurations on a secondary server (local server), then push the changes on night when no one is playing (like every admin usually do, or at least that's what I do)

**Comment by Venterok** [comment]
None of the above happens during /iareload. the server is completely empty, and there are no plugins using the api at this time on the server

**Comment by LoneDev6** [comment]
This is very strange.
I literally followed the instructions and I can't reproduce the issue, I even tried placing blocks very fast while using /iareload command with no result
> 1. put a couple of custom blocks in front of you
> 2. run /iareload
> 3. blocks are now regular mushrooms and note blocks
> 4. See error on console https://mcpaste.io/8996cc1511d0dbbb


My server: `This server is running Paper version git-Paper-704 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)`
