### ISSUE TITLE
[BUG] Furniture isn´t solid ERROR (Please)

### ISSUE THREAD

**Issue by TeiBri** [PluginBugs/Issues-ItemsAdder#935]
** Describe the bug **
In items_pack, I normally have solid = true for the chair, but when I turn on the server and place the chair, it reports an error  and https://pastebin.com/f4Gwnh0L you can walk through the chair.

** To Reproduce **
1. Go to 'server'
2. Click on 'on the ground and I place a stool'
3. See error in console

** Info (please complete the following information): **
  - Server version: 1.16.5 spigot
  - Client version: 1.16.5 vanilla
  - Plugin version: 2.3.9

** Additional context **
This thing does not work in plugin version 2.3.8 too. Please I haven't seen the same problem anywhere, what am I doing wrong?

The furniture.yml:
info:
  namespace: tiktoknews
recipes:
  crafting_table:
items:
  stool:
    display_name: Malá židle
    permission: stool
    lore:
    - ':new: &7Nový obsah'
    resource:
      material: LEATHER_HORSE_ARMOR
      generate: false
      model_path: furniture/stool1
    behaviours:
      furniture:
        gravity: false
        fixed_rotation: false
        small_hitbox: false
        solid: true
      furniture_sit:
        sit_height: 0.9

**Comment by LoneDev6** [comment]
Thanks this will be fixed in the next update.
anyway in the mean time if you use Paper you won't have this issue.
