### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by colhaydutu** [PluginBugs/Issues-ItemsAdder#937]
hide_item is dont work on ia_gui.yml

i wanna hide some items in all item menu but i can not

example code:

categories:
  all:
    enabled: true
    icon: "itemsadder:ruby_block"
    name: display-category-all
    show_all_items: true
    hide_items:
      - mcicons:icon_left_grey
      - "mcicons:icon_left_blue"
      - "mcicons:icon_right_grey"
      - "mcicons:icon_right_blue"
      - "mcicons:icon_up_grey"
      - "mcicons:icon_up_blue"
      - "mcicons:icon_next_white"
      - "mcicons:icon_next_orange"
      - "mcicons:icon_back_white"
      - "mcicons:icon_back_orange"
      - "mcicons:icon_cancel"
      - "mcicons:icon_confirm"
      - "mcicons:icon_lock"
      - "mcicons:icon_unlock"
      - "mcicons:icon_web"
      - "itemsadder:light_blue_coupon"
      - "itemsadder:turquoise_coupon"
      - "itemsadder:purple_coupon"
      - "itemsadder:green_coupon"
      - "itemsadder:red_coupon"
      - "itemsadder:black_coupon"
      - "itemsadder:white_coupon"
      - "itemsadder:golden_coupon"
      - "itemsadder:blue_ring"
      - "itemsadder:light_blue_ring"
      - "itemsadder:turquoise_ring"
      - "itemsadder:purple_ring"
      - "itemsadder:green_ring"
      - "itemsadder:red_ring"
      - "itemsadder:black_ring"
      - "itemsadder:white_ring"
      - "itemsadder:golden_ring"
      - "itemsadder:marriage_ring"

**Info :**
 - Server version: paper 1.16.5
 - Client version: fabric 1.16.5
 - Plugin version:  2.3.7

**Comment by LoneDev6** [comment]
update itemsadder before reporting issues, thanks

anyway you can't hide items from ALL category.
ALL category will show all items that a player has permission to see.
`ia.user.ia.* `
https://itemsadder.devs.beer/plugin-usage/permissions/example-permissions
