### ISSUE TITLE
[BUG] When in a backpack inventory, you can't hotkey any items

### ISSUE THREAD

**Issue by EvanBl** [PluginBugs/Issues-ItemsAdder#940]
**Describe the bug**
When in a backpack inventory, you can't hotkey any items
**To Reproduce**
1. Open an epic back pack ITEM (I have not tested the command inventory for this bug)
2. Try to hotkey any item in your inventory, it just cancels the event

**Expected behavior**
I expected hotkeys to work while in the backpack inventory

**Screenshots**
https://youtu.be/VQyhvQ29HxE

**Info (please complete the following information):**
 - Server version: (example: paper 1.15.2)
 - Spigot 1.12.2
 - Client version: (example: fabric 1.15.2)
 - Optifine 1.12.2
 - Plugin version: (example: 2.0.9 do not write "latest")
 - 1.3.4

**Additional context**

**Comment by LoneDev6** [comment]
this seems to be not a suggestion for itemsadder.
use the correct github.
I suspect it's a suggestion for backpacks plugin:
https://github.com/PluginBugs/Issues-EpicBackpacks/issues

thanks
