### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by EvanBl** [PluginBugs/Issues-ItemsAdder#941]
**Is your feature request related to a problem? Please describe.**
There's an option in the config where you can disable whether or not you want your item backpacks to be storable in ender chests, which means both EMPTY and FILLED backpacks cannot be put in ender chests
**Describe the solution you'd like**
I would like EMPTY backpacks to be storable in ender chests, but FILLED backpacks to not be storable in ender chests
**Describe alternatives you've considered**
None
**Additional context**

**Comment by LoneDev6** [comment]
this seems to be not a suggestion for itemsadder.
use the correct github.
I suspect it's a suggestion for backpacks plugin: 
https://github.com/PluginBugs/Issues-EpicBackpacks/issues

thanks
