### ISSUE TITLE
[BUG] Problem with / iazip on my resourcepack (it partial breaks it)

### ISSUE THREAD

**Issue by Yukylyu** [PluginBugs/Issues-ItemsAdder#943]
**Describe the bug**
Hi, I love your ItemsAdder plugin and more specifically this option which Protect resourcepack from unzip, however I have a problem with the /iazip, which partly breaks my resourcepack and the gameplay it is associated with (it breaks the visual of my custom blocks made with mushrooms…).
When the option (disable-REAL-behaviour__DISABLE_AT_YOUR_OWN_RISK as well as disable-REAL_TRANSPARENT-behaviour__DISABLE_AT_YOUR_OWN_RISK) is deactivated it systematically overwrites the file brown_mushroom_block.json, mushroom_stem.json and red_mushroom_block.json of the blockstates folder by them of default ItemsAdder resourcepack; and when activated, it completely deletes these files… No matter what tests I have performed, it cannot keep the modifications that we can do (and that we have done) to these files specific to our texture pack. 
It should at least that don’t delete them when the option is deactivated (or make sure not to modify it when these files are detected, a bit like you did with the pack.mcmeta file which keeps the modifications do to it) because this problem prevents me from using this great protection system by breaking the additions that I have done with the mushroom blocks…
Thanking you in advance for your help and your response.

**Info **
 - Server version: 1.16.5
 - Client version: 1.16.5 vanilla
 - Plugin version: 2.3.9

**Comment by LoneDev6** [comment]
Hello,
I don't get why you want to disable the custom blocks behaviour and expect itemsadder to keep the blockstate files even if the feature is disabled.
It's an intended behaviour and I can't disable this without getting complains of other customers confused on why their blockstate files are still there even if the feature is disabled (I already got complains about that).

If you want to use itemsadder custom blocks you have to keep the option enabled
