### ISSUE TITLE
Why Do The World Edit Developers Hate Fixing Bugs?

### ISSUE THREAD

**Issue by KingOwnageXV** [PluginBugs/Issues-ItemsAdder#944]
[Here's an example of people reaching out to support custom blocks, no interest from WE developers](https://github.com/PluginBugs/Issues-ItemsAdder/issues/917#issuecomment-855744207) 

They also pointed out that most servers don't run on 1.12.2 [here.](https://github.com/EngineHub/WorldEdit/issues/1773#issuecomment-857299602) Although that is technically true its misleading since there are so many small / amateurs servers that may opt to run on the latest version of minecraft just because but a lot of really big servers use 1.12 because they want to use the latest plugins, blocks and minecraft features without the terrible performance any update past 1.12 introduces. Logic suggest this should be considered, but if you care about quantity over quality then sure just drop support for a plugin that's broken. At that point don't release the plugin at all if you're willing to leave it in a broken state any time a new update releases.

Don't bother responding with a half assed answer I'm turning off notifications on this github thread.

**Comment by LoneDev6** [comment]
> Don't bother responding with a half assed answer I'm turning off notifications on this github thread.
I'm always kind, this time I'll follow your suggestion, I'll ignore that.
I've pointed out multiple times why I can't fix the worldedit problems and wasted a lot of hours trying to bypass that crap plugin incompatibilities to deliver a solution, with no success and no collaboration from the worldedit team.

Have a nice day

**Comment by LoneDev6** [comment]
Also I don't quite understand the purpose of this message, this is not the worldedit team github, "Why Do The World Edit Developers Hate Fixing Bugs?" is the title of this issue report and guess what? I'm not a worldedit team member and I have no answer for your question.
