### ISSUE TITLE
[Suggestion] update from minecraft 1.17 pls

### ISSUE THREAD

**Issue by MrJorman** [PluginBugs/Issues-ItemsAdder#947]
update from minecraft 1.17 pls

**Comment by 100petr** [comment]
And do you have specific problems at 1.17? What does not work?

**Comment by LoneDev6** [comment]
![image](https://user-images.githubusercontent.com/27242001/121858564-0bafef80-ccf7-11eb-8a18-0f3f173405c4.png)

**Comment by MrJorman** [comment]
sry bro, you banned me from your ds SERVER, I CRACKEDLIX
