### ISSUE TITLE
[BUG] Can't remove furnitures in creative mode

### ISSUE THREAD

**Issue by SirGlozz** [PluginBugs/Issues-ItemsAdder#949]
**Describe the bug**
If we try to remove a furniture in creative mode, we can't, the model stays in the site, if we have a solid furniture we can break the barriers but the model stays. In survival mode there are no problems.

**To Reproduce**
1. Switch to creative mode
2. Place a furniture
3. Try to remove it (in creative mode)
4. We can't remove the armorstand with the model

**Expected behavior**
I think it's not a big bug, we can't remove furnitures in creative mode but we can in survival mode

**Info (please complete the following information):**
 - Server version: Paper 1.14.4
 - Client version: Forge 1.14.4
 - Plugin version: 2.3.11

**Additional context**
Hope we can have a fix soon, thanks

**Comment by LoneDev6** [comment]
Thanks, this will be fixed
