### ISSUE TITLE
Disconnect when click a Custom Block [BUG] 

### ISSUE THREAD

**Issue by HeadsShot** [PluginBugs/Issues-ItemsAdder#951]
**Describe the bug**

Whenever me or my players tried to click on any custom block from Ore, any kind of ingot blocks when you right click it just disconnect you from the server without any error logs

**To Reproduce**
1. Get any ore or ingot blocks 
2. Right Click on the blocks
3. Disconnected
4. No Error Logs

**Expected behavior**

My friend was testing a custom block that was defaultly added onto itemsadder when my friend tried it just disconnect him from the server and i was not expecting this to happened i tried everything nothing works

**Screenshots**

i can show you a video of it
Link: https://imgur.com/a/AhsmCTP

**Info (please complete the following information):**
 - Paper 1.16.5 #775 build
 - Optifine/Vanilla 1.16.5
 - Plugin version: 2.3.12

**Additional context**

**Comment by LoneDev6** [comment]
If you're using bungeecord update it.
If it still doesn't work use Waterfall
