### ISSUE TITLE
[BUG] onPacketReceiving(PacketEvent)

### ISSUE THREAD

**Issue by Schwi-Dol** [PluginBugs/Issues-ItemsAdder#952]
**Describe the bug**
I don't really know what it is or how it happens, but I came to report!

**To Reproduce**

Idk :/

**Expected behavior**

N/A

**Screenshots**

https://pastebin.com/Ce2du7F5.

**Info (please complete the following information):**
 - Server version: paper 1.16.5
 - Client version: 1.16.5
 - Plugin version: 2.3.10

**Comment by LoneDev6** [comment]
Update the plugin when reporting errors
