### ISSUE TITLE
[Suggestion] Add fuel that returns items after burn.

### ISSUE THREAD

**Issue by Dkavila** [PluginBugs/Issues-ItemsAdder#953]
Is your feature request related to a problem? Please describe.
- I want to create a fuel that returns an item after burn.

Describe the solution you'd like
- Something like the Lava Bucket that returns an Empty Bucket after burn.

**Comment by Dkavila** [comment]
I have created the fuel solicitation as well and want to add this feature to the implemented fuel system.

**Comment by LoneDev6** [comment]
I don't think this is very easy to implement without introducing duplication bugs.
I'm afraid I cannot add this particular feature, I hope you understand
