### ISSUE TITLE
[BUG] problems with solid blocks

### ISSUE THREAD

**Issue by Ronglito** [PluginBugs/Issues-ItemsAdder#955]
**Describe the bug**
I updated to the latest version of itemsadder last night and all of the solid furniture items I have in the server is no longer solid even when it has the solid option on

**To Reproduce**
install the latest version of itemsadder

**Expected behavior**
when I walk to a solid item I shouldn't be able to move thru it

**Screenshots**
https://ibb.co/2nCzLZn

**Info (please complete the following information):**
 - Server version: paper 1.16.5
 - Client version: fabric 1.16.5
 - Plugin version: 2.3.12

**Comment by LoneDev6** [comment]
It's impossible, ItemsAdder is not removing barrier blocks on its own.
Probably an admin or another plugin replaced all the barrier blocks in the area.

**Comment by Ronglito** [comment]
im not saying itemsadder is removing berrier blocks its just that the custom furnitures i added to the server that were solid like tables are no longer solid and that happened when I updated and now I did a rollback to the old version of itemsadder and its fixed
so it is something in itemadder causing this

**Comment by LoneDev6** [comment]
Did you try to update to 2.4.0?

**Comment by Ronglito** [comment]
im gonna wait for all the plugins I'm using to update to java 16 so I can update all at once so ill try it then and see what happends
