### ISSUE TITLE
[BUG] multiverse-core and itemsadder

### ISSUE THREAD

**Issue by 100petr** [PluginBugs/Issues-ItemsAdder#956]
**Describe the bug**
If I have created a flat world via Multiverse-Core, the search magnifier does not work.

**To Reproduce**
1. Install IA (LoneLibs, ProtocolLib, etc) and Multiverse-Core
2. Create a flat world (/ mv create flatroom normal -t flat)
3. Open /ia and try the search magnifier
4. the sign opens and closes immediately
There is no error in the log.

**Expected behavior**
The search sign will remain

**Screenshots**
https://user-images.githubusercontent.com/29830635/122600184-b31e8080-d06f-11eb-9bbf-ce73f61a3f0b.mp4

**Info (please complete the following information):**
 - Server version: Purpur 1.16.5
 - Client version: optifine 1.16.4 & vanilla 1.16.5 
 - Plugin version: 2.3.12
 - MV version: 4.2.3-SNAPSHOT-b845

**Additional context**
I think Jirsaacek (former admin) once wrote to you with a similar problem. Only today did his successor notice that its related to the type of world (probably)
![image](https://user-images.githubusercontent.com/29830635/122603018-05fa3700-d074-11eb-81e0-2a0ecc09f843.png)

**Comment by LoneDev6** [comment]
I can't find the cause of this nor reproduce the issue, works fine on a flat world for me
