### ISSUE TITLE
[BUG]  PlayerResourcePackStatusEvent

### ISSUE THREAD

**Issue by KolakZ** [PluginBugs/Issues-ItemsAdder#959]
**Describe the bug**
I keep getting kicked from my server and it is saying the following in console.
https://pastebin.com/GhYW1pdU

**Expected behavior**
I expected to be able to play on the server without any errors.

**Info (please complete the following information):**
 - Server version: Purpur 1.16.5
 - Client version: Lunar Client 1.16.5
 - Plugin version: ItemsAdder 2.3.12

**Comment by LoneDev6** [comment]
Did you kick the player during login?
Did it disconnect during login?

**Comment by KolakZ** [comment]
It got fixed when I updated to `2.4.0`.
