### ISSUE TITLE
[BUG] BreakBlockEvent on damaging Barrier blocks (Survival)

### ISSUE THREAD

**Issue by zhenghanlee** [PluginBugs/Issues-ItemsAdder#960]
**Describe the bug**
ItemsAdder seems to directly/indirectly fire **BlockBreakEvent** when player is only damaging blocks of type `Material.BARRIER` in survival mode, and it is un-cancelled.

**To Reproduce**
1. Create a sample plugin to register both BlockBreakEvent and BlockDamageEvent:
```
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.block.BlockBreakEvent;
import org.bukkit.event.block.BlockDamageEvent;
import org.bukkit.plugin.java.JavaPlugin;

public final class Plugin extends JavaPlugin implements Listener {
    @Override
    public void onEnable() {
        getServer().getPluginManager().registerEvents(this, this);
    }

    @EventHandler
    public void onBarrierBreak(BlockBreakEvent evt) {
        getServer().getLogger().info("BlockBreakEvent triggered, cancelled: " + evt.isCancelled());
    }

    @EventHandler
    public void onBarrierDamage(BlockDamageEvent evt) {
        getServer().getLogger().info("BlockDamageEvent triggered, cancelled: " + evt.isCancelled());
    }
}
```
2. Start the server and game.
3. Enter survival mode and attack a barrier block.
4. See log on console.

**Expected behaviour**
Attacking Barriers blocks in survival should only fire **BlockDamageEvent**, which can be verified with ItemsAdder plugin removed.

**Screenshots**
![Screenshot 2021-06-20 at 11 01 29 AM](https://user-images.githubusercontent.com/75558451/122660802-e881b600-d1b6-11eb-9819-569bdedecde6.png)

**Info (please complete the following information):**
 - Server version: Spigot 1.16.5
 - Client version: Optifabric 1.16.5
 - Java version: 16
 - Plugin version:
    - ItemsAdder: 2.3.12
    - LoneLibs: 1.0.9
    - LightAPI: 3.4.6
    - ProtocolLib: 4.6.1-SNAPSHOT-b505

**Additional context**
I inferred this issue from the CustomShop plugin, which works fine with ProtocolLib, LightAPI, LoneLib, but not when ItemsAdder is added. I have a handler each for both BlockBreakEvent (creative) and BlockDamageEvent (survival) for breaking shops, but whenever ItemsAdder is added, I can insta-break shops in survival, without exceptions/error.
I got a temporary workaround by checking for player's game-mode.

**Comment by LoneDev6** [comment]
I sincerely don't understand what do I have to do nor if I can fix this. You may have to keep your workaround since I can't edit my method.
BlockBreakEvent is fired when I want to check if the player can break a block in a particular location or not.
A lot of other plugins use this similar method:
```java
    public static boolean canBreak(Block block, Player player)
    {
        if(block.getType() == Material.AIR)
            return false;
        FakeBlockBreakEvent b = new FakeBlockBreakEvent(block, player);
        b.setDropItems(false);
        Bukkit.getServer().getPluginManager().callEvent(b);
        return !b.isCancelled();
    }
```
