### ISSUE TITLE
[Suggestion] Add custom block effect to skript api

### ISSUE THREAD

**Issue by MinecollYT** [PluginBugs/Issues-ItemsAdder#961]
**Is your feature request related to a problem? Please describe.**
Yes, I can't use custom blocks in all of my script events

**Describe the solution you'd like**
Add a custom block effect like the already existing custom item one

**Describe alternatives you've considered**
e.g. 
set block at player to custom block "ruby_ore"

**Comment by LoneDev6** [comment]
Not highly requested so I close
