### ISSUE TITLE
[BUG] crashed 1.17 server

### ISSUE THREAD

**Issue by GitJhopa** [PluginBugs/Issues-ItemsAdder#964]
server core: Tuinity 1.17
datapack 1.17: caves up to -60 m high

my config itemsadder: https://pastebin.com/XWsu9e0J
crash server: https://pastebin.com/AUjWUhQH

**Comment by LoneDev6** [comment]
Datapacks with custom height are not supported.
They also are not supported by other Spigot plugins, I'm not the only one.

I hope you can be patient for a future update

**Comment by GitJhopa** [comment]
Well, how can the same be done so that the ores can spawn up to -60 height? please do it.

**Comment by GitJhopa** [comment]
Can you make it so that the ores can spawn at a height of 0 to -60 as well? If so, I will be very grateful to you, because I can not run my server without this feature, thank you, you are the best.

**Comment by LoneDev6** [comment]
> 
> 
> Well, how can the same be done so that the ores can spawn up to -60 height? please do it.

Mojang developers clearly stated that the new features are not meant to be used until 1.18, so you should really wait before using the custom world height datapacks

**Comment by LoneDev6** [comment]
Anyway I'll allow negative min height values in the next update hoping it doesn't create other issues
