### ISSUE TITLE
[BUG] 1.17 Could not pass event ChunkUnloadEvent to ItemsAdder v2.4.0

### ISSUE THREAD

**Issue by Wolfbros** [PluginBugs/Issues-ItemsAdder#965]
**Describe the bug**
When flying around the world this error (https://pastebin.com/9Jc9y6KE) sometimes appears in the console. 

**To Reproduce**
1. Create new world
2. Load new chunks
3. unload chunks

**Expected behavior**
No error message in the console.

**Info (please complete the following information):**
 - Server version: spigot 1.17
 - Client version: vanilla 1.17
 - Plugin version: latest

**Additional context**
The error:
https://pastebin.com/9Jc9y6KE

**Comment by LoneDev6** [comment]
use the command /version and send me the output.
"spigot 1.17" is not enough, plugin works fine in the version I used to develop.

**Comment by Wolfbros** [comment]
I updated spigot to version: This server is running CraftBukkit version 3159-Spigot-f773da8-887bc05 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) and get this error: https://pastebin.com/QWfVT0Am

**Comment by 100petr** [comment]
maybe it's related https://pastebin.com/0ryGzVhw

**Comment by LoneDev6** [comment]
Update LibsDisguises and ProtocolLib

**Comment by 100petr** [comment]
![image](https://user-images.githubusercontent.com/29830635/123673843-36469000-d841-11eb-88d4-053b2dc20d16.png)

**Comment by LoneDev6** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/29830635/123673843-36469000-d841-11eb-88d4-053b2dc20d16.png)

I'll follow this advice and publish a new update
