### ISSUE TITLE
[Suggestion] Possibility to overcame tool limitations

### ISSUE THREAD

**Issue by GuazP** [PluginBugs/Issues-ItemsAdder#966]
**Is your feature request related to a problem? Please describe.**
This is not related to any problem.

**Describe the solution you'd like**
For example, I wanted to make a tool like multi-tool. As this I choosed Hammer, which of course is based on pickaxe to keep correct mining speed, but despite of that, I would like to give it properties of axe to disable shields and sword swing ability.
Idk if that's possible due to minecraft limitations. Also control which enchantments could be added via enchanting table or books would be nice to give this weapon sweeping edge, fire aspect, sharpness and so on.

Second thing possibly related, is to change weapon attributes when hit player/air, recharged for specific period of time. This could finaly make pickaxe more like real weapon danger - deadly damage, but if stuck in mobs body, attackspeed should drop a lot for specific time, then be rewersed (because when hit air, it doesn't took so long to draw weapon out, generally pickaxe is very deadly when it comes to penetrate armored targets).

**Describe alternatives you've considered**
Doesn't apply

**Additional context**
Doesn't apply

**Comment by LoneDev6** [comment]
I think this can be implemented with a separate addon because of how detailed and complex this feature request is, it won't fit ItemsAdder purpose.
