### ISSUE TITLE
[Suggestion] Additional armor points display

### ISSUE THREAD

**Issue by GuazP** [PluginBugs/Issues-ItemsAdder#968]
**Is your feature request related to a problem? Please describe.**
Generally minecraft allows to scale armor up to 30, armor toughness up to 20. Additionally to thirst, mana or other future features, itemsAdder is around custom items itself, and even with built-in ItemsAdder armors this is possible to maintain over 20 armor by attributes, but minecraft displays it up to 20. 

**Describe the solution you'd like**
In my opinion, it would be nice if ItemsAdder got built-in or addon to display armor up to its real limit (like with thirst), and finally show what's missing - armour toughness.

**Describe alternatives you've considered**
It could be very hard to code armor at left side, because of additional hearts from Absorption effect from golden apple, and ability to control max_health via items as well... But right side is fine to go with it, or left side just next to quick access bar like with mana.

**Additional context**
Example where it could be placed, left one fill more like it in my opinion: (additional 10 armour icons
![image](https://user-images.githubusercontent.com/33330881/122898361-1992ef80-d34b-11eb-823c-0634797860bf.png)

As example: 
First column (or last, whatever feels more correct) for armor exceeding 20 to 30 (in this example it shouldn't because armor bar isn't filled, but that's just photoshop to show concept)
Second and third column, for armour toughness with minecraft cap limit up to 20. (with slightly different color, or even own different icon, that's just concept.)
![image](https://user-images.githubusercontent.com/33330881/122899679-50b5d080-d34c-11eb-90c5-1c679f40d9bd.png)

**Comment by YouHaveTrouble** [comment]
Issue here is in minecraft an entity cannot benefit from more than 20 armor. It's limited within internal calculation and it's not simple to change the math responsible for that even on a software fork level. Even if the value was uncapped, having 30 armor would literally cause player to take 0 damage, as it would grant 100% damage reduction (normally you get up to 79% damage reduction before  toughness calculation and it scales linearly).

**Comment by LoneDev6** [comment]
This is a cool feature and can be implemented with an addon (Java + resourcepack).
I sadly don't have the time to investigate and find the complexity of this task, but surely someone can do that in the future.

@YouHaveTrouble noticed the first problem of this idea for example, so for now I can't develop this feature.
Thanks for the idea tho

**Comment by GuazP** [comment]
> Issue here is in minecraft an entity cannot benefit from more than 20 armor. It's limited within internal calculation and it's not simple to change the math responsible for that even on a software fork level. Even if the value was uncapped, having 30 armor would literally cause player to take 0 damage, as it would grant 100% damage reduction (normally you get up to 79% damage reduction before toughness calculation and it scales linearly).

@YouHaveTrouble I totally disagree. Please check minecraft wiki before talking nonsense.
1. Armor attribute is capped at 30 for player attributes, I checked manually and it really gives additional protection.
2. Protection from armor is capped to 80% by formula to calculate armor protection in minecraft: 
`dmg*(1- min(20, max(armor/5, armor-dmg / (armorToughness /4 + 2)))/25)=dmg_after_armor_reduction`

If you want to know how it behaves, and how many dmg it'll reduce, you can look at this excel: 
https://docs.google.com/spreadsheets/d/17P4FXlBkDxUp8fWWF8ZTyhkTATuzcJb-MkXgoqqjKe8/edit?usp=sharing

From my manual testing, it really shows correct values for armor above 20 + specific armor toughness attribute.

Please reconsider suggestion :)

**Comment by LoneDev6** [comment]
I'll keep this in my todo list, for now this task is not so easy to be implemented and it will require an addon.
You may try to ask on my Discord server community channel to see if a Java dev can take this task and make an addon, since ItemsAdder has an easy to use API.

Thanks
