### ISSUE TITLE
[BUG] Can't break ores

### ISSUE THREAD

**Issue by Wolfbros** [PluginBugs/Issues-ItemsAdder#969]
**Describe the bug**
Place an ItemsAdder ore and break it. Then the error message (https://pastebin.com/ZmszqbwT) apperas and you get kicked.

**To Reproduce**
1. /ia & klick on ores (creative)
2. Get one ore in your inventory  (creative)
3. Place it  (creative)
4. Break it (survival)

**Expected behavior**
No kick on block break.

**Info (please complete the following information):**
 - Server version: spigot 1.17
 - Client version: vanilla 1.17
 - Plugin version: latest

**Additional context**
Error message: https://pastebin.com/ZmszqbwT

**Comment by LoneDev6** [comment]
use the command /version and send me the output.
"spigot 1.17" is not enough, plugin works fine in the version I used to develop.

Also try to update bungeecord or change it to waterfall, another user reported a similar issue in the past and was a bungeecord bug.

**Comment by Wolfbros** [comment]
Thank you waterfall fixed the problem (the newest BungeeCord doesn't).

**Comment by LoneDev6** [comment]
Thanks for the information, this issue is very strange and doesn't happen with normal Spigot or using Waterfall so I suspect it's a Bungeecord bug.

Have a nice day!
