### ISSUE TITLE
[BUG] Could not pass event PrepareAnvilEvent to ItemsAdder v2.4.0 org.bukkit.event.EventException: null

### ISSUE THREAD

**Issue by taka1945** [PluginBugs/Issues-ItemsAdder#970]
**Describe the bug**
got this error to 1.17 spigot

**Info (please complete the following information):**
 - Server version: spigot 1.17
 - Plugin version: 2.4.0

[22:17:42] [Server thread/ERROR]: Could not pass event PrepareAnvilEvent to ItemsAdder v2.4.0
org.bukkit.event.EventException: null

https://pastebin.com/AY0u6gdR

**Comment by LoneDev6** [comment]
This is not the full log and I can't identify the cause of this
