### ISSUE TITLE
[BUG] Trees spawn in water 

### ISSUE THREAD

**Issue by yebanme** [PluginBugs/Issues-ItemsAdder#971]
**Describe the bug**
Trees are found in the water on the generated map 

**Info (please complete the following information):**
 - Server version: 3159-Spigot-f773da8-887bc05 (MC: 1.17)
 - Client version: fabric 1.17
 - Plugin version: 2.4.0

![image](https://user-images.githubusercontent.com/20102749/122950225-dec2a300-d3ae-11eb-9df1-27d94154baaa.png)

**Comment by LoneDev6** [comment]
Should be fixed in the next update, thanks
