### ISSUE TITLE
[BUG] The plugin recognizes the mushrooms generated in the world as custom blocks 

### ISSUE THREAD

**Issue by yebanme** [PluginBugs/Issues-ItemsAdder#972]
**Describe the bug**
Use data packets to generate the world, which is recognized as a custom block in naturally generated mushrooms 

**To Reproduce**
1. Use data pack [Overhauled Overworld](https://www.planetminecraft.com/data-pack/william-wythers-caves-and-cliffs-add-on-for-overhauled-overworld-1-17/)
2. Run the server 
3. Find the brown mushroom in the underground cave 

**Info (please complete the following information):**
 - Server version: 3159-Spigot-f773da8-887bc05 (MC: 1.17)
 - Client version: fabric 1.17
 - Plugin version: 2.4.0

![image](https://user-images.githubusercontent.com/20102749/123110807-024d2280-d46f-11eb-8d99-bd09888c2e58.png)

**Comment by LoneDev6** [comment]
This statement this wrong:
> The plugin recognizes the mushrooms generated in the world as custom blocks 

it's only a visual glitch, ItemsAdder won't make these block drop the custom block.

Read here to avoid this:
https://itemsadder.devs.beer/faq/blocks-minerals-issues/custom-blocks-glitch-texture/glitched-blocks-in-some-areas-custom-worlds
