### ISSUE TITLE
[Suggestion] Adding crafting recipe support to adding?

### ISSUE THREAD

**Issue by VOIDDERtm** [PluginBugs/Issues-ItemsAdder#973]
**Is your feature request related to a problem? Please describe.**
No, its a additional function needed to use/
**Describe the solution you'd like**
Will recipe support be added? So that JEI mods and the like are displayed? And adding to recipe book.

**Describe alternatives you've considered**
Plugin MmoItems use MythicLib to adding resipe support, and this recipe can see in recipe book and if use mod JER (or similar)

**Additional context**
![image](https://user-images.githubusercontent.com/79021022/123140263-c199dd00-d45f-11eb-88c5-adf3a78c12f5.png)

**Comment by LoneDev6** [comment]
The question is not really clear.
Anyway I can't add recipes to the Minecraft recipe books because of a duplication bug Mojang didn't fix.

Here are other pages about it.
#6
#665
#330
