### ISSUE TITLE
[BUG] Blocks Dropping Noteblocks Instead of Correct Custom Blocks

### ISSUE THREAD

**Issue by ocyt** [PluginBugs/Issues-ItemsAdder#974]
**Describe the bug**
Custom ores/blocks dropping noteblocks instead of the custom block. (This is happening with the default ores/blocks)

**To Reproduce**
1. Find mysterious ore
2. Mine
3. Noteblock drops instead of mysterious ore

**Expected behavior**
Custom blocks to drop

**Info (please complete the following information):**
 - Server version: Purpur version git-Purpur-1157 (MC: 1.16.5)
 - Client version: Vanilla 1.16.5
 - Plugin version: 2.3.10

**Additional context**
N/A

**Comment by LoneDev6** [comment]
Update the plugin to the latest version before opening issue reports
