### ISSUE TITLE
[BUG] Permissions not working properly anymore

### ISSUE THREAD

**Issue by ocyt** [PluginBugs/Issues-ItemsAdder#975]
**Describe the bug**
Default permissions not working correctly anymore. To view all items in /ia, to view all categories, etc.

**To Reproduce**
1. Add * permissions to group/player
2. Type /ia
3. All categories and items dont show up

**Expected behavior**
All the items and categories to show up/permissions to work properly like they did previously before the 2.3.11 or 2.3.12 update. (Permissions work fine on 2.3.10)

**Screenshots**
N/A

**Info (please complete the following information):**
 - Server version: Purpur version git-Purpur-1157 (MC: 1.16.5) 
 - Client version: Vanilla 1.16.5
 - Plugin version: 2.3.12

**Additional context**
N/A

**Comment by LoneDev6** [comment]
Are you sure that reverting to 2.3.10 permissions work fine?
I can't find any change in the code about permissions from 2.3.10 to 2.4.0
