### ISSUE TITLE
[BUG] onPacketReceiving(PacketEvent)

### ISSUE THREAD

**Issue by Schwi-Dol** [PluginBugs/Issues-ItemsAdder#976]
**Describe the bug**
I don't really know what it is or how it happens, but I came to report! again...

**To Reproduce**
Idk :/

**Expected behavior**
N/A

**Screenshots**
https://pastebin.com/w1PK4DFL console log
https://prnt.sc/16jk6l0 print

**Info (please complete the following information):**
 - Server version: paper 1.16.5
 - Client version: 1.16.5
 - Plugin version: 2.4.0

**Additional context**
I can't say why it happens, but even updating the version as the dev said the problem persists

**Comment by LoneDev6** [comment]
Seems a player is trying to break a block removed from itemsadder configurations, so the plugin can't recognize it and throws this error.
I'll publish an update that will make unrecognized blocks drop without throwing this error
