### ISSUE TITLE
[BUG] Kick doesn't work on recent version

### ISSUE THREAD

**Issue by GuazP** [PluginBugs/Issues-ItemsAdder#977]
**Describe the bug**
I just updated 3 days ago ItemsAdder, and earlier option `'kick-player-on-decline: true'` worked just as desired, now it doesn't work at all.

**To Reproduce**
1. Change in config: `kick-player-on-decline` to `true`
2. Login and decline resourcepack.
3. Server doesn't kick you.

**Expected behavior**
It should just kick.

**Screenshots**
Doesn't apply

**Info (please complete the following information):**
 - Server version: purpur 1.16.5
 - Client version: Optifine + Forge with mods [xaenial minimap and inventory hud]
 - Plugin version: 2.3.12
 I know there is up 2.4.0 now, but I have few days to official start of server, and 2.4.0 crashes out when I tried to use it.... And generally I have a lot more scripts and other stuff to do instead of getting new issue right now. I'll be back to update issue when I find time.

**Additional context**
Doesn't apply.

**Comment by LoneDev6** [comment]
Check if you have the permission `ia.resourcepack.bypasskick`

**Comment by GuazP** [comment]
Ah, yea. That's the case, sorry for wasteing your time.
