### ISSUE TITLE
[Suggestion] Add allowed-break property to furniture/placed items

### ISSUE THREAD

**Issue by chrismwiggs** [PluginBugs/Issues-ItemsAdder#978]
**Is your feature request related to a problem? Please describe.**
Not a specific problem, but a nice way to extend custom blocks in a survival world. 

**Describe the solution you'd like**
It would be a property that would let you set a (maybe default mc) item that is allowed to break a placed furniture. For example, I make a custom chair (furniture) and want to make it so you can only break/pick it back up with a wooden axe. 

The use case came up from a player suggestion to create "training dummies"; furniture placed that you can attack but won't die/break when hit, but when you hit it with a specific item, it allows you to damage/break it. Essentially to allow unbreakable armor stands, but have some way to pick them back up so they're not stuck in the world forever.

**Comment by LoneDev6** [comment]
I think this can be easily implemented making a Java addon.
You have to intercept the `EntityDamageByEntityEvent` and cancel it when you want to avoid the furniture to be dropped.

It should work fine.
