### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by userrrrr-69** [PluginBugs/Issues-ItemsAdder#981]
i cant join server with custom txt beacouse error show up

i join server 
click yest do downlad texturepack 
error showup and kick me from server

![image](https://user-images.githubusercontent.com/80201005/123507753-76541a00-d66b-11eb-8307-e85d110aa7f4.png)

i know that server version is 1.16.5
but its all

**Comment by 100petr** [comment]
Can you send a log? Do you have a resource-pack host set up? https://itemsadder.devs.beer/first-install

**Comment by userrrrr-69** [comment]
[09:44:58] [Worker-Cape-11/ERROR]: Couldn't download http texture: java.net.SocketTimeoutException: connect timed out

**Comment by LoneDev6** [comment]
You erased the issue template, a lot of info is missing and I can't identify the issue.
Anyway reading the last message you sent I can suspect it's due to a misconfiguration of the resourcepack url, be sure to follow the first install tutorial, there is even a video step by step
