### ISSUE TITLE
[BUG] music disc

### ISSUE THREAD

**Issue by 100petr** [PluginBugs/Issues-ItemsAdder#982]
**Describe the bug**
IA musics discs in jukebox do not work 

**To Reproduce**
1. Place jukebox
2. Try inserting a IA music disc into jukebox
3. See error https://pastebin.com/bSVa4FYF

**Expected behavior**
IA music discs will be inserted to the jukebox and no error occurs

**Info (please complete the following information):**
 - Server version: purpur 1.17
 - Client version: optifine 1.17
 - Plugin version: 2.4.0

**Comment by LoneDev6** [comment]
Will be fixed
