### ISSUE TITLE
[BUG] 1.17 Run Error

### ISSUE THREAD

**Issue by Comhrai-McNicholl** [PluginBugs/Issues-ItemsAdder#983]
**Describe the bug**
When ItemsAdder is loaded into the server it's not sending out any Error packets or error returns into the console, it seems to load in perfectly fine on 1.17 - But once you're in-game you're able to detect the bugs running the `/ia` command in-game opens up the menu and the images of the blocks are everywhere on the screen and some of the blocks do not match the images that are inside of the /ia menu. The plugin seems to have an Issue with all of the UTF-8 codes such as ":smile:, :wave:, :joy:", etc. They'll either show an entirely different image or return no image at all. 

**Screenshots**
I've a few screenshots of the menu, chat issues and the block menu being different - If you take a look at this album you're able to see the screenshots; https://imgur.com/a/pKe08SM

**Info (please complete the following information):**
 - Server version: paper 1.17 (#48)
 - Plugin version: ItemsAdder 2.4.0

**Comment by Comhrai-McNicholl** [comment]
Just an addition, the server is running paper spigot 1.17 the latest of right now (# 48); I also run 1.16.5 paper and the plugin does the same thing so it's a Java 16 issue in the plugin

**Comment by 100petr** [comment]
Have you tried /iareload and /iazip?

**Comment by LoneDev6** [comment]
Follow the installation tutorialm you need to regenerate your resourcepack and host it (using dropbox or self hosting)
