### ISSUE TITLE
[BUG] kicked when hiting on ia blocks

### ISSUE THREAD

**Issue by Schwi-Dol** [PluginBugs/Issues-ItemsAdder#984]
**Describe the bug**
when you hit some ia block in a certain position or place, it gives an error and kites you from the server

**To Reproduce**
hit an ia block and you will fall and get this message [here](https://prnt.sc/170pjoq)

**Expected behavior**
break a block

**Screenshots**
minecraft screen: [here](https://prnt.sc/170pjoq)
video: [here](https://youtu.be/h3cpKwR3owY)

**Info (please complete the following information):**
 - Server version: 1.16.5
 - Client version: 1.16;5
 - Plugin version: 2.4.0

**Additional context**
nothing appears in the log when this event occurs, you're just kitted 
log: [here](https://prnt.sc/170pzad)

**Comment by LoneDev6** [comment]
Read more here:
https://github.com/PluginBugs/Issues-ItemsAdder/issues/969
https://github.com/PluginBugs/Issues-ItemsAdder/issues/951
https://github.com/PluginBugs/Issues-ItemsAdder/issues/875
