### ISSUE TITLE
[BUG] itemfame broken furniture

### ISSUE THREAD

**Issue by KigITS** [PluginBugs/Issues-ItemsAdder#986]
**Describe the bug**
Smash blocks in item frames and separate objects, see video.
I updated all the latest plugins.

**Expected behavior**
broken furniture

**Screenshots**
https://www.youtube.com/watch?v=iP0tvX4NBl8

**Info (please complete the following information):**
 - Server version:  paper 1.16.5
 - Client version: optifine-1.16.5
 - Plugin version: 2.4

**Additional context**
I've already reported it in Discord.

**Comment by LoneDev6** [comment]
paper 1.16.5 doesn't mean anything, I need the version obtained form /version command.

Anyway this doesn't happen on my server, I just tested.
Consider updating ProtocolLib, Paper and also try to update to ItemsAdder 2.4.1 (upcoming)
