### ISSUE TITLE
[BUG] 1.17 not accepting BUNDLE material

### ISSUE THREAD

**Issue by zhenghanlee** [PluginBugs/Issues-ItemsAdder#990]
**Describe the bug**
`/iazip` fails for items' materials set to `BUNDLE`. Changed all material to `PAPER` and all works fine.

**To Reproduce**
1. Create a simple add-on yml with an item of material `BUNDLE`
2. Run `iazip` on server console
3. See error
4. Change material to `PAPER`
5. Error gone

**Expected behavior**
ItemsAdder to support materials of the server's version.

**Screenshot**
![Screenshot 2021-06-29 at 5 42 17 PM](https://user-images.githubusercontent.com/75558451/123776257-b46a6b80-d901-11eb-982a-5cc59dce664f.png)

**Info:**
 - Server version: (spigot 1.17)
 - Client version: (Not Applicable)
 - Plugins version:
   - ItemsAdder (v2.4.1)
   - ProtocolLib (v4.7.0-SNAPSHOT-b526)
   - LoneLibs (v1.0.12)

**Additional context**
Adding ItemsAdder compatibility for ColorBundles plugin.

**Comment by LoneDev6** [comment]
Will be fixed, thanks
