### ISSUE TITLE
[BUG] dupe 2.3.12

### ISSUE THREAD

**Issue by SolarPepper** [PluginBugs/Issues-ItemsAdder#992]
in build 2.3.12, you can dupe furniture through the frames in 2.3.9 everything is ok
[https://www.youtube.com/watch?v=iO18FRRJ08A](url)

**Comment by LoneDev6** [comment]
Update the plugin

**Comment by SolarPepper** [comment]
the dupe runs on 2.4.2 :c

**Comment by LoneDev6** [comment]
Thanks, this will be fixed as noted in this other report
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1004
