### ISSUE TITLE
[BUG] Death message spam

### ISSUE THREAD

**Issue by jurajplayercze** [PluginBugs/Issues-ItemsAdder#993]
**Describe the bug**
When player dies, it just spams the chat with same death message. When we had not itemsadder, it was fine. I tried to restart server, disable many plugins, but it still doing it

**To Reproduce**

**Expected behavior**

**Screenshots**
https://images2.imgbox.com/e8/26/R3ofluyl_o.png

**Info (please complete the following information):**
 - Server version:  Spigot 1.17 Build 3164, development
 - Client version: 1.17
 - Plugin version: 2.4.2

**Additional context**

**Comment by LoneDev6** [comment]
How is this related to ItemsAdder?
