### ISSUE TITLE
[Suggestion] Add 1.17 item "filled" predicate for bundles

### ISSUE THREAD

**Issue by zhenghanlee** [PluginBugs/Issues-ItemsAdder#996]
**Is your feature request related to a problem? Please describe.**
This is specific to bundles added in 1.17. Bundles when filled have different textures. This is achieved by filled bundle's model overriding bundle's model with a `filled` predicate like so

```yml
"overrides": [
    { "predicate": { "filled": 0.0000001 }, "model": "item/bundle_filled" }
]
```

I have a plugin, **ColorBundles**, that allows players to dye their bundles, much like wool and shulker boxes. To add compatibility to the plugin, it is much more convenient to have a `filled` predicate available at the item configuration level, analogous to the following:

```yml
"overrides": [
    { "predicate": { "filled": 0.0000001 }, "model": "item/bundle_filled" },
    {
        "predicate": { "custom_model_data": 123 },
        "model": "item/custom_bundle"
    },
    {
        "predicate": { "filled": 0.0000001, "custom_model_data": 123 }, # model data same as unfilled version
        "model": "item/custom_bundle_filled"
    }
]
```

**Describe the solution you'd like**
Since I cannot manually override models with predicates again to render another texture for filled bundles, it is best that ItemsAdder make `filled` predicate available under **resource** configuration section.

_bundle model -> filled -> filled bundle model (same custommodeldata but with additional "filled": 0.0000001 in predicate)_

**Describe alternatives you've considered**

1) ItemsAdder maintaining a unique custom model data on every bundle models, filled or not, and manually update the custom model data on bundle fill/empty in player interact inventory events. Convenient for users, uglier to implement.
2) Users combine the two texture packs manually. Convenient for me, not that user-friendly.

**Comment by LoneDev6** [comment]
Thanks, this will be added in the next update 
https://itemsadder.devs.beer/plugin-usage/adding-content/beginners/creating-a-custom-item/bundle
