### ISSUE TITLE
[BUG] ItemsAdder's ores doesn't spawn in Multiverse-Core's worlds

### ISSUE THREAD

**Issue by Feniksovich** [PluginBugs/Issues-ItemsAdder#999]
**Describe the bug**
Despite the fact that I added the world name in the ItemsAdder `world-populators` configuration, it does not spawn in worlds that were created using Multiverse-Core.

**To Reproduce**
1. Add name of futher world with custom ores to `world-populators`.
2. Restart IA/server.
3. Create new custom world with Multiverse-Core's with `/mv create <name> normal`
4. Try to find custom ores from ItemsAdder.

**Expected behavior**
Ores should spawn.

**Screenshots**
None.

**Info (please complete the following information):**
 - Server version: git-Purpur-1149 (MC: 1.16.5)
 - Client version: 1.16.5

**Special Info**
 - ItemsAdder version: 2.4.2
 - LightAPI Fork version: 3.5.0
 - LoneLibs version: 1.0.13
 - ProtocolLib version: 4.6.0
 - Multiverse-Core version: 4.2.2

**Additional context**
— These ores spawns in the default Minecraft worlds (world, for example).
— The presence of the RealisticWorldGenerator plugin does not affect this issue.

**Comment by LoneDev6** [comment]
Did you try enabling world populator logs in itemsadder config?
It will print coords of generated ores in console.

Also make sure the world is not pregenerated

**Comment by Feniksovich** [comment]
@LoneDev6 
> Did you try enabling world populator logs in itemsadder config?
> It will print coords of generated ores in console.
> 
> Also make sure the world is not pregenerated

I turned on logging as you said and tested again.
There are logs for the standard world "world", but not for the MvC world.

**Comment by LoneDev6** [comment]
I sincerely have no idea, I tested the plugin using Multiverse and worked fine.
There is something interfering with ores spawning and it's hard to tell.

If you want you can try to create a local simple server with only itemsadder and multiverse, then check if ores spawn this time.
Have a nice day
